### ISSUE TITLE
Order of CSS injection

### ISSUE THREAD

**Issue by geelen** [styled-components/styled-components#1]
Just hit a problem:

```js
const SVG = styled.svg`
  line {
    stroke-width: 1px;
  }
`

const Horizontal = styled.g`
  line {
    shape-rendering:crispEdges;
  }
`

const Vertical = styled.g`
  line {
    stroke-width: 1.5px;
  }
`

export default () => (
  <SVG>
    <Horizontal>
      <line x1={0} y1={0} x2={width} y2={0}/>
    </Horizontal>
    <Vertical>
      <line x1={0} y1={0} x2={width} y2={height}/>
    </Vertical>
  </SVG>
)
```

Because `Horizontal` and `Vertical` get rendered before `SVG`, and I'm only injecting the styles on render, `._compile_from_Vertical line {}` appears _before_ `._compiled_from_SVG line {}`. They have the same specificity of course and so `SVG` wins.

Injected source should be in the same order it is written, not in the order it's rendered.

**Comment by geelen** [comment]
The above demo works now because of #29 but this one doesn't:

```jsimport React from 'react'
import styled from 'styled-components'

const Outer = styled.div`
  padding: 1rem;
  p {
    color: red;
  }
`

const Inner = styled.div`
  p {
    color: blue;
  }
`

const AlternateInner = styled(Inner)`
  p {
    color: green;
  }
`

export default () => (
  <div>
    {/* This causes AlternateInner to be rendered, then Inner */}
    <AlternateInner/>
    {/* Then outer gets rendered, overwriting both of them */}
    <Outer>
      <p>This should be red</p>
      <Inner>
        <p>This should be blue</p>
      </Inner>
      <AlternateInner>
        <p>This should be green</p>
      </AlternateInner>
    </Outer>
  </div>
)
```

![image](https://cloud.githubusercontent.com/assets/23264/18820708/4998a34e-83e3-11e6-9ff0-8717b01a6d41.png)

If you drop the initial `<AlternateInner/>` it works:

```js
export default () => (
  <div>
    <Outer>
      <p>This should be red</p>
      <Inner>
        <p>This should be blue</p>
      </Inner>
      <AlternateInner>
        <p>This should be green</p>
      </AlternateInner>
    </Outer>
  </div>
)
```

![image](https://cloud.githubusercontent.com/assets/23264/18820735/75c433b6-83e3-11e6-95ea-489b544e46ba.png)

This is... going to be a pain to fix.

**Comment by geelen** [comment]
Simpler example not using descendant tag selectors since those are going to hurt no matter what: 

```js
const Outer = styled.div`
  padding: 1rem;
  color: red;
`

const Inner = styled.div`
  color: blue;
`

const AlternateInner = styled(Inner)`
  color: green;
`

export default () => (
  <div>
    <AlternateInner/>
    <Outer>
      This should be red
      <Inner>
        This should be blue
      </Inner>
      <AlternateInner>
        This should be green
      </AlternateInner>
    </Outer>
  </div>
)
```

![image](https://cloud.githubusercontent.com/assets/23264/18820783/cebafedc-83e3-11e6-9c34-79799f2631b0.png)

Again, commenting out `<AlternateInner/>` makes it work.

**Comment by geelen** [comment]
Ah, I think `componentDidUpdate` will fire in the right order. So maybe we have to defer injection of the CSS until that point.

**Comment by mxstbr** [comment]
> So maybe we have to defer injection of the CSS until [`componentDidUpdate`]

Hmm, sounds like that might introduce flashes of unstyled content?

**Comment by geelen** [comment]
I just implemented it, it doesn't seem to. I think we're good.

**Comment by geelen** [comment]
The idea being that if you called `styled(X)` then `X`s styles are injected before your own. That's the same guarantee `composes` gives you in CSS Modules.

**Comment by mxstbr** [comment]
Wouldn't that break in this case?

```JS
const Comp = styled.something`
styles: here;
`;

const SomeOtherComp = styled(Comp)`
styles: overridden;
`;

// …

<SomeOtherComp>
  <SomeComp />
</SomeOtherComp>
```

**Comment by geelen** [comment]
Nope, that should be fine.

**Comment by geelen** [comment]
Interesting, by fixing the more complex case we break the original case :/

Test cases:

```js
const SVG = styled.svg`
  line {
    stroke-width: 4px;
  }
`

const Vertical = styled.g`
  line {
    stroke-width: 1px;
  }
`

export default () => (
  <SVG>
    <line x1={10} y1={10} x2={90} y2={10}/>
    <Vertical>
      <line x1={10} y1={10} x2={90} y2={90}/>
    </Vertical>
  </SVG>
)
```
```js
const Outer = styled.div`
  padding: 1rem;
  color: red;
`

const Inner = styled.p`
  color: blue;
`

const AlternateInner = styled(Inner)`
  color: green;
`

export default () => (
  <div>
    <AlternateInner/>
    <Outer>
      This should be red
      <Inner>
        This should be blue
      </Inner>
      <AlternateInner>
        This should be green
      </AlternateInner>
    </Outer>
  </div>
)
```

If we inject the CSS during `componentWillReceiveProps` we get CSS injected as Components get rendered:

![image](https://cloud.githubusercontent.com/assets/23264/18822375/8475ba88-83f2-11e6-92ad-1bfd44011454.png)

If we wait until `componentDidUpdate` we get:

![image](https://cloud.githubusercontent.com/assets/23264/18822391/a19603b6-83f2-11e6-9fda-0b03a6ae23d8.png)

So... I think we need to actually go off the _source order_ of the `style.tagName` calls then inject the CSS _into that spot_. Having a separate `style` tag for each one would work, but 😱😱😱

**Comment by geelen** [comment]
Mind you, the only reason that SVG example breaks is because there are two descendant tag selectors (which is not good practice), so I'm going to ship the version that works for `const AlternateInner = styled(Inner)` (i.e. `componentDidUpdate`).

I did just confirm that if the styles have the right specificity then the picture is right for both examples:

![image](https://cloud.githubusercontent.com/assets/23264/18822648/7cb97304-83f5-11e6-9dbf-2c89fb14b360.png)

I did that by repeating the class selectors N times where N is the order of their definition. But we can't do that in production, so we have to insert rules out-of-order. Glamor can't do that at the moment, and I'm a bit worried about the pef implications (one rule injected at the top could invalidate A LOT of styles). But if I can figure out some other approach I will.

**Comment by geelen** [comment]
Woo, found a manual escape hatch:

```js
const Vertical = styled.g`
  && line {
    stroke-width: 1px;
  }
`
```

This generates `.xxx.xxx line` which lifts its specificity above `.yyy line` (from `SVG` above), so tbh I think this is "good enough" to consider this option closed.

In fact you can actually use `&& { some: thing; }` to target the element itself (not just descendants). In case you have some greedy rules outside (like `html p`) which would override a `styled.p` with a single class name. This is great, since we don't have to design good JS to cover bad CSS, we can just give folks a way to generate even worse CSS 👍

**Comment by mxstbr** [comment]
`&&` ≈≈ `aphrodite/important` – I like it!

**Comment by geelen** [comment]
So this didn't stay solved for long. I found that server-side rendering wasn't firing the `componentDidMount`, so we can't use that to inject.

**Comment by Robbiesmo** [comment]
https://gist.github.com/Robbiesmo.com
