### ISSUE TITLE
Different class name on client and server (SSR)

### ISSUE THREAD

**Issue by rustam-gaifiev** [styled-components/styled-components#1000]
After server side rendering I got following error:

> Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
>  (client) <div class="sc-dnqmqq fySkez" data-
>  (server) <div class="sc-kGXeez kzFDmm" data-

it is not very convenient because  it can be cover real problem. 

I have very simple code:

```
const AppWrapper = styled.div
  height: 100%;
  width: 100%;
  overflow: hidden;
;

class App extends React.Component {

  render() {
    return (
      <AppWrapper>
      </AppWrapper>
    );
  }
}

```

**Comment by philpl** [comment]
It's quite a common issue when the code on the client ends up being loaded in a different order than the one on the server.

Our babel plugin has an ssr option to generate unique and matching component ids during transpilation time.

https://github.com/styled-components/babel-plugin-styled-components
