### ISSUE TITLE
Docs: "Getting started" doesn't show you how to get started

### ISSUE THREAD

**Issue by callumlocke** [styled-components/styled-components#1009]
The [getting started](https://www.styled-components.com/docs/basics#getting-started) section is really just a light overview of the syntax. It doesn't actually show you how to import the module or other crucial stuff for getting started.

**Comment by mxstbr** [comment]
PRs welcome! (also let's move this to the [website repo](https://github.com/styled-components/styled-components/website)?)

**Comment by philpl** [comment]
I've opened an issue regarding this already: https://github.com/styled-components/styled-components-website/issues/60

So maybe you're open to contribute to it there? :)
