### ISSUE TITLE
Is there a way to add / remove !important globally to each value?

### ISSUE THREAD

**Issue by anselmh** [styled-components/styled-components#101]
I have a project here which already uses a custom emulation of scoped styles (in a way how styled-components and CSSModules et al work — by randomizing class names). However, I really like the way styled-components is doing the implementation and I’m considering switching over.

To ensure my styles are as scoped as possible, I’m adding `!important` to each value in my styles at the moment. It would be far better though if a tool like styled-components would do that for me automatically for all of my values in the codebase.

Is there any way to enable this as an option perhaps? It would be really useful for a better approximation to native scoped styles.

## Version
1.0.6

## Reproduction
http://www.webpackbin.com/416pMDaR-

**Comment by mxstbr** [comment]
We, in general, opted against configuration for the sake of making third-party ui libraries easier to make and use. (if you have global configuration, users have to be aware of that which gets annoying quickly, see #39)

That being said, this _might_ be possible similar to how we do emoji classnames over at https://github.com/styled-components/styled-components-experimentation. Every internal file we have exports a singleton, which means you can compose together parts of styled-components however you need. (be aware that I'm not sure what you're trying to do is possible that way, and that it becomes your responsibility to maintain your custom instance)

**Comment by anselmh** [comment]
Thanks, I’ll try to use an "extension" for it as you suggested. I totally understand your decision to not make s-c configurable. :)

**Comment by mxstbr** [comment]
> Thanks, I’ll try to use an "extension" for it as you suggested. 

Let me know if you can make it work, and if not, which files you'd need access to!
