### ISSUE TITLE
Nested Styled components with React Native

### ISSUE THREAD

**Issue by shivrajkumar** [styled-components/styled-components#1012]
Is there a way to style child component depending on parent component's prop in react-native.
Say i have Styled Button and a Styled Text. Now if the Button has a prop `primary`, i want to set some background color to Button and also change the color of Text. Its possible in react. But is it possible in react-native. If not any work around?

**Comment by philpl** [comment]
No, there's no way to directly do it, since there's no concept of selectors in React Native.

I'd abstract it into a structural component that passes the same props to multiple components and restructure the container to use it instead :wink:
