### ISSUE TITLE
style-components looks wired in React devtools.

### ISSUE THREAD

**Issue by SidKwok** [styled-components/styled-components#1013]
## Version
2.1.0

## Reproduction

It's not really a bug but it does confuse me a little.

￼
![2017-07-20 18 45 02](https://user-images.githubusercontent.com/13268747/28413811-8621b3c8-6d7b-11e7-8828-89f726a4646d.png)

## Expected Behavior

I expected it to be actual component name like 'Wrapper' or 'Button'.

How can I achieve that? or it just can't?

**Comment by philpl** [comment]
You can use the babel-plugin's displayName option to add more meaningful names.
