### ISSUE TITLE
React Native: start and end properties are not supported

### ISSUE THREAD

**Issue by iddan** [styled-components/styled-components#1014]
## Version
2.1.1

## Reproduction
```JavaScript
import styled from 'styled-components/native';

const StyledView = styled.View`
    border-start-width: 1px;
`;
```

## Expected Behavior
https://facebook.github.io/yoga/docs/rtl/

## Actual Behavior
<img width="376" alt="screen shot 2017-07-20 at 15 58 45" src="https://user-images.githubusercontent.com/12671072/28418433-5af41c20-6d64-11e7-84ae-501372002581.png">

**Comment by philpl** [comment]
Should it actually work? There's no mention of it in the docs https://facebook.github.io/react-native/releases/0.30/docs/layout-props.html

And it's not a standard css property either.

What are you trying to do? Did you mean to use border-top-width and bottom?

**Comment by iddan** [comment]
https://facebook.github.io/react-native/releases/next/docs/layout-props.html links to https://facebook.github.io/yoga/docs/rtl/

**Comment by iddan** [comment]
I try to use border-left-width but in the RTL supporting syntax of border-start-width

**Comment by philpl** [comment]
cc @jacobp100

**Comment by jacobp100** [comment]
This is on the RN side - it's saying it doesn't support `borderStartWidth`. It's worth trying these things with `StyleSheet.create` before if you're unsure what to expect!
