### ISSUE TITLE
Style Object Creation in React Native

### ISSUE THREAD

**Issue by MrLoh** [styled-components/styled-components#1015]
First of all, I love styled components, so thank you guys a lot!!!

I have a question about react-native styles. Can I somehow generate a style sheet like object for react native with styled components. Many React Native components take several style objects, e.g. ScrollView (which takes an additional contentContainerStyle) or react navigation components (which take several styles in their factory methods), it would be nice to define those styles with styled components as well, including the use of theme variables. I would have expected the `css` function to do something like that on native, but that doesn't seem to be the case.

**Comment by philpl** [comment]
The only way to do this right now is to use the `attrs` method:

```js
styled.ScrollView.attrs({
  contentContainerStyle: {
    // object style styling
  }
})`
  // normal css-like styling
`
```

**Comment by MrLoh** [comment]
@philpl how does that address the issue? It just co locates both styles right, but doesn't help at all to write the contentContainerStyle with styled components, which is what I'm looking for. 

@mxstbr why did you close this? 

Shouldn't styled components implement a comprehensive styling solution for React native. Otherwise it seems to just add a bunch of overhead, needing to learn two ways of styling. Or am I missing something.

**Comment by philpl** [comment]
@MrLoh you're completely right in that it breaks with our normal approach to styling which allows you to write normal CSS.

The problem is that there's almost no sensible pattern in this case that works for everyone without hugely complicating things.

We were looking into using the css helper for this case, but it made things a lot more complicated. We might look into it again however

**Comment by scf4** [comment]
@philpl any progress?

**Comment by philpl** [comment]
@scf4 As stated before, there's no plans to pick this up again as of now.

cc @geelen

**Comment by MaxInMoon** [comment]
New syntax: `.attrs(props => ({}))` instead of `.attrs({})`:

```js
const ScrollViewStyled = styled.ScrollView.attrs((props) => ({
  contentContainerStyle: {
    flexGrow: 1,
    backgroundColor: props.theme.light,
    padding: 20,
  },
}))`
  flex: 1;
`;
```

**Comment by MrLoh** [comment]
I built a tiny lib for convenience a while back. https://github.com/MrLoh/styled-css

**Comment by wood1986** [comment]
v5 still does not support this natively

```
const SectionList = styled.SectionList.attrs((props: SectionListProps) => ({
  contentContainerStyle: css`
    "width": ${props.width}px;
    "margin": "auto";
    "padding-vertical": ${props.gripGap}px;
  `
}))``;
```

Any update?

**Comment by RobertWHurst** [comment]
@kitten If I make a sensible PR to add this would it be considered?
