### ISSUE TITLE
refs are attached to the styled components wrapper

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components#102]
## Version

All of them

## Reproduction

http://www.webpackbin.com/NJKccFpC-

## Steps to reproduce

Attach a ref to a styled component

## Expected Behavior

The ref is attached to the DOM node rendered, e.g. in the case of a `styled.input` the `<input>`

## Actual Behavior

The ref is attached to the styled-components wrapper, making it impossible to e.g. focus a `styled.input` programmatically.

**Comment by mxstbr** [comment]
Turns out, React doesn't support "forwarding" refs. The core team wants to add support for that, but it's not high priority so it'll be a while.

I think the way we need to work around this is have a special prop maybe called `innerRef` that attaches to the inner component:

```JS
const StyledInput = styled.input`
  some: styles;
`;

<StyledInput innerRef={comp => this.input = comp} />

// this.input.focus() works 🎉
```

Something to be aware of is that this won't work with string refs, only with callback refs, since react cannot guess which component to attach the ref to. That's something we'll need to mention in the docs.

Thoughts?

**Comment by evan-scott-zocdoc** [comment]
Could this information be surfaced on the main README instead of buried in the "tips & tricks" section?

**Comment by AshCoolman** [comment]
@mxstbr bumping for https://reactjs.org/docs/forwarding-refs.html

**Comment by kitten** [comment]
@AshCoolman we have new issues for that and it’s unrelated to the solution that was introduced for this: the innerRef prop
