### ISSUE TITLE
TypeScript support for primitives

### ISSUE THREAD

**Issue by AlexLeung** [styled-components/styled-components#1025]
I'm currently getting the following error when trying to use the new experimental `styled-components/primitives` submodule in my typescript project:
```
node_modules/styled-components/primitives/index.d.ts(1,34): error TS7016: Could not find a declaration file for module 'react-primitives'.
```
I'm not sure if this is an error that needs to be addressed by the `react-primitives` team, or if it would make sense for the `styled-components` team to push their own fix.

**Comment by philpl** [comment]
As you already opened an issue for this, it should be unnecessary to pursue this here any further: https://github.com/lelandrichardson/react-primitives/issues/82

cc @styled-components/typers
