### ISSUE TITLE
Add alias for react-native ImageBackground component

### ISSUE THREAD

**Issue by wachunei** [styled-components/styled-components#1027]
Nested components inside `Image` will be deprecated and developers should use `ImageBackground` instead, which is currently not supported as an alias.

As a workaround I'm using styled function (without alias)
```jsx
const Container = styled(ImageBackground)`
  border-radius: ${props => props.theme.thumbnailSize / 2};
`;
```

**Comment by k15a** [comment]
Would you mind opening a PR?

**Comment by wachunei** [comment]
Sure! Working on it…

**Comment by wachunei** [comment]
@k15a done —» #1028 😺
