### ISSUE TITLE
onClick not invoked if `onMouseDown` is present and updates state

### ISSUE THREAD

**Issue by alansouzati** [styled-components/styled-components#1029]
Let me start by saying that this is a very weird bug. I tried investigating your source code and I could not find anything that would possible lead to this.

It also happens if `ouMouseUp`, `onMouseOver` are provided.

## Version
2.1.1

This bug happens with or without the babel plugin.

## Reproduction

https://codesandbox.io/s/mZz51wGPG

## Steps to reproduce

Just add a onMouseDown and onClick together where the onMouseDown update the react state.

```javascript
const TestDiv = styled.div``;
 <TestDiv onMouseDown={() => this.setState({ hi: true })} onClick={() => alert('hi')}>click me, it does not work</TestDiv>
```
## Expected Behavior

onClick is called

## Actual Behavior

onClick is not called

**Comment by probablyup** [comment]
Is setState returning false somehow and aborting the cascade?

**Comment by alansouzati** [comment]
Not from the caller's perspective. You can check the code sandbox I'm not aborting the cascade.

**Comment by philpl** [comment]
To clarify, this is unlikely to be a bug with SC :wink: But let's keep investigating

**Comment by alansouzati** [comment]
Yeah I agree that is unlikely to be a bug in SC. But how do we explain the fact that the last example in the code sandbox works just by switching from SC to a regular react div?

**Comment by philpl** [comment]
@alansouzati You were creating the styled component dynamically on every render. Thus it unmounts and the event is aborted / not captured. https://codesandbox.io/s/v2MzwvyKM

Please consult our docs for guides, intros, and usage of styled-components :wink: https://www.styled-components.com/docs

**Comment by alansouzati** [comment]
nicely done. thanks for the quick follow up.

**Comment by alansouzati** [comment]
FYI. In my case I was doing stuff like this:

```javascript
import StyledButton from './StyledButton';

const Button = ({ href, ...rest }) => {
  let Tag = StyledButton;
  if (href) {
     Tag = StyledButton.withComponent('a');
  }
  return (
    <Tag {...rest} href={href} />
  );
};
```

Based on your finds and the documentation, I replaced it to be something like this (which makes totally sense):

```javascript
import StyledButton from './StyledButton';

const AnchorStyledButton = StyledButton.withComponent('a');

const Button = ({ href, ...rest }) => {
  const Tag = href ? AnchorStyledButton : StyledButton;
  return (
    <Tag {...rest} href={href} />
  );
};
```

I'm sharing here just in case hits a similar problem 👍
