### ISSUE TITLE
www.styled-components.com does not render in IE and is very flaky in Edge. Is this true for apps that use styled-components?

### ISSUE THREAD

**Issue by dgennetten** [styled-components/styled-components#1030]
## Version
2.1.0

## Reproduction

https://www.webpackbin.com/bins/-KeeZCr0xKfutOfOujxN
https://codesandbox.io/s/rkmNRByE4

**Comment by philpl** [comment]
First of all, this is not the website's repo. Please open an issue there.

This is not a styled-components issue. We made sure that it supports the same versions of browsers as React.

I haven't tested the site in IE or Edge so it's probably another Web API. I also can't tell you what went wrong without some debugging output or sth similar.

Also, the issue template is totally not fitting the issue, and please don't put your entire subject in the title. I'm reading every single issue every day. I'd just like to take a minute to tell you, that no matter whether you put in 5 seconds or 5 hours to write an issue, someone will have to read it. And that takes time out of the things that they could be doing instead. So please write GH issues like you'd expect to receive them yourself :wink:
