### ISSUE TITLE
Add .extend and .withComponent deterministic ID generation

### ISSUE THREAD

**Issue by philpl** [styled-components/styled-components#1031]
For server-side rendering it is often crucial to generate deterministic and stable IDs during transpilation time, so that the import-order of modules—and thus the order in which StyledComponents are instantiated—doesn't influence the `componentId`. A failure to do so leads to a checksum mismatch between the SSR result and React on the client side.

To generate these IDs we have the `ssr` option in our babel-plugin: https://github.com/styled-components/babel-plugin-styled-components

> By adding a unique identifier to every styled component this plugin avoids checksum mismatches due to different class generation on the client and on the server. [...]

But due to the way it works, it adds `withConfig` to any call that creates a new Styled Component. This is tough to implement correctly as of now, and the way we communicate the component ids in the transpiled code will change completely in styled-components v3, when we introduce stable preprocessing.

So what we can do now is add some dynamic `componentId` generation to the runtime instead.

https://github.com/styled-components/styled-components/blob/master/src/models/StyledComponent.js#L219

In `extend` on this line, instead of filtering out `componentId`, we'll want to append a hash of the new CSS to it. This can probably just use `ComponentStyle.generateName` together with all the concatenated string templates, which is a "unique-enough" source (as a temporary heuristic here).

https://github.com/styled-components/styled-components/blob/master/src/models/StyledComponent.js#L211

In `withComponent` we can just concatenate the tag string ([or the `displayName` if it's a component](https://github.com/styled-components/styled-components/blob/master/src/models/StyledComponent.js#L177)).

Apart from the sources of the suffix, the implementation will mostly look like this:

```js
const newComponentId = `${componentId}-${extraId}`
```

**Comment by kakadiadarpan** [comment]
@philpl I'm taking this up.

**Comment by neoziro** [comment]
@kakadiadarpan still on it? I will try too.
