### ISSUE TITLE
Uncaught TypeError: ns.charCodeAt is not a function

### ISSUE THREAD

**Issue by andy1028** [styled-components/styled-components#1033]
environment：
  "next": "latest",
"styled-components": "^2.1.1",

below is my demo code

```js
// index.js
import React from 'react';
import styled from 'styled-components';

const Title = styled.h1`
  font-size: 1.5em;
  text-align: center;
  color: #ddd;
  `;
export default () => (
  <div>
    <Title>it is just an demo</Title>
  </div>
  );
```

```js
   // _document.js
import Document, { Head, Main, NextScript } from 'next/document';
import { ServerStyleSheet } from 'styled-components';
import flush from 'styled-jsx/server';

export default class MyDocument extends Document {
  static getInitialProps({ renderPage }) {
    const { html, head, errorHtml, chunks } = renderPage();
    const styles = flush();
    return { html, head, errorHtml, chunks, styles };
  }

  render() {
    const sheet = new ServerStyleSheet();
    const main = sheet.collectStyles(<Main />);
    const styleTags = sheet.getStyleElement();
    return (
      <html lang="zh">
        <Head>
          <style>{'body { margin: 0 } /* custom! */'}</style>
          {/* inject:js */}
          <script src="../static/demo.js" />
          {/* endinject */}
          {styleTags}
        </Head>
        <body className="custom_class">
          <div>root</div>
          <div className="root">
            {main}
          </div>
          <NextScript />
        </body>
      </html>
    );
  }
}

```

browser throw TypeError

![image](https://user-images.githubusercontent.com/13925688/28604101-08ab06cc-71fb-11e7-9bde-49f1a80003a1.png)

but the `Title` component is work still

**Comment by andy1028** [comment]
i try switch version to 2.1.0 of `styled-components`, there is no above issues.

but version of `2.1.1` work well out of next.js.

im not sure this issues is in next.js or styled-components

**Comment by philpl** [comment]
It seems like there's a mismatch between your styled-components and stylis version, I'd say. Have you tried removing your node_modules and installing again?

**Comment by andy1028** [comment]
i try removing node_modules many times

**Comment by stheobald** [comment]
Confirming this issue - I removed node_modules and .next. Manually installed stylis@3.2.8, and have verified that this error is present with styled-components@2.1.1, but NOT in styled-components@2.1.0

**Comment by philpl** [comment]
@stheobald @andy1028 I'm certain it's an installation issue. What version of npm or yarn are you using? And what's the output of `npm ls stylis` or `yarn list stylis`?

**Comment by stheobald** [comment]
yarn list stylis
yarn list v0.27.5
├─ next@2.4.9
│  └─ stylis@3.1.5
└─ stylis@3.2.8

Note that I have a babel-plugin.js as per https://github.com/zeit/next.js/tree/v3-beta/examples/with-styled-jsx-postcss  (only not postcss) to pick up the correct stylis version

npm --version
5.0.3

yarn --version
0.27.5

**Comment by philpl** [comment]
@stheobald A couple of things I can see here :)

- styled-components is not listed
- next should only passively depend on stylis via styled-jsx
- styled-jsx-postcss should depend on styled-jsx as well which depends on stylis in turn
- stylis@3.2.8 is installed globally which should work

Sone background: styled-components updated to a new version of stylis that added the constructor API to separate configuration between multiple consumers. It seems that an old version of stylis is being used with SC.

So what you can try is:

- Try removing styled-jsx-postcss
- Try upgrading styled-jsx to 1.0.10 (it might be that stylis is being wrongfully deduped)
- Try reinstalling all packages from scratch (remove node_modules **and** yarn.lock) and send the `npm ls stylis` again

**Comment by stheobald** [comment]
@philpl - perhaps it's less ambiguous if I just share a reproducing repo :-D (I'm not using postcss)

https://github.com/stheobald/next-nested-grid   
Using next@latest, styled-components@latest and styled-jsx@latest WITH a babel patch entry for styled-jsx

In this project, the error doesn't visibly break any styling (mostly because there's not much there). In my full project, the error causes layout mayhem.

I'm not sure what to make of the "invalid" outputs:

npm ls stylis
with-styled-components@1.0.0 /home/n/Experiments/with-styled-components
├─┬ babel-plugin-styled-components@1.1.7
│ └── stylis@3.2.8  deduped
├─┬ styled-components@2.1.2 invalid
│ └── stylis@3.2.8
└─┬ styled-jsx@1.0.10 invalid
  └── stylis@3.2.8  deduped

yarn list stylis
yarn list v0.27.5
├─ next@2.4.9
│  └─ stylis@3.1.5
└─ stylis@3.2.8
Done in 1.03s.

next@latest has a dependency on styled-jsx@1.0.6, which explains the stylis@3.1.5 there, but in practice our .babelrc will be overriding that, and using styled-jsx@latest with stylis@3.2.8 I believe.

**Comment by philpl** [comment]
@Thysultan any ideas? seems fine to me

**Comment by thysultan** [comment]
Yes, it works fine on my end. Looks like a cache issue on your end, though i'm not sure why it would be using the next@2.4.9 version – stylis@3.1.5 that does not support the `new Stylis()` API that s-c@latest moved to.

**Comment by protoEvangelion** [comment]
Simply using yarn instead of npm fixed it for me!

**Comment by philpl** [comment]
I'll close this due to its age and inactivity

Thanks @protoEvangelion for resurfacing it :smile:
