### ISSUE TITLE
Component theme independence?

### ISSUE THREAD

**Issue by albertovilva** [styled-components/styled-components#1034]
First of all thanks for this amazing resource! 

Im all about component extraction in my projects and I have come to a doubt regarding the use of styled components.

What would be the best way to go about making components theme agnostic? For example, let's say I make a bunch of components which are rigged to my theme heavily, but I want them to be used completely isolated from my enviroment as standalone components. For example in React Storybook.

One way is setting a theme each time you want to use that component. Which I feel like its not the best way. And the other obvious option I see is managing everything with conditionals.

```javascript
const NavbarStyled = styled(Navbar) `
  a{
    color:${props => props.theme.colors ? props.theme.colors.red : 'red'};
  }
`
```

Still not sure if its the best way. So, any info regarding using styled-components and component extraction is greatly appreciated.

Thanks!

**Comment by geelen** [comment]
Personally, I'd achieve this with a theme helper of some sort. Something like:

```
import { theme } from '../helpers'

const NavbarStyled = styled(Navbar) `
  a{
    color:${ theme(['colors','red'], 'red', null) };
  }
`
```

...or whatever API you choose. If your target audience can support [proxies](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy), you can do some really crazy stuff: https://www.webpackbin.com/bins/-KkTyZXtM2tpHBc0xJNL

**Comment by mxstbr** [comment]
Why not just use `defaultProps`?

```JS
const NavbarStyled = styled(Navbar) `
  a{
    color:${props => props.theme.colors ? props.theme.colors.red : 'red'};
  }
`

NavbarStyled.defaultProps = {
  theme: {
    colors: {
      red: 'crimson',
    },
  },
};
```

This could then maybe even be extracted into it's own utility:

```JS
NavbarStyled.defaultProps = setDefaultColors({
  red: 'crimson',
});
```
