### ISSUE TITLE
Ability to override a component's tagName per-instance

### ISSUE THREAD

**Issue by callumlocke** [styled-components/styled-components#1035]
styled-components already lets you use an existing component as the basis for a new component (``styled(Foo)`/* override styles... */`;``), but it is not possible to override the **tag name** of the original component, AFAICT. Sometimes I want to do this when I want to use a more semantic tag in one particular place.

### Example

I'm currently using styled-components to make some 'grid' primitives like this:

```jsx
<Container>
  <Row>
    <Column span="8">foo</Column>
    <Column span="4">bar</Column>
  </Row>
</Container>
```

All three of the above components are made with ``styled.div`/* ...styles... */`;``

But sometimes I want them to be semantic elements like `nav` instead of `div`, and it would be convenient if I could use them like this (notice the `tagName` attribute):

```jsx
<Container>
  <Row>
    <Column tagName="main" span="8">foo</Column>
    <Column tagName="aside" span="4">bar</Column>
  </Row>
</Container>
```

At the moment I'm generating a unique `Column` class on the fly for each unique tagName, but it's a lot of boilerplate that I have to repeat for any component I want to do this on, and it would be cool if styled-components could do this for me.

**Comment by callumlocke** [comment]
Just realised you can do it like this:

```jsx
const AsideColumn = Column.withComponent('aside');

<AsideColumn span="8">foo</AsideColumn>
```

[Extending styles docs](https://www.styled-components.com/docs/basics#extending-styles)

**Comment by mxstbr** [comment]
Also you can do a slightly more magic-ey approach to create a whitelist of supported tags for that component by attaching them as properties:

```js
const Column = styled.div``
Column.section = Column.withComponent('section');

<Column /> // Renders a div
<Column.section /> // Renders a section
```

**Comment by leotm** [comment]
For anyone else who finding their way here, just wanted to point out in the docs:
_.withComponent was marked as a candidate for future deprecation._
Better to use: https://www.styled-components.com/docs/api#as-polymorphic-prop
