### ISSUE TITLE
Proposition of builtin CSS transition handlers with react-transition-group

### ISSUE THREAD

**Issue by ezsper** [styled-components/styled-components#1036]
Most of the time transitions are hard and messy to perform and maintain, Styled Components bring us a very easy API to handle styling. I was thinking of an idea to add transition helpers to the API levered by [react-transition-group](https://reactcommunity.org/react-transition-group/) and make it even better.

```
import styled from 'styled-components-transition-group';

// transition() wraps TransitionGroup
const List = styled.div.transition() ``;

// animated() wraps CSSTransition
const ListItem = styled.div.animated() `
  transition: opacity 300ms cubic-bezier(0.4, 0.0, 0.2, 1) 0ms;

  &:appear, &:enter, &:exit {
    opacity: 0;
  }
  &:appear-active, &:enter-active {
    opacity: 1;
  }
`;
```

Access my [example repository](https://github.com/ezsper/styled-components-transition-group) and launch storybook for a working demo of this proposition.
![storybook](https://user-images.githubusercontent.com/798804/28619716-1e739c46-71e0-11e7-97b7-cfab48a1339b.gif)

**Comment by geelen** [comment]
Cool idea! My suggestion would be to have the API called `animated` and have it _generate_ styled components, rather than injecting it into the existing API:

```js
import { transition, animated } from 'styled-components-transition-group'

const List = transition.div``;

const ListItem = animated.div`
  transition: opacity 300ms cubic-bezier(0.4, 0.0, 0.2, 1) 0ms;

  &:appear, &:enter, &:exit {
    opacity: 0;
  }
  &:appear-active, &:enter-active {
    opacity: 1;
  }
`;
```

That way you could publish it as a separate package and get people playing with it. If we need to make some internal changes to SC to better facilitate packages like this, I'm open to that.

**Comment by wtgtybhertgeghgtwtg** [comment]
> But it would be nicer if styled-components attach some sort of extending methods for styled and css. So something like bellow come to place.

Why?  You already use injection in `styled-components-transition-group`, why not stick to that?
```
import originalStyled from 'styled-components';
import injectSomething from 'styled-components-something';

const styled = injectSomething(originalStyled);
```
It gets messy if you're injecting multiple things
```
import originalStyled from 'styled-components';
import injectSomething from 'styled-components-something';
import injectOr from 'styled-components-or';
import injectOther from 'styled-components-other;

const styled = injectSomething(injectOr(injectOther(originalStyled)));
```
but it's not particularly cleaner than a plugin system would be.
```
import {createStyled} from 'styled-components';
import something from 'styled-components-something';
import or from 'styled-components-or';
import other from 'styled-components-other;

const styled = createStyled({something, or, other});
```

**Comment by duro** [comment]
@ezsper I would love to make use of this, and I think it's a great idea to make it a separate package that does not require bundling into styled-components to get out the door.

**Comment by mxstbr** [comment]
We're not going to add any configuration to styled-components, see #1143. This would be great as an external package!

**Comment by gabiseabra** [comment]
If anyone's still interested, I made [styled-transition-group](https://github.com/gabiseabra/styled-transition-group), which exports a new styled object as geelen proposed.

**Comment by granmoe** [comment]
I appreciate the conciseness of the proposed APIs of [styled-transition-group](https://github.com/gabiseabra/styled-transition-group) and [styled-components-transition-group](https://github.com/ezsper/styled-components-transition-group), but couldn't this easily be accomplished by just creating a little component that takes styles (as strings or maybe as styled-components.css templates) for the entering/entered/exiting/exited states, and a few other options, and a styled component, and returns a react-transition-group/Transition and just applies the styles to the styled component as the state changes? Something like:

```javascript
// in some component's render method
const animationStyleProps = {
  entering,
  exiting,
  transition,
  duration
}

return <Animate status={this.state.show} {...animationStyleProps} component={SomeStyledComponent} />
```

I like the creativity, but it seems like there's a high cost in terms hackiness (reaching into styled-components internals, for example) to get the sole benefit of concise syntax. Plus, we'd have to create editor extensions (or create a PRs for existing extensions) for CSS syntax highlighting within these new "transition" styled components. Am I missing part of the picture here?

**Comment by corysimmons** [comment]
@ezsper @gabiseabra Thank you! This is beautiful and makes animations a joy to work with.

**Comment by granmoe** [comment]
I'm throwing my hat in the ring. I've used a slightly different, more minimal approach: https://github.com/granmoe/styled-animate

**Comment by corysimmons** [comment]
Gonna try to get one of these working with https://github.com/cheapsteak/react-transition-group-plus (Sarah Drasner mentioned this pairs well with GSAP which is exciting), and react-router for cancelable/reversable page transitions 🤤. Will post boilerplate if I get it.

**Comment by sonaye** [comment]
I looked into a couple of implementations here and ended up abstracting what I was looking for to so something much simpler (doesn't require `styled-components` and powered by `react-transition-group`).

```javascript
// animates a child
<Animated>
  <Foo />
</Animated>

// animates a group of children
<Animated items>
  {foos.map(() => <Animated item><Foo /></Animated>)}
</Animated>

// it comes with some presets out of the box (fade, scale, etc ..)
// to use a custom transition preset

// foo.css
.foo-appear,
.foo-enter {
  opacity: 0;
}

.foo-appear-active,
.foo-enter-active {
  opacity: 1;
  transition: opacity 400ms ease-in;
}

.foo-exit {
  opacity: 1;
}

.foo-exit-active {
  opacity: 0;
  transition: opacity 400ms ease-out;
}

// ..

import './foo.css'; // once

<Animated preset="foo">
  <Bar />
</Animated>
```

[Demo](https://4ron7o8157.codesandbox.io/) & [package](https://github.com/sonaye/react-animated-transitions), thanks for inspiring this work.

**Comment by sonaye** [comment]
I tried to make it play nice with `styled-components` for a minute, I found it to be tricky since the generated class names are not fixed. Also not sure if the css is attached to each component or if it's optimized.

Let's say that we have:

```javascript
const Foo = styled.p`color: red;`;
const Bar = styled.p`color: red;`;
```

@geelen Will `styled-components` generate a single css class that is attached to both components? since the css is identical here.

**Comment by corysimmons** [comment]
@sonaye That's actually really awesome. Will definitely start using that (I'm back on SCSS now).

**Comment by sonaye** [comment]
@corysimmons I actually didn't know that you can do that, nice. This addresses something I was looking for in this library a while ago (composition of styled-components https://github.com/styled-components/styled-components/issues/932). I've been stubborn about writing css in string templates, but I finally gave it a shot and I kind of like it now, I am gradually moving to use `styled-components` exclusively.

`react-transition-group` doesn't require a fixed class name, it requires another prop called `classNames` that takes values that help mapping the total transition.

I was able to integrate the package with `animate.css`, adding animations in React is truly a breeze now.

**Comment by granmoe** [comment]
@yss14 Thanks! 😄 

I would very much welcome PRs for it if you find that there's anything missing or if anything can be improved--I'm working on a deep learning project in most of my off time currently.

**Comment by aperkaz** [comment]
Great tip @sonaye ! I applied you tip, and working with animations is so much easier now :slightly_smiling_face: 
If someone is curious, I pieces together an example of `react-transition-group` and `animate.css` at: https://codesandbox.io/s/csstransition-react-n1t10?file=/index.js

Happy codding! :rocket:
