### ISSUE TITLE
Style an already styled component, accessing child styled components

### ISSUE THREAD

**Issue by dsaisho** [styled-components/styled-components#1037]
Is it possible to add styles to a child of a styled component, with that child already being a styled component? For Example, Thumbnail is a component with Icon and Image:

```
export const StyledThumbContainer = styled.div`
width:200px
`
export const StyledIcon = styled.div`
color:red
`

export const Thumbnail =>
<StyledThumbContainer>
    <StyledIcon/>
</StyledThumbContainer>

```

Now, I want to use this thumbnail in an image gallery but with different styles on the StyledThumbContainer and StyledIcon. I tried a few things and they all failed, for example:
```
//import the above for try 1 and 2
import Thumbnail from "components/thumbnail"

//import for try 3
import Thumbnail, {StyledThumbContainer} from "components/thumbnail"

//try 1
export const StyledThumbnail = styled(Thumbnail)`
width:50px;
`
//try2
export const StyledThumbnail = styled(Thumbnail)`
div{width:50px;}
`
//try3
export const StyledThumbnail = styled(Thumbnail)`
${StyledThumbContainer}{width:50px;}
`
export const ImageGallery =>
<ImageGallery>
<StyledThumbnail>
<...image gallery stuff>
</ImageGallery>
```

What is the best way to handle this situation? Thanks!

## Version
2.1.0

## Reproduction

https://www.webpackbin.com/bins/-KeeZCr0xKfutOfOujxN
https://codesandbox.io/s/rkmNRByE4

**Comment by epilande** [comment]
Hey @dsaisho how about passing props to the `Thumbnail` component and changing the styles based on the props?

For example: 
```javascript
const StyledThumbContainer = styled.div`${props => css`
  width: 200px;

  ${props.size === 'small' && `
    width: 50px;
  `}
`}`;

const Thumbnail = (props) => (
  <StyledThumbContainer size={props.size}>
    <StyledIcon/>
  </StyledThumbContainer>
);

<Thumbnail size="small" />
```

**Comment by geelen** [comment]
Yep @epilande's suggestion is a good one. In general you should try to make your components _describe what about themselves can change_. Here, you're saying there are two variants, small or not. In your example above you're relying on multiple classnames to do the same job.

That said, if you change your Thumbnail to be:

```js
export const Thumbnail = ({ className }) =>
<StyledThumbContainer className={className}>
    <StyledIcon/>
</StyledThumbContainer>
```

Then your `//try 1` code will work.

**Comment by dsaisho** [comment]
Hey all, I appreciate the suggestions! I wanted to pass props initially however that was poor architecture for how we build our app. I am very noob at this and the answer which I just found out was simply adding className={className} to the child component :)
