### ISSUE TITLE
Failed to Pass TypeScript Enum Type Prop into Styled Components

### ISSUE THREAD

**Issue by li-xinyang** [styled-components/styled-components#1038]
## Version
2.1.0

## Reproduction

When I try to pass a enum value to a Styled Component like below,

    <Style.Indicator type={TransactionType.Income} />

I got the following error message,

    ERROR in [at-loader] ./src/components/base/transaction-indicator/TransactionIndicator.tsx:94:13
        TS2322: Type '{ type: TransactionType.Income; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ThemedOuterStyledProps<HTMLProps<HTMLSpa...'.
      Type '{ type: TransactionType.Income; }' is not assignable to type 'Readonly<ThemedOuterStyledProps<HTMLProps<HTMLSpanElement> & { type: TransactionType | undefined;...'.
        Types of property 'type' are incompatible.
          Type 'TransactionType.Income' is not assignable to type '(undefined & TransactionType.Expense) | (undefined & TransactionType.Income) | (undefined & Trans...'.

When I remove the `prop` typing inside `Style.Indicator` which shows the following error (I think it is expecting a stying type props),

    ERROR in [at-loader] ./src/components/base/transaction-indicator/TransactionIndicator.tsx:94:13
        TS2322: Type '{ type: TransactionType.Income; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ThemedOuterStyledProps<HTMLProps<HTMLSpa...'.
      Type '{ type: TransactionType.Income; }' is not assignable to type 'Readonly<ThemedOuterStyledProps<HTMLProps<HTMLSpanElement>, any>>'.
        Types of property 'type' are incompatible.
          Type 'TransactionType.Income' is not assignable to type 'string | undefined'.

Below is the declaration of `Style.Indicator` and `TransactionType`,

    export const Indicator = styled.span`
      border-radius: 50%;
      box-sizing: border-box;
      display: inline-block;
      height: 15px;
      width: 15px;
      position: relative;
      top: 2px;
      margin-left: 5px;
    
      ${(props: { type: TransactionType|undefined }) =>
        props.type === TransactionType.Expense ? ColorExpense : ''};
      ${(props: { type: TransactionType|undefined }) =>
        props.type === TransactionType.Income ? ColorIncome : ''};
      ${(props: { type: TransactionType|undefined }) =>
        props.type === TransactionType.Transfer ? ColorTransfer : ''};
    `;

    export enum TransactionType {
      Expense,
      Income,
      Transfer
    }

**Comment by philpl** [comment]
cc @styled-components/typers

**Comment by patrick91** [comment]
Have you tried to make it a String enum?

**Comment by Igorbek** [comment]
Do not use `type` as a prop name because React already uses it for in intrinsic attributes as defined in `HTMLAttributes` as `type?: string`. That effectively makes your `type` be of type `(string | undefined) & (TransactionType | undefined)`

**Comment by Igorbek** [comment]
Can we close as it's been resolved?
