### ISSUE TITLE
Add an option to include the component's displayName in the generated class names

### ISSUE THREAD

**Issue by sylvain-hamel** [styled-components/styled-components#1039]
Hi this is feature request for an option to include the component's displayName in the generated class names, something like `MyComponent_u2jd38`. 

Without this, it is very hard identify where styling issues comes from when using Dev Tools to investigate. After a few weeks using `styled-components` in my team, this issue has been raised by several people.  We transitioned from `css-modules` where we had this feature and now we miss it a lot.

FYI: We would probably enable this option for `development` builds only.

**Comment by epilande** [comment]
@sylvain-hamel styled-components has a [babel plugin](https://github.com/styled-components/babel-plugin-styled-components) that does this and makes debugging 👌 

https://www.styled-components.com/docs/advanced#better-debugging

**Comment by TazmanianD** [comment]
@epilande I don't suppose there's another alternative for this? We're using the TypeScript form of Create React App and it doesn't use babel.

**Comment by TazmanianD** [comment]
Can we reopen this and consider this a feature request for styled-components?

**Comment by mxstbr** [comment]
Unfortunately, due to the way JavaScript works this is impossible without a build-step. Example:

```JS
const Button = someFn();

const Wrapper = someFn();

const someFn = () => {
  // I cannot know what I'm called in here :(
}
```

**Comment by VictorChen** [comment]
For people using create react app, is there any way to solve this without ejecting?

**Comment by olivierbeaulieu** [comment]
For those using create react app, you can solve this without ejecting by using babel macros.

Simply `import 'styled-components/macro'` instead of the usual `styled-components`. You don't need to install anything special. The downside is that you will need to import this everywhere.

Example:
```js
import styled from 'styled-components/macro';

const MyStyledComponent = styled.``; // When used, this component will have a nice readable className like "MyStyledComponent_fa09we8".
```

**Comment by shmdhussain** [comment]
> For those using create react app, you can solve this without ejecting by using babel macros.
> 
> Simply import `styled-components/macro` instead of the usual `styled-components`. You don't need to install anything special. The downside is that you will need to import this everywhere.
> 
> Example:
> 
> ```js
> import styled from 'styled-components/macro';
> 
> const MyStyledComponent = styled`
>   color: pink;
> `;
> ```
> 
> When used, this component will have a nice readable className like `MyStyledComponent_fa09we8`.

`import styled from 'styled-components/macro';` here from styled-components version 6.1, this macro has been removed from the styled-components. ref: https://styled-components.com/docs/tooling#babel-macro
