### ISSUE TITLE
Minimizing the server side rendering CSS output

### ISSUE THREAD

**Issue by selbekk** [styled-components/styled-components#1042]
I'm playing with `styled-components` for the first time, and have to say I'm very impressed. Great job guys!

I'm trying out your server side rendering features, and I'm noticing that the output from `ServerStyleSheet.prototype.getStyleTags`  is commented and not minified. Is there a particular reason why not? It's probably mostly OCD, but in my mission to shave the last bytes off my payloads, this would be a micro-improvement I would love to see.

I'd love to help out with a PR (haven't seen the code base yet), but I'd first like to ask why things are they way they are.

**Comment by philpl** [comment]
Apart from the `ssr` option which is crucial for correct SSR with varying import order, our babel-plugin also includes a `minify` option :wink:

https://www.styled-components.com/docs/advanced#minification
