### ISSUE TITLE
@supports returning true for backdrop-filter when it shouldn't

### ISSUE THREAD

**Issue by unindented** [styled-components/styled-components#1045]
## Version
2.1.1

## Reproduction

Pure CSS no repro: https://codepen.io/unindented/pen/NvGoRX
Styled Components repro: https://codepen.io/unindented/pen/EvVryz

## Steps to reproduce
Open both links in latest stable Chrome (which doesn't support backdrop-filter). With pure CSS, background will be red indicating lack of support. With Styled Components, background will be green even though there's no support.

## Expected Behavior

With Styled Components, background should also be red.

## Actual Behavior

With Styled Components, background is green.

**Comment by thysultan** [comment]
I don't think css supports flat css rules in at-supports and nesting at-supports, so the codepens don't testing the same behavior.

```css
h1 {
    @supports (){
        // css does not support this
    }
}

@supports (){
    body {
        // css supports this
    }
}

```

**Comment by philpl** [comment]
Yep, the other way around it should work. Inline declarations in at-rules (see our media query examples) should be allowed though if I'm not mistaken :D

**Comment by unindented** [comment]
@thysultan @philpl sorry, I didn't follow. You're saying this should work? Cause it doesn't...

```js

const Overlay = styled.div`
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  background-color: rgba(255, 0, 0, 0.5);

  @supports (backdrop-filter: blur(10px)) or (--webkit-backdrop-filter: blur(10px)) {
    & {
      background-color: rgba(0, 255, 0, 0.5);
      backdrop-filter: blur(10px);
    }
  }
`;
```

**Comment by unindented** [comment]
Neither does this:

```js

const Overlay = styled.div`
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  background-color: rgba(255, 0, 0, 0.5);

  @supports (backdrop-filter: blur(10px)) or (--webkit-backdrop-filter: blur(10px)) {
    background-color: rgba(0, 255, 0, 0.5);
    backdrop-filter: blur(10px);
  }
`;
```

**Comment by thysultan** [comment]
@unindented The Pure CSS version uses invalid CSS since Pure CSS does not support SASS-like nesting, with this patched fork [https://codepen.io/thysultan/full/PKNpZV](https://codepen.io/thysultan/full/PKNpZV) they are both green on my version of Chrome.

**Comment by unindented** [comment]
@thysultan Right, but it **shouldn't** be green, cause Chrome doesn't support `backdrop-filter`, only Safari does. That was my original complaint.

**Comment by thysultan** [comment]
@unindented I think it's because Chrome and Firefox support `--webkit-backdrop-filter`, if you remove the `or (--webkit-backdrop-filter:   blur(10px))` part, it reverts to red.

**Comment by mxstbr** [comment]
Or just add `--webkit-backdrop-filter` to your rules!

```JS
const Overlay = styled.div`
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  background-color: rgba(255, 0, 0, 0.5);

  @supports (backdrop-filter: blur(10px)) or (--webkit-backdrop-filter: blur(10px)) {
    background-color: rgba(0, 255, 0, 0.5);
    backdrop-filter: blur(10px);
    --webkit-backdrop-filter: blur(10px);
  }
`;
```

**Comment by unindented** [comment]
@mxstbr aah, I thought styled-components was doing `autoprefixer` magic for me, so that I didn't have to add prefixes manually.

**Comment by mxstbr** [comment]
Hmm yeah actually, it should. That looks like a bug @thysultan?

**Comment by thysultan** [comment]
Yes, it does autoprefix it with `-webkit-backdrop-filter`.
