### ISSUE TITLE
Direct class referencing

### ISSUE THREAD

**Issue by zero-t4** [styled-components/styled-components#1047]
Hi, how can i dirrectly reference to the class, which is not child of my component.
like this 
```
const Div = styled.div`
  display: inline-block;
  &:hover {
    border: 1px solid red;
  }
 // HERE im referencing to the outer  BODY tag
  body {
  font-size: 20px;
  }
`;
```

## Version
2.1.0

## Reproduction

https://www.webpackbin.com/bins/-KeeZCr0xKfutOfOujxN
https://codesandbox.io/s/rkmNRByE4

**Comment by k15a** [comment]
You can do this with injectGlobal:

```js
const Div = styled.div`
  display: inline-block;
  &:hover {
    border: 1px solid red;
  }
`;

injectGlobal`
 // HERE im referencing to the outer  BODY tag
  body {
  font-size: 20px;
  }
`
```

It's good practice to do this only once per Project for example in you App.js or where your Root component lives.

**Comment by zero-t4** [comment]
Wow, big thanks , it was really helpful
