### ISSUE TITLE
Component not updating css on property update

### ISSUE THREAD

**Issue by hanselsen** [styled-components/styled-components#1050]
I'm relatively new to React and styled-components and I'm bumping into this issue.
When my styled-component is re-rendered, it should refresh the CSS, but the property is changed and the CSS is not.

Here  is my component:

```
StyledMap = styled(Map)`
    cursor: ${props => { 
        console.log(props.isCreatingMarker);
        return props.isCreatingMarker ? 'crosshair' : 'pointer'}
    }};
`;
```

    
On refresh, I see 'true' in my log and the cursor is a crosshair. Super! But when I click my trigger, the log shows false, and the cursor is still the crosshair.

Can somebody provide some insight for me?

**Comment by philpl** [comment]
Can you supply some reproductions? It's probably a usage issue, so with a webpackbin/codesandbox we can check what's going on :smile:

There's some instructions and links in the issue template, if you're unsure what to submit :wink:

**Comment by mxstbr** [comment]
Can you try wiggling your cursor after clicking? I think the browser just might not re-render the cursor on-click.

**Comment by hanselsen** [comment]
I fixed this by using an overlay which becomes visible when props.isCreatingMarker is true and vice versa.
Could not fix the original issue, but this is very acceptable as well.

**Comment by demidborodin** [comment]
Probably, i have the same problem...

```javascript
import React, { Component } from "react";
import ReactDOM from "react-dom";
import styled from "styled-components";

class ModalPortal extends Component {
  render = () => <div className={this.props.overlayClassName} />;
}

class Modal extends Component {
  componentDidMount() {
    document.body.appendChild(this.node);
  }

  componentWillUnmount() {
    document.body.removeChild(this.node);
  }

  getOverlayClassName = `${this.props.className}__overlay`;

  render() {
    if (!this.node) {
      this.node = document.createElement("div");
      this.node.className = this.props.className;
    }

    return ReactDOM.createPortal(
      <ModalPortal {...this.props} overlayClassName={this.getOverlayClassName} />,
      this.node
    );
  }
}

export const StyledModal = styled(Modal)`
  display: ${props => {
    // THIS IS NOT WORK, WHEN I TOGGLE IS OPEN FROM PARENT COMPONENT
    return props.isOpen ? "block" : "none";
  }};

  &__overlay {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: rgba(255, 255, 255, 0.75);
  }

  &__content {
    position: absolute;
    top: 40px;
    left: 40px;
    right: 40px;
    bottom: 40px;
    border: 1px solid #ccc;
    background: #fff;
    overflow: auto;
    -webkit-overflow-scrolling: touch;
    border-radius: 4px;
    outline: none;
    padding: 20px;
  }
`;
```
Somebody can help with this, for several days already, I'm puzzling how to make flexible modal windows :|
