### ISSUE TITLE
Reversing the relationship in theming

### ISSUE THREAD

**Issue by thejameskyle** [styled-components/styled-components#1055]
Heyo,

Right now the recommended pattern across styled-components and [theming](https://github.com/iamstarkov/theming) (including the packages that consume it like [emotion](https://github.com/tkh44/emotion)) is to pass specific styles down from the root of your app:

```js
const Button = styled.button`
  color: ${props => props.theme.main};
`;

const theme = {
  main: 'mediumseagreen',
};

<ThemeProvider theme={theme}>
  <Button>Themed</Button>
</ThemeProvider>
```

This works for certain types of problems. But when you're writing a full theme for your app, you're touching hundreds or even thousands of styles. Structuring it this way becomes painful.

You quickly start having this separate set of styles that lives at the top of your app that is separate from your components:

```js
const themeLight = {
  buttonDefaultColor: "#123456",
  buttonDefaultHoverColor: "#123456",
  buttonDefaultActiveColor: "#123456",
  buttonDefaultFocusColor: "#123456",
  buttonPrimaryColor: "#123456",
  buttonPrimaryHoverColor: "#123456",
  buttonPrimaryActiveColor: "#123456",
  buttonPrimaryFocusColor: "#123456",
  // ...
};

const themeDark = {
  buttonDefaultColor: "#123456",
  buttonDefaultHoverColor: "#123456",
  buttonDefaultActiveColor: "#123456",
  // ...
};
```

And your components start filling up with lookup functions and lose their scan-ability.

```js
const Button = styled.button`
  color: ${props => props.theme.buttonDefaultColor};
  background-color: ${props => props.theme.buttonDefaultBackgroundColor};
  border-color: ${props => props.theme.buttonDefaultBorderColor};

  &:hover {
    color: ${props => props.theme.buttonDefaultHoverColor};
    background-color: ${props => props.theme.buttonDefaultHoverBackgroundColor};
    border-color: ${props => props.theme.buttonDefaultHoverBorderColor};
  }

  &:active {
    color: ${props => props.theme.buttonDefaultActiveColor};
    background-color: ${props => props.theme.buttonDefaultActiveBackgroundColor};
    border-color: ${props => props.theme.buttonDefaultActiveBorderColor};
  }

  &:focus {
    color: ${props => props.theme.buttonDefaultFocusColor};
    background-color: ${props => props.theme.buttonDefaultFocusBackgroundColor};
    border-color: ${props => props.theme.buttonDefaultFocusBorderColor};
  }
`;
```

Then you start getting into component variants where you are depending on other properties and every one of these functions gets more complicated:

```js
const Button = styled.button`
  color: ${props => {
    if (props.kind === "default") return props.theme.buttonDefaultColor;
    if (props.kind === "primary") return props.theme.buttonPrimaryColor;
    if (props.kind === "success") return props.theme.buttonSuccessColor;
    if (props.kind === "warning") return props.theme.buttonWarningColor;
    if (props.kind === "danger") return props.theme.buttonDangerColor;
  }};
  // ...
`;
```

I've seen people try to abstract all of this work and accidentally introduce performance problems. (When you're making calculations for thousands of styles across hundreds of components on every render cycle, it's hard not to have a performance problem)

It also is tough to try and abstract the giant object of styles at the root of your app. Trying to abstract a design system from the code side is a bit of a recipe for disaster long term.

# Reversing the relationship

Colocation is a huge feature of CSS-in-JS, it leads to a whole lot of wins (which anyone using css-in-js already knows so I won't get into it here). The problems I've described with theming are because we've given up the colocation of styles and put them in two places.

If we made a couple minor changes to our theming apis, and started documenting/teaching it differently we could set developers up for success.

Let me give an example:

Instead of passing specific styles from the root of the app. We could instead pass down descriptors like:

```js
<ThemeProvider theme={{ mode: "dark" }}>
```

Then from the component side it initially looks like this:

```js
const buttonColor = {
  default: { light: "#123456", dark: "#123456" },
  primary: { light: "#123456", dark: "#123456" },
  success: { light: "#123456", dark: "#123456" },
  warning: { light: "#123456", dark: "#123456" },
  danger: { light: "#123456", dark: "#123456" },   
};

const Button = styled.button`
  color: ${props => buttonColor[props.kind][props.theme]};
  // ...
`;
```

Writing it out like this colocates your themes with your styles with your component, and we're back to the awesome workflow of CSS-in-JS.

## API Design

I've designed a tiny little API to encourage this pattern called [styled-theming](https://github.com/thejameskyle/styled-theming). It basically just abstracts this:

```js
const fontSize = {
  small: '1em',
  large: '1.2em',
};

const buttonColor = {
  default: { light: "#123456", dark: "#123456" },
  // ...
};

const Button = styled.button`
  font-size: ${props => fontSize[props.theme.size]};
  color: ${props => buttonColor[props.kind][props.theme.mode]};
  // ...
`;
```

Into this:

```js
const fontSize = theme('size', {
  small: '1em',
  large: '1.2em',
});

const buttonColor = theme.variants('mode', 'kind', {
  default: { light: "#123456", dark: "#123456" },
  // ...
});

const Button = styled.button`
  font-size: ${fontSize};
  color: ${buttonColor};
  // ...
`;
```

We've started using this API on a project and it has simplified a _lot_ of work being done.

---

# Encouraging this pattern

We should, as a community, encourage developers to work in a way that sets them up for success. We can do this via api design, documentation, teaching, etc.

I would like to see tools include a very lightweight api for encouraging this pattern, it could be the one I created with styled-theming, but also does not have to be.

Further, I would like to see tools like styled-components to start documenting theming this way. I'm happy to write up new docs for the styled-components site and the [theming](https://github.com/iamstarkov/theming) library. But wanted to put this issue out there first.

Thanks for reading

cc @iamstarkov

**Comment by mxstbr** [comment]
I like it!

Related: https://github.com/styled-components/styled-components/pull/113

**Comment by nelix** [comment]
This is pretty good if your app has some themes, but its less useful if you wish to provide a way for consumers of your library a way to provide their own theme.

**Comment by thejameskyle** [comment]
@nelix The changes I suggested above don't remove any functionality like that. But I would argue that relying on users to theme third-party components from the top of their app is already a bad API for it.

If you do this:

```js
const thirdPartyComponentStyles = {
  target1: { backgroundColor: 'red' },
  target2: { backgroundColor: 'blue' },
};

function App() {
  return (
    <ThemeProvider theme={{ thirdPartyComponent: thirdPartyComponentStyles }}>
      <Page/>
    </ThemeProvider>
  );
}

// page.js
function Page() {
  return <ThirdPartyComponent/>;
}
```

You are now tied into that one theme for the third-party component throughout your app, you don't have the option to use it in different ways visually.

Instead you immediately need to move the ThemeProvider down into a wrapper component.

```js
import ThirdPartyComponent from 'third-party-component-lib';

const styles = {
  target1: { backgroundColor: 'red' },
  target2: { backgroundColor: 'blue' },
};

export default function WrapperComponent(props) {
  return (
    <ThemeProvider={{ thirdPartyComponent: styles }}>
      <ThirdPartyComponent styles={styles} {...props}/>
    </ThemeProvider>
  );
}
```

We should be encouraging users to always wrap their components this way because it colocates styles and avoids the need for future abstraction.

But at that point you might as well just accept the theme as a prop:

```js
function WrapperComponent(props) {
  return <ThirdPartyComponent styles={styles} {...props}/>;
}
```

This allows your users to consume your third-party component before they've even installed styled-components.

Then if you are using styled-components internally, your users can immediately use the above theming API:

```js
const target1BackgroundColor = theme('mode', {
  light: 'red',
  dark: 'darkred',
});

const target2BackgroundColor = theme('mode', {
  light: 'blue',
  dark: 'darkblue',
});

const styles = {
  target1: { backgroundColor: target1BackgroundColor },
  target2: { backgroundColor: target2BackgroundColor },
};

export default function WrappedComponent(props) {
  return <ThirdPartyComponent styles={styles} {...props}/>
}
```

You could build additional APIs to make this more convenient inside of the third party component library.

**Comment by philpl** [comment]
@mxstbr I think this is really valuable advice for styled-components at scale. Do you think we should expand the docs' theming section and add this approach?

**Comment by mxstbr** [comment]
Yep, I think that makes a lot of sense.

**Comment by thejameskyle** [comment]
@mxstbr do you want to migrate the API of styled-theming into styled-components or move the styled-theming repo into the styled-components org?

**Comment by vladimir-kondratenko** [comment]
Why not just resolve this problem like below?
```javascript
const Button = styled.button`
  color: ${props => props.theme.buttonDefaultColor};
  background-color: ${props => props.theme.buttonDefaultBackgroundColor};
  border-color: ${props => props.theme.buttonDefaultBorderColor};
`;

const ButtonPrimary = styled(Button)`
  color: ${props => props.theme.buttonPrimaryColor};
  background-color: ${props => props.theme.buttonPrimaryBackgroundColor};
  border-color: ${props => props.theme.buttonPrimaryBorderColor};
`;
```
or
```javascript
const Button = styled.button`
  color: ${props => props.theme.buttonDefaultColor};
  background-color: ${props => props.theme.buttonDefaultBackgroundColor};
  border-color: ${props => props.theme.buttonDefaultBorderColor};
  &.primary {
    color: ${props => props.theme.buttonPrimaryColor};
    background-color: ${props => props.theme.buttonPrimaryBackgroundColor};
    border-color: ${props => props.theme.buttonPrimaryBorderColor};
  }
`;
```

**Comment by probablyup** [comment]
This only works if you don’t expect to change the base styles. At Zocdoc,
we are building white labelled sites now that customize the entire page
style via extending a base theming blob.

So we have the complexity you spoke of, plus having to freely swap out the
underlying values of the base theme. Breaking up the styles and dispersing
them becomes impossible to maintain.

**Comment by geelen** [comment]
This is excellent work. I've always considered both the props and theming APIs as kind of a minimum viable approach that anyone can build their own interfaces on top of, once we had a bit more real-world usage.

> @mxstbr do you also want to migrate the API of styled-theming into styled-components or move the styled-theming repo into the styled-components org?

I would prefer to keep it as a separate package, but under the organisation, and fully integrated into the documentation. That way, SC itself keeps the low level API (if your interpolation returns a function, we'll call it) and, for anyone who looks closely, it's clear how you can build up your own designs from it.

My only question is similar to @nelix's—it's not clear to me how I might provide a custom theme. In fact, it feels like more of a way to generate _variations_ of a component rather than _theme_ them. (I guess that's kinda the issue title now I think about it). I think, if the API could be extended somehow to allow outside-in theming it might be enough to cover all use-cases.

Perhaps that can be done by treating `'mode'` as special (or some other word). Then, you could set a top-level theme variable that `mode="custom"` or something, which then caused each component to look outside of its immediate definitions to something somewhere else that's also provided by the inherited theme. In the case of a complete theming override, I think it's fair to assume that the consumer will have gone into the source of the component and looked at its internal structure, so you could pass an object that has the exact same structure as `fontSize` and `buttonColor`, there just needs to be a way to wire it up.

If nothing else, though, I really like the way this approach makes it easier for components to not hard-code so much of their CSS. I think the easier that is, the more people will use it, and the more shareable and reusable everyone's components will be by default.

**Comment by thejameskyle** [comment]
This API does not get rid of the ability to pass down CSS values:

```js
<ThemeProvider theme={{ mode: 'dark', userProfileAccentColor: 'purple' }}/>
```

```js
const componentColor = theme('mode', {
  default: { light: "#123456", dark: "#123456" },
  // ...
});

const Component = styled.div`
  color: ${componentColor};
  border-left-color: ${props => props.theme.userProfileAccentColor};
`;
```

Passing down just the information you need and doing everything else at the component level is a lot easier to manage.

**Comment by thejameskyle** [comment]
Also, I'll transfer the repo if no one has any objections

**Comment by geelen** [comment]
> This API does not get rid of the ability to pass down CSS values:

Of course, but that's only because it doesn't change the basic functionality. By making it easier to pass down keys into your styling data structures you guide people away from passing down values at all. It would be way better if, when you take a component and give it two variants using a _mode_, you also got the ability to overwrite it from outside.

Personally, I don't like passing down values. I think the syntax you're onto here with theme objects that select values based off some metadata (_size_, _mode_, _kind_) is actually really clever, but if all the data for the "themes" has to be hard-coded when the component is written, you're still shipping a walled-off component the same as if you'd hard-coded the styles.

What about something a bit more like:

```js
import theme from '../utils'

theme.defineSimple('fontSize', 'size', {
  small: '1em',
  large: '1.2em'
})

theme.defineVariants('buttonColor', ['mode', 'kind'], {
  default: { light: "#123456", dark: "#123456" },
  // ...
})

const Button = styled.button`
  font-size: ${theme.fontSize};
  color: ${theme.buttonColor};
  // ...
`;
```

Then, you could define some override object like this:

```js
const overrides = {
  fontSize: { large: '1.5em'; },
  buttonColor: { default: { dark: 'black' } },
}

<ThemeProvider theme={ size: 'small', mode: 'default', 'sc-overrides': overrides }>
  //...
</ThemeProvider>
```

If we could narrow down on an API that helps both component authors and consumers with unpredictable requirements, this could be really awesome.

**Comment by thejameskyle** [comment]
One of the things I really like about what `<ThemeProvider/>` already provides is the simplicity of an arbitrary object I can pass down.

It's very recognizable in React when compared to `props`. It doesn't require any additional learning.

Explaining `theme()` and `theme.variants()` is made easy by the fact that it's just writing a simple function for you with no additional conventions or work happening behind the scenes.

I think we should leverage the fact that `theme={}` is Just An Object and not try to enforce any additional conventions.

Otherwise who knows what other cool `theme()` or `theme.variants()` like functions people will come up with. I think just setting up the idea of pulling theme information down into the component-level will cause people to build interesting things they hadn't thought about previously.

**Comment by geelen** [comment]
I get that point, having `theme` as a normal object is good and shouldn't be removed lightly. But the `theme` function you're suggesting has an implementation like this (for a simple case):

```js
const theme = (propName, definitions) => (
  props => definitions[props.theme[propName]]
)
```

I'm suggesting you allow a fallback along the lines of this:

```js
const theme = (propName, definitions) => (
  props => (props.theme.overrides || definitions)[props.theme[propName] || 'default']
)
```

I get that it makes the function more complex but it also is a really useful seam where you can add some dynamic customisation for free. Or, at least as close to free as possible.

**Comment by geelen** [comment]
An alternate API:

```js
export const componentColor = theme('mode', {
  default: { light: "#123456", dark: "#123456" },
  // ...
});

const Component = styled.div`
  color: ${componentColor};
`;
export default Component;
```

```js
import { componentColor } from './Component'

// Good ol' mutable data structures
componentColor.definitions.default.dark = 'black'

// Alternatively, a mutation API
componentColor.injectVariant({
  mode: {
    default: {
      dark: 'black'
    }
  }
})
```

This is worse (mutating singletons) but sometimes worse is better 😄

**Comment by mxstbr** [comment]
Yeah please transfer the repo, would love to add the docs to the website as well!

**Comment by FabioAntunes** [comment]
I'm a bit confused how does this solves the problem: 

```
const fontSize = theme('size', {
  small: '1em',
  large: '1.2em',
});

const buttonColor = theme.variants('mode', 'kind', {
  default: { light: "#123456", dark: "#123456" },
  // ...
});

const Button = styled.button`
  font-size: ${fontSize};
  color: ${buttonColor};
  // ...
`;
```

You would still have computations, but instead on relying on the theme you are relying custom functions?

What happens if me as a user of the theme want to change one of the default colours to something else? Let's say I want my primary color to have the value `#133777` how can I easily override that value across my entire application?

**Comment by thejameskyle** [comment]
You can still pass values down if you need to, but you should default to co-locating your theme styles with your components.

**Comment by FabioAntunes** [comment]
But isn't that the same as using the default `props.theme`?  I'm just trying to understand how would this works in terms of providing a framework on top of styled components and allowing the users to be able to customise it.

This seems to work fine if you hardcode the styles and just have a couple of options to choose from, but if you want to have something like Bootstrap sass variables, were everything is customised I don't see how can this solve the problem.

I'm sorry if I'm missing something

**Comment by thejameskyle** [comment]
Having implemented UI frameworks that way I think it's just the wrong way to work with CSS-in-JS and components.

The best way to do it is to have your users wrap your UI framework components with their own components that pass in their theming directly. 

```js
import * as React from 'react';
import {Button} from 'ui-framework';

export default function CompanyButton(props) {
  return <Button {...props} theme={{ ... }}/>;
}
```

Then use that everywhere instead.

```diff
- import {Button} from 'ui-framework';
+ import {Button} from './company-ui/Button';
```

Supplying the company theme through context is extremely limiting in that you can only have provide one theme per component and all of your styles live at the top of your app which makes them totally unmanageable.

Trying to replicate the design CSS frameworks outside of CSS-in-JS is a poor design choice in my experience.

**Comment by thejameskyle** [comment]
Also this was covered [earlier in the thread](https://github.com/styled-components/styled-components/issues/1055#issuecomment-320443948) so I encourage you to go back and read the entire thread

**Comment by FabioAntunes** [comment]
Allow me to disagree, a theme should supply variables/units to be used across the components, not styles. I think the other way around it's way more unmanageable, you will always need to have some reference on your styles to the base unit you are using, either be it the colour or the font-size. You will need to reference that value across multiple components either importing a variable or using a theme

```
import { ThemeProvider } from 'styled-components';

const theme = {
  fontSize: '1rem',
  blue: 'blue',
  red: 'red',
  get primary() {
    return this.blue;
  },
  get danger() {
    return this.red;
  }
}

const App = () => (
  <ThemeProvider theme={theme}>
  <div>
   ...
  </div>
  </ThemeProvider>
);

export default App;
```

I don't see how this is unmantainable comparing to having this, where you have the colour hardcoded:
```
const fontSize = theme('size', {
  small: '1em',
  large: '1.2em',
});

const buttonColor = theme.variants('mode', 'kind', {
  default: { light: "#123456", dark: "#123456" },
  // ...
});

const Button = styled.button`
  font-size: ${fontSize};
  color: ${buttonColor};
  // ...
`;
```

eventually you will end up doing this:
```diff
+ import { dark, light } from '../../../myGlobalCssVars';
const fontSize = theme('size', {
  small: '1em',
  large: '1.2em',
});

const buttonColor = theme.variants('mode', 'kind', {
-  default: { light: "#123456", dark: "#123456" },
+  default: { light: "${light}", dark: "${dark}" },
  // ...
});

const Button = styled.button`
  font-size: ${fontSize};
  color: ${buttonColor};
  // ...
`;
```

if I want to use a different value for the light color I will need to be passing those values over and over again for every single component.


Although the idea is to build independent components you always need to have some global vars to be shared across your components, like font-size, line-height. You need those things to be consistent across your entire application.

**Comment by a-type** [comment]
I maintain an internal component library for my organization and ran into a lot of problems with how to co-locate themes, allow library consumers to extend component styling or modify theme properties, etc, as discussed here. Came upon this thread and was pretty inspired by the proposals. Like @FabioAntunes , though, I was really dreaming of a solution where I can reference some 'universal' values when defining style configurations for individual components. I also wanted to expose customization powers to library consumers in a very straightforward way.

So today I've been working on this: https://a-type.github.io/styled-library-themer/#introduction

I think it provides a similarly usable API, and hopefully gives library consumers a lot of power to modify the styling of a library without having to understand the internal structure of the components, or even how styled-components works at all.

An example component definition:

```javascript
const select = theme
  .register('anchor', theme => ({
    color: theme.colors.primary,
    fontWeight: 'bold',
  }))
  .addVariant('secondary', theme => ({
    color: theme.colors.secondary,
  }))
  .createSelector();

const Anchor = theme.connect(styled.a`
  color: ${select('color')};
  font-weight: ${select('fontWeight')};
  text-decoration: underline;
  font-family: sans-serif;
`);

Anchor.Secondary = theme.variant('secondary')(Anchor);
```

Just wanted to touch back here to add to the conversation a bit. I'll be looking to integrate this with our internal projects and see how it goes.

**Comment by thejameskyle** [comment]
I just made a change to styled-theming that accepts functions as theme values:

```js
theme('mode', {
  light: props => props.theme.userProfileAccentColor.light,
  dark: props => props.theme.userProfileAccentColor.dark,
});
```

While this shouldn't be your default, it does give you a lot more flexibility. In the future with the optional chaining operator, it can be nice with defaults too:

```js
theme('mode', {
  light: props => props.theme.?userProfileAccentColor.light || 'skyblue',
  dark: props => props.theme.?userProfileAccentColor.dark || 'royalblue',
});
```

If people want to define their own utilities for describing theme values, it's now quite simple:


```js
function provided(themeKey, defaultValue) {
  return props => props.theme[themeKey] || defaultValue;
}

theme('mode', {
  light: provided('appColorLight', 'pink'),
  dark: provided('appColorDark', 'hotpink'),
});
```

**Comment by a-type** [comment]
Nice! I personally feel that it's a key feature. `styled-theming` is definitely more lightweight and targeted than my more framework-like approach. I've yet to do any serious exploration of performance, which can obviously be a big gotcha with this kind of stuff.

**Comment by mxstbr** [comment]
Closing since there's nothing actionable left to do here. Thanks @thejameskyle for the great lib and discussion!
