### ISSUE TITLE
Flow: styled-components/native. Required module not found

### ISSUE THREAD

**Issue by DaniyarJakupov** [styled-components/styled-components#1057]
## Version
styled-components@2.1.1
flow-bin@0.47.0
flow-typed@2.1.5

## Reproduction

Bootstrapped app with create-react-native-app. Installed storybook, styled-components and added flow. Installed definitions:
`flow-typed install styled-components@2.1.1`

Have really simple component:
```
/* @flow */
import React, { Children } from 'react';
import styled from 'styled-components/native';

type Props = {
  onPress: Function,
  children: Children
};

const Wrapper = styled.TouchableOpacity`background-color: steelblue;`;

const Button = ({ onPress, children }: Props) =>
  <Wrapper onPress={onPress}>
    {children}
  </Wrapper>;

export { Button as default };
```

When I run flow, I'm getting this error:

<img width="827" alt="screen shot 2017-08-02 at 15 40 14" src="https://user-images.githubusercontent.com/17025967/28876287-fad2af52-7798-11e7-9e6d-a00ebd0d726c.png">

**Comment by DaniyarJakupov** [comment]
I figured it out. As it is described in docs I did this:

> Ignore styled-components source
You should add the following lines to your .flowconfig, if you run into Flow errors, coming from the styled-components package in your node_modules directory.
`[ignore]
.*/node_modules/styled-components/.*`

But it's not mentioned there that we need to add styled-components under the libs section. Maybe it was obvious, but still I think it should be in the docs explicitly.

**Comment by philpl** [comment]
cc @styled-components/typers

**Comment by relekang** [comment]
> But it's not mentioned there that we need to add styled-components under the libs section. Maybe it was obvious, but still I think it should be in the docs explicitly.

That should not be necessary, can you paste the flowconfig you ended up with?

**Comment by DaniyarJakupov** [comment]
Sure, here it is:
```
[ignore]
; We fork some components by platform
.*/*[.]android.js

; Ignore "BUCK" generated dirs
<PROJECT_ROOT>/\.buckd/

; Ignore unexpected extra "@providesModule"
.*/node_modules/.*/node_modules/fbjs/.*

; Ignore duplicate module providers
; For RN Apps installed via npm, "Libraries" folder is inside
; "node_modules/react-native" but in the source repo it is in the root
.*/Libraries/react-native/React.js
.*/Libraries/react-native/ReactNative.js

; Additional create-react-native-app ignores

; Ignore duplicate module providers
.*/node_modules/fbemitter/lib/*

; Ignore misbehaving dev-dependencies
.*/node_modules/xdl/build/*
.*/node_modules/reqwest/tests/*

; Ignore missing expo-sdk dependencies (temporarily)
; https://github.com/expo/expo/issues/162
.*/node_modules/expo/src/*

; Ignore react-native-fbads dependency of the expo sdk
.*/node_modules/react-native-fbads/*

; Ignore styled-components source
.*/node_modules/styled-components/.*

[include]

[libs]
node_modules/react-native/Libraries/react-native/react-native-interface.js
node_modules/react-native/flow
flow/
styled-components

[options]
module.system=haste

emoji=true

experimental.strict_type_args=true

munge_underscores=true

module.name_mapper='^[./a-zA-Z0-9$_-]+\.\(bmp\|gif\|jpg\|jpeg\|png\|psd\|svg\|webp\|m4v\|mov\|mp4\|mpeg\|mpg\|webm\|aac\|aiff\|caf\|m4a\|mp3\|wav\|html\|pdf\)$' -> 'RelativeImageStub'

suppress_type=$FlowIssue
suppress_type=$FlowFixMe
suppress_type=$FixMe

suppress_comment=\\(.\\|\n\\)*\\$FlowFixMe\\($\\|[^(]\\|(\\(>=0\\.\\(4[0-7]\\|[1-3][0-9]\\|[0-9]\\).[0-9]\\)? *\\(site=[a-z,_]*react_native_oss[a-z,_]*\\)?)\\)
suppress_comment=\\(.\\|\n\\)*\\$FlowIssue\\((\\(>=0\\.\\(4[0-7]\\|[1-3][0-9]\\|[0-9]\\).[0-9]\\)? *\\(site=[a-z,_]*react_native_oss[a-z,_]*\\)?)\\)?:? #[0-9]+
suppress_comment=\\(.\\|\n\\)*\\$FlowFixedInNextDeploy
suppress_comment=\\(.\\|\n\\)*\\$FlowExpectedError

unsafe.enable_getters_and_setters=true

[version]
^0.47.0
```

**Comment by jonasws** [comment]
I have the same problem, running a fresh bootstrap of `create-react-native-app` on Fedora 26. The `.flowconfig` in the previous comment did not cut it for me.

**Comment by IvanCoronado** [comment]
@relekang Same problem here, the project was working fine but after remove node_modules and install it again with yarn. I got the same problem.

`[ignore]
.*/node_modules/styled-components/.*
.*/node_modules/stylelint/.*

[include]

[libs]

[options]

[lints]
`
styled-components@2.1.1
flow-bin@0.50.0
flow-typed@2.1.2

**Comment by philpl** [comment]
As it seems that none of the issues here seem to be issues with our typings, but usage issues, I have to ask you to try to:

- Use the **exact** instructions (including the exact `flowconfig`  without extra sections) in the docs: https://www.styled-components.com/docs/api#flow
- Try the mentioned `lib` trick above
- Open a new issue with a **reproduction repo** adhering to the issue template

As the original poster resolved this and we don't have a reproduction right now, I'd prefer new issues with more detailed descriptions instead of keeping a potentially unrelated issue going. Sorry :smile:
