### ISSUE TITLE
Styling Redux Connected Components Doesn't Apply Class Name

### ISSUE THREAD

**Issue by bhough** [styled-components/styled-components#106]
## Version
1.0.6

## Reproduction
http://www.webpackbin.com/EyrDcW0CZ

## Steps to reproduce
The example above is a bit contrived, but should demonstrate the basics. Whenever you are working with a component that is connected with Redux and want to override any styles on it, those styles get raised but because `styled` is getting passed `connect(Component)` instead of the `Component` itself, the class is never applied to the underlying component. 

## Expected Behavior
Class should be added to the connected component and styling should be added to the head.

## Actual Behavior
Styling is added to the head but the class for those styles is not applied to the component.

**Comment by mxstbr** [comment]
As stated in the documentation, the only thing you need to do to make that work is attach the classname to an actual DOM node. See here: http://www.webpackbin.com/VyippfRRZ

I changed two lines of code to attach the `className` from the props in `HelloWorld`:

```
function HelloWorld(props) {
  return (
    <Text className={props.className}>Provide your bug reproduction in HelloWorld.js!</Text>
  );
}
```

That's everything needed to make it work! 🎉

**Comment by bhough** [comment]
Thanks @mxstbr, sorry we missed this on our end. Glad to know it is a simple fix.
