### ISSUE TITLE
Warn when ignoring

### ISSUE THREAD

**Issue by matt-erhart** [styled-components/styled-components#1062]
I had some color names as strings, e.g. 'green', and I was getting no styles showing up and no errors. I think it would help to have warnings in the console when something is ignored by a styled-component.

**Comment by philpl** [comment]
You mean you had quotes around some values?

Right now it's not possible for us to literally lint your CSS, I'm afraid 😞  You can try our stylelint-processor, or wait for v3 which will actually parse all CSS.
