### ISSUE TITLE
TypeScript props interface is cast to never when theme prop is not given and BaseStyledInterface is used

### ISSUE THREAD

**Issue by philpl** [styled-components/styled-components#1068]
This line (L66) was recently added, and it causes an edge case in a very specific (but common) use case: 

https://github.com/styled-components/styled-components/blob/62ae36eeb6ddf43ec2f1d5b8e0546dd8df47b15d/typings/styled-components.d.ts#L65-L68

Here we set the theme prop to be optional when `P extends { theme?: T; }`. But by default `T` is `any` in the exposed `BaseStyledInterface`.

This causes `WithOptionalTheme` to exhibit the bug. It then casts `P` to `never`. That means that the resulting interface is just: `{ theme?: any }`.

The bug disappears when `T` is not `any`, meaning when `theme` is set to something else.

Here is an image of @JonWallsten's reproduction: http://imgur.com/a/i1GrD

The interface of `ICombinedSpinButton` is:

```ts
export interface ICombinedSpinButton extends IAutoplayButton {
  autoplayActive?: boolean
  autoplayRunning?: boolean
  hidden?: boolean
}
```

(Ignore the extend, it's irrelevant)

Note that the `theme` property is not cast to a type.

cc @Igorbek

**Comment by philpl** [comment]
@Igorbek I just hunted this bug down with @JonWallsten. It's a really specific edge case with the `styled()` factory, but not at all unlikely to be encountered. It is caused by the change you last made in the typings file. Mind having a look? I know how to get rid of it, but not how to properly fix `WithOptionalTheme` :wink:

**Comment by Igorbek** [comment]
Sure, let me take a look.

**Comment by Igorbek** [comment]
Sorry, I couldn't understand what the problem was by given screenshot. Can you please give the full repro code and point what the type expectations you had that were not met.
I tried repro code from #1070 and it did work for me.

@IIIristraM I've used the simplified repro from #1070:

```ts
import * as React from "react";
import styled from "styled-components";

interface IconProps {
    className?: string;
    icon: string;
}

class Icon extends React.PureComponent<IconProps, {}> {
    public render() {
        const { className, icon, ...others } = this.props;

        return <div />;
    }
}

const InputIcon = styled(Icon) ``;
const IconErase = styled(InputIcon) ``;

<IconErase icon="save" />; // works
<IconErase {...{ icon: "save" }} />; // works
```

@IIIristraM you didn't provide `IconProps` interface, please correct me if it differs from in what I showed.

**Comment by philpl** [comment]
@JonWallsten can you please paste some code so we can come up with a minimal reproduction? :)

**Comment by JonWallsten** [comment]
@philpl This should probably do it:
https://www.webpackbin.com/bins/-KqwRNbXrBQ3PDkUF9Hi
Webpackbin however won't show interface related errors. So you would probably have to test it locally. I don't have a simple boilerplate, so it's probably faster you you to test it. Is that okey with you?

**Comment by avindra** [comment]
```tsx
interface Props extends React.SVGProps<SVGElement> {
  isOpen?: boolean;
}

const DumbBox =  ({ isOpen }: Props) => (
  <div width={isOpen ? "50px" : "25px"}>
     Hello World 
  </div>
);

const StyledDumbBox = styled(DumbBox)`
  color: red;
`;
```

This will throw an error in `StyledDumbBox`

Reverting to `2.1.1` fixes the build error.

**Comment by Igorbek** [comment]
Ah, I think I've got what's going on... I'll fix it shortly

**Comment by philpl** [comment]
I'll release a minor version today containing this fix

**Comment by avindra** [comment]
No rush on this since we just pinned our app to the previous version, but when is 2.1.3 due?
