### ISSUE TITLE
Internet Explorer support

### ISSUE THREAD

**Issue by didierfranc** [styled-components/styled-components#107]
<img width="1413" alt="capture d ecran 2016-10-17 a 21 55 19" src="https://cloud.githubusercontent.com/assets/14132464/19453185/753ecfdc-94b4-11e6-8b6c-366ca1df296b.png">

It seems ***styled-component*** doesn't support Internet Explorer 10

👀 https://github.com/styled-components/styled-components/issues/107#issuecomment-254332819

## Version
1.0.5/1.0.6

## Steps to reproduce
Run your app on IE10

## Expected Behavior
Work

## Actual Behavior
Crash

**Comment by mxstbr** [comment]
Thanks for digging in and submitting an issue about this!

While I hate IE as much as the next front-end developer, I understand that sometimes business needs come above technology needs, and that sometimes IE does need to be supported.

It's not super high priority for me to fix this, especially now that we have support for IE11 (see #82), but I'd love if somebody could dig in and add support for lower versions of IE as well!

**Comment by didierfranc** [comment]
I would like to implement ***styled-component***, it will simplify a lot for our applications, unfortunately app from https://github.com/xeonys/ and so Deloitte, needs support for IE10+ 😭

**Comment by mxstbr** [comment]
> unfortunately apps from Xeonys and so Deloitte, needs support for IE10+

That's exactly what I mean!

I (or @geelen) would love to give you some pointers if you want to dig in? It shouldn't be _too_ hard to fix this as far as I understand!

**Comment by didierfranc** [comment]
Yes, it will be great ;)

**Comment by amsb** [comment]
In IE10, the console gives me the error:

> SCRIPT5007: Unable to get property 'appendRule' of undefined or null reference

It looks like `this.insertedRule` is being set to null or undefined in:

https://github.com/styled-components/styled-components/blob/master/src/models/ComponentStyle.js#L25

styleSheet is a global glamour Stylesheet singleton created here:

https://github.com/styled-components/styled-components/blob/master/src/models/StyleSheet.js#L8

which is defined here:

https://github.com/threepointone/glamor/blob/98d4f44ba4335abd0e63bf946edff04ec51d3a41/src/sheet.js#L65

It looks like glamour is being thoughtful about some of the older IE issues (but I'm no expert) so I'm not yet sure why insert is return null at the moment. Is the Stylesheet singleton being created too soon in the document lifecycle on IE10?

**Comment by didierfranc** [comment]
@mxstbr @geelen Here I am → https://github.com/didierfranc/styled-components/commit/f588e2250df4e97a09a19e462d51a6a8c01c7b62

Seems to quick fix the crash of IE10

**Comment by mxstbr** [comment]
@didierfranc well, that is a very hacky fix hah! Let's cc @threepointone, who definitely wants to be aware of this issue.

**Comment by threepointone** [comment]
so this was a combo of 2 things making this fail - 
- all IEs <= 10 support updating a stylesheet via `+cssText`
- the vendored version didn't return the modified `appendRule` object in the above case, only during the `appendChild` case 

now, ie9+ *also* supports using `appendChild`, so @didierfranc's proposed fix is correct; the commented out code exists only for IE8 and below anyway, which we don't support. (I'm copying this fix for glamor, thanks!)

ps - this problem will pop up again for SC when `speedy` mode is turned on, because that portion in the vendored version again has no corresponding `appendRule` being returned.

**Comment by mxstbr** [comment]
Oh wow, I did not expect that! @didierfranc would you mind submitting a PR with the fix? Then we'll have IE10+ support 😎

**Comment by didierfranc** [comment]
Done 👍

**Comment by mxstbr** [comment]
Done by the amazing @didierfranc and released as of `v1.0.8`!

**Comment by axelson** [comment]
For future reference I believe this is the commit that fixes this issue: https://github.com/styled-components/styled-components/commit/9115834c56b68e6fd124b22c309b6da1b546ca54
