### ISSUE TITLE
Warning with server side rendering

### ISSUE THREAD

**Issue by stephane-r** [styled-components/styled-components#1071]
Hi community,

## Version
2.0.0

## Actual Behavior

I use styled-components on Meteor project with server side rendering, and i've React warning in browser console :

```
Warning: React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
 (client) t</span></span></a><a class="sc-ifAKCX D
 (server) t</span></span></a></nav><a class="activ
```

It's on Meteor project, so i don't have webpack config.

You can see my **index.js** on server :

```
onPageLoad(sink => {
  const sheet = new ServerStyleSheet();
  const html = renderToString(sheet.collectStyles(
    <Routes location={sink.request.url} />
  ));
  const helmet = Helmet.renderStatic();
  sink.appendToHead(helmet.title.toString());
  sink.appendToHead(helmet.meta.toString());
  sink.renderIntoElementById('app', html);
  sink.appendToHead(sheet.getStyleTags());
});
```

And my **babelrc** :

```
{
	"presets": [
		"stage-1"
	],
 	"plugins": [
  		"transform-decorators-legacy",
  		"transform-class-properties",
  		["styled-components", {
      		"ssr": true
    	}]
  	]
}
```

I think the problem is because i use styled-components on server AND on client. Maybe i need to configure my module for use only on server side ?

Thank you community !

**Comment by philpl** [comment]
So you're already using the babel plugin which generates consistent component IDs:

```["styled-components", { "ssr": true }]```

But from what I can see here is that you're simply outoutting different class names here:

```js
 (client)  t</span></span></a><a class="sc-ifAKCX D
 (server) t</span></span></a></nav><a class="activ
```

This output is cut off so you'll have to investigate this yourself, but you can see here that on the server the `a` tag starts rendering a class called `activ...` and on the client I'm only seeing the styled-components class: `sc-ifAKCX...`

Also make sure to upgrade to the latest version. 2.0.0 is seriously outdated and we fixed a couple of bugs since then. https://github.com/styled-components/styled-components/releases

I'm also not sure whether you're actually using the plugin correctly. The className that I can see on your client snippet there suspiciously looks like an auto generated one from the runtime.

**Comment by stephane-r** [comment]
Hi @philpl 

Thank for your response.

I've upgrade my styled-components package on latest version :) But same problem. Maybe, the problem is my routes ? I've my routes on server-side AND client side, styled-components is executed on server and client ? :

My server side routes :

```
const Routes = (props) => {
  const context = {};
  return (
    <StaticRouter location={props.location} context={context}>
      <Switch>
        <AppLayout exact path='/' component={Home} />
        <AppLayout exact path="/blog" component={Blog} title={Trans.page.blog.title} />
        <AppLayout path='/blog/:slug' component={Article} title={Trans.page.blog.title} subtitle />
      </Switch>
    </StaticRouter>
  );
}
```

And my client side routes :

```
const Routes = () => {
  return (
    <BrowserRouter>
      <Switch>
        <AppLayout exact path='/' component={Home} />
        <AppLayout exact path="/blog" component={Blog} title={Trans.page.blog.title} />
        <AppLayout path='/blog/:slug' component={Article} title={Trans.page.blog.title} subtitle />
      </Switch>
    </BrowserRouter>
  );
}
```

Maybe, the problem is here ?

**Comment by philpl** [comment]
@stephane-r I think that's unlikely. The most plausible explanation is that the babel plugin is not taking effect on either the server code, client code, or even both.

Can you paste a snippet of the transpiled server code and client code of one of the affected styled components?

Also the original code so I can make sure that it's not a simple usage mistake.

I'm afraid without seeing any part of your app, it's impossible to pin down :/

**Comment by stephane-r** [comment]
@philpl I've find the difference server side/client side : i add new item on my navigation (item Admin, display after client load with Meteor) :

server side :

`data-reactid="16">contact</span></span></a></nav><a class="active`

client side :

`data-reactid="16">contact</span></span></a><a class="App__NavigationItem-zyueqg-1 gMzkOZ" href="/admin" data-reactid="17"><span data-reactid="18"><span class="App__Text-zyueqg-2 iRDlts" data-text="admin" data-reactid="19">admin</span></span></a></nav><a class="active`

**Comment by philpl** [comment]
Ok, make sure to only add a difference after the initial render :)
