### ISSUE TITLE
Warning: Unknown prop `innerRef` on <div> tag.

### ISSUE THREAD

**Issue by gurs1kh** [styled-components/styled-components#1073]
I keep on getting the following warning:
`Warning: Unknown prop 'innerRef\' on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop`

The only way to resolve this seems to be by changing\
`const StyledView = styled(({position, ...props}) => <View {...props} />)`
to
`const StyledView = styled(({position, innerRef, ...props}) => <View {...props} />)`

I have also tried using
`styled.View.attrs({
  position: props => props.position
})`
but then it gives a warning that prop `position` can't be found.

**Comment by gurs1kh** [comment]
Also, I have done my best to look through other issues, but none have solved my problem

**Comment by philpl** [comment]
When you're wrapping your own component we don't filter any props so they go directly onto the renderer element. Make sure to take care of that.

It'd be even better to reverse this order. Wrapping your own components is often not preferable and you should try to instead have your structural components above your presentational ones

**Comment by gurs1kh** [comment]
I'm not sure what you mean. Can you provide an example? By the way, innerRef is not a prop that I created.

**Comment by philpl** [comment]
It looks to me like you're using a very outdated version then? The `innerRef` is only passed if the child is a StyledComponent as well. I think we had a bug passing it all the time before v2 or in some patch of v2.

https://github.com/styled-components/styled-components/blob/master/src/models/StyledComponent.js#L159

**Comment by gurs1kh** [comment]
I'm on the latest version, but only recently updated to it. Before updating, I didn't get this warning

**Comment by philpl** [comment]
Is `View` a styled component as well?

Please submit all the necessary details for me to look into this. I hope you understand that it's near impossible without them to find out what exactly is going on 😢  Please don't just skip and delete the issue template when opening an issue

https://raw.githubusercontent.com/styled-components/styled-components/master/.github/ISSUE_TEMPLATE.md

**Comment by gurs1kh** [comment]
sorry about that. I am on version 2.1.2 and I'm having issue on the React Native version of styled-comoponents (styled-components/native).
View refers to React Native's View component.

**Comment by philpl** [comment]
Right, in this case you're using React Native Web or something similar, I assume.

This is expected behaviour since each component needs to handle refs for setNativeProps. You need to pass on the innerRef prop as ref. The warning that is telling you to do this only comes up when setNativeProps is called.

On web you can also safely ignore this warning or filter innerRef as you already did.

I see that you're not doing anything inside your stateless component that you wouldn't be able to do in just a styled component. Just use the styled.View shorthand.

**Comment by gurs1kh** [comment]
When using styled.View, I get the following error:
`Warning: Unknown prop `position` on <div> tag.`
This is because the position prop is not a prop of View.
