### ISSUE TITLE
defaultValue property not supported for styled.input

### ISSUE THREAD

**Issue by ungerpeter** [styled-components/styled-components#1074]
I think the defaultValue property is not working with an enhanced input field using styled.input.

Code:
```
<input defaultValue={entry.foo} />
```
is working. 
Ref: [https://facebook.github.io/react/docs/uncontrolled-components.html#default-values](https://facebook.github.io/react/docs/uncontrolled-components.html#default-values)

Now I try to style it with following code:
```
const StyledInput = styled.input`
  ...
`;

...

<StyledInput defaultValue={entry.foo} />
```
is not working.

Is there a way to achieve the defaultValue behavioure in this scenairo?

**Comment by philpl** [comment]
Can't reproduce it. Seems to be working fine for me. I also don't see how this can be related to SC, as we just wrap a normal React element in our styled components.

Have you made sure that `entry.foo` actually passes a correct value?

https://codesandbox.io/s/48V26znOn

**Comment by ungerpeter** [comment]
Sorry for the confusion, this was actually my fault.
The entry.foo wasn't containing the desired value on the initial render call.
