### ISSUE TITLE
How to get keyCode from styled component?

### ISSUE THREAD

**Issue by joetidee** [styled-components/styled-components#1078]
Please see this S.O. question...

[https://stackoverflow.com/questions/45612899/how-to-capture-the-keycode-from-a-styled-component](https://stackoverflow.com/questions/45612899/how-to-capture-the-keycode-from-a-styled-component)

**Comment by k15a** [comment]
Take a look how React handles events at https://facebook.github.io/react/docs/events.html. styled-components doesn't change this behaviour at all.

**Comment by joetidee** [comment]
Looks like I needed to check event.charCode as well.

**Comment by k15a** [comment]
It should be the same with event.charCode :)
