### ISSUE TITLE
[TS] StyledComponentClass does not have any construct or call signatures

### ISSUE THREAD

**Issue by renatorib** [styled-components/styled-components#1079]
Hello. I'm trying to up a new project with typescript + styled-components, but I faced with a problem with prop types + jsx.
I get this error: `[ts] JSX element type 'Styled' does not have any construct or call signatures` when I try to use a Component from styled.

```tsx
type Props = {
  color: string,
};

const Styled = styled<Props>('div')`
  color: ${p => p.color};
`;

// later
render() {
  return (
    <Styled />  {/* [ts] JSX element type 'Styled' does not have any construct or call signatures */}
  ) ;
}
```

![image](https://user-images.githubusercontent.com/3277185/29192601-5ca6429c-7df8-11e7-81ed-3784105a7a94.png)

`Styled` type is `StyledComponentClass<Props, any, Props>` by inference as specified in styled typings.

![image](https://user-images.githubusercontent.com/3277185/29192539-275d0f3a-7df8-11e7-9895-da9ba8d7885e.png)

But if I force the type as `any` it works 'normally', without error:

```tsx
const Styled: any = styled<Props>('div')`
  color: ${p => p.color};
`;
```

![image](https://user-images.githubusercontent.com/3277185/29192674-a0203c44-7df8-11e7-9f1a-e4464261d82c.png)

But this way I'll loss all the typing benefit, I think.

I tried put `StatelessComponent<Props>` instead of any, but unsuccessfully (I don't know why, I'm new with TS)

![image](https://user-images.githubusercontent.com/3277185/29192757-fe1460a0-7df8-11e7-95ad-b5f8f1fe287c.png)

---

How can I get around this situation?

**Comment by renatorib** [comment]
**Updating:** it seems that the prop types do not influence the error:


![image](https://user-images.githubusercontent.com/3277185/29193041-18c45fe4-7dfa-11e7-8169-889f79508355.png)

**Comment by renatorib** [comment]
Sorry, my bad. I forgot to install `@types/react`;

**Comment by MariusAlch** [comment]
Thank for documenting, had same issue. :)

**Comment by tur-nr** [comment]
Even with `@types/react` I get this error 😒 

![image](https://user-images.githubusercontent.com/817134/43945211-cfdf3660-9cc4-11e8-90fd-cf9b5ade4de0.png)

```json
{
  "dependencies": {
    "react": "16.4.1",
    "react-native": "0.56.0",
    "styled-components": "^3.4.1"
  },
  "devDependencies": {
    "@types/jest": "^23.3.1",
    "@types/react": "^16.4.9",
    "@types/react-native": "^0.56.6",
    "@types/react-navigation": "^2.0.13",
    "@types/react-test-renderer": "^16.0.2",
    "babel-jest": "23.4.2",
    "babel-preset-react-native": "^5",
    "jest": "23.4.2",
    "react-addons-test-utils": "^15.6.2",
    "react-dom": "^16.4.2",
    "react-native-typescript-transformer": "^1.2.10",
    "react-test-renderer": "16.4.1",
    "ts-jest": "^23.1.3",
    "typescript": "^3.0.1"
  }
}
```

**Comment by tur-nr** [comment]
After much playing about I noticed that you have to enable Typescript support on VSCode. I had a fresh install of VSCode and after installing/enabling full support the Typingscript it worked.

![image](https://user-images.githubusercontent.com/817134/43982680-6bd4b85e-9d3a-11e8-915e-9f682b83f69a.png)

Just click Typescript on the welcome screen and reload your editor. It's funny cause Typescript syntax works out the box for VSCode, but only after I do this does it begin to work 🤔 

I can confirm that it works for me, thanks again team.

❤️💅
