### ISSUE TITLE
Classname ordering problem since 2.1.2

### ISSUE THREAD

**Issue by probablyup** [styled-components/styled-components#1083]
## Version
styled-components@2.1.2
babel-plugin-styled-components@1.1.7 (SSR enabled, no preprocessing)

## Reproduction / Steps to reproduce
I don't have repro steps right now, but I'm seeing an issue with the order of how the generated classes are concatenated in v2.1.2, specifically in NODE_ENV=production. Downgrading to v2.1.1 fixes it.

I have a component chain that looks like this:

```
1. BaseSVG = ({ height, width, ...props }) => <svg {...props} />
2. Icon = styled(BaseSVG)
3. Arrow = Icon.extend.attrs({ viewBox: '0 0 63 40' })
4. StyledArrow = styled(Arrow)
```

For some reason, the generated class name for `#4` is being concatenated before `#2`.

**Comment by philpl** [comment]
So first the disclaimer: Factories that wrap around StyledComponents (see `styled(Arrow)` where `Arrow` is a StyledComponent) are not the preferred use-case anymore, so things could be screwy. Not sure.

We have some missing information:

- What's the resulting classnames?
- What does the reproduction case on codesandbox / webpackbin look like?
- Is the babel plugin being used? (If yes, what version, what options, what's its code output?)

Also an important question: How are they being loaded? If there's sth fishy going on with the import order, for example a circular dependency, then the code might still work, but the className for `#2` is injected before `#4`, since that's a factory with two separate classnames.

Btw the only thing that has changed is the addition of generation deterministic ID generation for `.extend` and `.withComponent`.

**Comment by probablyup** [comment]
> Factories that wrap around StyledComponents (see styled(Arrow) where Arrow is a StyledComponent) are not the preferred use-case anymore, so things could be screwy. Not sure.

What do you mean? What's the recommended pattern then if you need to do override styles?

**Comment by philpl** [comment]
@probablyup The `.extend` and `.withComponent` methods. I mean you are using `.extend` for 3, but not for 4. https://www.styled-components.com/docs/basics#extending-styles

**Comment by probablyup** [comment]
Isn't it wasteful to use .extend though unless you need to, since it
duplicates all the styles?

**Comment by philpl** [comment]
@probablyup that only applies to SSR, and in that case gzip takes care of the duplication for you quite nicely. :)

**Comment by probablyup** [comment]
Hmm alright, noted. I'll try switching syntax internally and seeing if that
improves things.

**Comment by probablyup** [comment]
@philpl I've been thinking more on this and have a general note: people on my team have commented that it's confusing to know when to use `styled()` vs `.extend`.

I agree with that and unless you have an IDE popup that tells you what you're touching is a styled-component, you have to dig down into the impl to figure out which thing to use.

It would be better to always use the `styled()` API and have whether it extends or simply adds a class be an implementation detail.

**Comment by philpl** [comment]
@probablyup The general rule we've established is: Always use `.extend`.

https://github.com/styled-components/styled-components/issues/45
https://github.com/styled-components/styled-components/pull/46

This is also what we state in the documentation: https://www.styled-components.com/docs/basics#extending-styles

**Comment by probablyup** [comment]
`.extend` doesn't work on non styled-components. What I'm saying is your API is made confusing for no reason by giving two ways to do the same thing that require impl knowledge to differentiate.

Styled components should just automatically `.extend` if given another styled component.

**Comment by probablyup** [comment]
I'm going to move this into a new issue since the conversation has kind of diverged.

**Comment by Aleksion** [comment]
Is the className ordering issue fixed? I'm experiencing it 50% of the time, when I deploy my code to production.

 It seems to happen whenever I've used .extend:

<img width="214" alt="screen shot 2017-09-06 at 11 36 33" src="https://user-images.githubusercontent.com/3367641/30120754-c36c8130-92f7-11e7-932a-90142dcfb83b.png">
<img width="217" alt="screen shot 2017-09-06 at 11 36 49" src="https://user-images.githubusercontent.com/3367641/30120756-c3a8acc8-92f7-11e7-8907-001d86750a05.png">

**Comment by probablyup** [comment]
Happens to me too. Haven't quite figured out the issue yet.

**Comment by Aleksion** [comment]
This is becoming more and more of an issue. Any idea why this is happening?

**Comment by philpl** [comment]
Locked in favour of https://github.com/styled-components/styled-components/issues/1164

@probablyup Since this issue needed more info and the new one as well, if you can, please help us find a reproduction, or answer the questions I've posted there :smile:

**Comment by geelen** [comment]
> So first the disclaimer: Factories that wrap around StyledComponents (see styled(Arrow) where Arrow is a StyledComponent) are not the preferred use-case anymore, so things could be screwy. Not sure.

I know this discussion is locked and all but just to be clear—`styled(Arrow)` should _always_ work 100% great no-problems A+ you win! If it's ever "screwy" it's a bug. The only reason you'd choose `.extend` is if you _know_ what you're extending is a SC. Across file boundaries I think that's very rarely the case.

> @philpl I've been thinking more on this and have a general note: people on my team have commented that it's confusing to know when to use styled() vs .extend.

I've seen this too. I should add something to the docs on this point but I haven't yet, sorry.
