### ISSUE TITLE
Components with ability to override styles 

### ISSUE THREAD

**Issue by webchaz** [styled-components/styled-components#1085]
When sharing components using styled components I've seen a few different ways folks will allow the end user to override or customize the styles, such as including class names or allowing inline styles in props.  Is there a recommended way or standard to allowing components to be overridden.  I could see possibly allowing a styled component as a prop, but having the ability to merge the styles?

**Comment by geelen** [comment]
Yep, definitely the recommended way to override styles is to pass a classname. Calling `styled(Comp)` actually wraps `Comp` and passes `className` down, which sounds like what you're looking for: https://www.styled-components.com/docs/basics#styling-any-components

**Comment by gustavopch** [comment]
@geelen Some components like `react-autosuggest` allow you to use some CSS classes to style not only the root component, but a bunch of subcomponents too. I don't see how styled-components could be used in this case. Any idea?

**Comment by k15a** [comment]
```js
const StyledComponent = styled(AutoSuggest)`
// styles

.subcomponent-class {
     // subcomponent styles
}

.another-subcomponent-class {
     // another subcomponent styles
}
`
```

**Comment by gustavopch** [comment]
Thank @k15a. Your answer led me to the solution and I'll let it here for other people:
```javascript
const classNames = {
  container: 'react-autosuggest__container',
  containerOpen: 'react-autosuggest__input',
}

const AutosuggestWrapper = styled.div.attrs(classNames)`
  .${classNames.container} {
    // Some styles here
  }
  .${classNames.input} {
    // Some styles here
  }
}
`

const Component = () =>
  <AutosuggestWrapper>
    <Autosuggest
      theme={classNames}
      /* Hiding other props for brevity */
    />
  </AutosuggestWrapper>
```

This will basically create a `<div>` outside of the Autosuggest elements and the classes will be applied.
