### ISSUE TITLE
Inline styles are passed through (instead of being added to the generated CSS)

### ISSUE THREAD

**Issue by ravinggenius** [styled-components/styled-components#1091]
Once in a while I have some component that needs little style tweaks basically everywhere it is used. It is pretty cumbersome to add a whole bunch of optional props to try to mix and match to get the results I want, so I just add a couple rules inline. Below is an example how I currently handle this:

```javascript
const Foo = styled.span`
  // a bunch of standard styles shared by all `Foo` instances

  // i can get what i'm asking for if i use a different prop (not `style`)
  ${({ tweaks }) => tweaks}
`;

const Generic = () => <Foo />;
const AAA = () => <Foo tweaks={{ padding: '10px' }} />;
const BBB = () => <Foo tweaks={{ fontSize: '64px' }} />;
```

In my case the tweaks are completely arbitrary but generally one or two rules. Adding props to handle each case would quickly get out of hand. Another solution could be to create new wrappers that extend the base component, but that feels super-pedantic:

```javascript
const Foo = styled.span`...`;
const PaddedFoo = Foo.extend`padding: 10px;`;
const BigFoo = Foo.extend`font-size: 64px;`;
```

The examples above work, but I'd much rather styled-components automatically handle the `style` prop the way I'm handling `tweaks` instead of passing it through.

**Comment by wmertens** [comment]
The `style` prop is for inline styling, not for adjusting classes. With `style` you can have 60fps animations, with classes not.

**Comment by ravinggenius** [comment]
Good point about inline styles being used for animation; I hadn't considered that. Is there any interest in pulling in `[tweaks]` (or some "standard" prop) to adjust classes the way I described?

**Comment by philpl** [comment]
@ravinggenius Sorry, we’re not looking into adding a prop like that. We believe that it’d encourage the wrong patterns that go against the best practices laid out by our API.

You can also use the attrs method btw to compute some style on the fly. It often shouldn’t be necessary to pass any inline styles. Animations are a big exception depending on how you implement them
