### ISSUE TITLE
Using StyleSheet helper for react-native

### ISSUE THREAD

**Issue by Noitidart** [styled-components/styled-components#1092]
Hi I had a question. I searched issues and I tried on gitter but got no reply yet. On spectrum it seems only few issues created. Please excuse this.

I'm trying to decide if I should use styled-components in my React Native project. Does this use StyleSheet component imported from react-native project? Or is it doing inline styles on all the components?

**Comment by k15a** [comment]
We're using `css-to-react-native` to create the React Native StyleSheet objects from CSS.

**Comment by Noitidart** [comment]
Thank you sir, it seems that package does not use `StyleSheet`. Thank you for leaving this issue open for me to close.
