### ISSUE TITLE
Can't pass props to exported named components

### ISSUE THREAD

**Issue by jpls93** [styled-components/styled-components#1097]
## Version
2.1.2

## Reproduction
See [Webpack Bin](https://www.webpackbin.com/bins/-Krv9odtidkQAN75uvbS)
## Steps to reproduce
See [Webpack Bin](https://www.webpackbin.com/bins/-Krv9odtidkQAN75uvbS)
## Expected Behavior
`DivB` should receive props
## Actual Behavior
`DivB` does not receive props

**Comment by philpl** [comment]
Your wrapped component must accept the className prop. It’s all in the docs in this section :wink: https://www.styled-components.com/docs/basics#styling-any-components

It also mentions that this pattern is not recommended :smile: Try to use the presentational component (in our case styledcomponent) as the lowest one, and put your presentational components around it instead

**Comment by jpls93** [comment]
@philpl Thank you so much!
