### ISSUE TITLE
CSS `filter` isn't prefixed

### ISSUE THREAD

**Issue by dmitrizzle** [styled-components/styled-components#1099]
## Version
`styled-components@2.1.2`

## Reproduction
```javascript
const StyledDiv = styled.div`
  filter: grayscale(100%);
`
// or any CSS filter property
```
## Steps to reproduce
- Use the above component and inspect element in browser

## Expected Behavior
```css
-webkit-filter: grayscale(100%);
filter: grayscale(100%);
```

## Actual Behavior
```css
filter: grayscale(100%);
```

***
I'm not really sure what the cut off for prefixes is, because it works well in most cases (like `flexbox`) and doesn't show in others (like `box-shadow`) - which is expected since we're way past this in terms of browser support.

**Comment by mxstbr** [comment]
@thysultan

**Comment by diondiondion** [comment]
> I'm not really sure what the cut off for prefixes is, because it works well in most cases (like flexbox) and doesn't show in others (like box-shadow) - which is expected since we're way past this in terms of browser support.

Especially these three regularly make me cry in silence every time I come across them:

![screen shot 2017-08-20 at 16 39 27](https://user-images.githubusercontent.com/5636050/29495777-3c36850a-85c6-11e7-9c15-4a0fc305c0da.png)

😢

**Comment by thysultan** [comment]
Pushed a patch for this in 3.2.9. @diondiondion I'm sure that was also patched in a previous release.

**Comment by mxstbr** [comment]
Thanks @thysultan!
