### ISSUE TITLE
Pass props not as strings

### ISSUE THREAD

**Issue by stavb** [styled-components/styled-components#1100]
Hi, I'm fairly new to this and I'm trying to style my components according to props passed not as strings, like "Button primary small" for example. 

Say I have 7-8 of those button types, (small/large/primary/warning etc), each has some different styling, is there a nicer way to do that rather than use { css } ?

Right now I have something like that:
${(props) => props.small && css& { 
    (all the styles here)
}}
${(props) => props.large && css& { font-size: 
    (all the styles here)
}}
and it's not very pretty when done for each type.

I **don't** want to pass them as strings (like "Button type="Primary") so I can do something like
background-color: ${(props) => theme.buttons.background[props.type]};

So is there an elegant way for what I am looking for?

Thank you very much!

**Comment by wmertens** [comment]
I don't understand what you are asking. If you're talking about repeating styles, you can put the styling in a theme object, and then grab the style from the theme object.

```js
const theme = {large: css`…`}
const Button = styled.button`
 ${p => p.large && p.theme.large}
`
```

**Comment by stavb** [comment]
Thank you, it's actually wasn't what I was asking. I am using a theme object.
My theme looks something like that:

`{
primary: {
        background: '#52c7ca',
        color: '#212121',
   },
success: {
        background: '#2196f3',
        color: '#fff',
      },
 info: {
        background: '#69f0ae',
        color: '#212121',
      }
}`

It's just a fragment of course. It's actually huge. Hence the problem. Once I have around 8 possible props (primary, success, info... etc) with each has it's own totally different styles, I end up with 8 blocks of styles for the same component:

`${(props) => props.primary&& css& {
(block of styles)
}}`

So my question is - is there a nicer way in that case.

I understand you're suggesting a whole different theme for each prop?

**Comment by k15a** [comment]
@stavb If you use code fences you can actually make your comments a log more readable:
````md
```jsx (this can be another language as well)
    const Comp = styled.div`
        background-color: red;
    `
```
````

**Comment by wmertens** [comment]
Yes actually, what we (Yaska.eu) do is we switch themes throughout the app.

We follow the Material UI reasoning of having a base color + an accent
color for a theme, and then 3 text opacities for the primary/secondary/hint
text; the text is either black of white, depending on the color.

Then we have some helper functions that select a color, and use those in
the css depending on use case. So if we want to highlight a text or a
button, we just add the prop `accent` and it uses the current accent color.

For buttons, we have a couple of default themes (default/danger) that get
applied unless you pass the prop `useTheme`.

**Comment by stavb** [comment]
@k15a thank you so much, I was embarrassed to ask how :))

**Comment by stavb** [comment]
I'll look into that then. Thank you for the answer!

**Comment by k15a** [comment]
@stavb You can even enable syntax highlighting if you put your language after the fence:

````markdown
```language

```
````

For example:

````markdown
```jsx

```
````

**Comment by stavb** [comment]
@k15a Thanks!
