### ISSUE TITLE
support for unnamed components

### ISSUE THREAD

**Issue by jole78** [styled-components/styled-components#1101]
Hello, I've used SC for a while now and I can't help noticing that my components get "cluttered" with a lot of these SC components, like this one for example.
```javascript
const StartPage = styled.div`
    display: flex;
    flex-direction: column;
`;

function App() {
  return (
    <StartPage>
      Hello world!
    </StartPage>
  )
}
```

Using glamorous I can just do something like this for example:

```javascript
const { Div } = glamorous

function App() {
  return (
    <Div
      display="flex"
      flexDirection="column"
    >
      Hello world!
    </Div>
  )
}
```
However I can not see this possible with styled-components or have I misunderstood it completely?

I love SC and don't want to use object literals, love that it's just css but I'm really missing this feature sometimes.

Thanks

**Comment by dashed** [comment]
You probably don't need styled-components.

If you want what you're proposing, you can just do this then:

```js
const Div = props => {
  const { children, ...rest } = props;

  return (
    <div style={{ ...rest }}>
      {children}
    </div>
  );
};

function App() {
  return (
    <Div display="flex" flexDirection="column">
      Hello world!
    </Div>
  );
}

const mountNode = document.getElementById("root");

ReactDOM.render(<App />, mountNode);
```

**Comment by jole78** [comment]
Yes I know I can do that. But this was more along the lines of a feature request/discussion that something like this would be possible.

```javascript
import styled from "styled-components"

function App() {
  return (
    <styled.div`
      display: flex;
      flex-direction: column;
    `>
      Hello world!
    </styled.div>
  )
}
```
FYI, I know that API wouldn't actually work but something that resembles it perhaps??. Or something that would make a use case with using an 'unnamed' styled component work.

**Comment by dashed** [comment]
Reason why it won't work is because jsx syntax doesn't allow it: http://facebook.github.io/jsx/

If your file feels cluttered, perhaps that's a sign to refactor components into their own files.

**Comment by philpl** [comment]
This is all done on purpose. We encourage the user to enforce a strict "pyramidal" structure of components where: container/logic components come first (uppermost), structural components come second, and presentational components come last (leaf components).

This is exactly why we do not support this use case. styled-components is all about enforcing best practices and keeping the styling maintainable and this stands in conflict with putting CSS properties/code into the JSX fully dynamically.

You can however create a library of reusable components that fit multiple use-cases to get around this.

cc @mxstbr
