### ISSUE TITLE
babel-plugin-styled-components caused client warning and does not minify

### ISSUE THREAD

**Issue by ablbol** [styled-components/styled-components#1103]
Thanks for this library. 
I am using styled-components for the first time (v. 2.1.2). I am using ssr with babel in the backend and webpack for the front end.  Things work great without babel-plugin-styled-components. But when I use the plugin (v. 1.1.7) , I start getting warnings in the client
```
Warning: Prop `className` did not match. Server: "styles__Nav-yml20y-0 kAAKah" Client: "sc-bdVaJa cnYbMq"
```
Also when I use the "minify": true option, the styles coming from the server are not minified.

This is the style I am getting from the server:
```
<style type="text/css" data-styled-components="kAAKah cnYbMq" data-styled-components-is-local="true">
/* sc-component-id: styles__Nav-yml20y-0 */
.styles__Nav-yml20y-0 {}

.kAAKah{background:red;}

/* sc-component-id: sc-bdVaJa */
.sc-bdVaJa {}
.cnYbMq{background:red;}</style>
```
This is what I have in package.json
```
"plugins": [
      "transform-class-properties",
      "transform-object-rest-spread",
      "syntax-dynamic-import",
      "transform-react-constant-elements",
      "transform-react-inline-elements",
      [
        "styled-components",
        {
          "ssr": true,
          "minify": true
        }
      ]
    ]
```

Any idea why I get the warning and css is not minified?
Thanks

**Comment by philpl** [comment]
> Warning: Prop `className` did not match. Server: "styles__Nav-yml20y-0 kAAKah" Client: "sc-bdVaJa cnYbMq"

It seems that only the server code is being transpiled and not the client code :wink:

**Comment by ablbol** [comment]
How do you transpile the client code?

**Comment by philpl** [comment]
@ablbol that fully depends on your set up. Generally, for example in next.js, the transpiler is used for both and server code is emitted to a separate path before it gets transpiler again and bundled up for the client.

Oftentimes people run the transpiler for the server completely separately or run a second bundler, so it’s rare to see that in your case only the server code is being transpired correctly.

It might also be an issue where your client Babel config (if it’s separate) is using the env property. In that case you need to add the plugin to the env object instead of the top most one.

What’s your set up? I’m sure I can help out with more info here :)

**Comment by ablbol** [comment]
I am using webpack in the frontend and babel in the backend.  I don't have babel setup for the front end.  I am able to use the plugin in babel by following instructions but I have no idea how to add the plugin in webpack. This is what I have in package.json. But it is not clear to me how to add the plugin in webpack!! Thanks for your help.

```
  "scripts": {
    "security": "nsp check",
    "webpack": "webpack -wd --colors",
    "dev": "NODE_ENV=development nodemon --exec NODE_PATH=./src babel-node ./src/server/index.js",
    "test": "jest --watch",
    "prod-build": "rimraf ./build && rimraf ./public/js && webpack -p && babel src -d build -s inline --copy-files",
    "prod-start": "NODE_ENV=production NODE_PATH=./build node ./build/server/index.js"
  },
  "babel": {
    "presets": [
      "react",
      [
        "env",
        {
          "targets": {
            "node": "current"
          }
        }
      ]
    ],
    "plugins": [
      "transform-class-properties",
      "transform-object-rest-spread",
      "syntax-dynamic-import",
      "transform-react-constant-elements",
      "transform-react-inline-elements"
    ]
  }
```

Here is what I have in webpack config:
```
let browserConfig = {
  name: "browser",
  target: "web",
  entry: ["babel-polyfill", "./src/browser/renderer.js"],
  devtool: "cheap-module-source-map",
  resolve: {
    modules: [path.resolve("./src"), path.resolve("./node_modules")]
  },
  output: {
    path: path.resolve(__dirname, "public"),
    publicPath: "/",
    filename: "js/bundle.js"
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        loader: "babel-loader",
        query: {
          presets: ["react", "env", "stage-2"]
        }
      }
    ]
  }
};
```

**Comment by ablbol** [comment]
I resolved this issue.
I thought that webpack will pick up configs from babelrc but for some reason it did not.  I ended up adding the following line to webpack config:
```
plugins: [["styled-components", { ssr: true, displayName: true }]]
```
Thanks alot for all your time and help.
