### ISSUE TITLE
position: sticky not prefixed for iOS

### ISSUE THREAD

**Issue by martynhoyer** [styled-components/styled-components#1104]
## Version
2.1.1

## Steps to reproduce

Use `position: sticky;` on a component.

## Expected Behavior

Resultant CSS:
```
position: sticky;
position: -webkit-sticky;
```

## Actual Behavior

```
position: sticky;
```
(no prefixed rule)

Both https://github.com/styled-components/styled-components/issues/158 and https://github.com/styled-components/styled-components/issues/111 reference this issue but they're closed, so I'm raising this one as requested.

You can work around it by manually adding in the prefixed value like so: 

```
export const StickyHeader = styled.div`
  position: sticky;
  position: -webkit-sticky;
  top: 0;
`
```

**Comment by philpl** [comment]
cc @thysultan

**Comment by thysultan** [comment]
patched in stylis 3.2.10

**Comment by philpl** [comment]
Cheers :)

**Comment by martynhoyer** [comment]
Thanks folks! Speedy turnaround 👍
