### ISSUE TITLE
Input not working on react-native

### ISSUE THREAD

**Issue by smolleyes** [styled-components/styled-components#1106]
hi

i can  t use input on react-native

when i do a simple

```
const MyInput = styled.input`
  border: solid 1px white;
`;
```

i have 

`_.native2.default.input is not a function` Oo

everything else works :/

just reinstalled with yarn add ... and rn 0.47.1

thanks !

**Comment by philpl** [comment]
You’re referring to a tag name / Dom element name here, but for React Native you need to refer to their components’ names: https://facebook.github.io/react-native/docs/components-and-apis.html

For an input you can use the InputText component. So the call would be styled.InputText

**Comment by smolleyes** [comment]
hi

ok thanks

but you might have a look to your doc

https://www.styled-components.com/docs/basics#react-native

i searched for" input" on this page :)

**Comment by philpl** [comment]
@smolleyes the problem is that we don’t have a whole lot of space right now for a list. Also it’d be kind of redundant. Maybe we should link to the components list? I’d appreciate an issue with some ideas on the website repository :)
