### ISSUE TITLE
How to change asset URLs?

### ISSUE THREAD

**Issue by OutThisLife** [styled-components/styled-components#1107]
Looking for functionality similar to https://github.com/postcss/postcss-url but I don't believe styled-components works w/ postcss.

Anyone have a solution?

**Comment by philpl** [comment]
We don’t have compile time plugin support and likely won’t have it anytime soon — If ever. Sorry for that! We like to keep things focused ;)

Instead you could write a small helper function that does this for you? Babel-plugin-preval could even help you with compile time checks and path resolution

**Comment by philpl** [comment]
cc @mxstbr do you have more ideas by any chance?

**Comment by OutThisLife** [comment]
I'll check out preval, thanks for the direction.

**Comment by OutThisLife** [comment]
@philpl @mxstbr Is there a better way to do this?
