### ISSUE TITLE
props are comming empty from the server

### ISSUE THREAD

**Issue by ablbol** [styled-components/styled-components#1111]
I am using styled-components (v. 2.1.2).
I am using SSR with the following configuration:
I am bundling the front end with webpack and compiling the backend with babel.
I was not able to use babel plugin for styled component in the front end because I could not figure out how to use the plugin with webpack.
I have a style that looks like this:
```
export const Link = styled.a`
  color: ${props => props.theme.primary}; 
`;
```

In the server, props.theme.primary is empy but it is okay on the client.  Any explanation to that.  I wonder if it has anything to do with the babel plugin?
Thanks

**Comment by philpl** [comment]
This is unfortunately by far not enough information to go after.

> I was not able to use babel plugin for styled component in the front end because I could not figure out how to use the plugin with webpack.

The plugin needs to be used on both with the `ssr` option enabled. Otherwise the ids are not going to match up.

> In the server, props.theme.primary is empy but it is okay on the client.

Sounds like the `ThemeProvider` is not in the right context / not being used.

**Comment by ablbol** [comment]
Thanks for your quick reply.
I am using the Theme provider in the client side. This is how it looks:

```
ReactDOM.hydrate(
  <ThemeProvider theme={theme}>
    <ApolloProvider store={store(client)} client={client}>
      <BrowserRouter>
        <App />
      </BrowserRouter>
    </ApolloProvider>
  </ThemeProvider>,
  document.getElementById("root")
);
```

This is what I have in the server side:
```
app.use(async (req, res) => {
  const routeContext = {};
  const client = apollo(req);
  const dataStore = store(client);
  const sheet = new ServerStyleSheet();

  const components = (
    <StyleSheetManager sheet={sheet.instance}>
      <StaticRouter location={req.url} context={routeContext}>
        <ApolloProvider store={dataStore} client={client}>
          <App />
        </ApolloProvider>
      </StaticRouter>
    </StyleSheetManager>
  );
  await getDataFromTree(components);
  const initialState = client.getInitialState();
  const styles = sheet.getStyleElement();

  const htmlStream = new PassThrough();
  htmlStream.write("<!DOCTYPE html>");
  const reactStream = ReactDOMServer.renderToStream(
    <Html state={initialState} styles={styles}>
      {components}
    </Html>
  );
  res.status(200);
  res.contentType("text/html");
  reactStream.pipe(htmlStream).pipe(res);
});
```

**Comment by philpl** [comment]
The ThemeProvider is indeed missing on your server side ;) just add it there as well. You could alternatively just add it to your app if it’s also just a wrapper. I’d recommend you to share as much code there as possible between the client and server, especially if it ends up being the same.

Also make sure to set up the Babel plugin on both ends. I’m not sure why you’re not setting up the same Babel config for both with two environments? (Env property)

**Comment by ablbol** [comment]
After placing the theme provider in the server, things worked well. I was was following the docs but it did not say to place the ThemeProvider no both side.
Thank you soooo much for your help.
