### ISSUE TITLE
When using styled-component, unit test becomes not fesible

### ISSUE THREAD

**Issue by adamchenwei** [styled-components/styled-components#1112]
Things like `wrapper.find('.traveler-selection__input')` with enzyme becomes no longer fesible because we don't use class name the regular way in styled-component.

Is there a solution on this?

Thanks

**Comment by philpl** [comment]
There are already a load of issues asking for different approaches. It’s not infeasible but part of separating presentational and structural components surfaces during testing when it’s not strictly executed

https://github.com/styled-components/styled-components/issues/896#issuecomment-324469861

https://github.com/styled-components/styled-components/issues/624

Apart from the necessity to search for issues first, please also adhere to the issue template. If you spend less time on the issue that’s more time we have to dedicate to it ;)

**Comment by adamchenwei** [comment]
@philpl sorry! yes, I need to search for the issues first... duh... silly me since there are already 66 issues lol

Thanks for answering me with reference those I was reading those and found them very helpful!

Thanks
