### ISSUE TITLE
Wrong css if a template string wrapped to newline.

### ISSUE THREAD

**Issue by chiss2906** [styled-components/styled-components#1113]
After the css is being wrapped by a formatter, in that case Prettier, it seems to lack the tabs
```
border: thin solid
		${p => (p.theme.input ? p.theme.input.textEditorColor.border : `#000`)};
```

The devtools output:
<img width="210" alt="screen shot 2017-08-24 at 18 50 34" src="https://user-images.githubusercontent.com/3668084/29678258-27a34e30-88fe-11e7-9d19-238c68e4245b.png">

**Comment by philpl** [comment]
I'm pretty sure we can't really do anything to fix this as it's simply unexpected. Have you tried using the `minify` option of the babel plugin?

Maybe @thysultan's stylis can fix this upstream by checking whether the char after the stripped whitespaces is significant, and then keeping one?

Also note that you can work around this as follows:

```js
styled.div`
  ${p => css`
    border: thin solid ${p.theme.input ? p.theme.input.textEditorColor.border : `#000`)};
  `}
`
```

I think prettier doesn't look at nested tagged template strings yet, so this is safe from the formatter.

This is a really peculiar case and you should probably open an issue on their repo. Inserting a newline in the input is not always safe.

**Comment by thysultan** [comment]
@philip How would the input passed to stylis look like that produces this.

**Comment by mxstbr** [comment]
@thysultan the input would look like

```
border: thin solid
		rgba(0,0,0,.45);
```

can we fix this in stylis? Looks like a pretty big edge, to me that sounds like a bug in prettier. /cc @azz

Going to close this out since it's likely not relevant to our issue tracker.

**Comment by thysultan** [comment]
Hard to tell, this produces `border:thin solid;rgba(0,0,0,.45)` on my end. What version of stylis is installed in this case?
