### ISSUE TITLE
Unknown props when using .attrs constructor

### ISSUE THREAD

**Issue by momosh** [styled-components/styled-components#1115]
So, I'm trying out the new .attrs constructor that comes with the v2. And I'm doing the exact same thing as in example about Attaching additional props.
And I get this error: 
Unknown props `margin`, `padding` on <input> tag. Remove these props from the element.

I'm using:
"react": "^15.6.1",
"styled-components": "^2.1.2",
"webpack": "^3.5.3"

**Comment by k15a** [comment]
We are not filtering the attrs and just passing them down to the component. That's the reason why this method is called attrs and not props :)

**Comment by momosh** [comment]
Thanks for answering me, but I'm completely sure that I understand this, just started using styled-components myself pretty recently.
What would be a solution to this problem then, can you give me some example? Thnx :)

**Comment by philpl** [comment]
@momosh The solution is to either:

- Ignore the warning (but note that the prop will appear as an attribute on the DOM element)
- Rename `margin` and `padding` (the example in the docs is contrived and should not be used as is)
- Do the computation for your actual props using a transform function

If we assume that you've just used the example, it would become this:

```js
const getSize = p => p.size || '1em'

const Input = styled.input.attrs({
	// we can define static props
	type: 'password'
})`
	color: palevioletred;
	font-size: 1em;
	border: 2px solid palevioletred;
	border-radius: 3px;

	/* here we use the dynamically computed props */
	margin: ${getSize};
	padding: ${getSize};
`;
```

Note that I'm not using an intermediate `attrs` to compute the actual size.

**Comment by PengyuanZhao** [comment]
This warning could be gone in React 16 which supports [custom attributes](https://facebook.github.io/react/blog/2017/09/08/dom-attributes-in-react-16.html)
