### ISSUE TITLE
Serverside Inlineling for emails

### ISSUE THREAD

**Issue by episodeyang** [styled-components/styled-components#1116]
## TLDR: need an `inline` mode for rendering emails

HI, I tried to look for this but couldn't find it anyway. Now react is almost truly universal, at least universally used, I would like to build an email server that renders with `react`. 

Emails clients typically strips `<styles>` component leaving only the inline ones, so it is typical for email servers to inline all CSS. Is there a mode (like a flag) for `styled-components` that we can use to turn on this inlining conditionally?

Thanks in advance!
Ge

**Comment by k15a** [comment]
It's best to use another tool for inlining CSS :)

**Comment by episodeyang** [comment]
@k15a  Nah,  ¯\_(ツ)_/¯ that's how it is used to be done (for 20 years now?) 

Really with the full css-in-js stack this is a use case that is gonna come up sooner or later.

**Comment by k15a** [comment]
I don't think that we should take care of inlining CSS for emails at all. That's not our focus area and so it's much better to rely on a tool specifically made for inlining CSS.

I don't see any advantage of this:
```jsx
styled.inlineCSS = true
const email = ReactDOMServer.renderToStaticMarkup(<StyledEmail />)
```
over this:
```jsx
const juice = require('juice');
const email = juice(ReactDOMServer.renderToStaticMarkup(<StyledEmail />))
```

It will just bloat our library because we have to take care of something that's not used by 95% of our users.

**Comment by philpl** [comment]
As already said we don’t add a lot of features and APIs an instead try to cleanly and directly solve the 90% usecase.

I’m sure you can code up a library that does this in a really simple way in a day :) I’m sorry, but it doesn’t have any other usecases on the web unfortunately

**Comment by episodeyang** [comment]
My current thinking is that this is probably best done as an add-on library specifically for the `styled-components`.

@philpl Email is a big part of the web. Just like mobile, mobile web and desktop web, email is another large platform that is often overlooked. Even if this use case shouldn't be part of the core library, I would like to ask for your help to shape it as a `styled-component` or `react-DOM` based library for the `styled-component` eco system :)

@k15a So the issue there is that the HTML DOM module have to parse the HTML string, and this is typically a slow process (with JSDOM). In addition, the CSS inline process searches through the DOM and it add an extra pass through the DOM tree. Now if you do the CSS inlining directly on the virtual DOM, you could save quite a bit of time.

Emails are typically rendered only once for each recipient, and it easily runs into the millions. so the performance is quite important.

(`juice` uses `cheerio` which is faster).

With `juice` (and other slower implementations), an extra step of 
1. Parsing the HTML string (O(kN)))
2. Tree search through the DOM for each CSS class (O(N + M), N being the number of nodes, assuming the number of classes M is 1:1 to the number of nodes, and is already indexed so the search is fast. 

Now with `styled-components`, you
1. First can just by-pass the parsing
2. Can make a lot of assumptions in the CSS inlining. 
   - For example all classes are local. <= this gets rid of the `M` in the O(MN) inlining step.
3. The use already existing `RenderToHTML`.

Any suggestion in how to do this would be greatly appreciated! Otherwise I will come back to this later. Thanks for the great work on `styled-components`!

**Comment by philpl** [comment]
@episodeyang you can probably import all the constructors that we’re using and replace ComponentStyle with something like InlineStyle that is using our original stylis logic to object the css string into the style prop but disallows rules. That should be sufficient ?

**Comment by episodeyang** [comment]
Oh I see, does this work for nested selectors like child selectors? 🤔

**Comment by philpl** [comment]
@episodeyang Unfortunately that's not how the style attribute works. Since it can't inject **any** rules, we can't provide any functionality like this anyway.

Maybe at this point you'd like to consider a simpler solution? You can't use nested rules, pseudo selectors, child selectors, or even dynamic CSS (via interpolations in our case)

If you'd like to keep the best practices of styled-components, maybe it's wiser to just write a simple wrapper around the `style` prop? In fact, let me see what I can do.

**Comment by episodeyang** [comment]
Let's break this down:
- **pseudo selectors**: this is either not supported in email clients, or needed but can just be attached to the component themselves.
- **nested rules**: this is needed, but best done by Juice in fact, now thinking about it.
- **child selectors**: this is also needed, but best done by Cheerio. 
    
    Apparently, besides inlining CSS for each component, you need to query all applicable children nodes to inline. To apply the styles inline, we need to clone the child components. This feels very dirty.
- **dynamic CSS**: this is just javascript, can just be handled the current way.

I completely agree with you, that this doesn't look like something `styled-component` could do easily! Thanks for your time! Hopefully, this discussion would be helpful for the future when this question is raised again.

**Comment by acro5piano** [comment]
I managed to be able to render React component + styled-components to static template with inline-css.

For anyone who is looking for server-side email rendering, take a look at the following file.

https://github.com/acro5piano/react-emailify/blob/master/src/index.tsx

Hope this helps.

**Comment by ImedAdel** [comment]
For anyone coming from the future, [styled-email-components](https://github.com/sbekrin/styled-email-components) is a good solution.

**Comment by PopTudor** [comment]
> For anyone coming from the future, [styled-email-components](https://github.com/sbekrin/styled-email-components) is a good solution.

would use it but it needs some upgrading :(
