### ISSUE TITLE
font weight does not work on react-native ios

### ISSUE THREAD

**Issue by vonovak** [styled-components/styled-components#1125]
## Steps to reproduce
```
export const Component = styled.Text`
  font-size: 16px;
  letter-spacing: -0.4px;
  text-align: left;
  color: #435569;
  font-weight: 600;
`;
```
## Expected Behavior

font-weight works

## Actual Behavior

font-weight is ignored on ios, works on android

when using RN's stylesheet, it works on ios too

**Comment by mxstbr** [comment]
As long as a font of that weight is included it should definitely work. You likely don't have the font in weight 600 on iOS!

/cc @jacobp100 for good measure.

**Comment by vonovak** [comment]
sorry, you're right, it was the font
