### ISSUE TITLE
Excessive warnings while running tests

### ISSUE THREAD

**Issue by bkazi** [styled-components/styled-components#1127]
Running the tests locally results in a lot of warnings since React has recently moved the test utils and renderers to different libraries. This add unnecessary noise while debugging the tests.

Can be fixed as referenced [here](https://github.com/airbnb/enzyme/issues/968#issuecomment-310996577), by removing `react-addons-test-utils` as a a dependency and adding `react-test-renderer` instead

**Comment by mxstbr** [comment]
PRs very welcome!
