### ISSUE TITLE
Markdown link incorrectly formatted in documentation

### ISSUE THREAD

**Issue by danoc** [styled-components/styled-components#1128]
## Version
2.1.2

## Reproduction
1. Visit: https://www.styled-components.com/docs/api#withcomponent
2. See that `(Extending Styles)[/docs/basics#extending-styles]` is not rendered as a link.

![image](https://user-images.githubusercontent.com/916038/29851262-085c7392-8ce8-11e7-8360-9308f134c53e.png)

**Comment by philpl** [comment]
Good spot! Thanks for reporting :smile:

In the future btw, there's a separate repo for the website where you can report these: https://github.com/styled-components/styled-components-website

**Comment by philpl** [comment]
I've got a fix in place for it: https://github.com/styled-components/styled-components-website/pull/98
