### ISSUE TITLE
No vendor prefixing when there is a space before a colon

### ISSUE THREAD

**Issue by craigdallimore** [styled-components/styled-components#1129]
## Version
2.1.2

## Reproduction

https://www.webpackbin.com/bins/-KslbnNurc9fc65tePBR

## Steps to reproduce

Use a `display : flex` instead of `display: flex`

## Expected Behavior

Having a space before a colon would not influence vendor prefixing

## Actual Behavior

A space before a colon prevents vendor prefixing from being applied

**Comment by craigdallimore** [comment]
This is possibly a documentation thing - if the rule is "don't have a space" that would be good to know, if it's in the documentation I'm afraid I did not see it. (I can see that all examples have the "no-space" style)

**Comment by k15a** [comment]
@thysultan

**Comment by thysultan** [comment]
Patched in stylis 3.2.14.

**Comment by craigdallimore** [comment]
Incredible, thanks very much!
