### ISSUE TITLE
[Started] Webstorm / IntelliJ Language Support Plugin 

### ISSUE THREAD

**Issue by daedlock** [styled-components/styled-components#1131]
As discussed on parent issue https://github.com/styled-components/styled-components/issues/176. I have started working on the plugin and I am more than half-way through.

Here is the repo:
https://github.com/daedlock/styled-components-webstorm-syntax

Please re-open the old issue so that I can accept suggestions from users & contributors

**Comment by mxstbr** [comment]
Posted over there to notify the folks, also submitted a couple issues in the repo. Awesome work so far!

**Comment by daedlock** [comment]
@mxstbr thanks! will respond to the issues shortly
