### ISSUE TITLE
Does the PR for syntax supporting in babel-sublime already merged? I still not seeing in SublimeText.

### ISSUE THREAD

**Issue by jaggerwang** [styled-components/styled-components#1133]
The [PR](https://github.com/babel/babel-sublime/pull/289) is already merged. I'm using the latest SublimeText3 with latest babel-sublime plugin, but still cannot seeing the syntax highlight.
![image](https://user-images.githubusercontent.com/1255011/29911364-342a27a2-8e60-11e7-8779-f0dfc5b6bd96.png)

## Version
2.1.2

## Reproduction

Using the latest SublimeText3 with plugin bable-sublime.

## Expected Behavior

Syntax highlighted.

## Actual Behavior

Syntax not highlighted.

**Comment by mxstbr** [comment]
I don't think so :cry: @zertosh it'd be great to finally get that released!!
