### ISSUE TITLE
Refer to same component

### ISSUE THREAD

**Issue by hmontes** [styled-components/styled-components#1134]
Hi

I need to do this.
```
.comment-wrap {
		padding: 36px 16px 0 104px;
		position: relative;
		
		.comment-wrap {
			padding: 0 0 0 88px;
			
			&.comment-reply {
				padding: 0 0 0 88px;
				margin-top: 28px;
			}
		}	
}			

```

My question is: How can i do that with Styled components?

I tried.
```
const CommentWrap = styled.div`
 padding: 36px 16px 0 104px;
 position: relative;
  ${this} {
    padding: 0 0 0 88px;
  } 

`
```
But doesn't work. The padding 36px 16px 0 104px is in ALL the divs with CommentWrap components. Not only in the Children.

Thanks

**Comment by mxstbr** [comment]
With an ampersand! `&`

```JS
const CommentWrap = styled.div`
 padding: 36px 16px 0 104px;
 position: relative;
 & {
    padding: 0 0 0 88px;
  } 
`
```

**Comment by hmontes** [comment]
Your solution don't worked (Affects ALL the divs. not only the children). But thanks to your post i found the solution: Is with TWO ampersand.

```
const CommentWrap = styled.div`
 padding: 36px 16px 0 104px;
 position: relative;
 & & {
    padding: 0 0 0 88px;
  } 
`
```

I think is not the ideal but works.

Thank you

**Comment by philpl** [comment]
cc @thysultan Is there anything we can do to avoid this un-contextual behaviour of the ampersand selector? I know we can talk about that for v3, but to kind of talk about this right now:

Based on the feedback above that means that this resolves to the same selector still, right?

```
& {
  & {
  }
}
```

**Comment by hmontes** [comment]
Sorry. My mistake. That solution don't work

**Comment by thysultan** [comment]
@philpl Yes?

**Comment by philpl** [comment]
@hmontes Yes cheers, aware of that :)

@thysultan I think this might not match the spec, or does it?

**Comment by thysultan** [comment]
SASS spec or CSS spec?
