### ISSUE TITLE
Some issues preventing thorough minification

### ISSUE THREAD

**Issue by probablyup** [styled-components/styled-components#1135]
1. There are some instances of `typeof process !== 'undefined'` in the codebase which will defeat DCE in some build tools like webpack. By default, webpack only replaces `process.env.NODE_ENV` in production mode (`-p`) and would not touch a naked use of `process`.

2. `process.env.NODE_ENV` is being replaced by rollup for non-minified builds (e.g. `dist/styled-components.es.js`) which then does not allow webpack to replace it downstream properly and for uglify to DCE it due to the resulting invalid comparison (`"production" !== "production"`)

https://github.com/styled-components/styled-components/blob/master/rollup.config.js#L50-L52

An example of the output in `dist/styled-components.es.js`:

```
var warnTooManyClasses = void 0;
    if (typeof process !== 'undefined' && "development" !== 'production') {
      warnTooManyClasses = createWarnTooManyClasses(displayName);
    }
```

Recommendations:

1. Remove usage of `typeof process !== 'undefined'`
1. Only run the replace plugin on the minified build

**Comment by mxstbr** [comment]
PRs very welcome! :blush:

**Comment by philpl** [comment]
Yep, I’ve noticed that as well. I’m not sure if rollup replaces this for us already? Whoever likes to pick this up will need to check unfortunately :)

**Comment by rossipedia** [comment]
Unfortunately, this breaks usage of the development (non es-modules) version in the browser via unpkg, as it still contains references to `process.env.NODE_ENV`: https://unpkg.com/styled-components@2.2.1/dist/styled-components.js 

Perhaps `process.env.NODE_ENV` should only be left alone in the `ESBUNDLE` build?

**Comment by mxstbr** [comment]
Great catch @rossipedia, but don't you mean the UMD bundle? A PR to minify that would be much appreciated!

**Comment by rossipedia** [comment]
To clarify, yes: the UMD bundles should have `process.env` replaced out with `"development"` or `"production"`. I'll go ahead and get to work on the PR :)
