### ISSUE TITLE
shouldComponentUpdate isn't called when wrapping React components with styled-components

### ISSUE THREAD

**Issue by searene** [styled-components/styled-components#1140]
I have three files, `App.js`, `InputContainer.js` and `index.js`

# App.js
```javascript
import React, { Component } from 'react';
import InputContainer from './InputContainer';
import styled from 'styled-components';

class App extends Component {
  constructor() {
    super();
    this.state = {
      count: 0
    }
  }
  render() {
    const StyledInputContainer = styled(InputContainer)`
    `
    return (
      <div>
        <StyledInputContainer placeholder={this.props.placeholder} />
        <button onClick={this.increaseCount.bind(this)}>{this.state.count}</button>
      </div>
    );
  }
  increaseCount() {
    this.setState(prevState => ({
      count: prevState.count + 1
    }))
  }
}

export default App;
```

# InputContainer.js
```javascript
import React, { Component } from 'react';

class InputContainer extends Component {
  shouldComponentUpdate() {
    console.log("calling shouldComponentUpdate");
    return false;
  }
  render() {
    console.log('render InputContainer');
    return (
      <input type="text" id="editor" placeholder={this.props.placeholder} />
    );
  }
}

export default InputContainer;
```

# index.js
```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import registerServiceWorker from './registerServiceWorker';

ReactDOM.render(<App />, document.getElementById('root'));
registerServiceWorker();
```

# interface
![2017-09-03-123752_380x51_scrot](https://user-images.githubusercontent.com/3351317/30000591-e176188a-90a4-11e7-8c87-5deaa697b1d4.png)

# Expected behavior
When I click on the button, only one line will be appended in the console:

```
calling shouldComponentUpdate
```

Because `shouldComponentUpdate()` returns false, so `render InputContainer` won't be output.

![2017-09-03-124410_416x69_scrot](https://user-images.githubusercontent.com/3351317/30000626-bd97d2fe-90a5-11e7-83db-94c8eb480bd1.png)

# Actual Behavior

`shouldComponentUpdate()` wasn't called, and `render InputContainer` was appended to the console.

![2017-09-03-124502_283x89_scrot](https://user-images.githubusercontent.com/3351317/30000635-dbc1f1ec-90a5-11e7-8b10-db40a000d624.png)

# Why is it a styled-component issue?

Because if I don't use `styled-components`, i.e. if I change this line

```javascript
<StyledInputContainer placeholder={this.props.placeholder} />
```

to

```javascript
<InputContainer placeholder={this.props.placeholder} />
```

it will show the expected behavior, `calling shouldComponentUpdate` will be appended to the console and `InputContainer` will not be rendered.

Is it a bug?

**Comment by philpl** [comment]
You're dynamically creating a StyledComponent here:

```js
  render() {
    // !
    const StyledInputContainer = styled(InputContainer)`
    `
    return (
      <div>
        <StyledInputContainer placeholder={this.props.placeholder} />
        <button onClick={this.increaseCount.bind(this)}>{this.state.count}</button>
      </div>
    );
  }
```

As with every component, you are recreating the type of an element, forcing it to be of a different type on every rerender. Not only is this really expensive as React throws away that part of the subtree, but it also causes the behaviour you are experiencing as that component is never the same in two rerenders.

styled-components creates components. If you adhere to the examples on the homepage and keep them static, they will behave as you expect them to. They're not like your usual css-in-js tool that creates rules/classes :wink:

Just to be sure I'll link you to the docs/basics section here: https://www.styled-components.com/docs/basics

There is an open issue for a new section in FAQ that clears things up: https://github.com/styled-components/styled-components-website/issues/75

**Comment by mxstbr** [comment]
Boom, now it works!

```JS
const StyledInputContainer = styled(InputContainer)`
`

  render() {
    return (
      <div>
        <StyledInputContainer placeholder={this.props.placeholder} />
        <button onClick={this.increaseCount.bind(this)}>{this.state.count}</button>
      </div>
    );
  }
```

**Comment by searene** [comment]
@philpl @mxstbr Thanks, now it works!
