### ISSUE TITLE
Class attachment is failing 

### ISSUE THREAD

**Issue by yordis** [styled-components/styled-components#1141]
## Version
2.1.0

## Reproduction
https://codesandbox.io/s/3y3wl59x1p

## Steps to reproduce
- Extend the Original logo to another version

## Expected Behavior
I expect the `AlternativeLogo` to apply the styles added
## Actual Behavior
The `AlternativeLogo` do not have the styles.

The classes is been created with the values if I am not mistaking but the class is not been attached to the element

**Comment by morajabi** [comment]
You need to transfer the rest of props (or just the `className`) to the wrapper in the `Original` component in order to extending works. like this:

```

const Original = ({
  size = "40px",
  color = "#e0b14c",
  ringColor = "#e0b14c",
  ...props
}) => {
  return (
    <Logo {...props} color={color} size={size} viewBox="0 0 213.8593 193.2121">
      <Ring
        color={ringColor}
        d="M26.7993,40.7841a94.2814,94.2814,0,0,1,145.5239-7.8466,95.1339,95.1339,0,0,1,21.3211,38.4335.8185.8185,0,0,0,1.5773-.4343A95.9289,95.9289,0,0,0,62.6415,9.47,97.2161,97.2161,0,0,0,25.3873,39.9591c-.6269.845.79,1.6627,1.412.825"
      />
      <Ring
        color={ringColor}
     d="M195.6343,112.9941A94.2667,94.2667,0,0,1,51.019,175.3764,95.583,95.583,0,0,1,16.8359,135.36c-.438-.954-1.8481-.1254-1.412.8268C29.0764,165.94,57.4209,187.27,89.94,191.6257a95.9419,95.9419,0,0,0,107.2721-78.1972c.1871-1.0285-1.39-1.47-1.5773-.4343"
      />
    </Logo>
  );
};
```

**Comment by yordis** [comment]
@morajabi aahh I see what you are doing there 👍 Got it!

Thanks a lot for the help!
