### ISSUE TITLE
Cannot share Styled Components between components (SSR, Production Build Only)

### ISSUE THREAD

**Issue by tsupol** [styled-components/styled-components#1145]
## Version
2.1.2
babel-plugin-styled-components: 1.2.0

## Steps to reproduce
in Heading.js
```
import styled from 'styled-components'

export const Heading1 = styled.div`
  display: inline-block;
  font-size: 3rem;
`
```
in index.js
```
import { Heading1 } from './Heading'
- use heading somewhere in jsx -
```

## Expected Behavior
no error in production

## Actual Behavior
produces the following error
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `t`
```
(Minified React error 130;)

## More Details
Used with next.js@3.2.1, react@15.5.4
Styled Component in the same file works normally
No error or warning in development mode

**Comment by tsupol** [comment]
The issue seem to be caused by the mixing of various plugins not the fault of Styled Component itself.
Sorry for posting this.

**Comment by mxstbr** [comment]
No worries, happy that you've figured it out!
