### ISSUE TITLE
Styled-components together with Material-UI and Next.js

### ISSUE THREAD

**Issue by dmt-13** [styled-components/styled-components#1146]
Hi. I'm trying to use styled-components together with Material-UI. Also I'm using Next.js for server rendering. I used your documentation and now styled-components are rendered fine on the server side. But I have some difficulties with server-side rendering for Material-UI. It uses JSS and react-jss package, the last one has class `SheetsRegistry`, which collects critical CSS and renders it on the server side. I'm wonder if styled-components have something similar? I'm using `getStyleElement` method, but it collects styled-components styles only, so Material-UI styles are not rendered. Do you have any ideas how I can implement it? Thanks in advance.

**Comment by morajabi** [comment]
Doesn't this help you with SSR on Next.js?
It's an example for Next with Styled Components:
https://github.com/zeit/next.js/tree/master/examples/with-styled-components

**Comment by dmt-13** [comment]
@morajabi Not actually. As I wrote, styled-components works nicely, I have a problem with Material-UI. It is not rendered on the server-side and `getStyleElement` doesn't grab it's styles.

**Comment by mxstbr** [comment]
I would suggest asking this question [over in the material-ui repo](https://github.com/callemall/material-ui) or on StackOverflow, you'll have better luck there finding folks who know how to server-side render it!

**Comment by FMcIntosh** [comment]
I had the same issue, but solved it by using the material-ui example code, and then adding the styled-components specific part - the opposite way to how you did it.  Here is what my _document.js looks like:
`import React from 'react';
import Document, { Head, Main, NextScript } from 'next/document';
import JssProvider from 'react-jss/lib/JssProvider';
import getContext from 'styles/getContext';

class MyDocument extends Document {
  render() {
    return (
      <html lang="en" dir="ltr">
        <Head>
          <title>My page</title>
          <meta charSet="utf-8" />
          {/* Use minimum-scale=1 to enable GPU rasterization */}
          <meta
            name="viewport"
            content={
              'user-scalable=0, initial-scale=1, ' +
              'minimum-scale=1, width=device-width, height=device-height'
            }
          />
          {/*
            manifest.json provides metadata used when your web app is added to the
            homescreen on Android. See https://developers.google.com/web/fundamentals/engage-and-retain/web-app-manifest/
          */}
          <link rel="manifest" href="/static/manifest.json" />
          {/* PWA primary color */}
          <meta name="theme-color" content={this.props.stylesContext.theme.palette.primary[500]} />       
          <link
            rel="stylesheet"
            href="https://fonts.googleapis.com/css?family=Roboto:300,400,500"
          />
          <style>{`
            body, html { 
                width: 100%;
                margin: 0;
                font-family: Roboto, sans-serif;
            }
            `}
            </style>
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    );
  }
}

MyDocument.getInitialProps = ctx => {
  // Resolution order
  //
  // On the server:
  // 1. page.getInitialProps
  // 2. document.getInitialProps
  // 3. page.render
  // 4. document.render
  //
  // On the server with error:
  // 2. document.getInitialProps
  // 3. page.render
  // 4. document.render
  //
  // On the client
  // 1. page.getInitialProps
  // 3. page.render

  // Get the context to collected side effects.
  const context = getContext();
  const page = ctx.renderPage(Component => props => (
    <JssProvider registry={context.sheetsRegistry} jss={context.jss}>
      <Component {...props} />
    </JssProvider>
  ));

  return {
    ...page,
    stylesContext: context,
    styles: (
      <style
        id="jss-server-side"
        // eslint-disable-next-line react/no-danger
        dangerouslySetInnerHTML={{ __html: context.sheetsRegistry.toString() }}
      />
    ),
  };
};

export default MyDocument;`

Hope this helps!

**Comment by oliviertassinari** [comment]
styled-components interoperability with Material-UI is documented under this page: https://material-ui-next.com/guides/interoperability/#styled-components.

**Comment by kitten** [comment]
@nmpatzios open an issue with an actual reproduction please. Don't just comment on closed / stale issues. I'm sorry if this sounds rude, but I tend to write these messages ten times a week

Please investigate this in detail yourself first to see whether it might be more suited for an issue on Material UI. It's most likely a usage issue and not a bug.

**Comment by oliviertassinari** [comment]
@nmpatzios The mismatch seems to be with the styled-components classNames:
- Server: "MuiButtonBase-root-47 MuiButton-root-86 sc-VigVT iwjLMD"
- Client: "MuiButtonBase-root-47 MuiButton-root-86 sc-bwzfXH cHkGGL"

**Comment by kitten** [comment]
@oliviertassinari @nmpatzios true, please take a look at our babel plugin for ssr debugging: https://www.styled-components.com/docs/tooling#serverside-rendering

I'll lock this issue btw, as it probably won't make sense to further answer questions here :wink:
