### ISSUE TITLE
How can I add a third party library (like normalize) to my project?

### ISSUE THREAD

**Issue by jmmolina796** [styled-components/styled-components#1152]
I want to add a third party library such as normalize, Does it exist a way to do it with styled-components? Or Do I have to import it like whatever file?
`import 'normalize.css'`

**Comment by mxstbr** [comment]
Use `injectGlobal`! See https://www.styled-components.com/docs/api for more information.

**Comment by jmmolina796** [comment]
Thank you!
At the end I did this:
```
import { injectGlobal } from 'styled-components';
import styledNormalize from 'styled-normalize';

const baseStyles = () => injectGlobal`
  ${styledNormalize}

  body {
	 background-color: #EEE;
	}
`;
```
