### ISSUE TITLE
styled-props demo link in readme section has gone

### ISSUE THREAD

**Issue by nb256** [styled-components/styled-components#1154]
styled-props (demo) link should be fixed since it does not work.

http://www.webpackbin.com/N1EKUqgvG

> The reason you see this page is that the route is invalid. You have probably clicked an old Webpackbin link. Please notify the author about moving their BIN to the new version of Webpackbin. In the meantime you can continue to the old version.

**Comment by diegohaz** [comment]
cc @RafalFilipek

**Comment by diegohaz** [comment]
Closed in #1157
