### ISSUE TITLE
The final HTML DOM should not have any props from JSX Wrapper except with using `attrs`

### ISSUE THREAD

**Issue by wood1986** [styled-components/styled-components#1155]
## Version
2.1.0

## Reproduction

https://www.webpackbin.com/bins/-KtVOP6OYjAfjyqgdtrs
![untitled](https://user-images.githubusercontent.com/5212215/30201057-3b2648be-942e-11e7-8f45-f47475e1facc.png)

## Steps to reproduce
See my screenshot and https://www.webpackbin.com/bins/-KtVOP6OYjAfjyqgdtrs

## Expected Behavior
`<section data-react-root class="sc-bwzfXH gzMTbA">`

## Actual Behavior
`<section data-reactroot height="300" width="300" dir="rtl" class="sc-bwzfXH gzMTbA">`

**Comment by mxstbr** [comment]
This is expected behaviour, we maintain a whitelist of valid DOM attributes and pass them through.

----

@geelen this would be an interesting solution to the whitelist problem? Did you consider removing the whitelist and only passing through props from `.attrs`?

**Comment by wood1986** [comment]
Based on the question you ask @geelen, I want to know if you think it is nice to have this behavior. If so, I am going to fix that. My point is I think `height="300" width="300" dir="rtl"` should come from the attrs only. And I am concerned about the priority of attrs and the props from the Wrapper

**Comment by mxstbr** [comment]
The idea behind the whitelist is that's it's a much nicer DX, see #731 and all the linked discussion for the context around the question.
