### ISSUE TITLE
Theme & passed props performance best practice question

### ISSUE THREAD

**Issue by sbrichardson** [styled-components/styled-components#1163]
After reviewing your docs and strategies for building heavily themed/dynamic components

I thought it may be better performance to have the property functions run once, instead of defining a function for each property. This method below also improve using the 'extend' sc method, since that outputs a single stylesheet that has the original properties, as well as duplicates for any over-ridden styles (potentially making a larger stylesheet than needed).

I realize using nested ThemeProviders could work also, passing a function to override certain values, but this can potentially take away the control you get with using props directly. I guess even if this isn't the best way to customize themes based on props, do you think it's more performant potentially to not invoke a new function on each property as in your docs?

**Usage in component:**
```
<Section>I'm a regular section</Section
<Section mode="dark">I'm a dark section</Section>
```

**Updated Styled Component Syntax**
Using ES6 Destructuring for the params to help make properties easier to read. I also separated the dark/light themes into functions to keep the base styles easier to read. Only 2 functions run with this technique.
```
import styled from 'styled-components'

const theme = {
  dark: t => `
    background: ${t.color.dark};
    color: ${t.color.lighter};
    > a {
      color: ${t.color.light};
     
      &:visited {
        color: ${t.color.light};
      }
    }
    input {
      color: ${t.color.dark};
      background: ${t.color.light};
    }
  `,
  light: t => `
    background: ${t.color.lighter}
  `
}

const applyTheme = (mode = 'light', t) => theme[mode](t)

const Section = styled.section`
  ${({theme: t, ...p}) => `
    flex-grow: ${t.section.flexGrow};
    flex-shrink: ${t.section.flexShrink};
    flex-basis: ${t.section.flexBasis};
    padding-top: ${t.section.paddingTop};
    padding-right: ${t.section.paddingRight};
    padding-bottom: ${t.section.paddingBottom};
    padding-left: ${t.section.paddingLeft};
    ${applyTheme(p.mode, t)}
  `}
`

export { Section }

```

**Alternate Dynamic Method**
The component type is available within 'this.a.target' when using 'styled.section' etc So you could do the below to read from a theme file based on the target, without declaring each time. Another benefit is that you could add/remove properties to the theme file without having to update the styled component code.

assuming the theme object looks like:
```
// theme file object

const colors = {
  primary: '#ffdb03',
  secondary: 'hsla(230, 91%, 61%, 1)',
  secondaryFocus: 'hsla(230, 88%, 57%, 1)',
  secondaryActive: 'hsla(230, 84%, 52%, 1)',
  normal: '#31393C',
  dark: '#31393C',
  disabled: '#5d6262',
  disabledBg: '#e0e0e0',
  light: '#ffffff',
  lighter: '#fafafa'
}

{
  section: {
   base: {
      'color': colors.normal,
      'font-weight': 300,
      'font-size': '1em',
      'padding-top': '.5em',
      'padding-bottom': '.5em',
      'padding-left': '.5em',
      'padding-right': '.5em',
      'margin-top': '1.14em',
      'margin-bottom': '1.14em',
      'margin-left': '0em',
      'margin-right': '2.25em',
      'background': 'inherit',
      'border-width': '0.0625em',
      'border-style': 'solid',
      'border-radius': '0px',
      'width': '14em'  
    },
    states: {
      focus: {
        'outline-style': 'solid',
        'outline-color': colors.secondary,
        'outline-width': '0.125em',
      },
      disabled: {
        'cursor': 'not-allowed',
        'border-color': colors.disabled,
        'color': colors.disabled,
        'background-color': colors.disabledBg
      }
    }
  },
  input: {
    // etc
  },
  button: {
    // etc
  }
}

```
You could: 

```
import { each } from 'lodash'
import styled from 'styled-components'

// this.a.target would be 'section'

const makeProps = (obj) => {
  let css = ``
  each(obj, (val, key) => {
    css += `${key}: ${val};`
  })
  return css
}

const applyBaseTheme = (t) => {
  let css = makeProps(t.base)
  if (t.states) {
    each(t.states, (val, key) => {
      css += `&:${key} {${makeProps(val)}}`
    })
  }
  return css
}

const Section = styled.section`
  ${p => `
    ${applyBaseTheme(p.theme[this.a.target])}
  `}
`

export { Section }

```

**Old / Current Method**
 13 functions have to run, and the conditional syntax gets harder to write as you add different variations (dark/normal/alternate etc)

**Syntax Using Existing Extend Method**
Lose ability to use a basic prop to switch theme, also the overridden properties will be duplicated, creating a larger stylesheet. Also means you have to import more components where used in other files.

**Comment by sbr464** [comment]
I also tested the performance of caching identical styles. By default, each time you use an instance of a styled component, all of the theme functions are re-ran. The them file doesn't need to be regenerated over and over for identical unique classes, just for the variations. 

Not really a typical use case but I was curious if it would help, I rendered 10,000 elements on a page in a loop (lodash.times(1000) and timed the difference using window.performance.now(). You can see that their isn't a huge difference, I'm using a pretty simple dynamic theme, but the cached times are lower and more consistent.

**Un-Cached Times - 10k nodes**
Call to gen inputs took 184.08499999999992 milliseconds.
Call to gen inputs took 169.13500000000005 milliseconds.
Call to gen inputs took 155.57 milliseconds.
Call to gen inputs took 146.10999999999996 milliseconds.
Call to gen inputs took 186.89999999999998 milliseconds.
Call to gen inputs took 200.15000000000003 milliseconds.
Call to gen inputs took 192.14499999999998 milliseconds.
Call to gen inputs took 175.51999999999998 milliseconds.
Call to gen inputs took 169.58999999999997 milliseconds.
Call to gen inputs took 192.04999999999995 milliseconds.
Call to gen inputs took 194.23000000000008 milliseconds.
Call to gen inputs took 179.79000000000002 milliseconds.
Call to gen inputs took 156.14499999999998 milliseconds.
Call to gen inputs took 392.6300000000001 milliseconds.
Call to gen inputs took 204.56999999999994 milliseconds.
Call to gen inputs took 192.47000000000003 milliseconds.
Call to gen inputs took 730.065 milliseconds.
Call to gen inputs took 382.30499999999995 milliseconds.



**Cached Times - 10k nodes**

Call to gen inputs took 132.825 milliseconds.
Call to gen inputs took 132.41999999999996 milliseconds.
Call to gen inputs took 187.04500000000007 milliseconds.
Call to gen inputs took 156.75000000000006 milliseconds.
Call to gen inputs took 154.075 milliseconds.
Call to gen inputs took 169.8850000000001 milliseconds.
Call to gen inputs took 134.44999999999993 milliseconds.
Call to gen inputs took 123.45500000000004 milliseconds.
Call to gen inputs took 125.37 milliseconds.
Call to gen inputs took 133.52999999999997 milliseconds.
Call to gen inputs took 135.88500000000022 milliseconds.
Call to gen inputs took 122.01999999999998 milliseconds.
Call to gen inputs took 164.61500000000012 milliseconds.
Call to gen inputs took 128.91500000000008 milliseconds.
Call to gen inputs took 142.93499999999995 milliseconds.
Call to gen inputs took 155.2 milliseconds.
