### ISSUE TITLE
Identifier (e.g. className) uglifying or hashing

### ISSUE THREAD

**Issue by enginehenryed** [styled-components/styled-components#1165]
This may be either a question or a feature request.
I used to develop React application with Webpack, and one of the most useful gimmicks of Webpack was its `css-loader`'s `localIdentName`. What [localIdentName](https://github.com/webpack-contrib/css-loader#modules) does was to give the reference to the css selector with a hashed name.

For example, if there is a style definition as following,
```css
.foo {
  color: blue;
}
```
I could reference `foo` in my JavaScript file, but the name could be hashed or 'uglified' as in `12lk1j`.
```javascript
var styles = require('./file.css');
styles.foo // 12lk1j
```

I now use `styled-components`, refraining from defining styles in external `css` files. I, however, still need the feature (uglified css identifier) and currently have to define my own custom function (css name resolver) to make it happen. But I'm asking, would there be any chance you add this functionality (in whatever way) into the library? Or is there anyone in a similar situation who uses his own tricks?

**Comment by k15a** [comment]
Could you clarify a bit more? Our classes are normally hashed and so exactly what you want?

**Comment by mxstbr** [comment]
I also don't understand this question. If you want human readable names, use https://github.com/styled-components/babel-plugin-styled-components!

If you don't want human readable names, then don't use it.

**Comment by enginehenryed** [comment]
The issue is closed but I late explain what I have asked, just to make it clear.
I was trying to do something like this.
```css
styled.div`
   // someStyle
   .child {
      display: inline-block;
   }
   .child2 {
      display: block;
   }
`
```

So when writing render(), for example, I don't have to wrap all the html elements with `styled-component`.
```javascript
return (
  <StyledParent>
     <div className='child1'>
        ...
     </div>
     <div className='child2'>
        ...
     </div>
  </StyledParent>
)
```
When I used `css-loader` in a similar situation, the names of selectors `child1`, `child2` could be hashed if I wanted. I particularly liked the feature with regards to security, since I could intentionally remove semantic information about the html elements. `styled-components` do also hash the classnames but not what is written inside the template literal. 

However, I realized that I'd better use this library while having possibly every html element that I would like to style wrapped with styled-component (especially if I would like to hash all those elements). At least it is what I understand. It just took some time for me to get used to it. (If I'm wrong here, I'm glad to be corrected)

**Comment by k15a** [comment]
The correct usage of styled-components in your example would be:

```js
const Parent = styled.div`
     // styles
`

const Child1 = styled.div`
    display: inline-block;
`;

const Child2 = styled.div`
    display: block;
`

const Comp = () => (
    <Parent>
        <Child1>
               ...
        </Child1>
        <Child2>
               ...
        </Child2>
    <Parent>
)
```

If I understand you correctly that's the thing you are moving to which is good :)

**Comment by ngocongtuan** [comment]
I want to know what condition className is hashed based on(the first className). can someone help me?
