### ISSUE TITLE
Input elements get re-rendered in DOM when contained in styled components

### ISSUE THREAD

**Issue by coopermaruyama** [styled-components/styled-components#1166]
## Version
2.1.2

## Reproduction

https://www.webpackbin.com/bins/-Ku1w7qFoN6MVobreB-a

## Steps to reproduce

1. Create a styled component
2. Put a controlled text input in it
3. type into the text input

## Expected Behavior
input should not lose focus

## Actual Behavior
Input loses focus

This is due to the fact that a styled components re-renders completely, so it removes then adds a new text input to the DOM, which causes it to lose focus. This also happens on any react element where the root element in it is a styled component. Because of this, I always need to use inline styles and avoid styled components for my root elements to avoid this problem.

**Comment by epilande** [comment]
@coopermaruyama having the styled component in the `render` function causes it to re-render. Your `Container` styled component gets dynamically created on every render.

Updated example: https://www.webpackbin.com/bins/-Ku224IKqB3pQVsdsx9d

**Comment by coopermaruyama** [comment]
ahhh okay. Thats very interesting. thanks for pointing this out, I was really scratching my head over this one. Will close this now.

**Comment by webmobiles** [comment]
how i can render if my component is outside render, and attributs changed accord props?

**Comment by epilande** [comment]
@webmobiles pass the attributes as props to the styled-component.

```jsx
const Container = styled.div`
  margin: 10px 0;
  width: ${props => props.size};
`;
```

**Comment by webmobiles** [comment]
nice, thanks
