### ISSUE TITLE
Generating optimal payloads

### ISSUE THREAD

**Issue by probablyup** [styled-components/styled-components#1169]
I came across this stylis-plugin today: https://www.npmjs.com/package/stylis-atomic

Not used much, but it brings up an interesting train of thought on strategies that libraries like styled-components can harness to dramatically slim the amount of CSS pushed to the client. 

Curious if a technique like this is on the roadmap? Or perhaps even just trying out this plugin. 

It seems like it would be safe within the same injection, but not across injections. The secret sauce would be figuring out how to preserve what was already generated from previous stylis invocations and carry it forward to the next compilation pass.

**Comment by k15a** [comment]
We already had a discussion about this at https://github.com/styled-components/styled-components/issues/351. You might want to check it out.

**Comment by mxstbr** [comment]
Going to close this as a duplicate, didn't know about that @thysultan plugin though!
