### ISSUE TITLE
linear-gradient support for React Native

### ISSUE THREAD

**Issue by anthify** [styled-components/styled-components#1170]
Hey,

There seems to be no support for gradients.

Example:
```javascript
const Front = styled.View`
   background: linear-gradient(45deg, #1D3475, #060D1F);
`;
```

returns `Failed to parse declaration "background...`

I see this is a feature React Native itself lacks, and have found some libraries that provide this functionality, but it would be cool to have access to it via styled-components.

Any ideas on how it could be implemented?

Anth

PS _*loving styled-components*_

**Comment by jacobp100** [comment]
So I think there is some sort of native support React Native [here](https://github.com/facebook/react-native/blob/master/Libraries/ART/ReactNativeART.js).

If someone wants to look into this, I help on the CSS parsing side.

**Comment by philpl** [comment]
Afaik that's not actually exposed for styling, otherwise this wouldn't exist, right? ^^ https://github.com/react-native-community/react-native-linear-gradient

Shall we close this for now?

**Comment by jacobp100** [comment]
[There's an example in the React Native examples.](https://github.com/facebook/react-native/blob/master/RNTester/js/ARTExample.js) I think we should leave this open until it's been looked into!

**Comment by mxstbr** [comment]
The linear gradient support is for react-art though? https://github.com/reactjs/react-art That's a drawing tool?

**Comment by jacobp100** [comment]
Yea, but that's implemented in React Native core. I looked into it and we might have something like,

```js
const gradient = styled(ART.Shape)`
  background: linear-gradient(...);
`
```

And this might need to direct properties rather than style properties. Then again, the documentation is sparse, so I could be wrong.

**Comment by mxstbr** [comment]
I don't think there's anything we can do here, I don't really want to support `react-art`. I'd recommend using https://github.com/react-native-community/react-native-linear-gradient!

**Comment by dengwanc** [comment]
Config `react-native-linear-gradient` is UNFRIENDLY. 

const Front = styled.View`
   background: linear-gradient(45deg, #1D3475, #060D1F);
`;

why is better ?

**Comment by Johnba1988** [comment]
@anthify I have the same problem of you , I want to do `linear-gradient(-180deg, #1D3475, #060D1F)` .Please if you found the solution , tell me how you did this , and thanks .

**Comment by anthify** [comment]
@Johnba1988 hey, sorry I'm afraid not. For this project I abandoned gradients :(

**Comment by Johnba1988** [comment]
@anthify  :(  Ok , thank you.

**Comment by fellipesnoww** [comment]
If anyone need use gradients, you can use lib _ react-native-linear-gradient _. For me works well. I found this page explaining how to use https://blog.logrocket.com/understanding-react-native-linear-gradient/.
Hope this works for you. 😊

**Comment by galohernandez** [comment]
If you want to use linear-gradient with styled components in React.js you can use this example:


```
const Circle = styled.div`
  width: 440px;
  height: 440px;
  background: linear-gradient(20deg,#BF953F, #FCF6BA, #B38728, #FBF5B7, #AA771C);
  border-radius: 50%;
`

const OuterCircle = () => {
    return (
        <div>
            <Circle/>
        </div>
    );
};

```
