### ISSUE TITLE
withComponent question

### ISSUE THREAD

**Issue by wagg-matt** [styled-components/styled-components#1172]
I'm working on a project where I have external component repos all built with styled components.

When trying to use `withComponent` internally like below it works as intended:
```
const FunnelTitle = ({ funnelName, style }) => {
  const Container = styled.div`
    display: flex;
    justify-content: flex-start;
  `;

  const Title = styled.h1`
    font-family: Raleway, sans-serif;
    font-size: 28px;
    fontWeight: 600;
    line-height: 1.21em;
    margin: 0;
    text-transform: capitalize;
  `;

  const SubTitle = Title.withComponent('h3');

  return (
    <Container style={style}>
      <Title>
        {funnelName} funnel
      </Title>
      <SubTitle>
        Subtitle me
      </SubTitle>
    </Container>
  );
};
```

Yet when I try to use an external repo, all built with styled-components I get a `_Button2.default.withComponent is not a function` error. With the below code:

```
import Button from '@external/atoms/dist/atoms/Button';

const FunnelTitle = ({ funnelName, style }) => {
  const Container = styled.div`
    display: flex;
    justify-content: flex-start;
  `;

  const Title = styled.h1`
    font-family: Raleway, sans-serif;
    font-size: 28px;
    fontWeight: 600;
    line-height: 1.21em;
    margin: 0;
    text-transform: capitalize;
  `;

  const SubTitle = Button.withComponent('h3');

  return (
    <Container style={style}>
      <Title>
        {funnelName} funnel
      </Title>
      <SubTitle>
        Subtitle me
      </SubTitle>
    </Container>
  );
};
```

Is this the intention or is this a bug? I am using version `2.1.2`.

Thanks

## Version
2.1.2

**Comment by mxstbr** [comment]
First of all, you should move your styled-components definitions out of your render method-otherwise you're creating a new component on every render unnecessarily which could have a large performance impact:

```JS
const Container = styled.div`
    display: flex;
    justify-content: flex-start;
  `;

  const Title = styled.h1`
    font-family: Raleway, sans-serif;
    font-size: 28px;
    fontWeight: 600;
    line-height: 1.21em;
    margin: 0;
    text-transform: capitalize;
  `;

  const SubTitle = Title.withComponent('h3');

const FunnelTitle = ({ funnelName, style }) => {
  return (
    <Container style={style}>
      <Title>
        {funnelName} funnel
      </Title>
      <SubTitle>
        Subtitle me
      </SubTitle>
    </Container>
  );
};
```

Second, it sounds like your external `<Button />` is not a styled component directly. **Only styled-components have a `.withComponent` method**, not normal React components!

If it is a styled component, not a normal React component, then the issue might be that your external component ships with `styled-components` v1.

**Comment by wagg-matt** [comment]
@mxstbr thanks very much

**Comment by mgtitimoli** [comment]
I was just wondering how the name of `withComponent` was choosen...

Wouldn't a name like `copyStyleTo` make more sense?
