### ISSUE TITLE
Reacts low priority warning regarding createClass and props-types

### ISSUE THREAD

**Issue by Chaoste** [styled-components/styled-components#1174]
Hi guys,

I'm getting the following react warnings. Styled-components is the only library I'm using and I already removed those deprecated code styles from my code. Do you still use createClass and PropTypes from the react package? Would be great to remove these warnings :)

Greetings,
Thomas

**Comment by mxstbr** [comment]
PRs to remove any left over usage very welcome! Probably related to #1090?

**Comment by j13l** [comment]
@mxstbr is this still up for grabs? would love to give it a shot.

**Comment by mxstbr** [comment]
I think so? PR to remove any leftovers very welcome!

**Comment by j13l** [comment]
Alright, thanks.

First steps, please bear with me. :)

Is there any documentation on how to get started? I've read CONTRIBUTING.MD, built the dist but not sure what next. 

`npm run dev` links to a broken page in the browser, /ssr.html looks good but still throws `ReferenceError: process is not defined ...`

I know it's normal as process is not available in the browser, but how else should I use the example? How does your dev flow look like?

**Comment by lukebelliveau** [comment]
I took a quick look - seems like the only use of these deprecated things is in the react-primitives dependency. When their [corresponding issue](https://github.com/lelandrichardson/react-primitives/issues/84) is resolved, this should go away.

**Comment by mxstbr** [comment]
Thanks @lukebelliveau, looks good to me!

**Comment by mxstbr** [comment]
@j13l sorry, I totally missed this comment. Usually I develop either with tests or by `npm link`ing styled-components into a local project of mine—that being said we should probably get a better development environment into this repo!
