### ISSUE TITLE
Circular dependencies

### ISSUE THREAD

**Issue by ashleyw** [styled-components/styled-components#1177]
Hi all!

We have a few circular dependencies in our codebase. Normally this isn't an issue but we've found it to be a major headache with styled-components due to how they're declared and extended.

```js
import { WhitePopover } from 'ui';

const PermissionPopover = WhitePopover.extend`
  max-width: initial !important;
  padding: 0 !important;
  min-width: 300px;

  > .popover-content {
    padding: 0 !important;
  }
`;
```

Since the `WhitePopover` component hasn't loaded *yet*, we get this error:
```
Uncaught TypeError: Cannot read property 'extend' of undefined
```

We've solved this issue elsewhere by wrapping the component like this:

```js
import { WhitePopover } from 'ui';

const PermissionPopover = () => {
  const StyledComponent = WhitePopover.extend`
    max-width: initial !important;
    padding: 0 !important;
    min-width: 300px;

    > .popover-content {
      padding: 0 !important;
    }
  `;

  return <StyledComponent {...this.props} />;
};
```

However in this case it causes redux-form to repeatedly initialize and destroy the contained form.

Is there a known workaround for this issue?

Thanks!

**Comment by mxstbr** [comment]
> Is there a known workaround for this issue?

Don't have any circular dependencies. 😜  (use [this webpack plugin](https://www.npmjs.com/package/circular-dependency-plugin) to detect and then remove them)

----

Unfortunately, there's nothing we can do from our side to fix this as this is a webpack thing. See this discussion for more information and maybe submit a new issue over at the webpack repo. https://github.com/webpack/webpack/issues/1788

**Comment by philpl** [comment]
> However in this case it causes redux-form to repeatedly initialize and destroy the contained form.

In case it's not clear, this is not recommended as you're recreating the component on every rerender :wink: So it's more of a bodge than a workaround :smile:

If you can't resolve the circular dependency, then I'd suggest you only create it once, but it's important to eventually fix the circular dependency

**Comment by ashleyw** [comment]
Yeah -- a complete bodge! 🙊

We've ended up with a couple dozen circular dependencies (!!) so I've just hoisted the above example to our UI package. I guess it's more fitting anyway!

Thanks guys!
