### ISSUE TITLE
Add a "how to test" section to documentation

### ISSUE THREAD

**Issue by diegohaz** [styled-components/styled-components#118]
I'm trying to test my components with styles (more or less as this library does [here](https://github.com/styled-components/styled-components/tree/master/src/test)), but I still can't figure out how to do that (for example: if I pass some prop, expect the component to have a margin).

I see that you use the [expectCSSMatches](https://github.com/styled-components/styled-components/blob/master/src/test/utils.js#L23), which uses a [method](https://github.com/threepointone/glamor/blob/master/src/sheet.js#L65) of glamor, but I'm very confused. Can you clarify this for me and maybe add this to docs?

**Comment by stephenkingsley** [comment]
May I ask u some a question first? you ran `npm install` in your project? I think the code after babel transform is hard to test.

**Comment by mxstbr** [comment]
> I see that you use the expectCSSMatches, which uses a method of glamor, but I'm very confused. Can you clarify this for me and maybe add this to docs?

This is testing our _implementation_ of `styled-components`, i.e. if the library works as expected with glamor, I'm pretty sure you can't use this to test your components.

I honestly haven't even done that sort of testing yet, I'm not sure why I would want to. Wouldn't this be much better as a visual regression test?

**Comment by diegohaz** [comment]
@stephenkingsley don't know if I understood you correctly, but I had no problems with that. [Here](https://github.com/diegohaz/arc/blob/master/src/components/atoms/Button/Button.test.js) is an example of what I'm doing.

**Comment by stephenkingsley** [comment]
I will review your code first and then answer your question. I will do it as soon as possible

**Comment by diegohaz** [comment]
@mxstbr 
> Wouldn't this be much better as a visual regression test?

You're right. But as I have a bunch of `${props => props.foo ? 'bar' : 'baz'}` in my styles, I want to cover those lines just to make sure everything is ok.

Currently I'm just [`mount`ing the components with different props](https://github.com/diegohaz/arc/blob/master/src/components/molecules/IconButton/IconButton.test.js#L7-L16), which is sufficient, but would be better to make some assertions on that.

**Comment by mxstbr** [comment]
> You're right. But as I have a bunch of ${props => props.foo ? 'bar' : 'baz'} in my styles, I want to cover those lines just to make sure everything is ok.

Yeah I can see that being valuable!

Right now we don't expose the right things to make that possible. I don't have an idea what that could look like at the moment, but I'll let it sit and maybe I can come up with something. What would your ideal API look like?

**Comment by garetmckinley** [comment]
I also want to +1 this. There's more use cases than just the one listed above as well. There's times when you might have accidentally left an overriding rule in your style that causes your given value to not get rendered.

It's nothing that's stopping me from using `styled-components`, but it is holding me back from submitting a PR to the [electron-react-boilerplate](https://github.com/chentsulin/electron-react-boilerplate). I see you're facing a similar situation with the `react-boilerplate` as well.

I'll put some thought into what would be an idea API for me and throw in my two cents 👌

**Comment by geelen** [comment]
I think this is relevant to #124 actually. Whatever works for server side rendering will also work for testing...

**Comment by threepointone** [comment]
are you up for running something like phantom? that's how I wrote tests for glamor, lets you render real components and check 'computed' styles  https://github.com/threepointone/glamor/blob/master/tests/index.js

**Comment by chmaltsp** [comment]
Would be great to have something like `expectedCSSMatches` to be exposed for testing utilities like the media queries example in Tips and Tricks. Looking forward to #124 being merged!

**Comment by seancurtis** [comment]
+1 for exposing some helpers for testing. I've got prop and theme checking logic in my styles like @diegohaz does. Hard to test them currently.

**Comment by diegohaz** [comment]
@seancurtis I ended doing this for styles I want to test:
```js
import styled, { css } from 'styled-components'
import { font, palette } from 'styled-theme'

export const fontSize = ({ level }) => `${0.75 + (1 * (1 / level))}rem` <------

const styles = css`
  font-family: ${font('primary')};
  font-weight: 500;
  font-size: ${fontSize}; <------
  margin: 0;
  margin-top: 0.85714em;
  margin-bottom: 0.57142em;
  color: ${palette({ grayscale: 0 }, 1)};
`
```

So I can test `fontSize`. I'm quite satisfied with this approach. It's just javascript. No need for libraries.

**Comment by lukebatchelor** [comment]
@diegohaz That only tests that the logic for calculating fontSize works though right? It cant test that anything was actually applied.

You could have a regressions where someone deleted that line (`font-size: ${fontSize}`) for example, and all your tests would still pass.

**Comment by diegohaz** [comment]
@lukebatchelor Yeah, this is true. For my use case, it's ok, I prefer other ways to test applied styles, like browserstack. I just needed a way to unit test more complex logics like that `fontSize` example. But I still see value on unit test applied styles like we do internally. I think it would be great if one could dig into this.

**Comment by garetmckinley** [comment]
@diegohaz that works great for testing small parts, but it doesn't help against style overrides. Also there's been a few times where I've had a missing semicolon after a `${props => ...}` statement which in turn, broke the rules immediately following. It would be great to be able to assert our css rules.

Your 'hacky' solution seems a bit promising though, that's more on the lines of what I'm looking for. But I don't think matching snapshots is ideal.

IMO an assertion API like this would be incredibly valuable

    expect(StyledComponent).toHaveStyle('background-color', '#fff');

It could even be better with regex support (not a necessity)

    expect(StyledComponent).toHaveStyle('background-color', '(#(fff|ffffff)|white)');

Testing nested selectors could also work like

    expect(StyledComponent).selector(':hover').toHaveStyle('color', 'dodgerblue')


A few caveats:

- if the rule immediately preceding a rule does not end in a semicolon, the `toHaveStyle` should fail (unless no rules are preceding it)
- if the rule immediately preceding a selector does not end in a semicolon, the selector should fail to select (unless no rules are preceding it)
- styles that are overridden should not match (in the above examples, it should fetch all instances of `background-color`, but only match the rules against the topmost rule.

**Comment by MicheleBertoli** [comment]
I had and idea and some free time so I built this:
https://github.com/MicheleBertoli/jest-styled-components

I'm still not sure how useful it is, but it could be a starting point :)
Feedback are welcome.

**Comment by diegohaz** [comment]
Amazing job, @MicheleBertoli. It's very similar to what I've thought on https://github.com/styled-components/styled-components/issues/118#issuecomment-275585268

Will try that soon.

**Comment by mahcloud** [comment]
👍  I would prefer to not have to introduce jest to my project though.
I'm using Enzyme now.

**Comment by mxstbr** [comment]
@MicheleBertoli's `jest-styled-components` is freaking amazing!

**Comment by George-Payne** [comment]
Here is a jest extension based on @garetmckinley's ideas, and @diegohaz's hacky solution. No selectors yet, but supports regex. Takes a component rendered with react-test-renderer.

``` javascript

import styleSheet from 'styled-components/lib/models/StyleSheet';

const toHaveStyle = (expect) => {
  expect.extend({
    toHaveStyle(received, selector, value) {
      try {
        const { props: { className } } = received.toJSON(),
              css = styleSheet.componentStyleSheet.tags[0].innerHTML,
              styles = new RegExp(`${className} {([^}]*)`, 'g').exec(css)[1],
              capture = new RegExp(`${selector}:[\s]*([^;]+);`, 'g'),
              values = styles.match(capture).map(r => r.replace(capture, '$1').trim());

        if (
          values &&
          values.some((v) => {
            if (value instanceof RegExp) {
              return v.match(value);
            }

            return v === value;
          })
        ) {
          return {
            message: () => (
              `Expected component to have ${selector} matching ${value}`
            ),
            pass: true,
          };
        }

        return {
          message: () => (
            `Expected component to have ${selector} matching ${value} received: ${styles}`
          ),
          pass: false,
        };
      } catch (e) {
        return {
          message: () => (
            `Expected ${received} to be a component from react-test-renderer. ${e}`
          ),
          pass: false,
        };
      }
    },
  });
};

export default toHaveStyle;
```

Usage:

``` javascript
import renderer from 'react-test-renderer';
import toHaveStyle from './toHaveStyle';
import { Blueberry } from 'components';

// Couldn't seem to get access to "expect" in imported files / setup.
toHaveStyle(expect);

describe('Blueberry ', () => {
  it('should be blue', () => {
      const component = renderer.create(
        <Blueberry />,
      );
      expect(component).toHaveStyle('background-color', 'blue');
  });

  it('should be white if a ghost', () => {
      const component = renderer.create(
        <Blueberry ghost />,
      );
      expect(component).toHaveStyle('background-color', /(#(fff|ffffff)|white)/i);
  });
});
```
Please be aware that while strings are exact matches, regex are just .match, so:
``` javascript
expect(component).toHaveStyle('display', /(inline)/);
```
Will match `inline`, `inline-block`, `inline-flex` etc.

**Comment by leocreatini** [comment]
I took what @George-Payne and made it available for [Enzyme](http://airbnb.io/enzyme/index.html):

```
import styleSheet from 'styled-components/lib/models/StyleSheet';

const toHaveStyle = (() => {
  window.expect.extend({
    toHaveStyle(received, selector, value) {
      try {
        /* eslint-disable no-underscore-dangle */
        const className = received.node._reactInternalInstance._renderedComponent._instance != null
          ? received.node._reactInternalInstance._renderedComponent._instance.state.generatedClassName
          : received.node._reactInternalInstance._renderedComponent._currentElement.props.className;
          /* eslint-enable no-underscore-dangle */
        const css = styleSheet.tags[0].innerHTML;
        const styles = new RegExp(`${className} {([^}]*)`, 'g').exec(css)[1];
        const capture = new RegExp(`${selector}:[\s]*([^;]+);`, 'g'); // eslint-disable-line no-useless-escape
        const values = styles.match(capture).map((r) => r.replace(capture, '$1').trim());

        if (
          values &&
          values.some((v) => {
            if (value instanceof RegExp) {
              return v.match(value);
            }

            return v === value;
          })
        ) {
          return {
            message: () => (
              `Expected component to have ${selector} matching ${value}`
            ),
            pass: true,
          };
        }

        return {
          message: () => (
            `Expected component to have ${selector} matching ${value} received: ${styles}`
          ),
          pass: false,
        };
      } catch (e) {
        return {
          message: () => (
            `Expected ${received} to be a component from enzyme.\n${e}`
          ),
          pass: false,
        };
      }
    },
  });
})();

export default toHaveStyle;
```

Same usage, except I put the code in an IIFE so you do not need to pass expect into it. Just import it.

And you have to `mount` it, `shallow` rendering just won't work.

```
import React from 'react';
import { mount } from 'enzyme';
import Icon from '../index';
import '../../../testUtils/toHaveStyle';

describe('<Icon />', () => {
  it('should pass the color prop to the rendered component', () => {
    const color= '#666';
    const wrapper = mount(
      <Icon
        type="download"
        color={color}
      />);

    expect(wrapper).toHaveStyle('color', color);
  });
});
```

**Comment by MicheleBertoli** [comment]
Please add your matchers to [jest-styled-components](https://github.com/styled-components/jest-styled-components) @George-Payne @leocreatini : )
We already have `toHaveStyleRule` for React Native.

**Comment by George-Payne** [comment]
I took what @leocreatini did and updated my continued to be worked on version, so now you can also test :hover and ::after, and it works with both react test renderer and enzyme. 

``` javascript

/* eslint-disable one-var, no-useless-escape, no-underscore-dangle */

import { styleSheet } from 'styled-components';

const toHaveStyle = (() => {
  window.expect.extend({
    toHaveStyle(received, selector, value) {
      try {
        const className = findClassName(received),
              css = styleSheet.styleSheet.tags[0].innerHTML,
              styles = new RegExp(`${className} {([^}]*)`, 'g').exec(css),
              capture = new RegExp(`${selector}:[\s]*([^;]+)`, 'g');

        if (styles && styles[1].match(capture)) {
          const values = styles[1].match(capture).map(r => r.replace(capture, '$1').trim());

          if (
              values &&
              values.some((v) => {
                if (value instanceof RegExp) {
                  return v.match(value);
                }

                return v === value;
              })
            ) {
            return {
              message: () => (
                  `Expected component to have ${selector} matching ${value}`
                ),
              pass: true,
            };
          }
        }

        return {
          message: () => (
              `Expected ${className} to have ${selector} matching ${value} received: ${styles || css}`
            ),
          pass: false,
        };
      } catch (e) {
        return {
          message: () => (
              `Expected ${received} to be a component from react-test-renderer, or a mounted enzyme component. ${e}`
            ),
          pass: false,
        };
      }
    },
  });
})();

function findClassName(received) {
  let className = '';

  const component = received.component || received;

  // constructor.name doesnt work in older versions of node
  if (component.constructor && typeof component.toJSON === 'function') {
    // react test renderer
    className = component.toJSON().props.className;
  } else if (component.node) {
    // enzyme
    className = component.node.className ? component.node.className :
        received.node._reactInternalInstance._renderedComponent._instance !== null
          ? received.node._reactInternalInstance._renderedComponent._instance.state.generatedClassName
          : received.node._reactInternalInstance._renderedComponent._currentElement.props.className;
  }

  // styled components adds the className on the end.
  className = className.split(' ').pop();

  if (received.modifier) {
    className += received.modifier;
  }
  return className;
}

export default toHaveStyle;

```

Some usage: 
``` javascript
// ...

import '../../../testUtils/toHaveStyle';

// ...

expect(component).toHaveStyle('color', color);
expect({component, modifier: ':hover'}).toHaveStyle('color', hover);
expect(component.find('button')).toHaveStyle('color', 'pink');

```

**Comment by leocreatini** [comment]
@MicheleBertoli, I am working on adding it now.

@George-Payne, what version of styled-components are you using? I am unable to get styleSheet from the index's exports in mine, (1.4.6).

**Comment by George-Payne** [comment]
@leocreatini 2.0.0-15 (styled-components@next).

**Comment by leocreatini** [comment]
@George-Payne Ok, that sort of helps, it changes again with 2.0.0-17. It's no longer in there in the latest. Looking more into the code, it's been a bit bumpy trying to catch up with the code base :smile:

**Comment by three60five** [comment]
Is there anything like `jest-styled-components` for enzyme? I want the `toHaveStyleRule` API specifically.

**Comment by MicheleBertoli** [comment]
Hello @three60five, the `toHaveStyleRule` matcher of `jest-styled-components`works with v2 and both enzyme's [shallow](https://github.com/styled-components/jest-styled-components/blob/master/test/index.spec.js#L63) and [mount](https://github.com/styled-components/jest-styled-components/blob/master/test/index.spec.js#L69) rendering.
Feel free to [open an issue](https://github.com/styled-components/jest-styled-components/issues/new) on the repo if you have any problem.

**Comment by mxstbr** [comment]
Closing this now that `jest-styled-components` exists and is in the docs. Thanks for the insightful discussion folks!
