### ISSUE TITLE
enhacement, debug 

### ISSUE THREAD

**Issue by webmobiles** [styled-components/styled-components#1182]
I'm building a theme,  have no errors, but have problems with my variables i think and i'm getting wrong colors , it's possible to debug inside  ` ` expressions to see the values? the problem i see it's not a regular js function, or i can do something like this:

 ```
background-color:  ${
    console.log(props.plain) ;
    console.log(props.tehme.S) ;
   .... here te code to solve the background variable...

 };
```

below the code:

themes.js
```
import styled from 'styled-components';

export const themes = {
  sky: {
    P: '#7bb4dd',
    PLight: '#aee6ff',
    PDark: '#4984ab',
    PText: '#000000',
    S: '#616161',
    SLight: '#8e8e8e',
    SDark: '#5d99c6',
    SText: '#373737',
    fg: '#EEEEEE',
  },
};


export const Button = styled.button`
  font-size: 1em;
  padding: 0.25em 1em;
  border: none;
  border-radius: 3px;
  background-color:  ${props => (props.plain ? 'transparent' : (props.secondary ?  props.theme.S : props.theme.P))};
  color: ${props => (props.secondary ?  props.theme.SText : props.theme.PText)};
  
`;
```

App.js
```
import { themes, Button } from './components/Themes';
class App extends Component {
  constructor() {
    super();
    this.state = {
      name: 'React',
      theme: themes.sky,
    };
  }
  render() {
    return (
          <ThemeProvider theme={this.state.theme}>
<div style={{ width: '200px', border: 'solid 1px black',background: '#EEEEEE' }}>

        <Button plain>Plain Primary</Button>
        <Button plain secondary>Plain Secondary</Button>
        <Button primary>Raised Secondary</Button>
        <Button secondary>Raised Primary</Button>
        <Button>Raised</Button>


      </div>
```

but i'm getting the wrongs  colors:

![screen shot 2017-09-27 at 17 54 56](https://user-images.githubusercontent.com/21120559/30924012-bfdf9482-a3ad-11e7-925d-f4ebfc0b9b34.png)

correct is this:

![screen shot 2017-09-27 at 18 07 51](https://user-images.githubusercontent.com/21120559/30924437-03755bb8-a3af-11e7-9207-492ab94fc98a.png)

**Comment by mxstbr** [comment]
> the problem i see it's not a regular js function

They are! They are just [arrow functions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions), a new introduction with the latest version of JavaScript.

To console.log some stuff in there you'd do something like this:

```JS
export const Button = styled.button`
  font-size: 1em;
  padding: 0.25em 1em;
  border: none;
  border-radius: 3px;
  background-color:  ${props => {
    console.log(props.plain);
    return (props.plain ? 'transparent' : (props.secondary ?  props.theme.S : props.theme.P))
  }};
  color: ${props => {
    console.log(props.secondary);
    return (props.secondary ?  props.theme.SText : props.theme.PText)
  }};
`;
```

Note the extra pair of curly brackets, those work just like a "normal" `function` function would!

**Comment by webmobiles** [comment]
that is nice, i know arrow functions, but not realized that in ES6 Template literals i could to write like in normal function. thanks !
