### ISSUE TITLE
Upgrade Enzyme to v3?

### ISSUE THREAD

**Issue by bkazi** [styled-components/styled-components#1185]
Enzyme v3 launched recently which introduced a change to the way Enzyme internals work
More importantly adding potential to support React-like libraries.
React 16 is only supported by v3 so to test styled-components against the latest stable version of React the upgrade might be necessary
Airbnb reports that most test cases should continue to work as is without any change
I think the major changes would be in handling the different adapters for different React versions

**Comment by mxstbr** [comment]
PR welcome, though I don't want to force our users to upgrade to React v16! (they should be able to if they want to though)
