### ISSUE TITLE
compatibility with react 16 fiber

### ISSUE THREAD

**Issue by webmobiles** [styled-components/styled-components#1187]
the only add on package  that i use on my react project is styled-component, today i decide to migrate:

can I use it with react16 ?

**Comment by mxstbr** [comment]
Should work fine, are you getting any warnings?

**Comment by webmobiles** [comment]
I've just installed after your message, and working 2x fast, it rocks ! thanks

**Comment by StevenLangbroek** [comment]
I imagine `styled-components` works perfectly fine with `renderToString`, but `renderToNodeStream` is a different problem entirely, but it could add great benefits for performance at scale (re: work distribution). It could be wrapped in a Promise (Streams -> Promise is relatively straightforward), with user-land implementation looking like:

```js
    const sheet = new ServerStyleSheet()
    const main = await sheet.collectStyles(<Main />)
    const styleTags = sheet.getStyleElement()
```

My use-case is in next.js, but something has been bothering me a bit about the example implementation: render is being called multiple times (in `getInitialProps` in the super Document), and in its `render` method. Is my assumption correct (about render being called twice)? And is there maybe a way to override renderPage? Have there been talks with Zeit?

**Comment by mxstbr** [comment]
Look at the styled-components example in the Next repo! Also see #1192
