### ISSUE TITLE
Multiple image requests in Safari

### ISSUE THREAD

**Issue by petrhanak** [styled-components/styled-components#1188]
Rerender sometimes causes to download image again. In general only some images are affected, but on localhost every image is downloaded twice, same with every image uploaded to imgbb.com.
I couldn't find pattern here, but the problem is probably somewhere else.

## Version
styled-components: 2.2.0
safari: 11.0
react: 15.6.2, 16.0.0

## Reproduction
https://www.webpackbin.com/bins/-Kv9Z0z-rErayJ_ssOVK

## Steps to reproduce
- open network tab in web inspector
- click the "click me" button

## Expected Behavior
Nothing happens - background image is already downloaded and used

## Actual Behavior
Image is downloaded again

**Comment by mxstbr** [comment]
Sorry for the slow answer here, this is probably not a problem with styled-components. Maybe try StackOverflow?
