### ISSUE TITLE
Optimizing tree shaking

### ISSUE THREAD

**Issue by wmertens** [styled-components/styled-components#1195]
Right now, all styled components are created at module load time, even if preprocessed with the babel plugin.

Would it be possible to instead convert them like this:

actual code:
```js
const MyBox = styled.div`border: thick solid pink`
```

post-processed by plugin:
```js
const MyBox = props => <styled.Wrap Cmp="div" css={[`border: thick solid pink`]}/>
```

This simply defines a function without any side effects, and it can be tree shaken if not used. The current approach is a function call with possible side effects and as such can't be tree shaken.

The only difference is that styled components css classes will be created on first use, not when defined.

Maybe even this is possible? It would shave off a tree level:
```js
const MyBox = props => <div {...props} className={styled.getClassNames(props, [`border: thick solid pink`])}/>
```

**Comment by wmertens** [comment]
After the discussion at https://spectrum.chat/thread/a8359eb6-741b-477c-be38-a343ffeda9f6 it became clear that due to the SC API, there's no way around creating them at module load time. Closing.

**Comment by philpl** [comment]
What we can do though is utilise Uglify’s “ #__PURE__” annotation. If we pull that off right in the lib and our Babel plugin, I think we can get dead-code elimination in uglify to help us out

**Comment by wmertens** [comment]
Ah yes indeed! I wonder if the annotation could be done on the library
instead?

**Comment by alubbe** [comment]
any news here? Would be great to have tree shaking support!
