### ISSUE TITLE
Interpolating a wrapped styled component.

### ISSUE THREAD

**Issue by cameron-martin** [styled-components/styled-components#1197]
I'm using react-styleguidist in a project, and for react-docgen to pick up the components, I have to wrap them in a standard component, e.g.

```jsx

const InnerComponent = styled.div``;

export default function Component {
    return <InnerComponent />;
}
```

However, this now means that I cannot interpolate them in the template literals, e.g.

```js
styled.div`${Component} > & {}`;
```

TypeScript gives me a type error if I try to, and I assume it does not work at runtime either as there is not a way of obtaining the component's generated class name.

Is there any way around this problem?

**Comment by mxstbr** [comment]
You could export the styled components with a named export and use that for targeting.

```JS
export const InnerComponent = styled.div``;

export default function () => {
    return <InnerComponent />;
}
```

```JS
// 👇 This imports the styled component
import { InnerComponent } from '../Inner';

styled.div`${InnerComponent} > & {}`;
```

**Comment by cameron-martin** [comment]
This seems slightly nasty exporting the underlying component. If I were to make the wrapper have a static getter of `styledComponentId` which just delegated to the underlying component, would this work? If so, would you accept a PR to update the typescript definitions to just require this property?

**Comment by mxstbr** [comment]
We definitely do not want to expose that API externally, it's only for internal use.

The real fix here is for `react-docgen` to understand `styled.div` calls so you don't have to create the wrapper at all. See this issue https://github.com/reactjs/react-docgen/issues/187 and the linked PR from there https://github.com/reactjs/react-docgen/pull/195, maybe you could try submitting an updated PR with the fixes requested by the maintainer?
