### ISSUE TITLE
Create a Babel macro

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components#1200]
We should create a [Babel macro](https://github.com/kentcdodds/babel-macros) and have a `macro.js` file at the root of the project. This would let users do the following:

```JS
import styled from 'styled-components/macro';

const Bla = styled.div`
  color: blue;
`
```

The big difference is that the macro version would do all the stuff [our Babel plugin](https://github.com/styled-components/babel-plugin-styled-components) does via `babel-macros`. (I'm unsure if all of it is possible, but it's worth a try)

This would be awesome to get the Babel plugin into `create-react-app`: https://github.com/facebookincubator/create-react-app/issues/2730#issuecomment-329577078

/cc @gaearon @kentcdodds @threepointone

**Comment by PiereDome** [comment]
I am currently working on this. There are a few things that I have discovered. 

- We won't be able to modify the import statement, so we cannot append the /no-parser that happens with the preprocess setting. 
- Also it looks like we would need to import styled-components as well as the macro because the macro is "consumed" during the transpilation of babel-macros

```
import styled from 'styled-components'
import macro from 'styled-components/macro'

const macro.div`
  background: red;
`
```

becomes (with all settings set to true)

```
import styled from 'styled-components';


styled.div.withConfig({
  displayName: 'src',
  componentId: 's5geyt2-0'
})(['\n  background: red;\n']);
```

is this still valuable to proceed working on?

**Comment by kentcdodds** [comment]
> We won't be able to modify the import statement, so we cannot append the /no-parser that happens with the preprocess setting.
> Also it looks like we would need to import styled-components as well as the macro because the macro is "consumed" during the transpilation of babel-macros

You may not be able to modify the import statement (because it'll be removed), but you _can_ add a new import statement by getting the `Program` node and unshifting a new import onto the body of the program :)

So no, people wont have to import both, you can make it work without that :)

**Comment by PiereDome** [comment]
Sweet. Thanks for the tip. I will get that implemented then.

**Comment by kentcdodds** [comment]
I created a macro for glamorous that does what I suggested above. Here it is for your reference 😉
https://github.com/bernard-lin/babel-plugin-glamorous-displayname/blob/master/src/macro.js

**Comment by probablyup** [comment]
Closed via https://github.com/styled-components/styled-components/pull/2032
