### ISSUE TITLE
Caching does not take .attrs into consideration

### ISSUE THREAD

**Issue by rtkhanas** [styled-components/styled-components#1216]
## Version
2.2.1

## Reproduction

This is a 2.2.1 bug, 2.2.0 works well. Seems like it is a bug in a caching feature.

https://www.webpackbin.com/bins/-KvugYeqOLsl-sk21VeB (2.2.1)

## Steps to reproduce

Click on a text.

## Expected Behavior

Position should be changed every time you click on a text.

https://www.webpackbin.com/bins/-KvukacztYA0RLVrQqkH (2.0.0-10)

## Actual Behavior

Position never changes.

**Comment by mxstbr** [comment]
Great catch @rtkhanas, sorry for the troubles—this is indeed an oversight in the caching mechanism, we only check if the component has functions in the styles!

PR to improve this very welcome, /cc @schwers

**Comment by rtkhanas** [comment]
Seems like it is fix now!

Thank you @mxstbr and @schwers!

**Comment by mxstbr** [comment]
Yep, this is fixed, totally forgot to close this-thanks!
