### ISSUE TITLE
Add danger-plugin-jest

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components#1221]
We should add the `danger-plugin-jest` to our Dangerfile so folks can easily see test failures: http://danger.systems/js/plugins/danger-plugin-jest.html

**Comment by apoorv-mishra** [comment]
Hi @mxstbr , I would like to work on this issue. Well, do we need to create a custom output file(`tests/results.json`) or `test-results.json` would suffice?

**Comment by mxstbr** [comment]
I think a root-level `test-results.json` would be better since we don't have a root-level `tests` folder! :blush:

**Comment by apoorv-mishra** [comment]
Alright. Also, do we need to call `jest()` at the top, right after import or do we need to call it inside `jsTestChanges.forEach(...)` at the end?

**Comment by mxstbr** [comment]
I don't think that starts Jest, I think it just gets the `test-results.json` file, so either way is fine I think?

**Comment by apoorv-mishra** [comment]
Alright. Thanks.

**Comment by mxstbr** [comment]
Thank you @apoorv-mishra!
