### ISSUE TITLE
[HMR] Styles not updating with v2.2.1

### ISSUE THREAD

**Issue by PiereDome** [styled-components/styled-components#1225]
## Version
2.2.1
babel-plugin-styled-components version: N/A

## Reproduction

HMR is broken for styled component styles with upgrade from 2.2.0 to 2.2.1. I believe that the culprit may be #1069. Perhaps we could do a check if the code is running in dev environment and not cache the statics then.

## Steps to reproduce
Run webpack-dev-server with HMR using the react-hot-loader plugin

## Expected Behavior
When I change a style attribute in my styledComponent I would expect the style to change in the browser without a full page refresh. I did test that this is working in 2.2.0.

## Actual Behavior
The style change does not happen until I do a full page refresh

**Comment by mxstbr** [comment]
Yep, very likely. Good catch, @schwers any idea how we can detect HMR? Should we turn off caching in development?

**Comment by tannerlinsley** [comment]
Ah ha! Just realized this is what's breaking styled-components hot reloading for react-static users.  Looks like I'm gonna have to lock things down to 2.2.0 until it's fixed.

**Comment by schwers** [comment]
@PiereDome sorry about that, if by chance its only affecting `attrs` usage I have a PR open for it https://github.com/styled-components/styled-components/pull/1219 (not sure why travis is failing but appveyor passes)

@mxstbr  I'll have to try out something with HMR. I would think if the component is re-evaluated we wouldn't have to do anything. i.e. a `new ComponentStyle` should be created, which would recompute `isStatic` and its content has; if its only `attrs` I think that patch will resolve. A dev check could work but right now it looks like we hardcode that in at build time so we might need to do some trickery to read in the user's env vars at runtime.

**Comment by PiereDome** [comment]
@schwers I am not using `attrs` in my StyledComponents. It did seem to work when I was using the `connect` HOC from react-redux but not 100% sure that was the reason it was working. I can further try to narrow the working vs non-working components if you need me to.

**Comment by schwers** [comment]
Okay, gotcha. I'll try repro'ing later today. If you're able to provide any
minimal examples of a SC that stay stale that'd be awesome.

**Comment by PiereDome** [comment]
Looks like if you have a function call inside the styledComponent the HMR will work. i.e. 
`` const StyledComponent = styled(Component)`
  ${functionCall}
  background: red;
` ``
``const functionCall = () => `
    padding: 7px;
` ``

**Comment by philpl** [comment]
@mxstbr @schwers:

> Should we turn off caching in development?

That sounds like a sensible solution to me :+1:

**Comment by theKashey** [comment]
As @PiereDome mentioned - HRM start working when you do have function inside style, ie style is not static.
RHL, on code update, will trigger componentWillReceiveProps, but component is sealed from any changes.
```js
 componentWillReceiveProps(nextProps: { theme?: Theme, [key: string]: any }) {
      // If this is a staticaly-styled component, we don't need to listen to
      // props changes to update styles
      const { componentStyle } = this.constructor
      if (componentStyle.isStatic) {
        return
      }
```

So, just replace it by 
```js
      if (!module.hot && componentStyle.isStatic) {
        return
      }
```
PS: `module` exists in node.js and webpack environment, better to extract it as helper function.

**Comment by mxstbr** [comment]
Hmm, that could work but might break some folks if they don't use webpack. Maybe if they properly guard against it?

**Comment by theKashey** [comment]
```js
const isHMREnabled = () => typeof module !== 'undefined' && module.hot
```
Should I create a PR, or you can manage this by your own?

**Comment by mxstbr** [comment]
Please create a PR!

**Comment by cr0cK** [comment]
Any news on this?

**Comment by theKashey** [comment]
@cr0cK - was releases a month ago - v2.2.4

**Comment by cr0cK** [comment]
Oh sorry. But it still doesn't work for me. 
But I just noticed that it's all my HMR that is broken. Time to debug.

**Comment by elliothimmelfarb** [comment]
@cr0cK Did you figure it out? I'm having the same problem at v2.4.0.

**Comment by theKashey** [comment]
@elliothimmelfarb - just post an example, and we will figure out which part is broken - HRM, RHL or Styled.

**Comment by elliothimmelfarb** [comment]
@theKashey 
This is the error message I am getting in the devtools after a hot reload:

```
React Hot Loader: this component is not accepted by Hot Loader. 
Please check is it extracted as a top level class, a function or a variable. 
Click below to reveal the source location: 
 ƒ StyledComponent() {
        classCallCheck(this, StyledComponent);
        return possibleConstructorReturn(this, _ParentComponent.apply(this, arguments));
      }
```
Is that telling?

**Comment by theKashey** [comment]
@elliothimmelfarb - it is about - StyledComponent could cause a state loss, as long it got updated.
Anyway - try `yarn add --dev react-hot-loader@next` and rerun.
I am not sure it will help, it works, as long it print warnings.

**Comment by hawkeng** [comment]
I'm having this issue with version 4.0.11.

Any ideas?
