### ISSUE TITLE
Developer friendly class names for easier debugging

### ISSUE THREAD

**Issue by jjant** [styled-components/styled-components#1227]
I think it would be cool to have developer friendly class names when `NODE_ENV === 'development'`.

When using things like React Perf tools, I get output like this:
![image](https://user-images.githubusercontent.com/15112080/31368850-80b2975a-ad80-11e7-91df-f1a0160bebbb.png)

Now, it's difficult to recognise which styles change from looking at that, if I don't know what triggered the class change, I have to go to the html and look for the class, and the differences in style.
I think we could have a better developer experience if class names had more descriptive names, perhaps something as concatenating the properties it carries (perhaps something like `margin_right_50px_left_0_border_style_solid` vs a hash like `jqZp00`).

Glad to hear your thoughts.

**Comment by mxstbr** [comment]
I think it's more important to be able to figure out which component was rendered. Imagine if you saw:

```JS
{"className":"margin_right_50px_left_0_border_style_solid"}
```

How the hell are you going to find out which component that is? You won't, that's why the component name is in there. I don't think it's worth optimizing for ReactPerf usage at the expense of everybody having a much worse time figuring out which component is which.

**Comment by philpl** [comment]
> Now, it's difficult to recognise which styles change from looking at that, if I don't know what triggered the class change, I have to go to the html and look for the class, and the differences in style.

That is something we could possibly do, but the change that was triggered doesn't stem from the generated CSS, it stems from the props that change it. I don't think it makes sense to make this big leap and say that this means that we should augment react-perf-tools to show style changes :/
