### ISSUE TITLE
Extend not working in Next.js 4 version

### ISSUE THREAD

**Issue by alivelee** [styled-components/styled-components#1228]
## Version
2.1.1

Babel-plugin-styled-components version 

1.2.1
## Reproduction

```
const Title = styled.h1`
  color: red;
  font-size: 50px;
`
const AnotherTitle = Title.extend`
  color:blue;
`
export default () => <AnotherTitle>My page</AnotherTitle>
```
Works perfectly in Next.js 3 version but not in 4

it said

```
Warning: <{color:blue}
/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInBhZ2VzL2luZGV4LmpzP2VudHJ5Il0sIm5hbWVzIjpbXSwibWFwcGluZ3Mi
OiJBQVFpQyxBQUVhLFdBQ1oiLCJmaWxlIjoicGFnZXMvaW5kZXguanM/ZW50cnkiLCJzb3VyY2VSb290IjoiL1VzZXJzL2Fkc3BlL05leHRKcyIsInNvdXJjZXNDb250ZW50IjpbIlxuaW
1wb3J0IFJlYWN0IGZyb20gJ3JlYWN0J1xuaW1wb3J0IHN0eWxlZCBmcm9tICdzdHlsZWQtY29tcG9uZW50cydcblxuY29uc3QgVGl0bGUgPSBzdHlsZWQuaDFgXG4gIGNvbG9yOiByZWQ7
XG4gIGZvbnQtc2l6ZTogNTBweDtcbmBcbmNvbnN0IEFub3RoZXJUaXRsZSA9IFRpdGxlLmV4dGVuZGBcbiAgY29sb3I6Ymx1ZTtcbmBcbmV4cG9ydCBkZWZhdWx0ICgpID0+IDxBbm90aGVyVGl0bGU+TXkgcGFnZTwvQW5vdGhlclRpdGxlPiJdfQ== */
/*@ sourceURL=pages/index.js?entry */ /> is using uppercase HTML. Always use lowercase HTML tags in React.
{ Invariant Violation: Invalid tag: {color:blue}
/*# sourcemappingurl=data:application/json;base64,eyj2zxjzaw9uijozlcjzb3vyy2vzijpbinbhz2vzl2luzgv4lmpzp2vudhj5il0sim5hbwvzijpbxswibwfwcgluz3mioijbqvfpqyxbquvhlfdbq1oilcjmawxlijoicgfnzxmvaw5kzxguanm/zw50cnkilcjzb3vyy2vsb290ijoil1vzzxjzl2fkc3bll05lehrkcyisinnvdxjjzxndb250zw50ijpbilxuaw1wb3j0ifjlywn0igzyb20gj3jlywn0j1xuaw1wb3j0ihn0ewxlzcbmcm9ticdzdhlszwqty29tcg9uzw50cydcblxuy29uc3qgvgl0bgugpsbzdhlszwquadfgxg4gignvbg9yoibyzwq7xg4gigzvbnqtc2l6ztogntbwedtcbmbcbmnvbnn0iefub3rozxjuaxrszsa9ifrpdgxllmv4dgvuzgbcbiagy29sb3i6ymx1zttcbmbcbmv4cg9ydcbkzwzhdwx0icgpid0+idxbbm90agvyvgl0bgu+txkgcgfnztwvqw5vdghlclrpdgxlpijdfq== */
/*@ sourceurl=pages/index.js?entry */
    at invariant (/Users/adspe/NextJs/node_modules/fbjs/lib/invariant.js:42:15)
    at validateDangerousTag (/Users/adspe/NextJs/node_modules/react-dom/cjs/react-dom-server.node.development.js:2399:34)
    at ReactDOMServerRenderer.renderDOM (/Users/adspe/NextJs/node_modules/react-dom/cjs/react-dom-server.node.development.js:2791:5)
    at ReactDOMServerRenderer.render (/Users/adspe/NextJs/node_modules/react-dom/cjs/react-dom-server.node.development.js:2755:23)
    at ReactDOMServerRenderer.read (/Users/adspe/NextJs/node_modules/react-dom/cjs/react-dom-server.node.development.js:2722:19)
    at renderToString (/Users/adspe/NextJs/node_modules/react-dom/cjs/react-dom-server.node.development.js:2980:25)
    at renderPage (/Users/adspe/NextJs/node_modules/next/dist/server/render.js:168:24)
    at Function.getInitialProps (/Users/adspe/NextJs/node_modules/next/dist/server/document.js:83:25)
    at _callee$ (/Users/adspe/NextJs/node_modules/next/dist/lib/utils.js:36:30)
    at tryCatch (/Users/adspe/NextJs/node_modules/regenerator-runtime/runtime.js:65:40) name: 'Invariant Violation', framesToPop: 1 }
```

**Comment by morajabi** [comment]
I can confirm.

**Comment by philpl** [comment]
I don't really see how this could be generated by our babel-plugin: `<{color:blue}`

Is it something from styled-jsx?

**Comment by morajabi** [comment]
I didn't use the `styled-jsx` but I got the error with Next 4 (I tried on a very minimal repo).

**Comment by philpl** [comment]
@morajabi Next sets up the `styled-jsx/babel` plugin by default, hence it has caused some issues before:

https://github.com/zeit/next.js/blob/master/server/build/babel/preset.js#L29

**Comment by morajabi** [comment]
See. They updated styled-jsx to version 2 and improved the performance so it can be styled-jsx's

**Comment by alivelee** [comment]
@philpl so What's the solution here.

**Comment by mxstbr** [comment]
Disable the styled-jsx Babel plugin?

**Comment by alivelee** [comment]
@mxstbr then i can't use style-jsx at the same time with styled-component, is that right

**Comment by morajabi** [comment]
@alivelee That's right.

**Comment by philpl** [comment]
@morajabi @mxstbr @arunoda here's a small reproduction https://github.com/philpl/next-4-repro

cc @giuseppeg

**Comment by mxstbr** [comment]
Since this is definitely not on our side, I'm going to close this out for now. Hoping @giuseppeg has a fix out soon :blush:

**Comment by alivelee** [comment]
@mxstbr it seems that disable certain babel plugin in .babelrc file is not a option
https://github.com/babel/babel/issues/3016

**Comment by morajabi** [comment]
@alivelee Alternatively, you can not use `.extend` and use `styled()` or just extract the css and use it somewhere else:
```
const commonStyles = css`
  font-size: 13px;
`

const Title = styled.div`
  ${commonStyles}

  color: blue;
`
```

But they're not best practices though (‍‍‍`styled()` is bad practice too 🙃).

**Comment by alivelee** [comment]
I accept that,Thanks for the temp solution

**Comment by philpl** [comment]
@morajabi that won't work. It seems that all TaggedTemplateLiterals are affected (except `css`)

**Comment by morajabi** [comment]
I'm using SC with next@4 right now!

**Comment by giuseppeg** [comment]
@philpl thanks for putting a testcase together and for investigating a bit. 
I'll see if I can figure out if anything is broken in styled-jsx – I added a check to only transpile our tagged template literals https://github.com/zeit/styled-jsx/blob/5213cee0e3aa5f50f61b4f9dfcdd6deb78c1b972/src/babel-external.js#L24 🤔

**Comment by giuseppeg** [comment]
probably they are both `undefined` 😅

**Comment by philpl** [comment]
@giuseppeg thanks for jumping on this quickly :smile: :+1:

**Comment by morajabi** [comment]
@giuseppeg Worth mentioning that normal styled statements are not affected. This works perfectly:
```
import styled from 'styled-components'

const Title = styled.div`
  color: blue;
`
```

**Comment by alivelee** [comment]
@morajabi so why the extends cause the problem

**Comment by giuseppeg** [comment]
@philpl shipit? https://github.com/zeit/styled-jsx/pull/304 (thanks for the test case again)

**Comment by philpl** [comment]
@giuseppeg looks great! Thanks again for the quick reply 👍

**Comment by martahj** [comment]
Sorry to comment on a closed issue, but is there a Nextjs release this is fixed on? Would love to be able to use `.extend`

**Comment by martahj** [comment]
In 4.1.4?

**Comment by morajabi** [comment]
In fact just a few hours after this issue was created the issue was gone 😉

**Comment by martahj** [comment]
Oh, I see - apologies, I was looking at [an issue](https://github.com/styled-components/styled-components/issues/1239) that linked to this one, but it looks like the error message is different :)

**Comment by eugenesia** [comment]
I got a "Warning: Prop `className` did not match." like in #1239 when using a styled component's `extend` method e.g. ``StyledComp.extend`...` `` method. When I changed it to ``styled(StyledComp)`...` `` the error disappears.

The error appears in Next version 4.2.1 - latest as of 12th Dec 2017.

**Comment by alexdevero** [comment]
The same issue here with extend not working (`Warning: Prop `className` did not match.`).

next: 4.2.1
babel-plugin-styled-components: 1.3.0
styled-components: 2.3.2
