### ISSUE TITLE
Feature Request: Above-the-fold CSS generation

### ISSUE THREAD

**Issue by giles-v** [styled-components/styled-components#1229]
Currently, `styled-components` allows developers to only generate CSS for the components they have on the page, referred to in the docs as "critical CSS" for server-side-rendering (SSR) so that even if your app has a huge CSS base, `styled-components` can only output the subset of that CSS which applies to the page you rendered.

For SSR apps which might render large pages, however, that leaves some space for improvement. I might have a large article with 5000 vertical pixels of embedded slideshows, videos, and so forth; but the only part above the fold is the header, the lead image, and some text. For me, "critical CSS" is styling what's above the fold, so that I can try to get everything I need to render that [into the first 15kB](https://www.youtube.com/watch?v=R8W_6xWphtw) for the quickest response. 

Since I design the pages, I can provide data on what is above the fold. What would be ideal for me is to be able to pull out CSS rules just for a subset of components (and global styles), put _that_ CSS in `<head>`, and then output the rest of the CSS later on in the document.

Example usage: suppose here's my page:
```xml
<App>
  <Header>
    <Logo/>
  </Header>
  <ArticleBody>
    <ArticleLeadImage />

    Lorem ipsum dolor sit amet, consectetur adipisicing elit, 
    sed do eiusmod tempor incididunt ut labore et dolore 
    magna aliqua. 

    <!-- LET'S SAY THE FOLD IS HERE --->

    Ut enim ad minim veniam, quis nostrud exercitation ullamco
    laboris nisi ut aliquip ex ea commodo consequat. 

    <ArticleInlineGallery />

    Duis aute irure dolor in reprehenderit in voluptate velit esse
    cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat
    cupidatat non proident.

    <ArticleCredits />
  </ArticleBody>
  <Footer />
</App>
```
In this case, my critical CSS will be for the components `Header`, `ArticleBody` and `ArticleLeadImage`.

I do **not** want CSS for `ArticleInlineGallery`, `ArticleCredits` or `Footer` in my `<head>`, since I'm trying to optimize for start render.

```javascript
const sheet = new ServerStyleSheet()
const html = renderToString(sheet.collectStyles(<App />)
const criticalPathCSS = sheet.getStyleTags([ Logo, ArticleBody, ArticleLeadImage ])
const entireDocumentCSS = sheet.getStyleTags()
```
In this example, the `getStyleTags` method permits an argument which acts as a whitelist filter on the matching components. (I'm not familiar with how the data flow works in this module, so putting the filter here might not make sense; but it's intended to be illustrative).

The filter would be interpreted upward, so `Logo` will implicitly include CSS for `Header` and `App`, but `ArticleBody` will not implicitly include `ArticleInlineGallery`.

---

To flesh out a bit more context here: in using a setup like this, I envision marking up all my base page templates in my app with a specific list of above the fold components, thus:
```javascript
// pages/article.js

const FrontEndPageController { 
  constructor() {
    this.criticalPathComponents = [ Header, Logo ];
  }
}

const ArticleController extends FrontEndPageController {
  constructor() {
    super();
    this.criticalPathComponents.push(ArticleBody);
  }

  render() {
    return (
      <ArticleBody>
        // stuff
      </ArticleBody>
    );
}
```
You could imagine your FE components being self-aware of whether they are critical, or pages accepting that responsibility; they could push that data into a Redux store, and when the SSR render step ran, it can pull the aggregated list of critical components out of the store, and pass it into `styled-components`, thus allowing me to generate true critical CSS and optimize the heck out of my above the fold render.

**Comment by philpl** [comment]
I think it’s pretty easy to filter the rendered CSS in the ServerStyleSheet by styles components.

The question is whether that will have any consequences for the rehydration as it works today.

cc @geelen

**Comment by giles-v** [comment]
@philpl do you mean it's easy for a consumer of this module? Or easy as a feature request? If the former, would you mind putting some pseudocode on how you'd see this being implemented?

**Comment by philpl** [comment]
@giles-v As a feature request

**Comment by evan-scott-zocdoc** [comment]
I'm not sure how you could possibly do this without the server having a concept of static layout, knowing the requesting browser dimensions, and then being able to figure out which components are in view.

In other words, not possible.

**Comment by philpl** [comment]
@evan-scott-zocdoc that is indeed out of our scope, but it might be possible to filter the output with a list of critical components as per the original post

**Comment by chmaltsp** [comment]
This would help out a lot with larger dashboards with lots of components to be able to render just the frame or 'shell' as specified in PWA Guidelines.

**Comment by philpl** [comment]
@chmaltsp for now I’d recommend you to split your bundle to exclude those expensive components. This can be done using a dynamic import and maybe react-loadable depending on the setup

**Comment by chmaltsp** [comment]
@philpl good call on react-loadable haven't seen that before, I am already splitting up everything by routes so my load times aren't even that long. I guess this is more of a nice to have but it would be nice to be able to filter out some components and extract styles for them while being able to keep everything in sc. You could always just manually inject these 'critical styles' at the top of your index.html. I am also talking about a non SSR setup too.

**Comment by probablyup** [comment]
Given that we aren't moving forward with preprocessing or static extraction in the foreseeable future, going to close this.

**Comment by joachimesque** [comment]
Is there any chance this Issue will be revived? Performance-wise, it would be really interesting to get the critical "above the fold" CSS rules in the `<head>` while everything else is loaded later.

I don't know how it could be done (JS is not my strength), but it's a feature I really need. Perhaps it could be done by declaring which components in the app are considered part of the critical path (Header, Hero…) and the rest (Footer, etc…) is to be put in an external stylesheet.
