### ISSUE TITLE
Cannot read property 'state' of undefined - props.location.state - react-router

### ISSUE THREAD

**Issue by 4886Talga** [styled-components/styled-components#1232]
## Version
2.1.0

## Reproduction
My code

I´m sending my props with link state prop to my details page
 
   ` <Link to={{pathname:`/beerdetail`, state: {beer:beer} }}>` 

and trying to extract img_url and add it to my styled-component

`const BeerImage = styled.div`	  
**`background-image: url(${props => props.location.state.beer.img_url});`**
`background-size: 60px 200px;`
`background-color: #fff;`
`height: 200px;`
`width: 100px;`
`background-repeat: no-repeat;`
`background-position: center;`
`margin: 0 auto;`
`;`

but i´m getting this message 

`Cannot read property 'state' of undefined`

What i´m doing wrong here?
Thans

**Comment by mxstbr** [comment]
You're not passing the location to your styled component?

```JS
<BeerImage location={props.location} />
```
