### ISSUE TITLE
Add development environment to the repo

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components#1238]
This repository should ship with a development environment so folks can help us develop styled-components more easily.

The optimal workflow would look something like this:

1. `git clone` the repo
2. Install the dependencies with `npm install` (or yarn)
2. Run `npm run dev` 

This should start a live-reloading React app process with a couple of styled components which automatically serves the local version of the code.

From #1174, h/t @j13l

**Comment by lazopm** [comment]
@mxstbr Is anyone working on this? I would like to take a shot at this during the weekend.

**Comment by philpl** [comment]
@lazopm feel free to pick this up if you’d like 👍🙌

**Comment by mxstbr** [comment]
@lazopm please do, it'd be great to have this! :blush:

**Comment by gribnoysup** [comment]
@lazopm are you working on this?

@mxstbr @philpl do you still need help with this?

**Comment by mxstbr** [comment]
Done thanks to the amazing @gribnoysup!
