### ISSUE TITLE
defaultProps and default theme

### ISSUE THREAD

**Issue by oomathias** [styled-components/styled-components#1240]
I'm trying to make Components with some default Theme, so they can be rendered outside of a `ThemeProvider`.

I understand that my result is normal and is due to how defaultProps works.
I'll paste an example, so it's easier to understand.

```js
// My theme
const theme  = {
  color: 'red',
  backgroundColor: 'yellow'
}

// A component style the color, uses the theme color and fallback do blue
const A = styled('div')`
  color: ${props => props.theme.color}
`

A.defaultProps = {
  theme: {
    color: 'blue'
  }
}

// B component style de background-color, uses the theme backgroundColor and fallback to grey
const B = styled(A)`
  background-color: ${props => props.theme.backgroundColor}
`
B.defaultProps = {
  theme: {
    backgroundColor: 'grey'
  }
}

render(
  <div>

    <A>A without Theme</A>
    <B>B without Theme</B>

    <ThemeProvider theme={theme}>
      <A>A with Theme</A>
      <B>B with Theme</B>     
    </ThemeProvider>

  </div>
)
```
Render this: (nb: my Theme provider changes the font but that's not the issue here)
![image](https://user-images.githubusercontent.com/465790/31551508-15afcbe6-b035-11e7-8456-e2bdd8c8549e.png)

What I would like to have is:
![image](https://user-images.githubusercontent.com/465790/31551740-c4f0c31c-b035-11e7-8a4f-06c451280b49.png)

Do you have any idea how I could achieve this behavior?

Maybe we need to create something like `defaultTheme`
```js
const A = styled('div').defaultTheme({
  color: 'blue'
})`
  color: ${props => props.theme.color}
`
```

**Comment by philpl** [comment]
The simple answer is `styled(AnotherStyledComponent)` is most of the times not recommendable, so if you use `AnotherStyledComponent.extend` the problem resolves itself fortunately :wink:

**Comment by oomathias** [comment]
@philpl Thanks that was fast but `const B = A.extend` renders:

![image](https://user-images.githubusercontent.com/465790/31552487-f3e40484-b037-11e7-80b7-30bfacfd2fce.png)

**Comment by philpl** [comment]
@oomathias yea, it doesn't carry over the `A.defaultProps`, you'll still have to merge those yourself. But the good news is that with `extend` you don't have think about a styled component rendering another styled component :wink:

**Comment by oomathias** [comment]
I understand that but with a more complex hierarchical tree like:

Panel > Header > Button > Box it becomes really hard to carry over all the default theme props.

**Comment by philpl** [comment]
@oomathias well, at every point you'll only have to merge it once

You could also switch over to an alternative method for theming: https://www.styled-components.com/docs/tooling#styled-theming

**Comment by oomathias** [comment]
I already have something like that, I guess I will just not support rendering my UI outside of a ThemeProvider. 🤷‍♂️ 

```js

const commons = {
  color: {
    default: p.black,
    danger: p.white,
    info: p.white,
    muted: p.white,
    primary: p.white,
    success: p.white,
    warning: p.white
  },

  backgroundColor: {
    default: p.lightgrey,
    danger: p.red,
    info: p.cyan,
    muted: p.grey,
    primary: p.blue,
    success: p.green,
    warning: p.orange
  }
}

const theme = {
  button: {
    backgroundColor: {
      default: commons.backgroundColor,
      active: p.bright2(commons.backgroundColor),
      hover: p.bright1(commons.backgroundColor)
    },

    color: commons.color
  }
}
```

**Comment by philpl** [comment]
@oomathias you could write getters for your theme properties that have a built in fallback?

**Comment by oomathias** [comment]
Yeah that's a good idea :)

**Comment by alvgaona** [comment]
This is the best way I could find for now. Although, you have to write the default prop in two places. 

```javascript
const B = styled(A)`
  background-color: ${props => props.theme.backgroundColor || 'grey'}
`
B.defaultProps = {
  theme: {
    backgroundColor: 'grey'
  }
}
```
