### ISSUE TITLE
autoCorrect warning, boolean value to string - React 16

### ISSUE THREAD

**Issue by rossfishkind** [styled-components/styled-components#1241]
I just upgraded to React 16, and noticed this error when I reloaded one of my pages:

`Warning: Received true for non-boolean attribute autoCorrect. If this is expected, cast the value to a string.`

I searched my repo and the only instance of `autoCorrect` being defined was in `styled-components`. When I looked a little more, I found that where the default attributes are being set for `styled-components`, `autoCorrect` is explicitly set to a `true` boolean rather than a string.

Thoughts? Thanks!

**Comment by philpl** [comment]
This is not an issue with styled-components, but with the way that props are now passed through to elements in React 16.

The filtering is gone and the mapping of some attributes is only present where it’s needed.

This means that when you see a warning like this you’ll have to make sure that you pass it what React expects to not need a mapping. If you think they should add a mapping back, I guess you could open a issue in their repo to get some clarification.

**Comment by itsthatguy** [comment]
@philpl Can you provide an example? The explanation of this is not very clear.

**Comment by rossfishkind** [comment]
@itsthatguy with React 16, it allows for pass-through props, where a prop can can be displayed directly on a tag.

ex: `<Component hello="hi" />` would show as `<div hello="hi">...</div>`

In previous version of React, `hello` would never have been passed through to the div and instead you would have needed to rely on data props.

The issue I had was unrelated to `styled-components` (as I took a deeper dive), however the solution to a similar warning would be to make sure that your pass-through prop is written in lowercase instead of camelcase.

As an example with `autoCorrect`, you would want to write it as `autocorrect` in order for React to not freak out.

I hope this helps! :)

**Comment by dlebedynskyi** [comment]
Solution above may work for simple div, But what about cases with 
```
const  C = styled.div`
 color: ${props => props.invalid ? 'red' : 'blue'};
`
```
In this case we rely on invalid being passed into styled component. How can we filter those out?

**Comment by AviArro** [comment]
I have a similar thing going but I don't quite understand why. 
Could you please help me understand that?

I have a component like this (it's stripped to relevant stuff):
```
const Flex = styled.div`
  flex-direction: ${props => (props.column && 'column') || 'row'};
  flex-wrap: ${props => (props.wrap && 'wrap') || 'nowrap'};
`;


Flex.propTypes = {
    column: PropTypes.bool,
    wrap: PropTypes.bool,
};`
```
Using it like `<Flex wrap>...</Flex>` gives me a warning

> Warning: Received `true` for a non-boolean attribute `wrap`.
> If you want to write it to the DOM, pass a string instead: wrap="true" or wrap={value.toString()}.

Using `column` attribute is fine. (`<Flex column>...</Flex>`). If I change `wrap` to `wrapp` it's also fine (no warning).
I think it somehow understood the attribute `wrap` for the html `<textarea>` attribute `wrap` and hence the problem.

Not sure if I should just ignore that, disable warnings, or change attribute name not to confuse React.

**Comment by rossfishkind** [comment]
@AviArro weird! It's up to you, however if you do `<Flex wrap="true">` written explicitly and surrounded with quotes, then the warning should disappear.
