### ISSUE TITLE
[React Native] text-transform css-to-react-native support

### ISSUE THREAD

**Issue by Inlesco** [styled-components/styled-components#1243]
FEATURE REQUEST.

As you know, RN team currently (and for the past 2.5+ years) has seen no apparent reason to implement support for CSS prop text-transform which is great for keepings things separate and generally follows DRY.

Even though there's no support from RN team on lack of `text-transform` is it possible to implement it for `styled-components`? Is there any way to retrieve a `Text` nodes values in the `styled.[[NODE_NAME]]` scope and pass it back after parsing and applying `text-transform` value?

**Comment by philpl** [comment]
This is something that is clearly in React Native's domain (Here's one of the many issues for it btw: https://github.com/facebook/react-native/issues/2088)

The biggest problem for us is that it needs to bubble down to child text nodes. The problems there are obvious: We can't just recursively walk your entire tree and search for some elements that have strings as their children. That is a slow and unnecessary task.

Instead you can simply achieve this yourself with either `attrs` in many cases even and using `toUpperCase()` / `toLowerCase()` etc.

I'll keep this open for a while in case further discussion comes in, but generally it is:

- Not supported by React Native for a reason
- An unnecessary feature to carry over as it can be replaced with more explicit code even
- Is too tricky to take on efficiently by us (bubbling, text nodes, etc)
- Holds no significant value for styled-components

cc @mxstbr @jacobp100

**Comment by Inlesco** [comment]
@philpl thx for the input. so, if RN team finally manages to implement this as this feature is very much needed and is very comfortable to use (especially when porting web -> native), is it a possibility you'd implement it?

could you explain your `attrs` based approach to workaround lack of stylish `text-transform`? I'm aware of the JS string callbacks method and I find ridiculous. there's a reason why `text-transform` exists on web and RN team seems to not get that (but... how??).

**Comment by mxstbr** [comment]
I agree with @philpl, we don't want to support anything custom which ReactNative doesn't support.

If they ever implement it it'll work out of the box with `styled-components/native` but until they do there's nothing we'll do, so I'm going to close this.
