### ISSUE TITLE
Comments not preserved in injectGlobal

### ISSUE THREAD

**Issue by MatteoVH** [styled-components/styled-components#1249]
## Version

2.1.1
babel-plugin-styled-components@1.1.7: {"minify": false}

## Problem Description

Place comments inside of `injectGlobal`. Notice that in the rendered css there are no comments. This is necessary for some font faces in order to place a legal disclaimer.

![image](https://user-images.githubusercontent.com/4573586/31633089-37dcbe72-b28d-11e7-9dfd-4b0cb7ea653e.png)

![image](https://user-images.githubusercontent.com/4573586/31633120-5b2b9df8-b28d-11e7-8f50-ae1f4501149d.png)

**Comment by mxstbr** [comment]
Similar to what `normalize.css` and others do you should write your comment with `/*!` at the beginning to indicate it's a legal statement, and then we should preserve it when injecting.

**Comment by epilande** [comment]
@mxstbr this looks like it should be handled in [`babel-plugin-styled-components`](https://github.com/styled-components/babel-plugin-styled-components)?

**Comment by mxstbr** [comment]
Yep, PRs very welcome!

**Comment by epilande** [comment]
Oops just noticed @MatteoVH is setting `"minify": false`. When I looked through the source code, it looks like `babel-plugin-styled-components` will only remove comments when `minify` is set to `true`.

But yeah, looks like stylis also strips out block and line comments.

**Comment by thysultan** [comment]
Yes, stylis removes all comments – though it probably could make an exception for the `/*!` convention.

**Comment by mxstbr** [comment]
You should probably make that exception, afaik it's a pretty common convention!

**Comment by MatteoVH** [comment]
Just to confirm: using the `/*!` convention does not work currently (with my version of styled-components at least).

**Comment by epilande** [comment]
Sweet stylis now supports this ([stylis changelog](https://github.com/thysultan/stylis.js/blob/master/CHANGELOG.md#340-october-20-2017)).

I've also submitted a PR to the babel plugin https://github.com/styled-components/babel-plugin-styled-components/pull/100

**Comment by mxstbr** [comment]
Thanks so much @epilande, that was an amazing PR! :tada:

This will be fixed in the next release of the Babel plugin!
