### ISSUE TITLE
Report syntax errors

### ISSUE THREAD

**Issue by k15a** [styled-components/styled-components#125]
Hey,

I currently debugged a problem where I had some CSS syntax error which were hard to see.

Is it possible that styled-components logs all syntax errors in the console?
#### Steps to reproduce:

http://www.webpackbin.com/Ek8DrVsRZ
Just remove a colon.

**Comment by mxstbr** [comment]
Yes definitely, #120 is a part of that (see https://github.com/styled-components/stylelint-processor-styled-components) but we should be reporting PostCSS parsings errors too.

**Comment by mxstbr** [comment]
I think with the stylelint-processor being stable we're good to close this, eventually stylis might report faulty CSS in development but it's not too high of a priority anymore.

**Comment by philpl** [comment]
@mxstbr in v3 we could definitely do this (meaning: that'll be the default) :smile: might still be a while off though obviously
