### ISSUE TITLE
It's impossible to extend styled components with attrs

### ISSUE THREAD

**Issue by kajas90** [styled-components/styled-components#1250]
## Version
2.2.0
babel-plugin-styled-components 1.2.0

## Steps to reproduce
Everytime we create styled-components primitive like this one

```
const Param = styled.div`
  order: ${props => props.order};
`
```

and then we will try to extend our component with attributes

```
const Label = Param.attrs({
  className: 'someclass',
})`
  overflow: hidden;
  text-overflow: ellipsis;
`
```

## Expected Behavior
Seems that it should be possible to add attrs to styled primitve component

## Actual Behavior
Error appears
![screen shot 2017-10-17 at 11 38 42](https://user-images.githubusercontent.com/10749622/31657847-c7b6a114-b32f-11e7-8daa-cec94ce7c51e.png)

this code does the trick, but shouldn't be possible to do this with simpler approach?

```
const Label = styled(Param).attrs({
  className: 'someclass',
})`
  overflow: hidden;
  text-overflow: ellipsis;
`
```

**Comment by morajabi** [comment]
Shouldn't this be possible with `Param.extend.attrs({`?

**Comment by philpl** [comment]
Yes, @morajabi is correct. Once a styled component is created it’s unsafe to modify attrs while it might being used.

The safe thing to do is to only allow attrs to be called during construction. This you need to use extend to create a new styled component

**Comment by kajas90** [comment]
okay, thanks!

**Comment by kajas90** [comment]
btw, guys don't you think that this is not that obvious that `attrs` mutate given component instead cloning it?
I have not found in documentation that `attrs` should be used with `extend`

**Comment by morajabi** [comment]
@kajas90 In fact, it's common to use `.attrs` with new components, i.e links:
```
const BlankLink = styled.a.attrs({
  target: '_blank',
})`
  color: blue;
  font-size: 12px;
`
```

Why do you want to use `.attrs` for that purpose? You can just define a new component if you don't want to change/add any of the styles:
```
const Label = props => <Param {...props} someAttr="bla" foo="baz" />
```

**Comment by kajas90** [comment]
Indeed, but I really like this convention and to avoid overriding attrs in every use of given component with your example, passing attrs looks more composable

**Comment by mxstbr** [comment]
Yeah let's add more documentation, PR welcome! https://github.com/styled-components/styled-components-website

**Comment by Undistraction** [comment]
So what is the correct way to official way to set attributes on a custom styled component?  I understand how to do it for a `styled.*` component, but what about when extending?

**Comment by kizu** [comment]
This is something I'd like to have as well. I think it should be totally possible to call `attrs` on any existent styled-component, which shouldn't change the original component, but should return a new one with redefined attrs (merged with those if they were defined before?) in a way `withComponent` or `extend` work.

This would allow to create variations of a component with different sets of attributes. Easiest use case:

``` jsx
const Link = styled.a``;
const ExternalLink = Link.attrs({ target: '_blank' });
```

**Comment by kitten** [comment]
@kizu that's a great idea :+1: but we'll need to think about this `constructWithOptions` stuff in general I think. Right now the code is quite gnarly.

You can already achieve this by doing `Link.extend.attrs()` which is quite explicit. Introducing `Link.attrs` might lead to some confusion 🤔

**Comment by mnpenner** [comment]
To be clear... the syntax for anyone stumbling across this github issue is:

```js
import Button from './Button';

export default Button.extend.attrs({
    type: 'submit'
})``;
```

You need the two backticks at the end even if you don't want to override any styles.

**Comment by JamesGelok** [comment]
⚠️ **For anyone who stumbles on this thread^: [`.extends` was deprecated](https://github.com/styled-components/styled-components/issues/1546#issuecomment-419865424)**
