### ISSUE TITLE
Serverside rendering / client rehydration does not work after there has been a redirect on the server.

### ISSUE THREAD

**Issue by GGAlanSmithee** [styled-components/styled-components#1252]
Serverside rendering / client rehydration does not work after there has been a redirect on the server.

## Version
2.1.2
(not using `babel-plugin-tyled-components`)

## Reproduction
I will try to explain this as well as I can, sorry if I am a bit vauge. It is non-trivial to provide a reproduction.

Using `react-router` I have a protected route, which requires the user to be logged in. If the user is not logged in, it gets reidrected to the login page. After logging in and navigating back to the protected route (so it hits the server), the wrong styles get applied. The only reason that I can see for this happening is that `styled-components` somehow caches the styles the first time the route is rendered and therefor reuses the wrong styles the second time. I have no idea if you are doing something like this though, it's just a guess.

My `styled-components` related code on the server looks like this;

```js

...
const component = (
    <Provider store={store}>
        <RouterContext {...props}/>
    </Provider>
)
    
const sheet   = new ServerStyleSheet()
const styles  = sheet.collectStyles(component) 
const content = renderToString(styles)
const css     = sheet.getStyleTags()
    
const html = renderToString(<Html store={store} content={content} css={css}/>)

res.status(200).send(`<!doctype html>${html}`)
...
```

## Steps to reproduce
1. Access the hidden route on the server (by URL) when you are not logged in
2. Application redirects you to the login screen (this happens on the server)
3. Login
4. Access the hidden (now accessible) route on the server (by URL)

## Expected Behavior
The same styles gets applied on both the server and on the client

## Actual Behavior
The client and server has different styles for the same route

**Comment by GGAlanSmithee** [comment]
There seems to be some caching going on, but I'm not sure how applicable that is to this situation. Shouldn't matter from what I could gather at a quikc glance.

**Comment by philpl** [comment]
@GGAlanSmithee 

- Are you sure you're creating a new ServerStyleSheet for the new route?
- What is the behaviour you're seeing?
- What are the diverging styles?

We'll need some more information to help you out here :wink:

**Comment by GGAlanSmithee** [comment]
@philpl

Thanks for the quick answer.

* Yes, I am creating it in the inner most scope of react router's match callback
* Different css class on server and client (generated, non deterministic)
* Cannot tell as the server styles get overwritten, could just be the css class name which differs

Do you think it could be because I am not using the Babel plugin? At any rate it should provide me with more debuggable output I guess. I will add it and see what happens. I am not at a computer right now, will update with more info when i can.

**Comment by philpl** [comment]
@GGAlanSmithee yes, different classes do hint at the Babel plugin’s ssr feature being needed 😬

**Comment by GGAlanSmithee** [comment]
@philpl 

I followed your advise and added `babel-plugin-styled-components` and it seems like it did the trick! At least I haven't been able reproduce the behavior yet.

For any future googler;

```js
['babel-plugin-styled-components', {
    'ssr' : true,
    // ... other options
}]
```

Thanks for the quick and accurate help. :+1:
