### ISSUE TITLE
Setting styles based on props in stateless functional components

### ISSUE THREAD

**Issue by owenauch** [styled-components/styled-components#1254]
I'm writing a lot of my React Native app using styled-components and stateless functional components, but I can't figure out how to set a styled based on props when using stateless functional components. For example:
```
const Wrapper = styled.View`
background-color: ${props => props.primary ? blue : white};
height: 10;
width: 10;
`

const Component = (props) => (
<Wrapper />
)
```

This doesn't seem to switch based on props. Is this possible to do with functional stateless components and styled-components, or are props not accessible where styles are defined?

**Comment by mxstbr** [comment]
You have to pass the props to your styled component!

```JS
const Wrapper = styled.View`
background-color: ${props => props.primary ? blue : white};
height: 10;
width: 10;
`

const Component = (props) => (
<Wrapper primary={props.primary} />
)
```

**Comment by owenauch** [comment]
Thank you!!!

**Comment by mxstbr** [comment]
No worries, happy to help!
