### ISSUE TITLE
Styled-components errors with React 16 + Typescript

### ISSUE THREAD

**Issue by itsthatguy** [styled-components/styled-components#1255]
## Version
babel-preset-react@6.24.1
react@16.0.0
styled-components@2.2.1
typescript@2.5.3

## Steps to reproduce

1. Upgrade to React 16
2. Create the following code
```typescript
import React from 'react';
import styled from 'styled-components';

interface Props {
  className?: string;
  text: string;
}

class Text extends React.Component<Props, any> {
  public render() {
    const { className, text } = this.props;
    return <span className={className}>{text}</span>;
  }
}

export default styled(Text)`
  color: blue;
`;
```

## Expected Behavior

Component compiles and works

## Actual Behavior

Get the following error:
```
TS2605: JSX element type 'Component<ThemedOuterStyledProps<Props, any>, ComponentState>' is not a constructor function for JSX elements.
```

**Comment by itsthatguy** [comment]
This was caused by yarn cache. Not relevant.

**Comment by meff34** [comment]
@itsthatguy, can you explain, what did you mean about 'yarn cache'?

I get same trouble.

**Comment by mxstbr** [comment]
`rm -rf node_modules && yarn cache clean && yarn`

**Comment by meff34** [comment]
So sad.
I use npm@5.5.1 and as it say, it keeps cache 'guaranteed OK'.

**Comment by edude03** [comment]
I'm having the same issue, but clearing the Yarn cache didn't fix it. How'd you determine the cause @mxstbr / @itsthatguy ?

**Comment by patrick91** [comment]
@edude03 I had a similar issue, I had to make sure that I was only using one version of the react typings (I was having both react 16 and 15 typings)
HTH

**Comment by danmo** [comment]
getting close to 2019, still seeing this issue without a clear explanation on why it happens and an accepted solution for fixing it.

**Comment by probablyup** [comment]
Ask on DT. None of the core team uses typescript

**Comment by OzairP** [comment]
`@type/react@16.7.3` fix this for me

**Comment by brianboyko** [comment]
> Ask on DT. None of the core team uses typescript

I might have to fork this repo then.
