### ISSUE TITLE
BUG REPORT -> Ampersand usage 

### ISSUE THREAD

**Issue by fredconv** [styled-components/styled-components#1258]
## Version
"2.2.1",

## Reproduction

```
const MyComponent = styled.div`
  position: relative;
  ...
 & + & {
   margin-top: 40px;
   background:red;
  } 
 &::before{
    content: '';
    position: absolute;
    .....
  }
 `;
```

## Expected Behavior
'MyComponent' is a div containing other stuff. 
By default it had no margin top defined and a pseudo element set 
If a 'MyComponent' is directly following another 'MyComponent', a extra margin top and a visual red background should be added on the component. 

## Actual Behavior
If i remove the pseudo element (&::before ..) it works fine. but as soon as I add the pseudo element, the pseudo element (&::before) is correctly displayed , but the extra margin + bg color on the MyComponent following another 'MyComponent' (& + &) doesn t work anymore  . 

In a scss project everything is working fine. 
it seems the & is no longer refering to the current component .

**Comment by mxstbr** [comment]
Did you resolve this issue!

**Comment by fredconv** [comment]
Hi, not yet but after investigation it seems the bug is because of some props related code. I'll paste the full bug issue I've encountered and will modify the bug ticket, than only, I'll open it again.

**Comment by philpl** [comment]
The issue is indeed not with the pseudo selector, but it lies in the interpolation + sibling selector: https://github.com/styled-components/styled-components/issues/774

It’s a bug that is well known to us and expected behaviour as far as the logic is concerned.

A workaround is to write “& + {() => MyComponent}” instead
