### ISSUE TITLE
Styled components with HOT RELOAD

### ISSUE THREAD

**Issue by GiancarlosIO** [styled-components/styled-components#1259]
It's about [this](https://github.com/gaearon/react-hot-loader/issues/684) issue.
I'm trying to use react-hot-loader, it works with simple react components but when i try to change the styles for a SC it not update the styles.

Apparently it no update the styles inside the head tag of the html page.
I need a extra configuration for this?

Project:
https://github.com/GiancarlosIO/Django-HMRReact-boilerplate

Thanks!.
![styled-bug](https://user-images.githubusercontent.com/17274950/31864853-94a50244-b72a-11e7-9e19-3e12f622acee.gif)

**Comment by chuson1996** [comment]
Got this too. Need help!

**Comment by mxstbr** [comment]
Yes, this is a bug right now. See #1225, we'll resolve this asap!

**Comment by mhaagens** [comment]
Was just wondering if this bug has been resolved?
Running the latest version with the same problems, have to use a fn call to get HMR back.

**Comment by mxstbr** [comment]
See #1225, PRs fixing this would be appreciated!
