### ISSUE TITLE
[question] Flow coverage?

### ISSUE THREAD

**Issue by iRoachie** [styled-components/styled-components#1262]
## Version
2.1.0

## Reproduction

https://www.webpackbin.com/bins/-KeeZCr0xKfutOfOujxN
https://codesandbox.io/s/rkmNRByE4

Is there anyway to achieve flow coverage inside styled-components declarations?

```js
const Content = styled.div`
  flex: 1;
  overflow: scroll;
`
```

`flow coverage, uncovered code`

**Comment by mxstbr** [comment]
What's the question here?

**Comment by iRoachie** [comment]
Sorry about that

**Comment by relekang** [comment]
Not sure what you mean by inside?

**Comment by iRoachie** [comment]
It's highlighted green, when hover over it shows `uncovered code`. Also running `flow coverage` shows the lines above as uncovered.

![screen shot 2017-10-24 at 2 13 28 pm](https://user-images.githubusercontent.com/5962998/31960358-897448de-b8c5-11e7-8dbf-d076047f0efa.png)

**Comment by VadymBilyy** [comment]
have the same issue, the flow-coverage report indicate styled component as uncovered 
<img width="485" alt="screen shot 2017-10-26 at 14 50 35" src="https://user-images.githubusercontent.com/20760927/32056669-2fd4b5f4-ba5d-11e7-87c0-4981e03eaddf.png">

**Comment by relekang** [comment]
I don't know when I will have time to do anything about this. 

One way to avoid problems were components is wrongly used because of they being inferred as any it can help to do something like:

```
const Component: React.Component<Props> = styled.div``
```

**Comment by iRoachie** [comment]
@relekang Ah okay. It doesn't change anything

**Comment by mwalkerwells** [comment]
Let's move the discussion here: https://github.com/styled-components/styled-components/issues/1321#issuecomment-348711046

**Comment by mxstbr** [comment]
Yep @mwalkerwells, closing in favor of https://github.com/styled-components/styled-components/issues/1321#issuecomment-348711046
