### ISSUE TITLE
Error: Can't collect styles once you've called getStyleTags!

### ISSUE THREAD

**Issue by salimakhtar786** [styled-components/styled-components#1265]
I am using this component `"styled-components": "^2.1.1"` in my VulcanJS app

This code is a server-side code:
```
import { ServerStyleSheet } from 'styled-components';
```
I am using the following code in my app
```
const sheet = new ServerStyleSheet();
console.log(sheet.getStyleTags())
```
`sheet.getStyleTags()` is generating the following error:

```
url:  /
I20171025-11:02:07.279(5.5)? [Error: Can't collect styles once you've called getStyleTags!]
W20171025-11:02:07.292(5.5)? (STDERR) Wed Oct 25 2017 11:02:07 GMT+0530 (IST) 'error while server-rendering' 'Error: Can\'t collect styles once you\'ve called getStyleTags!\n    at ServerStyleSheet.collectStyles (/home/deligence/1.Projects/Streetail/node_modules/styled-components/lib/models/ServerStyleSheet.js:116:28)\n    at generateSSRData (packages/vulcan:routing/lib/server/router.jsx:58:35)\n    at sendSSRHtml (packages/vulcan:routing/lib/server/router.jsx:87:45)\n    at packages/vulcan:routing/lib/server/router.jsx:149:11\n    at /home/deligence/1.Projects/Streetail/node_modules/react-router/lib/match.js:67:5\n    at /home/deligence/1.Projects/Streetail/node_modules/react-router/lib/createTransitionManager.js:108:11\n    at done (/home/deligence/1.Projects/Streetail/node_modules/react-router/lib/AsyncUtils.js:79:19)\n    at /home/deligence/1.Projects/Streetail/node_modules/react-router/lib/AsyncUtils.js:85:7\n    at getComponentsForRoute (/home/deligence/1.Projects/Streetail/node_modules/react-router/lib/getComponents.js:11:5)\n    at /home/deligence/1.Projects/Streetail/node_modules/react-router/lib/getComponents.js:35:5'

```
[Here this is the complete code see the line no- 57 and 59](https://github.com/VulcanJS/Vulcan/blob/master/packages/vulcan-routing/lib/server/router.jsx)

**Comment by mxstbr** [comment]
You have to call `sheet.getStyleTags()` after `sheet.collectStyles()`, then everything will work as expected. Because you `console.log(sheet.getStyleTags())` before `sheet.collectStyles()`, we throw an error when you `sheet.collectStyles` because you've already gotten the style tags.

This is the correct order:

https://github.com/VulcanJS/Vulcan/blob/06b681d36049e1397e3d698cad8b1ac78fd64ec7/packages/vulcan-routing/lib/server/router.jsx#L57-L59

**Comment by kushalmahajan** [comment]
Although, I am writing my sheet.collectStyles before styleTags I still encounter this issue.


`import React from 'react'
import ReactDOMServer from 'react-dom/server';
import { Provider } from 'react-redux';
import { ConnectedRouter } from 'react-router-redux';
import store from '../../src/store';
import {createMemoryHistory } from 'history';
import { StaticRouter } from 'react-router'
import App from '../../src/containers/app';
import { ServerStyleSheet } from 'styled-components'

const path = require('path');
const fs = require('fs');
const history = createMemoryHistory({
  initialEntries: ['/', '/next', '/last'],
  initialIndex: 0
});
const sheet = new ServerStyleSheet();

export default (req, res, next) => {
    const filePath = path.resolve(__dirname, '..', '..', 'build', 'index.html');
    fs.readFile(filePath, 'utf8', (err, htmlData) => {
        if (err) {
            console.error('err', err);
            return res.status(404).end()
        }
        const body = ReactDOMServer.renderToString(
            sheet.collectStyles(
                <Provider store={store}>
                  <ConnectedRouter history={history}>
                    <App />
                  </ConnectedRouter>
                </Provider>
            )
        );
        const styleTags = sheet.getStyleTags();
        var htmlData = htmlData.replace(
                '</head>',
                `${styleTags}</head>`
            );
        var htmlData = htmlData.replace(
                '<div id="root"></div>',
                `<div id="root">${body}</div>`
            );
        return res.send(htmlData);
    });
}
`

**Comment by kitten** [comment]
@kushalmahajan You have to create a **new** `ServerStyleSheet` on every rerender.

Conceptually this is because internally we do store a lot of styles, but for each server-side render you only want the critical ones, the ones that have been used on the given component tree.

**Comment by kushalmahajan** [comment]
Okay. Worked!

**Comment by kushalmahajan** [comment]
Okay. One more issue -  some images are rendered as "Object object" in src.

**Comment by kitten** [comment]
@kushalmahajan That is probably a mistake in your code. Can you please avoid posting on old issues and create a new one instead? :wink:
