### ISSUE TITLE
Feature request, please provide some way of exporting styles in css

### ISSUE THREAD

**Issue by markpradhan** [styled-components/styled-components#1269]
Hi guys,

I've been looking at the other issues mentioning this, looks like it isn't possible.

Although this is ok for most use cases, it blocks us from using services like 'smartlook' and 'mouseflow'. (These are screen recording tools you can use to visually understand how users use your platform. They also help with finding bugs that are very hard to reproduce.)

I know there are limitations because of how styled-components work.

But still, i think we cant ignore that there are services which really need css files to work properly.
In the services i mentioned above, because styling are handled through javascript the whole recording becomes an unclear mess of unstyled elements.

So my question is: will it ever be possible?
If so, i highly recommend you guys mention it somewhere.

(PS. i love how styled components work and we're not dropping it, just kinda feel sad we cant use some services because of it)

**Comment by mxstbr** [comment]
We'll likely not make that happen, but I'm curious: How do smartlook and mouseflow work? Why do they not work with styled-components?

**Comment by markpradhan** [comment]
@mxstbr 
This is the reply we got from mouseflow support.

```
I've investigated the issue and confirmed the cause - Mouseflow automatically strips all javascript from the site when recording data, so all the styling you apply via Javascript will be stripped.

It is possible to work around this issue if you can create a separate CSS file that contains all the styling currently handled by your javascrip, which we can then create a reference to during playback. This CSS file would not need to be loaded on your live site - we can just create a reference to it for playback in Mouseflow.
```

We found a similar service (finally) which works [Session Stack](https://www.sessionstack.com/pricing/).

**Comment by mxstbr** [comment]
That just seems like a very weird thing to do on Mouseflow's part. What are they going to do with any single page application?

There's unfortunately not much we can do to resolve that unfortunately, this is an issue on Mouseflows part and/or you should server-side render your app.
