### ISSUE TITLE
[flow] function call function cannot be called on any member of intersection type intersection

### ISSUE THREAD

**Issue by IljaDaderko** [styled-components/styled-components#1270]
## Version
2.2.2

## Steps to reproduce
1) Implement flow
2) `flow-typed install styled-components@2.2.2`

## Expected Behavior
Should work without abnormal flow errors

## Actual Behavior
Receiving this error
```
 function call function cannot be called on any member of intersection type intersection
```
when doing something like this
```
const SView = styled(View)`
  height: 100%;
  background-color: ${props => props.color};
`;
```

error specifically highlights this line `const SView = styled(View)` when I click through I am referred to this rule in styled-component typed package

```
  declare module.exports: {
    $call: $npm$styledComponents$Call<NativeComponentListKeys>,
```

**Comment by philpl** [comment]
cc @styled-components/typers

**Comment by relekang** [comment]
Which version of flow is this?

**Comment by IljaDaderko** [comment]
@relekang current react native one, 0.53.0

**Comment by mxstbr** [comment]
Any ideas what the issue here is @relekang?

**Comment by relekang** [comment]
My best guess is that we have not typed it correctly in the libdef, there is no test for this use case. I have not worked with react native before so need to look into that to reproduce. It looks like the following works in the libdef tests:

```
styled.View.extend``
```

@IljaDaderko is this a possible workaround?

**Comment by probablyup** [comment]
Hey folks, flow typings for styled-components are located in [flowtyped](https://github.com/flow-typed/flow-typed), so please feel free to move your issue there where you'll receive better community support.

**Comment by hernanif1** [comment]
// $FlowFixMe for now :(

**Comment by probablyup** [comment]
Rather than complain that you have to use a suppression, it would be more productive to offer to help fix it on flow-typed.
