### ISSUE TITLE
Exporting a styled component as default leads to `Prop `className` did not match.`-Warning

### ISSUE THREAD

**Issue by zeemawn** [styled-components/styled-components#1272]
## Version
2.2.2
babel-plugin-styled-components: 1.3.0

## Reproduction
Exporting a styled component as default leads to `Prop `className` did not match.`-Warning

https://www.webpackbin.com/bins/-KeeZCr0xKfutOfOujxN
https://codesandbox.io/s/rkmNRByE4

## Steps to reproduce
Create a JS-file, e.g. named "Flex.js" in which you directly export a styled component:

```
import styled from 'styled-components'

export default styled.div`
    display: inline-flex;
`
```

## Expected Behavior
No warning in browser-console

## Actual Behavior
Warning in the form of ```Warning: Prop 'className' did not match. Server: "Flex-s1rf88eb-0 dMObJs" Client: "Flex___default-s1rf88eb-0 bunKfG"```

**Comment by mxstbr** [comment]
Good catch, mind copying this bug report over to https://github.com/styled-components/babel-plugin-styled-components? 

Thanks!
