### ISSUE TITLE
Copy attrs with extend

### ISSUE THREAD

**Issue by sibelius** [styled-components/styled-components#1274]
I have a common scrollview that has a fixed prop (keyboardShouldPersistTaps) like below:

```jsx
const Scroll = styled.ScrollView.attrs({
   keyboardShouldPersistTaps: 'handled',
})``;
```

I'd like to styled it and create a new component and keep the props defined on attrs, like this:

```jsx
const MyCustomScrollView = styled(Scroll)`
   background-color: #eee;
`
```

is it possible? it is not working like that

styled(Component) and .extend should provide the same behavior?

**Comment by mxstbr** [comment]
> styled(Component) and .extend should provide the same behavior?

Nope. `styled(Component)` only generates a `className` and passes it to `Component`, `.extend` generates a single class from the two style fragment.

I guess `.extend` could also copy `.attrs` maybe? `styled(Comp)` definitely won't though.

**Comment by philpl** [comment]
@mxstbr `.extend` shouldn't influence the attrs actually: https://github.com/styled-components/styled-components/blob/master/src/models/StyledComponent.js#L277

So if the `attrs` do become ineffective when using `extend` then that's a bug

**Comment by mxstbr** [comment]
No I'm saying it maybe should!

**Comment by philpl** [comment]
@mxstbr My bad, I wasn't making that clear; I meant they're not influenced as they should be copied by the rest and subsequent spread here:

```js
const {
          rules: rulesFromOptions,
          componentId: parentComponentId,
          ...optionsToCopy
        } = options

**Comment by sibelius** [comment]
`.extend` works great tks

I think it would be good to have a FAQ about the differences of `styled()` and `.extend`

**Comment by morajabi** [comment]
> I think it would be good to have a FAQ about the differences of styled() and .extend

@sibelius We'll have! Probably we'll merge it tomorrow to the docs.
