### ISSUE TITLE
Suggestion to add section about where its safe to apply HOCs in documentation?

### ISSUE THREAD

**Issue by thomastvedt** [styled-components/styled-components#1278]
Hi, I just wasted a few hours looking for a bug when using styled-components together with redux-form and Formik. I thought it was incompatibility between styled-components and other HOC libraries, but of course it was me doing it all wrong... It would have been really helpful in my case if the documentation on styled-components had a section describing where it's safe to create styled components (apply a HOC). 

It all makes sense to me now, but for a "newbie" (like myself only yesterday) it might not be clear that you should not create your styled components inside render. I found two bugs #143 and #540 both asking the same question as me. 

If you decide to add this to the docs, here is another library that has a good section on it: [redux-auth-wrapper where it's safe to apply HOCs](https://mjrussell.github.io/redux-auth-wrapper/docs/Getting-Started/Overview.html)

Or maybe give a more "complete" example in the basic tutorials, where you place the styled components where they "should" be? :) 

So, it's just a suggestion, feel free to close this if you don't agree ;)

**Comment by mxstbr** [comment]
That's an awesome idea, we should definitely add "Why should I not create styled components in the render method?"! Mind moving this over to https://github.com/styled-components/styled-components-website, or even better submitting a PR with that information added? :blush:

Thanks for noticing and letting us know this was confusing, this kind of thing makes the library and documentation a lot more valuable for everybody!
