### ISSUE TITLE
CSS code for HTML symbols throwing syntax error

### ISSUE THREAD

**Issue by oyeanuj** [styled-components/styled-components#1285]
Hi folks! I'm not sure this is a SC error or a stylis error (or my own), so thought I'd start here. There is a CodeSandbox link reproducing the error. If it is an error on my part, and can be added to docs, I'd be happy to send that PR.

Thank you!

## Version
2.2.3

## Reproduction

https://codesandbox.io/s/knnpn9p0r

## Steps to reproduce
Add CSS code of an HTML sequence in `:before`'s `content` attribute.
```css
&:before {
    content: "\2713";
```

## Expected Behavior
Should display the HTML symbol

## Actual Behavior
Throws the following syntax error:
```
Invalid escape sequence in template
```

**Comment by thysultan** [comment]
Looks like a JavaScript error related to escape sequences in template literals. I get `Octal escape sequences are not allowed in strict mode.` when i try ``"\2713";`` in the console. On the other hand `\\2713` should work.

**Comment by philpl** [comment]
Yes, @thysultan is correct. This has been reported before and it’s because the escape goes to JS as a string first.

This means that you have to escape the backslash, since otherwise JS will try to interpret the escape code for the string itself.

Double backslash should therefore work

**Comment by elliotec** [comment]
Is this in the documentation anywhere? I couldn't find it. Is there any plan to fix it, or can it go in the docs?

**Comment by philpl** [comment]
@elliotec This is not; I'd be happy to review a PR that adds some notes about CSS escape sequences inside template strings to the website  👍
