### ISSUE TITLE
Extending a <ThemeProvider>'d component fails to server side render

### ISSUE THREAD

**Issue by petetnt** [styled-components/styled-components#1289]
This is a weird one: it works properly on the client side, but fails on SSR

## Version
2.2.3

## Reproduction

``` jsx
// Foo.js
import React from 'react';
import styled from 'styled-components';
import Original from './Original';

const Foo = styled(Original)`
  background-color: red;
`;

const theme = {
  color: red;
}

export default () => <Foo theme={theme} />

// Original.js
import React from 'react';
import styled from 'styled-components';

const Title = styled.h1`
  color: ${props => props.theme.color || "blue"};
`;

export default ({ theme }) => (
  <ThemeProvider theme={theme}>
    <Title>HelloWorld!</Title>
  </ThemeProvider>
);
```

## Steps to reproduce

Render Foo.js on server side as well on the client

## Expected Behavior

Equal outputs

## Actual Behavior

The client version works correctly, but SSR version doesn't apply the theme in `Original.js` and the color is `blue` instead of `red`.

**Comment by philpl** [comment]
```
const Foo = styled(Original)`
  background-color: red;
`;
```

^ this is something you should avoid

```js
export default () => <Foo theme={theme}></Foo>
```

^ this actually uses the theme inside the styled-component Foo, but shouldn't pass it on to `Original`.

> The client version works correctly, but SSR version doesn't apply the theme in Original.js and the color is blue instead of red.

^ this I can't debug without more info on the SSR process.

Hope that helps :smile:

**Comment by petetnt** [comment]
Yeah, that component was written just when StyledComponents were released (or at least when ThemeProvider first came up, cannot remember) and I am honestly surprised it works at all. 

That said 

``` js
const Foo = styled(Original)`
  background-color: ${props => props.theme.color};
`;
```

Colors both the text and background red on the client side and only the background when SSR:ing.

The SSR side is fairly basic, and looks like this:

``` js
  ...
  const content = renderToString(
    sheet.collectStyles(
      React.createElement(
        Provider,
        {
          store: mockStore,
        },
        React.createElement(
          StaticRouter,
          {
            location: req.url,
            context,
          },
          React.createElement(ReactApp),
        ),
      ),
    ),
  );

  const styleTags = sheet.getStyleTags();
  ...
  return res.send(RenderedApp.replace('</head>', `<style>${styleTags}</style></head>`));
```

> ^ this actually uses the theme inside the styled-component Foo, but shouldn't pass it on to Original.

I see 🤔

Sorry if the reduced examples aren't much help, scraping them off a much larger codebase currently 😬

Thanks @philpl!

**Comment by philpl** [comment]
so essentially this,

```js
const B = styled.div``
const A = styled(({ theme }) => <ThemeProvider theme={theme}><B /></ThemeProvider>)``
<A theme={theme} />
```

is not supposed to work. So you'll need to change it either way. Also btw `Original` doesn't pass on the `className`.

Apart from that it seems to be impossible for me to go after something here. There's no difference in how the `ThemeProvider` is treated on the server or client, so it's either a usage issue (which most of the problems here point to), or a setup issue.

I'd recommend you to get rid of the pattern described in my example above. And actually, in general, try not to wrap a structural component in a styled HOC.

So, let me propose a solution: I don't think I can track down the bug with the information I have currently. But to fix your problem, make sure that `Foo`, in your example, doesn't use a styled-component AND renders a ThemeProvider.

Does that work?

**Comment by petetnt** [comment]
Like I said, the examples kinda sucks as I reduced it quite hastily (sorry!) things like `className` obviously should be (and are) applied.

And I agree that getting rid of the pattern sucks and shouldn't be used either so getting rid of that is the easiest fix.

However, I do think that there's some weirdness going here. I'll close this issue and reopen it after I have done actual working (broken) MVP you can try out.

Thanks @philpl!

**Comment by philpl** [comment]
@petetnt another quick question, are you seeing a server-client mismatch warning? Rehydration should definitely fail when both SSR and client styles don’t match up

**Comment by petetnt** [comment]
Sorry for getting back so late but I didn't get any errors despite having different outputs 🤔 🤔 

Super weird ¯\\\_(ツ)_/¯ I'll get back to this when I have bit more time, thanks again for your help
