### ISSUE TITLE
if else syntax

### ISSUE THREAD

**Issue by kopax** [styled-components/styled-components#129]
I am trying to create button with styling attributes,

This is not very conveniant but it work.

```JS
const Button = styled.button`
  /* Adapt the colors based on primary prop */
  color: ${props =props.theme.atoms.Button.default.color};
  background: ${
  (props) =>
    // if primary
    props.primary ? props.theme.atoms.Button.primary.background :
    // else if success
    props.success ? props.theme.atoms.Button.success.background :
    // else if success
    props.info ? props.theme.atoms.Button.info.background :
    // else if warning
    props.warning ? props.theme.atoms.Button.warning.background :
    // else if danger
    props.danger ? props.theme.atoms.Button.danger.background :
    // else default
    props.theme.atoms.Button.default.background
  }
  font-size: 1em;
  margin: 1em;
  padding: 0.25em 1em;
  border: 2px solid palevioletred;
  border-radius: 3px;
`;
```

Also eslint is now complaining: 

```
/workspace/github.com/mxstbr/react-boilerplate/app/components/atoms/Button/index.js
   6:12  error  Expected parentheses around arrow function argument            arrow-parens
   8:3   error  Arrow function used ambiguously with a conditional expression  no-confusing-arrow
  10:5   error  Do not nest ternary expressions                                no-nested-ternary
  12:5   error  Do not nest ternary expressions                                no-nested-ternary
  14:5   error  Do not nest ternary expressions                                no-nested-ternary
  16:5   error  Do not nest ternary expressions    
```

I guess there must be a better way.

Thanks in advance for informing me

**Comment by mxstbr** [comment]
Why not do something like this:

```JS
const Button = styled.button`
  background: ${props => props.theme.atoms.Button[props.style].background};
  /* More styles here */
`;
```

Then you can use your different button styles like this:

```JSX
<Button style="primary" />
<Button style="warning" />
// etc.
```

You might now think "but now people can pass wrong values (or even nothing!) into the `style` prop", and you'd be right – except we're talking about a react component, which can have `propTypes` and `defaultProps`! 🎉

```JS
Button.propTypes = {
  style: React.PropTypes.oneOf(['primary', 'success', 'info', 'danger', 'warning'])
}

Button.defaultProps = {
  style: 'default',
}
```

Does that answer the question?

**Comment by kopax** [comment]
Thank you for this advice, yes it answer the question.

Let me ask one more advice:

What is the advantage of your method, and the one from having herited components like

    <Button>Normal<Button>
    <ButtonPrimary>Primary</ButtonPrimary>
    <ButtonSuccess>Success</ButtonSuccess>
    <ButtonInfo>Info</ButtonInfo>
    <ButtonWarning>Warning</ButtonWarning>
    <ButtonDanger>Danger</ButtonDanger>

**Comment by kopax** [comment]
I am sorry but I have to reopen this.

I have tried to change my code with your purposition.

Except I haven't choose "style" key but "nature", "style" is used by react.

Unfortunatly, this code break : 

    import React from "react";
    import styled from "styled-components";
    
    
    const Button = styled.button`
      /* Adapt the colors based on primary prop */
      color: ${props => props.theme.atoms.Button[props.nature].color};
      font-size: 1em;
      margin: 1em;
      padding: 0.25em 1em;
      border: 2px solid palevioletred;
      border-radius: 3px;
    `;
    
    Button.propTypes = {
      nature: React.PropTypes.oneOf([
        "default",
        "primary",
        "success",
        "info",
        "danger",
        "warning"
      ]),
      theme: React.PropTypes.object
    };
    
    Button.prototype.componentWillMount = function(){
      console.log(this.props.theme);
      console.log(this.props.theme.atoms.Button);
      console.log(this.props.nature);
      console.log(this.props.theme.atoms.Button[this.props.nature]);
    }
    
    // Set the default theme, in our case main will be
    // palevioletred if no other theme is specified
    Button.defaultProps = {
      nature: "default",
      theme: {
        atoms: {
          Button: {
            default: {
              background: "yellow",
              color: "palevioletred"
            },
            primary: {
              background: "red",
              color: "purple"
            },
            success: {
              background: "orange",
              color: "yellow"
            },
            info: {
              background: "green",
              color: "blue"
            },
            warning: {
              background: "pink",
              color: "cyan"
            },
            danger: {
              background: "lightblue",
              color: "orange"
            }
          }
        }
      }
    };
    
    export default Button;

I don't know why but if you replace the color line with  

    color: ${props => console.log(props)};

You will see that `props.theme` is just an empty object {}.

However, `props.nature` will be `"default"`, I guess it's inherited from the nature attribute in the jsx, not the defaultProps.

Removing the defaultsProps load the theme correctly.

**Comment by mxstbr** [comment]
> Except I haven't choose "style" key but "nature", "style" is used by react.

Ah yes, of course, I forgot, sorry!

> You will see that props.theme is just an empty object {}.

Yes, this is because you cannot override `props.theme` – it's inherited from the theme passed to a higher up `ThemeProvider`. This is an unrelated bug, see #123 for tracking.

I don't quite understand why you have to put `theme` in the `defaultProps` at the moment, since a `ThemeProvider` exists at the root of the app according to #130?

Why can't you just do this, why do you have to set the `theme` in there? You shouldn't have to.

```JS
Button.defaultProps = {
  nature: 'default',
}
```

**Comment by mxstbr** [comment]
As to answer your first questions

> What is the advantage of your method, and the one from having inherited components like

Why not have both? 

```JS
const ButtonPrimary = props => (
  <Button {...props} nature="primary" />
)
```

*(see [this excellent talk](https://twitter.com/mxstbr/status/789380932709019648) by @chantastic about exactly this topic)*

**Comment by chantastic** [comment]
Thanks for the inclusion :)

**Comment by kopax** [comment]
@mxstbr , I am still stuck in how to do an else if efficently with the current styled component version. 

I can't believe ternary is the only one solution, no one did that before? What is the correct pattern of configuration usage then?

If we can't get use of the variables configuration possibility, I don't see no additional gain to use styled-component over postcss that cannot be globally configured also with variables but at least have syntax color.

**Comment by mxstbr** [comment]
> I am still stuck in how to do an else if efficiently with the current styled component version.

Sorry, I don't quite know why, to be completely honest!

The code above _currently_ does not work due to the bug outlined in #123 – as soon as that's fixed, it will work perfectly fine. What do you not like about that?

----

> Both cannot be configured with global variables but at least you have syntax color, real css files, and still possibility to import variables for each files.

This is a totally different discussion I don't really want to get into in this issue, but here are my thoughts about this:

That's not what `styled-components` is about at all.

`styled-components` is great because it _enforces_ best practices for components (small, focussed, independent, split smart and dumb components, single-use classes) by removing the mapping between styles and the component. With `styled-components`, it's easy write a great component-based system and hard to mess it up.

With just CSS (doesn't matter if vanilla, PostCSS, Sass or whatev) it's the exact opposite – it's easy to mess up your component based system by reusing classes across components, having huge components with lots of business logic and styling, etc. It takes a lot of focussed effort to build a good component-based system with just CSS.

That you write _actual_ CSS code is just an implementation detail, we could've just as well have chose to let you write JS objects for the styles. We didn't, because JavaScript object syntax isn't made for styling, whereas CSS syntax is.

(Also, short note: You can import variables with `styled-components`, and not only that but they're also shared between JS and CSS. You can have syntax color, it exists currently in Atom and will be in Sublime Text soon. Not sure how PostCSS has any benefit in that regard.)

**Comment by kopax** [comment]
> The code above currently does not work due to the bug outlined in #123 – as soon as that's fixed, it will work perfectly fine. What do you not like about that?

I missunderstood, sorry, I am completely OK with that.

> This is a totally different discussion I don't really want to get into in this issue, but here are my thoughts about this...

I've read your though in other threads and thanks for taking the time to share again.

I feel a bit cold changing years of practice. 

Anyway, nobody ever before purposed me to write html once and run it everywhere (:-) so you got 100% of my attention. I will try to use as much as possible styled-components and see where it goes.

**Comment by mxstbr** [comment]
No worries, glad that it's all cleared up now! I'll close this for now, let's track #123, which a PR was submitted for at #132, so it should be done very soon!

**Comment by kopax** [comment]
I'jve just pull `1.0.9` which fix #123 #132 and #136.

The above code doesn't work as expected : 

    const Button = styled.button`
      speak: ${console.log(this)};
      background: ${this.props.theme.atoms.Button[this.nature].background};
      color: ${this.props.theme.atoms.Button[this.nature].color};
    `;

    Button.propTypes = {
      nature: React.PropTypes.oneOf([
        "default",
        "primary",
        "success",
        "info",
        "danger",
        "warning"
      ])
    };
    
    Button.defaultProps = {
      nature: "default"
    };

My theme is loaded as follow : 

    const theme = {
      "base": {},
      "font": {},
      "atoms": {
        "Button": {
          "default": {
            "background": "yellow",
            "color": "palevioletred"
          },
          "primary": {
            "background": "red",
            "color": "purple"
          },
          "success": {
            "background": "orange",
            "color": "yellow"
          },
          "info": {
            "background": "green",
            "color": "blue"
          },
          "warning": {
            "background": "pink",
            "color": "cyan"
          },
          "danger": {
            "background": "lightblue",
            "color": "orange"
          }
        }
      }
    };

    const render = (translatedMessages) => {
      ReactDOM.render(
        <Provider store={store}>
          <ThemeProvider theme={theme}>
            ...
          </ThemeProvider>
        </Provider>,
        document.getElementById("app")
      );
    };

My console show that `this` in css context is just an empty object.

![image](https://cloud.githubusercontent.com/assets/1866564/19717567/7486f19a-9b8b-11e6-9eb8-76d5d621d424.png)

**Comment by kopax** [comment]
You are right, thanks for fixing it that fast. :+1:

**Comment by mxstbr** [comment]
Our documentation has a section about tagged template literals: https://github.com/styled-components/styled-components/blob/master/docs/tagged-template-literals.md

And then [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Tagged_template_literals) is great of course

**Comment by kopax** [comment]
@mxstbr I see, but this is a bit annoying.
This means our class will not be able to be written in class and we will have to use old prototype to store our method is that correct ?

**Comment by mxstbr** [comment]
> This means our class will not be able to be written in class and we will have to use old prototype to store our method is that correct ?

Sorry, how do you mean?

**Comment by kopax** [comment]
Your example to create a styled component involve a syntax like this : 

    const Title = styled.h1`
      font-size: 1.5em;
      text-align: center;
      color: palevioletred;
    `;

It mean if you need to add method you will have to write something like this : 

    Title.prototype.render = function(){
            .....
    }

Instead of storing in a ES6 class. it would be nice to write the css inside a class syntax.


    class Title extends styled.h1 {

              // <- put the css function somewhere inside this
    }

**Comment by vedranio** [comment]
@mxstbr you mentioned above that Atom has syntax support for styled-components. I can't find the package. Is it meant to be this one: https://atom.io/packages/language-styled-css

Getting a 404 page

**Comment by mxstbr** [comment]
@vedranio it's actually now merged upstream into the `language-babel` package! https://github.com/gandm/language-babel

**Comment by alansutherland** [comment]
small aside for anyone reading this now:

I had to import PropTypes likes this

`import PropTypes from 'prop-types'`

and all instances of React.PropTypes change to just PropTypes e.g.

`PropTypes.oneOf([`
