### ISSUE TITLE
[typescript] Property 'FlatList' does not exist on type 'StyledInterface'.

### ISSUE THREAD

**Issue by IljaDaderko** [styled-components/styled-components#1294]
## Version
2.2.3 [native]

## Reproduction
```
const StyledFlatList = styled.FlatList``;
```

this results in error

> Property 'FlatList' does not exist on type 'StyledInterface'.

**Comment by VintorezVS** [comment]
+1

**Comment by philpl** [comment]
cc @styled-components/typers

**Comment by probablyup** [comment]
Is this still a thing?

**Comment by AharonDror** [comment]
Still a thing in version 3.3.3

**Comment by probablyup** [comment]
Hey folks, TS typings for styled-components have been moved to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), so please feel free to move your issue there where you'll receive better community support.
