### ISSUE TITLE
Identical styled generating different classnames

### ISSUE THREAD

**Issue by johnnyBira** [styled-components/styled-components#1299]
## Version
2.2.1

Hi!
I'm writing a HOC for wrapping and enhancing my styled component. I know this kind of pattern has been frowned upon in previous issues (#316), and without going into the details of what my HOC is doing, just trust me when I say I have a valid use case.

To enhance my wrapped component I'm parsing it's props and generate some styles which I then pass to the `styled` method of `styled-components`, passing in my `WrappedComponent` to be used as a base.
My only problem with this approach is that even though I generate the exact same styles a unique class name is created for every component. I'm concerned that this might turn into a performance hog in the long run and would like to know if there's a better way to "inject" styles into an existing component.

**Comment by philpl** [comment]
> My only problem with this approach is that even though I generate the exact same styles a unique class name is created for every component.

That sounds either like you're confusing the static and dynamic class we create, or it sounds like you're recreating the styled component on every render.

> I'm writing a HOC for wrapping and enhancing my styled component. I know this kind of pattern has been frowned upon in previous issues (#316), and without going into the details of what my HOC is doing, just trust me when I say I have a valid use case.

It's not encouraged for a reason, and I don't think there is **any** valid use case to be honest. Sorry, if that comes across as harsh, but HOCs for styling do not scale, and we do not want to recommend them, or be associated with the pattern :smile:

**Comment by johnnyBira** [comment]
Thank you for the fast reply @philpl !

**Comment by johnnyBira** [comment]
Thank you for the fast reply @philpl !

I do understand the concept of dynamic and static styles, but looking at the docs I can't find any other way to compose and reuse functionality the way I would like to.

To give you some context the goal of my HOC is to provide a centralised way of dealing with different breakpoints. The enhanced components receives props in the following format
```javascript
<Column columns={{ x: 2, l: 3, xl: 4 }} />
```
Where the name/key `columns` corresponds to the name of a function/mixin and the value of x, l and xl becomes it's input. I like this approach because it's compassable and provides a common API for dealing with responsive styles in a conditional way.

Could you recommend any other way of achieving the same result with a different pattern?

**Comment by johnnyBira** [comment]
> That sounds either like you're confusing the static and dynamic class we create, or it sounds like you're recreating the styled component on every render.
Is it an expected behaviour for the "dynamic classes" to always get a unique class-name, regardless if i.e. two two created components receive identical props?
In that case I might have come up with a functioning solution to my problem.

**Comment by johnnyBira** [comment]
> That sounds either like you're confusing the static and dynamic class we create, or it sounds like you're recreating the styled component on every render.

Turns out you were spot on with this comment :D I was both confusing the dynamic and static classes AND recreating the styled component on every render, haha.

Moving the styled component out of render solved that issue. Thank you.

I just have one more questing. Is it an expected behaviour for the dynamic classes to always get a unique class-name, regardless if i.e. two created components receive identical props?

**Comment by philpl** [comment]
@johnnyBira the dynamic class is generated from the generated CSS string. So if you pas the same props, into the same interpolations, generating the same CSS string, you can expect the dunamicclass not to be duplicated.

I’d suggest you to take a look at the css helper, which you can use to apply a mixin pattern. There’s an example here: https://www.styled-components.com/docs/advanced#media-templates and some API descriptions here: https://www.styled-components.com/docs/api#helpers

Essentially you can use it statically by having some interpolations in it or produce one in a factory function. You can then apply it to a styled component by putting it into a interpolation there.

This encourages you to keep styled components as leaf components, I.e. you’d avoid wrapping **any** is your own components using styled.

This scales really well and you’ll always know where to look for styles. Wrapping your own non-styled components encourages you instead to refer to children, scatter the styling, and to resort to higher specificity to resolve problems. I’ve written about this in some other issues, which I can’t find now unfortunately

**Comment by johnnyBira** [comment]
@philpl , thank you for taking the time to explain.

I am using the CSS helper and the mixin pattern with interpolation inside my HOC. What mixins/functions the HOC should handle at each breakpoint are passed as arguments to the HOC, tougehter with the wrapped component, making it easy to follow what styles can be applied.

As I see it I'm basically doing what you describe except I've abstracted it inside the HOC. I guess that's why I still struggle to see why this would be a bad pattern.

Let me know if you find the issues you mentioned.
I'm planing to release this as a package and would be very interested in your feedback on the matter.

**Comment by philpl** [comment]
@johnnyBira I'd still recommend you **not** to abstract styling into HOCs. It doesn't make much sense either, since the layouting logic will be quite contained, judging from the examples.

Anyway, I hope I answered all your questions for you :smile:

**Comment by johnnyBira** [comment]
I totally see your arguments agains doing this, personally I think the pros overweight the cons in this particular case.

Another reason for this approach in my option is portabilty. Imagine you've defined media querie with their responsive styles, encapsulated inside each styled component.
Now you want to reuse the component in another project with different breakpoints.
This logic could of course be tailor for every individual component, but I still prefer not having to repeat that logic and also have a common API for responsive props.

Thank you @philpl you've been very helpful.
