### ISSUE TITLE
Where to define site font

### ISSUE THREAD

**Issue by kopax** [styled-components/styled-components#130]
I am trying to get the phylosophie of styled-components about styling a web page.

For example, should the webpage have a font and component could inherit from it.

This way, if the components is imported in another project, we don't have to care about the old fonts.

Or should we just template the font-family and reimport it in every component.

This sounds a bit odd, but could bring some nice advantages.

Any ideas are well apreciated

## Version
1.0.5

**Comment by mxstbr** [comment]
That's a very philosophical questions we're just discussing in #113! I think it should be a theme, since with an import you'd have to have that file in every project you do.

**Comment by kopax** [comment]
So you think we should be able to configure the whole web application for general styles.

I don't understand what #113 is about, your solution sounds a bit complicated.

I have implemented theming this way : 

    - app
    | - myCoolTheme
        | -  atoms
            | - Button.js
            | - index.js
        | -  molecules
            ...
        | -  organism
            ...
        | -  templates
            ...
        | -  atoms
            ...
        | - index.js

In `app/myCoolTheme/index.js`

  import atoms from "./atoms";
  
  export default {
    atoms
  };

In `app/myCoolTheme/atoms/index.js`

    import Button from "./Button";

    export default {
      Button
    };

In `app/myCoolTheme/atoms/Button.js`

    export default {
      default: {
        background: "yellow",
        color: "palevioletred"
      },
      primary: {
        background: "red",
        color: "purple"
      },
      success: {
        background: "orange",
        color: "yellow"
      },
      info: {
        background: "green",
        color: "blue"
      },
      warning: {
        background: "pink",
        color: "cyan"
      },
      danger: {
        background: "lightblue",
        color: "orange"
      }
    };

In my `app/components/atoms/Button/index.js` __Note: this modification is currently not working (see #129)

    import React from "react";
    import styled from "styled-components";
    
    
    const Button = styled.button`
      /* Adapt the colors based on primary prop */
      color: ${props => console.log(props)};
      font-size: 1em;
      margin: 1em;
      padding: 0.25em 1em;
      border: 2px solid palevioletred;
      border-radius: 3px;
    `;
    
    Button.propTypes = {
      nature: React.PropTypes.oneOf([
        "default",
        "primary",
        "success",
        "info",
        "danger",
        "warning"
      ]),
      theme: React.PropTypes.object
    };
    
    Button.prototype.componentWillMount = function(){
      console.log(this.props.theme.atoms.Button[this.props.nature]);
    }
    
    // Set the default theme, in our case main will be
    // palevioletred if no other theme is specified
    Button.defaultProps = {
      nature: "default",
      theme: {
        atoms: {
          Button: {
            default: {
              background: "yellow",
              color: "palevioletred"
            },
            primary: {
              background: "red",
              color: "purple"
            },
            success: {
              background: "orange",
              color: "yellow"
            },
            info: {
              background: "green",
              color: "blue"
            },
            warning: {
              background: "pink",
              color: "cyan"
            },
            danger: {
              background: "lightblue",
              color: "orange"
            }
          }
        }
      }
    };
    
    export default Button;

in `app.js` ,  I initialize the theme applied to my site

    const render = (translatedMessages) => {
      ReactDOM.render(
        <Provider store={store}>
          <ThemeProvider theme={theme}>
            <LanguageProvider messages={translatedMessages}>
              <Router
                history={history}
                routes={rootRoute}
                render={
                  // Scroll to top when going to a new page, imitating default browser
                  // behaviour
                  applyRouterMiddleware(useScroll())
                }
              />
            </LanguageProvider>
          </ThemeProvider>
        </Provider>,
        document.getElementById("app")
      );
    };

Then in the a lambda React component : 

        <Button nature="default">Normal</Button>
        <Button nature="primary">Primary</Button>
        <Button nature="success">Success</Button>
        <Button nature="info">Info</Button>
        <Button nature="warning">Warning</Button>
        <Button nature="danger">Danger</Button>

This way, I have basic styling and I can provide components base styling.
I can just replace the load another template by creating another tree next to `themes/myCoolTheme`.

Is this what your trying to achieve or you see cons ?

**Comment by mxstbr** [comment]
Yes this sounds good to me!

**Comment by kopax** [comment]
This way we could use the same var configuration in components to store the global font family.

In order for this to work in another project you will have to create the configuration with the same tree.
