### ISSUE TITLE
addEventListener is undefined

### ISSUE THREAD

**Issue by tgdn** [styled-components/styled-components#1300]
Not entirely sure this is a bug, but not being able to use `addEventListener` is a little annoying. This obviously can be bypassed by using props such as `onMouseDown` etc...

But sometimes there is a need for more control on whether there is an event listener or not on some DOM element and it just looks cleaner to have it all done in componentDidMount and componentWillUnmount.

## Version
2.2.3

babel-plugin-styled-components: v1.3.0

## Reproduction

https://codesandbox.io/s/yvx5w2w9x9

## Steps to reproduce

See comments in codesandbox. Uncomment addEventListener for Title component.

## Expected Behavior

Event listener is added and no error is thrown when trying to use addEventListener on styled component.

## Actual Behavior

`addEventListener is not a function` because it is undefined.

**Comment by mxstbr** [comment]
You have to use `innerRef`. See https://www.styled-components.com/docs/advanced#refs for more information.
