### ISSUE TITLE
Targeting Of Child Component Instances

### ISSUE THREAD

**Issue by Undistraction** [styled-components/styled-components#1302]
It feels like styled-components examples and docs are missing support for a common pattern in styling. I've read through the docs and lots of related issues without finding an answer. Sorry if I'm missing something obvious. This subject is partially covered in the FAQs, but the discussion stops short of needing to target specific child instances.

Obviously one of the main goals of styled-components is to make these components as reusable as possible. Using Flexbox is really helpful for linear layouts and we can use descendent selectors so that a parent doesn't need to know or care about what its children are:
```
> * + * {
  margin-left: ${h-spacing(1.5)};
}
```

However in many situations, a parent needs to be able to target individual children for layout as they need to be treated in a non-linear way. In such cases, I am aware that I can target classes of child components using interpolation:
```
> ${Example} { ... }
```

Although this is far preferable to targeting elements using descendant selectors, it is still quite brittle. If a child component is swapped out for another, the layout breaks. I've always followed a pattern where a component should only be responsible for laying out its children - not itself and I'm treating this as axiomatic. I find this makes components much more reusable, focussed, and pushes you into using specialised layout components (which don't mix lipstick styles and layout styles). Using BEM, this works by classing the child components using a 'slot' class, using something like:
```
.Container-alpha { ... };
.Container-bravo { ... }:
.Container-charlie { ... };
```
With this pattern these classes are effectively declaring slots in the parent component. It doesn't matter what the children are as long as they are classed with the appropriate slot as well. 

```
<div class="Container">
  <div class="Container-alpha Delta">...</Container>
  <div class="Container-bravo Echo">...</Container>
  <div class="Container-charlie Foxtrot">...</Container>
</div>
```

This pattern can be improved upon at the expense of more markup by using a separate layer of elements:
```
<div class="Container">
  <div class="Container-alpha>
    <div class="Delta">...</div>
  </Container>
  <div class="Container-bravo">
    <div class="Echo">...</div>
  </Container>
  <div class="Container-charlie">
    <div class="Foxtrot">...</div>
  </Container>
</div>
```

When using styled components, the first variation is not possible. The second variation is possible, and allows children that are not also styled-components to be laid out. Effectively this means declaring a new styled component for each slot - and crucially it doesn't matter whether or not `Delta`, `Echo` and `Foxtrot` are styled components or not:
```
<Container>
  <ContainerAlpha>
    <Delta />
  </ContainerAlpha>
  <ContainerBravo>
    <Echo />
  </ContainerBravo>
  <ContainerCharlie>
    <Foxtrot />
  </ContainerCharlie>
</Container>
```

Using this pattern, each of the Container sub-components act only as a means of the Container targeting them to lay them out - they don't have any styles of their own:
```
const ContainerAlpha = styled.div``;
const ContainerBravo = styled.div``;
const ContainerCharlie = styled.div``;

const Container = styled.div`
   > ${ContainerAlpha} { ... }; 
   > ${ContainerBeta} { ... }; 
   > ${Containerharlie} { ... }; 
`;
```

Given that these children are without styles of their own, they are effectively completely generic. Their entire purpose is to act as a hook for the container. If they are renamed as such, and we are careful to always use direct descendant selectors in our containers to avoid inadvertently selecting grandchildren, we can potentially use these slot components where ever we like:

```
<ContainerAlpha>
  <SlotOne>
    <Delta />
  </SlotOne>
  <SlotTwo>
    <Echo />
  </SlotTwo>
  <SlotThree>
    <Foxtrot />
  </SlotThree>
</ContainerAlpha>
<ContainerBeta>
  <SlotOne>
    <Delta />
  </SlotOne>
  <SlotTwo>
    <Echo />
  </SlotTwo>
</ContainerBeta>
```

Whilst this cuts down on the number of styled components, it also makes the relationship between container and slots much less obvious.

**So what is the 'styled-components way' of achieving the styling of subcomponents in situations where the following are true?**

- A generic descendant selector cannot be used because finer-grained control is needed.
- The children are not styled components (they are vanilla React components), or are the same styled component but need to be laid out differently from one-another (therefore precluding  an interpolation).

**Comment by mxstbr** [comment]
FWIW, we highly discourage targetting specific children from a parent. As you can see in the docs too, we recommend targetting yourself from specific parents, so all the styling for a component stays at the same place.

That being said, if you're set on sticking to your old ways why not just keep using classes like you did anyway?

```HTML
<Container>
  <Comp1 className="Container-alpha>
    <Comp2 className="Delta">...</Comp2>
  </Comp1>
  <Comp1 className="Container-bravo">
    <Comp2 className="Echo">...</Comp2>
  </Comp1>
  <Comp1 className="Container-charlie">
    <Comp2 className="Foxtrot">...</Comp2>
  </Comp1>
</Container>
```

Doesn't matter wether they're styled or normal React components, you can now do:

```JS
const Container = styled.div`
   > .Container-alpha { ... }; 
   > .Container-bravo { ... }; 
   > .Container-charlie { ... }; 
`;
```

**Comment by Undistraction** [comment]
> FWIW, we highly discourage targetting specific children from a parent. As you can see in the docs too, we recommend targetting yourself from specific parents, so all the styling for a component stays at the same place.

But doesn't this make the children far less portable? By doing this you are binding the component to its context. Or are you suggesting each component should define its layout for every context in which it will appear?

**Comment by philpl** [comment]
> But doesn't this make the children far less portable?

The selectors make it far less portable and manageable, in both ways. So the best solution is to avoid them altogether, but practically the rule of thumb is to keep all styling relevant to a styled component with that styled component.

This will prevent you from guessing where some extra styling is coming from in your codebase.

(reference to the docs: https://www.styled-components.com/docs/faqs#can-i-refer-to-other-components)

**Comment by mxstbr** [comment]
> Are you suggesting each component should define its layout for every context in which it will appear?

Yes.

```JS
const Child = styled.div`
  // Normally I'm blue
  color: blue;
  // But within a container I'm red
  ${Container} & {
    color: red;
  }
`
```

That makes it so that all the styling related to that one component is in the same place. Otherwise you'll end up with semi-global styling all over the app again, which leads to annoying bugs where you're trying to track down where a CSS rule is coming from but you have no idea.

> This doesn't make sense in the context of styled-components because the class for Container is being generated, so the link between the Container class and the child classes is lost - the container won't have the class of Container, so calling its children Container-alpha etc doesn't really make sense.

Your component is called `Container`, so obviously the `.Container-alpha` class is related to it? I don't understand why the `Container` not having a class has anything to do with it, but you can also add another class to that component if that makes you happy:

```html
<Container className="Container">
  <Comp1 className="Container-alpha">
    <Comp2 className="Delta">...</Comp2>
  </Comp1>
  <Comp1 className="Container-bravo">
    <Comp2 className="Echo">...</Comp2>
  </Comp1>
  <Comp1 className="Container-charlie">
    <Comp2 className="Foxtrot">...</Comp2>
  </Comp1>
</Container>
```

There you go, now the Container will also have a class of `Container`! :blush: 

> Is there any discussion regarding the decision not to support this pattern anywhere?

What? We support this pattern. How did you come to the conclusion that we a) don't support it and b) consciously decided so? We totally support this pattern, in fact you can do it in a myriad of different ways as you've elborated yourself.

If you have any furhter ideas how we can make this use case better please let us know, we'd be happy to discuss any additional APIs that you feel could make your life easier here.

**Comment by Undistraction** [comment]
@mxstbr I'm sorry if I came off as brusque. I've only been using styled-components for a few days and this is the only thing that I'm struggling to understand how to approach. I know it might be a matter of changing how I do things and my post was a bi-product of the process of tying to understand the system.

I'll try and make the case better as I think this is a potentially useful discussion. It feels like there is a distinction between layout properties and aesthetic properties (color, background, font etc) and though I can absolutely see the benefit of using the reverse-selector pattern for these aesthetic properties, when it comes to layout I think this no longer holds true. The special case of layout and the fact it straddles styling and markup, parent and child, has always been a troublesome area for UI frameworks and libraries going back as far as I can remember. In the past I have found using very focused components that are solely responsible for laying out their children to be a good way of solving some of these problems. 

I think I probably need to spend some more time with styled-components and see if I can come up with some more practical use cases and actionable issues.

**Comment by mxstbr** [comment]
Yep I agree totally agree with using layout components! That's why we advocate using something like `grid-styled`, `hedron` or any other of those component-based grid systems, I don't know if there's anything we can do inside of styled-components to improve that use case though.

**Comment by Undistraction** [comment]
The problem with that kind of approach is you are encoding layout into the container props. For me this whole thing falls apart if you start passing css props into components. There needs to be a layer of separation - the canonical primary button example makes sense because what primary actually is has nothing to do with the property - the property is semantically decoupled from the selectors that will make it primary. However with `grid-styled`, widths and box model props are being passed straight in. OK they are named differently, but they have a direct analog in css styles. With `hedron` This is exactly the coupling that needs to be avoided. Surely props should tell the component what it is, not how to be that thing. I've seen this done with flexbox where a `vertical` or `horizontal` prop is passed in, but this feels like a terrible idea - what happens when you want to switch direction at a breakpoint? I prefer for the implementation of layout to be handled by the layout component itself - yes it means the component isn't usually reusable, but it is small and focussed, and it its styles are not being passed in as props. 

I know this goes back to the old argument of whether you should class elements with `grid-col-4` vs using a mixin within a semantic class, but given how well you handle the idea of mixins using interpolations, that feels way more in keeping with how you do things than adding this via props.

I totally understand why people love the idea of grid classes / grid props on elements. It does make things easier to reason over and that is by no means a small thing, however this quickly gets clouded by needing to add additional classes / props for different breakpoints.

**Comment by philpl** [comment]
@Undistraction I agree, for different grids I personally prefer to share only mixins at most, and not use configurable props. Something like dimensions are most of the times in themes, the specifics of the styling in the context of such a container element should just be where the container is used, so I'm totally against reusable container components that accept arbitrary values.

So, feel free to find your own way here, and we do not offer up a lot of best practices apart from the enforced ones. And that's on purpose, because most people gravitate towards the same patterns, and only rarely to some special ones.

But apart from that, the ones that we do warn about, should be avoided. We're careful with our advices, so the ones we do give, are best to be taken to heart most of the time.

So I hope this discussion has helped you to shape an idea of how you'd like to structure your projects :smile:

**Comment by Undistraction** [comment]
Thank you. Yes it has been very helpful. And thank you all for putting styled components together. Now I've spent a few days with it I'm really impressed. I love how simple it is - it has enough flexibility to support my prefered approach without feeling like I'm bending it too far. Not felt comfortable with any CSS-in-JS solution until using this one :)

**Comment by Richacinas** [comment]
@mxstbr 

The piece of code where you are referring to a parent (Container) and styling based on the child living inside it, doesn't work.

```
const Child = styled.div`
  // Normally I'm blue
  color: blue;
  // But within a container I'm red
  ${Container} & {
    color: red;
  }
`
```

In the end, my feeling is you have to keep passing props to the child in order to cover all the possible scenarios of styles that an element could have. This way, it is not very clear what names to choose for these props because they are just meant for a set of styles.

Don't you think that it would be better to actually be able to refer to a parent the way you wrote?

Thanks a lot

**Comment by mxstbr** [comment]
That should work. If it doesn't please submit a reproduction and a bug report!

**Comment by Richacinas** [comment]
It works, but it applies the style always. Doesn't care about the container wrapping.

**Comment by mxstbr** [comment]
Can you show us a reproduction please? That would help us narrow down the issue.

**Comment by Richacinas** [comment]
Here it is @mxstbr : 

[New Issue](https://github.com/styled-components/styled-components/issues/2264)

**Comment by fabb** [comment]
@Undistraction so what‘s your preferred approach for applying layout styles to layout components and their render slots/children nowadays?

**Comment by Undistraction** [comment]
@fabb I use a variety of techniques depending on circumstance. 

I try to use shallow descendant selectors where it makes sense - where the relationships are generic and don't make assumptions on order, except for example using first or last child to control spacing between elements.

Sometimes I'll use wrappers to target children, but this can end up adding a lot of unecessary extra elements to the DOM in cases where a component is repeated. 

I do occasionally add a class to a child to target it, but I don't like doing it and having to explicitly pass classmate down to a layout SC makes this clunky. Instead, I much prefer to use the Babel plugin to add the component name to SC's generated classes and use selectors to target those (using partial matches as the hash will change).

None of these approaches are entirely satisfying. Imho this is the single biggest weakness of SC's API - that you can only interpolate an SC, but not a generic React component.

**Comment by fabb** [comment]
Thanks for your thorough answer! I just started with SC, and want to do some nested flexboxes (with different layouts for different media queries) and want to avoid too many wrapper elements.
