### ISSUE TITLE
Access to the theme in the injectGlobal helper

### ISSUE THREAD

**Issue by Spy-Seth** [styled-components/styled-components#1303]
## Version
2.2.2

## Reproduction

https://codesandbox.io/s/74mwq5936

## Expected Behavior
We should have access to the theme data inside the `injectGlobal` helper:
```js
injectGlobal`
  body {
    color: ${({theme}) => theme.fontColor}; // Should works
  }
`;
```

By decorating the `injectGlobal` I could succeed to have the theme for the root `injectGlobal` scope. But this is a dirty hack. And this do not give acces to the theme in the _child_ context (in a mixin for example, see the given codesandbox playground)

## Actual Behavior

The theme is not accessible from the `injectGlobal` context

```js
injectGlobal`
  body {
    color: ${({theme}) => theme.fontColor}; // Fails, no theme in this context
  }
`;
```

**Comment by morajabi** [comment]
@Spy-Seth Why don't you just export your theme object and import it where you're using `injectGlobal`? `injectGlobal` only invokes once and on the initial render so you won't gain anything from having the theme inside `${}`.

**Comment by mxstbr** [comment]
This is because `injectGlobal` is not rendered inside the component context. You should export your theme object and use that directly:

```JS
import { theme } from './somewhere';

injectGlobal`
  color: ${theme.primaryColor};
`
```

**Comment by mxstbr** [comment]
Ahh, @morajabi was quicker! :grinning:

**Comment by Spy-Seth** [comment]
> Why don't you just export your theme object and import it where you're using `injectGlobal`?

I could not simply import my theme, it's generated dynamically at runtime and injected in the `ThemeProvider`: I have no file to import that contain it. That's why I'm trying to access it from the parent context 😕 

Did you think it's impossible too have it inside the `injectGlobal` helper?

**Comment by mxstbr** [comment]
It's impossible with the current API, yes. The theme is passed via the React context feature, which only exists for the component tree. `injectGlobal` is outside of the component tree though.
