### ISSUE TITLE
Adapting based on props bug

### ISSUE THREAD

**Issue by jbw** [styled-components/styled-components#1304]
## Reproduction

https://codesandbox.io/s/w6n0p8ynj7

## Expected Behavior

I expect the buttons to have 'primary' or 'normal' text on them.

## Actual Behavior

No text (content) set on the button.

**Comment by philpl** [comment]
This is a usage problem, and here's a fix: https://codesandbox.io/s/346wkk1mm

If you write:

```js
styled.button`
  content: ${"text"};
`
```

Then `"text"` here is a string in JS, but the quotes in the generated CSS are missing.
Thus you have to write:

```js
styled.button`
  content: '${"text"}';
`
```

To generate `content: 'text';` and not `content: text;` which is invalid

**Comment by jbw** [comment]
@philpl I did check DevTools and this isn't what I saw. I saw property value invalid. Also the example you posted is no different to mine and doesn't show a fix.

**Comment by philpl** [comment]
@jbw Sorry, I accidentally removed the pseudo selector in the CodeSandbox, which is now updated. If you follow the hint about the quotes it'll work just fine.

**Comment by 3s2branches** [comment]
> This is a usage problem, and here's a fix: https://codesandbox.io/s/346wkk1mm
> 
> If you write:
> 
> ```js
> styled.button`
>   content: ${"text"};
> `
> ```
> 
> Then `"text"` here is a string in JS, but the quotes in the generated CSS are missing.
> Thus you have to write:
> 
> ```js
> styled.button`
>   content: '${"text"}';
> `
> ```
> 
> To generate `content: 'text';` and not `content: text;` which is invalid
> 
> Edit: Btw, I'd suggest to always look at the DevTools in your browser. This way it's clearly visible that something's missing 😄
> 
> <img alt="screen shot 2017-11-09 at 21 41 40" width="150" src="https://user-images.githubusercontent.com/2041385/32631025-cb8c2588-c596-11e7-95a0-5096fe2a8b41.png">

I feel straight up retarded when i do things like this

**Comment by kitten** [comment]
@3s2branches Please refrain from using words like "retarded". Our code of conduct is quite clear about this https://github.com/styled-components/styled-components/blob/master/CODE_OF_CONDUCT.md#our standards

Also replying to a closed issue a year after is counterproductive, so please open a new issue if you'd like to voice concerns, propose new features or changes, or ask questions. Cheers 🙌
