### ISSUE TITLE
Styles not injected when importing another package that uses styled-components (via a monorepo)

### ISSUE THREAD

**Issue by gausie** [styled-components/styled-components#1305]
I have a monorepo with a component library that is built using Babel. The moment styled-components is imported in that library, the styles stop being injected to the page in the parent project (that also uses styled-components).

**Comment by mxstbr** [comment]
This is probably because you then have two different styled-components version on the page. Remove one of them.

See #1011

**Comment by gausie** [comment]
@mxstbr but if the library and main package both used `styled-components` to create React components, how can I remove one of them?

**Comment by mxstbr** [comment]
That depends entirely on your build setup. How are you building the component library?

**Comment by gausie** [comment]
Using babel directly from the package.json file. So is the solution to pass through a reference to the parent's instance of styled-components (or visa versa)?

**Comment by gausie** [comment]
peerDependencies worked!

**Comment by mxstbr** [comment]
Awesome, great to hear!

**Comment by BiancaYen** [comment]
Good day! I'm having the same issue - can I please send someone my webpack / package.json files so they can confirm if I'm including styled components correctly.

**Comment by gausie** [comment]
I'm waiting for #1102 to be merged to see if there is a better way to solve
this, as peer dependencies is causing a real poor developer experience.

**Comment by philpl** [comment]
@gaysie I’m sorry you feel this way, but while this could pose as a different solution, this could lead to you accidentally including the library twice, which you probably do not want.

There’s some nice tools to make monorepos and peer dependencies play nicely, for instance there’s lerna.

**Comment by gausie** [comment]
I am using lerna and it doesn't really help. And it's spelt @gausie 😉

**Comment by philpl** [comment]
@gausie sorry, I was on my phone 😅What exactly do you mean by a poor dev experience? Anything we can do there? Because it'd be a real shame if we'd be pushing people to include styled-components twice in their final product 😿

**Comment by gausie** [comment]
Haha thank you!

Well basically when we are consuming a library in the monorepo from an
application in the monorepo, we want it to use the parent's
styled-components. However, when we're using styleguidist (for example)
directly in the library, it needs to bring its own styled-components cause
there isn't a parent peer to inherit it from.

At the moment we have to add and remove the styled-components folder from
node_modules of the library depending on the situation because node seems
to always resolve to the local copy of the library, ignoring
peerDependencies if it can.

Does that make sense?

**Comment by rayjsiu** [comment]
For those experiencing this issue or issue #1032 :
My situation was I built a private library using styled-components.
Note that I used the create-react-library project to build my private library.
I have a project that itself uses styled-components and I am using create-react-app with dynamic imports (code-splitting) to load a route that imports the private library.
Upon loading the private library, it was trying to load styled-components and thus overwriting the <style> tag on the SPA and I would be losing a bunch of styles on my styled-components.

Solution:
In the private library's package.json, I declared styled-components in both `"devDependencies"` and `"peerDependencies"`, removed styled-components from the `"dependencies"` and then in the webpack.config.prod.js config that builds the library, I declared styled-components as part of `"externals"`.
`
externals: {
   'react': 'react',
   'react-dom': 'react-dom',
   'styled-components': 'styled-components'
  },
`

No more conflicts in the main project. :smile: 
I hope this helps someone in the same situation.

**Comment by philpl** [comment]
@rayjsiu exactly what I’d recommend :) I’d also mention that the module alias Babel plugin is nice if Webpack is not being used. For SSR without transpilation there’s module-alias too.

@gausie I know that this is highly confusing but unfortunately it’s out of our hands as far as monorepos go.

**Comment by codeflyer** [comment]
I had the same issue.

My configuration was made by a Lerna repo with the main app as a package of the mono repo.

I've tried everything written here above but continued to have the issue.

I've solved referencing directly the module from the file system:


```
  // component-package/package.json
  "peerDependencies": {
    "styled-components": "^3.4.5"
  },
  "devDependencies": {
   ...
    "styled-components": "file:../main-app/node_modules/styled-components"
  }
```


```
  // main-app/package.json
  "dependencies": {
   ...
   "styled-components": "^3.4.5"
  }
```
 
Now everything is working perfectly, I can run storybook on the component package and run the app without any issue.

**Comment by jbuschke** [comment]
I'm facing this issue now and couldn't yet resolve:

I have a library project that uses styled-components as peer and dev-dependency. I have my an app project which uses styled-components as a dependency. Styles are not correctly applied in the app project.

The app project references the library project with a local npm (file:.../my-lib) project reference.

Imho this setup should work out of the box, without ejecting my cra app and fiddling with webpack. What is the root issue here?

**Comment by probablyup** [comment]
https://www.styled-components.com/docs/faqs#duplicated-module-in-node_modules

**Comment by jbuschke** [comment]
Thanx for the link. Im now using `resolve: { modules: [path.resolve(appFolder, "node_modules"), "node_modules"],  }`
to prioritize the apps node_modules over my linked project ones.
Unfortunatly I need to eject, but I guess the root "issue" is nodes module resolution / CRAs configuration.
