### ISSUE TITLE
'children' in css class if use not named components

### ISSUE THREAD

**Issue by dmitrymalakhov** [styled-components/styled-components#1306]
## Version
styled-components 2.2.2
babel-plugin-styled-components 1.2.1

## Reproduction

```javascript
const Div = styled.div`${p => p}`;

/../
render() {
 return (
        <Div>some content</Div>
    );
}

```
## Actual Behavior

![screenshot from 2017-11-10 15-37-29](https://user-images.githubusercontent.com/2477267/32660040-5295809c-c632-11e7-9820-6f63af13e4e3.png)

![screenshot from 2017-11-10 15-37-00](https://user-images.githubusercontent.com/2477267/32660034-4b1878a6-c632-11e7-8fe9-2e7084ab614a.png)

**Comment by philpl** [comment]
It's not possible to use props directly for styling without some filtering. So either you can pass through a `style` prop, or you can check out this small code snippet here: https://twitter.com/mxstbr/status/927875960162136065

**Comment by dmitrymalakhov** [comment]
Oh, thank you! Apparently I missed this tweet.
