### ISSUE TITLE
Unable to add theme to any Styled component for even basic usage

### ISSUE THREAD

**Issue by mukurpuri** [styled-components/styled-components#1308]
I tried basic implementation of Theming Styled components, as shown in the documentation [Styled component Theming](https://www.styled-components.com/docs/advanced#theming)

I tried with my basic parent component, 

```
const theme = {
	main: 'mediumseagreen'
};
const Button = styled.button`
	font-size: 1em;
	margin: 1em;
	padding: 0.25em 1em;
	border-radius: 3px;

	/* Color the border and text with theme.main */
	color: ${props => props.theme.main};
	border: 2px solid ${props => props.theme.main};
`;
```

```
ReactDOM.render(
	<ThemeProvider theme={theme}>
		<Button>Themed</Button>
	</ThemeProvider>,
	document.getElementById('root')
);
```

build passes but browser consoles an Error

```
**Uncaught Error: Cannot create styled-component for component: [object Object]**
    at constructWithOptions (styled-components.es.js:2089)
    at styled (styled-components.es.js:2024)
    at mountIndeterminateComponent (react-dom.development.js:8038)
    at beginWork (react-dom.development.js:8229)
    at performUnitOfWork (react-dom.development.js:10215)
    at workLoop (react-dom.development.js:10279)
    at HTMLUnknownElement.callCallback (react-dom.development.js:540)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:579)
    at invokeGuardedCallback (react-dom.development.js:436)
    at renderRoot (react-dom.development.js:10357)
```
Using Chrome Browser, with project dependencies 

```
"dependencies": {
    "react": "^16.1.0",
    "react-dom": "^16.1.0",
    "styled-components": "^2.2.3"
  }
```
@mxstbr 
@geelen

**Comment by mxstbr** [comment]
Can you provide a reproduction on webpackbin.com please? This doesn't happen for me, at all. Maybe it's a React v16 thing?

**Comment by mukurpuri** [comment]
@mxstbr  What is your React version?

**Comment by mxstbr** [comment]
15.0, but I haven't had any troubles running v16 either. Can you provide a broken reproduction? Then we can look into this.

**Comment by mukurpuri** [comment]
@mxstbr  Ohh I see, I reproduced it by adding code to an app created by CRA (create-react-app)

I am showing you the basic app.js implementation of it, which this then called by index.js

```
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import styled from 'styled-components';
import ThemeProvider from 'styled-components';

class App extends Component {
  render() {
    const theme = {
      main: 'mediumseagreen'
    };
    const Button = styled.button`
      font-size: 1em;
      margin: 1em;
      padding: 0.25em 1em;
      border-radius: 3px;

      /* Color the border and text with theme.main */
      color: ${props => props.theme.main};
      border: 2px solid ${props => props.theme.main};
    `;

    return (
      <ThemeProvider theme={theme}>
        <Button>Themed</Button>
      </ThemeProvider>
    );
  }
}

export default App;
```
and the parent component index.js be

```
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import registerServiceWorker from './registerServiceWorker';

ReactDOM.render(<App />, document.getElementById('root'));
registerServiceWorker();
```

It shows the same error inside the parent component as before

![2017-11-13_17h00_28](https://user-images.githubusercontent.com/10636579/32723646-4340f93c-c894-11e7-9e20-2391e2c28afc.png)

**Comment by mxstbr** [comment]
You're recreating the styled component in every render, which is a bad idea. Can you try doing it the recommended way:

import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import styled from 'styled-components';
import ThemeProvider from 'styled-components';

const Button = styled.button`
      font-size: 1em;
      margin: 1em;
      padding: 0.25em 1em;
      border-radius: 3px;

      /* Color the border and text with theme.main */
      color: ${props => props.theme.main};
      border: 2px solid ${props => props.theme.main};
    `;

    const theme = {
      main: 'mediumseagreen'
    };

class App extends Component {
  render() {
    return (
      <ThemeProvider theme={theme}>
        <Button>Themed</Button>
      </ThemeProvider>
    );
  }
}

export default App;

**Comment by morajabi** [comment]
@mxstbr What the hell is this, Max: (!!!)
```
import ThemeProvider from 'styled-components';
```

**Comment by mxstbr** [comment]
Oh yeah that's the issue, lol. Totally missed that. Closing!

**Comment by mukurpuri** [comment]
@morajabi  Thank you brother for pointing this silly mistake. But there was no point to make a laugh out of this. 
If it was so silly, I had rather appreciate the explanation but not an emojical fun.

**Comment by philpl** [comment]
@mukurpuri Sorry, about that. We didn't mean to offend at all!

If it helps, we were finding it funny that @mxstbr didn't see this straight away and instead jumped to another suggestion, but we didn't intend to be rude, so definitely apologies from my end! 😞

**Comment by morajabi** [comment]
@mukurpuri Really sorry about that didn't see that was in your code (until now), I thought Max wrote that. That's why I didn't close the issue myself.

**Comment by mukurpuri** [comment]
@philpl  @morajabi  .. Oh God, brothers, its blunder for misunderstanding, you both didn't saw my code and I didn't saw Max's code which had this silly mistake of mine.  :x: 
I am really sorry, I acted jerk without seeing anything.

You all are doing a great job, by making this amazing package, helping us everywhere.

Love from India :india:  :heart:

**Comment by philpl** [comment]
@mukurpuri don’t be sorry 😅 it was also a little rude from our end.

Anyway, feel free to DM me on Twitter (@_philpl) or on Spectrum, where you can also create threads for questions, if you need some quicker help and debugging

**Comment by tylerbrownhenry** [comment]
> ```js
> import styled, { ThemeProvider } from 'styled-components';
> ```

This was my problem.
