### ISSUE TITLE
Using withComponent('tag') on styled(Component) removes styling

### ISSUE THREAD

**Issue by petergombos** [styled-components/styled-components#1310]
## Version
2.2.3

## Reproduction
codesandbox:
`https://codesandbox.io/s/2xwzowxx3j`

```js
const BaseComponent = styled.div`
  background: black;
  padding: 10px;
  color: red;
`

export const ComponentFromDifferentFile = styled(BaseComponent)`
  margin: 5px;
`.withComponent('p')

export const ComponentFromSameFile = BaseComponent.extend`
  margin: 5px;
`.withComponent('p')
```

## Expected Behavior
I would assume that both ComponentFromDifferentFile, ComponentFromSameFile should still have the styling from BaseComponent. 

## Actual Behavior
ComponentFromDifferentFile does not have the style from BaseComponent. This only happens if I use withComponent.

**Comment by philpl** [comment]
When you call `styled(BaseComponent)` it doesn't **extend** the `BaseComponent` but instead wraps it in another styled component.

So calling `withComponent` on the outer styled component will replace `BaseComponent` with `"p"` instead of replacing `"div"` in the child styled component.

**Comment by philpl** [comment]
cc @geelen: regarding our recent discussion; I'm all for getting rid of `.extend`, but this would then become an issue.

**Comment by k15a** [comment]
@philpl could you please explain what you mean with getting rid of `.extend`? I thought that we introduced it so we don't have any magic inside of `styled()`

**Comment by philpl** [comment]
@k15a we were previously discussing it here and might do again soon: https://github.com/styled-components/babel-plugin-styled-components/issues/79#issuecomment-343453978

**Comment by petergombos** [comment]
@philpl Thanks for the quick reply! Could you perhaps suggest a way I should approach this then? How can I change a styled(component)'s html tag?

**Comment by goodwin64** [comment]
+1, I've faced with similar issue

**Comment by superfunkminister** [comment]
An ever helpful +1

**Comment by maximus-lynn** [comment]
+ 1
