### ISSUE TITLE
Incorrect typings for withComponent()

### ISSUE THREAD

**Issue by fenok** [styled-components/styled-components#1315]
## Version
2.2.3

## Reproduction
I'm trying to pass Stateless Functional Component to `withComponent()` method. Everything works fine, but typescript complains about its type. It seems that `StyledComponentClass` interface is missing something like `withComponent(element: StatelessComponent<P>): StyledComponentClass<P, T, O>;` (not very familiar with typescript though).

## Steps to reproduce
1. Pass Stateless Functional Component to withComponent() method.
## Expected Behavior
Typescript not complaining about incompatible types.
## Actual Behavior
Typescript complaining about incompatible types.

**Comment by philpl** [comment]
cc @styled-components/typers

**Comment by Igorbek** [comment]
Could you please provide a reproduction code and versions of typescript, @types/react?

**Comment by fenok** [comment]
Typescript version is 2.4.1.
```
import * as React from 'react';
import styled from 'styled-components';

interface Props {
    className?: string;
}

function StatelessComponent(props: Props) {
    return <div className={props.className}>
        </div>;
}

// Here
const StyledStatelessComponent = styled.div``.extend``.withComponent(StatelessComponent);

export { StyledStatelessComponent };
```

**Comment by patwritescode** [comment]
I've run into this issue, or at least a similar one, with the latest version of styled-components.

If I have a styled span for example as so:
```javascript
import styled from "styled-components";

export default styled.span`
    color: green;
`
```

... and I use withComponent to use an anchor tag as so:

```javascript
import styled from "styled-components";
import Span from "./span";

export default Span .withComponent("a");
```
I get type errors when trying to use props like `href`.

```javascript
import * as React from "react";
import Link from "./link";

const Tests: React.SFC = () => {
    return (
        <Link href="test"/>        
    );
}
```

Compiling gives the following error:
```
error TS2559: Type '{ href: string; }' has no properties in common with type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ThemedOuterStyledProps<DetailedHTMLProps<HTMLAttributes<HTMLSpanElement>, HTMLSpanElement>, any>, ComponentState>> & Readonly<{ children?: ReactNode; }> & Readonly<ThemedOuterStyledProps<DetailedHTMLProps<HTMLAttributes<HTMLSpanElement>, HTMLSpanElement>, any>>'.
```
It seems to be because in the typings `O = P` will set that to the same type (in this example, the type of intrinsic span). Then, `withComponent` returns a `StyledComponentClass` where the third generic passed is `O` meaning if `O = P` in the parent then the `withComponent` result will have an intersected type with whatever that type was. In this case, span doesn't have a prop `href` so we receive the error above.

```typescript
export interface StyledComponentClass<P, T, O = P> extends ComponentClass<ThemedOuterStyledProps<O, T>> {
  extend: ThemedStyledFunction<P, T, O>;

  withComponent<K extends keyof JSX.IntrinsicElements>(tag: K): StyledComponentClass<JSX.IntrinsicElements[K], T, O>;
  withComponent(element: ComponentClass<P>): StyledComponentClass<P, T, O>;
}
```

This is tough because we use `styled-components` in our internal shared ui library with typescript. So far we've had to just cast the export to a type that works but that excludes us from ever using a real value for `O` and having it pass down through `withComponent`.

**Comment by onemenzel** [comment]
I experience the same issue after an upgrade to TypeScript 2.8.1. On TypeScript 2.7.2 however, the error does not appear. From the error message I get, I'd conclude that @patwritescode is right. Here a quick example:
```typescript
const Btn = styled.input``.withComponent('button').extend``

const BtnPropsProxy = (props: {onButtonClick: MouseEventHandler<HTMLButtonElement>}) => (
  <Btn onClick={props.onButtonClick}/>
)
```
throws
```
Type '{ onClick: (event: MouseEvent<HTMLButtonElement>) => void; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ThemedOuterStyledProps<DetailedHTMLProps...'.
Type '{ onClick: (event: MouseEvent<HTMLButtonElement>) => void; }' is not assignable to type 'Readonly<ThemedOuterStyledProps<DetailedHTMLProps<InputHTMLAttributes<HTMLInputElement>, HTMLInpu...'.
Types of property 'onClick' are incompatible.
Type '(event: MouseEvent<HTMLButtonElement>) => void' is not assignable to type '((event: MouseEvent<HTMLInputElement>) => void) | undefined'.
Type '(event: MouseEvent<HTMLButtonElement>) => void' is not assignable to type '(event: MouseEvent<HTMLInputElement>) => void'.
```
and
```
Type '{ onClick: (event: MouseEvent<HTMLButtonElement>) => void; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ThemedOuterStyledProps<DetailedHTMLProps...'.
Type '{ onClick: (event: MouseEvent<HTMLButtonElement>) => void; }' is not assignable to type 'Readonly<ThemedOuterStyledProps<DetailedHTMLProps<InputHTMLAttributes<HTMLInputElement>, HTMLInpu...'.
Types of property 'onClick' are incompatible.
Type '(event: MouseEvent<HTMLButtonElement>) => void' is not assignable to type '((event: MouseEvent<HTMLInputElement>) => void) | undefined'.
Type '(event: MouseEvent<HTMLButtonElement>) => void' is not assignable to type '(event: MouseEvent<HTMLInputElement>) => void'.
Types of parameters 'event' and 'event' are incompatible.
Type 'MouseEvent<HTMLInputElement>' is not assignable to type 'MouseEvent<HTMLButtonElement>'.
Type 'HTMLInputElement' is not assignable to type 'HTMLButtonElement'.
Property 'status' is missing in type 'HTMLInputElement'.
```

I can work around this by doing `onClick={props.onButtonClick as MouseEventHandler<any>}`. However, I find this to be kind of unsatisfying...

**Comment by mbrowne** [comment]
There might be multiple issues here, but specifically regarding stateless functional components, the problem is this line:

    withComponent(element: ComponentClass<P>): StyledComponentClass<P, T, P>;

It should be changed to:

    withComponent(element: ComponentType<P>): StyledComponentClass<P, T, P>;

That way it will work for both class components and function components. It shouldn't break anyone's existing code since it will still work exactly the same way for class components.

Let me know if you'd like me to submit a PR for this.

**Comment by Igorbek** [comment]
@mbrowne that change should be ok. a PR is very welcome.

**Comment by 6r1anchen** [comment]
@mbrowne @Igorbek I was hit with this bug today. 
I made a PR based on the work and discussion in #1283 and #1201 , I hope it is ok since they are not updated for a while.

**Comment by mbrowne** [comment]
Thanks @6r1anchen, I was planning to do a PR but haven't had time yet, so please proceed with your PR. But your PR doesn't fix the original issue reported in this thread...I added a comment on the PR with a suggested solution.
