### ISSUE TITLE
Complex state access from styled component

### ISSUE THREAD

**Issue by xahon** [styled-components/styled-components#1317]
I think styled-components have one big problem. It's too hard to make flexible component styles based on main component state/props
Currently, AFAIK passing props to `styled` component is only able via DOM element props. Let's look on one example of `StyledDiv` that was created from `styled.div` element.  
`<StyledDiv stateProp={ this.state.someProperty } />`
I tried to pass `stateProp` into `styled` css generator. So what if i don't want to pass any props into this element but i need access master component state? May be it'll be better if we could access this component props/state via something like this ``styled.div`left: ${@state.someProp}px` ``?

#### Problems 
1. Passing local state into components down may cause hard-detectable and unexpected bugs. 
2. Passing spread (Containing style sensitive and others props) may break component look and feel. (E.g. if i pass `{...this.state}` as prop to styled component and state contains 'title' prop, this title will show in the child component as popup on hover). Selective props passing can cause problems from 1 paragraph

#### Possible solutions
I think that it need to add some sugar to have:  
1. Access to state via `${@state}`.  
2. Access to holder component props via `${@props}`
3. Access to this (styled) components props via `${@this.someprop}`

By this way we will be able to generate styles based on component state without passing props down

Currently i'm using that way `<StyledComponent props={ ...this.props, ...this.state } />` but it's too complex to keep track on that prop and easy to be mistaken.

## UPD
I'm developing card game and have component named `PlayerHandDeck` that contains `Card` elements as state (Will be replaced with redux store). Cards should be placed on above each other relative to screen width and cards count. So i need pass `count={this.state.cards.length}` to calculate offset and it'll passed into each `Card` component. On card click i'm lifting props up from card to `PlayerHandDeck` and get property `count: 20`. This is only one concrete example but i have a lot of such cases

Sorry for bad english

**Comment by mxstbr** [comment]
> Currently i'm using that way `<StyledComponent props={ ...this.props, ...this.state } />` but it's too complex to keep track on that prop and easy to be mistaken.

That's exactly why we recommend being explicit, so you always know which props are being passed in:

```JS
<StyledComponent count={this.state.cards.length} />
```

> I think that it need to add some sugar

We won't add any syntactic sugar to the CSS you write in styled-components, at least definitely not in the core library.

If you really want to have this feature you could write a Babel plugin that does this transformation:

```JS
// Input:
const Bla = styled.div`
  color: $state.color;
`

// Output:
const Bla = styled.div`
  color: ${p => p.state.color};
`
```

I still wouldn't recommend it and would stick with the explicit way of doing things, even if it might take a couple more keystrokes.
