### ISSUE TITLE
Misplaced curly brace resulting in invalid styles

### ISSUE THREAD

**Issue by dominicgabrielgo** [styled-components/styled-components#1318]
The generated styles have a misplaced curly brace. Here's an example:

**Generated style:** 
```
/* sc-component-id: sc-bdVaJa */
.sc-bdVaJa {}
.bfgYbg
  padding: 30px;
  max-width: 1280px;
  margin: 0 auto;
```

**Expected style:**
```
/* sc-component-id: sc-bdVaJa */
.sc-bdVaJa 
.bfgYbg {
  padding: 30px;
  max-width: 1280px;
  margin: 0 auto;
}
```

## Version
I'm using babel-plugin-styled-components ^1.3.0

## Reproduction
I'm on a nextjs stack using the with-styled-components-example.

**Comment by philpl** [comment]
Indentation are not significant tokens in the CSS language, thus there is not a lot that can even be done on stylis to accommodate this behaviour.

In a future version that will use a CSS parser, we might introduce more strict parsing and errors when the syntax is invalid
