### ISSUE TITLE
NavigatorProperties type

### ISSUE THREAD

**Issue by stief510** [styled-components/styled-components#1320]
When using RN 0.50 and TypeScript, I get a type error:

`error TS2694: Namespace ...@types/react-native/index"' has no exported member 'NavigatorProperties'`

from `styled-components/native/index.d.ts (38,52)`

**Comment by philpl** [comment]
This will be addressed in https://github.com/styled-components/styled-components/pull/1339

**Comment by mxstbr** [comment]
Nope it won't, this is TypeScript not flow? /cc @Igorbek

**Comment by Igorbek** [comment]
It will, #1339 changes TS definitions.

**Comment by shadrech** [comment]
So will the #1339 PR fix this issue and if so when will it be merged?
In mean time how can we go around this error any ideas?

**Comment by Igorbek** [comment]
It will fix this issue. Sorry, nothing comes to my mind that would fix the issue in the meantime.
