### ISSUE TITLE
Add API for style insertion point

### ISSUE THREAD

**Issue by Secretmapper** [styled-components/styled-components#1322]
Related: #860 #1253 

Specificity in `styled-components` is supported through repeated selectors, i.e:

```
const Button = styled(Button)`
   &&&& {
     display: block;
   }
`

```
This works but it is rather bizzare, is tedious to write, and adds code smell, especially if this needs to be done for every component in a library (such as `material-ui`)

My proposal is to allow something like [jss insertion points](https://github.com/cssinjs/jss/blob/b841b18a9e564f35176174f3a2fdb1e7e35ec89a/docs/setup.md#specify-dom-insertion-point), which defines where the styles are injected into the DOM.

### What will it allow you to do that you can't do today?

It will allow me to write the above as:

```
const Button = styled(Button)`
   display: block;
`
```

While it may seem simple enough, consider that something like this can appear a **LOT** in a single app.

### How will it make current work-arounds straightforward?

(Above example)

Would love to hear if you guys are open to adding something like this.

### What potential bugs and edge cases does it help to avoid?

It should prevent unnecessary repeated selectors - which in turn should avoid 'selector races' similar to 'z-index races' where the z-index grows too much arbitrarily. Since repeated selectors becomes the norm, extending components like this might entail just adding more and more ampersands.

**Comment by mxstbr** [comment]
See #1102.
