### ISSUE TITLE
problem when nesting selector

### ISSUE THREAD

**Issue by Memoyr** [styled-components/styled-components#1326]
It's seems to throw an error  when I use the nesting solution as refered in [FAQ](https://www.styled-components.com/docs/faqs#can-i-nest-rules) with an imported component.

Is this suppose to work ? I found that it works when it's not an imported component. Do I miss a something? Thanks

TypeError: Cannot convert a Symbol value to a string
node_modules/styled-components/dist/styled-components.es.js:72

I'm using  "styled-components": "^2.2.3",

```
import MyComponent from ./MyComponent;

const NiceButton = styled.button`
  color: red;
  &:hover ${MyComponent} {
    color: blue;
  }
`;

const Something = ({ }) => (
    <NiceButton>
      <MyComponent />
    </NiceButton>
);

export default Something;
```

**Comment by philpl** [comment]
Please make sure that “MyComponent” there is actually a styled component :)

This is a duplicate issue and there is some more info here: https://github.com/styled-components/styled-components/issues/1314#issuecomment-3451056

We’ll update the website soon to reflect this
