### ISSUE TITLE
Styled components selector ".class" not specific enough to override ".class tagname"

### ISSUE THREAD

**Issue by pke** [styled-components/styled-components#1329]
## Version
2.1.0

## Reproduction

https://www.webpackbin.com/bins/-L-2M40p6gvgtP9kOCIe

## Steps to reproduce

Have class on the `<body class="ios">` with this CSS:

```css
.ios p {
  background-color: blue;
  color: white;
  font-size: 120%;
}
```

and a styled p component 

```es6
const Text = styled.p`
  font-size: 70%;
  background-color: white;
`
```

## Expected Behavior

`Text` should have a white background and small font.

## Actual Behavior

`Text` has the font size and background of the body via more stronger selector `.ios p`. Which is stronger than the styled components selector. When the styled components selector would be `p.<generatedname>` it would take precedence and all would work good.

Is there a way to force the tag name to the generated styled class name?

**Comment by philpl** [comment]
This is expected behaviour and there are some tricks to make this work correctly: https://www.styled-components.com/docs/advanced#existing-css

In the case of having your `Text` component have a higher specificity, you can let it repeat its own classname:

```js
const Text = styled.p`
  & { /* or add more & here until specificity is high enough */
    font-size: 70%;
    background-color: white;
  }
`;
```

Since this is not that nice, generally we don't recommend using global rules like the one you have here, but I suppose that's not new code but legacy?

**Comment by pke** [comment]
I tried the `&` trick but it did not work.
The "global" rule is just fine CSS. The real rule in my mobile app to enforce the iOS text font on paragraphs.

**Comment by philpl** [comment]
@pke I'd recommend you to move the code for this into a `css` helper tag: https://www.styled-components.com/docs/api#helpers or maybe you can even code a more complex helper, like this one: https://www.styled-components.com/docs/advanced#media-templates

If that's on an option you have to repeat the parent selector until the specificity is high enough (in this case `&&`): https://www.webpackbin.com/bins/-L-2WWEg3jLDspr0Hwou

But I really don't recommend working with global classes together with styled-components, as it defeats the purpose of 1) not having to worry about specificity, and 2) encapsulation & componentisation
