### ISSUE TITLE
How to apply a sort of life cycle to how css got applied?

### ISSUE THREAD

**Issue by adamchenwei** [styled-components/styled-components#1330]
## Version
latest
## Reproduction
https://github.com/styled-components/styled-components/issues/1253

## Steps to reproduce
follow the issue above
## Expected Behavior
has some sort of css injection life cycle, so we dont have to use the hack like `&&` to override styles, and be able to controll which style got apply first, for above issue exaxmple, its a collaboration between style-component and materal-ui component styles

## Actual Behavior
use && to increase priority, but imagine if several components nested together and all try to access the same style, but in a different way, it may get hard to debug, or I maybe just think a bit too far?

**Comment by philpl** [comment]
The order of style tags will be controllable using: https://github.com/styled-components/styled-components/pull/1324

But we can't dynamically change the specificity since external/existing CSS can simply have any number of higher ones.
