### ISSUE TITLE
Cut a release?

### ISSUE THREAD

**Issue by probablyup** [styled-components/styled-components#1331]
There are a couple important fixes in the pipeline that need to be released: https://github.com/styled-components/styled-components/blob/master/CHANGELOG.md#unreleased

The HMR thing in particular is quite a nuisance when developing.

**Comment by philpl** [comment]
Sure :) @mxstbr maybe we should consider semantic releases at some point 😅

**Comment by morajabi** [comment]
@philpl We don't have?
