### ISSUE TITLE
Styled component not transforming on prop change

### ISSUE THREAD

**Issue by appzter** [styled-components/styled-components#1334]
Hi,

Having a problem with a side drawer component that is supposed to slide in from the right on open. Wrote it in a separate CSS file first and it works like a charm, but for some reason styled-components ignores the fact that the props.open changes. I tried logging the props and the component receives it as it should.  

Here is my code: 

`const SideDrawerBox = styled.div`
    position: fixed;
    width: 280px;
    max-width: 70%;
    height: 100%;
    right: 0;
    top: 0;
    z-index: 200;
    background-color: #2E2E3A;
    padding: 32px 16px;
    box-sizing: border-box;
    transition: transform 0.3s ease-out;

    transform: translateX(${props => props.open ? '0%' : '+100%' });

    @media(min-width:1024px){
      display: none;
    }
  ``

`<SideDrawerBox>
        <SideDrawerItems>
          <SideDrawerLogo src={Logo} />
          <SideDrawerText>Register</SideDrawerText>
          <SideDrawerText>Log in</SideDrawerText>
        </SideDrawerItems>
      </SideDrawerBox>`

Any ideas? Thanks!

**Comment by philpl** [comment]
Please adhere to the issue template and submit a reproduction please :smile: Otherwise, it'd take up too much time to hunt down the issue

https://raw.githubusercontent.com/styled-components/styled-components/master/.github/ISSUE_TEMPLATE.md

Also, btw, you can create codeblocks in markdown using triple backticks followed by the language that should be used to highlight your code, e.g. in this case `js`. https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by appzter** [comment]
Sorry about that, first time here! :) 

## Reproduction

Set up project using create-react-app
Used NPM to install styled-components v2.2.3

## Steps to reproduce

I have a Layout component that looks like this: 

´´´js
class Layout extends Component {

  //show or hide drawer for mobile devices
  state = {
    showDrawerToggle: false
  }

  //toggles the side drawer
  onSideDrawerToggleHandler = () => {
    this.setState(prevState => {
      return { showDrawerToggle: !prevState.showDrawerToggle }
    })
  }

  render() {
    return(
      <Aux>
        <Toolbar toggleSideDrawer={this.onSideDrawerToggleHandler} />
        <SideDrawer
          open={this.state.showDrawerToggle}
          toggleSideDrawer={this.onSideDrawerToggleHandler} />
        
         ...other components 

      </Aux>
    )
  }
}
´´´

And my SideDrawer, looking like this: 

´´´js

const sideDrawer = (props) => {

  // *** STYLE *** //

  const SideDrawerBox = styled.div`
    position: fixed;
    width: 280px;
    max-width: 70%;
    height: 100%;
    right: 0;
    top: 0;
    z-index: 200;
    background-color: #2E2E3A;
    padding: 32px 16px;
    box-sizing: border-box;
    transition: transform 0.3s ease-out;

    transform: translateX(${props => props.open ? '0' : '+100%' });

    @media(min-width:1024px){
      display: none;
    }
  `

  // *** END_STYLE *** //

  return (
    <Aux>
      <Backdrop show={props.open} clicked={props.toggleSideDrawer} />
      <SideDrawerBox>
        
          ...other components 

      </SideDrawerBox>
    </Aux>

  )
}

´´´

## Expected Behavior

The SideDrawerBox receives open as a true/false prop. If open is true, the SideDrawerBox should be visible, as translateX(0), and if open is false, it should move out of screen, translateX(+100%). 

I have verified that the SideDrawerBox receives the prop as if I change places of the turnary expression returns, ( ```js  ${props => props.open ? '+100%' : '0' } ```, the SideDrawerBox is visible. Also, by console.log(props), I can clearly see that the component receives new props.


## Actual Behavior

The problem is that when props changes, the SideDrawerBox is not restyled, it ignores the fact that the prop that decides wether or not it is open has changed.

**Comment by philpl** [comment]
```js
const sideDrawer = (props) => {

  // *** STYLE *** //

  const SideDrawerBox = styled.div`
```

You're recreating the styled component `SideDrawerBox` over and over again on every render. This will cause React to recycle that part of your element tree and readd everything again.

Very expensive for all moving parts that are involved :wink:

You'll always want to have every component, including especially styled components, outside of other component's render cycle, or any other method :smile:

**Comment by LaraWho** [comment]
I'm confused as to how this solves the problem?

**Comment by bailycase** [comment]
I'm having this same issue, and there is no resolution listed here. Why was this closed?

**Comment by kitten** [comment]
@bailycase as stated above, the StyledComponent is recreated every time the parent component renders. Like any component this will cause React not to recycle the underlying DOM structure, which will mean that no animation actually  plays since the DOM node is destroyed.

We create actual components so they'll have to be kept static across the life cycle of a component.

If you're still experiencing issues and need help though it might make sense to open a new issue and ask for help with your specific snippet of code 🙌

**Comment by maximforever** [comment]
So, I just ran into this problem, and while this thread was not helpful, I _did_ find a solution elsewhere.

In my case, the styled component was defined within the react component, which was re-rendering and nullifying my transition. Pulling the styled components outside the react component (defining it before the react component) resolved my issue.
