### ISSUE TITLE
Strange bug w/Redux-form & possibly Radio buttons

### ISSUE THREAD

**Issue by michaelryancaputo** [styled-components/styled-components#1335]
## Version
    "styled-components": "^2.2.4",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",

## Reproduction
This is difficult to set up in an isolated environment since I use React Storybook, and i'm working with a few private NPM packages:
- Form elements library contains vanilla form fields like text inputs, dropdowns, buttons all styled with Styled-components
- Form library is a custom form tool i've built using redux-form that generates forms based on a JSON form definition. This has the form elements as a peer dependencies, however both libraries use styled-components. Their styled components versions match.

I have isolated this to a storybook environment using React 16.2.0, toggling between stories with and without radio input fields. Toggling between inputs like text, textarea, select, seems fine, however as soon as I display a radio button my styled-components styles go away and I get vanilla inputs with no styling.

## Steps to reproduce
Described above, I will try to reproduce in isolation.

![nov 30 2017 9_53 am](https://user-images.githubusercontent.com/80901/33446363-a049a1e2-d5b4-11e7-9752-36227a281758.gif)

## Expected Behavior
Styles applied via styled components should not go away.

## Actual Behavior
Loosing all styles when radio inputs are being displayed.

**Comment by michaelryancaputo** [comment]
![nov 30 2017 9_53 am](https://user-images.githubusercontent.com/80901/33446363-a049a1e2-d5b4-11e7-9752-36227a281758.gif)

**Comment by michaelryancaputo** [comment]
I seem to have fixed it by removing a nested functional component.

**Comment by philpl** [comment]
> Toggling between inputs like text, textarea, select, seems fine, however as soon as I display a radio button my styled-components styles go away and I get vanilla inputs with no styling.

This hints at a typo in one of your component's styles. This could be an extra or missing parenthesis, curly brace, etc.

If you need further help, please provide a CodeSandbox / other kind of reproduction. A gif, or screenshot, or even just a small code snippet won't cut it in most cases. You can find templates for a sandbox env in the issue template.

> I seem to have fixed it by removing a deeply nested functional component.

I'll close this for now as you've partially found the issue, and we don't have anything to go after here yet :wink:

**Comment by michaelryancaputo** [comment]
Thanks for the hint, i'll look into that.
