### ISSUE TITLE
Maintaining innerRef through React.cloneElement().

### ISSUE THREAD

**Issue by hueyhe** [styled-components/styled-components#1337]
## Version
2.1.2

## Reproduction
I'm trying to maintain the ref prop through `React.cloneElement()`. According to [Refs to DOM Nodes](https://github.com/styled-components/styled-components/blob/master/docs/tips-and-tricks.md#refs-to-dom-nodes), I pass the ref handler callback to innerRef prop of the child. But what I get is `undefined`.

```javascript
const Header = styled.header`
`;

const Content = styled.content`
`;

class Parent extends React.Component {
  componentDidMount() {
    // got 'undefined'
    console.log(this.header);
  }

  render() {
    const { children } = this.props;

    return (
      <div>
        {
          React.Children.map(children, child => {
            if (child && child.type === Header) {
              return React.cloneElement(child, {
                innerRef: node => { this.header = node; },
              });
            }

            return child;
          });
        }
      </div>
    );
  }
}

// In render of App.js.
<Parent>
  <Header />
  <Content />
</Parent>
```

## Expected Behavior
Get the dom node of `Header`.

## Actual Behavior
Get `undefined`.

**Comment by mxstbr** [comment]
Can you provide a reproduction on codesandbox or webpackbin please? This is very hard to track down just like that. Here's two starter bins/boxes: https://www.webpackbin.com/bins/-KeeZCr0xKfutOfOujxN https://codesandbox.io/s/rkmNRByE4

Thanks!
