### ISSUE TITLE
ThemeProvider doesn't work as expect

### ISSUE THREAD

**Issue by yordis** [styled-components/styled-components#1340]
From the documentation

> In the render tree all styled-components will have access to the provided theme, even when they are multiple levels deep.

So I did this https://github.com/straw-hat-team/impetus_bit/blob/master/src/OTP/Core/Application.js#L40

```jsx
render() {
    const shouldShowLoadingScreen = this.showLoadingScreen()
    const children = shouldShowLoadingScreen ? this.renderLoadingScreen() : this.renderBody()

    return (
      <Provider applicationStore={this.store}>
        <IntlProvider locale={navigator.language}>
          <ThemeProvider theme={Theme}>
            <BaseHold baseline={Theme.baseline} ratio={Theme.ratio} unit={Theme.unit}>
              {children}
            </BaseHold>
          </ThemeProvider>
        </IntlProvider>
      </Provider>
    )
  }
```

So notice I add my `ThemeProvider` but when I do `console.log(this.props.theme)` doesn't show any `theme` key

## Expected Behavior
I should see `theme` key in the props in all the components from that HoC in.

## Actual Behavior

I don't see the `theme` key in the props

**Comment by mxstbr** [comment]
This is likely a usage problem, please post the code where you do ` console.log(this.props.theme)`.

**Comment by yordis** [comment]
@mxstbr I did in the BaseHold component which was directly into ThemeProvider https://github.com/straw-hat-team/impetus_bit/commit/cf112eecdffce8d9e9f02700a0e9ebf506bcbc23#diff-04dc67449c1b1d8ddf45724657e3db4fR78

**Comment by yordis** [comment]
@mxstbr I added it back https://github.com/straw-hat-team/impetus_bit/blob/61126594dc805f9e3390c9327857583c7d254709/src/%40straw_hat/boa/components/Basehold.js#L82

still saying `undefined`

**Comment by yordis** [comment]
I even removed all the code and let

```js
<ThemeProvider theme={Theme}>
            <BaseHold baseline={Theme.baseline} ratio={Theme.ratio} unit={Theme.unit}>
              {children}
            </BaseHold>
          </ThemeProvider>
```

and it didn't work

**Comment by mxstbr** [comment]
“In the render tree all **styled-components** will have access to the provided theme, even when they are multiple levels deep.”

Only all `styled-components` have access to the theme, like so:

```JS
const SomeComp = styled.div`
  colors: ${props => props.theme.primary};
`
```

If you want to get the theme in your normal React component you have to use our `withTheme` higher order component:

```JS
import { withTheme } from 'styled-components'

class SomeComp extends React.Component {
  render() {
    console.log(this.props.theme);
  }
}

export default withTheme(SomeComp);
```

Next time when you have a usage question please ask in [the community](https://spectrum.chat/styled-components) or on StackOverflow, this is an issue tracker. Thanks!
