### ISSUE TITLE
Extended attrs are not affecting props to the original components attrs

### ISSUE THREAD

**Issue by Flydiverny** [styled-components/styled-components#1343]
Not sure if this is a bug or expected/wanted behaviour but I got a bit confused when combining `extend` and  `attrs` on a styled component which already used `attrs` in itself.

## Version
styled-components: 2.2.4

## Reproduction
https://codesandbox.io/s/pjmzp25vy0

## Steps to reproduce
See usage of combining `extend` & `attrs` in reproduction.

## Expected Behavior
I'd expect the component to receive the result of the evaluated attrs passed from the extended component.
Attributes from `MagicText` to affect attributes of extended style. Ie in reproduction it would say `Magic Hello world`.

## Actual Behavior
Attributes are merged and only evaluated for the "original" component (the one you choose to extend).

**Comment by philpl** [comment]
@Flydiverny hm, this is intended since it’d be quite difficult to then override the attrs of the upper styled component if necessary.

I’m wondering whether we can make both nicer by passing the old attrs as a second argument so they can be applied additionally more easily if necessary

cc @mxstbr

**Comment by probablyup** [comment]
I don't think we're going to ever support this for generic attrs. We did add support for shallow merging the "style" prop though. https://github.com/styled-components/styled-components/commit/a20588de17648ea135faab4433237b6c5ca3fdf8
