### ISSUE TITLE
Support for React 16

### ISSUE THREAD

**Issue by lavelle** [styled-components/styled-components#1348]
Hi there,

At @thumbtack we've started adopting Styled Components in our React codebase. We're liking it a lot so far from a developer experience perspective, but wanted to reach out with some technical concerns to make sure its a viable technology for us to invest in going forwards.

We have recently added a server-side React renderer to our setup, and plan to upgrade both our client and server side React to v16 soon. This comes with [lots of improvements for SSR](https://hackernoon.com/whats-new-with-server-side-rendering-in-react-16-9b0d78585d67), including an asynchronous `renderToNodeStream` method that can be used on the server to start sending data to the client sooner, and a `hydrate` method on the client to more efficiently re-render server rendered components when the client loads.

We wanted to find out if you guys had a plan or roadmap for supporting these features in React 16, to avoid getting into a situation in the future where we're unable to upgrade React due to restrictions on other libraries.

Cheers,

Giles

**Comment by philpl** [comment]
@lavelle we likely won't be able to support this anytime soon but we have an issue tracking it here: https://github.com/styled-components/styled-components/issues/1192

Please note that this is not a "general support for v16" issue as support for v16 is working as intended :wink:
