### ISSUE TITLE
Flow: allow intersection types for `styled()`

### ISSUE THREAD

**Issue by sohkai** [styled-components/styled-components#1350]
## Version
```
styled-components: 2.2.3
flow-typed: styled-components_v2.x.x.js
```

## Reproduction

Sometimes, it's useful to attach a component onto another component as a namespacing technique.

In flow, this can be done by typing your base component as an intersection. It looks something like:

```jsx
/* @flow */

import type { ComponentType } from 'react'
import React from 'react'
import styled from 'styled-components'

type SubHeaderProps = {
  textTransform: string,
}
const SubHeader: ComponentType<SubHeaderProps> = styled.h2`
  textTransform: ${({ textTransform }) => textTransform};
`

type HeaderProps = {
  color: string,
}
type HeaderType = {
  SubHeader: ComponentType<SubHeaderProps>,
}
const Header: ComponentType<HeaderProps> & HeaderType = styled.h1`
  color: ${({ color }) => color};
`

// Attach SubHeader on Header
Header.SubHeader = SubHeader

/**************************
 *     Using `styled()    *
 **************************/
const StyledHeader = styled(Header) // Unexpected -- causes flow error: styled() does not allow intersection types
```

## Expected Behavior

Ideally `styled()` wouldn't cause a Flow error here :).

## Actual Behavior

`call of styled. Function cannot be called on any member of intersection type` is thrown by flow.

**Comment by monopieces** [comment]
I have the similar issue since I upgraded flow to `v0.57`

Component like this:
```js
import styled from 'styled-components';
const component = styled.div.attrs({  className: 'Flex' })`
     font-size: 13px;
`;
```

Flow will show an error:
> call of method `attrs`. Method cannot be called on any member of intersection type

**Comment by mxstbr** [comment]
Yep, that would be v nice, I really like the `Component.SubComponent` pattern. /cc @ryyppy any ideas how to do that?

**Comment by msmfsd** [comment]
bump!

**Comment by SilencerWeb** [comment]
still not fixed, huh?

**Comment by wmertens** [comment]
@msmfsd @SilencerWeb your comments are not helpful. PRs are.

I believe the main problem here is that we don't know how to proceed, any ideas?

**Comment by msmfsd** [comment]
@wmertens beyond my knowledge how to do this... Perhaps this can be pushed back for more important PRs?

**Comment by breadadams** [comment]
I'm running into this similar to as @monopieces mentions, I'm trying to use `.extend` on a styled component defined with `ComponentType<Props>`. And trying to use `ReactComponentStyled` from the flow-typed libdef it throws:
```
intersection This type is incompatible with statics of `$npm$styledComponents$ReactComponent`
```
on the `styled.div` (in this case).

**Comment by probablyup** [comment]
@sohkai I'd recommend moving this issue to https://github.com/flowtype/flow-typed since that's where the types are

**Comment by msita143** [comment]
Any update on this?

**Comment by probablyup** [comment]
no
