### ISSUE TITLE
Confusing behavior with ampersand selector

### ISSUE THREAD

**Issue by mrtkrcm** [styled-components/styled-components#1351]
Hi,

I'm having confusing behavior with the plugin. I'm not quite sure this is a bug or expected behavior but I couldn't find any answer for this online neither docs.

## Steps to reproduce
Create a styled component
```
const StyledComponent = styled(Component)`
.parent {
  & .hede {
    color:black
  }
}`
```

## Expected Behavior / Output
`.rm-promotional .hede{color:black;}`

## Actual Behavior / Output
`.iQAcRJ .rm-promotional .hede{color:black;}`

It includes the unique class of the component when I use ampersand sign to get parent selector. Is it normal? If yes, is there any way to get parent selector like SASS?

Cheers

**Comment by mxstbr** [comment]
This is intended behavior, the ampersand always resolves to the unique class of the component. To get the parent selector just write `.parent .hede` :wink:

**Comment by mrtkrcm** [comment]
Sorry, my mistake. The example I gave doesn't explain my issue well. Please check following example. My target is to use an ampersand instead of using hard-coded parent class as you provide.

## Steps to reproduce
Create a styled component
```
const StyledComponent = styled(Component)`
.parent {
  &__kido {
    &__kido + &__kido1 {
      color: red
  }
}`
```

## Expected Behavior / Output
```
.jWYrOs .parent__kido + .parent__kido1 {
    color: red;
}
```

## Actual Behavior / Output
```
.jWYrOs .parent__kido + .jWYrOs .parent__kido1 {
    color: red;
}
```

Pay attention to selector after + in actual behavior. It prepends unique class before parent with this it's not possible to use the ampersand.

**Comment by thysultan** [comment]
There is a missing closing `}` bracket in your example. I get the following when i include that into the example:

```css
.#id .parent__kido__kido + .#id .parent__kido__kido1 {color:red;}
```

This is expected behavior, identical to how sass might handle this [https://www.sassmeister.com/gist/d3f195349c51210b58076f057abb432e](https://www.sassmeister.com/gist/d3f195349c51210b58076f057abb432e) where `id` represents the unique component class.

That said in your expected/actual examples don't both `#id .parent__kido + .parent__kido1 { color: red; }` and `#id .parent__kido + #id .parent__kido1 { color: red; }` archive the same result with the only difference being that the later has more explicit specificity?

**Comment by mxstbr** [comment]
:ok_hand:

**Comment by mrtkrcm** [comment]
Thank you for your respond @thysultan 

Your example has #id grandparent my example has not. This is better to example: https://www.sassmeister.com/gist/a0d0edcf464c230778cebde664d2cd41

With this behavior in some cases(like mine) its impossible to use the ampersand. So it means the plugin changes functionality/usage of SASS. It would be cool if there will be some styled-components only selector to get parent without unique class.

Cheers

**Comment by thysultan** [comment]
The id in the example is a placeholder to demonstrate what s-c generates, so this.

```css
styled.div`
.parent {
  &__kido + &__kido1 {
    color: red
  }
}
```

Is treated like sass would treat the following.

```css
div {
  .parent {
    &__kido + &__kido1 {
      color: red
    }
  }
}
```

That is to say, it uses the same parent > child name-spacing* mechanism found in sass.

>With this behavior in some cases(like mine) its impossible to use the ampersand.

Note sure i see the problem, the only difference between the expected vs actual is the added specificity.

**Comment by philpl** [comment]
@mrtkrcm It'd be helpful to understand what you're *actually* trying to achieve apart from your current approach :wink: I hope that I can help you nonetheless for now.

> `&__kido + &__kido1`

I understand that you're trying to apply some kind of BEM modifiers as sibling identifiers here? This is actually not something we'd recommend, but to detail what `&` does,

The parent selector, or ampersand, or simply `&`, resolves to the component class. This is not the dynamic class that is generated depending on dynamic props. Thus `&` is going to resolve to the "wider" component's id.

At the same time you're trying to achieve something that doesn't behave like the CSS nesting dictates it to behave.

So maybe you can detail your use case and we can help you to clear up the confusion
