### ISSUE TITLE
Ship flat bundles instead of a lib folder

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components#1359]
Based on [this blogpost by the React core team](https://reactjs.org/blog/2017/12/15/improving-the-repository-infrastructure.html#compiling-flat-bundles) we should ship flat bundles instead of the `lib` folder we have right now.  Essentially, rather than shipping tons of files we'd only ship two bundles that contain the CommonJS code.

This will make it possible for us to experiment with Google Closure Compiler, ref #1360.

**Comment by juristr** [comment]
Nice 👍. The angular team also ships their libs as FESM (Flat ES Modules). Here's the spec they use: https://docs.google.com/document/d/1CZC2rcpxffTDfRDs6p1cfbmKNLA6x5O-NtkJglDaBVs

Also gave a talk about it last week: https://youtu.be/K4YMmwxGKjY. Maybe it helps 🙂

**Comment by GGAlanSmithee** [comment]
Interesting how the bundle winds are blowing, but the reasons mentioned in the linked article are sound, it was am interesting read. Am I right in that this won't start the es module bundle at all? @mxstbr what are you looking for as a first step regarding this?

**Comment by mxstbr** [comment]
I don't know how to start this off to be honest @GGAlanSmithee. I guess a good first step would be to look at Reacts rollup config and figure out the parts that are related to the flat CJS bundles?

We already use rollup to create our `.js` and `.min.js` UMD bundles for script tags and the `.es.js` esm bundle for bundlers to get better treeshaking, so it might not be too.hard to copy those parts and output two more bundles maybe?

**Comment by Andarist** [comment]
Going to prepare a PR for this.

**Comment by mxstbr** [comment]
Amazing @Andarist, can't wait! 😍

**Comment by wardpeet** [comment]
I can work on closure if you like.

**Comment by mxstbr** [comment]
@wardpeet that'd be awesome, please comment in #1360!
