### ISSUE TITLE
Replace Uglify with Google Closure Compiler

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components#1360]
Based on [this blogpost by the React team (@gaearon)](https://reactjs.org/blog/2017/12/15/improving-the-repository-infrastructure.html#migrating-to-google-closure-compiler), we should look into replacing Uglify with [Google Closure compiler](https://github.com/google/closure-compiler-js).

We're already using ES modules and Rollup, so we're basically pretty far of the way there. The last step to get this into the realm of possibilities is shipping flat bundles, ref #1359.

**Comment by ConAntonakos** [comment]
Perhaps this PR will be helpful as a reference? https://github.com/facebook/react/pull/10236/files

**Comment by wardpeet** [comment]
I'll have a look at this one

**Comment by probablyup** [comment]
This ends up being more trouble than it's worth. We'll get some nice bundle savings with the various improvements planned for 4.0
