### ISSUE TITLE
Conjuction with loaded CSS

### ISSUE THREAD

**Issue by papigers** [styled-components/styled-components#1368]
## Explanation
I'm using [antd](https://ant.design) which uses css/less for styling its components.
See it's usage [here](https://ant.design/docs/react/introduce#Use-modularized-antd). The issue occurs when I'm using "modularized antd", importing specific component css every time component is imported, using `babel-import-plugin` is advised, but I've confirmed this issue occurs even without the plugin.
The problem is that the generated css from styled-components gets inserted into the head before the imported antd css, which causes the antd default css override mine.
I'm currently using `!important` to overcome this, but clearly this is not very ideal.

## Version
styled-components: 2.2.4
babel-plugin-styled-components: 1.3.0

## Reproduction
See this bin: https://www.webpackbin.com/bins/-L0dBNToN7h_iyqiPjqA

## Steps to reproduce
Reorder the following lines on `Root.js`:
```js
import GlobalSpin from './GlobalSpin';
import GlobalHeader from './GlobalHeader';
```

## Expected Behavior
No matter the imports are organized, the styled global header should override default antd styles (Global header background color should always be white).

## Actual Behavior
When GlobalSpin is imported before GlobalHeader, antd styles take precedence.

I realize this might not be an actual issue with styled-components, as the way antd does styling is very problematic, but I figured maybe you guys could help.

**Comment by mxstbr** [comment]
Use the multiple `&&&` workaround from https://github.com/styled-components/styled-components/issues/1253#issuecomment-337871693!
