### ISSUE TITLE
Prettier pre-commit hook

### ISSUE THREAD

**Issue by lukebelliveau** [styled-components/styled-components#1372]
Now that [we're using prettier](https://github.com/styled-components/styled-components/issues/589) to keep our formatting consistent, is there interest in a pre-commit hook to ensure all commits are Prettified? I've had great success with this in my day job, but I'm not sure how common this is on large open-source projects.

If this _is_ something we want, which direction would we want to go in? There are [a few options](https://prettier.io/docs/en/precommit.html) on the Prettier docs. I've always used the `lint-staged` with `husky` solution, but I'd like to hear thoughts on this.

I'm happy to pick this up myself if we want it implemented.

**Comment by mxstbr** [comment]
Yes yes yes yes! Let's go `lint-staged` with `husky`.

**Comment by philpl** [comment]
This should already work since we’re using the prettier eslint plugin :) but I’m all for switching to husky

**Comment by lukebelliveau** [comment]
Cool, I'll try to get around to this tonight. I'll post back before I get started, so if anybody wants to pick it up beforehand, feel free!

**Comment by existentialism** [comment]
@lukebelliveau really we're just talking about switching from `pre-commit` -> `husky` yeah?

As @philpl already mentioned It's already running `eslint --fix` (and prettier via `eslint-plugin-prettier`) via lint-staged?

**Comment by glennreyes** [comment]
> @lukebelliveau really we're just talking about switching from pre-commit -> husky yeah?

And prettier, which would be a concurrent linting step within lint-staged. If we move prettier over to lint-staged, we can add `eslint-config-prettier` and remove the eslint plugin.

**Comment by lukebelliveau** [comment]
I think I'm almost done here. I'm under the impression we want to run this on the _whole_ repo, based on [this comment](https://github.com/styled-components/styled-components/pull/593#issuecomment-351965625). @mxstbr, can you confirm?

I'm also having some issues between `prettier` and the `flow-typed` definitions:
```es6
flow-typed/lodash_v4.x.x.js
[error] flow-typed/lodash_v4.x.x.js: SyntaxError: default is a reserved word (444:55)
[error]   442 |     conforms(source: Object): Function;
[error]   443 |     constant<T>(value: T): () => T;
[error] > 444 |     defaultTo<T1:string|boolean|Object,T2>(value: T1, default: T2): T1;
[error]       |                                                       ^
[error]   445 |     // NaN is a number instead of its own type, otherwise it would behave like null/void
[error]   446 |     defaultTo<T1:number,T2>(value: T1, default: T2): T1|T2;
[error]   447 |     defaultTo<T1:void|null,T2>(value: T1, default: T2): T2;
```

Has anybody seen this before? I'm not super experienced with `flow`, and not sure if this is a bug in `flow`, `prettier`, or our code. [This issue](https://github.com/prettier/prettier/issues/1624) seems somewhat related..

**Comment by philpl** [comment]
@lukebelliveau 

> I'm also having some issues between prettier and the flow-typed definitions:

I do not think we should run either prettier or eslint on the `flow-typed/` folder
