### ISSUE TITLE
Remove syntax highlighting setups and alternative installation instructions from readme

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components#1373]
**CLAIMED BY @Caryyon**

----

@JamesJefferyUK added the alternative installation instructions the website (ref: https://github.com/styled-components/styled-components-website/pull/192) and @SaraVieira added the the syntax highlighting setups to the website (ref: https://github.com/styled-components/styled-components-website/pull/191), so we should remove them from the README of this repo since there's really no need for them to be there anymore.

This is a great first issue, **I'd like for someone who's never contributed to open source before (or only very little) to pick this up.** Please comment below to claim the task if you want to work on it. (so we don't have two people tackling this at the same time)

Our [contributing instructions](https://github.com/styled-components/styled-components/blob/master/CONTRIBUTING.md#code-contributions) should help you get setup locally with the repo. Then, you have to delete those two sections from the readme (delete them entirely) and submit a Pull Request with your changes.

If you're unsure how to submit a Pull Request, again check the steps in the contributing guidelines. If those don't make any sense, I'd recommend watching http://makeapullrequest.com, and if you're still stuck after that comment here and we'll help you out!

**Comment by WendellAdriel** [comment]
I created some small projects and helped other small projects, but never helped any great and important project. I can help with this!!! xD

**Comment by mxstbr** [comment]
Since @Caryyon was just a tiny bit faster I'm going to give it to them, but @WendellAdriel we have a bunch of other good first issues too! https://github.com/styled-components/styled-components/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22 https://github.com/styled-components/styled-components-website/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

**Comment by WendellAdriel** [comment]
Oh, there's no problem!!! xD
I didn't saw @Caryyon reply!! I'll check the issues, thanks @mxstbr!!! :wink:

**Comment by Caryyon** [comment]
@mxstbr should I close this issue now?

**Comment by mxstbr** [comment]
You did this, right? So yep, if it's done close it!
