### ISSUE TITLE
v2.3.3 data-* attributes lost

### ISSUE THREAD

**Issue by donovan-graham** [styled-components/styled-components#1379]
## Version
styled-components: 2.3.3

## Reproduction
As of version 2.3.3 Styled components are stripping out `data-*` attributes and not passing them on or respecting them in the rendering.  Rolling back to 2.3.1 seems to still keep the desired behavior.  These attributes should also continue to be passed on to any components that are extended by styled-components.

## Steps to reproduce
```
const Node = styled.div` background-color: red;`
export default Component = () => <Node data-value="it works">Test</Node>
```

## Expected Behavior
Html output
```
<div class="auto-generated"  data-value="it works">Test</div>
```

## Actual Behavior
Html output
```
<div class="auto-generated">Test</div>
```

**Comment by probablyup** [comment]
Investigating

**Comment by probablyup** [comment]
@donovan-graham out of curiosity, do you have multiple of the same data attribute in your codebase? wondering if it has something to do with regex stickiness

**Comment by probablyup** [comment]
Tested it locally and I'm not seeing this behavior:

<img width="560" alt="screen shot 2017-12-20 at 11 18 08 am" src="https://user-images.githubusercontent.com/570070/34216830-7cd63ec8-e577-11e7-8cd2-d437cb6fcf6e.png">

<img width="407" alt="screen shot 2017-12-20 at 11 18 28 am" src="https://user-images.githubusercontent.com/570070/34216850-87478a4c-e577-11e7-980f-88b347c0c108.png">

**Comment by mxstbr** [comment]
@donavon-graham are you sure you're on `v2.3.3` and not `v2.3.1`? Maybe I mis-published? That patch should've fixed the bug, not introduced it.

**Comment by jonathaningram** [comment]
FWIW I had to roll back to `v2.3.0` to get things working again. Neither `v2.3.3` nor `v2.3.1` worked for me.

**Comment by probablyup** [comment]
It's definitely working in 2.4.0. Please try upgrading @jonathaningram and @donovan-graham

**Comment by jonathaningram** [comment]
@probablyup works for me, cheers.

**Comment by probablyup** [comment]
Glad to hear it!
