### ISSUE TITLE
Conditional styling not working in React Native

### ISSUE THREAD

**Issue by paulxuca** [styled-components/styled-components#138]
## Version

1.0.8
## Code

Styling code  

```
const LinkText = styled.Text`
  font-family: Avenir;
  opacity: ${ props => props.active ? 1 : 0.3 }
`;
```

Component Render Code  

```
<LinkText active>Hello</LinkText>
```
## Expected Behavior

Link text should have full opacity (1)
## Actual Behavior

Link text has the opacity 0.3, as if it is not active

**Comment by suevalov** [comment]
Looks like the props are not being passed at all.

**Comment by mxstbr** [comment]
Fixed by the amazing @haikyuu in #190! Will be released soon!

**Comment by jh3y** [comment]
Is there an ETA on that release?  Or best to pull in `master` for now?

Keen to use `styled-components` 👍

**Comment by mxstbr** [comment]
Released as 1.0.11! 🎉

**Comment by jh3y** [comment]
Hero!

**Comment by jh3y** [comment]
Unfortunately I'm not getting any joy with this :cry:

I'm getting `can't find variable: props` error.

My implementation is;
```js
import styled from 'styled-components/native'

const StyledEl = styled.View`
  background-color: ${(props.light) ? 'white' : 'black' };
`
```

Anything I'm missing?

**Comment by jh3y** [comment]
To add, previously it was as if the props were just being ignored, there was no error.

**Comment by jh3y** [comment]
Seems this [PR](https://github.com/styled-components/styled-components/pull/171) could fix the issue but awaiting a rebase 👍 

Hopefully this can get pushed in sharp. I'd be happy to do the rebase but I don't think that's logistically possible :joy:

**Comment by mxstbr** [comment]
You just have a typo there, it needs to be a function:

`${props => props.light ? 'white' : 'black'}` should work!

**Comment by jh3y** [comment]
Ah brilliant! Thanks, typical to miss something simple 😄  :joy:
