### ISSUE TITLE
type prop is rendered for div elements

### ISSUE THREAD

**Issue by doque** [styled-components/styled-components#1383]
## Version
styled-components: 2.2.4
babel-plugin-styled-components: 1.3.0

## Reproduction
https://www.webpackbin.com/bins/-L0rwqKG605DVicM-YK5 (inspect the rendered markup of the green box)

## Steps to reproduce
Use a prop that occurs for HTML elements (e.g. `type`) for a styled component.

## Expected Behavior
For HTML elements that don't have a type attribute, it should not be rendered.

## Actual Behavior
The rendered markup includes the type attribute, e.g. `<div class="xx888" type="SUCCESS"/>`

**Comment by k15a** [comment]
Looks like this is fixed in https://github.com/styled-components/styled-components/releases/tag/v2.3.2 so you might want to upgrade styled-compoennts.

**Comment by doque** [comment]
Awesome, thanks for the quick update!

**Comment by doque** [comment]
@k15a It doesn't look like its fixed, see https://www.webpackbin.com/bins/-L0rwqKG605DVicM-YK5 running `react@16.1.0` and `styled-components@2.3.2`.

```js

const Box = styled.div`
  height: 100px;
  width: 100px;
`;

const Message = Box.extend`
  ${({ type, theme }) => type === 'success' ? `background-color: ${theme.success};`: '' }
`;

// returns <div class="sc-bwzfXH glPayP" type="success">Awesome!</div>
<Message type="success">Awesome!</Message>
```

**Comment by k15a** [comment]
Ok looks like we've never had this filtering. Also not sure if we should add it because it basically doesn't hurt anyone. Is it a problem for you app?

**Comment by mxstbr** [comment]
Yeah we've never filtered attributes based on the DOM node that's rendered. That would add an even huger amount of unnecessary weight to the package, for basically no gain since it doesn't really hurt to have the `type` prop on a `div`.
