### ISSUE TITLE
How to style a slider thumb with styled-components

### ISSUE THREAD

**Issue by Lauchi** [styled-components/styled-components#1384]
I am trying to style a slider with styled-components for React, but I do not get how I can style the thumb. I have a CSS that looks like this:

    .faderInput::-webkit-slider-thumb {
       -webkit-appearance: none;
        width: 15px;
        height: 15px;
        border:1px solid black;
        ...
    }

and my styled component looks like this

    const FaderInput = styled.input`
        ...
        ::-webkit-slider-thumb {
            -webkit-appearance: none;
            width: 15px;
            height: 15px;
            border:1px solid black;
            ...
      }
    `;

Does anybody know how I can port this class selector to styled-components?

**Comment by mxstbr** [comment]
```JS
const FaderInput = styled.input`
    &::-webkit-slider-thumb {
        -webkit-appearance: none;
        width: 15px;
        height: 15px;
        border:1px solid black;
  }
`;
```
