### ISSUE TITLE
Warning when `ref` is used vs `innerRef`

### ISSUE THREAD

**Issue by jackfranklin** [styled-components/styled-components#1385]
Hello!

I just lost some time debugging because I used `ref` on a styled component vs `innerRef` which does what I want.

In the dev build I would love a warning from styled-components telling me that I've probably done that. It feels rare that the actual behaviour of `ref` is what I'd like.

I'm happy to take on the PR if you think it's a reasonable idea?

Jack

**Comment by mxstbr** [comment]
I would _love love love_ to do that, but I think React doesn't tell the component that it has a ref attached to it :cry:

```JS
class SomeComp extends Component {}
// SomeComp does not know whether or not it has a ref attached :(
<SomeComp ref={whatever} />
```

That being said, if you can figure out a way to make this happen we'd very much appreciate a PR! (`src/models/StyledComponent.js` and `src/models/StyledNativeComponent.js` are the relevant files)

**Comment by jackfranklin** [comment]
Ah rubbish, I was hoping you'd be able to figure out that `SomeComp` had a `ref` attached to it. I'll do some digging but I am pretty sure you're right, thinking about it!

**Comment by jackfranklin** [comment]
You could do this via a babel plugin that detected a `ref` on a styled component and duplicated it as `notRightRef` and the component would detect that, or something similar. Not sure that's worth the effort though!

**Comment by mxstbr** [comment]
Yeah we've thought about that, but unfortunately Babel isn't aware which components are styled or not across files/folders/etc. :cry:

Really really great idea, we just can't do it. Maybe one day React will let us do this :sparkles: Anyways, good suggestion!
