### ISSUE TITLE
Confusion about using "Styling any Components" with styled components (Pro/Cons)

### ISSUE THREAD

**Issue by mtin79** [styled-components/styled-components#1386]
Hi out there,
i wasn't able to get into the styled-components sprectrum chat (due to Internal Server Error), so i am taking my question to this place.

I am relatively new to react(js) and looked for the best ways to add styling to a new medium sized react project. When i found styled-components it looked like the most promising solution to solve all my styling problems.

So this is how i started, and got stuck:

1. As i usually start with an import of Bootstrap 4 css / js. So i imported the corresponding css and js files in the index.js to reference its classes in my components.
2. I added the styled-components Theming for my global colors, sizes, ...
3. THIS IS WHERE I TO GET STUCK: 
3.1 For trivial (simple/flat) presentational components i see how styled-components is an amazing choice. 
3.2 But what about more complex components with two or more levels deep? So this would be an example of a LoginForm - Component:

**.../components/LoginForm/LoginForm.js**
```
import React from 'react';
import LoginHeader from './LoginHeader';
import LoginForm from './LoginForm';
import LoginFormTitle from './LoginForm/LoginFormTitle/LoginFormTitle';
import LoginFormFields from './LoginForm/LoginFormFields/';

const Login = (props) => {
  return (
    <div className="row">
      <div className={props.className}>
        <LoginHeader>Login</LoginHeader>
        <LoginForm>
          <LoginFormTitle>
            {props.title}  // or {children}?
          </LoginFormTitle>
          <LoginFormFields />
        </LoginForm>
       </div>
    </div>
  );
};
export default Login;
```

And now i would like to dress up this component with a style and tend to create the following:

**.../components/LoginForm/styled.js**
```
import styled from 'styled-components';
import Login from './Login';

const LoginStyled = styled(Login).attrs({
  className: ${ props => props.center ? "mx-auto" : ""}
})`
  background-color:grey;
  color: white;
  border-color: black;
`;

export default LoginStyled;
```

And the third file renaming the LoginStyled component to Login component:
**.../components/LoginForm/index.js**

```
import LoginStyled from './styled';

const Login = LoginStyled;

export default Login;
```

to reference it in App.js component like this:

**...App.js**

```
const App = () => (
  <ThemeProvider theme={theme}>
    <Window>
      <Header>
        <Menu />
        <Title />
        <Toolbar>
          <ToolbarItem />
          <ToolbarItem />
          <ToolbarItem />
        </Toolbar>
      </Header>

      <Content>
        <Login  title="Welcome" center />
      </Content>
    </Window>
  </ThemeProvider>
);

export default App;
```

Sorry for typos and other conceptual mistakes as i am new to both (react) and styled-components.
In general i try to figure out if styled-components can be my one-stop shop for all styling tasks and how it's meant to be or how far i can bend it so i can a clean component structure ...

Thanks a lot for help and suggestions!

**Comment by mxstbr** [comment]
The idiomatic way of using styled-components is to go the other way around:

```
const LoginWrapper = styled.div.attrs({
  className: ${ props => props.center ? "mx-auto" : ""}
})`
  background-color:grey;
  color: white;
  border-color: black;
`;

const Login = (props) => {
  return (
    <div className="row">
      <LoginWrapper>
        <LoginHeader>Login</LoginHeader>
        <LoginForm>
          <LoginFormTitle>
            {props.title}  // or {children}?
          </LoginFormTitle>
          <LoginFormFields />
        </LoginForm>
       </LoginWrapper>
    </div>
  );
};
export default Login;
```

Rather than using the `styled(Login)` way of doing things and attaching the class name, create a small Wrapper component that you use instead of the `<div className={props.className} />`!

Hope that helps

**Comment by mtin79** [comment]
Additionally i don't really understand the statement on the styled-components pages regarding "Styling any Component":

> Consider carefully whether to wrap your own components in a styled component, when it isn't necessary. You will disable the automatic whitelisting of props, and reverse the recommended order of styled components and structural components.

**Comment by mtin79** [comment]
@mxstbr : Thanks Max for your quick reply and help.
For me styled-components looks like a a Decorator (Pattern) for react components.
So what would be wrong about using styled-components in the way i laid out above? (Maybe clarifying it with the statement in the quote above?)

Thanks a lot for help!

**Comment by mxstbr** [comment]
> Consider carefully whether to wrap your own components in a styled component, when it isn't necessary.

Self explanatory

> You will disable the automatic whitelisting of props,

We ship a whitelist of valid DOM attributes, and filter them from the props you pass to your components. For example:

```JSX
const Button = styled.button``

// This JSX:
<Button primary />

// outputs this HTML:
<button class="sc-asdf123 asdf123" />

// Note how the primary _prop_ of the component is not attached as an attribute to the DOM
```

```JSX
const CustomButton = (props) => <button {...props} />
const Button = styled(CustomButton)``

// This JSX:
<Button primary />

// outputs this HTML:
<button class="sc-asdf123 asdf123" primary="true" />
```

> and reverse the recommended order of styled components and structural components.

The idiomatic way of using styled-components encourages the creation of small, encapsulated components that do one thing and do it well. (styling/layout) This leads to a more understandable system overall, since more easily understanding the small pieces leads to more easily understandable big pieces.

**Comment by mtin79** [comment]
@mxstbr : Thanks again Max.
For me (as a newbie) to react, your explanations clarified a lot!
Sorry to bother you as it seems really trivial to you i suppose.

Last remaining question for me is this: 

So that means for every depth / layer i should basically create a styled component?
As i got a lot of structural elements like this in my react project (due to bootstrap layouting):

```
<div class="container">
  <div class="row">
    <div class="col-XYZ">
      <OtherComponents ...>
    </div>
  </div>
</div>
```

I was hoping to create "one" styled component out of them. To encapsulate layout into one.
```
<StyledComponent>  // which previously was the 3 divs .
  <OtherComponents ...>
</StyleComponent>
```


Thats why i came up with things like above:

const ConceptualComponent = (props) => {
  return (
_............ these three elements should be styled and hidden via styled components as one: ............._
  <div className="container">
     <div className="row">
      <div className={props.className}>
_.................................................................................................................................................._
       {props.children}
      </div>
    </div>
  </div>
  )
};

const StyledComponent = styled(ConceptualComponent).attrs({
  .....
  })`
`;
        
So i guess my confusion was about how to facilitate styled-components to slim down html-elements with styling into one placeholder component.
