### ISSUE TITLE
Question: How to write styles with a deep structure in react native?

### ISSUE THREAD

**Issue by rtkhanas** [styled-components/styled-components#139]
I really like `styled-components`, it is great, thank you @mxstbr for a this module.

I'm trying to use it with react native, but cannot find a way to describe this case:

```
style: {
  transform: [
    { perspective: 850 },
    { translateX: - Dimensions.get('window').width * 0.24 },
    { rotateY: '60deg'},
  ],
}

export default styled.View`
  transform: ???;
`;
```

Is it possible? Thank you in advance.

**Comment by mxstbr** [comment]
Huh, that's interesting, I didn't know that was possible in ReactNative! I don't think we support this right now – what would that look like in CSS?

**Comment by JamieDixon** [comment]
In CSS I think this would look like:

```
perspective: 850;
transform: translateX(-123) rotateY(60deg)
```

Where `perspective` is a valid stand-alone CSS property and `translateX` sand `rotateY` are both function values that are composed with a space.

**Comment by rtkhanas** [comment]
I don't know all the cases in RN since I just started working with it, but I see that there is also:

```
shadowOffset ReactPropTypes.shape(
  {width: ReactPropTypes.number, height: ReactPropTypes.number}
)
```

Here is more info:

https://facebook.github.io/react-native/docs/shadow-props.html#props
https://facebook.github.io/react-native/docs/transforms.html#props

Could be nice to have `perspective` as a 1st level prop, in that case it can be reused in react for web as well. But seems like there are many cases possible, so can be like:

```
transform-perspective: 850;
transform-rotate: 60deg;
shadow-offset-width: 1;
```

This way we have a clean logic how to write those styles without learning and remembering all those expectional cases, but just `perspective: 850;` looks better and reusable in this particular case.

**Comment by jacobp100** [comment]
I have an implementation [here](https://github.com/jacobp100/cssta/blob/master/cssta/src/native/bodyTransform.js). @mxstbr suggested a separate module for this, and I agree. If you want to set up the repo, I wouldn’t mind helping out. (Or I can set up the repo—whatever’s easiest for you)

**Comment by jacobp100** [comment]
Will do!

**Comment by mxstbr** [comment]
Closing in favor of #210, which will add support for this!
