### ISSUE TITLE
Home page playground error

### ISSUE THREAD

**Issue by maicss** [styled-components/styled-components#1390]
**animations** field

url: https://www.styled-components.com/docs/basics#animations

## Steps to reproduce
Modify any code, 
```
render(
  <Rotate>&lt; 💅&gt;</Rotate>
);
```
will add `>"`after the icon
It's like your xss rules error.

**Comment by maicss** [comment]
![image](https://user-images.githubusercontent.com/9784767/34350540-456a87de-ea52-11e7-9b0e-74ad1e0d81a6.png)

**Comment by philpl** [comment]
Can you report this on the react-live repo please: https://github.com/FormidableLabs/react-live

Cheers :wink: I'll keep an eye on this and will fix it asap
