### ISSUE TITLE
typescript compiler complains about use object inside interpolation

### ISSUE THREAD

**Issue by plrthink** [styled-components/styled-components#1397]
## Version
styled-components: 2.2.4
polished: 1.9.0
typescript: 2.6.2

## Reproduction
https://codesandbox.io/s/ol58j538p9

## Steps to reproduce
use ellipsis function the way docs said.

````js
const StyledButton = styled.button`
  ${ellipsis('12rem')};
`
````

## Expected Behavior
would compile without warnings or errors

## Actual Behavior
but ts compiler complains the following:
````bash
Argument of type 'Object' is not assignable to parameter of type 'Interpolation<ThemedStyledProps<DetailedHTMLProps<HTMLAttributes<HTMLHeadingElement>, HTMLHeading...'.
  The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?
    Type 'Object' is not assignable to type 'ReadonlyArray<string | number | Styles | StyledComponentClass<any, any, any> | InterpolationFunct...'.
      The 'Object' type is assignable to very few other types. Did you mean to use the 'any' type instead?
        Property 'length' is missing in type 'Object'.
````

Of course, I can cast the ellipsis function's return type to 'any', but it would not work if 'no-any' is on. 

Another workaround I'm currently using is `${[ellipsis('12rem')] as InterpolationValue[]};`.

**Comment by mchandler-cng** [comment]
I've seen this same issue. Seems to happen in every case where the interpolation does not contain a function definition. My use case was something like the following:

```javascript
const withIcon = ({ src, size, top, right, bottom, left }: IconProps) => css`
	${left && `left: ${left};`};
	${right && `right: ${right};`};
	${top && `top: ${top};`};
	${bottom && `bottom: ${bottom};`};
`
```

Each line inside the tagged template literal fails with `Argument of type 'string | undefined' is not assignable to parameter of type 'Interpolation<ThemedStyledProps<ThemeInterface>>` unless I use the workaround @plrthink mentioned. Can post a reproduction if needed.

**Comment by philpl** [comment]
cc @styled-components/typers

**Comment by probablyup** [comment]
Hey folks, TS typings for styled-components have been moved to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), so please feel free to move your issue there where you'll receive better community support.
