### ISSUE TITLE
Keyframes

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components#14]
We need to get keyframes to work, maybe something like this?

```JS
styled.div`
@keyframes {
  0% { color: transparent; }
  100% { color: awesome; }
}
`;

**Comment by geelen** [comment]
Hmm. How about:

```js
import styled, { keyframes } from "styled-components"

const animationName = keyframes`
  0% { color: transparent; }
  100% { color: radboats; }
`

const Div = styled.div`
  animation: ${animationName} 0.3s 0s both;
`

**Comment by mxstbr** [comment]
I like this as an underlying primitive and exposed API point, but same as with media queries – the user shouldn't have to be aware of the stuff we do to make their lives easier. Writing `@keyframes` into your string should _just work_, just like `@media`.

**Comment by geelen** [comment]
How do you attach the keyframes to the element though? Just have css-modules like name mangling?

```
styled.div`
animation: local-name 0.3 0s both;
@keyframes local-name {
  0% { color: transparent; }
  100% { color: awesome; }
}
`;
```

**Comment by mxstbr** [comment]
Ah I forgot you have to define more than just `@keyframes`, dang. Warming to your idea now!

**Comment by geelen** [comment]
So, my example above looks really bad to me, because it breaks the metaphor for `styled.tag`:

```js
const Div = styled.div`
  /* any css here */
`
```

is the _exact_ equivalent of this (this example could be useful in the docs in future)

```css
.class-ac32cf84 {
  /* any css here */
}
```
```jsx
const Div = ({children, className, ...props}) => (
  <div class={`class-ac32cf84 ${className}`} {...props}>
    {children}
  </div>
)
```

right? We're allowing nesting and `@media` and `&` to define extra classnames which feels good because it works just like Sass. But defining `@keyframes` _within_ a definition doesn't really make any sense:

```css
.class-ac32cf84 {
  animation: local-name 0.3 0s both;
  @keyframes local-name {
    0% { color: transparent; }
    100% { color: awesome; }
  }
}
```

That doesn't really make any sense. In Sass or in any PostCSS or anything, keyframes are always global.

I'm thinking we should instead do this:

```js
const LocalName = styled.keyframes`
    0% { color: transparent; }
    100% { color: awesome; }
`
const Div = styled.keyframes`
  animation: ${LocalName} 0.3s 0s both;
`
```

Then we can also do something like `styled.global` for injecting global styles, since we wanted to have that capability as well, right?

**Comment by haikyuu** [comment]
Bonus point, you can use 
```javascript
function rotationBuilder(degree) {
  const rotation = keyframes`
    0% {
      transform: rotate(0deg);
    }
    25% {
      transform: rotate(-${degree}deg);
    }
    50% {
      transform: rotate(0deg);
      opacity: .9
    }
    75% {
      transform: rotate(${degree}deg);
    }
  `;
  return rotation;
}
```
```javascript
const StyledDiv = styled.div`
  animation: ${rotationBuilder(10)} 1s linear infinite;
`
```

Which is totally awesome. @mxstbr  I wonder if we still need animations in js ?

**Comment by ljsherlock** [comment]
I wanted to add the following for anyone that is, like I was, trying to find a way to make **keyframes** work with a styled component created via the **object method.**

```js
let FieldMarker: any = styled('div')(
  props => ({
    position: 'absolute',
    width: props.theme.space[6],
    height: props.theme.space[6],
    left: `${props.x}px`,
    top: `${props.y}px`,
    '&:after': {
      position: 'absolute',
      left: 0,
      right: 0,
      top: 0,
      bottom: 0,
      margin: 'auto',
      transform: 'scale(0, 0)',
      backgroundColor: props.active && 'rgba(34, 203, 233, .2)',
      borderRadius: '50%',
      content:'""',
      height: '3.5em',
      width: '3.5em',
    }
  })
)

FieldMarker = styled(FieldMarker)`
  &:after {
    animation: ${css`${markPulse} 3s ease-out infinite;`}
  }
```
