### ISSUE TITLE
Proposal: Unmount components when the display property is set to none 

### ISSUE THREAD

**Issue by fdidron** [styled-components/styled-components#140]
Hello,

Following a conversation with @mxstbr on Twitter, I would like to get users opinion on the following:

**Proposal**
Styled component unmount when their display property is set to none .

**Allows**
A built in way to conditionally mount / unmount UI parts (Based on the application state or media queries for example).

**Use case**
We are currently building an Intranet application with an IM feature that listens to message events on the server side. The IM widget should only be displayed on Desktops. Currently we have an HOC that listens to the matchmedia event to mount / unmount the widget based on the screensize.

**Questions**
1. Should it be an opt-in / opt-out feature or the default behavior
2. Performance related concerns ?
3. Other use cases ?

I'm fine to make a PR if this proposal is accepted.

**Comment by mxstbr** [comment]
This is such an interesting idea. I have no idea what the tradeoffs here are though. I wonder if Radium does this?

**Comment by degroote22** [comment]
This complicates server side rendering a lot...
As long as srr has a simple fallback for this we're good.

**Comment by vdanchenkov** [comment]
My concern is that temporary change of screen size would destroy local state of component.

By temporary change I mean (often accidental) switching between landscape and portrait on tablets, manual drag of window border to see another app, opening of dev tools. 

For example, in use case described by @fdidron it would clear message log and <textarea> with message not sent yet, if not handled specially.

So I think it's at least too aggressive to enable by default.

**Comment by fdidron** [comment]
@vdanchenkov In my example, as you mentioned, I'm handling state via a global store  (mobx) so it wouldn't be an issue, but users needs to be aware of this.

I agree with you, it should be an optin behavior !

**Comment by geelen** [comment]
Hmm, I'm not really in favour of this, to be honest. If anything, it'd be better to delete the CSS on a `componentWillUnmount` callback but that seems unnecessary too. If the styles aren't being used, or if a component has `display: none` set and therefore isn't being displayed, what's the harm in having those styles existing in the CSS?

**Comment by mxstbr** [comment]
Yeah same here, I think this has too many edge cases for us to implement safely. Thanks for kicking off this discussion though @fdidron!

**Comment by smeijer** [comment]
I would love this one actually. But I guess it can be done trough a plugin?

I already see myself writing code like:

```js
const Button = styled.button`
  /* Adapt the colors based on primary prop */
  background: ${props => props.primary ? 'palevioletred' : 'white'};
  color: ${props => props.primary ? 'white' : 'palevioletred'};

  font-size: 1em;
  margin: 1em;
  padding: 0.25em 1em;
  border: 2px solid palevioletred;
  border-radius: 3px;
`;

export default Button;
```

```jsx
<Button renderIf={userCanCancel}>Cancel</Button>
<Button primary>Submit</Button>
```
