### ISSUE TITLE
Styled Components does not allow me to set a background color

### ISSUE THREAD

**Issue by Leisors** [styled-components/styled-components#1400]
So, just found out about Styled Components. I go on and _yarn add_ it to my react native project, set it up and this happends:

```
Invariant Violation: Invalid prop `backgroundColor` supplied to `StyleSheet generated`: '#166191'
Valid color formats are
  - '#f0f' (#rgb)
  - '#f0fc' (#rgba)
  - '#ff00ff' (#rrggbb)
  - '#ff00ff00' (#rrggbbaa)
  - 'rgb(255, 255, 255)'
  - 'rgba(255, 255, 255, 1.0)'
  - 'hsl(360, 100%, 100%)'
  - 'hsla(360, 100%, 100%, 1.0)'
  - 'transparent'
  - 'red'
  - 0xff00ff00 (0xrrggbbaa)

StyleSheet generated: {
  "flexGrow": 1,
  "flexShrink": 1,
  "flexBasis": 0,
  "backgroundColor": "'#166191'"
}
```

Here is my _common.js_ file to group the few common styles in my app
```javascript
import styled from 'styled-components/native';

export const Container = styled.View`
    flex: 1;
    background-color: '#166191';
`;
```

On my component I import the container through
`import { Container } from '../styles/common';`
and use it as `<Container>`.
Why is this not working :'(

(moving all the code inside of the component file does not change anything)

**Comment by gribnoysup** [comment]
@Leisors have you tried without quotes around the color value?

```
export const Container = styled.View`
    flex: 1;
    background-color: #166191;
`;
```

**Comment by Leisors** [comment]
Oh damn, how did I miss that? That's exacly what it was.
I was so sure that the syntax would have been identical to css.
When you stop noticing those things it's clearly time to take a break.

Thanks dude!

**Comment by AdamZikmund** [comment]
Had same problem :D overworked 👍

**Comment by ttchuah** [comment]
Ditto. Taking out the quotes did it for me. Thanks!

**Comment by fbartho** [comment]
Super unobvious & frustrating given the error message includes single quotes around all the example views.

But now that I know, I guess it works. Thanks for the workaround @gribnoysup

**Comment by alessandrocapra** [comment]
> @Leisors have you tried without quotes around the color value?
> 
> ```
> export const Container = styled.View`
>     flex: 1;
>     background-color: #166191;
> `;
> ```

It finally worked, thanks!
