### ISSUE TITLE
Extended component class names are identical to source since 2.4.0

### ISSUE THREAD

**Issue by a-type** [styled-components/styled-components#1402]
I've found a change in behavior in 2.4.0 regarding a use case which I have throughout my projects.

## Version
styled-components: 2.4.0
babel-plugin-styled-components: 1.1.4

## Reproduction
Here's a bin with `styled-components@2.1.0` showing the old behavior and an example use case:
https://www.webpackbin.com/bins/-L21eW94UfVVgVMuHpFB

Here's a bin with `styled-components@2.4.0` showing the new behavior:
https://www.webpackbin.com/bins/-L21fE4nVqxENjuFYlZg

This also happens when you have two entirely separate components which happen to share the same display name. That becomes especially tricky when using the Babel transform... it may not be ideal, but I also bet it's not uncommon for users to define multiple `const Button = styled.button\`...` components at various parts of large applications.

A bin of that: https://www.webpackbin.com/bins/-L21qbcO5llu9TPJihao

## Steps to reproduce
1. Create a component with a display name
2. Create another component by `.extend`ing the first one
3. Reference the original component in a css selector and apply specific rules
4. Reference the extended component in a subsequent selector and apply different rules
5. Result: the original component matches the second selector

This behavior occurs whether the display name is provided using `withConfig` or via the Babel transform.

## Expected Behavior
A variant of a styled-component which was created with `.extend` will receive a unique class name. When referenced as a parent in a css selector, that selector will not match the original component which was extended.

## Actual Behavior
A variant of a styled-component which was created with `.extend` keeps the same class name as the original, and selectors for either component match both.

## Notes
This behavior is the direct result of the new hashing introduced in 2.4.0, but I wasn't sure if this was an intentional change or not, so I thought some discussion might be welcome before submitting a PR.

The biggest problem I can see with the new behavior going forward is that I believe it's now impossible to differentiate between a source component and a component which was `.extend`ed from it using component selectors alone.

I'm also not aware of any way to tell that a component is extended during the hashing, so I'm guessing that may have to be added to generate unique but stable class names for extended components. Fixing for the extended case also doesn't fix for the identical display name case. As much as I agree with the desire to have consistent hashing, I think it's also good not to have to wonder whether your component's name collides with another in your project or external libraries before you use it in a selector.

**Comment by probablyup** [comment]
Please upgrade your version of the babel plugin.

**Comment by mxstbr** [comment]
Yeah, we changed the hashing algorithm in the Babel plugin too so if you upgrade that to the latest version it should resolve your issue I think

**Comment by a-type** [comment]
Thanks for the suggestion. I've got `2.4` and `1.4` installed respectively, but the problem persists.

I read the changes to the hashing algorithm on the babel plugin side, it seems that the simplified hash now only computes based on the file name. In our code, we use `.extend` to attach 'variant' components to a main component within a single file. See an example of the source [here](https://github.com/Bandwidth/shared-components/blob/styled-components-1.4/src/components/Navigation/styles/NavigationBar.js). The component has three variations, all of which are used as 'reverse selectors' in nested children to change rules (like [here](https://github.com/Bandwidth/shared-components/blob/styled-components-1.4/src/components/Navigation/styles/NavigationItem.js#L41)).

Though complex, this pattern was inspired by the docs. While it may be argued that components should be defined in separate files, I don't think the way we've attached variants within a single file is unreasonable; nor does the babel plugin require or recommend that components be defined in separate files (as far as I've read).

As a fix, I can go and explicitly define `displayName`s for all my variants using `withConfig`, which will work to get us on the new version. Or, I could stop using reverse selectors (but I like them, so I'll go with the first option).

Still, users who do not use the babel plugin will also see the change in behavior I documented with the webpack bins in the original issue, although I could definitely understand if you considered behavior around extending components with explicit `displayName`s as undefined, since it's not clearly documented what should happen. But nevertheless the behavior is a bit confusingly inconsistent in 2.4, where adding a `displayName` to the base component will transform extended component classnames into copies of their parent, as demonstrated in [this bin](https://www.webpackbin.com/bins/-L2VcnmlJuT46m7kVjRl).

To summarize...

* Defining an extended component in the same file:
  * With babel plugin:
    * When no displayNames specified: generates identical classnames **(behavior changed)**
    * When the base component has a displayName: generates identical classnames **(behavior changed)**
    * When both have unique displayNames: generates unique classnames
  * Without the babel plugin:
    * When no displayNames specified: generates unique classnames
    * When the base component has a displayName: generates the identical classnames **(behavior changed)**
    * When both have unique displayNames: generates unique classnames


I hope I'm not being too nit-picky on this. Tone is hard to convey in text... I love this library; I'm practically obsessed with it :smile:. And I'm a fan of more stable class names. I just wanted to be sure that the behaviors were documented, since I ended up spending a lot of time head-scratching on this issue and understanding the different permutations of outcomes. Perhaps a lot of this could be cleared up if it was more explicit what exactly an `.extend`ed component is meant to be. I inferred that it would be basically a unique, deep-copied entity; but this isn't consistent with the new behavior regarding reverse selectors.

**Comment by philpl** [comment]
So, this is somehow connected to this: https://github.com/styled-components/babel-plugin-styled-components/issues/79

It's a little confusing to be honest, but basically we currently have no way to attach a component ID to `.extend`. I think the recent changes just make the bug surface in a different way.

**Comment by marcelosedano** [comment]
For what it's worth, I was having a similar issue to this where any extended styled component I created would result in the same component as the original. After spending hours trying to debug the issue, upgrading my versions of `styled-components` and the Babel plugin, I was ultimately able to resolve it by disabling the `"preprocess": true` option that I had previously enabled for the `babel-plugin-styled-components` in my `.babelrc`.

Hope this helps someone else!

**Comment by a-type** [comment]
@philpl I didn't see that thread, but the discussion looks very relevant. After reading it, I definitely sympathize with the '`.extend` is confusing' camp. I used extend for our variant definitions completely because of the recommendations in the [FAQ](https://www.styled-components.com/docs/faqs#when-should-i-use-styled) and how negative it seemed to be toward `styled()`. And at first glance, I'm quite partial to the solution proposed in #1209, given that using `css\`\`` instead of extending from a base component would probably be my next go-to solution for implementing our variant patterns.

**Comment by philpl** [comment]
@a-type thanks for your thoughts! In all honesty, I steered the docs towards the extends API as I thought it better than the non-explicit styled() which encourages some other adverse patterns.

But in the future, we will definitely encourage composition and mixins over inheritance. We’ll just have to make some necessary changes first

**Comment by a-type** [comment]
@philpl Looking forward to those changes! I'll go ahead and pivot our project to use `css` mixins for now as a solution. Hopefully this discussion will steer anyone running into the same issues I did.

**Comment by fatfisz** [comment]
I spotted this issue today too; either inlining the styles or using the `styled(BaseComponent)` wrapper works.

I was thinking about this a bit, and maybe having named exports `extend` and `withComponent` would solve the issue? After all it's as easy (hard?) to check if they are being used as the `styled` export.

**Comment by a-type** [comment]
Seems like this will be addressed by the deprecation / removal of `.extend` https://github.com/styled-components/styled-components/issues/1546
