### ISSUE TITLE
[React Native] Unsupported CSS fails silently when using react-native-web

### ISSUE THREAD

**Issue by Zacqary** [styled-components/styled-components#1403]
Working with `styled-components` and `react-native-web` can be frustrating, because things like:

```js
const StyledView = styled(View)`
  &:hover { /* some hover state */ }
`
```

will just not compile on the web without throwing an error. It'd be really helpful for multi-platform projects to know when our web-specific syntax is getting stripped so that we can refactor correctly.

**Comment by probablyup** [comment]
If you use the stylelint styled-components setup, I think https://github.com/kristerkari/stylelint-react-native will be useful for you.

This seems like a better task for a linter than the library itself.
