### ISSUE TITLE
Base class name change breaks margin

### ISSUE THREAD

**Issue by haniotis** [styled-components/styled-components#1407]
## Version
2.2.4

## Reproduction

Margin isn't being applied because the base class name has changed and the adjacent selector no longer works. Code example is self-explanatory.

https://codesandbox.io/s/m35jv98oxx

## Expected Behavior
Margin is applied on every element

## Actual Behavior
Margin isn't being applied

**Comment by philpl** [comment]
It’s a known issue: https://github.com/styled-components/styled-components/issues/1275

And there is a workaround for it: https://github.com/styled-components/styled-components/issues/1258#issuecomment-338241207

We’ll hopefully have the ability to fix it properly and securely once we introduce an actual parser 😬

**Comment by haniotis** [comment]
Thanks!
