### ISSUE TITLE
Use third party component seems to be broken

### ISSUE THREAD

**Issue by santaclauze** [styled-components/styled-components#141]
## Version
1.0.9

I can't use the third party wrapper and get no styles on my rendered component: 

    import React from 'react';
    import styled from 'styled-components';
    
    class Nav extends React.Component {
    
        render() {
    
            return (
                <nav>
                    <button info type="button">REGISTER</button>
                    <button type="button">LOGIN</button>
                </nav>
            );
    
        }
    }
    
    
    let Nav2 = styled(Nav)`
      color: #222;
      border: 3px solid red;
      background: blue;
      font-size: 1.5em;
      font-family: Helvetica, Arial, sans-serif;
      text-align: center;
    `;
    
    
    export default Nav2;

## Reproduction
http://www.webpackbin.com/EyvHTuK1f

## Expected Behavior

Expect Nav border to be 3px solid and red and background blue

## Actual Behavior

Nav use default styling

**Comment by santaclauze** [comment]
Solved this using this syntax:

    const Nav = styled.nav`
      position: fixed;
      top: 0;
      left: 0;
      right: 0;
      border: 3px solid red;
      height: 3.5em;
      box-shadow: 0 0 2px rgba(0,0,0,.5);
      padding: 1em;
      display: flex;
      align-items: center;
      background-color: #fff;
      z-index: 1;
    `;
    
    
    class NavStyled extends Nav {
    
        render() {
            return (
                <Nav>
                    <Button info type="button">REGISTER</Button>
                    <Button type="button">LOGIN</Button>
                </Nav>
            );
        }
    
    }
    
    export default NavStyled;

**Comment by vdanchenkov** [comment]
@santaclauze

First example would work if you changed render to
```jsx
<nav className={this.props.className}>
   <button info type="button">REGISTER</button>
   <button type="button">LOGIN</button>
</nav>
```

In second example what is the reason to extend Nav? Will it work for you with:
```jsx
class NavStyled extends Component {
  ...
}
```

Both ways are not ideal. I've been thinking lately about styling container tag. For now I settled on this pattern for small components. 
 
```jsx
const thru = (styledComponent, f) => f(styledComponent)

// or, if you use babel-plugin-styled-components-named

const  thru = (styledComponent, f) => {
  const component = f(styledComponent)
  component.displayName = `${styledComponent.displayName}Wrapper`
  return component
}

const Nav = thru(styled.nav`
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  border: 3px solid red;
  height: 3.5em;
  box-shadow: 0 0 2px rgba(0,0,0,.5);
  padding: 1em;
  display: flex;
  align-items: center;
  background-color: #fff;
  z-index: 1;
`, Root => props => (
  <Root>
    <button info type="button">REGISTER</button>
    <button type="button">LOGIN</button>
  </Root>
) )
```

**Comment by vdanchenkov** [comment]
Another approach https://twitter.com/jamiedixon/status/791239301602353152

**Comment by bhough** [comment]
@santaclauze You're missing a small piece. If you look at the [Third Party component](https://github.com/styled-components/styled-components#third-party-components) part of the docs you will see a note about including a `className` on the "third-party" component you are styling in order for the class that is generated to be properly applied.

Here is an example: http://www.webpackbin.com/4JR5NCY1f

**Comment by mxstbr** [comment]
@bhough is totally correct, all that's needed to make that example work is to attach the `className` to an actual DOM element as mentioned in the third party component docs!

**Comment by santaclauze** [comment]
Hey sorry for not answering. To be honest, I am learning how to code and my friend put me on this project. He actually asked the question for me and I did not want to continue the discussion as I was afraid to look too much like a noob :) Thanks for the info though, I am still working on this topic :)

**Comment by mxstbr** [comment]
> I did not want to continue the discussion as I was afraid to look too much like a noob

Let me tell you something @santaclauze – never ever be afraid to ask a question or say your opinion. As soon as you stop being curious, you stop learning. Always ask questions, figure out what you want to know, discuss with people!

Good luck with learning to code! :blush:

**Comment by jh3y** [comment]
It seems I'm having trouble with this slightly too. Can you use the third-party component feature with `react-native` too?

I am trying to use it without JSX and instead use `React.createElement`, is this possible?

My code is something like the following;

```js
import styled from 'styled-components/native'
import Button from 'components/Button'

const styledButton  = styled(Button)` ... styles ...`
const styledText      = styled.Text` ... styles ... `

const newButton = React.createElement(styled(Button), newProps)
const newText = React.createElement(styledText, someProps)
```

The `newText` element would work as expected, but nothing is rendered for `newButton` :cry:

When I inspect the element Object inside the remote debugger, it has `type.displayName` of `Styled(undefined)` as if it can't see the third party component yet the `type.target` property seems correct in that it shows the `Button` constructor.

Is there something simple I'm missing here? I've added a `className` prop in my props also.
