### ISSUE TITLE
Hoist non react statics

### ISSUE THREAD

**Issue by oliviertassinari** [styled-components/styled-components#1411]
### What will it allow you to do that you can't do today?

Solve https://github.com/mui-org/material-ui/issues/9736 out of the box. We add a `muiName` static property to some of the Material-UI components. However, this static property is lost after wrapping the component with styled-components.

### How will it make current work-arounds straightforward?

You are already solving the problem for withTheme:
https://github.com/styled-components/styled-components/blob/1dfc7a64ff8ff3706424d68bbe021b8f973ff9db/src/hoc/withTheme.js#L6

### What potential bugs and edge cases does it help to avoid?

It's making the styled component higher-order component transparent to static properties.

**Comment by mxstbr** [comment]
Sounds reasonable.

**Comment by philpl** [comment]
@mxstbr I’m not 100% convinced. This would possibly encourage the use of the styled function as a HOC 

I’m not sure whether we need to pass through all static properties, assuming that the user always has access to the underlying ones. I think we can add it — Also got to consider that it adds a minor initialisation cost — but it would maybe encourage some other patterns

**Comment by danez** [comment]
The same applies to `react-tabs` which also assigns static properties to its components so the wrapping component can identify his children. The are sadly lost when using styled components and people use workarounds to get it working. https://github.com/reactjs/react-tabs/issues/148#issuecomment-368809171

**Comment by probablyup** [comment]
Hmm I thought we were already doing this. It's considered a best practice for anything wrapping another component, so I think we should do it.

**Comment by probablyup** [comment]
I believe we would need to exclude our own properties from hoisting though or it will screw up style rule ordering.

**Comment by chengjianhua** [comment]
@kitten I think it's necessary to cover this requirement.

For example:

`styled.js`

```javascript
import { Select as RawSelect } from 'antd';
import styled from 'styled-components';

export const Select = styled(RawSelect)``;
```

`app.js`

```javascript
import { Select }  from './styled';

const { Option } = Select.target;

export default function App() {
  return (
    <Select>
      <Option>Option 1</Option>
      <Option>Option 2</Option>
    </Select>
  );
}
```

If a component is a sub-component of an another and that component needs to be styled, the step of getting the sub-component would be verbose.

**Comment by chengjianhua** [comment]
@probablyup Is this issue ended without disagreement?

**Comment by probablyup** [comment]
@chengjianhua it was fixed and released as part of https://github.com/styled-components/styled-components/releases/tag/v3.3.0

**Comment by chengjianhua** [comment]
Sorry ... I didn't notice that. Super! 👍 @probablyup

**Comment by keatz55** [comment]
So how do you get this to play nicely with typescript? Whenever I try to access a hoisted static property I get something like the following:
```
Property 'Summary' does not exist on type 'StyledComponentClass...
```
