### ISSUE TITLE
Easy way to disable styles?

### ISSUE THREAD

**Issue by JamesBliss** [styled-components/styled-components#1413]
Hi,

I have some complex styling in some of my components but on occasion I need them to render without any styling my only options seems to be:

Add a new prop which wraps the styling like this which has issues if referencing other components:

```
const UiButton = styled.button`
  ${ props => props.themeNone ? `` : `
    padding: 0;
    box-sizing: border-box;
  `};
`;
```

Have a second component which is the same minus using any of the styled components e.g. just render the button element.
Is there a better way to do it?

**Comment by mxstbr** [comment]
This question is probably better suited for the community: https://spectrum.chat/styled-components please ask there!

**Comment by philpl** [comment]
> I have some complex styling in some of my components but on occasion I need them to render without any styling

not sure why you'd do this 🤔 maybe the underlying approach could entirely be changed?

Fwiw, you could just wrap it in a structural component that switches it out with a normal element actually, maybe?

**Comment by JamesBliss** [comment]
@philpl the idea would be that if someone was to use my components and not want to use the styling provided through styled components they could.

**Comment by mxstbr** [comment]
But then... What are your components? :sweat: An HTML `<input>`? That doesn't seem very valuable to use by somebody else...

**Comment by philpl** [comment]
@JamesBliss So this is indeed a problem since it should be worthwhile to avoid `styled(YourComponent)` to keep the structure of the styled "elements" clean.

I'd recommend you to look into `renderProps` :wink: they could enable you to style a component using styled-components, while keeping it customisable enough to "eject" from them

**Comment by JamesBliss** [comment]
Yeah pretty much, but all the onClick, onBlur, error, santization etc etc that an input would do is useful just not the style layer.

**Comment by mxstbr** [comment]
Oh I see, I'd probably in your case then do something like

```JS
export class UnstyledInput extends Component {
  /* ... */
  render() {
    return <input className={this.props.className} />
  }
}

export default styled(UnstyledInput)`
  color: blue;
`
```

Now your users can do

```JS
import Input, { UnstyledInput } from 'input';
```
