### ISSUE TITLE
[Typescript + Suggestion] Add withStyles, withAttrs Api

### ISSUE THREAD

**Issue by zheeeng** [styled-components/styled-components#1415]
A general situation is applying the same stylesheet on different components and tags. In Vanilla Javascript it is easy to curry styled function:

```js
const withStyles = (...styleRules) => {
    let settedAttributes = {}
    const storeAttrs = (attributes) => Object.assign(settedAttributes, attributes)
    const applyStyles = (component) => styled(component).attrs(settedAttributes)(...styleRules)
    applyStyles.attrs = (attributes) => {
        storeAttrs(attributes)
        return applyStyles
    }
    return applyStyles
}

const withAttrs = ...blabla

// general usage:

const StyledComponent = withStyles`
   font-size: 50px;
`.attrs({ data: 'hello' }).attrs({ title: 'world' })(Component)


// specific usage:

const makeFullHeight = withStyles`
    height: 100%
`
const FullHeightSidebar = makeFullHeight(Sidebar)
const FullHeightCard = makeFullHeight(Card)
```

But in typescript, It's hard to define the `withStyles` function. One reason is that it is hard to declare the component types which are accepted by `styled` function. Unless extracting a lot of declaration from [here](https://github.com/styled-components/styled-components/blob/master/typings/styled-components.d.ts#L53-L59) and reorganize them to shape the `withStyles`. I also tried to use generics to curry `styled` function, unfortunately, it failed. See https://github.com/Microsoft/TypeScript/issues/21062

`styled` itself used many overloads to implementation. It's what Typescript not good at and I can't properly curry it with type-safe.

So I plead **Add built-in withStyles and withAttrs function and their Typescript types declarations** to solve this problem.

**Comment by probablyup** [comment]
Hey folks, TS typings for styled-components have been moved to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), so please feel free to move your issue there where you'll receive better community support.
