### ISSUE TITLE
Accessing reference returned by innerRef in componentDidUpdate

### ISSUE THREAD

**Issue by joetidee** [styled-components/styled-components#1419]
I am using innerRef like this:

```
const Back = styled.a``;

class NavBack extends Component {

    componentDidUpdate() {
        //setTimeout(() => this.backLink.focus(), 2000);
        this.backLink.focus();
    }

    render() {
        return (
            <Back
                tabIndex="0"
                innerRef={backLink => {
                    this.backLink = backLink;
                }}
            >Some Link</Back>
        );
    }
}
```

Although the `<a>` tag does get focus, it causes some strange positioning on the wrapper component of `<Back>`, where the wrapper is using `transition: all .3s ease-in-out;` and `transform: translateX(-20%);`. Putting this behaviour to one side, I just wanted to ask if there is likely to be an issue accessing `backLink` from `componentDidUpdate`. The reason I ask this is because when I uncomment the `setTimeout` line above, the positioning behaviour no longer exists.

**Comment by philpl** [comment]
This truly sounds like some odd behaviour. I'd love to help you looking into this, but can you quickly copy some more relevant code into a CodeSandbox? There's a link to a precreated one in the issue template if you need it :wink:

Also, the question here seems to be lost a little. I'm not sure what the wrapper is doing with `transform` and when; it'd be helpful to see in the CodeSandbox reproduction.

**Comment by joetidee** [comment]
ok. I figured it out. Not related to styled-components.
