### ISSUE TITLE
How to whitelist props after wraping custom component in styled

### ISSUE THREAD

**Issue by vegetablesalad** [styled-components/styled-components#1422]
I read in documentation that :

> Consider carefully whether to wrap your own components in a styled component, when it isn't necessary. You will disable the automatic whitelisting of props, and reverse the recommended order of styled components and structural components.

My question is if there is any way around this? I need a way to apply style to custom components, from legacy code or different libraries. But doing it this way I loose all my props, so IDE and transpiler is throwing me errors.

```
export interface MyProps {
    hello:string;
}

export type AllProps = MyProps & ButtonProps;

let ClearButton:React.SFC<AllProps> = ({className,children}) =>
    <Button className={className} {...this.props}>{children}</Button>;
    
const RegularButton = styled(ClearButton)`
    color: greenyellow;
    font-weight: bold;
`;

export {RegularButton};
```

```
 // I can't access **hello** prop here
 <RegularButton hello="aaa" >test</RegularButton>
```

**Comment by amcculloughflexera** [comment]
@vegetablesalad did you ever get a way around this, also having the same issue

**Comment by probablyup** [comment]
Hey folks, TS typings for styled-components have been moved to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), so please feel free to move your issue there where you'll receive better community support.
