### ISSUE TITLE
[native] missing styled.ImageBackground and styled.SafeAreaView

### ISSUE THREAD

**Issue by IljaDaderko** [styled-components/styled-components#1424]
## Version
styled-components: 2.2.4

## Reproduction

https://www.webpackbin.com/bins/-KeeZCr0xKfutOfOujxN
https://codesandbox.io/s/rkmNRByE4

## Steps to reproduce

```
import styled from "styled-components/native";

const Example = styled.ImageBackground /* Not available */
const Examle2 = styled.SafeAreaView /* .Not avaliable */
```

## Expected Behavior

Components are not yet documented I think, but should be available on `styled`? As they can be imported from "react-native"

**Comment by philpl** [comment]
This will be fixed as part of https://github.com/styled-components/styled-components/pull/1339

**Comment by IljaDaderko** [comment]
@philpl gotcha, had a quick glance, looks like it is adding SafeAreaView, but not ImageBackground however.

**Comment by mxstbr** [comment]
We should add that to that PR?

**Comment by breadadams** [comment]
Just ran into `ImageBackground` not working, turns out it wasn't included over in `flow-typed`, should be fixed when https://github.com/flowtype/flow-typed/pull/2203 is merged

**Comment by femiveys** [comment]
SafeAreaView still seems to be missing

**Comment by probablyup** [comment]
@femiveys try the latest release
