### ISSUE TITLE
Typescript checking error

### ISSUE THREAD

**Issue by yordis** [styled-components/styled-components#1428]
```jsx
import * as React from 'react'
import styled from 'styled-components'

interface ISVGIconProps {
  color: string,
  children: React.ReactNode,
  titleAccess: boolean,
  size: string,
  viewBox: string
}

const SVG = styled.svg`
  display: inline-block;
  fill: currentColor;
  height: ${(p: any) => p.size};
  width: ${(p: any) => p.size};
  user-select: none;
  flex-shrink: 0;
  color: ${(p: any) => p.color};
  transition: ${(p: any) => p.theme.transition.create('fill', { duration: p.theme.transition.durations.shorter })};
`

export const SVGIcon: React.StatelessComponent<ISVGIconProps> = (props) => {
  const { titleAccess, children, size, ...others } = props

  return (
    <SVG
      width={size}
      height={size}
      // @ts-ignore
      size={size} // <--- this is the issue
      focusable="false"
      aria-hidden={titleAccess ? 'false' : 'true'}
      {...others}
    >
      {titleAccess ? <title>{titleAccess}</title> : null}
      {children}
    </SVG>
  )
}

SVGIcon.defaultProps = {
  color: 'inherit',
  size: '1.5em',
  viewBox: '0 0 24 24'
}

```

```
[ts] Property 'size' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ThemedOuterStyledProps<SVGProps<SVGSVGEl...'.
```

Basically any attribute that do not belongs to specific element (whatever that means because after custom element we do not need to do `data-` anymore but I guess make sense to the old elements?!)

Typescript will complains that any extra attribute I add for the propose of using it in my styled component it will rise this issue.

**Comment by yordis** [comment]
cc @styled-components/typers

**Comment by DogPawHat** [comment]
Having a similar issue here

**Comment by DogPawHat** [comment]
Ok, I looked into this, it's fixed as far as `styled-components` are concerned, but there's some issues with Typescript.

Bascilly, `styled-components` already has this:

https://github.com/Microsoft/TypeScript/issues/11947

```
export interface ThemedStyledFunction<P, T, O = P> {
  (strings: TemplateStringsArray, ...interpolations: Interpolation<ThemedStyledProps<P, T>>[]): StyledComponentClass<P, T, O>;
  <U>(strings: TemplateStringsArray, ...interpolations: Interpolation<ThemedStyledProps<P & U, T>>[]): StyledComponentClass<P & U, T, O & U>;
  attrs<U, A extends Partial<P & U> = {}>(attrs: Attrs<P & U, A, T>): ThemedStyledFunction<P & A & U, T, O & U>;
}
```

where `U` could be used to define additional prop types:

```
interface MyProps {
    primary: boolean;
    // etc...
}

const MyButton = styled.button<MyProps>`
  color: ${props => props.primary ? 'white' : 'red'}
`
```

Unfortunaly, this syntax doens't work, and the issue below has been open for over a year:

https://github.com/Microsoft/TypeScript/issues/11947

So I don't know when that will get fixed.

---

That said, usually this works: 

```
interface MyProps {
    primary: boolean;
    // etc...
}

const MyButton = styled.button`
  color: ${(props: MyProps) => props.primary ? 'white' : 'red'}
`
```

at least on TS 2.6.2. your `(p: any)` should otherwise be fine, I think.

**Comment by probablyup** [comment]
Is there anything actionable here from our side?

**Comment by nderscore** [comment]
There's a working solution for this in [styled-components-ts](https://github.com/jacob-ebey/styled-components-ts)  (though the npm package doesn't seem to be working for me right now?)

https://github.com/jacob-ebey/styled-components-ts/blob/master/src/styled-components.ts

**Comment by alveshelio** [comment]
@nderscore, I was able to install styled-components-ts, however, I'm having two problems.
One is that TSLint is complaining that styled-components-ts is not listed in the dependencies in package.json and I've double checked and it is listed there.

The other issue I have is the following.

I have this code in app.tsx:

`
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import styled, { ThemeProvider } from 'styled-components';
import styledComponentsTS from 'styled-components-ts';

import { ThemeInterface, theme } from './theme';
import Message from './components/message';

const Wrapper = styledComponentsTS<ThemeInterface>(styled.div)`
    background-color: ${(props) => props.theme.primaryColor};
    color: ${(props) => props.theme.primaryColorInverted};
    width: 1248px;
    margin: 0 auto;
    padding: 10px 20px;
`;

class App extends React.Component<{}, {}> {
  public render() {
    return (
      <ThemeProvider theme={theme}>
        <Wrapper>
          <Message title='This is my beautiful message' message='This is the body of my beautiful message' />
        </Wrapper>
      </ThemeProvider>
    );
  }
}

ReactDOM.render(<App />, document.getElementById('app'));
`
and in theme.ts I have this code:
`
export interface ThemeInterface {
  primaryColor: string;
  primaryColorInverted: string;
}

export const theme: ThemeInterface = {
  primaryColor: '#2196F3',
  primaryColorInverted: '#DE690C',
};
`
My Wrapper styled-component is giving me the following error:

Error:(21, 9) TS2322: Type '{ children: Element; }' is not assignable to type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ThemedOuterStyledProps<ThemeInterface & ...'.
  Type '{ children: Element; }' is not assignable to type 'Readonly<ThemedOuterStyledProps<ThemeInterface & HTMLProps<HTMLElement>, any>>'.
    Property 'primaryColor' is missing in type '{ children: Element; }'.

I'm not sure I understand this message and I really don't know if I'm setting up things properly.

**Comment by nderscore** [comment]
@alveshelio I can't speak for why you're running into linting issues, but I can see why you're getting that type error.

`styledComponentsTS` takes a generic interface that describes props. In your snippet, you're passing an interface that describes the theme object.

Since `ThemeProvider` passes the theme to styled components as a prop called `theme`, your interface should probably look like this:

```javascript
export interface WrapperProps {
  theme: ThemeInterface
}

// ...

const Wrapper = styledComponentsTS<WrapperProps>(styled.div)`
  ...
`;
```

**Comment by nickbreaton** [comment]
If you are looking for other solutions for typings, I had published a small module to help with this as well. Feel free to check it out. Not asking for it to be incorporated in this repo (don't think that would be appropriate), but it might help someone out.

https://www.npmjs.com/package/styled-with-props

**Comment by DogPawHat** [comment]
`styledComponentWithProps` from styled-components-ts just returns what you pass in with types, so its doen't add much beyond fixing this issue. It might still be the best fix until Microsoft/TypeScript#11947 gets fixed.

@yordis have you had any luck with your issues?

**Comment by yordis** [comment]
@DogPawHat no joke

```
npm uninstall typescript
```

I gave up to Typescript, productivity is more valuable for me than preventing issues that I do not face.

No more Typescript, best scenario `flow` for props validation and I am thinking on using `prop-types` for that even.

**Comment by DogPawHat** [comment]
@yordis Fair enough.

**Comment by nderscore** [comment]
@philpl Issue #630 provides some more context.

`styled-components` does not provide any way to extend the prop typings of built-ins that use tagged template literals syntax. 

[TypeScript currently offers no way to pass a generic type interface to a tagged template literal function](https://github.com/Microsoft/TypeScript/issues/11947), so a wrapper function (like the one found in `styled-components-ts`) that takes a generic is the only workaround that exists right now.

Perhaps this wrapper function could be implemented as part of `styled-components` so an additional library isn't needed, but the _real_ solution for this needs to come from Typescript.

**Comment by jacob-ebey** [comment]
Addressing styled-components-ts, it exists simply to add typechecking and let you have intellisense in your ide. If you are a TypeFreek and want to keep "noAny" on in your project, this allows it. As @DogPawHat  mentioned, there is a deeper issue here that the Typescript team needs to address before any true fix can be added to the styled-components library.

**Comment by bwlt** [comment]
@yordis are you sure that `size` is a valid attribute to be passed to an SVG element? I cannot find it in [this MDN reference](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute#SVG_attributes_A_to_Z)

I solved a similar issue on a input[type=checkbox] extending the Prop interface.
In your case define `ISVGIconProps` like this:
```
interface ISVGIconProps extends React.SVGProps<SVGElement>  {
  color: string,
  children: React.ReactNode,
  titleAccess: boolean,
  size: string,
  viewBox: string
}
```
Then you have to remove the `size` prop (because it is not recognized) and (sadly) also the `{...others}` spread (cannot understand why) on `SVG` component.

**Comment by viiiprock** [comment]
yeah I got the same issue, did you resolve this @glensomerville ?

**Comment by jacob-ebey** [comment]
@viiiprock See https://github.com/jacob-ebey/styled-components-ts

**Comment by AntonioRedondo** [comment]
The  [TypeScript fix](https://github.com/Microsoft/TypeScript/pull/23430) for this issue has been merged into Master and it can be used with the `next` npm version. Any example guys from the `style-components` team to fix the `IntrinsicAttributes...` error?

**Comment by jacob-ebey** [comment]
I'd like to deprecate styled-components-ts, but I'm not willing to do that until there are examples for the community.

**Comment by r4j4h** [comment]
@jacob-ebey 

I feel like having to declare each aspect of styled-system I use is wrong, but this worked for me and made my TypeScript compiler happy:

```
interface HasMarginBottomStyledSystemProps {
  mb?: number;
}

import styled from "styled-components";
import { space } from "styled-system";
let StyledH5 = styled.h5<HasMarginBottomStyledSystemProps>`
  ${space};
`;
```

Then I can use like so

```
<StyledH5 mb={0}>So dumb</StyledH5>
```

And no pesky error from TypeScript!

----

Towards improving things, although I am an absolute newbie to TypeScript, I feel like there should be an easier way to maybe expose all optional props from styled-system by doing something clever with generics maybe like styled-components does like

```
export type StyledSystemDefaultOptionalProps {
  everything like m, p, etc
}
export type StyledSystemStyledProps<P, T> = P & StyledSystemDefaultOptionalProps<T>;
```

Not sure if that was along the lines of what you were looking for or if I'm just re-stating the obvious at this point though.. :(

**Comment by r4j4h** [comment]
Hey guys, we were able to get this working via two ways. One way works now but isn't the official way forward, the other way is the official way forward but is broken until the next TypeScript release (2.9.1)

The interface to allow us to use `mb` margin-bottom shortcut somewhere:

```
import { space } from "styled-system";
interface HasMarginBottomStyledSystemProps {
    mb?: number;
}
```

Example usage (goal is to have it work w/o TypeScript errors):

```
<StyledH5 mb={0}>
    Hello World!
</StyledH5>
```

The first way that works now:

```
let StyledH5 = styled<HasMarginBottomStyledSystemProps, any>("h5")`
   ${space};
`;
```

The future way that will work soon:

```
let StyledH5 = styled.h5<HasMarginBottomStyledSystemProps>`
   ${space};
`;
```

You can track the status of fix for future way here (note the related issues at bottom): https://github.com/Microsoft/TypeScript/issues/24449

* Credit to @robophred for helping me work through the TS syntax issues.

**Comment by AntonioRedondo** [comment]
Hi @probablyup, what's the reason for this ticket being closed? Any progress in the issue?

**Comment by probablyup** [comment]
Because of this:

> Ok, I looked into this, it's fixed as far as styled-components are concerned

If there's nothing to do on our end, the issue doesn't need to be open.
