### ISSUE TITLE
Passed 'onClick' is always executed even when changed in 'attrs'

### ISSUE THREAD

**Issue by MichaelDeBoey** [styled-components/styled-components#1429]
## Version
styled-components: 2.4.0

## Reproduction
[https://codesandbox.io/s/pjl4o8z4yq](https://codesandbox.io/s/pjl4o8z4yq?expanddevtools=1)

## Steps to reproduce
Take a styled `div` and pass in an `onClick` method. Also provide an `onClick` method in the `attrs`.

## Expected Behavior
The newly created `onClick` method in `attrs` gets called.

## Actual Behavior
The passed in `onClick`-method gets called.

**Comment by mxstbr** [comment]
`.attrs` overrides whatever you pass via props, you have to explicitly forward it:

```JS
styled.button.attrs({
  onClick: (props) => props.onClick ? props.onClick : () => console.log('attrs version')
})
```

**Comment by MichaelDeBoey** [comment]
@mxstbr Take a look at my codesandbox please 🙂
It shouldn't be called in that case I think?

**Comment by MichaelDeBoey** [comment]
@mxstbr Your example isn't working either btw 😕
At least not on a `div`...

**Comment by mxstbr** [comment]
Oh I see what you mean, the passed one overrides the `.attrs` one—I got that the wrong way around! Anyways, that still makes sense though for the use case why you'd use `.attrs`. Imagine a PasswordInput:

```JS
const PasswordInput = styled.input.attrs({
  // We want <PasswordInput />s to be input[type="password'], duh
  type: 'password'
})``;

// Somewhere else in the codebase, we might want to show the password if a user has
// selected a checkbox about showing the password to make sure they don't have typos
<PasswordInput type={this.state.passwordVisible ? 'password' : 'text'} />
```

It makes sense that the specific `type` overrides the more generic type, no?

**Comment by MichaelDeBoey** [comment]
It's how you look at it I think, for me it makes more sense to provide something extra to the component, so the component can decide for itself what `type` it is like:

```jsx
const PasswordInput = styled.input.attrs({
  type: ({ passwordVisible }) => passwordVisible ? 'password' : 'text',
})``;

<PasswordInput passwordVisible={this.state.passwordVisible} />
```

That's how I approached this case anyway...

**Comment by mxstbr** [comment]
I think of `.attrs` as a sort-of "set of defaults" more than a fixed restriction, but I see why that could be confusing...

**Comment by MichaelDeBoey** [comment]
The thing is when you have multiple values that depend on a certain `boolean` to change, it's annoying and cumbersome to do the check on all of these values yourself, instead of the component...

**Comment by mxstbr** [comment]
I'm not 100% sure why you couldn't do that anyway, do you have a specific example? It would just set a default rather than a fixed value

**Comment by MichaelDeBoey** [comment]
My case is that you could do

```jsx
const PasswordInput = styled.input.attrs({
  type: ({ visible }) => visible ? 'text' : 'password',
  onChange: ({ disabled, onChange }) => disabled ? null : onChange,
})`
  background-color: ${({ disabled }) => disabled ? 'red' : 'blue'};
`;

<PasswordInput
  disabled={this.state.password.disabled}
  passwordVisible={this.state.password.visible}
/>
```

instead of

```jsx
const PasswordInput = styled.input.attrs({
  type: 'password',
})`
  background-color: ${({ disabled }) => disabled ? 'red' : 'blue'};
  border-color: ${({ visible }) => visible ? 'yellow' : 'green'};
`;

<PasswordInput
  disabled={this.state.password.disabled}
  onChange={this.state.password.disabled ? null : handlePasswordChange}
  passwordVisible={this.state.password.visible}
  type={this.state.password.visible ? 'text' : 'password'}
/>
```

I've taken this a bit extreme, 'cause I don't have a good use case for an `input` at the moment, but I think you see what I mean?

**Comment by MichaelDeBoey** [comment]
@mxstbr My case is that you could do

```jsx
const PasswordInput = styled.input.attrs({
  type: ({ visible }) => visible ? 'text' : 'password',
  onChange: ({ disabled, onChange }) => disabled ? null : onChange,
})`
  background-color: ${({ disabled }) => disabled ? 'red' : 'blue'};
`;

<PasswordInput
  disabled={this.state.password.disabled}
  passwordVisible={this.state.password.visible}
/>
```

instead of

```jsx
const PasswordInput = styled.input.attrs({
  type: 'password',
})`
  background-color: ${({ disabled }) => disabled ? 'red' : 'blue'};
  border-color: ${({ visible }) => visible ? 'yellow' : 'green'};
`;

<PasswordInput
  disabled={this.state.password.disabled}
  onChange={this.state.password.disabled ? null : handlePasswordChange}
  passwordVisible={this.state.password.visible}
  type={this.state.password.visible ? 'text' : 'password'}
/>
```

I've taken this a bit extreme, 'cause I don't have a good use case for an `input` at the moment, but I think you see what I mean?
