### ISSUE TITLE
Styled input field stops accepting additional characters after typing just a single character

### ISSUE THREAD

**Issue by evolve2k** [styled-components/styled-components#143]
## Version
1.0.5

## Reproduction
http://www.webpackbin.com/Ekn1JlskG

## Steps to reproduce
In the provided webpackbin, try typing a word into the input, you will see that the styles are correctly applying but that you can only enter a single character before being stopped.

## Expected Behaviour
Should be able to easily type a sentence like "Styled Components are very fancy".

I suppose technically, would be to say it's not currently possibly to easily write in multiple consecutive characters as is expected behaviour for an input.

## Actual Behavior
Instead you can type the first character being say "S" and then the input maybe looses focus and no further characters can be effectively typed in.

**Comment by vdanchenkov** [comment]
Actual problem here is that you create new InputWrapper component inside the render function of TextField. 

Each key press changes state of TextField which forces new render, which replaces component with a new one.

Move definition of InputWrapper outside of TextField class and it will work just fine.

**Comment by mxstbr** [comment]
What @vdanchenkov is the actual solution, thanks for realizing that!

This breaks with a standard react component as well, try doing this inside your `render` method and you'll see:

```JS
render () {
    const Input = (props) => <input {...props} />
    return (
      <Input
          type="text"
          value={this.state.value}
          onChange={this.handleChange} />
    )
  }
```

**Comment by barbalex** [comment]
It might be a good Idea to point this out in the readme - I'm sure many more will stumble over this.

Thanks for this _GREAT_ tool.

**Comment by barbalex** [comment]
Actually, being new to using es6 classes and being new to using styled-components, I am struggling on how to do this best in an es6 class component. This here seems rather odd:

    class Projekte extends React.Component { // eslint-disable-line react/prefer-stateless-function

      Container() {
        return styled.div`
          display: flex;
          flex-direction: column;
          height: 100%;
        `
      }

      render() {
        const Container = this.Container()

        return (
          <Container>
          </Container>
        )
      }
    }

**Comment by mxstbr** [comment]
Why not just do

```JS
const Container = styled.div`
  display: flex;
  flex-direction: column;
  height: 100%;
`

class Projekte extends React.Component {
  render() {
    return (
      <Container>
      </Container>
    )
  }
}
```

Why are you binding it and overriding the getter in your ES6 class?!

**Comment by barbalex** [comment]
Yeah, meanwhile I have changed to defining styled components outside of the component class too. Thanks!

Sometimes you need access to the store though as Styling may depend on it.

I am still not quite sure how to do this best. But it is an es6 class question and has nothing to do with styled-components, outside of the fact that I do think some other people would benefit from the readme explicitly mentioning that it is important to create styled components _outside_ of the render method - and maybe even have an es6 class example for dummies like me ;-)

**Comment by barbalex** [comment]
@mxstbr @geelen Thanks so much for this great tool - makes working with css so much easier! (and sorry for spamming you)

**Comment by mxstbr** [comment]
If you need to conditionally change the styling pass props to the styled component!

```JS
const Container = styled.div`
  display: flex;
  flex-direction: column;
  height: 100%;
  display: ${props => props.visible? 'block' : 'none'};
`

class Projekte extends React.Component {
  state = { visible: false }
  render() {
    return (
      <Container visible={this.state.visible}>
      </Container>
    )
  }
}
```

**Comment by k15a** [comment]
In addition to @mxstbr comment you can also supply defaultProps and propTypes to `styled-components` and they get used.
```JS
const Container = styled.div`
  background-color: ${props => props.backgroundColor};
`

Container.defaultProps = {
  backgroundColor: 'red',
}
```

**Comment by barbalex** [comment]
Great help, thanks a lot!
