### ISSUE TITLE
Styled components fills head tag with additional unused style tags, doesn't clean them up

### ISSUE THREAD

**Issue by South-Paw** [styled-components/styled-components#1431]
Hi guys, unsure if this is an issue or intended behavior but thought I'd raise this to get a clear answer...

## Version

styled-components: 2.4.0

## Reproduction

We found this in our own apps at my work place and thought it was only for us, but I can also reproduce on the styled components website: https://www.styled-components.com/

(neither of the code bins worked to create a reproduction)

## Steps to reproduce

1. Go to https://www.styled-components.com/
2. Open developer tools, inspect the documents `<head />` tag
3. Inside the editor example on the web page, being making changes to the buttons border (for example)
4. See all the additional tags appearing in the head of the document with every keypress/change to the example

![2018-01-17_08-49-09](https://user-images.githubusercontent.com/2154764/35009042-5c55fb78-fb63-11e7-91d6-92a4cc987488.gif)

## Expected Behavior

I expected/thought that styled component should try to minimize the number of style tags appearing in the head by cleaning up or removing unused styles.

I am or was under the impression that this sort of thing was not occurring before, but I definitely could be mistaken...

## Actual Behavior

Head tag has additional style tags and css classes added that remain unused and are not removed.

This pollutes the head tag of the document, especially noticable on SPAs with lots of styled-components in use.

We are seeing a new style tag added with anywhere between 5 to 20 additional classes appearing on every click/navigation in our app.

This a portion of our apps document head after a few minutes of usage:

![image](https://user-images.githubusercontent.com/2154764/35010094-9f2ea744-fb66-11e7-886d-754a1f245537.png)

Thanks 👍

**Comment by mxstbr** [comment]
Yeah, we don't remove styles as it'd add unnecessary performance overhead—why does it hurt you to have more style tags in the head?

Also, how are you using styled-components so that you "add anywhere between 5 to 20 additional classes appearing on every click/navigation in our app"? That seems like a usage problem rather than a library problem

**Comment by philpl** [comment]
A separate component will be created every time you call styled(). This component receives a componentId and injects it’s styles under there with a hash.

The amount of styles you have there might mean that you have a large app.

But it might also indicate that you’re calling styled() in a render function / stateless component and are recreating it every time. Or it might mean that you’re passing arbitrarily complex float values to it

**Comment by South-Paw** [comment]
Thanks for the super quick replies.

@mxstbr We have an in-house react component library to build our apps from. We have 12 components  from our library used in one of these app and each of those components vary in complexity and size. For example, the two navigation components of our apps - the Header and Sidebar, both have ~12 styled components each. There is also 3 different color themes i n each app which creates the same issue (far lesser than navigating though)

Here's an example of navigation in an app creating more classes in the head:

![2018-01-17_10-03-01](https://user-images.githubusercontent.com/2154764/35012169-b2db3292-fb6d-11e7-8083-dc2c059aafb1.gif)

I'd love to provide you guys with more than just the developer tools but I can't screenshot/gif the app layouts or anything 😒 

@philpl I think that the large app issue may be more of the case - there are heaps of styled components in these apps. However you could also be right that something has been done wrong by us and we are indeed calling styled() too often - is there a way I'd be able to see, gauge or debug this case?

**Comment by South-Paw** [comment]
@mxstbr Sorry, also re your question "why does it hurt you to have more style tags in the head?"

Unsure if it hurts anything necessarily - it just seemed wrong to have the head of the document so polluted like that. I was also wondering how likely collisions were with the class names.

From what I understand, the users of some of these apps will be leaving them running for a few days at a time... so with normal use that could be a lot of classes that are unused.

But, unsure if that's an issue or is fine - this is all why I wanted to raise this and ask the experts 😄

**Comment by South-Paw** [comment]
Hi guys,

Is there any followup or comments on this?

Cheers 👍

**Comment by probablyup** [comment]
It's not something on our roadmap to change in the near future, since it doesn't appear to be a burning issue. I'd recommend following @kitten's advice and working on reducing the dynamicness of whichever component(s) is generating all that excess CSS.

In some cases, a highly dynamic (>3 possible values) style is better to do via inline style.

**Comment by South-Paw** [comment]
I don't think we'll be reducing the dynamicness of our entire component library, it's very much built on top of styled components 😄

But after a month of having this occur (and it was happening before as well) we haven't seen, had or received any performance complaints or other issues with it so I guess that means it's fine as it is.

Thanks for the awesome package and keep it up 👍
