### ISSUE TITLE
.displayName missing in snapshot tests

### ISSUE THREAD

**Issue by doque** [styled-components/styled-components#1432]
We have a great number of buttons in our app and created some handy exports to make them easily usable:

```js
import ActionButton, { PrimaryButton } from '../../ui/buttons/ActionButtons';

export const CancelButton = props => (
  <PrimaryButton
    icon="cancel"
    text={t('popups.actions.cancelAppointment')}
    {...props}
  />
);
// CancelButton.displayName = 'CancelButton';

export const BackAlternativeButton = props => (
  <ActionButton
    icon="arrow-left"
    text={t('popups.actions.alternativesBack')}
    {...props}
  />
);
// BackAlternativeButton.displayName = 'BackAlternativeButton';
```

```js
// ActionButtons.js
import Button from './Button'; // pretty complicated Button that implements sizes, borders, loading etc.

const ActionButton = props => <Button size="l" {...props} />;
const PrimaryButton = props => <ActionButton buttonType="primary" {...props} />;

export default ActionButton;
export { PrimaryButton };
```

The buttons look and work as expected. But when creating snapshot tests (or using `react-storybook`), the displayName used is either `Unknown` or `Component`:
```js
<Unknown
  disabled={false}
  isLoading={false}
  onClick={[Function]}
/>

// if one of the button is contained within React.Fragment, we receive this:
<Component
  disabled={true}
  key="decline"
  onClick={[MockFunction]}
/>
```
Only by manually adding a `displayName` (like above) we get the correct JSX output.
Is this by design? It's a pretty simple workaround (just add `.displayName` properties), but it's a bit annoying nonetheless :-)

## Version
styled-components: 2.4.0
babel-plugin-styled-components: 1.4.0

## Expected Behavior
The snapshot should contain the correct component name.
## Actual Behavior
The snapshot contains `Unknown` or `Component` for the component name.

**Comment by probablyup** [comment]
Is storybook taking your `.babelrc` into account and including `babel-plugin-styled-components`?

**Comment by doque** [comment]
I haven‘t supplied a babelrc, I’m not sure if Storybook includes that by default. But other component names are displayed correctly.

**Comment by philpl** [comment]
@doque you might want to add our babel plugin to both your sources and to Storybook's babel config

https://storybook.js.org/configurations/custom-babel-config/

**Comment by doque** [comment]
Unfortunately that did not help. We're using a pretty basic webpack config for storybook:

```js
module.exports = {
  resolve: {
    modules: ['node_modules', path.resolve(__dirname, '../app')]
  },
  module: {
    rules: [
      {
        test: /\.(svg|png|jpg|gif)$/,
        use: [
          {
            loader: 'file-loader'
          }
        ]
      }
    ]
  }
};
```

Together with this `.babelrc`:

```js
{
  "presets": [
    ["env", { "targets": { "node": true } }],
    "react",
    "stage-2"
  ],
  // this doesn't help
  "plugins": [
    "babel-plugin-styled-components"
  ]
}

```

Adding the babel plugin did not change anything. Interestingly enough, even though the plugin wasn't present anywhere (we define the babel plugins within the webpack configuration we use for dev/build, not for storybook), all component displayNames are rendered correctly, with the above exception.

**Comment by lhache** [comment]
Shouldn't it be like that instead?

```
"babel": {
    "plugins": [
      "styled-components"
    ]
  }
```
I mean `styled-components` instead of `babel-plugin-styled-components`

**Comment by aganglada** [comment]
@doque do you still get that behaviour?

I'm testing with:

```
"styled-components": "^3.3.3",
"babel-plugin-styled-components": "^1.5.1",
```

and I don't get this anymore.
