### ISSUE TITLE
New style blocks should inject after the last one

### ISSUE THREAD

**Issue by probablyup** [styled-components/styled-components#1433]
Currently when rendering in the browser, style blocks are automatically appended to the end of the `<head>` tag: https://github.com/styled-components/styled-components/blob/master/src/models/BrowserStyleSheet.js#L169

We should revise this behavior to instead grab a reference to the last known styled-components style block and inject after that, wherever it is in the DOM (falling back to `document.head` if it's the first one.)

**Comment by probablyup** [comment]
> I'm wondering what can go wrong?

Like what happens if we don't do the above?

The `#1` case I can think of is if you are using SSR and extract the critical CSS but place it in `<body>` instead of `<head>`. When styled-components takes over upon rehydration, any additional styles are injected to the default location (`<head>`) and then if any of those styles are building off the critical CSS, they'll be out of order and manifest all sorts of bugs.

**Comment by chrislaughlin** [comment]
I would be happy to pick this up as a first contribution, is it still valid?

**Comment by mxstbr** [comment]
Yes please @chrislaughlin, that'd be awesome!

**Comment by Amritha777** [comment]
As far as I understand, @chrislaughlin has already implemented a proposed solution to this issue.
Me and @riyak1998 would like to work on this, as a part of our RGSOC application.
Kindly confirm if there is something that still needs to be done (since this issue is still open).

**Comment by chrislaughlin** [comment]
My changes were covered as part of [1501](https://github.com/styled-components/styled-components/pull/1501). This issue should be closed.

**Comment by kitten** [comment]
@chrislaughlin true! thanks for bumping the issue :+1: it'll go out as part of 3.2.0
