### ISSUE TITLE
Dynamic styled(component) by passing component as prop

### ISSUE THREAD

**Issue by samueldepooter** [styled-components/styled-components#1434]
## Version
styled-components: ^2.2.1
babel-plugin-styled-components: ^1.1.7

## Steps to reproduce
1. Create a styled component that takes a prop containing a component and return it.
```js
const Icon = styled(({ component }) => component)`
  background: red;
`
```
2. Use the styled component in your render & pass it a 'component' prop.
```js
<Icon component={<MyCustomIco fill={color} width={size} height={size} />} />
```
3. The outcome should be that the style is applied to
```js
<MyCustomIco />
```

## Expected Behavior

Created a generic styled component, for example Icon. Then I'm passing a component as a prop to the styled component. In the styled component, I write a function that takes out the component prop (containing my component) and returns it. I expect it to use this component to apply the styled component to.

## Actual Behavior
Nothing is being applied to the passed component.

**Comment by probablyup** [comment]
The styles are generated as a `className` which needs to be used in the custom ico component. You could modify your thing like this I think:

```jsx
const Icon = styled(
    ({ component, ...props }) => React.cloneElement(component, props)
)`
  background: red;
`
```

**Comment by samueldepooter** [comment]
Of course! Forgot about that part. Works like a charm 👌

**Comment by philpl** [comment]
@samueldepooter On this note btw, I wouldn't recommend you to use styled-components as "dynamic" render components / HOCs. If possible you should try to keep them static.

If the Icon component is a third party component it's totally fine if you wrap it, but maybe try to pass the right props using our `.attrs()` helper. (More info is on our website)

**Comment by samueldepooter** [comment]
@philpl Thanks! Will take a look at it.

**Comment by anthonator** [comment]
@kitten can you elaborate on or point me to some documentation explaining why dynamic render components are not recommended? Is it the same issue with using `styled` in `render`?

**Comment by plankguy** [comment]
@probablyup's solution works well, but if you want React dev tools to have the node with a displayName, you need to pass a named function rather that anonymous to `styled()`:
```
const Icon = styled(
  Icon = ({ component, ...props }) => React.cloneElement(component, ...props)
)`...`;
```

**Comment by cklaymen** [comment]
> @kitten can you elaborate on or point me to some documentation explaining why dynamic render components are not recommended? Is it the same issue with using `styled` in `render`?

https://styled-components.com/docs/faqs#why-should-i-avoid-declaring-styled-components-in-the-render-method
