### ISSUE TITLE
Failed install v3.0.0

### ISSUE THREAD

**Issue by olegreznichenko** [styled-components/styled-components#1437]
## Version
styled-components: 3.0.0

OS Windows 10
node 9.4.0
npm 5.6.0

![image](https://user-images.githubusercontent.com/11960153/35225976-82cbddd0-ff92-11e7-8de7-fec602c53e7b.png)

**Comment by mxstbr** [comment]
Thanks for the heads up. @philpl wanna unpublish real quick?

**Comment by paulxtiseo** [comment]
FWIW, experiencing the exact same issue.

**Comment by philpl** [comment]
@mxstbr unpublished v3 & marked the tag as a prerelease. I'm not sure who added the postinstall because that's executed on all machines.

**Comment by paulxtiseo** [comment]
Any word on when v3 will be back online? I'm starting a new project and may as well wait for the full version change.

**Comment by mxstbr** [comment]
Should be back as `v3.0.1`! :blush:

**Comment by philpl** [comment]
@paulxtiseo v3.0.1 (patch release) should be up now with new release notes 👍 let me know if it works

**Comment by justinhp** [comment]
@philpl Installed successfully.  Works for me.  Thanks!

**Comment by paulxtiseo** [comment]
@philpl Worked for me too. That was quick! I was ready to wait a bit, but now I have no excuses. Back to the project. :) 

Thanks!
