### ISSUE TITLE
Publish a codemod to migrate away from the deprecated "styled-components/native" imports

### ISSUE THREAD

**Issue by kitten** [styled-components/styled-components#1441]
It'd be great to write a babel-codemod that quickly rewrites all imports and requires from `styled-components/native` to just `styled-components`;

Examples include:

```js
// in
import /* ... */ from 'styled-components/native';
require('styled-components/native');

// out
import /* ... */ from 'styled-components';
require('styled-components');
```

Starting point would be the babel-codemod repo: https://github.com/square/babel-codemod

Here's a good example of how to write a babel-codemod plugin: https://github.com/kentcdodds/babel-codemod-example

And finally this is how we target imports/requires in our babel plugin: 

- https://github.com/styled-components/babel-plugin-styled-components/blob/master/src/index.js#L12-L14
- https://github.com/styled-components/babel-plugin-styled-components/blob/master/src/visitors/assignStyledRequired.js#L4-L11

Hope this helps someone to get started with contributing to styled-components :heart:

The codemod should probably live in its own little repo that we can migrate to the styled-components org 💟

**Comment by RIP21** [comment]
Hey. I can write such but using JS-codeshift codemod, looks like not a big deal. Or, ofc I can try to dig into babel one, but never did that :)

**Comment by mxstbr** [comment]
A js-codeshift would be totally fine too imo!

**Comment by philpl** [comment]
@RIP21 sure like Max says that’s fine too as long as it works correctly :) since this is a first timer issue I’d just like to provide some helpful tips for someone to get started but it’s not a guideline at all

**Comment by RIP21** [comment]
@philpl @mxstbr So it's done.
https://github.com/RIP21/styled-components-native-to-plain-codemod
No magic with AST, the task is simple, don't want to overcomplicate, just some simple replaces.

**Comment by RIP21** [comment]
I may transfer repo so you reorganize it somehow if you like, to some `styled-components codemods` to collect them all. Cause it's not clear where should I commit that :)

**Comment by philpl** [comment]
@RIP21 I'll take a look later today :+1: Btw, can we warn and abort the codemod if we detect a TS project? This special new import switch doesn't work with TS yet (#1442)

**Comment by RIP21** [comment]
@philpl I wrote `ramda-codemod` with almost the same approach and it worked well for over 500+ files with no issues at all. I think it's quite safe to do it this way. This codemod is not a rocket science. So changing it to something more sophisticated is preliminary optimization and overengineering IMO. (I would personally just run search and replace against my project dir in IDE for such migration)

About TS, by default, `js-codeshift` is running against `.js` files. So `.ts` files will not be touched until user say so using extensions flag like: `--extensions ts,js,jsx,tsx`.

**Comment by bbuckland** [comment]
Is this still an issue? I have created a babel-codemod for this with the sole purpose of learning. Let me know if you'd like me to do anything with this. 

https://github.com/bbuckland/styled-components-native-codemod

**Comment by probablyup** [comment]
@bbuckland That's great! Want to add it to the RN section of the [website](https://github.com/styled-components/styled-components-website)?
