### ISSUE TITLE
TS2339: Property 'div' does not exist on type '(tag: any) => any'.

### ISSUE THREAD

**Issue by astyfx** [styled-components/styled-components#1444]
## Version
styled-components: 3.0.2
typescript: 2.6.2
ts-loader: 3.3.0

I am gradually changing the `JavaScript` based code to `TypeScript` based.

I refer to this [repository](https://github.com/Microsoft/TypeScript-React-Conversion-Guide).

using  both `babel-loader` and `ts-loader`
```
- webpack config
module.exports = config = {
  entry: ['babel-polyfill', './src/index'],
  module: {
    rules: [
      {
        test: /\.(t|j)s(x?)$/,
        exclude: /node_modules/,
        use: [
          {
            loader: 'babel-loader',
          },
          {
            loader: 'ts-loader',
          },
        ],
      },
      {
        enforce: 'pre',
        test: /\.js$/,
        loader: 'source-map-loader',
      },
    ],
  },
  plugins: [],
};
```

```ts
interface RootProps {
  className?: string;
  isFixed?: boolean;
  isOpen?: boolean;
}
```

- does not work
```tsx
const StyledRoot = styled.div`
  position: ${(props: RootProps) => (props.isFixed ? 'fixed' : 'static')};
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  z-index: 9999;
  ${(props: RootProps) => (props.isOpen ? '' : 'pointer-events: none')};
`;
```

- it worked
```tsx
const StyledRoot = styled('div')`
  position: ${(props: RootProps) => (props.isFixed ? 'fixed' : 'static')};
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  z-index: 9999;
  ${(props: RootProps) => (props.isOpen ? '' : 'pointer-events: none')};
`;
```

i assume also import seems to weired it says

`[ts] cannot find module 'styled-components';`

<a href="https://ibb.co/gzuGOb"><img src="https://preview.ibb.co/kifCww/Screen_Shot_2018_01_24_at_1_41_03_PM.png" alt="Screen_Shot_2018_01_24_at_1_41_03_PM" border="0"></a>

- tsconfig.json
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "es6",
    "allowJs": true,
    "jsx": "react",
    "sourceMap": true,
    "outDir": "./dist/",
    "strictNullChecks": true
  },
  "include": ["./src/"]
}
```

- ADDITIONAL QUESTION
when i do `import { StyledFunction } from 'styled-components';`

it has [tsl] error 
`TS2305: Module '".../node_modules/styled-components/dist/styled-components.es"' has no exported member 'StyledFunction'.`

i assuem `ts-loader` cause this error but i can't sure

**Comment by astyfx** [comment]
is it resolved with tsconfig.json `"module": "commonjs"`

**Comment by astyfx** [comment]
resolved with change module setting to "commonjs" in tsconfig.json

**Comment by lifeeric** [comment]
resolved by `yarn add @types/styled-components`

**Comment by JavierBeni** [comment]
for people with npm:
`npm i @types/styled-components`

**Comment by felix-horn** [comment]
Hi. I had `@types/styled-components` installed but for me a was a wrong `tsconfig.json` setup.. I had 

`"module": "NodeNext",
"moduleResolution": "NodeNext",` 

configured in my `compilerOptions`. Changing it to 

`  "module": "es2020",
    "moduleResolution": "node",`

But I don't know why that is. Could anyone explain?

THX!
