### ISSUE TITLE
Third Part Styled-Component Looses Style

### ISSUE THREAD

**Issue by guilhermegregio** [styled-components/styled-components#1447]
## Version
styled-components: 3.0.2

## Reproduction

Im trying to create a lib based on styled components. When I try to use the library everything works fine. But when I try to wrap some component with another styled component the stylesheet generated on the <head> tag gets overridden with the new stylesheet, what makes our component style loose its styles.

## Steps to reproduce
 - Create a basic component styled.
 - Export the component to other project as a depedency
 - Wrap the component with another styled component

## Expected Behavior
  - The component style keeps with its own styles and adds extra styles to its container

## Actual Behavior
  - The third part component looses its styles

**Comment by gribnoysup** [comment]
Hi @guilhermegregio! Are you bundling `styled-components` with your library? This may cause the issue you are encountering. Right now you can't have several instances of `styled-components` running on one page.

**Comment by wellyal** [comment]
I also have a similar issue.

**Comment by probablyup** [comment]
Any chance there are multiple versions of styled-components on the page? `npm ls styled-components` should reveal it if there are any instances that are not marked as "deduped".

The way to get around this is for the base library to declare `styled-components` as a peer dependency, and ideally set the allowed version as low as possible... perhaps ">= 2".

**Comment by filipposarzana** [comment]
As @gribnoysup said, I had the same issue and solved after finding out that I was using a library with different `styled-components` version :tada:
