### ISSUE TITLE
Uncaught Error: Cannot create styled-component for component: undefined

### ISSUE THREAD

**Issue by pak11273** [styled-components/styled-components#1449]
I'm getting this type of error with a very simple component:
```
Uncaught Error: Cannot create styled-component for component: undefined
    at constructWithOptions (styled-components.es.js:2109)
    at styled (styled-components.es.js:2044)
    at eval (index.js:43)
    at Object.<anonymous> (bundle.js:2569)
    at m (bundle.js:1)
    at t (bundle.js:1)
    at eval (index.js:48)
    at Object.<anonymous> (bundle.js:101)
    at m (bundle.js:1)
    at t (bundle.js:1)
```
This component produces the error:

```javascript
import {Container} from '../../components/index.js'

const ProfileContainer = styled(Container)`
  width: 100%; 
`
class Profile extends Component {
  render() {
    return (
      <ProfileContainer />
    )
  }
}

export default Profile
```
Here is the file that I export my components:

```javascript
import Container from '../components/Container'
import Box from '../components/Box'
import List from '../components/List'

export {
  Container,
  Box,
  List
}

```

Here is the imported Container component:

```javascript
import React, {Component} from 'react'
import styled from 'styled-components'

const Container = styled.div`
  display: ${props => props.display};
  grid-template-columns: ${props => props.gridtemplatecolumns};
  overflow-x: ${props => props.overflowx};
  overflow-y: ${props => props.overflowy};
`
export default Container
```
There is no issue if I import the Container component directly but I would rather keep using my export file so I can do things like this:

```javascript
import {Container, Box, List} from '../../components/index.js'
```

**Comment by philpl** [comment]
There's some pieces of the puzzle missing here I think;

> Uncaught Error: Cannot create styled-component for component: undefined

This signifies most likely that `Container` in `const ProfileContainer = styled(Container)` is undefined (try to debug it there; also, why try to debug it with the minified build?)

> There is no issue if I import the Container component directly but I would rather keep using my export file [...]

That's fair but there's something going wrong in that file then, I'd say if the reexporting file causes the later imported Container to eventually be undefined.

One weird thing I noticed is:

`import Container from '../components/Container'`
vs
`import {Container} from '../../components/index.js'`

is this just accidental?

Also, try to check for circular imports; sometimes they can cause this behaviour.

i.e. `components/A <=> components/index <=> components/B` would cause either A to be `undefined` in `B` or `B` to be `undefined` in A.

This can only be resolved by **not** going via the `index` (reexporting) file in those files that are being reexported

**Comment by pak11273** [comment]
`Container vs { Container }` is just importing from an export default vs a named export.  I have had no issues importing components this way.  I do this in React with most of my components:
```javascript
import React, { Component }  from 'react'
```
I just like the convention of importing components via destructuring rather than having a whole list of import statements.  It would be a real pain if I had to check all components for circular importing so I'm fine with just importing components directly if I have to style a styled component:
```javascript
eg. const newComponent = styled(anotherComponent)``
```
I just wish there was another way to do this.

**Comment by philpl** [comment]
There's a Webpack plugin which warns you about it: https://www.npmjs.com/package/circular-dependency-plugin

I don't think you'd have to check all even, but you can start one by one as you see these errors, since that's how you can confirm the theory

**Comment by pak11273** [comment]
I tried this plug-in and so basically you do not want to create an index file for your components if you want to use it.  I think the solution to this issue is to not create index files for components.

**Comment by philpl** [comment]
@pak11273 actually, as I mentioned in my comment before, you **can** create an index file. Just don't use it in other components that are **also in the index file**.

> i.e. components/A <=> components/index <=> components/B would cause either A to be undefined in B or B to be undefined in A.
>
> This can only be resolved by not going via the index (reexporting) file in those files that are being reexported

**Comment by abhishekchhugani** [comment]
Is this issue resolved I am facing the same issue

**Comment by VinceSJ** [comment]
I had the exact same issue and was able to get around it after I saw [this comment on another repo](https://github.com/diegohaz/arc/issues/130#issuecomment-282408542). Basically, the trick was this:
```
// fails
const ExtendedComponent = styled(OriginalComponent)`
  [Your awesome styles here]
`;

// works
const ExtendedComponent = styled(props => <OriginalComponent {...props} />)`
  [Your awesome styles here]
`;
```

I did not have to address any sort of circular import issue, although I should be encountering the exact same problem. I have a single central `index` file where I export `ComponentA` (which is styled). I then import that in another file (from the `index`), extend the styles as I talked about above to create `ComponentB`, which I use in making `ComponentC`, which then gets exported in the exact same `index` file.

No clue why this trick is working for me -- if somebody knows and could tell me, I'd love to learn, thanks.

**Comment by Stijnkool** [comment]
I got the `Cannot create styled-component for component: undefined` error because I was using [transform-es2015-modules-commonjs](https://babeljs.io/docs/en/babel-plugin-transform-es2015-modules-commonjs) as a fix for an [issue](https://github.com/facebook/jest/issues/2081) I had using jest.
Only using the transform-es2015-modules-commonjs plugin during testing, instead of always using it, fixed it.

It's probably not related though.

**Comment by mkascel** [comment]
@VinceSJ solution fixed this for me as well... my setup (which I imagine is pretty common) is that I have an index file for common components, which exports them all in this fashion, so I can do things like `import {X, Y, Z} from 'components/common'`:

index.js
```js
export { default as TwoColumn } from './Grid/TwoColumn';
export { default as Flex } from './Flex';
```

Can this module pattern not be used then in conjunction with styled-components?  It's a nice pattern so it would be good if this was resolved.

**Comment by vadikace** [comment]
Was this issue fixed in newer release of styled-components? I know that 3.4.2 release is already quite obsolete, but in that version it's still an issue.

**Comment by davilima6** [comment]
Still present in 4.2.0

**Comment by kitten** [comment]
To be clear, since it hasn't been clearly stated, this is not a bug in styled-components but a project/build level issue, hence not something we can fix 😀

**Comment by vadikace** [comment]
Thanks @kitten! It appeared to be indeed a project issue: forgot to set up mock for svgr components in jest environment, so styled-components was trying to wrap and style `undefined`.

**Comment by jescowuester** [comment]
I'm using [babel-plugin-transform-imports](https://www.npmjs.com/package/babel-plugin-transform-imports) with a configuration like this

```
 [
      "transform-imports",
      {
        "@components": {
          "transform": "@components/${member}",
          "preventFullImport": true
        }
      }
    ],
```

That way I can still import them via `import {Box, Text} from '@components'` without having to worry about circular dependencies.

**Comment by marrkeri** [comment]
I am facing with same error. I have 1 generic index.tsx where I do export of all my components.
But some components e.g. ChatRoom is using TextBox so when I had ChatRoom export before TextBox it fails.

// FAILS
export { default as ChatRoom } from './ChatRoom'
export { default as TextBox } from './Fields/TextBox'

// WORKS
export { default as TextBox } from './Fields/TextBox'
export { default as ChatRoom } from './ChatRoom'

I hope that this helps.

**Comment by DoctypeRosenthal** [comment]
@VinceSJ This also works for me. But according to the documentation from https://www.styled-components.com/docs/basics#extending-styles it should work without the extra arrow function. So this seems to be a bug in the package then.

**Comment by adam-hanna** [comment]
@VinceSJ thanks for the solution, it really helped me!

However, I was hit with the following error whenever I tried to forward a ref to `ExtendedComponent `: `Function components cannot be given refs.`

Here is my slight modification to your solution:

```
const ExtendedComponent = styled(
  forwardRef<
    HTML<Original Component Type, Here>Element,
    Props
  >(({ ...props }, ref) => (
    <OriginalComponent ref={ref} {...props} />
  ))
)`
  [your styles here]
`
```

**Comment by ducin** [comment]
@DoctypeRosenthal _probably_ it's not a problem with the package but with the application codebase itself.

The _solution_ by @VinceSJ does work and it helped us, but it's an overcome. Together with @agnieszkaac we've found out the problem were circular dependencies within our codebase formed by JS/TS `import` statements. Imports are processed synchronously and if there is a cycle, then JS might continue with a certain imported value being `undefined`

The solution that worked perfectly for us is:
- install `madge` npm package
- run as CLI tool with `--circular` flag (e.g. `madge src/index.tsx --warning --circular`)
- the tool sets non-zero exit code, co it works perfectly within CI/CD tools and `husky` (will break build/git hook if circular dependency found)
- graphviz and drawing diagrams is unnecessary
- supports TS and especially, the `baseUrl` compiler option which allows to replace relative import paths (e.g. `from ../../../components/x/y/z`) with absolute paths based on the directory (e.g. `from components/x/y`)

Often, using index files (`index.js` which includes `export * from './xyz'`) introduces circular dependencies. A quick fix in many cases is to replace `import A from './lib'` where `index.js` was re-exporting the contents with direct file `import A from './lib/a'.

Again, @VinceSJ quick fix helped us to carry on, but after we removed the root cause, the quick fix was not needed anymore :)

**Comment by nik72619c** [comment]
> Thanks @kitten! It appeared to be indeed a project issue: forgot to set up mock for svgr components in jest environment, so styled-components was trying to wrap and style `undefined`.

@vimkin could you elaborate on it a bit?

**Comment by willzfrank** [comment]
i am having the same issues here but am still lost on how to debug it can any one help out

×
Error: Cannot create styled-component for component: undefined.
▼ 24 stack frames were expanded.
j
C:/Users/Developer Room/Desktop/Okteller/src/utils/error.js:30
e
C:/Users/Developer Room/Desktop/Okteller/src/constructors/constructWithOptions.js:12
He
C:/Users/Developer Room/Desktop/Okteller/src/constructors/styled.js:8
Module.<anonymous>
C:/Users/Developer Room/Desktop/Okteller/okteller/src/components/Navbar/NavbarElements.js:31
Module../src/components/Navbar/NavbarElements.js
http://localhost:3000/static/js/main.chunk.js:452:30
__webpack_require__
C:/Users/Developer Room/Desktop/Okteller/okteller/webpack/bootstrap:851
fn
C:/Users/Developer Room/Desktop/Okteller/okteller/webpack/bootstrap:150
Module.<anonymous>
http://localhost:3000/static/js/main.chunk.js:467:73
Module../src/components/Navbar/index.js
http://localhost:3000/static/js/main.chunk.js:693:30
__webpack_require__
C:/Users/Developer Room/Desktop/Okteller/okteller/webpack/bootstrap:851
fn
C:/Users/Developer Room/Desktop/Okteller/okteller/webpack/bootstrap:150
Module.<anonymous>
http://localhost:3000/static/js/main.chunk.js:128:76
Module../src/App.js
http://localhost:3000/static/js/main.chunk.js:241:30
__webpack_require__
C:/Users/Developer Room/Desktop/Okteller/okteller/webpack/bootstrap:851
fn
C:/Users/Developer Room/Desktop/Okteller/okteller/webpack/bootstrap:150
Module.<anonymous>
http://localhost:3000/static/js/main.chunk.js:1123:62
Module../src/index.js
http://localhost:3000/static/js/main.chunk.js:1219:30
__webpack_require__
C:/Users/Developer Room/Desktop/Okteller/okteller/webpack/bootstrap:851
fn
C:/Users/Developer Room/Desktop/Okteller/okteller/webpack/bootstrap:150
1
http://localhost:3000/static/js/main.chunk.js:1233:18
__webpack_require__
C:/Users/Developer Room/Desktop/Okteller/okteller/webpack/bootstrap:851
checkDeferredModules
C:/Users/Developer Room/Desktop/Okteller/okteller/webpack/bootstrap:45
Array.webpackJsonpCallback [as push]
C:/Users/Developer Room/Desktop/Okteller/okteller/webpack/bootstrap:32
(anonymous function)
http://localhost:3000/static/js/main.chunk.js:1:69

**Comment by veharrison** [comment]
I was facing the same issue. I solved it by mocking the dependency that was causing this issue.

**Comment by ughitsaaron** [comment]
I just came across this issue while running tests with `jest` 26.6.3, `jest-styled-components` 7.0.4, and `styled-components` 5.2.1 on Node v12. I _know_ we have to upgrade our dependencies, but in case some other unfortunate soul happens across this bug on a similar setup, I resolved the error by updating the export of the original component from `const` to a named function, e.g.,

```diff
// original component
- export const OriginalComponent = ({ … }) => { … };
+ export function OriginalComponent({ … }) { … }
```

**Comment by oscdeveloper** [comment]
1) Install SVGR npm package.
2) Use this solution: https://react-svgr.com/docs/jest/

**Comment by jahirfiquitiva** [comment]
> I had the exact same issue and was able to get around it after I saw [this comment on another repo](https://github.com/diegohaz/arc/issues/130#issuecomment-282408542). Basically, the trick was this:
> 
> ```
> // fails
> const ExtendedComponent = styled(OriginalComponent)`
>   [Your awesome styles here]
> `;
> 
> // works
> const ExtendedComponent = styled(props => <OriginalComponent {...props} />)`
>   [Your awesome styles here]
> `;
> ```
> 
> I did not have to address any sort of circular import issue, although I should be encountering the exact same problem. I have a single central `index` file where I export `ComponentA` (which is styled). I then import that in another file (from the `index`), extend the styles as I talked about above to create `ComponentB`, which I use in making `ComponentC`, which then gets exported in the exact same `index` file.
> 
> No clue why this trick is working for me -- if somebody knows and could tell me, I'd love to learn, thanks.

How could one do this with TypeScript? I also have this issue

**Comment by bradley-varol** [comment]
I had this same issue as it was an import that was causing it.

`import x from '.'` <- '.' is the issue

**Comment by nriccar** [comment]
in my case was circular dependencies as well, I was trying to use a component from the same folder which has an index with a switch that contains both

**Comment by axipro1995** [comment]
> in my case was circular dependencies as well, I was trying to use a component from the same folder which has an index with a switch that contains both

Exactly source of my problem. Tks u so much

**Comment by lucasvieceli** [comment]
I solved the error by doing the following

`
export const Button = styled((props) => DefaultButton(props))`
`

**Comment by nishitha-cherunghatti** [comment]
i am facing same issue like Cannot create styled-component for component: undefined

import {BottomSheetBackdrop} from '@gorhom/bottom-sheet';
import {SharedValue} from 'react-native-reanimated';
import styled from 'styled-components/native';

export interface StyledBottomSheetBackDropProps {
  enableTouchThrough?: boolean;
  appearsOnIndex?: number;
  disappearsOnIndex?: number;
  animatedIndex: SharedValue<number>;
  animatedPosition: SharedValue<number>;
}

const StyledBottomSheetBackDrop = styled(BottomSheetBackdrop).attrs(
  ({
    enableTouchThrough = false,
    appearsOnIndex = 0,
    disappearsOnIndex = -1,
  }: StyledBottomSheetBackDropProps) => ({
    enableTouchThrough,
    appearsOnIndex,
    disappearsOnIndex,
  }),
)``;

export default StyledBottomSheetBackDrop;
