### ISSUE TITLE
fontWeight 400 does not work in React Native

### ISSUE THREAD

**Issue by jurmous** [styled-components/styled-components#145]
## Version

1.0.9
## Steps to reproduce

const Label = styled.Text`
  fontWeight: 400;
'
## Actual Behavior

```
Unhandled JS Exception: Invalid prop `fontWeight` of value `400` supplied to `StyleSheet generated`, expected one of ["normal","bold","100","200","300","400","500","600","700","800","900"].
StyleSheet generated: {
  "fontWeight": 400
}
```

With various versions of quotes it also fails:

```
Unhandled JS Exception: Invalid prop `fontWeight` of value `"400"` supplied to `StyleSheet generated`, expected one of ["normal","bold","100","200","300","400","500","600","700","800","900"].
StyleSheet generated: {
  "fontWeight": "\"400\""
}
```

**Comment by mxstbr** [comment]
Which version are you on? I think we fixed this recently can you try updating?

**Comment by jurmous** [comment]
1.0.9 as stated at top 😄

**Comment by mxstbr** [comment]
Sorry, that's what happened when I'm tired! @geelen you fixed that bug IIRC?

**Comment by geelen** [comment]
Yep I think you need to use `font-weight: 400` instead of the camel-case version. Though, we could probably try to match both here: https://github.com/styled-components/styled-components/blob/6d54e92055dc95fd174b90888e4a9db23a8971e8/src/models/InlineStyle.js#L14

**Comment by mxstbr** [comment]
Closing in favor of #210, which will fix this!
