### ISSUE TITLE
SC has Git Conflicted files *.orig on NPM

### ISSUE THREAD

**Issue by yordis** [styled-components/styled-components#1450]
I notice that I am downloading Git *.orig files for some reason from NPM

- src/models/ServerStylesheet.js.orig
- src/models/BrowserStylesheet.js.orig
- src/models/BrowserStylesheet.js.orig
- CHANGELOG.md.orig
- README.md.orig

**Comment by probablyup** [comment]
Interesting. Which version do you have downloaded?

```
npm ls styled-components
```

**Comment by yordis** [comment]
@probablyup `"styled-components": "^3.0.2"`

**Comment by probablyup** [comment]
Whatever it is seems to have started with v3.0.1. 2.4.0 doesn't have it. Very strange...

**Comment by philpl** [comment]
Hm seems that we should expand the gitignore; btw this sounds like you’ve landed on a prerelease for some reason

**Comment by probablyup** [comment]
Seems to be fixed in the last few releases
