### ISSUE TITLE
Switch to new context API

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components#1459]
React will soon introduce [a new API for context](https://github.com/reactjs/rfcs/pull/2). We should start using the latest version of [`react-broadcast`](https://github.com/ReactTraining/react-broadcast), which is a polyfill of that API. When we first built styled-components we inlined an implementation of `react-broadcast` to avoid introducing an unnecessary layer of components, so that needs to be removed too.

PRs very welcome! 💯 

/cc @gaearon

**Comment by k15a** [comment]
I've heard that the new context API is statically typable. How would this work for us?

**Comment by TrySound** [comment]
There's also ready to go polyfill [create-react-context](https://github.com/thejameskyle/create-react-context)

**Comment by yordis** [comment]
@mxstbr from https://github.com/styled-components/styled-components/issues/1459#issuecomment-361260412 are you use you want to jump to `react-broadcast` instead of use the polyfill?

**Comment by gaearon** [comment]
>We should start using the latest version of react-broadcast, which is a polyfill of that API.

FWIW I'm not confident that would work great because `react-broadcast` will be more heavyweight at runtime than the new context API, and in case of `styled-components` that overhead is shared by every component.

Maybe it would be better to cut a new major with 16.3+ compatibility.

**Comment by mxstbr** [comment]
That'd make sense to me, /cc @kitten @probablyup.

**Comment by probablyup** [comment]
Yeah let’s put it on the roadmap for 4.0, but we don’t need to release it
until React 17 rolls around.

Given that it’s new functionality, I’d prefer to let it be tested in the
wild for a bit before we migrate off something that works.

**Comment by mxstbr** [comment]
> but we don’t need to release it until React 17 rolls around.

The React team is introducing warnings that'll be thrown if the old context APIs used in 16.4 afaik, so we don't have time until React 17 😅

**Comment by Caryyon** [comment]
Where is this at?

**Comment by probablyup** [comment]
Not a priority at the moment

**Comment by charliewilco** [comment]
i can try and take this up!

**Comment by probablyup** [comment]
@charliewilco PRs welcome! Please coordinate with the other PR introducing React 16 lifecycles stuff. 

I’d like to use create-react-context for this so tearing it out later is super easy.

**Comment by halvves** [comment]
@probablyup - i've begun taking a look at this. which is the other PR i should coordinate with?

**Comment by halvves** [comment]
@probablyup @mxstbr - I'm thinking I may make a chore PR of just upgrading `flow-bin` and fixing all the flow errors/warnings involved as a preparatory step for this new context PR (which I made some decent headway on). The version of `flow-bin` currently being used doesn't know about `createRef` among other things. What are your thoughts?

**Comment by kitten** [comment]
@probablyup `create-react-context` is pretty popular now so the impact would indeed be minimal.

@halvves this would need to be coordinated a little with #1664, I suspect.

**Comment by charliewilco** [comment]
the one thing i kept wondering as i was looking into this was: what happens when `getChildContext()` goes away?

because you could make real heavy use of `withTheme()` and `<ThemeProvider />` but i couldn't figure out how to handle that without the HOC or wrapper of some kind.

**Comment by halvves** [comment]
@charliewilco - are you meaning like throughout the rest of the styled-components ecosystem/api? right now i've just been using the `<Consumer />` from the `createContext()` I did for theme inside all necessary components.

i think the trickiest issue right now is actually handling merging of themes with the new context api... the simplest way i could think of was something like this:

```
    <Consumer>
      {outerTheme => (
        <Provider value={mergeThemes(theme, outerTheme)}>
          {React.Children.only(children)}
        </Provider>
      )}
    </Consumer>
```

but this creates a new object every render.

**Comment by charliewilco** [comment]
@halvves this might be an implementation issue but this is the issue i had run into trying to port to the new context. https://codesandbox.io/s/rrn0ym8z64

**Comment by halvves** [comment]
@strt yep! awesome work! sorry i’ve been mia and never finished this one out 😔
