### ISSUE TITLE
How to Override Props Dependent Subcomponent styles?

### ISSUE THREAD

**Issue by jeff-lau** [styled-components/styled-components#1463]
Hi all,

I am building a reusable component which contains several styled components, with the aim of potentially allowing people to override specific styles in any of the parent or child components.

Let say for example it looks like this:

```
const Parent = styled.div`padding: 20px`

const ChildLabel = styled.label.attrs({className: 'child-label'})`
   color: ${props => props.hasError ? 'red' : 'blue'};	
`

const component = (props) => (
    <Parent className={props.className}>
        <ChildLabel>My Input</ChildLabel>
        <input type="text" />
   </Parent>
)

export default component
```

When I use it, I would like to override the label to green and blue (if error):
The following doesn't seem to work:

```
import component from '...'

const NewComp = styled(component)`
   ${ChildLabel} {
      color: ${props => props.hasError ? 'green' : 'blue'} 
   }
`
// Doesn't work.  Label stays blue which shows the override works, just not the props.
```

Logging the props passed shows that it has the props of the parent, which I guess makes sense, but the question is how do I override Props depending subcomponent styles?

Apologies for any typos/syntax errors in code, I just typed it up here.

**Comment by probablyup** [comment]
I think this needs to be inverted:

```js
const ChildLabel = styled.attrs({className: 'child-label'}).label`
  // stuff
`;

const ChildLabel = styled.label.attrs({className: 'child-label'})`
  // stuff
`;
```

**Comment by jeff-lau** [comment]
Thanks for replying @probablyup 

Yes, that was a syntax error in my question, I will update it.
Doesn't answer my question though.

**Comment by mxstbr** [comment]
Your example should work. Can you please provide a broken reproduction on Codesandbox? Then we can take a closer look.

**Comment by diondiondion** [comment]
Make sure you're actually passing the `hasError` prop to the relevant components. In your first example, the `ChildLabel` component would never receive a prop called `hasError` (or any props, really).

You didn't post an example of how you're using NewComp in JSX, but it might be the same issue there.

**Comment by jeff-lau** [comment]
That’s the problem.

The prop is internally passed inside the parent to the child. It’s not
something that i want to expose on the parent.

Is it possible to override a prop dependent property in a sub component via
the parent component?

I ll try and put something in a sandbox today.

Thanks

**Comment by jeff-lau** [comment]
Apologies for the delay, but here is a sandbox demonstrating the problem:

https://codesandbox.io/s/9882w08mqr

Gist of it is that I want to be able to override specifc sub components properties, and I can do that as long as the property is not dependent on any specific props.

**Comment by mxstbr** [comment]
First of all, you always want to define your styled components outside of the render method, otherwise they're re-created a thousand times over:

```JS
const OverridenComponent = styled(ReusableComp) `
  ${ChildLabel} {
    color: ${props => props.hasError ? 'black' : 'blue'}
  }
`

class App extends React.Component {
  render() {
    return (
      <div>
        Original button toggles between red and green.
        <ReusableComp />

        Overriden button suppose toggle between blue and black
        <OverridenComponent />

      </div>
    )
  }
}
```

Secondly, the `props` you're interpolating in the `styled(ReusableComp)` refer to the props that are passed to the resulting `OverridenComponent`, _not_ the props passed to the `ChildLabel`! That's why it doesn't work.

**Comment by jeff-lau** [comment]
@mxstbr 

Thanks for you reply.  

Yes I understand that isthe issue, my question was more towards how do I achieve the behavior that I wanted.

More specifically, overriding a specific prop adapting CSS property nested inside a component.
