### ISSUE TITLE
speedy injection bugs for styled(StyledComponent) in MS browsers

### ISSUE THREAD

**Issue by probablyup** [styled-components/styled-components#1464]
I don't have a repro just yet, but things are definitely injecting out of order in IE11. Looking at MDN, it seems that IE has a [spotty implementation of `insertRule`](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule) so we might just want to opt out of SPEEDY mode for the IE user agent.

**Comment by probablyup** [comment]
cc @philpl

**Comment by probablyup** [comment]
Spent some more time in BrowserStack and confirmed that all IE versions and all Edge versions have buggy behavior around the `insertRule` API. Firefox, Safari, and Chrome are all ok.

I recommend we do a quick UA test and disable speedy for MS browsers for the time being.

**Comment by evan-scott-zocdoc** [comment]
Mitigation: https://github.com/styled-components/styled-components/pull/1465

**Comment by probablyup** [comment]
Based on a [conversation with a PM over on Edge](https://twitter.com/probablyup/status/958138927981977600), the workaround for this issue is to prime the cloned stylesheet with a textNode before running `insertRule()` for the first time.

So theoretically in `replaceElement` we'd need to do this after clone:

```js
element.textContent = ' ';
```
