### ISSUE TITLE
FOUC for with-styled-component example

### ISSUE THREAD

**Issue by ichyr** [styled-components/styled-components#1472]
Here is repository with all information in readme: https://github.com/ichyr/next-js-sc-fouc

I'm basing my issue on #162. As I understand the issue is supposed to be gone after using example, but it's not for my minimal setting. Relative issue in *Next.js* is https://github.com/zeit/next.js/issues3108 but I can't see that the solution was provided. 

## Your Environment

| Tech    | Version |
|---------|---------|
|styled-components| 2.4.0|
|babel-plugin-styled-components| 1.5.0|
| next    |4.2.3|
| node    |8.9.3|
| OS      |MacOS High Sierra 10.13.3 (17D47)|
| browser |Chrome Version 63.0.3239.132 (Official Build) (64-bit)|
| etc     |         |

## Steps to reproduce
1. clone https://github.com/ichyr/next-js-sc-fouc
2. npm install
3. npm run dev
4. go to `localhost:3000` and observer the FOUC

## Expected Behavior
There is not FOUC. Server side rendering adds styles to `head` section.

## Actual Behavior
When using styled-components with next.js you get a FOUC (flash of unstyled content).

If you use react's built in styles then you do not get this issue.

You may see images from Google Chrome Dev tools Performance tab with preview of content in Readme of provided github repo (https://github.com/ichyr/next-js-sc-fouc)

## Investigation

1. `head` section of initial html of this example 

```
<head>
    <meta charSet="utf-8" class="next-head" />
    <link rel="preload" href="/_next/1517325460755/page/index.js" as="script" />
    <link rel="preload" href="/_next/1517325460755/page/_error.js" as="script" />
    <link rel="preload" href="/_next/1517325460755/manifest.js" as="script" />
    <link rel="preload" href="/_next/1517325460755/commons.js" as="script" />
    <link rel="preload" href="/_next/1517325460755/main.js" as="script" />
</head>
```

doesn't have any styles defined.

2. `getInitialProps` from `MyDocument` class of is not executed (see the `_document.jsx` lines 12 and after)

at least I can't see anything in my both consoles.

**Comment by lookapanda** [comment]
I'm not 100% sure, but I think next.js doesn't support `.jsx` file endings. Try renaming your `_document.jsx` to `_document.js`

For me, using next.js with styled-components is working fine.

**Comment by StevenLangbroek** [comment]
It's because your document has `.jsx` extension (just tested).

**Comment by ichyr** [comment]
works like charm. thank you!

**Comment by Yangeok** [comment]
Does the `.tsx` extension has anything to do with it?
