### ISSUE TITLE
Major compilation issues since 3.1.0.

### ISSUE THREAD

**Issue by piotrf** [styled-components/styled-components#1477]
## Version

styled-components: `3.1.0` and above

## Reproduction

Upgrade from `3.0.2` to `3.1.0` and above.

## Steps to reproduce

Upgrade styled-components from `3.0.2` to `3.1.0` or above.

## Expected Behavior

Page renders as usual.

## Actual Behavior

Feels like many styles are being discarded in the bundle. Likely something is causing CSS compilation errors—either there’s a bug in my styles that has been ignored by all the previous versions or a bug introduced in styled-components `3.1.0`.

Here’s a screenshot of the issue on my localhost. It’s a gatsbyjs site, so it’s enough to run `yarn` and `yarn run dev` to launch locally. Then update styled-components to `3.1.0` or newer and restart. The issue persists in the final `build` and not just dev environment.

Here’s the repo I’m using: https://github.com/piotrf/gatsby-test

<img width="787" alt="screen shot 2018-02-01 at 16 33 13" src="https://user-images.githubusercontent.com/377206/35686878-a6892588-076d-11e8-9ee5-9d9d480ff7a4.png">

**Comment by probablyup** [comment]
Can you respond to my ask in the other thread please?

**Comment by piotrf** [comment]
Tested against this issue with styled-components `3.1.0-speedy6`, as well—no luck.
