### ISSUE TITLE
Streaming styles breaking in production but working in development

### ISSUE THREAD

**Issue by oyeanuj** [styled-components/styled-components#1481]
## Version
styled-components: 3.1.5
babel-plugin-styled-components: 1.5.0

## Reproduction
It is hard for me to reproduce since the application isn't open-source yet. But I have created a diff of the rendered HTML code in development, and in production, and notice some strange looking differences which might indicate why the production page is breaking.

https://www.diffchecker.com/2lYyyofM

(if you want to use a diff tool of choice: https://gist.github.com/oyeanuj/1f07ff95409cb91ce9e702430b437c71)

## Expected Behavior
Styles, and the CSS classes would render the same in both production and development.

## Actual Behavior
Styles are broken in production, and some classes seem to be missing. Also, to note that in `3.1.5`, it works if I am not using streaming for styles.

**Comment by probablyup** [comment]
Could you try out `styled-components@stream` and let me know if it makes a difference for you?

**Comment by oyeanuj** [comment]
@probablyup this feels like a stupid question but I can't seem to find that release or branch?

**Comment by evan-scott-zocdoc** [comment]
I think it evaluates to `styled-components@3.1.6-0` - prerelease :)

**Comment by oyeanuj** [comment]
@evan-scott-zocdoc @probablyup (same person or coincidence of names?): it works now with `3.1.6.-0`. Do you know what might have been going on causing the issue with the previous release?

**Comment by evan-scott-zocdoc** [comment]
Same person, just my work account :)

There was an off-by-one issue that was causing some odd problems. We'll cut a formal release soon.

**Comment by oyeanuj** [comment]
@evan-scott-zocdoc actually, i spoke too soon. My enthusiasm got the better of me as I hadn't tested properly. I realized the reason it was working was because I had commented out `consolidateStreamedStyles` on the client file. Once, I uncomment it, then I get back to the same result that I was seeing earlier.

On the positive side, it seems to do with rehydration on the client?

**Comment by evan-scott-zocdoc** [comment]
This should fix it for you: https://github.com/styled-components/styled-components/pull/1482#issuecomment-362539714

Just make sure `consolidateStreamedStyles()` is called as early as possible in your bundle, ideally before any React components have been imported.

**Comment by oyeanuj** [comment]
@evan-scott-zocdoc Moving `consolidateStreamedStyles()` to the top of the page worked (I tested with 3.1.6-2). 

Do you consider this to be a temporary fix or is likely to be the only fix? I'd love to understand how this fixed the problem?

Appreciate all the help :)

**Comment by evan-scott-zocdoc** [comment]
It needs to be called before any styled component constructors are run or things break. Basically the style injection is run at `constructor()` time instead of `componentWillMount` which means runtime order is significant.

If a new rule is inserted before `consolidateStreamedStyles()` is called it causes a lot of problems because of "speedy" mode. In a nutshell, `insertRule()` does some weird stuff to the stylesheet and if you detach it from the DOM (even momentarily, like we do with consolidation), all rules added to it disappear.

We are looking at some future changes to loosen the restriction though!

**Comment by oyeanuj** [comment]
Good to know, thanks for the explanation!
