### ISSUE TITLE
Client-side style rule extraction

### ISSUE THREAD

**Issue by PlanetIrata** [styled-components/styled-components#1487]
With SC2.4.0, I was using a workaround to extract styles generated by SC on the client side (#893) using the exposed StyleSheet component (SSR API using ServerStyleSheet can't work client side due to BrowserTag). In V3 this component is not exported anymore (yes it is exported in test mode for jest-styled-components but it is not my use case). So I revert to V2 (#1483)

Extracting styles generated by SC on the client side could be useful in every app where the goal is to generate html & css on the client side (or any Electron app). In such case, SC is used to style the. Suppose that I want to create a single page app allowing visitors to generate CSS3 buttons. The page could be structured like this :

```html
<App>
  <ButtonSettings>
    Some UI components styled with SC to tweak my button
  </ButtonSettings>
	
  <ButtonPreview>
    This is a styled.button`...` component generated with SC
    from the settings made above in <ButtonSettings>
  </ButtonPreview>
	
  <ButtonHtmlCode>
    To extract the button HTML code and allow
    the visitor to copy it from here, I'll just use
    React's renderToStaticMarkup(<ButtonPreview .../>)
  </ButtonHtmlCode>

  <ButtonCssRules>
    Here, I need to display to the user the CSS
    generated by SC to render <ButtonPreview> 
    (and ONLY those styles, not the styles injected
    by SC for the other UI components !)
  </ButtonCssRules>
</App>
```

I can do that with SC 2 by using StyleSheet like described in #893, but I can't do it anymore with SC3.

This is a very basic use case, but in every App that build HTML & CSS where SC is used to style the App AND to style the exportable component(s) made by the app, a function like ```renderToStaticCss(<ComponentToExport.../>)``` similar to React would be great. And it should allow to only export the styles around the component received in argument, not the styles of the entire app.

Thanks for the great work on this lib !

**Comment by mCzolko** [comment]
@PlanetIrata Thank you for raising this. @mxstbr The app that I'm building is a WYSIWYG editor for emails. Client designs email by rich UI and hit download button - at that point I'm calling React's function to get static markup and also I need styles - I've used same hack as @PlanetIrata did. I'd like to have an API to extract styles if possible.

And I also have to thank you for the great work on styled-components, it makes my life a lot easier.

**Comment by kitten** [comment]
We actually don't technically want to expose our StyleSheet for these purposes, and I think it has been discussed before in various ways. One idea was to enable a component to output its rules so it can be recreated from them (like a `component => mixin` conversion); This obviously doesn't apply to your usecase.

Luckily you can still use the `StyleSheet` since we're now exposing it as a "secret internal";

https://github.com/styled-components/styled-components/blob/master/src/secretInternals.js

So you can import it using:

```js
import { __DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS as scSecrets } from 'styled-components'

// or

const scSecrets = require('styled-components'). __DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS

const { StyleSheet } = scSecrets
```

One thing to be aware of though is that our `insertRule` BrowserTag doesn't support the previous "raw" outputs anymore. I had some code for that, and it was simply removed to shrink the bundlesize a little, but we could readd it to enable these more complex usecases. It might even be interesting to build a package around them, since the secret internal is not going anywhere soon.

cc @mxstbr

**Comment by PlanetIrata** [comment]
Thanks @kitten but no, @mxstbr already point me to the spooky ghost workaround, but unfortunately it only works in test environment : https://github.com/styled-components/styled-components/issues/1483#issuecomment-362613961

**Comment by kitten** [comment]
@PlanetIrata Yes, we've just quickly discussed this; So making this work would involve two things:

- Exposing the secret internals in all environments
- Readding `toHTML` and `toRawCSS` to the `SpeedyBrowserTag`

This would likely enable your usecases

**Comment by PlanetIrata** [comment]
thx @kitten, here is the 3 lines css extraction code that work with SC 2.4 :
 
```
import ReactDOMServer from 'react-dom/server';
import styleSheet from 'styled-components/lib/models/StyleSheet';

styleSheet.reset(false);
ReactDOMServer.renderToStaticMarkup( <AWebPreviewComponent />);
console.log(styleSheet.instance.toHTML());
```

So exposing StyleSheet in all config could certainly help, and regarding the ```SpeedyBrowserTag```, if it can replace the ```styleSheet.instance.toHTML()``` then it should work !

Thanks !

**Comment by kitten** [comment]
The Stylesheet is now exposed in v3.2.0 via our secret internals export.

If any questions arise or if you’d like to request more methods please open new issues 😬

https://github.com/styled-components/styled-components/releases/tag/v3.2.0

**Comment by mikhailrojo** [comment]
So is it ```const {StyleSheet} = require('styled-components').__DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS;``` now the official and unique way for css extraction code on the server?

**Comment by kitten** [comment]
@mikhailrojo no, on the server it’s our SSR APIs. Also, the name here implies it’s not “official” or recommended in that sense

**Comment by pbogdan03** [comment]
@kitten, using the secrets in development is working fine since the style `data-styled-components` has all the styles, but production breaks with an error around not being able to use `cssText of undefined`. I think this is due to the empty style tag. Any thoughts on this?

**Comment by kitten** [comment]
@pbogdan03 oh, nice catch! Can you open an issue please? I wasn’t aware that style tags can have undefined cssText properties. It’d be interesting to track down when exactly this edge case occurs

**Comment by probablyup** [comment]
I thought we added an empty text node to style sheets to remedy this?

**Comment by kitten** [comment]
@probablyup it's just a bug in the css output function for speedy tags, I think. See https://github.com/styled-components/styled-components/issues/1660 (which you've already seen I guess 😆)
