### ISSUE TITLE
Empty theme object when upgrading to 3.x

### ISSUE THREAD

**Issue by tabrindle** [styled-components/styled-components#1492]
Re conversation on Twitter, and StackOverflow post:

https://stackoverflow.com/questions/48586409/styled-components-v3-has-empty-theme-object

After upgrading to styled-components@latest (3.1.0) upon starting the app, this error is thrown:

`Uncaught TypeError: Cannot read property 'margin' of undefined`

Upon inspection, it looks like the theme object is empty in a component defined like this:

```
export const Form = styled.form`
  ${({ theme }) => theme.layout.margin.all.small};
`;
```

Logging `theme` here returns `{}`, however at the `<ThemeProvider>` level in jsx, the theme logs as expected, complete with all the values. 

If I downgrade to 2.4.0, it works fine and as expected. 

## Version
styled-components: Upgrading from 1.4.6 => 3.x (2.4.0 works)

`npx envinfo --packages --markdown` (filtered a bit)

### System:
 * OS: macOS High Sierra 10.13
 * CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
 * Free Memory: 1.26 GB
 * Total Memory: 16.00 GB
 * Shell: /bin/bash - 3.2.57
### Binaries:
 * Node: 8.9.4
 * Yarn: 1.3.2
 * npm: 5.6.0
### Browsers:
 * Chrome: 63.0.3239.132
### Packages:
 * browserify: ^14.1.0 => 14.5.0
 * jest-styled-components: ^4.9.0 => 4.9.0
 * lerna: ^2.1.2 => 2.5.1
 * react: ^16.2.0 => 16.2.0
 * react-dom: ^16.2.0 => 16.2.0
 * styled-components: ^1.4.5 => 1.4.6  

## Reproduction

Still working on reproduction: this is in a huge mono repo which uses browserify. Will update this ticket

## Expected Behavior
Theme object is passed to styled components the same way throughout the entire tree

## Actual Behavior
Theme object is defined and full of theme properties at top of tree where ThemeProvider is defined, but is an empty object inside styled component definition.

**Comment by mxstbr** [comment]
Thanks for the detailed issue! I've marked this "needs more info" for now since it didn't happen for us when upgrading to v3, but this sounds to me like an actual bug somewhere in s-c. (we're using webpack fwiw)

**Comment by tabrindle** [comment]
So I'm starting to think this isn't really your fault at all - it seems like that though your upgrade path between major versions aren't breaking changes, there is something that stops styled-components from cooperating with other versions of itself when loaded in the same app. 

In this giant monorepo, I found no less than 4 different versions of styled-components anywhere from 1.4.5, to 2.2.1, to 2.4.0, to 3.1.6. Im guessing that something in 3.x changed so that multiple copies interfere with each other.

It's up to you if you want to investigate this further, but I personally think this is a footgun not worth going after. However, I do think a solution might be to add a note in your issue template to use `envinfo --packages --duplicates` for getting package versions and environment info (shameless plug). When I integrated envinfo into CRA, @gaearon thought of a nifty feature for me to add: finding duplicate packages with different versions. I'd be happy to make a PR for this. 

Ex: 

### System:
* OS: macOS High Sierra 10.13
* CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
* Free Memory: 1.21 GB
* Total Memory: 16.00 GB
* Shell: /bin/bash - 3.2.57
### Binaries:
* Node: 8.9.4
* Yarn: 1.3.2
* npm: 5.6.0
* Watchman: 4.9.0
* Docker: 17.12.0-ce, build c97c6d6
* Homebrew: 1.5.2
### IDEs:
* Android Studio: Not Found
* Atom: 1.23.3
* VSCode: 1.19.3
* Sublime Text: Build 3143
* Xcode: Xcode 9.0 Build version 9A235
### Languages:
* Bash: 4.4.12
* Go: 1.9.3
* PHP: 7.1.7
* Python: 2.7.10
* Ruby: 2.3.3p222
### Browsers:
* Chrome: 63.0.3239.132
* Chrome Canary: 66.0.3340.0
* Firefox: 58.0
* Firefox Developer Edition: 57.0
* Firefox Nightly: 58.0a1
* Safari: 11.0
* Safari Technology Preview: 11.1
### Packages:
* babel-plugin-styled-components: ^1.5.0 => 1.5.0 
* styled-components: ^3.1.6 => 3.1.6 (3.1.6, 2.4.0)

**Comment by kitten** [comment]
> it seems like that though your upgrade path between major versions aren't breaking changes, there is something that stops styled-components from cooperating with other versions of itself when loaded in the same app.

yep, this is currently unsupported unfortunately as it is not the recommended usage of the library 😞

**Comment by tabrindle** [comment]
Okey dokey then. Closing!

**Comment by kitten** [comment]
@tabrindle btw the issue in question is: https://github.com/styled-components/styled-components/issues/1032

Maybe we'll find a better way to resolve it
