### ISSUE TITLE
react-native exports not accessible since 3.1.6 in tests

### ISSUE THREAD

**Issue by SandroMachado** [styled-components/styled-components#1495]
## Version
styled-components: 3.1.6

## Reproduction

I have a project that has code to run under a React Web app and a React Native app.
After the upgrade to the version 3.X.X the native environment tests started to fail. I searched the issues list and I found the solution to fix the native testes in the issue #1451.

The problem is that using that workaround makes the native tests to pass and the web tests start failing as expected since we are pointing the `styled-components` library to the native dist.

``` 
"moduleNameMapper": {
      "styled-components": "<rootDir>/node_modules/styled-components/dist/styled-components.native.cjs.js"
    },
``` 

## Steps to reproduce

Create a project with WEB and Native code. Integrate `styled-components`. Make simple tests to run in both environments (WEB and Native).

## Expected Behavior

The tests should pass.

## Actual Behavior

I got the following message in the native tests:

```
Test suite failed to run:
TypeError: _styledComponents2.default.Text is not a function
TypeError: _styledComponents2.default.View is not a function
TypeError: _styledComponents2.default.Image is not a function
```

**Comment by kitten** [comment]
@mxstbr at some point I renamed the native file here https://github.com/styled-components/styled-components/blob/master/package.json#L9

I renamed it from `dist/styled-components.native.cjs.js` to `dist/styled-components.cjs.native.js` but it was renamed back by someone at some point? Assuming that Jest resolves `./dist/styled-components.browser.cjs.js` by default, if we rename this correctly wouldn't a `.native.js` be picked up?

If someone is running native tests in a separate setup, all they'd have to do is add the following to their native jest config:

```js
moduleFileExtensions: ["ios.js", "native.js", "js", "json", "jsx", "node"]
```

where the default is: `["js", "json", "jsx", "node"]`

**Comment by WaldoJeffers** [comment]
@SandroMachado I'm seing the same issue but not only in tests. All React Native components must be imported from `styled-components/native`, [contrary to what the docs say](https://www.styled-components.com/docs/basics#react-native). This is confusing.

**Comment by stowball** [comment]
I've just set up a new RN project with styled-components 3.4.2 and I get the same errors (not just in tests).

Using the code [from the docs](https://www.styled-components.com/docs/basics#react-native):

```
import React from "react";
import styled from "styled-components";

const StyledView = styled.View`
  background-color: papayawhip;
`;

const StyledText = styled.Text`
  color: palevioletred;
`;

class MyReactNativeComponent extends React.Component {
  render() {
    return (
      <StyledView>
        <StyledText>Hello World!</StyledText>
      </StyledView>
    );
  }
}
```

results in:

```
_styledComponents2.default.View is not a function
handleException @ ExceptionsManager.js:63
handleError @ InitializeCore.js:69
reportFatalError @ error-guard.js:42
guardedLoadModule @ require.js:143
_require @ require.js:132
(anonymous) @ App.js:30
executeApplicationScript @ RNDebuggerWorker.js:1
t @ RNDebuggerWorker.js:1
RCTLog.js:46 Module RCTImageLoader requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.
logToConsole @ RCTLog.js:46
logIfNoNativeHook @ RCTLog.js:29
__callFunction @ MessageQueue.js:351
(anonymous) @ MessageQueue.js:116
__guardSafe @ MessageQueue.js:314
callFunctionReturnFlushedQueue @ MessageQueue.js:115
t @ RNDebuggerWorker.js:1
```

If you log `styled`, it's an empty object…

**Comment by probablyup** [comment]
Did the metro bundler stop paying attention to the “native” package.json
field?

**Comment by stowball** [comment]
@probablyup OK this is weird. On a new RN 0.57 project, SC `3.4.9` now runs (see first screenshot), however if `4.0.0-beta.8` is installed via npm (yarn is fine) it now has a completely different error as soon as you `import styled from "styled-components";`.  Console output and simulator screenshot below:

```
(index):174 Console was cleared
ExceptionsManager.js:76 Cannot read property 'indexOf' of undefined
handleException @ ExceptionsManager.js:76
handleError @ InitializeCore.js:69
reportFatalError @ error-guard.js:42
guardedLoadModule @ require.js:181
metroRequire @ require.js:115
(anonymous) @ memoize-one.cjs.js:40
executeApplicationScript @ debuggerWorker.js:40
(anonymous) @ debuggerWorker.js:65
RCTLog.js:47 Running application styledComponents4 ({
    initialProps =     {
    };
    rootTag = 21;
})
ExceptionsManager.js:76 Module AppRegistry is not a registered callable module (calling runApplication)
handleException @ ExceptionsManager.js:76
handleError @ InitializeCore.js:69
reportFatalError @ error-guard.js:42
__guard @ MessageQueue.js:299
callFunctionReturnFlushedQueue @ MessageQueue.js:105
(anonymous) @ debuggerWorker.js:72
ExceptionsManager.js:84 Unhandled JS Exception: Cannot read property 'indexOf' of undefined
reactConsoleErrorHandler @ ExceptionsManager.js:84
logToConsole @ RCTLog.js:47
logIfNoNativeHook @ RCTLog.js:30
__callFunction @ MessageQueue.js:349
(anonymous) @ MessageQueue.js:106
__guard @ MessageQueue.js:297
callFunctionReturnFlushedQueue @ MessageQueue.js:105
(anonymous) @ debuggerWorker.js:72
ExceptionsManager.js:84 Unhandled JS Exception: Module AppRegistry is not a registered callable module (calling runApplication)
reactConsoleErrorHandler @ ExceptionsManager.js:84
logToConsole @ RCTLog.js:47
logIfNoNativeHook @ RCTLog.js:30
__callFunction @ MessageQueue.js:349
(anonymous) @ MessageQueue.js:106
__guard @ MessageQueue.js:297
callFunctionReturnFlushedQueue @ MessageQueue.js:105
(anonymous) @ debuggerWorker.js:72
```

![image](https://user-images.githubusercontent.com/853552/45917438-8f2bb180-beba-11e8-953d-0956cfff9c3e.png)

![image](https://user-images.githubusercontent.com/853552/45917454-ea5da400-beba-11e8-8aac-597e9720207b.png)

**Comment by probablyup** [comment]
@stowball appears to be a dup of #2044 

I have no idea what could be causing this issue though...

**Comment by dawidk92** [comment]
I have the same issue: `TypeError: styled_components_1.default.View is not a function`

I don't think that this issue is a duplication of #2044.
This issue seems to be connected with Web whereas #2044 with Native.

I work with `react-native-web` and I get this issue when I try to import `styled` from `styled-components` and use native components like: `const Test = styled.View` on Web.

Instead of it I have to import it from `styled-components/native`, but importing `styled` from `styled-components` on Native works fine.

I tested it with both versions `3.4.10` and `4.0.0-beta.11.3`

**Comment by probablyup** [comment]
Ok I think I'm starting to understand what's going on here. I think at one point the metro bundler supported a "react-native" package.json field that was part of what is now their "resolverMainFields" configuration. It appears that field is no longer honored by default and that's why an import to `styled-components` isn't working anymore.

**Comment by probablyup** [comment]
I'm updating the docs to account for this, sorry for the confusion: https://github.com/styled-components/styled-components-website/pull/359

There is a config you can add to your metro bundler config though that makes this work again called `resolverMainFields`: https://facebook.github.io/metro/docs/en/configuration.html#resolver-options

The config would probably look like this:

```json
{
  resolver: {
    resolverMainFields: ["react-native", "main"]
  }
}
```

**Comment by dawidk92** [comment]
Unfortunately it still doesn't work (I get the same error).

I added `metro.config.js` and configured it like this:
```js
module.exports = {
  resolver: {
    resolverMainFields: ["react-native", "main"]
  }
};
```

I also tried:
```js
module.exports = {
  resolver: {
    resolverMainFields: ["react-native-web", "main"]
  }
};
```

But none of these work.

Beside `react-native-web` I also use `TypeScript` in my project and I run my `web:dev` task like this: `react-scripts-ts start`. Maybe this is causing some problem somehow.

Versions of packages I use:
react: `16.4.0`
react-native: `0.55.4`
react-native-web: `0.8.9`
typescript: `^3.0.1`
react-scripts-ts: `^2.17.0`
styled-components: `3.4.9` (also tried `4.0.0`)

**Comment by dawidk92** [comment]
I think that this issue shouldn't be solved by Metro because it appears on the Web, not on Native app.
It appears only on Web when I'm trying to:
```js
@import styled from "styled-components"
```

And then get Native component from it:
```js
const TestCmp = styled.View`...`
```

**Comment by Ingibjorg** [comment]
@probablyup can you please provide further information in the docs on how we can use `resolverMainFields` to `import styled-components` instead of `import styled-components/native`.

Like @dawidk92, adding a metro config to my package.json did not allow me to `import styled-components`.

```
  "metro": {
      "resolver": {
        "resolverMainFields": ["react-native", "main"]
      }    
  },
```
