### ISSUE TITLE
production style inject throws error

### ISSUE THREAD

**Issue by tabrindle** [styled-components/styled-components#1497]
Currently running into an issue where the development build is fine on 3.1.6, but the production build throws the following error:

```
common.js:663 Error
    at sheetForTag (ap2.js:601)
    at t.inject (ap2.js:601)
    at e.inject (ap2.js:601)
    at r.generateAndInjectStyles (ap2.js:601)
    at r.t.generateAndInjectStyles (ap2.js:601)
    at ap2.js:601
    at n (ap2.js:601)
    at r.t.componentWillMount (ap2.js:601)
    at mountClassInstance (common.js:662)
    at beginWork (common.js:662)
```

Kind of amusing that in the original code: `This should never happen`😂

```
// Source: https://github.com/threepointone/glamor/blob/master/src/sheet.js#L32-L43
var sheetForTag = function sheetForTag(tag) {
  if (tag.sheet) {
    // $FlowFixMe
    return tag.sheet;
  }

  for (var i = 0; i < document.styleSheets.length; i += 1) {
    if (document.styleSheets[i].ownerNode === tag) {
      // $FlowFixMe
      return document.styleSheets[i];
    }
  }

  // NOTE: This should never happen
  throw new Error('');
};
```

## Version
`npx envinfo --packages --markdown` (filtered a bit)

### System:
 * OS: macOS High Sierra 10.13
### Binaries:
 * Node: 8.9.4
 * Yarn: 1.3.2
 * npm: 5.6.0
### Browsers:
 * Chrome: 63.0.3239.132
### Packages:
 * browserify: ^14.1.0 => 14.5.0
 * jest-styled-components: ^4.11.0-1 => 4.11.0-1 
 * styled-components: ^3.1.6 => 3.1.6 

## Reproduction
Working on it ¯\_(ツ)_/¯ 
## Steps to reproduce
Working on it ¯\_(ツ)_/¯ 
## Expected Behavior
No Error, rendered page
## Actual Behavior
Error, everything breaks

**Comment by kitten** [comment]
@tabrindle Very intriguing! This should indeed never happen as far as I could tell when I wrote this. I suspect that the input to this function is already borked when this fails.

A reproduction would certainly help 😞

**Comment by tabrindle** [comment]
As with my last issue, this is part of a super massive mono repo, paring it down is a chore. Will do my best. 

In the mean time, would screenshots of the debug from the breakpoints help?

**Comment by kitten** [comment]
@tabrindle yep! that would definitely help; the input to the function and the caller would certainly be helpful :+1:

**Comment by tabrindle** [comment]
1. It's entirely possible there is more than one instance. Part of my issue yesterday was that this project had 5 different versions bundled with it. 🤦‍♂️ 
2. Also possible there is manual style tag manipulation. Part of what I'm removing in favor of styled-components is a dynamic style sheets implementation 🤦‍♂️ 

This suggests that there is something going on with the length of StyleSheetList:
<img width="1222" alt="screen shot 2018-02-06 at 1 37 09 pm" src="https://user-images.githubusercontent.com/2925048/35877848-7ca65f58-0b44-11e8-98ee-5c0ea82f1e2f.png">

**Comment by tabrindle** [comment]
Fixed.

Once again, not really a styled-components bug, but a footgun that should perhaps at least be documented (I volunteer as tribute). Unlike in previous versions, it looks like you cannot have more than one copy of the code in your application, or this can happen. Seems like 2.4.0 and earlier are happy enough with multiple instances. 

Turns out that styled-components was included in both bundles that were loaded, and upon loading the second bundle something bad happened. I'm assuming styled-components does something on init that is incompatible with another instance? It would be great if there was a warning in the console about this like react with the same issue. Discussion [here](https://github.com/facebook/react/issues/2402).

Most interesting about this is that it works fine in dev, but prod it breaks because of the SPEEDY enhancements. Is there an blessed/easy way to enable/disable this?

Thank you so much for your help!

**Comment by tabrindle** [comment]
Well don't I feel silly now, you guys are already on it! The duplication warning got merged 6 hours ago :-)

https://github.com/styled-components/styled-components/pull/1412

So the only other outstanding issue might be how to enable speedy in dev.

**Comment by mxstbr** [comment]
> So the only other outstanding issue might be how to enable speedy in dev.

The issue is that styles injected in speedy mode unfortunately aren't editable in DevTools :cry: That makes it very unsuitable for dev, as much as we'd love to have that consistency

**Comment by kitten** [comment]
@mxstbr I think we could actually force-enable speedy in dev through the `StyleSheetManager`?

**Comment by mxstbr** [comment]
How so?

**Comment by kitten** [comment]
@mxstbr by adding a prop for it to make this behaviour configurable

**Comment by tabrindle** [comment]
I think that's a great idea actually.

**Comment by mxstbr** [comment]
Oh god so we're back at config eh? :wink: I like making the config component-based a lot more than making it `styled.config({ })` or something.

**Comment by kitten** [comment]
@mxstbr I feel like the `StyleSheetManager` would definitely be a nice solution! Unfortunately—as discussed in DMs—the manager's sheet/target is not working in all edge cases and scenarios yet 😢

**Comment by TeemuKoivisto** [comment]
Yea I had the same error, got me very confused. 
```
  // NOTE: This should never happen
  throw new Error('');
```
wasn't really helpful in finding out what the problem was. :grinning:

In the end it was simply because of double importing of styled-components but which was made less obvious with React working properly and styled-components too in dev-environment. Maybe add check for double importing? Or at least add `// have you accidentally double-imported your styled-components` before the `throw Error()`.

**Comment by kitten** [comment]
@TeemuKoivisto That's a good suggestion, I think I'll add some warnings in development. I don't really see any reason against it :)
