### ISSUE TITLE
Standard lib for styles in JS

### ISSUE THREAD

**Issue by ericclemmons** [styled-components/styled-components#150]
Hi!  I'm porting over "'widgets" on our websites from PHP/SASS to to React using `styled-components`.  In doing this, I've been looking for JS-friendly replacements for:
- [Bourbon](http://bourbon.io/) (e.g. mixins like Compass offers)
- [Neat](http://neat.bourbon.io/) (grid)

From my own research, I've found that:
- [`color`](https://github.com/qix-/color) works great for color manipulation.
- [`grid-styled`](https://github.com/jxnblk/grid-styled) is a fairly new answer for grids.
- ...not much else.

Personally, I've used both [Bootstrap](http://getbootstrap.com/) and [Bulma](http://bulma.io/) (my current favorite!) for styling React components.

But, what I suppose I was looking for were **recommendations on what libs in the ecosystem would work well with `styled-components`** to fill in the holes that CSS doesn't cover (but Bourbon & Compass do).  That is, until this project deems it appropriate to own that functionality...

**Comment by mxstbr** [comment]
I would love a "standard lib" for `styled-components`, kind of like Bourbon/Compass except in JavaScript. This would include things like `color`, but also "mixins" maybe?

If somebody wants to take that on I'll happily open a repo for it!

**Comment by bhough** [comment]
I definitely like this idea. I would be interested in helping take this on.

**Comment by mxstbr** [comment]
>  would be interested in helping take this on.

Awesome! Let's start by figuring out what some of the _very_ useful utils (like `color`) are that everybody would want? (by looking at compass, bourbon, etc.)

**Comment by bhough** [comment]
Great I will put a list of proposed utils and mixing in the next day or two and share it on this issue.

**Comment by ericclemmons** [comment]
A couple things I've already started doing:

- Choosing a white/black text color based on the contrast ratio (`color(...).light()`) of the background color.
- A custom `eh` function that's like `vh`, but for the container element:

  ```css
  font-size: ${eh(12.5)};
  margin: 0 ${eh(5});
  ```

  Of course, this is reliant on `this.props.size` coming from `react-sizeme`, but I found it neat & don't expect it here ;)

Looking forward to what @bhough comes up with.  I can already guarantee we'll need something like this internally or externally.

**Comment by ericclemmons** [comment]
Another thing that came up: being able to reset/normalize styles, which is something worth supporting by default when using things like `fieldset` especially (it has borders!):

- https://github.com/maximkoretskiy/postcss-initial
- https://github.com/maximkoretskiy/postcss-autoreset

**Comment by bhough** [comment]
Thanks @ericclemmons I will take a look at those. If I'm reading those docs correctly, these are for handling cases where you're dealing with global css and need to reset certain things to a configured default? I would be interested to hear @mxstbr and @geelen's take on this. It might be useful for those transitioning to styled-components, but overall wouldn't see much use in a project fully using styled-components, as there won't be much global styles (if any) to fight against.

It does bring to mind another potential enhancement that would cover this case. Since PostCSS is being used to process the outputted CSS anyway, the ability to configure the library to use other Post CSS plugins on the users side would be useful. That way you could cover these type of scenarios that people are bound to run into when transitioning, or even just give them more control over what processing happens to the CSS, without having to either make them dependencies or recreating the functionalities in the standard styles lib.

**Comment by mxstbr** [comment]
> the ability to configure the library to use other Post CSS plugins on the users side would be useful

Just a note here, we probably won't be reliant on PostCSS forever. It's very very big (~50% of our pkg size), so we're aiming to replace it with a more minimal parser eventually, which is why we don't expose anything to the users!

I'm more looking for helpers for e.g. colors here, auto-resets are still a bit wonky, especially in teams, in my experience.

**Comment by ericclemmons** [comment]
Last night I added additional tests to a "widget" where I kept randomly injecting other sites' `.css` files into the page to ensure that styles didn't affect the presentation.

I ended up putting `margin: 0; padding: 0; box-sizing: border-box; border: none;` and more on pretty much every component.

I mentioned the PostCSS plugins because I starred those _fully expecting to use them with `css-modules`_, but ended up using this instead.

I agree that we probably don't want to adopt PostCSS plugins & inherit that bulk.  If there's a way for _end-users_ to leverage existing ecosystems, by all means!

However, I think auto-prefixing, normalization, color, & layout helpers are table stakes for anything dealing with CSS nowadays.

(A gentle reminder that my team, as I assume many others, are slowly adopting React within existing projects and can't afford to completely redo all styling with `styled-components`, especially since we're unaware of an answer to what Bourbon/Neat/etc. offers.)

**Comment by bhough** [comment]
Here is an initial list that I think gets us to a good starting spot. I've filtered out any mixins that are purely for adding prefixes only. Also filtered out anything that is reliant on asset pipline functionality (like sprite generation) or helpers that are easily recreated in JS (that don't have some underlying formula) This includes things like guards, loops, etc. Open to discussion on any of these, or if there are suggestions for any that might be missing:

**Mixins**
- Clearfix
- Ellipsis
- Flexbox
- Font Face
- Hide Text
- HiDPI Media Query
- Keyframes
- Placeholder
- Radial Gradient
- Reset/Normalize
- Retina Image
- Selection
- Size
- Timing Functions
- Triangle
- Word Wrap

**Shorthand**
- Animation
- Background
- Background Image
- Borders
- Margin
- Inputs
- Padding
- Position
- Transition

**Utils**
- px to em
- px to rem
- golden ratio

**RGB**
- RGB
- RGBA
- red
- green
- blue
- mix

**HSL**
- hsl
- hsla
- hue
- saturation
- lightness
- adjust-hue
- lighten
- darken
- saturate
- desaturate
- grayscale
- complement
- invert

**Opacity**
- alpha
- rgba
- opacify
- transparentize

**Misc Color**
- shade
- tint

**Comment by mxstbr** [comment]
This looks great to me! Anything missing for you @ericclemmons?

**Comment by bhough** [comment]
Great! @mxstbr let me know when you have a chance to create a repo for it, or if you'd like me to go ahead and do it. I've started bootstrapping the project, getting build system and such in place. Should hopefully start work later on functionality later this week so we can start discussing the api and what not.

I'll also keep an eye on this issue for any additional discussion on features.

**Comment by mxstbr** [comment]
Ah sorry, I missed this comment, my bad! What should this be called? Any good ideas for names?

**Comment by bhough** [comment]
So far all I've come up with is something boring like `styled-library`, very open to suggestions on this one if we want something flashier.

**Comment by mxstbr** [comment]
Since this doesn't have to be something that is styled-components specific, I'd love to call it something more generic. I'd love for this library to become the de-facto standard for all CSS-in-JS methods!

What do you think about `cynosure`? It's kind of a synonym of "compass", see the [definition in MarriamWebster](http://www.merriam-webster.com/dictionary/cynosure):

> :  one that serves to direct or guide

It also was an open package name on npm, I've reserved it since I quite like the name! What do you think?

**Comment by kopax** [comment]
Has recommended by @mxstbr in [#1182](https://github.com/mxstbr/react-boilerplate/issues/1182) I would like to add these less function

- ceil : Rounds up to the next highest integer.
- floor : Rounds down to the next lowest integer.
- spin : Rotate the hue angle of a color in either direction.
- fadein : Decrease the transparency (or increase the opacity) of a color, making it more opaque.

**Comment by mxstbr** [comment]
> ceil : Rounds up to the next highest integer.
> floor : Rounds down to the next lowest integer.

These are already build into JavaScript, so we don't need to add them manually!

```
const Box = styled.div`
  border-radius: ${Math.ceil(someNumber)};
  border-radius: ${Math.floor(someNumber)};
`
```

> spin : Rotate the hue angle of a color in either direction.

I think that's what `adjust-hue` mentioned above does?

> fadein : Decrease the transparency (or increase the opacity) of a color, making it more opaque.

The `alpha` helper above covers that!

**Comment by kopax** [comment]
You are right, I was just completing the list, these could be used as aliases.

**Comment by bhough** [comment]
@mxstbr I like that name! I'm good with rolling with that.

> since this doesn't have to be something that is styled-components specific

All for this, just want to make sure we are all on the same page that cynosure will always assume that the user is using something else to handle prefixing.

**Comment by mxstbr** [comment]
> just want to make sure we are all on the same page that cynosure will always assume that the user is using something else to handle prefixing.

Yes. Good idea to point that out! I'll create the repo now!

**Comment by mxstbr** [comment]
Created the repo, feel free to push a first version up and I'll get cracking at helping you make it happen!

**Comment by mxstbr** [comment]
Closing this in favor of individual discussions over at https://github.com/styled-components/cynosure!

**Comment by ericclemmons** [comment]
Hah, I was going to recommend `polish` or `styled-polish` or `style-polish`, since the 💅 emoji is common :)

Anyway, the list is exhaustive and a huge step forward!  Great job!

**Comment by mxstbr** [comment]
Oh wow, `polish` is a great name!

**Comment by bhough** [comment]
Love `polish`!

**Comment by mxstbr** [comment]
Sadly taken in all variations 😢

**Comment by ericclemmons** [comment]
Dang, so is [polished](https://www.npmjs.com/package/polished)!

:trollface:

**Comment by santaclauze** [comment]
What is polished if not a "pearl"? :)
