### ISSUE TITLE
Typescript issue with return type of ThemedCssFunction

### ISSUE THREAD

**Issue by mbrowne** [styled-components/styled-components#1502]
## Version
styled-components: 3.1.6

## Reproduction
The issue occurs when using the `css()` helper and passing the return value into one of the `styled` component factory methods.

## Steps to reproduce
Try the following code in a TypeScript project:

    const contentWrapperStyles = css`
        margin: 30px;
    `
    
    const ContentWrapper = styled.div(contentWrapperStyles)

## Expected Behavior

It should compile without type errors

## Actual Behavior

    Argument of type 'InterpolationValue[]' is not assignable to parameter of type 'TemplateStringsArray'.
      Property 'raw' is missing in type 'InterpolationValue[]'.

## Possible Solution

I was able to get it working by modifying the return type for `ThemedCssFunction` in `stylde-components.d.ts`. I added this type:

    export type InterpolationTemplateStringsArray = InterpolationValue[] & TemplateStringsArray

And used it as follows:

    export interface ThemedCssFunction<T> {
      (strings: TemplateStringsArray, ...interpolations: SimpleInterpolation[]): InterpolationTemplateStringsArray;
      <P>(strings: TemplateStringsArray, ...interpolations: Interpolation<ThemedStyledProps<P, T>>[]): FlattenInterpolation<ThemedStyledProps<P, T>>[];
    }

(the original return type of the first function signature was `InterpolationValue[]`)

I don't know if this is a proper solution, but if so I'm happy to submit a PR.

## Workarounds

In the meantime, I found 2 workarounds:

1. `const ContentWrapper = styled.div`${contentWrapperStyles}`
2. `const ContentWrapper = styled.div(contentWrapper as InterpolationValue[] & TemplateStringsArray)`

I think it would be better to fix the issue at its source, but these workarounds aren't too bad (with the second one I'd create a reusable type alias)...

**Comment by kitten** [comment]
```
const contentWrapperStyles = css`
    margin: 30px;
`

const ContentWrapper = styled.div(contentWrapperStyles)
```

The ocde here is actually invalid and doesn't comply with our API. Our `css` mixin helper doesn't return `[string[], ...Interpolation]`, but `(Interpolation | string)]]` (these are of course not valid typings but just to make this a little clearer)

Instead you should **always** do this:

```
styled.div`
  ${contentWrapperStyles}
`
```

Hope this helps 👍

**Comment by mbrowne** [comment]
Oh ok, thanks. I assumed it was valid syntax because it worked fine in plain JS.

**Comment by kitten** [comment]
@mbrowne It'll probably work fine as long as you don't use interpolations; but that's more coincidental than not :wink:

Please refer to the docs if you haven't seen them yet, as they have more examples around usage 😀 https://www.styled-components.com/docs

**Comment by mbrowne** [comment]
FYI the reason I was trying to do it that way was because I was importing `contentWrapperStyles` from a separate file (because this is for my main App component and I don't want it to get too big). But this is fine:

    styled.div`
      ${contentWrapperStyles}
    `
