### ISSUE TITLE
Use theme for RTL

### ISSUE THREAD

**Issue by muneebkhan7737** [styled-components/styled-components#1504]
Hi, as styled components don't support RTL till now so could we create a separate theme for RTL?

**Comment by mxstbr** [comment]
Yes, of course, why not? If you like writing all your CSS in the theme 🤷‍♂️

**Comment by muneebkhan7737** [comment]
@mxstbr is there any example where I could get some idea?

**Comment by mxstbr** [comment]
I don't know! I'd ask [in the community](https://spectrum.chat/styled-components) how folks handle that right now.

**Comment by muneebkhan7737** [comment]
Thanks, I'll be waiting for your response.
