### ISSUE TITLE
The link to your contributors is broken on your README

### ISSUE THREAD

**Issue by Frazer** [styled-components/styled-components#1505]
On your readme, the image of all the contributors links to:
https://github.com/styled-components/styled-components/blob/master/graphs/contributors

which returns a 404

## Version
styled-components: 2.2.4
babel-plugin-styled-components: 1.3.0

## Reproduction

https://www.webpackbin.com/bins/-KeeZCr0xKfutOfOujxN
https://codesandbox.io/s/rkmNRByE4

**Comment by kitten** [comment]
Oh, good catch! It's a pretty new addition to our readme. Mind sending a quick PR please? :smile:

**Comment by chinesedfan** [comment]
I will take it. :)
