### ISSUE TITLE
Interpolating objects in React Native

### ISSUE THREAD

**Issue by jacobp100** [styled-components/styled-components#1509]
We had an [issue](https://github.com/styled-components/css-to-react-native/issues/68) in the `css-to-react-native` project. Somebody tried to do,

```js
export const AppName = Text.extend`
  ${{
    textShadowColor: 'black',
    textShadowOffset: { width: -4, height: 1 },
    textShadowRadius: 14,
  }}
`;
```

This doesn't work, (I assume) because the object will go through `css-to-react-native`. What is the expected behaviour here? Should we treat the style as complete, or process it? Or should we only process string values?

A note on if we only process string values: interpolating `{ margin: '10%', margin: 10 }` will use `margin: 10%`, because it gets expanded to `margin{Top,Right...}`, which have higher priority.

**Comment by kitten** [comment]
I’m pretty sure I’d suggest ppl to use “.attrs” in this case. If you use the style prop explicitly there’s nothing you lose and it’s pretty clear then that it bypasses our logic

**Comment by mxstbr** [comment]
People might use that to use `polished` in React Native, which always returns objects.

**Comment by kitten** [comment]
@jacobp100 since nested rules are not a thing in react native, would it make sense to alter the object stringification for it to pass css-to-react-Native some more useful info?

**Comment by jacobp100** [comment]
So convert objects to something that looks enough like CSS to parse?

**Comment by probablyup** [comment]
We support objects now

**Comment by amowu** [comment]
Hi @probablyup, I have upgraded styled-components^3.3.3, but I still can't use objects

```js
const StyledShadowView = styled(View)`
  ${{
    shadowColor: 'rgb(255, 0, 255)',
    shadowOffset: {
      height: 2,
    },
    shadowOpacity: 1.0,
    shadowRadius: 4,
  }}
`;
```

It got `Node of type rule not supported as an inline style` warn

**Comment by probablyup** [comment]
Yeah don’t use a template literal, just call styled(View)(yourStyleObject)

**Comment by amowu** [comment]
Hi @probablyup, I tried to change to this version, but the result is still the same `Node of type rule not supported as an inline style`, Is the **v3.3.3** version correct?

```js
const StyledShadowView = styled(View)({
  shadowColor: 'rgb(255, 0, 255)',
  shadowOffset: {
    height: 2,
  },
  shadowOpacity: 1.0,
  shadowRadius: 4,
})
```

**Comment by probablyup** [comment]
Hmm maybe just use the combined syntax?

boxShadow: “0 2 4px rgb(255, 0, 255)”

**Comment by tobiaseisenschenk** [comment]
This should really be documented more clearly as the official [RN docs suggest to use exactly this nested syntax](https://facebook.github.io/react-native/docs/shadow-props). Is it welcome for me to contribute a PR?

**Comment by jacobp100** [comment]
PRs always welcome. If you wanna see some test cases for parsing, you can look [here](https://github.com/styled-components/css-to-react-native/tree/master/src/__tests__). Feel free to ping me if you have any questions.

**Comment by anderzilla** [comment]
Only for knowledge inline needs ${ ..., ..., ... } syntax
