### ISSUE TITLE
Imported styles from component that uses the styles as well are not applied

### ISSUE THREAD

**Issue by hundsim** [styled-components/styled-components#1512]
## Version
styled-components: 3.1.6

## Steps to reproduce
https://stackblitz.com/edit/react-sx8q29

## Expected Behavior
Want both components to display the same inherited styles.

## Actual Behavior
Styling is only applied on the the component where the styles (`background`) are defined.

**Comment by mxstbr** [comment]
You're importing the component, not the fragment:

```diff
-import background from './Hello'
+import { background } from './Hello'
```

**Comment by hundsim** [comment]
OK sorry for that, that was unintentional. 

Correctly importing the fragment incur the same issue, here's an updated code sample

https://stackblitz.com/edit/react-mssand?file=World.js

**Comment by mxstbr** [comment]
That's probably because you have a cyclical dependency, which means webpack will resolve `background` to undefined. See https://github.com/webpack/webpack/issues/1788 for tips on how to resolve that.

**Comment by hundsim** [comment]
Alright thanks, I see. 

I assume detecting circular dependency isn't a `styled-component` concern, but it had been so useful if an error was thrown. 

When styles are reaching target component, but not getting applied and no errors - it's easy (for beginners like me) to hunt bugs for a handful of hours in vain 😳

**Comment by mxstbr** [comment]
Hehe sorry about that—circular dependencies are unfortunately a bit of a pain with webpack right now!
