### ISSUE TITLE
Can't load webfonts with injectGlobal in create-react-app

### ISSUE THREAD

**Issue by ArtanisAce** [styled-components/styled-components#1513]
Hi,

first of all, apologies is this is not the place to put this. It might be a create-react-app issue, but I just wanted to get more info on how this works, or maybe somebody has an idea why this is not working...

So I'm developing a simple app with create-react-app and styled-components. I wanna load a webfont I downloaded previously, and the webfont files lie on my './src/fonts' folder. So to inject them into the app, I thought of injectGlobal, which works nice for this kind of stuff (already 'injecting' some body rules).  So in my main component, App.js, I have the following code:

```
injectGlobal`
   @font-face {
    font-family: 'Raleway Thin';
    src: url('./fonts/raleway_thin-webfont.eot');
    src: url('./fonts/raleway_thin-webfont.eot?#iefix') format('embedded-opentype'),
         url('./fonts/raleway_thin-webfont.woff') format('woff'),
         url('./fonts/raleway_thin-webfont.ttf') format('truetype'),
         url('./fonts/raleway_thin-webfont.svg#Raleway-Thin') format('svg');
    font-weight: normal;
    font-style: normal;
  } 
  /* Apply a natural box layout model to all elements, but allowing components to change */
  html {
    box-sizing: border-box;
  }
  *, *:before, *:after {
    box-sizing: inherit;
  }

  body {
    margin: 0;
    padding: 0;
    font-family: 'Sanchez', Arial, serif;
  }
`;
```

Box-sizing and body rules are applied correctly, but somehow the font is not loaded. I get an error -

> > Failed to decode downloaded font: http://localhost:3000/public/fonts/raleway_thin-webfont.woff

I have also tried to put the fonts in /public folder, but no success. It works when I put the @font-face declaration in a css, and import it in index.js for example. 

Does anybody has any idea why this might happen? Thanks a lot! :)

**Comment by kitten** [comment]
@ArtanisAce Since you're just specifying paths, for instance `'./fonts/raleway_thin-webfont.eot'`, which are just strings, those fonts won't magically appear in your `public` folder.

I'd suggest you to just move your `fonts` folder to `./public/` and to change your fonts paths to be absolute, i.e. `/fonts/...`.

**Comment by ArtanisAce** [comment]
That worked! Thanks a lot @kitten ! :D I was just thinking I have to specify the path relative to the component where the injection happens... but I get this approach

**Comment by DieLaughing** [comment]
Could someone, anyone, maybe post an example I could 'git clone' showing how this works? Because me and the best minds in the world are a little bit stumped. Thanks.

**Comment by ArtanisAce** [comment]
Hey @DieLaughing , here's what I did:

```
injectGlobal`

  @font-face {
    font-family: 'Raleway Thin';
    src: url('/fonts/raleway_thin-webfont.eot');
    src: url('/fonts/raleway_thin-webfont.eot?#iefix') format('embedded-opentype'),
         url('/fonts/raleway_thin-webfont.woff') format('woff'),
         url('/fonts/raleway_thin-webfont.ttf') format('truetype'),
         url('/fonts/raleway_thin-webfont.svg#Raleway-Thin') format('svg');
    font-weight: normal;
    font-style: normal;
  }
`
```

and my /fonts folder lives on the /public folder. Hope will be useful :)

**Comment by DieLaughing** [comment]
Thank you so much!

**Comment by Richacinas** [comment]
What about v4 with the new createGlobalStyles function? You get a styled component that are supposed to deliver with your component repository and instantiate at a high level in the same app that is consuming the components. That url wouldn't work in that case so... how would you solve this problem when you use your bundled library from another app?

**Comment by Caillou09** [comment]
That worked @kitten ! I have been looking for a solution since 10:00am (it is now noon)
