### ISSUE TITLE
Add support for new padding and margin property in React Native 0.51+

### ISSUE THREAD

**Issue by mojtabast** [styled-components/styled-components#1515]
As you can see in [this release note](https://github.com/facebook/react-native/releases/tag/v0.51.0), React Native now supports for `padding` and `margin`. It seems Styled Components still doesn't support it.
 
## Version
styled-components: 3.1.6

## Reproduction
``const RoundButton = styled.View`
    borderRadius: 8;
    background: ${ props => props.background || 'black' };
    padding: 5;
`;``

## Expected Behavior
It should works as you can see it in [React Native's documentation](https://facebook.github.io/react-native/docs/layout-props.html#padding)

## Actual Behavior
<img width="341" alt="screen shot 1396-11-23 at 01 54 24" src="https://user-images.githubusercontent.com/3523430/36079422-e525c44a-0f97-11e8-8e7e-1c9d52c61516.png">

**Comment by kitten** [comment]
This has been supported for a while by css-to-react-native, which is a sub-library to convert more web-like css rules to React Native compliant CSS.

`padding: 5` however needs a unit to be parsed correctly, meaning `padding: 5px;` will work just fine. This is to differentiate it with the ambiguous `padding: 5%`, which we've introduced to do some conversions more easily.

If we indeed don't need to convert this to `padding{Top,Right,Bottom,Left}` anymore, we still can't quite remove it, so that we support older versions of React Native.

cc @jacobp100

**Comment by jacobp100** [comment]
There was always support for `padding` on its own, we expand it to match css behaviour. I think this is more about paddingStart/paddingEnd, which change with writing direction

We do, however, need to look at multiple border colours and styles now being supported

**Comment by mojtabast** [comment]
I tested this: `padding: 5px` and it works. IMO it's better to support unitless values for shorthand CSS too, because React Native is basically unitless. It makes users confuse.

**Comment by kitten** [comment]
@mojtabast What's better is of course always subjective and relative, and you do have an argument.

But we have discussed this at length, and apart from the strongest argument—imho—is that we're trying to make things *more* similar to the web (like when we're emulating how `flex` works on the web). And then come the technical reasons of why this makes `css-to-react-native`'s job easier.

**Comment by marcus-franzen** [comment]
I have also stumbled over this topic.

So basically 
   margin: 6; 
cannot been parsed, but needs to be
   margin: 6px;

But  margin-top: 6; just works fine. I think it would be better to have some consistence here.

**Comment by jacobp100** [comment]
That's more of an implementation detail in `css-to-react-native`. We're going to try and get some dev warnings for these cases

**Comment by stvmachine** [comment]
+1
