### ISSUE TITLE
Invalid classNames in current master branch (bcd2120)

### ISSUE THREAD

**Issue by gribnoysup** [styled-components/styled-components#1521]
## Version
styled-components: master (bcd2120)
babel-plugin-styled-components: 1.3.0

## Reproduction

Just run sandbox in current master branch

## Steps to reproduce

1) Checkout to current master branch
2) Follow instructions in the `CONTRIBUTING.md` to bootstrap sandbox
> Ignore react-live warnings, `Button.example` is a little bit broken right now, but this doesn't make a difference for the end result
3) Inspect `Header`, `Title`, `Subtitle` on the page. `className` generated by `styled-components` is an invalid character - number:

![image](https://user-images.githubusercontent.com/5036933/36214569-15b5d51e-11aa-11e8-844c-b3ede3aa0684.png)

4) Inspect `Code` and `Button` component. They have the same `className` (this may be react-live issue, but I'm not sure)

![image](https://user-images.githubusercontent.com/5036933/36215015-2c15a0f4-11ab-11e8-81fe-4ca1346449e5.png)

To confirm that this wasn't an issue before, you can check out to `3.1.4` tag and run sandbox again

## Expected Behavior

Generated `classNames` should be valid CSS class names and not repeating themselves

## Actual Behavior

See n.3 and n.4 above

I think that this could be somehow connected to https://github.com/styled-components/styled-components/pull/1516 but I don't have enough knowledge about hashing algorithms to confirm this 😅 

/cc @kitten

**Comment by probablyup** [comment]
You need to update your version of the babel plugin.

**Comment by kitten** [comment]
@probablyup Actually that's not quite right

The bug was introduced lately and will be fixed by #1514

**Comment by gribnoysup** [comment]
@kitten thanks for a quick update! I don't mind if you close the issue if you want because it is not in the latest stable release 😸

**Comment by kitten** [comment]
@gribnoysup I'd just like to keep this issue up top for anyone who's looking to build `master` right now :wink:
