### ISSUE TITLE
Using Tagged template literals for media queries but with breakpoints from theme

### ISSUE THREAD

**Issue by arovillard** [styled-components/styled-components#1525]
I'm trying to figure out the best way to do this, but using the breakpoints I define on my theme through the theme provider.  How do I expose the theme to something that is not a component?
```
// these sizes are arbitrary and you can set them to whatever you wish
import { css } from 'styled-components'

const sizes = {
  giant: 1170,
  desktop: 992,
  tablet: 768,
  phone: 376
}

// iterate through the sizes and create a media template
export const media = Object.keys(sizes).reduce((accumulator, label) => {
  // use em in breakpoints to work properly cross-browser and support users
  // changing their browsers font-size: https://zellwk.com/blog/media-query-units/
  const emSize = sizes[label] / 16
  accumulator[label] = (...args) => css`
    @media (max-width: ${emSize}em) {
      ${css(...args)}
    }
  `
  return accumulator
}, {})
```

**Comment by mxstbr** [comment]
Import it maybe? Not sure what the question here is

```
import theme from '../theme'
```

**Comment by arovillard** [comment]
I'm writing an npm package that gives me 2 things, a Grid and a template for media queries. It has default breakpoints, but I want the user to be able to define their own breakpoints. The best approach I could think was using the <ThemeProvider> and have them define their breakpoint there, but I don't know how to get the theme (and the breakpoints) from a non Component.

So my question is, how do you get that theme object into a something like this:
```
export const media = Object.keys(sizes).reduce((accumulator, label) => {
  // use em in breakpoints to work properly cross-browser and support users
  // changing their browsers font-size: https://zellwk.com/blog/media-query-units/
  const emSize = sizes[label] / 16
  accumulator[label] = (...args) => css`
    @media (max-width: ${emSize}em) {
      ${css(...args)}
    }
  `
  return accumulator
}, {})
```
I hope the question is more clear now, otherwise I can try to go into mode details.

**Comment by mxstbr** [comment]
You can only do it from components, because the dynamic theme is passed down via the component tree. Anything outside of components won't work!

Why don't you go with an API similar to this?

```JS
export const media = (sizes) => Object.keys(sizes).reduce(/* ... */);


// Usage:

const myMediaQueries = media({
  small: 102,
  medium: 300,
  large: 400,
  xlarge: 1500
})
```

**Comment by kitten** [comment]
I second @mxstbr here. You could let the user add:

```js
<ThemeProvider theme={{
  ...bla,
  media: media({ ...breakpoints /* as shown by Max */ })
>
```

And then `media` can expose itself on the theme:

```
styled.div`
  ${p => p.media.large`
    ...
  `}
`
```

**Comment by arovillard** [comment]
I'm just not a fan of that api, it would have been great to keep the original api
```
styled.div`
    ${media.large`
        ....
    `}
`
```
But ultimately @kitten 's solution is better than nothing.

This is the package I made, https://www.npmjs.com/package/styled-grid-responsive

I'll update it so the user can use `mediaQuery` when they define their `media` in the theme

Thanks for the info!

**Comment by kitten** [comment]
@arovillard that API is possible too :wink: It just depends on your object having a consistent structure.

Say you enforce:

```js
const mediaProperties = mediaProperties({
  small: 102,
  medium: 300,
  large: 400,
  xlarge: 1500
})

<ThemeProvider theme={{
  ...theme,
  mediaProperties
>
```

To have certain properties only and create a "meta object" with some configs. Then this could work:

```js
styled.div`
 ${media.large`
  ....
 `}
`
```

Where `media.large` does something like:

```js
media.large = (strings, ...interpolations) => p =>
  css`
    @media (max-width: ${emSize(p.theme.mediaProperties)}em) {
      ${css(...args)}
    }
  `
```

For making this work you can either restrict the number of settings and properties, or you can use proxies, which isn't quite a good idea yet though

**Comment by arovillard** [comment]
I know this is closed and nobody will ever find this, but I took the advice and made mediaQuery into a function. This solves the problem and I get to do the api like I wanted.
I updated the readme with implementation.
@kitten @mxstbr  thank you very much for your help!
https://www.npmjs.com/package/styled-grid-responsive
