### ISSUE TITLE
Localization/Filipino translation

### ISSUE THREAD

**Issue by jcpuzs1** [styled-components/styled-components#1526]
Sir, I would like to contribute in translation, localizing to Filipino.

**Comment by kitten** [comment]
You probably meant to post this on our website repository :wink:

Unfortunately we haven't set up the proper tooling and structure for translations yet, but we will let everyone know once that's ready. It's not a high priority for us right now, as we've been working a lot on the library itself and don't have anyone yet who is championing this task again.

https://github.com/styled-components/styled-components-website/issues/86
