### ISSUE TITLE
Styled-components doesn't work properly with functional components + TS

### ISSUE THREAD

**Issue by zaclummys** [styled-components/styled-components#1527]
## Version
styled-components: 3.1.6
VSCode: 1.20.1
typescript: 2.8

## Reproduction
https://codesandbox.io/s/y042x24wlz

## Expected Behavior
Functional components should be working with styled-components.

## Actual Behavior
Typescript says:

`<TextWithProps />`: _JSX element type 'StyledComponentClass<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, any, Deta...' is not a constructor function for JSX elements.
  Property 'render' is missing in type 'StyledComponentClass<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, any, Deta...'._

**Comment by kitten** [comment]
In your reproduction you're returning `TextStyled` (A component class) from `TextWithProps`. Instead you should return `<TextStyled />` if that is your plan? Otherwise you're not rendering an element :wink:

**Comment by zaclummys** [comment]
I'll use your recommendations.Thank you for caring to answer.
