### ISSUE TITLE
sheet.collectStyles makes my SSR crash

### ISSUE THREAD

**Issue by cesarenaldi** [styled-components/styled-components#1534]
## Version
styled-components: 2.4.0
babel-plugin-styled-components: 1.5.0

## Reproduction

I have a project which makes use of SSR. I'm in the process of splitting it into a common part and more app specific ones. I'm using "yarn workspaces" to handled the dependencies.

All dependency are pulled into the root folder of my project.

The SSR started to produce this error:
```
TypeError: css.replace is not a function
   at ServerTag.inject (....../apps/node_modules/styled-components/lib/models/ServerStyleSheet.js:69:21)
   at StyleSheet.inject (....../apps/node_modules/styled-components/lib/models/StyleSheet.js:126:9)
   at ComponentStyle.generateAndInjectStyles (....../apps/node_modules/grid-styled/node_modules/styled-components/dist/styled-components.cjs.js:1836:18)
   at StyledComponent.generateAndInjectStyles (....../apps/node_modules/grid-styled/node_modules/styled-components/dist/styled-components.cjs.js:1492:40)
```

I excluded any of my components by rendering a simple `<h1>` in my top level `App.jsx` component.

I narrowed it down to the use of `sheer.collectStyles` function.

The renderer which fails looks like this:
```
export default function (element) {
  const sheet = new ServerStyleSheet();
  const html = renderToString(sheet.collectStyles(element));

  return { sheet, html };
}
```

If I get rid of `sheet.collectStyles` the error goes away and the Server Side renders the style correclty. But *I'm still uncomfortable to do something as not specified in the Styled Component spec*.

I'm running out of ideas. Nothing else in my project is changes, just moved some files around.

https://www.webpackbin.com/bins/-KeeZCr0xKfutOfOujxN
https://codesandbox.io/s/rkmNRByE4

## Steps to reproduce

See reproduction section.

## Expected Behavior

SSR should work using Styled Components APIs as per spec.

## Actual Behavior

See error in reproduction section.

**Comment by kitten** [comment]
This actually sounds like a usage problem.

Can you post some of your code or optimally a reproduction please?

**Comment by cesarenaldi** [comment]
Turns out that during the changes I got a slightly newer version of `grid-styled` (from `2.0.0-11` to `2.0.0-12`) which now has dependency on `style-components` 3.x.

The issue was likely caused by having 2 different copies of style component for my code and `grid-style`.

Closing the issue.

Thanks for looking into this.
