### ISSUE TITLE
styled.video does not respect controlsList

### ISSUE THREAD

**Issue by marhalpert** [styled-components/styled-components#1535]
## Version
styled-components: 2.2.4
babel-plugin-styled-components: 3.1.6

## Steps to reproduce

```js
const Root = styled.video`
  width: 100%;
`

<Root
    controls
    controlsList="nodownload">
        <source src="some/location/video.webm" type="video/webm"/>
</Root>

```

## Expected Behavior
Here us the speck of the expexted behavior: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/controlsList

<img width="603" alt="screen shot 2018-02-21 at 12 06 04 am" src="https://user-images.githubusercontent.com/745640/36425478-18a1e362-169b-11e8-90ca-22e582c23033.png">

## Actual Behavior
![ddd](https://user-images.githubusercontent.com/745640/36425706-aa6d1924-169b-11e8-8507-765f8622ad6e.jpg)

## Workaround
```js
const Root = styled.video.attrs({
  controlsList: 'nodownload'
})`
  width: 100%;
`

<Root
    controls>
        <source src="some/location/video.webm" type="video/webm"/>
</Root>
```

**Comment by mxstbr** [comment]
Good catch, support for this was only [recently merged](https://stackoverflow.com/a/44614700). We should update our `validAttrs.js` file, PRs welcome!
