### ISSUE TITLE
Passing props doesn't work with :after and :before

### ISSUE THREAD

**Issue by borovik96** [styled-components/styled-components#1536]
## Version
styled-components: 3.1.6

## Reproduction
https://codesandbox.io/s/jp17xk248w

## Expected Behavior
Passing props works well with `:after`, `:before`
## Actual Behavior
Passing props doesn't work with `:after`, `:before`

**Comment by mxstbr** [comment]
If you look in the DevTools you'll see that you're outputting invalid CSS:

![screen shot 2018-02-20 at 14 39 51](https://user-images.githubusercontent.com/7525670/36426932-fba9f4b0-164b-11e8-9984-47e93b91a3db.png)

You're missing a set of quotes around the `test`. 

```diff
-    content: ${() => "test"};
+    content: ${() => '"test"'};
```

That single change makes it work: https://codesandbox.io/s/23mrnp9p30

----

Next time you have a usage question please either ask it on StackOverflow or [in the community](https://spectrum.chat/styled-components). Thanks.
