### ISSUE TITLE
Styles are not generated using themeProvider in production mode V2.4.0

### ISSUE THREAD

**Issue by GiancarlosIO** [styled-components/styled-components#1538]
## Version
styled-components: 2.4.0
babel-plugin-styled-components: 1.3.0

## Reproduction
I have no repo to reproduce this because the project is so big, my main goal is to see if someone else has the same problem . If it's necessary i can spend a couple of hours to trying to create a repo to reproduce this.

## Expected Behavior
The styles should be created successfully.

## Actual Behavior
the styles are not generated.

Extra info:
I noticed the styles are no being generated for the components using the props from ThemeProvider
also i'm using some hoc/providers components:
- Provider/connect from redux
- ApolloProvider/graphql from react-apollo
- MuiProvider from material-ui
- Router/Swich/Route/withRouter from react-router-dom

babel-plugin-styled-component config:
![captura de pantalla de 2018-02-20 11-23-48](https://user-images.githubusercontent.com/17274950/36435716-6bef9bd8-1630-11e8-8a71-f3568c3ca001.png)

## Screenshots
In development mode:
![captura de pantalla de 2018-02-20 10-50-04](https://user-images.githubusercontent.com/17274950/36434047-15b2a43a-162c-11e8-8cec-cbadd8fded60.png)

In production mode:
![captura de pantalla de 2018-02-20 10-59-00](https://user-images.githubusercontent.com/17274950/36434542-3b712b1e-162d-11e8-88b1-9d2eae7a48c3.png)

Also i tried to install v3.1.6 but the styles are broken.
![captura de pantalla de 2018-02-20 10-42-58](https://user-images.githubusercontent.com/17274950/36434617-6f9b0e50-162d-11e8-958f-84dc66e5f075.png)

**Comment by fabian818** [comment]
Same here.

**Comment by typeoneerror** [comment]
Works on first load, but when I refresh the page, the theme is not propagated down to sub-components. Maybe a service worker issue?

**Comment by kitten** [comment]
Can you please upgrade to the latest version and try again. Please refer to the releases page for a list of breaking changes (there shouldn’t basically be any big ones)

We also do *need* some kind of minimal reproduction

**Comment by GiancarlosIO** [comment]
@kitten i was using some helpers inside my MaxContainer, i just put them in the injectGlobal function and the components get the correct styles, only 2-4 components(aside bar and card) are not getting the correct styles. so strange

![captura de pantalla de 2018-02-21 10-30-04](https://user-images.githubusercontent.com/17274950/36488763-48fd100c-16f2-11e8-9e9b-6a35ef00aa3d.png)

I had to use classNames and sass to fix the problem of sidebar and card

**Comment by kitten** [comment]
@GiancarlosIO `injectGlobal` is completely unrelated to the `ThemeProvider`. Are you referring to some of your StyledComponents instead? I really cannot help you if you don't post some code :wink: this sounds like a usage issue to me. Have you checked whether you have some invalid CSS somewhere that is breaking some rules?

**Comment by GiancarlosIO** [comment]
@kitten ok that was my bad, i found the problem.
In that page we are using reactour it use styled-componentv3.1.5 and it conflicts with our v2.4 i guess
So we created an alias for styled-components

`'styled-components': join(pathNodeModules, 'styled-components'),`

actually we not get warning messages in the console (https://www.styled-components.com/docs/faqs#why-am-i-getting-a-warning-about-several-instances-of-module-on-the-page) that's why i not used the alias.

Maybe we can add some warnings to advice the user.

**Comment by kitten** [comment]
@GiancarlosIO I think `2.4` might be a version before the warning was introduced. It works by setting a global flag, so we won't actually output the warning.

Feel free to come up with new ideas and open a PR for it, if you have a better idea :+1:
