### ISSUE TITLE
IE9/IE10 error - Unable to get value of the property 'isStatic' : object is null or undefined

### ISSUE THREAD

**Issue by austingray** [styled-components/styled-components#1539]
## Version
styled-components: 3.1.6

I believe I'm using styled-components normally but it is a large front end using `react-apollo`. However the version without styled-components works on IE9 and IE10.

I am going to go through each of my components and determine what is causing this and will report back when I discover the issue.

**Comment by kitten** [comment]
Please do! However, please note that IE9 is not supported due to React not supporting it

**Comment by mxstbr** [comment]
Actually, our browser support is IE9+ given that React supports IE9+. Ref: https://reactjs.org/docs/react-dom.html#browser-support and https://www.styled-components.com/docs/faqs#which-browsers-are-supported

**Comment by austingray** [comment]
There was a component that was extending from another component:
```
class CustomComponent extends GenericComponent {
```

fixed it by making it extend React.Component:
```
class CustomComponent extends React.Component {
```
IE9/10 working as intended, thank you.
