### ISSUE TITLE
Animate to Component by adding className via event

### ISSUE THREAD

**Issue by santaclauze** [styled-components/styled-components#154]
This is a practical question. I was going to ask the question on stackOverflow but my rep is to small to create a tag styled-component and due to the very recent nature of this project I am unsure I will receive an answer.

Similar to the Login-Flow of @mxstbr https://github.com/mxstbr/login-flow, I am trying to add a neat 'Tremble' effect via onClick. I am not sure how to do this. 

Right now I have created a Tremble styled-component:

        const shake = keyframes`
           10%, 90% {
            transform: translate3d(-1px, 0, 0);
          }
          
          20%, 80% {
            transform: translate3d(2px, 0, 0);
          }
        
          30%, 50%, 70% {
            transform: translate3d(-4px, 0, 0);
          }
        
          40%, 60% {
            transform: translate3d(4px, 0, 0);
          }
        `;

        const Tremble = styled.div`
          display: inline-block;
          &:hover {
            animation: ${shake} 0.82s cubic-bezier(.36,.07,.19,.97) both;
            transform: translate3d(0, 0, 0);
            backface-visibility: hidden;
            perspective: 1000px;
          }
        `;

        export default Tremble;

I also have my Form:

        export class FormLoginTest extends React.Component { // eslint-disable-line react/prefer-stateless-function

          static propTypes = {
            isTrembling: React.PropTypes.bool
          };
          
          static defaultProps = {
            isTrembling: true
          };

          onMakeTremble = () => {
              alert('clickity');
          }

          render() {
            return (
              <Form isTrembling={this.props.isTrembling>
                <ContainerFluid>
                  <H2>Login</H2>
                </ContainerFluid>
                <ContainerFluid>
                  <Label htmlFor="username">Username</Label>
                  <Input type="text" id="username" placeholder="bob" autoCorrect="off" autoCapitalize="off" spellCheck="false" />
                </ContainerFluid>
                <ContainerFluid>
                  <Label htmlFor="password">Password</Label>
                  <Input id="password" type="password" placeholder="••••••••••" />
                </ContainerFluid>
                <ContainerFluid>
                  <Button nature="success" onClick={this.onMakeTremble}>Hello</Button>
                </ContainerFluid>
              </Form>
            );
          }
        }

        export default FormLoginTest;

I know my code is messy, as stated in another issue, I am actually learning how to code with react -_-.

Is there a way to apply a new Css className to my FormLoginTest via onClick so that the Tremble effect is applied to the component.

This actually leads me to the next question: If i wanted to create utilities class, say "pull-right", how could this be done and applied without using an css style sheet?

**Comment by TheSisb** [comment]
I haven't worked with styled-components at all yet, in fact I just found this repository, however I think this is a React question first.
I don't think you want the button to be trembling continuously, do you? That would be annoying for users.  So you _probably_ don't really want it passed as a prop without the ability to toggle it.  I think you would rather state here.
```
getInitialState() {
  return {
    isTrembling: false  // or this.props.isTrembling
  };
}
```

Then your onClick function would just set that to true for an interval (I'll leave the setTimeout as an exercise to the reader - use React Timer Mixin though!).
```
this.setState({isTrembling: true}); // or isTrembling: !this.state.isTrembling to toggle it
```

and lastly in your render do something like this
```
<Tremble isTrembling={this.state.isTrembling}>
   <Button etc.. />
</Temble>
```

**Comment by tzs34** [comment]
I'm trying to do something similar. I'd say you need to setState via your event and use the pass props in approach to fire our animation.  See the docs for passed in props
