### ISSUE TITLE
Question about the internals of the css utility

### ISSUE THREAD

**Issue by ryanzec** [styled-components/styled-components#1540]
So this is more of question of the internals of the `css` utility so figure this would be a good local for that kind of question.

So from my basic experimenting with what is returned by using `css` from styled is that it returns an array of strings that seem to store one or more of the css rules defined in it. My question is whether or not this is always the case and whether or not there are any intentions on changing that?

The context of my question is that I am trying to come update with a system that allows me to easily test the styles of styled components with AVA (which it not support by the testing utils styled components current have). My current solution is that nothing using styled (like `styled.div`, `styled(Component)` etc.) adds actual css rules but instead it calls function that then return the styles like this:

```jsx
export const baseContainerStyles = (props) => {
  return `
    color: white;
    background-color: {props.backgroundColor};
  `;
}

export const MyComponent = styled.div`
  ${baseContainerStyles}
`;
```
This is done because testing the results of `styled.div` is not very easy with AVA but testing `baseContainerStyles()` is very simple, it just returns text. The downside of this approach is that editors / IDEs no longer give syntax highlighting, intellisense, etc. If I know using `css` will alway return an array of strings of the css rules, then I can easy adapt my test utility to account for that and allow using `css` which will give better editor / IDE support.

Any info on this would be great.

**Comment by kitten** [comment]
I’d suggest you to take a look at the jest-styled-components library as to how to extract the css rules and component IDs during testing.

The css function just interleaves all tagged template string parts (strings, interpolations; both alternating) and runs it through a first stringification stage where non-functional interpolations are resolved immediately.

If you’d like to ask these kinds of questions btw Spectrum might be a better starting point.

If you’re interested in building some test utilities for Ava, please ping me on Twitter DMs (or Spectrum, etc), and is be happy to explain you what’s involved in getting this done :+1:

**Comment by mxstbr** [comment]
https://spectrum.chat/thread/5d00ef20-6a3b-4d94-bae7-01f67c71423b
