### ISSUE TITLE
Do styled-components@3.1.0 and grid-styled@3.0.0 work together?

### ISSUE THREAD

**Issue by leushkin** [styled-components/styled-components#1541]
## Version
styled-components: 3.1.0 or latest
grid-styled: 3.0.0 or latest

## Steps to reproduce
Just install latest versions of those packages.

individually they work fine. But together they don't. Looks like Flex rules do not work.

**Comment by kitten** [comment]
Please ask this question in the grid-styled repo, as this issue doesn’t concern the dependency but the dependent :wink:

Generally, not much has changed in the last major, however we’re now hiding internal files by using bundles for all entries.

When you submit an issue please make sure to also submit a reproduction. “Flex rules do not work” is too vague. Cheers
