### ISSUE TITLE
Add CHANNEL and CHANNEL_SHAPE back

### ISSUE THREAD

**Issue by alansouzati** [styled-components/styled-components#1545]
Hey previously we where able to access `CHANNEL_NEXT`, `CHANNEL`, and `CONTEXT_CHANNEL_SHAPE ` since you exported that inside ThemeProvider. Now this seems to be gone. I have a scenario where a library may or not use ThemeProvider. by using `withTheme` it yields a warning if ThemeProvider is not being used. Is is possible to add the export back?

In the meantime I had to manually set that in my code:

https://github.com/grommet/grommet-icons/commit/8c7094f74c1daba7f948b69430516d71bb4deb2c

**Comment by kitten** [comment]
We are now just exposing flat bundles. This means that internal files and APIs may not be accessed.

This is really important to us as it allows us to simplify builds, optimise bundle sizes, and most importantly we ran into trouble often where people would import internal files and break things or duplicate the library in their build.

So all in all, we’d rather avoid exposing things that are not to be used directly by users. What exactly is your use case of using or not using the theme? Can you describe a small example please?

**Comment by alansouzati** [comment]
Hey @kitten thanks for the quick answer.

I'm fine with your plan to avoid exposing things that are not meant to be used outside.

We are recently migrating Grommet to styled-components, you can see some of the components here: 
http://v2.grommet.io/components

As part of the move process we created a lib called `grommet-icons`, you can see them here:

http://grommet.io/grommet-icons/

Grommet icons can be used in a handful of different scenarios. One of the possible use case is to have the Grommet theme support or the ThemeProvider from Styled Components. So, our Icon component takes care of checking the context and see if the subscribe channel is available. If yes, it means that ThemeProvider is in the context. Otherwise, we will use the grommet theme capabilities.

So it would be nice to have some API from your end to maybe pass the context and return the `subscribe/unsubscribe` functions?

**Comment by mxstbr** [comment]
Why can't you use `withTheme`?

**Comment by alansouzati** [comment]
because it adds a warning if you are not using `ThemeProvider`. Please correct me if my interpretation is wrong.

Here is the place where it triggers the warning:

https://github.com/styled-components/styled-components/blob/beed1b813a1bbe11a94f73d7aa3669392bd891eb/src/hoc/withTheme.js#L49

It would also be great if `theme` prop would be added inside a `styledComponent` context. Most of our grommet components support `theme` as a prop and it conflicts with `withTheme`

**Comment by probablyup** [comment]
This isn't going to work with the new context API I think?

**Comment by alansouzati** [comment]
can you expand on that @probablyup ?

**Comment by evan-scott-zocdoc** [comment]
It doesn't work on the premise of context channels anymore: https://medium.com/dailyjs/reacts-%EF%B8%8F-new-context-api-70c9fe01596b

Essentially the context keys get removed.

**Comment by kitten** [comment]
@alansouzati Another idea for a solution here, can't you use `withTheme` and set `defaultProps.theme`? We won't log a warning when a default is being applied which you might already be harnessing for your library?

**Comment by probablyup** [comment]
Closing this since v4 uses new context and this stuff doesn't exist anymore
