### ISSUE TITLE
:host-context

### ISSUE THREAD

**Issue by rr-kalbeck** [styled-components/styled-components#1547]
is there something similar to :host-context in styled components?
https://developer.mozilla.org/en-US/docs/Web/CSS/:host-context()

i noticed angular has this...
https://angular.io/guide/component-styles#host-context

until now i've been passing props to achieve the same thing. was just wondering if there is a better way or if perhaps it's an idea to implement this, so we could write something like eg..

```
const ComponentStyles = styled.div`
    h1 {
        color: yellow;
    }
    
    :host-context( AnotherComponent ) h1 {
        color: orange;
    }
`;
```

**Comment by alexpate** [comment]
You can use Sass like syntax, as well as targeting components.

For example:
```javascript
const ComponentStyles = styled.div`
  h1 {
    color: yellow;
    
    ${AnotherComponent} & {
        color: orange;
    }
  }
`;
```

The hashed classname for `AnotherComponent` would be placed before the classname of `ComponentStyles`:

```css
.componentStyles h1 {
  color: yellow;
}

.anotherComponent .componentStyles h1 {
  color: orange;
}
```

It's kind of an anti-pattern though and has the potential to become quite messy.

**Comment by kitten** [comment]
Yes, I have no idea what `:host-context` is or where it came from 😅 but the above reply seems to be what you're searching for.

Here's the corresponding doc page: https://www.styled-components.com/docs/advanced#referring-to-other-components
