### ISSUE TITLE
apply additional styles above an existing react component is not working

### ISSUE THREAD

**Issue by adamchenwei** [styled-components/styled-components#1548]
## Version
`"styled-components": "^2.2.3"`

## Reproduction

https://www.webpackbin.com/bins/-KeeZCr0xKfutOfOujxN
https://codesandbox.io/s/rkmNRByE4

## Steps to reproduce
create two components

FormattedFormTitle.js
```
import styled from 'styled-components';
import FormTitle from './../../../components/FormTitle';

export default styled(FormTitle)`
  && {padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 16px;
  padding-right: 16px;}
`;

```

FormTitle.js
```
import React from 'react';
import PropTypes from 'prop-types';
import Container from './style/Container';
import Title from './style/Title';

const FormTitle = (props) => {
  const {
    title,
    hasBorder,
  } = props;
  return <Container hasBorder={hasBorder}><Title>{title}</Title></Container>;
};

FormTitle.propTypes = {
  title: PropTypes.string,
  hasBorder: PropTypes.bool,
};

FormTitle.defaultProps = {
  title: 'Form',
  hasBorder: false,
};

export default FormTitle;
```

`FormattedFormTitle` component wont apply the style into the original `FormTitle` component when I render `FormattedFormTitle` into another component somewhere else.

How to resolve this?

## Expected Behavior
The paddings should apply on top of `FormTitle` when `FormattedFormTitle` is used in somewhere else in my React JS App
## Actual Behavior
No paddings are added.

**Comment by adamchenwei** [comment]
btw https://www.styled-components.com/docs/advanced bottom of page method does not apply to this scenario. I tried.

**Comment by kitten** [comment]
You're not passing down the `className` prop. Here's the section you might be searching for: https://www.styled-components.com/docs/basics#styling-any-components

> styled-components always generates a real stylesheet with classes. The classnames are then passed to the React component (including third party components) via the className prop.

The reason why it's under this title is that `styled(FormTitle)` where `FormTitle` is **not** a third-party or StyledComponent is not recommended per se, and thus in our eyes an edge case.

I've seen that you commented on that other thread where I'm explaining why (in my opinion) this should be avoided, so I hope you found an answer there.

Please go to StackOverflow or Spectrum first for usage questions :wink:
