### ISSUE TITLE
Issue with styled-components in “custom” single page application

### ISSUE THREAD

**Issue by farzadmf** [styled-components/styled-components#1549]
I'm currently working on an old project, which has its "own way" of doing a single page application (does Ajax calls to an MVC application, gets the view, replaces the view client-side, appends styles and lots of other stuff!!), and although not ideal, currently I'm stuck with it!

I am trying to integrate an existing React application into this site, and what I'm doing is to use `create-react-app` and then `build` to create the bundles, and in the application, in the view begin returned from the server for a specific page, I'm putting `script` and `link` tags, pointing to my bundle files. It's worth noting that this server view is a partial ASP.NET MVC view, so my `script` and `link` tags are somehow part of the `body`.

I'm also using `styled-components` in my React application.

I was inspecting the page, and I saw that `styled-components` is doing things with a custom `link` created in the `head`, and I see `data-styled-components` attribute being populated with custom class names as my components are loaded, but when the problem arises, in Chrome Developer Tools, I see that the `link` tag flashes as if it's changed, but it stays the same.

I have attached a GIF of the tag:
- It starts with the initial page load
- I navigate away and come back and I see more classes being appended
- I repeat the step, and I only see that it flashes

I know the post is already long, but any help is deeply appreciated. Is it possible that, with the current infrastructure, it has something to do with the fact that whenever I come back to the page, a `script` tag is sent from the server pointing to my React bundle?

![styled-components](https://user-images.githubusercontent.com/5768792/36578374-d0f1d3ec-182a-11e8-9c4e-1fc9d242b9e4.gif)

**Comment by mxstbr** [comment]
> Is it possible that [...] it has something to do with the fact that whenever I come back to the page, a script tag is sent from the server pointing to my React bundle?

Yes. That means you have multiple instances of styled-components running at the same time, which does not work. You'll have to somehow make sure to only load styled-components once.

Also see https://www.styled-components.com/docs/faqs#why-am-i-getting-a-warning-about-several-instances-of-module-on-the-page

**Comment by farzadmf** [comment]
@mxstbr  Thank you for your answer. I had seen this in the Website, but does it mean that I should receive the error that's mentioned there, telling me about multiple instances? Because the thing is that I don't see any messages in the console complaining about multiple instances.

**Comment by mxstbr** [comment]
No I don't think we've published that version yet 😅

**Comment by farzadmf** [comment]
Oh, OK, thank you so much for your help :)
