### ISSUE TITLE
performance/filesize optimizations for pwa projects

### ISSUE THREAD

**Issue by markoshust** [styled-components/styled-components#1550]
`styled-components` is being considered for a pretty nice-sized react/pwa project, however the 40kb zipped size is way too large to be considered for a pwa. Thinking through ways this filesize can be tremendously sized down. I'm not sure what final bundle size maximum would be, but it's not near 40kb ;)

It may be too late for this project, but pwa's aren't going away, and styled-components will continue to be looked over due to the bundle size. I think we have two possible solutions:
- a "mini/slim" version of styled-components. what possible features can be majorly stripped out that don't effect core functionality?
- perhaps major filesize optimizations that can be made in sweep (has prepack been looked at yet?)

Another possibility is a fork or other OSS project that uses the concepts of styled-components, but much more slimmed down. Does anyone know of any?

Cheers 🍺 
Mark

**Comment by mxstbr** [comment]
https://github.com/jxnblk/diet-cola by @jxnblk is probably your best bet!

That being said, I'd love somebody to look at prepack! I tried running it but it just failed so I gave up.

**Comment by jxnblk** [comment]
Also made another clone, that uses inline style tags (works with streaming and in iframes) if that's of any use https://github.com/jxnblk/nano-style

**Comment by markoshust** [comment]
@mxstbr thanks much, what i was looking for. it appears prepack doesn't recognize jsx (just found that out), so that's perhaps why :)
