### ISSUE TITLE
Nested Styled components

### ISSUE THREAD

**Issue by michaelroevievictoria** [styled-components/styled-components#1555]
I have a problem in nested style my warning says

> Prop `style` did not match. Server: "display:inline-block;color:#ffffff;fill:#ffffff;height:24px;width:24px;user-select:none;transition:all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms;mui-prepared:;-webkit-user-select:none;-moz-user-select:none;-ms-user-select:none;-webkit-transition:all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms;-moz-transition:all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms" Client: "display:inline-block;color:#ffffff;fill:#ffffff;height:24px;width:24px;user-select:none;transition:all 450ms cubic-bezier(0.23, 1, 0.32, 1) 0ms;mui-prepared:"

my code looks like this,
```

const OrderInfo = styled(Grid)`
  .width {
    padding-left: 8px;
    padding-right: 8px;
    padding-top: 8px;
  }
  .paper {
    padding: 10px 0px;
    margin-top: 45px;
  }
  .goalPercentage {  

    display: inline-block;
    position: relative;
    width: 100px;
    height: 100px;
    vertical-align: middle;
    
    svg {
      circle {
        transition: stroke-dashoffset 1s linear;
        stroke: #CFD8DC;
        stroke-width: 5pt;
      }
      circle.completed {
        stroke: #00BCD4;
      }
    }
  }

  .goalPercentage:after {
    position: absolute;
    display: block;
    width: 100%;
    left: 0;
    top: 50%;
    content: attr(data-pct) "%";
    margin-top: -18.5px;
    border-radius: 100%;
    font-size: 26px;
    text-align: center;
    margin-left: auto;
    margin-right: auto;
    letter-spacing: -2px;
  }
`;
```
```


render() {
    let circleStyle = {
      strokeDasharray: 2 * Math.PI * 40
    }

    let completedStyle = {
      strokeDasharray: 2 * Math.PI * 40,
      strokeDashoffset: (100 - this.props.goalPercentage) / 100 * 2 * Math.PI * 40
    }
    return (
      <OrderInfo fluid className='width' style={{ maxWidth: '1200'}} >
        <Paper className='paper'>
          <Col xs={6}>
            <Col xs={3} style={{display: 'inlineBlock'}}>
              <div className='goalPercentage' data-pct={this.props.goalPercentage}>
                <svg viewPort='0 0 100 100' version='1.1' xmlns='http://www.w3.org/2000/svg'>
                  <circle r='40' cx='50' cy='50' fill="transparent" style={circleStyle} transform='rotate(-90, 50, 50)'></circle>
                  <circle className='completed' r='40' cx='50' cy='50' fill="transparent" style={completedStyle} transform='rotate(-90, 50, 50)'></circle>
                </svg>
              </div>
            </Col>
            <Col xs={3} style={{borderLeft: '1px solid #B0BEC5', paddingLeft: 20}}>
              <h1 style={{margin: 0, whiteSpace: 'nowrap', overflowX: 'hidden', textOverflow: 'ellipsis'}}>
                test
              </h1>
            </Col>
          </Col>
          <Col xs={6}>

          </Col>
        </Paper>
      </OrderInfo>
    );
  }
```

**Comment by kitten** [comment]
We're not utilising the `style` prop for our CSS rules, so it's likely that the issue lies some place else.

Have you checked whether you're generating some dynamic styles in a way that affects the server differently?

**Comment by Amritha777** [comment]
Hey @michaelroevievictoria, me and @riyak1998 are currently working on styled-components, as a part of our RGSOC application. We'd like to work on the issue. Can you make a minimal repository that can be cloned and run to reproduce this issue?

**Comment by probablyup** [comment]
Hmm what is this syntax?

```css
content: attr(data-pct) "%";
```

Looks like SCSS or something.

**Comment by michaelroevievictoria** [comment]
Hi @Amritha777 I dont know what really happen, I just want to make css format inside my 'index.js'  not doing extended css.

**Comment by Djelnar** [comment]
@michaelroevievictoria can you please provode a minimal example with this issue?

**Comment by schang124** [comment]
I am experiencing the same issue.
It seems like the inline style with server side rendering causes the warning.
Does anyone solve this issue?

**Comment by kitten** [comment]
@schang124 I'm not sure whether that's likely the same issue :wink: This issue is stale so please open a new one.

If it's inline styles you're having rehydration issues with, then there's likely a usage problem in your code, that doesn't affect/is caused by styled-components. Feel free to open an issue or ask around on Spectrum for help :+1:
