### ISSUE TITLE
Wrap styled component

### ISSUE THREAD

**Issue by maxs15** [styled-components/styled-components#1558]
Hello,

I'm wondering if there is any way to customize the component returned by styled() ?
I would like to wrap it with a component that will pass some props (like the media) and that will observe changes with mobx to re-render the component.
I don't know if there is already any easy and clean way to do this (didn't find any) but something like that for instance would be handy:
```js
// styled.js file
import React from 'react';
import {inject, observer} from 'mobx-react';
import styled from 'styled-components';

@inject('app')
@observer
class MediaComponent extends React.Component {

  render() {
     var {Component, app, ...props}  = this.props;  

     return <Component media={app.media} {...props}/>
  }

}

// This function won't be enough to handle all the tags: styled.div, styled.form...
export default function(Component) {
    return styled(Component).withComponent(MediaComponent);
}
// Maybe we could create an utility method withDefaults that will take care of all of that automatically
export default styled.withDefaults({attrs: {mode: 'light'}, component: MediaComponent});


// home.js file
import styled from './styled';

// Declare a styled component supporting the media and mobx by default
const Layout = styled(Box).attrs({type: 'test'})`
   background: ${({media}) => media == 'mobile' ? 'red' : 'blue'}
`
```

Let me know if you see any way to do that currently and what you think about my proposal.

Thanks

**Comment by maxs15** [comment]
It's not an usage question, it's a feature proposal open for discussion...

**Comment by maxs15** [comment]
Thanks @kitten for the feedback.
In a few words, I'm looking for an easy way to wrap the components I declare using styled().
Currently the only way to do that would be to call a function on my styled components declarations.
```js
   const Layout = componentWrapper(styled(Box).attrs({color: red})`
       background: ${(props) => props.color};
   `)

   const Wrapper = componentWrapper(styled.div`
       background: blue;
   `)
```

I think you'll agree this solution isn't ready the best for code readability and maintenance.

**Comment by karol-majewski** [comment]
I'm also looking for this. My use case: I'm following the [Methodical UI](https://jdauriemma.com/programming/methodical-html-css-development) method when working with CSS.

Methodical UI introduces a bunch of rules. One of them is: _every inline element needs to have a block wrapper`. This means I cannot have a nice, expressive markup like this:

```tsx
<Container>
  <Header>
    <Icon />
    <Title>{title}</Title>
  </Header>
  <Body>
    <Picture href={href} />
    <Message>{message}</Message>
  </Body>
</Container>
```

because every inline element needs its own container required for individual positioning:

```tsx
<Container>
  <Header>
    <IconContainer>
      <Icon />
    </IconContainer>
    <TitleContainer>
      <Title>{title}</Title>
    </TitleContainer>
  </Header>
  <Body>
    <PictureContainer>
      <Picture href={href} />
    </PictureContainer>
    <MessageContainer>
      <Message>{message}</Message>
    </MessageContainer>
  </Body>
</Container>;
```

This introduces noise in my markup, making code more difficult to comprehend.

> The default use-case for styled-components is [...] to style small elements and build up structural components

I agree with the premise completely — it's not precise what _small_ means though. Conceptually, an inline element wrapped with a `div` determining its size is still one unit to me. An API like this would come in handy:

```tsx
const Message =
  styled
    .span`
      color: aliceblue;
      font-size: 16px;
      font-family: SF Mono;
    `
    .wrappedWith(props => styled.div`
      display: flex;
      align-items: center;
      border-radius: 2px;
    `);
```

> **Aside**. A bonus benefit would be extended capabilities for static analysis. Some HTML elements are not meant to be descendants of other HTML elements, and this technique could prevent some of cases like this. For example, a `styled.p` should not be allowed to be wrapped with another `styled.p`.
