### ISSUE TITLE
innerRef for functional components

### ISSUE THREAD

**Issue by jacobp100** [styled-components/styled-components#1560]
In #439 (Separate HTML attributes from styling props), most people's approach was to use a functional component to perform filtering.

```jsx
const FilteredDiv = styled(({ color, ...props }) => <div {...props} />)`
  color: ${props => props.color};
`
```

If I understand correctly, there's now no way to get a ref to the div. If you use `innerRef`, the ref will be attached to the functional component, and be called with null.

There could be two solutions to this.

The first is to just invoke functional components with the props. Then you could pass `innerRef` into the above code without any changes. This will probably cause bugs, especially with HOC composition.

The second would be to pass `innerRef` into the functional component. This would mean to use refs, the above code would have to change to,

```jsx
const FilteredDiv = styled(({ color, innerRef, ...props }) => <div ref={innerRef} {...props} />)`
  color: ${props => props.color};
`
```

We have to be careful with this though. We can only pass `innerRef` if it was actually set in the styled component, otherwise users will get a bunch of warnings.

What's the best way forward?

**Comment by probablyup** [comment]
Hmm why doesn't this work right now? We seem to do something like option 1 already https://github.com/styled-components/styled-components/blob/master/src/models/StyledComponent.js#L217-L221

**Comment by jacobp100** [comment]
I think that’s only for composing styled components

**Comment by probablyup** [comment]
Nay, it also attaches refs for non-styled components. Won’t work with a SFC
of course though since they don’t have an instance to refer to...

**Comment by jacobp100** [comment]
Here's an example

https://stackblitz.com/edit/react-skc4ps

**Comment by kitten** [comment]
@jacobp100 this was intentional. We never planned for styled(Component) in mind, but instead for components purely for elements. So this API caters for that usecase only. You can work around it by setting styledComponentId to any value on your components / SFCs. Maybe we should document this somewhere?

**Comment by kitten** [comment]
@jacobp100 Makes sense to me actually; An `innerRef` on a functional component only makes sense if it passes on the `innerRef` prop. We'll need some documentation for it though, but seeing your proposal it's very compelling, since this is the only "proper possible option" for `innerRef` in this case.

What do you think, @mxstbr?

**Comment by AshCoolman** [comment]
Is the `innerRef` workaround something that will continue to be supported given the release of [forwarded refs](https://reactjs.org/docs/forwarding-refs.html) in 16.3?

**Comment by jacobp100** [comment]
Yea, this proposal probably needs to be rethought. Say styled-components forwards the ref, would the following just work?

```jsx
const RefAttachedToDiv = styled(React.forwardRef(({ color, ...props }, ref) => <div {...props} />))`
  some: styles;
`
```

**Comment by probablyup** [comment]
@AshCoolman We'll be removing `innerRef` in 4.0 in favor of `React.forwardRef()`.

**Comment by probablyup** [comment]
Folding this into the [v4 roadmap](https://github.com/styled-components/styled-components/issues/1694)

**Comment by sportnak** [comment]
Here to note that the example: https://www.styled-components.com/docs/api#innerref-prop seems to be broken. Was (unsuccessfully) trying to get innerRef working with my functional styled component.

**Comment by probablyup** [comment]
@sportnak there's a note on that API description that it was removed in v4. It should definitely work if you're still on v3.

**Comment by sportnak** [comment]
@probablyup the documentation example is also broken. But I also have to work around another functional component that was stealing my innerRef so I think my issue is resolved.

**Comment by probablyup** [comment]
Hmm I'll check it out. Thanks.

**Comment by davl3232** [comment]
styled-components/styled-components#1560
