### ISSUE TITLE
Element type is invalid after switching to beta version

### ISSUE THREAD

**Issue by c0debreaker** [styled-components/styled-components#1562]
I'm trying out the `"material-ui": "^1.0.0-beta.35"` right now but I'm encountering an error. I don't have these issues on v0.2.

Here's the screenshot of the error- https://imgur.com/a/VqoR5

```js
import React from 'react';
import { MuiThemeProvider } from 'material-ui'
import {List, ListItem} from 'material-ui/List';
import PowerOnOff from 'material-ui-icons/PowerSettingsNew';
import Settings from 'material-ui-icons/Settings';
import DeviceHealth from 'material-ui-icons/BatteryAlert';
import DeviceOther from 'material-ui-icons/DevicesOther';
import Dashboard from 'material-ui-icons/LaptopWindows';
import MultilineChart from 'material-ui-icons/MultilineChart';
import DevBoard from 'material-ui-icons/DeveloperBoard';
// import Subheader from 'material-ui-icons/Subheader';
import styled from 'styled-components';
import theme from 'styled-theming';
import colors from 'helpers/themecolors';
```

**Comment by mxstbr** [comment]
/cc @oliviertassinari

This should really be over at the mui repo though.

**Comment by c0debreaker** [comment]
Oops, I really thought I was in mui repo. It's not a styled-components issue. My bad Max.

**Comment by oliviertassinari** [comment]
@c0debreaker Please don't open an issue on Material-UI.
v1 is a complete rewrite of the libraries and comes with many breaking changes. Checkout the migration page and feel free to contribute the missing part.

**Comment by c0debreaker** [comment]
Apology for posting it here since I wasn't wearing my reading glasses.
