### ISSUE TITLE
Error when style-components is used as peerDependencies

### ISSUE THREAD

**Issue by ludovicmnji** [styled-components/styled-components#1563]
## Version
styled-components: 3.1.6

## Reproduction

I created a little demonstration of the error there : https://github.com/ludovicmnji/styled-components-issue

## Steps to reproduce

To reproduce the bug, read the README. After you can delete `styled-components` in https://github.com/ludovicmnji/styled-components-issue/blob/master/packages/components/package.json#L35 and re-build the packages to not have issue.

## Expected Behavior

Use styled-components in peerDependencies & devDependencies to build a library of components without include styled-component in final prod bundle.

## Actual Behavior

I started my project with lerna to have a monorepo. Inside I have a UI components package (built with rollup.js but I've tried also webpack) and an another package based on create-react-app to build a styleguide with my UI components. React and styled-components are in peerDependencies and devDependencies in my UI components package but in dependencies in my website package.

When I'm building the website for development (`npm start` in `packages/website`), it works very good. But when I'm building for production (`npm run build` in `packages/website`), I got these errors : 

<img width="374" alt="capture d ecran 2018-02-28 a 18 41 12" src="https://user-images.githubusercontent.com/6171841/36804125-e83212c2-1cb9-11e8-83ea-4d328a6aee91.png">

Thanks of a Spectrum user (https://spectrum.chat/styled-components/help?thread=bcbf5a4b-f1cc-46d8-a034-907d85ddef74) I removed the devDependencies of styled-components and now it works great !

I'm still confused, I didn't understand why it didn't work. I've checked my build before the fix and styled-components wasn't included in my bundle (dev or prod). Someone can help me to understand ? I think it's a bug in styled-components because other libraries works well in this case (React for example). Moreover, I can't use correctly eslint-plugin-import since I can't have styled-components in devDependencies.

**Comment by igoldny** [comment]
i have the same issue.
downgrade to styled-components 2.2.4
and using lerna hoisting fix the problem 
https://github.com/lerna/lerna/blob/master/doc/hoist.md

but with latest styled-components version they still have an issue:
https://github.com/styled-components/styled-components/issues/1571

**Comment by mxstbr** [comment]
See this and the follow-up FAQ answer: https://www.styled-components.com/docs/faqs#i-am-a-library-author-should-i-bundle-styledcomponents-with-my-library

**Comment by ludovicmnji** [comment]
@mxstbr So, only the version 2.4.0 is working to build a library ? 🤔 
Because this is exactly what I've done in my repository but with version 3.1.6 : https://github.com/ludovicmnji/styled-components-issue/blob/master/packages/components/package.json#L35

**Comment by gribnoysup** [comment]
@mxstbr hey, I just noticed that the version of the FAQ on the website is different from the one in the master branch of `styled-components-website`. The latest version contains more advice on how to actually exclude `styled-components` from library build. Maybe this is what confuses people 🤔

**Comment by mxstbr** [comment]
Oh we should redeploy the website!

**Comment by mxstbr** [comment]
Redeployed the website with the additional information, please check that FAQ entry from above again!

**Comment by ludovicmnji** [comment]
@mxstbr I already have excluded `styled-components` as the new FAQ explains (thanks for the fast update !).

Previously I used helper function to exclude automatically the peerDependencies of my package.json but I updated my demo with hardcoded string and it's the same (see https://github.com/ludovicmnji/styled-components-issue/blob/master/packages/components/rollup.config.js#L57). I have the strange error I described in my first post error I'm building my website in production ... 

As @igoldny said, If I used  version 2.4.0 of styled components, the error is not still there ! 😮 
Something went wrong between 2.4.0 and 3.1.6 🤔

**Comment by ludovicmnji** [comment]
If other users have the same issue, version 3.2.0 helped to fix it (without change anything) 🚀
