### ISSUE TITLE
flow-typed v3 libdef?

### ISSUE THREAD

**Issue by ryanzec** [styled-components/styled-components#1565]
It seems like v1 / v2 have libdefs in flow-typed but are there any plans to add v3 to flow-typed?

**Comment by mxstbr** [comment]
Should just a matter of copy-and-pasting the v2 libdef and and adding a type def for `sheet.interleaveWithNodeStream` I think! Wanna take that on?

**Comment by ryanzec** [comment]
Once I figure out a way to be able to apply flow types for styled components without having to wrap the styled component in another stateless or class component, I could probably find some time to do that.

**Comment by probablyup** [comment]
Dup of #1490
