### ISSUE TITLE
Using themes in InjectGlobal

### ISSUE THREAD

**Issue by c0debreaker** [styled-components/styled-components#1566]
I didn't want to post this question here but spectrum.chat's api right now is really bad. I spent 20-30 minutes too just joining on that site. I was posting a question but I would always get a 502 which is gateway timeout, meaning upstream server could be down. https://imgur.com/a/IFycQ

My injectGlobal is in App.js. My ThemeProvider is also in this file. How can I use the theme modes I created using Styled-Theming?

Right now, I have to edit 2 lines. I also created a function that changes it which I think is a crappy solution.

// App.js
```
const setBackground = (theme) => {
  const themes = {
    midnight: colors.bgMidnight,
    light: colors.bgLight
  };
  return themes[theme]
}

injectGlobal`
  body {
    background: ${setBackground('light')};
  }
`

class App extends Component {
  state = {
    mode: 'light'
  };
```

**Comment by mxstbr** [comment]
Sorry about the troubles with Spectrum, I'm on it.

That is unfortunately the way it is right now, but that's exactly why we're planning on doing #1333.

**Comment by c0debreaker** [comment]
Thank you Max! I'm very excited! I can't wait for that change. :)
