### ISSUE TITLE
Returning a boolean expression when the return type is Interpolation<T> Typescript

### ISSUE THREAD

**Issue by TSilviu** [styled-components/styled-components#1567]
## Version 
styled-components: ^3.1.6

## Reproduction
Could not reproduce the issue exactly, but here is a close reporesentation of our setup: https://codesandbox.io/s/2oz1nqq6qy

## Context

We have been converting our internal library of styled components to Typescript. We have this component:

```
interface HrProps {
  inSection: boolean;
}

const Hr = withProps<HrProps, HTMLHeadingElement>(styled.hr)`
  width: 100%;
  max-width: ${({ theme }) => theme.font.typographyBreakpoint};
  border: 1px solid ${({ theme }) => theme.colors.greys.light};
  margin: ${({ theme }) => theme.padding.base} 0;

  ${({ inSection }) =>
    inSection &&
    css`
      margin-top: 0;
      margin-bottom: calc(${({ theme }) => theme.padding.base} * 10);
    `};
`;
```

And this is the `withProps` function:

```
type StyledFunction<T> = styledComponents.ThemedStyledFunction<
  T,
  ThemeInterface
>;

function withProps<T, U extends HTMLElement = HTMLElement>(
  styledFunction: StyledFunction<React.HTMLProps<U>>
): StyledFunction<T & React.HTMLProps<U>> {
  return styledFunction;
}

```
What we do here is returning a styled function which is wrapped with our custom props(`HrProps` in this case) and the HTML props of that element. This was taken from: https://github.com/jacob-ebey/styled-components-ts. This is not directly relevant to the issue - just giving you the context in which the problem occurs.

## Problem

The issue happens inside this interpolation:

```
  ${({ inSection }) =>
    inSection &&
    css`
      margin-top: 0;
      margin-bottom: calc(${({ theme }) => theme.padding.base} * 10);
    `};

```

and we get: 

`error TS2345: Argument of type '({ inSection }: ThemedStyledProps<HrProps & HTMLProps<HTMLHeadingElement>, ThemeInterface>) => fa...' is not assignable to parameter of type 'Interpolation<ThemedStyledProps<HrProps & HTMLProps<HTMLHeadingElement>, ThemeInterface>>'.
  Type '({ inSection }: ThemedStyledProps<HrProps & HTMLProps<HTMLHeadingElement>, ThemeInterface>) => fa...' is not assignable to type 'ReadonlyArray<string | number | Styles | StyledComponentClass<any, any, any> | InterpolationFunct...'.
    Property 'concat' is missing in type '({ inSection }: ThemedStyledProps<HrProps & HTMLProps<HTMLHeadingElement>, ThemeInterface>) => fa...'.`

## Solution

We found a workaround for this by doing:

```
  ${({ inSection }) =>
    inSection
      ? css`
          margin-top: 0;
          margin-bottom: calc(${({ theme }) => theme.padding.base} * 10);
        `
      : ''};
```
Although this works, it is not the same thing as we are now returning an empty string instead of a `null` if `inSection` is equal to `false`.

The issue seems to be that you cannot provide `null` to what is expected to be `Interpolation<T>`. Is this intended behaviour, or should this be a possibility?

**Comment by kitten** [comment]
cc @styled-components/typers

**Comment by Igorbek** [comment]
If `true` and `false` are valid results of interpolation functions, we should add it to the returning type.
I'll check the code how it treats results.

**Comment by probablyup** [comment]
Hey folks, TS typings for styled-components have been moved to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), so please feel free to move your issue there where you'll receive better community support.
