### ISSUE TITLE
New version soon?

### ISSUE THREAD

**Issue by bliitzkrieg** [styled-components/styled-components#1568]
Hey, Is there any timeline for the next version to be released? There is a feature I want to use in the master branch that will resolve a huge bug in my system.

Feature:
https://github.com/styled-components/styled-components/blob/master/src/models/StyleSheetManager.js#L22

**Comment by kitten** [comment]
A release will go out pretty soon :)

Feel free to ask on Twitter or spectrum as those channels are better suited for small questions or questions general

**Comment by bliitzkrieg** [comment]
Which person should I reach out to on twitter if I have a few more questions?

**Comment by kitten** [comment]
@bliitzkrieg feel free to ping myself (“_philpl” on twtr), or one of the other core contributors, namely Max (mxstbr), or Evan (probablyup). We three are probably the most active ones on Twitter out of the five core contributors and are doing most of the planning around all recent releases.
