### ISSUE TITLE
styled-components (3.1.6) in monorepo on production load with no styles

### ISSUE THREAD

**Issue by igoldny** [styled-components/styled-components#1571]
## Version
styled-components: 3.1.6
babel-plugin-styled-components: 1.3.0

## Reproduction
styled-components(3.1.6) within monorepo project plus ssr loads perfectly fine on the server side but when the client loads it empty all the css from styled-components style tag in the head, only on production mode.
styled-components(2.2.4) works perfectly fine on both with no problems at all.

btw i had few [issues with multiple instances](https://www.styled-components.com/docs/faqs#i-am-a-library-author-should-i-bundle-styledcomponents-with-my-library) and every thing was taken care of and the errors are gone but still not working well.

## Steps to reproduce
1. use monorepo project
2. with ssr
3. that have more then one package that use styled-components (for example a theme package)
4. build with webpack (for production)
5. start production mode web server
6. ssr render loads perfectly fine
7. wait till client side bundle (that you build with webpack) finish loads
8. styled-components empty style tag with all the css in in it
9. you get page with no css in it 

## Expected Behavior
work both on server and client as it works on the old versions (2.2.4)

## Actual Behavior
when the client loads all the styles rendered by styled-components are removed from the style tag.

**Comment by Djelnar** [comment]
3.1.5 works as usual

**Comment by igoldny** [comment]
3.1.5 same as 3.1.6 working but when the client javascript loads all the styles are gone and i see at the head style that looks like that:

```
<style type="text/css" data-styled-components="dyvYhs MQotx efCFoP ifJJhX foKyZS cfPwcX cyIHoQ fAiwkk hGVNvw cgDMBd bRiSom dYuZfi iuqgnf cVyPUd delylL cmCUYA isxog cKOCOL fgiwma iqggqU iswaBd dudNxm dASKYP fsrtGB lbRdgg kdQQMF duXgcR hmovvv ijUcOq drZBuZ VoBwn dmhwcB ceNzIu dJsBTB lkWxaD gZwZte jNOoOU gNdyct ksvySG hVSHoy FqmtD dqqalG cBOwyp gqyxlV cpmdiw kxpjWC eWACas ikfhih eJXpGW eXNOgS emDTGU bvMLAr llDtP cqYyrR jpJErh jKoVQi gQcbIw dQzwnV eRDmSX erstze hmRIEz eCjyUi icecTO ciICBD kFcrFH bpHhpR jKQqTX dkfgUJ cYofeF bEEaSb jiKENg bBouRn dpQbWA XOKFs lbOUDL ldtCc wbhGr eMKlgw fVhVWS ixzJSl kbJYxq cHYTaq kimZnM eWty kPTyjr gVNGWp gOzTuD bxVNLl jmPWXG fiWmMf wrMKK gPKDcA jnoejp VTFgo fzvKDH gacAjp eMcGrK cWnQIv xVpJL hcvWKb gwpirM eUCaCh bxKByn bmlduy eqnUkZ cejJEJ kdzEKD jnmYQf ilekTo eUTGbY fexMWO iRYzOv bmMVxj iUgjbv fSxucX ejbvhF gLmEto djPUdb jaPzuW eWkAsp eTvgXU eCEpVV ewkFOo dAYhKK guDEKU faqmLF fPpRuv bByFxR cZzcqJ PKikf bPxMMi eFuNTI kJkVkm gPXtGr hLpqYU heVrOn kzMwvF bexfQo hwWisY kDiLKg gvRWBf fNzJlT inwRHV kgFkUe eFvxzC jTWudI dEczSn bSOSsw bPQwPr ehomBw hpOcUY iXZUzl jbUVLo kEqyhY ciZDNr iGvtbl cMVWJh jfPCIh gJOeef ckODtr szOVR dxpCok bMjpKu iCARCS jZASkt dIFbMn krBXFx fjfERE eFgQxd hZlrHg lbhHWX dUestw gdvBeM jaQHyN hqKtXk kGskHD cOQTiG djWqQb hlQmbX EafdB kIngnl hyyciy kYsRnE dcHJRY fBppAB jtejjM bqcpaM gVQYQt eAUtgB NFikf hFYXco kXSCYc jXGvww lhenWg fKeDbN jvNtIP CbMrc iOrfat epRAiE hVwnYO crhFov hhbphY eMOALa dqryeR ewYWto ddHRir boBtIc gWghjI" data-styled-components-is-local="true"></style>
```

**Comment by MauriceButler** [comment]
This same issue causes issues with snapshotting as well.

`document.documentElement.outerHTML` contains no styles if built in production mode

**Comment by probablyup** [comment]
There are a ton of issues and replies on the subject... v3.1+ uses a new
injection mode called “speedy” (CSSOM insertRule) in production. Due to how
the CSSOM works with this injection method, styles are visible in the
inspector but are not physically in the style tags in the normal way.

**Comment by probablyup** [comment]
So the question is: do you see styles on your page? Not in the tag, but applied to elements visually? If no, then there’s a bug. If yes, there’s nothing to do here.

**Comment by probablyup** [comment]
Note that if you are using the babel plugin as well, you should update to latest.

**Comment by igoldny** [comment]
it's working with lates one, the whole project was working prefectly fine with latest styled-components(3.1.6) version upuntil we move to use monorepo and it still works but only on development, this bug happens only when it built to prod.

**Comment by probablyup** [comment]
@igoldny try adding this to your webpack config

```js
{
  resolve: {
    alias: {
      'styled-components': path.resolve('./node_modules/styled-components')
    }
  }
}
```

(adjust as needed for your directory structure)

**Comment by igoldny** [comment]
@probablyup thnx for help, that alias fix this problem.
even tho i tried to do it before but i guess i did it wrong
