### ISSUE TITLE
import external fonts is broken in 3.2.0

### ISSUE THREAD

**Issue by piuccio** [styled-components/styled-components#1574]
## Version
styled-components: 3.2.0
babel-plugin-styled-components: 1.5.1

## Reproduction

Sorry I tried to reproduce it [here](https://codesandbox.io/s/z2zz2x0jp) but it works fine, however you can see the issue on [this repo](https://github.com/piuccio/styled-bug) it's a clone of react-boilerplate.

There's a file called `global-styles.js` that injects global CSS, including the following

```js
import { injectGlobal } from 'styled-components';

/* eslint no-unused-expressions: 0 */
injectGlobal`
  @import url(https://fonts.googleapis.com/earlyaccess/notosansjapanese.css);
`
```

## Steps to reproduce

`npm install` with styled-component `3.2.0` and `npm start` it'll load a local server. Inspect the styles and you'll see that `Noto Sans` is not used.

Kill the server, change package.json to `3.1.6`, `npm install && npm start` and the fonts are now `Noto Sans`

## Expected Behavior

Always use `Noto Sans`

![screen shot 2018-03-06 at 11 24 38](https://user-images.githubusercontent.com/680284/37011401-4f3821be-2133-11e8-8503-088fe2bf452a.png)

## Actual Behavior

Uses fallback font

![screen shot 2018-03-06 at 11 25 34](https://user-images.githubusercontent.com/680284/37011417-609a5030-2133-11e8-8b5c-898db146dbcc.png)

**Comment by kitten** [comment]
It is in fact reproducible: https://codesandbox.io/s/6wk63nr91n

It seems that I've forgotten to port over some exceptions for `@import` in the migration.

Unfortunately I think it'll be tough to make this work in tandem with #1493, as the `@import` rules need to be at the beginning of the stylesheet, but at the same time we need to be able to remove them at any time.

cc @mxstbr @probablyup

**Comment by mxstbr** [comment]
Oh damn we really need to fix this.

**Comment by kitten** [comment]
@piuccio Can you help me to test out a prerelease that addresses this bug please? It's from the PR referenced above and seems to fix the problem in the CodeSandbox, where I reproduced the bug, just fine: https://codesandbox.io/s/v6v6r73j37

**Comment by piuccio** [comment]
@kitten I tested `3.2.1-2` and it works fine. Thanks for the quick fix
