### ISSUE TITLE
componentWillMount is deprecated in react 16.3

### ISSUE THREAD

**Issue by macrozone** [styled-components/styled-components#1575]
componentWillMount will be deprecated and replaced with UNSAFE_componentWillMount

because it is not safe for async rendering. see https://medium.com/@baphemot/whats-new-in-react-16-3-d2c9b7b6193b

**Comment by kitten** [comment]
We're aware of a lot of the changes involved, but we'll eventually create an umbrella issue for all the changes that need to be made :wink:

I'll leave this open until then

**Comment by gaearon** [comment]
FWIW, migration strategies are here
https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

Let us know if some use case is missing.

**Comment by retrax24** [comment]
should I manually be changed all WillMounts etc to DidMount's?

**Comment by probablyup** [comment]
Folding this issue into https://github.com/styled-components/styled-components/issues/1655
