### ISSUE TITLE
Some characters are broken in SSR @ 3.2.0

### ISSUE THREAD

**Issue by misund** [styled-components/styled-components#1579]
## Version
styled-components: 3.2.0
babel-plugin-styled-components: 1.5.1

## Reproduction
3.1.6 -> 3.2.0 seems to break some characters. In my case, the single quote is the biggest nuisance. Might be a stylis issue?

## Steps to reproduce
1. Create some styles with single quotes.
```injectGlobal`@import url('https://fonts.googleapis.com/css?family=Roboto')` ```
1. Server side render it

## Expected Behavior
This should be server side rendered:
`@import url('https://fonts.googleapis.com/css?family=Roboto');`

## Actual Behavior
Quotes come out escaped from `ServerStyleSheet.collectStyles()`, like this:
`@import url(\'https://fonts.googleapis.com/css?family=Roboto\');`

After a run through webpack, this is server side rendered:
`@import url(&#x27;https://fonts.googleapis.com/css?family=Roboto&#x27;);`

**Comment by kitten** [comment]
I can confirm that this seems to be happening. I've tried it with styled-components.com and it does seem to suffer from the same bug in 3.2.0 as well.

The curious thing is that this is not showing up in our tests at all, and it seems to affect all of SSR, but not under all circumstances.

**Comment by kitten** [comment]
Ok, sorry, this was a really stupid mistake on my end that slipped through the cracks during the refactor. It'll be fixed soon https://github.com/styled-components/styled-components/pull/1580

**Comment by misund** [comment]
That was fast. Almost _dangerously_ fast. Thanks!
