### ISSUE TITLE
position: sticky isn't prefixed for Safari

### ISSUE THREAD

**Issue by oscar-b** [styled-components/styled-components#158]
## Version
1.0.10

## Reproduction
```css
position: sticky;
```

## Expected Behavior
Autoprefix should add prefixed version for Safari:
```css
position: sticky;
position: -webkit-sticky;
```

## Actual Behavior
No prefix.

**Comment by mxstbr** [comment]
This is a duplicate of #111, could you post your specific issue as a comment in that thread? Thank you very much!

(also, cc @threepointone)

**Comment by threepointone** [comment]
thanks, made an issue.

**Comment by threepointone** [comment]
I fixed this on glamor's end with a custom plugin.

**Comment by MbF-Sathya** [comment]
thanks
