### ISSUE TITLE
Question: How do I use styled-components for layout / position styles?

### ISSUE THREAD

**Issue by EdmundMai** [styled-components/styled-components#1588]
I have a large "Homepage" component that is made up of a lot of styled-components. So far so good.

However, I now notice that I need a few plain divs that just need styles for their position. My question is: Do I need to make components for those divs? The only property I need is something like position: relative;.

    <div> <------ I need this to have position: relative, How?
      <Countdown> <------  I need this to have top: -150px, which I did using styled-components.
        <Text>COUNTDOWN</Text>
      </Countdown>
    </div>

So I thought the idea of styled-components was to avoid classNames altogether? What do I do in a situation like this? It feels like it would be component overkill if I had to make a component out of absolutely everything.

Also, I don't know if top: -150px belongs in Countdown... It's weird to have positioning styles as part of the default styling of a component, since that makes it a lot less reusable.

**Comment by kitten** [comment]
> My question is: Do I need to make components for those divs

In the strict idea of styled-components, yes! But luckily this won't be too hard:

```js
const Wrapper = styled.div`
  position: relative;
`;
```

Remember that these can be "one-off" styledcomponents that are local to this one place. In that case you're only defining some styling and are colocating it with a component or some layouting.

> It feels like it would be component overkill if I had to make a component out of absolutely everything.

That is exactly what we are recommending though. One StyledComponent per element, where an element would also be appropriate.

> Also, I don't know if top: -150px belongs in Countdown...

Check this out :) https://www.styled-components.com/docs/advanced#referring-to-other-components
