### ISSUE TITLE
Strongly typed theme property

### ISSUE THREAD

**Issue by farzadmf** [styled-components/styled-components#1589]
Hi,

I am using TypeScript and `ThemeProvider` for my components, and I had a couple of questions:

1. First of all, my components are created using `map`, so I used to assign a `key` to each one, now I have put `ThemeProvider` to be the top parent component, and hence I need to set the `key` on that. I was just wondering does it hurt to do this? Or should I find a way to create a single `ThemeProvider`?

2. Since I'm using TypeScript, it would be very nice if I could somehow make my `props.theme` property be strongly typed. Right now when I hover over `props.theme`, I see that the type is `any`. It would VERY nice if I could somehow define the type for the `theme` property while not changing the inferred type for `props`

Thank you, and the more I use this library, the more I find out how great it is!

**Comment by kitten** [comment]
Regarding 1., I’m not aware of any negative implications of having multiple separate contexts active in React. I wouldn’t expect that to have any negative implications even though I’m not sure why you’d need that :wink:

There’s actually a way to retype components that we create to be based on a theme’s type but I’m not entirely sure anymore how to go about that

cc @styled-components/typers

**Comment by Igorbek** [comment]
@farzadmf please refer to [the docs](https://www.styled-components.com/docs/api#typescript) that describe how to acheive this.

**Comment by farzadmf** [comment]
Hi @Igorbek , Actually I saw the docs _after_ I posted this question, and I thought it was my answer. Although it was very useful, I still don't know how to have a custom property on `props` while using a strongly typed `theme`. Example: if I want to have `status` as a property on `props`, I can create an `interface` like this:

```ts
interface CompProps {
  status: string;
}
```

But now, the problem is that if I have something like this:

```ts
const MyDiv = styled.div`
  background-color: ${(props: CompProps) => ...};
`
```

Now, it will not let me access `theme` on `props` (and also the other ones that I could have accessed without specifying the type for `props`)

I ended up changing my interface to something like this:

```ts
interface CompProps {
  status: string;
  theme?: MyThemeInterface;
}
```

I had to make `theme` optional to prevent TypeScript to force me setting it when creating `MyDiv`, but now I have to do something like this to access `theme`:

```ts
const MyDiv = styled.div`
  background-color: ${(props: CompProps) => (props.theme as MyThemeInterface).propery...};
`;
```

Because even if I use the method mentioned in the docs, as soon as I want to have my own properties on `props`, everything gets complicated

**Comment by Voronar** [comment]
@farzadmf 
[This method](https://github.com/styled-components/styled-components/issues/565#issuecomment-287535650) works well and for `styled` function.

**Comment by farzadmf** [comment]
@Voronar Thank you for your answer, but it doesn't seem to be working for me; what I have:

```ts
// In my 'styled' wrapper:
import { ThemedStyledProps } from 'styled-components';

export type MyThemeProps<P> = ThemedStyledProps<P, MyTheme>;

// In my custom styled component:
interface IProps {
  status: string;
}

type IMyCompProps = MyThemeProps<IProps>;

// Here, 'styled' is the wrapper mentioned in the documentation
export const MyComp = styled.div`
  background-color: ${(props: IMyCompProps) => props.theme.myComp.color[props.status]};
`;
```

So, in my custom styled component, everything seems to be fine, but when I try to use this component like this:

```jsx
<MyComp status="my-stats">Display my status</MyComp>
```

It complains that property `status` does not exist on the type mentioned as `IntrinsicAttributes & IntrinsicClassAttributes<...>`

Am I missing something here?

**Comment by probablyup** [comment]
Hey folks, TS typings for styled-components have been moved to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), so please feel free to move your issue there where you'll receive better community support.

**Comment by thetrompf** [comment]
Hi found the following solution rather useful:

```tsx
// Theme.tsx
import baseStyled, { ThemedStyledInterface } from 'styled-components';

export const theme = {
    color: {
        lightShade: '#eeeee8' /* Cararra */,
        lightAccent: '#949b92' /* Stack */,
        mainBrand: '#876351' /* Shadow */,
        darkShade: '#252423' /* Shark */,
        darkAccent: '#ac7742' /* Cape Palliser */,
        primary: '#876351' /* Shadow */,
        info: '#232525' /* Shark */,
        success: '#5e9850' /* Fruit Salad */,
        warning: '#db8818' /* Zest */,
        danger: '#f44336' /* Pomegranate */,
    },
};

export type Theme = typeof theme;
export const styled = baseStyled as ThemedStyledInterface<Theme>;
```

```tsx
// App.tsx
import { ThemeProvider } from 'styled-components';
import { Sidebar } from './Sidebar';
import { theme } from './Theme';

export const App = () => {
    return (
        <ThemeProvider theme={theme}>
             <Sidebar />
        </ThemeProvider>
    );
};
```

```tsx
// Sidebar.tsx
import { styled } from './Theme';

interface Sidebar {
    isOpen: boolean;
}

const Sidebar = styled.div<LayoutProps>`
    background-color: ${props => props.theme.color.darkShade};
    display: flex;
    transition: min-width 300ms;
    flex: 0 0 0px;
    min-width: ${props => (props.isOpen ? 250 : 10)}px;
`;
```

**Comment by alexcheuk** [comment]
I managed to just autocomplete `props.theme` properly by adding this file in my project `typings/styled-components.d.ts`

```
import { theme } from 'config/themes'

type ThemeInterface = typeof theme

declare module "styled-components" {
  interface DefaultTheme extends ThemeInterface {}
}
```

**Comment by Tismas** [comment]
Is it possible to solve this situation: https://codesandbox.io/s/pw087l0y17  
without making theme optional prop and adding `... as ITheme` everywhere?
Solutions above didn't work for this case

**Comment by thetrompf** [comment]
@tismas My solution where you re-export styled-components with your theme types supports your scenario.

**Comment by IrvingArmenta-ML** [comment]
@thetrompf  
Your scenario works fine on elements like this: 
```
const Sidebar = styled.div<Props>`
    background-color: ${props => props.theme.color.darkShade};
    display: flex;
    transition: min-width 300ms;
    flex: 0 0 0px;
    min-width: ${props => (props.isOpen ? 250 : 10)}px;
`;
```

But it doesn't seem to work fine when using with a functional component that may include other typings, for example: 

```
import { Icon } from '@blueprintjs/core';
import { Box, BoxProps } from '@rebass/grid';
import React from 'react';
import { styled } from './../common/GlobalStyle';
import { Theme } from './../common/GlobalStyle';

type NoticeMessageType = BoxProps & Theme;

const NoticeMessage = (props: NoticeMessageType) => {
    return (
        <Box {...props}>
            <span className="icon-wrap">
                <Icon icon="warning-sign" iconSize={20} />
            </span>
            <p>static string text</p>
        </Box>
    );
};

NoticeMessage.defaultProps = {
    mx: 'auto'
};

const NoticeMessageStyled = styled(NoticeMessage)`
    max-width: 900px;
    text-align: center;
    color: ${props => props.theme.colors.reeed};
    margin-top: 32px;
    .icon-wrap {
        display: block;
        margin-bottom: 10px;
    }
    p {
        text-align: left;
        margin-bottom: 0;
    }
`;

export default NoticeMessageStyled;
```
It's hard to explain my whole scenario but essentially what I'm trying to do is to use the `<Box>` component to build my own `NoticeMessage` component, the `defaultProps` is part of the `<Box>` props, and of course I want to be able to pass the props to `<Box>` from `<NoticeMessage>` but it's a typing error if I add the two typings as such. If I just put `(props: any)` on the Functional component then the components works of course, but the `${props => ...}` typing becomes `any` as well, and there is no auto-completion at all.

**Comment by thetrompf** [comment]
Hmm 🤔 I have to try this myself, because on the top of my head this should work alright. The only thing that "smells" is the intersection of your `Theme` type and the prop types to `NoticeMessage`, that shouldn't be necessary, unless `Box` from `@rebass/grid` requires it. Your custom re-exported `styled` should be able to inject your theme prop into the types without any effort on your part. So the props to `NoticeMessage` should just be of type `BoxProps`, if you have exported styled as mentioned in my example above.

**Comment by samuelcastro** [comment]
@hiwelo Was your commit merged already?

**Comment by kettanaito** [comment]
I think a proper way to type annotate your theme is to create a custom `styled-components.d.ts` (name matters not) and extend the "styled-components" module.

```ts
// src/theme.ts
export default {
  colors: {
    black: '#000'
  }
}
```

```ts
// ./styled-components.d.ts
import theme from './src/theme'

type CustomTheme = typeof theme

declare module 'styled-components' {
  export interface DefaultTheme extends CustomTheme {}
}
```

Make sure to include this file in your `tsconfig.json`:

```json
{
  "compilerOptions": {
    "includes": ["styled-components.d.ts"]
  }
}
```

**Comment by jacknevitt** [comment]
@alexcheuk @kettanaito Thanks for these, they look clean. However no autocomplete comes up for theme in my component

**Comment by kettanaito** [comment]
@jacknevitt that sounds strange. Could you share your setup? There must be something off.

**Comment by tolerance-go** [comment]
**love it**

**Comment by rumanbsl** [comment]
@kettanaito you are lifesaver. 
![selectAll](https://user-images.githubusercontent.com/13895272/80504978-6a43ce00-897c-11ea-9240-d1d918363fbc.gif)

**Comment by tareqdayya** [comment]
The type definition file works wonders for me. I don't need to do anything else.
The only problem is that, for some reason, using **component selectors** inside the css immediately goes away with the editor's auto-complete for that very styled component.

I'm not sure if it's my editor (web storm) or something else.
 Can anyone confirm that it's not just me?  Here's an example if you wanna try it in ur editors:

```
const A = styled.div`
color: ${(props) => props.theme.color.solid.success};
`;

const B = styled.div`
color: ${(props) => props.theme.color.solid.warning};

${A}:hover & {
color: ${(props) => props.theme.color.solid.danger};
}
`;
```

In my case, auto-complete in **B** is not working.

**Comment by OlegBrony** [comment]
> @kettanaito you are lifesaver.
> ![selectAll](https://user-images.githubusercontent.com/13895272/80504978-6a43ce00-897c-11ea-9240-d1d918363fbc.gif)

what soft do you use? I use webstorm and autocomplete didn't work.

**Comment by rumanbsl** [comment]
> > @kettanaito you are lifesaver.
> > ![selectAll](https://user-images.githubusercontent.com/13895272/80504978-6a43ce00-897c-11ea-9240-d1d918363fbc.gif)
> 
> what soft do you use? I use webstorm and autocomplete didn't work.
> upd: the autocomplete is working if I type a whole first key. here:
> ![image](https://user-images.githubusercontent.com/19880334/82248339-a00f1d80-9950-11ea-82b6-58499ba18688.png)
> and here:
> ![image](https://user-images.githubusercontent.com/19880334/82248364-af8e6680-9950-11ea-9118-18787ac11491.png)
> any solutions?

I am using VS-code, I won't be of any help I am afraid. I can put down a scaffold project, if that helps :)

**Comment by brendanmc6** [comment]
@kettanaito Thank you for the solution, however your claim that "name matters not" for `styled-components.d.ts` was misleading in my case.
In my project, naming the file `styled-components.d.ts` was overwriting the entire module declaration.
I have to name it `styled.d.ts` or put the declaration with my other global types inside `index.d.ts`

This behavior is in a fresh next.js typescript project with default configuration.

Otherwise, this works great, thank you!

**Comment by teroqim** [comment]
I have a fresh project with nextjs+typescript and I'm using vscode. None of the above proposed solutions worked for me... until I installed @types/styled-components as a dependency. After that the solution proposed by kettanaito worked like a charm. Thanks!

**Comment by Ed-Ed** [comment]
> I think a proper way to type annotate your theme is to create a custom `styled-components.d.ts` (name matters not) and extend the "styled-components" module.
> 
> ```ts
> // src/theme.ts
> export default {
>   colors: {
>     black: '#000'
>   }
> }
> ```
> 
> ```ts
> // ./styled-components.d.ts
> import theme from './src/theme'
> 
> type CustomTheme = typeof theme
> 
> declare module 'styled-components' {
>   export interface DefaultTheme extends CustomTheme {}
> }
> ```
> 
> Make sure to include this file in your `tsconfig.json`:
> 
> ```json
> {
>   "compilerOptions": {
>     "includes": ["styled-components.d.ts"]
>   }
> }
> ```

A few notes about this.

- "includes" is not a compiler options
- if you keep `styled-components.d.ts` inside `@types` for example, you'll need to point to that directly like so: `@types/styled-components.d.ts`

**Comment by shopkins131** [comment]
If you are using styled-components together with Material UI 

`
import { Theme } from "@material-ui/core";

declare module 'styled-components' {
  export interface DefaultTheme extends Theme
}
`

didn't need anything in the compiler options in tsconfig.json

thanks @kettanaito!

**Comment by meissam** [comment]
Hi Guys. 
when I configured my theme based on the documentation, the vs code's autocompleting functionality works like a charm when I'm using "createGlobalStyle" and "css" modules. when I use "styled" it doesn't work. do you have experienced this strange behaviour before? 
![01](https://user-images.githubusercontent.com/69047033/120334797-3157f480-c306-11eb-8803-8ff1634c1e85.png)
![02](https://user-images.githubusercontent.com/69047033/120334815-34eb7b80-c306-11eb-9e0a-feec69f78f9a.png)

**Comment by chordmemory** [comment]
> Hi Guys.
> when I configured my theme based [on the documentation](https://styled-components.com/docs/api#create-a-declarations-file), the vs code's autocompleting functionality works like a charm when I'm using "createGlobalStyle" and "css" modules. when I use "styled" it doesn't work. Have you experienced this strange behaviour before?
> ![01](https://user-images.githubusercontent.com/69047033/120334797-3157f480-c306-11eb-8803-8ff1634c1e85.png)
> ![02](https://user-images.githubusercontent.com/69047033/120334815-34eb7b80-c306-11eb-9e0a-feec69f78f9a.png)

I had the opposite problem, `styled` working fine, `createGlobalStyle` was not.

I fixed it by providing an empty type in the props generic field where the props were not specified before:

```js
createGlobalStyle<{}>`
  background: ${props => props.theme.color.background}
`
```

Might be worth trying for `styled` to see if it fixes your issue. Weird behavior.

**Comment by danksch** [comment]
Any solution for _styled_ tag not working with theme or props in general ? If tried all of the above and none is working, unfortunately.

**Comment by PhilVargas** [comment]
> I think a proper way to type annotate your theme is to create a custom `styled-components.d.ts` (name matters not) and extend the "styled-components" module.
> 
> ```ts
> // src/theme.ts
> export default {
>   colors: {
>     black: '#000'
>   }
> }
> ```
> 
> ```ts
> // ./styled-components.d.ts
> import theme from './src/theme'
> 
> type CustomTheme = typeof theme
> 
> declare module 'styled-components' {
>   export interface DefaultTheme extends CustomTheme {}
> }
> ```
> 
> Make sure to include this file in your `tsconfig.json`:
> 
> ```json
> {
>   "compilerOptions": {
>     "includes": ["styled-components.d.ts"]
>   }
> }
> ```

Has anyone gotten this to work with react hooks?

```
const theme = useTheme()
```

type of theme is the empty object DefaultTheme, not my extended CustomTheme.

**Comment by LeandrodeLimaC** [comment]
I'm experiencing a similar issue in my monorepo structure, which consists of two packages: "themes" and "components". Both of these packages are part of our company's design system.

Inside the "components" package, the DefaultTheme works perfectly when using styled('div'). However, the problem arises when I install this package in another application, as the expected type declarations are missing. Does anyone have any suggestions?

Here are some additional details:

I'm exporting the styled function so that users can create components with the theme.
The values in the theme, such as theme.colors.primary, are accessible and functional, but the type information is missing.
During compilation, an index.d.ts file is generated, but I cannot find the DefaultTheme that I created. Instead, I only see the default theme that comes with styled-components. I believe this might be the cause of the problem, but I haven't found a solution yet.
The versions I'm using are tsup 6.7.0, React 18, styled-components 6.0.0-rc.1, and TypeScript 5.0.2.
Here's an overview of my file structure:

The node_modules directory is located at the root of my repository, so I have to reference it using '../../node_modules/'.

```
// src/@types/styled.d.ts

import 'styled-components'
import { Theme } from '../styles/theme'

declare module 'styled-components' {
  export interface DefaultTheme extends Theme {}
}
```

```
// src/styles/theme.ts

import { brandName } from '@myCompany/themes'

const theme = { ...brandName }

export type Theme = typeof theme
export default theme
```

```
// tsconfig.json
{
  "compilerOptions": {
    "typeRoots": [
      "../../node_modules/@types",
      "./src/@types"
    ],
    "types": ["./src/@types/styled"]
  },
  "include": [
    "src",
  ]
}
```

**Comment by richard-lopes-ifood** [comment]
I understand that the current way works like this, but isn't there a better, less obscure way to strongly type it?

**Comment by Remi-Tribia** [comment]
Interface merging

**Comment by mobeigi** [comment]
Hi everyone,

I am following the steps from the documentation:
```
import 'styled-components';
import { DefaultThemeOverride } from '@/types/theme';

declare module 'styled-components' {
  export interface DefaultTheme extends DefaultThemeOverride {}
}
```

I manage to get auto complete working with no issues.

My problem is that the typing seems incorrect for the top level. So if you try to access a property that does not exist at the top level, it gladly accepts it due to the type of `theme` being:
```
export interface DefaultTheme {
    [key: string]: any;
```

Here is observed behaviour:
```
export const StyledDiv= styled.div`
  display: flex;

  // Example
  ${({ theme }) => theme}; // OK
  ${({ theme }) => theme.doesnotexist};  // No error here when there should be
  ${({ theme }) => theme.breakpoints}; // OK
  ${({ theme }) => theme.breakpoints.doesnotexist}; // Typescript throws proper error here
 }
```

If I add `noPropertyAccessFromIndexSignature: true` to my `tsconfig.json` `compilerOptions` then it does throw the error as expected but I don't understand why that would be needed since I should have overridden the type on `theme` completely, why does it seem to type it as the original type declaration.

Any ideas?

**Comment by LeandrodeLimaC** [comment]
> Hi everyone,
> 
> I am following the steps from the documentation:
> 
> ```ts
> import 'styled-components';
> import { DefaultThemeOverride } from '@/types/theme';
> 
> declare module 'styled-components' {
>   export interface DefaultTheme extends DefaultThemeOverride {}
> }
> ```
> 
> I manage to get auto complete working with no issues.
> 
> My problem is that the typing seems incorrect for the top level. So if you try to access a property that does not exist at the top level, it gladly accepts it due to the type of `theme` being:
> 
> ```ts
> export interface DefaultTheme {
>     [key: string]: any;
> ```
> 
> Here is observed behaviour:
> 
> ```ts
> export const StyledDiv= styled.div`
>   display: flex;
> 
>   // Example
>   ${({ theme }) => theme}; // OK
>   ${({ theme }) => theme.doesnotexist};  // No error here when there should be
>   ${({ theme }) => theme.breakpoints}; // OK
>   ${({ theme }) => theme.breakpoints.doesnotexist}; // Typescript throws proper error here
>  }
> ```
> 
> If I add `noPropertyAccessFromIndexSignature: true` to my `tsconfig.json` `compilerOptions` then it does throw the error as expected but I don't understand why that would be needed since I should have overridden the type on `theme` completely, why does it seem to type it as the original type declaration.
> 
> Any ideas?


You can find the reason why here: https://learntypescript.dev/04/l4-interfaces#declaration-merging

> It is legal in TypeScript for multiple interfaces with the same name to be created. TypeScript will merge interfaces with the same name in a process called declaration merging.

```typescript
interface A {
  a: string
}

interface A {
  b: string
}

// will result in interface `A` having both `a` and `b`
```

So, in your example you have something like this
```typescript
import 'styled-components';
import { DefaultThemeOverride } from '@/types/theme';

declare module 'styled-components' {
  // This is what came by default inside styled-components module
  export interface DefaultTheme {
    [key: string]: any;
  }

  // This is what you added
  export interface DefaultTheme extends DefaultThemeOverride {}
}
```

**Comment by mobeigi** [comment]
@LeandrodeLimaC Good to know, thanks for sharing! Is there a way to disable this behaviour in this case or override the interface without keeping the previous declaration of it? That was typescript would properly warn me if I tried to use a property that didn't exist on my type.

**Comment by Igornorlin** [comment]
@mobeigi Had the same issue for our React Native project. This should fix the issue.

```js
export interface ThemeInterface { // Does not contain type for the top property: colorPrimary (see last snippet)
  spacers: {
    basePadding: number
    devicePaddingWidth: number
  }
  colors: Colors
  font: typeof Font
  isDarkMode: boolean
  radius: typeof radius
  shadows: typeof shadows
  sizes: typeof sizes
  spacing: typeof spacing
}
```

In your `styled.d.ts` or whatever your type file is called. Doesn't matter.

```js
import 'styled-components/native'

import { ThemeInterface } from '~/theme/tokens'

declare module 'styled-components/native' {
  export interface DefaultTheme extends ThemeInterface {}
  export const useTheme: () => ThemeInterface
}
```

If you are using web


```js
import 'styled-components'

import { ThemeInterface } from '~/theme/tokens'

declare module 'styled-components' {
  export interface DefaultTheme extends ThemeInterface {}
  export const useTheme: () => ThemeInterface
}

```

and then just use

```js
import { useTheme } from 'styled-components'

const FunctionalComponent = () => {
  const theme = useTheme()

  const shouldGiveTypescriptError = theme.colorPrimary // Does not exist as top property in the ThemeInterface
}
```
