### ISSUE TITLE
SSR StyleSheetManager error "styleSheet.hasNameForId is not a function"

### ISSUE THREAD

**Issue by LennardWesterveld** [styled-components/styled-components#1591]
## System:
 - OS: macOS High Sierra 10.13.3
## Binaries:
 - Node: 9.4.0
 - npm: 5.6.0
 - Watchman: Not Found
 - Docker: 18.02.0-ce, build fc4de44
 - Homebrew: 1.5.4
### babel-plugin-styled-components:
 - wanted: ^1.5.1
 - installed: 1.5.1
### styled-components:
 - wanted: ^3.2.1
 - installed: 3.2.1

## Reproduction
```  // Styled components
  const sheet = new ServerStyleSheet();

  // Declare our React application.
  const app = (
    <Provider {...mobxStore}>
      <StaticRouter location={request.url} context={reactRouterContext}>
        <StyleSheetManager sheet={sheet}>
          <App />
        </StyleSheetManager>
      </StaticRouter>
    </Provider> );

    const appString = renderToString(app);
    const styleTags = sheet.getStyleElement();

    const html = renderToNodeStream(
      <Html
        manifest={manifest}
        reactAppString={appString}
        helmet={Helmet.rewind()}
        initialState={initialState}
        styleTags={styleTags} />
    );

  );
```

## Error message
```TypeError: styleSheet.hasNameForId is not a function
    at ComponentStyle.generateAndInjectStyles (...node_modules/styled-components/dist/styled-components.cjs.js:1975:23)
    at StyledComponent.generateAndInjectStyles (...node_modules/styled-components/dist/styled-components.cjs.js:1672:40)
    at ...node_modules/styled-components/dist/styled-components.cjs.js:1703:43
    at subscribe (...node_modules/styled-components/dist/styled-components.cjs.js:1441:5)
    at StyledComponent.componentWillMount (...node_modules/styled-components/dist/styled-components.cjs.js:1700:30)
    at ...node_modules/react-tree-walker/commonjs/index.js:145:22
    at doTraverse (...node_modules/react-tree-walker/commonjs/index.js:78:21)
    at doVisit (...node_modules/react-tree-walker/commonjs/index.js:116:9)
    at ...node_modules/react-tree-walker/commonjs/index.js:142:9
    at new Promise (<anonymous>)
    at reactTreeWalker (...node_modules/react-tree-walker/commonjs/index.js:70:10)
    at mapper (...node_modules/react-tree-walker/commonjs/index.js:88:29)
    at ...node_modules/react-tree-walker/commonjs/index.js:52:28
    at ...node_modules/react-tree-walker/commonjs/index.js:38:14
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)````

**Comment by kitten** [comment]
This sounds like you might have multiple installations of styled-components. Are your components maybe using a newer version than your server-side code?

Because `hasNameForId` is a method that was introduced on the stylesheet after the refactor.

**Comment by LennardWesterveld** [comment]
node_modules is shared while compiling for client and server-side. I also deleted the whole node_modules folder and reinstalled everything but didn't help.

**Comment by flybayer** [comment]
I'm having a similar problem (different name, similar stack trace). Happened after upgrading from 3.1.6 to 3.2.x.

I figured out it's because I use `system-components` which has `styled-components` as a dependency at 3.1.6.

**Comment by kitten** [comment]
@flybayer that is indeed a potential problem, since `peerDependencies` should be used in that case in `system-components`. However, it says `>=3.0.0` so I'm not sure why that isn't being applied completely in your case https://github.com/jxnblk/styled-system/blob/master/system-components/package.json#L25

@LennardWesterveld Sorry, I just noticed that you have a mistake in your code.

```js
  const sheet = new ServerStyleSheet();

  // Declare our React application.
  const app = (
    <Provider {...mobxStore}>
      <StaticRouter location={request.url} context={reactRouterContext}>
        <StyleSheetManager sheet={sheet}>
```

`sheet` here is supposed to be `sheet.instance`; Or just use our `collectStyles` method. Please read the docs carefully and try whether that works:

https://www.styled-components.com/docs/advanced#server-side-rendering

Questions like these which haven't been properly debugged are more suited for spectrum or stackoverflow btw.

**Comment by LennardWesterveld** [comment]
I know i did also try that, but didn't work i searched for a example in this repo and found this one that why i tried that: https://github.com/styled-components/styled-components/blob/1585570a1b44739732dcdb895a51caa04263604d/typings/tests/server-test.tsx

A fine, i thought it was a issue/bug because i did have it working with the previous version.
