### ISSUE TITLE
"Several instance" warning while running tests with Jest

### ISSUE THREAD

**Issue by AlexMeah** [styled-components/styled-components#1592]
When using jest's auto mock with styled-components we are seeing the "Several instance" warning.

Example repo here: https://github.com/AlexMeah/sc-jest-bug
Test file with the issue: https://github.com/AlexMeah/sc-jest-bug/blob/master/src/components/Comp2/test.js

Run `yarn test` to reproduce.

I think this is probably a symptom of how jest handles mocking, however you might want to warn users to avoid wasted time debugging.

**Comment by kitten** [comment]
cc @MicheleBertoli: I think this is indeed problematic. Is this something we can work around, or do we need to find a way to disable the warnings in Jest entirely?

**Comment by probablyup** [comment]
If we need to disable them, we can put a guard like `process.env.NODE_ENV
!== “test”`

**Comment by kitten** [comment]
@probablyup I think we've now seen that we can't rely on `NODE_ENV` in Jest or similar test environments as they're pretty configurable and flexible

**Comment by probablyup** [comment]
Jest sets that one itself, so it should be ok.

**Comment by mxstbr** [comment]
Yeah that should be fine imo

**Comment by MicheleBertoli** [comment]
Another option would be checking if the DOM is provided by [jsdom](https://github.com/jsdom/jsdom), like:
`navigator.userAgent.includes("Node.js") || navigator.userAgent.includes("jsdom")`
Source: https://github.com/jsdom/jsdom/issues/1537
What do you think?

**Comment by kitten** [comment]
@mxstbr I've seen some ppl launch jest using `NODE_ENV=production`, but since that leads to more issues, maybe we should not support that?

@MicheleBertoli that's actually quite a brilliant alternative.

Any thoughts?

**Comment by MicheleBertoli** [comment]
I confirm that running tests in the `production` env is a common practice, for example [React](https://github.com/facebook/react/blob/master/package.json#L114) does that.
Since the issue is due to side-effects of importing this package, I would go with the jsdom fix.

**Comment by probablyup** [comment]
This would work only in the non SSR use case. If you’re running jest with jest-environment node then JSDOM isn’t present and navigator won’t be defined. 

So maybe we can do both approaches at once?
