### ISSUE TITLE
Rename the repos to shorter versions?

### ISSUE THREAD

**Issue by wmertens** [styled-components/styled-components#1597]
The org and repo together are very long, and email notifications have no useful title on mobile because of that.

I wonder if they can't be renamed to stld-cmps/stld-cmps or even s-c/s-c?

Just wondering out loud :)

**Comment by mxstbr** [comment]
Probably not :blush:

**Comment by kitten** [comment]
Agreed, styled-components has become a “household name” and at this point it’d be disastrous to go for a hackt workaround to shorten the name :/
