### ISSUE TITLE
CSS rules are accumulated when doing SSR with styled-components@3.2.0^

### ISSUE THREAD

**Issue by DeividasK** [styled-components/styled-components#1602]
## Environment
# System:
 - OS: macOS High Sierra 10.13.3
 - CPU: x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
 - Free Memory: 409.59 MB
 - Total Memory: 16.00 GB
 - Shell: /bin/zsh - undefined
## Binaries:
 - Node: 8.9.4
 - Yarn: 1.5.1
 - npm: 5.6.0
 - Watchman: Not Found
### styled-components:
 - wanted: ^3.2.1
 - installed: 3.2.1

## Reproduction

Couldn't think of a nice way to reproduce this without creating a SSRed app with multiple entry points, which would have different styles.

Current relevant parts of the setup

````js
async function renderHtmlDocument({ history, store, sagasDone, webpackStats }) {
  // 1st render phase - triggers the sagas
  renderToString(<Main history={history} store={store} />);
  // send signal to sagas that we're done
  store.dispatch(END);
  // wait for all tasks to finish
  await sagasDone();

  // capture the state after the first render
  const state = store.getState();

  // taken straight out of documentation
  const sheet = new ServerStyleSheet();
  // 2nd render phase - the sagas triggered in the first phase are resolved by now
  const appMarkup = renderToString(
    sheet.collectStyles(<Main history={history} store={store} />)
  );

  const css = sheet.getStyleTags();
  const { cssHash, js, styles } = flushChunks(webpackStats, {
    chunkNames: flushChunkNames(),
  });

  const head = Helmet.rewind();

  return `<!DOCTYPE html>
  <html lang="en" ${head.htmlAttributes.toString()}>
    <head>
    ...
    <!-- Inlined first render css -->
    ${css}
   ...
  </head>
  <body>
    ...
  </body>
</html>`;
}
````

## Steps to reproduce
- SSR a page.
- Navigate to any other page. Do a refresh so that the page is SSR'ed.
- Go back to the previous page and SSR it.

## Expected Behavior
index.html file should not include CSS rules for other pages that were SSR'ed. Quick way to check this is if index.html file is of the same size.

## Actual Behavior
index.html file includes CSS rules for other pages that were SSR'ed (it visibly increases in size).

I can reliably reproduce this on our site by installing styled-components@3.2.0 or above. styled-components@3.1.6 works fine with the same setup. The issue described above leads to index.html becoming so big (140kb+) that it takes 20s+ for the browser to parse it, which often crashes a mobile browser.

I hope there's something immediately obvious that you guys changed from 3.1.6 to 3.2.0 that led to this behaviour, but if not, let me know if you need more info.

**Comment by mxstbr** [comment]
@kitten this sounds like a bug in your StyleSheet rewrite

**Comment by mxstbr** [comment]
Any news @kitten? Any hunches why this happens?

**Comment by kitten** [comment]
@mxstbr didn’t have any time yet to take a look :) also have to build a reproduction but since I’ll be more busy in the coming days, I’ll have to find a free evening to work on this

**Comment by kitten** [comment]
Had a quick look; I think I messed up ServerTag#clone; I’ll push a fix this eve

**Comment by kitten** [comment]
@DeividasK Hiya, pushed out a quick fix since this wasn't too complex to fix and just a messup 😅 Can you help me test the fix please? It's published as `
v3.2.2-0` under `styled-components@dev`

**Comment by simonkberg** [comment]
FWIW, the `v3.2.2-0` release resolves an issue with snapshot tests that I was just about to report :sweat_smile: (all styles were disappearing from nested components). So I assume jest-styled-components is also affected by this.

**Comment by DeividasK** [comment]
@kitten Hey Phil, I've checked it and it does not fix the issue.

**Comment by kitten** [comment]
@DeividasK sorry, I'm really under the weather today; I've messed up one of the clone functions again — let me push out another commit and prerelease;

**Comment by DeividasK** [comment]
@kitten sorry for taking a bit to respond, but I wanted to double check this - it seems that the styles rules are still being accumulated (based on the increasing index.html size). I will double check the actual output of styled-components tomorrow and will let you know.

**Comment by kitten** [comment]
@DeividasK that might just be our component comment markers. If so, I’m aware of that regression but it’s intended as long as we’re waiting for some ppl who’re relying on that (not for SSR)

**Comment by kitten** [comment]
@DeividasK v3.2.2 is now released with the fix in place :) https://github.com/styled-components/styled-components/releases/tag/v3.2.2

**Comment by bringking** [comment]
@kitten We are seeing this leak in our prod servers at Weedmaps. We just hotfixed to update to 3.2.2 and I think we are still seeing similar behavior. Here is a snippet from a heap dump - 

<img width="1318" alt="screen shot 2018-03-13 at 7 03 13 pm" src="https://user-images.githubusercontent.com/864845/37379579-670bb0f8-26f1-11e8-82fc-1704904f3242.png">
<img width="1324" alt="screen shot 2018-03-13 at 7 02 59 pm" src="https://user-images.githubusercontent.com/864845/37379583-6ae972e6-26f1-11e8-8ba1-4450247650e7.png">

Environment - 
Alpine Linux 3.7.0
Styled Components - 3.2.2

Node - 9.7.0
Express - 4.16.3
NextJS - 5.0.0

We are using the following method to collect our styles (basically the example from the NextJS repo)

```

export class DeliveriesDocument extends Document {
  static async getInitialProps({ renderPage, req }) {
    const sheet = new ServerStyleSheet();
    const page = renderPage(App => props =>
      sheet.collectStyles(<App {...props} />),
    );
    const styleTags = sheet.getStyleElement();
    return {
      ...page,
      styleTags,
    };
  }

  render() {
    const { styleTags } = this.props;
    return (
      <html lang="en">
        <Head>
          {styleTags}
        </Head>
        <body>
          <Main />
          <NextScript />
        </body>
      </html>
    );
  }
}

```

**Comment by bringking** [comment]
@kitten we aren't seeing the accumulated styles being flushed into the DOM, but it seem they are still being retained

**Comment by boxman0617** [comment]
@kitten I see `clones, deferred, tagMap` grow

**Comment by bringking** [comment]
@kitten I have not dug into styled-components source too much, but debugging your tests, I see you assert that the generated style tags do not bleed over, however I am seeing the `tagMap` instance on the Stylesheets contains two values for each Sheet, when it should contain 1. If I comment out `SheetB`, then `SheetA` only contains 1 tag in the `tagMap` - Debugging done on the test here - https://github.com/styled-components/styled-components/pull/1605/files#diff-ff4f58ec4bfe127b48d620e3f45853e5R68

**Comment by kitten** [comment]
@bringking yep, that’s all still expected behaviour and as it worked before. At any point in time we need to preserve the order of components that were created.

If you’re seeing a growing tagMap that just means that you’re encountering new components over time. We can probably optimise this in the future, but for now please open a new issue if this really bothers you, as this was how it already worked pre-3.2 ;)

**Comment by DeividasK** [comment]
@kitten I can confirm that 3.2.2 works the same way as 3.1.6. As you've mentioned, some markers are being accumulated, but that is the same behaviour as in 3.1.6.

**Comment by bringking** [comment]
@kitten @DeividasK, thanks for the info we will keep digging. We are still seeing rapid memory growth with 3.2.2, but I want to get a solid repro case for you and I will open another issue if it is something in styled-components. Thank you guys!

**Comment by kitten** [comment]
@bringking @DeividasK I've got an easy modification here, which I was aware would help with this but left out during the refactor to keep everything the same.

https://github.com/styled-components/styled-components/pull/1612

It's published under the `ssrmem` tag. Can you two take a look at that PR, test the prerelease and report whether it improves the situation please? 👍🙌 

I'll lock this issue for now, so that no one gets your discussion confused with the original issue :wink: Sorry about that, let's move the discussion to the PR
