### ISSUE TITLE
Add bundles that switch off insertRule/speedy mode while maintaining a prod env

### ISSUE THREAD

**Issue by pekala** [styled-components/styled-components#1603]
There is a genre of tracking software which "records" actions that the user takes on the page and allows to replay the session later for behavior analysis. Some examples: Crazy Egg, ClickTale, Mouseflow, Inspectlet, Lucky Orange, HotJar, Mousestats, Navilytics.

The way they work usually is by listening to all DOM events and changes to the DOM and sending that over the wire. As creepy as this is, it's quite useful and actually works quite well for most websites and web apps.

Unfortunately, since the recent introduction of the `insertRule`-backed "speedy mode", apps that use styled-components production bundle are not compatible with these user recording tracking services. `insertRule` essentially bypasses the DOM so for the tracker these styles are invisible.

I can't really think of a way to get both the performance boost from `insertRule` and still support these trackers. As I understand, there is currently no way to disable the "speedy mode" in production, and it seems like the right choice. There might be however value in providing an alternative bundle to address this issue as well as the "read-only"ness of the `insertRule` styles ([this was suggested by @kitten on Twitter](https://twitter.com/_philpl/status/973265736876490753)).

I mostly wanted to open this issue to document that this use case is not supported for people that come across this issue in the future.

**Comment by kitten** [comment]
So summing this up, we might want to add another bundle option that switches off insertRule while keeping the prod env optimisations;

cc @probablyup @mxstbr: Thoughts? I think adding this wouldn't really hurt

**Comment by pekala** [comment]
I also asked Hotjar support about this issue, and they are away of it. 

```
Unforuntately, at this time Hotjar does not support styles applied with insertRule() as we look for mutations in the DOM and the insertRule() creates blank <style> elements that we are unable to track.

At this time, the only workaround we have is to downgrade styled-components and unfortunately lose the newly found performance optimizations.

We are definitely aware of this issue and are currently investigating how to support it. It should not affect your use of other Hotjar tools.
```

If this kind of tools can figure out support for `insertRule` then maybe making that separate bundle is not needed. But I'm not sure if it's technically possible to extract these styles.

**Comment by tabrindle** [comment]
@kitten I think we talked about doing something similar back in https://github.com/styled-components/styled-components/issues/1497 - basically a way to switch off speedy in production for debugging or places where it's not supported.

**Comment by kitten** [comment]
@tabrindle yes, the difference here is that the idea would be to add a separate bundle; It'd achieve the same thing but would be less controversial, as in it doesn't have any implications for our API

**Comment by jaggli** [comment]
**Disclaimer: this is a hack, you've been warned**

After some intense trial and error, I ended up by just synchronising the grabbed styles into the beginning of the `<head>` tag, so the following 'real' ones still can override everything. Synchronization is done twice per second by using getAnimationFrame(), so this might result in a style-update delay in Hotjar recordings of max 500ms, which we are ok with.

Check out the first file in [this gist](https://gist.github.com/jaggli/5b2141c60cef3095a51661bac96de183#file-1_hotjarfix-js) 

The second file is an failed attempt to send fake mutations along the real ones, because Hotjar records mutations.

**Comment by harshmaur** [comment]
Is there any update on this? Or shall I downgrade styled-components to make it work?

**Comment by probablyup** [comment]
@harshmaur not at the moment - I'd go ahead and downgrade until we have a more evolved strategy.

**Comment by pie6k** [comment]
![image](https://user-images.githubusercontent.com/7311462/39119272-bbb616a6-46eb-11e8-96ab-e5b1a71ca1a1.png)

Yup. Upgrading `styled-components` has broken all our analytics services for session recordings.

We've contacted support service of our analytics service and response was: `Your site is using Javascript API called insertRule. Our tracking tools is not able to capture these styles as they exist neither in a CSS stylesheet we can fetch or in the actual DOM of the page`

**Comment by harshmaur** [comment]
@pie6k Just downgrade your styled-components as of now.

**Comment by GazzaHazza** [comment]
@harshmaur What version did you downgrade to?

**Comment by harshmaur** [comment]
`3.0.1`

**Comment by GazzaHazza** [comment]
@harshmaur Thanks

**Comment by pkrisz89** [comment]
We have slightly altered @jaggli's gist so have a workaround which can be used without downgrading styled-components. https://engineering.brighthr.com/blog-posts/hotjar-styled-components-fix/

**Comment by stephenpitchford** [comment]
This shouldn't be a problem with the Hotjar tracking anymore. An update was released that allows the script to deal with styles added using insertRule.

**Comment by pkrisz89** [comment]
@stephenpitchford Did you release the update recently? Just because it was not working for us yesterday.

**Comment by stephenpitchford** [comment]
@pkrisz89 The change was released earlier today.
