### ISSUE TITLE
Styled Components naming convention

### ISSUE THREAD

**Issue by daviddelusenet** [styled-components/styled-components#1604]
**Hello everyone!**

Recently I've been using Styled Components for a React application I'm building. Everything is going well so far.

However, I do have some questions regarding the **naming convention of Styled Components**. Let me give an example. The following code is actual code I've written for my project.

I've a `ProductDetail` component which has an `Image` subcomponent.

```
// Styled Components
import ProductDetailWrapper from './ProductDetail.sc';

// Child Components
import Image from './Image/Image';
import Information from './Information/Information';

export default class ProductDetail extends React.Component {
  // Some stuff here

  render() {
    const { imageURL, information, nextImageURL, showVariants, variants } = this.props;
    const HasVariants = variants.length > 0;

    return(
      <ProductDetailWrapper>
        <Information {...information} />
        <Image imageURL={imageURL} nextImageURL={nextImageURL} variantsAreBeingShown={HasVariants && showVariants} />
      </ProductDetailWrapper>
    );
  }
}
```

In this project every component has another file where I define all my Styled Components. So in this case the filename is `ProductDetail.js` and the Styled Components are inside of `ProductDetail.sc.js`.

This brings me to my first issue: in an ideal world I would like to name my *wrapper* component the same as the class itself. However, this of course isn't possible since you can't have a component name which is the same as the class name.

That's why I decided to go with `class + Wrapper` naming. In this case that leads to my `ProductDetailWrapper` name.

Now lets take a look at my `Image` subcomponent:

```
// Styled Components
import { Image, ImageWrapper } from './Image.sc';

export default class ProductDetailImage extends React.PureComponent {
  // Some stuff here

  render() {
    const { variantsAreBeingShown } = this.props;
    const { imageURL } = this.state;

    return(
      <ImageWrapper variantsAreBeingShown={variantsAreBeingShown}>
        <Image innerRef={ref => this.image = ref} onLoad={this.imageIsLoaded} src={imageURL} />
      </ImageWrapper>
    );
  }
}
```

This component illustrates another issue I've been facing regularly: I want to call my class `Image`. However, the component itself already has a Styled Component called `Image` so I can't do that. That's why I resorted to calling the class `ProductDetailImage` (since it's a subcomponent of the `ProductDetail` component).

I would like to know **your thoughts** about this. Do you like my solutions or would you do it differently? Are there already a (better) naming conventions defined?

**Thanks in advance!**

**Comment by diondiondion** [comment]
> That's why I decided to go with class + Wrapper naming. In this case that leads to my ProductDetailWrapper name.

Why not just call it `Wrapper`, without being extra specific? If you use babel-plugin-styled-components, your class name will then be `ProductDetail_Wrapper`.

That's one of the nice things about styled-components: you don't really have to worry about naming all that much.

As to your next example:
> This component illustrates another issue I've been facing regularly: I want to call my class Image. However, the component itself already has a Styled Component called Image so I can't do that.

You could give your component another name during the import:
`import { Image as StyledImage, ImageWrapper } from './Image.sc';`

But if I was you I'd probably call the Image component StyledImage or StyledImg to begin with.

It's hard to generalise this advice as it depends a lot on your project's setup and how re-usable you want your components to be. The more reusable, the less you'll want to rely on contextual/descriptive information to identify components, and the more you should name components according to their role or functionality.

**Comment by diondiondion** [comment]
By the way, I think this is quite an interesting discussion, but it's not really an "issue" with styled-components. Would be a good fit for a topic in styled-component's Spectrum channel: https://spectrum.chat/styled-components

**Comment by daviddelusenet** [comment]
@diondiondion thanks for your response!

At the moment I'm not using `babel-plugin-styled-components` but I'm definitely gonna add it to my project today.

I went with `ProductDetailWrapper` to add some context to the render function. Almost every component I build so far starts with a wrapper component. If I would just all call them `Wrapper` it would be hard to distinguish which component you're looking at when seeing the render function.

However, I do think I still might refactor everything to just `Wrapper` to be consistent with the rest of my naming. You can always just check the filename to see which component you're looking at 😏.

And I really like the solution you gave here, didn't even think about it:

`import { Image as StyledImage, ImageWrapper } from './Image.sc';`

This way I can at least keep my class naming consistent through out the project.

Still curious about other people's opinions tho so keep them coming!

**Comment by danielrob** [comment]
Hello @daviddelusenet I'd be interested in your take on my approach of avoiding having to name the wrappers elements altogether! 

https://www.npmjs.com/package/styled-as-components

**Comment by joaoreynolds** [comment]
Even though this is closed, I think this is a logical place for this discussion (and I couldn't find a thread on spectrum about this). All I could find there (and via google) are discussions about styled components and BEM - but BEM is not really needed, as you've mentioned, classes aren't global with styled-components.

When I first started my project, I created a wrapper for everything, as suggested. But when using chrome devtools, I saw a whole bunch of `Wrapper` classes, which made it really hard to debug (especially since sourcemaps aren't supported see: )

So then I went with `ComponentName`+`View`. Just like what you've been doing. It works, but, like you, I'd like to know what approach others are taking.

![image](https://user-images.githubusercontent.com/1928724/39204540-47762db0-47b5-11e8-9def-61d051baca8e.png)

**Comment by ben-rogerson** [comment]
After finished a few smaller projects with Styled Components I'm keen to hear some more opinions on this too.

**Some of my thoughts:**
- A naming prefix for the styled components could be a good solution. Eg: styledImage, styledWrapper
- They have to be immediately recognisable as a styled-component, and not be confused with a component-component :)
- It would be great to cut down on the number of 'wrappers'
- Your styled components should really be reusable across your project - this means a naming convention that 'groups' it with the component may not be the best idea

**Comment by joaoreynolds** [comment]
Just today I ended up converting a styled component into a "component component". The nice thing was that I didn't have to rename all my instances, which I'd have to do if I named it `StyledWrapper` for example. I don't know if this is really an argument for or against your method, because I could have just as easily wrapped the original styled component in my own new component (just as I would have done before `styled-components` came along.

**Comment by reinseth** [comment]
The old pluggable look and feel concepts from Swing springs to mind. Components delegate the job of creating the actual user interface to UI classes. For example, a JButton uses an implementation of ButtonUI.

**Comment by dccarmo** [comment]
@daviddelusenet In your example, are `Text` and `Image` styled-components or are they the RN ones?

**Comment by daviddelusenet** [comment]
@dccarmo just normal Styled Components.

**Comment by sami616** [comment]
i tend to have a `styled` folder with an index file that exports all of my styled components.

Then in the component i want to use it in i can `import * as SC from './styled'`

And use like this: `<SC.Image />`

This helps me avoid naming collisions with real components.

**Comment by vgrynch** [comment]
Maybe its a little bit late, but I found out this great article about naming conventions for styled components:
https://medium.com/inturn-eng/naming-styled-components-d7097950a245

**Comment by ben-rogerson** [comment]
Great, thanks for sharing 🙏

**Comment by myleftshoe** [comment]
This gets more complicated when you throw react-pose/popmotion into the mix. This is what I am trialing:

```
const toast = {};

toast.style = styled.div`
    background-color: #0003;
    margin: 4px 12px 4px 8px;
    padding-bottom: 8px;
`

toast.pose = posed(toast.style)({
    enter: { opacity: 1, delay: 300 },
    exit: { opacity: 0 }
});

const Toast = toast.pose
```

The usable component is <Toast/> which can be set to either toast.style or toast.pose. The lower case T of toast.style and toast.pose is an indication that  they should not be used as a react components in themselves.

**Comment by jiangqizheng** [comment]
Can consider to BEM, similar to [https://tech.decisiv.com/structuring-our-styled-components-part-i-2bf21fa64b28](https://tech.decisiv.com/structuring-our-styled-components-part-i-2bf21fa64b28)

**Comment by siunegu** [comment]
> i tend to have a `styled` folder with an index file that exports all of my styled components.
> 
> Then in the component i want to use it in i can `import * as SC from './styled'`
> 
> And use like this: `<SC.Image />`
> 
> This helps me avoid naming collisions with real components.

You lose treeshaking in webpack if you do this though
