### ISSUE TITLE
3.2 strips out external constants

### ISSUE THREAD

**Issue by dangodev** [styled-components/styled-components#1607]
Using Create React App and Styled Components 3.2, trying to access in-scope constants fails:
```js
const blue = 'blue';
const white = 'white';

const Styled = styled.div`
  background-color: ${white};
  color: ${blue};
`
```

Gets compiled to:
```js
background-color: ","; color: ",";
```

Is this intentional behavior?

## Reproduction
Simplified repo: https://github.com/dangodev/sc-test

**Comment by kitten** [comment]
Haven't checked your repro, but as you can see on CodeSandbox here, it works as intended: https://codesandbox.io/s/xrzm91j8mq

**Comment by dangodev** [comment]
Hi @kitten, thanks so much for looking into this!

I forgot to copy a critical part of the reproduction instructions here: **running `yarn build`**. This issue only happens:

- In Styled Components 3.2
- While running `yarn build` or `npm run build` (whatever the build script is to generate production-ready code)

This works fine in dev/sandbox mode, but when building Styled Components, the issue happens.

I did find this isn’t a Create React App thing; I was able to reproduce using stock webpack here:https://github.com/dangodev/sc-test-2

**Comment by kitten** [comment]
@dangodev Just checked your repro and it all works fine, but I've noticed that you might have misunderstood the template literals :)

> Inspect the built JS file to find background-color: ",";\n color: "," rather than the expected values.

Those are the expected values; The tagged template literals has the structure of: `styled.x(string[], ...interpolations[])`

Check out the CSS in your build and you will see that all is well. You can find more information about tagged template literals in our docs: https://www.styled-components.com/docs/advanced#tagged-template-literals

**Comment by dangodev** [comment]
@kitten thanks for the explanation! You’re right.

I’m trying to track down a bug where Styled Components really _are_ not building properly, and styles are missing in production, and it is happening in 3.2. But it seems like this was a red herring as to the real problem in our production app 😅 , and I can’t say it’s not Styled Components and not some other conflict in our build process.

Thanks again!

**Comment by kitten** [comment]
@dangodev 

> and styles are missing in production

This might be related to the following issue: https://github.com/styled-components/styled-components/issues/1576

It'll be fixed in the next patch and is an underlying issue in stylis; The only way to debug it would be to look at what's actually injected using `insertRule`;

The bug would affect all at-rules that are nested inside style rules, so have a look at those; You can already check whether the next patch will fix your bug since I've got a prerelease ready. It's `3.2.2-1` under the `@dev` tag

**Comment by dangodev** [comment]
@kitten Yup! That was our issue! Just tried that release and that fixed our missing styles. Thanks again!

**Comment by kitten** [comment]
fyi v3.2.2 is now released with this fix :wink: https://github.com/styled-components/styled-components/releases/tag/v3.2.2

**Comment by dangodev** [comment]
@kitten Awesome! Thanks for all the work you do. The development community doesn’t deserve the Styled Components team! We’re not worthy!

![we’re not worthy](https://media.giphy.com/media/MUeQeEQaDCjE4/giphy.gif)
