### ISSUE TITLE
Add support for postcss-responsive-properties

### ISSUE THREAD

**Issue by alexandr-solovyov** [styled-components/styled-components#1608]
Hey, there! I have a suggestion for the way how to improve writing of responsive `styled-components`. It seems, that you, guys using some lightweight version of PostCSS? So, I suggest to try figure out, could we add support for this postcss-plugin: https://github.com/alexandr-solovyov/postcss-responsive-properties ? So, we can write responsive values for our rules, thanks!
Even though it's a pretty simple example, I think it might help to make writing more complex styles a bit easier. 

### Instead of this: 
```
const Example = styled.div`
  height: 3em;
  width: 3em;
  background: papayawhip;

  @media (min-width: 700px) {
    background: palevioletred;
  }

  @media (min-width: 1024px) {
    width: 5em;
    height: 5em;
  }
`;
```

### We could write this: 
```
const Example = styled.div`
  height: {
    0: 3em;
    1024: 5em;
  }
  width: {
    0: 3em;
    1024: 5em;
  }
  background: {
    0: papayawhip;
    700: palevioletred;
  }
`;
```

**Comment by kitten** [comment]
@alexandr-solovyov We unfortunately switched away from PostCSS and are now relying on stylis. We might in the future switch again to an ISTF/Sweetsour based pipeline, but that's far away.

So the thing with these plugins though is that we'd like to keep our supported CSS as closely to vanilla CSS as possible; so this probably won't be something we'll support, and only if our pipeline ever becomes customisable — no promises here :wink: — then this'd be in your hand.

Hope this clarifies it 😅 Sorry, if SC's internals are not as transparent as they maybe should be
