### ISSUE TITLE
3.2.2 broken in prod

### ISSUE THREAD

**Issue by edqd** [styled-components/styled-components#1610]
## System:
 - OS: macOS High Sierra 10.13.3
 - CPU: x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
 - Free Memory: 84.10 MB
 - Total Memory: 16.00 GB
 - Shell: /bin/zsh - undefined
## Binaries:
 - Node: 9.6.1
 - Yarn: 1.3.2
 - npm: 5.6.0
 - Watchman: Not Found
### babel-plugin-styled-components:
 - wanted: ^1.5.0
 - installed: 1.5.0
### styled-components:
 - wanted: 3.2.2
 - installed: 3.1.6

## Reproduction
- building project with prod settings and run it

## Steps to reproduce
there are different webpack plugins used between dev and prod environment:
### dev
`
plugins: [
    new webpack.HotModuleReplacementPlugin(),
    new webpack.NoEmitOnErrorsPlugin(),
    new webpack.DefinePlugin({
      'process.env.BROWSER': JSON.stringify(true),
    }),
  ]
`
### prod
`
  plugins: [
    new webpack.optimize.OccurrenceOrderPlugin(),
    new webpack.optimize.UglifyJsPlugin({
      uglifyOptions: {
        toplevel: true,
      },
    }),
    new ExtractTextPlugin('css/[name].[hash].css'),
    new webpack.DefinePlugin({
      'process.env.BROWSER': JSON.stringify(true),
    }),
  ],
`

## Expected Behavior
render SSR and rehydrate it on client

## Actual Behavior
Curiously this only affects 3.2.2, 3.1.6 works as expected.
Dev build works as expected but in production build SSR goes through ok but client crashes with 
`
Error
    at t.replaceElement (spa.d873bd565c92be9a4cf8.js:formatted:11892)
    at t.inject (spa.d873bd565c92be9a4cf8.js:formatted:11922)
    at e.inject (spa.d873bd565c92be9a4cf8.js:formatted:12020)
    at r.generateAndInjectStyles (spa.d873bd565c92be9a4cf8.js:formatted:12448)
    at r.t.generateAndInjectStyles (spa.d873bd565c92be9a4cf8.js:formatted:12537)
    at r.t.componentWillMount (spa.d873bd565c92be9a4cf8.js:formatted:12547)
    at mountClassInstance (spa.d873bd565c92be9a4cf8.js:formatted:22525)
    at beginWork (spa.d873bd565c92be9a4cf8.js:formatted:23102)
    at o (spa.d873bd565c92be9a4cf8.js:formatted:23931)
    at a (spa.d873bd565c92be9a4cf8.js:formatted:23954)
    at u (spa.d873bd565c92be9a4cf8.js:formatted:23978)
    at w (spa.d873bd565c92be9a4cf8.js:formatted:24220)
    at b (spa.d873bd565c92be9a4cf8.js:formatted:24199)
    at h (spa.d873bd565c92be9a4cf8.js:formatted:24140)
    at d (spa.d873bd565c92be9a4cf8.js:formatted:24117)
    at Object.updateContainer (spa.d873bd565c92be9a4cf8.js:formatted:24407)
    at spa.d873bd565c92be9a4cf8.js:formatted:24939
    at Object.unbatchedUpdates (spa.d873bd565c92be9a4cf8.js:formatted:24311)
    at vn (spa.d873bd565c92be9a4cf8.js:formatted:24938)
    at Object.hydrate (spa.d873bd565c92be9a4cf8.js:formatted:26440)
    at r (spa.d873bd565c92be9a4cf8.js:formatted:21303)
    at o (spa.d873bd565c92be9a4cf8.js:formatted:15859)
    at <anonymous>
`

**Comment by kitten** [comment]
Can you provide some more information please? A production would be optimal, but I know that’s unrealistic for SSR.

Can you post the entire error message please and the nature of your SSR setup? Are you using streamed SSR, are both versions on 3.2? Have you upgrade from 3.1.6 (3.2 is a large refactor so there might be some incompatibilities between server/client that slipped through)

Also, the error message on replaceElement could imply that something weird is going on with the style tag injection? Where are you expecting the style tags to go? Is this some standard SSR setup where you put the style tags in SSR into one place without moving DOM elements manually around them?

**Comment by edqd** [comment]
The error i attached to original post is the only error i receive.
Im not using streamed SSR, and this error only happed on 3.2.2 in prod configuration.
3.1.6 are both on dev and prod alright, 3.2.2 is ok on dev but fails on prod build.
SSR gist: https://gist.github.com/edqd/d900ff0f336d9e8c38a133b9c4e73c4e
the ssr tags are extracted using getStyleElement and placed in response. Weird thing is that SSR itself runs ok and the app crashes on client initialization

**Comment by edqd** [comment]
i just tried to switch out webpack configs so only changed variable is NODE_ENV
error now shows as: 
`
styled-components.browser.es.js:361 Uncaught (in promise) Error
    at sheetForTag (styled-components.browser.es.js:361)
    at SpeedyBrowserTag.inject (styled-components.browser.es.js:520)
    at StyleSheet.inject (styled-components.browser.es.js:807)
    at ComponentStyle.generateAndInjectStyles (styled-components.browser.es.js:1799)
    at StyledComponent.generateAndInjectStyles (styled-components.browser.es.js:1455)
    at styled-components.browser.es.js:1486
    at subscribe (styled-components.browser.es.js:1211)
    at StyledComponent.componentWillMount (styled-components.browser.es.js:1483)
    at mountClassInstance (react-dom.production.min.js:109)
    at beginWork (react-dom.production.min.js:133)
`

**Comment by edqd** [comment]
I just tried to run prod build and built app with NODE_ENV set to development and everything is running smoothly, when i do the same with NODE_ENV set to production, the client crashes

**Comment by kitten** [comment]
> I just tried to run prod build and built app with NODE_ENV set to development and everything is running smoothly, when i do the same with NODE_ENV set to production, the client crashes

Yep, that's because you're essentially switching off speedy mode, i.e. `insertRule`, where this error stems from.

My problem is essentially that I do not know what error it is you're running into, i.e. ` Uncaught (in promise) Error at sheetForTag` being imprecise.

It doesn't sound like a bug though. There are a couple of possibilities:

- You have multiple instances of styled-components on the client which all try to rehydrate and are removing each other's tags
- You're moving around / unmounting / modifying the style tags somehow

So I'm not convinced it's a bug 😅 Your SSR code looks fine though; I'm wondering whether it's a problem with your client webpack setup

**Comment by kitten** [comment]
Also, I suspect the error comes from here: https://github.com/styled-components/styled-components/blob/master/src/utils/insertRuleHelpers.js#L20

Sorry, for not having a good error message there yet. (we have an issue for that somewhere)

This strongly hints at the style element not being mounted somehow. This is actually a very common indicator of duplicated styled-components instances, which does happen accidentally to some ppl when upgrading webpack/styled-components.

**Comment by mxstbr** [comment]
See the docs for the steps on resolving a duplicate module: https://www.styled-components.com/docs/faqs#i-am-a-library-author-should-i-bundle-styledcomponents-with-my-library

**Comment by kitten** [comment]
^ this is probably the relevant section :+1: https://www.styled-components.com/docs/faqs#duplicated-module-in-node_modules

**Comment by kitten** [comment]
@edqd hiya, do you have some update of what's going on? As we haven't heard similar reports of this, I'm inclined to close this for now. But I'd love to help you fix this 🙌

**Comment by sanex3339** [comment]
3.1.0 breaked all my styles in prod, now with 3.2.0 in prod they works but breaked in dev

**Comment by kitten** [comment]
@sanex3339 I mean, there's not really anything to go after here. Sorry, if you're already at the point of being frustrated, but especially if you went from sth wrong with 3.1 to sth wrong with 3.2, where a huge refactor took place in-between. It's likely to be a usage error.

Please try to find out if you are using duplicated styled-components modules, and open a new issue if you can't resolve the issue otherwise.

**Comment by edqd** [comment]
Yep sry guys for not replying, i had to focus on other matter, im looking into the issue right now, about to try to find out whether we have any duplications of sc lib or whether there are any monkey business with moving around of styled-components

**Comment by edqd** [comment]
Alright so status report:
- we had a duplicated styled-components lib in one of our dependencies => we moved set it as peerDependency but the problem still persisted so 
- i tried to remove any usage of innerRefs we have which solved the issue
Now i'm trying to figure out which concrete usage was breaking the app, since we still need to use refs

**Comment by kitten** [comment]
@edqd 

> i tried to remove any usage of innerRefs we have which solved the issue
Now i'm trying to figure out which concrete usage was breaking the app, since we still need to use refs

This sounds kind of unrelated; Let's see what's going on

> we had a duplicated styled-components lib in one of our dependencies => we moved set it as peerDependency but the problem still persisted so

If the problem persisted then I'd guess it didn't quite work. This can happen if your environment still installs `devDependencies`. The node resolution algorithm won't know that something is a `peerDependency`, so make sure that your dev environment points to a single module. (Webpack config maybe? Can be found here: https://www.styled-components.com/docs/faqs#duplicated-module-in-node_modules)

**Comment by edqd** [comment]
sorry maybe i made myself unclear. setting styled-components as peerDependency removed duplicated SC lib in our bundle and if check whats being installed, sure enough it's not there:
```bash
⇒  find -L ./node_modules | grep /styled-components/package.json
./node_modules/styled-components/package.json
```
and when i check bundle-analyzer its there once too.
but i noticed that there are three of these errors upon pageload and there are three instances of innerRef usage on the first view so i started to suspect something odd is happening with the refs (maybe misuse)

**Comment by kitten** [comment]
@edqd ah, okay, sorry for the misunderstanding 😵

Can you by any chance post one of these components and their usage? Maybe it’s something obvious. If it’s not we can always try a CodeSandbox

**Comment by edqd** [comment]
Alright i stand corrected, upon erasing whole node_modules and reinstalling whole repo from scratch, everything started working as expected. With no other change the act of moving the styled-components to peerDependencies on our lib module was the correct thing to do as it fixed the problem you foresaw in the beginning. 😄 i have no idea how could it happen that the styled-components was not visible (findable?) in the bundle-analyzer. 
Thanks for your time guys 👍

**Comment by Slapbox** [comment]
I'm seeing this same issue with 3.4.4 and nothing in this thread makes any difference.

**Comment by Slapbox** [comment]
Here's what I see immediately prior to failure:

![image](https://user-images.githubusercontent.com/6835891/44598508-3c6ab700-a7a1-11e8-8418-83352118d2cb.png)
