### ISSUE TITLE
3.2x Breaking Jest/Enzyme tests of components that mount elements using unstable_RenderSubtreeIntoContainer

### ISSUE THREAD

**Issue by byrondevonwall** [styled-components/styled-components#1613]
Jest/enzyme tests that were passing until 3.2x release are now failing once 3.2x is installed.  Reverting to 3.1.6 solves the issue.

### System:
 - OS: macOS High Sierra 10.13.3
 - CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
 - Free Memory: 1.41 GB
 - Total Memory: 16.00 GB
 - Shell: /bin/zsh - undefined
### Binaries:
 - Node: 7.10.0
 - Yarn: 0.23.3
 - npm: 4.2.0
 - Watchman: 4.7.0
#### babel-jest:
 - wanted: ^20.0.3
 - installed: 20.0.3
#### babel-plugin-styled-components:
 - wanted: ^1.3.0
 - installed: 1.5.1
#### enzyme:
 - wanted: ^2.7.1
 - installed: 2.9.1
#### jest:
 - wanted: ^20.0.4
 - installed: 20.0.4
#### styled-components:
 - wanted: ^3.0.0
 - installed: 3.2.2

### System:
 - OS: macOS High Sierra 10.13.3
 - CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
 - Free Memory: 1.47 GB
 - Total Memory: 16.00 GB
 - Shell: /bin/zsh - undefined
### Binaries:
 - Node: 7.10.0
 - Yarn: 0.23.3
 - npm: 4.2.0
 - Watchman: 4.7.0
#### babel-jest:
 - wanted: ^20.0.3
 - installed: 20.0.3
#### babel-plugin-styled-components:
 - wanted: ^1.3.0
 - installed: 1.5.1
#### enzyme:
 - wanted: ^2.7.1
 - installed: 2.9.1
#### jest:
 - wanted: ^20.0.4
 - installed: 20.0.4
#### styled-components:
 - wanted: 3.1.6
 - installed: 3.1.6

## Reproduction
I am unable to share the code in which I found this behavior, but can create a repo to repro if needed.

## Steps to reproduce
Using React 15x, create a component that has a child that is rendered via `unstable_renderSubtreeIntoContainer`, write test using enzyme's `mount`.  Tests pass with version `3.1.6` but fail under version(s) `3.2x`.

## Expected Behavior
Tests don't break due to warning from `styled-components` that DOM node mounted with `unstable_renderSubtreeIntoContainer` is unmounted.  Tests pass with 3.1.6 but do not with 
## Actual Behavior
Tests break with this sample output (where `Feedback.js.jsx` is a child of the mounted component that uses `unstable_renderSubtreeIntoContainer`) when moving from 3.1x to 3.2x:
~~~
 FAIL  app/__tests__/dashboard_test.js
  ● Test suite failed to run

    Trying to insert a new style tag, but the given Node is unmounted!
    - Are you using a custom target that isn't mounted?
    - Does your document not have a valid head element?
    - Have you accidentally removed a style tag manually?
      
      at makeStyleTag (node_modules/styled-components/dist/styled-components.cjs.js:510:13)
      at makeTag (node_modules/styled-components/dist/styled-components.cjs.js:818:14)
      at StyleSheet.makeTag$$1 [as makeTag] (node_modules/styled-components/dist/styled-components.cjs.js:1045:12)
      at StyleSheet.getTagForId (node_modules/styled-components/dist/styled-components.cjs.js:1063:18)
      at StyleSheet.deferredInject (node_modules/styled-components/dist/styled-components.cjs.js:1103:10)
      at new ComponentStyle (node_modules/styled-components/dist/styled-components.cjs.js:1963:27)
      at createStyledComponent (node_modules/styled-components/dist/styled-components.cjs.js:1808:26)
      at templateFunction (node_modules/styled-components/dist/styled-components.cjs.js:2076:14)
      at Object.<anonymous> (app/components/feedback.js.jsx:15:116)
      at Object.<anonymous> (app/components/dashboard.js.jsx:12:19)
      at Object.<anonymous> (app/__tests__/dashboard_test.js:9:20)
      at handle (node_modules/worker-farm/lib/child/index.js:44:8)
      at process.<anonymous> (node_modules/worker-farm/lib/child/index.js:51:3)
      at emitTwo (events.js:106:13)
      at process.emit (events.js:194:7)
      at process.nextTick (internal/child_process.js:766:12)
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickCallback (internal/process/next_tick.js:104:9)
~~~

**Comment by byrondevonwall** [comment]
Looking at the output more closely, the "Several Instance" warning mentioned in this issue: https://github.com/styled-components/styled-components/issues/1592 is also being thrown for these tests (the warning terminal output got overwritten initially).  So this issue may be related to Jsdom/jest setting multiple instances of `styled-components`.

**Comment by kitten** [comment]
I really need some reproduction here; it's unlikely that it's possible to debug this without one.

That being said: Make sure that you don't have multiple instances, try to run in a non-jsdom environment if possible, make sure that you don't do anything bad to the `head` element accidentally

https://github.com/styled-components/styled-components/blob/master/src/models/StyleTags.js#L100-L106

**Comment by byrondevonwall** [comment]
Thanks for the quick response, I will work on a repro repo and hopefully have one fairly soon.

**Comment by kitten** [comment]
Actually, I have a hypothesis. It might be that a jsdom environment in enzyme and jest resets the head element, without styled-components being reset.

In 3.2 we're now attempting to keep all elements together. So we're appending to the last style tag's parent and are inserting the new style tag after the last.

So knowing that, maybe a reset will do it. Can you try the following for me please?

```js
beforeAll(() => {
  const secretInternals = require('styled-components')
    .__DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS
  const StyleSheet = secretInternals.StyleSheet;
  StyleSheet.reset(typeof document === 'undefined')
})
```

**Comment by byrondevonwall** [comment]
I tried it as a beforeAll in the affected files, an afterAll in the files that run before the affected files, and as an async global beforeAll.  Unfortunately none of these approaches fixed the issue.   

I think that your hypothesis is correct (or not incorrect) though, because each of the files that fail when run as part of a larger suite pass when run individually.  

I will look into modifying your approach a bit more (thanks, btw!) and if that doesnt work make a repro repo.

**Comment by kitten** [comment]
@byrondevonwall you could try `StyleSheet.reset(true)` to force it into a server-side rendered result. That'll maybe break some of your tests depending on what you're doing, but this could show us whether this actually seems to be the issue

**Comment by BRKalow** [comment]
Chiming in...we have a fairly large collection of styled components in our application (~1000 off of a quick search) tested with jest 23 using `v3.1.4`. Upgrading to `v3.3.2` triggered the above error in a few of our test files:
```
    Trying to insert a new style tag, but the given Node is unmounted!
    - Are you using a custom target that isn't mounted?
    - Does your document not have a valid head element?
    - Have you accidentally removed a style tag manually?
```

For us, the error actually seems to get thrown before any test cases are run. We were able to get past the error by un-mocking certain modules, but the stack trace indicates that modules containing styled component declarations are being imported/evaluated during test setup, before the DOM environment is initialized (possibly as a result of how jest handles mocking?). (The `styled-components` specific stack trace looks very similar to the OP).

@kitten Your workaround did the trick for us, but hoping you might be able to shed some light on why this is happening. Noting the `StyleSheet` rewrite from `3.1.x` to `>3.2`, did the point at which styles get injected into the document change?

Here's the snippet added to our test initialization, pulled from your comments. Based on my understanding we're now using the server stylesheet instead of the DOM based one.
```
const secretInternals = require('styled-components')
  .__DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS;
const StyleSheet = secretInternals.StyleSheet;
StyleSheet.reset(true);

beforeAll(() => {
  StyleSheet.reset(true);
});
```

Happy to connect and provide more info if it would be helpful!

**Comment by janybravo** [comment]
Hi, 
I'm using `styled-components 3.3.2, react 16.2, jest 23.0, enzyme 3.20, jest-styled-components 5.0.1`.
Resetting StyleSheet to server rendering isn't working here, even if its called before tests are run. That is where it actually gets broken, at imports. If I try to use less than 40 styled component, style tag remains empty. That also seems problematic. When code is run in actual browser no such error can be observed.
I observed document.head if it is somehow changes, due to JSDOM but it just remains the same after first <style> is inserted. It looks like SC looses reference to it and throws due to `tagEl.parentNode` is `null`.

Does anybody have any clues?

**Comment by themre** [comment]
we were able to bypass this problem by setting `NODE_ENV=production` in npm script. if this solves the problem, can we opt-in this limit for development?

**Comment by themre** [comment]
hm... render props shouldn't be a problem, we hardly use them. It's a problem how many style rules are allowed in development mode. Enzyme somehow cleans DOM if it gets too big and this removes some previous styles and breaks SC. I don't know what is the best option here... allowing to bump this limit or somehow force enzyme not to clean DOM every time.

**Comment by taylor1791** [comment]
I can reliably reproduce this. `jest@20.0.4` `react@16.4.2` `styled-components@3.3.3`. Upgrading to jest@23.4.2 gives a different (unrelated) error. 

This is what I did to reproduce it. If you are trying to reproduce this, please use the files exactly as below. There are many things that I would expect to have no effect that actually do.

test.js
```
const styled = require('styled-components').default;
jest.mock('./test2');
require('styled-components').default.div({});
require('./test2');

for (var i = 0; i < 40; i++) {
  styled.div({});
}

test('hello', () => {});
```

test2.js
```
const styled = require('styled-components').default;

styled.div({});
styled.div({});
```

Running `jest test.js` produces the following

```
 FAIL  ./test.js
  ● Test suite failed to run

    Trying to insert a new style tag, but the given Node is unmounted!
    - Are you using a custom target that isn't mounted?
    - Does your document not have a valid head element?
    - Have you accidentally removed a style tag manually?

      at makeStyleTag (node_modules/styled-components/dist/styled-components.cjs.js:533:13)
      at makeTag (node_modules/styled-components/dist/styled-components.cjs.js:847:14)
      at StyleSheet.makeTag$$1 [as makeTag] (node_modules/styled-components/dist/styled-components.cjs.js:1075:12)
      at StyleSheet.getTagForId (node_modules/styled-components/dist/styled-components.cjs.js:1093:18)
      at StyleSheet.deferredInject (node_modules/styled-components/dist/styled-components.cjs.js:1133:10)
      at new ComponentStyle (node_modules/styled-components/dist/styled-components.cjs.js:2030:27)
      at createStyledComponent (node_modules/styled-components/dist/styled-components.cjs.js:1861:26)
      at Function.templateFunction [as div] (node_modules/styled-components/dist/styled-components.cjs.js:2142:14)
      at Object.<anonymous> (test.js:7:10)
          at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.688s
Ran all test suites matching "test.js".
```

I am going to keep looking into how to fix this, but perhaps this may help others track it down faster than I.

**Comment by taylor1791** [comment]
Here is my assessment of the problem. Disclaimer: I am new to styled components, so my analysis could be wrong.

If the previous styled tag is created by way of jest's automock, the previous style tag (lastEl) will not be available. When styled-components tries to create a new style tag (to append it after the previous). 💥We get the aforementioned error since (i think) "[jest] removed the style tag" during its automock process.

**Comment by taylor1791** [comment]
Upgrading to jest 23.4.2 fixed it for me. Not sure what the minimum version that fixes it. Unfortunately there are many people stuck using jest 20.0.4 since that is the latest version that ships with react-scripts 1.x series.

I worked around it by manually mocking the `jest.mock` that was giving me problems.

**Comment by ersel** [comment]
We run into the same issue with `jest.mock` calls in test module causing `Trying to insert a new style tag, but the given Node is unmounted!` error.

We ended up changing our mocks from this

```
jest.mock('../somePath/SomeDependency.js');
```

to this:

```
jest.mock('../somePath/SomeDependency.js', () => ({
  methodToMock: jest.fn();
}));
```

**Comment by master-atul** [comment]
Here is how I solved it:
I created a mock file for `styled-components`
`__mocks__/styled-components.js`

```js

const StyledComponent = require("styled-components")

const fixNodeUnmountedErrorInTestForStoryShots = styledComponents => {
  const secretInternals = styledComponents.__DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS //eslint-disable-line
  const prevMakeTag = secretInternals.StyleSheet.prototype.makeTag
  secretInternals.StyleSheet.prototype.makeTag = function makeTagMock(tag) {
    const newTag = tag || {}
    newTag.styleTag = newTag.styleTag || document.createElement("style")
    const { head } = document
    if (!newTag.styleTag.parentNode) {
      head.appendChild(newTag.styleTag)
    }
    const prevMakeTagBinded = prevMakeTag.bind(this)
    return prevMakeTagBinded(newTag)
  }
}

fixNodeUnmountedErrorInTestForStoryShots(StyledComponent)

module.exports = StyledComponent

```

**Comment by mbrowne** [comment]
Upgraded to the latest versions and still experienced this issue:

jest@24.9.0
styled-components@4.3.2

**Comment by mvelkCisco** [comment]
If anyone else runs into these problems... another solution that seem to work is to force styled-components to use server side rendering in your tests.

It can be done by adding this to one of the files you have specified in your `jest.config.js` as `setupFilesAfterEnv`.
```
import { __DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS } from 'styled-components';

__DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS.StyleSheet.reset(true);
```
The `true` is assigned to `forceServer` variable. This must run _before_ the imports in tests (it's not enough to put it to test itself).

**Comment by wmertens** [comment]
I combined the answers, I put the stylesheet reset of the comment above in `__mocks__/styled-components.js` and return the original.

**Comment by melounek** [comment]
Trying to upgrade react-scripts from version `3.0.1` to `3.1.2` or `3.2.0` but in both cases the @master-atul workaround stopped working. I tried all possible ways how to apply what's in the last two comments ☝, but no success. Is there someone with updated `react-scripts` with working solution? or can you @wmertens describe better what you did exactly?

**Comment by wmertens** [comment]
@melounek 
I did one better, upgraded to `styled-components@beta` and I don't need the mock any more (but now my tests are sometimes missing styles hmm).

**Comment by fitfab** [comment]
is this issue fixed with this release? https://github.com/styled-components/styled-components/releases/tag/v5.0.0

**Comment by probablyup** [comment]
This is an ancient issue, please reopen with updated reproduction etc if you are seeing a problem. Thanks.
