### ISSUE TITLE
Remove deprecated ThemeProvider channel

### ISSUE THREAD

**Issue by kitten** [styled-components/styled-components#1618]
We have had this deprecated theme channel for a while now, and it should be removed.

It's quite a simple task since nothing should be depending on it anymore, but it does involve some "housekeeping" task of checking whether there's any leftovers, renaming the new `CHANNEL`, and checking libraries that might depend on it still.

https://github.com/styled-components/styled-components/blob/master/src/models/ThemeProvider.js#L80-L88

**Comment by mxstbr** [comment]
We should probably just do this in one sweep while moving to the new context API, ref #1459

**Comment by pnkapadia6** [comment]
Hey @kitten @mxstbr! Should I give it a try and remove ThemeProvider channel or the changes will be made alongwith the new context API itself?

**Comment by alexandernanberg** [comment]
Closing this since we now have moved to the new context API #1894
