### ISSUE TITLE
Deprecate experimental preprocess mode

### ISSUE THREAD

**Issue by kitten** [styled-components/styled-components#1619]
We had this `preprocess` mode for a while which has been replaced by our ISTF/Sweetsour effort. The old approach was deeply flawed and is borderline unusable.

I still see people from time to time who are switching it on, believing that it would work as intended.

This task involves the deprecation (and future removal potentially) of this mode, so that we can delete its bundles.

The tasks under this umbrella issue are:

- [x] Deprecate preprocess bundle (add warning)
- [ ] Remove preprocess bundle (in a future major, separate PR)
- [ ] Remove preprocess code and flag from babel plugin

**Comment by Samatar26** [comment]
@kitten Can I work on this one?

**Comment by mxstbr** [comment]
Yes please!

**Comment by kitten** [comment]
@Samatar26 Absolutely! And please let me know if you need any help 🙌

**Comment by chengjianhua** [comment]
@kitten Hi ~ I'm very curious about the progress of the ISTF since I read the article you wrote. Could you mind to open a issue to introduce the great works you have done ?

It's amazing 😍 and I'm waiting for the appearance of the implementation, but I can't know any state changes about it, so sad 🙈. I'll appreciate that if you can introduce more progress about the ISTF, thx ~

**Comment by kitten** [comment]
@chengjianhua hiya :) the latest progress can be seen on the Sweetsour repo. https://github.com/kitten/sweetsour

I’m mindful of posting any kind of timeline as I don’t have time to work on it continuously. That being said the parser itself is pretty much done and the next idea on how to proceed might be #1617

**Comment by rodocite** [comment]
@kitten Was surfing the issues and saw this. I know @Samatar26 is working on it, but was just wondering if this block is what you're talking about:

https://github.com/styled-components/styled-components/blob/75502fbf1f1fb413eeafd3f9f4cadfe06f646df6/sandbox/server/webpack.config.js#L33

**Comment by kitten** [comment]
@rodocite no, specifically what we're referring to is:

- https://github.com/styled-components/styled-components/tree/master/no-parser
- https://github.com/styled-components/styled-components/tree/master/src/no-parser
- https://github.com/styled-components/styled-components/blob/master/rollup.config.js#L149-L162
- https://github.com/styled-components/babel-plugin-styled-components/tree/master/src/css
- https://github.com/styled-components/babel-plugin-styled-components/blob/master/src/visitors/noParserImport.js
- https://github.com/styled-components/babel-plugin-styled-components/blob/master/src/visitors/templateLiterals/preprocess.js
- https://github.com/styled-components/babel-plugin-styled-components/blob/master/src/utils/options.js#L9
- https://www.styled-components.com/docs/tooling#preprocessing

**Comment by kitten** [comment]
The deprecation warning is in place, so we'd only need someone to jump onto updating the babel plugin now :+1:

**Comment by Samatar26** [comment]
@kitten working on it :+1:

**Comment by probablyup** [comment]
It's dead and deleted
