### ISSUE TITLE
Proposal: styled can take function returning css tagged string

### ISSUE THREAD

**Issue by acjay** [styled-components/styled-components#1620]
In a styled component that takes a lot of input from its props and needs to do intermediate calculations, it can be really cumbersome. Here's some real code we have (apologies for the lack of context, but wanted to illustrate the situation):

```
const borderWidth = dir =>
  dir === 'right' ? '8px 0 8px 10px' : '8px 10px 8px 0'
const borderColor = (dir, c) =>
  dir === 'right'
    ? `transparent transparent transparent ${c}`
    : `transparent ${c} transparent transparent`
const Arrow = styled.div`
  border-width: ${p => borderWidth(p.direction)};
  border-color: ${p => borderColor(p.direction, p.theme.colors.green)};
  border-style: solid;
  width: 0;
  height: 0;
`
```

This was refactored from:

```
const Arrow = styled.div`${({ theme, direction} => {
  const borderWidth =
    direction === 'right' ? '8px 0 8px 10px' : '8px 10px 8px 0'
  const borderColor =
    direction === 'right'
      ? `transparent transparent transparent ${theme.color}`
      : `transparent ${theme.color} transparent transparent`

  return  `
    border-width: ${borderWidth};
    border-color: ${borderColor};
    border-style: solid;
    width: 0;
    height: 0;
  `
}}`
```

What I'd like is more like:

```
const Arrow = styled.div({ theme, direction } => {
  const borderWidth = 
    direction === 'right' ? '8px 0 8px 10px' : '8px 10px 8px 0'
  const borderColor =
    direction === 'right'
      ? `transparent transparent transparent ${theme.color}`
      : `transparent ${theme.color} transparent transparent`

  return css`
    border-width: ${borderColor};
    border-color: ${borderWidth};
    border-style: solid;
    width: 0;
    height: 0;
  `
})
```

So basically, I want the straightforward syntax of the first example (no nested template strings or dance of brackets, parentheses and backticks!) with the encapsulation and brevity of the second example (no functions inside interpolants). This is a small use case, but we have tons of similar stuff throughout our codebase, and situations where the proposed syntax would be even more of a sweet spot.

Apologies if this has been proposed before, or if I'm missing a more idiomatic solution that's already available. If this seems helpful to other folks, I'd tentatively say I'd be interested in trying to implement it.

**Comment by wmertens** [comment]
I would also like this, as well as maybe being able to pass a style object
directly.

I know that @mxstbr is not a fan of extending the API, but maybe this will
sway him :)

**Comment by kitten** [comment]
Both APIs you’re proposing are not impossible right now and seem like they make things simpler. But with good helper functions and segregated interpolations you gain a lot more. By removing duplication that becomes excessively long you will probably come up with some good helpers and props for your components.

Now, I think the presented use case there with four different border properties is kind of an edge case, but I would not like to argue against your workflows in particular.

But what I’d like to remind you of is that the approaches you present directly conflict with our static analysis / preprocessing plans. A function that returns a tagged template literal can have as many branches as you’d like and is this unlikely to be completely statically analysable. The same goes for functions returning objects (which I btw find inelegant, it’d encourage style props etc with bad perf, and is not a styled-components style API)

That’s just my opinion, but I’d love to hear @mxstbr and @probablyup’s opinions

**Comment by acjay** [comment]
@kitten Thanks for the feedback!

I don't think I fully understand what you're proposing as an alternative, although I think there's a pretty good chance that there are other solutions that I just haven't thought of. Just to be clear, when you say "good helper functions", do you mean my first example? I can certainly live with this approach, but my overall point was just that it breaks encapsulation of logic that really is specific to the `Arrow` component. Sure, it could be come more abstract in order to lose that specificity, but I don't think that's a great idea if there ends up being only one use case. And to be clear, this is just one use case that is probably of intermediate complexity in the scope of our styling.

By "segregated interpolations", I assume you mean something different than my second example, since that's more like "nested interpolations".

I don't know much about the static analysis situation, but maybe I'll look into it just to make sure I understand what you mean.

Anyway, maybe there's a solution that's a little wordy, but not too bad. Model the scope as a component, rather than a function that returns CSS.

```
const Arrow = withTheme(({ theme, direction }) => {
  const borderWidth =
    direction === 'right' ? '8px 0 8px 10px' : '8px 10px 8px 0'
  const borderColor =
    direction === 'right'
      ? `transparent transparent transparent ${theme.colors.green}`
      : `transparent ${theme.colors.green} transparent transparent`

  const Inner = styled.div`
    border-width: ${borderWidth};
    border-color: ${borderColor};
    border-style: solid;
    width: 0;
    height: 0;
  `
  return <Inner />
})
```

**Comment by probablyup** [comment]
So in a nutshell your desired syntax is something like this?

```js
styled.div(p => `
  color: ${p.color};
`)
```

or now with object support

```js
styled.div(p => ({
  color: p.color,
}))
```

**Comment by acjay** [comment]
@probablyup Yeah, either way. The object syntax seems even better though. Does that work now?

**Comment by probablyup** [comment]
Yeah objects were added in 3.3.0. The desired function syntax isn’t a thing yet though.

**Comment by acjay** [comment]
@probablyup Thanks for the head's up! If that PR merges, both syntaxes will be possible.
