### ISSUE TITLE
Using styled-components and puppeteer

### ISSUE THREAD

**Issue by boazhoch** [styled-components/styled-components#1622]
So I am using puppeteer for E2E test and I would like to test for a div with a certain class name.

`document.querySelctor('classname')`

but I don't know what is the generated class name by styled-components, How can I test it then?

**Comment by probablyup** [comment]
Don’t. Use something else like a data selector or HTML id to query since
they will be stable.

The pattern we use at my work is data-test=“component-name”

**Comment by mxstbr** [comment]
I swear we had a note about this in the docs before, but I can't seem to find it anymore :confused:

We use `data-e2e-id` in our codebase!
