### ISSUE TITLE
target specific browser and give them specific rules ?

### ISSUE THREAD

**Issue by CyrusZei** [styled-components/styled-components#1626]
Hi guys,

I cant find a way to target for example Firefox and give it a specific rules.

My problem is this : I am using react and styled components for all the styling. I am using chrome as my browser and when I look at Firefox there are some stuffs that are not correct. So I need to add som rules, but I only want to add those rules if it is Firefox. 

Any suggestions on how to approach this ?

**Comment by mxstbr** [comment]
This has nothing to do with styled-components, it's a CSS question! Maybe try something like https://stackoverflow.com/questions/952861/targeting-only-firefox-with-css?
