### ISSUE TITLE
pseudo elements having no effect on primitives API

### ISSUE THREAD

**Issue by jcampbell05** [styled-components/styled-components#1627]
## System:
 - OS: macOS Sierra 10.12.6
 - CPU: x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
 - Free Memory: 479.27 MB
 - Total Memory: 16.00 GB
 - Shell: /bin/zsh - 5.2
## Binaries:
 - Node: 8.9.4
 - Yarn: 1.3.2
 - npm: 5.6.0
 - Watchman: 4.9.0
### styled-components:
 - wanted: ^3.2.3
 - installed: 3.2.3

## Reproduction

Create a project with react-primitives and styled components, add a hover style to a view. Notice how it has no effect

## Expected Behavior

Should hover on web

## Actual Behavior

Nothing happens

**Comment by mxstbr** [comment]
That's a react-native-web thing, they don't allow pseudo selectors.

**Comment by mxstbr** [comment]
I don't have a source for that decision, /cc @necolas who'll surely be able to point you to it!

**Comment by jcampbell05** [comment]
Ah thanks for the info :) Is there any recommendation on how we can implement this ? Just use javascript events ?

**Comment by mxstbr** [comment]
Yep, using JavaScript events!

**Comment by jcampbell05** [comment]
Gotcha, thanks for your help :) Realise this is out of the scope for primtives, so thank you :)

**Comment by necolas** [comment]
React Native doesn't support CSS selectors (this lib should probably print a warning when they are passed to react native). You can use this though https://gist.github.com/necolas/1c494e44e23eb7f8c5864a2fac66299a

**Comment by mike3run** [comment]
@mxstbr im thinking for simple stuff like `:focus` on react native it'd be nice if on the background the library added the necessary events to just trigger those style changes

Something along this

https://stackoverflow.com/questions/34087459/focus-style-for-textinput-in-react-native#34091564

but auto 😄
