### ISSUE TITLE
Selector "& + &" not working on deep levels

### ISSUE THREAD

**Issue by Ky6uk** [styled-components/styled-components#1629]
I tried to use `& + &` selector and it works well on the first level

```js
const Component = styled.div`
  & + & {
    margin-top: 10px;
  }
`;
```

but if I tried to use it on the one more level deeply it just do nothing

```js
const Component = styled.div`
  section {
    // doesn't work
    & + & {
      margin-top: 10px;
    }

    // works well as `Component > section > div`
    & > div {
      padding: 5px;
    }
  }
`;
```

There is an example https://codesandbox.io/s/ppv4no73p7

**Comment by rodocite** [comment]
Instead of `& + &`, you could use `& + section` which works with your example. My guess is with your example, you're selecting the adjacent "self" instead of the DOM node of that type/selector.
```js
const Root = styled.div`
  width: 100px;
  height: 100px;
  text-align: center;

  section {
    border: 1px solid brown;

    & > div {
      margin: 5px;
      border: 1px dashed black;
    }

    & + section {
      margin-top: 10px;
    }
  }
`;
```

**Comment by Ky6uk** [comment]
@rodocite that problem is more about "Why the second `&` is not interpreted as the first `&`?" than "My code don't work". Using `& + &` is the most convenient way for logic presented above. 

I still confused about it because the only one `&` from two of them is pointer to a current element.

**Comment by rodocite** [comment]
I did a quick investigation on jsfiddle and jsbin; the styled-component behavior mirrors both SCSS and LESS `&` behavior. I also skimmed the documentation for LESS and the examples are all non-nested. If you can show me an example where this actually works, then I'll take a look. However, this looks like intended behavior for SCSS, LESS, and styled-components.

Nested Examples (not working)
https://jsfiddle.net/7xkhf5an/2/ - You need to press "play" to see the changes
https://jsbin.com/homoyebihe/edit?html,css,output

Not Nested
https://jsbin.com/dexuyorojo/edit?html,css,output

**Comment by Ky6uk** [comment]
@rodocite hmm. So if styled components takes behaviour from SASS/LESS then it looks logical now. Because in those tools `&` will compiled as a reference with a full path of selectors tree. I will think about it in the SASS-conception now. Thanks.
