### ISSUE TITLE
Uncaught Error in prod (StyleSheetManager)

### ISSUE THREAD

**Issue by berkaey** [styled-components/styled-components#1633]
Hey there,

I'm getting an _Uncaught Error_ in production (cra build) error happens inside sheetForTag.

PS: I'm developing a react test tool called react-scenes and I used StyleSheetManager to collect styles. with target like

```
      <StyleSheetManager target={target}>
        <FrameComponent {...frameProps}>{this.props.children}</FrameComponent>
      </StyleSheetManager>
```

BTW, everything is just works on dev. env. without any issues or errors.

```
....
/* retrieve a sheet for a given style tag */
var sheetForTag = function sheetForTag(tag) {
  // $FlowFixMe
  if (tag.sheet) return tag.sheet;

  /* Firefox quirk requires us to step through all stylesheets to find one owned by the given tag */
  var size = document.styleSheets.length;
  for (var i = 0; i < size; i += 1) {
    var sheet = document.styleSheets[i];
    // $FlowFixMe
    if (sheet.ownerNode === tag) return sheet;
  }

  /* we should always be able to find a tag */
  throw new Error();
};
```

## System:
 - OS: macOS High Sierra 10.13.3
 - CPU: x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
 - Free Memory: 392.12 MB
 - Total Memory: 8.00 GB
 - Shell: /bin/bash - 3.2.57
## Binaries:
 - Node: 9.4.0
 - Yarn: 1.3.2
 - npm: 5.6.0
 - Watchman: 4.9.0

## Reproduction

npm install react-scenes-cli
then setReactScenes on any folder then follow the installation steps then yarn build and open page in static server.

## Steps to reproduce
-
## Expected Behavior
-
## Actual Behavior
-

**Comment by kitten** [comment]
Can you follow the steps detailed in the comments in the following issue please? It’s likely the same cause https://github.com/styled-components/styled-components/issues/1610#comment-372965065

By the way, the target prop on the StyleSheetManager is currently unlikely work in combination with SSR, if that’s part of your environment.

If the above instructions in the issue don’t solve your issue we’ll most likely need a reproduction please

**Comment by berkaey** [comment]
I already tried and read that issue, and no there is no SSR setup I actually just want to build a static react app with CRA and its build. You can easily reproduce by

1. `npm install react-scenes-cli -g`
2. go to your desktop 
3. `mkdir demo && cd demo`
4. `setReactScenes`
5. `cd .scenes && yarn`
6. `yarn build`
7. `serve -s build`

**Comment by berkaey** [comment]
you can also check here [https://github.com/doubco/react-scenes/blob/master/src/Frame.js](https://github.com/doubco/react-scenes/blob/master/src/Frame.js)

**Comment by berkaey** [comment]
Looks like somehow directly related to NODE_ENV, I ejected cra and manually changed process.env.NODE_ENV  to development in webpack config, it just worked again.

**Comment by kitten** [comment]
@berkaey Sorry, I won't have enough time to look at this today. It's definitely related to https://github.com/styled-components/styled-components/issues/1634 interestingly.

So, summary is, in production we're performing `insertRule` style injection, so your expectations are breaking. I'm not sure whether your code and repo will correctly represent **what you're trying to do**, so just to be on the safe side, what is the behaviour you're ultimately expecting? :wink:

You'd like to copy the styles over once? Or do they have to be kept in sync? The above issue is probably very much related, but it's not a trivial problem. Copying over the styles will only work once obviously, and not in this way if it's in production.

**Comment by berkaey** [comment]
Normally, react-scenes probably works only under development environments, (I also just faced the issue while trying to create a demo page.) so not a huge issue for me but basically, I want to collect styles before/after rendering so I can inject to iframe (react-scenes works like storybook without separate compiling process). if you have any more questions, just ask ;)

**Comment by kitten** [comment]
```js
/* note that this is obviouslt a hacky approach :D */
import { __DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS } from 'styled-components';
const { StyleSheet } = __DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS;

/* if you don't care about the target or the result that much you can also force it into server-side render mode using: new StyleSheet(null, true)
const sheet = new StyleSheet(target)

/* your render cycle comes in here instead of the target and stuff */
<StyleSheetManager sheet={sheet} />

/* after the render cycle */
sheet.toReactElements() // if you need elements
sheet.toHTML() // if you need html

/* or you can also just get the raw css (which is not guaranteed to be a stable API) */
sheet.tags.map(tag => tag.css()).join('\n')
```

Would this work? This assumes that you care about a "server-side render"-like output in the browser, is that correct?

**Comment by berkaey** [comment]
Yes exactly 
```
  sheet.collectStyles(<App location={sink.request.url} />)
  const css = sheet.getStyleTags();
```
^^^ for SSR but I guess your workarond does the same/similar thing
, I will definitely try tomorrow and report here, thanks.

**Comment by berkaey** [comment]
with your suggestion, I guess I will get all generated styles right? because I only need 
```
<StyleSheetManager target={target}>
        <FrameComponent {...frameProps}>{this.props.children}</FrameComponent>
</StyleSheetManager>
```
FrameComponent and its children styles(css) so I can only inject that to iframe. so while testing your component iframe will be separated from app itself (app itself uses styled components too.)

**Comment by kitten** [comment]
@berkaey sorry for the late reply, you might want to take a look here as it's almost the same usecase (?) https://github.com/styled-components/styled-components/issues/1634

**Comment by berkaey** [comment]
Sorry, I just checked there related issues and comments but I couldn't understand how and which version can give me the SSR like style-tag export. Can you give me a little demo? Maybe on this code ```import React, { Component, Fragment } from "react";
import is from "is";
import FrameComponent from "react-frame-component";
import { StyleSheetManager } from "styled-components";

/*globals
setTimeout
document
*/

let target;

if (typeof document !== "undefined") {
  target = document.createElement("div");
}

const d2s = node => {
  let parent = document.createElement("div");
  if ("outerHTML" in parent) return node.outerHTML;
  let div = parent.cloneNode();
  div.appendChild(node.cloneNode(true));
  return div.innerHTML;
};

class Frame extends Component {
  constructor(props) {
    super(props);
    this.state = {
      styles: [],
      ready: false
    };
  }

  updateStyles() {
    const { styleClassNames, stylesheet } = this.props;

    let styles = [];

    if (is.array(styleClassNames)) {
      let styleTags = [];
      for (let className of styleClassNames) {
        let tag = document.getElementsByClassName(className);
        if (tag) {
          styleTags = styleTags.concat(Array.from(tag));
        }
      }
      for (let style of styleTags) {
        styles.push(d2s(style));
      }
    }

    if (stylesheet) {
      styles.push(`<style>${stylesheet}</style>`);
    }

    styles.push(d2s(target));

    this.setState({ styles });
  }

  componentWillReceiveProps(nextProps) {
    setTimeout(() => {
      this.updateStyles();
    }, 1);
    // TODO: why we need timeout?
  }

  componentDidMount() {
    setTimeout(() => {
      this.updateStyles();
    }, 1);
    // TODO: why we need timeout?
  }

  render() {
    const { styles = [], children } = this.state;

    const head = (
      <Fragment>
        {styles.map((style, idx) => {
          return (
            <div
              id={`component-styles-${idx}`}
              key={idx}
              dangerouslySetInnerHTML={{ __html: style }}
            />
          );
        })}
      </Fragment>
    );

    let frameProps = { ...this.props, head };

    delete frameProps.stylesheet;
    delete frameProps.styleClassNames;

    return (
      <StyleSheetManager target={target}>
        <FrameComponent {...frameProps}>{this.props.children}</FrameComponent>
      </StyleSheetManager>
    );
  }
}

export default Frame;
```

**Comment by berkaey** [comment]
https://github.com/doubco/react-scenes/blob/master/src/Frame.js
