### ISSUE TITLE
Wrong typings: 'ReadableStream from NodeJS namespace which is not present'

### ISSUE THREAD

**Issue by Havret** [styled-components/styled-components#1640]
## System:
 - OS: Windows 10
 - CPU: x64 Intel(R) Core(TM) i5-4340M CPU @ 2.90GHz
 - Free Memory: 3.31 GB
 - Total Memory: 15.69 GB
 - Shell: ¯\_(ツ)_/¯
## Binaries:
 - Node: 8.9.4
 - Yarn: 1.3.2
 - npm: 5.6.0
 - Watchman: Not Found
### styled-components:
 - wanted: ^3.2.3
 - installed: 3.2.3

The system cannot find the path specified.

## Reproduction

in [at-loader] ./node_modules/styled-components/typings/styled-components.d.ts:116:51 
    TS2694: Namespace 'NodeJS' has no exported member 'ReadableStream'.

## Steps to reproduce

Just install styled-components in Typescript project.

## Expected Behavior

It should run without errors.

## Actual Behavior

Typings are using ReadableStream from NodeJS namespace which is not present in current node typings.

**Comment by kitten** [comment]
cc @styled-components/typers 

related to #1642
