### ISSUE TITLE
Cannot find namespace 'NodeJS'.

### ISSUE THREAD

**Issue by StevenTCramer** [styled-components/styled-components#1642]
## Environment

Environment:
  OS: Windows 10
  Node: 9.8.0
  Yarn: 1.5.1
  npm: 5.8.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Version  3.0.0.0 AI-171.4443003

## Reproduction
https://github.com/StevenTCramer/Issue1

## Steps to reproduce

Build a default react-native application, with Typescript and add styled-components, reference it in the app and attempt to compile causes the following error:
node_modules/styled-components/typings/styled-components.d.ts(116,44): error TS2503: Cannot find namespace 'NodeJS'.

reproducible repo. 
https://github.com/TimeWarpEngineering/TypeScript-React-Native-Starter/blob/ffe5a5e49ca572288dfcd5ab1ab87da4bfd4299c/README.md

## Expected Behavior

compiles

## Actual Behavior

node_modules/styled-components/typings/styled-components.d.ts(116,44): error TS2503: Cannot find namespace 'NodeJS'.

**Comment by tashaffin** [comment]
If, like myself, you simply need a quick solution until this is resolved, I uninstalled the latest and re-installed a specific version:

npm uninstall styled-components
npm install styled-components@3.1.6

Best Wishes

**Comment by elliotaplant** [comment]
For anyone landing here from trying Heroku, I found that a solution to this was to move my `"@types/*"` declarations from the `devDependencies` to the `dependencies` section of my `package.json`. Heroku runs your install/build with a `NODE_ENV=production` flag, so `devDependencies` don't get installed.

Also, @tashaffin's quick fix worked too.

**Comment by sorenhoyer** [comment]
Same problem. Ty @tashaffin  for the temporary workaround. Hope this is fixed soon. :-)

**Comment by MrBlenny** [comment]
Installing `@types/node` fixed this for me. 
Ideally there would be a separate set of types for browser based projects.

**Comment by huy-nguyen** [comment]
I didn't want to install `@types/node` because it can mess with the type definition of timers (`setInterval`/`setTimeout` etc) among other things so I  made a fake definition and put it in a `.d.ts` file:

```typescript
declare namespace NodeJS {
  export interface ReadableStream {

  }
}
```

**Comment by PhilippSpo** [comment]
Adding `node` to `compilerOptions.types` worked for me. Found it [here](https://github.com/TypeStrong/typedoc/issues/320#issuecomment-301241430).

**Comment by donaldpipowitch** [comment]
Because no one mentioned it so far: You can also use `skipLibCheck: true`. Than you don't need to use `@types/node` in your browser project and don't need to use fake definitions. I found this setting quite useful every now and then and also speeds up the build.

**Comment by pranithan-kang** [comment]
> For anyone landing here from trying Heroku, I found that a solution to this was to move my `"@types/*"` declarations from the `devDependencies` to the `dependencies` section of my `package.json`. Heroku runs your install/build with a `NODE_ENV=production` flag, so `devDependencies` don't get installed.
> 
> Also, @tashaffin's quick fix worked too.

I have faced the problem when I involved with `NodeJs.Timer`. I try moving the `@types/__` up to the `dependencies`, and it is able to be compiled.
