### ISSUE TITLE
Primitives text component not interpreting unitless line-height correctly

### ISSUE THREAD

**Issue by hilary-L** [styled-components/styled-components#1643]
## Environment
Environment:
  OS:  macOS Sierra 10.12.6
  Node:  9.9.0
  Yarn:  1.5.1
  npm:  5.6.0
  Watchman:  4.7.0
  Xcode:  Xcode 9.2 Build version 9C40b
  Android Studio:  3.0 AI-171.4408382

Using styled from styled-components/primitives, create a styled Text component and give it a line-height property with a unitless value. Put this styled component inside of a styled View component. Result is a text component whose line height is transformed to px values.

https://codesandbox.io/s/q9w9788lvw

## Expected Behavior

For text with a font-size of 48px and a line-height of 1.25, total height of text element should be 60px.

## Actual Behavior

Text with a font-size of 48px and a line-height of 1.25 results in a text element with a height of 1.25px.

**Comment by kitten** [comment]
React Natives lineHeight Style property is explicitly in px and not relative to the current font size. This is not something we can change since we don’t have access to the style cascade and parents in general.

That’s why it also applies to React Primitives

**Comment by hilary-L** [comment]
If that's the case, couldn't styled-components (or perhaps react-primitives?) do some parsing to convert a unitless line-height value into one that is relative based on the set font size?

At the very least this seems like it should be documented somewhere. It's strange to be able to write standard CSS when using styled-components/primitives for *everything* but line-height.

**Comment by kitten** [comment]
>  This is not something we can change since we don’t have access to the style cascade and parents in general.

No sorry, we really can’t (see above). We’re not guaranteed to know about the current font size. Also on React Native everything is expressed in numbers usually, and numbers mean pixel values.

You’re also not able to write standard CSS for everything, in fact most of it is React Native styling. We just have some shorthands and we need you to specify “px” as a unit in shorthand’s. That should already be documented :)
