### ISSUE TITLE
Dependency conflicts with React

### ISSUE THREAD

**Issue by andraaspar** [styled-components/styled-components#1644]
## System:
 - OS: Windows 10
 - CPU: x64 Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz
 - Free Memory: 2.06 GB
 - Total Memory: 7.89 GB
 - Shell: ¯\_(ツ)_/¯
## Binaries:
 - Node: 8.9.3
 - Yarn: 1.5.1
 - npm: 5.8.0
 - Watchman: Not Found
### styled-components:
 - wanted: ^3.2.3
 - installed: 3.2.3

## Steps to reproduce

1. Take an empty project with the following in package.json (please note `flat: true`):

```JSON
{
  "license": "UNLICENSED",
  "flat": true,
  "dependencies": {
    "react": "^16.2.0",
    "react-dom": "^16.2.0"
  }
}
```

2. Install React
```
yarn
```

3. Install SC

```
$ yarn add styled-components
```

## Expected Behavior

SC to install without issues.

## Actual Behavior

```
info Unable to find a suitable version for "core-js", please choose one by typing one of the numbers below:
  1) "core-js@^1.0.0" which resolved to "1.2.7"
  2) "core-js@^2.4.0, core-js@^2.4.0" which resolved to "2.5.4"
Answer?: 1
info Unable to find a suitable version for "node-fetch", please choose one by typing one of the numbers below:
  1) "node-fetch@^1.0.1" which resolved to "1.7.3"
  2) "node-fetch@1.6.3" which resolved to "1.6.3"
Answer?: 1
info Unable to find a suitable version for "supports-color", please choose one by typing one of the numbers below:
  1) "supports-color@^3.2.3" which resolved to "3.2.3"
  2) "supports-color@^2.0.0" which resolved to "2.0.0"
Answer?: 1
info Unable to find a suitable version for "strip-ansi", please choose one by typing one of the numbers below:
  1) "strip-ansi@^3.0.0, strip-ansi@^3.0.0" which resolved to "3.0.1"
  2) "strip-ansi@^4.0.0" which resolved to "4.0.0"
Answer?: 1
info Unable to find a suitable version for "ansi-regex", please choose one by typing one of the numbers below:
  1) "ansi-regex@^3.0.0" which resolved to "3.0.0"
  2) "ansi-regex@^2.0.0, ansi-regex@^2.0.0" which resolved to "2.1.1"
Answer?: 1
info Unable to find a suitable version for "regenerator-runtime", please choose one by typing one of the numbers below:
  1) "regenerator-runtime@^0.11.0" which resolved to "0.11.1"
  2) "regenerator-runtime@^0.10.0" which resolved to "0.10.5"
Answer?: 1
```

**Comment by andraaspar** [comment]
I am against including more than one version of dependencies in the client-side code, that's why I install client side dependencies in flat mode. Not even sure what will happen when I have 2 sets of core-js. Which one wins? This threatens the stability of the code base. This prevents the use of this library in my current setup.

Is there a suggested correct answer to the conflicts above?

Is there an intent to fix this somehow?

**Comment by mxstbr** [comment]
I'm not sure why this is happening at all, honestly, sorry.

**Comment by kitten** [comment]
I’m not quite sure where these conflicts stem from but a lot of things can go awry with flat installs.

I don’t recognise them as things that will be bundled actually. We have a flat bundle that pulls in just a couple of packages, so regular installs will be fine. But I’ll take a look

**Comment by dkfiresky** [comment]
I think it's the expected behavior:

(https://yarnpkg.com/en/docs/cli/install#toc-yarn-install-flat)
> Install all the dependencies, but only allow one version for each package. On the first run this will prompt you to choose a single version for each package that is depended on at multiple version ranges. These will be added to your package.json under a resolutions field.

Does it matter if `styled-components` and `react` or any other package have the same dependencies?

**Comment by kitten** [comment]
Just had a look, it seems that the `opencollective` package is responsible for all of these conflicts. Since we were planning to replace it, I can just open a PR to remove it
