### ISSUE TITLE
[RFC] Testing selectors API

### ISSUE THREAD

**Issue by jamiebuilds** [styled-components/styled-components#1647]
- Browser integration testing requires some sort of attribute to identify elements in the DOM
- In the past many used `class="..."` but CSS-in-JS kills that
- Today many are manually adding some sort of `[data-test-id]` attribute
- But that's like... work... and... stuff
- Instead what if styled-components abstracted that away

For example, a component:

```js
import React from 'react';
import styled from 'styled-components';

export const ConfirmForm = styled.form`...`;
export const ConfirmButton = styled.button`...`;

export default function ConfirmPage(props) {
  return (
    <ConfirmForm onSubmit={props.onSubmit}>
      <ConfirmButton type="submit">Confirm.</ConfirmButton>
    </ConfirmForm>
  );
}
```

Then in your tests:

```js
import React from 'react';
import { render } from 'react-dom';
import ConfirmPage, { ConfirmForm, ConfirmButton } from './ConfirmPage';
import { find, findAll } from 'styled-components/test';

let root = document.getElementById('root');
render(<ConfirmPage/>, root);

let form = find(root, ConfirmForm); // <form/>
let buttons = findAll(form, ConfirmButton);  // [<button type="submit"/>]
```

You can actually write these methods today with styled-components:

```js
function find(el, component) {
  return el.querySelector("." + component.styledComponentId);
}

function findAll(el, component) {
  return el.querySelectorAll("." + component.styledComponentId);
}
```

See: https://codesandbox.io/s/1ryxvkkmrl

**Comment by oviava** [comment]
Might be besides the point but enzyme is pretty widely used as a helper for testing react apps and it has 'find' in it's api

**Comment by jamiebuilds** [comment]
Just published: https://github.com/jamiebuilds/tested-components

**Comment by kitten** [comment]
@jamiebuilds:

> But that's like... work... and... stuff

_publishes tested-components_ 😆 

I think we might want to merge it into `jest-styled-components` maybe? Then again it's actually quite compatible to multiple testing environments.

Anyway, We might also want to introduce a babel transform for our `withConfig` hook to add some test-id attributes? It seems like a common usecase

cc @MicheleBertoli

**Comment by probablyup** [comment]
This is cool. Since this code is so simple, we could even just add an ES5 file at the root like:

```js
import { find } from 'styled-components/test';
```

**Comment by jamiebuilds** [comment]
I can just transfer `tested-components`

**Comment by probablyup** [comment]
I'll defer to your judgement @mxstbr, but my general PoV on this sort of thing is it's better to keep test utils tightly coupled to what they're testing so it's not possible for them to fall out of sync. I also prefer to make developer usage as easy as possible, and adding additional libraries to keep track of drifts from that vision.

**Comment by mxstbr** [comment]
Yeah that's a good point @probablyup. I think the monorepo should help us keep stuff in sync, but I guess until then we could add `/test`. @jamiebuilds wanna submit a PR that adds `styled-components/test`?
