### ISSUE TITLE
Remove usages of unsafe lifecycle methods

### ISSUE THREAD

**Issue by Hypnosphi** [styled-components/styled-components#1655]
React team recently published a blogpost: https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

TL;DR: `cWM`, `cWRP`, and `cWU` methods are considered unsafe for future async rendering and will be deprecated soon. The recommended way for open source maintainers to deal with it is to use [`react-lifecycles-compat`](https://github.com/reactjs/react-lifecycles-compat) package and migrate to new `static getDerivedStateToProps` method

**Comment by camjackson** [comment]
Adding the full lifecycle names here for searchability: `componentWillMount`, `componentWillReceiveProps`, `componentWillUpdate`.

**Comment by mxstbr** [comment]
Would love a PR for this change!

I think (correct me if I'm wrong) we should be able to get by without `react-lifecycles-compat` by moving the subscriptions and unsubscription logic to componentDidMount and componentWillUnmount, and then computing the theme in `render()` instead of caching it in state, right?

**Comment by Hypnosphi** [comment]
the goal of `react-lifecycles-compat` is to keep compatibility with older React versions when using `static getDerivedStateFromProps` and `getSnapshotBeforeUpdate`

**Comment by Hypnosphi** [comment]
The goal of 16.3 release is to allow contributors to remove the unsafe methods before they are formally deprecated (with warning messages) in 16.x:

https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html#gradual-migration-path

**Comment by janhoogeveen** [comment]
When using the `<StrictMode>` component,  my console is being blasted by warnings like these:

`componentWillMount: Please update the following components to use componentDidMount instead: Anchor__Link, Footer__AuthLinks, Footer__Links, Footer__Logo, Footer__LogoContainer, Footer__StyledFooter, Footer__StyledLink`

Of course I understand that these are just warnings and I'm happy to see the migration path already being discussed here 😄 . But seeing as React is already exposing the API in 16.3 and showing these warnings in the console makes me believe the new lifecycle methods are pretty much locked down already.

**Comment by tsiq-swyx** [comment]
also posting for searchability. my warnings look like these

```
Warning: Unsafe lifecycle methods were found within a strict-mode tree:

componentWillMount: Please update the following components to use componentDidMount instead: styled.div

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: styled.div
```

**Comment by yonatanmn** [comment]
Any estimation for this ?

**Comment by alexandernanberg** [comment]
By using the new `React.createContext` API (#1894) the need for the unsafe lifecycle methods has gone away. We've also added a test for `<StrictMode />` so everything should be async safe going forward. These changes are in the `develop` branch if you want to check them out.

I guess we can close this now?

**Comment by probablyup** [comment]
Yup! Thanks @Hypnosphi for your work here.
