### ISSUE TITLE
styled-theming derived attribute not setting in defaultProps of React.Component

### ISSUE THREAD

**Issue by jongear** [styled-components/styled-components#1657]
Essentially the issue I am facing is that if I attempt to use colors derived from `styled-theming` in the Footer component which is not created with `styled` the prop is never set.  Please note that `textColor` works absolutely flawlessly in the `FooterLink` component however when I attempt to set it as a `defaultProp` for the `Footer` component I receive nothing.  For sanity checking, I created a static prop `textColorStatic` that simply sets text to yellow.  This works fine.  Which tells me something is out of sync with how `textColor` is set 

```jsx
import React from 'react'
import styled from 'styled-components'
import theme from 'styled-theming'
import colors from '../../themes/colors'
import { OutboundLink } from 'gatsby-plugin-google-analytics'

const backgroundColor = theme('mode', {
  light: colors.GRAY_DARKER,
  dark: '',
})

const FooterWrapper = styled.footer`
  background: ${backgroundColor};
  position: absolute;
  width: 100%;
  right: 0;
  bottom: 0;
  left: 0;
  padding: 1rem;
  text-align: center;
`

const textColor = theme('mode', {
  light: colors.GRAY_LIGHTER,
  dark: colors.GRAY_LIGHTER,
})

const FooterLink = styled.a`
  color: ${textColor};
  text-decoration: none;
  padding-left: 1rem;
`

class Footer extends React.Component {
  constructor(props, context) {
    super(props, context)
  }

  render() {
    return (
      <FooterWrapper>
        <div>
          <FooterLink href="/">© MyCompany {new Date().getFullYear()} </FooterLink>
          <span
            style={{
              float: 'right',
            }}
          >
            <OutboundLink
              href="https://twitter.com/MyCompany"
              target="_blank"
              style={{
                color: this.props.textColor(this.props),
                //color: this.props.textColorStatic,
                textDecoration: 'none',
              }}
            >
              Twitter
            </OutboundLink>
            <FooterLink href="https://medium.com/MyCompany" target="_blank">
              Medium
            </FooterLink>
          </span>
        </div>
      </FooterWrapper>
    )
  }
}

Footer.defaultProps = {
  mode: 'light',
  textColor: textColor,
  textColorStatic: 'yellow',
}

export default Footer
```

**Comment by jongear** [comment]
Right after posting this I figured it out.  The `defaultProps` required copying in the theme object

```jsx
Footer.defaultProps = {
  textColor: textColor,
  textColorStatic: 'yellow',
  theme: {
    mode: 'light',
  },
}
```

This does raise concerns about whether or not the `Footer` component will receive theme changes made from the root

**Comment by jongear** [comment]
In light of this discovery, this appears to be more of an issue of me not knowing how to wrap regular components in `styled` so that they are automatically passed `props.theme`.

A feel like the solution to this should be something as simple as  
```jsx
render() {
    return styled(
       ...
   )
}
```

Obviously, that syntax will not work but is there something in the same vein that I am missing?

**Comment by jongear** [comment]
Last point of interest.  Outside of manually of manually adding the props to `Footer` is there a way to tell standard components to inherit the theme of their parent?  This would solve the issue I am having with using `styled-theming` properties

```jsx
    <ThemeProvider theme={{ mode: 'light' }}>
      <div>
        <Header />

        {children()}

        <Footer />
      </div>
    </ThemeProvider>

**Comment by probablyup** [comment]
> is there a way to tell standard components to inherit the theme of their parent

This is automatic and the shallow-merged theme is available as `props.theme.*` in function interpolations.
