### ISSUE TITLE
StyleSheetManager don't includes keyframes

### ISSUE THREAD

**Issue by berkaey** [styled-components/styled-components#1659]
## System:
 - OS: macOS High Sierra 10.13.3
 - CPU: x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
 - Free Memory: 90.32 MB
 - Total Memory: 8.00 GB
 - Shell: /bin/bash - 3.2.57
## Binaries:
 - Node: 9.4.0
 - Yarn: 1.3.2
 - npm: 5.6.0
 - Watchman: 4.9.0
### babel-plugin-styled-components:
 - wanted: ^1.5.1
 - installed: 1.5.1
### styled-components:
 - wanted: ^3.2.1
 - installed: 3.2.1

## Steps to reproduce

```
      <StyleSheetManager target={target}>
        <Loading />
      </StyleSheetManager>
```

Give Loading a animation like;

```
import styled, { keyframes } from "styled-components";

const flashing = keyframes`
  0% {
    opacity: 0;
  }
  50% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
`;

export const LoadingIndicator = styled.div`
  width: 8px;
  height: 8px;
  margin: 4px;
  animation: ${flashing} 1s linear infinite;
  ${p =>
    p.light
      ? `background: rgba(255, 255, 255, 0.5)`
      : `background: rgba(0, 0, 0, 0.5)`};
  border-radius: 4px;
`;


```

## Expected Behavior

Keyframes should be included to StyleSheetManager target.

## Actual Behavior

Keyframes didn't included to StyleSheetManager target.

**Comment by kitten** [comment]
This is expected behaviour. For now the keyframes and injectGlobal helpers don’t have access to the React context.

This is already being worked on. The issue tracking this is located here: https://github.com/styled-components/styled-components/issues/1333
