### ISSUE TITLE
TypeError:

### ISSUE THREAD

**Issue by eeeman1** [styled-components/styled-components#1661]
TypeError: undefined is not a function (evaluating '_styledComponents2.default.div(_templateObject)')
package.json -
"dependencies": {
    "expo": "^25.0.0",
    "prop-types": "^15.6.1",
    "react": "16.2.0",
    "react-native": "0.52.0",
    "react-navigation": "^1.5.9",
    "styled-components": "^3.2.5"
  }

file - 

```
import React, {Component} from 'react';
import {
    Platform,
    StyleSheet,
    Text,
    View,
    ListView,
    ScrollView,
    FlatList,
    Dimensions,
    Button,
    TouchableOpacity,
    TouchableHighlight,
    TouchableNativeFeedback,
    TextInput,
    WebView,
    Image
} from 'react-native';

import styled from 'styled-components';

class Authorization extends Component {

    render() {

        const div = styled.div`box-shadow: 10px 5px 5px black;`;

return (<Div/>)

}
```
node -v
v8.4.0
npm -v
4.6.1

**Comment by kitten** [comment]
On React Native we’re switching over to a different module which aliases and wraps all react Native components: https://www.styled-components.com/docs/basics#react-native

So instead of doc you would use View

**Comment by anmol-raj** [comment]
Getting this error ---->
**TypeError: styled_components__WEBPACK_IMPORTED_MODULE_2__.default.View is not a function
package.json -**
"dependencies": {
    "expo": "~36.0.0",
    "react": "~16.9.0",
    "react-dom": "~16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-36.0.0.tar.gz",
    "react-native-error-boundary": "^1.1.0",
    "react-native-web": "~0.11.7",
    "styled-components": "^5.0.1",
    "react-native-svg": "9.13.3"
  },




`import` React from "react";
import styled from "styled-components";

const City = props => (

  <Container>
    <Image source={props.image} />
    <Text>{props.text}</Text>
  </Container>
  
);

const Container = styled.View`
  margin-left: 5px;
`;

const Image = styled.Image`
  margin-left: 5px;
  width:36px;
  height: 36px;
`;

const Text = styled.Text`
  margin-left: 5px;
`;

export default `City;`

**Comment by ShaikhahMaasher** [comment]
@anmol-raj getting the same error, did you find a solution for this?

**Comment by Binomi0** [comment]
I found the solution here: https://github.com/styled-components/styled-components/issues/1542#issuecomment-561023152

just `import styled from 'styled-components/native';`
