### ISSUE TITLE
box-shadow

### ISSUE THREAD

**Issue by eeeman1** [styled-components/styled-components#1665]
not working box-shadow on react native, just a gray square without a shadow - 

```
        const Div = styled.View`
            width: 50px;
            height: 50px;
            background: #ccc;
            margin-bottom: 20px;
            box-shadow: 10px 5px 5px #000;
        `;
...
render() {
...
    <Div/>
...
}
```

"styled-components": "^3.2.5"

node -v
v8.4.0
npm -v
4.6.1

p.s. background: linear-gradient(#e66465, #9198e5); - Error: Failed to parse declaration "background: linear-gradient(#e66465, #9198e5)"

**Comment by kristerkari** [comment]
You code example works for me in React Native. 

> p.s. background: linear-gradient(#e66465, #9198e5); - Error: Failed to parse declaration "background: linear-gradient(#e66465, #9198e5)"

This might be why `<Div />` is not rendering correctly for you. React Native does not support CSS gradients. Try removing that line and see if `<Div />` after that.

**Comment by probablyup** [comment]
@eeeman1 were you able to get things working after removing that linear gradient?

**Comment by probablyup** [comment]
This appears to work. https://snack.expo.io/BkdLhDObQ
