### ISSUE TITLE
Set displayName manually

### ISSUE THREAD

**Issue by andraaspar** [styled-components/styled-components#1667]
I would like to set the displayName manually.

# What will it allow you to do that you can't do today?

- Understand markup.
- Debug CSS issues.
- Avoid using Babel / a nonexistent (?) Webpack plugin / React dev tools.

## What will that allow you to do that you can't do today?

- Faster builds.
- Less configuration.
- Makes SC less dependent on build / dev tools → Confidence.

**Comment by andraaspar** [comment]
Basically something like:
```JS
const MyTag = styled.div.withDisplayName('MyTag')``
```

**Comment by kitten** [comment]
You can, and it's quite intuitive :wink:

```
const MyTag = styled.div``
MyTag.displayName = 'MyTag'
```

and that's it :tada: our babel plugin is more specific since we'd like the displayName to include the component name. Without the babel plugin we fall back to this: https://github.com/styled-components/styled-components/blob/master/src/models/StyledComponent.js#L251-L253

**Comment by andraaspar** [comment]
No good. It does not show up in class names. :(

**Comment by andraaspar** [comment]
I am looking to replace a call to `.withConfig({ displayName: ... })` since that is a private API.

**Comment by andraaspar** [comment]
With the method recommended above (Comp.displayName = 'Comp'), the
displayName shows in the React dev tool, but it does not become part of the
class name (sc-cRaPHere instead of Comp-cRaPHere).

**Comment by pitiboy** [comment]
I experience the same as reported by @andraaspar, on using 
```
NewComp = Comp.extend``;
NewComp.displayName='NewComp';
```
I still got the original Comp's name in the className, and not NewComp, with the 1.5.1 babel plugin.
Is there any fix I could use to get the displayName reflected in the classname?

**Comment by probablyup** [comment]
I think this should be fixed by https://github.com/styled-components/styled-components/pull/1755. Can y’all try installing the dev version mentioned in the PR thread?

**Comment by probablyup** [comment]
Hmm ok that might be a bug. I'll examine it further today or tomorrow and maybe revise my PR.

**Comment by probablyup** [comment]
I think this might actually have something to do with https://github.com/styled-components/styled-components/pull/1819. Could you try out `styled-components@3.3.3-2` and let me know @pitiboy?

**Comment by pitiboy** [comment]
thanks for checking this, @probablyup.
I upgraded to 3.3.3, however, the symptoms are the same, the masterclass name just does not wants to be reflected in the classname.

**Comment by mcmillion** [comment]
Any idea why this is closed? This still seems to be an issue.

**Comment by sarneeh** [comment]
Yup, `styled-components` inserts the component variable name into `class` instead of the `displayName` property 😢

**Comment by brianHolonis** [comment]
Is is possible to automatically assign a display name to styled-components or is it necessary to use .withConfig to set the displayName? I'm using typescript. How could I configure it to allow for automatic displayName assignment? Thanks
