### ISSUE TITLE
high order components with conditional rendering not working

### ISSUE THREAD

**Issue by ibreathebsb** [styled-components/styled-components#1670]
## System:
 - OS: macOS High Sierra 10.13.1
 - CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
 - Free Memory: 122.99 MB
 - Total Memory: 8.00 GB
 - Shell: /bin/zsh - 5.3
## Binaries:
 - Node: 6.11.1
 - Yarn: 1.5.1
 - npm: 5.6.0
 - Watchman: Not Found
### styled-components:
 - wanted: ^3.2.5
 - installed: 3.2.5

## Expected Behavior
I'm making a music player, and i have many player buttons, to DRY my code
I write a factory function to generate buttons with some base style and can receive some other style
```js
const commonStyle = `
  display: block;
  width: 24px;
  height: 24px;
  background-repeat: no-repeat;
  background-size: 100%;
`
const IconFactory = (extra) => (styled.i`${commonStyle} ${extra}`)
```
it works fine with my `prev` and `next` button
```js
const IconNext = IconFactory(`background-image: url(${iconNext});`)
const IconPrev = IconFactory(`background-image: url(${iconPrev});`)
```
But when I try to make my main play button with a prop named `playing` display a playing or pause state like:
```js
const IconPlay = IconFactory(`
  background-image: ${({playing}) => (`url(${playing ? iconPause : iconPlay})`)};
`)
```
The background was totally gone, it should display `iconPause` or `iconPlay`...
Am I doing it wrong?

**Comment by mxstbr** [comment]
You need to wrap all your CSS fragments with the css`` helper, that's why we have it!
