### ISSUE TITLE
Manually set class prefix in TypeScript without Babel

### ISSUE THREAD

**Issue by andraaspar** [styled-components/styled-components#1671]
### Bad:

```HTML
<div class="sc-dWudBO kJvgNC"></div>
```

### Good:

```HTML
<div class="ColumnComp-dWudBO kJvgNC"></div>
```

### Solved in TypeScript:

```TS
import { css, styled } from './Theme'

export const ColumnComp = styled('ColumnComp')`
	float: left;
`
```

This is fully supported by syntax highlighting in VS Code, by auto-completion via `typescript-styled-plugin`, and it requires the developer to specify the component name, on the same line as the constant name. The developer can also use `.withComponent('button')` if they need something other than a `div`.

### Made possible by this in `Theme.ts`:

```TS
import * as styledComponents from 'styled-components'

export interface Theme {...}

const { default: _styled, css, injectGlobal, keyframes, ThemeProvider }
	= styledComponents as styledComponents.ThemedStyledComponentsModule<Theme>

function styled<TTag extends keyof JSX.IntrinsicElements = 'div'>(name: string, tag?: TTag) {
	let result = tag ? _styled(tag) : _styled.div

	// Use private API to add class prefix
	result = (result as any).withConfig({
		displayName: name,
	})

	return result
}

export { styled, css, injectGlobal, keyframes, ThemeProvider }
```

**This is using a private API. It would be helpful to have a public API, and a canonical way to do this instead.**

## What will it allow you to do that you can't do today?

- Understand markup.
- Debug CSS issues.
- Avoid using Babel / a nonexistent (?) Webpack plugin / React dev tools.

### What will that allow you to do that you can't do today?

- Faster builds.
- Less configuration.
- Makes SC less dependent on build / dev tools → Confidence.

**Comment by andraaspar** [comment]
This is my second and final attempt to get across the point that having important functionality in a private API / via a compiler only is a bad idea. The former attempt is here: #1667.

React itself did not make `createElement` private. And we all profit. Please consider.

**Comment by andraaspar** [comment]
@Igorbek I know. I tried it. It didn't do a thing. It didn't even throw an error, it just silently failed to work.

And I know I can set up Babel for this (say hello to crappy synthetic default imports). What a hassle. It could be such a simple thing to implement a public call for this. Maybe it's a documentation change only. Oh well. There must be an agenda behind this.

**Comment by probablyup** [comment]
@andraaspar If you could give this another try with @Igorbek's plugin and latest styled-components, I'd appreciate it.

**Comment by andraaspar** [comment]
@probablyup Is there a public API for this now?

**Comment by probablyup** [comment]
@andraaspar `.withConfig` is the API @Igorbek is using to do it, which allows you to pass options like  `displayName`.

**Comment by ShanonJackson** [comment]
This is already possible with the "typescript-plugin-styled-components" which will automatically achieve the same functionality for you if you put it in your webpack build.

**Comment by ForestJohnson** [comment]
If you want to use babel,  i just looked into it, it looks like it actually works... sometimes... https://github.com/styled-components/styled-components/issues/2318#issuecomment-578038045
