### ISSUE TITLE
Atom + TypeScript support

### ISSUE THREAD

**Issue by Ky6uk** [styled-components/styled-components#1674]
I found there is lack of highlighting / autocompletion support for the Atom IDE when project using TypeScript language only.

**Comment by kitten** [comment]
Is this something you can file in a repo that is dedicated to the TS syntax for Atom? Maybe they can reintegrate parts of language-Babel?

**Comment by Ky6uk** [comment]
@kitten I am not sure how it works internally in Atom. I found it not so convenient to use `styled-components` when I tried to use this library in TS project. I hope Atom is "enough-hackable" for that. :)

**Comment by Ky6uk** [comment]
I found some info in https://github.com/atom/language-typescript/issues/10. Looks like VSCode have support `styled-components` for `ts`/`tsx` files as well.

**Comment by Ky6uk** [comment]
@probablyup Is it fixed or just dropped?

**Comment by d-ivashchuk** [comment]
@Ky6uk Have you found an adequate solution to  highlighting / autocompletion  of styled-components in atom in tsx? I think I've stumbled on some examples that hacked language-Babel somehow, but still they were not perfect. I am also in the process of configuring atom with typescript so if you find something ping me please!

**Comment by Ky6uk** [comment]
@d-ivashchuk unfortunately my current solution is the using VSCode instead of Atom. VSCode has both of autocompletion / highlighting things when you are using TS + SC. And I see the problem in Atom won't be fixed in future. 

Also as a bonus I got much better and faster TS integration.
