### ISSUE TITLE
Different styles on server vs client when using 3rd party component lib with styled-components

### ISSUE THREAD

**Issue by Fumler** [styled-components/styled-components#1676]
## Issue
Thank you for all your work with styled-components, it's a pleasure to use, but unfortunately we are experiencing an issue with it currently.

The problem is that we use a component library that's created with react 16.3 and styled-components 3.2.5 (+ babel sc plugin). (Very similar to https://github.com/diegohaz/reas - bug exists with both libraries, but reas is using styled-components 3.1.6)

When we use this library in our nextjs app, some styles do not work client side, from the server everything looks good, but client side the style is wrong as you can see here:

```css
/* SERVER */
/* sc-component-id: sc-kafWEX */
.sc-cIShpX + * .HJRRB{ stuff }

/* CLIENT */
/* sc-component-id: sc-kafWEX */
.sc-cIShpX+*.HJRRB{ stuff }
```

The issue is that it removes the space between `*` and `.`.

The source (link below) component:
``` javascript
  // This works on server but not client
  ${OuterWrapper} + * & {
    background: palevioletred;
    h1 {
      color: papayawhip;
    }
  }
```

I have provided two links to the app and links to two different branches below because as you can see there, the issue is only there if we import and use the external library, the syntax above works fine otherwise. We have tried with two different external libraries using styled-components and it happens with both. And it works server-side.

In our own app we also use (but not in the reproduction app):
```javascript
config.resolve.alias = {
	'styled-components': path.resolve(__dirname, 'node_modules', 'styled-components')
}
```
to be sure we don't have two versions of styled-components.

Should also note that this bug was not there when both app and library used styled-components 3.1.6

I appreciate everything you do and hope someone can help.

## System:
 - OS: macOS High Sierra 10.13.3
 - CPU: x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
 - Free Memory: 357.23 MB
 - Total Memory: 16.00 GB
 - Shell: /bin/zsh - 5.3
## Binaries:
 - Node: 9.8.0
 - Yarn: 1.5.1
 - npm: 5.6.0
 - Watchman: Not Found
### babel-plugin-styled-components:
 - wanted: ^1.5.1
 - installed: 1.5.1
### styled-components:
 - wanted: ^3.2.5
 - installed: 3.2.5

### Apps:
* Example with lib (not working): https://sc-next-bug-mizjydjbep.now.sh/
* Example without lib (working): https://sc-next-bug-jfmvebfqne.now.sh/

### Source: 
* https://github.com/Fumler/sc-next-bug/tree/master (not working)
* https://github.com/Fumler/sc-next-bug/tree/working (working) 

## Expected Behavior
Expect CSS to be same on server and client even if we use styled-components in the external library as well as in our app.

## Actual Behavior
CSS is different on client vs server

**Comment by kitten** [comment]
Judging from the class names that the plugin yields it would seem that the ssr option is not enabled on it. This will be necessary so that SSR works for all users of the library :)

Can you open an issue on their repo instead please? Let’s see if we can get this resolved

cc @diegohaz

**Comment by kitten** [comment]
@diegohaz Can you also make sure that styled-components is a peer dependency apart from enabling the plugin’s ssr option please? https://www.styled-components.com/docs/faqs#i-am-a-library-author-should-i-bundle-styledcomponents-with-my-library

**Comment by Fumler** [comment]
@kitten This same issue happens with our own library as well, which does use babel-plugin-styled-components with ssr option enabled (and styled-components as a peerDep). I only used reas as an example because it is an open source project and it happens with that as well.

**Comment by diegohaz** [comment]
I'm going to have a look at this. But shouldn't npm/yarn resolve ^3.1.6 and 3.2.5 to the same version? Maybe this is a regression introduced between 3.1.6 and 3.2.5?

**Comment by kitten** [comment]
@Fumler This looks suspicious:

```css
/* CLIENT */
/* sc-component-id: pages__InnerWrapper-s1xwgnjr-1 */
.pages__OuterWrapper-s1xwgnjr-0+*.iiRESd {}

/* SERVER */
/* sc-component-id: pages__InnerWrapper-s1xwgnjr-1 */
.pages__OuterWrapper-s1xwgnjr-0 + * .iiRESd {}
```

It looks like you're using `minify` but only on one side. Either disable the option entirely or make sure that it matches if you have separate server and client babel configs :wink:

**Comment by kitten** [comment]
@diegohaz it does, but using `peerDependencies` is always safer

**Comment by Fumler** [comment]
@diegohaz 

yarn.lock
```
"@aller/shiny@github:dbmedialab/shiny#156c7ac":
  version "0.3.0"
  resolved "https://codeload.github.com/dbmedialab/shiny/tar.gz/156c7acbb51feaf3d64cd0d534360cd82ad700d9"
  dependencies:
    "@aller/eslint-config-aller" "0.5.2"
    "@maji/react-prism" "1.0.1"
    "@storybook/addon-links" "3.4.1"
    "@storybook/react" "3.4.1"
    aurora-deep-slice-merge "github:soldotno/aurora-deep-slice-merge"
    babel-plugin-styled-components "1.5.1"
    babel-plugin-system-import-transformer "3.1.0"
    babel-plugin-transform-object-assign "6.22.0"
    intersection-observer "0.5.0"
    picturefill "3.0.2"
    polished "1.9.2"
    pretty-format "22.4.3"
    prism-themes "1.0.0"
    prismjs "1.14.0"
    prop-types "15.6.1"
    react "16.3.1"
    react-dom "16.3.1"
    react-intersection-observer "3.0.3"
    react-rating "1.1.2"
    react-stickyfill "0.2.3"
    react-styled-flexboxgrid "2.2.0"
    striptags "3.1.1"


babel-plugin-styled-components@1.5.1, babel-plugin-styled-components@^1.5.1:
  version "1.5.1"
  resolved "https://registry.yarnpkg.com/babel-plugin-styled-components/-/babel-plugin-styled-components-1.5.1.tgz#31dbeb696d1354d1585e60d66c7905f5e474afcd"
  dependencies:
    "@babel/helper-annotate-as-pure" "^7.0.0-beta.37"
    babel-types "^6.26.0"
    stylis "^3.0.0"

styled-components@^3.2.5:
  version "3.2.5"
  resolved "https://registry.yarnpkg.com/styled-components/-/styled-components-3.2.5.tgz#b5d5d7d618ab240ff10602b5ca5886b8db3d0a0d"
  dependencies:
    buffer "^5.0.3"
    css-to-react-native "^2.0.3"
    fbjs "^0.8.16"
    hoist-non-react-statics "^2.5.0"
    is-plain-object "^2.0.1"
    prop-types "^15.5.4"
    stylis "^3.5.0"
    stylis-rule-sheet "^0.0.10"
    supports-color "^3.2.3"
```

@kitten Minification is what puzzled me as well, but `.pages__OuterWrapper-s1xwgnjr-0 + * .iiRESd {}` style comes from the nextjs app, not from the component library. And the minifaction does not happen unless I import the external component library.

As you can see here: https://sc-next-bug-jfmvebfqne.now.sh/ exactly the same app and code except we do not import the component library.

While here: https://sc-next-bug-mizjydjbep.now.sh/ we import reas and the problem is there. The palevioletred styletag is not applied because of the missing spaces in the client.

I don't understand why importing a component library that does nothing to the `pages_OuterWrapper` style would suddenly minify everything?

**Comment by kitten** [comment]
@Fumler can you post a reproduction, e.g. some source code or similar. I don't think it's possible for me to investigate this further otherwise. It seems that the rule is present but derived from `*.class` so that it's invalid and different:

<img width="667" alt="screen shot 2018-04-11 at 17 51 47" src="https://user-images.githubusercontent.com/2041385/38631228-0b628908-3db1-11e8-9acc-87410363a597.png">

But it's impossible for me to tell:

- What the source CSS is
- Whether it's the minification
- Where it applies the minification
- Whether it's stylis
- Whether it's the speedy rule tags in production
- etc

😢

**Comment by SindreSvendby** [comment]
I should prop have posted the added info I did here instead of just mention it from fumler/sc-next-bug#1.

The relation between that now apps this is linked before is:

[master](https://github.com/Fumler/sc-next-bug): https://sc-next-bug-mizjydjbep.now.sh/
[working](https://github.com/Fumler/sc-next-bug/tree/working): https://sc-next-bug-jfmvebfqne.now.sh/

To see the different see the PR: https://github.com/Fumler/sc-next-bug/pull/1

As we see from this PR the only diff between them is the import and usage of 'reas'
And reas is only an example, we see the same bug when using a component from https://github.com/dbmedialab/shiny/. All other styles is correctly render on the server and the client correctly matches these.
```
  // This works on server but not client
  ${OuterWrapper} + * & {
    background: palevioletred;
    h1 {
      color: papayawhip;
    }
  }
```
If we change the selector to be
```
 ${OuterWrapper} + div & {
    background: palevioletred;
    h1 {
      color: papayawhip;
    }
  }
```
the client and server side styles is matching. I will create more apps and branches to reproduce that also.

**Comment by kitten** [comment]
@SindreSvendby @Fumler can you change your `.babelrc` please and try to set `"minify": false`? https://github.com/Fumler/sc-next-bug/blob/master/.babelrc#L6

**Comment by Fumler** [comment]
Tried setting `"minify": false` earlier, did not change anything.

**Comment by kitten** [comment]
@SindreSvendby @Fumler Alright, so this was extremely hard to debug (🤦‍♂️) but it seems that `cascade: false` was erroneously set on the stylis rule splitter that is used for SSR rehydration. I am not entirely sure why this hasn't come up before, but I suppose anyone who uses **no** space combinators in their CSS selectors won't see this bug...

Anyhow, #1677 will fix this

**Comment by Fumler** [comment]
Very awesome! Thank you @kitten for the quick solve 🎉 😄
