### ISSUE TITLE
Improve helper type operators through TypeScript 2.8

### ISSUE THREAD

**Issue by miZyind** [styled-components/styled-components#1683]
At that time before TypeScript 2.8, there wasn't a clean solution about how to "Omit" some keys from an existing interface.

But now we can use the new conditional type "Exclude" to improve type safety!

We can drop these helper type operators and rewrite some definition:
```typescript
// Line 73 ~ 76 in node_modules/styled-components/typings/styled-components.d.ts
// Helper type operators
type Diff<T extends string, U extends string> = ({ [P in T]: P } & { [P in U]: never } & { [x: string]: never })[T];
type Omit<T, K extends keyof T> = Pick<T, Diff<keyof T, K>>;
type WithOptionalTheme<P extends { theme?: T; }, T> = Omit<P, "theme"> & { theme?: T; };
```

After:
```typescript
// Helper type operators
type WithOptionalTheme<P extends { theme?: T; }, T> = Pick<P, Exclude<keyof P, "theme">> & { theme?: T; };
```

And now we get the benefit (Go to current props' definition & props' type checking)!
![improve](https://user-images.githubusercontent.com/21041375/38709653-b4f0ef44-3eee-11e8-9588-15e2a016c53e.png)

**Comment by leebenson** [comment]
Perhaps related: In Typescript v2.9.0-dev.20180519:

> node_modules/styled-components/typings/styled-components.d.ts:76:48 - error TS2344: Type 'keyof T' does not satisfy the constraint 'string'.
>   Type 'string | number | symbol' is not assignable to type 'string'.
>     Type 'number' is not assignable to type 'string'.
> 
> 76 type Omit<T, K extends keyof T> = Pick<T, Diff<keyof T, K>>;

**Comment by probablyup** [comment]
Please see https://github.com/styled-components/styled-components/issues/1778. Would love a fix contributed to that effort as y'all are able 👍
