### ISSUE TITLE
All my styled components generate an empty css class

### ISSUE THREAD

**Issue by sylvhama** [styled-components/styled-components#1686]
## Environment
I could reproduced on styled-components v3.2.5 and 3.2.3 and react-scripts 1.1.0 and 1.1.1.

## Reproduction

https://codesandbox.io/s/n3v5mnqjj4

## Steps to reproduce
You can inspect the red title or the div container.

## Expected Behavior
It should only have one css class specifying the given css.

## Actual Behavior
It creates a second empty css class for each styled component.

**Comment by probablyup** [comment]
@sylvhama no need to worry about this, it's expected.

styled-components actually generates a minimum of two classes per element: a stable class to represent the element itself (used for [component selectors](https://www.styled-components.com/docs/advanced#referring-to-other-components) mostly), and one or more classes used to represent particular rulesets. Dynamic styles will cause more than one additional class to be created.
