### ISSUE TITLE
Styled-component breaks a library on production mode

### ISSUE THREAD

**Issue by Hunsu** [styled-components/styled-components#1687]
## Environment

  OS: Linux 4.13
  Node: 8.1.4
  Yarn: 1.0.1
  npm: 4.6.1
  Watchman: 4.9.0
  Xcode: N/A
  Android Studio: Not Found

## Reproduction
https://snack.expo.io/SJbcMwynG
## Steps to reproduce
Use the library react-native-image-progress with styled component on react-native. Run the example on production mode `exp start --no-dev --minify`  
I run the example on my Android phone.

## Expected Behavior
The apps works and doesn't crashes.
## Actual Behavior
The app crashes with the error TypeError: Cannot call a class as a function. The library works without styled-component.

**Comment by probablyup** [comment]
I believe this is related to https://github.com/styled-components/styled-components/pull/1751. Will publish a patch release this weekend.

**Comment by Hunsu** [comment]
I though that the import "styled-components/native" was deprecated a while ago.

**Comment by probablyup** [comment]
Ah! You're totally right. Full disclosure, I don't use React Native at all 🙈disregard that comment.

I do think the core issue is solved by that merged PR though. Will comment back when I push the patch release.

**Comment by probablyup** [comment]
@Hunsu could you check out https://github.com/styled-components/styled-components/releases/tag/v3.3.2? I think it might fix your issue.

**Comment by Hunsu** [comment]
OK I will try it this evening.

**Comment by Hunsu** [comment]
Yes the bug is resolved. Thanks.
