### ISSUE TITLE
interop / move dom related collections into separate repo?

### ISSUE THREAD

**Issue by drcmda** [styled-components/styled-components#1688]
Regarding this file: https://github.com/styled-components/styled-components/blob/master/src/utils/domElements.js

And perhaps others. This stuff creeps up plenty depending on which libs are bundled in. For instance it's almost the same in react-spring: https://github.com/drcmda/react-spring/blob/master/src/animated/targets/react-dom.js and here's some of it in animated: https://github.com/animatedjs/animated/blob/master/src/targets/react-dom.js

There's also normalize-css-color, https://github.com/react-community/normalize-css-color/blob/master/index.js Not sure if styled-components has a use for it.

But anyway, would it make sense to have one sensible, modular repo for this stuff so that knowledge, spec-updates, etc. could be shared while also relieving bundles a bit?

**Comment by probablyup** [comment]
So we're actually working on a few strategies to drop those various lists in the next major version.

1. dom element list will be droppable once https://github.com/styled-components/babel-plugin-styled-components/issues/125 is in
2. the attribute whitelist will be droppable once this is in: https://github.com/styled-components/styled-components/pull/1682

`normalize-css-color` looks cool, but I don't think we have a need for it, at least on the web side. Maybe for native @kitten?
