### ISSUE TITLE
Expose forceServer option from ServerStyleSheet

### ISSUE THREAD

**Issue by kiddkai** [styled-components/styled-components#1692]
## Environment

```js
- Node.js
- JSDom
- vm
```

## Steps to reproduce

We are currently running our React runtime under a client-like environment. And we just upgrade to styled-component@3. And we figured out that when SC found out that if `document` exists. It will force itself into `client` mode, and when I try to use:

https://www.styled-components.com/docs/advanced#server-side-rendering

It will throw a error during `new ServerStyleSheet()` because it is assuming I am under a browser environment. 

And I also found out that in the `StyleSheet` class, I can call the static `reset` method to force the environment to become server mode. And locally, I am doing things like:

```js
import {
    ServerStyleSheet,
    __DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS,
} from 'styled-components';

const { StyleSheet } = __DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS;

StyleSheet.reset(true);

const sheet = new ServerStyleSheet();
```

And it works, so I am wondering if `ServerStyleSheet` could expose a `forceServer` option so we don't need to use this hack to make it work? So we won't be haunted by spooky ghosts?

## Actual Behavior

💥 
```js
The clone method cannot be used on the client!- Are you running in a client-like environment on the server?- Are you trying to run SSR on the client?
stack: Error
       at Object.throwCloneTagErr [as clone] (evalmachine.<anonymous>:84285:9)
       at evalmachine.<anonymous>:84824:24
       ...
```

**Comment by probablyup** [comment]
@kiddkai what's your definition of a client-like environment? We go so far as to look for the existence of [HTMLElement classes](https://github.com/styled-components/styled-components/blob/master/src/constants.js#L11) before deciding to render in browser mode. I think that's pretty reasonable.

**Comment by kitten** [comment]
@kiddkai can you also provide us with the version you’re using please?

**Comment by kiddkai** [comment]
Hey @probablyup , because the current frontend limitation we are having at the moment, we create a separate [vm](https://nodejs.org/api/vm.html) which includes some browser api like  document, window to make sure our js is not broken during server-side rendering.  But the `insertRule` there doesn't really works with the environment we've setup. So I use the `StyleSheet` internal API at the moment.

**Comment by kiddkai** [comment]
Hey @kitten , the current version in our `package.json` is `3.2.5`. Yeah, and we are only calling the `reset` right after we loads the server bundle. I can see why it's quite dangerous, but it seems like it's almost impossible for us now to having both a `client-like` environment with server-side rendering :(

**Comment by damassi** [comment]
I just ran into this issue when testing a library I'm writing in Jest. Is there any way we can expose `__DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS` as an API option? It seems rather extreme for what the ultimate aim is.

**Comment by bwhitty** [comment]
@kitten @probablyup a use case I have is running an integration test suite for my app server's SSR via Jest.

Since we're doing SSR with code splitting, I'm running a full webpack build of the server and then making calls against it using `supertest`. It looks like this:

```js
describe('app server', () => {
  let main;
  let app;

  beforeAll((done) => {
    // build all the necessary dependencies of the application server
    let compilationCount = 0;
    const compilerCallback = (err) => {
      if (err) {
        done(err);
      }

      compilationCount += 1;

      if (compilationCount === 2) {
        // require lazily so middlewares which require build files to be present (like favicon)
        // do in fact have their files ready
        main = require('app/app').main; // eslint-disable-line global-require
        done();
      }
    };

    // build both client and server since they both emit assets necessary for the app server
    // to properly run
    const clientCompiler = webpack(webpackClientConfig);
    const serverCompiler = webpack(webpackServerConfig);

    clientCompiler.run(compilerCallback);
    serverCompiler.run(compilerCallback);
  }, 100000);

  describe('basic application UI route', () => {
    test('returns rendered HTML with static asset references configured correctly', async () => {
      // now get the app server so all dependencies are ready
      app = await main(await getPort());

      expect.assertions(2);

      const {
        statusCode,
        text,
      } = await request(app).get('/');

      expect(statusCode).toBe(httpStatusCodes.OK);
      expect(text).toEqual(expect.stringContaining('<style data-styled'));
    });
  });
});
```

I've tried adding the call to `StyleSheet.reset()` within the top-level `describe()` block, and I've also tried using https://jestjs.io/docs/en/configuration.html#testenvironment-string and the 
```js
/**
 * @jest-environment node
 */
```
magic comment to force jest to run as a "node-like" environment, but neither stop Styled Components from throwing. 

Any ideas?

**Comment by bwhitty** [comment]
For anyone reading this in the future, I was able to fix this by a combination of two things:

1. Add the spooky hack *to my application code* (this is super undesirable)
```js
  // server renderer middleware
  const sheet = new ServerStyleSheet();
  const { StyleSheet } = __DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS;
  StyleSheet.reset(true);

  // render the app to a string
  const markup = renderToString(sheet.collectStyles(...));

   ...
```
2. Make sure Jest is running in "node" environment mode. `app-integration-test.js`:
```js
/**
 * @jest-environment node
 */

expect(...)
```

I would love to figure out how to do this without needing to modify application code...

**Comment by taylorc93** [comment]
I'm running into the exact same use case / issue as @bwhitty. His solution worked but, as he stated, it's super undesirable

**Comment by undrafted** [comment]
Is there any further update to this issue? Or we don’t have a choice but get haunted by spooky ghosts?

**Comment by probablyup** [comment]
@undrafted have you tried v4 or v5? the behavior is different

**Comment by undrafted** [comment]
@probablyup yes i'm using ^4.3.2

**Comment by kitten** [comment]
Closing due to age, inactivity, missing reproduction, or lack of details.

Generally speaking, this is now possible and has been resolved a while ago. The `ServerStyleSheet` already forces server-side behaviour, so if it's used manually it should switch everything over appropriately: https://github.com/styled-components/styled-components/blob/d96101a102b59a8f9ac4b6f278594674897282bb/packages/styled-components/src/models/ServerStyleSheet.tsx#L20
