### ISSUE TITLE
Typing for `innerRef` does not support React 16 `RefObject`

### ISSUE THREAD

**Issue by garycourt** [styled-components/styled-components#1695]
Typescript throws an error when trying to use React 16's new RefObject with `innerRef`. Example:

```
const ref = React.createRef();
<StyledComponent innerRef={ref}/>
// Types of property 'innerRef' are incompatible.
// Type 'RefObject<any>' is not assignable to type '(instance: any) => void'.
```

The offending line appears to be: https://github.com/styled-components/styled-components/blob/6cff64644d22e447504e917ffed4bffdf8c93b5e/typings/styled-components.d.ts#L15

It should probably be: `innerRef?: Ref<any>;`

**Comment by Keraito** [comment]
Could I try my hands on this to familiarize myself with the `styled-components` codebase?

**Comment by probablyup** [comment]
I believe there is already a PR for this?

**Comment by Keraito** [comment]
Oh yeah I think #1711

**Comment by codepunkt** [comment]
That's correct. Feel free to improve these typing, if possible. Thanks for reporting!
