### ISSUE TITLE
[TypeScript] Implement generics for tagged template literals

### ISSUE THREAD

**Issue by nickbreaton** [styled-components/styled-components#1697]
Hello styled-components team,

Today support for  passing generic types to tagged template literals was [merged](https://github.com/Microsoft/TypeScript/pull/23430) into TypeScript master and is pending release in TypeScript 2.9. This opens the door to what is, in my opinion, a more stream lined way of typing components:

```ts
interface Props {
  inverse: true;
}

const Button = styled.button<Props>`
  color: ${props => props.inverse ? 'white' : 'black'};
  background: ${props => props.inverse ? 'black' : 'white'};
`
```

This is opposed to the currently suggested way documented [here](https://www.styled-components.com/docs/api#caveat-with-classname).

I am opening this issue to start a discussion around if this will be supported. If help is needed I may be able to contribute. The original issue on the TypeScript repo was opened in regards to the styled-components API. That issue is visible [here](https://github.com/Microsoft/TypeScript/issues/11947). 

Thanks for building such an awesome tool and I look forward to better TypeScript. 

__Edit:__ This would also potentially introduce a way for the type checking props when using components `<Button inverse>Example</Button>` just like normal stateless and class based components allow.

**Comment by beshanoe** [comment]
I've checked whether it's supported out of the box with typescript@next, and it turned out that it is, but with some issues. Here's the interface responsible for handling tagged templates in `styled-components.d.ts`:
```ts
export interface ThemedStyledFunction<P, T, O = P> {
  (strings: TemplateStringsArray, ...interpolations: Interpolation<ThemedStyledProps<P, T>>[]): StyledComponentClass<P, T, O>;
  <U>(strings: TemplateStringsArray, ...interpolations: Interpolation<ThemedStyledProps<P & U, T>>[]): StyledComponentClass<P & U, T, O & U>;
  attrs<U, A extends Partial<P & U> = {}>(attrs: Attrs<P & U, A, T>): ThemedStyledFunction<P & A & U, T, O & U>;
}
```

if you just have a code like this:
```ts
export const RedBox = styled.div<{foo: string}>`
  background: red;
  ${props => props.foo} // Error: foo doesn't exist
`;
```
It won't work because looks like first declaration in the interface witch is without `<U>` hits first and compiler doesn't pass generic, but if we remove or comment out this first declaration:
```ts
export interface ThemedStyledFunction<P, T, O = P> {
  <U>(strings: TemplateStringsArray, ...interpolations: Interpolation<ThemedStyledProps<P & U, T>>[]): StyledComponentClass<P & U, T, O & U>;
  attrs<U, A extends Partial<P & U> = {}>(attrs: Attrs<P & U, A, T>): ThemedStyledFunction<P & A & U, T, O & U>;
}
```
Everything starts working fine.
The question here, do some other places in library should have a support for such a syntax? There's already a possibility to add props type like:
```ts
const Box: React.SFC<{foo: string}> = props => <div>{props.foo}</div>

const StyledBox = styled(Box)`
  background: red;
  ${props => props.foo} // foo exists
`
```
or
```ts
const StyledBox = styled.div.attrs<{foo: string}>({foo: 'red'})`
  background: red;
  ${props => props.foo} // foo exists
`
```
Does it make sense to add other props types to already typed component?

**Comment by ralexand56** [comment]
That's amazing! Any chance we'll get an update for the styled-components typed definitions to fix that issue?

**Comment by tomitrescak** [comment]
Hi, it does not work for me. Following:

```typescript
import { Input } from 'semantic-ui-react';
 
interface InputProps {
  icon: string;
  placeholder: string;
}

const Search = styled(Input)`
  width: 300px;
`;

const Foo = () => <Search icon="search" placeholder="Find Process..." />;
```

throws error

```
Type '{ icon: string; placeholder: string; }' has no properties in common with type 'IntrinsicAttributes & IntrinsicClassAttributes<Component<ThemedOuterStyledProps<WithOptionalTheme...
```

**Comment by probablyup** [comment]
Please see https://github.com/styled-components/styled-components/issues/1778. All efforts for TS improvements that require 2.9 should be consolidated there!

**Comment by tomitrescak** [comment]
That’s so sad to see. You are going the other way as many package developers who maintain consistent typings. It will now depend on the community to catch up with api changes. Anyway, this is still open source so I’ll keep quiet and enjoy this great package :)

**Comment by probablyup** [comment]
It’s not sad, it’s a practical decision based on the incredible volume of
issues we receive about typings and the lack of interest by myself and the
rest of the core team to maintain them.

This isn’t a TS-based repo, so typings will always play second fiddle to
the code. We simply can’t keep up and need to ensure our time and attention
are entirely devoted to making the library better, not triaging issues
around stuff we don’t maintain ourselves.

**Comment by tomitrescak** [comment]
I understand where this is coming from. Creating typings for complex API is never easy (unless you go typescript from the beginning). Yet, once a stable typing definition is up and running, API changes tend to take minimum time to update typings. Anyway, keep up the great work and let’s hope the community will be able to keep up, I’ll pitch my efforts in as much as I can.

**Comment by gilbsgilbs** [comment]
@probablyup Sad for the users, not for the team :wink: . Still, I totally understand that the amount of work isn't worth it and thanks for being honest about it. You should mention this in #1778, rather than “to allow the community to type the library at their own pace elsewhere”. DefinitelyTyped provides a far worse user experience than built-in types, no doubt about it.

Thank you for the amazing work so far anyways. That's all that counts.

**Comment by Bartekus** [comment]
Try it like this:
```
// before
export const Anchor = styled.a`
  ${styles};
`;
```

```
// after
export const Anchor = styled<{}, any>('a')`
  ${styles};
`;
```

**Comment by A1vinSmith** [comment]
> Try it like this:
> 
> ```
> // before
> export const Anchor = styled.a`
>   ${styles};
> `;
> ```
> ```
> // after
> export const Anchor = styled<{}, any>('a')`
>   ${styles};
> `;
> ```

It's a good solution. But I lost my autofocus at the same time.
