### ISSUE TITLE
[BUG] Static props not taken with styled HOC

### ISSUE THREAD

**Issue by JigsWeb** [styled-components/styled-components#1699]
### System:
 - OS: Windows 10
 - CPU: x64 Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz
 - Memory: 1.30 GB / 7.89 GB
### Binaries:
 - Yarn: 1.5.1 - ~\AppData\Roaming\npm\yarn.CMD
 - npm: 5.8.0 - D:\Anthony\Workspace\mpx-front-groceries\node_modules\.bin\npm.CMD

## Reproduction

https://codesandbox.io/s/wn6pkm53v7

## Steps to reproduce

Add a static prop to your component, and export it with styled HOC.

## Expected Behavior

Keep static props

## Actual Behavior

Undefined static props

**Comment by probablyup** [comment]
Dup of #1411
