### ISSUE TITLE
Broken behavior when using Yarn & Webpack Dev Server

### ISSUE THREAD

**Issue by good-idea** [styled-components/styled-components#1701]
I'm having really odd problems when I've installed via Yarn. I've made a sample repo to reproduce the problem - I've essentially stripped out everything I possibly can from an actual project to try to figure out what the cause is.

This *may* be an issue with webpack, but there are no real errors being reported and it's only Styled Components that seems to be affected. I also believe that it has something to do with the bundling process, and not in rendering, because sometimes including or removing imports of various components *or* removing a styled component will change the behavior, even if that component isn't used. (These are all annotated with comments, just do a search for `[PROBLEM]` within the files)

## Environment

Environment:
  OS: macOS High Sierra 10.13.3
  Node: 8.10.0
  Yarn: 1.6.0
  npm: 5.7.1
  Watchman: 4.9.0
  Xcode: Xcode 9.3 Build version 9E145
  Android Studio: Not Found

## Reproduction

https://github.com/good-idea/styled-yarn-problem

## Steps to reproduce

Clone the repo.

`npm install` and `npm run dev`: you should see this working version:

![image](https://user-images.githubusercontent.com/11514928/39079252-a98f618e-44cb-11e8-82b7-e019bf3c5ca7.png)

Switch to yarn: `mv node_modules node_modules-npm && yarn install`, then `npm run dev`. You'll see this:

![image](https://user-images.githubusercontent.com/11514928/39078966-e40ca614-44c6-11e8-8a31-538f11e01c6f.png)

Here, the styles provided by `injectGlobal` are working, but styled components are not.

Then, delete `import Icon from 'Components/Icon/Icon'` from MainTitleBar.js. You'll see this:

![image](https://user-images.githubusercontent.com/11514928/39079013-a400b88e-44c7-11e8-9d64-2693a87bd5b3.png)

Here, all styles are broken. Note that `Icon` isn't even used after being imported.

It still works in production: `npm run build`, then `npx serve public` -> go to localhost:5000 and you'll see the working version again.

**Comment by probablyup** [comment]
It looks like you have some invalid styles. Dev mode is more tolerant of such things, but it won’t work in production.

**Comment by good-idea** [comment]
@probablyup I'll review the styles in use to see if this is the problem, but it *is* working in production, not in dev mode. If invalid styles in dev mode are the problem, then the issue is that this should be reported in the console.

**Comment by rkhayat** [comment]
I am experiencing similar issues..randomly during refreshes styles will disappear.

**Comment by DieLaughing** [comment]
Is this why @font-face doesn't EVER work inside injectGlobal when I use yarn? GREAAAAAAAAAAAAAT.

**Comment by probablyup** [comment]
Here's how it's used:

```js
injectGlobal`
    @font-face {
        font-family: 'Your Font';
        src: url('/path/to/your/font.woff') format('woff');
    }

    html {
        font-family: 'Your Font';
    }
`
```

**Comment by probablyup** [comment]
@good-idea I'll take a look at your example repo tomorrow or Sunday if you don't figure it out before then

**Comment by probablyup** [comment]
@DieLaughing here's an example repo: https://github.com/probablyup/cra-styled-components-font-example

I think where there might be a stumbling block with my initial suggestion of `html { font-family: 'Thing' };` in terms of CRA is they do font styling on the `<body>` tag instead of `<html>`.

You can see the example setup here: https://github.com/probablyup/cra-styled-components-font-example/blob/master/src/App.js#L6-L15

And if you run `yarn start` in the project it works as expected.

**Comment by DieLaughing** [comment]
Thank you so much! This REALLY helps me a bunch. Totally worth broadcasting my shameful idiocy. Thanks again.
