### ISSUE TITLE
Styled attrs is not updated though props change

### ISSUE THREAD

**Issue by Mathieu-R** [styled-components/styled-components#1703]
## Environment
`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`

## System:
 - OS: Linux 4.16
 - CPU: x64 Intel(R) Core(TM) M-5Y10c CPU @ 0.80GHz
 - Free Memory: 965.40 MB
 - Total Memory: 3.76 GB
 - Shell: /usr/bin/zsh - 5.5.1
## Binaries:
 - Node: 9.11.1
 - Yarn: Not Found
 - npm: 5.8.0
 - Watchman: Not Found
### babel-plugin-styled-components:
 - wanted: ^1.5.1
 - installed: 1.5.1
### styled-components:
 - wanted: ^3.2.6
 - installed: 3.2.6

## Reproduction
https://codesandbox.io/s/m5kxzw50v9

## Steps to reproduce

I've got 2 styled-components but `RangeRoundContainer` inline-style does not update although its props (they share the same props: position) change.

```js
const RangeTrack = styled.div.attrs({
  style: props => ({
    transform: `translate(0, -50%) scaleX(${props.position})`
  })
})`
  position: absolute;
  top: 50%;
  left: 0;
  width: 100%;
  height: 100%;
  background: #FFF;
  transform-origin: 0 50%;
`;

const RangeRoundContainer = styled.div.attrs({
  style: props => ({
    transform: `translateX(${props.position * 100}%, -50%)`
  })
})`
  position: relative;
  width: 100%;
  background: 0 0;
  border: none;
  outline: none;
`;
```

## Expected Behavior

The inline style of the two styled-components should update as props `position` change.

## Actual Behavior

The inline style of `RangeRoundContainer` does not change.

**Comment by kitten** [comment]
Can you please provide a reproduction? Should be a simple usage issue. You already have the CodeSandbox template in your issue description ;)

**Comment by Mathieu-R** [comment]
Done :grinning:

**Comment by kitten** [comment]
@Mathieu-R That's a React thing; you've got a typo in your style property :wink: This is what you have

```css
translateX(${props.position * 100}%, -50%)
```

But since that's still two coordinates it should use `translate` as in:

```css
translate(${props.position * 100}%, -50%)
```
