### ISSUE TITLE
Not rendering routes when wrapping them with styled-components in production/electron

### ISSUE THREAD

**Issue by gemma-ferreras** [styled-components/styled-components#1705]
## System:
 - OS: macOS High Sierra 10.13
 - CPU: x64 Intel(R) Core(TM) i3-4170 CPU @ 3.70GHz
 - Memory: 2.98 GB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 8.9.4 - /usr/local/bin/node
 - Yarn: 1.3.2 - /usr/local/bin/yarn
 - npm: 5.6.0 - /usr/local/bin/npm
 - Watchman: 4.7.0 - /usr/local/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: ^1.5.1 => 1.5.1 
 - styled-components: ^3.2.6 => 3.2.6 

## Steps to reproduce

When we build for production the router stops working. It works perfectly in development. If we change the UserPanelSectionRouting styled component to a regular div with inline styles the routing will work. 

```
class UserPanel extends PureComponent {

    constructor(props) {
        super(props);
    }

    render() {
        return(
            <MainSceneBackgroundContainer>
                <Menu />

                <UserPanelSectionRouting>
                    <Routes />
                </UserPanelSectionRouting>

            </MainSceneBackgroundContainer>
        )
    }
}


```

```

import styled from 'styled-components';

const UserPanelSectionRouting = styled.div`
    font-family: "Avenir Next";
    background-attachment: fixed;
    background-size: cover;
    flex: 1;
    position: relative;
    overflow-y: auto;
    margin-top: 80px;
    margin-bottom: 80px;
    margin-right: 44px;
`;

export default UserPanelSectionRouting;

```

```
const Routes = (props) => {
    let { match } = props;

    return(
        <Switch>
            <Redirect   exact   from={match.path}   to={`${match.url}/profile`} />

            <Route              path={`${match.path}/history`}          component={History}         />
            <Route              path={`${match.path}/not-authorized`}   component={NotAuthorized}   />
        </Switch>
    )
};

export default withRouter(Routes);


```

## Expected Behavior
It should work as in development.

## Actual Behavior
The routes are not rendering in production.

**Comment by probablyup** [comment]
@gemma-ferreras any chance you could provide a minimal reproduction for us?

**Comment by probablyup** [comment]
Going to close this as it's been a while with no reproduction. Feel free to reopen if it's still not working for you and you can provide something like a codesandbox to reproduce.
