### ISSUE TITLE
testID prop

### ISSUE THREAD

**Issue by charliewilco** [styled-components/styled-components#1706]
working on refactor of react-native-web for styled-components. one thing that's help with RNW is those components have a `testID` that transpiles to the data-attr on the rendered HTML `[data-test-id]`.

i added a  #1698 to add this similar API

```
const View = styled.div` background: red `
...

render () {
  return (<View testID='A_THING_FOR_INTEGRATION_TESTS_TO_FIND' />)
}

```

**Comment by probablyup** [comment]
Closing this also since the PR was closed. Still open to adding the prop for StyledNativeComponent if you change your mind!
