### ISSUE TITLE
Feature request: Option to prepend <style> tags

### ISSUE THREAD

**Issue by TrevorBurnham** [styled-components/styled-components#1707]
I'm migrating an existing app to styled-components. A problem I'm running into is that `<style>` tags generated by styled-components override existing styles, even when they have minimal specificity, because they occur later in the `<head>` than the app's base stylesheet. (See the detailed example below.) To resolve this, I'd like an option to make styled-components render its `<style>` tags at the start of the `<head>` instead of the end of it.

I'm happy to submit a PR to add this functionality to `StyleSheetManager`, if you folks think it's a good idea. At first I was hoping that #1491 would provide a solution for me, but I don't think it's possible to use that feature to inject styles before the end of the `<head>`. Let me know if I'm mistaken!

### Problem example

Let's say that I have a `Paragraph` component in my app:

```jsx
const Paragraph = ({className, ...rest}) => (
  <p className={classNames(className, 'paragraph')} {...rest} />
)
```

I've defined the default styles in a stylesheet:

```css
.paragraph {
  font-size: 16px;
}
```

Downstream, someone wants to render a bigger paragraph

```js
<Paragraph className="big-paragraph" />
```

with a style rule like

```css
.big-paragraph {
  font-size: 24px;
}
```

This works because the app has two stylesheets in its `<head>`: The first has base styles like the `.paragraph` rule, and the second has more specific styles like the `.big-paragraph` rule.

Now let's say that I rewrite `Paragraph` using styled-components:

```jsx
const Paragraph = styled.p`
  font-size: 16px;
`
```

Since styled-components injects the `<style>` tag with that rule at the end of `<head>`, the `.big-paragraph` rule is rendered inoperable! What seems like a harmless refactoring breaks the app's styles.

**Comment by diondiondion** [comment]
> Since styled-components injects the `<style>` tag with that rule at the end of `<head>`

It's not really documented and I haven't tried it myself yet, but it seems like you should be able to control where your styles will be injected using the StyleSheetManager's `target` prop that was introduced in [3.2.0](https://github.com/styled-components/styled-components/releases/tag/v3.2.0); might be worth giving it a try.

**Comment by kitten** [comment]
You could use SSR for that. Actually, you don't even need SSR, I guess. As long as you put this tag at the right place in your HTML, the rehydration logic should be taking care of the position of all future style tags for you:

```html
<style type="text/css" data-styled-components></style>
```

**Comment by TrevorBurnham** [comment]
🤔 Interesting! I’ll try that.

**Comment by TrevorBurnham** [comment]
It actually seems to work well for me (I'm on styled-components@3.2.3), but it'd be nice to have some kind of API guarantee that this functionality won't break in the future. I'm not using SSR.

**Comment by TrevorBurnham** [comment]
@probablyup So, looking over the code, I'm satisfied that what you're suggesting is a stable solution. 👌 I'd like to take you up on that offer to add it to the docs, though: https://github.com/styled-components/styled-components-website/pull/257

**Comment by kitten** [comment]
@TrevorBurnham I think we can simply try to stay aware of this. The tests should also cover this as it's just part of SSR rehydration, so as long as it's in the docs we might be good :+1:

Hope the recent stylesheet/styletags refactor helped you find it quickly :heart:

**Comment by TrevorBurnham** [comment]
Thanks, that's a satisfactory resolution for me. Closing this one out.

**Comment by puru0019** [comment]
I can still face same issue. Unable to load my styled component styles at the end of the head section

![image](https://user-images.githubusercontent.com/23036485/58703839-a6b32680-83c7-11e9-86ac-ad6a889cf1fd.png)
