### ISSUE TITLE
Feature request: Global selector prefix (CSS namespace)

### ISSUE THREAD

**Issue by TrevorBurnham** [styled-components/styled-components#1708]
I have a use case where I'm injecting styled-components code into a third-party page. The page has various style rules that are both broad and high-specificity, such as

```css
.page-body button + button {
  margin-right: 8px;
}
```

that are rather difficult to override; something like

```jsx
styled.button`
  margin: 0;
`
```

lacks sufficient specificity. I could, of course, throw `&`s at the problem on a case-by-case basis:

```jsx
styled.button`
  &&& {
    margin: 0;
  }
`
```

However, doing this case-by-case is very tedious, especially if I bring in components written by other teams; I'd have to extend them just to increase their specificity.

What would be great would be if I could tell styled-components, "Always add this prefix before the selectors you generate." So e.g. if `globalPrefix=".my-app.my-app.my-app"`, then the styles generated by

```jsx
styled.button`
  margin: 0;
`
```

would look something like

```css
.my-app.my-app.my-app .ktSnBx {
  margin: 0;
}
```

This is analogous to the nested import feature in Sass, a popular way to put styles in a namespace: https://stackoverflow.com/a/17491478/66226

I'm happy to work on this feature if you'd welcome a PR.

**Comment by mxstbr** [comment]
Here you go: https://libraries.io/npm/@quickbaseoss%2Fbabel-plugin-styled-components-css-namespace

**Comment by TrevorBurnham** [comment]
No prospect of an official solution, then?

**Comment by mxstbr** [comment]
We probably won't support this given the Babel plugin linked above works perfectly fine :blush: Consider it the official solution!

**Comment by TrevorBurnham** [comment]
> Consider it the official solution!

In that case, I've submitted a PR to mention it in the docs: https://github.com/styled-components/styled-components-website/pull/258

**Comment by kitten** [comment]
@mxstbr @TrevorBurnham maybe before we add it to the docs and turn it into an "official" (OSS amirite) solution, we should contact them again and ask whether it's smarter to move the repository to our org for discoverability for maintainers and users, and accountability. Agreed?

**Comment by TrevorBurnham** [comment]
It would be great to see babel-plugin-styled-components-css-namespace join the styled-components family, though it might be even better to see its functionality added to babel-plugin-styled-components, where it was originally proposed: https://github.com/styled-components/babel-plugin-styled-components/pull/101
