### ISSUE TITLE
Make Interpolation Of Child Components Agnostic

### ISSUE THREAD

**Issue by Undistraction** [styled-components/styled-components#1713]
First a caveat - I appreciate that targeting specific children should be avoided *if possible* using flexbox or generic descendent selectors. I also appreciate that there is a good argument for keeping context in the child components themselves rather than have a parent know about child styles. However, when it comes to layout I think there are many cases where there is a strong argument for the parent defining how its children are laid out. Please note I'm not suggesting that a vanilla react (container) component does any laying out as I think it is important that there is a separation of concerns, so I'm assuming it uses a child styled-component to handle layout. 

```
const Example = () => (
  <ExampleLayout>
    <Child1 />
    <Child2 />
    <Child3 />
  </ExampleLayout>
)
```

In such a case we have really nice API that allows us to interpolate a child component:

```
${Child1} {
    margin-left: 20px;
  }
```

However there are many cases where some of the children are not child components, but vanilla react (container) components. This brings us to the inconsistency. If I want to target a vanilla react  component directly, I cannot use interpolation and I'm forced to use its `className` prop. This leads to styles like this [Full example on Codepen](https://codepen.io/Pedr/pen/yjVMze):

```
const ExampleLayout = styled.div`
  ${Child1},
  .Child2 {}
`
```

The only other workaround is to wrap the vanilla react component using `styled()`, but this in understandably discouraged.

I'm wondering if there is any way to smooth out this inconsistency and make the reference to child components identical for styled components and vanilla react components in the same way that `extend` is being removed in favour of a component-agnostic api using only `styled()`.

**Comment by mxstbr** [comment]
The way interpolating a styled-component works is that we basically do `Child1.className`, which doesn't exist for vanilla React components—so no, this isn't possible unfortunately :confused:

**Comment by Undistraction** [comment]
@mxstbr Could SC determine if the component is a styled-component and if so, behave as it does presently, but if not, execute the component and access its props.className (and use that as the interpolated value)?

**Comment by mxstbr** [comment]
> execute the component and access its props.className (and use that as the interpolated value)?

That might change depending on which props are in, so not really. We don't know which props the component expects and how they affect the rendered class name.

**Comment by Undistraction** [comment]
OK. I can see the problem. Thanks for explaining.
