### ISSUE TITLE
Persian Font Using 'styled-components'

### ISSUE THREAD

**Issue by GitHub1396** [styled-components/styled-components#1716]
Dear all,
I must thank you very much for providing such a fantastic tool. However, I have an issue with Persian font face while aadding it under injectGlobal like this:
injectGlobal`

@font-face {
    font-family: 'sans';
    src: url('./assets/fonts/iran-sans.ttf');
  }
   `
when I import globalStyle from relevant path and reload the page, nothing has changed and style will be set as a default not iran-sans which I had set above.
What's wrong with this code?

Your prompt reply is highly appreciated in advance.

**Comment by evan-scott-zocdoc** [comment]
@GitHub1396 are you using it?

```css
html {
    font-family: 'sans';
}
```

**Comment by GitHub1396** [comment]
@evan-scott-zocdoc  this way works perfect. Thank you very much.

**Comment by probablyup** [comment]
Glad to hear it!

**Comment by DieLaughing** [comment]
where do we put html { font-family: 'sans'; } because this crap happens to me too and this is a piss poor answer.

**Comment by probablyup** [comment]
Use injectGlobal like this:

```js
injectGlobal`
    @font-face {
        font-family: 'Your Font';
        src: url('/path/to/your/font.woff') format('woff');
    }

    html {
        font-family: 'Your Font';
    }
`
```

**Comment by DieLaughing** [comment]
That did not work.

**Comment by DieLaughing** [comment]
To reproduce: download any free font that is super visibly different from any default font. Use create-react-app to make a webpage. Display the custom local font. Now explain to me how you got it to display, because I cannot, nor can I find anything explaining why I cannot.
