### ISSUE TITLE
Filesystem / Create-React-App issue causing majority of styled-components to break.

### ISSUE THREAD

**Issue by Andrew1431** [styled-components/styled-components#1717]
# I'm not sure this belongs here, but...

## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`

## System:
 - OS: macOS High Sierra 10.13.3
 - CPU: x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
 - Memory: 732.56 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 8.11.1 - /usr/local/bin/node
 - npm: 5.6.0 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^2.2.3 => 2.2.3

## Reproduction

Unable to reproduce, seems like a filesystem issue.

## Steps to reproduce

`npm start` inside my create-react-app I've been successfully working on / deploying|building to production since November 1st.

I have extensive use of styled components throughout the app. On friday, the 27th of April, I `npm run build` our application and deployed to production with no issues. Monday I came in to work, launched our application development environment yesterday, and a majority of styled-components are not rendering their styles properly. It's the same with the two interns who started who were the first to see this issue. 

My simplest example as seen in the example below is a simple "Card" component that renders a hovering card.

```javascript
import styled from 'styled-components';

console.log('File is parsing.');

export default styled.div`
  position: relative;
  background-color: white;
  border: 1px solid #E3E3E3;
  box-shadow: ${({ flat }) => flat ? (
    'none'
  ) : (
    '0 3px 6px 0 rgba(0,0,0,0.16)'
  )};
  padding: 16px;
  margin: 64px 0 0 0;
`;
```

This component gets put in the dom, has the `class="sc-jibber isherr"` but none of it's styles are properly applied. I see the console log, `File is parsing.`.

Upon making any change in the file, the next page reload then renders all Cards properly in the application for the rest of the `npm start` session. When I cancel `ctrl + c` the process and restart, the Card component is gone again. It's only specific components that are failing though, some other components in the same component library are working and appearing exactly as expected. 

## Expected Behavior

Styled-components applies it's styles to components the first time they're loaded.

## Actual Behavior

I'm uploading a video to show what is happening, but basically 85% of my app components aren't rendering. Please hold.

https://www.youtube.com/watch?v=DLGGgkGvrTE&feature=youtu.be

For the love of god, been at this for the last 14 hours, if anyone figures this out ... I owe you atleast 4 beers.

**Comment by kitten** [comment]
Do you have a any subdependency (be it your own or external) that also depends on styled-components and is incorrectly set up so that two copies of styled-components are being bundled?

**Comment by Andrew1431** [comment]
Good question, definitely not my own, I will investigate my existing dependencies, but the brutal part here is that no matter how far back I roll my commits, all my components have broken. Also have rolled back:

All package.json versions,
All node / npm versions ( as low as v4 )
Git history right back to january which was still broken. 

I attached a video in the original ticket.

**Comment by Andrew1431** [comment]
@kitten no sir, just checked all my packages dependencies. Nothing else is using styled-components.

**Comment by tabrindle** [comment]
Just to double check - you mind running this, and pasting the output? This will recursively crawl the whole node_modules tree looking for SC.

`npx envinfo --npmPackages styled-components --duplicates --fullTree --clipboard`

**Comment by Andrew1431** [comment]
```andrew@ubuntu:~/code/test$ npx envinfo@latest --npmPackages styled-components --duplicates --fullTree --showNotFound
npx: installed 1 in 1.832s

  npmPackages:
    styled-components: ^3.2.6 => 3.2.6

andrew@ubuntu:~/code/test$```

**Comment by Andrew1431** [comment]
```➜  l4h-frontend git:(develop) ✗ npx envinfo@latest --npmPackages styled-components --duplicates --fullTree --showNotFound
npx: installed 1 in 1.531s

  npmPackages:
    styled-components: ^2.2.3 => 2.4.0```

From y mac, interesting, why is it actually changing versions here.

**Comment by Andrew1431** [comment]
In my original question, it says ^2.2.3 => 2.2.3

**Comment by Andrew1431** [comment]
Yeah not at the same time, sorry, I've been going crazy here with trying idfferent stuff, but in each environment the issues are happening, regardless of version. I might download yarn and try with that but i'm not feeling confident about it.

**Comment by Andrew1431** [comment]
If I mount my <Card> component in our `PrimaryView.js` area, the Card renders properly, and if in the same session I click to the backend admin area (seen in the video), the card is not rendering correctly. It's like it has to do with the view hierarchy. Is there _*anything*_ regarding context that could be breaking styled components? Is there a list of keys that i should stay away from? Obviously `theme` is one of them.

**Comment by Andrew1431** [comment]
Well, I don't have an explanation for it, but it's a code-splitting issue. One which I can not explain. The gains are not worth th esacrifice obviously, and as such I am removing code-splitting from our application.

**Comment by Andrew1431** [comment]
My god gentleman, I found it.

```


const Item = styled.div`
  display: flex;
  align-items: center;
  justify-content: space-between;
  cursor: ${({ onClick }) => !!onClick ? 'pointer' : 'auto'};
  color: rgba(255,255,255,0.8);
  transition: border 0.1s ease-in-out, background-color 0.1s ease-in-out;

  width: 100%;
  height: 80px;

  min-height: ${({ isChild }) => isChild ? '20px' : '40px'};

  &:hover {
    background-color: 'rgba(0,0,0,0.1);
  }

  margin-left: 0.5208vw;
  padding-right: 16px;

  ${media.portrait`
    margin-left: 15px;
    padding-right: 75px;
  `}

  ${media.mobile`
    margin-left: 5px;
    padding-right: 65px;
  `}
`;
```

Check out that &:hover. That code has been in there for as long as I can remember. I can't understand why it only just started causing issues. I was able to restore code-splitting into my application after removing the apostraphe from the `background-color` property. Maybe this is my reproducible bug?

@tabrindle @kitten
