### ISSUE TITLE
Problems with hydration when ssr multiple bundles

### ISSUE THREAD

**Issue by PsiXdev** [styled-components/styled-components#1722]
Hello. I use ssr and my server renders two bundles (on `/first` and `/second` routes, for example). On `/first` route everything is fine. But I have next warning in client console on `/second` route:

> secondbundle.js Warning: Prop `className` did not match. Server: "s1dwm4at-0-sc-exAgwC ghNmJf" Client: "s1dwm4at-0-sc-lhVmIH czisHZ"

That problem appears because of same components having different numbers in `identifiers` hash on client and server:

https://github.com/styled-components/styled-components/blob/f20d26465375aa3a2312ddb5e2d29159fd7a059e/src/models/StyledComponent.js#L26-L27

How it works:
I open `/first` route, server renders it and assigns increasing identifiers to all components in `firstbundle.js`.

https://github.com/styled-components/styled-components/blob/f20d26465375aa3a2312ddb5e2d29159fd7a059e/src/models/StyledComponent.js#L40-L47

When I go on `/second` route, server renders and continues to increase the identifiers of the components, but it does not start from scratch. All because StyledComponent (with `identifiers` hash inside) is singleton:

https://github.com/styled-components/styled-components/blob/f20d26465375aa3a2312ddb5e2d29159fd7a059e/src/index.js#L59-L66

My temporary solution: reset `require` cache before each rendering on server.

```
	...
	delete require.cache[require.resolve('styled-components')];
	render(currentBundleName)();
	...
```

It works, but it's a bad solution.
What do you think about it? Perhaps it is necessary to somehow get rid of the singleton.

**Comment by probablyup** [comment]
@PsiXdev are you using the babel plugin with the SSR option set to true?

**Comment by PsiXdev** [comment]
@probablyup oh sure

**Comment by kitten** [comment]
@PsiXdev make sure that there’s more information for the plugin:

- use a variable instead of export default’ing directly
- make filenames / paths descriptive
- make sure that folders + name are eventually discriptive

If this then still occurs we might have a problem :)

**Comment by PsiXdev** [comment]
I think I can create an example that shows the problem

**Comment by PsiXdev** [comment]
It was not fast, but I figured out more deeply and was able to repeat the problem in clean project. You can see it on https://github.com/PsiXdev/sc-multi-bundles-bug
The problem occurs when using ```const Component = BaseComponent.extend` ... `;```
I think that everything else that I wrote in the first message is true.

**Comment by kitten** [comment]
@PsiXdev yea, `.extend` does not generate a deterministic styled component id, which is one of the reasons why it's flagged for deprecation. Have you tried `styled(BaseComponent)` instead already?

**Comment by PsiXdev** [comment]
@kitten that solved the problem. At least in my example. In application we use more than hundreds extends and I'm not ready to fix them right now. It's strange that there is nothing in the documentation that the `.extend` is out of date. Or I just did not notice.

**Comment by kitten** [comment]
@PsiXdev sorry about that! I haven’t updated the website to reflect this when it came up as an issue.

**Comment by kitten** [comment]
@PsiXdev yep, I’ll go head and close it :) let us know if there’s anything else

And if you’re interested in helping us update the website that’d be :100:
