### ISSUE TITLE
How to avoid unnecessary re-renders?

### ISSUE THREAD

**Issue by brunobertolini** [styled-components/styled-components#1723]
Should not these re-renderers be avoided?

https://codesandbox.io/s/oo31k89q65

See the console

**Comment by kitten** [comment]
No, we rerender every time React is updating the component as you'd expect. We can't tell for sure whether something has changed in the props, as we don't put any restrictions or requirements on them, like purity.

It'd also be more expensive to check first, as usually we just process the CSS again and then check if the generated class-hash is already in the stylesheet. So there's nothing to worry about. Generally in your app, you'd probably want to prevent unnecessary rerenders in your React tree as high as possible, as it wouldn't make sense for styled-components to check each `StyledComponent` individually as there are just too many and they're most of the times rendered as leaf elements.
