### ISSUE TITLE
Next.js "Warning: Prop `className` did not match."

### ISSUE THREAD

**Issue by vjpr** [styled-components/styled-components#1728]
Just noting the solution for me. My babel config was only applying to my server-side and not client-side.

I suggest verifying that your babel config is running on the server-side and client-side, and includes `babel-plugin-styled-components`.

The cause of my config not loading client-side was https://github.com/zeit/next.js/issues/4301#issue-320945743.

**Comment by iwarner** [comment]
@vjpr Hiya could you expand on the solution with some code example of the steps you took to fix.

**Comment by mxstbr** [comment]
Add a `.babelrc` to the root of your Next.js project that has the styled-components Babel plugin. Something like

```JSON
{
  "plugins": ["babel-plugin-styled-components"]
}
```

**Comment by iwarner** [comment]
@mxstbr Thanks I already have this in my Babel, still causing this problem, I will re-open when I can minify my codebase to reproduce.
