### ISSUE TITLE
Invalid class name being generated (first character is number) causing styles to fail

### ISSUE THREAD

**Issue by seankoji** [styled-components/styled-components#1731]
Had a go trying to reproduce with a codepen snippet, but couldn't replicate it properly. I think its to do with the SSR option / deterministic component ID generation. 

It appears styled components is assigning component classnames based on folder/file path structure. For example I have a component

```
/14-offer-radbtn/index.js
```

that file contains a component

```
const HoverIndicator = styled.span`
    opacity: 0;
`;
const StyledLink = const StyledLink = styled.a`
    &:hover {
        ${HoverIndicator} {
            opacity: 1;
        }
    }
`;

const BA14OfferRadbtn = () => (
    <StyledLink>
        <HoverIndicator />
    </StyledLink>
);

export default BA14OfferRadbtn;
```

However the hover effect doesn't work. On closer inspection, it appears that the generated class name is invalid as it starts with a number and is being ignored by the browser
![image](https://user-images.githubusercontent.com/13824565/39796343-54f4d8a2-5399-11e8-8133-63ed82a1f517.png)

generated CSS rule: 
![image](https://user-images.githubusercontent.com/13824565/39796418-affa8e36-5399-11e8-97ea-c5f3d0d093b8.png)

It appears that the class name is generated by looking at the folder path of the file. As the containing folder begins with "14" the class name follows suit invalidly. 

## System:
 - OS: macOS High Sierra 10.13.4
 - CPU: x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
 - Memory: 361.34 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 8.9.4 - ~/.nvm/versions/node/v8.9.4/bin/node
 - npm: 5.8.0 - ~/.nvm/versions/node/v8.9.4/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.5.0 => 1.5.1
 - styled-components: ^3.2.3 => 3.2.6

## Expected Behavior
Valid CSS class name generated. 

## Actual Behavior
Invalid CSS classname generated, starting with a number, which is ignored by the browser

**Comment by probablyup** [comment]
Ooh, good catch. Can you move this over to the babel plugin repo?

**Comment by seankoji** [comment]
created https://github.com/styled-components/babel-plugin-styled-components/issues/138

**Comment by probablyup** [comment]
Excellent, thanks!
