### ISSUE TITLE
Improve Error Message: Cannot read property 'withConfig' of undefined

### ISSUE THREAD

**Issue by Undistraction** [styled-components/styled-components#1734]
At present, calling a tag on `styled` that isn't supported raises a:

> Cannot read property 'withConfig' of undefined

For example: 

```
const Example = styled.hh4``
```

This is pretty cryptic. I'm wondering if this message can be improved to point to the problem more clearly - that a tag has been used that isn't supported.

**Comment by mxstbr** [comment]
Can't really help you with a reproduction :wink: Something's wrong in your build setup most likely.

**Comment by Undistraction** [comment]
Sorry. Accidentally posted too early. Fleshing it out now.

**Comment by mxstbr** [comment]
Probably not, honestly. 😅 We'd have to attach every possible typo and make it throw a more helpful error, but obviously that's not quite feasible.

Sorry!

**Comment by Undistraction** [comment]
I was thinking that given that the error was being dropped by a Promise you could instead catch it there and error with a more informative message.

**Comment by mxstbr** [comment]
Wasn't dropped by a Promise unfortunately!
