### ISSUE TITLE
Small style variations to deeply nested components

### ISSUE THREAD

**Issue by MitchWeiss** [styled-components/styled-components#1735]
I've got a hero panel which contains a series of Step components. A Step has an image, title and subtitle. 

```
const Hero = ({steps}) => (
  <Wrapper>
     {steps.map(step) => (
       <Step
         title={step.title}
         subtitle={step.subtitle}
         img={step.img}
       />}
  </Wrapper>
);
```
```
const Step = ({title, subtitle, img}) => (
  <Wrapper>
    {img}
    <Title>{title}</Title>
    <Subtitle>{title}</Subtitle>
  </Wrapper>
);
```

`<Wrapper>`, `<Title>` and `<Subtitle>` all have default styling applied however each implementation also has some slight variation eg in font-size, color, padding, margin etc. **What is the best way to handle these styling variations?** I have come up with a few options but I'm not sure I like any of them:

1. Provide props
If there were only a few variations then this is fine, but its going to become unmanageable to pass all potential props eg `titleFontSize`, `titleFontWeight`, `titleFontColor`, `subTitleFontSize` etc

2. Add classes
I could add classNames to all the components in Step and then could use nested CSS at the top level to modify child component styles

3. Theme
I'm not too experienced with themes but it seems it would suffer the same issues as providing individual props, the only benefit would be that I can pass down a single `theme` prop. 

Thanks for the advice!

**Comment by kitten** [comment]
> I could add classNames to all the components in Step and then could use nested CSS at the top level to modify child component styles

This one is the least preferred one, I'd say. It's just not something that will keep your StyledComponents highly maintainable.

It might make sense to use props, but be careful about them. Maybe combine `1.` and `2.` and group them into **localised** themes. See styled-theming https://www.styled-components.com/docs/tooling#styled-theming

It might also make sense to just extend all of the three base components and create a variation of `Step` or to switch these using props. This could also be done using `css` mixins in each of the base components.

You could also try to solve as much as possible using `Wrapper` and then use a reverse selector on the other small components: https://www.styled-components.com/docs/advanced#referring-to-other-components

Hope this gives you some ideas 🙌

**Comment by MitchWeiss** [comment]
Thanks for the response @kitten. This definitely feels like a drawback of styled-components and that we have lost the 'c' in 'css'. If anyone else has another recommendation to solve this problem then I would love to hear it!

**Comment by driesg** [comment]
Just to add some more complexity: the base component that @MitchWeiss is talking about is used across different files:
- *Page 1* uses the default Step component
- *Page 2* needs the Step component but with a different font size `<Title>` 
- *Page 3* needs the Step component but with a different font size, padding, background-color for `<Title>` 
- ...

^ those CSS properties are all made up for illustration purposes. 
In this case it isn't possible to use a reverse selector, right? I'd go with the classname option here and end up with `<Title className='title'>` (looks a bit funny though :)). 

I get the benefits of styled components, but with plain old CSS I would've gone with something like
```
.step__title{}
.page2 .step__title{}
.page3 .step__title{}
```

**Comment by driesg** [comment]
oh wait you can use a reverse selector! ignore the above

**Comment by sylvhama** [comment]
I am using the [thene](https://www.styled-components.com/docs/advanced#theming) in my project in order to solve similar issue. 

Your theme is an object, it could contain several font sizes and colors e.g.
```js
export const theme = {
  colors: {
    primary: blue,
    secondary: green
  },
  fontSizes: {
    body: '1rem',
    subtitle: '1.5rem',
    title: '2rem'
  }
};
```

Then I would create all "typography" components such as `SubTitle`, `Title` etc... like this:
```js
const Body = styled.p`
  font-size: ${props => props.fontSizes.body};
`;

const Subtitle = styled.h2`
  color: ${props => props.colors.secondary};
  font-size: ${props => props.fontSizes.subtitle};
  font-weight: ${props => props.bold ? 'bold' : 'normal'};
`;
```
So my Subtitle component can be bold by doing this: ```<Subtitle bold>Hello</Subtitle>```

Then if there are specific cases then I would use [extending styles](https://www.styled-components.com/docs/basics#extending-styles) to create variants in each page.

**Comment by diondiondion** [comment]
> Just to add some more complexity: the base component that @MitchWeiss is talking about is used across different files

My recommendation would be: Don't try to put all variations into a single component. React is great at composition, so use that to create variations of a component that share the same building blocks and you'll end up with a set of super clear, maintainable, and predictable components that are easy to adapt to each scenario. Using the original example, it could look something like this:

```jsx
const Step1 = ({title, subtitle, img}) => (
  <Wrapper>
    {img}
    <Title>{title}</Title>
    <Subtitle>{title}</Subtitle>
  </Wrapper>
);

const Step2 = ({title, subtitle, img}) => (
  <Wrapper align="center">
    {img}
    <Title large>{title}</Title>
    <Subtitle padding="xl">{title}</Subtitle>
  </Wrapper>
);

const Step3 = ({title, img}) => (
  <Wrapper padding="s">
    {img}
    <Title position="top">{title}</Title>
  </Wrapper>
);
```

If needed, you could then write another component that selects the right step to render based on a prop like `layoutName` or similar.

```jsx
const stepMap = {
  default: Step1,
  magical: Step2,
  whimsical: Step3,
}

const StepSelector = ({layoutName, ...otherProps}) => {
  const StepToRender = stepMap[layoutName];

  return <StepToRender {...otherProps} />;
}

const Hero = ({steps}) => (
  <Wrapper>
     {steps.map(step =>
       <StepSelector {...step} />
     )}
  </Wrapper>
);
```

**Comment by probablyup** [comment]
Lots of good suggestions in this thread, but going to close since there isn't anything actionable on our side.
