### ISSUE TITLE
Function results in attrs should not be overridden by component instance attributes

### ISSUE THREAD

**Issue by mvasin** [styled-components/styled-components#1736]
This issue emerged from the [spectrum.chat discussion](https://spectrum.chat/styled-components?thread=bc6034a4-7c91-4f96-9c85-cb3065ec5b7c).

I believe the current `attrs` behaviour regarding props precedence is wrong.

Vanilla react component declarations have final say on how they interpret props coming from component instances.

I can merge a component instance attributes giving them a higher precedence:
```
const PliableDiv = props => {
  const style = {
    ...props.style,
    backgroundColor: "green"
  };

  return <div style={style}>{props.children}</div>;
};

<PliableDiv style={{color: "red", backgroundColor: "blue"}}>Hello</PliableDiv>
```
I can merge a component instance attributes giving them a lower precedence:
```
const OpinionatedDiv = props => {
  const style = {
    backgroundColor: "green",
    ...props.style
  };

  return <div style={style}>{props.children}</div>;
};

<OpinionatedDiv style={{color: "red", backgroundColor: "blue"}}>Hello</OpinionatedDiv>
```

Or I can completely ignore what a component instance is trying to impose:
```
const CarelessDiv = props => {
  const style = {};
  return <div style={style}>{props.children}</div>;
};
< CarelessDiv style={{color: "red", backgroundColor: "blue"}}>Hello</CarelessDiv>
```

Contrary to a standard component's behaviour, function results in styled component `attrs`' are always overridden by component instance attributes:
```
// I want to get rid of the inline style, but I can't!
const CarelessStyledDiv = styled.div.attrs({
  style: props => ({})
})``;

<CarelessStyledDiv style={ color: "red" } />
```

Initially, I stumbled upon this issue when dealing with `children` in `attrs`, but it applies to any props; I use inline style here because it's easier to see - check out the [codesandbox demo](https://codesandbox.io/s/yj19j8212j).

It can be worked around by assigning a different props name, like this: `const Div = styled.div.attrs({style: props => props.instanceStyle})`. But I'd prefer to align the behaviour with ordinary react components.

**Comment by probablyup** [comment]
> Vanilla react component declarations have final say on how they interpret props coming from component instances.

This isn't an equivalent comparison. `attrs` is essentially a second layer of props that are akin to `defaultProps`, with the added bonus of being able to inspect other sibling props at runtime and adjust itself as desired. As such, explicitly passed props will always take priority over `attrs` because they are not a fallback.
