### ISSUE TITLE
Using `withComponent` in react-native?

### ISSUE THREAD

**Issue by breadadams** [styled-components/styled-components#1737]
I'm wondering, is `.withComponent` available for use with react-native?

## Environment
```
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.10.0
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.7.0
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: 3.1 AI-173.4720617
```

## Steps to reproduce

Within a react-native project, create a `styled` component, and try to _extend_ it with `.withComponent`:

```jsx
import styled from 'styled-components/native';

const StyledImage = styled.Image`
  width: 10px;
  height: 10px;
`

const StyledImageBackground = StyledImage.withComponent('ImageBackground');
```

## Expected Behavior
You should be able to use both `StyledImage` & `StyledImageBackground` as individual components, as you can using the same technique with `styled-components` for "web".

## Actual Behavior
![image](https://user-images.githubusercontent.com/5795227/40016967-48d896b2-57b8-11e8-927c-855b2f787027.png)

**Comment by mxstbr** [comment]
ReactNative doesn't have string-based tags. `Component.withComponent('div')` works because `<div>` works without an import—on ReactNative you always have to import the component:

```JS
import styled from 'styled-components/native';
import { ImageBackground } from 'react-native';

const StyledImage = styled.Image`
  width: 10px;
  height: 10px;
`

const StyledImageBackground = StyledImage.withComponent(ImageBackground);
```

**Comment by breadadams** [comment]
Thanks for the quick response @mxstbr, I tried that too but got another red screen - will give it another go and get back to you ✌️

**Comment by breadadams** [comment]
That works perfectly, no idea what popped up before 😅 - thanks again
