### ISSUE TITLE
Nesting Component Selectors inside of functions

### ISSUE THREAD

**Issue by mecarter** [styled-components/styled-components#1743]
I have a question about component selector usage.

My styled components are defining some blocks based on a `prop` passed to the component, like so:
```
const Label = styled.label`
  // some styles
  ${props => props.disabled && `
    // disabled-specific styles
  `}
`;
```

I tried to nest a reference to another component inside of this block, using the component selector pattern. However, it seems that the reference to the component is not run within this block:
```
const Checkbox = styled.input``;

const Label = styled.label`
  // some styles
  ${props => props.disabled && `
    &:hover {
      ${Checkbox} {
        // hover effect for disabled checkbox
      }
    }
  `}
`;
```

Does it makes sense that the component selector should work inside of a block like this? Or would it be better to restructure my styled component in a different way? I like the idea of having blocks of css that only get included based on checks on `props`, like in the example. It feels clean, but I'm very open to suggestions.

**Comment by probablyup** [comment]
Yes that should work. One thing about your code sample that jumped out at
me is I use the css`` helper for that kind of dynamic block vs a basic
template literal. Might be needed for special interpolations to work.

**Comment by mecarter** [comment]
Hey, that worked. Thanks for the help!
