### ISSUE TITLE
Overriding function props using .attrs() does not work

### ISSUE THREAD

**Issue by gausie** [styled-components/styled-components#1744]
## Environment
See the reproduction

## Reproduction
https://codesandbox.io/s/7458jqox6x

## Steps to reproduce
Type into the textbox and observe the output in the console

## Expected Behavior
onChange is overridden and console shows the text in the input box

## Actual Behavior
onChange is not overridden and console shows the raw events coming through

**Comment by gausie** [comment]
On some further research, I believe this is the same issue as #1736. Feel free to close if you agree.

**Comment by sarneeh** [comment]
Have the same issue. But the error I get is `Unknown prop `myProp` on <button> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop`

**Comment by wmertens** [comment]
@gausie this is indeed a duplicate of #1736. @sarneeh you want #1682
