### ISSUE TITLE
v 3.26 and nextjs 6.0

### ISSUE THREAD

**Issue by atanasster** [styled-components/styled-components#1745]
Hi,

Since upgrading to 3.26 from 2.xxx I have huge slowdowns in the app UI with the CPU locked at 100+%. Reviewed the threads related to next.js, including duplicated class names but not sure if I have the same issue
some of the project dependencies:
```
"next": "^6.0.0",
"grommet": "https://github.com/grommet/grommet/tarball/NEXT-stable",
"styled-components": "^3.2.6",
```
repo: https://github.com/atanasster/crypto-grommet

**Comment by probablyup** [comment]
Are you using the babel plugin by any chance? If so, please make sure it's fully up to date. There was a feature we were trying and ultimately disabled because it was making builds incredibly slow.

**Comment by atanasster** [comment]
Thanks for checking. I am using the plugin v 1.5.1. Also the grommet guys are checking if the issue is on their end, i will update this thread as soon as i get more info

**Comment by probablyup** [comment]
@atanasster Any updates on this? Very curious where the issue is. I highly recommend doing some node profiling if you can to try and identify the hot spots.

**Comment by atanasster** [comment]
@probablyup , verry sorry but still no update, the grommet team stated that they have found the issue and working on it but still didnt let me know if its styled-components related or just grommet. I will post this thread again in the grommet slack and try to get an update. I reverted to earlier versions of grommet, as the slowdown was unbearable.

I havent forgotten this thread and will let you know as soon as i have some info.

**Comment by probablyup** [comment]
bump

**Comment by atanasster** [comment]
HI Evan, i didnt get updates on this specific issues, but seems was related to the bew react 16 context API and it is now fixed in grommet.
We can close rhis issue and thanks again for keeping on top of it
