### ISSUE TITLE
Styled Components & x-error-message

### ISSUE THREAD

**Issue by mlecoq** [styled-components/styled-components#1752]
Hi,

I have required field, in order to customize error message on firefox, I have to add x-error-message property on inputs (for Chrome, title is used) 

When I create my own styled input, x-error-message is missing on generated input

## Reproduction

I have made a small example here, in the first input, the x-error-message is missing
https://codesandbox.io/s/m7rx320o1p

## Steps to reproduce
Create a styled input with x-error-message attribute

## Expected Behavior
x-error-message is present in generated input

## Actual Behavior
x-error-message is missing

**Comment by mlecoq** [comment]
Done : #1753

**Comment by probablyup** [comment]
Released in https://github.com/styled-components/styled-components/releases/tag/v3.3.0!
