### ISSUE TITLE
Missing TypeScript type definitions for v3.3.0 style objects

### ISSUE THREAD

**Issue by Wund3r** [styled-components/styled-components#1756]
Seems like there are no corresponding TypeScript definitions for the first-class object support mentioned in the released notes of 3.3.0

#### System:
 - OS: Windows 10
 - CPU: x64 Intel(R) Core(TM) i3-4150 CPU @ 3.50GHz
 - Memory: 8.22 GB / 15.66 GB
#### Binaries:
 - Yarn: 1.6.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
 - npm: 5.0.3 - C:\Program Files\nodejs\npm.CMD

#### Packages used:
 - styled-components: 3.3.0
 - typescript: 2.9.0-rc

## Steps to reproduce

The problem can be reproduced with a few lines of code like
```
import styled from "styled-components";

const Container = styled.div({
  color: "white",
});

export default Container;
```

## Expected Behavior

No TypeScript error shown

## Actual Behavior

TypeScript throws an error
```
Error:(4, 3) TS2345: Argument of type '{ color: string; }' is not assignable to parameter of type 'TemplateStringsArray'.
  Object literal may only specify known properties, and 'color' does not exist in type 'TemplateStringsArray'.
```

**Comment by probablyup** [comment]
Want to add them?

**Comment by probablyup** [comment]
cc @styled-components/typers

**Comment by davidtkramer** [comment]
I'm not sure if this is the right approach, but something like the following might work.  I'm able to get type safety with these modifications but no intellisense.

```typescript
// new type for style objects
type StyleObject<P, T, U> = {
  [K in keyof P]: ((props: ThemedStyledProps<P & U, T>) => P[K]) | P[K];
}

export interface ThemedStyledFunction<P, T, O = P> {
  <U = {}>(strings: TemplateStringsArray, ...interpolations: Interpolation<ThemedStyledProps<P & U, T>>[]): StyledComponentClass<P & U, T, O & U>;
  // new call signature for style objects
  <U = {}>(styles: StyleObject<P, T, U>): StyledComponentClass<P & U, T, O & U>;
  attrs<U, A extends Partial<P & U> = {}>(attrs: Attrs<P & U, A, T>): ThemedStyledFunction<P & A & U, T, O & U>;
}
```

@probablyup I'd be happy to open a PR if this seems like the right direction.

**Comment by probablyup** [comment]
@Igorbek would be a good person to look over this. I don't use typing stuff personally.

**Comment by davidtkramer** [comment]
I realized my solution above only works with React Native due to the component styles being included in the Prop interfaces. I'm working on a solution that will work for both web and native and will open a PR for further discussion when it's ready. 👍

**Comment by Igorbek** [comment]
@davidtkramer your solution is quite close, I think. You can access the type of styles of the component by using `P["styles"]` type operator. That extracts type of `styles` of the given `P extends { styles?: object; }`.

**Comment by davidtkramer** [comment]
@Igorbek, thanks for the tip! I've opened a PR for further discussion here #1837

**Comment by probablyup** [comment]
Hey folks, TS typings for styled-components have been moved to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), so please feel free to move your issue there where you'll receive better community support.
