### ISSUE TITLE
interleaveWithNodeStream not piping data chunks

### ISSUE THREAD

**Issue by jonsanders101** [styled-components/styled-components#1757]
(Using v 3.2.6)

`interleaveWithNodeStream()` doesn’t seem to pipe chunks of data to the response as expected, defeating the performance benefit of React’s `renderToNodeStream()`.

We noticed the issue when trying to implement error handling:
```
const sheet = new ServerStyleSheet();
const jsx = sheet.collectStyles(<App />);
const stream = sheet.interleaveWithNodeStream(renderToNodeStream(jsx)).
    on(‘error’, () => {
        // redirect user to Error page
    });
stream.pipe(res, { end: false });
```

We would expect the React stream returned by `renderToNodeStream(jsx)` to pass chunks of streamed data to the Styled Components stream, which interleaves styles into these chunks and writes them to `res` as soon as each is available. That’s what the `data` event handler in `interleaveWithNodeStream()` looks as though it ought to do:

```
   readableStream.on('data', chunk => {
      const { tags } = instance
      let html = ''

      /* retrieve html for each new style tag */
      for (; instanceTagIndex < tags.length; instanceTagIndex += 1) {
        const tag = tags[instanceTagIndex]
        html += tag.toHTML(streamAttr)
      }

      /* force our StyleSheets to emit entirely new tags */
      instance.sealAllTags()
      /* prepend style html to chunk */
      ourStream.push(html + chunk)
    })
```
That’s not the behaviour we see. If an error is thrown by <App />, we can see that _no_ chunks of HTML have been streamed to the browser before the Error page redirect. If we remove Style Components from the equation...

```
const stream  = renderToNodeStream(jsx).
    on(‘error’, () => {
        // redirect user to Error page
    });

stream.pipe(res, { end: false })
```
...we _do_ see chunks of data flushed to the browser before the error is thrown and the user is redirected.

Moreover, if I add `.on('data', () => {console.log('[React/Styled Component] stream - data chunked')})` handlers to the React stream and the interleaving Styled Components stream, we can see that all the React stream data events are called before the Styled Component events, rather than each taking turns.

Is there a way to force `interleaveWithNodeStream()` to pipe chunks as it receives them to ensure we get the performance benefits of streaming?

**Comment by mxstbr** [comment]
This sounds like a pretty grave bug to me, /cc @probablyup

**Comment by evan-scott-zocdoc** [comment]
Yeah I recently learned about transform streams which might be a better implementation for this use case and avoid the mentioned issue :/

**Comment by probablyup** [comment]
@jonsanders101 I'm unfortunately having a very hard time reproducing this. Do you happen to have a public repo I could take a look at that exhibits the behavior?

**Comment by mattlunn** [comment]
@probablyup;

I've created this example (I've been looking at this with @jonsanders101);

**index.js**
```
import http from 'http';
import express from 'express';
import styled, { ServerStyleSheet } from 'styled-components';
import { renderToNodeStream  } from 'react-dom/server';
import React, { Component } from 'react';

const app = express();
const Div = styled.div`
  font-size: ${props => props.height + '%'}
`;

class App extends Component {
  render() {
    const output = [];

    for (let i=0;i<1000;i++) {
      output.push(<Div height={i}>Hello</Div>);
    }

    return output;
  }
}

app.get('/', (req, res) => {
  const sheet = new ServerStyleSheet();
  const body = sheet.collectStyles(<App />);
  const nodeStream = renderToNodeStream(body);
  const styledStream = sheet.interleaveWithNodeStream(nodeStream);

  nodeStream.on('data', () => {
    console.log('Received chunk of node stream');
  });

  styledStream.on('data', () => {
    console.log('Received chunk of style stream');
  });

  styledStream.pipe(res);
});

http.createServer(app).listen(8080);

console.log('http://localhost:8080');
```

**package.json**
```
{
  "name": "",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "babel-node index.js --presets env,react"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "babel-preset-env": "^1.7.0",
    "babel-preset-react": "^6.24.1",
    "express": "^4.16.3",
    "react": "^16.4.0",
    "react-dom": "^16.4.0",
    "styled-components": "^3.3.0"
  },
  "devDependencies": {
    "babel-cli": "^6.26.0"
  }
}
```

**Console output;**

```
matt@mac ~/dev/styled-components $ node --version
v10.3.0
matt@mac ~/dev/styled-components $ npm run start

> @1.0.0 start /Users/matt/dev/styled-components
> babel-node index.js --presets env,react

http://localhost:8080
Over 200 classes were generated for component styled.div.
Consider using the attrs method, together with a style object for frequently changed styles.
Example:
  const Component = styled.div.attrs({
    style: ({ background }) => ({
      background,
    }),
  })`width: 100%;`

  <Component />
Received chunk of node stream
Received chunk of node stream
Received chunk of node stream
Received chunk of node stream
Received chunk of style stream
Received chunk of style stream
Received chunk of style stream
Received chunk of style stream
```

The red flag for us here is that we're seeing all the "Received chunk of node stream" _before_ we see "Received chunk of style stream". What we were instead expecting to see was;

```
...
Received chunk of node stream
Received chunk of style stream
Received chunk of node stream
Received chunk of style stream
Received chunk of node stream
Received chunk of style stream
Received chunk of node stream
Received chunk of style stream
```

Hope that helps,
Matt

**Comment by probablyup** [comment]
That's perfect, thank you!

**Comment by b4le** [comment]
@probablyup 

Work with @jonsanders101 

I've tried out the PR that was created and it definitely works but I don't know whether it works as intended. From the example @mattlunn posted before (and in our own codebase), we're now getting interleaving but it's not as interleaved as we expected, see below:

```
Received chunk of style stream
Received chunk of node stream
Received chunk of node stream
Received chunk of style stream
Received chunk of node stream
Received chunk of node stream
Received chunk of style stream
Received chunk of style stream
```

Can you guys just confirm if this is what you'd expect to see or if you'd expect it to be one and then the other (as we expected)?

Cheers!

**Comment by probablyup** [comment]
@b4le if you view the page, does it look right with JS disabled? The ordering of the logs might just be an async artifact. Locally when I was building & testing it seemed to be emitting in the right order.

**Comment by jonsanders101** [comment]
@probablyup - I've installed Styled Components from the master branch to test this locally, but I'm getting `Error: Cannot find module 'styled-components'`. It's definitely in my Node Modules. Do I need to compile Styled Components locally?

**Comment by probablyup** [comment]
@jonsanders101 I'll publish a dev version to make this easier

**Comment by probablyup** [comment]
Ok you should be able to install via `yarn add styled-components@dev`

**Comment by b4le** [comment]
@probablyup If you've got it working I'm happy with that. We see interleaving just a couple of discrepancies. Either way, it's an improvement. Cheers
