### ISSUE TITLE
Using ThemeProvider props in injectGlobal

### ISSUE THREAD

**Issue by discovrbookings** [styled-components/styled-components#1761]
How can I access the `ThemeProvider` `props` in `global.js`?

For example in theme.js I have `${props => props.theme.fonts.fontSize}` calling a default font size of `16px` 

    const theme = {
        fonts: {
            fontSize : '16px',
        }
    }
    
    export default theme

This is provided in `/layouts/index.js` as

    import React from 'react'

    import { ThemeProvider } from 'styled-components'
    import '../style/global';
    import theme from '../style/theme'
    
    class Template extends React.Component {
      render() {
        const { children } = this.props
    
        return (
          <ThemeProvider theme={theme}>
            ...
            {children()}
            ...
          </ThemeProvider>
        )
      }
    }
    
    export default Template

From here I can access the `${props => props.theme.fonts.fontSize}` within each component or child page.

But how can I pass to `global.js` in the same way when global is technically a level above `theme.js`? So that I could create a global style as

    injectGlobal`
      html {
        font-size: (${props => props.theme.fonts.fontSize} / 16px) * 1em;
      }
    `

  [1]: https://www.styled-components.com/

**Comment by mxstbr** [comment]
We're working on a better API that'll allow you to do this, see #1333.
