### ISSUE TITLE
Improving CSS-object support

### ISSUE THREAD

**Issue by quicksnap** [styled-components/styled-components#1762]
Howdy! I'm coming from Glamorous, and I would like to improve styled-components CSS-object support. The actual implementation shouldn't be too difficult, but I wanted to talk about the use case a little before opening a PR.

Current functionality possible via #1732 is `styled.div({ color: 'blue' })`, etc. Hooray!

A nice improvement on this would be to allow for a recursive array of style objects that are deeply merged: 

```js
styled.div([
  { color: "blue", fontSize: 22, fontWeight: "bold" },
  [{ color: "red" }],
  [[[{ color: "pink", fontSize: 11 }]]]
]);

// Would generate a component of: 
// => { color: "pink", fontSize: 11, fontWeight: "bold" }
```

Allowing interpolation functions into the mix would be even nicer:

```js
styled.div([
  { color: "blue", fontSize: 22, fontWeight: "bold" },
  [ (props) => ({ color: props.theme.colorBlindMode ? "red" : "black" }) ], // <- Nested Interop fn 
]);

// Would generate a component of: 
// => { color: "red or black", fontSize: 22, fontWeight: "bold" }
```

Finally, it would be great if the returned value of the interop functions could recursively nest, too:

```js
 (props) => [{ ...someCss}, (props) => [{...moreCss}, anotherObjOrFunction, etc] ]
```

If we were able to accept recursive arrays of objects or interop functions, it would enable really great compositional patterns for plain-object styles. Also, it types pretty well with TypeScript: https://github.com/paypal/glamorous/blob/master/typings/css-properties.d.ts#L24-L39

It'd be happy to explore adding this feature, and it shouldn't take too much work.

An open question I have: I'm new to styled-components, and am not clear on if there's a difference between static styles and interpolated style functions. I saw in Emotion's code that there's a difference so that they may extract static CSS. Is this something to look out for in this library?

Happy to hear thoughts on implementing this feature. It enables some really nice patterns! If any of my examples aren't clear, I can make up some more.

**Comment by quicksnap** [comment]
I'm happy to move forward with #1775 any time. Just need a little guidance from maintainers on implementation details.

**Comment by wagerfield** [comment]
This is coming up on a year old now, but I'd like to see better support for CSS objects in Styled Components. At the bare minimum, it would be great if it could support a flat array of style objects as the first argument.

[See my comment here](https://github.com/styled-components/styled-components/pull/1775)

**Comment by kitten** [comment]
Closing due to age, inactivity, missing reproduction, or lack of details.
