### ISSUE TITLE
new `stylelint` support.

### ISSUE THREAD

**Issue by gucong3000** [styled-components/styled-components#1763]
I am working on `stylelint` and `postcss` that support `styled-components`.
`stylelint-processor-styled-components` is not support for automatically fixes, so I created `postcss-jsx` to support it.
I need more testing and feedback. Can someone help me?
You can install it like this:
```bash
npm install --save-dev stylelint/stylelint postcss-jsx stylelint-config-styled-components
stylelint **/*.{js,jsx,css}
```

**Comment by ai** [comment]
@mxstbr I used `postcss-styled` in my project to sort properties in git commit hook and it works great

**Comment by mxstbr** [comment]
Ohh nice!

@gucong3000 post about this in the styled-components community, a lot more people will see it there: https://spectrum.chat/styled-components
