### ISSUE TITLE
[enhancement ✨] classNameFromProps(...)

### ISSUE THREAD

**Issue by osi-oswald** [styled-components/styled-components#1764]
It is a common pattern to use something like the following code snippet:
(it's even the first thing you see on the front page of [styled-components](https://www.styled-components.com))
```js
const Button = styled.a`
  ${props => props.primary && css`
    background: white;
  `}
`
```

In my opinion the ${...} sections add a lot of clutter and hurt the readability (the less ${...} the better 🎉).

I therefore propose a new tag function called 'classNameFromProps' (or shorter name, see suggestions below), which can be used like this instead:
```js
const Button = styled.a.classNameFromProps('primary')`
  &.primary {
    background: white;
  }
`
```

It basically checks if the listed props keys are truthy, and if yes, add the key name as class name to the component. 

In my opinion you get really far with the truthy check. If some other check is needed, 'the old way' can still be used (props function), or the prop can be assigned in a boolean manner (ex. ```<Button primary={myNumber != null} />```)

The behavior can be currently achieved via the 'attrs' function:
```js
function classNameFromProps(...keys) {
  return {
    className: props => keys.reduce((cn, k) => props[k] ? cn + ' ' + k : cn)
  }
}

const Button = styled.a.attrs(classNameFromProps('primary'))`
  &.primary {
    background: white;
  }
`
```

But I would like to have it as first class citizen, since it is such a common styled-components pattern. 

For **TypeScript** (I do not know about Flow) the 'classNameFromProps' could even return a tag type with the listed keys as props. So instead of:
```ts
const Button = styled.a<{primary?}>`
  ${props => props.primary && css`
    background: white;
  `}
`
```
you can just write ```styled.a.classNameFromProps('primary')``` and get an a-Tag with proper props type.

Some shorter name suggestion would be:
* classFromProps(...)
* or just classNames(...) **💪 my favorite, since attrs is not called attrsFromProps as well**

**Optional**
'classNameFromProps' could be enhanced similarly to the attrs function:
```js
styled.a.classNameFromProps('someProp'); // as proposed
styled.a.classNameFromProps({ someClass: p => ... }); // in addition
```

**Comment by probablyup** [comment]
I'm 👎 on this. It's way too easy to accidentally make conflicting classNames with a strategy like this. Part of the utility of styled-components is automatic and effortless scope isolation.

If you feel strongly about it, I'd recommend a userland wrapper. It should be possible as you mentioned to do something in `attrs()` that generates and appends the deterministic `className`.
