### ISSUE TITLE
`onClick` when declared in `.attrs({})` is invoked prematurely

### ISSUE THREAD

**Issue by garrettmaring** [styled-components/styled-components#1766]
## Environment

```
## System:
 - OS: macOS High Sierra 10.13.4
 - CPU: x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
 - Free Memory: 583.71 MB
 - Total Memory: 16.00 GB
 - Shell: /bin/zsh - 5.3
## Binaries:
 - Node: 8.9.4
 - Yarn: 1.6.0
 - npm: 5.6.0
 - Watchman: Not Found
## npmPackages:
### styled-components:
 - wanted: ^3.2.6
 - installed: 3.3.0
```

## Reproduction

Setting `onClick` via `attrs` doesn't work as expected.

## Steps to reproduce

```typescript
// ./PreviousArrow.tsx
const StyledPreviousArrow = styled(Icon).attrs({
  onClick: this.props.navigationFunction.bind(null, this.props.activeSlide - 1),
  type: IconType.LeftArrow,
})`
  ${absolutelyCenter(Direction.Vertical)};
  left: 0;
  z-index: 2;
  padding: 0 11px;

  width: 22px;
  height: 34px;
`;

// ./Icon.tsx
class Icon extends React.Component<IIconProps, {}> {
  public render() {
    return (
      <img className={this.props.className} src={this.props.type} onClick={this.props.onClick} />
    );
  }
}

export default styled(Icon)`
  width: 24px;
  height: 24px;
`;
```

## Expected Behavior

The bound `this.props.navigationFunction` is set to the `<img>` tag's `onClick` attribute which is only called when the element is clicked.
 
## Actual Behavior

![screen shot 2018-05-29 at 11 18 49 am](https://user-images.githubusercontent.com/8270120/40677457-90639b3c-6332-11e8-9d18-2dcf4c1c88e1.png)

The actual behavior is that the `onClick` function is being called repeatedly. If the contents of the `onClick` function is updated to contain a simple `console.log`, that is called repeatedly until there is an overflow.

The workaround was simple. Since `onClick` seems to be called by styled-components when it should be set, I can wrap the bound function in a function that will return it. However, this is obviously not the intended behavior.

```typescript
// ./PreviousArrow.tsx
const StyledPreviousArrow = styled(Icon).attrs({
  onClick: () => this.props.navigationFunction.bind(null, this.props.activeSlide - 1),
  type: IconType.LeftArrow,
})`
  ${absolutelyCenter(Direction.Vertical)};
  left: 0;
  z-index: 2;
  padding: 0 11px;

  width: 22px;
  height: 34px;
`;
```

**Comment by mxstbr** [comment]
Where are you defining `StyledPreviousArrow`? It seems like you're defining it in a render method, (based on the `this.props.navigationFunction`) which is a big no-go.

**Comment by garrettmaring** [comment]
Ah, why so?

And what do you mean where? If you see above, it's defined in its own component file. I removed the export/imports to simplify the example.

**Comment by Djelnar** [comment]
@garrettmaring 
[https://www.styled-components.com/docs/basics#attaching-additional-props](link)
> The .attrs object also takes functions, that receive the props that the component receives.
Closing as it is a declared behavior

**Comment by probablyup** [comment]
@garrettmaring 

```js
styled(Icon).attrs({
  onClick: () => this.props.navigationFunction.bind(null, this.props.activeSlide - 1),
  type: IconType.LeftArrow,
})`
```

functions in `attrs` are called with `props` as an argument and then whatever is returned by that function is the prop that is passed on
