### ISSUE TITLE
Breaking change in v3.3.0

### ISSUE THREAD

**Issue by nicgirault** [styled-components/styled-components#1781]
## Reproduction

These codesandbox use the same code with 2 different versions of styled-components. The result is different.

version 3.2.6 https://codesandbox.io/s/3qz76mno01
version 3.3.0 https://codesandbox.io/s/w7nlzzlqj7

```javascript
import React from "react";
import { render } from "react-dom";
import styled from "styled-components";

const Title = styled.h1`
  color: red;
`;

// this styled is ignored is v3.3.0
// it must be replaced by
// const ExtendedTitle = Title.extend
const ExtendedTitle = styled(Title)`
  background-color: blue;
`;

const ExtendedExtendedTitle = ExtendedTitle.extend`
  border: 2px solid green;
`;

const App = () => (
  <div>
    <ExtendedExtendedTitle>Hello</ExtendedExtendedTitle>
  </div>
);

render(<App />, document.getElementById("root"));
```

**Comment by Ky6uk** [comment]
@nicgirault I'd recommend you to not use `Tag.extend()` in favor to use `styled(Tag)`. I'm already got a similar problem in [this thread](https://spectrum.chat/users/ky6uk?thread=b02a24ae-01a0-4271-bd9a-807577c4b679). But it seems nobody care about it (it means nobody uses it). 😞

**Comment by probablyup** [comment]
Thanks for the repro cases @nicgirault. I'll try to look into this. We do intend on dropping extend for 4.0 but it should still function/interop correctly in the 3.x branch.
