### ISSUE TITLE
Add support for TypeScript 2.9 type arguments

### ISSUE THREAD

**Issue by sandervspl** [styled-components/styled-components#1782]
[TypeScript 2.9](https://blogs.msdn.microsoft.com/typescript/2018/05/31/announcing-typescript-2-9/) added support for type arguments for tagged template strings. This solves a lot of issues when working with TypeScript.

Their example code shows the following code that should be possible now:

```typescript
export interface InputFormProps {
    invalidInput: string;
}

export const InputForm = styledInput<InputFormProps> `
    color:
        ${({themeName}) => themeName === 'dark' ? 'black' : 'white'};
    border-color: ${({invalidInput}) => invalidInput ? 'red' : 'black'};
`;
```

**Comment by probablyup** [comment]
Please see https://github.com/styled-components/styled-components/issues/1778
