### ISSUE TITLE
TypeScript 2.9.1 makes typings break

### ISSUE THREAD

**Issue by ducin** [styled-components/styled-components#1783]
The following error is thrown, when using with TypeScript `2.9`:
```/node_modules/styled-components/typings/styled-components.d.ts
(76,48): Type 'keyof T' does not satisfy the constraint 'string'.
  Type 'string | number | symbol' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.
```

Environment: Windows

Reproduction: install these:
```
    "styled-components": "^3.3.0"
    "typescript": "^2.9.1"
```
and try to compile your app

Actual Behavior: compiler error related to typings file of styled-components, not the app code

Expected Behavior: compiler passes styled-components source typings file.

**Comment by Swatinem** [comment]
This was fixed by https://github.com/styled-components/styled-components/pull/1773, please close @Igorbek
