### ISSUE TITLE
`injectGlobal is not a function` error on Native

### ISSUE THREAD

**Issue by Zacqary** [styled-components/styled-components#1786]
![screen shot 2018-06-01 at 4 37 13 pm](https://user-images.githubusercontent.com/1445834/40864591-0fc2b168-65ba-11e8-8033-d1c5dc0420eb.png)
https://www.styled-components.com/docs/api indicates that `injectGlobal` is supported on React Native, but it doesn't appear to be an importable function in the native library. Not sure if support is intended and there's a bug in the library, or if `injectGlobal` isn't intended to be supported on native and the docs are incorrect.

### System:
 - OS: macOS High Sierra 10.13.4
 - CPU: x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
 - Memory: 1.85 GB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
### Binaries:
 - Node: 8.9.4 - /usr/local/bin/node
 - Yarn: 1.6.0 - /usr/local/bin/yarn
 - npm: 5.6.0 - /usr/local/bin/npm

## Reproduction
https://snack.expo.io/ry5NnVJlQ

## Steps to reproduce
Create a React Native app, and try to import and use `injectGlobal`.

## Expected Behavior
`injectGlobal` injects global styles properly without throwing an error.

## Actual Behavior
An error stating that `injectGlobal` is not a function gets thrown.

**Comment by mxstbr** [comment]
It's definitely not supported on ReactNative—ReactNative doesn't have global style support! Mind sending a PR to https://github.com/styled-components/styled-components-website? Thanks!
