### ISSUE TITLE
npm/yarn install installs latest v2.x version

### ISSUE THREAD

**Issue by jerelmiller** [styled-components/styled-components#1788]
I'm not sure if this is a bug, or intended behavior, but I at least wanted to get something in here. When installing `styled-components` fresh (either via `yarn` or `npm`), it appears v2.4.1 is the version installed by default. I see there are both v2 and v3 versions available (with v3.3.0 being the latest of the v3 release at the time of this issue).

Is this intentional?

Thanks so much! I just wanted to make sure someone knew this was happening in the event this was unintentional.

**Comment by simonkberg** [comment]
Looks like the v2.4.1 hotfix got published to the "latest" dist-tag on npm.

![screenshot from 2018-06-02 15-06-22](https://user-images.githubusercontent.com/173085/40874910-8f4ff65e-6676-11e8-8780-430d404ec546.png)

**Comment by probablyup** [comment]
Wow, yarn isn’t smart enough to follow the semver range? I’ll likely be
pushing a 3.x patch tonight anyway but that’s bad.

**Comment by probablyup** [comment]
Ok I think I fixed it.

```
npm dist-tag add styled-components@3.3.0 latest
```

^ for anyone in the future

**Comment by jerelmiller** [comment]
Thanks for fixing!
