### ISSUE TITLE
Feature: Adding selector scoping for generated classNames

### ISSUE THREAD

**Issue by ItsJonQ** [styled-components/styled-components#1789]
Hi there! 👋 

I have a feature request :). Would it be possible to provide the ability to (intentionally) scope/increase the specificity of SC classNames?

### Use case

The use case for this would be if we wanted to implement SC React components into an older applications, with hostile pre-existing CSS rules (that probably won't/can't go away soon). The company I work for has this very use-case!!

### Implementation idea

My idea was to leverage `ThemeProvider` (or maybe a newly created Provider?) where you can define a `scope` prop.

```jsx
<ThemeProvider scope="html #App">
  <StyledCard />
</ThemeProvider>
```

If the hashed CSS classes for StyledCard was `.13jdhx`, they will now render as `html #App .213jdhx`.

Any SC components that live within this ThemeProvider will receive this scoping. Using this technique, we could ensure that these component's CSS will always trump (with the exception of `!important) whatever pre-existing styles that may exist in the older environment.

### Implementation details

If we decide to use `ThemeProvider`, then it'll have to make the `scope` prop available for the `styled` component generator, specifically when it gets to the point where `stylis` comes into play to generate the CSS.

Within `stringifyRules.js`, on line `56`, we can modify to something like:

```jsx
// Before
  return stylis(prefix || !selector ? '' : selector, cssStr)

// After
  return stylis(scope + (prefix || !selector ? '' : selector), cssStr)
```

Assuming the `scope` can be passed down, and falling back to `''`.

### Other info

I actually built my own library that borrows many ideas from Styled Components (thank youuu! 🙇), where I was able to achieve something like this:

https://github.com/helpscout/fancy/blob/master/docs/theming.md#scoping

And it works great for integration with not-so-friendly existing CSS.

The reason I'm reaching out is I've hit some limitations with my (perhaps naive) attempt at recreating Styled Components 😅 . I would love to use this library if it had some kind of scoping feature. 

I read through the docs and even poked around the source code, but I couldn't find a way to do this.

Thank you so much for your time!

### Contribution

If this is a feature you guys think would be valuable,  I would be more than happy to help contribute if someone can maybe point me in the right direction in regards to what file(s) to modify and potential side effects to look out for?

Thanks again!

**Comment by probablyup** [comment]
> My idea was to leverage ThemeProvider (or maybe a newly created Provider?) where you can define a scope prop.

Ohh. I actually kind of like that. We'd need to limit the scoping to only non-global styles though, so anything via `injectGlobal` wouldn't receive the scoping.

There is also a syntax like this to increase the specificity for a style:

```
styled.div`
  && {
    color: red;
  }
`
```

Which creates the style as a double selector like ".foo.foo", thereby increasing the specificity proportionally. There could perhaps be a setting that does this globally.

@mxstbr @kitten thoughts?

**Comment by ItsJonQ** [comment]
@probablyup I considered stacking `&`, but the compiled styles of `.foo.foo` (or even `.foo*40`) will not trump anything that's styled within an `#id`.

A good example is if you're working in an unfortunate example where legacy CSS like the following (bad) code exists:

```css
#app ul {
  margin: 0;
  display: inline-block;
}
```

And, for reasons, that code can't be removed (not for a while).

If I add a `styled.ul` React component in there… The styled-components CSS will be trumped.

So, theoretically, if there was a way to add extra scope (via a Provider), the compiled styled-components rules can be adjusted to compile like…

`html body #app .13jdhx`, which isn't ideal, but it'll guarantee to work without breaking legacy things with basically zero (theoretical) side effects.

Hope this makes sense! 🤗

**Comment by probablyup** [comment]
Yeah, it definitely does. I'm open to the idea. Just need to get consensus from the other core members and figure out if there are any edge cases I didn't think of.

**Comment by geelen** [comment]
Coming late to this issue sorry, but the following is already possible, do you think this would be sufficient?

```js
const StyledCard = styled.div`
  html #app & {
    // everything here is scoped up as needed
  }
`
```

Breaking that into a little helper constant, can give you a lot better signalling:

```js
import { arghBootstrapWhy } from '../styles/utils'

const StyledCard = styled.div`
  ${arghBootstrapWhy} {
    // everything here is scoped up as needed
  }
`
```

The good thing here is that your scoping isn't all-or-nothing, you can style things up as normal, but then when you hit a specificity issue, escalate your own code to have priority.

---

Just on this, the whole idea of specificity never decreasing over the life of the code base is what you're trying to fight against. SC, like most other component-centric CSS workflows, really needs a clean slate to be building off. You might be able to take a different approach:

```scss
#app [data-legacy-css] ul {
  margin: 0;
  display: inline-block;
}

#app [data-legacy-css] li {
  ...
}
```

If you can rewrite your existing CSS to be _more_ specific by expecting a data-attribute somewhere in the DOM, you can start reducing its surface area on the app. So, maybe CMS-driven content pages still get the `data-legacy-css` attribute, but your new login screen doesn't. Once you have more SC-driven components on pages with legacy styling, you take a more granular approach and add `data-legacy-css` to those sub-areas that still assume the global styling.

This is an approach I've used, and it worked ok for me with a site with not all that many distinct templates. But it does give you a different way to control things, so it's worth having a look.

**Comment by probablyup** [comment]
I definitely think both strategies can and should co-exist. It really depends on what your needs are... if you are embedding your code on another side, a global override makes a lot of sense to avoid lots of boilerplate. If it's a targeted one like your examples, the local lifting is a good choice that is easy to refactor later on.

**Comment by ItsJonQ** [comment]
Haiii!!

Thanks for getting back to me on this one @geelen 🙌 ! And I agree with @probablyup .

The tricky part of having a "hard-coded" prefix in your styles (like `${arghBootstrapWhy}`) is that it limits the styles to a singular application (cannot easily be used for libraries). And if you wanted to add it into existing styles, it involves manually adding that prefix to a bunch pre-existing code 😅 .

I have some updates!~ I've refactored the styled-components-like library that I use for my company. It now uses a enhanced forked version of Emotion under the hood. (I went with Emotion instead of SC because I found the smaller files easier to pluck + hack, haha).


#### `ScopeProvider` 🔎

I went with the strategy of creating a `ScopeProvider` ([wrote some docs here](https://github.com/helpscout/fancy/blob/master/docs/scoping.md)).

Example:
```jsx
<div>
  <StyledCard />
  ...
  <ScopeProvider scope="html #App">
    <div id="App">
      <StyledCard />
    </div>
  </ScopeProvider>
  ...
</div>
```

The idea is… anything created with `styled` should not have to worry about scope… therefore, no need to manually add prefixes (when you create them).

If it appears under a `ScopeProvider`, it will then get prefixed by anything defined by the `ScopeProvider`. If it appears outside, it's business as usual. It allows for `styled` components to seamlessly be used inside/outside of scoped areas.

This strategy allows for scoping to be added to an **existing** application/system of styled components without changing anything, minus the root(s) where `ScopeProvider` needs to be added, which is nice. 

The way I've written `ScopeProvider` works very much the same way as how `ThemeProvider` works (context + internal broadcast + sub/unsub for the `styled` component). The only tricky bit coordinating and sending that prefix (`string`) to `stylis` during the CSS processing phase (if a scope is defined).

Here's the [source code](https://github.com/helpscout/fancy/blob/master/src/ScopeProvider/ScopeProvider.js). There's not much too it! The heavy lifting comes from the [`styled-component factory`](https://github.com/helpscout/fancy/blob/master/src/create-emotion-styled/index.js#L191)

#### ScopeProvider within a ScopeProvider? 🤔 

> Yo dawg, I heard you like Scope…

I know the strategy `ThemeProvider` extends previously established theme configs when nesting happens. For scoping, I think it's probably simplest to assume that only the closest `ScopeProvider` scope will be used. No inheriting/chaining.

Thank you so much for your time!

---

Side note...

#### iFrames 🤓
This is out of scope for this feature request, but I took the same strategy and applied it to another tricky issue that libraries like styled-components, emotion, jss, etc… have, and that is correctly rendering styles within iFrames. I did this by creating a [`FrameProvider`](https://github.com/helpscout/fancy/blob/master/docs/iframes.md).

```jsx
<App>
  <StyledCard />
  <Frame>
    <FrameProvider>
      <StyledCard />
    </FrameProvider>
  </Frame>
</App>
```

The `FrameProvider` is used within your iFrame (folks usually use [`react-frame-component`](https://github.com/ryanseddon/react-frame-component)). If any `styled` components render within, the `FrameProvider` will provide the style generator with the correct `document` to render it's `style` tags into. (We can discuss this in another GH issue if you're interested)

Thanks again for your time!!!

**Comment by Andarist** [comment]
From what I see you do not expose possibility to add stylis plugins in styled-components, but if you would it would be possible to cover this use case with https://github.com/Andarist/stylis-plugin-extra-scope

**Comment by probablyup** [comment]
We aren’t planning on exposing that configuration because stylis is just an implementation detail. If we add this functionality. It will be a first-class part of the API.

**Comment by sag1v** [comment]
What i like the most about this API:
```
<ScopeProvider scope="html #App">
```
Is that `scope` can be dynamic.

**Comment by ReasonableDeveloper** [comment]
Is it possible that this will enable styling components inside `shadow-dom`? See https://github.com/Wildhoney/ReactShadow/issues/62

**Comment by feychenie** [comment]
I might be wrong, but in my understanding, 5.0 main scope is to be retro-compatible with 4, couldn't this one be moved to 5.1, as it is kind of a new feature?
Also, this issue hasn't really moved for a year now, so...

**Comment by yordis** [comment]
@probablyup any updates on this? Is there any spec about the implementation? We are facing some issues that this may solve, so we could have some time to contribute back to the community, but I would love to have your support in the process since I am not sure what is the final direction.

**Comment by probablyup** [comment]
None at the moment, not currently planned for 5.0 but could show up in a minor point release

**Comment by ItsJonQ** [comment]
As a work-around for this, I've created a library called `styled-providers` which includes solutions for scoping + iFrames for `styled-components` and `Emotion`

https://github.com/itsjonq/styled-providers

Just a heads up, the `styled-components` solution is for V5+. Emotion support is for v10+

**Comment by yordis** [comment]
@probablyup could we gather all the info and trying to move this forward? It seems @ItsJonQ got it working already so I am not sure what's left in order to make to v5

**Comment by casperle** [comment]
Hi guys. The provided package by @ItsJonQ is not working correctly with the `styled-components`. The problem lays inside `stylis-plugin-extra-scope` where an anonymous function is returned, which fulfils the requirements for `stylis` but does not define a name property for it, which is required by `styled-components`. You can see it here https://github.com/styled-components/styled-components/blob/v5.0.0/packages/styled-components/src/utils/stylis.js#L97

The working version should look like this (without any extra package):
```jsx
import React, { useMemo } from 'react';
import { StyleSheetManager } from 'styled-components';

function extraScopePlugin(extra) {
  const scope = `${extra.trim()} `;

  const _extraScopePlugin = (
    context,
    content,
    selectors,
    parents,
    line,
    column,
    length,
    type
  ) => {
    if (context !== 2 || type === 107) return;

    for (let i = 0; i < selectors.length; i++) {
      // avoid to apply the extra scope multiple times
      if (!selectors[i].includes(scope)) {
        selectors[i] = `${scope}${selectors[i]}`;
      }
    }
  };

  // the name property definition
  Object.defineProperty(extraScopePlugin, 'name', {
    value: extra.trim(),
  });

  return _extraScopePlugin;
}

export const StyledScopeProvider = ({
  children = null,
  scope = '',
  ...restProps
}) => {
  const stylisPlugins = useMemo(() => {
    return [extraScopePlugin(scope)];
  }, [scope]);

  return (
    <StyleSheetManager stylisPlugins={stylisPlugins} {...restProps}>
      {children}
    </StyleSheetManager>
  );
};

```

**Comment by probablyup** [comment]
You can add this yourself at runtime via Object.defineProperty until the plugin author updates their code

**Comment by Andarist** [comment]
If only the issue has been raised against the plugin... 🤷‍♂ 

Gonna fix it in a moment.

**Comment by motevallian** [comment]
Is it possible as a complement to this issue or a side feature to consider providing a className prefix in runtime as well. I mean for example
```
 <ScopeProvider classNamePrefix="myApp">
  ..
</ScopeProvider>
```
would lead to all child components of this section to have their classnames prefixed with `myApp-`. This way, in micro-frontend world one can guarantee each app is isolating its classsNames (not just the secelctors) from other apps hence being completely isolated.

**Comment by ivnmaksimovic** [comment]
We had the same use case and solved it by using styled-components ThemeProvider, StyleSheetManager, and stylis-plugin-extra-scope.

```jsx
import React from 'react';
import PropTypes from 'prop-types';
import {
  StyleSheetManager,
  ThemeProvider as SCThemeProvider,
} from 'styled-components';
import extraScopePlugin from 'stylis-plugin-extra-scope';

Object.defineProperty(extraScopePlugin, 'name', {
  value: 'someuniquename'
});

const ThemeProvider = ({ children, theme, scope }) => {
  const stylisPlugins = scope ? [extraScopePlugin(`${scope}`)] : [];

  return (
    <StyleSheetManager stylisPlugins={stylisPlugins}>
      <SCThemeProvider theme={theme}>{children}</SCThemeProvider>
    </StyleSheetManager>
  );
};

ThemeProvider.defaultProps = {
  scope: undefined,
};

ThemeProvider.propTypes = {
  children: PropTypes.node.isRequired,
  theme: PropTypes.object.isRequired,
  scope: PropTypes.string,
};

export { ThemeProvider };
export default ThemeProvider;
```
You can use it like:
```jsx
const theme = { primaryColor: 'red' };

const SomeApp = () => {
  return (
    <ThemeProvider theme={theme} scope='#MyScope'>
      Some components here
    </ThemeProvider>
  );
};
```
Resulting css is sometihng like:
```css
#MyScope .hOEOyg {
  background: red;
}
```

**Comment by kitten** [comment]
Resolved via the Babel plugin sufficiently: https://styled-components.com/docs/tooling#namespace

**Comment by chrisvltn** [comment]
Using the `stylis-plugin-extra-scope` seemed to solve the issue at first, but then it was noticed that dynamic styles are not handled properly when the plugin is used.

The following component, for example:

```typescript
const StyledAnchor = styled.a<{ isRed: boolean }>`
    color: ${({ isRed }) => isRed ? 'red' : 'blue'};
`
```

Will generate the following styles:

```css
.sc-123 {
    color: blue;
}

.sc-123 {
    color: red;
}
```

Resulting in the link being always red or blue, independent of what the value of `isRed` is.

After some investigation it was found that the problem seems to be in the `selfReferenceReplacer` function: https://github.com/styled-components/styled-components/blob/main/packages/styled-components/src/utils/stylis.ts#L26-L36

There, the class seems to be replaced with the component id (`sc-123`) instead of the dynamic hashed class (`.abcDEF`).

As there we have another statement that checks for consecutive self references (`!string.match(_consecutiveSelfRefRegExp)`), it seems that simply having consecutive self-references in the selector will make it stop replacing it with the component id.

So, to solve the issue we are not only adding the additional scope, but also repeating the class to make sure it is self-referenced.

Here is an example:

```javascript
const createExtraScopePlugin = (scope) => {
    const plugin = (context, content, selectors) => {
        if (context === -1) {
            for (let i = 0; i < selectors.length; i++) {
                const selector = selectors[i];
                selectors[i] = `${scope} ${selector.repeat(2)}`;
            }
        }
    };

    // Styled-components require the function to have a name
    Object.defineProperty(plugin, 'name', { value: `scope-${scope}` });

    return plugin;
};


const ScopedStyleProvider = ({ theme, scope, children }) => {
    const stylisPlugins = scope ? [createExtraScopePlugin(`#${scope}`)] : [];

    return (
        <StyleSheetManager stylisPlugins={stylisPlugins}>
            <Theme theme={theme}>{children}</Theme>
        </StyleSheetManager>
    );
};
```

The resulting CSS will be as expected:

```css
#MyScope .abcDEF {
    color: blue;
}

#MyScope .defABC {
    color: red;
}
```
