### ISSUE TITLE
Webstorm - Cannot resolve symbol '<Component>' after installing styled components

### ISSUE THREAD

**Issue by lakhman** [styled-components/styled-components#1793]
## Environment
```
Environment:
  OS: macOS High Sierra 10.13.4
  Node: 8.11.1
  Yarn: 1.6.0
  npm: 5.8.0
  Watchman: 4.6.0
  WebStorm: 2018.1
  Xcode: Xcode 9.3.1 Build version 9E501
  Android Studio: 2.3 AI-162.3764568
```

## Reproduction

```bash
yarn add styled-components
```

## Steps to reproduce

- When I install styled components, **Webstorm 2018.1** fails to recognise react native imports

e.g:

**Before installing styled components I can do this:**

![screen shot 2018-06-05 at 10 48 22](https://user-images.githubusercontent.com/1582690/40968970-b88e9ffe-68ae-11e8-9296-57a9515ca1f0.png)

Install styled-components (you don't need to import it).

```
# Simply installing this will cause the auto complete in webstorm to stop working
yarn add styled-components
```

![screen shot 2018-06-05 at 10 49 10](https://user-images.githubusercontent.com/1582690/40969066-df7db9ce-68ae-11e8-9cca-764403109e68.png)

> "Cannot resolve symbol 'Component Name'"

```
# Remove it and it comes back like normal with auto complete
yarn remove styled-components
```

## Expected Behaviour

It shouldn't do this. I don't understand why it breaks the auto complete of existing libraries.

**Comment by probablyup** [comment]
No idea. If WebStorm uses typescript typings to do its thing, it's possible that the `@types/react-native` dependency `styled-components` has doesn't list that export or something?
