### ISSUE TITLE
Support for hot reloading styled-components in React Native

### ISSUE THREAD

**Issue by pavsidhu** [styled-components/styled-components#1796]
I'm unsure if this is a bug or an unimplemented feature. Using `react-native@0.55.4` and `styled-components@3.3.0`, I found that when hot reloading is enabled, after editing a styled component I have to manually reload to see the changes.

Considering hot reloading is supported on the web, I assumed it would be for react-native too. Let me know if there's anything I can do to help.

**Comment by probablyup** [comment]
cc @kitten

**Comment by kitten** [comment]
I’ve seen this behaviour as well but haven’t investigated it yet. To add to the confusion, it’s working on the same project that I’ve been working on for some people

**Comment by stevefan1999** [comment]
Just add this line:
```js
if (module.hot) module.hot.accept()
```

**Comment by probablyup** [comment]
Looks like the issue isn't on our end, so closing.
