### ISSUE TITLE
Visual Studio Code

### ISSUE THREAD

**Issue by oscar-b** [styled-components/styled-components#180]
Syntax highlight support and linting support for Visual Studio Code.

Stylelint support:
https://github.com/shinnn/vscode-stylelint/issues/38

Syntax highlight support:
https://github.com/Microsoft/vscode/issues/14905
https://github.com/Microsoft/TypeScript-TmLanguage/issues/342
Was recommended to look at https://github.com/natewallace/language-vscode-javascript-angular2 for a similar plugin.

I currently don't have any free time to work on this, unfortunately.

**Comment by julienp** [comment]
I had a go at this: https://github.com/julienp/vscode-styled-components https://marketplace.visualstudio.com/items?itemName=jpoissonnier.vscode-styled-components

It's currently based on the VSCode SCSS grammar. I also just realised I forgot to add support for `injectGlobal`!

@mxstbr is it ok to use the styled-components logo for the extension?

**Comment by mxstbr** [comment]
Yeah definitely @julienp! Would you mind transferring the repo to this org (`styled-components`)? We'll add you as a collaborator!

**Comment by julienp** [comment]
Cool, done!

**Comment by mxstbr** [comment]
Would you mind submitting a PR adding this to the README @julienp? Great job! Closing this in favor of submitting issues over at https://github.com/styled-componets/vscode-styled-components

**Comment by oscar-b** [comment]
@julienp nice!
@mxstbr your link above is wrong

**Comment by mxstbr** [comment]
Ah, thanks @oscar-b!

**Comment by lXSPandora** [comment]
Hey guys look at this https://github.com/lXSPandora/vscode-styled-components-snippets
