### ISSUE TITLE
Setting nonce per-request with streaming SSR

### ISSUE THREAD

**Issue by bodhi** [styled-components/styled-components#1802]
(Apologies for deleting the issue template, but I couldn't make this issue fit very well into the template)

#1022 (and #1043) introduced using `global.__webpack_nonce__` to configure nonces for `<style>` tags when doing SSR:

https://github.com/styled-components/styled-components/blob/34d18292e6cc97b508b7adb572f1d357232bccd5/src/utils/nonce.js#L6-L7

But nonces should be randomly generated per-request, and using a global variable opens the possibility of nonces leaking between requests, if `global.__webpack_nonce__` is set again before the current request finishes:

1. request `A` generates nonce `Na`
2. `global.__webpack_nonce__` is set to `Na`
3. React starts rendering response for `A`
4. request `B` generates nonce `Nb`
5. `global.__webpack_nonce__` is set to `Nb`
6. `A` rendering starts using `Nb` for nonce instead of `Na`

I don't know enough of the details about whether `styled-components` can be interrupted by another request (apparently React's `renderToString` is synchronous, but `renderToNodeStream` may be asynchronous?) but perhaps one way to avoid this would be to accept the nonce as a parameter on one of `ServerStyleSheet`, `collectStyles` or `getStyleTags`.

---

This can be worked around on SSR by adding the nonce to the React elements by hand:

```
sheet.getStyleElement().map(e => React.cloneElement(e, { nonce }));
```

(But then I run into separate problems with Next.js's nonce handling, which make it hard to trouble-shoot Styled-components...)

**Comment by probablyup** [comment]
Yeah webpack nonces are not set up to be generated dynamically, sorry. It’s
a flaw in the bundler setup. s-c just implements a solution against the
current setup.

**Comment by osamu38** [comment]
same problem.

**Comment by mxstbr** [comment]
I think it'd make sense for `ServerStyleSheet` to accept a unique `nonce` prop to avoid the nonce leaking between streaming requests. I'm not sure how webpack handles that case though, how do they have unique nonces then?

**Comment by osamu38** [comment]
I passed `__webpack_nonce__` to the client, but it does not hook on the styled-components side.

```
<script
  dangerouslySetInnerHTML={{
    __html: `__webpack_nonce__ = '${nonce}';`,
  }}
  nonce={nonce}
/>
```

Is something wrong?

If `__webpack_nonce__` is `global.__ webpack_nonce__` or `window.__ webpack_nonce__`, styled-components can hook the client's nonce.

**Comment by osamu38** [comment]
I want to generate a nonce on the server side, not from webpack's `DefinePlugin`.

**Comment by mxstbr** [comment]
`global.__webpack_nonce__` needs to be set in the server.

**Comment by osamu38** [comment]
sorry, i can not tell you well.

https://github.com/styled-components/styled-components/blob/0aa3170c255a49cd41c3fbeb2b8051b5d132f229/src/utils/nonce.js#L6

On the client `__webpack_nonce__` becomes `undefined`.

How can I pass a value to `__webpack_nonce__` in the above file?

I think that `__webpack_nonce__` should be `window.__ webpack_nonce__` or `global.__ webpack_nonce__`.

**Comment by mxstbr** [comment]
```JS
// server/index.js
import express from 'express';
import { ServerStyleSheet } from 'styled-components';

app.use('*', (req, res, next) => {
  global.__webpack_nonce__ = uuid();
  // ...
  const styleSheet = new ServerStyleSheet();
  // ...
  const html = ReactDOMServer.renderToString(styleSheet.collectStyles(<App />));
  // ...
});
```

**Comment by kitten** [comment]
Closing due to age, inactivity, missing reproduction, or lack of details.
