### ISSUE TITLE
[TypeScript] styled wrapper doesn't preserve generic props

### ISSUE THREAD

**Issue by cdebotton** [styled-components/styled-components#1803]
## TypeScript 2.9.1

Using the `styled(Component)` method while wrapping a component with generic props doesn't preserve the generic argument, it simply defaults it to `{}`.

## Reproduction

```tsx
import React, { Fragment, ReactNode } from 'react';
import styled from 'styled-components';

interface Props<T> {
  renderChild: (props: T) => ReactNode;
  values: T[];
}

function GenericComponent<T>(props: Props<T>) {
  return (
    <Fragment>
      {props.values.map(props.renderChild)}
    </Fragment>
  );
}

const ThisWorks = (
  <GenericComponent
    values={[{ id: 1, value: 'foo' }]}
    renderChild={props => <p key={`I_${props.id}`}>{props.value}</p>}
  />
);

const StyledGenericComponent = styled(GenericComponent)`
  position: relative;
`;

const ThisDoesntWork = (
  <StyledGenericComponent
    values={[{ id: 1, value: 'foo' }]}
    renderChild={props => <p key={`I_${props.id}`}>{props.value}</p>} // Errors: Property 'id' does not exist on '{}', Property 'value' does not exist on '{}' 
  />
);
```

## Expected Behavior
TypeScript should be able to evaluate the props object passed to `renderChild`, in this case, it should recognize it as `id: number; value: string`.

## Actual Behavior
When wrapped in `styled`, props resolves to `{}`. `renderChild` in the wrapped example throws:
`Error: Property 'id' does not exist on '{}'`
`Error: Property 'value' does not exist on '{}'`

**Comment by probablyup** [comment]
Would either of these just-merged PRs fixed this?

https://github.com/styled-components/styled-components/pull/1806
https://github.com/styled-components/styled-components/pull/1798

You can install a prerelease version for testing with this:

```sh
npm i styled-components@dev
```

**Comment by Igorbek** [comment]
I don't think these PRs are gonna fix this issue.
The problem here is here: `const StyledGenericComponent = styled(GenericComponent)`. With this, `styled` does not expect a generic component, it expects a concrete component (with concrete prop type).
In general, this is almost impossible to distinguish a generic component from a regular one when it comes to higher-order functions. I can think of how it can be worked around, but you can read this TS issue where such problems are discussed: https://github.com/Microsoft/TypeScript/issues/9366

**Comment by thgreasi** [comment]
So far I've been using the following as a workaround:
```ts
const StyledGenericComponent = styled(GenericComponent)`
  position: relative;
`  as any as new <T>() => GenericComponent<T>;

const ThisWorksOnTs29 = <StyledGenericComponent<MyDataStructure>
  data={aMyDataStructureVar}
  />;
```

**Comment by probablyup** [comment]
Hey folks, TS typings for styled-components have been moved to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), so please feel free to move your issue there where you'll receive better community support.

**Comment by jgdev** [comment]
This works perfectly for me:

```typescript
const StyledComponent: new <T>() => Component<T> = styled(Component)`
    background-color: red;
` as any;

export default StyledComponent;
```

**Comment by acro5piano** [comment]
I created `typings/styled-components.d.ts` in my root directory:

```ts
declare module 'styled-components/native' {
  // original node_modules/@types/styled-components/native.d.ts 
  import * as React from 'react'
  import * as ReactNative from 'react-native'

  // ...

  // Add as the workaround. See https://github.com/styled-components/styled-components/issues/1803#issuecomment-407332173
  declare interface StyledFlatList {
    FlatList<T>(styles: any): new () => ReactNative.FlatList<T>
  }

  declare const styled: ReactNativeStyledInterface<DefaultTheme> & StyledFlatList
```

**Comment by waynevanson** [comment]
> This works perfectly for me:
> 
> ```ts
> const StyledComponent: new <T>() => Component<T> = styled(Component)`
>     background-color: red;
> ` as any;
> 
> export default StyledComponent;
> ```

I wonder why the `any`.

Anyway, for those with scoped generics, ya'll could use this. `ReactSlider` is the name of your component.

```tsx
const StyledReactSlider: new <T extends number | number[]>() => ReactSlider<T> = styled(ReactSlider)`
    background-color: red;
` as any;
```

**Comment by osdiab** [comment]
@waynevanson @jgdev @acro5piano I'm confused how you guys are making that work.

Say I have a generic functional component like this:

```ts
export function MyComponent<Item>(
  props: React.PropsWithChildren<MyComponentProps<Item>>
): React.ReactElement | null {
  // ...
}
```

If I do the following, I get an error:

```ts
// => 'MyComponent' refers to a value, but is being used as a type here.
const MyComponentWithStyles: new <T>() => MyComponent<T> = styled(MyComponent)`
    background-color: red;
` as any;
```

This lines up with what @melounek experienced in https://github.com/DefinitelyTyped/DefinitelyTyped/issues/39136 . Not sure how you guys are able to instantiate things this way - am I missing something?

**Comment by osdiab** [comment]
Hi all, I have a solution that worked for me (and doesn't involve type suggestions to `any`). See the full code below.

It would be nice if this could be done a) without a type suggestion, and b) retaining the generic after the `styled` invocation, though I don't think generics can survive through TypeScript's inference passing through a function call like that, so these might be infeasible at the moment. so I think a type suggestion will be as good as it gets for now.

```tsx
interface ExampleProps<Generic> {
  genericMember: Generic;
}
type ExampleComponent<Generic> = React.FC<ExampleProps<Generic>>;

// functions can't "implement" a type as far as I know, so we do it by setting the
// proper values for parameters and return type
function Example<Generic>(
  ...[props]: Parameters<ExampleComponent<Generic>>
): ReturnType<ExampleComponent<Generic>> {
  return <p>{props.genericMember}</p>;
}

// now let's say you want the component, with a string as the generic:
const StyledExample = styled(Example as ExampleComponent<string>)`
  color: red;
`;
const Page: React.FC = () => <StyledExample genericMember="value" />; // works
const OtherPage: React.FC = () => <StyledExample genericMember={5} />; // fails
```

Hope this helps someone!

**Comment by Naararouter** [comment]
Hello! I've found the next solution, maybe, it will help someone else. I've came to this view when I was trying to type my components from antd library, particularly its `Select` component. It can be generic. But above, I'll put a common view of solution.

**Definition:** 
```javascript
export function StyledGeneric<T>(): StyledComponent<React.FC<GenericProps<T>>, {}, {}, never> {
    return styled(props => <Generic<T> {...props} />)`
        // ... some styles
    `;
}
```
**Use-case**
```javascript
// ...other imports
import { StyledSelect } from './StyledSelect';

const SelectBase = <T extends {}>({
   // ...some props
}: SelectWrapperProps<T>) => {
    const handleChange = (selection: T, option: React.ReactElement | React.ReactElement[]) => {
         // ...some handler logic
    };
    const TypedSelect = StyledSelect<T>();
    return (
        <TypedSelect onChange={handleChange}>
            {/* options mapping */}
        </TypedSelect>
    );
};
```

**Comment by TeemuKoivisto** [comment]
After spending way too long figuring out how to preserve the generic props without losing the typings on the props (`Property 'value' does not exist on type IntrinsicAttributes` error), I got it working thanks partly to the snippets here so I wanted to share my solution. The element I'm using the generics for is a dropdown menu currently located at here https://github.com/Aalto-LeTech/CodeClusters/blob/master/frontend/src/elements/Dropdown.tsx

The props:
```ts
type OptionValue = string | number
type Option<K extends OptionValue, V extends OptionValue> = {
  key: K
  value: V
}
interface IProps<K extends OptionValue, V extends OptionValue> {
  className?: string
  options: Option<K, V>[]
  selected?: V
  disabled?: boolean
  required?: boolean
  placeholder?: string
  fullWidth?: boolean
  onSelect: (option: Option<K, V>) => void
}
```

The exports:
```ts
export const GenericDropdown = <K extends OptionValue, V extends OptionValue>() =>
  styled((props: IProps<K, V>) => <DropdownEl<K, V> {...props} />)``

export const Dropdown = GenericDropdown<string, string>()
```

And then you can the generic version whenever you need it like so:
```ts
const CustomDropdown = styled(GenericDropdown<number, string>())`
 ...
`
```

Sadly though the styled components loses the highlighting on the styles of that CustomDropdown component. Oh well. I guess it will have to do.

**Comment by dfernandez-asapp** [comment]
@Naararouter If I read the code example correctly, this line:
```

const TypedSelect = StyledGeneric<T>();
```

Will create a new styled component for each render of `GenericBase`... it's not a good idea to do that.

**Comment by Naararouter** [comment]
@dfernandez-asapp 
yeah, that was a missing, thanks, but...no necessity for a dislike, you can easily fix this, just define this outside of render method and where you already know an exact type (you must have this place in any case somewhere in app).
as another solution, you can use memo for this, but I believe it's an overhead and the first way is more acceptable because is only type-solution.

**Comment by dfernandez-asapp** [comment]
@Naararouter Removed the dislike 😄 don't worry about it... I added it, because if someone sees the solution and does a copy & paste to use, it may found some performance issues with it.

**Comment by Naararouter** [comment]
@dfernandez-asapp, added the comment about this in the initial post, thanks again :)

**Comment by dfernandez-asapp** [comment]
> @dfernandez-asapp, added the comment about this in the initial post, thanks again :)

👍 Cool thanks for the comment. I'm curious how you move the `StyledGeneric<T>` outside since `T` is bound to the parent function. (this is an honest question, since I'm struggling with the same issue).

**Comment by Naararouter** [comment]
@dfernandez-asapp
It's not trivial case, it's a cause of difficult to make 100% solution for each case, but in my project, it was possible to resolve all issues even with our last fix (but now, we need to make, at least, one additional prop - it's just the fastest solution what I could found since you exposed the issue), we have a pretty much tricky cases with TypeScript and I hope it will be useful for you and your adaptation for your project. 
Well...suppose we have structure like this:

1. The same `StyledGeneric` as before, but I'll provide you more concrete implementation from our project: 
```javascript
export function StyledSelect<T>(): StyledComponent<React.FC<SelectProps<T>>, {}, {}, never> {
    return styled(props => <Select<T> {...props} />)`
        // some styles
    `;
}
```
2.  The next step is we have some `SelectBase` component:
```javascript
export const SelectBase = <T extends {}>({
    TypedSelect,
    onChange = () => {},
    options = [],
}: SelectWrapperInterface<T>) => {
    const handleChange = (selection: T, option: React.ReactElement | React.ReactElement[]) => {
        onChange(selection, option);
    };

    return (
        <TypedSelect onChange={handleChange}>
            {options.map((option, index) => (
                <Option key={index} value={option.value}>
                    {option.label}
                </Option>
            ))}
        </TypedSelect>
    );
};
```

3. And also, we have a some form which has a main use-case of this components with some preparation of our new styled:
```javascript
const StringStyledSelect = StyledSelect<string>();
const StringSelect = (props: SelectFieldInterface<string>) => (
    <SelectBase<string> {...props} TypedSelect={StringStyledSelect} />
);
export const InnerForm: React.FC<InnerFormInterface> = () => {
    return (
        <Form>
            <StringSelect />
        </Form>
    );
};
```

So...something like that, hope it is more clear now, in any case, maybe it's a bit overhead solution and sometimes it will be really faster to take just some `any` solution, but...in our project we have strict requirements for typescript definitions and...if there are a some `any` what we can replace with more concrete implementation (even if it has a some complexities), we must make it.

**Comment by Kadrian** [comment]
As a workaround, I'm using the `css` property instead of a styled component, maybe that's an option for someone else as well:

```typescript
const styles = css`
  position: relative;
`;

const MyComp = () => {
  return (
    <MyGenericComponent<SomeType> css={styles} />
  );
};
```

**Comment by choznerol** [comment]
Given `StyledFoo = styled(Foo)`, another workaround is to write `<StyledFoo<FC<FooProps<Bar>>> ... />` (instead of `<StyledFoo<Bar>`) to achieve same type safety as `<Foo<Bar>`.

More: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/39136#issuecomment-719950054

**Comment by badsyntax** [comment]
In the case of ReactNative FlatList, this is the solution I'm using, which seems like the simplest workaround:

```ts
type ItemType = {
  id: string;
  title: string;
};

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const List: new () => FlatList<ItemType> = styled(FlatList)`` as any;
```

**Comment by young666** [comment]
For those of guys looking for a way to generic type of Ant Design component (my case is Ant Design Table), here is my solution:
````javascript
import { Table, TableProps } from 'antd';

class WrapTableType<T> {
  wrapped(e: T) {
    return Table<TableProps<T>>(e);
  }
}

const MyTable = (styled(Table)`...` as React.ComponentType) as <T>(props: TableProps<T>) => ReturnType<WrapTableType<T>['wrapped']>;
````

**Comment by AbreezaSaleem** [comment]
I have been using the following solution: 
```
export const StyledCarousel = styled(FlatList)`
  border-radius: ${wp(2)};
  flex: 1;
` as React.ComponentType as new <T>() => FlatList<T>;
```

But eslint throw an error: `Missing Semicolon` at `as React.Component` and I have no idea why! Can someone please tell me why this is happening/

**Comment by cristianmartinez** [comment]
For anyone having this issue, this is my workaround:

```
const StyledSelect = styled(Select)`
  margin: 0 var(--spacing);
` as typeof Select;

```

**Comment by x1mrdonut1x** [comment]
I have found that I can't pass [transient props](https://styled-components.com/docs/api#transient-props) when using this workaround. Any ideas?

**Comment by michal-kurz** [comment]
> For anyone having this issue, this is my workaround:
> 
> ```
> const StyledSelect = styled(Select)`
>   margin: 0 var(--spacing);
> ` as typeof Select;
> ```

This works for most use-cases, but `StyledSelect` now cannot be [referred to in another styled component definition](https://styled-components.com/docs/advanced#referring-to-other-components):

```typescript
const Select: FC<void> = () => <div />

const StyledSelect = styled(Select)`
  margin: 0 var(--spacing);
` as typeof Select

const SelectWrapper = styled.div`
  &:hover ${StyledSelect} {
    // ...
}
```

<details>
<summary>Results in this error:</summary>
<br>
TS2769: No overload matches this call.   Overload 1 of 3, '(first: TemplateStringsArray | CSSObject | InterpolationFunction<ThemedStyledProps<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "key" | keyof HTMLAttributes<...>> & { ...; }, any>>, ...rest: Interpolation<...>[]): StyledComponent<...>', gave the following error.     Argument of type 'FC<void>' is not assignable to parameter of type 'Interpolation<ThemedStyledProps<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "key" | keyof HTMLAttributes<HTMLDivElement>> & { ...; }, any>>'.       Type 'FunctionComponent<void>' is not assignable to type 'InterpolationFunction<ThemedStyledProps<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "key" | keyof HTMLAttributes<HTMLDivElement>> & { ...; }, any>>'.         Types of parameters 'props' and 'props' are incompatible.           Type 'ThemedStyledProps<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "key" | keyof HTMLAttributes<HTMLDivElement>> & { ...; }, any>' is not assignable to type 'PropsWithChildren<void>'.             Type 'ThemedStyledProps<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "key" | keyof HTMLAttributes<HTMLDivElement>> & { ...; }, any>' is not assignable to type 'void'.   Overload 2 of 3, '(first: TemplateStringsArray | CSSObject | InterpolationFunction<ThemedStyledProps<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "key" | keyof HTMLAttributes<...>> & { ...; } & void & { ...; }, any>>, ...rest: Interpolation<...>[]): StyledComponent<...>', gave the following error.     Argument of type 'FC<void>' is not assignable to parameter of type 'Interpolation<ThemedStyledProps<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "key" | keyof HTMLAttributes<HTMLDivElement>> & { ...; } & void & { ...; }, any>>'.       Type 'FunctionComponent<void>' is not assignable to type 'InterpolationFunction<ThemedStyledProps<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "key" | keyof HTMLAttributes<HTMLDivElement>> & { ...; } & void & { ...; }, any>>'.         Type 'ReactElement<any, any> | null' is not assignable to type 'Interpolation<ThemedStyledProps<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "key" | keyof HTMLAttributes<HTMLDivElement>> & { ...; } & void & { ...; }, any>>'.           Type 'ReactElement<any, any>' is not assignable to type 'Interpolation<ThemedStyledProps<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "key" | keyof HTMLAttributes<HTMLDivElement>> & { ...; } & void & { ...; }, any>>'.             Type 'ReactElement<any, any>' is not assignable to type 'CSSObject'.               Index signature for type 'string' is missing in type 'ReactElement<any, any>'.
</details>

**Comment by cristianmartinez** [comment]
You are right @michal-kurz, and this should be expected since it is breaking the initial inference TS has from the styled function.  Trying to think of a better solution but I'm not sure how to force styled to respect generic types.

**Comment by j-perl** [comment]
Like some of you, I'm using antd and this is the solution I came up with:

```
const styledTable = <RecordType extends object = any>(T: typeof Table) => styled((props: TableProps<RecordType>) => {
    return <T {...props}/>
})`
  ...
`

const MyTable = styledTable<RecordType>(Table/* coming from antd*/)
```

**Comment by colemars** [comment]
```tsx
export const StyledTable = StyledTableInternal as <T>(
  props: TableProps<T>
) => ReturnType<typeof Table>;
```

**Comment by isc30** [comment]
any news on this? it is a blocker for us

**Comment by badsyntax** [comment]
@isc30 I could not find any acceptable solution to this problem. In the end I switched to using emotion and I have zero problems with the emotion types.

**Comment by isc30** [comment]
@badsyntax isn't emotion using `any` all over the place? Last time I checked that's how they handled edge caes like this

**Comment by badsyntax** [comment]
@isc30 not sure, but this exact scenario (I wouldn't call it an edge case) works as expected with emotion.

**Comment by isc30** [comment]
nope, emotion doesn't work either:

```tsx
const X = function<T>(props: { wow: T, hey: T}) { return  null }
const A = styled(X)<{ $extra: 'yes' }>`color: red;`
```

then using it like this:

```tsx
<A wow={123} hey='asd' $extra='yes' />
```

it compiles perfectly and shows the following types (notice the unknown as the prop type instead of it being a generic component):

```tsx
const A: StyledComponent<{
    wow: unknown;
    hey: unknown;
} & {
    theme?: Theme | undefined;
} & {
    $extra: 'yes';
}, {}, {}>
```

**Comment by marcebdev** [comment]
It seems that if you don't need to use the props in the styled template you're ok with some of the above methods. 

However, if you want to use the props in the css you have to make an intermediary React Component that forwards the generic type and then wrap that in `styled()` as so

```TSX
const ExtendedRadioGroup = <T,>(props: StyledRadioGroupProps<T>): ReactElement => (
  <MuiRadioGroup {...props} />
)
const StyledRadioGroup = styled(ExtendedRadioGroup)`
  flex: 1;
  flex-direction: ${(props) => (props.horizontal ? 'row' : 'column')};
  gap: 1rem;
`
```

**Comment by delijah** [comment]
> > For anyone having this issue, this is my workaround:
> > ```
> > const StyledSelect = styled(Select)`
> >   margin: 0 var(--spacing);
> > ` as typeof Select;
> > ```
> 
> For a solution to support extra props passed for styled components CSS, I used
> 
> ```ts
> as <T>(props: SelectProps<T> & { $specialProp: string }) => React.ReactElement;
> ```
> 
> Does anyone see an issue with this approach?

Yes. It will miss out on the execution props like "as", "forwardedAs" and "theme".

**Comment by mikeyjk** [comment]
We have had some mixed success using this approach, which avoids needing `as` or `any`, but I can't claim to fully understand it, and I don't think it works in all instances.

```
export const StyledComponent: typeof BaseComponent = styled(BaseComponent)``;
```

**Comment by caihai123** [comment]
I also encountered a similar problem, but I dealt with it this way. I don't know if this is a solution.
```
const StyledGenericComponent:typeof GenericComponent = styled(GenericComponent)`
  position: relative;
`;
```


> ## TypeScript 2.9.1
> 在使用通用 props 包装组件时使用该`styled(Component)`方法不会保留通用参数，它只是将其默认为`{}`。
> 
> ## 生殖
> import React, { Fragment, ReactNode } from 'react';
> import styled from 'styled-components';
> 
> interface Props<T> {
>   renderChild: (props: T) => ReactNode;
>   values: T[];
> }
> 
> function GenericComponent<T>(props: Props<T>) {
>   return (
>     <Fragment>
>       {props.values.map(props.renderChild)}
>     </Fragment>
>   );
> }
> 
> const ThisWorks = (
>   <GenericComponent
>     values={[{ id: 1, value: 'foo' }]}
>     renderChild={props => <p key={`I_${props.id}`}>{props.value}</p>}
>   />
> );
> 
> const StyledGenericComponent = styled(GenericComponent)`
>   position: relative;
> `;
> 
> const ThisDoesntWork = (
>   <StyledGenericComponent
>     values={[{ id: 1, value: 'foo' }]}
>     renderChild={props => <p key={`I_${props.id}`}>{props.value}</p>} // Errors: Property 'id' does not exist on '{}', Property 'value' does not exist on '{}' 
>   />
> );
> ## 预期行为
> TypeScript 应该能够评估传递给的 props 对象`renderChild`，在这种情况下，它应该将其识别为`id: number; value: string`。
> 
> ## 实际行为
> 当包装在 中时`styled`，props 解析为`{}`。`renderChild`在包装的示例中抛出： `Error: Property 'id' does not exist on '{}'` `Error: Property 'value' does not exist on '{}'`

**Comment by FatahChan** [comment]
```tsx
const StyledTable = <T extends object>(props: TableProps<T>) => {
  return styled(Table<T>)`
    .ant-table-thead > tr > th {
      color: var(--db-color-blue);
      background-color: transparent;
    }
    .ant-table-thead
      > tr
      > th:not(:last-child):not(.ant-table-selection-column):not(
        .ant-table-row-expand-icon-cell
      ):not([colspan])::before {
      content: none;
    }
  `(props);
};
```
