### ISSUE TITLE
css helper awful performance

### ISSUE THREAD

**Issue by alextewpin** [styled-components/styled-components#1805]
I've already summarised my thoughts [here](https://spectrum.chat/styled-components?thread=ccd93ee1-8c3a-419d-820d-72d3971c1694).

`css` helper have awful performance. That's basically it. It see no reason why it should be [recommended  or enforced](https://github.com/styled-components/styled-components/issues/1178), but I see at least one why it should be considered harmful.

I've made a [codesandbox demo](https://codesandbox.io/s/03o7po7mnw) to test `css` performance and as I can see it's ~50-100 times slower than good old functions that returns plain strings.

It that really it? Why it's recommended? Am I missing something?

**Comment by probablyup** [comment]
Interesting. @mxstbr do you have any commentary on this?

If at this point there's no particular usefulness to the css helper other than syntax highlighting, we could just convert it to be a simple passthrough.

**Comment by probablyup** [comment]
Yes, it's unavoidable @taneba 

Simple template literals can't handle interpolated functions, etc in the special way we need for everything to work properly. I've made some refactorings to the helper in v4 as you've noticed, but there is an upper limit to how much we can optimize it.

That being said, you only need to use the `css` helper when you're doing a function, component, or object interpolation. If you're putting in a simple string value, you can use a regular template literal.

**Comment by uriklar** [comment]
Is this still relevant? Should I avoid using the css helper?
