### ISSUE TITLE
Why would the CSS rendering order differ between local and production builds?

### ISSUE THREAD

**Issue by bhellman1** [styled-components/styled-components#1809]
Hello, my ui-components using styled components have begun to differ between local and production builds. See the screenshots below, given the same browser dimensions etc...

Notice how the css style ordering is different between local and production. This is not desired and causing components to break on production. What would cause this?

What would cause styled-components to output the CSS style ordering differently for a particular component? This is not happening for all components. After spending the day trying to debug this, I'm hoping for advice to point me in the right direction. 

Thank you

**Locally:**
<img width="744" alt="local_dom" src="https://user-images.githubusercontent.com/298219/41391516-ffe88a84-6f4f-11e8-8cd5-3a942c575efc.png">
<img width="400" alt="local_css" src="https://user-images.githubusercontent.com/298219/41391515-ffd31582-6f4f-11e8-83a4-529a52b18eaf.png">

**Production:**
<img width="714" alt="prod_dom" src="https://user-images.githubusercontent.com/298219/41391523-0f63fc28-6f50-11e8-8d68-248e054ec541.png">
<img width="402" alt="prod_css" src="https://user-images.githubusercontent.com/298219/41391525-10d53b4e-6f50-11e8-86ea-fce0088f8668.png">

## System:
 - OS: macOS High Sierra 10.13.4
 - CPU: x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
 - Memory: 191.13 MB / 8.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 8.1.4 - ~/.nvm/versions/node/v8.1.4/bin/node
 - Yarn: yarn install v0.24.4
 - [1/4] Resolving packages...
 - success Already up-to-date.
 - Done in 1.13s. - /usr/local/bin/yarn
 - npm: 5.0.3 - ~/.nvm/versions/node/v8.1.4/bin/npm
## npmPackages:
 - styled-components: 3.1.6 => 3.1.6 

## Expected Behavior
Components output renders the same locally and on production

## Actual Behavior
Local and Production component rendering differs. This is not happening for all components, it's random.

**Comment by kitten** [comment]
Are you using SSR by any chance? Try setting up the babel-plugin maybe, if so. Can you maybe try to identify the affected component and extract it into a CodeSandbox or code snippet? Do you maybe have some custom CSS here as well? Maybe it's just the order of your external CSS and the SC CSS?

**Comment by bhellman1** [comment]
We are not using ssr. Sadly the effected component(s) seem to be occurring randomly every time we deploy.

**Comment by probablyup** [comment]
It might be something to do with module concatenation. You can turn it off
via webpack config

**Comment by bhellman1** [comment]
fyi, we're still working to debug the issue. So far we've learned the issue started occurring when we moved from npm to yarn.

**Comment by probablyup** [comment]
Oh interesting. Could be an issue with library duplication.

Does `yarn list styled-components` show more than one installed version? You can also ensure deduplication by adding a [webpack alias](https://www.styled-components.com/docs/faqs#duplicated-module-in-node_modules).

**Comment by bhellman1** [comment]
library duplication, 2 different versions of styled-components via yarn dependency handling  ended up being the issue... Thanks for your help
