### ISSUE TITLE
How can we avoid stylis used as a transitive dependency?

### ISSUE THREAD

**Issue by richardborge** [styled-components/styled-components#1811]
Hi, we are using styled-components in a project we are using, but we are getting some problems when transpiling out project. Basically we are creating a component to be used in another project and for this to work on IE11 we must transpile using ES5. However, for some reason, we get a problem with our transpiled code:
```javascript
var cursorptn = /zoo|gra/
var transformptn = /([,: ])(transform)/g
```
Has been transpiled into
```javascript
var cursorptn = /zoo|gra/var transformptn = /([,: ])(transform)/g
``` 
Which gives us a javascript error.

We see that this code comes from `stylis` and for some obscure reason the ES5 transpiler cant handle the lack of semicolon / lack of `/g` at the end of regex.

Now, we see that in `node_modules/styled-components/dist/styled-components.js` stylis is shipped with semicolons, and would therefore solve the problem nicely, but it seems that the distribution of styled components is not used, instead the code from stylus is being used.

Our package.json looks like this:
```javascript
...
  "dependencies": {
    ...
    "styled-components": "^3.3.2"
  },
...
```
And our package-lock.json looks like this:
```javascript
    "styled-components": {
      "version": "3.3.2",
      ....
      "requires": {
        ...
        "stylis": "^3.5.0",
        "stylis-rule-sheet": "^0.0.10",
        "supports-color": "^3.2.3"
      },
....
    },
    "stylis": {
      "version": "3.5.0",
      "resolved": "https://registry.npmjs.org/stylis/-/stylis-3.5.0.tgz",
      ...
    },
    "stylis-rule-sheet": {
      "version": "0.0.10",
      "resolved": "https://registry.npmjs.org/stylis-rule-sheet/-/stylis-rule-sheet-0.0.10.tgz",
      ...
    },
```
I can´t understand why, when we use styled-components, instead of using it´s own dist styled-components uses the stylis code, can anyone offer some help?

**Comment by probablyup** [comment]
@richardborge You don't need to transpile styled-components or its dependencies. It's already transpiled to working ES5 code.
