### ISSUE TITLE
Nested styled components don't seem to work on React Native

### ISSUE THREAD

**Issue by Zacqary** [styled-components/styled-components#1812]
It seems like the [Referring to other components](https://www.styled-components.com/docs/advanced#referring-to-other-components) feature is built entirely on `className` and CSS inheritance, and there isn't an equivalent system to produce the same behavior on React Native.

## Environment
Environment:
  OS: macOS High Sierra 10.13.5
  Node: 8.9.4
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: Not Found
  Xcode: Xcode 9.4 Build version 9F1027a
  Android Studio: Not Found

## Reproduction
https://snack.expo.io/S1ivtkebX

## Steps to reproduce
On React Native, style a component referring to another component, like so:
```js
const StyledText = styled(Text)`
  color: blue;
`

const StyledView = styled(View)`
  padding-left: 40px;
  padding-top: 120px;
  ${StyledText} {
    color: red;
  }
`
```

## Expected Behavior
`<StyledText>` within `<StyledView>` should be red, and blue when it's outside a `<StyledView>`

## Actual Behavior
`<StyledText>` is always blue

**Comment by probablyup** [comment]
@kitten any ideas?

**Comment by probablyup** [comment]
@Zacqary could you try out `styled-components@3.3.3-2` and let me know if it fixes it?

**Comment by probablyup** [comment]
Okay if I'm not mistaken @kitten, I don't think this feature would work for RN since styling is done inline right?

**Comment by probablyup** [comment]
It's kind of hacky, but you could use nested `ThemeProviders` to achieve something similar :-/

**Comment by mxstbr** [comment]
Yeah, this won't ever work on RN, it just doesn't have support for the cascade at all. Sorry!

**Comment by Zacqary** [comment]
If implementing missing CSS features into RN is outside the scope of this project that's fine. I'll post an update here if I figure out a good hack.

**Comment by chasms** [comment]
Could this under the hood just pass through a `style` prop? Just as it does in css having to pass a `className` prop through React components that are wrapped as `styled(<ReactComponent>)`

**Comment by probablyup** [comment]
That’s how our RN implementation works

**Comment by hyoretsu** [comment]
Make it more clear I guess, although everyone creates tons of components in RN, if you want to nest styles you won't find much info saying that you can't.
