### ISSUE TITLE
Empty classes after extending styles

### ISSUE THREAD

**Issue by psa-gbellencontre** [styled-components/styled-components#1815]
Hello

I'm using StyledComponents since a few weeks, and it's totally awesome.

I'm currently on a project with multiple themes, and I'm working on a Button component with multiple types (primary, secondary, ternary). Lots of combination.

To make this work, I extend styled component multiple times, and I'm getting lots of classes names on my button element (one per theme, and one per button type). Problem is most of them are empty. I don't need a theme class, or a button type class when I use another one.

I searched in the documentation, in Github issues, but I didn't really find a solution to get rid of these empty classes names.

Thanks for you time.

<img width="308" alt="capture d ecran 2018-06-16 a 20 54 26" src="https://user-images.githubusercontent.com/28106884/41501579-896e0afa-71a7-11e8-9b07-56d54e78962e.png">

**Comment by probablyup** [comment]
The stable class names are required for component selector targeting. Don’t
worry, they add minimal size and compress well.
