### ISSUE TITLE
Styles disappear after using withComponent(tag)

### ISSUE THREAD

**Issue by SilencerWeb** [styled-components/styled-components#1817]
## Environment
`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard` - zsh: command not found: npx

## Reproduction
https://codesandbox.io/s/w64609zl37

heading.js
```jsx
import * as React from "react";
import styled from "styled-components";

const Wrapper = styled.h1`
  color: red;
  margin-top: 0;
  margin-bottom: 0;
`;

export const Heading = props => {
  return <Wrapper className={props.className}>{props.children}</Wrapper>;
};
```

index.js
```jsx
import React from "react";
import ReactDOM from "react-dom";
import styled from "styled-components";

import { Heading } from "./heading";

const Name = styled(Heading)`
  width: 100%;
  text-transform: capitalize;
  text-align: center;
  outline: none;
`;

const NameWithChangedTag = styled(Heading)`
  width: 100%;
  text-transform: capitalize;
  text-align: center;
  outline: none;
`.withComponent("h2");

function App() {
  return (
    <div>
      <Heading>Heading with styles</Heading>
      <Name>Still with styles</Name>
      <NameWithChangedTag>
        Boom! Where are styles? Nobody knows! Magic
      </NameWithChangedTag>
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

## Expected Behavior
`NameWithChangedTag` should be rendered like `Heading` but with another tag

## Actual Behavior
`NameWithChangedTag` renders with antoher tag but without styles from `Heading`

P.S. it is simplified example!

**Comment by SilencerWeb** [comment]
@Fer0x what is the difference between my example and example in the docs?

![image](https://user-images.githubusercontent.com/20713191/41508460-a2b9d68a-725e-11e8-9d5a-f11a9a1db873.png)

In this example component `Link` saves all styles from `Button`

**Comment by Fer0x** [comment]
@SilencerWeb The difference is that `styled.button` is low level element without internal styles. When you pass React component, `withComponent` knows nothing about it realization, so it only shallow copy styles, created with `styled()` factory.

I slightly modified your example: https://codesandbox.io/s/rjk6350v4n
There is `AnotherHeading` component. I try to show that when you use `withComponent`, original component will be completely replaced with new.

**Comment by probablyup** [comment]
Thanks @Fer0x for your explanation and example 😄

**Comment by josegoval** [comment]
> @SilencerWeb The difference is that `styled.button` is low level element without internal styles. When you pass React component, `withComponent` knows nothing about it realization, so it only shallow copy styles, created with `styled()` factory.
> 
> I slightly modified your example: https://codesandbox.io/s/rjk6350v4n
> There is `AnotherHeading` component. I try to show that when you use `withComponent`, original component will be completely replaced with new.

Is there any way to "extends" old styles and change its tag with `as` prop or `withComponents`?

**Comment by josegoval** [comment]
> Thanks @Fer0x for your explanation and example 😄

This is what you want [forwardedAs](https://styled-components.com/docs/api#forwardedas-prop) prop.
