### ISSUE TITLE
Importing external SASS file

### ISSUE THREAD

**Issue by haldunanil** [styled-components/styled-components#1818]
Hello and nice work on the library! I'm working on building an application with `reactstrap` as the baseline for my UI components and I want to style these components with a global theme. 

For the most part, I understand that I need to essentially rewrite the global theme file (which is currently written in SASS format) as a JS object. However, I also need to import SASS variables from the bootstrap package and I'm not quite sure how to do that since there's no support for `@import` statements as far as I'm aware. 

Is there a workaround for this that doesn't involve recreating the bootstrap variables?

**Comment by probablyup** [comment]
Hey there. Hmm perhaps there's a converter you can use (or write a simple build step in your project) to generate a JS file off the SCSS variables file and then plug it into a ThemeProvider?

**Comment by haldunanil** [comment]
I looked at https://github.com/jgranstrom/sass-extract-loader but it doesn't seem to have much action going on (last commit was 7 months ago) and gives me a bunch of weird errors when I try to use it. Is there a specific converter or build step you've found that has worked for others?

**Comment by probablyup** [comment]
Maybe this? https://www.npmjs.com/package/sass-to-js-var-loader

I don’t use SCSS so not really sure.

**Comment by probablyup** [comment]
Going to close this though since there's nothing actionable here to be done on the library side.
