### ISSUE TITLE
Media Template Trick

### ISSUE THREAD

**Issue by erikras** [styled-components/styled-components#182]
Hi all. An issue might not be the best place for this, but I wanted to share a little trick I discovered with the `styled-components` community. It's really too simple to be a feature or utility function in the library itself, but I am finding it extremely useful and wanted to give back.

```jsx
const sizes = {
  giant: 1170,
  desktop: 992,
  tablet: 768,
  phablet: 572,
  phone: 376
}

export const media = Object.keys(sizes).reduce((accumulator, label) => {
  accumulator[label] = (...args) => css`
    @media (max-width: ${sizes[label]}px) {
      ${css(...args)}
    }
  `
  return accumulator
}, {})
```

This creates a media template for each of the sizes, so you can do _this_ in your components:

```jsx
const Container = styled.div`
  color: #333;
  ${media.desktop`padding: 0 18px;`}
  ${media.tablet`padding: 0 18px;`}
  ${media.phablet`padding: 0 10px;`}
  ${media.phone`padding: 0 3px;`}
`
```

Thanks for all the work you are doing. `styled-components` is the most elegant styling solution I've seen so far.

**Comment by mxstbr** [comment]
Would love for you to add this to the Tips and Tricks doc! 👏

**Comment by wmertens** [comment]
You know, that's already nice, but if you use the JS mediaquery API, these values can be read from JS and you can render a completely different UI depending on viewport.

I do this in https://www.npmjs.com/package/redux-mediaquery for Redux (so the app redraws on change) but having these values available in styled would also be really nice. Plus, still not sure if it should be in the store and not in context (but then it doesn't force redraw).

**Comment by valscion** [comment]
Would you be OK with changing the breakpoint example values from `px` unit to `em`? It would work properly cross-browser and support users changing their browsers `font-size` accordingly.

Source: https://zellwk.com/blog/media-query-units/

**Comment by mxstbr** [comment]
Yeah sure, I don't mind that.

**Comment by erikras** [comment]
@valscion Thanks for that link. With CSS it's literally possible to learn some new quirk every single day of your life. 😂
