### ISSUE TITLE
Does sass @at-root work in styled-component 

### ISSUE THREAD

**Issue by athimannil** [styled-components/styled-components#1831]
Is there any option to run sass `@at-root` in styled-component  ? Currently  selecting parent element with `&` works fine but unfortunately `@at-root` not seems to be working. 

```
export const ButtonContainer = styled.div`
  display: block
  ${(props) => props.fixed ? `
    position: fixed
    right: 0
    bottom: 0
    left: 0
    z-index: 100
    width: 100%

    @at-root body {
      background-color: tomato;
    }
    ` : ''
}
```

**Comment by mxstbr** [comment]
I'm not sure what that does, but it's definitely not something we want to encourage from looking at your example :wink:

**Comment by athimannil** [comment]
@mxstbr Looking for the solution to apply for `@at-root` feature https://sass-lang.com/documentation/file.SASS_REFERENCE.html#at-root

**Comment by probablyup** [comment]
@athimannil I think this is what you want: https://codesandbox.io/s/m73v75rz09

```js
const Box = styled.div`
  height: 100px;
  width: 100px;
  background: blue;

  body & {
    border: 1px solid red;
  }
`;
```

**Comment by athimannil** [comment]
@probablyup Not really 
I just need to apply properties for parent class. Somethings like this http://sassbreak.com/getting-back-to-our-roots/

**Comment by probablyup** [comment]
Oh I see. Yeah we can't support that for the moment... the `createGlobalStyle` helper in v4 should make it a little easier to arrive at this functionality with something like this though:

```js
const Comp = styled.div`
  color: red;
`;

const GlobalStyle = createGlobalStyle`
  body ${Comp} {
    color: blue;
  }
`;
```

etc
