### ISSUE TITLE
I want to throw away `className` completely, is there any problems will happen?

### ISSUE THREAD

**Issue by manglobe** [styled-components/styled-components#1832]
```
const Button = styled.span`
  height: 36px;
  ${props=>props.styles}
`
class A extends PureComponent {
  render() {
    const { styles, children} = this.props;
    return (
      <Button styles={styles} >
        {children}
      </Button>
    );
  }
}

const styleB = `width: 36px;`
const B = ()=>(
  <A  styles= {styleB}/>
)
```
Hello guys , I'm using `styled-components` for the first time, it's cool !
And I think the `className` was useless now, so I just use `styles` to transmit style string. It works well,
but then I see , I can't use `styled(tagName)`, it need explicitly define `className`.
- Is there any way to solve it ?
- Any other problems will happen without `className`?

**Comment by wmertens** [comment]
Styled-components works using classes (in the DOM at least). So you definitely need to pass `className` to the DOM components.

If you have more questions, it's better to go to the community on https://spectrum.chat

Closing because it's not an issue.
