### ISSUE TITLE
Among many input fields sharing the same state, if one input state  changes, causing all other styled components to re-render in both development and production environment.  

### ISSUE THREAD

**Issue by Mukhammadali** [styled-components/styled-components#1834]
I have a big form with 30-40 styled Input elements along with styled buttons, paragraphs, div containers. And if one input changes, it is causing all styled elements to re-render , and as I type it si lagging significantly, and delaying the input. I tried with Regular HTML inputs along with plain CSS, it is working just fine. We have been using Styled-Components heavily in our project and we cannot move to another library or env and I love SC. I shared the code snippet that I wrote which follows kind of the same structure with our actual project. What am I doing wrong here?  

I am using ComponentShouldUpdate for now as a workaround, but this is unnecessary and annoying to put it in each component. It is not happening with regular HTML elements, so I think there is a bug or I am misusing SC.
## System:
 - OS: macOS High Sierra 10.13.5
 - CPU: x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
 - Memory: 2.39 GB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 8.11.3 - /usr/local/bin/node
 - Yarn: 1.7.0 - /usr/local/bin/yarn
 - npm: 5.6.0 - /usr/local/bin/npm
## npmPackages:
 - styled-components: 3.3.3 => 3.3.3

## Reproduction
You can see the actual code here:
https://stackblitz.com/edit/styled-components-bug

## Expected Behavior
It should only re-render the component which receives different props.  
## Actual Behavior
Here I uploaded the videos , on the left side Input fields and paragraphs with regular HTML and on the right side Styled HTML Elements with SC

https://youtu.be/KTWx3eGl_VE . Production Env
https://youtu.be/u7T3Av8npcA.  Development Env

**Comment by probablyup** [comment]
Hmm I'm not seeing your bug. I have the React devtools open with "trace on updates" enabled and only the input I'm working on seems to be updating.

![update-example](https://user-images.githubusercontent.com/570070/42395155-7370fda4-8122-11e8-961c-379da4fd6302.gif)
