### ISSUE TITLE
styled-components messes with my IDE

### ISSUE THREAD

**Issue by joeLloyd** [styled-components/styled-components#1836]
## Environment

  OS:  macOS High Sierra 10.13.5
  Node:  8.6.0
  Yarn:  1.3.2
  npm:  5.3.0
  Watchman:  4.9.0
  Xcode:  Xcode 9.4.1 Build version 9F2000
  Android Studio:  3.1 AI-173.4697961

## Reproduction

Use phpstorm/webstorm and have react-native imports like 

`import { View } from 'react-native';`

Install `styled-components` with yarn
Check warnings on your imports. They now say

> Cannot resolve symbol View

## Expected Behavior

I expect that my components such as View and Text to still be resolvable like they were before installing styled-components.

## Actual Behavior

Upon installing styled-components all of my imports from react-native are unable to be resolved.

## Additional Notes

These IDE (phpStorm/webStorm) warnings seem to go away if I delete 

> /node_modules/styled-components/flow-typed/react-native.js

Something about this file interferes with my IDE even if I'm not importing `styled-components` into my project. Is it possible that there is some kind of encapsulation problem here?

This is a minor annoyance I wondered if someone knew the real cause or why this file is messing with my IDE.

**Comment by dylmye** [comment]
Have you seen this? https://github.com/styled-components/webstorm-styled-components

**Comment by joeLloyd** [comment]
Yeah I'm using that for syntax highlighting. But its nothing to do with killing my react-native imports.

I have automated the removal of the flow file that causes the problem. I just run this function with node 

``` javascript

const fs = require('fs');

const removeFlowTyped = () => {
	const path = '../node_modules/styled-components/flow-typed/react-native.js';

	if (fs.existsSync(path)) {
		console.log('Found');
		fs.unlink(path, (err) => {
			if (err) throw err;
			console.log(path, ' was deleted');
		});
	} else {
		console.log('not found');
	}
};

removeFlowTyped();

```

It uses relative path so if others want to use this make sure your path is correct.

**Comment by probablyup** [comment]
You can send a PR to update our npmignore file if you’d like. Then this will be excluded.

**Comment by probablyup** [comment]
Hey folks, TS typings for styled-components have been moved to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), so please feel free to move your issue there where you'll receive better community support.
