### ISSUE TITLE
Avoid renderToString twice during SSR

### ISSUE THREAD

**Issue by caribou-code** [styled-components/styled-components#1838]
## Environment

**System:**
 - OS: macOS High Sierra 10.13.4
 - CPU: x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
 - Memory: 1.01 GB / 16.00 GB
 - Shell: 5.3 - /bin/zsh

**Binaries:**
 - Node: 10.5.0 - ~/.nvm/versions/node/v10.5.0/bin/node
 - npm: 6.1.0 - ~/.nvm/versions/node/v10.5.0/bin/npm

**npmPackages:**
 - babel-plugin-styled-components: ~1.5.1 => 1.5.1
 - styled-components: ~3.3.2 => 3.3.3

## Reproduction

**server.js**
```
import { renderToString } from 'react-dom/server';
import { ServerStyleSheet } from 'styled-components';
import express from 'express';
import React from 'react';

const app = express();

app.get('/', (req, res) => {
  const sheet = new ServerStyleSheet();
  const html = renderToString(sheet.collectStyles(<App />));
  const styleElements = sheet.getStyleElement();

  const reactDOM = renderToString(<App styleElements={styleElements} />);
  res.send(`<!DOCTYPE html>${reactDOM}`);
});
```

**App.js**
```
import { injectGlobal } from 'styled-components';
import { normalize } from 'polished';

import React from 'react';

import { Body, HTML } from './App.style';

injectGlobal([normalize()]);

export default = props => (
  <HTML lang="en">
    <head>
      <meta charSet="utf-8" />
      {props.styleElements.map(styleElement => styleElement)}
    </head>
    <Body>
      Hello
    </Body>
  </HTML>
);
```

I'm server side rendering my React app. The `App.js` component holds the core DOM and has both globally injected styles, and individual element styles imported from a separate file `App.style.js`.

In [the docs](https://www.styled-components.com/docs/advanced#server-side-rendering) regarding SSR, there is the following note:

> NOTE
> sheet.getStyleTags() and sheet.getStyleElement() can only be called after your element is rendered. As a result, components from sheet.getStyleElement() cannot be combined with <YourApp /> into a larger component.

This means I've had to do a `renderToString` to render the app and get the styles, then do the same again but passing in the calculated styles. So it's doing the work twice. Is this intended usage? Is there a better way to do it? Or is this a bug?

**Comment by caribou-code** [comment]
@probablyup Not sure I understand. I’ve called renderToString twice - once without injected styles and once with. I’m guessing each time it will do a virtual DOM render of the entire app. I realise it only renders once on client side, but unless I’m mistaken it’s doing the work twice on the server.

**Comment by kitten** [comment]
@caribou-code for a more complete answer, this is unavoidable in your case. Either you can:

- use React Helmet to manipulate the head tags dynamically and keep everything but a dig in the body (or the body itself if you must) dynamic inside React. This is often recommended
- or use our SSR streaming API

The streaming API would work easily with just some small changes and we inject style tags in between chunks which are then removed and accumulated in the browser during runtime.

The first approach might still be worth it, as it’s quite common for scripts (even browser extensions) to mess with the DOM which throws React’s virtual Dom off if you render it dynamically.

Either way, I’d start with the Streamed SSR API: https://www.styled-components.com/docs/advanced#streaming-rendering

**Comment by caribou-code** [comment]
Ok so I guess my approach to having the entire DOM generated in React was not good. With that in mind I've ended up with a solution that uses a static DOM wrapper function and injects the styles and React DOM. I used this approach instead of the streaming because it was something I had started doing previously, and seemed a little easier to understand. Thanks @kitten for your help with this.

My server.js request now looks like this:

```
const html = (
  reactDOM: string,
  styleTags?: string = '',
) => `
  <!DOCTYPE html>
  <html lang="en">
    <head prefix="og: http://ogp.me/ns#">
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1">
      <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
      ${styleTags}
    </head>
    <body>
      <div id="app">${reactDOM}</div>
      <script src="/vendors~app.bundle.js" async defer></script>
      <script src="/app.bundle.js" async defer></script>
    </body>
  </html>
`;

app.get('/', (req, res) => {
  const sheet = new ServerStyleSheet();
  const reactDOM = renderToString(sheet.collectStyles(<App />));
  const styleTags = sheet.getStyleTags();
  res.send(html(reactDOM, styleTags));
});
```

**Comment by kitten** [comment]
@caribou-code seems perfect 🙌 let me know if you need any more help. You can also ask questions on spectrum where responses sometimes come in quicker and by more community members ✨
