### ISSUE TITLE
Typed Props not compatible with Jest

### ISSUE THREAD

**Issue by borisonr** [styled-components/styled-components#1841]
I'm having issues getting Jest running with styled-components and typescript. I'm using babel-jest with @babel/plugin-transform-typescript. Jest doesn't complain about regular typings like `const x: string='hey'` but it complains when I try to type props for a styled component like `const button = styled.div<{height: string}>` In the latter scenario, when I run Jest I get the following error: `ReferenceError: string is not defined` even though my IDE doesn't complain and it runs fine in the browser. I tried defining an interface instead of defining the types within the <>, but then the error is just that the interface is not defined.

What I'm using:
"@babel/core": "^7.0.0-beta.40",
"babel-jest": "^22.4.1",
"@babel/plugin-transform-typescript": "^7.0.0-beta.53",
"styled-components": "^3.3.3",

**Comment by probablyup** [comment]
Hey folks, TS typings for styled-components have been moved to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), so please feel free to move your issue there where you'll receive better community support.
