### ISSUE TITLE
Need Error handling when referencing to none styled components

### ISSUE THREAD

**Issue by xZarisx** [styled-components/styled-components#1846]
When you mistakenly reference to a none styled component like so:

```jsx
const Bar = () => (<p>bar</p>)

const Foo = styled.div`
  & ${Bar} {
    //some styles
  }
`
```

you get an `Uncaught TypeError: Cannot convert a Symbol value to a string` error.

It would be helpful if you got an error that said that you can only reference styled components.

**Comment by probablyup** [comment]
This sounds reasonable. Want to send a PR and make sure the error message is only present for non-production?

**Comment by epilande** [comment]
I can tackle this if no one else wants to
