### ISSUE TITLE
Typescript error in docs example for ThemeProvider

### ISSUE THREAD

**Issue by teddybradford** [styled-components/styled-components#1847]
When implementing [the docs example](https://www.styled-components.com/docs/api#typescript) of how to use ThemeProvider in a Typescript project, the following error appears:

> Exported variable `ThemeProvider` has or is using name `React.ComponentClass` from external module `./node_modules/@types/react/index` but cannot be named.

That error is thrown in this block:

```ts
const {
  default: styled,
  css,
  injectGlobal,
  keyframes,
  ThemeProvider
} = styledComponents as ThemedStyledComponentsModule<ThemeInterface>;
```

**Comment by wetoolaguer** [comment]
Thanks @teddybradford, this helped me fix it.

**Comment by probablyup** [comment]
Hey folks, TS typings for styled-components have been moved to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), so please feel free to move your issue there where you'll receive better community support.
