### ISSUE TITLE
Detect window resize from styled component?

### ISSUE THREAD

**Issue by JanoshRiebesell** [styled-components/styled-components#1848]
I have a responsive nav that is fully displayed on laptop and upwards and slides out upon clicking a burger icon on tablets and smaller. The slide out effect uses a CSS transition which unfortunately also triggers at the breakpoint from laptop to tablet.

I would like the transition to occur only if the user clicks the burger icon, a close button or any of the links in the nav. The way I thought to achieve this was to disable the CSS transition while the browser window resizes.

Is there any way to determine if the window is currently being resized from a styled component?

Here's my nav component:
```
export const Nav = styled.nav`
  display: grid;
  overflow: scroll;
  ${mediaQuery.minTablet} {
    grid-auto-flow: column;
    grid-gap: 2rem;
  }
  ${mediaQuery.tablet} {
    position: fixed;
    right: 0;
    z-index: 2;
    background: ${props => props.theme.darkGray};
    padding: 2rem;
    grid-gap: 1rem;
    height: 100vh;
    min-width: 30vw;
    grid-auto-rows: max-content;
    transform: translate(${props => props.hideNav ? `100%` : `0`});
    transition: transform 0.5s ease;
  }
`
```

**Comment by Djelnar** [comment]
@JanoshRiebesell can you please provide an example how would you do that without styled-components?

**Comment by JanoshRiebesell** [comment]
@Djelnar [It seems like this is usually done using jQuery and may also be achieved with vanilla JS DOM functions](https://stackoverflow.com/questions/11131875/what-is-the-cleanest-way-to-disable-css-transition-effects-temporarily/16575811).

**Comment by Djelnar** [comment]
@JanoshRiebesell resize event has no 'start' and 'finish' events, but it can be implemented using this  [answer](https://stackoverflow.com/a/5926068), but styled-components itself has nothing related to DOM events, so you can achieve this feature by writing your own piece of code like HOC that attaches some prop during resize event.
Am I right? @probablyup

**Comment by probablyup** [comment]
That's correct.

> I would like the transition to occur only if the user clicks the burger icon, a close button or any of the links in the nav.

This will be very difficult to achieve using CSS transitions. I'd almost recommend going full JS instead to get the level of control you're desiring. Greensock is a pretty amazing animation library for this purpose.
