### ISSUE TITLE
Specific `attrs` cannot be merged inside component that is wrapped with `styled()`

### ISSUE THREAD

**Issue by fiznool** [styled-components/styled-components#1849]
## System:
 - OS: macOS High Sierra 10.13.5
 - CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
 - Memory: 135.84 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 10.6.0 - /usr/local/bin/node
 - Yarn: 1.7.0 - /usr/local/bin/yarn
 - npm: 6.1.0 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^3.3.0 => 3.3.3 

## Reproduction

https://codesandbox.io/s/885yo82z19

## Steps to reproduce

Please see the codesandbox. Note that this is a highly contrived example - the inline styles in a real project are ones that change frequently, hence the reason for putting them in the style attribute in the first place (as per #134).

Essentially:

- set up a component which uses a styled-component that defines a `style` key as one of its `attrs`
- set up another component which wraps this first component with `styled` and attempts to set different inline styles

## Expected Behavior

- The `...props.style` spread inside the `Paragraph` component should merge the styles from the `BlueText` component

## Actual Behavior

- Inline styles are not merged.

I believe this is related to #1343, however in that example `extend` is used directly on the styled-component, in this example we are wrapping the styled-component in a regular component, and using the `styled()` wrapper instead.

**Comment by wzchua** [comment]
`<Paragraph style={this.props.style}>` overwrites the style from attrs

```
const Paragraph = styled.p.attrs({
  style: props => ({
    ...props.styleParent,
    fontSize: `${props.fontScale}em`
  })
})``;
<Paragraph styleParent={this.props.style}>
```
Doing it like this will make it work as expected.

**Comment by probablyup** [comment]
@wzchua correct. I'm making a change to handle the "style" prop though specifically since that's likely a common use case.

**Comment by fiznool** [comment]
@probablyup thanks for implementing this!
