### ISSUE TITLE
API breaks composition

### ISSUE THREAD

**Issue by oliviertassinari** [styled-components/styled-components#185]
I believe that the signature of the `styled` API is breaking some **composition** capabilities.
> (tag: Component) =>
(strings: Array<string>, ...interpolations: Array<Interpolation>) =>
WrappedComponent: Component

Let's say you want to add a pure logic, connect a field with redux and get the window width.
You have 3 Higher order Components to do so: `pure`, `withWidth` and `connect`.

You would right something like this:
```jsx
import styled from 'styled-components';

const MainActionButton = () => <div />; 

const HoCs = compose(
  pure,
  withWidth(),
  connect(mapStateToProps),
)(MainActionButton);

export default styled(HoCs)`cursor: pointer;`

```

So I think that it would be much better to have **curried functions** (unary arity). So we can write:
```jsx
import styled from 'styled-components';

const MainActionButton = () => <div />; 

export default compose(
  pure,
  styled`cursor: pointer;`,
  withWidth(),
  connect(mapStateToProps),
)(MainActionButton);

```

*compose is taken from recompose, it's a simple [flowRight](https://lodash.com/docs/4.16.6#flowRight)*.

I have already opened a similar issue on [react-jss](https://github.com/cssinjs/react-jss/issues/37).

**Comment by mxstbr** [comment]
This was discussed at length in #81, please refer to that issue! This is on purpose, for a variety of reasons.
