### ISSUE TITLE
Support objToCss in the public API

### ISSUE THREAD

**Issue by joelnet** [styled-components/styled-components#1850]
Consider supporting `objToCss` in the public API.

I have a styled-components theme that I want to dynamically import everything in a specific section.

```
// example theme
const theme = {
  typography: {
    body: {
      fontSize: "0.875rem",
      fontWeight: 400,
      fontFamily: ["Roboto", "Helvetica", "Arial", "sans-serif"],
      lineHeight: "1.46429em",
      color: "rgba(0, 0, 0, 0.87)",
    }
  }
}
```

I want to avoid this:

```
const Section = styled.div`
  font-size: ${theme => theme.typography.body.fontSize},
  font-weight: ${theme => theme.typography.body.fontWeight},
  font-family: ${theme => theme.typography.body.fontFamily},
  line-height: ${theme => theme.typography.body.lineHeight},
  color: ${theme => theme.typography.body.color},
`
```

This works. This is exactly what I need to do...

```
import { objToCss } from "styled-components/lib/utils/flatten";

export const Section = styled.div`
  ${props => objToCss(props.theme.typography.body)};
`
```
...but I am importing styled-components/lib/utils/flatten, which doesn't look like it's part of the "public" API. This can change in the future, so it is risky.

Is there a better way I should be doing this? Or could styled-componets expose `objToCss` as part of the public API?

**Comment by nahumzs** [comment]
what about:
```js
const Wrapper = styled(Box)({
  color: 'blue'
})
```

**Comment by probablyup** [comment]
Going to close, I think @nahumzs's recommendation to just use object styles satisfies what you're trying to do.
