### ISSUE TITLE
Cannot target child components by prop modifier

### ISSUE THREAD

**Issue by JonJamesDesign** [styled-components/styled-components#1853]
## System:
 - OS: macOS High Sierra 10.13.4
 - CPU: x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
 - Memory: 624.50 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 9.11.1 - /usr/local/bin/node
 - Yarn: 1.5.1 - /usr/local/bin/yarn
 - npm: 5.6.0 - /usr/local/bin/npm
## npmPackages:
 - styled-components: ^3.3.3 => 3.3.3

&nbsp;

## Steps to reproduce

I have created two styled components, `Header.js` and `Banner.js`:
&nbsp;
`MyReactComponent.js`:
```
  <Header>
    <img src="some/logo.jpg" />
  </Header>
  <Banner fullHeight>
    <h1>Page Title</h1>
  </Banner>
```

When I place an instance of `Banner` with a `fullHeight` prop beneath a `Header` component, I want to be able to to adjust the `min-height` of the `Banner` component, to compensate for the header.

`Banner.js`:
```
  import styled from 'styled-components'

  export const Banner = styled.div`
    padding: 100px 0;
    ${props => props.fullHeight && `
      min-height: 100vh;
    `}
  `
```

`Header.js`:
```
  import styled from 'styled-components'
  import { Banner } from '../ui-elements'

  export const Header = styled.header.attrs({
    role: 'banner'
  })`
    position: fixed;
    left: 0; top: 0;
    width: 100%; height: 150px;
    background-color: black;

    + ${Banner} {
      padding: 50px 0;
      {props => props.fullHeight && `
        min-height: calc(100vh - 150px)
      `}
    }
  `
```

&nbsp;

## Expected Behavior

The `Banner` component beneath the `Header` component has the padding reduced from `100px 0` to `50px 0`, and the `min-height` adjusted if the `fullHeight` prop exists.

&nbsp;

## Actual Behavior

The `Banner` component beneath the `Header` component has the padding reduced from `100px 0` to `50px 0`, **but** the `min-height` is **not** adjusted if the `fullHeight` prop exists.

**Comment by JonJamesDesign** [comment]
<sup>(Just to clarify the problem...)</sup>

In conventional `CSS`, this would be easy:
```
 1    .banner {
 2      padding: 100px 0;
 3      &.fullHeight { min-height: 100vh; }
 4    }
 5
 6    .header {
 7      position: fixed;
 8      left: 0; top: 0;
 9      width: 100%; height: 150px;
10      background-color: black;
11      + .banner {
12      padding: 50px 0;
13      &.fullHeight { min-height: calc(100vh - 150px); }
14      }
15    }
```

`Line 13` is the one I'm struggling to replicate with the `styled-components` library.

**Comment by probablyup** [comment]
I think the issue is multiple classes being generated at the same level of specificity. When you do an interpolation, the resulting style ends up being another class that's appended to the element.

To bump up the specificity, you could try this:

```css
&& + ${Banner} {
  padding: 50px 0;
  {props => props.fullHeight && `
    min-height: calc(100vh - 150px)
  `}
}
```

**Comment by probablyup** [comment]
@JonJamesDesign can you confirm if the suggestion took care of your issue?
