### ISSUE TITLE
Customize class name hash function ala getLocalIdent?

### ISSUE THREAD

**Issue by rossPatton** [styled-components/styled-components#1856]
## What will it allow you to do that you can't do today?
Customize the generated class name ala the `getLocalIdent` function feature that css-modules allows you to do

## How will it make current work-arounds straightforward?
It will give users total control over what the class name output looks like, beyond just adding displayNames / fileNames to the class

## What potential bugs and edge cases does it help to avoid?
It will allow for reduced css, which is one of the advantages css-in-js systems are supposed to have

If this feature already exists, then my bad. I was not able to find anything in the documentation or in prior issues to suggest that it does. With css-modules, I use a custom function for class names that allows me to generate much shorter names in production, it would be nice to be able to do the same in styled-components

The kind of names styled-components tends to generate: `s8ji26z-0 iwNJkL`

The kind of (much shorter) names I can generate with css-modules using a custom `getLocalIdent` function: `a0_a7`

**Comment by Oreville** [comment]
I also enjoyed this feature in CSS Modules. I spent the morning looking through styled-components documentation looking for such a feature, but unfortunately wasn't able to find anything. This would be very nice and hopefully will be added in the very near future.

**Comment by probablyup** [comment]
What's the value add here? We're generally 👎 on this sort of customization unless there's a compelling use case.

**Comment by rossPatton** [comment]
The value add is reduced css output. I don't understand the point of using unnecessarily long class names that increases the amount of html and css required to render the page

Ideally, the output would be as short as possible already and not require customization, but that is currently not the case

**Comment by probablyup** [comment]
Just put displayName: false into the Babel plugin options

**Comment by rossPatton** [comment]
? Yes, obviously there are some options for reducing output. The point is that even when you do that, you still get unnecessarily long class name output

in more tangible terms, just shortening the class name output on a site i've been working on recently cut css by ~20kb, which is nothing to sneeze at considering we didn't have to remove a single line of css to do it

i realize maybe that's not the case for every site, but I don't understand why it's not at least an option

**Comment by probablyup** [comment]
Because the library would have to be greatly restructured for that to work
and there isn’t much value in it due to gzip on the HTML side.

**Comment by probablyup** [comment]
In any case, we likely won’t support something like this in the forseeable future. People can 👍 the OP if they really want it and we’ll do a sweep over unimplemented feature requests at a later date.

**Comment by theinterned** [comment]
I'm working on a code base that uses a lot of snap shot testing of components (via [storyshots](https://github.com/storybooks/storybook/tree/master/addons/storyshots/storyshots-core)). 

We are having a lot of trouble with class-name churn where the addition of a single new styled component will cause the classes for all styled components to change.

This is leading to a lot of noise in our tests. 

I'm looking for a way that we can render completely stable deterministic styled components class names in jest.

My ideal would be to use something like what CSS modules gives you where the class name would be generated form a function that is given the filename, component name, a uuid ... maybe the path?

Maybe there is another way to achieve this?

**Comment by three60five** [comment]
@theinterned https://www.styled-components.com/docs/tooling#jest-integration

**Comment by theinterned** [comment]
@three60five okay we are using this, but it still doesn't let me control the class name does it? and the class name is still determined by the number of styled components in scope right?

**Comment by three60five** [comment]
@theinterned sorry, can't help you. sounds like your issue is with storyshots.

**Comment by theinterned** [comment]
Okay thanks for your time! If I figure it out I’ll post here.

**Comment by theinterned** [comment]
For anyone else coming across this, it turns out that we weren't correctly applying the `jest-styled-components` serializer in Storyshots. We were using the `multiSnapshotWithOptions` which ignores serializers configured in your projects jest config.

A simplified version of our `storyshots.test.js` file looks like this:

```js
import initStoryshots, {
  multiSnapshotWithOptions,
} from '@storybook/addon-storyshots';
import styleSheetSerializer from 'jest-styled-components/src/styleSheetSerializer';

initStoryshots({
  test: multiSnapshotWithOptions({}),
  snapshotSerializers: [styleSheetSerializer],
});

```
