### ISSUE TITLE
Why cannot you add simple support for such styles as border-bottom?

### ISSUE THREAD

**Issue by SilencerWeb** [styled-components/styled-components#1858]
Why cannot you add support for border-bottom?
![image](https://user-images.githubusercontent.com/20713191/43045096-cd8a4a06-8dcb-11e8-964d-535da69ba3ab.png)

What about box-shadow? Or you think this is more convenient way https://github.com/styled-components/styled-components/issues/709#issuecomment-295274475?

What about a simple transform?
![image](https://user-images.githubusercontent.com/20713191/43045126-23c0bb4e-8dcc-11e8-9241-dd8db5f97d12.png)

What about calc()?
![image](https://user-images.githubusercontent.com/20713191/43045758-1a38aa26-8dd8-11e8-9db4-634f9f6c73e7.png)

**Comment by Djelnar** [comment]
@SilencerWeb Are you sure they valid react-native stylesheet properties?

**Comment by SilencerWeb** [comment]
@Djelnar 
1. `border-bottom` - yes, but you have to write all styles separately, like `border-bottom-width`, `border-bottom-color`, when just `border` can be written as `border: 1px solid #000`.
2. `box-shadow` - yes, but again, you have to write all styles separately like mentioned [here](https://github.com/styled-components/styled-components/issues/709#issuecomment-295274475).
Also these would work:
`box-shadow: 2px 4px 12px red;`
`boxShadow: 2px 4px 12px red;`
These would not work (neither with rgb):
`box-shadow: 2px 4px 12px rgba(202, 202, 214, 0.25);`
`boxShadow: 2px 4px 12px rgba(202, 202, 214, 0.25);`
3. `transform` - it does not support percentages, i guess it is react-native issue
4. `cacl()` - no sure, but why not to realize this? it is simple math but it would be very useful

**Comment by probablyup** [comment]
Related #1874 

Going to close this one and consolidate discussions there since support for these things is driven by the RN stylesheet, not this library.
