### ISSUE TITLE
Automatically apply attrs when object is given

### ISSUE THREAD

**Issue by Gameghostify** [styled-components/styled-components#1865]
I have a really simple feature request that could potentially improve the syntax of applying `attrs` a little.

Lets say we have a styled card component with `attrs` for our `background-color`:

```
var Card = styled.div.attrs({
  bg: "tomato"
})`
  background-color: ${props => props.bg}
`
```

Now, applying `attrs` like that can make the code look really cluttered - so why not use something like this:

```
var Card = styled.div.attrs(this.attrs)`
  background-color: ${props => props.bg}
`

Card.attrs = {
  bg: "tomato"
}
```

Automating this - simplifying it so we only would have to define `Card.attrs` - would be really cool

**Comment by probablyup** [comment]
That’s not how JS works. “this” is bound to the lexical scope at that point
and would not give you the result you want.

**Comment by Gameghostify** [comment]
The method above using `this` was rather a demonstration than actual syntax to be used.

What I was trying to say is that the concept of React's `defaultProps` could also be applied to `.attrs`, this way the code would look a bit better.

**Comment by probablyup** [comment]
I understand, probably not something we’ll do. It’d be easy enough for you
to write a helper function to do that though if you want in your project.
