### ISSUE TITLE
allow shorthand to render props without interpolations functions

### ISSUE THREAD

**Issue by alzalabany** [styled-components/styled-components#1868]
3. Do you have a feature request?
=============================

- currently styled-components can adapt to props by usage of interpolates/ nested functions in tags.
- we also support amazing ThemeProvider

yet when it comes to building component that depends on may props, tag literal become very hard to read, lines can be too long. specially when using ThemeProvider then you need to access a property inside props.theme so you cannt even use simple distructor `${({key})=>key}`

what do you think about using Strings in Tag expressions to point styledcomponent that this is a props attribute ?

## What will it allow you to do that you can't do today?

according to (css grammer)[https://www.w3.org/TR/CSS21/grammar.html#scanner] there are many symbols that is not used by anyway in Css, and so sytled-components can check Expressions of type string if exp[0] = agreed sign we render prop inplace.

## How will it make current work-arounds straightforward?

currently only way supported

```js
const StyledUserImage = styled.img`
  vertical-align: middle;
  ${({isBlock})=>isBlock && 'display:block'};
  height: ${props=>!props.imageHeight};
  border-radius: 50%;
  margin-right: 10px;
  margin-top: ${({imageMarginTop})=>imageMarginTop};
  margin-bottom: ${({theme})=>theme.imageMarginBottom};
```

well since $ sign is not part of any valid native css property/value names -that im aware of- we can do something like

```js
// use $sign for prop.variables
// use $! && $!![key],val for simple on/off switchs
const StyledUserImage = styled.div`
  vertical-align: middle;
  display: ${'$!!isBlock,block'} ${'$!!isFlex,flex'};
  height: ${"$imageHeight"};
  border-radius: 50%;
  margin-right: 10px;
  margin-top: ${"$imageMarginTop"};
  margin-bottom: ${"$theme.imageMarginBottom"};
```

implemenration is a matter or checking if `typeof key && key[0]==='$'`

**Comment by probablyup** [comment]
Not going to do this, sorry. We are pretty strongly opposed to “Magic” and we are trying to keep the css composed here as close to vanilla as possible + functions.

**Comment by alzalabany** [comment]
hmm, agree its magic. good call.

how about a slim mixin toolbelt ?

**Comment by probablyup** [comment]
Hmm I’m not sure how you’d do that other than make a wrapper around `styled` and intercept the template literals, then do something with the interpolations... but this is probably a lot of effort.

**Comment by jehillert** [comment]
Apologies in advance if this post is completely daft... still relatively new to coding ...in fact, I will probably delete it later.

So I understand the OP requested a baked-in shorthand to avoid coding out interpolation functions, and the response was that there are compelling reasons not to do that. And I know some compactness can already be had by using styled(MyAlreadyStyledComponent) as a way to avoid duplicating code.  But I was wondering:
1. Are there currently any other ways to shorthand interpolations in styled-components?   
2. If not, could something like one of the following implementations work (implicit in this question is that the suggested implementation would not be a ridiculous way of doing things for other reasons?)

**Shareable Aliases for Styled Components Defined in the Same File.**
So at the top of a component file it might say something like:
```
import styled, { StyledAliases } from 'styled-components';

StyledAliases = {
  p = props;
  p.t = props.theme;
}
```
Then in different styled components defined in the same file:
```
StyledComponent1 = styled.div`
  background-color: ${p => p.t.bgColor};
  margin:  ${p => p.t.m(1)};
  padding:  ${p => p.t.p(2)};
`;

StyledComponent2 = styled.div`
  color: ${p => p.t.fgColor};
  margin:  ${p => p.t.m(2)};
  padding:  ${p => p.t.p(2.5)};
`;
```
Note: p() and m() are just functions embedded in the theme, and not part of the shorthand I am trying to illustrate.

**Alias for whole function call... made accessible to styled components defined in that same file**
```
import styled, { AliasedInterpolations } from 'styled-components';

AliasedInterpolations = {
  p0 = `${props => props.theme.p(0)}`;
  p1 = `${props => props.theme.p(1)}`;
  p1_5 = `${props => props.theme.p(1.5)}`;
}
```
Then in the styled components:
```
StyledComponent1 = styled.div`
  padding: p0 p1;
`;

StyledComponent2 = styled.div`
  padding: p0 p1 p1_5 p0;
`;

StyledComponent3 = styled.div`
  padding: p1_5 p1 p1_5 p0;
`;
```

**Destructure theme values at the top of the file and make accessible to styled components defined in that same file**
This last one is probably the most absurd of the three.  
```
import styled, { pAsProps, StyledDestructuring } from 'styled-components';

p = pAsProps(props);
{ bgColor_p, cardHeight_p, cardWidth_p, m_p } = StyledDestructuring(p.theme);
```
Then in the styled components:
```
StyledCard = styled.div`
  background-color: ${p => bgColor_p};
  height:  ${p => cardHeight_p};
  width:  ${p => cardWidth_p};
  margin:   ${p => m_p(1.5)};
`;

StyledModal = styled.div`
  background-color: ${p => bgColor_p};
  height:  ${p => cardHeight_p};
  width:  ${p => cardWidth_p};
  margin:   ${p => m_p(3)};
`;
```

**Comment by adriannecris** [comment]
I know the issue is old, but  we take advantage of the css utility and styled object properties, to remove the ugly long interpolation of props by destructuring the props and implement it in the css utility

```js
import styled, { css } from "styled-components"

const Button = styled.button(
  ({ bgColor, fontColor }) => css`
    background: ${bgColor};
    color: ${fontColor};
  `
);

function App() {
  return (
    <Button bgColor="#000" fontColor="#fff"> Hello World </Button>
  )
}
```

[Example in codesandbox](https://codesandbox.io/s/styled-object-css-utility-7c05ge?file=/src/App.js)
