### ISSUE TITLE
Way to create components conditionally

### ISSUE THREAD

**Issue by DavidHe1127** [styled-components/styled-components#1869]
Need to refactor code below to use **styled-component** style.

```js
{isResult && <table className="fkrc-result-table-ui">xxxx</table>}
{!isResult && <table className="fkrc-table-ui">xxxx</table>}
```
As you can see, `div` element can be built and rendered conditionally.

But with **styled-component**, it appears you have to always create them upfront:

```js
const ResultTable = styled.div`
  ...
`;

const Table = styled.div`
  ....
`;
```

Wonder if it is possible to conditionally build and render the component like what you would with pure react.

**Comment by MeCKodo** [comment]
```JavaScript
function createTab(isResult) {
  const ResultTable = styled.table``;
  const Table = styled.table``;
  return isResult ? resultTable : table
}

```

**Comment by probablyup** [comment]
You can but it’s highly discouraged because the dynamically-generated
components won’t be cached properly. Making them ahead of time is
significantly more performant.

Your sample code seems pretty straightforward, why can’t you just make the
components beforehand?

**Comment by DavidHe1127** [comment]
@probablyup thanks for your suggestions.
I don't even know components created up-front can be cached. Can you share links with me regarding how components can be cached?

When comes to refactoring, the first thing comes to mind is create the components only when you need it.

**Comment by probablyup** [comment]
Just make them outside your React class and then use them like any other
React component.

**Comment by MeCKodo** [comment]
That's right.It's my fail. I was forgotten the cached.
Thank you very much.  @probablyup And how do you think about this example?

```JavaScript
const Table = styled.table``;
const ResultTable = styled.table``;

const YourTable = (props) => props.isResult ? resultTable : Table;

class App extends Component {
  render() {
    const { isResult } = this.state;

    return (
      <YourTable isResult={isResult} />
    )
  }
}

```

**Comment by probablyup** [comment]
Yeah that should work, but you’ll probably want to pass the props down to
the table in YourTable.

**Comment by probablyup** [comment]
It’s just something that happens on construction and componentWillMount for
the first time. If you make new versions of the styled component class
dynamically, it’ll keep re injecting the styles over and over
