### ISSUE TITLE
Default export not set to `styled` global

### ISSUE THREAD

**Issue by maxsteenbergen** [styled-components/styled-components#1870]
I'm trying to use styled-components in browser without any bundler, so I just copied the CDN link from the docs. It loads fine, but when I want to actually use it I get the message `styled.<element> is not defined`. I found out that when I use `styled.default.<element>` it works, however, this breaks my syntax highlighting and who knows else that I haven't run into yet.
I still have limited knowledge of ES6 modules, but it appears that the `styled` object is not properly exported as default and set as the `styled` global as used in the docs.
I made a screenshot of the FF Dev Edition console here -> 

![FF Developer Edition console](https://maxsteenbergen-2.stackstorage.com/public-share/5zC5J1ZFu6CDHk4/preview?path=/&mode=thumbnail&size=medium)

Sidenote: we use ReactJS.NET to transpile JSX to JS on the fly but given I get the same results directly from the browser console I do not think this is the culprit. Adding `styled = styled.default;` to the very top of the document works too, though obviously this is quite a terrrible hack.

**Comment by probablyup** [comment]
This isn't really fixable since the library has both a default and named exports.

**Comment by maxsteenbergen** [comment]
I don't have any issue with the workaround I'm using at the moment since we're making a strictly contained product so I'm actually fine with the situation as is. However, I do think the team needs to decide on what your recommendation in this situation is and, more importantly, reflect it in the docs.

**Comment by probablyup** [comment]
Going to address this for 4.0
