### ISSUE TITLE
Cannot simulate press event on styled TouchableOpacity 

### ISSUE THREAD

**Issue by petermekhaeil** [styled-components/styled-components#1871]
## System:
 - OS: macOS High Sierra 10.13.4
 - CPU: x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
 - Memory: 2.24 GB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 8.9.4 - ~/.nvm/versions/node/v8.9.4/bin/node
 - Yarn: 1.7.0 - ~/.yarn/bin/yarn
 - npm: 6.0.1 - ~/.nvm/versions/node/v8.9.4/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^3.3.3 => 3.3.3 

## Reproduction

Hi,

A styled TouchableOpacity does not render with the `onPress` prop, so a press event can not be simulated in Jest.

```js
import React from 'react';
import { TouchableOpacity } from 'react-native'
import renderer from 'react-native-test-utils';
import mockComponent from 'react-native/jest/mockComponent';
import styled from 'styled-components/native';

const StyledComponent = styled.TouchableOpacity``;

describe('Styled TouchableOpacity', () => {

  it('should render', () => {
    jest.mock('TouchableOpacity', () => mockComponent('TouchableOpacity'));
    const mockFn = jest.fn();
    const Component = <StyledComponent onPress={mockFn}>Click Me</StyledComponent>;
    const tree = renderer(Component).toJSON();
    expect(tree).toMatchSnapshot();
  });

  it('should invoke press event', () => {
    jest.mock('TouchableOpacity', () => mockComponent('TouchableOpacity'));
    const mockFn = jest.fn();
    const Component = <StyledButton onPress={mockFn}>Click Me</StyledButton>;
    const dom = renderer(Component);

    expect(mockFn).not.toHaveBeenCalled();
    dom.simulate('press');
    expect(mockFn).toHaveBeenCalled();
  });

});

```

The snapshot being rendered does not show the `onPress` prop.

```
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`Styled TouchableOpacity should render 1`] = `
<View
  accessible={true}
  isTVSelectable={true}
  onResponderGrant={[Function]}
  onResponderMove={[Function]}
  onResponderRelease={[Function]}
  onResponderTerminate={[Function]}
  onResponderTerminationRequest={[Function]}
  onStartShouldSetResponder={[Function]}
  style={
    Object {
      "opacity": 1,
    }
  }
>
  Click Me
</View>
`;

```

## Expected Behavior

`onPress` prop to be rendered in snapshot and test to pass when simulating press event.
The snapshot should also render a TouchableOpacity component not a View.

An example of a native TouchableOpacity snapshot:

```
// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`TouchableOpacity should render 1`] = `
<TouchableOpacity
  activeOpacity={0.2}
  onPress={[MockFunction]}
>
  Click Me
</TouchableOpacity>
`;
```

## Actual Behavior

`onPress` prop is missing and test fails when trying to simulate press event.

We are not sure if we are missing a step, or if this is a bug.

Cheers,
Peter

**Comment by probablyup** [comment]
I think it might have something to do with that Jest method you're calling. We don't mess with the props in the way you're describing.

A few things:

1. Jest mocks should go at the top of the file, not inline per test.
2. It looks like Jest itself has issues mocking RN components, see this issue for more info: https://github.com/facebook/jest/issues/1720
