### ISSUE TITLE
Styled ReactNative TextInput doesn't have a `focus` method.

### ISSUE THREAD

**Issue by purespace** [styled-components/styled-components#1872]
## Environment
  OS:  macOS High Sierra 10.13.6
  Node:  8.9.3
  Yarn:  1.7.0
  npm:  5.5.1
  Watchman:  4.9.0
  Xcode:  Xcode 9.2 Build version 9C40b
  Android Studio:  3.1 AI-173.4819257

## Steps to reproduce

Create a styled TextInput and programmatically focus on the field
```
const HiddenInput = styled.TextInput`
    opacity: 0;
    position: absolute;
    z-index: 1;
`

onCirclePress = () => {
    this.textInput.focus();
};

<HiddenInput
     ref={textInput => {
          this.textInput = textInput;
      }}
      value={hubId}
      onKeyPress={this.onKeyPress}
      autoFocus
 />
```

## Expected Behavior
The field should focus

## Actual Behavior

<img width="374" alt="screen shot 2018-08-01 at 10 23 35" src="https://user-images.githubusercontent.com/41284215/43513300-53978d1a-9575-11e8-9480-d1859e85bb66.png">

**Comment by probablyup** [comment]
use innerRef not ref
