### ISSUE TITLE
Switch RN Stylesheet implementations

### ISSUE THREAD

**Issue by probablyup** [styled-components/styled-components#1874]
https://github.com/vitalets/react-native-extended-stylesheet seems to be far better than the built-in one RN offers and supports stuff like media queries.

What do you think @kitten?

**Comment by mxstbr** [comment]
I feel like we should deviate as little as possible from the built-in StyleSheet to avoid confusion and reduce the API surface area. In fact, I've been considering that we should revert our initial choice to make RN styles "look like" web styles (with `px` and stuff), and only allow a direct translation of the objects. E.g.

```JS
const Box = styled.View`
  font-size: 16;
  padding: 8;
`

// instead of what we require right now, which doesn't really make sense on RN

const Box = styled.View`
  font-size: 16px;
  padding: 8px;
`
```

While that's kinda nice when coming from a web dev background, lots of RN devs come from mobile/RN-only backgrounds, which makes this really confusing/hard to know when to put `px` and when not to put `px`. I've started feeling like the "a bit nicer way to write styles for devs with web background" isn't worth the additional mental overhead for everybody else.

**Comment by probablyup** [comment]
Isn’t the one of the points of RN though to lower the friction of web devs transitioning to mobile development through being able to reuse familiar patterns?

I agree that units get weird in native land, but the other stuff like media queries are highly requested.

**Comment by SilencerWeb** [comment]
@probablyup omg, it is brilliant, devs with web background will love media queries, rems, percents, pseudo classes and other things from this library

**Comment by kitten** [comment]
@mxstbr I definitely second that. I’m surprised actually that there’s no libraries out there yet that provide a lean library for media queries for instance that ends up working with the same API on RN as well.

I don’t see any provider API where additional units are introduces, or pseudo classes working out well implementation-wise.

But on the other hand I don’t think it’d be wise to remove the translations we now have as a lot of people are relying on them.
