### ISSUE TITLE
Missing name in typescript definition 

### ISSUE THREAD

**Issue by tsantef** [styled-components/styled-components#1878]
I started getting this error while compiling: 

```
...node_modules/styled-components/typings/styled-components.d.ts
(98,52): Cannot find name 'Component'.
```

https://github.com/styled-components/styled-components/blob/26be229adbc5629927dead3b95cf1076d88abcd6/typings/styled-components.d.ts#L98

This issue started happening in v3.3.3 
v3.3.2 does not have this issue.

**Comment by Ky6uk** [comment]
`v3.3.3` also ok for me. Possible duplicate of #1875

**Comment by tlaak** [comment]
I'm getting this with `v3.3.3` as well

**Comment by tlaak** [comment]
Component is imported as ReactComponent alias, so changing the `Component<object>` to `ReactComponent<object>` on line `98` seems to resolve the issue. Not sure though if it's actually fixing it or just making the error go away 🤔

**Comment by kachkaev** [comment]
There might be a fix in https://github.com/styled-components/styled-components/pull/1879

**Comment by probablyup** [comment]
Duplicate of https://github.com/styled-components/styled-components/issues/1875
