### ISSUE TITLE
using html entities via content

### ISSUE THREAD

**Issue by thisguychris** [styled-components/styled-components#188]
## Version
1.0.5

## Reproduction
http://www.webpackbin.com/VyBp2UlWz

## Steps to reproduce
add `&:after { content: '\2192'; }` inside any line element

## Expected Behavior
should output html arrow / entity, etc.  →

## Actual Behavior
parse error "Octal literal in strict mode ..."

**Comment by thisguychris** [comment]
I'd like to add use case for this. Basically, content inside &:after or &:before are very useful for adding bullets, arrows, icons or whatever pseudo styling for your list.

**Comment by mxstbr** [comment]
Just need to escape the backslash. This works perfectly fine:

```JS
content: '\\2192';
```

That's why we have a linter. 😉

**Comment by thisguychris** [comment]
@mxstbr may I know what rule where you using in your linter to see this error?

**Comment by geelen** [comment]
Ah what a pain! I don't think there's anything we can do about this, that's just a fundamental difference from JS strings and CSS text. But it means you can't quite "just copy-paste CSS!" which is what I was hoping for.

**Comment by geelen** [comment]
Changed the title to help people googling this error message in future.

**Comment by viiiprock** [comment]
hah, I spent hours for this, even I though it's must be JS problems

**Comment by thysultan** [comment]
[String.raw](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Template_literals#Raw_strings) could fix this, though runtime support is less that great.
