### ISSUE TITLE
className did not match server

### ISSUE THREAD

**Issue by caribou-code** [styled-components/styled-components#1880]
I've found a few issues posted on this topic already but the context was sometimes different and others were closed/locked. None solved my problem, hence I'm creating a new issue.

#### System:
 - OS: macOS High Sierra 10.13.4
 - CPU: x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
 - Memory: 6.23 GB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
#### Binaries:
 - Node: 10.7.0 - ~/.nvm/versions/node/v10.7.0/bin/node
 - npm: 6.1.0 - ~/.nvm/versions/node/v10.7.0/bin/npm
#### npmPackages:
 - babel-plugin-styled-components: 1.5.1 => 1.5.1
 - styled-components: 3.4.0 => 3.4.0

## Reproduction

I am using NextJS with styled components. I have a custom .babelrc file in the root of my project that looks like this:

```
{
  "presets": ["next/babel"],
  "env": {
    "development": {
      "plugins": [
        ["styled-components", {
          "displayName": true,
          "ssr": true
        }]
      ]
    },
    "production": {
      "plugins": [
        "@babel/plugin-transform-react-inline-elements",
        ["styled-components", {
          "displayName": false,
          "ssr": true
        }]
      ]
    }
  }
}
```

Now I have the following test code in my project:

**./Reset.style.js**
```
import styled from 'styled-components';

const Input = styled.input`
  display: block;
`;

export default Input;
```

**./index.style.js**
```
import styled from 'styled-components';
import InputReset from './Reset.style';

export const InputStyled = InputReset.extend`
  height: 2rem;
`;
```

In development I run `npm run server` command to boot up the NextJS development server. Package.json script below:

```
"scripts": {
    "server": "NODE_ENV=development next"
}
```

## Expected Behavior

- An instance of `<InputStyled />` should have the stying `display: block; height: 2rem;`
- No errors to show in the console

## Actual Behavior

- In development mode, the expected behaviour happens on first browser load. On page refresh I get the following error:
`warning.js:33 Warning: Prop `className` did not match. Server: "n0htw-0-Resetstyle__Input-kUBTJg fZJnKC" Client: "n0htw-0-Resetstyle__Input-ccbgDZ hpsTWS"`

I've tried countless potential solutions but nothing seems to be working for me to get rid of these console errors. I don't get the error in production.

**Comment by mxstbr** [comment]
Does this work?

```JS
export const InputStyled = styled(InputReset)`
  height: 2rem;
`;
```

**Comment by mxstbr** [comment]
Yeah, that's unfortunately an issue with `.extend` that we haven't been able to solve, which is why we'll be deprecating it in favor of the `styled(Comp)` notation in a future major version!

Sorry for the troubles, glad to hear it's working now.

**Comment by caribou-code** [comment]
Ah right. Perhaps if it doesn't work correctly with things like NextJS, and will be deprecated soon, it should be removed from the docs? Otherwise people like me that are fairly new to SC go and learn it and start using it in a project only to find it doesn't work and is deprecated soon after...

**Comment by mxstbr** [comment]
Yeah good point, a PR adding a deprecated badge and a note where it breaks to the docs would be much appreciated: https://github.com/styled-components/styled-components-website :pray:

**Comment by caribou-code** [comment]
Sure. I'll take a look if I get a chance.

**Comment by kachkaev** [comment]
I also had this warning in my Next.js app and it was related to the use of ````.extend`` ```` and `withComponent()`:

```jsx
import styled from "styled-components";

const LogoNoLink = styled.div`
  /* shared css */
`;

const LogoLink = LogoNoLink.withComponent("a").extend`
  /* bespoke css */
`;
```

Switching to `styled(LogoNoLink)` did not help, because `withComponent("a")` was cancelling all  shared css declared in `LogoNoLink`:

```jsx
// ! this is not working !

const LogoLink = styled(LogoNoLink)`
  /* bespoke css */
`.withComponent("a");
```

---

Workaround:

```jsx
import styled, { css } from "styled-components";

const logoCss = css`
  /* shared css */
`;

const LogoNoLink = styled.div`
  ${logoCss};
`;

const LogoLink = styled.a`
  ${logoCss};
  /* bespoke css */
`;
```

No more warning  🎉

**Comment by dalfriedrice** [comment]
I am trying to find a solution for my problem which is somewhat related to this but still no solution.

**Error** => Warning: Prop `className` did not match. Server: "sc-jDwBTQ hmnZjO" Client: "sc-jDwBTQ hNPaAr

I am using matchmedia with styled components and this error is appearing when I am trying to load my page initially on mobile width

**Expected**
The matchmedia mobile class should be applied to the div

**Actual**
From the server, it is giving the desktop class but on client the matchmedia is trying to change the class for mobile, but not happening giving the above error

**Comment by probablyup** [comment]
Make your matchmedia changes in a useEffect. Server and client output must
be equal on initial mount, this is a general react rule for rehydration.

**Comment by dalfriedrice** [comment]
@probablyup I already applied that solution, but I was taking that as hack
Is applying changes in useEffect is the only solution..?

**Comment by aezakmi** [comment]
Spent a lot of time and found that my problem was in the wrapping `styled-components` module by custom file. I tried to avoid typescript problems with themes, so it was looking like:
`
import { DefaultTheme } from 'Utils/styles';
import baseStyled, {
	createGlobalStyle,
	css,
	ServerStyleSheet,
	ThemedStyledInterface,
	ThemeProvider,
} from 'styled-components';

export { createGlobalStyle, css, ServerStyleSheet, ThemeProvider };
export default baseStyled as ThemedStyledInterface<DefaultTheme>;
`

Have no ideas why does it corrupt everything: all my classes became unreadable and server didn't match with server styles, so I just changed this paradigm on declaration:

`
// styled.d.ts
import 'styled-components';
import { DefaultTheme as theme } from 'Utils/styles';

declare module 'styled-components' {
	// eslint-disable-next-line @typescript-eslint/no-empty-interface
	export interface DefaultTheme extends theme {}
}
`

And it solved everything, hope it'll help you!

**Comment by jasonsilberman** [comment]
hi @aezakmi, just wanted to say that i've been trying to debug this problem for quite a long time and finally found your comment which solved my problem. Still not sure what the reason was but thank you very much!
