### ISSUE TITLE
data-styled-components contain all classes from all sessions in server side rendering  

### ISSUE THREAD

**Issue by adambatso** [styled-components/styled-components#1884]
## System:
 - OS: macOS High Sierra 10.13.4
 - CPU: x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
 - Memory: 160.34 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 8.4.0 - /usr/local/bin/node
 - npm: 5.3.0 - /usr/local/bin/npm
## npmPackages:
 - babel-plugin-styled-components: 1.5.1 => 1.5.1 
 - styled-components: 3.2.5 => 3.2.5 
- next: 4.2.1
## Reproduction
Hi,
We use next and styled components server Side Rendering  and we implement it according to styled-component documentation. We have issue that the data-styled-component look the same across all the pages ( it shouldn’t be the same) and every time we switch to a different page with server side navigation new styles are been added to the data-styled-component. which causes the html page to grow. So for example when we start the node server the data-styled-components for this page, theculturetrip.com/europe/russia/articles/a-local-photographers-walking-guide-to-st-petersburg/,  look like this 
![image](https://user-images.githubusercontent.com/9741960/43684338-2a8bd478-98a7-11e8-96a2-4846a9dd90d9.png)
after couple of hours (more pepole enter to our server) the data-styled-components object look like 
![image](https://user-images.githubusercontent.com/9741960/43684360-7a14469c-98a7-11e8-8174-948c0c0aeada.png)

## Steps to reproduce
1. start node server.
2. Enter to couple of pages (server side navigation)
3. Check page source for data-styled-components
## Expected Behavior
The data_styled_components should be the same in all sessions and it should contain only the classes that the page used. 
## Actual Behavior
It look like the object contain all the styled from all user sessions.
The second issue is that is equal to all pages.

**Comment by mxstbr** [comment]
What does your ssr code look like? When do create new ServerStyleSheets?

**Comment by adambatso** [comment]
Hi,
Thanks you for your quick answer i just fixed the issue.
The issue was that the new ServerStyleSheets was in _document render function and not in getInitialProps.
when i change it the data_styled_components (in my local machine) work as expect.

Thanks!
