### ISSUE TITLE
Broken on TypeScript?

### ISSUE THREAD

**Issue by adalberht** [styled-components/styled-components#1888]
## Environment
```
## System:
 - OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
 - CPU: x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
 - Memory: 318.69 MB / 7.69 GB
 - Container: Yes
 - Shell: 5.4.2 - /usr/bin/zsh
## Binaries:
 - Node: 10.7.0 - ~/.nvm/versions/node/v10.7.0/bin/node
 - Yarn: 1.9.2 - ~/.nvm/versions/node/v10.7.0/bin/yarn
 - npm: 6.2.0 - ~/.nvm/versions/node/v10.7.0/bin/npm
## npmPackages:
 - styled-components: ^3.4.0 => 3.4.1 
```

Hi guys I tried to import styled-components from my typescript react file (just a simple import, `import styled from "styled-components") and I got this error:

```(179,59): Generic type 'StyledComponentClass<P, T, O>' requires between 2 and 3 type arguments.```

I even followed the [docs](https://www.styled-components.com/docs/api#typescript) to add support for the TypeScript but it's not working.

Is there any issue with this or this is just me?

Any help would be appreciated. Thank you!

**Comment by kitten** [comment]
This has unfortunately slipped through but is already fixed on master. It’ll be fixed in the next patch https://github.com/styled-components/styled-components/pull/1886

**Comment by farzadmf** [comment]
Is there any way to know when the next patch will be released?

**Comment by probablyup** [comment]
Tomorrow
