### ISSUE TITLE
SSR duplicates stylesheets on refresh

### ISSUE THREAD

**Issue by ronnyhaase** [styled-components/styled-components#1890]
### System:
 - OS: macOS High Sierra 10.13.6
 - CPU: x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
 - Memory: 111.95 MB / 8.00 GB
 - Shell: 3.2.57 - /bin/bash
### Binaries:
 - Node: 9.10.1 - /usr/local/bin/node
 - Yarn: 1.6.0 - /usr/local/bin/yarn
 - npm: 6.1.0 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
### npmPackages:
 - babel-plugin-styled-components: ^1.5.1 => 1.5.1 
 - styled-components: 3.4.1 => 3.4.1 

## Reproduction

I cloned the official example of styled-components with NextJS: https://github.com/zeit/next.js/tree/master/examples/with-styled-components

It works as expected with initial version *^2.1.0*.
It works as expected with version *3.3.3*.
__It does not work as expected with *3.4.0* and *3.4.1*__

Using different versions of NextJS or the Babel plugin did not impact the behavior.

## Steps to reproduce
Run `npm run dev`, view page source and hit refresh with >= 3.4.0.

## Expected Behavior
The created stylesheet exists once.

## Actual Behavior
The created stylesheet gets duplicated with every browser refresh.
~It does *not* occur after a hot reload.~ 
It also happens in production mode. [See comment](https://github.com/styled-components/styled-components/issues/1890#issuecomment-410644078) by @elgubbo

---

~It's by no means a show blocker, since you usually don't refresh when using HMR, but~ I think it still might be a bug.
As far as I saw in the NextJS repo this occured as well before styled-components SSR was stable at some point.
If you'd like me to try to isolate the problem out of NextJS, shout.
Thank you!

**Comment by elgubbo** [comment]
same thing is happening here, even in production mode - meaning over time our document size grows very very large - will downgrade to 3.3.3 for now.

**Comment by elgubbo** [comment]
does not work for us with 3.3.3 btw. same issue - going back further

**Comment by mxstbr** [comment]
Seems to have been okay with `3.0.2` according to twitter? https://mobile.twitter.com/toolmantim/status/1026401600661676032

@elgubbo it'd be great if you could pinpoint the exact version where it broke :pray:

**Comment by ronnyhaase** [comment]
I can not confirm that it occurs on 3.3.3 as well!

Both running via Next and static export behave as expected.
@elgubbo May I ask if you are absolutely sure that you downgraded properly?

**Comment by josephluck** [comment]
Second this - I've downgraded to `2.4.1` which is working okay - I'll do some more digging!

**Comment by toolmantim** [comment]
I don't think we're experiencing any problems on 3.3.3 — after reverting back (buildkite/site#173) https://buildkite.com/home is looking 👌🏼 again.

**Comment by Sly777** [comment]
Is it possibly related to react version? We had no problem when it was like this below;

```
"react": "^16.2.0"
"react-dom": "^16.2.0"
"styled-components": "^3.1.6"
```

**Comment by kitten** [comment]
Can someone here add some output of what's being generated here?

It's hard to quickly get an idea of what's going wrong, looking just at the description :)

**Comment by josephluck** [comment]
What we've found is that `sheet.collectStyles` will append a duplicate set of styles on subsequent calls. I've attached a screenshot of what happens.

I haven't investigated what's going on under the hood yet, but I assume that there's a reference that isn't cleared when a fresh `ServerStyleSheet` is instantiated. I'll do some digging and see if I can provide something more concrete!

![screenshot from 2018-08-06 11-02-35](https://user-images.githubusercontent.com/11628330/43710699-40c10e4a-9968-11e8-8008-eb0c19ed5f8d.png)

**Comment by kitten** [comment]
@josephluck Can you show me some excerpts of the style tags content themselves please? Specifically the raw-HTML result (not inspect) pre-JS-runtime, and the post-JS-runtime style tags (without content will do)

I basically would like to see where the duplication takes place and what the rehydration does, if anything

**Comment by josephluck** [comment]
**Pre-JS-runtime** via `view-source` using `"styled-components": "^3.4.1",` on a clean server, first visit

```
<style data-styled-components="dBJVys bpJAGW jLQkRA lctWYD iDPIKf hjWMSY cJlpmh kScyrz lgadhd lasZkf guKXoy gBIPIe jWobCN gjwCtd jvccXB cUvvdE iXzFkB NkhCm bpzmFZ gQGuxx kSoors lQfOr ksxotE dpjReh jkMDVE ePGmst bJEZTv jqREyx fplzRC bKKqGz gPzBgn NVmOC chianT iBMAZp ezousU euLgjZ gGihdt cERNaV lpsHMD iVwvoN eOiECa ciSJwP fJPXZE gsISJH bIRigW gtxwJQ dtWjJM leuhoB gRBovt srFOU kKVqur iSQoUz hkPetm bvoVDP hvqhSZ glxTKv eKtJzo kFpBPR kfmzfj kElIJu iDyrgY laYXKv jDprLg gJArzd dwxPFE cFUSrI eRNsrA fmCmQg bmyfCi iNFNWt fwFdSK cqXgne dvhjsc dslXRt cjIWFT cNCzro jidmAY gKaLC iEJJRn hcqLiS dOBjDe cAlHyH RxJla jDITAu jdAiyf iAhsnd geyBTV hmuCCp oomAx isFIbZ bQQWKQ fzmqgp fNdtQr hBcayn fpMWRb bimOta cHjanj dOQqWG lhXRMf beqeYO bEDcPW gyVQRV jdQuMQ kowMQv kzKrle bRmzSO PSsop hxytJN gVtdXO gLZbyk hPLecy kAErAd">
--
  | /* sc-component-id: sc-bdVaJa */
  | .jqREyx{padding:0 1.25rem;margin-bottom:0;margin-left:auto;margin-right:auto;margin-top:0;max-width:78.75rem;width:100%;} @media (min-width:48rem){.jqREyx{padding:0 1.25rem;width:95%;}} @media (min-width:64rem){.jqREyx{width:87.5%;}}
/* sc-component-id: sc-htpNat */
--
  | .jvccXB{text-transform:uppercase;font-weight:700;line-height:1.2em;}.cUvvdE{color:#f2f2f2;line-height:1.2em;}
  | /* sc-component-id: sc-dnqmqq */
```

**Pre-JS-runtime** via `view-source` using `"styled-components": "^3.4.1",` on a clean server, third visit

```
<style data-styled-components="dBJVys bpJAGW jLQkRA lctWYD iDPIKf hjWMSY cJlpmh kScyrz lgadhd lasZkf guKXoy gBIPIe jWobCN gjwCtd jvccXB cUvvdE iXzFkB NkhCm bpzmFZ gQGuxx kSoors lQfOr ksxotE dpjReh jkMDVE ePGmst bJEZTv jqREyx fplzRC bKKqGz gPzBgn NVmOC chianT iBMAZp ezousU euLgjZ gGihdt cERNaV lpsHMD iVwvoN eOiECa ciSJwP fJPXZE gsISJH bIRigW gtxwJQ dtWjJM leuhoB gRBovt srFOU kKVqur iSQoUz hkPetm bvoVDP hvqhSZ glxTKv eKtJzo kFpBPR kfmzfj kElIJu iDyrgY laYXKv jDprLg gJArzd dwxPFE cFUSrI eRNsrA fmCmQg bmyfCi iNFNWt fwFdSK cqXgne dvhjsc dslXRt cjIWFT cNCzro jidmAY gKaLC iEJJRn hcqLiS dOBjDe cAlHyH RxJla jDITAu jdAiyf iAhsnd geyBTV hmuCCp oomAx isFIbZ bQQWKQ fzmqgp fNdtQr hBcayn fpMWRb bimOta cHjanj dOQqWG lhXRMf beqeYO bEDcPW gyVQRV jdQuMQ kowMQv kzKrle bRmzSO PSsop hxytJN gVtdXO gLZbyk hPLecy kAErAd">
--
  | /* sc-component-id: sc-bdVaJa */
  | .jqREyx{padding:0 1.25rem;margin-bottom:0;margin-left:auto;margin-right:auto;margin-top:0;max-width:78.75rem;width:100%;} @media (min-width:48rem){.jqREyx{padding:0 1.25rem;width:95%;}} @media (min-width:64rem){.jqREyx{width:87.5%;}} .jqREyx{padding:0 1.25rem;margin-bottom:0;margin-left:auto;margin-right:auto;margin-top:0;max-width:78.75rem;width:100%;} @media (min-width:48rem){.jqREyx{padding:0 1.25rem;width:95%;}} @media (min-width:64rem){.jqREyx{width:87.5%;}} .jqREyx{padding:0 1.25rem;margin-bottom:0;margin-left:auto;margin-right:auto;margin-top:0;max-width:78.75rem;width:100%;} @media (min-width:48rem){.jqREyx{padding:0 1.25rem;width:95%;}} @media (min-width:64rem){.jqREyx{width:87.5%;}}
  | /* sc-component-id: sc-htpNat */
```

As you can see, it duplicates the `.jqREyx` each render.

For some reason (might be related?) the injected style tag appears empty when inspected (`<style data-styled-components=""></style>`) however when I inspect styles using Chrome's developer tools, the rules point to this style tag. So I'm unable to give you the HTML output post-JS-runtime right now.

Hope this helps!

**Comment by mxstbr** [comment]
> As you can see, it duplicates the .jqREyx each render.

Any chance you could show us the component responsible for that class, you might be able to infer it based on the class contents?

**Comment by probablyup** [comment]
In production mode we use an alternate injection process that devtools
doesn’t show yet for some reason. The styles are there though, just in the
style sheet object model not in the DOM

**Comment by kitten** [comment]
@probablyup @mxstbr The only difference in logic I can spot is this, which might be a potential bug either way. When sheets are cloned they inherit all `deferred` arrays. So we keep adding more and more duplicate rules to `deferred` now for each cloned sheet from master that is still around since we're not immutably adding on new rules here:

https://github.com/styled-components/styled-components/blob/2d8dc789fd2bae88968318770a0911feec495dac/src/models/StyleSheet.js#L279

https://github.com/styled-components/styled-components/pull/1843/files#diff-4e63369bd36b3727c0e1c99cd6ef1459R279

Sorry for not spotting this during the review. Mutable stuff is obviously great for perf optimisations but come with subtle bugs.

**Comment by josephluck** [comment]
> Any chance you could show us the component responsible for that class, you might be able to infer it based on the class contents?

No trouble, it's a pretty standard styled-component:

```
interface Props {
  textAlign?: variables.TextAlign
  backgroundColor?: variables.Color
  position?: variables.Position
  marginBottom?: variables.Spacing
  marginTop?: variables.Spacing
}

const wrapper: StyledFunction<Props & React.HTMLProps<HTMLDivElement>> =
  styled.div

export const Wrapper = wrapper`
  padding: 0 ${variables.spacing._20};
  margin-bottom: ${({ marginBottom }) =>
    marginBottom ? variables.spacing[marginBottom] : 0};
  margin-left: auto;
  margin-right: auto;
  margin-top: ${({ marginTop }) =>
    marginTop ? variables.spacing[marginTop] : 0};
  max-width: ${variables.size._1260};
  width: 100%;

  @media (min-width: ${variables.media.tablet}) {
      padding: 0 ${variables.spacing._20};
      width: 95%;
  }

  @media (min-width: ${variables.media.desktop}) {
      width: 87.5%;
  }
`
```

**Comment by toolmantim** [comment]
If it helps, here's how to re-create it using [buildkite/site](https://github.com/buildkite/site):

```shell
git clone https://github.com/buildkite/site.git buildkite-site
git checkout renovate/styled-components-3.x
cd buildkite-site
yarn install
env NODE_ENV=production yarn run build
env NODE_ENV=production yarn run start
```

You can see the ever-growing style block:

```
curl -sI http://localhost:3000/ | grep Content-Length
Content-Length: 23490
curl -sI http://localhost:3000/ | grep Content-Length
Content-Length: 32193
curl -sI http://localhost:3000/ | grep Content-Length
Content-Length: 40896
curl -sI http://localhost:3000/ | grep Content-Length
Content-Length: 49599
```

vs doing the same, but on v3.3.3:

```
$ curl -sI http://localhost:3000/ | grep Content-Length
Content-Length: 23490
$ curl -sI http://localhost:3000/ | grep Content-Length
Content-Length: 23490
$ curl -sI http://localhost:3000/ | grep Content-Length
Content-Length: 23490
$ curl -sI http://localhost:3000/ | grep Content-Length
Content-Length: 23490
```

Having a quick look, they grow like this:

```css
/* sc-component-id: pages__Section-ottsxv-2 */
.hQmYDN{margin-top:150px;margin-bottom:150px;}
/* sc-component-id: ottsxv-2-pages__Section-hxexeD */
.gKFcBQ{margin-top:150px;margin-bottom:150px;margin-top:100px;position:relative;}
```

```css
/* sc-component-id: pages__Section-ottsxv-2 */
.hQmYDN{margin-top:150px;margin-bottom:150px;} .hQmYDN{margin-top:150px;margin-bottom:150px;}
/* sc-component-id: ottsxv-2-pages__Section-hxexeD */
.gKFcBQ{margin-top:150px;margin-bottom:150px;margin-top:100px;position:relative;} .gKFcBQ{margin-top:150px;margin-bottom:150px;margin-top:100px;position:relative;}
```

```css
/* sc-component-id: pages__Section-ottsxv-2 */
.hQmYDN{margin-top:150px;margin-bottom:150px;} .hQmYDN{margin-top:150px;margin-bottom:150px;} .hQmYDN{margin-top:150px;margin-bottom:150px;}
/* sc-component-id: ottsxv-2-pages__Section-hxexeD */
.gKFcBQ{margin-top:150px;margin-bottom:150px;margin-top:100px;position:relative;} .gKFcBQ{margin-top:150px;margin-bottom:150px;margin-top:100px;position:relative;} .gKFcBQ{margin-top:150px;margin-bottom:150px;margin-top:100px;position:relative;}
```
