### ISSUE TITLE
Repeated / appended classes when refreshing SSR

### ISSUE THREAD

**Issue by leebenson** [styled-components/styled-components#1896]
I haven't done any investigation of this yet, so forgive the lack of a bug template -- I wanted to get some quick feedback first, in case anyone has seen this before. I'll do some proper analysis and amend as needed.

But basically - hitting refresh on an SSR'd Styled Components appends _existing_ class names to the root.

Example (me slamming on refresh):

![refresh-error](https://user-images.githubusercontent.com/719722/43779952-6ccb01f0-9a51-11e8-99ad-38b58a5dd4c7.gif)

Weird. Never seen this until now. Anyone come across that before?

**Comment by probablyup** [comment]
Yes this is a duplicate. We’re shipping the patch in a few hours

**Comment by leebenson** [comment]
Thanks. Apologies for the dupe.
