### ISSUE TITLE
Version 3.4.2 Tagged Template Literals Broke

### ISSUE THREAD

**Issue by zicodeng** [styled-components/styled-components#1897]
### System:
 - OS: macOS High Sierra 10.13.6
 - CPU: x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
 - Memory: 96.96 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
### Binaries:
 - Node: 10.5.0 - ~/.nvm/versions/node/v10.5.0/bin/node
 - Yarn: 1.9.2 - /usr/local/bin/yarn
 - npm: 6.2.0 - ~/.nvm/versions/node/v10.5.0/bin/npm

## Reproduction
```
import React from 'react';
import styled from 'styled-components';

const Form = styled.div`
    width: 500px;
    height: 500px;
    background-color: pink;
`;

class StyledComponentsForm extends React.Component {
    render() {
        return (
            <Form></Form>
        );
    }
}
```

When I inspect the element, classname is produced and attached to `<form>`, but style is missing

## Expected Behavior
See a 500x500 pinky form

## Actual Behavior
form with no style

**Comment by probablyup** [comment]
Yes you can’t call them both the same import name. In the emotion babel
config there is an option to change the import variable name so they won’t
conflict

**Comment by zicodeng** [comment]
I was reading the plugin's option. They do have `importedNames` option. Really appreciate your help!
