### ISSUE TITLE
SSR mismatch when using .extend in 3.4.2

### ISSUE THREAD

**Issue by disintegrator** [styled-components/styled-components#1898]
## System:
 - OS: macOS High Sierra 10.13.6
 - CPU: x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
 - Memory: 226.79 MB / 16.00 GB
 - Shell: 5.4.2 - /usr/local/bin/zsh
## Binaries:
 - Node: 8.11.3 - /usr/local/bin/node
 - Yarn: 1.9.4 - /usr/local/bin/yarn
 - npm: 6.2.0 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: 1.5.1 => 1.5.1 
 - styled-components: 3.4.2 => 3.4.2 

## Reproduction

https://glitch.com/edit/#!/steel-coriander

## Steps to reproduce

- Click "Show" on the glitch demo
- Open developer tools
- Note the React client/server mismatch warning

## Expected Behavior

No mismatch warning

## Actual Behavior

```
Warning: Prop `className` did not match. Server: "s8do7ct-0-pages__Text-jHVPQi jCLvdG" Client: "s8do7ct-0-pages__Text-csBzLo kVCOkx"
```

**Comment by mxstbr** [comment]
`.extend` always has SSR checksum mismatches—replace `Comp.extend` with `styled(Comp)` and it'll be fixed! 

We'll deprecate `.extend` in the next major version.

**Comment by disintegrator** [comment]
Thank you!!!
