### ISSUE TITLE
Typescript: Unable to provide prop types to CSS Helper

### ISSUE THREAD

**Issue by seanemmer** [styled-components/styled-components#1901]
It is possible to provide Typescript prop types to a regular styled component (ThemedStyledFunction) using the following technique (as per the official docs at https://www.styled-components.com/docs/api#typescript):

```
interface StyleProps {
  row?: boolean,
}

export const Flex = styled<StyleProps>(component)`
  display: flex;

  ${p => p.row && css`
    flex-direction: row;
  `}
}
```

However, it is not possible to do so with a CSS block generated using the CSS helper (ThemedCssFunction):

```
interface StyleProps {
  _p: number,
  _m: number
}

export const helpers = css<StyleProps>`
  ${p => p._p && css`
    padding: ${p._p}px
  `}

  ${p => p._m && css`
    margin: ${p._m}px
  `}
`
```

It does not appear that ThemedCssFunction has the same type variable signature as ThemedStyledFunction, and is unable to extend the prop types available to the underlying template literal.

**Comment by probablyup** [comment]
cc @styled-components/typers

**Comment by probablyup** [comment]
Hey folks, TS typings for styled-components have been moved to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), so please feel free to move your issue there where you'll receive better community support.
