### ISSUE TITLE
Future plan for Themeing

### ISSUE THREAD

**Issue by asafigan** [styled-components/styled-components#1902]
What is the plan for the theme system going into the future?

According to [caniuse](https://caniuse.com/#search=custom%20properties), css variables support is at 86.3%. And for my target audience (US mobile users), the support is 96.7%.

For that reason, I don't use the theme system, instead using css variables.

I know that at this time not everybody can switch to using css variables, but would it be worth splitting out the theme system into it's own package? And if not now, when would it be?

The concerns that I have are:

Is the impact of the theme system on performance (bundle size and runtime) too small to matter? 
How hard would it be to move it into it's own library?
How would third party libraries work with themeing?

My initial idea is that the current theme system could be replaced with a wrapper.

```
withTheme(styled.div`
  background-color: ${p => p.theme.primaryColor};
`)
```

This simply injects the theme into the props like the current withTheme hoc.
You could than just split it into it's own library and refer to the new library in the docs or have a path to import it like `import {withTheme, ThemeProvider, ThemeConsumer} from "styled-components/theme"`.

But I guess the real question is if the benefit is high enough.

I love this library but the biggest disadvantage is it's size. I don't know if this would eliminate much size or if there are other things that will have a greater impact.

**Comment by probablyup** [comment]
I mean there's nothing stopping you from setting CSS variables in `injectGlobal` and then using them downstream in your style blocks without JS function interpolations. I think it's just another way of doing things that doesn't replace our existing theming situation.

**Comment by mxstbr** [comment]
I initially modeled our `ThemeProvider` API to work similarly to CSS variables, because I wanted to use CSS vars but couldn't do due my browser support requirements at the time. I'd be happy if we could make the theming stuff optional so you wouldn't have to ship the `ThemeProvider` if you don't use it!

The code for detecting and injecting the theme into the styled components' props is very small, so you wouldn't even need the `withTheme` wrapper: the styled components could just pick up the theme from context when it's there, but it doesn't have to be. Then the only thing we really gotta move is the `ThemeProvider` and the `withTheme` helper so those are imported from `styled-components/theme` I think?! That should give us some nice size savings for folks who don't use theming. Let's do that for v4 @probablyup?

**Comment by probablyup** [comment]
I personally don’t want to change the API too much. We’re already making a lot of big under the hood changes for v4.0

**Comment by asafigan** [comment]
@mxstbr  Your idea would be great. Don't change the api, but add optional import.

**Comment by garetmckinley** [comment]
What if there was a flag that could be set on the babel plugin that converted theme variables into actual CSS variables, with the variable assignments getting injected into the `<head />`? That way there would be nothing extra that needs to be added to styled-components, and migrating your sites to use CSS vars would be painless and instant.

Basically what I'm thinking is that something like this:

```jsx
const theme = {
  background: "palevioletred",
  color: "white"
}

const Component = styled.div`
  background: ${props => props.background};
  color: ${props => props.color};
`

<ThemeProvider theme={theme}>
  <Component>Styled Component</Component>
</ThemeProvider>
```

Would then get converted upon compilation to this:

```jsx
const theme = {
  background: "palevioletred",
  color: "white"
}

const Component = styled.div`
  background: var(--Component-hash-background);
  color: var(--Component-hash-color);
`

<ThemeProvider theme={theme}>
  <Component>Styled Component</Component>
</ThemeProvider>
```

With this injected into the `<head />`

```css
:root {
  --Component-hash-background: palevioletred;
  --Component-hash-color: white;
}
```

Not entirely sure if this is possible, but I feel like it should be. It was just a random idea I had when browsing this, so it's possible I've overlooked something.

**Comment by probablyup** [comment]
It's possible, but CSS variables just aren't as flexible as the JS theming system. With the JS way you can switch out entire subsets of styles on a whim, whereas CSS vars are meant more for setting a single property.

I think they can definitely coexist, but CSS vars don't supplant JS ones.

**Comment by asafigan** [comment]
After thinking about it, I agree. Also the bundle savings will probably be minimal. One think I thought of the other day was portals and other things like that. Context would go to the portal were as css variables wouldn't. I think that moving to the new context api would make the current themeing system so small that it wouldn't matter.

**Comment by mxstbr** [comment]
Already done for v4! :100: I'm going to close this out for now as there's nothing actionable for us to do.

Thanks for the great discussion!
