### ISSUE TITLE
Typescript ThemedStyledComponentsModule from documentation does not compile

### ISSUE THREAD

**Issue by seanemmer** [styled-components/styled-components#1905]
Implementing example from docs (small change to avoid multiple imports from same module):

```
import * as styledComponents from 'styled-components'
import { ThemeInterface } from 'types'

const {
  default: styled,
  injectGlobal,
  keyframes,
  ThemeProvider,
  withTheme,
  css
} = styledComponents as styledComponents.ThemedStyledComponentsModule<ThemeInterface>

export { injectGlobal, keyframes, ThemeProvider, withTheme, css }
export default styled
```

Results in compilation error:
`This assertion is unnecessary since it does not change the type of the expression.`

I can confirm that the type of the individual methods is changing.  

E.g. the type for 'css' changes from:
`StyledComponents.ThemedCssFunction<Any>`

To:
`StyledComponents.ThemedCssFunction<ThemeInterface>`

Styled-Components Version: `3.4.2`
Typescript Version: `3.0.1`

**Comment by probablyup** [comment]
cc @styled-components/typers

**Comment by probablyup** [comment]
Hey folks, TS typings for styled-components have been moved to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), so please feel free to move your issue there where you'll receive better community support.
