### ISSUE TITLE
styled() does not recognise React defaultProps in Typescript 3.0.1

### ISSUE THREAD

**Issue by nathanbirrell** [styled-components/styled-components#1914]
Since Typescript [introduced support for defaultProps](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#support-for-defaultprops-in-jsx) recently, it would be nice to have styled-components recognise their presence.

## Reproduction

Create a component with one required and one optional prop, set a default prop for the optional.

```js
interface IProps {
  requiredProp: boolean
  optionalProp: string // Shouldn't need to be optional here
}

class MyComponent extends React.PureComponent<IProps> {
  static defaultProps = {
    optionalProp: 'fallback'
  }

  render() {
    const { requiredProp, optionalProp } = this.props
    return (
      <span>
        {requiredProp.toString()}
        {optionalProp.toString()}
      </span>
    )
  }
}
```

Then use that component, once as a normal react component and once as a styled-component:

```js
const MyComponentStyled = styled(MyComponent)``

// No type error (expected) because optionalProp is defined in defaultProps
<MyComponent requiredProp />

// Type error (unexpected), styled() doesn't recognise optionalProp is defined in defaultProps
<MyComponentStyled requiredProp />

```

## Expected Behavior

No type error when using `MyComponentStyled` without `optionalProp`.

## Actual Behavior

Type error, because styled() doesn't seem to recognise `optionalProp` is defined in `defaultProps`

`Property 'optionalProp' is missing in type '{ requiredProp: true; }'.`

## Environment
```
## System:
 - OS: Linux 4.15 Fedora 27 (Workstation Edition) 27 (Workstation Edition)
 - CPU: x64 Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz
 - Memory: 2.88 GB / 15.34 GB
 - Container: Yes
 - Shell: 4.4.19 - /bin/bash
## Binaries:
 - Node: 8.9.4 - /usr/bin/node
 - npm: 5.6.0 - /usr/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.5.0 => 1.5.1
 - styled-components: ^3.4.2 => 3.4.2
 - typescript: ^3.0.1 => 3.0.1
```

**Comment by probablyup** [comment]
cc @Igorbek

**Comment by Igorbek** [comment]
Thank you for reporting. It is indeed a desired behavior. I'll think how could it be typed. The first idea is to forward `defaultProps` to styled component class; or, extract effective prop types from a original component.
I cannot commit to work on this in the next three weeks as I am on vacation.

**Comment by probablyup** [comment]
Hey folks, TS typings for styled-components have been moved to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), so please feel free to move your issue there where you'll receive better community support.
