### ISSUE TITLE
Type inference does not work with Styled wrapper on imported React Component

### ISSUE THREAD

**Issue by seanemmer** [styled-components/styled-components#1917]
When implementing the following code:

```
import { FontAwesomeIcon as Icon } from '@fortawesome/react-fontawesome'

const ChevronRight = styled(Icon)`
  margin-right: 3px;
  margin-left: 6px;

  transition: margin-left ease-in-out 0.25s, margin-right ease-in-out 0.25s;
`
```

I get the error:
`'ChevronRight' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.`

This error does not occur when I use React components that I declare as SFCs inside of the app.

The issue is resolved when I explicitly cast ChevronRight: 
`const ChevronRight: StyledComponentClass<{icon: IconProp}, ThemeInterface>`

**Comment by probablyup** [comment]
Flow, TS ?

**Comment by seanemmer** [comment]
TS

**Comment by seanemmer** [comment]
Diving into some more detail - this issue was caused by a comment block of CSS.  When I remove the comment block it goes away:

```const ChevronRight= styled(Icon)`
  margin-right: 3px;
  margin-left: 6px;

  transition: margin-left ease-in-out 0.25s, margin-right ease-in-out 0.25s;

  /* ${Button}:hover & {
    margin-left: 9px;
    margin-right: 0;
  } */
````

**Comment by probablyup** [comment]
@Igorbek's on vacation for a few weeks so unless someone else is free to look into this might be a bit

**Comment by Igorbek** [comment]
Comment block is not recognized by TS as something that is not used, so it does appear in the interpolation. Is `Button` being imported?

**Comment by seanemmer** [comment]
Button is declared earlier in the file as 'export const Button = ...'

The commented out block does not work in Styled-Components + TS though, issue referenced here:

https://github.com/styled-components/vscode-styled-components/issues/117#issuecomment-416269538

**Comment by probablyup** [comment]
Hey folks, TS typings for styled-components have been moved to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), so please feel free to move your issue there where you'll receive better community support.
