### ISSUE TITLE
Default props for ThemeProvides

### ISSUE THREAD

**Issue by fnpen** [styled-components/styled-components#1929]
Hello,

I have some problem with themming.

Example: https://codesandbox.io/s/4zr657x5o4
```
const SomeComponent = styled('button')`
    color: ${props => props.theme.color};
    border: 10px solid ${props => props.theme.borderColor};
  `;

SomeComponent.defaultProps = {
  theme: {
    color: 'yellow',
    borderColor: 'gray'
  }
};

function App() {
  return (
    <ThemeProvider theme={{ color: 'green' }}>
      <SomeComponent>Themed</SomeComponent>
    </ThemeProvider>
  );
}
```

I expect that button is borderColor: gray; but its green.
I wanna use component without ThemeProvider(with defaultProps) and set some theme variables to customize it.

**Comment by probablyup** [comment]
Yeah we currently ignore a local prop called "theme" if there is a context-provided theme via `ThemeProvider`. I've actually proposed [an API adjustment of this nature](https://github.com/styled-components/styled-components/pull/1682#issuecomment-399496564), but it's not agreed upon yet.

**Comment by probablyup** [comment]
Closing this, just provide a full theme object to ThemeProvider. We don’t do shallow merging of defaultProps against context theme because that’s not in the spirit of how defaultProps are implemented or used in React.
