### ISSUE TITLE
Theme is not updated properly

### ISSUE THREAD

**Issue by petehouston** [styled-components/styled-components#193]
## Version
Tried with 1.0.10, it might happen with previous versions.

## Reproduction
http://www.webpackbin.com/EyB9mzGWf

## Steps to reproduce
Just click the button on the above WebpackBin, open browser console log to see the log.

## Expected Behavior
It should update the correct theme.

## Actual Behavior
It updates the old theme.

*This issue has been raised on gitter.*

**Comment by bhough** [comment]
One clarification that I think will be useful in debugging here is that it doesn't update only on the first click. However, if you click the button again it updates but is always one update "behind".

I haven't had a chance to dive into this bug yet, but my guess is the issue starts with this line of code: https://github.com/styled-components/styled-components/blob/master/src/models/ThemeProvider.js#L50

**Comment by petehouston** [comment]
It works fine if using `shouldComponentUpdate` instead of `componentWillReceiveProps` to publish event for new theme.

**Comment by geelen** [comment]
@mxstbr any idea why `shouldComponentUpdate` works here and `componentWillReceiveProps` doesn't?

**Comment by mxstbr** [comment]
I have no idea whatsoever.

**Comment by petehouston** [comment]
@gaearon could you please give us a hand on this? what is the difference between `componentWillReceiveProps` and `shouldComponentUpdate` in this case?

**Comment by gaearon** [comment]
const theme = passedTheme || this.props.theme


You are reading it from current props. But you want nextProps.

**Comment by gaearon** [comment]
Oh wait, I misunderstood the argument. Never mind.

**Comment by thisguychris** [comment]
@gaearon is this a styled-components bug or otherwise?

**Comment by mxstbr** [comment]
This should be fixed with #253, will release a new version with that fix shortly!
