### ISSUE TITLE
Add theme object to styled-components without ThemeProvider

### ISSUE THREAD

**Issue by trevorwhealy** [styled-components/styled-components#1932]
Hello 👋, has anyone tried overwriting / injecting the default `styled` export with their theme object?

I'm not able to use `<ThemeProvider/>` successfully without errors. My best guess is that it may have to do with the SSR nature of our app, but it fails on `cannot find subscribe of undefined` within a `getChildContext` invocation.

Anyway, this isn't a bug report with ThemeProvider, I'm just clarifying that I know ThemeProvider exists, just that it's not going to work for me, but I still want to utilize theming.

I'd like to overwrite a copy of `styled` from styled components and apply my themes. If it's too complicated you can just close this issue, just felt like someone here might have tried this already. 

This is more or less what I'm trying to accomplish:

config/styled.js
```
import styled from 'styled-components'

const theme = {
  color: 'blue'
}

const moddedStyled = withTheme(styled, theme)
export default moddedStyled
```

components/index.js
```
import styled from '../config/styled'

const Div = styled.div`
    border: ${props =>`1px solid ${props.theme.color}`};
`

export default () => Div
```

**EDIT**
For those who may come here in the future with this problem, I just imported my theme config into any file that consumed it, and just passed them directly.

```
import theme from './theme

const Div = styled.div`
   border: ${theme.color}
`
```

**Comment by Richacinas** [comment]
@trevorwhealy don't you lose the possibility of consuming your components using ThemeProvider and so then not being able anymore to give a custom theming to them?
