### ISSUE TITLE
Module not found: Can't resolve 'styled-components/primitives'

### ISSUE THREAD

**Issue by fmujakitz** [styled-components/styled-components#1936]
## Steps to reproduce
Install **styled-components@3.4.2 or @3.4.1 or @3.4.0**
Use styled-components/primitives
Error: Module not found: Can't resolve 'styled-components/primitives'

## Expected Behavior
filenames in styled-components/dist **do not** have trailing **m**
ie. styled-components-primitives.cjs.js

## Actual Behavior
filenames in styled-components/dist have trailing **m**
ie. styled-components-primitivesm.cjs.js

## Workaround
downgrade to styled-components@3.3.3

**Comment by probablyup** [comment]
It's fixed in master, just haven't done a patch release yet. I'll try to get one out today.

**Comment by probablyup** [comment]
Should be resolved in 3.4.3
