### ISSUE TITLE
Broken styles with 2 instances of styled-components on the same page

### ISSUE THREAD

**Issue by jackrobertscott** [styled-components/styled-components#1941]
The problem is that I want to load 2 instances of styled-components on the same page. But when I do, the second overwrites the first's styles. This causes all the styles to break.

#### Why?

Because I am building a project which injects dom onto a page and uses react/styled-components to do this. Some of the projects I will be injecting the dom into will already have styled components installed. This is where it breaks.

#### Similar issues (non of which have an answer)

#1032 
#1102
#1491 

## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`

#### System:
 - OS: macOS High Sierra 10.13.3
 - CPU: x64 Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz
 - Memory: 91.38 MB / 8.00 GB
 - Shell: 5.3 - /bin/zsh
#### Binaries:
 - Node: 8.7.0 - ~/.nvm/versions/node/v8.7.0/bin/node
 - Yarn: 1.7.0 - /usr/local/bin/yarn
 - npm: 6.1.0 - ~/.nvm/versions/node/v8.7.0/bin/npm

## Reproduction

I have created a sandbox to illustrate where I am currently at with this problem. It is *not* a solution.

https://codesandbox.io/s/z6npzz1zkm

## Steps to reproduce

Load 2 different styled component implementations onto the same page.

## Expected Behavior

All styles would be preserved for the both instances of styled components. Do *not* override the styles of the first instance of styled components.

Alternatively, it would be awesome if there was the ability to rename the `<style data-styled-components=""></style>` component tag.

## Actual Behavior

The second instance of styled components overrides the first. I believe this has to do with the `<style data-styled-components=""></style>` element which is stored in the head.

**Comment by probablyup** [comment]
This will be fixed in v4: https://github.com/styled-components/styled-components/pull/1919

**Comment by probablyup** [comment]
Should hopefully have a beta out next week

**Comment by jackrobertscott** [comment]
@probablyup You would be my hero <3

**Comment by nitroin** [comment]
We are hitting - _I think_ - the very same problem.

We are developing 3+ _independent_ `React` apps:
  - 1 lib with all our UI components building blocks (`cra` + `react-styleguidist` + `styled-components`)
  - 2+ apps (`cra` + `styled-components`) that uses (dep in `package.json`) the former

Using `peerDependencies` causes some dev pain (after `yarn` we are not able to import `styled-components`).

## Environment
#### System:
 - OS: macOS 10.14
 - CPU: x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
 - Memory: 772.15 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh

#### Binaries:
 - Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
 - Yarn: 1.9.4 - /usr/local/bin/yarn
 - npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman

**Comment by probablyup** [comment]
Yes you need to use webpack aliasing so only one version of s-c is being used. v4 will fix this issue, but we don't have a beta ready yet.

**Comment by kitten** [comment]
@nitroin You're indeed going to live _more_ dangerously, since we don't guarantee this to work perfectly in the future. That being said, you probably also don't want to bundle multiple versions of styled-components to keep your bundlesize down. Duplication is really not a good thing in these cases.

I suspect that your dependency on your UI library is causing some trouble. If you just link this package into your app you will almost always have multiple dependencies duplicated.

In the case of styled-components it might be enough (at least for prod installation and building) to add a `resolutions` entry to your `package.json`.

First check how many installations of `styled-components` you have:

```sh
yarn list styled-components
```

Suppose the output then comes back with:

```
└─ styled-components@3.4.5
└─ your-ui-library@x.x.x
    └─ styled-components@3.3.3
Done in 1.24s.   
```

And let's suppose you're not using `lerna`, `yarn workspaces`, `peerDependencies`, or anything else to keep this in check.

Then in your app's `package.json` you can definitely set up this, to manually tell Yarn to always use this specific version:

```
  "resolutions": {
    "styled-components": "3.4.5"
  }
```

Keeping it detailed here in case someone else stumbles upon this issue. This is definitely not a styled-components-specific issue, but simply a dependency management and bundling issue. But luckily this means that there'll always be several solutions.

**Comment by probablyup** [comment]
It’s best to only have one. What versions are installed? Try yarn list styled-components

**Comment by nitroin** [comment]
@kitten thanks for the detailed infos. That helped a lot, never heard of `resolutions` before!

@probablyup`yarn list styled-components` was returning only one instance of `styled-components` but `find -L ./node_modules | grep /react-scripts/package.json` was returning 2.

I'll review with the UI lib team all the deps. Related [RTFM](https://www.styled-components.com/docs/faqs#i-am-a-library-author-should-i-bundle-styledcomponents-with-my-library)!

Thank you!

**Comment by probablyup** [comment]
@jackrobertscott beta is out if you haven't tried it already. Closing this. Feel free to reopen if it still is an issue on your end.

**Comment by strange-developer** [comment]
This error also shows up when your CSP is strict enough to disallow inline styles. You may need to use nonce's to get around this or the NOT recommended solution of allowing `unsafe-inline`.

To diagnose whether your CSP is giving the issue in your development environment, it's good to try adding `unsafe-inline`. I repeat, it is to diagnose the issue and not the solution.

**Comment by karltaylor** [comment]
I am still getting this problem.

I have a `ui-package` using `styled-components`

And my main app

```js
import styled from 'styled-components'
import { Random Ui Stuff } from 'ui-package'
```

And my styles completely break.

`$ npm ls styled-components`

```
app
├── styled-components@4.1.3
└─┬ ui-package
  └── styled-components@4.1.3  extraneous
```

in my `package.json` I added

```
"resolutions": {
  "styled-components": "^4.1.3"
}
```

**Comment by jaril5976** [comment]
Mr. @kitten , One thing I want to share with you that the package list I checked already with following steps

`npm ls styled-components`

and the output is this:

`work-webapp@2.0.0 /Users/jaril/jaril/work-webapp
└── styled-components@4.3.2 `

there are 0 duplicate packages found, then however it's crashing the productions application, I think this is not happening through duplication package in my case, it's happening in only productions environment , Thanks!!

**Comment by chaitanya71998** [comment]
> Mr. @kitten , One thing I want to share with you that the package list I checked already with following steps
> 
> `npm ls styled-components`
> 
> and the output is this:
> 
> ```
> work-webapp@2.0.0 /Users/jaril/jaril/work-webapp
> └── styled-components@4.3.2 
> ```
> 
> there are 0 duplicate packages found, then however it's crashing the production's build, I think this is not happening through the duplication package in my case, it's happening in only the production environment but the error redirects me to this issue thread, Thanks!!

+1
