### ISSUE TITLE
Restyling previously styled component doesn't work

### ISSUE THREAD

**Issue by moseskarunia** [styled-components/styled-components#1943]
So, say I have a React Component styled with styled-component named `AppBar`. And then, I want to change that component position. 

So, I wrap that component in with `const PositionedAppBar = styled(AppBar)`. (As per this [doc](https://www.styled-components.com/docs/basics#styling-any-components))

But, it seems that the newly wrapped component, ignore it's new css properties.

Maybe I missed something??

Below I have also the codesandbox to replicate the problem. In that sandbox, I want to make the appbar position to be at the bottom (nonsense I know, it's just to replicate the problem)

## Environment
`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`

returns

> npx: installed 1 in 5.785s
> 
> ## System:
>  - OS: Windows 10
>  - CPU: x64 AMD FX-9800P RADEON R7, 12 COMPUTE CORES 4C+8G
>  - Memory: 2.14 GB / 7.46 GB
> ## Binaries:
>  - npm: 6.2.0 - C:\Program Files\nodejs\npm.CMD
> 
> (node:9544) UnhandledPromiseRejectionWarning: Error: The system cannot find the path specified.
> 
>     at Function.e.exports.sync (C:\Users\moses\AppData\Roaming\npm-cache\_npx\9544\node_modules\envinfo\dist\cli.js:2:7690)
>     at Object.copySync (C:\Users\moses\AppData\Roaming\npm-cache\_npx\9544\node_modules\envinfo\dist\cli.js:2:104342)
>     at Object.t.writeSync.e [as writeSync] (C:\Users\moses\AppData\Roaming\npm-cache\_npx\9544\node_modules\envinfo\dist\cli.js:2:122592)
>     at C:\Users\moses\AppData\Roaming\npm-cache\_npx\9544\node_modules\envinfo\dist\cli.js:2:123354
>     at Promise.all.then.e (C:\Users\moses\AppData\Roaming\npm-cache\_npx\9544\node_modules\envinfo\dist\cli.js:2:123369)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
> (node:9544) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
> (node:9544) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

## Reproduction
https://codesandbox.io/s/2jx2w76070

## Expected Behavior
(In my codesandbox) the appbar become positioned at the bottom-most of the screen

## Actual Behavior
(In my codesandbox) the appbar stays on top.

**Comment by kachkaev** [comment]
@moseskarunia I think you just forgot to pass `classaName` down. Try replacing

```js
class AppBar extends Component {
  render = () => {
    return <StyledAppBar />;
  };
}
```

with

```js
class AppBar extends Component {
  render = () => {
    return <StyledAppBar className={this.props.className} />;
  }
}
```

Docs: https://www.styled-components.com/docs/basics#how-do-styled-components-work-within-a-component

**Comment by moseskarunia** [comment]
@kachkaev ah right. silly me. Thanks.
