### ISSUE TITLE
Import of component causing error and two components assigned the same ID

### ISSUE THREAD

**Issue by krothenbaum** [styled-components/styled-components#1945]
## System:
 - OS: macOS High Sierra 10.13.6
 - CPU: x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
 - Memory: 230.79 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 10.1.0 - ~/.nvm/versions/node/v10.1.0/bin/node
 - Yarn: 1.9.4 - /usr/local/bin/yarn
 - npm: 6.2.0 - ~/.nvm/versions/node/v10.1.0/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.5.1 => 1.5.1
 - styled-components: ^3.3.2 => 3.3.2

## Expected Behavior
To be able import SC like so `import { A } from '../../elements`.

From two different SCs to have different ID 

## Actual Behavior
One file error when importing with the above pattern, have to use `import A from '../../elements/A`

Two components extended from that component are assigned the same ID and causing issues with inheritance.

## Description
We have a styled anchor component that we use to set up base styles and then import into other components and use `.extend` to add component specific modifications to that element. This pattern has been working great but I’ve run into two issues I suspect are related but I’m not sure how to debug or resolve them.

Our styled components are structured the following way:

Styles
|
|---Blocks (This contains all the styles for a specific component in our app)
|    |
|    |--- StyledFooter (example component folder)
|         |--- Text.js
|         |--- Logo.js
|         |----index.js 
|
|---Elements
|    |--- Headings (folder with all Headings)
|    |--- A.js (individual component file)
|    |--- P.js, LI.js, UL.js, … etc
|    |--- index.js (imports and exports all elements)
|

In all but one of our components I have been able to import our element in the following way:
`import { A } from ‘../../elements’`

However in one component I get the following error if I import that way:

```
{ TypeError: Cannot read property 'extend' of undefined    at Object../styles/blocks/StyledAnchorLink/index.js (styles/blocks/StyledAnchorLink/index.js:4:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 91055a60dda075004afb:21:0)
    at Object../styles/elements/HEADINGS/H1.js (styles/elements/HEADINGS/H1.js:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 91055a60dda075004afb:21:0)
    at Object../styles/elements/HEADINGS/index.js (styles/elements/HEADINGS/index.js:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 91055a60dda075004afb:21:0)
    at Object../styles/elements/index.js (styles/elements/index.js:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 91055a60dda075004afb:21:0)
    at Object../styles/blocks/StyledFooter/Legal.js (/Users/krothenbaum/lytics/documentation/build/server/bundles/pages/index.js:973:68)
    at __webpack_require__ (webpack:/webpack/bootstrap 91055a60dda075004afb:21:0)
    at Object../styles/blocks/StyledFooter/index.js (styles/blocks/StyledFooter/index.js:1:0)
    at __webpack_require__ (webpack:/webpack/bootstrap 91055a60dda075004afb:21:0)
    at Object../components/Footer.js (/Users/krothenbaum/lytics/documentation/build/server/bundles/pages/index.js:294:86)
    at __webpack_require__ (webpack:/webpack/bootstrap 91055a60dda075004afb:21:0)
    at Object../pages/index.js (/Users/krothenbaum/lytics/documentation/build/server/bundles/pages/index.js:725:77)
    at __webpack_require__ (webpack:/webpack/bootstrap 91055a60dda075004afb:21:0) sourceMapsApplied: true }
```

If I import directly from that components file it works, `import A from ‘../../elements/A’`, however this leads to different issue that I suspect is related but I’m not sure how to go about debugging it.

As I described above, we import this `A` styled component and extend it for various components. This has worked well but now I’m running into an issue where two different components are getting assigned the same styled component ID and class despite being separate files. This is causing unwanted styling on a component that references one for the components being duplicated but not the other. Code:

A.js - base element of all anchor tags
```
import styled from 'styled-components';
import { applyStyleModifiers } from 'styled-components-modifiers';
import { colors } from '../variables';
import { TEXT_MODIFIERS } from '../modifiers';

const A = styled.a`
  color: ${colors.fc.linkPrimary};
  text-decoration: none;
  transition: 200ms;
  cursor: pointer;

  &:hover {
    color: ${colors.fc.linkHover};
    text-decoration: underline;
    transition: 200ms;
  }

  ${applyStyleModifiers(TEXT_MODIFIERS)};
`;

export default A;
```

StyledAnchorLink - Component that is throwing the above error
```
import A from '../../elements/A';
import { spacing } from '../../variables';

const StyledAnchorLink = A.extend`
  display: block;
  margin-top: ${spacing.xxxl};

  &:first-child {
    margin-top: 0;
  }

  &:hover {
    text-decoration: none;
  }
`;

export default StyledAnchorLink;
```

StyledCard/Link.js - Extends A and wraps our Card component which contains an H3 element
```
import { ifProp } from 'styled-tools';
import { A } from '../../elements';

const Link = A.extend`
  display: flex;
  flex: 0 1 ${ifProp('theme.largeCard', '50%', '33%')};
  flex-wrap: wrap;
  justify-content: flex-start;

  @media (max-width: 1170px) {
    flex-basis: ${ifProp('theme.largeCard', '100%', '50%')};
  }

  @media (max-width: 767px) {
    flex-basis: 100%;
  }
`;

export default Link;
```

HEADINGS/H3.js - Has styling when it is the child of 1StyledAnchorLink1 which are being applied in our card component despite not being a child of that component. In fact 1StyledAnchorLink1 is not used anywhere on the page where I’m seeing the issue.
```
import styled from 'styled-components';
import { applyStyleModifiers } from 'styled-components-modifiers';
import { prop } from 'styled-tools';
import StyledAnchorLink from '../../blocks/StyledAnchorLink';
import { TEXT_MODIFIERS } from '../../modifiers';
import { colors, fonts, lineHeight, spacing } from '../../variables';

const H3 = styled.h3`
  font-family: ${fonts.ff.sans};
  font-size: ${fonts.fs.md};
  font-weight: ${fonts.fw.medium};
  line-height: ${lineHeight.expanded};
  color: ${prop('theme.color', colors.fc.darkPrimary)};
  margin: ${spacing.md} 0;

  ${StyledAnchorLink} & {
    display: inline;

    &:hover {
      text-decoration: none;
      color: ${colors.fc.darkHover};
    }
  }

  ${applyStyleModifiers(TEXT_MODIFIERS)};
`;

export default H3;
```

Console log of `StyledAnchorLink` and `StyledCard/Link.js` showing they have the same class but different styles.

```
StyledAnchorLink 
{ [Function: StyledComponent]
  withComponent: [Function: withComponent],
  contextTypes:
   { '__styled-components__': { [Function: bound checkType] isRequired: [Function: bound checkType] },
     '__styled-components__next__': { [Function: bound checkType] isRequired: [Function: bound checkType] },
     '__styled-components-stylesheet__': { [Function: bound checkType] isRequired: [Function: bound checkType] } },
  warnTooManyClasses: [Function],
  displayName: 'A',
  styledComponentId: 's16kb36c-0-A-bJefwH',
  attrs: undefined,
  componentStyle:
   ComponentStyle {
     rules:
      [ 'color:',
        '#0080CE',
        ';text-decoration:none;transition:200ms;cursor:pointer;&:hover{color:',
        '#0067a5',
        ';text-decoration:underline;transition:200ms;}',
        [Function],
        ';',
        '\n  display: block;\n  margin-top: ',
        '48px',
        ';\n\n  &:first-child {\n    margin-top: 0;\n  }\n\n  &:hover {\n    text-decoration: none;\n  }\n' ],
     isStatic: false,
     componentId: 's16kb36c-0-A-bJefwH' },
  target: 'a' }
```
```
Link
{ [Function: StyledComponent]
  withComponent: [Function: withComponent],
  contextTypes:
   { '__styled-components__': { [Function: bound checkType] isRequired: [Function: bound checkType] },
     '__styled-components__next__': { [Function: bound checkType] isRequired: [Function: bound checkType] },
     '__styled-components-stylesheet__': { [Function: bound checkType] isRequired: [Function: bound checkType] } },
  warnTooManyClasses: [Function],
  displayName: 'A',
  styledComponentId: 's16kb36c-0-A-bJefwH',
  attrs: undefined,
  componentStyle:
   ComponentStyle {
     rules:
      [ 'color:',
        '#0080CE',
        ';text-decoration:none;transition:200ms;cursor:pointer;&:hover{color:',
        '#0067a5',
        ';text-decoration:underline;transition:200ms;}',
        [Function],
        ';',
        '\n  display: flex;\n  flex: 0 1 ',
        [Function],
        ';\n  flex-wrap: wrap;\n  justify-content: flex-start;\n\n  @media (max-width: 1170px) {\n    flex-basis: ',
        [Function],
        ';\n  }\n\n  @media (max-width: 767px) {\n    flex-basis: 100%;\n  }\n' ],
     isStatic: false,
     componentId: 's16kb36c-0-A-bJefwH' },
  target: 'a' }
```

**Comment by probablyup** [comment]
Please don’t use extend, its deprecated and has a lot of problems

**Comment by krothenbaum** [comment]
OK, going with `styled()` instead of `.extend` fixed the issue with two components getting assigned the same class. I did not see the note on using `.extend` across files.

I still can't import that anchor component in that single file using `import { A } from '../../elements'. This isn't a huge deal but I like to be consist. Is there a way to debug this and find out why I can't import this from an index file?

**Comment by probablyup** [comment]
It looks like you’re exporting it as default not as a named export?
