### ISSUE TITLE
Hexadecimal RGBA values not properly transpiled for older browsers

### ISSUE THREAD

**Issue by edahlseng** [styled-components/styled-components#1948]
## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`
### System:
 - OS: macOS High Sierra 10.13.6
 - CPU: x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
 - Memory: 95.50 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
### Binaries:
 - Node: 8.11.3 - /usr/local/bin/node
 - npm: 6.4.0 - /usr/local/bin/npm
### npmPackages:
 - styled-components: ^3.4.5 => 3.4.5

## Reproduction

https://codesandbox.io/s/74160p5o4q

## Steps to reproduce
* Use a hexadecimal RGBA value. (`background: #000000AA`)
* Open the page in Internet Explorer 11 (or any browser that doesn't support hexadecimal RGBA values).

## Expected Behavior
The color displays as specified.

## Actual Behavior
The color does not display, because some older browsers don't support hexadecimal RGBA values, and styled-components does not transpile these colors.

**Comment by probablyup** [comment]
Yeah I mean we only do vendor prefixing through stylis. We aren’t SCSS

**Comment by edahlseng** [comment]
@probablyup I don't quite understand your response. My understanding was that styled-components performed CSS preprocessing in order to support browsers down to IE 8. Is that not the case?

Since we're unable to add our own preprocessing plugins in order to provide backwards compatibility for CSS features, what's the best way of resolving this? Should this be worked into stylis itself?

**Comment by probablyup** [comment]
This is the preprocessor being used: https://github.com/thysultan/stylis.js/blob/master/README.md

If you want to request a new feature in it such as this, i’d open an issue with them or offer to implement it.
