### ISSUE TITLE
Comment in CSS breaks production build / TypeError: foo.js: Property value expected type of string but got null

### ISSUE THREAD

**Issue by genox** [styled-components/styled-components#1949]
With my current Babel 7 / TypeScript 3 instance of NextJS (latest canary), I ended up with this production build error while dev worked fine:

`TypeError: foo.js: Property value expected type of string but got null`

The culprit was a commented line of CSS:

`// top: -${slope - 1}px;`

Once I removed the comment, the build went through just fine. I'm not even sure this is a bug or a peculiar "feature" of Babel or one of its components. But I thought I add it here so others can find it.

**Comment by imbhargav5** [comment]
Hmmm, the issue isn't really clear to me personally. What version of styled-components and babel are you using? Can you provide an example git repo so we can take a look?

**Comment by kitten** [comment]
This is a known issue AFAIK.

Multiline comments will work since stylis understands them. Single line comments however only work when they don't contain interpolations currently

**Comment by genox** [comment]
Not sure if it is a known issue, but it's easily reproduceable: add a single line comment to an interpolated css attribute, e.g.

`  // max-width: ${theme.breakpoints[1]};`

and you'll get 

`TypeError: Property value expected type of string but got null`

when building for prod with Babel 7.0.0 and `styled-components@latest` using a `.babelrc` config like this:

`      "plugins": [
        [
          "babel-plugin-styled-components",
          {
            "ssr": true,
            "displayName": false,
            "preprocess": false,
            "minify": true
          }
        ]
      ]
`

**Comment by probablyup** [comment]
Single line comments cause issues with interpolations yes. I recommend
using /* style */ comments for the time being

**Comment by probablyup** [comment]
@genox Should be fixed if you upgrade babel-plugin-styled-components to 1.6.0
