### ISSUE TITLE
How to change styles if parent have selector?

### ISSUE THREAD

**Issue by svrcekmichal** [styled-components/styled-components#195]
Is it possible to create parent-child hierarchy with styled-components? I'm currently using css-modules and have something like this.
```
//style.css
.parent { ... }
.child { ... }
.parent .child { ... }
```

Now I can style ma child component differently if it is used inside another component, for example Button is child, and if it is inside ButtonGroup some different styles are applied. 

Can we do something like this with styled-components? Maybe add something like this to doc if possible? Thanks!

**Comment by mxstbr** [comment]
You would normally use a theme for this with our `ThemeProvider`!

We're debating about adding a child component selector in #142.
