### ISSUE TITLE
TypeScript compile fail due to @types/react-native and @types/node clashes (styled-components needs @types/node while RN project can't use it)

### ISSUE THREAD

**Issue by elnygren** [styled-components/styled-components#1950]
The problem:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/15960

Example of a RN lib dealing with it:
https://github.com/Microsoft/appcenter-cli/issues/437

In my own words: 
styled-component requires @types/node to compile, however, including @types/node in an RN project will lead to problems outlined in issue 15960 above.

Example output when @types/node is not present:

```
> tsc

node_modules/styled-components/typings/styled-components.d.ts:188:11 - error TS2304: Cannot find name 'StyleSheet'.

188   sheet?: StyleSheet
              ~~~~~~~~~~

node_modules/styled-components/typings/styled-components.d.ts:189:12 - error TS2304: Cannot find name 'Node'.

189   target?: Node
               ~~~~

node_modules/styled-components/typings/styled-components.d.ts:203:21 - error TS2503: Cannot find namespace 'NodeJS'.

203     readableStream: NodeJS.ReadableStream
                        ~~~~~~

node_modules/styled-components/typings/styled-components.d.ts:204:6 - error TS2503: Cannot find namespace 'NodeJS'.

204   ): NodeJS.ReadableStream
         ~~~~~~

node_modules/styled-components/typings/styled-components.d.ts:205:13 - error TS2304: Cannot find name 'StyleSheet'.

205   instance: StyleSheet
                ~~~~~~~~~~
```

**Comment by elnygren** [comment]
This is probably not your problem. `@types` will have to figure out how they'll handle conflicts between different `@types/$foo` packages.

**Comment by JKillian** [comment]
Fwiw, I've recently [updated the typings for styled-components to remove the `node` type dependency](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/32843). If anyone stumbles across this problem in the future, it should be resolvable by updating `@types/styled-components`.
