### ISSUE TITLE
https://www.mol.gov.sa/CIW/Files/%D8%A7%D9%84%D9%85%D9%85%D8%AB%D9%84%20%D8%A7%D9%84%D8%B1%D8%A6%D9%8A%D8%B3%D9%8A%20%D9%84%D9%84%D9%85%D9%86%D8%B4%D8%A3%D8%A9.pdf

### ISSUE THREAD

**Issue by 1bbbrrr800** [styled-components/styled-components#1953]
## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`

## Reproduction

https://www.webpackbin.com/bins/-KeeZCr0xKfutOfOujxN
https://codesandbox.io/s/rkmNRByE4

**Comment by kitten** [comment]
This looks like spam. If it wasn't please open a proper issue, following the template and our CONTRIBUTING guide please
