### ISSUE TITLE
Something interesting happened, I try to change a `prop`, but open a new window .

### ISSUE THREAD

**Issue by manglobe** [styled-components/styled-components#1955]
https://codesandbox.io/embed/k14vz0x703

- Click the `hellow word`
- Browser will open a new window tab! XD

**Comment by probablyup** [comment]
Hehe this was fun. Basically because in your CSS you didn't put `open` and `close` in a string, it was defaulting to `this.open` which is [`window.open`](https://developer.mozilla.org/en-US/docs/Web/API/Window/open).
