### ISSUE TITLE
A parameter "allow"  is not passed to styled.iframe

### ISSUE THREAD

**Issue by StipJey** [styled-components/styled-components#1958]
If I use a **styled.iframe**, then I do not have access to the camera and microphone, if I use a **native iframe**, then access is

Example:
```
const StyledIFrame = styled.iframe``;
<StyledIFrame
    src="https://example.com"
    allow="geolocation; microphone; camera"
>It's not work</StyledIFrame>
<iframe
    src="https://example.com"
    allow="geolocation; microphone; camera"
>It's work</iframe>
```

## Reproduction
[![Edit Styled Components](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/93x81p9zjo)

![image](https://user-images.githubusercontent.com/8746529/44780053-b926d800-ab89-11e8-85b1-0f02cd311173.png)

**Comment by probablyup** [comment]
Looks like that one isn't in https://github.com/styled-components/styled-components/blob/9d72abe32754ae9dd0bf9edf8a652ea592bdd06a/src/utils/validAttr.js#L15

Want to make a PR?

**Comment by probablyup** [comment]
This is fixed in v4 (develop), so going to close. You're welcome to make a PR against v3 if you'd like.
