### ISSUE TITLE
How do you use `attrs` with TypeScript?

### ISSUE THREAD

**Issue by ryansmith94** [styled-components/styled-components#1959]
Hi, it's unclear how `attrs` should be used with TypeScript, I'm not sure if there's just a bug in the types. Here's what we've got so far, this is the only way to make the component definition work as expected, but then the component usage fails with the error `[ts] Type 'string' is not assignable to type 'never'.`.

```ts
import styled from '../utils/mural-styled-components';

interface AdditionalProps {
  readonly size: string;
}

interface ChangedProps {
  readonly type: string;
  readonly margin: string;
  readonly padding: string;
}

const WeirdComponent = styled.input.attrs<AdditionalProps, ChangedProps>({
  // we can define static props
  type: 'password',

  // or we can define dynamic ones
  margin: (props) => props.size || '1em',
  padding: (props) => props.size || '1em',
})`
  color: palevioletred;
  font-size: 1em;
  border: 2px solid palevioletred;
  border-radius: 3px;

  /* here we use the dynamically computed props */
  margin: ${(props) => props.margin};
  padding: ${(props) => props.padding};
`;

import React from 'react';
export const X = () => (
  <WeirdComponent size="massive"/>
); // [ts] Type 'string' is not assignable to type 'never'.
```

## Environment
```md
## System:
 - OS: Linux 4.15 Linux Mint 19 (Tara)
 - CPU: x64 Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
 - Memory: 7.84 GB / 15.60 GB
 - Container: Yes
 - Shell: 4.4.19 - /bin/bash
## Binaries:
 - Node: 10.7.0 - ~/.nvm/versions/node/v10.7.0/bin/node
 - npm: 6.4.0 - ~/github/mural/node_modules/.bin/npm
## npmPackages:
 - styled-components: ^3.3.0 => 3.4.4
```

**Comment by mixalezhnev** [comment]
@Funkyskank, you should have offered a solution instead of 'same issue' :+1:

**Comment by probablyup** [comment]
Hey folks, TS typings for styled-components have been moved to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), so please feel free to move your issue there where you'll receive better community support.

**Comment by ryansmith94** [comment]
Reposted https://github.com/DefinitelyTyped/DefinitelyTyped/issues/28597

**Comment by beausmith** [comment]
Another working solution for extending an html element type as a styled component with custom attributes:

Component `Main.tsx`: 

```ts
interface Props {
  noMargin?: boolean
}
const Main = styled('main')<Props>`
  margin: ${({ noMargin }: Props) => (noMargin ? undefined : '1rem')};
`
export default Main
```

Usage in other component `OtherComponent.tsx`:

```ts
import Main from './Main'
const OtherComponent = () => (
  <Main noMargin />
); 
export default OtherComponent
```

**Comment by wujie520303** [comment]
It works with me, as follows:
`
import React from 'react';
import styled from 'styled-components';

const Input = styled.input.attrs(({ size }): any => ({
  // 定义静态属性
  type: "password",

  // 定义动态属性
  margin: size || "1em",
  padding: size || "1em"
}))`
  color: palevioletred;
  font-size: 1em;
  border: 2px solid palevioletred;
  border-radius: 3px;

  /* 动态计算属性 */
  margin: ${props => props.margin};
  padding: ${props => props.padding};
`;

const CssInJs: React.FC = () => {
  return (
    <div>
      <Input placeholder="A small text input" size="1em" />
      <Input placeholder="A bigger text input" size="2em" />
    </div>
  )
}

export default CssInJs;
`

**Comment by anthonylim24** [comment]
> It works well with me, as follows:
> 
> ```ts
> import React from 'react';
> import styled from 'styled-components';
> 
> const Input = styled.input.attrs(({ size }): any => ({
>   // 定义静态属性
>   type: "password",
> 
>   // 定义动态属性
>   margin: size || "1em",
>   padding: size || "1em"
> }))`
>   color: palevioletred;
>   font-size: 1em;
>   border: 2px solid palevioletred;
>   border-radius: 3px;
> 
>   /* 动态计算属性 */
>   margin: ${props => props.margin};
>   padding: ${props => props.padding};
> `;
> 
> const CssInJs: React.FC = () => {
>   return (
>     <div>
>       <Input placeholder="A small text input" size="1em" />
>       <Input placeholder="A bigger text input" size="2em" />
>     </div>
>   )
> }
> 
> export default CssInJs;
> ```

The above didn't work for me, but this did.

`export const Job = styled(Button).attrs<{}>({
  type: Button.TYPES.PLAIN,
})``
`

**Comment by chasms** [comment]
If you need props inside your component and need to type those with a generic, you can use this pattern:

```
export const Item = styled.View.attrs<ItemProps>({
  pointerEvents: ({ show }) => (show ? 'auto' : 'none'),
  ...other attrs
})<ItemProps>`
  opacity: ${({ show }) => (show ? '1' : '0')};
  ...other styles
`;
```

**Comment by spcfran** [comment]
@chasms solution works great, although the IDE stops highlighting the CSS chunk.

An alternative is to move the type of the props inside the attrs() call, although only works with the specific props on the interface and not the default ones (unless you specify the whole `& React.DetailedHTMLProps` etc).

![image](https://user-images.githubusercontent.com/4398367/62155168-2134ef80-b300-11e9-8b13-e31e9c651c00.png)

**Comment by webcoderkz** [comment]
@chasms 
```
interface BtnProps {
  variant: string;
  size: string;
  mr: number;
}

const Btn = styled(Button).attrs<BtnProps>(({ variant, size }) => ({
  forwardedAs: Link,
  size: size ?? 'md',
  variant: variant ?? 'primary'
}))<BtnProps>`
  color: white;
  margin-right: ${({ mr }) => mr ?? '10px'};
  &:hover {
    color: white;
  }
`;
```
Seems like TS doesn't check type of `mr` variable. Does it work at all?

**Comment by KirdesMF** [comment]
Hi I find a way for people who want to keep css intelisense.

```ts
type TSPolygon = {
   originHex: TPoint;
   cube: TCube;
   sizeHex: number;
   pathname: string;
};

const Hex = styled.polygon<THex>`
   fill: ${({ theme, pathname }) => theme.colors[pathname]};
   stroke: ${({ theme }) => theme.colors.white};
   transform: rotate(0deg);
   transform-origin: center;
   stroke-width: 2;
`;

export const Hexagon = styled(Hex).attrs<THex>(
   ({ points }) => ({
      points: points,
   })
)(Hex);



```

**Comment by just0110** [comment]
> If you need props inside your component and need to type those with a generic, you can use this pattern:
> 
> ```js
> interface ItemProps {
>   show: boolean;
> }
> 
> const Item = styled.View.attrs<ItemProps>(
>   ({ show }) => ({
>     pointerEvents: ({ show }) => (show ? 'auto' : 'none'),
>     ...other attrs,
>   })
> )<ItemProps>`
>   opacity: ${({ show }) => (show ? '1' : '0')};
>   ...other styles
> `;
> ```
Great solution, thanks!
But this works perfectly, until we don't have custom component (not a View). That's the situation when TS errors appears.
for example when we use this 
```js
 const Item = styled(AnotherItem).attrs<ItemProps>(.......)``;

<Item  show={isShow} />
```
we have got an error `Property 'show' does not exist on type 'IntrinsicAttributes &....`

Any idea?

**Comment by chasms** [comment]
> ```js
>  const Item = styled(AnotherItem).attrs<ItemProps>(.......)``;
> 
> <Item  show={isShow} />
> ```
> 
> we have got an error `Property 'show' does not exist on type 'IntrinsicAttributes &....`
> 
> Any idea?

You will need to make sure that `show` exists and is typed properly on the Props interface for `AnotherItem`

**Comment by just0110** [comment]
> > ```js
> >  const Item = styled(AnotherItem).attrs<ItemProps>(.......)``;
> > 
> > <Item  show={isShow} />
> > ```
> > 
> > 
> > we have got an error `Property 'show' does not exist on type 'IntrinsicAttributes &....`
> > Any idea?
> 
> You will need to make sure that `show` exists and is typed properly on the Props interface for `AnotherItem`

This is what i need to avoid. Because i want to add this prop only for styles, not to a component at all. 
Like working with interface
```tsx
interface iSome {
    show: boolean;
}
const Some = styled.View<iSome>`
    background: ${({ show }) => show ? 'black' : 'white'};
`
```

**Comment by just0110** [comment]
Solved!
I was a bit inattentively, and forgot to add return type in the end :)
```tsx
// in the end 
 const Item = styled(AnotherItem).attrs<ItemProps>(.......)<ItemProps>``;

<Item  show={isShow} />
```

**Comment by fingerartur** [comment]
The answer everybody was looking for

`
  import styled from 'styled-components'
  
  const Container = styled.div.attrs<
      { size: number }, // What is consumed by .attrs()
      { width: number, height: number } // What comes out of .attrs()
  >((props) => {
      return {
          width: props.size,
          height: props.size,
      }
  })<{ size: number }> // The outer type
  `
      width: ${props => props.width}px;
      height: ${props => props.width}px;
`

const container = <Container size={200} />
`

**Comment by bochen2014** [comment]
can we make it a bit messier?

**Comment by pedrobneto** [comment]
I'm having a problem while trying to use it with FlatList, this is my code for the Styled FlatList:
`
interface FlatListProps {
  hasContent: boolean
}
`

`
export const StyledFlatList = styled(FlatList as new () => FlatList<IInvoice>).attrs<FlatListProps>(({ hasContent }) => ({
  contentContainerStyle: hasContent ? 
    { marginHorizontal: 16, marginTop: 36 } : 
    { height: '100%', justifyContent: 'center'}
}))``;
`

But when I try to pass `hasContent = {!!content.length}` to it I get 'no overload matches this call', not sure if I'm missing something.

**Comment by curtvict** [comment]
@fingerartur legend!

**Comment by pke** [comment]
Thanks @fingerartur your solution is the closest to perfect. One little detail is that the return value of the keys in 

```
return {
          width: props.size,
          height: props.size,
      }
``` 

are not type-checked. One can change `width` to `with` and TS would not complain. Any idea how to solve this?

**Comment by mrtrust** [comment]
Found a little bit smaller version of [fingerartur](https://github.com/fingerartur) answer
Difference is that we do need to pass second type, TS will take care of it, and pass 1st type before .attr

`  import styled from 'styled-components'
  
  const Container = (styled.div<{ size: number }>).attrs((props) => {
      return {
          width: props.size,
          height: props.size,
      }
  })<{ size: number }> // The outer type
  `
      width: ${props => props.width}px;
      height: ${props => props.width}px;
`

const container = <Container size={200} />`
