### ISSUE TITLE
IE11 and Object.assign

### ISSUE THREAD

**Issue by oscar-b** [styled-components/styled-components#196]
## Version
1.0.10

IE11 barfs an error because the use of `Object.assign`:

```
Uncaught (in promise) TypeError: Object doesn't support property or method 'assign'
```

Might be worth mentioning that it needs a polyfill, if it can't be solved some other way?

**Comment by didierfranc** [comment]
Run app on IE without polyfill like polyfill.io is not an option

**Comment by oscar-b** [comment]
@didierfranc I figured as much and added `Object.assign` to my Polyfill.io request, but it should be documented at least.

**Comment by mxstbr** [comment]
We should be using the `object-assign` package to avoid this, and ponyfill it similar to what (afaik) React does
