### ISSUE TITLE
Is there a way to use sass `@for` in styled-components

### ISSUE THREAD

**Issue by seyade** [styled-components/styled-components#1960]
I have a `@mixin` in SASS that I'd to translate in `styled-components` and it has a `@for` loop in it. But I don't know how to do it. How would you do it?

    @mixin circleIt($circle-size, $item-count) {
      $rot: 0;
      @for $i from 1 through $item-count {
        &:nth-of-type(#{$i}) {
          transform: 
            rotate($rot * 1deg) 
            translate($circle-size / 2) 
            rotate($rot * -1deg);
        }
      }
    }

**Comment by kitten** [comment]
I suppose the exact 1 to 1 translation of this mixin would be:

```js
import { css } from 'styled-components';

const circleIt = (circleSize, itemCount) => {
  const rot = 0;

  return new Array(itemCount).fill().map((_, i) => css`
      &:nth-of-type(${i + 1}) {
        transform: 
          rotate(${rot}deg) 
          translate(${circleSize / 2}px) 
          rotate(${-rot}deg);
      }
  `)
};
```

Of course, stylistically it'd be better to write it a little differentially in styled-components' tagged-template literal case. But tl;dr: Just use JavaScript.

Also this question is better suited for our Spectrum or StackOverflow :wink: (See issue template)

**Comment by seyade** [comment]
Sorry I needed a solution as quickly as possible. Thanks for the response. I'll try it.
