### ISSUE TITLE
Codemod from injectGlobal to createGlobalStyle

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components#1961]
We should provide a codemod from `injectGlobal` to `createGlobalStyle`. Since cGS requires you to put the created component into the component tree, we cannot do it fully automatically, but we could throw a runtime error to make sure people remember to!

Something like:

```JS
// Before:
import { injectGlobal } from 'styled-components';

injectGlobal`
  html {
    background: red;
  }
`

// After
import { createGlobalStyle } from 'styled-components';

export const GlobalStyle = createGlobalStyle`
  html {
    background: red;
  }
`

throw new Error('You need to render the <GlobalStyle /> component! Do that, then delete this error message.')
```

Wdyt?

Also, at this point we should probably have a styled-components-codemods package... 😅

**Comment by wuweiweiwu** [comment]
Can I pick this up?

**Comment by mxstbr** [comment]
Yes please!

**Comment by probablyup** [comment]
I'm actually going to close this. Considering the impl is so different I don't think it's codemoddable in a way that's useful compared to a straightforward switch like `innerRef` -> `ref`.

**Comment by mxstbr** [comment]
Consider people with many `injectGlobal` calls throughout their app (for whatever reason), this could really save them a ton of time. I think we should have this codemod.

**Comment by imbhargav5** [comment]
Will this be a separate package?

**Comment by wuweiweiwu** [comment]
For `react-virtualized` we just created a folder `codemods` with codemods nested under version migrations. I was thinking of doing the same thing

**Comment by mxstbr** [comment]
@wuweiweiwu that sounds reasonable as long as folks can run them from the command line with a single command and don't have to install anything else :+1: 

```JS
npm i -g styled-components
styled-components codemod v4
```

Or something like that

**Comment by Aidurber** [comment]
I thought I'd give it a dabble as an opportunity to contribute and learn about codemods and ASTs. 

I've hit a bit of a wall and I'm tired so I thought I'd share my progress if anyone wants to pick it up. 

https://gist.github.com/Aidurber/26939f1753cc9903e5b43ca7846d193f


It currently produces: 
```javascript
import { createGlobalStyle } from 'styled-components';

createGlobalStyle`
  html {
    background: red;
  }`;

```

I'm got stuck on creating the `export const GlobalStyle`. Please, forgive my trash first attempt 😁

**Comment by imbhargav5** [comment]
@Aidurber Thank you for the snippet! Will take a look. It's not trash. We value all contributions and it means a lot to us.

**Comment by probablyup** [comment]
Any movement on this?

**Comment by StevenLangbroek** [comment]
@Aidurber how I'd approach it is:

- Collect the `createGlobalStyles` calls like you're already doing
- Find out how to turn them into variable declarations. You might have to increment a counter to keep the names unique in case someone declares more than one in a file
- Create named exports for each
- Append to source

`astexplorer.net` is a good resource for finding out how to transform. Put this snippet in and you can just go over the differences:

```js
createGlobalStyles``;

const thing = createGlobalStyles``;

export thing;
```

**Comment by StevenLangbroek** [comment]
![image](https://user-images.githubusercontent.com/296796/46263019-e8729100-c509-11e8-9df9-817d27d413e1.png)

**Comment by probablyup** [comment]
> Create named exports for each

Might want to skip that step in case they're not using es modules yet. Also throw in a console.warn like "An injectGlobal usage was converted to createGlobalStyles via codemod but needs to be hooked up. See {api website link} for instructions."

**Comment by StevenLangbroek** [comment]
@probablyup you're right of course. was just trying to break it down into manageable steps :).

**Comment by mxstbr** [comment]
I made a styled-components-codemod package, it'd be great to add the createGlobalStyle codemod to it! https://github.com/styled-components/styled-components-codemods

**Comment by StevenLangbroek** [comment]
If there's no movement I wouldn't mind taking care of this, I just don't want to duplicate effort. @Aidurber @probablyup would you like me to take care of this? Would you like to do a remote pair programming session?

**Comment by probablyup** [comment]
@StevenLangbroek Feel free to take over! I'm traveling for work the next few days but you can ping me through Twitter or Spectrum and I'll get back to you as I can.

Would be awesome if you could contribute directly to that repo Max made 👍

**Comment by StevenLangbroek** [comment]
Yeah I just don't want to deprive @Aidurber of a learning experience, it's a lot of fun to get started with. Are you waiting for the changes in enzyme re: ForwardRef, or now that they can't give a timeline do you want to move forward as soon as this codemod lands?

**Comment by StevenLangbroek** [comment]
(yes I'm paying attention on twitter :D )

**Comment by probablyup** [comment]
Yeah given the noncommital response from Jordan we’ll just move forward as soon as the codemods are done. I made a PR also to add a test util for grabbing styled components in enzyme more easily.

**Comment by StevenLangbroek** [comment]
Cool. On it then. Have some meetings and work to finish in the morning, should be able to have a PR for you later today.

**Comment by mxstbr** [comment]
Awesome @StevenLangbroek! 🙌

**Comment by StevenLangbroek** [comment]
Sorry this got away from me a bit. I'm doing some general clean-up on the file organization in the repo (the codemod that was there was in an `index.js` file etc), I'll open a PR early to gather feedback along the way.

**Comment by StevenLangbroek** [comment]
Lol babel codemods are kind of a awkward compared to jscodeshift. Not complaining, just observing :). Sifting through statements like jscodeshift does is incredibly elegant.

**Comment by probablyup** [comment]
I'm fine with either, whatever is easier to implement. I care more about getting this out and ease of use

**Comment by StevenLangbroek** [comment]
No babel-codemod is fine, merely observing. Either the styled-extend has to be rewritten or this one has to be done from scratch, i'll take the existing infra. Then on my spare time I'll tinker s'more with jscodeshift (could be fun to combine with Ramda lenses).

**Comment by StevenLangbroek** [comment]
I could make an assumption here:

- If someone uses `require` -> `exports.GlobalStyle = `
- If someone uses `import`, use `export const GlobalStyle`

Agree?

**Comment by StevenLangbroek** [comment]
Actually if I were in line with the one that's already there, I'd only accounts for `import`, so maybe we should just assume people are using ES modules here too?

**Comment by probablyup** [comment]
Honestly I would totally skip doing an export and just leave the warning in. Everyone's setup is going to be different so simply switching the helper used and putting in the console warning is enough IMO

**Comment by StevenLangbroek** [comment]
Alright, fair enough.
