### ISSUE TITLE
Disable styled-components (question)

### ISSUE THREAD

**Issue by sshmyg** [styled-components/styled-components#1964]
Hi, sorry for new issue, but I think devs could help in my question very quickly.

I have a few different projects, and single code base. Now I am moving from sass  to styled-components. And common code base already has styled-components integrated. But some others projects has not. And I should use sass there for some time. Can you help me, how could I turn off styled components for such projects? Maybe replace `style` tag or something?

Thank, you.

**Comment by msokk** [comment]
Do you use webpack? If so, you could replace `styled-components` module using https://webpack.js.org/plugins/normal-module-replacement-plugin/ with your shim of no-op functions. For `styled.<tag>` you need to loop through all used tags - https://github.com/styled-components/styled-components/blob/master/src/utils/domElements.js

**Comment by sshmyg** [comment]
@msokk I tried this way, but in some files we have multi exports and so on. So just file replace is not an option.

**Comment by sshmyg** [comment]
Also tried to simply delete `style` components, but bundle compiled with windows will broke all app (

**Comment by probablyup** [comment]
> Can you help me, how could I turn off styled components for such projects?

I mean just don't import it and use it? I don't really understand the question.
