### ISSUE TITLE
Props Cannot able to use it inside inject globals(body,html tags)

### ISSUE THREAD

**Issue by venkatesh-freshworks** [styled-components/styled-components#1965]
## Steps to reproduce
      When i try to use background color for html element from props,props didn't come inside injectGlobals
Even i try to use it inside my main components(Styled-component) of my application
## Expected Behavior
    is there any alternative way for that,I expected like 
html {
background-Color: {$props => props.theme.background && props.theme.background}
}

## Actual Behavior
 html background color didn't affected in my application

**Comment by probablyup** [comment]
Yeah, `injectGlobal` doesn't support theming. However the new `createGlobalStyle` component we're working on does, so stay tuned for the v4 beta coming soon.

**Comment by venkatesh-freshworks** [comment]
@probablyup ,thanks for writing
