### ISSUE TITLE
withComponent loses styles of the grandparent's component

### ISSUE THREAD

**Issue by madbence** [styled-components/styled-components#1966]
`.withComponent` loses styles of the grandparent, when the grandparent was extended with `styled` (works with the `.extend` method)

## Environment

```js
    "react": "15.6.1",
    "react-dom": "15.6.1",
    "styled-components": "3.4.5",
```

## Reproduction

https://codesandbox.io/s/9yl3p1v17y

```js
const Foo = styled.div`color: red;`;
const Bar = styled(Foo)``;
const Baz = Bar.withComponent("span");

render(<Baz>Red</Baz>, document.getElementById("root"));
```

## Expected Behavior

Text should be red.

## Actual Behavior

Text is black.

cc @robotkutya

**Comment by probablyup** [comment]
duplicate of #1956 #1817 

Please see those issues for more explanation. We have a formal solution coming in v4.
