### ISSUE TITLE
SC plugin for spacemacs/emacs?

### ISSUE THREAD

**Issue by osenvosem** [styled-components/styled-components#1970]
Is there such plugin or there a plan to create the plugin?

**Comment by probablyup** [comment]
No plan, but you’re welcome to work on it. There are ones for vim etc you can use for inspiration.

**Comment by rangeoshun** [comment]
I know this is an old topic, but still could not find a mode or plugin for `styled-components`. Hence I combined `typescript-mode`, `css-mode`, and a bit of extra by using `mmm-mode`. Here's my [gist](https://gist.github.com/rangeoshun/67cb17392c523579bc6cbd758b2315c1). Hope this helps some.
