### ISSUE TITLE
Styled-components v4 beta does not apply css style to the first styled component when using createGlobalStyle

### ISSUE THREAD

**Issue by rainstormza** [styled-components/styled-components#1973]
## System:
 - OS: macOS Sierra 10.12.6
 - CPU: x64 Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz
 - Memory: 693.23 MB / 16.00 GB
 - Shell: 5.2 - /bin/zsh
## Binaries:
 - Node: 10.9.0 - /usr/local/bin/node
 - Yarn: 1.9.4 - /usr/local/bin/yarn
 - npm: 6.4.1 - /usr/local/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.6.2 => 1.6.2 
 - styled-components: ^4.0.0-beta.0 => 4.0.0-beta.0 

## Reproduction

https://github.com/rainstormza/next-with-styled-components-v4

I have tried to use styled-component-v4-beta with nextjs ([example nextjs with styled components](https://github.com/zeit/next.js/tree/canary/examples/with-styled-components)), it works perfectly fine when I run in development mode (yarn dev).

But when I try to build app (yarn build && yarn start) the first styled-component after `<GlobalStyle />` does not render css style.

I think it might have some problem with babel-plugin-styled-components or ServerStyleSheet.
Anyway it used to work fine with styled-component v3

## Steps to reproduce

git clone https://github.com/rainstormza/next-with-styled-components-v4.git
yarn install
yarn build
yarn start
go to localhost:3000

## Expected Behavior

![image](https://user-images.githubusercontent.com/4003032/45120287-da8a5400-b187-11e8-872d-5a2cb3aa0b47.png)

## Actual Behavior

![image](https://user-images.githubusercontent.com/4003032/45120318-f3930500-b187-11e8-99a2-5d31112506f1.png)

Another problem is when I use `<GlobalStyle />` in multiple component (index.js , nav.js)
and I have tried to build and run app with command `yarn build && yarn start` this error happen

![image](https://user-images.githubusercontent.com/4003032/45120967-e1b26180-b189-11e8-86b5-05390b519a6c.png)

**Comment by probablyup** [comment]
Thank you very much for the reproduction repo! Looking into this.

**Comment by probablyup** [comment]
@rainstormza At your convenience go ahead and try installing `styled-components@dev`. It should be fixed.

**Comment by rainstormza** [comment]
It works.
thanks @probablyup 

Would you mind if I want to know about the cause of those bugs briefly?

**Comment by karolisgrinkevicius** [comment]
Someone knows when this bugfix will be brought in the next stable release?
