### ISSUE TITLE
👋 Render prop alternative to `withTheme` HOC

### ISSUE THREAD

**Issue by lukerollans** [styled-components/styled-components#1977]
Hey stylish people,

I've taken a look at the codebase and documentation but I can't see a render prop alternative to the `withTheme` HOC. I'm riding the render prop train pretty hard, so it'd be great to have this.

If I've missed it, sorry, please let me know where it is! If I haven't missed it, I'd be happy to contribute a PR.

Thanks!

**Comment by imbhargav5** [comment]
Can you give an example snippet as a reference for everyone to understand the issue better?

**Comment by lukerollans** [comment]
Sure thing! So here's an example of using the `withTheme` HOC

```javascript
import React from "react"
import { withTheme } from "styled-components"

const BrandLogo = ({ theme }) => (
  <img src={theme.brandLogoSrc} width="150" />
)

export default withTheme(BrandLogo)
```

Recently, but not super recently, [the render props pattern](https://cdb.reacttraining.com/use-a-render-prop-50de598f11ce) has started to become popular. React Router v4, React Apollo and other libraries have started embracing it. Some people, like me, prefer this pattern instead of using HOC's

```javascript
import React from "react"
import { Themed } from "styled-components"

const BrandLogo = () => (
  {/* Using the children prop */}
  <Themed>
    {theme => <img src={theme.brandLogoSrc} width="150" />}
  </Themed>

  {/* Using the render prop */}
  <Themed
    render={theme => <img src={theme.brandLogoSrc} width="150" />}
  />
)
```

This wouldn't replace `withTheme`, it would introduce the `Themed` component (name is just a placeholder) whose render function calls `props.render` or `props.children` so people who prefer this pattern can use it.

I'm happy to put together a PR as long as it's not going to be flat out rejected, but I can't think of a reason why it would be

**Comment by imbhargav5** [comment]
@probablyup What do you think? I think this feature can be released if we expose ThemeContext.Consumer.

**Comment by probablyup** [comment]
@imbhargav5 I think we'd basically have to recreate that component due to https://github.com/styled-components/styled-components/blob/40497c480bc8dc212bd13eb8c2a4544042cdee1e/src/hoc/withTheme.js#L14

**Comment by imbhargav5** [comment]
Oh that's right. @probablyup

**Comment by probablyup** [comment]
Oh hmm. Yeah I guess that's true.

**Comment by probablyup** [comment]
It's been exposed in beta.2 👍

**Comment by lukerollans** [comment]
@probablyup Great! Are we able to get a code sample here for future people, please. I'd also like to update the docs if you haven't already

**Comment by imbhargav5** [comment]
Sure go ahead!
