### ISSUE TITLE
Writing a Definition (d.ts) file for my UI library that is using regular Javascript

### ISSUE THREAD

**Issue by andrewhartwig** [styled-components/styled-components#1978]
### Preface
I'm sorry guys I know this isn't the right place but I'm just so lost and have no clue what to google to achieve this. I'm also very new to Typescript so combining this with trying to learn how to write definition files is just hurting my brain.

### Issue
I'm trying to add definitions to my UI library to help myself and others be able to use the UI library quickly and efficiently in vscode or w/e they use. We're not using typescript in our application or the UI library, its strictly to offer intellisence / documentation to our library.

Basic react components took a bit of tinkering, but I've figured it out.

But unfortunately I've just hit my first styled component. I actually got extremely close following the typescript guide. I had it working, but then typescript linter in vscode got mad at me for  `[ts] A 'const' initializer in an ambient context must be a string or numeric literal.`

DEFINITION:
```typescript
export interface ButtonProps {
  /**
   * Style the button as per the secondary theme
   */
  secondary?: boolean,
  /**
   * Style the button as per the alert theme
   */
  alert?: boolean,
  /**
   * Makes the button have equal width and height. Useful for icons.
   */
  square?: boolean
}

declare const Button = styled.default<ButtonProps, 'button'>('button')``;

export default Button;
```
^^^ This actually works, when I import Button elsewhere, I get all the expected prop autocompletes. But this is an "ambient" definition file. https://basarat.gitbooks.io/typescript/content/docs/types/ambient/d.ts.html
 so vscode turns the file red and blows everything up (even though it actually works).

SOURCE:
```javascript
import styled from 'styled-components';

const Button = styled.button` ...stuf using secondary, alert, square...`;

Button.propTypes = {
  secondary: PropTypes.bool,
};

Button.displayName = "Button";

export default Button;
```

Honestly the hardest part for me is that i can't find any good resources for how to actually figure this stuff out, so an acceptable helpful answer to me would be just giving me some resources that I can read to help learn stuff related to react / typescript / styled-components, and regular definitions / class extensions / types.

Any help is greatly appreciated :)

**Comment by probablyup** [comment]
StackOverflow or [our spectrum](https://spectrum.chat/styled-components) is the medium you're looking for!
