### ISSUE TITLE
Syntax highlighting issues

### ISSUE THREAD

**Issue by IljaDaderko** [styled-components/styled-components#198]
following completely breaks syntax highlighting for us:

`border: 0.25rem solid rgba(${props => props.white ? colours.white : colours.black}, 0.2);`

atom, using language-babel plugin

**Comment by mxstbr** [comment]
Would you mind submitting an issue over at https://github.com/gandm/language-babel? Thank you!

**Comment by UnsungHero97** [comment]
> Please note that this package is no longer supported

@mxstbr is `language-babel` still the recommended tool?

**Comment by mxstbr** [comment]
It still is, not sure why @gandm put that notice in the `README`! Works for me 😉
