### ISSUE TITLE
V4: Using 'as' prop on an extended styled component does not inherit parent styles

### ISSUE THREAD

**Issue by maureenwaggl** [styled-components/styled-components#1981]
## Reproduction

https://codesandbox.io/s/5441z07oyl

## Steps to reproduce

1. Create a React component that returns a styled component (Header in the reproduction example)
2. Extend that component by wrapping it in another `styled()` instance (Name in the example)
3. Add the `as` prop to the extended component

## Expected Behavior

The extended component should have the original styles (ie. Name should have all the Header parent styles)

## Actual Behavior

The parent component styles are not extended to the child instance. In the example, we are passing all props to the Header element, so it should be getting both the `as` and `className` props. It is also rendering the correct element that you specify as the `as` prop, but the styles are just missing.

**Comment by probablyup** [comment]
@maureenwaggl upgraded your example to latest beta and made a tweak https://codesandbox.io/s/4xkl5z5qz4

Since there's an interim custom component ("Heading") between the "Wrapper" styled component and the "Name" component, folding can't take place. We only fold when another styled component is directly passed into the `styled()` wrapper.

Thus when you use the "as" prop with a styled() wrapper around a custom component, the custom component is no longer the thing being rendered, but the styles from the `styled()` wrapper are carried through. Makes sense?

**Comment by maureenwaggl** [comment]
@probablyup That does make sense, thank you for explaining!

**Comment by probablyup** [comment]
A little visual for anyone that finds this issue later on:

```
                          -> (which classes are rendered as a result)

Foo = styled.div``        -> .Foo
Bar = styled(Foo)``       -> .Bar (flat-combined styles of Foo + Bar)

<Bar as="h1" />           -> .Bar (flat-combined styles of Foo + Bar)

Foo = styled.div``        -> .Foo
Bar = () => <Foo />       -> () => .Foo
Baz = styled(Bar)``       -> .Baz .Foo (each set of styles is separately added)

<Baz as="h1" />           -> .Baz (only the topmost styles remain since the target is switched out)

```

**Comment by maureenwaggl** [comment]
What would be the correct approach for handling this type of scenario?

Say you have a button component that can be rendered as a `button` or an `a`, so it needs to support the `as` prop.

The button component should have base styles, but it also does need to be a react component to be able to apply click handlers and custom classes (ie. `className={``${className} ${theme} ${size} ${disabled ? 'disabled' : ''}``}`).

The button should still be customizable, but it needs to have the event and other prop bindings or manipulations. You could potentially set up the classes for each instance manually (like `<CustomButton className="customClass small primary" />`), but it's not as friendly to do that and if you wanted to remove the theme from the class down the line, you'd have to do it in every instance instead of just the button component. 

Is there a suggested way to handle this?

Thank you!

**Comment by mxstbr** [comment]
@probablyup hmm, not a big fan of that. I think having to provide a default element makes sense even in a case like that where you're always defining at runtime.

**Comment by sami616** [comment]
Bit hacky, admittedly but i managed to get around this limitation but composing directly in my styled components `children` attribute. 

Added a safeguard of throwing if the user accidentally passes a 'children' prop as it always overrides what you define in `attrs`

![sc](https://user-images.githubusercontent.com/21065581/62869118-1706ee00-bd0f-11e9-9eca-4c06d626ace0.png)

**Comment by greypants** [comment]
In case anyone else lands here, the `forwardedAs` prop [added in 4.3.0](https://github.com/styled-components/styled-components/blob/master/CHANGELOG.md#v430---2019-06-05) in solves this issue.

Here's an example:
```jsx
const StyledTableCell = styled.th`
  background-color: ${props => props.bgColor || "blue"};
`;

const StyledStyledTableCell = styled(StyledTableCell)`
  color: red;
`;

const SomeTableCell = ({ as, ...props}) => {
  return <StyledStyledTableCell forwardedAs={as} {...props} />;
};

const SuperExtendedCell = styled(SomeTableCell)`
  border: 1px solid red;
`;

render(
  <table>
    <tr>
      <SuperExtendedCell bgColor="orange" forwardedAs="th">
        Look at my properly extended styles!
      </SuperExtendedCell>
    </tr>
  </table>
);
```

**Comment by JulSeb42** [comment]
I'm running into the same issue.

I would like to have a router `<Link>` and a simple `<button>` styled the same. I was thinking to write it like this:
```
<Button href={props.href} as={props.href ? Link : "button"}>
    {props.children}
</Button>
```

But when I use it the `href` is empty. How to solve this?

Thanks!

**Comment by soujvnunes** [comment]
@JulSeb42 try using [[`forwardedAs`](https://styled-components.com/docs/api#forwardedas-prop)] instead, since you are wrapping a component that also accepts [`as`].

**Comment by soujvnunes** [comment]
@JulSeb42  
1. Use [[`forwardedAs`](https://styled-components.com/docs/api#forwardedas-prop)] instead, since you are wrapping a component that also accepts [`as`].
2. Prefer using [`to`] instead of [href], if you are using a `Link` component provided by React Router Dom, this way:
```jsx
<Button as={props.href ? Link : "button"} {...{ [props.href?.startsWith("href") ? "href" : "to"]: props.href }}> 💣
    {props.children}
</Button>
```

**Comment by yogeshdatir** [comment]
I want to pass an emotion-styled component in "as" polymorphic prop in a similar fashion as @soujvnunes has passed the Link component.  But I need to add propTypes for that component prop. Can someone help with that?
