### ISSUE TITLE
Styled-components peer dependency in third party library

### ISSUE THREAD

**Issue by brad-decker** [styled-components/styled-components#1983]
<!--
## Environment
I apologize but the npx command wouldn't run for me on linux/manjaro. 

My company publishes a WIP project called styled-material-components https://www.github.com/MerlinLabs/styled-material-components. Our current combination of our library + our product is working fine, although we realized we have a huge bundle for styled-material-components and i'm working on fixing that currently. 

The problem I have right now is that if i upgrade styled-components in our product anywhere I wrap my components from styled-material-components in 'styled()' all the styles from our library are stripped and it becomes a base component with just the latest styles applied. 

I *thought* the problem was in some kind of sub-dependency mismatch with styled-components on both SMC and our product repo but as it turns out when I am trying to extract styled-components from the bundle of SMC so that the version of our library doesn't prevent users downstream. However now even if both SMC bundle and our closed source repo are on the same version of styled-components i am noticing this issue.

I am using yarn link to test this. Does this sound like something anyone has ran into before and what is that thing i'm missing here? really appreciate any feedback.

**Comment by mxstbr** [comment]
Ask usage questions in the community at https://spectrum.chat/styled-components please.
