### ISSUE TITLE
Global styles disappear on page navigation

### ISSUE THREAD

**Issue by janosh** [styled-components/styled-components#1988]
This is somewhat of a follow up to #1986 ([same repo](https://github.com/StudentenBildenSchueler/homepage), same environment).

## Behavior

Using `createGlobalStyle` throws no errors and works as expected on initial page load. However, all global styles are dropped on page navigation, i.e. after clicking any internal link on a Gatsby site the resulting page is displayed without the global styles. The styles return when refreshing the page.

**Comment by probablyup** [comment]
Will check it out

**Comment by probablyup** [comment]
Fixed by #1989. Will cut another beta shortly

**Comment by janosh** [comment]
@probablyup It appears as though this issue was fixed in betas 2, 3 and 4 but reintroduced in 5.

**Comment by kachkaev** [comment]
@janosh I upgraded to `4.0.0-beta.5`, but could not see the bug.

**Comment by probablyup** [comment]
@janosh hmm I pulled down your repo again in the develop branch and installed beta 5 - I don't see the issue.

**Comment by janosh** [comment]
@probablyup That's odd. You're right the problem doesn't show up in the repo from #1986 when I upgrade to beta 5 there. I was working on [this repo](https://github.com/janosh/janosh.io) just now and it just tried upgrading to beta 5 again. The problem definitely occurs but disappears when I downgrade to beta 4.
