### ISSUE TITLE
Impossible to styled ForwardRef using v4

### ISSUE THREAD

**Issue by neoziro** [styled-components/styled-components#1990]
### System:
 - OS: macOS High Sierra 10.13.6
 - CPU: x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
 - Memory: 3.92 GB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
### Binaries:
 - Node: 8.11.4 - ~/.nvm/versions/node/v8.11.4/bin/node
 - Yarn: 1.9.4 - /usr/local/bin/yarn
 - npm: 5.6.0 - ~/.nvm/versions/node/v8.11.4/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
### npmPackages:
 - babel-plugin-styled-components: ^1.6.4 => 1.6.4
 - styled-components: ^4.0.0-beta.1 => 4.0.0-beta.1

## Reproduction

```js
import React from "react";
import styled from "styled-components";

const Div = ({ innerRef, ...props }) => <div ref={innerRef} {...props} />;

const ForwardRef = React.forwardRef(
  (props, ref) => <Div {...props} innerRef={ref} />
);

// This component does not forward any className
const StyledForwardRef = styled(ForwardRef)`padding: 4em`;

// This component works
const StyledDiv = styled(Div)`padding: 4em`;
```

A ForwardRef is a special type, are you checking the type of component?

**Comment by alansouzati** [comment]
I made an attempt to create a codesandbox for this, but something is up with 4.0 beta and the module distribution.

https://codesandbox.io/s/vvk5zzw633

**Comment by alansouzati** [comment]
Just updated the codesandbox. both seems to be working when I first load the codesandbox, but they both stop working if I make any edits to the codesandbox editor. I'm sure sure if this is a problem with styled-components though.

https://codesandbox.io/s/vvk5zzw633

**Comment by probablyup** [comment]
It seems to be working fine https://codesandbox.io/s/r7oz4p2lnp

**Comment by neoziro** [comment]
Yes it works in Codesandbox but not locally. That’s why I didn’t provide a Codesandbox example. I can’t figure out what’s going on. I will try to give you a repro out of Codesanbox.

**Comment by Paosder** [comment]
I found similar problem in forwardRef.

If you set `className` in forwardRef like below,
```
// html element (e.g. `div`)
const ForwardRef = React.forwardRef((props, ref) => (
  <div {...props} innerRef={ref} className="test" />
));

// or component
const ForwardRef = React.forwardRef((props, ref) => (
  <MyComponent {...props} innerRef={ref} className="test" />
));

// This component does not forward any className
const StyledForwardRef = styled(ForwardRef)`background:red; padding: 4em;`;

```

styles(by styled-components) will disappear and sometimes only dummy style name left(like `sc-EHOje`, but actually empty class). You can reproduce this issue just adding className in @probablyup 's Codesandbox, I think this issue was what @gregberge want to reproduce. To workaround this issue, just not use 'className' attribute in root of its forwardRef. However it seems really weird so, it should be resolved or warn users not to use like this.
