### ISSUE TITLE
Stylesheet grows on every request when SSR with Apollo

### ISSUE THREAD

**Issue by rovansteen** [styled-components/styled-components#1991]
When using apollo & styled-components together in SSR there is an issue where the stylesheet of styled-components keep growing for every request and every component that is rendered on the server will keep being served to every other request after that (even if the component is not on the page of that request).

### System:
 - OS: macOS High Sierra 10.13.6
 - CPU: x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
 - Memory: 242.20 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
### Binaries:
 - Node: 10.0.0 - /usr/local/bin/node
 - Yarn: 1.6.0 - /usr/local/bin/yarn
 - npm: 5.6.0 - /usr/local/bin/npm
 - Watchman: 4.7.0 - /usr/local/bin/watchman

## Reproduction
https://github.com/rovansteen/styled-components-apollo-ssr

This example is a small reproduction of the issue. This is a combination of the `next.js` examples of [apollo](https://github.com/zeit/next.js/tree/canary/examples/with-apollo) & [styled-components](https://github.com/zeit/next.js/tree/canary/examples/with-styled-components).

I added two pages `/foo` & `/bar`. The first one has a red box, the latter a blue one. When you first server render the `/foo` route, you get the following server side rendered stylesheet:
```
<style data-styled-components="jyimBH">
/* sc-component-id: foo__Box-dflpa2-0 */
.foo__Box-dflpa2-0 {} .jyimBH{background:red;}
</style>
```

That's all fine and exactly as you expect, but now if you render `/bar` you get this stylesheet:
```
<style data-styled-components="jyimBH hhmlmC">
/* sc-component-id: foo__Box-dflpa2-0 */
.foo__Box-dflpa2-0 {} .jyimBH{background:red;}
/* sc-component-id: bar__Box-sc-6q2tw8-0 */
.bar__Box-sc-6q2tw8-0 {} .hhmlmC{background:blue;}</style>
```

Now the styles from the `/foo` page get included on the request for `/bar`. You can imagine that if you have a big website with lots of different pages this can quickly add up and start making the site really slow after a while.

I have narrowed the problem down to the [`getDataFromTree`](https://github.com/rovansteen/styled-components-apollo-ssr/blob/master/lib/with-apollo-client.js#L23) method that Apollo uses to figure out which data needs to be fetched. If you comment out this part the server rendered stylesheets do not leak.

There is this comment in the example that might explain the issue:
```
      if (!process.browser) {
        // getDataFromTree does not call componentWillUnmount
        // head side effect therefore need to be cleared manually
        Head.rewind();
      }
```
Perhaps it has something to do with `componentWillUnmount` not being called? Although that seems obvious on the server. I looked for some way to "rewind" or reset the stylesheet but I could not find any.

Hope this reproduction and explanation makes it clear the issue I'm facing 🙌🏼

**Comment by probablyup** [comment]
@rovansteen can you call collect styles after getDataFromTree but before renderToString?

**Comment by rovansteen** [comment]
@probablyup it doesn't look like `next.js` allows me to pass anything down from `_document.js` (where I need all this to happen so I can put the style tags in the head) and `_app.js` where Apollo does it's thing.

I'm a little bit confused, why do styles leak if `collectStyles` is active for both the renders? It seemed to me that this could be an issue if you do not wrap `collectStyles` outside both the `getDataFromTree` and the regular render, but now everything should be captured and cleaned up right?

**Comment by probablyup** [comment]
Still thinking/looking into this. I don't think you're doing anything wrong and it matches the implementation from the official example exactly. [That example](https://github.com/zeit/next.js/tree/canary/examples/with-styled-components/pages) doesn't have much content in it though so it's possible the implementation is too minimal to see it's set up wrong.

But it could also be something on our side. Just haven't dug enough yet.

I can say that I've used styled-components successfully with that apollo method though, so I know it's workable.

**Comment by probablyup** [comment]
@rovansteen Still not sure, but interestingly the bug isn't present in the v4 beta. 🤷‍♂️

**Comment by probablyup** [comment]
@rovansteen Might want to check out the new v3 version I just published. There was an important streaming fix in there that I wouldn't be surprised if it was related to the issue you're seeing

**Comment by rovansteen** [comment]
@probablyup I tried the new v3 but same issue. I updated the repo if you want to try it out yourself. I can confirm that the v4 beta does **not** have the issue interestingly enough. Looks like it's stable enough to use it in the project where I was experiencing this issue.

Do you want to keep this issue open for further investigation or do you want to close it?

**Comment by probablyup** [comment]
Let's just go ahead and close it. v3 had a much more complicated flow for acquiring stylesheets and I probably won't have time to go through and debug it more thoroughly. Glad v4 is working as expected.
