### ISSUE TITLE
styled-component multi classname

### ISSUE THREAD

**Issue by desiresprout** [styled-components/styled-components#1992]
class HeaderContainer extends Component {        
    render() {
        const {login } = this.props; 
        
        return (              
              <Buttonstyle className="login" />                    
               }               
            
        );
    }
}

const Buttonstyle = ({ login }) => (
    <Button login={login} >
        Login / Resigter
    </Button>
);

export const Button = styled(Link)`
   &.login{
    font-weight: 1000;
    color: ${oc.gray[1]};    
    padding: 0.5rem;
    padding-bottom: 0.4rem;   
    border-radius: 2px;
    text-decoration: none;
    transition: .2s all;

  }
`

&.login not working... what's the problem??  thanks..

**Comment by probablyup** [comment]
@desiresprout could you make a codesandbox illustrating your issue? Much easier to debug with that. Thanks!

**Comment by desiresprout** [comment]
https://codesandbox.io/s/244lx0028r

here.. multi classname is not working.. thanks..

**Comment by desiresprout** [comment]
https://codesandbox.io/s/244lx0028r !! thanks.

**Comment by desiresprout** [comment]
https://codesandbox.io/s/kj18kjkp5

**Comment by probablyup** [comment]
@desiresprout you need to make sure you're passing `className` down https://codesandbox.io/s/x9m4xxy9op
