### ISSUE TITLE
jest enzyme different class names node version 10.7 and 10.9

### ISSUE THREAD

**Issue by odrzutowiec** [styled-components/styled-components#1995]
## Environment
node 10.7 vs node 10.9

## Reproduction
When running jest enzyme snapshots styled-component produces different class names for node version 10.7 and 10.9

## Expected Behavior
Should produce the same class names maybe? Close the issue if this behaviour is expected.

## Actual Behavior
![screen shot 2018-09-10 at 10 51 07](https://user-images.githubusercontent.com/2934746/45286973-751bc780-b4e7-11e8-8321-eab3c0d1312a.png)

**Comment by probablyup** [comment]
@odrzutowiec I wouldn't worry about it.

Also we definitely recommend using [jest-styled-components](https://github.com/styled-components/jest-styled-components) if you are going to be snapshotting.
