### ISSUE TITLE
Ideas to enhance mobx-styled-observers software design pattern

### ISSUE THREAD

**Issue by andraz** [styled-components/styled-components#1998]
I am building on the shoulders of giants, developing a software design pattern which merges the best of the best in the React ecosystem (without routing, to keep it simple for start and still cover 95% of use cases) while avoiding all of the "new bad parts" in ES6-7-8.

**Pattern wraps a styled-component in a closure, which hides the store inside the component.**

It covers some of the most important points for good developer experience:

- keeps the code DRY
- greatly reduces cognitive load
- removes as much boilerplate code as possible (simply avoids flux refactoring nightmares)
- protects the developers from themselves (discourages "clever" approaches and "hacky" solutions)

Store returns the component in a getter which makes it look (from outside) like a simple prop of the store. This prop can then be used as a JSX element directly.

This removes the need to pass the store through props or context or global var or any other exotic means and greatly simplifies code. The returned styled-component already has all information it needs to (re)render and refresh its content automatically on its own (with optimal performance).

## Environment

Minimal code needed for a complete React project, it takes only 4 files in 2 folders inside `/src`.

Components and stores can get added as needed.

Demo works online in CodeSandbox:
https://codesandbox.io/s/github/andraz/mobx-styled-observers

## Reproduction
for local cloning, use this repo:
https://github.com/andraz/mobx-styled-observers

## Steps to reproduce

As all experienced JS programmers agree, best things in life are those that work by themselves & work correctly (without bugs), in short - **automatic** is the name of the game:

* automatic CSS handling: `styled-components`
* automatic shouldComponentUpdate handling: `mobx-react`
* automatic state managment: `mobx-state-tree`

## Expected Behavior

**_Plug and play_** on all levels of developer experience, even **for designers**:
- designer can open a `component.style.js` and patch some CSS tweaks on his own
- beginner programmer can:
  - render a `<store.Header>` component coming from store by simply adding it to JSX without passing any props, keys, ids or state, it "just works"
  - prepare a new component from CSS without bothering to wire it up to views inside of the store
- senior programmer:
  - has all of the most powerful automatic tools at his disposal
  - can get components prepared by juniors and not waste time on generic tasks
  - gets high FPS updates built in automatically
  - gets the advanced environment while still keeping it simple enough to onboard anyone fast

## Actual Behavior

* Everything from expected behavior.
* Additional comments where we could improve this pattern even more are welcome...
* Additional ideas to use new features of the upcoming `styled-components` version also welcome...

At the moment I am researching how to improve the pattern for usage in array/map (where you return all child components of the tree node, then loop over them for rendering) & use in multilevel nesting of store models.

**Comment by probablyup** [comment]
Cool concept, but this is an issue tracker. I'd definitely recommend sharing your idea in our [Spectrum board](https://spectrum.chat/styled-components) though.
