### ISSUE TITLE
Style Several Components at once

### ISSUE THREAD

**Issue by MrLoh** [styled-components/styled-components#200]
I have a case where I want to style several external components in the same way. 

```js
const Star = styled(FaStar)`
    cursor: pointer;
    width: 1.2rem;
    padding: 0.1em;
`
const StarEmpty = styled(FaStarO)`
    cursor: pointer;
    width: 1.2rem;
    padding: 0.1em;
`
```

It would be really nice to not have to change the styles in two places. I could imagine something like this:

```js
const [Star, StarEmpty] = styled(FaStar, FaStarO)`
    cursor: pointer;
    width: 1.2rem;
    padding: 0.1em;
`
```

Would be happy to try and help with a pull request, if you think that would make sense. Or is there already a way or a better syntax to implement it?

**Comment by geelen** [comment]
Hmm, I'm not so keen on this approach. The "Styled Components Way" would be to simply break those props out into a variable:

```js
const commonStyles = css`
    cursor: pointer;
    width: 1.2rem;
    padding: 0.1em;
`
const Star = styled(FaStar)`
    ${ commonStyles }
`
const StarEmpty = styled(FaStarO)`
    ${ commonStyles }
`
```

Would that work in your use case?

**Comment by MrLoh** [comment]
cool, that makes a lot of sense
