### ISSUE TITLE
Feature Request: How to make it easier for third party UI libraries to adopt/support styled-components

### ISSUE THREAD

**Issue by acomito** [styled-components/styled-components#2002]
I love styled components.

One thing I've noticed is that very few ui libs "support" styled components. I know of 1 or 2 which are built with styled-components and support them-- but they're not the greatest libs. 

I love antd's library-- but they don't really support it. You can hack around using !important and insertGlobalStyles to get it working, but it's sketchy. Unfortunately antd seems against changing to use styled-components, because the majority of their lib depends on their classnames package.

I read about atlaskit which was built with styled components and I was super happy. But once I dove into it, I realized it was _built_ with styled components but didn't necessarily _support_ styled-components... in other words you can't simple pass an atlaskit button into styled() and apply your styles like you can on a normal div.

I unfortunately don't have any actionable suggestions for increasing adoption by third-party libraries, but I wanted to spark a discussion in case somebody smarter than I has ideas.

I'll update this post with additional details as I gather them.

**Comment by probablyup** [comment]
The biggest thing is making sure a third party library passes through an externally-provided `className` prop. Everything else is relatively automatic.

**Comment by acomito** [comment]
I didn't get a full understanding of this, but it seems like that's a big ask for some reason:

atlaskit seems oppose to it:

https://bitbucket.org/atlassian/atlaskit-mk-2/issues/117/is-it-possible-to-add-id-class-to-modal

antd seems to be using the className field in it's own way.

But I agree technically it seems like an easy no brainer. But, I guess everything is easy when you're not the one maintaining a enterprise ui library.

**Comment by selipso** [comment]
Part of this problem might also be tied to the relative newness of the CSS-in-JS paradigm and of styled-components. AFAIK, styled-components is the only styling library to get the styling compatible with CSS-in-JS and then some more. The rest of the styling libraries have quite a few missing features when it comes to supporting 'vanilla' CSS with CSS-in-JS.

As already mentioned, the 'className' API ('style' prop for React Native) are fairly low requirements for making your API compatible, and any new project will require doing some custom components work by adding classes anyways (for theming, consistency, etc.), so I've just decided to bite the bullet and develop my own cross-platform UI library using styled-components and storybook.

**Comment by acomito** [comment]
Hmm... maybe the question isn't what styled-components can do technically as a library but what the community can do to champion it to some of these (and future) libraries.

**Comment by sag1v** [comment]
Not sure what will convince others to use `styled-components` in their libs, but for me it was separation of concerns instead of separation of technologies (e.g js/css/html).  
Beyond that, I find `styled-components` a lot more suited for reusable components then any of the external CSS solutions.

**Comment by 0xF013** [comment]
@acomito I had a discussion recently about exposing className in one of our internal components. The main reason people might be against it is because the className prop is an escape hatch and can be a great source of leaky abstraction, i.e. having a clearly defined and limited set of style-related props creates a very limited combination of possible visual states that a component may have. With a className exposed, the owner of the original component loses the freedom of being able to modify the styles of the component radically and at will because the contract is no longer set by a limited number of props.

I know it applies to a limited scope of components but there can be good reasons why, say, a team responsible for an internal library distributed to several projects and hundreds of developers might not want to deal with things that brake after a change because someone deliberately mixed some styles at a later point in usage.

**Comment by probablyup** [comment]
>  because the className prop is an escape hatch and can be a great source of leaky abstraction

Or someone could legitimately need to add a class for targeting purposes, or if they have some legacy CSS, etc. Anyone who pushes back against letting someone pass a typical HTML attribute like  className, id, etc. is just being lazy, IMO.

Going to close this as I haven't seen anything raised that differs from our existing integration strategy and we've had good success with it thus far if you look at libraries like styled-system, rebass, etc.
