### ISSUE TITLE
Typescript, React Native and is not assignable to type

### ISSUE THREAD

**Issue by maitriyogin** [styled-components/styled-components#2003]
Hi,
I'm currently trying to use typescript with a react native application and have run into a problem when using styled components...
When I try and use a styled component as a component
```
const LoginFormStyledView = styled.View`
  flex: 1;
`;

const LoginForm = () => <LoginFormStyledView />;
```
 I get the following
```
[ts]
Type '{}' is not assignable to type 'Readonly<ThemedOuterStyledProps<View, any>>'.
  Property 'measure' is missing in type '{}'.
```

under the `<LoginFormStyledView />` component...
What do I need to do to get rid of this error?

Cheers,
Stephen.

**Comment by probablyup** [comment]
TS questions should go to DefinitelyTyped or some other help forum, thanks

**Comment by maitriyogin** [comment]
ok, sorry for bothering you, I'll post there.
/Stephen
