### ISSUE TITLE
How to use style component with react native element

### ISSUE THREAD

**Issue by fstn** [styled-components/styled-components#2004]
Hello,

I use React Native Elements, and would like to use styled component but the majority of components use custom style props like  "containerStyle" "iconStyle" instead of style, how do I can manage that?

**Comment by probablyup** [comment]
If you're wrapping a custom component (which I believe most RN components are implemented as since there's no string elements for them), they should just be passed through.

**Comment by selipso** [comment]
For buttons, what I've done is I have the "containerStyle" refer to the default style from the styled component's props. This way the RN Elements component would have a prop along the lines of `containerStyle={this.props.style}`.

Then, for iconStyle, I have it pre-defined to be one of a handful of settings that tie into the "theme" of the component, similar to the bootstrap convention of "default", "primary", "info", etc. The parent (styled) component will generate a dynamic style for the icon and pass it in as a property to the RN Elements component. For this part you can use either styled-components or just plain CSS-in-JS.

**Comment by probablyup** [comment]
Going to close this since this is more of a usage question than a feature request or bug report. Highly recommend Spectrum or SO for further discussion if needed.
