### ISSUE TITLE
CSS calc

### ISSUE THREAD

**Issue by ggregoire** [styled-components/styled-components#202]
Hi!

I got some weird results with `calc`.

## Version
1.0.11

## Steps to reproduce

```javascript
const DoubleInputContainer = styled.div`
  margin-bottom: calc(15px - 0.5rem) !important;
`
```

## Expected Behavior

```css
margin-bottom: calc(15px - 0.5rem) !important;
```

## Actual Behavior (Chrome console)

```css
margin-bottom: calc(15px - 0.5rem); /* !important is missing */
marginBottom: -webkit-calc(15px - 0.5rem) !important; /* marginBottom is not valid */
```

Thanks for the help!

**Comment by geelen** [comment]
Ah this is probably a bug with our Autoprefixer we use from Glamor. We had
to shoehorn it in pretty... creatively... so I'm not surprised it has some
problems

**Comment by threepointone** [comment]
ugh. sorry folks. will make an issue on my side too.

**Comment by threepointone** [comment]
so... I've moved away from the autoprefixer I had, and now use https://github.com/rofrischmann/inline-style-prefixer. consider doing the same?

**Comment by charlieeddus** [comment]
Could this change of autoprefixer in **glamor** be the reason I get: 

`Error in ./~/styled-components/lib/utils/autoprefix.js`
`Module not found: Error: Cannot resolve module 'glamor/lib/autoprefix' in [...]/node_modules/styled-components/lib/utils`
`@ ./~/styled-components/lib/utils/autoprefix.js 15:18-50`

**Comment by threepointone** [comment]
oh my, didn't know it was directly using it. lemme get it back for now.

**Comment by threepointone** [comment]
live in 2.18.2.

**Comment by charlieeddus** [comment]
Cheers! 👍

**Comment by mxstbr** [comment]
We didn't use that for some reason, @geelen can you remember why?

**Comment by geelen** [comment]
![](http://i.imgur.com/iw4YuOi.gif?noredirect)

**Comment by geelen** [comment]
Fixed this and added a test case for `calc()` in #208
