### ISSUE TITLE
Correct way of adding function props to styled()

### ISSUE THREAD

**Issue by doque** [styled-components/styled-components#2022]
Hello,

we have a couple of "base" components using `react-select` to generate reusable dropdown fields. We set some general props, such as `{ isClearable: false, autoFocus: false }` etc. to ensure consistent behavior and avoiding props bloat when using these components:
```js

import Select from 'react-select';

const FlexSelect = styled(Select).attrs({
  isClearable: false,
  autoFocus: false
})`
  display: flex;
`;
```

However, we're facing an issue when using a function as a prop, specifically `noOptionsMessage`:

```js
styled(Select).attrs({
  noOptionsMessage: () => 'nothing found'
})`
```

During runtime, this error occurs:
```js
Uncaught TypeError: noOptionsMessage is not a function
```

[Looking at the docs](https://www.styled-components.com/docs/api#attrs) for `.attrs`, it clearly states that a function cannot be passed: 
> These can be of any type, except functions. They'll stay static and will be merged into the existing component props.

However, the example right below this note shows the usage of a function prop:

```js
const Input = styled.input.attrs({
  // we can define static props
  type: "password",

  // or we can define dynamic ones
  margin: props => props.size || "1em",
  padding: props => props.size || "1em"
})`
```

This is confusing to us. What's the proper way of using functions in default props, if there is any?

I've added a sample repository to showcase the issue here: https://github.com/doque/styled-components-react-select-attr/blob/master/src/App.js#L5

**Comment by wzchua** [comment]
From what I can see, attrs elements are checked if they are a function and used to pass in the props

You can deal with that by returning a function from the function that is taking the props.
Like below:
```javascript
const FlexSelect = styled(Select).attrs({
  isClearable: false,
  noOptionsMessage: () => () => "nothing"
})`
  display: flex;
`;
```

**Comment by nicholaai** [comment]
have you tried utilizing defaultProps? something like the following

```js
export const Button = styled(Box)`
...
`;

Button.defaultProps = {
    as: 'button',
    bg: 'blue',
    method: () => ...
};

**Comment by probablyup** [comment]
It's kind of counterintuitive, but if you want to use attrs to pass a function, you have to actually do this:

```
styled(Select).attrs({
  noOptionsMessage: () => () => 'nothing found'
})`
```

The reason why is the top layer is styled-components passing the props into the function. What's returned from that is then what is provided as a prop.
