### ISSUE TITLE
`keyframes` returning undefined

### ISSUE THREAD

**Issue by illiteratewriter** [styled-components/styled-components#2024]
## Environment
 OS: Windows 10
  Node: 8.11.1
  Yarn: 1.6.0
  npm: 5.6.0
  Watchman: Not Found
  Xcode: N/A
  Android Studio: Not Found

## Reproduction

Tried the example for `@keyframes` it is throwing an error `(0 , _styledComponents.keyframes) is not a function`. So I tried to `console.log(keyframes)` and it is returning `undefined`

"styled-components": "^3.4.9"

    import { keyframes } from "styled-components"
    console.log(keyframes);

I am using this with `react-native`

**Comment by mxstbr** [comment]
Keyframes are not a thing on ReactNative. You will have to use the ReactNative `Animated` API.
