### ISSUE TITLE
Just A Couple Typos On The Basics Page Of The Documentation Website

### ISSUE THREAD

**Issue by dallanlee** [styled-components/styled-components#2026]
Three times throughout the Basics section of the Docs, ampersand is written amperstand (ampers_**t**_and).

https://www.styled-components.com/docs/basics

I googled to see if this was one of those European English vs North American English differences—like aluminium vs aluminum—but didn't find anything…

**Comment by probablyup** [comment]
Just a typo, you’re welcome to submit a PR fixing it
