### ISSUE TITLE
Can't use keyframes in createGlobalStyle

### ISSUE THREAD

**Issue by garetmckinley** [styled-components/styled-components#2027]
Version: 4.0.0-beta.8

I ran into this problem when attempting to add an animation to a body background, so I created [this codesandbox reproduction](https://codesandbox.io/s/lzrxkq9kz).

Basically, when `keyframes` is used within a `createGlobalStyle` block, the value of the `animation` property is `[object Object]`

![image](https://user-images.githubusercontent.com/1624279/45925648-36badb00-bedf-11e8-85cb-a62cd0d227b2.png)

I searched around and couldn't find any mentions or reference to this issue, so I apologize if it's been brought up and you're aware of it.

**Comment by probablyup** [comment]
Definitely a bug, thanks for reporting!

**Comment by jordmccordgcv** [comment]
Not sure if its related but this also causes the same bug and worked pre 4.0
```
const frames = i => keyframes`
  0% {
    transform: rotate3d(0, 0, 1, ${-45 - 235}deg);
    transform-origin: center;
  }
  100% {
    transform: rotate3d(0, 0, 1, ${i * 30 - 235}deg);
    transform-origin: center;
  }
`;

const someComponent = styled.div`
  animation: ${frames(1)} 1s infinite;
`
```

**Comment by probablyup** [comment]
Fixed in https://github.com/styled-components/styled-components/releases/tag/v4.0.0-beta.9!

**Comment by Yahkob** [comment]
@probablyup am I just doing this wrong or is this a bug too? on 4.0.0-beta-9 btw
```
        const CheckMark = styled.div`
            transform: rotate(45deg);
            ${(props => props.animate && `animation: ${ bounceCheckAnimation } 700ms linear;`)}
        `;
```
