### ISSUE TITLE
Support media queries with React Native

### ISSUE THREAD

**Issue by tlvenn** [styled-components/styled-components#203]
Thanks for the fantastic project guys, I am primarily targeting RN and I though it would be awesome if styled components could provide support for media queries seamlessly in RN.

Turns out that there is a new very promising project to add media queries support to both React and React Native.
> https://github.com/tuckerconnelly/uranium

It would be pretty neat if a bridge would exist to embed this functionality so that I dont have to wrap my style component (which is already a wrapper) with Uranium wrapper.

**Comment by tlvenn** [comment]
@mxstbr any though on the subject ?

**Comment by jacobp100** [comment]
Just so I understand correctly, are you looking to have this,

```css
height: 120;

@media (min-width: 600) {
  width: 56;
}
```

Go to,

```js
const styles = {
  base: {
    height: 120,

    '@media (min-width: 600px)': {
      height: 56,
    },
  },
}
```

**Comment by knowbody** [comment]
I'm curious what would media queries in RN do? What sort of problems are you trying to solve? Would you like to get something what https://github.com/aybadb/react-native-responsive does?

**Comment by tlvenn** [comment]
@knowbody you can check this proposal https://gist.github.com/grabbou/72767db51f97fe86cfea
That should give you an idea on what media queries could do on RN.

It addresses the same kind of problem domain that media queries solve on the web. When you have an RN app that target ios, android, phones and tablets alike and need to adapt its layout depending on the device orientation and so on...

I dont really like how react-native-responsive is implementing media queries, for me, media queries should be expressed as css rules, just like on the web. In that regard, Uranium is a much better prospect imho.

Extended Stylesheet implemented the proposal above:
> https://github.com/vitalets/react-native-extended-stylesheet#media-queries

**Comment by mxstbr** [comment]
As nobody has asked for this custom extension in more than half a year I doubt we'll include it in the library. On top of that many workarounds already exist that make media query functionality possible on ReactNative.

Thank you for suggesting improvements to the library!

**Comment by corysimmons** [comment]
Why didn't https://github.com/shripadk/styled-components/commit/d4fe1a9acd82d2f44d11012f5e18140453f5e38d get merged?

Does it add support for this?

I would love to use styled-components with RN but I need media queries. react-native-extended-stylesheet syntax is RN pojo nastiness...

Seems like a really valid request. Please re-open.

**Comment by eayllon1** [comment]
So, is media-query not possible in React-Native? Why not support all CSS3?

**Comment by probablyup** [comment]
I'm open to it if someone wants to make a new PR and lots of tests.

**Comment by HosseinAlipour** [comment]
Any new information on this? what does community use right now? 
there are many projects support the feature but all of them use different ways of defining styles and queries, making projects unintegrated and messy.

**Comment by corysimmons** [comment]
@HosseinAlipour Look at the PR I linked above. It's really simple. See if you can replicate that into a new PR like Evan suggested.

If that solution works for you locally, I'm sure someone could point you towards where a small test suite like that might live.

I haven't used RN in a long time, but would love media queries to be available next time I need to. :)

**Comment by nandorojo** [comment]
I'm working on a responsive, Theme UI-like library for React Native. It would be great if the `styled.View` from `styled-components/native` supported the web media queries the way `styled.div` does. This would be fine even if it **only works on web**. On web, it makes the most sense for media queries to be done using CSS, not JS, as some people have mentioned above. 

I already got the media queries to work on native using the `useDimensions` hook from `@react-native-community/hooks`.

That said, if you try to use React Native's `Dimensions` API to create JS-based media queries on web (instead of using CSS,) you'll break server side rendering (see https://github.com/vercel/next.js/discussions/14469#discussioncomment-29741.) That's why it would be great if the `styled.View` had the same functionality as `styled.div` for media queries.

**Comment by jamesone** [comment]
Is this something that's being considered?
