### ISSUE TITLE
Custom syntax escape hatch

### ISSUE THREAD

**Issue by 0xF013** [styled-components/styled-components#2030]
Before going on, I acknowledge the fact that SC is not going to introduce any custom syntax (SASS-like or similar) and I fully support the reasoning.

Now, I was thinking that it could be a good idea to create an API that would allow people to create their own custom syntax parsers that could be enabled via a context, which would keep SC out of muddying the vision with custom syntax, while giving users the freedom of enhancing the syntax if they choose to. My idea would look like this:

```
<CustomSyntaxProvider parsers={[
  variablesParser, shorthandBreakpointsParser, etc
]}>
  <MyStyledComponent />
</CustomSyntaxProvider>
```

and then the engine could simply pass the template literal to the parser/middlewares so that they can do their filthy magic on it.

I am aware this could be done easily with a preprocessor and might incur additional checks if done otherwise, so please point these things out. I would like to get an idea if this is even worth thinking about.

**Comment by probablyup** [comment]
I think this would be a stylis plugin?

**Comment by 0xF013** [comment]
I got the impression that stylis is an implementation detail and SC is not going to expose stylis-related APIs

**Comment by kitten** [comment]
I believe this has been resolved a while ago.
