### ISSUE TITLE
Add box shadow for React Native.

### ISSUE THREAD

**Issue by narutojone1218** [styled-components/styled-components#2034]
shadowOffset:{  width: 10,  height: 10,  },
shadowColor: 'black',
shadowOpacity: 1.0

This is the solution to show shadow for React Native components

**Comment by thomasgit123** [comment]
Thanks for your solution. It worked well

**Comment by probablyup** [comment]
This isn't an issue or feature request, so going to close the ticket. If you'd like to add some docs to the react native section of the website, that'd be cool!
