### ISSUE TITLE
lib is not published since 3.4.2

### ISSUE THREAD

**Issue by sergeybekrin** [styled-components/styled-components#2039]
Hey there 👋

I couldn't find any information about deprecation of styled-component internals usage, but since v3.4.2 there's no `lib` folder available in npm artifact. I'm not aware of any other affected libraries, but at the moment [styled-email-components](https://github.com/sergeybekrin/styled-email-components) can't be used with styled-components >= 3.4.2.

Is that change was intentional? There's also `lib` listed in `package.json#files` which confuses me a little bit 😅

Cheers!

**Comment by probablyup** [comment]
We ship flat files in dist now. Your bundler should be picking them up based on the various package.json fields like "main" and "module"

**Comment by sergeybekrin** [comment]
@probablyup thanks for your quick reply! In my case flat bundles won't work since they don't expose critical internals (for example [this part](https://github.com/sergeybekrin/styled-email-components/blob/master/src/index.js#L11)). I should've explained what styled-email-components is an extension over styled-components which relies on some internals.

Do you maybe have any ideas on how to workaround it? Like introducing build step on my end?

**Comment by probablyup** [comment]
You can consume src I guess and build it yourself - that's not part of our public API so I can't see us ever making that easy to access. We also removed most of the factories in v4

**Comment by sergeybekrin** [comment]
Ah alright, I see. Will check back on stable v4 release to re-evaluate on that's possible to do. Thanks!
