### ISSUE TITLE
Create an NPM package that USES styled-components . References to the package in a project that USES styled-components will cause errors

### ISSUE THREAD

**Issue by ahz549467483** [styled-components/styled-components#2040]
`
index.js:2178 Error: Trying to insert a new style tag, but the given Node is unmounted!

* Are you using a custom target that isn't mounted?
* Does your document not have a valid head element?
* Have you accidentally removed a style tag manually?
`

**Comment by probablyup** [comment]
https://www.styled-components.com/docs/faqs#duplicated-module-in-node_modules
