### ISSUE TITLE
Discussion: className cases

### ISSUE THREAD

**Issue by vdanchenkov** [styled-components/styled-components#205]
There is some cases where you have to use className and I want to find a way to get rid of it. One of cases is dynamic styles.

Consider this example.
```jsx
const Bar = styled.div`
  width: ${props => props.percent}px; 
  color: ${props => props.color || 'red'}
`
```
It would give us 100 different rules, so we have to extract style attribute to prevent it, but how do we compose it?

One way is to **define component for styled div**.

```jsx 
const BarContainer = styled.div`color: ${props => props.color || 'red'}`
const Bar = props => <BarContainer style={{ width: props.percent }} {...props} />
```

But I found it a little unnatural. It hard to come up with a good name for BarContainer. Should we call it Wrapper, Root or maybe Element? Another inconvenience is that we have to pass props to Container. 

Let's try it **other way round**. 

```jsx
const Bar = props => <div className={props.className} style={{ width: props.percent }}/>
const StyledBar = styled(Bar)`color: ${props => props.color || 'red'}`
```

We define component first and apply styling later. Looks more natural to me, but we got that ugly className.

Maybe we can consider automatic injection of className to make following work? 

```jsx
const Bar = props => <div style={{ width: props.percent }}/>
const StyledBar = styled(Bar)`color: ${props.color || 'red'}`
```

I could made it with extra function call but using it would be not much nicer than with className. For now, it breaks syntax highlighting in atom. 

```jsx
const Bar = props => <div style={{ width: props.percent }}/>
const StyledBar = styled(classed(Bar))`color: ${props => props.color || 'red'}`
```

**Comment by vdanchenkov** [comment]
For functional components it's easy:
```jsx
export default classed = comp => props => {
  const element = comp(props)
  if (props.className && !element.props.className) {
    return React.cloneElement(element, { className: props.className })
  }
  return element
}
```

For component classes it would require mangling with DOM and refs, so I would not support it.

**Comment by mxstbr** [comment]
> It would give us 100 different rules, so we have to extract style attribute to prevent it, but how do we compose it?

I think this assumption isn't true. Why do you want to prevent having different rules? What's the downside?

**Comment by vdanchenkov** [comment]
@mxstbr Main downside here is that rules are generated dynamically as percent values goes from 0 to 100 and it's slowdowns animation.

**Comment by mxstbr** [comment]
Ah yeah, you shouldn't do animation with dynamic values, that can only be slow. Use CSS keyframes instead! Closing favor of #134 where there is an discussion ongoing about this.

**Comment by vdanchenkov** [comment]
@mxstbr dynamic styles are not the point of discussion. Just an example. There is another reasons to use className and I wanted to to discuss the solution. I will put here another examples if I face some.
