### ISSUE TITLE
Unpredictable rendering using wildcard child selectors

### ISSUE THREAD

**Issue by dirtyhenry** [styled-components/styled-components#2050]
## System:
 - OS: macOS High Sierra 10.13.6
 - CPU: x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
 - Memory: 594.69 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 8.11.1 - ~/.nvm/versions/node/v8.11.1/bin/node
 - Yarn: 1.9.4 - /usr/local/bin/yarn
 - npm: 6.4.1 - ~/Developer/Projects/Margo/Code/webapp-components/node_modules/.bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^3.4.2 => 3.4.9 

## Reproduction

Reproduction attempt here: https://codesandbox.io/s/vjn52p1xry

## Steps to reproduce

I met a bug where commenting in/out an unused import would change the behavior of my components (Cf. the comment in the `ButtonsRow.js` file in the sandbox):

* Commenting out `import Button from "./Button";` would render buttons with no margin (cf. Actual Behavior screenshot below).
* Bringing back `import Button from "./Button";` would render buttons with some margin (cf. Expected Behavior screenshot below).

I was able to reproduce the bug very briefly in the sandbox. But after commenting in and then out again, the end result changed and the bug wasn't reproduced anymore. 
(For what it's worth, I feel like the origin of the bug is that the CSS rules order can change based on build state rather than file state but I have no idea if that intuition is relevant or not.)

The bug came from switching from a predictable behavior using 

## Expected Behavior

![screen shot 2018-10-02 at 11 16 41](https://user-images.githubusercontent.com/456506/46340060-aa25c080-c634-11e8-9a89-974cfb1ca107.png)

## Actual Behavior

![screen shot 2018-10-02 at 11 17 14](https://user-images.githubusercontent.com/456506/46340096-bf9aea80-c634-11e8-9c78-47a071bdc16f.png)

**Comment by dirtyhenry** [comment]
Update, this is the screenshot of my rendering (left screen) and my colleague's (right screen) after submitting the bug: 

![img_2446](https://user-images.githubusercontent.com/456506/46340917-29b48f00-c637-11e8-8e34-ccf63d112449.JPG)

Same code, different renderings :/

**Comment by probablyup** [comment]
Yeah I'm a bit confused by this myself

**Comment by 0xF013** [comment]
It's reproducing consistently for me in the sandbox, and the reason seems to consist of the fact that importing the button sets the margin: 0, and after then the rule for `> * + *` is included as the last `<style>` elements, so the margin-left is applied. If you comment the button, then this owl rule is applied first and in a later `<style>` definition the margin is set to 0. I've experienced something similar previously and it's just a mess of cascading and priority rules (something which SC was designed specifically to combat). I avoided it by iterating over the children of a similar ButtonsRow and wrapping them in a ButtonsRowChild component that I was able to specifically target.

**Comment by probablyup** [comment]
Alrighty this is a simple case of selector precedence. https://codesandbox.io/s/yp9rn7r94v

Basically * + * is lower precedence than a single .class selector, so you need to wrap your `> * + *` in a [precedence boost](https://www.styled-components.com/docs/basics#pseudoelements-pseudoselectors-and-nesting) so it takes effect over the individual button styles. See the linked sandbox above for a practical example.

**Comment by dirtyhenry** [comment]
Thanks @probablyup! `&&` did the trick and I wasn't aware of that feature.
