### ISSUE TITLE
Passing children in attrs works on web but not native

### ISSUE THREAD

**Issue by williamfeng91** [styled-components/styled-components#2051]
## System:
 - OS: macOS Sierra 10.12.6
 - CPU: x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
 - Memory: 279.81 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
 - Yarn: 1.9.4 - /usr/local/bin/yarn
 - npm: 6.4.1 - ~/.nvm/versions/node/v8.11.3/bin/npm
 - Watchman: 4.7.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^3.4.9 => 3.4.9 

## Reproduction

https://snack.expo.io/@williamf/styled-components-bug-reproduction

## Steps to reproduce
```javascript
const StyledText = styled.Text.attrs({
  children: 'Hello World'
});
const App = () => <StyledText />;
```
"Hello World" is not rendered.

## Expected Behavior
According to #820, `children` should get passed down just like other props and this is the behaviour on web. I expect that it behaves the same on React Native.

## Actual Behavior
Value of `children` is ignored and the underlying component receives `undefined`.

**Comment by probablyup** [comment]
Anyone have an idea why? We aren't doing any explicit filtering... the only thing I can think of is in the merge order `...this.attrs` comes before `...props` meaning props always take precedence over attrs.

**Comment by williamfeng91** [comment]
> Anyone have an idea why? We aren't doing any explicit filtering... the only thing I can think of is in the merge order `...this.attrs` comes before `...props` meaning props always take precedence over attrs.
> 
> But that seems to be the same in web too.

The third argument of `React.createElement` overrides property `children` in the second argument. You can see how [StyledNativeComponent.js](https://github.com/styled-components/styled-components/blob/6bb4822d42ae8e049e82bb9650d2aed3c1102969/src/models/StyledNativeComponent.js#L130) and [StyledComponent.js](https://github.com/styled-components/styled-components/blob/6bb4822d42ae8e049e82bb9650d2aed3c1102969/src/models/StyledComponent.js#L167) are different.

Would you like me to send a PR?

**Comment by probablyup** [comment]
Sure please, feel free to add to your existing PR and change the base branch to devleop

**Comment by williamfeng91** [comment]
> Sure please, feel free to add to your existing PR and change the base branch to develop

Looks like there is a merge conflict after I changed the base branch. Would I be better off creating a new PR?

**Comment by mxstbr** [comment]
> Would I be better off creating a new PR?

Yes that'd be great :pray:

**Comment by williamfeng91** [comment]
Closing as this has actually been fixed in the develop branch. Thanks for that. Looking forward to v4!

I have updated my pull request to just add some tests. You can decide whether you want to merge.
