### ISSUE TITLE
[v4.0.0-beta.9] 'as' prop has no effect if supplied in attrs.

### ISSUE THREAD

**Issue by Undistraction** [styled-components/styled-components#2054]
## Environment

```
## System:
 - OS: macOS High Sierra 10.13.6
 - CPU: x64 Intel(R) Core(TM) i5-5575R CPU @ 2.80GHz
 - Memory: 464.35 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
 - Yarn: 1.9.4 - /usr/local/bin/yarn
 - npm: 6.4.1 - ~/Sites/sleepstation-components/node_modules/.bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.8.0 => 1.8.0
 - styled-components: 4.0.0-beta.9 => 4.0.0-beta.9
```

## Reproduction

Note that the first `Extended` element is not rendered as a `header`, but as a `div`.

```javascript
const container = document.querySelector('.container')

const Base = styled.div`
  height: 100px;
  background: red;
`

const Extended = styled(Base).attrs({as: 'header'})`
  background: blue;
`

ReactDOM.render(<div>
    <Base />
    <Extended />
    <Extended as="header"/>
  </div>, container)
```

Only the second component is rendered as a header. 

Simple [Codepen](https://codepen.io/Pedr/pen/bmEORO?editors=1111).

## Expected Behavior

When `as` is supplied to an extended component using the extending component's `attrs` the component should be rendered using the supplied element.

## Actual Behavior

The element supplied by `as` is ignored and the original element defined using `styled` is rendered.

**Comment by imbhargav5** [comment]
Fixed with #2055. Thanks @Undistraction !!
