### ISSUE TITLE
styled-components className not randomly generated when styling 3rd party library

### ISSUE THREAD

**Issue by wang3324** [styled-components/styled-components#2056]
Hi I am having an issue when styling 3rd party dependency library component `for example: styled(Loading)`. The Loading comes from a 3rd party lib where it contains a collection of all defined CSS styles which is NOT a class, does NOT have DOM node or any return. So I can not pass className props into the DOM
The **issue** is:  when i run the new version below, it won't recognize my styled-component because styled-components random className is not being generated based on browser Inspect. Instead, the browser Inspect shows the original 3rd lib class name! Can anyone tell me what i need to fix with this issue? Thank you!

/*version:  styled-components@3.4.4*/
### this is how i added styled-component, but the style is not recognized 
import { Loading } from 'customizedstyle-react';

 const StyledLoading = styled(Loading)
      position: absolute !important;
      z-index: 9999 !important;
;
render(){
    return { 
                    `<StyledLoading  kind="dot" visible={true}/>`
    }
}
(leave alone the missing `` in styled-component)
### this is what it is originally looks like and it worked well with the style in div 
import { Loading } from 'customizedstyle-react';
render(){
    return {
            <Loading kind="dot" visible={true} style={{position:'absolute', zIndex: '9999'}}/>
   }
}

**Comment by wang3324** [comment]
<img width="785" alt="screen shot 2018-10-03 at 11 09 27 pm" src="https://user-images.githubusercontent.com/27749214/46450856-73999400-c761-11e8-8e2a-4cdbf35919c3.png">
you can see that instead of returning a random className like other classes above, it just returned the original className and render their original css style, which is not a desired outcome

**Comment by probablyup** [comment]
It'd be helpful to know what library you're referring to. In general when you wrap a custom component with `styled()` it must handle the `className` prop that is injected or styling won't be applied. My guess is the library is ignoring the `className` we give it and just does its own, which is why you aren't seeing your styles.

**Comment by wang3324** [comment]
@probablyup thanks for your reply, i understand that the third-party library has to pass this.props.className to className. But my library is just a list of CSS class selectors. i can not get access to the library and modify their code. Is there any way to solve the issue with the current code?

**Comment by probablyup** [comment]
If you can't modify their code, all you can do is make your own wrapper around theirs that handles className and you'll end up with 2 components instead of one. But it would be better just to make a PR for their library and fix it

**Comment by wang3324** [comment]
@probablyup i couldn't get the 2 components way, could you show me how to do it? thanks!!

**Comment by probablyup** [comment]
```jsx
// <Thing> is the original component that doesn't accept className

const StyledThing = styled(({ className, ...props}) => <div className={className}><Thing {...props} /></div>)`
    color: blue;
`;
```

I really don't recommend doing that and just fixing the issue at the source, but it should work.

**Comment by wang3324** [comment]
@probablyup thanks for your help! i tried, it still doesn't work though, maybe i shouldn't add styled component for it. But what is so weird my ORIGINAL method works for other components(Button) that comes from the same library.

### it worked for this component!!!!! but when i remove the !important, it doesn't work as usual
const StyledButton = styled(Button)
color: blue !important;

do you have idea why in this case it worked, maybe got luck?:)

**Comment by wang3324** [comment]
@probablyup you are right, i am going to raise a ticket to library. Appreciate your help, Evan!
