### ISSUE TITLE
 Error when using `4.0.0-beta.9` in test environment: Enzyme Internal Error: unknown node with tag 14 

### ISSUE THREAD

**Issue by yoloOnTheBattlefield** [styled-components/styled-components#2058]
## System:
 - OS: Linux 4.15 Ubuntu 16.04.5 LTS (Xenial Xerus)
 - CPU: x64 Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz
 - Memory: 13.21 GB / 31.35 GB
 - Container: Yes
 - Shell: 4.3.48 - /bin/bash
## Binaries:
 - Node: 10.8.0 - /usr/bin/node
 - Yarn: 1.9.2 - /usr/bin/yarn
 - npm: 6.2.0 - /usr/bin/npm
## npmPackages:
 - styled-components: ^4.0.0-beta.9
## Steps to reproduce

I have needed the latest version of styled-components so I can make use of the refs, to reload a styled video at certain moments. When I tried to mount the container component which would eventually sub-render this video component, enzyme `^3.6.0`, would throw the following error ` Enzyme Internal Error: unknown node with tag 14 `.  I then reverted to styled-components `^2.4.0` and added inline styles to a regular video tag  and the error disappeared. 

## Expected Behaviour

Enzyme should not throw any errors.

## Actual Behavior

Throws because of the ref feature

**Comment by probablyup** [comment]
You need to upgrade your enzyme adapter setup to match the React version
being used. v4 requires React 16.3+

**Comment by yoloOnTheBattlefield** [comment]
This is my react version: `^16.4.1`.

**Comment by probablyup** [comment]
Yes and your enzyme setup needs to be upgraded to match it since the adapters are only aware of specific react versions. You also have to use enzyme v3 with React 16+
