### ISSUE TITLE
`createGlobalStyle` is not exported from typings

### ISSUE THREAD

**Issue by azer** [styled-components/styled-components#2059]
## Environment

TypeScript 3.11 
Style-components 3.4.9
Node 10.4.1

## Reproduction

Import `createGlobalStyle` from a TypeScript file;

```
import { createGlobalStyle } from "styled-components"
```

It'll cause following error: 

```
'styled-components' does not contain an export named 'createGlobalStyle'.
```

**Comment by probablyup** [comment]
It’s a v4 api...

**Comment by azer** [comment]
Sorry, I'm closing the issue then.
