### ISSUE TITLE
Media queries don't work on react-native-web components

### ISSUE THREAD

**Issue by tychovbh** [styled-components/styled-components#2061]
Hi I'm developing an app and website in the same project and sharing almost a 100% code. I'd like to use styled components for style, but it doesn't allow me to use media queries on react native components on web why is that?

I'm developing mobile first so I don't actually need de queries for the react native app. And since react-native-web converts a View into a Div I see no reasons why my media queries don't apply.

Example:
```js
const Content = styled.View`
  background: papayawhip;
  height: 3em;
  width: 3em;

  @media (min-width: 700px) {
    background: palevioletred;
  }
`;
```
In react native i expect this to just ignore the media query but on web it should put the media query on the div.

Is this possible?

**Comment by probablyup** [comment]
React Native has no concept of media queries and we use the RN version of styled-components in this case, so yeah it just wouldn't work. Other stylesheet targets have been proposed though to improve the situation if you're interested in joining the conversation: https://github.com/styled-components/styled-components/issues/1874

**Comment by necolas** [comment]
@tychovbh media queries don't make sense in React Native's strict component model. Instead, you can essentially do "element queries" by using the `onLayout` prop to respond to changes in your component's dimensions, or listen to window size changes using the `Dimensions` API. This is how all the responsive design is accomplished in Twitter's PWA

**Comment by pavilion** [comment]
@necolas is this still the case? Are you still relying on `onLayout` and `Dimensions` to get responsiveness in both mobile and web platforms? Thanks.
