### ISSUE TITLE
[RN] Property 'View' does not exist on type 'ThemedBaseStyledInterface<any>'

### ISSUE THREAD

**Issue by jgfidelis** [styled-components/styled-components#2063]
This may be more of a usage question.

I am using TS `3.0.1`

I tried using version `3.4.9` and now I am trying with version `4.0.0-beta.10`. I have `@types/styled-components` v `3.0.1`

If I try to do `const A = styled.View` I get the error:
`Property 'View' does not exist on type 'ThemedBaseStyledInterface<any>'. Did you mean 'view'`

Am I missing something?

**Comment by probablyup** [comment]
File it against DefinitelyTyped please
