### ISSUE TITLE
react-script 2 + styled-components + styled-theme not working

### ISSUE THREAD

**Issue by RN-able** [styled-components/styled-components#2065]
I just update react-script to latest version after every styles are gone.
how can i fix this ?

**Comment by kitten** [comment]
Please don't just delete the issue template and provide a proper description of what's going on, with a reproduction if possible, to the best of your ability please :) https://raw.githubusercontent.com/styled-components/styled-components/master/.github/ISSUE_TEMPLATE.md

It's hard to keep up with issues and questions if we were to investigate all issues without any leads to go after immediately, so we need some more details unfortunately

**Comment by probablyup** [comment]
Yeah we really can't help you without a lot more information and ideally a reproduction case, sorry. Feel free to reopen if you can get those things.

**Comment by RN-able** [comment]
Hey 
sorry for the late.
i just update react-script and all styles are gone.
i'm not sure what happened looks like issue comes with styled-components
tell me what details you need then i can provide it.

thanks.
