### ISSUE TITLE
Missing Reference to `StyledComponent` in 4.10

### ISSUE THREAD

**Issue by aretecode** [styled-components/styled-components#2067]
https://github.com/styled-components/styled-components/blob/v4.0.0-beta.10/src/models/StyledComponent.js#L182

**Comment by probablyup** [comment]
If you're not going to use the issue template and give us a proper issue that we can look into and be helpful, don't bother opening one.

**Comment by aretecode** [comment]
@probablyup 
<img width="1053" alt="screen shot 2018-10-05 at 8 51 06 pm" src="https://user-images.githubusercontent.com/4022631/46544149-71aa0f00-c8e0-11e8-8af1-d3e4132b424c.png">

**Comment by probablyup** [comment]
What project is this? It works correctly in the main library.
