### ISSUE TITLE
create-react-app v2.0.4 // styled(MyComponent) yields error 1

### ISSUE THREAD

**Issue by sebastienfi** [styled-components/styled-components#2068]
## System:
 - OS: Windows 10
 - CPU: x64 Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz
 - Memory: 7.03 GB / 15.95 GB
## Binaries:
 - Yarn: 1.7.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
 - npm: 6.0.1 - C:\Program Files\nodejs\npm.CMD

![image](https://user-images.githubusercontent.com/5808108/46551644-900c0c80-c8d8-11e8-9b82-b0edd5f3b73d.png)

I am trying to migrate from `create-react-app@1.1.5` to `create-react-app@2.0.4`.
`styled-components@latest` works like a charm <3 in our CRA v1 setup, but breaks on CRA v2.
It only breaks on `yarn run build && yarn run serve` but `yarn run start` is perfectly fine.
The error imessage links to a component that was working perfectly fine prior to this upgrade.
```js
const ThumbnailImage = styled(MyImageComponent)`
  max-width: 100%;
  max-height: 100%;
  height: auto;
  width: 100%;
`
```
`MyImageComponent` is a function which execute some logic and return a React component.

Anybody running `create-react-app@2.0.4` and `styled-components@latest` having issues with the `styled()` function? Any idea what may be the issue here?

It seems that `MyImageComponent` is [not a valid tag](https://github.com/facebook/react/tree/master/packages/react-is#usage). But why?
![image](https://user-images.githubusercontent.com/5808108/46551721-c8134f80-c8d8-11e8-9fbb-1c7d3813e3da.png)

**Comment by probablyup** [comment]
Great question for the React repo. As you can see it’s a React core
dependency we consume, so there’s probably nothing to be done on our end.

**Comment by sebastienfi** [comment]
Thanks @probablyup
