### ISSUE TITLE
Supply css class to 3rd party lib without using the name "className"

### ISSUE THREAD

**Issue by vensa-albertgao** [styled-components/styled-components#2076]
#### System:
 - OS: macOS High Sierra 10.13.6
 - CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
 - Memory: 167.45 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
#### Binaries:
 - Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
 - Yarn: 1.10.1 - ~/.nvm/versions/node/v8.11.3/bin/yarn
 - npm: 6.4.1 - ~/.nvm/versions/node/v8.11.3/bin/npm
#### npmPackages:
 - styled-components: ^3.4.9 => 3.4.9

## Preparation
Create an app with `create-react-app`,

Change the App.js to this:
```javascript
import React, { Component } from "react";
import "./App.css";
import styled from "styled-components";

const MyPart = ({ pClassName }) => (
  <p className={pClassName}>this is the P tag</p>
);

const StyledMyPart = styled(MyPart).attrs({
  pClassName: "for-p-tag"
})`
  &.for-p-tag {
    font-size: 60px;
  }
`;

class App extends Component {
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <StyledMyPart />
        </header>
      </div>
    );
  }
}

export default App;
```

## Steps to reproduce
1. Run the app, expect the P tag to be displayed as 60px, but it's not.
2. Change the code to this:
```javascript
const MyPart = ({ className }) => (
  <p className={className}>this is the P tag</p>
);

const StyledMyPart = styled(MyPart).attrs({
  className: "for-p-tag"
})`
  &.for-p-tag {
    font-size: 601px;
  }
`;
```
3. Run the app, now it works.

## What is the problem
How to make the styling work when the `prop` name is not `className`?

## About it
Asked this previously on Stackoverflow.com without any luck. https://stackoverflow.com/questions/52378924/use-styled-components-to-supply-a-css-class/52441187#52441187

If the name of the `prop` is not `className`, it won't work.

Don't know if I did anything wrong, but I tried many ways.
Is this just not supported or I miss something? Thanks.

**Comment by probablyup** [comment]
Why can't you use `className`? We're generating CSS classes, so that prop must be used and attached. If you need to compose multiple classNames (ours and yours), you can use a helper library like https://github.com/JedWatson/classnames to make it easier.

**Comment by Albert-Gao** [comment]
Because the third party lib requires two separate props for handling two different parts of styles. Composing won’t help here because it won’t work as different classNames will apply to different parts of the DOM. 

So styled component doesn’t support this use case?

**Comment by probablyup** [comment]
This is what I meant: https://codesandbox.io/s/r7x338zp5n, joining your custom className with the one that styled-components generates.

**Comment by Albert-Gao** [comment]
Ah, I see! thanks!! :)

What about that `MyPart` belongs to a 3rd party lib where I can't access its code? Any way to pass the whole generated styled component class names (`className+pClassName`) to that `MyPart` with the help of `.attrs()`?

```javascript
const MyPart = ({ className, pClassName }) => (
  <p className={classnames(className, pClassName)}>this is the P tag</p>
);
```

**Comment by probablyup** [comment]
Updated the sandbox to illustrate: https://codesandbox.io/s/r7x338zp5n

If you do `className` in attrs, it'll be space-concatenated with the one styled-components generates. It's up to the third party library to accept className from outside though and put it on the child JSX.

**Comment by Albert-Gao** [comment]
I see. Thanks for your time. 

Which means I still have to mix up css modules along with styled components...

Styled components sits in the middle, why can't we just generate a class name and pass it to the `styled(MyPart)` as a prop. Oh pass it first, then generate it later.

**Comment by probablyup** [comment]
> why can't we just generate a class name and pass it to the styled(MyPart) as a prop

You can. styled components accept the className prop just fine, it's up to the underlying component to do something with it

**Comment by probablyup** [comment]
css modules still assigns to className, so you'd have the same issue

**Comment by Albert-Gao** [comment]
The following code works without problem:

```javascript
import DatePicker from 'react-datepicker'
import styles from './custom.css'

<DatePicker
  calendarClassName={styles.calendar}
/>
```

But if I change to this, it won't work:

```javascript
const StyledDatePicker = styled(DatePicker)`
    .my-calendar {
        color: black;
    }
`;

<StyledDatePicker
   calendarClassName="my-calendar"
/>
```

Or this won't work either:

```javascript
const StyledDatePicker = styled(DatePicker).attrs({
    calendarClassName: 'my-calendar'
})`
    .my-calendar {
        color: black;
    }
`;

<StyledDatePicker />
```

**Comment by probablyup** [comment]
Oh I see. You could use something like recompose to rename the prop as needed: https://github.com/acdlite/recompose/blob/master/docs/API.md#renameprop

**Comment by Albert-Gao** [comment]
Thanks, but that's tricky...
Because it uses `className` as a `prop` as well.

Which means, you need to use it like this:

```javascript
<DatePicker
   className="my-date-picker"
   calendarClassName="my-calendar"
/>
```

:(

**Comment by joewood** [comment]
I'm not sure why your above example doesn't work:
```javascript
const StyledDatePicker = styled(DatePicker)`
    .my-calendar {
        color: black;
    }
`;

<StyledDatePicker
   calendarClassName="my-calendar"
/>
```

The same approach works in this trivial example: https://codesandbox.io/s/q3zp4v70m9. You should be able to default the prop too, to make it simpler:

```javascript
const StyledDatePicker = styled(DatePicker).attrs({
    calendarClassName:"my-calendar"
})`{
    color:blue;
   }
    .my-calendar {
        color: black;
    }`;

<StyledDatePicker/>
```

**Comment by trkaplan** [comment]
> Thanks, but that's tricky...
> Because it uses `className` as a `prop` as well.
> 
> Which means, you need to use it like this:
> 
> ```js
> <DatePicker
>    className="my-date-picker"
>    calendarClassName="my-calendar"
> />
> ```
> 
> I want to use styled components to cover them all rather than wrap the `className` and use traditional css class name for the `calendarClassName` prop.
> 
> Any way to do that?
> 
> :(


> I'm not sure why your above example doesn't work:
> 
> ```js
> const StyledDatePicker = styled(DatePicker)`
>     .my-calendar {
>         color: black;
>     }
> `;
> 
> <StyledDatePicker
>    calendarClassName="my-calendar"
> />
> ```
> 
> The same approach works in this trivial example: https://codesandbox.io/s/q3zp4v70m9. You should be able to default the prop too, to make it simpler:
> 
> ```js
> const StyledDatePicker = styled(DatePicker).attrs({
>     calendarClassName:"my-calendar"
> })`{
>     color:blue;
>    }
>     .my-calendar {
>         color: black;
>     }`;
> 
> <StyledDatePicker/>
> ```

It does not work, because the component he used does not pass `className` prop to itself.
Same issue with the AntD Drawer component was fixed with this commit: https://github.com/ant-design/ant-design/commit/5cac2fab4a9f983652400ef0d0295d0b720821b3#diff-d2d31bc4ab00ef3c51a9f276b306fd9aL196

**Comment by naorye** [comment]
Is this fixed? I am using react-bootstrap and barely can integrate styled-components wince class names are not appended.

**Comment by rmolinamir** [comment]
Also happens with the Popover component :(

**Comment by georgekpc** [comment]
It doesn't work with libraries that don't use the className prop.
When I tried what is proposed above (the use of `attrs` method), it attaches the class but for some reason the css code you write for the class you just added, is not applied. So I ended up using CSS modules for those cases.

**Comment by Assem-Hafez** [comment]
@georgekpc This is because (the `attrs` method) requires that `className` should be wrapping the other elements in the library component. this is because the created selector is `.className .my-calendar`

**Comment by georgekpc** [comment]
@Assem-Hafez inspecting this element with chrome debugger I can see that .className and .my-calendar are applied to the same element which means an example like above should have worked

`const StyledDatePicker = styled(DatePicker).attrs({
    calendarClassName:"my-calendar"
})`
    &.my-calendar {
        color: black;
    }`;`

However it doesn't
