### ISSUE TITLE
Unable to refer to styled child within function

### ISSUE THREAD

**Issue by ZeeStorm** [styled-components/styled-components#2077]
## System:
 - OS: macOS High Sierra 10.13.6
 - CPU: x64 Intel(R) Core(TM) i5-2500S CPU @ 2.70GHz
 - Memory: 5.02 GB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 10.8.0 - ~/.nvm/versions/node/v10.8.0/bin/node
 - npm: 6.2.0 - ~/.nvm/versions/node/v10.8.0/bin/npm
## npmPackages:
 - @types/styled-components: ^3.0.1 => 3.0.1 
 - styled-components: ^3.4.9 => 3.4.9

## Reproduction
https://codesandbox.io/s/lyq7k4851l

## Steps to reproduce
Follow reproduction:
1. Create parent + child styled divs
2. Parent adds prop that effects child and refer to child component via `& ${child} {` (representing a typical `.parent .child` selector)

## Expected Behavior
CSS should properly have child styles when parent props match
In the codesandbox, both top and bottom boxes should be blue, while the top inner box should stay red, the bottom inner box should turn grey.

## Actual Behavior
Child javascript is outputted:
```
.dEEwGx function StyledComponent(){classCallCheck(this,StyledComponent);return:possibleConstructorReturn(this,_ParentComponent.apply(this,arguments));} .dEEwGx{background:#ccc;}
```

Parent class is also referenced twice (from the specified & and inherited after child; not allowing a proper `.parent-class .child-class`) --  see `.dEEwGx` in above example

**Comment by probablyup** [comment]
You need to use the [`css` helper](https://www.styled-components.com/docs/api#css) if you're interpolating complex values like other components or functions.

Revised sandbox: https://codesandbox.io/s/4qkklrzxo4
