### ISSUE TITLE
If I use styled-components and also PostCSS autoprefixer plugin in webpack, the same vendor prefixes are added twice?

### ISSUE THREAD

**Issue by kidmysoul** [styled-components/styled-components#2078]
if I use styled-components and also PostCSS autoprefixer plugin in webpack, 
I'm not sure if the same vendor prefixes are added twice

I think it is NOT , right?

And does it mean that it's unnecessary to use PostCSS autoprefixer if I use  styled-components in react ? 

thank you

**Comment by probablyup** [comment]
It's not necessary to use a prefixer with styled-components because the compiler adds them at runtime.

**Comment by fabb** [comment]
Runtime or compile time?

Autoprefixer/postcss use browserslist, so we can configure which browsers we want to target, and which prefixes should be generated at compile time.

When styled components does it at run time, it‘s even better, as it would only create the prefixes needed for the current user agent i suppose.

Autoprefixer has a really cool feature that supports [grid autoplacement for IE11](https://github.com/postcss/autoprefixer/blob/master/README.md#grid-autoplacement-support-in-ie) which we currently rely on (yet without SC). When migrating to SC, do we need to connect postcss with it somehow, or does it support something like this natively?

**Comment by polarathene** [comment]
> When styled components does it at run time, it‘s even better, as it would only create the prefixes needed for the current user agent i suppose.

It's apparently weighty to bring to client-side

> *Including browserlist-useragent in the webpack's bundle adds 400kb gzipped and almost 3mb unzipped. It is definitely not thinked to be executed client side.* - [Source](https://github.com/browserslist/browserslist-useragent/issues/9#issuecomment-396677458)

Although someone else says it's much less than that:

> *Apologies for the late response. I don't know if it makes sense to make the library working for browsers because the way that the detection is done is not really suitable for web. It requires you to download a regular expression file that is a whooping 200kb.* - [Source](https://github.com/3rd-Eden/useragent/pull/117#issuecomment-414295994)

It would be nice though if you could provide a browserlist config at build time with webpack to only provide prefixes for browsers you're interested in, and split those by browser which should help reduce the size. If it could be swapped for prefix config that `stylis` currently uses that'd be neat.

I personally need to blacklist a prefix for Firefox as it doesn't work as it should but will override any fallback, thus even though other browsers can use it, I can't as it'd completely break the layout for anyone on Firefox :cry:
