### ISSUE TITLE
Add prop to createGlobalStyle created-component to allow multiple mounts / disable multi-mount warning

### ISSUE THREAD

**Issue by mkralla11** [styled-components/styled-components#2082]
The new function createGlobalStyle is awesome, and I recognize that mounting/unmounting/mounting multiple times *could* be in issue for some people (hence why I understand the warning in development), but I would like to propose a way to suppress the warning on a per-component basis.

A simple example use case where it *doesn't matter* if we mount/unmount/mount is when we are specifically adjusting **font-face** declarations (which need to be at the outer scope of a stylesheet).

The public api could be something simple like (disregard lack of proper sanitization, this is just an example):

```
  const GlobalFontStyler = createGlobalStyle`
    ${({fontFaceRelatedStuff})=> fontFaceRelatedStuff}
  `


<GlobalFontStyler 
  suppressMultiMountWarnings={true}
  fontFaceRelatedStuff={this.props.fontFaceRelatedStuff}
/>

```

## npmPackages:
 - babel-plugin-styled-components: ^1.3.0 => 1.3.0 
 - styled-components: 4.0.0-beta.10 => 4.0.0-beta.10 

## Steps to reproduce

1. create a component with createGlobalStyle
2. mount, unmount, mount again

## Actual Behavior

createGlobalStyle behaves properly, but warns in development regarding mounting multiple times, which is unnecessary/not-beneficial in some cases.

**Comment by mkralla11** [comment]
Excellent! I will get on this. 👍

**Comment by probablyup** [comment]
Against master now if you choose to do it now that v4 final is out
