### ISSUE TITLE
styled.input does not pass on autocorrect and autocapitalize attributes

### ISSUE THREAD

**Issue by bjornicus** [styled-components/styled-components#2086]
## System:
 - OS: macOS High Sierra 10.13.6
 - CPU: x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
 - Memory: 92.07 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 10.7.0 - /usr/local/bin/node
 - Yarn: 1.7.0 - /usr/local/bin/yarn
 - npm: 6.1.0 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^3.3.3 => 3.4.5 

## Reproduction
define a styled input
```
const Input = styled.input``;
```
and then render:
```
    <div>
      <input type="text" autocorrect="off" autocapitalize="none" />
      <Input type="text" autocorrect="off" autocapitalize="none" />
    </div>
```
which produces the following markup:
```
<div>
  <input type="text" autocorrect="off" autocapitalize="none">
  <input class="sc-ejGVNB fcSSwx" type="text">
</div>
```

## Expected Behavior
both inputs should render the same markup
## Actual Behavior
the styled one is missing the expected attributes.

**Comment by probablyup** [comment]
It's actually `autoCorrect` and `autoCapitalize` per React's convention: https://react-cn.github.io/react/docs/tags-and-attributes.html#html-attributes

**Comment by bjornicus** [comment]
yep, I just discovered that after I posted this and noticed the warning in the console from react.  Using the react casing does work for both.
