### ISSUE TITLE
How to isolate or namespace third party library styles in one app?

### ISSUE THREAD

**Issue by agile116** [styled-components/styled-components#2087]
Hi All,

We have a project which contains two apps in one page, one is for navigation which can be plugged to many other apps. Currently the navigation app is using styled components, but both apps may use the same third party libraries, such as react-bootstrap which may be in different version. Styled components can make self created components to be isolated from overriding or override other apps, but third party styles can't. My question is that is there a way to isolate or add namespace third party libraries' style to the navigation app only? Thanks.

**Comment by probablyup** [comment]
Hi there - please post usage questions in a help forum like StackOverflow or our [Spectrum community](https://spectrum.chat/styled-components). This issue tracker is only meant for bug reports and feature requests.
