### ISSUE TITLE
Not working with typescript and SSR

### ISSUE THREAD

**Issue by iammarkps** [styled-components/styled-components#2090]
## System:
 - OS: macOS 10.14
 - CPU: x64 Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz
 - Memory: 86.66 MB / 8.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 10.11.0 - /usr/local/bin/node
 - Yarn: 1.10.1 - /usr/local/bin/yarn
 - npm: 6.4.1 - /usr/local/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.8.0 => 1.8.0 
 - styled-components: ^3.4.10 => 3.4.10 

## Reproduction
Simply clone NextJS with-styled-components example and setup typescript.

## Steps to reproduce

1. Clone NextJS with-styled-components example
2. Install their dependencies
3. Setup typescript

## Expected Behavior
It does not show any error in editor.

## Actual Behavior
<img width="1280" alt="screenshot 2018-10-11 18 42 11" src="https://user-images.githubusercontent.com/12445326/46805943-84b15900-cd90-11e8-80fe-fc6e80b08412.png">

**Comment by iammarkps** [comment]
@probablyup Sorry to bother you, but what actually is v4?

**Comment by mxstbr** [comment]
styled-components version four, see https://medium.com/styled-components/announcing-styled-components-v4-better-faster-stronger-3fe1aba1a112

**Comment by iammarkps** [comment]
@mxstbr 
❯ yarn add @types/styled-components@^4
zsh: no matches found: @types/styled-components@^4

**Comment by probablyup** [comment]
https://www.npmjs.com/package/@types/styled-components/v/4.0.0 🤷‍♂️

**Comment by iammarkps** [comment]
@probablyup Still no luck

**Comment by msokk** [comment]
@iammarkps your zsh shell is configured use caret ^ as glob matching parameter, so it never runs yarn add command, escape caret `\^`. Also 4.0.1 is tagged as latest, so specifing `@^4` is not needed.

**Comment by Lavoaster** [comment]
It's not a typing issue for `styled-components`. You aren't passing any types to the document of how the props are shaped, and the Next.JS doesn't infer prop types from `getInitialProps`.

E.G

```
...

interface MyClassProps {
    styleTags: string;
}

export default MyClass extends Document<MyClassProps> {
...
```

**Comment by iammarkps** [comment]
@Lavoaster You save my day thx!
