### ISSUE TITLE
TextInput color crash on RN Android

### ISSUE THREAD

**Issue by jgfidelis** [styled-components/styled-components#2091]
Bug with `styled-components@3.4.9`, `react-native@0.57.1` and `react@16.5.0`.
This component:
```
const Input = styled.TextInput`
  font-size: 14;
  letter-spacing: -0.5;
  font-weight: bold;
  background-color: transparent;
  color: ${props => props.color};
  height: 40;
  padding-horizontal: 0;
  text-align: ${props => props.align};
  font-family: OpenSans;
  margin-top: 20;
`;
```

when rendering with  this code:
`return <Input testID={testID} editable={editable} {...inputProps} color={'#242424'} innerRef={this.handleInputRef} />;`

Crashes with error: 
<img width="367" alt="screen shot 2018-10-11 at 17 33 16" src="https://user-images.githubusercontent.com/4925068/46832725-2b8bfa00-cd7d-11e8-90df-9cd7d8510a44.png">

When using this code:
```
return <Input testID={testID} editable={editable} {...inputProps} style={{ color: '#242424' }} innerRef={this.handleInputRef} />;
```

It works fine (removing `color: ${props => props.color};` from the component above).

**Comment by probablyup** [comment]
We've been seeing a LOT of issues with RN 0.57, many from in RN core itself. I think it's just a really buggy release and recommend sticking with 0.56 for the moment which seems to be working fine.

**Comment by probablyup** [comment]
That being said, if you could supply a reproduction repo I could try and investigate

**Comment by jgfidelis** [comment]
Thanks for the comments, I will see if I can provide one.

**Comment by majorb22** [comment]
I am experiencing the same problem with version 0.59.10.
Has anyone got a solution?
