### ISSUE TITLE
V4 media queries prioritized higher than extended styles

### ISSUE THREAD

**Issue by ksabry** [styled-components/styled-components#2095]
In v4, `MoreStyles` in this code will have a background-color of red or green, instead of the expected blue

```javascript
const Styles = styled.div`
  @media (min-width: 1000px) {
    background-color: red;
  }
  @media (max-width: 1000px) {
    background-color: green;
  }
`;

const MoreStyles = styled(Styles)`
  background-color: blue;
`;

```

V4 version with unexpected behavior: https://codesandbox.io/s/vq6k94rpz0
V3 version with expected behavior: https://codesandbox.io/s/0z48zxvn
(exactly the same code)

From what I can tell this is due to v4 adding styles to an existing class (of lower priority than the media query) rather than to a new class like v3 does:

**V3**:
![V3](https://i.imgur.com/gkLjxEM.png)

**V4**:
![V4](https://i.imgur.com/vkfyVFY.png)

Only work around I've found is something clunky like this

```javascript
const MoreStyles = styled(Styles)`
  @media screen {
    background-color: blue;
  }
`;
```

If this is the intended behavior what is the correct way to achieve this functionality? Also if it is intended it should be probably be mentioned in https://www.styled-components.com/docs/faqs#what-do-i-need-to-do-to-migrate-to-v4

**Comment by probablyup** [comment]
The way v4 currently works is styles are folded and flattened together in the case of nested `styled(StyledComponent)`, so the background blue is essentially getting grouped with the other static rules (height and width) and the media queries are appended after since they aren't part of the same style context.

Your v3 example works because before the components were not folded and each had its own generated style class. The blue background class comes after the first class due to runtime insertion order and then due to how CSS places higher precedence on equal-weight styles lower in the sheet, the blue is applied.

In terms of fixes, there are three I can think of:

1) Use a precedence boost:

  ```
  && {
    background-color: blue;
  }
  ```

  This seems like the better solution to me because it makes it more obvious that you intend for this particular style to be applied over other siblings.

2) Wrap it in a media query like you did; this forces the style to be broken off the main clump since media queries can not be nested inside a class definition and thus are inserted after the main set, becoming implicitly higher precedence

3) Use something like `!important`

**Comment by ksabry** [comment]
Thanks for the response, the precedence boost seems like the best solution for what I want.

Just to be clear, I take it that the current behavior is intended and won't be changed back, as doing so would probably require some messy logic around conditionally folding each attribute. If this is the case feel free to close the issue

**Comment by probablyup** [comment]
We're still discussing it internally. It'll be present in v4 at launch but we may make adjustments afterward.

**Comment by codeaid** [comment]
Not quite sure if it's a related issue but I'm having a similar precedence problem.

This works:

```javascript
styled.div`
    & + & {
        border-top: 1px solid #cccccc;
    }

    &:hover {
        background-color: #fafafa;
    }
`;
```

While this one does not generate styles defined in `& + &`:

```javascript
styled.div`
    &:hover {
        background-color: #fafafa;
    }

    & + & {
        border-top: 1px solid #cccccc;
    }
`;
```

Here's a demo: https://react-9lm5xr.stackblitz.io/

**Comment by probablyup** [comment]
@codeaid definitely a bug, for some reason the second example is generating `.cIZrDu + .sc-htpNat:hover` which is wrong, should be `.cIZrDu + .sc-htpNat`. I'll try and look into this today.

**Comment by kitten** [comment]
@codeaid this is definitely unrelated to the `@media` problem. Can you create a new issue to track this please?

**Comment by codeaid** [comment]
> @codeaid this is definitely unrelated to the `@media` problem. Can you create a new issue to track this please?

Does @probablyup's issue referenced above your comment not cover that?

**Comment by kitten** [comment]
@codeaid I hope it does at least 😅 but it's good to have an issue that's easy to find for others if they run into the same issue

**Comment by lydell** [comment]
I’ve only ever used v4. As a beginner, I was very surprised by this behavior.

**Comment by samushenkov** [comment]
Hey there. Did you come to some common agreement regarding this issue? Just started using styled-components and immediately faced the same problem.

From the point of a regular user the next styles

```
const Panel = styled.div`

  background-color: red;

  @media (min-width: 1000px) {
    background-color: green;
  }

  background-color: blue;
`;
```
are expected to be compiled into something like

```
.someClass {
  background-color: red;
}

@media (min-width: 1000px) {
  .someClass {
    background-color: green;
  }
}

.someClass {
  background-color: blue;
}
```

Yes, using of a precedence boost can help, but it is still a workaround. This also makes styles more complex.

**Comment by kitten** [comment]
Closing due to age, inactivity, missing reproduction, or lack of details.

**Comment by samushenkov** [comment]
Hello @kitten. Here is a link that shows a precedence issue - https://codesandbox.io/s/precedence-issue-4n4xx.

**Comment by kitten** [comment]
@samushenkov I've closed duplicate issues across the repo with more explanations, but refrained from adding it here since the issue is from 2018. These days you'll see this behaviour due to constant folding, which combines the rules of multiple components into one.
