### ISSUE TITLE
Optional types passed down as required

### ISSUE THREAD

**Issue by soutot** [styled-components/styled-components#2096]
I'm trying to customize some Material UI components using Styled Components, however once I wrap the MUI component with ```styled``` hoc TypeScript starts to warn regarding some props are not provided. Looking at MUI props definitions all of them are optional. If I use the pure MUI component it works fine.

Code example:

 ```
 import styled from 'styled-components';
  import { TextField } from '@material-ui/core';

  const TextFieldStyled = styled(TextField)``
  /* This returns missing props warning */   
  <TextFieldStyled 
      name={name}
      label={label}
      value={value}
      onChange={onChange}
    />

  /* This works fine */
  <TextField
      name={name}
      label={label}
      value={value}
      onChange={onChange}
    />
```

I found this PR that was used to solve a passing down props issue https://github.com/styled-components/styled-components/pull/1427/files

After updating the code to pass the props as partial. I tested and the warning is gone.
https://github.com/soutot/styled-components/blob/master/typings/styled-components.d.ts#L56

I'd like to share this with you and check if this is the correct approach or if this error was not suppoose to happen and I'm missing something.

My package.json contains
"styled-components": "^3.4.9"
"@material-ui/core": "^3.2.0",
"@types/material-ui": "^0.21.5",

Thanks

**Comment by probablyup** [comment]
cc @styled-components/typers

**Comment by probablyup** [comment]
Could you repost on DefinitelyTyped? We don't keep typings in this repo and aren't responsible for maintaining them.
