### ISSUE TITLE
[v4.0.0] Types: Could not find a declaration file for module 'styled-components/native'.

### ISSUE THREAD

**Issue by ReggaePanda** [styled-components/styled-components#2099]
there are no types for react-native components

## Environment
npx: Installierte 1 in 2.983s

## System:
 - OS: macOS High Sierra 10.13.6
 - CPU: x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
 - Memory: 751.21 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 10.9.0 - /usr/local/bin/node
 - Yarn: 1.10.1 - /usr/local/bin/yarn
 - npm: 5.10.0 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman

## Reproduction
add typescript and tslint

## Steps to reproduce
let tslint your code

## Expected Behavior
no error

## Actual Behavior
```
$ tslint --project tsconfig.json && yarn typecheck
$ tsc --noEmit
App.tsx(5,20): error TS7016: Could not find a declaration file for module 'styled-components/native'. '…/app/node_modules/styled-components/native/dist/styled-components.native.cjs.js' implicitly has an 'any' type.
```

<img width="388" alt="bildschirmfoto 2018-10-15 um 22 37 11" src="https://user-images.githubusercontent.com/2183135/46976864-e6dcc780-d0ca-11e8-84f7-a9271197f2f3.png">

<img width="1289" alt="bildschirmfoto 2018-10-15 um 22 38 01" src="https://user-images.githubusercontent.com/2183135/46977041-5fdc1f00-d0cb-11e8-920e-bebe8933bcfd.png">

**Comment by probablyup** [comment]
cc @styled-components/typers

**Comment by probablyup** [comment]
@ReggaePanda could you repost on definitelytyped? That's where our types actually are.

**Comment by MarkoCen** [comment]
Same error happened with `styled-components` v4.1.1 and `@types/styled-components` v4.1.1

**Comment by probablyup** [comment]
Post on definitelytyped please. We don’t maintain TS typings locally

**Comment by muhammadawaisshaikh** [comment]
Solution: All you have to do is edit your TypeScript Config file (tsconfig.json) and add a new key value pair as:
"noImplicitAny": false

**Comment by hugonomura** [comment]
You should add `@types/styled-components` as dependency to the project.

If you are using yarn, you can run the command
> yarn add @types/styled-components

**Comment by jaccao** [comment]
`styled-components/native` types are moved to `@types/styled-components-react-native`.

**Comment by AndreCosta101** [comment]
Just add: 

`❯yarn add @types/styled-components-react-native -D `

**Comment by pettomartino** [comment]
^ I have added `@types/styled-components-react-native` and the problem persist. Actually I started having after updating. Any clues?

**Comment by hanselabreu** [comment]
@pettomartino happening to me as well on `"@types/styled-components-react-native": "^5.1.1"`.

**Comment by leonardodelira** [comment]
> @pettomartino happening to me as well on `"@types/styled-components-react-native": "^5.1.1"`.
> 
> Edit:
> The problem appears to be with `@types/styled-components: "^5.1.7"`. Just downgrade to `5.1.6` and it should be fine.

Works for me, thanks!

**Comment by pedro-cal** [comment]
> Just add:
> 
> `❯yarn add @types/styled-components-react-native -D `

This solution has worked for me too. Thanks!

**Comment by GustavoEklund** [comment]
> > @pettomartino happening to me as well on `"@types/styled-components-react-native": "^5.1.1"`.
> > Edit:
> > The problem appears to be with `@types/styled-components: "^5.1.7"`. Just downgrade to `5.1.6` and it should be fine.
> 
> Works for me, thanks!

This solution works for me, but just change version to `5.1.6` and run `yarn install` didn't work, so I have to:

> yarn remove @types/styled-components
> yarn add -D @types/styled-components@5.1.6

**Comment by ROiPinheiro** [comment]
> `styled-components/native` types moved to `@types/styled-components-react-native`.

Need to make this info more explicit in docs

**Comment by KennedyKeinstein** [comment]
> `styled-components/native` types moved to `@types/styled-components-react-native`.

This works for me Thanks

**Comment by CarlCr** [comment]
> > `styled-components/native` types moved to `@types/styled-components-react-native`.

_This also_ **works** f_or me!!_

**Comment by cs-manughian** [comment]
> Just add:
> 
> `❯yarn add @types/styled-components-react-native -D `

I can confirm this works! Thanks!

**Comment by drfbwilliams** [comment]
Please update the docs folks - finding the answer in a closed thread is not helpful. But glad it worked.

Cheers

**Comment by TheSYNcoder** [comment]
> Just add:
> 
> `❯yarn add @types/styled-components-react-native -D `

Thanks this works!!

**Comment by leonardoprimieri** [comment]
> `styled-components/native` types moved to `@types/styled-components-react-native`.

Thank you!

**Comment by brendoncarvalho** [comment]
> "noImplicitAny": false

Works!!!

Insert into: "compilerOptions": { 
"noImplicitAny": false
}

**Comment by Giboork** [comment]
> > "noImplicitAny": false
> 
> Works!!!
> 
> Insert into: "compilerOptions": { "noImplicitAny": false }

you are not solving the issue, you are turning off the ts checking

**Comment by Krypto219** [comment]
>yarn add @types/styled-components-react-native -D

I solved problem using this command. Recommend

**Comment by subhranshudas** [comment]
I tried the below but **did not work** for me. 
```
yarn add @types/styled-components-react-native -D
```
my set up-
```
"dependencies": {
    "react": "17.0.2",
    "react-native": "0.68.1",
    "styled-components": "5.3.5"
  },
 "devDependencies": {
   "@types/styled-components": "5.1.25",
   "@types/styled-components-react-native": "^5.1.3"
  }
```
![Screen Shot 2022-08-03 at 9 15 29 AM](https://user-images.githubusercontent.com/6158624/182521579-76869665-455e-41d5-97a0-0ec63a565675.png)

**Comment by nazarmurza** [comment]
> I tried the below but **did not work** for me.
> 
> ```
> yarn add @types/styled-components-react-native -D
> ```
> 
> my set up-
> 
> ```
> "dependencies": {
>     "react": "17.0.2",
>     "react-native": "0.68.1",
>     "styled-components": "5.3.5"
>   },
>  "devDependencies": {
>    "@types/styled-components": "5.1.25",
>    "@types/styled-components-react-native": "^5.1.3"
>   }
> ```
> 
> ![Screen Shot 2022-08-03 at 9 15 29 AM](https://user-images.githubusercontent.com/6158624/182521579-76869665-455e-41d5-97a0-0ec63a565675.png)

downgrade @types/styled-components from 5.1.25 to 5.1.6. Worked for me

**Comment by roni-castro-db** [comment]
> I tried the below but **did not work** for me.
> 
> ```
> yarn add @types/styled-components-react-native -D
> ```
> 
> my set up-
> 
> ```
> "dependencies": {
>     "react": "17.0.2",
>     "react-native": "0.68.1",
>     "styled-components": "5.3.5"
>   },
>  "devDependencies": {
>    "@types/styled-components": "5.1.25",
>    "@types/styled-components-react-native": "^5.1.3"
>   }
> ```
> 
> ![Screen Shot 2022-08-03 at 9 15 29 AM](https://user-images.githubusercontent.com/6158624/182521579-76869665-455e-41d5-97a0-0ec63a565675.png)

Check if your tsconfig.json does not declare `types` implicitly or explicitly, if so, you need to add `"styled-components-react-native"` to it:

Example:

The `"@tsconfig/react-native/tsconfig.json"` base config from the react-native template defines the `types`, so I had to override it to:

```js
    "types": ["react-native", "jest", "styled-components-react-native"],
```

https://user-images.githubusercontent.com/95294257/184026064-65ee59f4-b080-4bf2-95b3-badcc12964c1.mov

**Comment by Gould219** [comment]
1. open cmd window
2. yarn add @types/styled-components-react-native

my project work well
sincerely

**Comment by gimwachan-git** [comment]
> Just add:
> 
> `❯yarn add @types/styled-components-react-native -D `

It worked!

**Comment by Gould219** [comment]
Okay
what is your github?

**Comment by cristiano-linvix** [comment]
> > I tried the below but **did not work** for me.
> > ```
> > yarn add @types/styled-components-react-native -D
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > my set up-
> > ```
> > "dependencies": {
> >     "react": "17.0.2",
> >     "react-native": "0.68.1",
> >     "styled-components": "5.3.5"
> >   },
> >  "devDependencies": {
> >    "@types/styled-components": "5.1.25",
> >    "@types/styled-components-react-native": "^5.1.3"
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![Screen Shot 2022-08-03 at 9 15 29 AM](https://user-images.githubusercontent.com/6158624/182521579-76869665-455e-41d5-97a0-0ec63a565675.png)
> 
> Check if your **tsconfig.json** does not declare `types` implicitly or explicitly, if so, you need to add `"styled-components-react-native"` to it:
> 
> Example:
> 
> The `"@tsconfig/react-native/tsconfig.json"` base config from the react-native template defines the `types`, so I had to override it to:
> 
> ```js
>     "types": ["react-native", "jest", "styled-components-react-native"],
> ```
> 
>  Screen.Recording.2022-08-10.at.18.44.51.mov

Works for me, thanks!!

**Comment by Gabriel-Jesusvix** [comment]
> > I tried the below but **did not work** for me.
> > ```
> > yarn add @types/styled-components-react-native -D
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > my set up-
> > ```
> > "dependencies": {
> >     "react": "17.0.2",
> >     "react-native": "0.68.1",
> >     "styled-components": "5.3.5"
> >   },
> >  "devDependencies": {
> >    "@types/styled-components": "5.1.25",
> >    "@types/styled-components-react-native": "^5.1.3"
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![Screen Shot 2022-08-03 at 9 15 29 AM](https://user-images.githubusercontent.com/6158624/182521579-76869665-455e-41d5-97a0-0ec63a565675.png)
> 
> Check if your **tsconfig.json** does not declare `types` implicitly or explicitly, if so, you need to add `"styled-components-react-native"` to it:
> 
> Example:
> 
> The `"@tsconfig/react-native/tsconfig.json"` base config from the react-native template defines the `types`, so I had to override it to:
> 
> ```js
>     "types": ["react-native", "jest", "styled-components-react-native"],
> ```
> 
>  Screen.Recording.2022-08-10.at.18.44.51.mov

This works for me!!!! 08-16-22

**Comment by Gould219** [comment]
1. open cmd window
2. yarn add @types/styled-components-react-native
3. restart Vs code

If this is not available, contact me

**Comment by hyoretsu** [comment]
In my case I was using a PNPM monorepo with hoisted node-linker, so I had to add "../node_modules/@types" to `typeRoots` in `tsconfig.json`

**Comment by JrossiGale** [comment]
Hi there, 

I am having some trouble getting this set up on my React Native project. 

I installed the dependency using npm: 

npm install @types/styled-components-react-native


<img width="363" alt="Screen Shot 2022-09-06 at 4 23 41 PM" src="https://user-images.githubusercontent.com/81778560/188731092-a54381f3-4a03-4682-a250-4c268563343f.png">
But I am still getting an error in my emulator 


Here is my package.json file: 

<img width="764" alt="Screen Shot 2022-09-06 at 4 24 54 PM" src="https://user-images.githubusercontent.com/81778560/188731343-2249a223-4174-44b6-8847-ddc862a4eb08.png">



Here is my App.js file. I am just trying to get this package working so I can work on this project. Please help me. Thanks so much 


<img width="646" alt="Screen Shot 2022-09-06 at 4 27 05 PM" src="https://user-images.githubusercontent.com/81778560/188731696-592854ee-eecf-4d48-8e83-a6d3c4777417.png">

**Comment by roni-castro-db** [comment]
> Hi there,
> 
> I am having some trouble getting this set up on my React Native project.
> 
> I installed the dependency using npm:
> 
> npm install @types/styled-components-react-native
> 
> <img alt="Screen Shot 2022-09-06 at 4 23 41 PM" width="363" src="https://user-images.githubusercontent.com/81778560/188731092-a54381f3-4a03-4682-a250-4c268563343f.png">
> 
> But I am still getting an error in my emulator
> Here is my package.json file:
> 
> <img alt="Screen Shot 2022-09-06 at 4 24 54 PM" width="764" src="https://user-images.githubusercontent.com/81778560/188731343-2249a223-4174-44b6-8847-ddc862a4eb08.png">
> 
> Here is my App.js file. I am just trying to get this package working so I can work on this project. Please help me. Thanks so much
> 
> <img alt="Screen Shot 2022-09-06 at 4 27 05 PM" width="646" src="https://user-images.githubusercontent.com/81778560/188731696-592854ee-eecf-4d48-8e83-a6d3c4777417.png">

You probably needs to import from `import styled from 'styled-components/native'` and not `import styled from '@types/styled-components-react-native'`

`.js` probably will not generate any warning =/, only `.ts`
<img width="621" alt="Screen Shot 2022-09-06 at 19 46 27" src="https://user-images.githubusercontent.com/95294257/188753531-a482c532-8b06-4628-a682-0378d5ba998f.png">

**Comment by JrossiGale** [comment]
@roni-castro-db Thank you so much for your help. Unfortunately, I am still being returned an error when I imported styles from 'styled-components-react-native' like you suggested. 

<img width="364" alt="Screen Shot 2022-09-08 at 4 14 42 PM" src="https://user-images.githubusercontent.com/81778560/189217095-76690008-1273-4493-94d1-da83d0aa29c0.png">

Does this work with .js? I fear that might be the problem. 

Please let me know if you have any suggestions. Also, what was your import statement? I used: 

npm i @types/styled-components-react-native -D

You can see my .json file in the post you quoted. Thanks again for all your help

**Comment by MouraVocal** [comment]
> > I tried the below but **did not work** for me.
> > ```
> > yarn add @types/styled-components-react-native -D
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > my set up-
> > ```
> > "dependencies": {
> >     "react": "17.0.2",
> >     "react-native": "0.68.1",
> >     "styled-components": "5.3.5"
> >   },
> >  "devDependencies": {
> >    "@types/styled-components": "5.1.25",
> >    "@types/styled-components-react-native": "^5.1.3"
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![Screen Shot 2022-08-03 at 9 15 29 AM](https://user-images.githubusercontent.com/6158624/182521579-76869665-455e-41d5-97a0-0ec63a565675.png)
> 
> Check if your **tsconfig.json** does not declare `types` implicitly or explicitly, if so, you need to add `"styled-components-react-native"` to it:
> 
> Example:
> 
> The `"@tsconfig/react-native/tsconfig.json"` base config from the react-native template defines the `types`, so I had to override it to:
> 
> ```js
>     "types": ["react-native", "jest", "styled-components-react-native"],
> ```
> 
> Screen.Recording.2022-08-10.at.18.44.51.mov

This worked for me thanks, I wonder why this isn't the default config?

**Comment by Seanmclem** [comment]
After adding "styled-components-react-native" to 'types', the error goes away, but now  none of my styled components accept children. 
`Type '{ children: Element[]; }' has no properties in common with type 'IntrinsicAttributes`

**Comment by sunniejai** [comment]
> After adding "styled-components-react-native" to 'types', the error goes away, but now none of my styled components accept children. `Type '{ children: Element[]; }' has no properties in common with type 'IntrinsicAttributes`

I am also seeing this behavior.

I had to define the component like this in order for it to work properly. Is this expected? `styled.TouchableOpacity<{ children: React.ReactNode }>`

**Comment by dev-one-company** [comment]
I solve the problem just by adding 

```json
"types": ["styled-components-react-native"]
```

to my `tsconfig.json` on `compilerOptions`

**Comment by brunopassos** [comment]
> ```json
> "styled-components-react-native"
> ```

Thanks, this helped me.

**Comment by ianlgnk** [comment]
> I solve the problem just by adding
> 
> ```json
> "types": ["styled-components-react-native"]
> ```
> 
> to my `tsconfig.json` on `compilerOptions`

it works for me
i'm using "styled-components": "^5.3.6" and "@types/styled-components-react-native": "^5.2.0",

**Comment by strawberryCheeseCake2** [comment]
> > I tried the below but **did not work** for me.
> > ```
> > yarn add @types/styled-components-react-native -D
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > my set up-
> > ```
> > "dependencies": {
> >     "react": "17.0.2",
> >     "react-native": "0.68.1",
> >     "styled-components": "5.3.5"
> >   },
> >  "devDependencies": {
> >    "@types/styled-components": "5.1.25",
> >    "@types/styled-components-react-native": "^5.1.3"
> >   }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ![Screen Shot 2022-08-03 at 9 15 29 AM](https://user-images.githubusercontent.com/6158624/182521579-76869665-455e-41d5-97a0-0ec63a565675.png)
> 
> Check if your **tsconfig.json** does not declare `types` implicitly or explicitly, if so, you need to add `"styled-components-react-native"` to it:
> 
> Example:
> 
> The `"@tsconfig/react-native/tsconfig.json"` base config from the react-native template defines the `types`, so I had to override it to:
> 
> ```js
>     "types": ["react-native", "jest", "styled-components-react-native"],
> ```
> 
>  Screen.Recording.2022-08-10.at.18.44.51.mov

You literally saved my life

**Comment by codexdevbrn** [comment]
> 

This solved it, Thanks!

**Comment by codexdevbrn** [comment]
> Just add:
> 
> `❯yarn add @types/styled-components-react-native -D `

This solved it, Thanks!

**Comment by Qyokizzzz** [comment]
Thanks.

**Comment by efstathiosntonas** [comment]
any ideas on how to type now that v6.0.0 is released? 

I get this error: `TS7006: Parameter 'props' implicitly has an 'any' type.`

![Screenshot 2023-06-28 at 10 34 59](https://github.com/styled-components/styled-components/assets/717975/3505cd7d-dc67-41a4-b51a-d49ba2df1e8b)

**Comment by andrefangeloni** [comment]
> any ideas on how to type now that v6.0.0 is released?
> 
> I get this error: `TS7006: Parameter 'props' implicitly has an 'any' type.`
> 
> ![Screenshot 2023-06-28 at 10 34 59](https://user-images.githubusercontent.com/717975/249389464-3505cd7d-dc67-41a4-b51a-d49ba2df1e8b.png)

Same here, on version 6, intellisense. is not working =/

**Comment by NatanTeixeiraVieira** [comment]
> any ideas on how to type now that v6.0.0 is released?
> 
> I get this error: `TS7006: Parameter 'props' implicitly has an 'any' type.`
> 
> ![Screenshot 2023-06-28 at 10 34 59](https://private-user-images.githubusercontent.com/717975/249389464-3505cd7d-dc67-41a4-b51a-d49ba2df1e8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE1MTg0NTAsIm5iZiI6MTcwMTUxODE1MCwicGF0aCI6Ii83MTc5NzUvMjQ5Mzg5NDY0LTM1MDVjZDdkLWRjNjctNDFhNC1iNTFhLWQ0OWJhMmRmMWU4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIwMlQxMTU1NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzRkODIxYmE3MmE0MDgwOGU2NTdlZjEwYjA2ZTdiM2RkMDE5ODZmZmYwZDViNDczYmQ0NDJkZTg5MmQ3MjUxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.PDG5sqPmKCcDMoQ-Jr1_aIMnTQ7KL-9dRwFw5XbkiEc)

From what I gathered, in version 6 of styled-components, there's no need to install `@types/styled-components-react-native`. It seems that the typing is included by default; you just need to install styled-components.

My dependencies:
![image](https://github.com/styled-components/styled-components/assets/95051728/3472e5ea-9171-4e5e-88f8-c5566861e8df)

To have intellisense in the themes, the configuration that worked for me was this:
![image](https://github.com/styled-components/styled-components/assets/95051728/5f1ede34-4796-4fd7-b3b3-3db15c12ee11)

In the `tsconfig.json`, I didn't add anything.
![image](https://github.com/styled-components/styled-components/assets/95051728/d9a59bd5-eb30-4f3b-8e48-f790668f91eb)
