### ISSUE TITLE
can't run styled component locally

### ISSUE THREAD

**Issue by johnanisere** [styled-components/styled-components#2100]
## System:
 - OS: macOS High Sierra 10.13.6
 - CPU: x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
 - Memory: 76.46 MB / 8.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 10.11.0 - /usr/local/bin/node
 - Yarn: 1.12.0 - /usr/local/bin/yarn
 - npm: 6.4.1 - /usr/local/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.3.0 => 1.3.0

## Reproduction

i. create a fork of the styled components repo
ii. clone it 
iii. cd styled-components
iv. yarn install

## Steps to reproduce

i. create a fork of the styled components repo
ii. clone it 
iii. cd styled-components
iv. yarn install

## Expected Behavior
successful dependency installation

## Actual Behavior
Error running install script for optional dependency: "/Users/busha03/Desktop/PlayGround/infer/community/styled-components/sandbox/node_modules/fsevents: Command failed.
Exit code: 1
Command: node install
Arguments:
Directory: /Users/busha03/Desktop/PlayGround/infer/community/styled-components/sandbox/node_modules/fsevents
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.6.39
node-pre-gyp info using node@10.11.0 | darwin | x64
node-pre-gyp info check checked for \"/Users/busha03/Desktop/PlayGround/infer/community/styled-components/sandbox/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node\" (not found)
node-pre-gyp http GET https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz
node-pre-gyp http 404 https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(404): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.11.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http 404 status code downloading tarball https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Tried to download(undefined): https://fsevents-binaries.s3-us-west-2.amazonaws.com/v1.1.3/fse-v1.1.3-node-v64-darwin-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for fsevents@1.1.3 and node@10.11.0 (node-v64 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp http Connection closed while downloading tarball file

**Comment by probablyup** [comment]
Sounds like you’re missing your Xcode developer tools. Not a styled
components issue.

**Comment by johnanisere** [comment]
@probablyup I have Xcode installed already, How do I install the developer tools? any idea?

**Comment by probablyup** [comment]
Idk it’s something like xcode-select --install or something. Google it

**Comment by probablyup** [comment]
I'm curious why it's trying to load `styled-components.js` since that's not what we have as `"main"` in package.json.

**Comment by johnanisere** [comment]
How do you run this project locally ? I just want to contibute.

**Comment by tusheer** [comment]
I can able to run it locally but if change anything in styled-component/src folder that doesn't reflect in the  sandbox folder from the main branch. 

I think [this CONTRIBUTING.md](https://github.com/styled-components/styled-components/blob/main/CONTRIBUTING.md) file is not good enough.
