### ISSUE TITLE
v4 does not handle nested animations with keyframes correctly

### ISSUE THREAD

**Issue by piuccio** [styled-components/styled-components#2102]
## Environment
 - babel-plugin-styled-components: 1.8.0 => 1.8.0 
 - styled-components: 4.0.0 => 4.0.0 

## Reproduction

https://codesandbox.io/s/438pwxmlpw

## Steps to reproduce

Nested animations are not output correctly.
I had this code which worked fine in styled-components 3

```js
styled.span`
  animation: ${rotateLoading} 3s ease infinite;
  ${(props) => props.reverse && `
    animation-name: ${rotateLoadingReverse};
  `}
`;
```

When updating to v4 I followed the guide suggesting to wrap keyframes in `css` and ended up with the code in the example above

```js
styled.span`
  animation: ${css`${rotateLoading} 3s ease infinite`};
  ${(props) => props.reverse && `
    animation: ${css`${rotateLoadingReverse} 3s ease infinite`};
  `}
`;
```

which however generates the invalid css

```
animation: [object Object],3s ease infinite;
```

It works ok if I rewrite to

```js
styled.span`
  animation: ${(props) => props.reverse ? reverseAnimation : rotateAnimation};
`
```

## Expected Behavior

Both boxes should spin

## Actual Behavior

Only the second works.

I don't know if it's too much an edge case, it doesn't matter too much because I have a fix, but maybe there's something wrong in nesting animation rules?

**Comment by probablyup** [comment]
The `css` helper should go on the outermost template literal here:

```
styled.span`
  animation: ${rotateLoading} 3s ease infinite;
  ${(props) => props.reverse && css`
    animation: ${rotateLoadingReverse 3s ease infinite;
  `}
`;
```

**Comment by probablyup** [comment]
And that style could be further simplified to this:

```js
styled.span`
  animation: ${p => p.reverse ? rotateLoadingReverse : rotateLoading} 3s ease infinite;
`;
```
