### ISSUE TITLE
[v4.0.0] Uglify(Terser) Error with Babel7, typescript, @babel/preset-typescript

### ISSUE THREAD

**Issue by astyfx** [styled-components/styled-components#2103]
## System:
 - OS: macOS High Sierra 10.13.3
 - CPU: x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
 - Memory: 82.66 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 10.8.0 - ~/.nvm/versions/node/v10.8.0/bin/node
 - Yarn: 1.10.1 - ~/.yarn/bin/yarn
 - npm: 6.4.1 - ~/.nvm/versions/node/v10.8.0/bin/npm
## npmPackages:
 - @types/styled-components: ^4.0.1 => 4.0.1
 - babel-plugin-styled-components: ^1.8.0 => 1.8.0
 - styled-components: ^4.0.0 => 4.0.0

## Reproduction
https://github.com/astyfx/styled-bug

## Steps to reproduce
1. Clone above repo
2. cd app
3. yarn
4. yarn build

## Expected Behavior
Build Success

## Actual Behavior
`ERROR in index-a366e6a54d1d10ea3dd3.js from Terser
Unexpected token: punc (})`

This error only happen when use styled.div

**Comment by probablyup** [comment]
Need some sort of reproduction repo so we can even attempt to fix this

**Comment by probablyup** [comment]
This line is your issue, has nothing to do with styled-components. https://github.com/astyfx/styled-bug/blob/10a16277793f747dcc7fcff857095d7ec3d9f561/app/webpack.config.js#L91

**Comment by astyfx** [comment]
@probablyup Thanks my mistake sorry for your time
