### ISSUE TITLE
Sibling selectors only work in one direction when referring to other components

### ISSUE THREAD

**Issue by shalanah** [styled-components/styled-components#2110]
### System:
 - OS: macOS High Sierra 10.13.6
 - CPU: x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
 - Memory: 375.03 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
### Binaries:
 - Node: 9.2.1 - /usr/local/bin/node
 - Yarn: 1.6.0 - /usr/local/bin/yarn
 - npm: 6.0.0 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
### npmPackages:
 - styled-components: ^4.0.0 => 4.0.0

## Reproduction
This worked in v3 but didn't once I upgraded. I have hidden radios and style them in another styled-component. I want to style my fancy radios based on how the hidden ones are responding. I'm using it with `:focus-visible` and focus visible polyfill but you can reproduce this with `:active`.

### Doesn't work
(Worked in v3)
```js
const PrettyRadio = styled`
  ${HiddenRadio}:active + & {
    outline: 1px dashed black;
  }
`
```
### Workaround
Flipped selector to hidden input and placed `HiddenRadio` after `PrettyRadio`
```js
const HiddenRadio = styled`
  &:active + ${PrettyRadio} {
    outline: 1px dashed black;
  }
`
```

## Expected Behavior
Both directions should work for adjacent sibling selector as in v3.

## Actual Behavior
Style is applied even if first condition is not met.

## Also...
Thank you for all your hard work! Love `styled-components` :)

**Comment by probablyup** [comment]
Can you try `styled-components@dev`? Merged a change today that hasn't been released yet around this functionality.

**Comment by shalanah** [comment]
@probablyup That worked for me 👍

**Comment by probablyup** [comment]
Fantastic. I'll close this then and look for a patch release tonight
