### ISSUE TITLE
A discussion on how we handle the syntax error

### ISSUE THREAD

**Issue by vensa-albertgao** [styled-components/styled-components#2112]
So, I wrote a wrong code in v3

```javascript
const Box = styled.div`
    font-size: ${fontSize.font13});
`;
```

Basically, there is an extra `)` at the end of the statement.

In v3. Everything seems to work where only this property will be wrong.
In v4, it will mess up the whole page style.

I think the v4 approach is better because it let me know there is a bug somewhere.

But considering how much time it took me to find it, shouldn't it be better if we can find this bug earlier?

I can think of 2 methods:

1. Update the IDE extension, so we can find this bug when we are writing the code. Currently, there are no errors. At least in WebStorm's SC extension.
2. Some kind of building warning like ESLint? But I think SC just export all the css strings without linting it?

**Comment by mxstbr** [comment]
You should totally be using stylelint: https://www.styled-components.com/docs/tooling#stylelint!
