### ISSUE TITLE
Can we use styled components export className ?

### ISSUE THREAD

**Issue by windyGex** [styled-components/styled-components#2113]
Consider the following code:

```jsx
const Wrapper = styled.div`
  &-icon {
    color: #fff;
  }
`
render() {
  const cls = Wrapper.getClassName();
  return <Wrapper>
   <div className={`${cls}-icon`}>xxx</div>
</Wrapper>
}
```

This saves a lot on the definition of the styled component。

**Comment by diondiondion** [comment]
I sometimes use a pattern like this when I need it:

```
const iconClassName = 'WrapperIcon'

const Wrapper = styled.div`
  & .${iconClassName} {
    color: #fff;
  }
`
Wrapper.iconClassName = iconClassName

render() {
  return (
    <Wrapper>
      <div className={Wrapper.iconClassName}>xxx</div>
    </Wrapper>
  )
}
```

**Comment by windyGex** [comment]
Well, But I want to get the className related to styled. 

The above code is same with the following:

```jsx
const iconClassName = 'WrapperIcon';
const Wrapper = styled.div`
  & .${iconClassName} {
    color: #fff;
  }
`
render() {
  return (
    <Wrapper>
      <div className={iconClassName}>xxx</div>
    </Wrapper>
  )
}
```
I mean how I can get the styled-components generated className, for example `gGHFzQ` ?

The real DOM like this: 

```html
<div class="gGHFzQ">
  <div class="gGHFzQ-icon"></div>
</div>
```

Please forgive my poor English.

**Comment by diondiondion** [comment]
> Well, But I want to get the className related to styled.

What for? The nice thing about styled-components is that you don't have to worry about the specifics of classes all that much.

> The above code is same with the following:

That only works as long as they're all in the same file. Also, attaching the className to the component as a property makes the relationship between the class and the component it belongs to clearer – after all the class won't work outside of `Wrapper`.

> Please forgive my poor English.

Your English is fine :)

**Comment by mrbone** [comment]
> > Well, But I want to get the className related to styled.
> 
> What for? The nice thing about styled-components is that you don't have to worry about the specifics of classes all that much.
> 
> > The above code is same with the following:
> 
> That only works as long as they're all in the same file. Also, attaching the className to the component as a property makes the relationship between the class and the component it belongs to clearer – after all the class won't work outside of `Wrapper`.
> 
> > Please forgive my poor English.
> 
> Your English is fine :)

Same issue, the use case is we need assign a classname to a 3rd UI library to some sub component, eg:

```ts
import { css } from 'styled-components';
const generatedCss = css`
  color: red;
`;

const extractFromStyledCss =  generatedCss.getClassName();

<AwesomeSelect dropdownClassname={extractFromStyledCss}>

</AwesomeSelect>
```

**Comment by d640k** [comment]
I also would like to be able to do this. I am using a library that has styling props in addition to `className` that accept a class to be able to style some internal elements.

**Comment by rubeonline** [comment]
```
const NavItemStyle = styled(Link)``
const extractFromStyledCss = String(NavItemStyle)

```
**Output:** 
.sc-fznJRM

**Dom:**
<img width="187" alt="image" src="https://user-images.githubusercontent.com/5664460/92577261-c0117680-f28a-11ea-8830-f381228238ad.png">

The last part of the class is missed. Any ideas?

**Comment by roberttaylor426** [comment]
> Same issue, the use case is we need assign a classname to a 3rd UI library to some sub component, eg:
> 
> ```ts
> import { css } from 'styled-components';
> const generatedCss = css`
>   color: red;
> `;
> 
> const extractFromStyledCss =  generatedCss.getClassName();
> 
> <AwesomeSelect dropdownClassname={extractFromStyledCss}>
> 
> </AwesomeSelect>
> ```

If the class name is needed in a sub component, could you not just pass your own class name and then reference that from your styled component?

Something like:

```ts
import { css } from 'styled-components';

const EnclosingStyledComponent = styled.div`
  .myDropdown {
    color: red
  }
`;

<AwesomeSelect dropdownClassname={'myDropdown'} >

</AwesomeSelect>
```

**Comment by mrbone** [comment]
> > Same issue, the use case is we need assign a classname to a 3rd UI library to some sub component, eg:
> > ```ts
> > import { css } from 'styled-components';
> > const generatedCss = css`
> >   color: red;
> > `;
> > 
> > const extractFromStyledCss =  generatedCss.getClassName();
> > 
> > <AwesomeSelect dropdownClassname={extractFromStyledCss}>
> > 
> > </AwesomeSelect>
> > ```
> 
> If the class name is needed in a sub component, could you not just supply your own class name and then reference that from your styled component?
> 
> Something like:
> 
> ```ts
> import styled from 'styled-components';
> 
> const EnclosingStyledComponent = styled.div`
>   .myDropdown {
>     color: red
>   }
> `;
> 
> <EnclosingStyledComponent>
>   <AwesomeSelect dropdownClassname={'myDropdown'} >
> 
>   </AwesomeSelect>
> </EnclosingStyledComponent>
> ```

sometimes not, cuz the children may attach to body or other nodes, the use case is modal or select.

**Comment by robert-wettstaedt** [comment]
> ```
> const NavItemStyle = styled(Link)``
> const extractFromStyledCss = String(NavItemStyle)
> ```
> 
> **Output:**
> .sc-fznJRM
> 
> **Dom:**
> <img alt="image" width="187" src="https://user-images.githubusercontent.com/5664460/92577261-c0117680-f28a-11ea-8830-f381228238ad.png">
> 
> The last part of the class is missed. Any ideas?

I've had the same issue. The way I worked around it now is the following:

```tsx
import styled, { createGlobalStyle } from 'styled-components'

const NavItemStyle = styled(Link)`
  // Keep this empty
`

const GlobalNavItemStyle = createGlobalStyle`
  ${NavItemStyle} {
    // Your custom styling here
  }
`

<>
  <GlobalNavItemStyle />

  <Nav itemClassName={NavItemStyle.styledComponentId} />
</>
```

I am using `.styledComponentId` explicitly because this is what is being returned from the `.toString()` method, but without the css class selector `.` in front of it.


Of course this is absolutely ridiculous and I wish there was an actual API for this.

**Comment by dsktschy** [comment]
> ```
> const NavItemStyle = styled(Link)``
> const extractFromStyledCss = String(NavItemStyle)
> ```
> 
> **Output:**
> .sc-fznJRM
> 
> **Dom:**
> <img alt="image" width="187" src="https://user-images.githubusercontent.com/5664460/92577261-c0117680-f28a-11ea-8830-f381228238ad.png">
> 
> The last part of the class is missed. Any ideas?

If last part means [generatedClassName](https://github.com/styled-components/styled-components/blob/9bef00cb03ab36c5e7d1faaf75e1f9419ae72f73/packages/styled-components/src/models/StyledComponent.js#L126) (e.g. `MnkPY`), I am using the following to get it.
But this is a temporary workaround and is not ideal.
Because, if the className is set to `<Child />`s in `<Parent />`, the value will change.

```tsx
// className and generatedClassName must be optional properties
interface Props {
  className?: string
  generatedClassName?: string
  bold: boolean
}

// The default value of className is set to avoid TypeScritpt errors
// It will never be used in practice
const Child = styled(
  ({
    className = '',
    generatedClassName = className.split(' ')[1] || '',
    bold
  }: Props): JSX.Element => (
    <div className={className}>
      {bold ? 'Bold' : 'Normal'}
      <div className={`${generatedClassName}__inner`}>Red</div>
    </div>
  )
)`
  font-weight: ${({ bold }) => (bold ? 'bold' : 'normal')};

  &__inner {
    color: red;
  }
`

// Don't set className and generatedClassName to <Child />s in <Parent />
const Parent = () => (
  <div>
    <Child bold />
    <Child bold={false} />
  </div>
)
```

```html
<div>
  <div class="sc-bdfBwQ Uvzes">
    Bold
    <div class="Uvzes__inner">Red</div>
  </div>
  <div class="sc-bdfBwQ bqGggS">
    Normal
    <div class="bqGggS__inner">Red</div>
  </div>
</div>
```

**Comment by dyabol** [comment]
Another solution, when you need pass custom props:

```tsx
type ClassNameConsumerProps = {
    width: number;
    className?: string;
    children: (className?: string) => React.ReactElement;
};

const ClassNameConsumer = ({ className, children }: ClassNameConsumerProps) => children(className);

const StyledClassName = styled(ClassNameConsumer)`
    width: ${(props) => props.width};
    overflow: auto;
`;

// using

const Button: React.FC = () => (
    <StyledClassName width={500}>
        {(className) => <button className={className}>Click me!</button>}
    </StyledClassName>
);
```

**Comment by jazzfog** [comment]
It is sad that there is no out of the box solution, it would be helpful for the cases described above.
At least there are couple viable workarounds here.

**Comment by jazzfog** [comment]
> I've had the same issue. The way I worked around it now is the following:
> 
> ```tsx
> import styled, { createGlobalStyle } from 'styled-components'
> 
> const NavItemStyle = styled(Link)`
>   // Keep this empty
> `
> 
> const GlobalNavItemStyle = createGlobalStyle`
>   ${NavItemStyle} {
>     // Your custom styling here
>   }
> `
> 
> <>
>   <GlobalNavItemStyle />
> 
>   <Nav itemClassName={NavItemStyle.styledComponentId} />
> </>
> ```
> 
> I am using `.styledComponentId` explicitly because this is what is being returned from the `.toString()` method, but without the css class selector `.` in front of it.
> 
> Of course this is absolutely ridiculous and I wish there was an actual API for this.

If you're using global style, probably you don't need that sc-generated class name, you could provide your own class and not worry about extracting the sc-one. Unless, of course, if you have multiple elements you want to style, then non-unique class might cause issues. But even then it might make sense to generate your own unique ID as opposed to relying on (not sure how well documented, possible internal) SC API.

```
import styled, { createGlobalStyle } from 'styled-components'

const GlobalNavItemStyle = createGlobalStyle`
  .myNavItem {
    // Your custom styling here
  }
`

<>
  <GlobalNavItemStyle />
  <Nav itemClassName=".myNavItem" />
</>
```

**Comment by fingerartur** [comment]
Why is this closed without any resolution?

**Comment by pie6k** [comment]
Seems the final class name is generated here - https://github.com/styled-components/styled-components/blob/38256f562b244877e146ce5a2fc77a5f54b133d7/packages/styled-components/src/models/ComponentStyle.ts#L14 - which looks like quite hard to be extracted away, which sucks

**Comment by WannapornNoicheen** [comment]
I faced the same issue when I wanted to assign className of the dropdown of other library's select. I ended up using [typestyle](https://typestyle.github.io/#/) instead since it does the job without any workaround.

**Comment by pie6k** [comment]
I think it is good to understand why full className is not available.

Consider such use case:

```ts
const UIDiv = styled.div`
  color: red;
  font-size: ${props => props.$fontSize}px;
`;
```

Such a div can technically result in infinite different classNames. eg. `<UIDiv $fontSize={12} />` and `<UIDiv $fontSize={14} />` will have the same 'base' class, but different 'target' class (eg. `sc-fznJRM MnkPY` where first one is always the same, but 2nd one depends on 'result' (of font-size in our case).

As styled-components can include props => results functions - in such case it cannot know what will be the result without knowing the props.

- - -

This context might help understand why it is not possible to get className for 'dynamic' styled component up-front.

Tho I'd still argue that with a 'static' use case, eg

```ts
const UIDiv = styled.div`
  color: red;
`;
```

The styled component could 'publish' both classNames, as it knows up-front there is no way anything dynamic will happen with this component styles.

**Comment by J4v4Scr1pt** [comment]
Love styled-components 😁
If I need to refer to a component to style it I usally do this:

1. Export whatever you need to access:
`export { Wrapper as CircledButtonWrapper };`

2. Import it where you need it:
`import  { CircledButtonWrapper } from "/Bla/CircledButton";`

3. Use it where you need to style it:
```
const Wrapper = styled.div` 
 /* Some other styles */
	&:hover {
		${CircledButtonWrapper} {
			opacity: 1;
		}
	} `;
```

**Comment by SergeyVolynkin** [comment]
Some simple'ish example making it work for https://ant.design/components/drawer :

```ts
type DrawerProps = ComponentPropsWithoutRef<typeof Drawer>;

const StyledDrawer = styled(({ className, children, ...rest }: DrawerProps) => (
  <Drawer rootClassName={className} {...rest}>
    {children}
  </Drawer>
))`
  .ant-drawer-mask {
    background: none;
  }

  .ant-drawer-header {
    height: 55px;
    border-bottom: none;
    padding: 16px;
  }
`;
```

**Comment by anion155** [comment]
> > ```
> > const NavItemStyle = styled(Link)``
> > const extractFromStyledCss = String(NavItemStyle)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > **Output:**
> > .sc-fznJRM
> > **Dom:**
> > <img alt="image" width="187" src="https://user-images.githubusercontent.com/5664460/92577261-c0117680-f28a-11ea-8830-f381228238ad.png">
> > The last part of the class is missed. Any ideas?
> 
> If last part means [generatedClassName](https://github.com/styled-components/styled-components/blob/9bef00cb03ab36c5e7d1faaf75e1f9419ae72f73/packages/styled-components/src/models/StyledComponent.js#L126) (e.g. `MnkPY`), I am using the following pattern to get it. It will simplify selectors in the template literal (e.g. `&__inner`). But this is a temporary workaround and is not ideal.
> 
> ```tsx
> // className and generatedClassName must be optional properties
> interface Props {
>   className?: string
>   generatedClassName?: string
>   bold: boolean
> }
> 
> // The default value of className is set to avoid TypeScritpt errors
> // It will never be used in practice
> const Child = styled(
>   ({
>     className = '',
>     generatedClassName = className.split(' ')[1] || '',
>     bold
>   }: Props) => (
>     <div className={className}>
>       {bold ? 'Bold' : 'Normal'}
>       <div className={`${generatedClassName}__inner`}>Red</div>
>     </div>
>   )
> )`
>   font-weight: ${({ bold }) => (bold ? 'bold' : 'normal')};
> 
>   &__inner {
>     color: red;
>   }
> `
> 
> // Don't set generatedClassName to <Child /> in <Parent />
> const Parent = () => (
>   <div>
>     <Child bold />
>     <Child bold={false} />
>   </div>
> )
> ```
> 
> ```
> <div>
>   <div class="sc-bdfBwQ Uvzes">
>     Bold
>     <div class="Uvzes__inner">Red</div>
>   </div>
>   <div class="sc-bdfBwQ bqGggS">
>     Normal
>     <div class="bqGggS__inner">Red</div>
>   </div>
> </div>
> ```

Needed to do exactly the same. Ended up doing something like this:

```
// Drawer.tsx
const Inner = styled.div`/* some default styles for inner */`
export function Drawer(props) {
  return <div {...props}><Inner /><div>
}
Drawer.Inner = Inner

// app.tsx
const CustomDrawer = styled(Drawer)`
  ${Drawer.Inner} {
    /* custom inner styles */
  }
`
```

**Comment by dobesv** [comment]
I think it might work with render props:

```
// Utility class
export interface StyleWrapperProps {
className: string;
children: (className: string) => ReactElement;
}

export function StyleWrapper(props: StyleWrapperProps): ReactElement {
  return children(props.className):
}
```

```
// Usage
const BlueWrapper = styled(StyleWrapper)`
  color: blue;
`;

export function MyComponent(props: any): ReactElement {
   return <div>
   <BlueWrapper>
    {blueClassName => <MyThirdPartyComponent className={blueClassName} />
</BlueWrapper>
</div>
}

```
