### ISSUE TITLE
Using @font-face inside global styles breaks the app

### ISSUE THREAD

**Issue by sistemico** [styled-components/styled-components#2115]
## Environment
```
"name": "styled-components",
"version": "4.0.1"
```

## Reproduction
https://codesandbox.io/s/zno49k7rjl

## Steps to reproduce
Try to use `@font-face` CSS at-rule inside `createGlobalStyle` helper

## Expected Behavior
Components should render correctly with the defined typography

## Actual Behavior
The entire application breaks displaying the following error:

```
TypeError: Cannot read property 'lastIndexOf' of undefined
```

**Comment by probablyup** [comment]
Juuuuust pushed 4.0.2 to fix this!

**Comment by sistemico** [comment]
Awesome! Thank you so much for that quick patch
