### ISSUE TITLE
Nicer syntax for composing mixins

### ISSUE THREAD

**Issue by sonhanguyen** [styled-components/styled-components#2116]
Currently we can do
```ts
styled.div`
    ${mixin1}
    ${mixin2}
    ${mixin3}
`
```
I wonder if people thinks it's better to ovreload the signature to enable `styled.div(mixin1, mixin2, mixin3)`?

**Comment by probablyup** [comment]
Technically you can supply an array since that's what a template literal turns into.

**Comment by mxstbr** [comment]
You can already do:

```JS
const Button = styled.div(shared1, shared2, shared3);
```

Demo: https://codesandbox.io/s/kzk8y99x5
