### ISSUE TITLE
Using Stateless Functional Components with the `attrs` constructor as `as` prop

### ISSUE THREAD

**Issue by timswalling** [styled-components/styled-components#2117]
Firstly, thanks to everyone involved for all the hard work on v4 - I'm really enjoying using it.

The introduction of the `as` prop is really useful, but it tripped me up when I tried to use it with the `attrs` constructor (which doesn't accept functions):

```jsx
// These work
const WithString = styled(StyledComponent).attrs({ as: 'div' })``;
const WithClass = styled(StyledComponent).attrs({ as: ClassComponent })``;
const WithWrappedFunction = styled(StyledComponent).attrs({
  as: () => StatelessFunctionalComponent,
})``;

// This doesn't
const WithFunction = styled(StyledComponent).attrs({
  as: StatelessFunctionalComponent,
})``;
```

Would you consider allowing the `attrs` constructor to accept Stateless Functional Components for the `as` prop? (For example, passing the value of the `as` prop instead of its result in [`buildExecutionContext`](https://github.com/styled-components/styled-components/blob/master/src/models/StyledComponent.js#L150).)

If not, what's the best workaround? (I'm happy to create a PR to add it to the docs.)

**Comment by probablyup** [comment]
Any time you pass a function to attrs it’ll be called with props and the
the result of that function is what is finally used as the prop. So yeah
you’ll want to do () => Component rather than just Component.

**Comment by mxstbr** [comment]
Maybe we can add a warning if an `.attrs`-called-function returns an element and tell people to wrap them in another function?

**Comment by probablyup** [comment]
@mxstbr yeah that seems sensible

**Comment by timswalling** [comment]
Thanks! Would it be better just to avoid using `as` with `attrs` and use `defaultProps` instead?

**Comment by probablyup** [comment]
I wouldn’t say it’s better, entirely depends on what feels more natural to
you!

**Comment by timswalling** [comment]
@probablyup @mxstbr thanks for your help. I can have a look at adding in the element warning later this week.

**Comment by dobesv** [comment]
It seems odd to use `as` with `attrs`.  Why not pass that component as the parameter to `styled` in the first place?  Or use `withComponent`?  What's the underlying use case not supported properly by `styled-components` here?

**Comment by sarneeh** [comment]
@dobesv Let's say you have a `Menu` component which you'd like to look like a `Card`, but appear in HTML as a `ul` tag. In this case, to reuse everything you have already, you'd like to do:
```js
const Menu = styled(Card).attrs({ as: List })``;
```

**Comment by dobesv** [comment]
Hmm I see, I have run into this kind of issue myself, wanting to inherit two different styles.  I think `styled-components` should provide a "built-in" system for doing this because it's pretty clunky the way it is now. If you look at that component you created above, if someone then goes ahead and uses the `as` attribute to try and combine it with some other style / element it'll override your `as` and the style won't be correct.

A safer way to merge two styles would be to create a temporary component:

```
const Menu = styled(props => <Card as={List} {...props}/>)` ... styles ...`;
```

It would be great if `styled-components` had a feature for this built-in, though, maybe something like:

```
const Menu = styled([Card, List])` ... styles ...`;
```

Or

```
const Menu = styled.div` @extend ${Card}; @extend ${List}; ... styles ...`;
```

**Comment by sarneeh** [comment]
@dobesv I agree, it would be perfect to be able to pass an array to `styled()` and maybe leave the `as` prop to only work as an explicit HTML tag setter. I think it would be more readable and intuitive. But I guess we went kinda offtopic here :smiley:

**Comment by kitten** [comment]
Closing due to age, inactivity, missing reproduction, or lack of details.
