### ISSUE TITLE
Internet explorer 10+ styled-components issue (JS error)

### ISSUE THREAD

**Issue by fatpc** [styled-components/styled-components#212]
Hi Guys -

Our app works in chrome and firefox except for IE10+. We are getting below JS error:

![image](https://cloud.githubusercontent.com/assets/8001832/20417260/4a6a3b5a-ad98-11e6-9514-fb300f85bbf2.png)

Below is the specific line of code:

![image](https://cloud.githubusercontent.com/assets/8001832/20417282/63e6dfd4-ad98-11e6-9699-c71cfa4293ae.png)

Is this a known issue? Also tried to access the styled-components website in IE and it does not load (JS error).

Thanks,
Pat

## Version
1.0.10

## Steps to reproduce
Run app in IE10+

## Expected Behavior
App works

## Actual Behavior
JS Error

**Comment by mxstbr** [comment]
Ugh that's annoying. Will fix this asap, sorry for the issues!

**Comment by thisguychris** [comment]
@mxstbr / @fatpc the fix is just use babel-polyfill via `import 'babel-polyfill'`

@mxstbr - while including babel-polyfill on a library level would indeed fix this.  As per babel docs: This  
>...will emulate a full ES2015 environment and is **intended** to be used in an application rather than a library/tool.

So I'm in disagreement including the polyfill in this library, maybe we just add it in the README?  Another alternative is just polyfill what the library use, maybe Symbol, or Array functions?  Let me know what course of action we should take and I'll issue a PR.

**Comment by mxstbr** [comment]
We'll just not use `.startsWith`, instead let's use a regex to check this!

`/$--/.test(decl.prop)` should do the trick I think?

**Comment by thisguychris** [comment]
@mxstbr checking in ie11 though I'm seeing a different error:
http://take.ms/U3iTM

That regex doesn't work by the way.
how about `!!(decl.prop.indexOf('--') === 0)`

**Comment by mxstbr** [comment]
I did mean `/^--/.test(decl.prop)`, my brain had a hanger there 😉 Would you mind submitting a PR to fix this? Thanks!

We fixed the Symbol thing a while ago, can you make sure you're running the newest version of `styled-components`?

**Comment by thisguychris** [comment]
@mxstbr sure will issue a PR in awhile.  Will pull the latest as well.

**Comment by thisguychris** [comment]
@mxstbr / @fatpc fixed at #217

**Comment by fatpc** [comment]
@thisguychris & @mxstbr thanks! will test it as well :D

**Comment by mxstbr** [comment]
Done, thanks @thisguychris!
