### ISSUE TITLE
as="" attribute doesn't work

### ISSUE THREAD

**Issue by trusktr** [styled-components/styled-components#2123]
I made a component:

```js
const Component = styled.div`
  ...
`
```

then I use it like

```js
<Component as="a" />
```

in Chrome devtools I see

```html
<div as="a" class="asdfa"></div>
```

I expect to see

```html
<a class="asdfa"></a>
```

**Comment by trusktr** [comment]
`v3.4.10`

**Comment by probablyup** [comment]
Are you using v4?

**Comment by probablyup** [comment]
Yeah it’s a new feature in v4

**Comment by trusktr** [comment]
Ah, okay, sorry about that!

**Comment by trusktr** [comment]
I was confused, because I'd just installed `styled-components` late last week, and I've been reading the docs without noticing that it updated to v4, so I didn't think within the week that the docs I was reading were for v4.
