### ISSUE TITLE
v4 components no longer work with react-flip-move

### ISSUE THREAD

**Issue by morleyzhi** [styled-components/styled-components#2124]
[React Flip Move](https://github.com/joshwcomeau/react-flip-move#gotchas) does not work with stateless functional components. 

in v3, this wasn't a problem; you could use styled components as children of ReactFlipMove components and it wouldn't complain.

In v4 however, attempting to render a ReactFlipMove component with styled children results in this error:

Error: Uncaught [TypeError: Cannot read property 'isReactComponent' of undefined]

## System:
 - OS: macOS 10.14
 - CPU: x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
 - Memory: 995.14 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 9.11.2 - ~/.nvm/versions/node/v9.11.2/bin/node
 - Yarn: 1.10.1 - ~/.nvm/versions/node/v9.11.2/bin/yarn
 - npm: 5.6.0 - ~/.nvm/versions/node/v9.11.2/bin/npm
## npmPackages:
 - babel-plugin-styled-components: 1.8.0 => 1.8.0
 - styled-components: 4.0.2 => 4.0.2

## Reproduction

Clone this repo, install, and run `yarn test`:

https://github.com/morleyzhi/styled-flip

This will show the following:

* v3 works flawlessly with react-flip-move
* v4 errors out

**Comment by probablyup** [comment]
Our components now use the forwardref API so that might be the issue.

**Comment by mxstbr** [comment]
Yeah this is an issue with react-flip-move, styled-components are still class components right now.

**Comment by morleyzhi** [comment]
Cool, I'll open a ticket with them.
