### ISSUE TITLE
Classname warning appears because loadable loading component doesn't attach it

### ISSUE THREAD

**Issue by FreddyFY** [styled-components/styled-components#2126]
When you try to style a HOC [like react-loadable] you will get a `console.warn`, that the className is not being passed down, even if it is.

## Reproduction
https://codesandbox.io/s/pyx951r0rj

## Steps to reproduce
Open the console.

## Expected Behavior
No `console.warn`

## Actual Behavior
There is this `console.warn`
`It looks like you've wrapped styled() around your React component (LoadableComponent), but the className prop is not being passed down to a child. No styles will be rendered unless className is composed within your React component. `

**Comment by mxstbr** [comment]
Ahh that's because the loading component doesn't attach the passed-in class name :confused: Not sure how we're supposed to tackle that...

/cc @probablyup

**Comment by probablyup** [comment]
I believe this is a dup of another ticket - my suggestion was to add another warning suppression prop, since it's an edge case in pretty specific circumstances.

**Comment by probablyup** [comment]
A setimeout of 0 should be sufficient

**Comment by probablyup** [comment]
But it would need to be in combination with a suppression prop. Async loading components could be many milliseconds before they finally do render, so that edge case still requires a manual suppression.

**Comment by vitalybe** [comment]
> styled(SomeComponent) is not recommended

I'm confused, I use the following pattern a lot. For example, I define a styled-component, as shown in the example file [example/example.js](https://github.com/styled-components/styled-components/blob/master/example/example.js):

```
class Example extends React.Component {
    render() {
      return (
        <Wrapper className={this.props.className}>
          <GlobalStyle />
          <Title>Hello World, this is my first styled component!</Title>
        </Wrapper>
      );
    }
  }
```

If I am using it in another component, I would style it to provide it with margins and position modifications, like so:
```
const ExampleStyled = styled(Example)`
  ${(props: {}) => css`
    margin: 1em;
    position: absolute;
  `};
`;
```

So the internal parts of the component are protected but I can reuse the component in various places, without providing it with "unnecessary" layout props.

Is it an anti-pattern somehow? Is there an alternative, suggested way?

P.S If this is offtopic, please delete this message and I'll ask it elsewhere.

**Comment by probablyup** [comment]
It is off-topic. But also not unrecommended, disregard.

**Comment by probablyup** [comment]
You'll be able to suppress the warning in the next release thanks to https://github.com/styled-components/styled-components/pull/2156

**Comment by artooras** [comment]
Thanks, the `suppressClassNameWarning` did indeed make the `className` warning go away. However, now I was receiving the error

`Warning: React does not recognize the suppressClassNameWarning prop on a DOM element...`

either when setting the `suppressClassNameWarning` as a prop or passing it in `attrs`.

In my case with `react-loadable` I managed to clear the latter as well like so:

```
const LoadableIcon = styled(Loadable({
  loader: () => import('./Icon'),
  render(loaded, {suppressClassNameWarning, ...props}) {
    const Icon = loaded.default
    return <Icon {...props} />
  },
  loading: () => <div>Loading...</div>
})).attrs({'suppressClassNameWarning': true})`
  ...your custom styles...
`
```

Perhaps this is helpful to someone.

**Comment by kuroski** [comment]
Maybe this will help someone.
In my scenario, we have mock the `Link` component.
Then you can pass the prop manually to the component:

```
jest.mock("react-router-dom", () => {
  return {
    Link: props => (
      <a href="bla.blaferson" {...props}>
        MyRant
      </a>
    )
  };
});
```

The just use the link normally.

**Comment by martonlanga** [comment]
For the folks using `Next.js`, don't forget to add this [.babelrc](https://github.com/zeit/next.js/blob/master/examples/with-styled-components/.babelrc) config to your project.
