### ISSUE TITLE
Incorrect order of styles when using StyleSheetManager

### ISSUE THREAD

**Issue by Fer0x** [styled-components/styled-components#2127]
## System:
 - OS: macOS 10.14
 - CPU: x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
 - Memory: 978.31 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 10.9.0 - ~/.nvm/versions/node/v10.9.0/bin/node
 - Yarn: 1.10.1 - /usr/local/bin/yarn
 - npm: 6.2.0 - ~/.nvm/versions/node/v10.9.0/bin/npm
## npmPackages:
 - styled-components: 4.0.2 => 4.0.2

## Reproduction

https://codesandbox.io/s/2jq9p5021r (with StyleSheetManager)
https://codesandbox.io/s/w0yr0m0p6l (without StyleSheetManager)

## Steps to reproduce

see codesandbox

## Expected Behavior

First div should have width=100%

## Actual Behavior

First div has width=150px

**Comment by mxstbr** [comment]
I think this ties into #2120 and @kitten's plan to overhaul the StyleSheet infra?

**Comment by Fer0x** [comment]
@mxstbr but it's not SSR bug in total

**Comment by mxstbr** [comment]
I know but it's a stylesheet bug where we're inserting things in the wrong order, which should be fixed by making sure the stylesheet always comes from context, right?

**Comment by Fer0x** [comment]
@mxstbr I get it. I just made a little research and found difference in behavior: without StyleSheetManger `StyleSheet.deferredInject` is used, and with StyleSheetManger - `StyleSheet.inject`.

**Comment by sarneeh** [comment]
Any news on this? Or maybe a workaround?

**Comment by probablyup** [comment]
@sarneeh try the new v5 beta! The stylesheet engine is totally reworked and should not have any of these issues.

**Comment by probablyup** [comment]
Confirmed fixed in v5 https://codesandbox.io/s/hopeful-platform-m0mzu
