### ISSUE TITLE
V4: classes not properly forwarded in some cases

### ISSUE THREAD

**Issue by mariusespejo** [styled-components/styled-components#2130]
## System:
 - OS: macOS High Sierra 10.13.6
 - CPU: x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
 - Memory: 459.63 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 8.12.0 - /usr/local/bin/node
 - Yarn: 1.10.1 - /usr/local/bin/yarn
 - npm: 6.4.1 - /usr/local/bin/npm
 - Watchman: 4.7.0 - /usr/local/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: ^1.8.0 => 1.8.0
 - styled-components: ^3.4.9 => 3.4.10

## Reproduction

https://codesandbox.io/s/w32730pr5

## Steps to reproduce
Try to extend the styles of a button from semantic-ui-react:

```javascript
import { Button as SemanticBtn } from "semantic-ui-react";
import styled from "styled-components"; // latest v4

import "semantic-ui-css/semantic.min.css";

const Button = styled(SemanticBtn)`
  &&& {
    background: green;
  }
`;

// inside render:
<Button primary>test </Button> // this gets the updated styles with semantic-ui styles properly
<Button as="a" primary> // this fails to have semantic-ui styles because the class does not get forwarded
```

## Expected Behavior

The second button should render as an anchor with the classes forwarded so that it is still styled properly like a button (Notice the expected "**ui primary button**" classes)
`<a class="ui primary button sc-bdVaJa kmcmFQ" />`

![image](https://user-images.githubusercontent.com/5385443/47243591-5e4e7780-d3a7-11e8-8108-bce84b642915.png)

Here is an example running styled-components v3.4.10 where this was previously working
https://codesandbox.io/s/62l6z2j02z

## Actual Behavior

Notice that the second button renders like this (button classes not forwarded):
`<a class="sc-bZQynM bMlcym">test </a>`

So it ends up losing some styles and does not render like a button

![image](https://user-images.githubusercontent.com/5385443/47243643-83db8100-d3a7-11e8-85f2-1187184b57e6.png)

**Comment by mxstbr** [comment]
This is expected behavior I think.

The way `as` works is that it switches out the underlying extended component, unless it's also a styled component then we merge the styles.

**Comment by diegohaz** [comment]
O wonder if it shouldn't just pass the `as` prop down if the original component is a custom component.

I pretty sure that Semantic UI handles that prop, right?

Anyway, if this were to happen, it would be only in v5.

**Comment by mariusespejo** [comment]
The `as` prop in semantic-ui-react simply changes the underlying html tag. I guess I don't understand why in the previous version styled-components properly merged the classes, while in v4 we're claiming that's expected behavior (that now it doesn't merge), @mxstbr? 

The way it works now with v4 is even custom classNames still get passed down like 
`<Button as="a" className="test" primary />` 
still ends up rendering like 
`<a class="test sc-bZQynM" />` 

It's just missing the classes "ui primary button". Regardless of what the underlying custom (semantic) component renders weather it is `<button>` or `<a>` wouldn't you want merge the styles either way? Apologies if I'm not understanding correctly. 


@probablyup would you mind explaining further? Are you saying that in v4 styled-components has its own handler for the `as` prop and that it is conflicting with semantic's (hence why it breaks)?

**Comment by probablyup** [comment]
"as" is interpreted by HOC wrappers in different ways, depending on the layer receiving the prop. If you have a `styled(Thing)` and give it an `as="div"` prop, `Thing` is not rendered and instead a div is rendered with the styles. When we add `$as` (transient prop), you'll be able to give a certain "as" to styled-components and send a different "as" to the underlying component if desired.

**Comment by probablyup** [comment]
> Are you saying that in v4 styled-components has its own handler for the as prop and that it is conflicting with semantic's (hence why it breaks)?

Exactly. But we will have a way around this soon.

**Comment by kusmierz** [comment]
Hey @probablyup, have you time to look at this?
