### ISSUE TITLE
Feature request: Aphrodite-style classnames instead of wrapping

### ISSUE THREAD

**Issue by johnnysprinkles** [styled-components/styled-components#2132]
I love writing CSS in template literals instead of transmogrifying into JS object literals! I don't love the wrapping of elements for a variety of reasons:

* Makes the markup harder to read, instead of H1's, DIVs, SPANs, etc you have to refer elsewhere to see what is what
* You have to mess around with innerRef
* Tests such as Enzyme can no longer be shallow because of the wrapping

I wish we could have the best of both worlds, such as:

    let redBox = styled.anything`
      border: 1px solid red;
    `;
    <div className={redBox.getClassName()}>Red</div>

Or something similar. My guess is that this goes against the design of styled-components at a fundamental level and wouldn't make sense to support. Maybe the best road is creating a new CSS-in-JS system that combines the best parts of Aphrodite and styled-components?

**Comment by probablyup** [comment]
I don't think we'll introduce the specific syntax you're looking for, but
emotion has the css prop that does roughly what you want.
