### ISSUE TITLE
createGlobalStyle does not work with next.js 7 when deployed to now

### ISSUE THREAD

**Issue by brianlovin** [styled-components/styled-components#2134]
## Environment

```sh
## System:
 - OS: macOS 10.14.1
 - CPU: x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
 - Memory: 125.21 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 10.6.0 - /usr/local/bin/node
 - Yarn: 1.3.2 - /usr/local/bin/yarn
 - npm: 6.1.0 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: ^1.8.0 => 1.8.0
 - styled-components: ^4.0.2 => 4.0.2
```

## Reproduction

This appears to be a problem with deploying a project using next.js v7 + styled-components v4, when the `createGlobalStyle` is used in the `_document.js` file.

## Steps to reproduce
1. Clone https://github.com/specfm/spec-next/tree/sc-4
2. Checkout `sc-4` branch
3. deploy with `now`

## Expected Behavior
The `normalize.js` file which contains the `createGlobalStyle` should be injected into the `<head>` of the document to provide global css reset styles.

## Actual Behavior
The `createGlobalStyle` does not inject the global css into the `<head>` when deployed with `now` - about 1/10 of my deploys has it *randomly* work, but most deploys will look like this:

<img width="1438" alt="screenshot 2018-10-21 23 17 27" src="https://user-images.githubusercontent.com/1923260/47279849-64e81500-d588-11e8-8022-d2ea474236d9.png">

Expected design is at [spec.fm](https://spec.fm) - the deploy live right now had to be built with `styled-components@3.x`

**Comment by brianlovin** [comment]
@mxstbr mentioned that this may be an issue of using `createGlobalStyle` in `_document.js` - to check, https://spec-next-fczfxpocww.now.sh/ works when deployed where `createGlobalStyle` is imported into `_app.js`

**Comment by probablyup** [comment]
I believe global styles need to go in _app.js or individual pages.

**Comment by mxstbr** [comment]
Yeah I think we'll have to document this in the docs somewhere, or maybe add it to the official example? /cc @timneutkens

**Comment by brianlovin** [comment]
Yup, just clarified documentation would be super helpful in this instance!

**Comment by eugeneross** [comment]
Can confirm that my team has this same issue. Was **unable** to get it working even after putting `createGlobalStyle` in `_app.js`.

**Comment by timneutkens** [comment]
I guess adding a comment in `_document.js` of the example makes sense.

**Comment by jetarin-min** [comment]
I also have this problem when using createGlobalStyle with nextjs v.7, and it happens only for the first request of built version of my project.(dev seems to be ok). I use express as a customized server for dynamic route of nextjs.

**Comment by mxstbr** [comment]
The styled-components example was recently updated, are you using the newest way of integrating the two? https://github.com/zeit/next.js/tree/canary/examples/with-styled-components

I'm using it this way and have not experienced any issues

**Comment by probablyup** [comment]
Going to close this then, since it seems a composition update on the next side is what was required.

**Comment by tcelestino** [comment]
@mxstbr, did you use `createGlobalStyle` in your project? In next.js example, there isn't about it uses this styled-components object.
