### ISSUE TITLE
"attrs" passes through "as" prop

### ISSUE THREAD

**Issue by dimitriirybakov** [styled-components/styled-components#2135]
## System:
 - OS: macOS 10.14
 - CPU: x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
 - Memory: 2.14 GB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 10.11.0 - ~/.nvm/versions/node/v10.11.0/bin/node
 - npm: 6.4.1 - ~/.nvm/versions/node/v10.11.0/bin/npm
## npmPackages:
 - @types/styled-components: ^4.0.1 => 4.0.1 
 - babel-plugin-styled-components: ^1.8.0 => 1.8.0 
 - styled-components: ^4.0.2 => 4.0.2 

## Reproduction

https://codesandbox.io/s/0xvjx5qq30

## Steps to reproduce
Just see the console

## Expected Behavior
"as" prop shouldn't be passed

**Comment by probablyup** [comment]
Dup of #2131

**Comment by dimitriirybakov** [comment]
@probablyup I don't really understand how it is duplicate. This problem is about different behavior of "as" prop with and without attrs

**Comment by probablyup** [comment]
Same root problem
