### ISSUE TITLE
background-image break down all next global styles

### ISSUE THREAD

**Issue by olegreznichenko** [styled-components/styled-components#2138]
Want re-open closed issue https://github.com/styled-components/styled-components/issues/2121. Unfortunately, it was not properly rewired with miscommunication.

## Reproduction
https://codesandbox.io/s/1qxl697vjj

## Steps to reproduce
Comments in codesandbox
## Expected Behavior
Comments in codesandbox

@mxstbr please check this out when you have free time.

**Comment by kitten** [comment]
Mate, please don't just open new issues. We're happy to address the other issue but we're not available every day, so often it can take more than a couple of hours :) I'll reply in the other thread, so that we can keep it in one place
