### ISSUE TITLE
Feature discussion: pre-processor for ".styled" files with styled-components syntax

### ISSUE THREAD

**Issue by michaelauderer** [styled-components/styled-components#2141]
When writing lots of styled components for a container, we extract them out into their own file next to the container. For example, `home-page.jsx` would have a neighbor file `home-page.styles.js` that looks something like:
```js
export const Wrapper = styled.div`
  display: inline-block;
  border-radius: 3px;
  padding: 0.5rem 0;
  margin: 0.5rem 1rem;
  ${props => props.primary && css`
    background: white;
    color: palevioletred;
  `}
`

export const StyledText = styled.span`
  color: palevioletred;
  font-size: 16px;
`

export const LargeStyledText = styled(StyledText)`
  font-size: 48px;
`
```

This does the job, but I see an opportunity for a big improvement here. Imagine if we additionally had a preprocessor that allowed for a file format like this:
```
Wrapper (div) {
  display: inline-block;
  border-radius: 3px;
  padding: 0.5rem 0;
  margin: 0.5rem 1rem;
  ${props => props.primary && css`
    background: white;
    color: palevioletred;
  `}
}

StyledText (span) {
  color: palevioletred;
  font-size: 16px;
}

LargeStyledText (StyledText) {
  font-size: 48px;
}
```

The file extension could be .styled, so in the previous example we would have `home-page.jsx` and `home-page.styled`.

This would probably need to involve some sort of babel manipulation to actually import these components into the app. Ideally, we could get imports working like:
```
import { StyledText, LargeStyledText } from './home-page.styled'
```
Is this possible with a custom babel plugin?

The main reasons for doing all of this:

- Easier to read and scan
- Feels much more familiar to css

What do you think? Would you find this helpful to your development, or is this idea a waste of effort?

**Comment by mxstbr** [comment]
We probably wouldn't do that, as a large part of the point of styled component is that it's just JavaScript™️!

**Comment by probablyup** [comment]
Just JavaScript and Just CSS :) we're trying to keep things feeling as close to the metal as possible.
