### ISSUE TITLE
4.0 styled(Component) not returning component

### ISSUE THREAD

**Issue by seanemmer** [styled-components/styled-components#2143]
Since upgrading to 4.0 styled(Component) no longer returns a react component, but instead returns an object literal:

```
import * as React from 'react'
import styled from 'styledComponents'

import { LauncherContainer, WindowContainer } from 'components'
import { Flex } from 'components/_utility'

export interface Props {
  className?: string,
}

const Component = ({ className }: Props) => (
  <div className={className} >
    <Flex column alignItems='flex-end'>
      <WindowContainer />
      <LauncherContainer />
    </Flex>
  </div>
)

export const FrameDisplay = styled(Component)`
  background-color: red;
`
```

Error: 

![image](https://user-images.githubusercontent.com/8183188/47326280-de314780-d61c-11e8-97a7-817a9adecb8b.png)

**Comment by probablyup** [comment]
Dup of https://github.com/styled-components/styled-components/issues/2106. You'll need to hold off on your 4.0 upgrade until `react-redux` supports `React.forwardRef`.
