### ISSUE TITLE
Unmentioned breaking change from v3 to v4 or bug: withComponent

### ISSUE THREAD

**Issue by asafigan** [styled-components/styled-components#2144]
I had a sneaky bug when upgrading. I redid my code to use `style(X)` instead of `X.extend`. I thought all was well until I found some edge cases with `withComponent`. Basically `withComponent` replaces the styled component rather than that component's child. So `as` and `withComponent` have different behavior.

I don't know if this is intentional or not. I am assuming that this is `withComponent`'s original behavior. I believe that this should have been mentioned in the [migration guide](https://www.styled-components.com/docs/faqs#what-do-i-need-to-do-to-migrate-to-v4). As the migration guide is written now it seems like you wouldn't get any bugs by just switching to the new api. But if you use `withComponent` you will.

I don't know if we should change how the code works, but we should at least warn people.

## System:
 - OS: Linux 4.9 Debian GNU/Linux 8 (jessie) 8 (jessie)
 - CPU: x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
 - Memory: 127.57 MB / 1.95 GB
 - Container: Yes
 - Shell: 4.3.30 - /bin/bash
## Binaries:
 - Node: 8.11.4 - /usr/local/bin/node
 - Yarn: 1.6.0 - /usr/local/bin/yarn
 - npm: 5.6.0 - /usr/local/bin/npm
## npmPackages:
 - styled-components: ^4.0.2 => 4.0.2

## Reproduction
```
Title.extend``.withComponent('h1')
styled(Title)``.withComponent('h1')
```
Top keeps all styles.
Bottom removes all styles.
https://codesandbox.io/s/0y90mkm6zp

## Steps to reproduce
Style a styled component than use `withComponent`.

## Expected Behavior
To have the same behavior as extending a styled component and using `withComponent`.
## Actual Behavior
The component only has the outer styles.

**Comment by probablyup** [comment]
Try using the ["as" prop or attr](https://www.styled-components.com/docs/api#as-polymorphic-prop) instead of `withComponent`. You're right though that wasn't specifically called out in the migration guide. Want to add it over at https://github.com/styled-components/styled-components-website?

**Comment by asafigan** [comment]
Thank you I didn't know about that repo. I added it as an issue on the website.
