### ISSUE TITLE
"as" polymorphic prop does not work properly for overlapping styles

### ISSUE THREAD

**Issue by meiriko** [styled-components/styled-components#2145]
## System:
 - OS: macOS High Sierra 10.13.6
 - CPU: x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
 - Memory: 116.98 MB / 16.00 GB
 - Shell: 2.7.1 - /usr/local/bin/fish
## Binaries:
 - Node: 10.9.0 - /usr/local/bin/node
 - Yarn: 1.9.4 - /usr/local/bin/yarn
 - npm: 6.2.0 - /usr/local/bin/npm
## npmPackages:
 - styled-components: 4.0.0-beta.4 => 4.0.0-beta.4 

## Steps to reproduce

https://codesandbox.io/s/p9q7k6qplm

Create 2 styled components (SC1, SC2) that overlap for a specific style, for example the border.
Now, instantiate
```
<SC1 as={SC2}>SC1 as SC2</SC1>
<SC2 as={SC1}>SC2 as SC1</SC2>
```

Both cases will take the value from the SC that was defined last. So if you have
```
const SC1 = ...
const SC2 = ...
```

SC2 will set the final value.

If you change it to

```
const SC2 = ...
const SC1 = ...
```

SC1 will set the final value.

## Expected Behavior
Elements 1-2 should have different border color (same for elemants 3-4)

## Actual Behavior
Elements 1-2 have the same border color (same for elements 3-4)

**Comment by probablyup** [comment]
They both are generating a single styling class and thus are at the same specificity, so CSS injection order comes into play. If you put a precedence boost on the one you want to act as an override, that will fix the issue (See the last paragraph in this section e.g. `&&` https://www.styled-components.com/docs/basics#pseudoelements-pseudoselectors-and-nesting)
