### ISSUE TITLE
React 16.6 Class.contextType support

### ISSUE THREAD

**Issue by drakang4** [styled-components/styled-components#2148]
React 16.6 released and [Class.contextType](https://reactjs.org/docs/context.html#classcontexttype) added.

I'm trying to use this with styled-componenets' theme context. `contextType` needs a Context object created by `React.createContext()`, but styled-components does not export it.

Creating context object using ThemeProvider and ThemeContext as a workaround makes an error:

> Warning: Component defines an invalid contextType. contextType should point to the Context object returned by React.createContext(). Did you accidentally pass the Context.Provider instead?

So, the context object should be provided to work with `contextType` property on a React class component.

**Comment by probablyup** [comment]
Yeah I suppose we can go ahead and expose the `ThemeContext` as well. Want to PR it?
