### ISSUE TITLE
Importing local fonts using @font-face not working

### ISSUE THREAD

**Issue by ConnorTCM** [styled-components/styled-components#2153]
## System:
 - OS: macOS 10.14
 - CPU: x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
 - Memory: 671.60 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 10.11.0 - /usr/local/bin/node
 - Yarn: 1.10.1 - /usr/local/bin/yarn
 - npm: 6.4.1 - /usr/local/bin/npm
## npmPackages:
 - babel-plugin-styled-components: 1.8.0 => 1.8.0 
 - styled-components: 4.0.2 => 4.0.2

## Steps to reproduce
Add a local 'fonts' directory that has multiple different font files (.eot, .svg, .ttf, .woff, .woff2). Create a helper function to avoid having to manually import each font file (in my case there are 40 files). Include the global style on the page.

```
import React from 'react';
import { createGlobalStyle } from 'styled-components';

function fontFace(fontFamily, src, svgName, fontWeight, fontStyle) {
  return `
    @font-face {
      font-family: '${fontFamily}';
      src: url(${require(`../fonts/${src}.eot`)});
      src: url(${require(`../fonts/${src}.eot?#iefix`)}) format('embedded-opentype'),
           url(${require(`../fonts/${src}.woff2`)}') format('woff2'),
           url(${require(`../fonts/${src}.woff`)}) format('woff'),
           url(${require(`../fonts/${src}.ttf`)}) format('truetype'),
           url(${require(`../fonts/${src}.svg`)}#${svgName}) format('svg');
      font-weight: ${fontWeight};
      font-style: ${fontStyle};
    }
  `;
}

const GlobalStyle = createGlobalStyle`
  ${fontFace(`euclid-flex`, `EuclidFlex-Bold-WebS`, `euclidflexbold`, `bold`, `normal`)};
  ${fontFace(`euclid-flex`, `EuclidFlex-BoldItalic-WebS`, `euclidflexbolditalic`, `bold`, `italic`)};
  ${fontFace(`euclid-flex`, `EuclidFlex-Medium-WebS`, `euclidflexmedium`, `500`, `normal`)};
  ${fontFace(`euclid-flex`, `EuclidFlex-MediumItalic-WebS`, `euclidflexmediumitalic`, `500`, `italic`)};
  ${fontFace(`euclid-flex`, `EuclidFlex-Regular-WebS`, `euclidflexregular`, `normal`, `normal`)};
  ${fontFace(`euclid-flex`, `EuclidFlex-RegularItalic-WebS`, `euclidflexregularitalic`, `normal`, `italic`)};
  ${fontFace(`euclid-flex`, `EuclidFlex-Light-WebS`, `euclidflexlight`, `300`, `normal`)};
  ${fontFace(`euclid-flex`, `EuclidFlex-LightItalic-WebS`, `euclidflexlightitalic`, `300`, `italic`)};

  body {
    font-family: 'euclid-flex', serif;
    color: red;
  }
`;

const IndexPage = () => (

  <body>
      <h1>Test</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras suscipit ante sit amet nisl molestie, ac gravida dui congue. Morbi nec pretium purus. Donec egestas est sit amet erat feugiat, ac elementum dolor mollis.</p>
  </body>
);

export default IndexPage;
```

## Expected Behavior
All text on the page to use 'euclid-flex' font-family.

## Actual Behavior
Text doesn't render with 'euclid-flex', instead it renders with the fallback.

The global styles are added in the <head> tag and can be seen when inspecting elements (the text is all red as per the global style so I know it isn't a selector issue). The references to the fonts appear to be correct (I can download the fonts if I copy and paste the src into the url bar). Example output...

`@font-face{font-family:'euclid-flex';src:url(http://localhost:8000/static/EuclidFlex-Bold-WebS-3c2e6d983d28e14245bc832374219312.eot);src:url(http://localhost:8000/static/EuclidFlex-Bold-WebS-3c2e6d983d28e14245bc832374219312.eot) format('embedded-opentype'), url(http://localhost:8000/static/EuclidFlex-Bold-WebS-056ba1e9da1f5ffe7f96f14f3fcfd39f.woff2') format('woff2'),           url(http://localhost:8000/static/EuclidFlex-Bold-WebS-69cdb37eb3a6688993eb1ea093d0ebc2.woff) format('woff'),           url(http://localhost:8000/static/EuclidFlex-Bold-WebS-285cb103dd097fc417d1b99d624b1035.ttf) format('truetype'),           url(http://localhost:8000/static/EuclidFlex-Bold-WebS-52cd60b63e0734697cb1850b27f83c98.svg#euclidflexbold) format('svg');      font-weight: bold;      font-style: normal;}`

Not sure if this is something to do with using `require` rather than `import` in my helper function? I couldn't think of a way to use `import` without having to manually write all of the imports.

**Comment by ConnorTCM** [comment]
Worth noting that if I import that it works e.g.

import euclidRegularWoff2 from '../fonts/EuclidFlex-Regular-WebS.woff2';

const GlobalStyle = createGlobalStyle`
  @font-face {
    font-family: 'euclid-flex';
    src: url(${euclidRegularWoff2}) format('woff2');
    font-weight: 'normal';
    font-style: 'normal';
  }

  body {
      font-family: 'euclid-flex', serif;
      color: red;
  }
}

**Comment by kitten** [comment]
- It doesn't look like you're including `GlobalStyle` as an element? It needs to be mounted to take effect
- If you're importing and it works that means you're *bundling* fonts
- styled-components doesn't and can't do any bundling, so if you give it a relative path that's just a CSS string and Webpack is unaware of it, as it should be :wink:

So make sure `GlobalStyle` is being applied and that you either let your bundler take care of the fonts or move it to a publicly served directory and change your url path to an absolute url.
