### ISSUE TITLE
Slight improvements to Sandbox

### ISSUE THREAD

**Issue by lustoykov** [styled-components/styled-components#2155]
Not a feature or a bug, slight improvement suggestions for sandbox:

**First suggestion**

Update to latest version of React 
Reason: Support `React.memo`

---

**Second suggestion:**  

Rewrite 

```js
const content = [<MemoButton>Memo Button</MemoButton>, <Button primary>Primary Button</Button>];
```

to 
```js
const content = (
  <React.Fragment>
    <MemoButton>Memo Button</MemoButton>
    <Button primary>Primary Button</Button>
  </React.Fragment>
);
```

Reason: Remove warning for missing "keys" _(Each child in an array or iterator should have a unique "key" prop)_

I don't know the rationale behind using an array, so I figured out to ask first - maybe you've decided for an array because it's easier for people newer to the ecosystem.

**Question: Would you accept PR for those?**

**Comment by BofEmptiness** [comment]
Maybe it's the same request? https://github.com/styled-components/styled-components/issues/2146

**Comment by lustoykov** [comment]
Hey, thanks for pointing this out. The project itself has been updated, so it's compatible with React.memo, but sandbox not (they have separate package.json as far as I see), therefore sandbox & production don't have the same version. Part of this proposal is to have them use the same version.

**Comment by probablyup** [comment]
We could probably use yarn workspaces for the sandbox to keep this in sync more easily
