### ISSUE TITLE
ThemeProvider and GlobalStyles in latest version 4

### ISSUE THREAD

**Issue by mhaagens** [styled-components/styled-components#2158]
Thought I'd report some findings I've had trying to switch to version 4.
Love styled-components and hoping this is just me doing something wrong, but just in case I'll report it here.

I have a server rendered React app using Express + Apollo Server and styled-components.
I've run into some issues;

* `<ThemeProvider />` breaks React Apollo during SSR (queries are not run on the server).
They run fine when I remove ThemeProvider (and `<GlobalStyles />`)
* `<GlobalStyles />` needs to be wrapped inside a styled.X component for it to work with HMR / React Hot Loader. If it is moved outside HMR will not work. If `<GlobalStyles />` is inside the styled component it reports this error;
````
"The global style component sc-global-3461151225 was composed and rendered multiple times in your React component tree. Only the last-rendered copy will have its styles remain in "
````

I downgraded to version 3.4.5 and now queries run as expected again on the server with `<ThemeProvider />` and `injectGlobal`.

Thanks for all the awesome work you do!

### System:
 - OS: macOS High Sierra 10.13.6
 - CPU: x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 472.64 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
### Binaries:
 - Node: 10.11.0 - ~/.nvm/versions/node/v10.11.0/bin/node
 - npm: 6.4.1 - ~/.nvm/versions/node/v10.11.0/bin/npm

## Reproduction

Here's a repo to illustrate the HMR issue, unfortunately I don't have Apollo set up there to test the queries; https://github.com/mhaagens/styled_globalstyles_hmr

## Steps to reproduce

Wrap `<ThemeProvider />`around your top level app and use `<GlobalStyles />` for global styling.

## Expected Behavior
Apollo Queries should run as normal on the server.
HMR should work.

## Actual Behavior
Apollo Queries stop running on the server.
HMR does not work if `<GlobalStyles />` isn't wrapped in a styled component.
If it is wrapped HMR works, but it reports errors.
Downgrading to 3.4.5 solves the query issue and HMR isn't supposed to work AFAIK.

**Comment by probablyup** [comment]
> `<GlobalStyles />` needs to be wrapped inside a styled.X component for it to work with HMR / React Hot Loader. 

Hmm, that's strange. During the beta we definitely tested cGS with a vanilla element root and it was working. I wonder if it's a strange interaction with apollo

**Comment by probablyup** [comment]
I tried running your example repo and it just brought me to a file directory page. Is there supposed to be an index to look at?

**Comment by joaogarin** [comment]
hello, I am experiencing the exact same problem in a very similar stack, the new v4 release is breaking SSR on a nextjs app that uses apollo as well.+

**Comment by pitops** [comment]
I am having similar issues with NextJS and Apollo. I have also narrowed it down to ThemeProvider rendering the components twice. (double console logs on page refresh).

**Comment by joaogarin** [comment]
Yeah its easily reproduceable at least with nextjs and apollo. For now reverted back to 3.4.10 where its working properly. My repo above is a good way to test the issue I guess..its minimal basicaly a combination of with-apollo and with-styled-components from the nextjs examples folder.

**Comment by NourSammour** [comment]
> https://github.com/joaogarin/styled-v4-next-withapollo

> Yeah its easily reproduceable at least with nextjs and apollo. For now reverted back to 3.4.10 where its working properly. My repo above is a good way to test the issue I guess..its minimal basicaly a combination of with-apollo and with-styled-components from the nextjs examples folder.

@joaogarin i've tried to update `"react-apollo": "2.3.0"` and it's working well with `styled-component v4`, and the issue solved 💃

**Comment by probablyup** [comment]
Going to close based on @NourSammour's comment and since there's nothing to be done on our side.

**Comment by mhaagens** [comment]
But the issue with HMR persists?
Started from scratch, still the same problem.
Repo here;
https://github.com/mhaagens/broken_hmr_styled

Try to update the state, then change the styles in Wrapper (styled component). The state will be reset.
If I remove the Wrapper then everything works as expected in terms of HMR, but then GlobalStyles will no longer hot reload.

**Comment by mhaagens** [comment]
**Update:**
HMR works if you remove the `<Wrapper>` around the app and add a prop to the `<GlobalStyle />` component. Then state is persisted between hot reloads.

**Comment by probablyup** [comment]
So I think part of the issue is that HMR without react-hot-loader totally wipes away the component and makes a new copy without running the unmount cycle of the first version until after the second is mounted. The loss of internal state means global styles will have super inconsistent results since the lifecycle order is all messed up.

I'm vaguely curious why adding a prop changes that...

With RHL it should definitely work though since it makes more of an effort to gently migrate the React tree. If it doesn't then let me know and we can diagnose.

**Comment by csalmeida** [comment]
I am experiencing a similar issue with `injectGlobal` with version `^4.1.3` and get the error below. This is fixed when rolling back to `3.4.5` as @mhaagens suggested.

**Failed to compile**
```
./src/Styles/index.js
Attempted import error: 'injectGlobal' is not exported from 'styled-components'.
```

**Comment by probablyup** [comment]
Look at the v4 migration guide, that API was replaced...

**Comment by csalmeida** [comment]
Thanks @probablyup, [I've followed the migration guide](https://www.styled-components.com/docs/faqs#what-do-i-need-to-do-to-migrate-to-v4) and using `createGlobalStyle` worked perfectly.

Also the fact that the guide complements examples with incorrect ones it's great! 🎉
