### ISSUE TITLE
A way to get rid of Consumer in devtool

### ISSUE THREAD

**Issue by sonhanguyen** [styled-components/styled-components#2160]
"Consumer" polluting the tree makes debugging harder
- Could switching to the new contextType help?
- Not my use case but some people probably appreciate a way to opt out of theme?

**Comment by kitten** [comment]
I absolutely agree with your assessment; unfortunately we also have context for our style sheets which is necessary for SSR and the StylesheetManager.

Context Type could temporarily help with one of them if we don't want to mix any concerns.

However, it'd probably be wiser to wait this out and opt for Hooks once they're ready

**Comment by probablyup** [comment]
> Could switching to the new contextType help?

Maybe, but it requires React 16.6 and enforcing that requires a semver-major change.

**Comment by probablyup** [comment]
Going to close this as there's nothing we can do at this time.
