### ISSUE TITLE
Bug on styled-components.com - unterminated comment crashes site

### ISSUE THREAD

**Issue by adrianhelvik** [styled-components/styled-components#2161]
## Environment
Chrome 70, on an iMac on styled-components.com.

## Reproduction
Change the style for the Button component like this:

```
const Button = styled.a`
  /*
`

render(
  <div>
    <Button
      href="https://github.com/styled-components/styled-components"
      target="_blank"
      rel="noopener"
      primary
    >
      GitHub
    </Button>

    <Button as={Link} href="/docs" prefetch>
      Documentation
    </Button>
  </div>
)
```

## Steps to reproduce
1. Copy/paste the code above into the editor on the website
2. Try to do anything

## Expected Behavior
It should treat the rest of the styling as a comment.

## Actual Behavior
The browser becomes unresponsive and must be force exited.

**Comment by probablyup** [comment]
Can you move this over to the website repo?

**Comment by adrianhelvik** [comment]
Okay.
