### ISSUE TITLE
`undefined is not an object argv.indexOf` when used with `styled-components/native`

### ISSUE THREAD

**Issue by developer239** [styled-components/styled-components#2163]
Application breaks when I import `styled-components`. **`styled-components` worked fine until I installed `native-base`.**  🙂 Any ideas what is happening?

```
Node: v10.11.0
npm: 6.4.1
```

```
  "dependencies": {
    "native-base": "^2.8.1",
    "react": "^16.7.0-alpha.0",
    "react-native": "0.56.1",
    "react-native-navigation": "^2.0.2608",
    "styled-components": "^4.0.2"
  },
```

```
import React from 'react'
import { View, Text } from 'react-native'
import styled from 'styled-components/native' // importing this line breaks the application when I install `native-base`

export default () => (
  <View>
    <Text>Screen</Text>
  </View>
)
```

![image](https://user-images.githubusercontent.com/14946081/47599369-6dae6180-d961-11e8-837f-2751752c6dd4.png)

**Comment by probablyup** [comment]
Install supports-color. There’s some sort of bundler bug

**Comment by developer239** [comment]
@probablyup it worked. Thank you so much. Is there an explanation to it? 😅

**Comment by probablyup** [comment]
No idea, haha. Some sort of package manager thing. Someone else reported it
too but it’s not a package we use so who knows

**Comment by developer239** [comment]
For feature reference this is the package:

`yarn add supports-color -D` resolves the problem

https://www.npmjs.com/package/supports-color
