### ISSUE TITLE
Amendment to ref documentation

### ISSUE THREAD

**Issue by LAITONEN** [styled-components/styled-components#2164]
**Did not find any button on the website to edit the documentation like React's website does, so I am forced to create an issue.**

### **Issue:**
[This](https://www.styled-components.com/docs/advanced#refs) particular section about refs has a confusing note saying:

> Using an older version of styled-components (v3 and lower) or of React? Use the innerRef prop instead.

I had styled-components 3.4.2, which is higher than v3 (which I interpreted as 3.0.0) and yet `ref` prop did not work in an expected way until I finally figured out that I needed to replace this attribute with `innerRef`, because v3 probably meant any version starting with number 3. 

This resulted in me spending several hours trying to figure out the issue and solving another adjacent issue simultaneously, which resulted in creation of a [question on StackoverFlow](https://stackoverflow.com/questions/53023869/react-refs-cannot-read-property-focus-of-null) and [pull request in React's GitHub repository](https://github.com/reactjs/reactjs.org/pull/1329).

### **Suggestion**

The suggestion is to amend the note by replacing `v3 and lower` with `below 4` (or any other more clear means of communicating the information about version number):

> Using an older version of styled-components (below 4.0.0) or of React? Use the innerRef prop instead.

**Comment by Fer0x** [comment]
@LAITONEN
You could create PR in https://github.com/styled-components/styled-components-website

**Comment by mxstbr** [comment]
Yes please, a PR would be appreciated!
