### ISSUE TITLE
style objects do not evaluate correct pixels given a number

### ISSUE THREAD

**Issue by minheq** [styled-components/styled-components#2165]
## Environment
Codesandbox

## Reproduction
https://codesandbox.io/s/k0ql0znm5r

## Steps to reproduce
Create given component
```
const BadComponent = styled('div')(() => ({
  height: 300,
  backgroundColor: 'red',
  color: 'white'
}))
```
## Expected Behavior
In CSS it should have `height: 300px`

It works with 
```
const GoodComponent = styled('div')(() => ({
  height: '300px',
  ...
}))
```

## Actual Behavior
It wrongly parses height value:
![image](https://user-images.githubusercontent.com/9356633/47613065-60f15100-daba-11e8-856e-13e4c753c80e.png)

**Comment by Fer0x** [comment]
In my project I have used slightly modified copy of https://github.com/facebook/react/blob/master/packages/react-dom/src/shared/dangerousStyleValue.js to add px to unitless numbers.

IDK, is core styled-components team have in plans to make this working out of box.

**Comment by probablyup** [comment]
I don't think we'll be able to support this without bloating the library with logic to remember what properties need units, sorry.
