### ISSUE TITLE
Add StyledProvider

### ISSUE THREAD

**Issue by probablyup** [styled-components/styled-components#2167]
There's been a decent amount of discussion and feature requests around customizing default behaviors of styled components, so let's make it happen.

Here are some of the individual requests:

- scoped selectors https://github.com/styled-components/styled-components/issues/1789
- ability to disable vendor prefixing https://github.com/styled-components/styled-components/issues/719
- disabling speedy mode https://github.com/styled-components/styled-components/issues/2038

It's been proposed by @kitten I believe that we could add another context provider/consumer combo to facilitate configuration overrides that do not need to be performed every time a styled component is created.

**Comment by Fer0x** [comment]
@probablyup Can `<StyleSheetManager />` handle it?

**Comment by probablyup** [comment]
The setup is more complicated for that since you have to initialize the
sheet for it? But yeah if we can make it easy

**Comment by probablyup** [comment]
Maybe we could edit `StyleSheetManager` to turn it into the "StyledProvider"

**Comment by imbhargav5** [comment]
So should we allow users to use `StyledProvider` multiple times throughout the app? I think "scope" requires that they be able to use it multiple times in the tree.

**Comment by probablyup** [comment]
It should only be used once yeah.

**Comment by Fer0x** [comment]
But `StyleSheetManager` can be used multiple times, for example, in my project I have three instances of StyleSheetManager, because I have three local frames created by react-frame-component.

**Comment by probablyup** [comment]
> DISABLE_SPEEDY , as I understand it, is a flag that will apply to the project as a whole, isn't it?

Yes that's true, it's an all or nothing sort of thing since we don't shard the stylesheets at runtime except in high rule volume scenarios. If we did want to allow partial subtrees to disable speedy mode, we'd need to have each `StyledProvider` make a new StyleSheet instance and somehow link up the DOM style tag with a particular instance. That sort of thing would require a babel visitor to make a stable reference hash to be used in SSR+client.

**Comment by imbhargav5** [comment]
@probablyup  What if we just released a ScopeProvider since we want partial subtrees to have scope? StyledProvider with scope (prefix) support and DISABLE_SPEEDY and DISABLE_VENDOR_PREFIXES seems like it is trying to be too many things at once.

**Comment by probablyup** [comment]
Most of this has landed in canary
