### ISSUE TITLE
Wrong warning

### ISSUE THREAD

**Issue by isi-gach** [styled-components/styled-components#2169]
### System:
 - OS: macOS 10.14
 - CPU: x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
 - Memory: 90.97 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
### Binaries:
 - Node: 8.11.3 - ~/.nvm/versions/node/v8.11.3/bin/node
 - Yarn: 1.10.1 - /usr/local/bin/yarn
 - npm: 5.6.0 - ~/.nvm/versions/node/v8.11.3/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
### npmPackages:
 - styled-components: ^4.0.2 => 4.0.2

## Reproduction

https://codesandbox.io/s/2wmmrz8qz0?expanddevtools=1

## Steps to reproduce

Open the link above, the console will show a wrong warning

## Expected Behavior

No warnings in console

## Actual Behavior

I get the following warning:
> It looks like you've wrapped styled() around your React component (Modal), but the className prop is not being passed down to a child. No styles will be rendered unless className is composed within your React component.

but the styles are rendered properly (yellow background for the modal)

**Comment by probablyup** [comment]
The issue is the `className` is not present until you've clicked the button to turn on the modal. This is definitely an edge case though and you can [suppress the warning with this prop](https://github.com/styled-components/styled-components/pull/2156) after we cut a release later today.
