### ISSUE TITLE
problem with @media 1++ 

### ISSUE THREAD

**Issue by enderlabo** [styled-components/styled-components#2174]
Hi everybody i try it to add some @media with StyledComponent, when i set 2 @media don't work, only work the first @media but the second is null (the browser don't take this condition) so it's my code: if i do some wrong please tell me.

Sorry for my EnglishLive..

```js
const Cuadrado = styled.div`

@media only screen and (max-width : 768px) and (max-device-width : 1024px) and (orientation : portrait) and (-webkit-min-device-pixel-ratio : 1) {
     #carrosel{
      background: blue;
    }
}
@media only screen and (max-width: 425px) and (max-device-witdh: 1024px) and (orientation: portrait) and (-webkit-min-device-pixel-ratio: 1) {
  #carrosel{
  background: orange;
      }
    }
 }`
```

**Comment by Fer0x** [comment]
@enderlabo Firstly, you have an extra bracket in second media query. Secondly, please, provide a reproduction with https://codesandbox.io

**Comment by enderlabo** [comment]
ty @Fer0x i found styled-component-breakpoint https://github.com/jameslnewell/styled-components-breakpoint so i can fix my problem, thank's.
