### ISSUE TITLE
Primitive components do not receive theme prop on 4.0.3

### ISSUE THREAD

**Issue by thecalvinchan** [styled-components/styled-components#2179]
## System:
 - OS: macOS 10.14
 - CPU: x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
 - Memory: 148.18 MB / 16.00 GB
 - Shell: 5.4.2 - /usr/local/bin/zsh
## Binaries:
 - Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
 - Yarn: 1.7.0 - /usr/local/bin/yarn
 - npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm

## Reproduction

https://codesandbox.io/s/8zmy421828

## Steps to reproduce

render a styled component from `styled-components/primitives` and try to access theme prop

## Expected Behavior

primitive components should receive theme prop if rendered inside a `ThemeProvider`

## Actual Behavior

primitive components do not receive theme prop if rendered inside a `ThemeProvider`

**Comment by probablyup** [comment]
It does work, but the sandbox is importing `ThemeProvider` from "styled-components" instead of "styled-components/primitives". They're different invocations of all the base models, so it's important to use a consistent set.

**Comment by thecalvinchan** [comment]
cool thanks.

If I have an app that uses both, `styled-components` and `styled-components/primitives`, should I be wrapping my app in 2 ThemeProviders? one for each set?

**Comment by Volune** [comment]
> Why would you use both in the same app?

I have the same issue. I'm making a component library with styled-components/primitives, but I'm relying on styled-components or styled-components/native for a few platform-specific implementations.

I will have to use two providers (one of them depending on the platform), which is not convenient as the theme is the same for all components.
