### ISSUE TITLE
css doesn't support native &:active &:hover in web, but extend work ?

### ISSUE THREAD

**Issue by PetroPavlenko** [styled-components/styled-components#2181]
- I checked 3 times issues and docs, and cannot understood: Is that bug or feature?
- css doesn't support native &:active &hover ?
css [link](https://www.styled-components.com/docs/api#css)

Reproduce:
- that works 
```
const getBorderAffectsCSS = props => `
        border-color: ${props.color};
        &:hover {
            border-color: ${darken(0.02, props.color)};
        }
        &:active {
            border-color: ${darken(0.04, props.color)};
        }
    `
```
- that doesn't 
``` 
const getBorderAffectsCSS = props => css`
  border-color: ${props => props.color}; //wroks
        &:hover {
            border-color: ${props => darken(0.02, props.color)}; // doesn't wrok
        }
        &:active {
            border-color: ${props => darken(0.04, props.color)}; // doesn't wrok
        }
`
```

Feature request?
- support mixin pseudo classes !!! 🤔 
- that will help in _composition over inheritance_

## System:
 - OS: macOS 10.14
 - CPU: x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
 - Memory: 110.73 MB / 8.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 10.7.0 - ~/.nvm/versions/node/v10.7.0/bin/node
 - Yarn: 1.10.1 - ~/.nvm/versions/node/v10.7.0/bin/yarn
 - npm: 6.1.0 - ~/.nvm/versions/node/v10.7.0/bin/npm
 - Watchman: 4.7.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ~4.0.3 => 4.0.3

**Comment by aesthytik** [comment]
why have you used 'css' word in styled component after that arrow notation? Haven't seen it used before!

**Comment by PetroPavlenko** [comment]
Sorry it was:
const getBorderAffectsCSS = css`
  border-color: ${props => props.color}; //wroks
        &:hover {
            border-color: ${props => darken(0.02, props.color)}; // doesn't wrok
        }
        &:active {
            border-color: ${props => darken(0.04, props.color)}; // doesn't wrok
        }
`

**Comment by probablyup** [comment]
Can you post a reproduction repo / codesandbox? Not really sure what you're doing here.

**Comment by PetroPavlenko** [comment]
I'll prepare that on weekends

**Comment by kitten** [comment]
By native do you mean React Native?

**Comment by PetroPavlenko** [comment]
@kitten No

**Comment by PetroPavlenko** [comment]
https://codesandbox.io/s/l29r18pvqq
I just created codesandbox and it works 🤔 
Then double checked my project and found that somewhere is used `props => css`` `
Sorry bothered you. Thanks for help ;)
