### ISSUE TITLE
TypeScript: Type of `ref` unclear

### ISSUE THREAD

**Issue by tp** [styled-components/styled-components#2182]
## Environment

```
## System:
 - OS: macOS 10.14
 - CPU: x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
 - Memory: 1.63 GB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 10.12.0 - /usr/local/bin/node
 - Yarn: 1.9.4 - ~/Sources/aboutyou-mobile-web-react/node_modules/.bin/yarn
 - npm: 6.4.1 - /usr/local/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.6.2 => 1.8.0
 - styled-components: ^4.0.3 => 4.0.3
 - typescript: => 3.1.5
```

## Reproduction

```
const Text = styled<{fontSize: number}, 'span'>('span')`
  font-size: ${props => props.fontSize}px;
`;

const ref = React.createRef<???>();

const Component = () => {
  return <Text ref={ref} fontSize={12} />;
};
```

## Expected Behavior

I would assume that one can pass a `React.RefObject<HTMLSpanElement>` to the `ref` property. Ideally even something more specific to the styled component.

## Actual Behavior

For the `???` neither `HTMLSpanElment` nor `typeof Text` work. What's expected here?

**Comment by probablyup** [comment]
Can you move this to DefinitelyTyped please? We don't keep the typings here anymore.

**Comment by sisyphsu** [comment]
Meet the same issue... and can't find any solution

**Comment by probablyup** [comment]
Great... post in DT.

**Comment by khusamov** [comment]
Hi! How to solve this problem? https://github.com/DefinitelyTyped/DefinitelyTyped/issues/30225
