### ISSUE TITLE
RGB background breaks when missing semicolon

### ISSUE THREAD

**Issue by vinnymac** [styled-components/styled-components#2186]
## Environment
Chrome 70

## Reproduction

https://codesandbox.io/s/xjp2j73w0w

## Steps to reproduce

1. Open up the code sandbox reproduction (wait for it to load)
2. Click on the `Title` component in the file editor on the left
3. Uncomment the working examples and compare them to the broken example default exports
4. Begin to visualize the problem in the pane on the right as you make changes to the Title component

## Expected Behavior

Renders styles correctly with the RGB background specified.

## Actual Behavior

Does not render styles correctly with the RGB background specified. It appears the style following the RGB also becomes broken. If we use a semicolon after the RGB definition or change it from RGB to Hex we can see it does indeed work as expected.

## Additionally
When trying this in combination with the `babel-plugin-styled-component` dependency on my local. All of the styles seemed to break when missing a semicolon. We can discuss that separately or in another issue however. (It appears turning off [minification](https://www.styled-components.com/docs/tooling#minification) solves that issue)

**Comment by probablyup** [comment]
We've been seeing a variety of similar issues relating to parens in CSS rules e.g. `url()` etc. I think there might be some issues in stylis around this.

**Comment by probablyup** [comment]
You should be putting semicolons in your CSS though. Although the tooling we use may (most of the time) insert them for you if you forget, styled-components CSS is meant to be like real CSS and real CSS requires semicolons except for the last property: value pair in a rule

**Comment by vinnymac** [comment]
I don’t mind using semicolons if they are required but it seemed a bit odd to me that it works without them sometimes.

The reproduction above goes through various cases. I am sure their are more.

Here is the link
https://codesandbox.io/s/xjp2j73w0w

**Comment by probablyup** [comment]
> I don’t mind using semicolons if they are required but it seemed a bit odd to me that it works without them sometimes.

I think of it more as a best-effort ASI thing rather than a core feature. CSS is meant to have semis, so it's not something we've spent a lot of time verifying that it works.
