### ISSUE TITLE
[Bug] Attrs overrides not working in v4

### ISSUE THREAD

**Issue by bernatfortet** [styled-components/styled-components#2192]
Could you please help me understand why overrides are not working in v4?

## Environment
  OS: macOS 10.14
  Node: 10.6.0
  Yarn: 1.0.0
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 2.2 AI-145.3330264

## Reproduction
V4: https://codesandbox.io/s/9yrww2z89p
V3.4: https://codesandbox.io/s/o9kylyqo2z

## Expected Behavior
both versions react the same way.

## Actual Behavior
v4 doesn't override attrs. See how v3.4 has a lot of margin, while v4, doesn't

**Comment by mxstbr** [comment]
Hmm I'm actually not sure if this is a bug or intended behaviour! For now you can work around it by using defaultProps: https://codesandbox.io/s/0pxx64q31v

Given that `defaultProps` works exactly as intended, I think the new `.attrs` behaviour makes more sense (otherwise why have that at all if it only works like `defaultProps`?) as a set of hard-coded attributes, but I'm not sure when/why that was changed or if it was done on purpose.   /cc @styled-components/core

**Comment by imbhargav5** [comment]
Same here. I am unsure if it's a bug or not. I tried a san. But there is one other way of making it work whether the issue is a bug or not. 
https://codesandbox.io/s/zk6oqv364p

```jsx
const Box = styled.div`
  ${p => (p.m ? `margin:${p.m}px;` : "")}
`;

const MyBox = styled(Box).attrs({ m: props => props.m || 12 })` `;

function App() {
  return (
    <div className="App">
      <MyBox m={100}>asdf</MyBox>
    </div>
  );
}
```

**Comment by imbhargav5** [comment]
Exactly!

**Comment by mxstbr** [comment]
> It seems like the attrs which are static have more preference over props, which should'nt be the case

I think this should be the case, no? If you want `props` to have preference you have to either manually make the `attrs` overrideable with a function or use `defaultProps`. This allows for usage like this:

```JS
const PasswordInput = styled.input.attrs({
  type: 'password'
})``
```

and it would always be a password input, even if people did `<PasswordInput type="text" />`. If you only wanted to set an overridable default, you should use `.defaultProps`, right?

**Comment by imbhargav5** [comment]
Yes, what I meant by "it shoudn't be the case" is that, from 3.x to 4.x, this is the part of `attrs` that users will find unexpected. A lot of the users assume attrs to be defaultProps. So this will take them by surprise. 
But we should definitely have just the one with the props function in attrs override them.

**Comment by bernatfortet** [comment]
Thanks for the thoughts and alternatives.
I build a big part of my component infrastructure is built with this attrs overriding in mind. So I'd like to have a good solution for now or maybe revert to 3.4 until this is figured out.

What I'm hearing is that overriding as it was possible in 3.4 will not change. 
That means that **default props** or **props functions in attrs** (in the future) are going to be the only ways to achieve overriding functionality, right?

**Comment by mxstbr** [comment]
That's my thinking at least, but I'm not sure why this was changed. I'd recommend you switch to `.defaultProps` across the board that should be the most future-proof solution for what you're trying to do, which is setting default props!

**Comment by bernatfortet** [comment]
Ok!
You're right, defaultProps should be the clearest way to define what I want. Thanks!

**Comment by mxstbr** [comment]
@probablyup do you know why and when this behaviour was changed?
