### ISSUE TITLE
Issues around rendering in external windows using portals on Edge

### ISSUE THREAD

**Issue by eramdam** [styled-components/styled-components#2193]
## Environment
```
## System:
 - OS: macOS 10.14
 - CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
 - Memory: 429.19 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 11.0.0 - ~/.nvm/versions/node/v11.0.0/bin/node
 - Yarn: 1.10.1 - ~/.yarn/bin/yarn
 - npm: 6.4.1 - ~/.nvm/versions/node/v11.0.0/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: ^1.5.0 => 1.8.0 
 - styled-components: ^4.0.2 => 4.0.2 
```

## Reproduction
I set up a project that reproduces the issue at => https://codesandbox.io/s/o74zzpypoz

## Steps to reproduce

In the sample project above, click "open window" in the live preview

## Expected Behavior

A new tab/window should render with the proper styles, like on Chrome

![screen shot 2018-11-06 at 3 42 51 pm](https://user-images.githubusercontent.com/1409924/48101373-980ee300-e1db-11e8-8ba0-9cfb20036feb.png)

## Actual Behavior

A couple of crashes occur in `createStyles` and `generateAndInjectStyles`, see screenshots below
![sc-edge-2](https://user-images.githubusercontent.com/1409924/48101822-3a7b9600-e1dd-11e8-8bf5-05332369270b.PNG)
![sc-edge-3](https://user-images.githubusercontent.com/1409924/48101823-3b142c80-e1dd-11e8-941e-93d7de1768a9.PNG)
![sc-edge](https://user-images.githubusercontent.com/1409924/48101824-3b142c80-e1dd-11e8-90bd-2dc0b62d7d46.PNG)

**Comment by probablyup** [comment]
I'd recommend opening an issue with that reproduction on the Edge issue tracker: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/

We specifically are using the [CSSOM CSSStyleSheet APIs](https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet), which don't appear to exist in a dynamically-opened window in Edge.

**Comment by eramdam** [comment]
I opened a ticket on the Edge issue tracker https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/20819328/
