### ISSUE TITLE
Removing PureComponents breaks inputs

### ISSUE THREAD

**Issue by olafura** [styled-components/styled-components#2195]
Hi, I did a bisect to find the problem we were having with styled components v4 and surveyjs. I ended up with narrowing the problem to this commit:
a7ab4704fbe0de7450ff0ff634e5024cad24fd31

I understand that PureComponents might cause some problem for you but you have to have some strategy not to mess with props.

The last version of v3 is fine if that helps.

**Comment by probablyup** [comment]
? The current implementation is equivalent to v3 since the purecomponent change was removed. That was going to be a new v4 optimization. v3 also used Component.
