### ISSUE TITLE
[object Window] appended to custom props bottom

### ISSUE THREAD

**Issue by pauldariye** [styled-components/styled-components#2198]
## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`

## System:
 - OS: macOS 10.14
 - CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
 - Memory: 293.01 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 10.11.0 - ~/.nvm/versions/node/v10.11.0/bin/node
 - Yarn: 1.10.1 - /usr/local/bin/yarn
 - npm: 6.4.1 - ~/.nvm/versions/node/v10.11.0/bin/npm
 - Watchman: 4.7.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^4.0.3 => 4.0.3 

## Reproduction
// Source: https://github.com/rebassjs/extras
```
import styled from 'styled-components'
import {
  position,
  zIndex,
  top,
  right,
  bottom,
  left,
} from 'styled-system'
import { Box } from 'rebass'

export const Position = styled(Box)(
  position,
  zIndex,
  top,
  right,
  bottom,
  left
)

export const Relative = styled(Position)([])

Relative.defaultProps = {
  position: 'relative'
}

export const Absolute = styled(Position)([])

Absolute.defaultProps = {
  position: 'absolute'
}

```
Usage

```
<Relative p={100}>
	<Absolute bottom="0" left="0">
		Absolute
	</Absolute>
</Relative>
```

See screenshots of the generated styles:
1. Relative
<img width="327" alt="screenshot 2018-11-09 15 17 58" src="https://user-images.githubusercontent.com/3650761/48286150-c5a19980-e432-11e8-95b6-3b879dbaab28.png">

2. Absolute
<img width="323" alt="screenshot 2018-11-09 15 17 49" src="https://user-images.githubusercontent.com/3650761/48286156-c9352080-e432-11e8-9013-37ca3f76dd12.png">

3. Styles
<img width="412" alt="screenshot 2018-11-09 16 11 56" src="https://user-images.githubusercontent.com/3650761/48288543-75c6d080-e43a-11e8-9128-c52f51e84652.png">

https://codesandbox.io/s/9lv73j6wvo (Weird, but it works perfectly here)

## Steps to reproduce
I'm using this in storybook. I'm not entirely sure what's going on.

**Comment by probablyup** [comment]
We don't do prop filtering for custom components, it's up to the third party library to filter that stuff out.
