### ISSUE TITLE
Flow doesn't return error with styled-components

### ISSUE THREAD

**Issue by ravecat** [styled-components/styled-components#2201]
### System:
 - OS: Linux 4.9 Debian GNU/Linux 9 (stretch) 9 (stretch)
 - CPU: (4) x64 Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
 - Memory: 3.17 GB / 15.38 GB
 - Container: Yes
 - Shell: 4.4.12 - /bin/bash
### Binaries:
 - Node: 10.12.0 - /usr/bin/node
 - Yarn: 1.10.1 - /usr/bin/yarn
 - npm: 6.4.1 - /usr/bin/npm
### npmPackages:
 - babel-plugin-styled-components: ^1.5.1 => 1.5.1 
 - styled-components: ^4.0.0-beta.10 => 4.0.0-beta.10 

## Reproduction

1. `git clone https://github.com/ravecat/styled-components-toolbox.git --single-branch --branch feature/migrate-to-flow`
2. `yarn`
3. `git commit --amend` and can see console output
> $ flow check
Found 0 errors

## Steps to reproduce

Create `Button.js` file with flow. Specifically indicated the wrong type for the variable (highlighted comment)

<details>
<summary>Button.js</summary>
<p>

```javascript
/* @flow */
import React from "react";
import styled, { css, type ReactComponentStyled } from "styled-components";
import BaseComponent, { BaseProps } from "common/components/BaseComponent";

type ButtonProps = BaseProps & {
  type?: string,
  href?: string,
  disabled?: boolean
};

const Button = ({ children, ...rest }: ButtonProps) => (
  // TODO Set wrong type for test flow
  <Wrapper as="button" type={42} {...rest}>
    <span>{children}</span>
  </Wrapper>
);

const Wrapper: ReactComponentStyled<ButtonProps> = styled(BaseComponent).attrs({
  type: ({ type }) => type || "button"
})`
  display: inline-block;
  height: 32px;
  padding: 0 15px;
  line-height: 30px;
  text-align: center;
  letter-spacing: normal;
  cursor: pointer;
  outline: 0;
  white-space: nowrap;
  color: ${({ theme }) => theme.textColor};
  background: ${({ theme }) => theme.primaryColor};
  border: 1px solid ${({ theme }) => theme.primaryColor};
  border-radius: 0;

  :hover {
    background: ${({ theme }) => theme.textColor};
    color: ${({ theme }) => theme.primaryColor};
  }

  ${({ disabled }) =>
    disabled &&
    css`
      && {
        cursor: default;
        background: ${({ theme }) => theme.textColor};
        border-color: ${({ theme }) => theme.dividerColor};
        color: ${({ theme }) => theme.dividerColor};
      }
    `};
`;

export default Button;

```

</p>
</details>

## Expected Behavior

Flow return error

## Actual Behavior

Flow check without error

Probably, this issue related with https://github.com/styled-components/styled-components/issues/1349 , but I cannot get answer on that problem

**Comment by probablyup** [comment]
Please move this to flow-typed, as we don't maintain the external typings.
