### ISSUE TITLE
setState causes flicker in chrome

### ISSUE THREAD

**Issue by jitenderchand1** [styled-components/styled-components#2205]
## System:
 - OS: Linux 4.14 Amazon Linux 2
 - CPU: (2) x64 Intel(R) Xeon(R) CPU E5-2686 v4 @ 2.30GHz
 - Memory: 368.21 MB / 3.85 GB
 - Container: Yes
 - Shell: 4.2.46 - /bin/bash
## Binaries:
 - Node: 8.12.0 - /usr/local/bin/node
 - npm: 6.4.1 - /usr/local/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.8.0 => 1.8.0 
 - styled-components: ^4.0.2 => 4.0.3 

##Bug description:

When I change state of component. fonts are re-requested every time.
Main.js

```
const App = () => (
  <Provider store={store}>
    <ThemeProvider theme={theme}>
      <Fragment>
        <Routes />
        <GlobalStyle />
        <Font />
      </Fragment>
    </ThemeProvider>
  </Provider>
);


export default App;
```

font.js

```
import { createGlobalStyle } from 'styled-components';
import Muli from './Muli/Muli-Regular.ttf';
import MuliBold from './Muli/Muli-Bold.ttf';

export default createGlobalStyle`
  @font-face {
    font-family: 'Muli';
    src: url(${Muli});
  }
  
  @font-face {
    font-family: 'MuliBold';
    src: url(${MuliBold});
  }
`;

```

<img width="1627" alt="screen shot 2018-11-13 at 4 32 11 pm" src="https://user-images.githubusercontent.com/19687185/48393068-2fd37a80-e762-11e8-9883-5e54bfd0ed6c.png">

Demo: 
https://drive.google.com/file/d/1LVwv1OpvHA7viQc4LafPJWv9TslT5eee/view

**Comment by jitenderchand1** [comment]
related to : [1593](https://github.com/styled-components/styled-components/issues/1593)

**Comment by probablyup** [comment]
Any chance you have a repo I could look at?

**Comment by jitenderchand1** [comment]
@probablyup I am afraid. it is a private repo. By the way I have fixed the issue by removing font from createGlobalStyle and inject font in main.scss. It solve the issue. If you need any additional info to cure this issue with createGlobalStyle. Please let me know.

**Comment by oriSomething** [comment]
@jimthedev I had the same problem with flickering when using `@font-face` with `createGlobalStyle`

**Comment by jitenderchand1** [comment]
for fixed this issue for now I have moved my font import to css file. 


```

@font-face {
  font-family: 'Muli';
  src: url('../fonts/Muli/Muli-Regular.ttf');
}

@font-face {
  font-family: 'MuliBold';
  src: url('../fonts/Muli/Muli-Bold.ttf');
}

```

app.js

`import './styles/main.scss';`
