### ISSUE TITLE
new attrs as a function doesn't pass theme to the function provided

### ISSUE THREAD

**Issue by NProtagoras** [styled-components/styled-components#2208]
## Environment
 - React-native IOS
## System:
 - OS: macOS High Sierra 10.13.6
 - CPU: x64 Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz
 - Memory: 43.83 MB / 8.00 GB
 - Shell: 5.6.2 - /usr/local/bin/zsh
## Binaries:
 - Node: 11.0.0 - /usr/local/bin/node
 - Yarn: 1.12.1 - /usr/local/bin/yarn
 - npm: 6.4.1 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^4.1.1 => 4.1.1 

## Reproduction
1. create a global theme and provide it using <ThemeProvider>. 
2. create a styled component with attrs, where the function expects a theme to be in the props. (eg, `styled.div.attrs(props => ({ backgroundColor: props.theme.bgcolor}))```)

## Expected Behavior
theme is provided to the props of the attrs function

## Actual Behavior
theme is not provided and the app crashes with  "cannot read property 'bgcolor' of undefined".

**Comment by varjmes** [comment]
I am finding all my snapshots test fail with an upgrade to 4.0.3 -> 4.1.1, with the error 'attrs.some is not a function'

**Comment by probablyup** [comment]
> with the error attrs.some is not a function

That's interesting... could you potentially make a reproduction? Should also be a different issue.

**Comment by probablyup** [comment]
@NProtagoras looking into this now, thanks!

**Comment by probablyup** [comment]
This is available as of https://github.com/styled-components/styled-components/releases/tag/v4.1.2
