### ISSUE TITLE
createGlobalStyle is reproducing wrong styling in production mode

### ISSUE THREAD

**Issue by shobhitsharma** [styled-components/styled-components#2209]
## Environment

Node v10x

## Reproduction

Its a react app, and I pass some styles including css reset and `body, html` basic styles using `createGlobalStyle` which works perfectly fine when working locally. However, I noticed the same styles are being ignored or didn't get imported when application is built using webpack production mode.

See results below. Tried many different tests, but it seems to be behaving indifferently which maybe caused by bug within css string to style tag compilation. 

## Steps to reproduce

Build script using webpack production mode.

## Expected Behavior
<img width="363" alt="screenshot 2018-11-13 at 5 40 06 pm" src="https://user-images.githubusercontent.com/772855/48428390-32869d80-e76b-11e8-926d-bf73ffc6aed0.png">

## Actual Behavior
<img width="352" alt="screenshot 2018-11-13 at 5 41 19 pm" src="https://user-images.githubusercontent.com/772855/48428452-58ac3d80-e76b-11e8-8906-d40e175bb8e1.png">

**Comment by shobhitsharma** [comment]
@probablyup In the codesanbox, it works as it does locally, but during webpack production build, the body wont be having those properties declared. See https://codesandbox.io/s/m4px5w6qny

**Comment by shobhitsharma** [comment]
Between, I was able to resolve it for my case using a work around by wrapping `createGlobalStyle` call separately in a stateless react component instead of direct exporting it. 

There is definitely an issue with string literal interpolation method, I will fork it and try to debug when I get spare time. But for now _try to imagine working solution through this scenario:_

**Call**:
```js
import GlobalStyle from './global-style'

...
 <GlobalStyle ...props>
...

```

**Before**: `global-style.js`
```js
...
export default createGlobalStyle`
    /* Reset CSS */
    ${ResetCSS}

    /* Import Fonts */
    ${(props: any) => (fontFamilies as any)[props.mode]}

    *,
    *:before,
    *:after {
        box-sizing: inherit;
    }

    html, body {
        font-family: ${(props: any) => props.theme.global.fontFamily}, sans-serif;
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
        overflow-x: hidden;
        text-rendering: optimizeLegibility;
        box-sizing: border-box;
    }

    body {
        color: ${(props: any) => props.theme.colors.primary};
    }

    a {
        color: ${(props: any) => props.theme.colors.primary};
    }

    b, strong, h1, h2, h3, h4, h5 {
        font-family: ${(props: any) => props.theme.global.fontFamily600}, sans-serif;
    }
`;
```
**After**: `global-style.js`
```js
...
class GlobalStyle extends React.Component<any, any> {
    public render(): JSX.Element {
        const { mode } = this.props;
        const GlobalCSSReset = createGlobalStyle`
            ${ResetCSS}
        `;
        const GlobalFonts = createGlobalStyle`
            ${(fontFamilies as any)[mode]}
        `;
        const GlobalDefaults = createGlobalStyle`
            *,
            *:before,
            *:after {
                box-sizing: border-box;
            }

            html, body {
                font-family: ${(props: any) => props.theme.global.fontFamily}, sans-serif;
                color: ${(props: any) => props.theme.colors.primary};
                -webkit-font-smoothing: antialiased;
                -moz-osx-font-smoothing: grayscale;
                overflow-x: hidden;
                text-rendering: optimizeLegibility;
            }

            a {
                color: ${(props: any) => props.theme.colors.primary};
            }

            b, strong, h1, h2, h3, h4, h5 {
                font-family: ${(props: any) => props.theme.global.fontFamily600}, sans-serif;
            }
        `;
        return (
            <React.Fragment>
                <GlobalFonts />
                <GlobalCSSReset />
                <GlobalDefaults />
            </React.Fragment>
        );
    }
}

export default GlobalStyle;
```

**Comment by probablyup** [comment]
That just creates a new global style component on every render...

**Comment by imbhargav5** [comment]
Can you try something like this and let us know?  The thing is, in your example. The CGS runs on every render, which means the same styles are injected each time they are created which leaks memory. Can you try this eg and let me know?

```jsx
       const GlobalCSSReset = createGlobalStyle`
            ${ResetCSS}
        `;
        const GlobalFonts = createGlobalStyle`
            ${(fontFamilies as any)[mode]}
        `;
        const GlobalDefaults = createGlobalStyle`
            *,
            *:before,
            *:after {
                box-sizing: border-box;
            }

            html, body {
                font-family: ${(props: any) => props.theme.global.fontFamily}, sans-serif;
                color: ${(props: any) => props.theme.colors.primary};
                -webkit-font-smoothing: antialiased;
                -moz-osx-font-smoothing: grayscale;
                overflow-x: hidden;
                text-rendering: optimizeLegibility;
            }

            a {
                color: ${(props: any) => props.theme.colors.primary};
            }

            b, strong, h1, h2, h3, h4, h5 {
                font-family: ${(props: any) => props.theme.global.fontFamily600}, sans-serif;
            }
        `;

class GlobalStyle extends React.Component<{ ... }, { ... }> {
    public render(): JSX.Element {
        const { mode } = this.props;
       
        return (
            <React.Fragment>
                <GlobalFonts mode={mode} />
                <GlobalCSSReset   />
                <GlobalDefaults />
            </React.Fragment>
        );
    }
}

export default GlobalStyle;

```

**Comment by shobhitsharma** [comment]
@probablyup In my case it wont re-render again.

@imbhargav5 I did move it up to outerscope and it works with build as long as I keep them separate. If thats the expected behavior from styled-components, then it should behave same while developing locally. All above its doing is to replace string, nothing more.

**Comment by probablyup** [comment]
The warning is removed as of https://github.com/styled-components/styled-components/releases/tag/v4.1.2

**Comment by shobhitsharma** [comment]
@probablyup Nice! It has been great experience working with this library. Love to contribute next time!

**Comment by probablyup** [comment]
Glad to hear it!
