### ISSUE TITLE
Safari 11 and below, Firefox 55: weird behavior when bundled

### ISSUE THREAD

**Issue by wmertens** [styled-components/styled-components#2219]
### System:
 - OS: macOS 10.14
 - CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
 - Memory: 314.69 MB / 8.00 GB
 - Shell: 3.2.57 - /bin/bash
### Binaries:
 - Node: 8.11.4 - ~/.nix-profile/bin/node
 - Yarn: 1.12.3 - ~/bin/node_modules/.bin/yarn
 - npm: 5.6.0 - ~/.nix-profile/bin/npm
 - Watchman: 4.9.0 - /Users/wmertens/.nix-profile/bin/watchman
### npmPackages:
 - babel-plugin-styled-components: ^1.8.0 => 1.8.0
 - styled-components: ^4.1.1 => 4.1.1

## Reproduction

On Safari 12 everything seems to work fine. On Safari 11 and below, the classnames are messed up.

## Steps to reproduce

1. Find a Safari 11 system
2. Go to https://cap-www.yaska.eu/en

## Expected Behavior

3. Everything is fine

## Actual Behavior

3. Notice that the SSR version looks ok (turn off javascript), and the hydrated version doesn't

The main difference is that the `position:fixed` header class is also present on the content body, and it royally messes things up. For some reason that className is repeated even though it shouldn't (className is `".

This only happens when the code is bundled. I turned off uglification and it's still happening. I think it's due to something that's turned on when `NODE_ENV === 'production'` but the only thing I could find was SC_SPEEDY and turning that off doesn't help.

## UPDATE

I tried with FF55 and it's the same problem. It only works in recent browsers.

**Comment by wmertens** [comment]
My dev build, which normally works fine on Safari 11, shows problems when I set `NODE_ENV=production` without any other changes.

So it is a behavior that is triggered by that, most likely in styled-components.

**Comment by probablyup** [comment]
Hmm.. maybe it's a consequence of minification?

**Comment by probablyup** [comment]
AHA! https://www.npmjs.com/package/terser there's a section on safari

**Comment by probablyup** [comment]
So the only build we minify ourselves in the standalone CDN build. If you're using webpack or whatnot, you'll want to try that setting out in your own build system.

**Comment by wmertens** [comment]
Ok, I was barking up the wrong tree - what happened was that in production SSR my initial data passing failed, and S-C had to work without rehydration data.

This somehow (and without warning) caused the styles to be wrong, they were repeated on the wrong elements. @probablyup any idea how that can happen? I'll probaby need to open another issue for that but I don't really have a reproduction case except for my whole older production app :-/

**Comment by probablyup** [comment]
@wmertens check this issue out, might have a fix for what you're seeing! https://github.com/styled-components/styled-components-website/issues/329

**Comment by wmertens** [comment]
@probablyup 	hmm very interesting, I'll be implementing that but I'm not sure it would help with messed up classnames on bad rehydrate…

**Comment by probablyup** [comment]
@wmertens were you able to figure this out?
