### ISSUE TITLE
Conditionnal CSS based on props

### ISSUE THREAD

**Issue by Steffi3rd** [styled-components/styled-components#2220]
Hi! 

I would like to use some CSS when I have some props.
For example, `if socialButtonIsFixed == true`, I would like to add CSS to a styleComponent

<img width="421" alt="capture d ecran 2018-11-16 a 10 00 04" src="https://user-images.githubusercontent.com/814410/48611521-bd8faf80-e986-11e8-902c-1de5bdf932a8.png">

<img width="292" alt="capture d ecran 2018-11-16 a 10 01 02" src="https://user-images.githubusercontent.com/814410/48611523-bf597300-e986-11e8-940f-b9738dc594b5.png">

I know it is possible to add conditional property by `font-size: ${ props => props.primary ? '4vw' : '18vw'}` but I think it's not what I need.

Someone knows how to do that please?

**Comment by mxstbr** [comment]
> I know it is possible to add conditional property by font-size: ${ props => props.primary ? '4vw' : '18vw'} but I think it's not what I need.

It is! This is probably what you want:

```JS
const Buttons = styled.button`
  ${props => props.fixed && css`${socialButtonsActive}`}
`;
```

**Comment by mxstbr** [comment]
Please direct usage question to the community: https://spectrum.chat/styled-components Thanks!
