### ISSUE TITLE
Pseudo-classes applied to styled components should not interfere with other elements

### ISSUE THREAD

**Issue by mvasin** [styled-components/styled-components#2226]
## System:
 - OS: macOS 10.14.1
 - CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
 - Memory: 1019.59 MB / 16.00 GB
 - Shell: 4.4.23 - /usr/local/bin/bash
## Binaries:
 - Node: 11.1.0 - /usr/local/bin/node
 - Yarn: 1.12.3 - /usr/local/bin/yarn
 - npm: 6.4.1 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^4.1.1 => 4.1.1

## Reproduction
https://codesandbox.io/s/6lz539qp5w

## Steps to reproduce
In this code last `Div1` (`last-child`) is selected correctly, it's red:
```jsx
import React from "react";
import ReactDOM from "react-dom";
import styled from "styled-components";

import "./styles.css";

const Div1 = styled.div`
  color: green;
`;

const Main = styled.main`
  ${Div1}:last-child {
    color: red;
  }
`;

function App() {
  return (
    <Main>
      <Div1>Div1, not last child, green</Div1>
      <Div1>Div1, last child, is RED</Div1>
    </Main>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

But if we append another div after it, `last-child` selection doesn't work for `Div1` (it's not red anymore):
```jsx
import React from "react";
import ReactDOM from "react-dom";
import styled from "styled-components";

import "./styles.css";

const Div1 = styled.div`
  color: green;
`;

const Main = styled.main`
  ${Div1}:last-child {
    color: red;
  }
`;

function App() {
  return (
    <Main>
      <Div1>Div1, not last child, green</Div1>
      <Div1>Div1, last child, should be RED</Div1>
      <div>
        div that spoils second Div1. Remove it and second Div1 will become red,
        as it should be.
      </div>
    </Main>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

## Expected Behavior
Pseudo-classes applied to styled components should not interfere with other elements.

## Actual Behavior
Elements of the same underlying DOM node type break pseudo-classes of styled components.

**Comment by probablyup** [comment]
At the end of the day, styled components compiles to normal CSS. The
:last-child selector operates on all the children of the closest parent
element, so when you add another element to the end, Div1 is no longer the
last child.

**Comment by mvasin** [comment]
I tried that in pure html/css and it works the same as SC: https://codepen.io/vermishelle/pen/xQXwvP

Here's the CSS:
```css
.div1 {
  color: green;
}

.div1:last-child {
  color: red;
}
```
here's HTML:
```html
<main>
  <div class="div1">
    Div1, not last child, green
  </div>
  <div class="div1">
    Div1, last child, should be RED
  </div>
  <div>div that spoils second Div1. Remove it and second Div1 will become red, as it should be.</div>
</main>
```
The spec says "The :last-child pseudo-class represents an element that is last in a list of siblings." But second div IS the last child of its type (of those with `div1` class, `.div1:last-child {}` in CSS). Still, the middle div is not red.

I'm confused, but that definitely has nothing to do with SC, sorry for disturbing. I'll model the situation in pure CSS next time before I post.

**Comment by probablyup** [comment]
Yes but the selector is a class not a div.

**Comment by probablyup** [comment]
What you actually want is div:last-child or *:last-child inside Main to get the desired behavior.
