### ISSUE TITLE
Importing fonts inside global styles cases re-importing fonts on every re-render

### ISSUE THREAD

**Issue by SilencerWeb** [styled-components/styled-components#2227]
## Environment

```
## System:
 - OS: macOS 10.14.1
 - CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
 - Memory: 330.83 MB / 8.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 11.0.0 - /usr/local/bin/node
 - Yarn: 1.10.1 - /usr/local/bin/yarn
 - npm: 6.4.1 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^4.1.1 => 4.1.1
```

## Reproduction
https://github.com/SilencerWeb/eslint-config-website

## Steps to reproduce
Create file .env with this line - `NODE_PATH="src/"`, then do the following:
```
git clone https://github.com/SilencerWeb/eslint-config-website
git checkout 5043b2e272b6f
npm i
npm run start
```

## Expected Behavior
On re-rendering the elements, components should update without blinking.

## Actual Behavior
On re-rendering the elements, components blink.

I'm sure it is because of new global styles API that was presented in 4th version of styled-components. I had the same issue with my app on electron and react but I thought it was next.js issue, not styled-components, I had to downgrade to 3th version and use old global styles API. In the current case, I had to move all my fonts to public folder - https://github.com/SilencerWeb/eslint-config-website/commit/7cd1722a816669b1a6d2642475cb11e4c7a77721. Please, check in Chrome, Opera or Safari - in these browser this bug exists for sure.

**Comment by probablyup** [comment]
This is only in dev right? In production you definitely should not see blinking. Dev tends to be rougher since we're using the old text node way of injecting styles, which causes a bigger restyle/relayout.

**Comment by SilencerWeb** [comment]
@probablyup unfortunately, in production too :(

**Comment by danbopes** [comment]
I'm having similar issues with this. When my page initially loads, I don't mind a small flicker as the fonts load in. The problem is, when I create another element on the page (In my case, I was adding a dropdown with some styled-components), it caused a re-render of the globalStyles which then caused a flicker as my fonts attempted to download again.

**Comment by probablyup** [comment]
I'll try and look into this sometime during the week.

**Comment by egoarka** [comment]
I faced same issue 1 week ago, and just turned my fonts into base64 URls https://github.com/webpack-contrib/url-loader
after this everything went well, but this is good for dev purposes not for production ones

after digging more deeper I found out that my fonts were loaded from server and were not cached at all

so
try to check your server configuration, at least check if it cache settings for assets or not

**Comment by danbopes** [comment]
It's absolutely a styled-components issue. The style tag is being surrendered again which is why another attempt to grab the fonts is made. Caching or not, it's still an issue. Just because the base64 decodes offered a workaround to this problem, doesn't mean that it's not a styled components issue. I'll have a look, and see if I can tackle the reason why this is happening.

**Comment by danbopes** [comment]
Alright, here is a barebones REPO: https://github.com/danbopes/styled-components-font-issue

Install, and run `npm run start:dev`. Navigate to http://localhost:8080. When you click the button, it causes a rerender of the style element, which blinks any fonts as it causes a reload. @probablyup I think the best solution would be to move the global styles into their own style tag, and reload everything else. (Most people will have fonts and what not, inside their global tag).

**Comment by richardhsueh** [comment]
#1593  There is a longer discussion of this problem in this issue, @SilencerWeb you may take a look here. So far one of the solution is to use a css/scss file to import the font separately

**Comment by rainstormza** [comment]
I had the same issue in styled-components v4, but it happens only production build.

I try with nextjs and reverse to styled-components v3, everything works fine again.

**Comment by probablyup** [comment]
Long story short, make sure your fonts are served with appropriate HTTP caching headers. If there is no caching header set, the browser will re-request them every time the style tag is touched.

**Comment by bitworking** [comment]
@probablyup Yes that sounds plausible. I've added this to my express server:

    server.get(/^\/static\/(images|fonts)\//, (_, res, nextHandler) => {
      res.setHeader('Cache-Control', 'public, max-age=300, immutable');
      nextHandler();
    });

**Comment by probablyup** [comment]
Something simple like this works too:

```js
server.use(
    express.static(/^\/static\/(images|fonts)\//, {
      maxAge: '365d',
    })
  );
```

Just have to make sure you rename the files if you change them, but generally speaking images and fonts rarely change so it's safe.

I'm a bit curious why I'm being downvoted in my comment above, this is basic browser behavior.

**Comment by jtomaszewski** [comment]
Because it's a workaround, not a real solution.

And it isn't documented anywhere, AFAIK, right?

[Googling](https://www.google.com/search?q=styled+components+docs+font+face&oq=styled+components+docs+font+face&aqs=chrome..69i57j33.3429j0j7&sourceid=chrome&ie=UTF-8) takes me [here](https://github.com/styled-components/styled-components/issues/2227#issuecomment-475112449), [here](https://github.com/styled-components/styled-components/issues/1593), [here](https://github.com/styled-components/styled-components/issues/233) and [here](https://stackoverflow.com/a/50174102) .

At least docs in styled-components should be improved, to contain something like this:

> You have to have cache headers on your font files that are put using `@font-face` and `createGlobalStyle`. Because of the way styled-components currently work, global styles are put in a`<style` element that gets rerendered very, very often, and will cause your browser to reload your fonts every time that element is rerendered.

Nevertheless, I'd vote for a better solution, for example, having a separate `<style` element for global styles, so that it doesn't get rerendered when it doesn't have to. (Or warning the devs when they use `@font-face`?)

**Comment by SebDuf** [comment]
For anybody who found this while trying to fix this problem and is using Webpack Dev Server with an *EJECTED* Create React App, here's how to fix it:

In `webpackDevServer.config.js`, for the key `before`, add this code (modified from @bitworking's example):

```
app.get(/^\/static\/(media)\//, (_, res, nextHandler) => {
    res.setHeader('Cache-Control', 'public, max-age=300, immutable');
    nextHandler();
});
```

Note the path to static files here is `static/media`, not `static/fonts`

Here's the full `before` function:

```
before(app, server) {
  // Keep `evalSourceMapMiddleware` and `errorOverlayMiddleware`
  // middlewares before `redirectServedPath` otherwise will not have any effect
  // This lets us fetch source contents from webpack for the error overlay
  app.use(evalSourceMapMiddleware(server));
  // This lets us open files from the runtime error overlay.
  app.use(errorOverlayMiddleware());

  if (fs.existsSync(paths.proxySetup)) {
    // This registers user provided middleware for proxy reasons
    require(paths.proxySetup)(app);
  }

  app.get(/^\/static\/(media)\//, (_, res, nextHandler) => {
    res.setHeader('Cache-Control', 'public, max-age=300, immutable');
    nextHandler();
  });
},
```

**Comment by unutoiul** [comment]
is there any fix without ejecting the react create app?

I have the same problem I use 

```

**Comment by a-m-dev** [comment]
any updates to workaround this issue?
+100000

**Comment by unutoiul** [comment]
I just injected the css in html but is a shit solution !

**Comment by luizfelipelaviola** [comment]
Same issue here... Font always flashes and re-download

**Comment by luizfelipelaviola** [comment]
I workaround this issue with creating a css outside styled components to setup @font-face, after this, i just importing the new .css file to globalStyles.js (out of createGlobalStyle). Works, but it is a shit solution...

`@font-face {
  font-family: ArialRounded;
  font-weight: bold;
  src: url('../fonts/arial-rounded-mt-std-extra-bold.otf') format("opentype");
}
`

`import { createGlobalStyle } from 'styled-components';

import 'react-toastify/dist/ReactToastify.css';
import 'react-perfect-scrollbar/dist/css/styles.css';
import './customFontIssue.css';

export default createGlobalStyle`

    @import url('https://fonts.googleapis.com/css?family=Roboto:400,700&display=swap');

    * {
        margin: 0;
        padding: 0;
        outline: 0;
        box`

**Comment by luizfelipelaviola** [comment]
I workaround this issue with creating a css outside styled components to setup @font-face, after this, i just importing the new .css file to globalStyles.js (out of createGlobalStyle). Works, but it is a shit solution...

`@font-face { font-family: ArialRounded; font-weight: bold; src: url('../fonts/arial-rounded-mt-std-extra-bold.otf') format("opentype"); }`

`import { createGlobalStyle } from 'styled-components';

import 'react-toastify/dist/ReactToastify.css';
import 'react-perfect-scrollbar/dist/css/styles.css';
import './customFontIssue.css';

export default createGlobalStyle`

@import url('https://fonts.googleapis.com/css?family=Roboto:400,700&display=swap');

* {
    margin: 0;
    padding: 0;
    outline: 0;
    box`

**Comment by luizfelipelaviola** [comment]
I workaround this issue with creating a css outside styled components to setup @font-face, after this, i just importing the new .css file to globalStyles.js (out of createGlobalStyle). Works, but it is a shit solution...

`@font-face { font-family: ArialRounded; font-weight: bold; src: url('../fonts/arial-rounded-mt-std-extra-bold.otf') format("opentype"); }`

```
import { createGlobalStyle } from 'styled-components';

import 'react-toastify/dist/ReactToastify.css';
import 'react-perfect-scrollbar/dist/css/styles.css';
import './customFontIssue.css';

export default createGlobalStyle`

@import url('https://fonts.googleapis.com/css?family=Roboto:400,700&display=swap');

{
margin: 0;
padding: 0;
outline: 0;
box....................
```

**Comment by ryparker** [comment]
> I workaround this issue with creating a css outside styled components to setup @font-face, after this, i just importing the new .css file to globalStyles.js (out of createGlobalStyle). Works, but it is a shit solution...
> 
> `@font-face { font-family: ArialRounded; font-weight: bold; src: url('../fonts/arial-rounded-mt-std-extra-bold.otf') format("opentype"); }`
> 
> ```
> import { createGlobalStyle } from 'styled-components';
> 
> import 'react-toastify/dist/ReactToastify.css';
> import 'react-perfect-scrollbar/dist/css/styles.css';
> import './customFontIssue.css';
> 
> export default createGlobalStyle`
> 
> @import url('https://fonts.googleapis.com/css?family=Roboto:400,700&display=swap');
> 
> {
> margin: 0;
> padding: 0;
> outline: 0;
> box....................
> ```

This solved the font flash for me. Is this a not recommended practice? What are the trade offs?

**Comment by tirmey** [comment]
> > I workaround this issue with creating a css outside styled components to setup @font-face, after this, i just importing the new .css file to globalStyles.js (out of createGlobalStyle). Works, but it is a shit solution...
> > `@font-face { font-family: ArialRounded; font-weight: bold; src: url('../fonts/arial-rounded-mt-std-extra-bold.otf') format("opentype"); }`
> > ```
> > import { createGlobalStyle } from 'styled-components';
> > 
> > import 'react-toastify/dist/ReactToastify.css';
> > import 'react-perfect-scrollbar/dist/css/styles.css';
> > import './customFontIssue.css';
> > 
> > export default createGlobalStyle`
> > 
> > @import url('https://fonts.googleapis.com/css?family=Roboto:400,700&display=swap');
> > 
> > {
> > margin: 0;
> > padding: 0;
> > outline: 0;
> > box....................
> > ```
> 
> This solved the font flash for me. Is this not a recommended practice? What are the trade offs?

I created an external stylesheet only to declare the fonts and imported it in the header of the main layout component of my app. The FOUT was gone completely bypassing styled-components styles rehydration.

**Comment by fpolica91** [comment]
I had the same issue you guys are mentioning when using nextjs and typescript. Since I could not create another file and import it inside of global.ts I imported the faces inside of _app.tsx. This fixed the issue.

**Comment by kayallapontes** [comment]
> I workaround this issue with creating a css outside styled components to setup @font-face, after this, i just importing the new .css file to globalStyles.js (out of createGlobalStyle). Works, but it is a shit solution...
> 
> `@font-face { font-family: ArialRounded; font-weight: bold; src: url('../fonts/arial-rounded-mt-std-extra-bold.otf') format("opentype"); }`
> 
> ```
> import { createGlobalStyle } from 'styled-components';
> 
> import 'react-toastify/dist/ReactToastify.css';
> import 'react-perfect-scrollbar/dist/css/styles.css';
> import './customFontIssue.css';
> 
> export default createGlobalStyle`
> 
> @import url('https://fonts.googleapis.com/css?family=Roboto:400,700&display=swap');
> 
> {
> margin: 0;
> padding: 0;
> outline: 0;
> box....................
> ```

Worked perfectly for me! Thanks!!

**Comment by vxcamiloxv** [comment]
FYI, maybe it's not nice but I fixed with this

```javascript
import fontsCss from './global/css/fonts.module.css'; // importing as CSS fix the issue
import resetStyles from './global/reset.styles';
import contentStyles from './global/content.styles';

const GlobalStyle = createGlobalStyle`
  ${fontsCss} // this sowrks as a normal styled css
  ${resetStyles}
  ${contentStyles}
`;
```

**Comment by LexiosAlex** [comment]
Hi there,
I'm actually solved it by webpack URL loader, so its not possible without custom webpack config
My final url-loader look like this

```
          {
            test: [/\.bmp$/, /\.gif$/, /\.jpe?g$/, /\.png$/, /\.(woff|woff2)$/],
            loader: require.resolve('url-loader'),
            options: {
              limit: imageInlineSizeLimit,
              name: 'static/media/[name].[hash:8].[ext]',
            },
          },
```

And `stylesGlobal.ts` looks like

```
import GlyphiconsHalflingsWOFF from 'app/resources/fonts/glyphicons-halflings-regular.woff'
import GlyphiconsHalflingsWOFF2 from 'app/resources/fonts/glyphicons-halflings-regular.woff2'
import MontserratRegularWOFF from 'app/resources/fonts/Montserrat-Regular.woff'
import MontserratRegularWOFF2 from 'app/resources/fonts/Montserrat-Regular.woff2'
import MontserratItalicWOFF from 'app/resources/fonts/Montserrat-Italic.woff'
import MontserratItalicWOFF2 from 'app/resources/fonts/Montserrat-Italic.woff2'

import { createGlobalStyle } from 'styled-components'

export const GlobalStyle = createGlobalStyle`
    @font-face {
    font-family: 'Glyphicons Halflings';
    font-display: swap;

    src: local('Glyphicons Halflings'), local('Glyphicons Halflings'),
      url('${GlyphiconsHalflingsWOFF2}') format('woff2'),
      url('${GlyphiconsHalflingsWOFF}') format('woff');
  }

  @font-face {
    font-family: 'Montserrat';
    font-weight: normal;
    font-style: normal;
    font-display: swap;

    src: local('Montserrat Regular'), local('Montserrat Regular'),
      url('${MontserratRegularWOFF2}') format('woff2'),
      url('${MontserratRegularWOFF}') format('woff');
  }

  @font-face {
    font-family: 'Montserrat';
    font-weight: normal;
    font-style: italic;
    font-display: swap;

    src: local('Montserrat Italic'), local('Montserrat Italic'),
      url('${MontserratItalicWOFF2}') format('woff2'), url('${MontserratItalicWOFF}') format('woff');
  }
`
```

**Comment by wesbos** [comment]
Fixed it in a similar way, but I couldn't use CSS because I wanted to import the fonts as assets.

```js
import React from 'react';

import radnika from '../assets/fonts/RadnikaNext/RadnikaNext-Black.woff2';

const fontCSS = /* css */ `
  @font-face {
    font-family: 'radnika';
    src: url(${radnika});
  }
`;

export default function Fonts() {
  /* eslint-disable react/no-danger */
  return (
    <style
      dangerouslySetInnerHTML={{
        __html: fontCSS,
      }}
    />
  );
  /* eslint-enable react/no-danger */
}

```

The reason I needed __dangerouslySetInnerHtml is because the quotes were being converted to HTML entities on the server (with gatsby) and not on the client - so you might not need that part and can use do `<style>{fontCSS}</style>`
