### ISSUE TITLE
Hashes and tests 🤧 

### ISSUE THREAD

**Issue by tomitrescak** [styled-components/styled-components#2228]
Hi, I was trying to find out how you calculate hashes since 95% of my failed test cases are changes in hashes of styled components. Weirdly enough, hashes of components that I have not even touched are regenerated with a different value.

I found this article https://medium.com/styled-components/how-styled-components-works-618a69970421 which specifies that you use MurMur algorithm, but it does not specify what is the input. would you be so kind and clarify under what circumstances are new hashes regenerated?

Please help me get rid of this fragile test hell:

```
cypress_runner.js:160646 Error: Snapshot difference
-<div class="ui secondary sc-VigVT hWbygT menu">
+<div class="ui secondary sc-VigVT iKHKYw menu">
```

**Comment by probablyup** [comment]
It's based on the file path and variable name mostly. We recommend using [`jest-styled-components`](https://github.com/styled-components/jest-styled-components) to eliminate the tracking of individual hashes in your tests.

**Comment by tomitrescak** [comment]
@probablyup what does "mostly" represent? I did not change the variable name, neither the file path and hashes are completely different. I cannot use jest-styled-components for e2e tests.

**Comment by probablyup** [comment]
I'm a bit confused why you would be snapshotting anything in an e2e test, but that's a separate conversation.

There are a lot of factors that go into the styled-components generated hash, including:

1. If you're using the styled-components babel plugin
2. The file path
3. The variable name of the component

If you aren't already using the babel plugin with the ssr option enabled, that will go a long way toward keeping the hashes stable, all other things being equal.

**Comment by tomitrescak** [comment]
@probablyup I'm just snapshotting as it is the fastest way to check for page consistency, the server calls are stubbed. Works quite well with Cypress.

I turned on the ssr, let's see if hashes will stabilise. I hope it will not mess anything up since I am not using SSR, but the creat-react-app.

**Comment by probablyup** [comment]
Ahhh if you're using create-react-app v2, I highly recommend using the babel macro: https://www.styled-components.com/docs/tooling#babel-macro

Adding the plugin to your babel config won't work alone I think because of how CRA works. And there's no harm to having ssr mode on... in fact it's on by default since 1.6 I believe.
