### ISSUE TITLE
don't deprecate attr key as function

### ISSUE THREAD

**Issue by macrozone** [styled-components/styled-components#2229]
### Backgorund

since version 4.1.0 its possible to have `.attrs()` directly receive a function of `props => newAttrs`.

e.g. 

```
const Icon = styled(MyComponent).attrs(props => ({
   color: props.theme.primaryLight,
   strokeColor: props.theme.primary
})
```

Before, you had to define a function for every key:

```
const Icon = styled(MyComponent).attrs({
   fill: props => props.theme.primaryLight,
   strokeColor: props => props.theme.primary
})
```

It has been decided that the new way is simpler and so the old way has been marked as deprecated.

I think this decision needs rethinking and I would vote to keep the old way.

### Reasoning

In the css-template-string you often have this structure:

```
<property>: static-value;
<property>:  ${<selectorFromThemeOrProps>};
```
where `selectorFromThemeOrProps` is something like `props => props....`

The old api for `.attrs()` matched this exactly. Every computed attribute was either a static value or a function/selector from props to attribute. This similarity allowed to write handy theme-selectors that can be used in both the template-string and in `.attrs()`:

```
// theme

const theme = {
   colors: {
       primary: "#DB7193",
       primaryLight: "#eee",
  }
};

// theme-selectors.js
const selectColor = key => props => props.theme.colors[key];

// and in your component:

const Heading = styled.h1`
   color: ${selectColor("primary")};

`

// if your component happens to consume some styling-values like colors as props, you can simply do:

const MyOtherComponent = styled(MyComponent).attrs({
   strokeColor: selectColor("primary"),
   fillColor: selectColor("primaryLight")
})``

```

now, this symetry and ellegance will be broken by the deprecation of this style of `.attrs`:

```
// using the new api..:

const MyOtherComponent = styled(MyComponent).attrs(props => ({
   strokeColor: selectColor("primary")(props),
   fillColor: selectColor("primaryLight")(props)
}))`` // <-- also notice, how many braces and parens you now need...

```

Much more noise!

I think that attrs should be used to add static properties, that are related to _styling_, so the amount of attrs i calculated from props or theme is always small. I also think that most users need it because some component needs to have styling information through props or html attributes instead through css.

I understand that the new api is more similar to recompose' `withProps` and is therefore considered to be "simpler", but i think that the old api mirrored perfectly the api of the string-template. As A thought-experiment, think about "mirroring" the new `.attrs` api back to the template-string. It would look like this:

```
const MyComponent = styled.div( props => props.active ? "color: "red; margin-bottom: 20px;" :  "margin-bottom: 20px;" 
```

I think this was the very reason, why `styled-components` was born ;-)

**Comment by probablyup** [comment]
The impetus behind this change is that historically we have had a lot of trouble resolving if a function is a react component or not. This caused all sorts of runtime issues and required ugly syntax workarounds:

```jsx
styled.div.attrs({
  thing: ReactClass, <- error, calling ReactClass without `new` keyword
  thing2: props => ReactClass, <- no error
})
```

From what we've heard from the community, it's also pretty difficult to properly type the object syntax when functions are allowed.

Now it's dead simple:

```jsx
styled.div.attrs(props => ({
  thing: ReactClass, <- no error
}))
```

You get props, you return back whatever you want without having to think about layering of functions. I realize this is a deviation from some of the other syntaxes we use, but ultimately this is better DX and will help you avoid mistakes.
