### ISSUE TITLE
Migrate to babel 7

### ISSUE THREAD

**Issue by kopax** [styled-components/styled-components#2230]
It is just curiosity, but I believe it will be tricky to adapt the rollup configuration.

I would like to know if anyone tried to update this repo to work with  https://babeljs.io/docs/en/v7 ?

**Comment by probablyup** [comment]
It's on the roadmap, but we saw some bundle size regressions so I never shipped the change.

**Comment by kopax** [comment]
@probablyup thanks for the quick answer. 
What do you mean bundle size regressions, could you be more specific? Or maybe, may I see the fork/branch where you tested those change?

**Comment by kopax** [comment]
That's bad news, I wanted to see how you did migrate the rollup and babel part as we have a similar repo inspired from styled-components environment.

**Comment by mmarkelov** [comment]
@kopax You can check my [branch](https://github.com/mmarkelov/styled-components/tree/Update_babel_rollup) - there are problems with tests and code is about 16.5 kB

**Comment by kopax** [comment]
Thanks @mmarkelov for remembering.
