### ISSUE TITLE
v4 styles for child not applied

### ISSUE THREAD

**Issue by delijah** [styled-components/styled-components#2232]
If you put a styled() over a styled() you cannot style the child from the parent anymore.

With version 3.4.9 and/or 2.0.1 this still worked, but with version 4.x.x not anymore.

Hint: If you replace the "<StyledD" with "<D", everything works as expected, because you remove one styled-instance like that.

### System:
 - OS: macOS High Sierra 10.13.5
 - CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
 - Memory: 191.48 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
### Binaries:
 - Node: 8.11.3 - ~/n/bin/node
 - npm: 5.6.0 - ~/n/bin/npm
 - Watchman: 4.7.0 - /usr/local/bin/watchman
### npmPackages:
 - babel-plugin-styled-components: ~1.8.0 => 1.8.0
 - styled-components: ~4.0.3 => 4.0.3

## Reproduction
https://codesandbox.io/s/nnnpyx5jrl

## Steps to reproduce
Just run the example.

## Expected Behavior
It must be possible to style the child as well. The border of the children must be green.

## Actual Behavior
It is not possible to style the child. The border of the children is brown (which is wrong).

**Comment by probablyup** [comment]
Hi there, so one of the major changes in v4 is "component folding", which effectively means that when you do `styled(StyledComponent)` the inner one's styles are lifted up but it isn't actually rendered separately. That's why your example doesn't work in v4. You'll need to refer to which component is actually rendered.

**Comment by boschni** [comment]
@probablyup, we are also running into this issue. We have a component library that contains a `Grid` component that is styling its direct child `GridItem` components with the `>` selector. But when a downstream project wraps a `GridItem` to provide some extra styles, the direct child selector does not work anymore and the grid system breaks. How should this be solved?

**Comment by mxstbr** [comment]
A potential solution

```JS
const gridItemClassName = 'grid-item'; // TODO: Make this more unique
const GridItem = styled.whatever.attrs({
  className: gridItemClassName,
})``

const Grid = styled.whatever`
  .${gridItemClassName} {
    // Override styles
  }
`;
```

**Comment by probablyup** [comment]
I think we'll need to gather up the names as we fold and still attach them anyway. It's the least surprising fix

**Comment by mxstbr** [comment]
But if we attach them won't that also attach the styles? That could have pretty unexpected consequences, no?

**Comment by probablyup** [comment]
Only styles written against component selectors, which is what you want attached anyway. We'd only be lifting the static className.

**Comment by mxstbr** [comment]
Ah that makes sense, sounds sensible!

**Comment by boschni** [comment]
Yeah that sounds like a proper solution :)

**Comment by delijah** [comment]
When will this fix be released?

**Comment by probablyup** [comment]
This week
