### ISSUE TITLE
Cannot create styled-component for component [object Object]

### ISSUE THREAD

**Issue by cihati** [styled-components/styled-components#2233]
## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`

```
## System:
 - OS: macOS High Sierra 10.13.6
 - CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
 - Memory: 160.71 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 8.9.4 - ~/.nvm/versions/node/v8.9.4/bin/node
 - Yarn: 1.10.1 - ~/.nvm/versions/node/v8.9.4/bin/yarn
 - npm: 6.4.1 - ~/.nvm/versions/node/v8.9.4/bin/npm
## npmPackages:
 - styled-components: ^4.1.1 => 4.1.1
```

## Reproduction

As I was trying to upgrade our application from react native 0.55.0 to 0.57.5, I am running into issues with styled-components. Specifically, when I start the app in Android emulator, I get

> Cannot create styled-component for component [object Object]

![image](https://user-images.githubusercontent.com/461998/48780880-cbb93500-ecd2-11e8-90fe-f117ba0c2f8d.png)

**(Surprisingly, I do not get such errors in iOS emulator!)**

The relevant portion of Typography.js (as shows in the image above):

```
const BaseTypography = styled.Text`
  color: ${getFontColor};
  ${color}
  ${props => props.capitalize && capitalizeFirstLetter};
  ${space};
`
```

I am using React 16.6.1, styled-components 4.1.1, @babel/core 7.0.0

Any ideas? I've seen https://github.com/styled-components/styled-components/issues/1308 , but I am not sure if it's relevant.

## Expected Behavior
No error

**Comment by mxstbr** [comment]
The reason must be that you're on a ReactNative version that doesn't handle `React.forwardRef` yet?

**Comment by cihati** [comment]
@mxstbr First of all, I highly appreciate a super quick answer! Why do you think I get no error for iOS, but only get error for Android? Also, is there any workaround?

**Comment by mxstbr** [comment]
Not sure to be completely honest 😕

**Comment by cihati** [comment]
@mxstbr That's really sad =/

By the way, how do you know that React Native does not support `React.forwardRef`? Did you find it out via https://github.com/facebook/react/issues/12814#issuecomment-389157894 or elsewhere?

**Comment by probablyup** [comment]
> By the way, how do you know that React Native does not support React.forwardRef?

I didn't know that but they will have to catch up since it's a core React feature.

**Comment by cihati** [comment]
@probablyup apart from the one comment I linked, I haven't found anything about react native + forwardRef. There's no info in React Native docs either. I did ask in https://github.com/facebook/react/issues/12814#issuecomment-440304239 , let's hope it gets answered.

**Comment by cpetzel** [comment]
This seems to only be happening on Debug Android builds, NOT release/production builds.

Here is an example of how we are creating a styled component. 

```javascript
const Divider = styled.View`
  width: 100%
  height: 1
  backgroundColor: ${colors.greyLighter}
`;
```

Now lets look at how React Native views are represented...

```javascript
import { View } from "react-native";
console.log("RN View == ", JSON.stringify(View));
```
For debug builds, this returns `View == ', '{"$$typeof":60112}'` //object representing a forward ref
For release builds, this returns `View == ', 'RCTView'` //string

Which will configure the styled components for each React Native view  [here.. ](https://github.com/styled-components/styled-components/blob/master/src/native/index.js#L38) 

If you take a look at the `react-is` [variables](https://github.com/facebook/react/blob/master/packages/shared/ReactSymbols.js#L41), you will see it will initialize the following const...

```javascript
var REACT_FORWARD_REF_TYPE = hasSymbol ? Symbol.for('react.forward_ref') : 0xead0;
```

This will get set to `{ _k: 'Symbol(react.forward_ref)_k.i0kqk9t5s8' }` for both release and debug builds. 

Now lets look at the `react-is` isValidElementType() function, which is called from [here](https://github.com/styled-components/styled-components/blob/master/src/constructors/constructWithOptions.js#L14)

```javascript
function isValidElementType(type) {
  return (
    typeof type === "string" || // RELEASE BUILDS WILL EARLY RETURN ON THIS CHECK
    typeof type === "function" ||
    // Note: its typeof might be other than 'symbol' or 'number' if it's a polyfill.
    type === REACT_FRAGMENT_TYPE ||
    type === REACT_CONCURRENT_MODE_TYPE ||
    type === REACT_PROFILER_TYPE ||
    type === REACT_STRICT_MODE_TYPE ||
    type === REACT_SUSPENSE_TYPE ||
    (typeof type === "object" &&
      type !== null &&
      (type.$$typeof === REACT_LAZY_TYPE ||
        type.$$typeof === REACT_MEMO_TYPE ||
        type.$$typeof === REACT_PROVIDER_TYPE ||
        type.$$typeof === REACT_CONTEXT_TYPE ||
        type.$$typeof === REACT_FORWARD_REF_TYPE)) // == 60112
  );
}
```

For release builds, it will return early after hitting this line, because the `tag` param is `RCTView`
```javascript
typeof type === "string"
```

But for debug builds, it will end up checking the Symbol references, which are NOT set correctly in debug builds.

ex...
```javascript
type.$$typeof === `{ _k: 'Symbol(react.forward_ref)_k.i0kqk9t5s8' }`
//instead of what it should be checking, is this...
type.$$typeof === 60112
```

If I hack react-is to not use the symbols, and simply use the hex values (the defaults), then it works on debug builds. 

I am not sure what the correct solution is here... I hope this puts someone on the right track to fixing it :)

**Comment by cihati** [comment]
@cpetzel Thank you so much for the detailed dive-in -- I'm so glad that I'm not alone hitting this issue! Were you running into this problem previously as well, or just started seeing this as you were upgrading? What are the versions of your React Native, React, Babel, Styled Components?

**Comment by HopeFE** [comment]
Whether to import @babel/polyfill?

**Comment by cihati** [comment]
@HopeFE I am not sure if that would help -- we do use `babel-polyfill` in our codebase.

**Comment by HopeFE** [comment]
I had the same problem, but after I removed @babel-polyfill in my projects, it could be run @cihati

**Comment by probablyup** [comment]
I'm going to leave this open for the time being, but doesn't look like an issue with styled-components.

**Comment by kashishgrover** [comment]
This worked for me too. Thanks :)

```
const CustomText = styled((props) => <Text {...props} />)`

`;
```

**Comment by kashishgrover** [comment]
Is someone working on fixing this? While this fix works temporarily, not being able to do `styled.Component` in my project anymore just sucks.

**Comment by creativityhurts** [comment]
> This worked for me too. Thanks :)
> 
> ```
> const CustomText = styled((props) => <Text {...props} />)`
> 
> `;
> ```

I'm having the same issue and this solution doesn't work for me. I haven't found an alternative fix yet.

**Comment by gustavoaz7** [comment]
I work with a huge codebase with lots of modules (which I do not work directly with) that use styled-component and it is simply impossible for me to change this everywhere in our codebase.

There is still no real solution for this issue?

> So, here are what we did, and it somehow worked:
> 
> * Learned through [#1449 (comment)](https://github.com/styled-components/styled-components/issues/1449#issuecomment-420087359)  (changed everywhere in the codebase)
> 
> ```
> // fails
> const ExtendedComponent = styled(OriginalComponent)`
>   [Your awesome styles here]
> `;
> 
> // works
> const ExtendedComponent = styled(props => <OriginalComponent {...props} />)`
>   [Your awesome styles here]
> `;
> ```
> * I removed `babel-polyfill` in all places (but had to add it to one other file)
> * We were importing styled-components in different places in two different ways. In the docs for styled-components, we found this about using the metro bundler for installation. https://www.styled-components.com/docs/basics#simpler-usage-with-the-metro-bundler

**Comment by probablyup** [comment]
My guess is multiple versions of `react-is` are installed and the symbols are getting clobbered as mentioned above. If you install it as a dependency in your project, it should dedupe and the issue will go away.

**Comment by dslounge** [comment]
I filed an issue about this in the react-native repo. I'm having a similar issue and I'm not sure how to fix it: https://github.com/facebook/react-native/issues/24553

**Comment by marrkeri** [comment]
I have 1 generic index.tsx where I do export of all my components.
But some components e.g. ChatRoom is using TextBox so when I had ChatRoom export before TextBox it fails.

// FAILS 
export { default as ChatRoom } from './ChatRoom'
export { default as TextBox } from './Fields/TextBox'

// WORKS 
export { default as TextBox } from './Fields/TextBox'
export { default as ChatRoom } from './ChatRoom'

I hope that this helps.

**Comment by testacode** [comment]
Darn, I'm having this while trying to clean my jest config. Only having this while unit testing.

**Comment by csvan** [comment]
Suddenly ran into this issue when bumping from SC 5.1 to 5.3, never seen it before. In particular, it seems to affect components from https://github.com/chenglou/react-motion.

I am curious what changed between 5.1 and 5.3 that would cause this.
