### ISSUE TITLE
Does it support `::selection `?

### ISSUE THREAD

**Issue by tangweikun** [styled-components/styled-components#2236]
I use `&::selection` in the code like below, but it not work.
```
const CodeWrapper = styled.div`
  position: relative;
  margin-bottom: 30px;

  &::selection {
    background: deeppink;
  }
`
```

**Comment by probablyup** [comment]
Appears to be working fine. https://codesandbox.io/s/pmnkzq5kpm

**Comment by ScottAgirs** [comment]
Sorry to re-open - I've also tried
```
  &::selection {
    background: deeppink;
  }
```
however it won't work. I've tried several lame man's ways too - like without & or with one colon, lol.

`"styled-components": "4.3.1"`
`"next": "^8.1.0",` **- SSR** - could this affect the styles applied to pseudo elements?

**Comment by tangweikun** [comment]
@ScottAgirs `::selection` is not inherited, maybe you are set on the wrong element
