### ISSUE TITLE
'background-clip: text' not vendor prefixed

### ISSUE THREAD

**Issue by dschu-lab** [styled-components/styled-components#2237]
## System:
 - OS: macOS 10.14.1
 - CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
 - Memory: 464.39 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
 - npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
## npmPackages:
 - styled-components: ^4.1.1 => 4.1.1 

## Reproduction

https://codesandbox.io/s/x3m9v30lkw

## Steps to reproduce
Create a styled component using `background-clip: text` property.

## Expected Behavior
Get a vendor prefix

## Actual Behavior
No vendor prefix, style is broken

**Comment by dschu-lab** [comment]
@probablyup Thanks for your fast response. I've created a new sandbox illustrating the same behaviour using vanillaJS + Stylis.

Here's the issue I've created: https://github.com/thysultan/stylis.js/issues/132

**Comment by lvalkov** [comment]
# Asdf 
asda

## Asdf
asdf

### asdf
asdf

#### asdf
asdf

##### asdf
asdf

**Comment by probablyup** [comment]
Thanks @dschu-lab. Going to close this issue since there's nothing to be done on our end.

**Comment by karlhorky** [comment]
Looks like Stylis v4 will have a prefix for `background-clip` so at least this will work when it is released and `styled-components` is updated:

https://github.com/thysultan/stylis.js/issues/132#issuecomment-596498211

**Comment by karlhorky** [comment]
To clarify: this causes an issue before the JavaScript runtime kicks in on a pre-rendered page (eg. `react-snap`) - maybe also when statically generating pages.

An illustration of the problem:

![Kapture 2020-04-07 at 20 46 09](https://user-images.githubusercontent.com/1935696/78707572-1449b080-7911-11ea-9170-02730d1c220c.gif)

The first tab is the version without [my hacky workaround](https://github.com/thysultan/stylis.js/issues/132#issuecomment-544109313). Note the missing `background-clip` styles when:

- refreshing the page
- disabling JavaScript

The second tab uses [my hacky workaround](https://github.com/thysultan/stylis.js/issues/132#issuecomment-544109313) and has no missing styles.
