### ISSUE TITLE
It looks like there are several instances of 'styled-components' 

### ISSUE THREAD

**Issue by jitenderchand1** [styled-components/styled-components#2238]
We have several apps which used the `styled-component` for UI component. Now most of the our component are common which can be shared.  So we are trying to create separate sharable UI component library so everyone can use it or add more component in it and we want to publish it as a NPM package. The idea is the sharable component should be able to take the theme from the app in which they being used.

The challenge we are facing is when are exporting our sharable app using NPM link to see if it work. It gave us following error.

` It looks like there are several instances of 'styled-components' initialized in this application. This may cause dynamic styles not rendering properly, errors happening during rehydration process and makes your application bigger without a good reason.`.

The error is well explained [here](https://www.styled-components.com/docs/faqs#why-am-i-getting-a-warning-about-several-instances-of-module-on-the-page).

Both the solution are kind of forcing user to change something at their end. Some of the our project are been created by create-react-app so they don't have access to webpack.

`npm dedupe` is another way to fix it but it is not good choice because it will not work well with `npm link`. So every time a change is made you have to publish it.

This error was occur because I have two version of styled-component one in my project repo and one in my sharable ui component repo. Even though I have add the `peerDependancy` and have an entry into `webpack` file of shareable ui component repo.  I wonder why this is only happening for `styled-component` why not for `react`. both is the part of `peerDependancy` and we already configured webpack  not to use it's own dependancy instead use from the parent.

Other NPM packages also use the library which was already there in the app in which they being used. eg. react. 

So there are two two version of react in app. One in project and one in node_module but it's work.

**Shareable UI-component file**
**Package.json**
```

{
  "name": "ui-component",
  "version": "1.0.0",
  "description": "Shareable web UI component",
  "main": "build/index.js",
  "scripts": {
    "dev": "start-storybook -p 6006",
    "build": "webpack",
    "build:storybook": "build-storybook",
    "test": "jest --env=jsdom",
    "lint": "eslint"
  },
  "jest": {
    "coverageThreshold": {
      "global": {
        "branches": 80,
        "functions": 80,
        "lines": 80,
        "statements": 80
      }
    },
    "collectCoverageFrom": [
      "src/**/*.{js,jsx}",
      "!storybook-static/**/*.{js,jsx}",
      "!congif/**/*.{js,jsx}"
    ],
    "setupFiles": [
      "<rootDir>/src/enzymeSetup.js"
    ],
    "testMatch": [
      "<rootDir>/src/**/?(*.)(spec|test).{js,jsx,mjs}"
    ],
    "testEnvironment": "node",
    "testURL": "http://localhost",
    "transform": {
      "^.+\\.(js|jsx|mjs)$": "<rootDir>/node_modules/babel-jest"
    },
    "transformIgnorePatterns": [
      "[/\\\\]node_modules[/\\\\].+\\.(js|jsx|mjs)$"
    ],
    "testPathIgnorePatterns": [
      "<rootDir>/__tests__/setup/"
    ],
    "moduleNameMapper": {
      "^@theme": "<rootDir>/src/theme.js",
      "^@validation": "<rootDir>/src/validation/index.js",
      "^@helper": "<rootDir>/src/helper.js"
    },
    "moduleFileExtensions": [
      "web.js",
      "js",
      "json",
      "web.jsx",
      "jsx",
      "node",
      "mjs"
    ]
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "*.js": [
      "npm run lint --fix",
      "cross-env CI=true npm test -- --coverage --bail --findRelatedTests"
    ]
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@material-ui/core": "^3.5.1",
    "@material-ui/icons": "^3.0.1",
    "react": "^16.6.3",
    "react-router-dom": "^4.3.1",
    "styled-components": "^4.1.1"
  },
  "devDependencies": {
    "@babel/core": "^7.1.6",
    "babel-core": "7.0.0-bridge.0",
    "@babel/preset-env": "^7.1.6",
    "@babel/preset-react": "^7.0.0",
    "@storybook/addon-actions": "^4.0.7",
    "@storybook/addon-centered": "^4.0.7",
    "@storybook/addon-info": "^4.0.7",
    "@storybook/addon-links": "^4.0.7",
    "@storybook/addon-options": "^4.0.7",
    "@storybook/addons": "^4.0.7",
    "@storybook/components": "^4.0.7",
    "@storybook/react": "^4.0.7",
    "babel-eslint": "^9.0.0",
    "babel-jest": "^23.6.0",
    "babel-loader": "^8.0.4",
    "css-loader": "^1.0.1",
    "enzyme": "^3.7.0",
    "enzyme-adapter-react-16": "^1.6.0",
    "eslint": "^5.9.0",
    "eslint-config-airbnb": "^17.1.0",
    "eslint-plugin-import": "^2.14.0",
    "eslint-plugin-jsx-a11y": "^6.1.2",
    "eslint-plugin-react": "^7.11.1",
    "file-loader": "^2.0.0",
    "husky": "^1.1.2",
    "jest": "^23.6.0",
    "lint-staged": "^8.0.4",
    "react-dom": "^16.6.3",
    "react-router-dom": "^4.3.1",
    "storybook-styled-components": "^1.1.2",
    "style-loader": "^0.23.1",
    "webpack": "^4.26.0",
    "webpack-cli": "^3.1.2",
    "webpack-dev-server": "^3.1.10"
  },
  "peerDependencies": {
    "react": "^16.6.3",
    "styled-components": "^4.1.1"
  }
}

```
**webpack.js**
```

const path = require ('path');

module.exports = {
  entry: {
    main: './src/index.js',
  },
  output: {
    path: path.resolve(__dirname, './build'),
    filename: 'index.js',
    libraryTarget: 'commonjs2',
  },
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        use: [{
          loader: 'babel-loader',
        }],
      }
    ],
  },
  optimization: {
    splitChunks: {
      cacheGroups: {
        commons: {
          test: /[\\/]node_modules[\\/]/,
          name: 'vendor',
          chunks: 'all',
        }
      }
    }
  },
  plugins: [],
  resolve: {
    alias: {
      '@theme': path.resolve(__dirname, './src/theme.js'),
      '@validation': path.resolve(__dirname, './src/validation/index.js'),
      '@helper': path.resolve(__dirname, './src/helper.js'),
    }
  },
  externals: {
    'react': 'commonjs react', // this line is just to use the React dependency of our parent-testing-project instead of using our own React.
    'styled-components': 'commonjs styled-components' // this line is just to use the React dependency of our parent-testing-project instead of using our own styled-component.
  }
}

```

Any suggestion how to fix this error which having so much change

**Comment by probablyup** [comment]
This FAQ section has some solutions on it: https://www.styled-components.com/docs/faqs#why-am-i-getting-a-warning-about-several-instances-of-module-on-the-page

If you're using yarn, there's also [a package.json hint that can be added called "resolutions"](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) that is like a  beefed up version of `npm dedupe` that really makes sure there is only one version of a particular package in the tree.

**Comment by jitenderchand1** [comment]
@probablyup  I have gone through the FAQ section but as I mention in my question. Some of my projects are still using create-react-app and unfortunately yarn is not there in any of my project.

I just wanted to know why `peerDepedancy` is not working here. Because I have other sharable package which use their own react version but work fine with other packages when it's being used.

I really really need to understand is what is exact issue. I am happy to look after the given solution in FAQ but without knowing the reason it be like waste of time what I have already spent. It is very important for my learning.
