### ISSUE TITLE
Silent error on condition palette call to incorrect theme item 🤯

### ISSUE THREAD

**Issue by GeorgiosP** [styled-components/styled-components#2241]
## System:
 - OS: macOS 10.14
 - CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
 - Memory: 110.11 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 8.12.0 - /usr/local/bin/node
 - Yarn: 1.12.3 - /usr/local/bin/yarn
 - npm: 6.4.1 - /usr/local/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.8.0 => 1.8.0 
 - styled-components: ^4.0.0 => 4.0.0 

## Reproduction
not passing a color and giving an undefined palette option will silently error, almost missed this until I checked my project on safari. 

the style for background wont even show up in the browser

[incorrect palette option](https://cl.ly/58c436495b73)

[correct palette option](https://cl.ly/038a4ed1c166)

button background
```
  background: ${(props: IProps) =>
    props.color ? props.color : palette("whitescale", 0)}; 
```

default theme
```
theme.palette = {
  primary: ["#F7901E"], 
  secondary: ["#00a3d9"],
  danger: ["#C65251"],
  alert: ["#EB9F00"],
  success: ["#519D33"],
  white: ["#ffffff"],
  grayscale: ["#212121", "#616161", "#9e9e9e", "#bdbdbd", "#e0e0e0", "#ffffff"],
}
```

## Steps to reproduce
create a theme, call a option that does not exist within a prop conditional style
## Expected Behavior
warning or error of some sort. 
## Actual Behavior
silently fails and simply does not include the style for background.

**Comment by mxstbr** [comment]
This is expected behaviour, we can't know whether you meant to not interpolate anything and get rid of the whole rule or not!

**Comment by GeorgiosP** [comment]
ok perfect thanks! wasn't sure 👍

**Comment by kitten** [comment]
I'd recommend you to instead use and place a function on the theme to access your palette :) it doesn't make a big difference access wise but you can validate inputs either programmatically or transform input/output. Type systems help too 🙌

**Comment by GeorgiosP** [comment]
awesome thanks!!! 💯
