### ISSUE TITLE
Tests failing after updating to v4

### ISSUE THREAD

**Issue by rjgreaves** [styled-components/styled-components#2242]
After updating to v4.1.1 with enzyme 3.7.0 my tests no longer work as expected.

This is the test that was working:

it('should render an <button> tag', () => {
  const renderedComponent = shallow(<StyledButton />);
  expect(renderedComponent.type()).toEqual('button');
});

## Expected Behavior
Test should pass

## Actual Behavior
Returns error:
Expected value to equal:
      "button"
Received:
      [Function type]

**Comment by probablyup** [comment]
See https://github.com/styled-components/styled-components/issues/1985

Basically enzyme / react-test-renderer handles forwardRef in a weird way. I really don't recommend shallow rendering for React 16 in general.
