### ISSUE TITLE
Typings broken since 4.1?

### ISSUE THREAD

**Issue by JeroenReumkens** [styled-components/styled-components#2243]
Hi There! 

It looks like the Typescript typings are broken since the upgrade to 4.1. There is an issue over at the @types repo, but I just wanted to make an issue here as well because I have the feeling that it otherwise would be overlooked. 

Please feel free to close this issue if you don't think there should be an issue here. 

The issue I'm referring to is: 
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/30536

Thanks a lot for all the effort!!

**Comment by Kovensky** [comment]
They are not broken, and that issue has already been fixed on master. However, the documentation on styled-components is now outdated.

In particular, the types now prefer dealing with component types directly instead of their props for purposes of ensuring the refs are correct.

**Comment by jimjeffers** [comment]
@Kovensky can you share an updated example of how we should specify props moving forward?

**Comment by sweeneyrobb** [comment]
@jimjeffers seems like it is 

```
styled.div<{show: boolean}>(props => `
    display: ${ props.show ? 'block' : 'none' }
`);
```
