### ISSUE TITLE
Upgrade node-fetch to >= 2.3.0 to fix semantic-release users that use styled-components

### ISSUE THREAD

**Issue by kopax** [styled-components/styled-components#2247]
## Environment

We are experiencing issue on travis while using semantic-release.

This happen because of a package having being fixed `node-fetch@2.3.0` for semantic-release to work.

Users that use both semantic-release and styled will have issues. 

- https://github.com/semantic-release/github/issues/129
- https://github.com/semantic-release/semantic-release/issues/995

## Reproduction

https://travis-ci.org/yeutech-lab/rollup-umd-documentation/jobs/459847412

```bash
$ npm ls node-fetch
@yeutech-lab/rollup-umd-documentation@2.4.2 /home/dka/workspace/github.com/yeutech-lab/rollup-umd-documentation
├─┬ @semantic-release/github@5.2.5
│ └─┬ @octokit/rest@16.0.1
│   └── node-fetch@2.3.0 
└─┬ styled-components@4.1.1
  └─┬ css-to-react-native@2.2.2
    └─┬ fbjs@0.8.17
      └─┬ isomorphic-fetch@2.2.1
        └── node-fetch@1.7.3 
```

## Steps to reproduce

- semantic-release: v15.12.1
- styled-components: v4.1.1

## Expected Behavior

To have `node-fetch@2.3.0`

## Actual Behavior

Styled-components bring `node-fetch@1.7.3` and breaks semantic-release.

## Solution

- **short term**: `npm install node-fetch@2.3.0 --save-dev`
- **long term**: Upgrade css-to-react-native or make it optional? (I do not use react-native)

**Comment by JennerChen** [comment]
same problem

**Comment by mxstbr** [comment]
> Upgrade css-to-react-native

Feel free to submit a PR to css-to-react-native to upgrade it's version! https://github.com/styled-components/css-to-react-native

**Comment by kopax** [comment]
@mxstbr thanks for offering to pass the PR, but this touch more than just css-to-react-native.

I've created 3 more issues on each project that needs to be updated, starting with isomorphic-fetch, we need to wait until the author approve the upgrade from `node-fetch` v1 to v2.

Shouldn't we leave this open? Closing an issues prior it's resolution isn't good action.

**Comment by mxstbr** [comment]
> but this touch more than just css-to-react-native.
> I've created 3 more issues on each project that needs to be updated, starting with isomorphic-fetch, we need to wait until the author approve the upgrade from node-fetch v1 to v2

Ahh I see, I didn't get that. Thank you!

> Shouldn't we leave this open? Closing an issues prior it's resolution isn't good action.

There isn't really anything to do in the styled-components package, so it doesn't make sense for this issue to stay open, right? There's nothing we can do to resolve this, so I think the one in the `css-to-react-native` project is perfect! 👍
