### ISSUE TITLE
Props are not evaluated for nested inheritance

### ISSUE THREAD

**Issue by Chaoste** [styled-components/styled-components#2250]
## Environment
```
## System:
 - OS: macOS High Sierra 10.13.6
 - CPU: x64 Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
 - Memory: 465.56 MB / 8.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 11.0.0 - /usr/local/bin/node
 - Yarn: 1.12.1 - /usr/local/bin/yarn
 - npm: 6.4.1 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: >= 1 => 1.8.0 
```
## Reproduction
See the related PR #2249 for reproduction code.

Examples for not working chains:
`styled(styled(styled.h1``)``.withComponent('h3'))`` `
`styled(styled(styled.h1``.withComponent('h2'))``.withComponent('h3'))`` `

Working chains:
`styled(styled.h1``)`` `
`styled(styled.h1``.withComponent('h2'))`` `
`styled(styled(styled.h1``.withComponent('h2'))``)`` `

## Steps to reproduce
1. Create a styled component which has some attributes which can be controlled through props:  `Parent = styled.h2`[...]` `
2. Extend `Parent` by using `Child = styled(Parent.withComponent('h2')`` ` since extend is deprecated.
3. Extend `Child` by `Grandson= styled(Gradson.withComponent('h3'))`` `
4. Child and Grandson should not override a property usage of Parent. However passing a prop to Grandson is not propagated through to the Parents styles.

## Expected Behavior
I use the 'correct' chaining of `withComponent` and `styled`. Therefore, I expect to have all props from my parent even if they are again inherited by another component.

## Actual Behavior
The props from a parents parent component disappear.

**Comment by mxstbr** [comment]
Does this work if you don't use `.withComponent` but the `as` prop? If so, just don't use `.withComponent`, it's pretty much deprecated anyway in favor of the `as` prop... 😅

**Comment by Chaoste** [comment]
Actually, I'd like to cry now - It works with `styled(Parent).attrs({as: 'h2})` 😭 😆

**Comment by Chaoste** [comment]
I updated the PR if you still want to have the unit tests. Thanks for the quick reponse!

**Comment by mxstbr** [comment]
No worries, happy to help! Glad it's resolved, and thanks for providing tests with the issue—would've made it a lot easier to fix, much appreciated :+1:
