### ISSUE TITLE
Child style rule ignored

### ISSUE THREAD

**Issue by artooras** [styled-components/styled-components#2252]
## System:
 - OS: macOS 10.14
 - CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
 - Memory: 102.24 MB / 8.00 GB
 - Shell: 2.7.1 - /usr/local/bin/fish
## Binaries:
 - Node: 8.11.2 - /usr/local/bin/node
 - npm: 5.6.0 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^4.1.1 => 4.1.1 

## Reproduction

https://codesandbox.io/s/42rm6v0804

## Steps to reproduce

Hover over the button.

## Expected Behavior

I would expect the underline style to not be applied to the child (Icon) component. However, the style even with `!important` is ignored.

## Actual Behavior

The underline is applied to the Icon.

**Comment by probablyup** [comment]
This is just how CSS works, see this sandbox implemented with regular HTML that has the same behavior: https://codesandbox.io/s/pky06r41qq
