### ISSUE TITLE
Babel macro with TypeScript and Create React App

### ISSUE THREAD

**Issue by soavie** [styled-components/styled-components#2253]
## System:
 - OS: macOS High Sierra 10.13.6
 - CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
 - Memory: 441.45 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
 - npm: 6.4.1 - ~/work/playground/sc-macro/node_modules/.bin/npm
## npmPackages:
 - styled-components: ^4.1.1 => 4.1.1 

## Reproduction

Apologies, I was unable to use the babel macro in codesandbox, so I threw together a quick CRA:

Create a react app with TypeScript:

```bash
npx create-react-app sc-macro --typescript
```

Then, following the [API docs for TypeScript](https://www.styled-components.com/docs/api#typescript), create a `theme.ts` file in `src/`:

```js
export default interface ThemeInterface {
  primaryColor: string;
  primaryColorInverted: string;
}
```
as well as a `styled-components.ts` file:

```js
import * as styledComponents from "styled-components";
import { ThemedStyledComponentsModule } from "styled-components";

import ThemeInterface from "./theme";

const {
  default: styled,
  css,
  createGlobalStyle,
  keyframes,
  ThemeProvider
} = styledComponents as ThemedStyledComponentsModule<ThemeInterface>;

export { css, createGlobalStyle, keyframes, ThemeProvider };
export default styled;
```

Finally, import and use the custom `styled-components.ts` module in `App.tsx`:

```js
import React, { Component } from "react";
import styled from "./styled-components";
import logo from "./logo.svg";
import "./App.css";

const Foo = styled.p`
  color: red;
`;

class App extends Component {
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <Foo>
            Edit <code>src/App.tsx</code> and save to reload.
          </Foo>
          <a
            className="App-link"
            href="https://reactjs.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            Learn React
          </a>
        </header>
      </div>
    );
  }
}

export default App;
```

Run `npm start` to fire up the app. It should compile successfully and the text should be red.

## Steps to reproduce

Update the import in `styled-components.ts` from:

```js
import { ThemedStyledComponentsModule } from "styled-components";
```

to use the [babel macro](https://www.styled-components.com/docs/tooling#babel-macro):

```js
import { ThemedStyledComponentsModule } from "styled-components/macro";
```

You should now get the following error:

```bash
./src/styled-components.ts
TypeError: Cannot read property 'name' of undefined
    at Array.map (<anonymous>)
```

## Expected Behavior

I would expect it to compile successfully, as the non-macro version did. I would also expect to then be able to [see the component name](https://www.styled-components.com/docs/tooling#better-debugging) on the `class` attribute in the page source (to verify that the plugin is working).

## Actual Behavior

```bash
./src/styled-components.ts
TypeError: Cannot read property 'name' of undefined
    at Array.map (<anonymous>)
```

**Comment by DevanB** [comment]
I'm running into this same exact thing now. While it isn't holding me up, those nice `displayName`s are sweet goodness

**Comment by probablyup** [comment]
I'm guessing DefinitelyTyped needs to be adjusted. Can you move this issue over there? We don't maintain the types here since v4.

**Comment by DevanB** [comment]
This isn't a types issue. It's happening on build for me.

**Comment by probablyup** [comment]
`ThemedStyledComponentsModule` comes from the TS side

**Comment by DevanB** [comment]
Oh, I didn't realize that till now. Interesting. Perhaps this does need to be moved to the DefinitelyTyped side. Sorry about that!

**Comment by probablyup** [comment]
Not sure, I don't use TS in my projects. Please do move over the issue though where you're more likely to get useful feedback

**Comment by soavie** [comment]
Thanks for your help @probablyup and @DevanB. I've moved the issue over to DefinitelyTyped and we'll see where the trail leads next!

**Comment by sebastien-p** [comment]
As @DevanB wrote I'm pretty sure this is not a typings issue.

Here's what I had to do to make it work:

```typescript
// FIXME: https://github.com/styled-components/styled-components/issues/2253

// import { ThemedStyledComponentsModule } from 'styled-components';
// import * as styledComponents from 'styled-components/macro';

// export const {
//   default: styled,
//   createGlobalStyle,
//   ThemeProvider
// } = styledComponents as ThemedStyledComponentsModule<Theme>;

import { ThemedStyledComponentsModule } from 'styled-components';

import styledComponents, {
  createGlobalStyle as styledCreateGlobalStyle,
  ThemeProvider as StyledThemeProvider
} from 'styled-components/macro';

export type Theme = {
  margin: string;
  primaryColor: string;
  secondaryColor: string;
};

export const {
  default: styled,
  createGlobalStyle,
  ThemeProvider
} = {
  default: styledComponents,
  createGlobalStyle: styledCreateGlobalStyle,
  ThemeProvider: StyledThemeProvider
} as ThemedStyledComponentsModule<Theme>;
```

The issue still is present.

**Comment by sebastien-p** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/30915#issuecomment-467934733

**Comment by chriserickson** [comment]
A valid workaround is shown here:
https://github.com/styled-components/styled-components/issues/2368
