### ISSUE TITLE
Consider creation of multiple components at once

### ISSUE THREAD

**Issue by dearfrankg** [styled-components/styled-components#2257]
Consider creation of multiple components at once

```js 
styled.createComponents`

  Button.button {
    color: #000;
    border: 1px solid black;
    width: 100px;
    height: 100px;
    margin-top: -1px;
    margin-right: -1px;
    font-size: 3rem;
    font-weight: bold;

    &:focus {
      outline: none;
    }
  }

  Board.div {
    display: inline-block;
    border: 5px solid black;
    border-radius: 5px;
  }
`
```

**Comment by probablyup** [comment]
Can't do this due to how component selectors work and such. We need a 1:1 creation of component to saved variable. You could probably make yourself a helper to get most of the way there, but you'll have issues when server side rendering

**Comment by dearfrankg** [comment]
Please get a second opinion -  there is no impossible :)

**Comment by probablyup** [comment]
I'm one of the primary maintainers of the library and know how it works. Sorry.
