### ISSUE TITLE
Can I use keyframes with props on styled-component attribute(v4)?

### ISSUE THREAD

**Issue by schang124** [styled-components/styled-components#2263]
Hi, I have been using styled-component attribute and keyframes with props dynamically on **v3**.
However, **v4** dose not allow me due to interpolation issue.

```javascript
// Keyframes
export const verticalMove = props => keyframes`
    0% {
      transform: translateY(${props.initialTranslateY}px);
    }

    100% {
      transform: translateY(${props.translateY}px);
    }
  `;

// Component - interpolation error
const Animate = styled.div.attrs(props => ({
    style: {
        animation: `${verticalMove} 1s ease-in-out`
    }
}))``

// Component - no error
const AnimateNoError = styled.div`
    animation: `${verticalMove} 1s ease-in-out`
`

// Usage
<Animate initialTranslateY={10} translateY={50} />Target</Animate>
```

The component *Animate* using attribute causes interpolation error like below
```
Unhandled Rejection (Error): It seems you are interpolating a keyframe declaration (eblbVe) into an untagged string. This was supported in styled-components v3, but is not longer supported in v4 as keyframes are now injected on-demand. Please wrap your string in the css\`\` helper (see https://www.styled-components.com/docs/api#css), which ensures the styles are injected correctly.
```

I really want to use the keyframes with attribute. 
Please help if anyone know there is any better or correct way to do this.

**Comment by mxstbr** [comment]
As the warning you're getting says, that is not a supported pattern in v4 as `keyframes` are now injected lazily and now longer return the animation name directly. See item number 6 in the migration guide: https://www.styled-components.com/docs/faqs#what-do-i-need-to-do-to-migrate-to-v4

This should work:

```JS
export const verticalMove = keyframes`
    0% {
      transform: translateY(${props => props.initialTranslateY}px);
    }

    100% {
      transform: translateY(${props => props.translateY}px);
    }
  `;
```

**Comment by lifeiscontent** [comment]
@mxstbr who should I reach out to about this API and updating the typescript types? I'd like to use this but typescript is saying it doesn't exist.
