### ISSUE TITLE
Style in child component not changing when wrapped inside a container component

### ISSUE THREAD

**Issue by Richacinas** [styled-components/styled-components#2264]
## Environment

```
## System:
 - OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
 - CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
 - Memory: 7.49 GB / 15.53 GB
 - Container: Yes
 - Shell: 4.4.19 - /bin/bash
## Binaries:
 - Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
 - npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
## npmPackages:
 - styled-components: ^4.1.1 => 4.1.1 
```

## Reproduction

I am getting different results in **codepen** and **codesandbox**.

Using same React, ReactDom and Styled components Versions:

[Codepen](https://codepen.io/Richacinas/pen/WYWMZV) (Wrong behaviour)

[CodeSandbox](https://codesandbox.io/s/2pnoo7ynxp) (Expected behaviour)

## Steps to reproduce

Watch how the buttons are rendered the same color in Codepen, and then watch the behaviour in CodeSandbox. The second button is rendered with a red background, when it is wrapped inside the Container component.

## Expected Behavior

I am getting the same result as in Codepen. My components don't change their style depending on container.

The expected behaviour is that I can change styles depending con container (context) so a certain small component becomes truly reusable. I know I could make it work passing props, but I would have to pass those props through a few components that shouldn't need to know about them, plus I have to be thinking about names for those props that are only used to include a set of styles, and it quickly becomes a mess of hard to understand props.

## Actual Behavior

Style in child component not changing when wrapped inside a container component.

**Comment by mxstbr** [comment]
You have to move the `Container` declaration over the `Button` declaration: https://codepen.io/anon/pen/XyQEgE

**Comment by Richacinas** [comment]
THANK YOU SO MUCH

**Comment by mxstbr** [comment]
No worries, happy to help!
