### ISSUE TITLE
Redux's connect() is not applied when overriding styles with styled()

### ISSUE THREAD

**Issue by kirillku** [styled-components/styled-components#2266]
## Reproduction
Seems that in `v4` Redux's `connect()` is not applied when wrapping connected styled component in `styled()`. I think it's somehow related to #2246.

[codesandbox example](https://codesandbox.io/s/v8lqko4x3)

## Expected Behavior
Should have props from Redux's `connect()`, check `FixedStyledConnectedBox`

## Actual Behavior
Seems that Redux's `connect()` was not called and props are not passed. There is 3 components mounted and `connect()` is only called 2 times, you can see in console.

**Comment by mxstbr** [comment]
You have to use the newest version of react-redux for `forwardRef` support, I'm pretty sure that's the issue here: https://github.com/reduxjs/react-redux/issues/914
