### ISSUE TITLE
Styled Component PropType

### ISSUE THREAD

**Issue by NSLS** [styled-components/styled-components#2271]
## Description

Recently in our project we started noticing weird PropTypes errors in components, which accept another components in their props.

A typical example is a `<Field />` component from `redux-form`, which is commonly used as
`<Field component={Input} />`.

In our use cases the passed component is a component wrapped in `styled()`, to inject some additional styles to the field.

Everything works fine, but when such `styled()` component goes through PropTypes check, it fails with a warning like "Failed prop type: Invalid prop `component` supplied to ...".

By debugging the PropTypes of the `Field` component and the type of the styled component, I found out that the return value of `styled()` call gets interpreted by PropTypes as an object, when majority of PropType rules for this case validate for either func, string or a node, but not an object.

This is quite weird as I'm not really sure if it's the problem with the styled-components or prop-types library, but I hope you will help us with this.

## System:
 - OS: macOS 10.14
 - CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
 - Memory: 136.18 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 10.14.1 - /usr/local/bin/node
 - Yarn: 1.9.4 - /usr/local/bin/yarn
 - npm: 6.4.1 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: ^1.5.1 => 1.9.2
 - styled-components: ^4.1.2 => 4.1.2

## Reproduction

1. Open sandbox
https://codesandbox.io/s/14r2xn4n7j
2. Open browser devtools' console
3. You should see a warning "Warning: Failed prop type: Invalid prop `component` supplied to `Wrapper`."

## Steps to reproduce

1. Create a `styled()` component
2. Pass it to a component as a prop
3. Add a PropTypes validation to this prop as follows:
```
PropTypes.oneOfType([
    PropTypes.func,
    PropTypes.string,
    PropTypes.node
]).isRequired
```
4. You should now see the warning, as styled components gets interpreted as an object 

## Expected Behavior

The component should be interpreted as a function or node by the prop-types

## Actual Behavior

Component is treated as an object and a warning is thrown

**Comment by mxstbr** [comment]
This is a problem with the PropTypes library, you probably have to update it. styled-components v4 returns a `React.forwardRef` object, which needs to be accounted for in `PropTypes.node`!

**Comment by NSLS** [comment]
Apparently prop-types package doesn't support a valid type for a `forwardRef` component.

For anyone stumbling upon this, here is the issue in the prop-types repo:
https://github.com/facebook/prop-types/issues/200

**Comment by natterstefan** [comment]
Just FTR, this worked for me: https://github.com/facebook/prop-types/issues/200#issuecomment-447754082.

**Comment by franzmoro** [comment]
You can now use `elementType` ([see this comment](https://github.com/facebook/prop-types/issues/200#issuecomment-462237174)).
