### ISSUE TITLE
input.attrs error

### ISSUE THREAD

**Issue by xhochipe** [styled-components/styled-components#2275]
1. 
   
input is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`.
    in input (created by Context.Consumer)
    in StyledComponent (created by styled.input)
    in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)
    in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)
    in Header (at App.js:7)
    in App (at src/index.js:6)

2. 
  ` create-react-app creare pro,`
    ``` export const NavSearch =styled.input.attrs({placeholder:"aaa" })`padding:0 15px; `; ```

use:
                `<Nav>
                    <NavSearch>搜索</NavSearch>
                </Nav>`
This will give you an error，The official website example is also used in this way，I don't know why this is a problem，So ask for help

**Comment by julioxavierr** [comment]
Hi, @xhochipe !

Just made a CodeSandbox using an input for example... Apparently the error is happening because you are defining a children (搜索) to the `input`, this shouldn't happen.
Also, it's nice that you define the type of the input too.

Take a look:
https://codesandbox.io/s/o71vq8wyjy
