### ISSUE TITLE
[doc] Are semi colon trimmed when concatened with css?

### ISSUE THREAD

**Issue by kopax** [styled-components/styled-components#2277]
I can see here https://www.styled-components.com/docs/api#keyframes that the last `;` on `css` and `styled.button` call is present twice:

```js
import styled, { css, keyframes } from 'styled-components'

const pulse = keyframes`
  0% {
    opacity: 0;
  }
  100% {
    opacity: 1;
  }
`

const animation = props =>
  css`
    ${pulse} ${props.animationLength} infinite alternate;
  `

const PulseButton = styled.button`
  animation: ${animation};
`
```

Is the extra semicolon removed or is it an error in the example?

**Comment by mxstbr** [comment]
No the CSS is valid, the `;;` just produces an empty statement and is removed 👍
