### ISSUE TITLE
Styled components extending React components Does not work as documented

### ISSUE THREAD

**Issue by shani-arnon** [styled-components/styled-components#2282]
Styled components extending React components Does not work as [documented](https://www.styled-components.com/docs/advanced#caveat)

use this online [failing example](https://codesandbox.io/s/zly6lo4omp) to see for yourselves 

## Environment
The online [example](https://codesandbox.io/s/zly6lo4omp) is using codesandbox.io with create-react-app

## Expected Behavior
I expect to be able to apply styles to the child react component from the parent and extend it.

## Actual Behavior
The styles on the parent (B) have no effect on child (A)

**Comment by probablyup** [comment]
You're using what we refer to as a "component selector" for those styles to be applied, A would need to physically be inside B in the DOM.

**Comment by shani-arnon** [comment]
I have tried your solution [here](https://codesandbox.io/s/1yk6lvrq3q)
As you can see it does NOT solve the problem
Can you please fork my example and provide a working code BEFORE closing this issue?
That would be kind of you

**Comment by probablyup** [comment]
https://codesandbox.io/s/ly03yqn0l9

**Comment by shani-arnon** [comment]
Thanks for that :)
I've been messing with it for too long and the documentation does not mention this...
cheers
