### ISSUE TITLE
Adding env var with webpack causes an error

### ISSUE THREAD

**Issue by mrpsiho** [styled-components/styled-components#2283]
## System:
 - OS: macOS 10.14.1
 - CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
 - Memory: 107.55 MB / 8.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 8.9.1 - /usr/local/bin/node
 - Yarn: 1.3.2 - /usr/local/bin/yarn
 - npm: 6.4.1 - /usr/local/bin/npm

## Steps to reproduce

Adding this code to my webpack config breaks 'styled-components' package:

```
new webpack.ProvidePlugin({
            'process.env.NODE_ENV': JSON.stringify(process.env.NODE_ENV)
})
```

## Expected Behavior
Everything should work

## Actual Behavior
I have got `Error: Cannot find module 'undefined'` error.

```
webpackEmptyContext
webpack:///./node_modules/styled-components/dist_sync?:2:10
<anonymous>
webpack:///./node_modules/styled-components/dist/styled-components.browser.esm.js?:2352:133
```

**Comment by probablyup** [comment]
Not familiar with that plugin... can you try `webpack.DefinePlugin` instead?

**Comment by mrpsiho** [comment]
@probablyup Thanks, it works now. It looks like I am misusing `webpack.ProvidePlugin`. I really should use `webpack.DefinePlugin` for adding env variables to my app.
