### ISSUE TITLE
refs does not work as documented

### ISSUE THREAD

**Issue by reduxdj** [styled-components/styled-components#2287]
version 4.03 - styled components, refs do not work width video players or at least I can't get any thing but null, but trying with an input or or other styled component works fie

https://github.com/styled-components/styled-components/blob/master/docs/tips-and-tricks.md

**Comment by reduxdj** [comment]
oh this does not work with a html 5 video tag:
```              <SimpleStyledVideoPlayer
                  ref={this.videoPlayer}
                  autoplay
                  controls
                  mp4="src"
                />```

```const SimpleVideoPlayer = ({mp4, ...props}) => (
  <video controls preload="auto" width="720" >
    <source src={mp4} type="video/mp4" />
    <track kind="captions" {...props} />
  </video>
)

SimpleVideoPlayer.defaultProps = {
  mp4: null
}
SimpleVideoPlayer.propTypes = {
  mp4: PropTypes.string
}```

**Comment by stevemao** [comment]
Hi @reduxdj, I don't understand if there's a bug in SC or not based on your second comment. Perhaps elaborate a little bit?
