### ISSUE TITLE
Request: use :global or :local similar to css-modules

### ISSUE THREAD

**Issue by taylorgoolsby** [styled-components/styled-components#2288]
I like to use `styled-components` like this (and I hope many other people do too):
```
function MyComponent() {
  return (
    <StyledComponent>
      <div className="direct-child">
        <div className="indirect-child"/>
      </div>
    </StyledComponent>
  )
}

const StyledComponent = styled.div`
  & > .direct-child {

  }

  .indirect-child {

  }
`

function TopLevelComponent() {
  return (
    <StyledTopLevel>
      <MyComponent/>
    </StyledTopLevel>
  )
}

const StyledTopLevel = styled.div`
  .indirect-child {
    // the styling here will affect the div inside MyComponent.
    // I want to prevent this from happening.
  }
`
```

I like to do this because I don't like making a bunch of styled components for wrappers and children.

The example above is contrived. But this is a pattern which I run into sometimes where it turns out to be simpler to describe class rule as an indirect descendant.

However, declaring rules `& .indirectly {}` will cause a problem if a top-level component also defines rules for a component of the same name.

I like how this is handled with css-modules where by default, all classes are `:local`, and you can opt out by using `:global`, or vise versa depending on your configuration.

Ideally, there is a babel plugin or a webpack plugin that will preprocess files that use `styled()()`. If it sees a className inside `styled()()` then it will transform it by prepending it with the filename, or a hash, and then it will find all occurences of that string in any `className` props on any children of the component create by the call to `styled()()`.

For backwards compatibility, I guess the default behavior is all classNames found inside `styled()()` are global, but it would be nice to be able to switch that around via configuration like you can with css-modules.

By doing this, then you can easily isolate each component's namespace.

It would look like this:

```
function MyComponent() {
  return (
    <StyledComponent>
      <div className="direct-child">
        <div className="indirect-child"/>
        <div className="global-rule"/>
      </div>
    </StyledComponent>
  )
}

const StyledComponent = styled.div`
  & > .direct-child {

  }

  .indirect-child {
    // the className here is automatically transformed to .hh3k34-indirect-child
    // Somehow, all the div className props are also transformed to "hh3k34-indirect-child"
  }
  
  :global(.global-rule) {
  
  }
`

function TopLevelComponent() {
  return (
    <StyledTopLevel>
      <MyComponent/>
    </StyledTopLevel>
  )
}

const StyledTopLevel = styled.div`
  .indirect-child {
    // the className here is automatically transformed to .abcdef-indirect-child
    // it's different from the inner .indirect-child, so it won't have an effect.
  }
  
  :global(.global-rule) {
    // opt out of the namespacing behavior
  }
`
```

I don't know much about how babel transform works and what its limitation are and whether or not this is possible, but in case it isn't, here is an alternative which requires a bit more work to setup:

```
import styled, {local} from 'styled-components'

const directChild = local('direct-child')
const indirectChild = local('indirect-child')
const I_dont_care_if_its_readable = local() // generate a BEM or Pacomo for source mapping

function MyComponent() {
  return (
    <StyledComponent>
      <div className={directChild}>
        <div className={indirectChild}/>
        <div className={I_dont_care_if_its_readable}/>
        <div className="global-rule"/>
      </div>
    </StyledComponent>
  )
}

const StyledComponent = styled.div`
  & > ${indirectChild} {

  }

  ${indirectChild} {

  }
  
  .global-rule {
  
  }
`

function TopLevelComponent() {
  return (
    <StyledTopLevel>
      <MyComponent/>
    </StyledTopLevel>
  )
}



const StyledTopLevel = styled.div`
  ${indirectChild} {
    
  }
  
  .global-rule {
    
  }
`
```

What do you think?

**Comment by imbhargav5** [comment]
You can use global styles using createGlobalStyle and put in as many global rules as you like in them. 

Also can you elaborate on the .global-rule inside a local rule use-case? That would just be a global rule right? Does it have to be within that div's scope?  

const StyledComponent = styled.div`
  & > ${indirectChild} {

  }

  ${indirectChild} {

  }
  
  .global-rule {
  
  }
`

**Comment by taylorgoolsby** [comment]
Hi. Thanks for the reply.

The `createGlobalStyles` function does not solve the problem. To clarify, the problem is that classname inside `styled()()` are global but I want them to be locally isolated.

For example if this is my styled component declaration:

```
const SomeComponent = styled.div`
  & .some-classname {
  }
`
```

Then `some-classname` is actually a global. It's not local. `SomeComponent` will be given a className which is locally isolated, but `some-classname` is still global.

`createGlobalStyles` is used when you want to define global styles without necessarily attaching styles to a component. The problem I am presenting here is that styles attached to a component are in fact global, not local. Only the root of the component is locally isolated. In other words, `&` is locally isolated, but rules nested in the SASS are global.

___

If that is still confusing, I made a working example here:
https://github.com/taylorgoolsby/styled-components-global-problem/blob/master/src/App.js

The problem is the TopLevelComponent is able to define global rules which will affect children: https://github.com/taylorgoolsby/styled-components-global-problem/blob/master/src/components/TopLevelComponent.js#L19-L21

And here is the child: https://github.com/taylorgoolsby/styled-components-global-problem/blob/master/src/components/BottomComponent.js#L10

___

One of the reasons I like using `styled-components` is because I don't have to worry about coming up with non-clashing names as much as I would have to if I was using traditional CSS. However, I am pointing out that `styled-components` still has problems with clashing, more so than CSS-Modules did because CSS-Modules made everything local by default in a way that was compatible with SASS nesting.  Where `styled-components` fall short is that even though `styled-components` makes the root `&` local, everything nested within the SASS isn't.

**Comment by pixelass** [comment]
@taylorgoolsby 	I'm not sure if this helps but what you are asking for can basically already be done without having to write a className over and over.(

(if you need readable names use the babel plugin)

Example: https://codesandbox.io/s/v38vlpkp97

<img width="440" alt="screen shot 2018-12-17 at 01 30 38" src="https://user-images.githubusercontent.com/1148334/50060977-65251b00-019b-11e9-9ced-5c285b8cc3bd.png">



```jsx
import * as React from "react";
import { render } from "react-dom";
import styled, { createGlobalStyle } from "styled-components";

const GlobalStyle = createGlobalStyle`
  .global-rule {
    background orange;
    color: black;
  }
`;

// const directChild = local('direct-child')
const DirectChild = styled.div``;
//const indirectChild = local('indirect-child')
const IndirectChild = styled.div``;
//const I_dont_care_if_its_readable = local() // generate a BEM or Pacomo for source mapping
const Idk = styled.div``; // generate a BEM or Pacomo for source mapping

function MyComponent() {
  return (
    <StyledComponent>
      <DirectChild>
        <IndirectChild>Indirect</IndirectChild>
        <Idk>I don't care</Idk>
        <div className="global-rule">GLOBAL RULE</div>
      </DirectChild>
    </StyledComponent>
  );
}

const StyledComponent = styled.div`
  & > ${IndirectChild} {
    font-weight: bolder;
  }

  ${IndirectChild} {
    color: red;
  }

  .global-rule {
    border: 10px solid blue;
  }
`;

function TopLevelComponent() {
  return (
    <StyledTopLevel>
      <MyComponent />
    </StyledTopLevel>
  );
}

const StyledTopLevel = styled.div`
  ${IndirectChild} {
  }

  .global-rule {
    border-style: dashed;
  }
`;
const App = () => (
  <React.Fragment>
    <TopLevelComponent />
  </React.Fragment>
);

render(<App />, document.getElementById("root"));

```

**Comment by mxstbr** [comment]
I think this has been answered pretty thoroughly, we're unlikely to support anything like this in styled components since it conceptually doesn't really make sense to uniquely scope strings inside the CSS block—how would get them out?
