### ISSUE TITLE
Doc needs to make clear if css prop will be recreated on every render pass

### ISSUE THREAD

**Issue by desmap** [styled-components/styled-components#2289]
The doc says [Define Styled Components outside of the render method](https://www.styled-components.com/docs/basics#define-styled-components-outside-of-the-render-method) which makes sense but does it mean that CSS props in components trigger a recreation with every render as well? If yes we need to add this to [css prop](https://www.styled-components.com/docs/api#css-prop).

**Comment by mxstbr** [comment]
No. CSS props get transformed at build-time to static styled components, e.g.

```JS
const Button = (props) => <button css={`
  color: ${props.primary ? 'papayawhip' : 'palevioletred'};
  background: ${props.primary ? 'palevioletred' : 'papayawhip'};
`} />

// conceptually this gets turned into
const StyledButton = styled.button`
  color: ${props => props.primary ? 'papayawhip' : 'palevioletred'};
  background: ${props => props.primary ? 'palevioletred' : 'papayawhip'};  
`

const Button = (props) => <StyledButton primary={props.primary} />
```

I hope that helps!
