### ISSUE TITLE
Add screenshot integration tests

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components#229]
We should do automated browser testing for each PR to make sure we don't have regressions like #212 again and to make sure our injection mechanism works as expected.

~~I have never done that, so if somebody has tips on free services we could use to test on IE10+ and all major evergreen browser that'd be 👌 It basically just needs to make sure our example in the `example/` folder renders as expected in all browsers and doesn't throw errors.~~

The best way to go about this would be to use screenshot integration testing, similar to [what we do for the styled-components website](https://github.com/styled-components/styled-components-website/pull/168). Essentially, have a simple page that you render with `puppeteer`, then screenshot it and compare it against a stored screenshot in the repo. If there's any diversion between the screenshots (i.e. if any injected styles have changed), fail the tests.

This would be a great first task for anybody wanting to start contributing to styled-components. Take a look at the website PR (https://github.com/styled-components/styled-components-website/pull/168) and implement something based on that in this repo.

**Comment by thisguychris** [comment]
@mxstbr take a look at saucelabs.

**Comment by FezVrasta** [comment]
I can take this, I literally just finished tweaking the SauceLabs tests for one of my projects, I could simply copy-paste the setup.

We should add `karma` and `karma-sauce-launcher` to be able to run `mocha` in the SL browsers.

Would it be okay @mxstbr?

**Comment by mxstbr** [comment]
I would love for you to do that @FezVrasta!

**Comment by geelen** [comment]
@FezVrasta thanks so much for picking this up! I'm going to add some comments against your PR. ❤️

**Comment by yanivefraim** [comment]
@FezVrasta @mxstbr - why Karma and not Selenium Webdriver? Selenium Webdriver is the standard way to write browser tests. It let you test on real browsers plus use service like [Applitools](https://applitools.com/) (we use them @ our company), which let you compare an image of your component before and after your change, so you have control over breaking UI changes... WDYT?

**Comment by mxstbr** [comment]
@yanivefraim no strong opinion on either, if you want to go ahead and submit a PR that integrates Selenium I'd love you forever!

**Comment by mxstbr** [comment]
We should do screenshot integration tests instead of relying on an external service, now that that's very easy to do with `puppeteer`. See the styled-components-website PR by @philpl https://github.com/styled-components/styled-components-website/pull/168, we'd love a PR that implements something similar!

**Comment by maciej-ka** [comment]
I will be happy to work on this.

**Comment by morajabi** [comment]
@maciej-ka Awesome! I strongly recommend taking a look at what @philpl did there as the first step as @mxstbr mentioned too. 
https://github.com/styled-components/styled-components-website/pull/168

**Comment by mxstbr** [comment]
Awesome @maciej-ka, it's all yours! Looking forward to the PR, if you got any questions ping me on Spectrum: https://spectrum.chat/styled-components

**Comment by maciej-ka** [comment]
Running `yarn`, `yarn build` and `yarn dev` and visiting localhost:3000 ends with my sad face looking at: 
<img width="295" alt="screen shot 2017-12-15 at 19 16 24" src="https://user-images.githubusercontent.com/5403694/34054714-78e2805a-e1cc-11e7-86ed-d8ab1a11e63b.png">

**Comment by maciej-ka** [comment]
Tried with `NODE_ENV=development yarn build`, didn't help
