### ISSUE TITLE
Pseudo elements with id selectors are not respected like html tags

### ISSUE THREAD

**Issue by Can-Sahin** [styled-components/styled-components#2291]
## System:
 - OS: macOS 10.14.1
 - CPU: (8) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
 - Memory: 204.44 MB / 8.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 8.12.0 - /usr/local/bin/node
 - Yarn: 1.6.0 - /usr/local/bin/yarn
 - npm: 6.4.1 - /usr/local/bin/npm
## npmPackages:
 - babel-plugin-styled-components: 1.8.0 => 1.8.0
 - styled-components: 4.1.2 => 4.1.2

## Reproduction

https://codesandbox.io/s/v8kpqk56k3

## Expected Behavior

I am trying to assign `before` `after` pseudo elements to all of the children of a specific element (element with an id) like

 ```
#header {
  ::after {
    box-sizing: border-box;
  }

  a {
    font-size: 1em;
  }
}
```

 which should add `after` to all the children of `header` element. But this gets converted into `#header::after {...}` (trimming the space in the middle) as if it was with `&`. 

Currently it behaves like
```
#header {
  &::after {
    box-sizing: border-box;
  }
}
```
 . So it only targets the `header` element itself not the children

 However,  `a` tag preserves the space and gets converted to `#header a{...}` which is expected. Whats the difference between pseudo elements and html tags in this phase. Why does it behave differently?

**Comment by mxstbr** [comment]
You want to use the asterisk `*` to target all children on the `::after`:

```JS
const Header = styled.header`
 *::after {
   box-sizing: border-box;
 }

 a {
   font-size: 1em;
 }
`
```

Hope that helps!
