### ISSUE TITLE
Styled-component@4.1.3 does not forward attributes to th(td) DOM

### ISSUE THREAD

**Issue by jim-king-2000** [styled-components/styled-components#2292]
## Reproduction

Here is the code of repro: "https://github.com/jim-king-2000/nextbugrepro".

## Steps to reproduce

1. Clone the code above.
2. npm I && npm run dev
3. Access "localhost:3000".
4. See that there is no rowspan and colspan in the top-left cell.

## Expected Behavior

I set rowspan=2 and colspan=2 in the top-left cell. But it is gone when using styled-components@4.1.3.

    const StyledTh = styled.th`
      border: 1px solid;
      text-align:center;
      padding: 5px;
    `;
    <StyledTable>
    <StyledTr>
      <StyledTh rowspan='2' colspan='2'></StyledTh>
      ...

It recovers if I change StyledTh to th. And the same issue applies to td. It only occurs in version 4.1.3. V4.1.2 is OK.

## Actual Behavior

The rendered DOM does not contain "rowspan=2" or "colspan=2".

**Comment by probablyup** [comment]
Should be `rowSpan` and `colSpan` (note the camelCasing). https://reactjs.org/docs/dom-elements.html#all-supported-html-attributes

**Comment by jim-king-2000** [comment]
You are right. Close the bug. Different behavior between v4.1.2 and v4.1.3.
