### ISSUE TITLE
Strange behaviour for the css prop

### ISSUE THREAD

**Issue by harmeetjaipur** [styled-components/styled-components#2293]
I am trying to use the css prop but it won't work unless I pull it out of the macro folder.

[Sandbox](https://codesandbox.io/s/xvo6mzvznq)
 

Button component: 

` <Button css={primaryButton} type="primary">
          Transfer Hub
        </Button>`

Button style:

`const primaryButton = css({
  "&.ant-btn": {
    backgroundColor: colors.highlight,
    border: 0
  }});`

What I mean by macro is, that if I use `import { css } from 'styled-components/macro'` inside the class component only the `primaryButton` style works as it should. But the html is as follows for the `button`: 

## Expected Behavior

I want the following class `ant-btn sc-ifAKCX cmUQLD ant-btn-primary` to work as it is right now without the `_css2` is also being added to the button. What might be the reason for that to happen and also, can I do this without using macro? So, the output should be:

``<button type="button" class="ant-btn sc-ifAKCX cmUQLD ant-btn-primary"><span>Transfer Hub</span></button>``

The css prop doesn't work altogether in the Sandbox for some reason but here is a gif if it helps. The button is supposed to be green and not blue:

<a href="https://ibb.co/RHZK4hV" target="_blank"><img src="https://i.ibb.co/C0NysJT/button.gif" alt="button" border="0"></a>

## Actual Behavior

`<button _css2="&amp;.ant-btn {
  background-color: #0cccad; border: 0;
}" type="button" class="ant-btn sc-ifAKCX cmUQLD ant-btn-primary"><span>Transfer Hub</span></button>`

## .babelrc

`{
  "plugins": [
    [
      "styled-components",
    ]
  ]
}`

## System:
 - OS: Linux 4.15 Linux Mint 19 (Tara)
 - CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
 - Memory: 897.12 MB / 15.15 GB
 - Container: Yes
 - Shell: 4.4.19 - /bin/bash
## Binaries:
 - Node: 10.9.0 - ~/.nvm/versions/node/v10.9.0/bin/node
 - Yarn: 1.10.1 - ~/.yarn/bin/yarn
 - npm: 6.4.1 - ~/.nvm/versions/node/v10.9.0/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.10.0 => 1.10.0
 - styled-components: ^4.1.3 => 4.1.3

**Comment by mxstbr** [comment]
The codesandbox thing sounds like an issue with how codesandbox handles Babel macros (cc @CompuIves).

Your first issue is a bit hard to understand because the output HTML is missing, can you post that again?

**Comment by harmeetjaipur** [comment]
HTML for the button: 

`<button _css2="&amp;.ant-btn { background-color: #0cccad; border: 0; }" type="button" class="ant-btn sc-ifAKCX cmUQLD ant-btn-primary"><span>Transfer Hub</span></button>`

**Comment by CompuIves** [comment]
Yes, this is an issue with CodeSandbox. The babel compiler didn't know how to handle package.json redirects.

I committed a fix, it should be live within 15 min!

**Comment by mxstbr** [comment]
@CompuIves you're a hero :100:

----

@harmeetjaipur it looks like your `Button` is passing through all props to the DOM, which is causing the internal `_css2` prop to be attached as an attribute.

This is how the Babel transform edits your code to make the `css` prop work:

```JS
<Button css={primaryButton} type="primary"> Transfer Hub </Button>

// gets turned into
const _StyledButton = styled(Button)`
  ${props => props._css2}; // this name uniquely generated, it might be _css1, _css2, _css3, etc.
`;

<_StyledButton type="primary" _css2={primaryButton}>Transfer Hub</_StyledButton>
```

So you need to make sure that your `Button` component only attaches valid DOM props, then everything will work as expected!
