### ISSUE TITLE
Styling styled components with new props is not compatible with typescript

### ISSUE THREAD

**Issue by Nizarius** [styled-components/styled-components#2294]
This case is in the official documentation: https://www.styled-components.com/docs/api#typescript, but not works as expected.

## System:
 - OS: macOS High Sierra 10.13.6
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 415.51 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 10.12.0 - /usr/local/bin/node
 - Yarn: 1.12.3 - /usr/local/bin/yarn
 - npm: 6.4.1 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - @types/styled-components: ^4.0.1 => 4.0.1
 - babel-plugin-styled-components: ^1.8.0 => 1.8.0
 - styled-components: ^4.0.2 => 4.0.2
 - typescript: ^3.1.3 => 3.1.3

## Reproduction

```
import baseStyled, { ThemedBaseStyledInterface } from 'styled-components';

const theme = {
  colors: {
    black: '#000',
    brownGrey: '#9b9b9b',
    grey: '#b9b9b9',
    white: '#fff',
  },
};

export type Theme = typeof theme;
export const styled = baseStyled as ThemedBaseStyledInterface<Theme>;

const Header = styled('h1')<{ isActive: boolean }>`
  color: ${props =>
    props.isActive ? props.theme.colors.black : props.theme.colors.brownGrey};
`;

const Title = styled<{ isGrey: boolean; isActive: boolean }>(Header)`
  color: ${props =>
    props.isGrey ? props.theme.colors.grey : props.theme.colors.white};
`;
```

## Expected Behavior
No error with typing.

## Actual Behavior
Showing error:
`Property 'isGrey' is missing in type 'ValidationMap<ThemedOuterStyledProps<ClassAttributes<HTMLHeadingElement> & HTMLAttributes<HTMLHeadingElement> & { isActive: boolean; }, { breakpoints: { mobile: number; desktop: number; 768: number; 1024: number; }; colors: { ...; }; fonts: { ...; }; sizes: { ...; }; layout: { ...; }; }>>' but required in type 'ValidationMap<{ isGrey: boolean; isActive: boolean; }>'.
`

**Comment by mxstbr** [comment]
Please submit your issue at DefinitelyTyped: https://github.com/definitelytyped/definitelytyped

**Comment by champagne-randy** [comment]
FYI @Nizarius downgrading styled-components and @types/styled-components to v4.0.3 solved this issue for me. [It's a workaround](https://stackoverflow.com/a/53902817) but might get you unblocked
