### ISSUE TITLE
Proposal: Explicit css prop API

### ISSUE THREAD

**Issue by dsblv** [styled-components/styled-components#2297]
Recent updates to `styled-components` introduced a long awaited feature — css prop:

```js
import 'styled-components/macro';
const BlueButton = (props) =>
  <button css="color: blue; padding: 1em;" {...props} />
```

**This proposal aims to augment this API the way that makes it explicit and
compatible with non-babel-macros aware build pipelines.** This is achieved by scoping babel transformation to specific components instead of every host react-dom element. We'll refer to them as _capital S Styled components_.

## Example

```js
import { Styled } from 'styled-components/macro';

const BlueButton = (props) =>
  <Styled.button css="color: blue; padding: 1em;" {...props} />
```

## Motivation

Although existing API appears very intuitive, I believe it has its drawbacks:

- It's not obvious for readers (and type systems) that `css` prop is special and handled by the build pipeline
- `babel-plugin-macros` is required which makes product code less portable
- It's easy to assume `styled-components` interchangeable with other libraries with similar API, but that's not the case

## Details

Similar to primary template literal API, we expose a set of components matching popular DOM elements such as `div`, `span`, `h1` etc. This lets us restrict the transformation specifically to these components, and also provide runtime fallback for cases when transformation doesn't happen.

In environments supporting babel-plugin-macros`, components are compiled to regular styled-components, the same way it happens now:

```js
/* before */
import { Styled } from 'styled-components/macro';
<Styled.h1 css="color: papayawhip">Hello css prop</Styled.h1>

/* after */
import styled from 'styled-components';
let H1 = styled.h1`
  color: papayawhip;
`;
<H1>Hello css prop</H1>
```

Otherwise, 'styled-components/macro' points to a special build where every _capital S Styled component_ is an actual React component that processes css prop at runtime. This turns `babel-macro` from hard dependency into opt-in optimisation!

### Is this a breaking change?

It doesn't conflict with existing API. Although the idea is to eventually replace it, initial release may support both approaches, with documentation favouring the explicit one. It is possible to provide a codemod, but considering how recent the new API is, manual migration seems acceptable too:

```diff
- <h1
+ <Styled.h1
    css="color: papayawhip"
  >
    Hello css prop
- </h1>
+ </Styled.h1>
```

## Drawbacks

- Slower API effectively becomes default.
- Product code may turn out verbose, which for some people defeats the purpose of even introducing new APIs.
- The size of s-c API surface _doubles_.
- Possible confusion among users who already adopted the new approach.
- Capital S is not distinctive enough.

## Alternatives

An alternative to introducing new APIs might be a separate, macro-only package that uses as much s-c internals as possible, allowing them to work side-by-side in existing codebases.

## Unresolved questions

- Can this cover all the use-cases of current API?
- Does `babel-plugin-macros` provide any way to fall back to runtime versions? Seems doable, but not mentioned in the docs.

**Comment by satya164** [comment]
How will this work with non-primitive components?

**Comment by dsblv** [comment]
Good point, for some reason I assumed css prop only applied to primitives 🤔 Very impressive!

One way I can think of is `as` prop, which already exists on styled components:

```js
<Styled.button as={CustomButton} css="..."></Styled.button>
```

Verbosity aside, this has a problem: what if `CustomButton` expects a prop named `css`? I'm curious how current implementation solves it?

**Comment by probablyup** [comment]
This would add too much confusion/complication to the library and its usage, we're unlikely to adopt such a strategy.
