### ISSUE TITLE
Mounting a a styled component results in an unstyled component

### ISSUE THREAD

**Issue by reduxdj** [styled-components/styled-components#2299]
styled-components": "^4.0.3"

## System:
 - OS: macOS 10.14
 - CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
 - Memory: 979.11 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 8.5.0 - /usr/local/bin/node
 - Yarn: 1.10.1 - /usr/local/bin/yarn
 - npm: 5.3.0 - /usr/local/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.10.0 => 1.10.0
 - styled-components: ^4.0.3 => 4.0.3

## Reproduction
```
import React from 'react'
import ReactDOM from 'react-dom'
import styled from 'styled-components'


/* eslint-disable */
class ToolTipView extends React.Component {
  render() {
    return (<div id='tooltip-view' ></div>)
  }
}


const StyledToolTip = styled(ToolTipView)`
  background: #000;
  position:fixed;
  width: 100px;
  height: 30px;
`

class ToolTip {
  static toolTip
  static delay = 2000
  static show(e, ...props) {
    ReactDOM.render(
      <StyledToolTip event={e} {...props} />, document.body.appendChild(document.createElement('div'))
    )
  }
}
export default ToolTip
```

## Steps to reproduce
call the function ToolTip.show on a click event like onClick={ToolTip.show}

## Expected Behavior
Expected to mount a styled component

## Actual Behavior
The component is unstyled the work around is to style the component and mount inside
a wrapper div

**Comment by mxstbr** [comment]
You need to attach the passed in className, see this docs section: https://www.styled-components.com/docs/basics#styling-any-components

```JS
class ToolTipView extends React.Component {
  render() {
    return (<div className={this.props.className} id='tooltip-view' ></div>)
  }
}
```
