### ISSUE TITLE
React-Native (1.1.0) - es2015 preset seems to be now a requirement? (see screenshot)

### ISSUE THREAD

**Issue by sync** [styled-components/styled-components#230]
## Version
1.1.0 (React Native 0.37.0) - yarn 0.17.6

## Steps to reproduce
Add styled-components to a bare bone react-native project, without es2015 as a dev dependency

## Expected Behavior
The app to render content and no error

## Actual Behavior
<img width="487" alt="screen shot 2016-11-21 at 11 27 28 pm" src="https://cloud.githubusercontent.com/assets/21725/20482811/cb55860a-b042-11e6-88d8-fea05afa5ef1.png">

**Comment by mxstbr** [comment]
That's weird, seems like an issue with `css-to-react-native`? cc @jacobp100

**Comment by jacobp100** [comment]
I think it’s because `npm run prepublish` tries to build `css-to-react-native`, but if I remove that, it’ll remove the guarantee that the project is correctly built before publishing. Do you know how to solve this?

**Comment by mxstbr** [comment]
Huh that's weird, let's remove that for now in favor of adding a release script?

**Comment by jacobp100** [comment]
Would you be able to set this up—or tell me what to do? I can’t quite see what’s different in the setup between `css-to-react-native` and `styled-components`.

**Comment by brunolemos** [comment]
The `.babelrc` file is causing this issue.

Workaround: remove the file `.babelrc` from `./node_modules/css-to-react-native/`
Fix: Add `.babelrc` to `.npmignore` or remove it. Pull request: [css-to-react-native#10](https://github.com/styled-components/css-to-react-native/pull/10).

**Comment by mxstbr** [comment]
Thank you @brunolemos, released as `css-to-react-native@1.0.4`! If you're having this issue, run `npm install` again and you should be good to go. Sorry for the troubles!
