### ISSUE TITLE
What is css and when should we use it

### ISSUE THREAD

**Issue by kopax** [styled-components/styled-components#2302]
I see a lot of code example showing: 

```jsx
<div css="overflow:hidden" />
```

and some other: 

```jsx
<div css={css`overflow:hidden`} />
```

But there is one difference, whenever I use `css` (`import { css } from 'styled-components`), my IDE IntellIJ is able to colorize the css into css.

I know that css cannot read props from the component it self it render, for this you need `styled()`, is that accurate affirmation ?

Regarding the colorization with the `css` utils, is this just my IDE bluffing me? 

- When is the css props required, when it is not?
- Bonus question, does the `css` props MUST be used with component wrapper with `withTheme` ?

**Comment by imbhargav5** [comment]
Perhaps this will help. https://www.styled-components.com/docs/tooling#babel-macro https://www.styled-components.com/docs/api#css-prop https://www.styled-components.com/docs/api#css

**Comment by probablyup** [comment]
> Regarding the colorization with the css utils, is this just my IDE bluffing me?

Yes. There's probably some recoloring rule based on the tagged template literal in the language file.

> When is the css props required, when it is not?

It's never required, but if you use it in conjunction with our babel plugin it allows you to make use of s-c without having to manually make components.

> Bonus question, does the css props MUST be used with component wrapper with withTheme ?

Nope
