### ISSUE TITLE
Improve TypeScript support for media templates

### ISSUE THREAD

**Issue by kripod** [styled-components/styled-components#2303]
Typing [media templates](https://www.styled-components.com/docs/advanced/#media-templates) can be cumbersome. I've spent a fair amount of time to figure out the following type declarations and casts compliant with TypeScript's strict mode:

```ts
import { ThemedCssFunction } from 'styled-components';
import { css } from './styled-components';
import ThemeInterface from './theme';

const sizes = {
  small: 600,
  medium: 1024,
  large: 1440,
  xlarge: 1920,
};

// Iterate through the sizes and create a media template
export const media = (Object.keys(sizes) as (keyof typeof sizes)[]).reduce(
  (acc, label) => {
    acc[label] = (first: any, ...interpolations: any[]) => css`
      @media (min-width: ${sizes[label]}px) {
        ${css(first, ...interpolations)}
      }
    `;

    return acc;
  },
  {} as { [key in keyof typeof sizes]: ThemedCssFunction<ThemeInterface> },
);
```

One of the possible solutions is writing docs including the aforementioned code snippet. An other way to get around the issue and lower the amount of boilerplate code required even for vanilla JS projects is to create a method which encapsulates the functionality above:

```ts
import { mediaTemplates } from 'styled-components';

const media = mediaTemplates({
  small: 600,
  medium: 1024,
  large: 1440,
  xlarge: 1920,
});
```

**Comment by kachkaev** [comment]
@kripod does the trick still work for you? After upgrading from `@types/styled-components@4.1.0` to `4.1.1...4.1.8` component props seem to no longer work inside media queries. Investigating.

**Comment by CoenWarmer** [comment]
I also noticed this @kachkaev. 

Styled Components version 4.1.2, using Typescript 3.1.1.

In the following component:

```
const Foo = styled.div`
  ${media.md`
    flex-shrink: 0;
    flex-basis: ${(props: CellProps) =>
      props.width ? `${props.width}px` : 'auto'};
    flex-grow: ${(props: CellProps) => props.grow};
  `};
```

with the mediaquery function noted in the docs at (https://www.styled-components.com/docs/advanced#media-templates)[https://www.styled-components.com/docs/advanced#media-templates],

I am noticing that only `flex-basis` is being applied. `flex-grow` does not appear on the component. It seems all props in the mediaquery function are applied, until the first dynamic prop. All other props after that (dynamic or otherwise) are not being set.

**Comment by fabb** [comment]
Imho writing media templates as template functions is not a good idea, because linting, syntax highlighting and auto completion won‘t work with its content css.

It is way eqsier and imho better to just create strings with the `@media` definitions:

```
const phone = „@media (max-width: 480px)“

const MyComponent = styled.div`
    background: palevioletred;
    ${phone} {
        background: dodgerblue;
    }
`
```

The media definitions could also read from the theme, this would work similarly.

**Comment by probablyup** [comment]
If there's anything else to be done here, feel free to open an issue over at DefinitelyTyped.

**Comment by kachkaev** [comment]
Many thanks for your suggestion @fabb! I refactored my media templates as you suggest and all typescript issues were gone, plus I got better autoformatting by Prettier in a couple of places 🎉

Wondering if [docs](https://www.styled-components.com/docs/advanced/#media-templates) could be to change to this:

```ts
const customMediaQuery = (maxWidth: number) =>
  `@media (max-width: ${maxWidth}px)`;

const media = {
  custom: customMediaQuery,
  desktop: customMediaQuery(922),
  tablet: customMediaQuery(768),
  phone: customMediaQuery(576)
};

const Content = styled.div`
  height: 3em;
  width: 3em;
  background: papayawhip;

  /* Now we have our methods on media and can use them instead of raw queries */
  ${media.desktop} {
    background: dodgerblue;
  }
  ${media.tablet} {
    background: mediumseagreen;
  }
  ${media.phone} {
    background: palevioletred;
  }
`;

render(<Content />);
```

* Looks much simpler and easier to read
* 100% understood by Prettier
* Perfectly works in TS with no added magic
* Is probably a bit faster because additional calls to `` css`...` `` are removed 🎉

@probablyup do you think this would make sense? I can submit a PR if that's potentially interesting.

**Comment by fabb** [comment]
Cheers!

**Comment by nayaabkhan** [comment]
@fabb @kachkaev This syntax is so simpler. Thank you! I've started to migrate to this syntax and the code feels much more readable and prettier has a good time formatting it.

That being said, be careful when coupling this with conditionals.

```jsx
// The old way looks and works as expected.
const ComponentWithConditional = div`
  ${props => props.isResponsive && media.medium`
    display: block
  `}
`
```

```jsx
// The new way looks correct but isn't.
// We are only interpolating the string literal.
// So when `!isResponsive` we get an "orphan" `display: block` which we didn't expect.
const ComponentWithConditional = div`
  ${props => props.isResponsive && media.medium} {
    display: block
  }
`

// The correct way. We don't get autocompletion with this but it is an acceptable
// trade-off if you don't have many conditions coupled with your breakpoints.
const ComponentWithConditional = div`
  ${props => props.isResponsive && `${media.medium} { display: block }`} 
`
```

After the fact, it seems like a silly mistake to make, but it took me a while to see it. I hope it will save someone from the frustration.

**Comment by fabb** [comment]
@nayaabkhan I usually do it like this:
```
const ComponentWithConditional = div`
  ${media.medium} {
    display: ${p => p.isResponsive ? "block" : "inherit"};
  } 
`
```

Of course this can become convoluted when defining several css properties.

**Comment by h1u2i3** [comment]
```typescript
import { css, CSSObject, SimpleInterpolation, FlattenSimpleInterpolation } from 'styled-components'

type Breakpoints = {
  xs: number
  sm: number
  md: number
  lg: number
  xl: number
  xxl: number
}

const sizes: Breakpoints = {
  xs: 480,
  sm: 576,
  md: 768,
  lg: 992,
  xl: 1200,
  xxl: 1600,
}

const initAcc: Interpolation<Breakpoints> = {
  xs: () => '',
  sm: () => '',
  md: () => '',
  lg: () => '',
  xl: () => '',
  xxl: () => '',
}

type BreakpointEntry = [keyof Breakpoints, Breakpoints[keyof Breakpoints]]
type Interpolation<T> = {
  [key in keyof T]:
    | ((
        first: CSSObject | TemplateStringsArray,
        ...interpolations: SimpleInterpolation[]
      ) => FlattenSimpleInterpolation)
    | (() => string)
}

interface CustomObject extends ObjectConstructor {
  entries<K extends keyof Breakpoints, T>(o: { [s in K]: T } | ArrayLike<T>): [K, T][]
}

const object: CustomObject = Object

export const media = object.entries(sizes).reduce<Interpolation<Breakpoints>>((acc, cur: BreakpointEntry) => {
  const [key, value] = cur
  acc[key] = (first, ...interpolations) =>
    css`
      @media (max-width: ${value}px) {
        ${css(first, ...interpolations)}
      }
    `

  return acc
}, initAcc)
```

**Comment by TravisBumgarner** [comment]
@kachkaev  Thanks so much!

**Comment by hdsantos89** [comment]
> ```ts
> import { css, CSSObject, SimpleInterpolation, FlattenSimpleInterpolation } from 'styled-components'
> 
> type Breakpoints = {
>   xs: number
>   sm: number
>   md: number
>   lg: number
>   xl: number
>   xxl: number
> }
> 
> const sizes: Breakpoints = {
>   xs: 480,
>   sm: 576,
>   md: 768,
>   lg: 992,
>   xl: 1200,
>   xxl: 1600,
> }
> 
> const initAcc: Interpolation<Breakpoints> = {
>   xs: () => '',
>   sm: () => '',
>   md: () => '',
>   lg: () => '',
>   xl: () => '',
>   xxl: () => '',
> }
> 
> type BreakpointEntry = [keyof Breakpoints, Breakpoints[keyof Breakpoints]]
> type Interpolation<T> = {
>   [key in keyof T]:
>     | ((
>         first: CSSObject | TemplateStringsArray,
>         ...interpolations: SimpleInterpolation[]
>       ) => FlattenSimpleInterpolation)
>     | (() => string)
> }
> 
> interface CustomObject extends ObjectConstructor {
>   entries<K extends keyof Breakpoints, T>(o: { [s in K]: T } | ArrayLike<T>): [K, T][]
> }
> 
> const object: CustomObject = Object
> 
> export const media = object.entries(sizes).reduce<Interpolation<Breakpoints>>((acc, cur: BreakpointEntry) => {
>   const [key, value] = cur
>   acc[key] = (first, ...interpolations) =>
>     css`
>       @media (max-width: ${value}px) {
>         ${css(first, ...interpolations)}
>       }
>     `
> 
>   return acc
> }, initAcc)
> ```

For some reason your implementation doesn't seem to work for me.

```jsx
const ResponsiveBox = styled.div`
  color: white;
  height: 100px;
  width: 500px;
  ${media.lg} {
    width: 300px;
    background-color: green;
  }
  ${media.md} {
    width: 200px;
    background-color: red;
  }
  ${media.sm} {
    width: 400px;
    background-color: blue;
  }
`;
```
