### ISSUE TITLE
babel-plugin-macros in dependencies field

### ISSUE THREAD

**Issue by monkindey** [styled-components/styled-components#2304]
I want to use `styled-components/macro`, I install the styled-components and it throw the Not Found `babel-plugin-macros` error. So I think can we put babel-plugin-macros in dependencies field?

**Comment by monkindey** [comment]
Thanks, the `babel-plugin-macro` now [is in `devDependencies` field](https://github.com/styled-components/styled-components/blob/master/package.json#L87). When I npm install `style-components`, the `babel-plugin-macro` will not install. But I use `style-components/macro` which [import `babel-plugin-macro`](https://github.com/styled-components/styled-components/blob/master/src/macro/index.js#L2) and it will throw the error.

**Comment by probablyup** [comment]
Macro support should be set up at the project-level, so that's why we don't provide it ourselves. For instance, CRA2 handles macro support on behalf of your project.
