### ISSUE TITLE
Cannot read property 'div' of undefined

### ISSUE THREAD

**Issue by kettanaito** [styled-components/styled-components#2309]
## System:
 - OS: macOS High Sierra 10.13.6
 - CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
 - Memory: 428.57 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 8.11.4 - /usr/local/bin/node
 - Yarn: 1.12.3 - /usr/local/bin/yarn
 - npm: 6.5.0 - ~/.npm-global/bin/npm
## npmPackages:
 - styled-components: ^4.1.3 => 4.1.3

## Reproduction

This issue occurred once I have updated project dependencies:

```diff
-    "babel-eslint": "^8.2.6",
-    "babel-loader": "^7.1.5",
+    "babel-eslint": "^10.0.1",
+    "babel-loader": "^8.0.4",
-    "flow-bin": "^0.86.0",
+    "flow-bin": "^0.89.0",
-    "lint-staged": "^7.3.0",
+    "lint-staged": "^8.1.0",
-    "styled-components": "^4.1.1",
+    "styled-components": "^4.1.3",
```

## Steps to reproduce

```bash
git clone https://github.com/kettanaito/atomic-layout
cd atomic-layout
git checkout dependencies
npm install
npm run storybook
```

> You can see all the config files (babel, webpack, etc.) on the [mentioned branch](https://github.com/kettanaito/atomic-layout/tree/dependencies).

See the following exception thrown by Storybook.

```
Cannot read property 'div' of undefined
    TypeError: Cannot read property 'div' of undefined
    at Module.srcComponentsBoxJsx (http://localhost:6020/main.4a3566b995dd1c2ae279.bundle.js:2172:76)
    at __webpack_require__ (http://localhost:6020/main.4a3566b995dd1c2ae279.bundle.js:199:27)
    at Module.srcIndexJs (http://localhost:6020/main.4a3566b995dd1c2ae279.bundle.js:2815:60)
    at __webpack_require__ (http://localhost:6020/main.4a3566b995dd1c2ae279.bundle.js:199:27)
    at http://localhost:6020/main.4a3566b995dd1c2ae279.bundle.js:393:14
    at http://localhost:6020/main.4a3566b995dd1c2ae279.bundle.js:395:6
    at webpackUniversalModuleDefinition (http://localhost:6020/main.4a3566b995dd1c2ae279.bundle.js:143:898)
    at Module.<anonymous> (http://localhost:6020/main.4a3566b995dd1c2ae279.bundle.js:144:3)
    at Module../index.js (http://localhost:6020/main.4a3566b995dd1c2ae279.bundle.js:5381:30)
    at __webpack_require__ (http://localhost:6020/runtime~main.4a3566b995dd1c2ae279.bundle.js:782:30)
```

The following outputs `undefined` in the console:

```js
import styled from 'styled-components'

console.log(styled)
```

**I do acknowledge that this is most likely not an issue with the `styled-components` package.** However, I would be very thankful for help, as I couldn't find any relevant issues anywhere else.

## Expected Behavior

- `styled` can be imported as a default export of `styled-components` package

## Actual Behavior

- `import styled from 'styled-components'` resolves `styled` to `undefined`

**Comment by probablyup** [comment]
If I had to guess, it's some sort of module re-exporting bug from having multiple versions of s-c in the tree. Have you tried the yarn "resolutions" field to dedupe? https://yarnpkg.com/lang/en/docs/selective-version-resolutions/

**Comment by kettanaito** [comment]
## Update

I have found the problematic package. Consider the next code:

```js
import styled from 'styled-component'
```

Using `babel-loader@8.0.5` results into `styled` being `undefined`.
Using `babel-loader@7.1.5` imports `styled` namespace properly.

The very same configs and settings are used, only the `babel-loader` version changes.

**Comment by altany** [comment]
I am facing the same issue as @kettanaito.

If I do `const Element = styled.View`  I get this error:
![image](https://user-images.githubusercontent.com/5974044/65133587-87d6af80-da0b-11e9-95ce-f1b4edbb0fdb.png)

It seems I need to change all my  declarations to
```javascript
import { View } from 'react-native
const Element = styled(View)
```
to make it work but I really don't want to do that, or downgrade my `babel-loader`.

Any ideas on how to fix this?

**Comment by trustyknave** [comment]
@altany curious if you ended up finding a solution to this issue. Started experiencing this today, and have found that it renders local development pretty much impossible.

**Comment by altany** [comment]
> @altany curious if you ended up finding a solution to this issue. Started experiencing it today, and have found that it renders local development pretty much impossible.

I have given up on it for now unfortunately.

**Comment by mzalazar** [comment]
I was having  the same error... i get rid of the selected code (in webpack.config.js):

![Screenshot at 2020-04-19 07-43-23](https://user-images.githubusercontent.com/942079/79685760-93908b80-8211-11ea-83ec-94d36b06fe9a.png)

and it worked for me =)

**Comment by mzalazar** [comment]
Oh by the way... i'm using this .babelrc:

![Screenshot at 2020-04-19 07-45-28](https://user-images.githubusercontent.com/942079/79685796-cd619200-8211-11ea-901c-7be28e5e2d7e.png)

**Comment by cseas** [comment]
Did anyone figure out a fix for this? I'm getting the same error when trying to use `styled.div`. The above solution did not work for me.

**Comment by vinamelody** [comment]
Hi, I'm getting this error when trying to override a style too

```javascript
// ErrorAlert.js

import { Modal, Icon, Typography, Button } from 'frozen/components'

// trying to override the PrimaryButton style
const ActionButton = styled(Button.PrimaryButton)`
  width: 100%;
`

```

Is there anything that I should remove? I don't have any mention of styled components in my webpack.

Here's my `.babelrc`

```
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "node": "current"
        },
        "useBuiltIns": "usage",
        "corejs": {
          "version": 3,
          "proposals": true
        }
      }
    ],
    "@babel/preset-react"
  ],
  "plugins": [
    "babel-plugin-styled-components",
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-proposal-object-rest-spread",
    "@babel/plugin-proposal-export-default-from",
    "@babel/plugin-proposal-export-namespace-from",
    [
      "@babel/plugin-proposal-class-properties",
      {
        "spec": true
      }
    ],
    "react-hot-loader/babel"
  ]
}

```

**Comment by kitten** [comment]
@vinamelody as you're saying you're using Webpack to bundle and I'm seeing a reference to Node in your configuration. I don't know if you're accidentally transpiling all modules with Babel and are converting them to CommonJS but try setting `modules: false` in your `@babel/preset-env` config

**Comment by vinamelody** [comment]
Hi @kitten tried that but for some reason it's still getting error.
Created this codesanbox but it works there https://codesandbox.io/s/sharp-shaw-nsfmf?file=/src/components/ErrorAlert.js

For now, i'd do a little hack by declaring the button that I want in my Button.js file and use it in the other component.

```javascript
// Button.js
import styled from 'styled-components'
import { Base } from './components'

const PrimaryButton = styled.button`
  min-width: 10em;
  height: 2.75em;
  color: ${props => props.theme.colors.salt};
  background: ${props => props.theme.colors.mint};
  border-radius: 0.3125em;
  border: 1px solid transparent;
  padding: 0.625em 1em;

  &:hover {
    color: ${props => props.theme.colors.salt};
    background: ${props => props.theme.colors.darkmint};
  }
  &[disabled] {
    color: ${props => props.theme.colors.grey400};
    background: ${props => props.theme.colors.grey200};
  }

  ${Base.MediaQuery[0]} {
    min-width: 7em;
  }
`
const SecondaryButton = styled.button`
  min-width: 10em;
  height: 2.75em;
  color: ${props => props.theme.colors.mint};
  background: ${props => props.theme.colors.salt};
  border: 1px solid;
  border-color: ${props => props.theme.colors.mint};
  border-radius: 0.3125em;

  ${Base.MediaQuery[0]} {
    min-width: 7em;
  }
`

const FullWidthButton = styled(PrimaryButton)` ---> this styled() works if I put it here
  width: 100%;
`

export default {
  PrimaryButton,
  SecondaryButton,
  FullWidthButton
}

```

then in my component:

```javascript
import React from 'react'
import styled from 'styled-components'
import iconFail from './assets/icon-fail.svg'
import { Modal, Icon, Typography, Button } from './components'

const ModalButtonWrapper = styled.div`
  width: 100%;
`

const IconImage = styled.img`
  max-height: 16em;
`
const CustomButton = styled(Button.PrimaryButton)` ----> this will throw Uncaught TypeError: Cannot read property 'PrimaryButton' of undefined
  width: 100%;
`

function ErrorAlert (props) {
  const { show, title, buttonText, handleClose } = props
  return (
    <Modal show={show}>
      <IconImage src={iconFail} />
      <Typography.PageTitle>{title}</Typography.PageTitle>
      <ModalButtonWrapper>
        <Button.FullWidthButton onClick={handleClose}>
          {buttonText}
        </Button.FullWidthButton>
      </ModalButtonWrapper>
    </Modal>
  )
}

export default ErrorAlert

```

**Comment by kitten** [comment]
@vinamelody You have a circular import in that file where `Base` is imported in `Button`'s file but both of them are imported and exported in that `components/index` file. If you reference `Base`'a file directly in `Button`do file it'll work.

I'll also have to ask you to please ask usage questions (particularly since this is Webpack related) on other platforms like StackOverflow or Spectrum :)
