### ISSUE TITLE
Investigate grouping media queries together

### ISSUE THREAD

**Issue by kripod** [styled-components/styled-components#2310]
The size of generated bundles can be reduced by [grouping media queries together](https://stackoverflow.com/questions/11626174/is-there-an-advantage-in-grouping-css-media-queries-together). For example, the following snippet:

```js
const Box = styled.div`
  :hover {
    @media (min-width: 600px) {
      color: red;
    }
  }

  :first {
    @media (min-width: 600px) {
      color: blue;
    }
  }
`;
```

Could be transformed into the following code during build (possibly by Babel):

```js
const Box = styled.div`
  @media (min-width: 600px) {
    :hover {
      color: red;
    }

    :first {
      color: blue;
    }
  }
`;
```

**Comment by probablyup** [comment]
Good idea. At the moment https://github.com/thysultan/stylis.js is what we use to handle preprocessing the CSS, maybe bring it up over there?

**Comment by kripod** [comment]
@probablyup Thank you for the suggestion, I've just opened an issue over there.
