### ISSUE TITLE
What's the status of styled-components/primitives ?

### ISSUE THREAD

**Issue by dispix** [styled-components/styled-components#2313]
Is there still a goal toward universal styled-components ? I noticed the whole subject is stalling a little (less activity in react-native-web, react-primitives, etc.) and that styled-components itself relies on some of these.

**Comment by mxstbr** [comment]
react-native-web is still actively developed, but I don't think react-primitives is anymore unfortunately :cry: Somebody would need to pick up react-primitives to make /primitives better
