### ISSUE TITLE
Odd/Even child selector unexpected behavior

### ISSUE THREAD

**Issue by Moshyfawn** [styled-components/styled-components#2314]
_Hi! It's my first issue ever. Feel free to correct me in anything issue creation related. Sorry for possible inconvenience._

I'm trying to access every odd child within my **Text** component. My code below doesn't provide me with the expected result. It applies styles to every child element.

There's my styled component **Text** with three _children_:
```
<Text>
  <span>There're</span>
  <span>three</span>
  <span>words</span>
</Text>
```
There're my styles:
```
const Text = styled.div`
  color: #374a67;
  &:nth-child(2n+1) {
    color: red;
  }
`;
```

**Comment by lukyth** [comment]
`&` will be `Text`'s class name. That means `&:nth-child(2n+1)` will apply to every `Text` which is an odd child.

I think what you need is `> :nth-child(2n+1)` (every direct odd child of `Text`).

**Comment by Moshyfawn** [comment]
Yes, you're right. Didn't get to me fully how `&` must be used for child elements. Thank you!

**Comment by ivkremer** [comment]
I understand it's an old post but I wouldn't do it like that though.
I would do it in the following way:

```html
{/* Component: */}
<Text>
  <Item>There're</Item>
  <Item>three</Item>
  <Item>words</Item>
</Text>
```

```JavaScript
// styled:
const Item = styled.span`
  color: #374a67;

  &:nth-child(2n+1) {
    color: red;
  }
`;
```

I believe it's much more atomic and precise, and hence maintainable.
