### ISSUE TITLE
Feature request: Export proxy object to reduce code

### ISSUE THREAD

**Issue by juraj98** [styled-components/styled-components#2315]
I've been using `styled-components` for a while now, and the one thing that always bugs me is that every time I want to use `props`, I need to write `props => props`. This is even more apparent when using themes with `props => props.theme`.

---

It would be much easier if we could write something like
```
const button = styled.div`
  padding-left: ${prop.leftPadding};
  color: ${theme.button.primary}
`;
```
instead of
```
const button = styled.div`
  padding-left: ${props => props.leftPadding};
  color: ${props => props.theme.button.primary}
`;
``` 

----

This could be achieved by using proxy objects([MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy)):

```
const propHandler = {
  get: (object, property) => {
    const proxyFunction = props => props;
    proxyFunction.path = object.path ? `${object.path}.${property}` : property;
    return new Proxy(proxyFunction, propHandler);
  },
};
export const prop = new Proxy({}, propHandler);

const themeHandler = {
  get: (object, property) => {
    const proxyFunction = props => props.theme;
    proxyFunction.path = object.path ? `${object.path}.${property}` : property;
    return new Proxy(proxyFunction, themeHandler);
  },
};
export const theme = new Proxy({}, themeHandler);
```
 
These objects could then be imported together with `styled` object
```
import styled, { prop, theme } from styled;
```

---

One thing I wasn't able to figure out is to apply this solution to conditions such as

```
const Button = styled.div`
  background-color: ${props => props.hasError ? props.theme.red : props.theme.green};
`
```

**Comment by probablyup** [comment]
Proxies aren’t supported by IE and we support what React supports

**Comment by juraj98** [comment]
I didn't think of using babel macro. I'll try to solve my issue that way. Thanks!

**Comment by mxstbr** [comment]
I don't this introducing this much magic is worth it, I'd rather be explicit and clear.
