### ISSUE TITLE
Props not defined when using ThemeProvider

### ISSUE THREAD

**Issue by eugeneross** [styled-components/styled-components#2320]
Howdy!

I'm currently trying to adapt my team's current boilerplate (which uses Nextjs) to start using `<ThemeProvider>` for our projects. I've set up a `theme.js` file which has some style properties. I then have my `theme.js` imported into my Global Styles file. I reference one of my theme's properties in my global style file and it works fine. 

However, when I go into an individual component's file that uses SC and reference a property like: `${props.theme.colors.white}`, I receive `Unhandled Rejection (ReferenceError): props is not defined`.

If I were to import my theme file directly into the file like so: `import { theme } from '@utils'` I would then need to change my reference to `${theme.colors.white}`, which for me, defeats the purpose of using a ThemeProvider in the first place. 

I'm currently a few hours stuck on this issue and have not had many helpful resources when searching online. If anyone would like to take a peek at the project, you can find it here: [https://github.com/eugeneross/tortuga](https://github.com/eugeneross/tortuga)

As for related files to this issue, I'll post below.

`_app.js`:

```
import App, { Container } from 'next/app'
import React from 'react'
import Head from 'next/head'
import { ThemeProvider } from 'styled-components';

import stylesheet from '../styles/index.sass'
import { GlobalStyle, theme } from '@utils'

class MyApp extends App {
  static async getInitialProps({ Component, ctx }) {
    let pageProps = {}

    if (Component.getInitialProps) {
      pageProps = await Component.getInitialProps(ctx)
    }

    return { pageProps }
  }

  

  render() {
    
    const { Component, pageProps} = this.props

    console.log(ThemeProvider, theme, this.props, Component);
    return (
      <Container>
        <GlobalStyle />
        <Head>
          <title>Page Title</title>
        </Head>
        <ThemeProvider theme={theme}>
          <Component {...pageProps} />
        </ThemeProvider>
      </Container>
    )
  }
}

export default MyApp
```

`theme.js`:

```

// Colors

const primary = '#5C90E8'
const black = '#141516'
const white = '#ffffff'
const gray = '#EFEFEF'
const text = '#444444'


// Transitions

const transitions = {

  cubic: time => {
    return `all ${time} cubic-bezier(0.25, 0.46, 0.45, 0.94)`
  },
  cubic2: time => {
    return `all ${time} cubic-bezier(.215,.61,.355,1)`
  },
  cubic3: time => {
    return `all ${time} cubic-bezier(.86,0,.07,1)`
  },
  ease: time => {
    return `all ${time} ease-in-out`
  }

}

export const theme = {
  colors: {
    primary,
    black,
    white,
    gray,
    text,
  },
  
  transitions
}

```

## Steps to reproduce

`git clone git@github.com:eugeneross/tortuga.git`
`yarn`
`yarn dev`

## Expected Behavior

Should render the webpage with a small code block.

## Actual Behavior

Returns an `Unhandled Rejection (ReferenceError): props is not defined` error 
<img width="1060" alt="screen shot 2019-01-12 at 4 15 43 pm" src="https://user-images.githubusercontent.com/174520/51078586-6277f180-1685-11e9-9818-9171c1ff017a.png">

I've had a few of our engineers take a look at this well and they're stuck too 🤕 . If there's any solution out there for this issue I would love to know about it!

**Comment by mxstbr** [comment]
That is correct. Your interpolations need to be functions, you're referring to a variable that doesn't exist!

For example in your Button component:

```diff
const Button = styled.a`
-  transition: ${props.theme.transitions.cubic('.3s')};
+  transition: ${props => props.theme.transitions.cubic('.3s')};
`
```

I hope that helps!
