### ISSUE TITLE
Is there any best practice available to quickly tell styled components from regular components?

### ISSUE THREAD

**Issue by kurtgn** [styled-components/styled-components#2330]
I've recently started using styled components, and the problem I bumped into is that in a complicated react component structure it is hard to tell which component is a regular React component, and which is just a styled `div`/`span`/etc.

Especially so if styled components use props to customize their behavior.

Take this structure:

```
      <React.Fragment>
        
        <BackgroundWrapper>
          {messages.map(
            message => (
              <TGMessage
                key={message.uniqueId}
                message={message}
              />
            ),
          )}
          <MessageCreateDropdown />
        </BackgroundWrapper>
        
        <KeyboardField>
          <KeyboardField.Inner />
        </KeyboardField>

        <TGQRButtonGroup />
        
      </React.Fragment>
```

If I were to figure it out to find what component has logic, I would have to drill down into each one of them - just to find that half of them are just `styled.div`s.

So, are there any best practices you guys have come up with to battle this?

So far, my only idea is to prefix the `styled` components with their corresponding HTML tag names, to reduce some cognitive load:

```
    <React.Fragment>
        
        <DivBackgroundWrapper>
          {messages.map(
            message => (
              <TGMessage
                key={message.uniqueId}
                message={message}
              />
            ),
          )}
          <MessageCreateDropdown />
        </DivBackgroundWrapper>
        
       
        <DivKeyboardField>  
          <DivKeyboardField.Inner />
        </DivKeyboardField>

        <TGQRButtonGroup />
        
      </React.Fragment>
```

are there any other approaches to this?

**Comment by mxstbr** [comment]
Why do you need to know?

**Comment by probablyup** [comment]
https://www.styled-components.com/docs/api#isstyledcomponent

**Comment by rdrnt** [comment]
I just append `Styled` to the front of a styled component. That way it's easier to tell whats Styled and what's not. 

Example:

```
const Box = () => (
 <div>box</div>
);

const StyledExampleContainer = styled.div`
  // whatever styles
`;

const Example = () => (
 <StyledExampleContainer>
  <Box />
</StyledExampleContainer>

)
```
