### ISSUE TITLE
Using `defaultProps` or `attrs` for altering the `as` and `theme` props

### ISSUE THREAD

**Issue by kripod** [styled-components/styled-components#2337]
_This is a question about the difference between the behavior of `defaultProps` and `attrs`. The reason for not asking it through [StackOverflow](https://stackoverflow.com/questions/ask?tags=styled-components) or [Spectrum](https://spectrum.chat/styled-components/help) is that I think the answer should be covered by the official docs._

While I have found [a use-case for `defaultProps`](https://www.styled-components.com/docs/advanced#theming) in a single section of the documentation, there are no explicitly stated pros and cons about them in comparison to [`attrs`](https://www.styled-components.com/docs/api#attrs).

---

I'm creating a system of components in which `Box` would be a base and others would extend it through the `styled` API:

```js
import { defaultTheme } from '../theme';

const Box = styled.div``;

const Box.defaultProps = {
  theme: defaultTheme,
}
```

Is it correct to use `defaultProps` to define a default theme through a base component? Should I prefer using `attrs` instead?

---

When creating a `Paragraph` which extends `Box`, which way should I construct it?

```js
const Paragraph = styled(Box)`
  line-height: 1.5;
`;

Paragraph.defaultProps = {
  as: 'p',
};
```

Or

```js
const Paragraph = styled.attrs({ as: 'p' })(Box)`
  line-height: 1.5;
`;
```

If the answer is the latter, how do I type my props? There are multiple ways available:

```ts
const Component1 = styled.attrs({ as: 'p' })<Props>(Box)``; // Breaks VS Code syntax highlighting
const Component2 = styled.attrs<?, ?>({ as: 'p' })(Box)``; // What should I put in place of the question marks?
```

**Comment by sam-robinson** [comment]
This works for me, and doesn't break VS Code syntax highlighting

@types/styled-components: ^4.1.6
styled-components: ^4.1.3

```JSX
import React from "react";
import styled from "styled-components";

const Box = styled.div`
    line-height: 1;
    border: 1px solid black;
`;

interface Props {
    lineHeight?: number;
}

const Paragraph = styled(Box).attrs({ as: "p" })<Props>`
    line-height: ${props => props.lineHeight || 1.5};
    border: 1px solid green;
`;

export const Textfield = () => (
    <div>
        <Box>Box</Box>
        <Paragraph lineHeight={2}>Paragraph</Paragraph>
    </div>
);
```

**Comment by sarneeh** [comment]
@kripod Check out [my answer](https://github.com/styled-components/styled-components-website/issues/56#issuecomment-459686917) about this issue.

Quick answer: it depends on how you want the component to behave. Hardcoding props via `attrs` makes it impossible to override it via props (unless you do it yourself in the `attrs` factory function). `defaultProps` allow overrides.
