### ISSUE TITLE
Invalid style string for one component can crash styles for another components

### ISSUE THREAD

**Issue by bromzh** [styled-components/styled-components#234]
## Version
1.0.5

## Reproduction
http://www.webpackbin.com/E1Ow20nZM

## Steps to reproduce
See `HelloWorld.js` file. 

## Expected Behavior
Invalid css property in `Title` component should not affect to styles for `MyComponent`.

## Actual Behavior
See web-inspector. 
<img width="282" alt="2016-11-22 12 07 51" src="https://cloud.githubusercontent.com/assets/6627568/20523169/d1d2b98a-b0c4-11e6-8238-2712aadf2199.png">
Styles for `Title` component begins from the top. But on the bottom you can see class for `MyComponent`. compiler silently adds invalid styles onto page and as result both components displays wrong (because they styles are in one style tag).

**Comment by mxstbr** [comment]
This definitely isn't nice behaviour, but I'm not sure we can do anything about it, to be honest. I don't know if PostCSS tells us when it encounters invalid CSS? @geelen

**Comment by bromzh** [comment]
In angular 2 each component's styles placed in separate style tag.
<img width="455" alt="2016-11-22 15 46 45" src="https://cloud.githubusercontent.com/assets/6627568/20524330/1aa003f6-b0cb-11e6-9c8e-2ca867982d90.png">
Angular also didn't checks CSS to validity but due to separation styles from one component didn't affect to another.

**Comment by mxstbr** [comment]
@threepointone why do we inject a single `style` tag with multiple components? Is there a performance benefit to doing that?

**Comment by threepointone** [comment]
Not really, tho I haven't benchmarked. Glamor uses multiple tags based on a configurable maxLength per tag.

**Comment by mxstbr** [comment]
We set that `maxLength` to `40` AFAIR, I wonder if we could limit that to just-this-selector-except-if-it's-over-maxLen?

**Comment by geelen** [comment]
I did some benchmarks, once you have _lots_ of components the weight of all those DOM tags really crunches things. When each style tag has _lots_ of declarations they become super slow to edit. 40 was a good goldilocks point.

I'm pretty sure it's just the fact that the `url()` expression is broken, which _really_ breaks the PostCSS and Chrome parsers. I think it's the postcss-safe-parser which is "doing its best" here and inserting a `}};}` which makes this problem worse. Perhaps we could go back to the normal parser? It's a lot more sensitive to things like missing `;`s though. But maybe we can go back to being strict on that?

**Comment by mxstbr** [comment]
As of landing the new parser, `stylis`, with PR #286 in the v2 branch, this should no longer be a problem. (/cc @thysultan) As soon as v2 lands on npm I'll post another comment here.

I'll close this issue so we don't clutter our milestone, please try the v2 branch on your projects and let us know if it works!
