### ISSUE TITLE
Implement 'useTheme' using Hooks API

### ISSUE THREAD

**Issue by markoradak** [styled-components/styled-components#2340]
Hey there! 👋

I was wondering if there are plans on implementing Hooks API for specific parts regarding context providers? This would help us to use something like `useTheme()` outside of context of styled components, where we're currently using either `withTheme` HOC, or a render props pattern.

The implementation could probably be as simple as following:
```js
const useTheme = (...path) => path.join(".").split(".")
  .reduce((a, c) => (a && a[c] ? a[c] : null), useContext(ThemeContext));
```
and it would allow us to do something like:
```jsx
<Component background={useTheme('colors.blue')} />
```

I guess this has already been thought of, but since I couldn't find any issue related to it, I wanted to get your opinion on it.

I'd be more than happy to do a PR including something like this, maybe under something such as `styled-components/hooks` for now, until 16.8 (hopefully 🤓).

**Comment by mxstbr** [comment]
We want to switch our entire theming setup to use hooks to avoid the DevTools bloat that comes with the `ThemeConsumer` components!

Great idea about the `useTheme` hook, had not thought of that. I will open a general "Let's use hooks!" issue with this included, give me two minutes.

**Comment by SeanRoberts** [comment]
For anyone looking for a dead simple hook while we wait for something official:

```
import { useContext } from 'react';
import { ThemeContext } from 'styled-components';

export default function useStyledTheme() {
  const theme = useContext(ThemeContext);
  return theme || {};
}
```

**Comment by hon2a** [comment]
```javascript
import { useContext } from 'react'
import { ThemeContext } from 'styled-components'
import { get, identity } from 'lodash/fp'

export const useTheme = path => (path ? get(path) : identity)(useContext(ThemeContext) ?? {})
```

**Comment by wmertens** [comment]
I'm reopening this, since #2343 does not include this.

I would like to see this as part of styled-components v5 and not a helper library.

I prefer the simplest version `const useTheme = () => useContext(ThemeContext)`:
* if you want to get some item at some path, you can use plain js or get or wrap the hook
* passing a theme to merge (`const currentTheme = useTheme({color: 'red'})`) is not possible, because it would require wrapping the component with a provider

**Comment by lcswillems** [comment]
Hooks are more and more used and it would be nice to include a `useTheme` hook in the library. I had to create my own this is not convenient.

SeanRoberts proposed a working example:
```
import { useContext } from 'react';
import { ThemeContext } from 'styled-components';

export default function useStyledTheme() {
  const theme = useContext(ThemeContext);
  return theme || {};
}
```

A  lot of other React library propose such hooks.

**Comment by hon2a** [comment]
@wmertens Absolutely understandable. I've listed the implementation I'm using just as inspiration for the meantime. Of course it makes little sense to bake the property getter into the hook that the generic library will provide.

**Comment by markoradak** [comment]
I created a small utility function based on @SeanRoberts answer as I do agree it makes most sense, and since I'm dragging it from project to project I realized it makes sense to publish it (at least until we see it within the library).

https://github.com/markoradak/use-styled-theme

**Comment by kachkaev** [comment]
`useTheme` was added in https://github.com/styled-components/styled-components/pull/2765 Once a new version is released, your React components will be able to do this:

```ts
import { useTheme } from "styled-components";

export const MyNonStyledComponent = () => {
  const myBlueColor = useTheme().colors.blue;

  return <SomeJsx />;
}
```

This solution is a bit better than `useTheme('colors.blue')`, which was originally proposed in this issue. Reasons are type-safety and performance.

**Comment by MathieuDoyon** [comment]
From @SeanRoberts most like answer.

For Typescript user I would use something like that
`const useTheme = <T = DefaultTheme>() => useContext<T>(ThemeContext) || {};`

**Comment by jesster2k10** [comment]
I think that there's an error in the typing when working with typescript. 
![Screenshot 2020-02-20 at 18 11 25](https://user-images.githubusercontent.com/6454286/74965050-69d30800-540c-11ea-84a4-a0934cb30420.png)

**Comment by semoal** [comment]
> I think that there's an error in the typing when working with typescript.
> ![Screenshot 2020-02-20 at 18 11 25](https://user-images.githubusercontent.com/6454286/74965050-69d30800-540c-11ea-84a4-a0934cb30420.png)

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/42415
Once this pull request is ready, it'll get fixed. Meanwhile just @ts-ignore it
