### ISSUE TITLE
props.theme is undefined in components imported from node_modules

### ISSUE THREAD

**Issue by iothetiger** [styled-components/styled-components#2347]
I'm attempting to use ThemeProvider.  It is working as expected for components imported from the same project, but is not working for components we are importing via our own package via yarn link.

I'm not sure if this is a bug or if this is expected behavior and it is not mentioned in the documentation.  If so, is there a recommended way to get it to work?

**Comment by iothetiger** [comment]
Our error is likely due to hot reloading in Electron and we are debugging.

**Comment by stearm** [comment]
Hi @iothetiger , we have to put styled-components as peerDependencies in your components package! In this way there will be only an instance of styled-components and only a ThemeProvider :)

**Comment by adriankremer** [comment]
Hey @stearm, i dont get the solution by adding it as an peerDeps because the components are already transpiled and node module resolves this already by shrinkwrap. Nevertheless i have tested it and it is not working :(

**Comment by probablyup** [comment]
Very likely to be an environment or node_modules duplication issue
