### ISSUE TITLE
Attach style tags on a different node

### ISSUE THREAD

**Issue by sammkj** [styled-components/styled-components#235]
I'm currently working on a chrome extension that uses shadow DOM and `styled-components`. Currently all styles are appended to `<head />`. That causes elements in shadow DOM unable to access the styles. Could there be a way to specify where I want the styles to be appended to?

**Comment by mxstbr** [comment]
Do you want to attach them to an arbitrary DOM node? I doubt this is a use case we'll support, but I'd be interested to hear what you imagine it working like!

**Comment by sammkj** [comment]
Yes. Let's say I have a chrome extension that is wrapped in a shadow dom component and a component like Radium's [`StyleRoot`](https://github.com/FormidableLabs/radium/tree/master/docs/api#styleroot-component):

```
/**
 * `meow-container` is the host
 */
<div id="meow-container" style="all: initial;">
  #shadow-root (open)
  <StyleRoot>
    <div class="meow-app">
      meow
    </div>
    /**
     * notice this style tag here.
     * Instead of appending styles to `head`,
     * styles are appended to `StyleRoot` component.
     * Anything outside of `meow-container` is not accessible.
     */
    <style>
      .meow-app {
        background-color: red;
      }
    </style>
  </StyleRoot>
</div>
```

**Comment by morsdyce** [comment]
I'm also interested in this feature, sometimes we don't own the application we're running in and are forced to use sandboxing techniques, it would be great if I could specify either a DOMNode or use a StyleRoot like suggested above.

**Comment by geelen** [comment]
Yeah I'd like this too. @mxsbtr I'll take a look at it when I'm next hacking

**Comment by mxstbr** [comment]
Could y'all please review #1102? It finally implements this in a nice-to-use API!

**Comment by mxstbr** [comment]
Closing in favor of https://github.com/styled-components/styled-components/issues/659
