### ISSUE TITLE
Importing a styled component from an external source doesn't work with webpack.

### ISSUE THREAD

**Issue by Pixelatex** [styled-components/styled-components#2352]
the setup is like this:

Repository 1 contains generic styled components (component library kind of)
Repository 2 will pull in rep 1 as-is. It is not compiled in anyway.

Rep 2 already has styled components in it and they compile correctly.

Notes:

Repository 1 and 2 both run the same version, `4.1.2`
Repository 1 has styled comp as a peer dependency to prevent duplicate styled comp..
Rep 1 has an alias for styled comp setup so it will use the styled comp from its node modules and not any other.

The error it keeps failing on is the generic:

```
Unexpected token (15:4)
You may need an appropriate loader to handle this file type.
|     backgroundColor,
| }) => (
>     <CardContainer
|         width={width}
|         border={border}
```

So it is not recognizing styled components at all somehow? I have tried googling this for an entire day and can 't find any fixes or people who had this exact issue. 

Anyone have any ideas?

**Comment by Pixelatex** [comment]
!small sidenote, I am pulling in the repository as a dependency, I'm not using a link.

**Comment by mxstbr** [comment]
This has nothing to do with styled-components, your bundler is not configured correctly to transpile JSX for some reason.
