### ISSUE TITLE
sass like "& &"

### ISSUE THREAD

**Issue by ChiefORZ** [styled-components/styled-components#2353]
i need to target the classes of another library descentand from this styled component and therefore need the operators `&-foo &-bar` but styled components is creating another class.

## Reproduction
https://codesandbox.io/s/6wqnwyl6kk

## Expected Behavior

i need the CSS selectors to be looking something like this:
```html
<style data-styled="" data-styled-version="4.1.3">
  /* sc-component-id: sc-bdVaJa */
  .gRwSxa .menu-sub .menu-submenu{border:1px solid red;}
</style>
```

## Actual Behavior

but when i write the CSS selectors inside the styled-component it inherits not only the parent class, but adds another class, what is not reference-able.
```html
<style data-styled="" data-styled-version="4.1.3">
  /* sc-component-id: sc-bdVaJa */
  .gRwSxa .menu-sub .sc-bdVaJa .menu-submenu{border:1px solid red;}
</style>
```

is this a bug, or could somebody explain the behavior of styled-components in this example to me

thanks!

**Comment by markoradak** [comment]
That's very much how Sass would interpret it. I think you're forgetting that `.menu` is not your parent class here, but rather a class (or classes in this case) created by Styled Components.

Imagine the following Sass snippet: 
```sass
.styled-component {
  .menu {
    &-sub &-submenu {
      border: 1px solid red;
    }
  }
}
```
That would yield the following css: 
```css
.styled-component .menu-sub .styled-component .menu-submenu {
  border: 1px solid red;
}
```
