### ISSUE TITLE
Autoprefixer in development mode ignored

### ISSUE THREAD

**Issue by berndschimmer** [styled-components/styled-components#2358]
## System:
 - OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
 - CPU: (4) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
 - Memory: 644.52 MB / 7.79 GB
 - Container: Yes
 - Shell: 4.4.19 - /bin/bash
## Binaries:
 - Node: 10.15.0 - ~/.config/versions/node/v10.15.0/bin/node
 - Yarn: 1.13.0 - /usr/bin/yarn
 - npm: 6.4.1 - ~/.config/versions/node/v10.15.0/bin/npm
## npmPackages:
 - styled-components: ^4.1.3 => 4.1.3 

## package.json 
...
"browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not ie <= 11",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version"
    ]
  }
... 

## Steps to reproduce
Install create react app, install styled-components. Add a div and style this div like this: 
```
const StyledDiv = styled.div`
  display: flex;
`;
```
yarn start 

## Expected Behavior
With the given browserlist development configuration the css output should be:
`display: flex;`

## Actual Behavior
The output is:
   ```
    display: -webkit-box;
    display: -webkit-flex;
    display: -ms-flexbox;
    display: flex;
```

Is this the correct repository for this problem or should i ask in the create-react-app or in the browserslist repo?

**Comment by probablyup** [comment]
We don’t use autoprefixer
