### ISSUE TITLE
@Keyframes not working in create-react-app

### ISSUE THREAD

**Issue by MoeSattler** [styled-components/styled-components#236]
![screen shot 2016-11-22 at 16 36 29](https://cloud.githubusercontent.com/assets/8615251/20529834/e1de61aa-b0d1-11e6-9502-8e7832e74627.png)
![screen shot 2016-11-22 at 16 37 23](https://cloud.githubusercontent.com/assets/8615251/20529874/f918a470-b0d1-11e6-9f87-f044bf8f9ea6.png)
 

Fresh and immediately ejected create-react-app. Just copy pasted the example keyframe. It gives me this.

**Comment by mxstbr** [comment]
Can you push that up to a repo so I can repro it? Thanks!

**Comment by MoeSattler** [comment]
Just reproduced it in an extra repo... and it works. Not sure what I did wrong before that. 
Sorry for that.
