### ISSUE TITLE
Trouble installing Styled-Components.

### ISSUE THREAD

**Issue by alexharrisdcj** [styled-components/styled-components#2360]
I can't seem to install styled-components properly using NPM. Upon attempting to install using 'npm install styled-components', I get the following error..
```
> styled-components@4.1.3 postinstall C:\Dealerhack\dealerhack\node_modules\styled-components
> node ./scripts/postinstall.js || exit 0

At line:1 char:31
+ node ./scripts/postinstall.js || exit 0
+                               ~~
The token '||' is not a valid statement separator in this version.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidEndOfLine
```

## System:
 - OS: Windows 10
 - CPU: (6) x64 Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
 - Memory: 6.86 GB / 15.93 GB
## Binaries:
 - Node: 8.12.0 - C:\Program Files\nodejs\node.EXE
 - npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

**Comment by mxstbr** [comment]
Interesting, we should figure out how to make our `postinstall` script windows compatible. What is the equivalent syntax for running a command if it fails?

**Comment by alexharrisdcj** [comment]
It seem to work find on my Windows PC at work, same NPM/Node versions.

Not sure what the issue is.

**Comment by alexharrisdcj** [comment]
I was able to fix this by changing my default npm shell. 

> npm config set script-shell "C:\\Program Files\\Git\\bin\\bash.exe"

Thanks!
