### ISSUE TITLE
Strange situaction (closing browser tab)

### ISSUE THREAD

**Issue by tborowy** [styled-components/styled-components#2361]
So... I dont' know if is styled-component bug or maybe webpack or other.
example i have two styled components. Both use backgroud
```
import styled from 'styled-components';
import profileDefault from './assets/profile_default.svg';

const One = styled.div`background : url(${profileDefault})`;
const Two = styled.div`background : url(${close})`;
```
I didn't notice that `close` is not imported. And when webpack build page and I open it in browser component trying to close browser window/tab (call close())

at the moment everything is working for me. However, I am very curious, why?

**Comment by mxstbr** [comment]
`window.close()` is a method that closes the window. When you interpolate any function in a styled component, we call it with the current props:

```JS
const Button = styled.button`
  color: ${props => props.color};
`
```

So when you put `window.close` into the styled component, we saw a function and called it with `props`! Functionally, this happened:

```JS
const Two = styled.div`
  background : url(${props => window.close(props)})
`;

Hope that makes sense
