### ISSUE TITLE
Support for Nested Properties

### ISSUE THREAD

**Issue by iamricky** [styled-components/styled-components#2362]
How feasible would it be to add support for nested properties?

e.g. the following code: 
```JSX
styled.h1`
  font: {
    size: 18px;
    weight: bold;
    variant: small-caps;
  }
  text: {
    align: 'left';
    transformation: 'capatalize';
    indent: 20px;
  }
`
``` 
would result in:
```
.h1 {
  font-size: 18px;
  font-weight: bold;
  font-variant: small-caps;
  text-align: 'left';
  text-transformation: 'capatalize';
  text-indent: 20px;
}
```

This is a basic sass/scss feature that I use quite often.

**Comment by mxstbr** [comment]
It is out of scope for styled-components to change the way you write CSS (apart from removing the class names). That being said, you could easily hack together a util that did this for you, something like this for example:

```JS
const font = (input) => {
  return Object.keys(input).reduce((output, key) => {
    output[`font-${key}`] = input[key];
    return output;
  }, {});
}

const Heading = styled.h1`
  ${font({
    size: '18px',
    weight: 'bold',
    variant: 'small-caps',
  });
`
```

(note that this is entirely untested, but you get the gist I hope)

Hope that helps!
