### ISSUE TITLE
Error while commenting variables inside interpolated strings

### ISSUE THREAD

**Issue by simformsolutions** [styled-components/styled-components#2364]
## System:
 - OS: macOS High Sierra 10.13.4
 - CPU: (4) x64 Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz
 - Memory: 346.27 MB / 12.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
 - Yarn: 1.13.0 - /usr/local/bin/yarn
 - npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: ^1.10.0 => 1.10.0
 - styled-components: ^4.1.3 => 4.1.3

## Steps to reproduce
I am facing an issue with styled-components commenting interpolated values. I have added fonts via the `@font-face` rule.
![fonts](https://user-images.githubusercontent.com/8736329/52058235-040ba800-258d-11e9-8102-32ac494ca7c2.png)

After commenting the code, it throws an error like this
![fonts-error](https://user-images.githubusercontent.com/8736329/52058327-3917fa80-258d-11e9-885b-bd91dbb61f93.png)

## Expected Behavior
It should not throw an error after commenting

**Comment by mxstbr** [comment]
JavaScript does not know about CSS comments at all, so it still interpolates the values from the interpolations.

There is unfortunately nothing we can do about that, since we cannot make JavaScript magically understand CSS comments inside strings! Sorry
