### ISSUE TITLE
Theme prop and defaultProp on a styled component is not working on react native 

### ISSUE THREAD

**Issue by lucastschmidt** [styled-components/styled-components#2367]
## System:
 - OS: macOS 10.14.2
 - CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
 - Memory: 289.74 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 8.15.0 - ~/.nvm/versions/node/v8.15.0/bin/node
 - Yarn: 1.13.0 - /usr/local/bin/yarn
 - npm: 6.4.1 - ~/.nvm/versions/node/v8.15.0/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman

## Reproduction

I want to define theme props for a styled component, using the React Native version, but theme is always set as an *empty object*, even when I define a defaultProps or a prop to the component. 

*Bug possibly only on native, I tested on the browser and it works:* https://codesandbox.io/s/y2ko222zqv

I analysed the code and noticed a difference between native and browser versions on method `StyledNativeComponent.render` versus `StyledComponent.renderInner`

On browser it considers the `props.theme`:

```    
    if (componentStyle.isStatic) {
      generatedClassName = this.generateAndInjectStyles(EMPTY_OBJECT, this.props);
    } else if (theme !== undefined) {
      generatedClassName = this.generateAndInjectStyles(determineTheme(this.props, theme, defaultProps), this.props);
    } else {
      generatedClassName = this.generateAndInjectStyles(this.props.theme || EMPTY_OBJECT, this.props);
    }
```

while on Native it doesnt:

```       
       if (theme !== undefined) {
          var themeProp = determineTheme(_this2.props, theme, defaultProps);
          generatedStyles = _this2.generateAndInjectStyles(themeProp, _this2.props);
        } else {
          generatedStyles = _this2.generateAndInjectStyles(theme || EMPTY_OBJECT, _this2.props);
        }
```

Possibly very simple fix, I cant right now do a merge request and run tests, late here, I thought I was crazy since the behaviour wasnt working :)

## Steps to reproduce
- create a styled component for a native element like Text, using a `prop.theme` to style it, you can define defaultProps as well
- do not use a theme provider in the app
- use the styled component passing a theme object as a prop

Same as I did on sandbox, but import the native version and use any 

## Expected Behavior

- when you use a prop as theme
-- expect the styled component to use the theme props
- when you do not inform any theme prop
-- expect the styled component to use the defaultProps

## Actual Behavior
- when you use a prop as theme
-- sets an empty object as theme
- when you do not inform any theme prop
-- sets an empty object as theme

**Comment by probablyup** [comment]
`determineTheme` will pull from `props.theme` if available

**Comment by lucastschmidt** [comment]
@probablyup sure, but it is only called if a theme provider is configured ... thats the bug 😄 

If you notice, the `else` statement, in the native version.
