### ISSUE TITLE
Debug class names do not work when styled function is reexported with macros

### ISSUE THREAD

**Issue by Hurtak** [styled-components/styled-components#2368]
When importing `styled` and using it in the same file, debug class names work as expected.

```jsx
// main.js
import styled from "styled-components/macro";
const Text = styled.div({ color: "red" });
```

---

When reexporting the styled function in another file, debug class names disappear

```jsx
// css.js
import styled from "styled-components/macro";
export { styled }
```

```jsx
// main.js
import { styled } from "./css.js";
const Text = styled.div({ color: "red" });
```

Perhaps this is limitation of the babel macros? If so maybe we should add _limitations_ chapter in the docs (https://www.styled-components.com/docs/tooling#babel-macro).

---

Versions:

```json
"styled-components": "4.1.3"
"react-scripts": "2.1.3"
```

**Comment by kitten** [comment]
As far as I remember this is indeed a limitation of macros, since they only operate on the file-only Babel AST.

A PR to our website repo is always welcome :) I'm sure we can mention some pitfalls there https://github.com/styled-components/styled-components-website

**Comment by atdrago** [comment]
I ran into this issue because I was trying to import `styled`, provide it a theme interface, then reexport it [as described here](https://www.styled-components.com/docs/api#define-a-theme-interface), but using the babel macro instead of the root package.

If this is your use case, I think I found a solution. Instead of having the extra `styled-components.ts` file mentioned in the docs, you can re`declare` the `"styled-components/macro"` module using your Theme interface, then `import styled from 'styled-components/macro'` directly. This solves the file-only problem.

Here's what I have in my `global.d.ts` (`ITheme` is my theme interface located in a different file):
```ts
declare module 'styled-components/macro' {
    import { ThemedStyledComponentsModule } from 'styled-components';
    import { ITheme } from 'typings';

    const ModuleInterface: ThemedStyledComponentsModule<ITheme>;

    export const createGlobalStyle: typeof ModuleInterface.createGlobalStyle;
    export const css: typeof ModuleInterface.css;
    export const keyframes: typeof ModuleInterface.keyframes;
    export const isStyledComponent: typeof ModuleInterface.isStyledComponent;
    export const ServerStyleSheet: typeof ModuleInterface.ServerStyleSheet;
    export const StyleSheetManager: typeof ModuleInterface.StyleSheetManager;
    export const ThemeConsumer: typeof ModuleInterface.ThemeConsumer;
    export const ThemeContext: typeof ModuleInterface.ThemeContext;
    export const ThemeProvider: typeof ModuleInterface.ThemeProvider;
    export const withTheme: typeof ModuleInterface.withTheme;
    export default ModuleInterface.default;
}
```

Then, make this change everywhere you imported `styled` previously:

```diff
- import styled from './styled-components.ts';
+ import styled from 'styled-components/macro';
```

I don't know if the above could be achieved more elegantly, but would love feedback!

**Comment by chriserickson** [comment]
@atdrago  -- thank you, that made things work for me.

**Comment by chriserickson** [comment]
I spoke a little too soon -- with the above solution, my `props.theme` value in any styled component is an `any` rather than `ITheme`.

**Comment by atdrago** [comment]
That's odd. My `props.theme` is `ITheme`. Are you sure you're importing from "styled-components/macro"?

![image](https://user-images.githubusercontent.com/144225/54229129-ddf8f200-44c0-11e9-9a20-3df4afdfe948.png)

**Comment by chriserickson** [comment]
My import is correct....

I'm thinking that `global.d.ts` is just getting ignored due to create-react-app.

**Comment by chriserickson** [comment]
Actually, it seems to be how my theme is defined. If I define it inline, then things work fine.

**Comment by esetnik** [comment]
I found that you can use `DefaultTheme` for this purpose and it works better. Check out the docs https://www.styled-components.com/docs/api.

```
// eslint-disable-next-line no-restricted-imports
import 'styled-components';

declare module 'styled-components' {
  export interface DefaultTheme {
    white: string;
    navy: string;
    warning: string;
    alert: string;
    teal100: string;
    teal80: string;
    teal60: string;
    teal40: string;
    teal20: string;
    grey100: string;
    grey80: string;
    grey60: string;
    grey40: string;
    grey20: string;
    grey10: string;
    borderRadius: string;
    fontFamily: string;
  }
}
```

```
// eslint-disable-next-line no-restricted-imports
import { DefaultTheme } from 'styled-components';
import { css } from 'styled-components/macro';

const sizes = {
  desktop: 992,
  tablet: 768,
  phone: 576,
};

export const media = (Object.keys(sizes) as Array<keyof typeof sizes>).reduce(
  (acc, label) => {
    acc[label] = (first: any, ...interpolations: any[]) => css`
      @media (min-width: ${sizes[label]}px) {
        ${css(first, ...interpolations)}
      }
    `;

    return acc;
  },
  {} as { [key in keyof typeof sizes]: typeof css }
);

export const theme: DefaultTheme = {
  white: '#ffffff',
  navy: '#242d3a',
  warning: '#fbb304',
  alert: '#c10000',
  teal100: '#639fab',
  teal80: '#639fabcc',
  teal60: '#639fab99',
  teal40: '#639fab66',
  teal20: '#639fab33',
  grey100: '#333333',
  grey80: '#555555',
  grey60: '#999999',
  grey40: '#cccccc',
  grey20: '#eaeaea',
  grey10: '#fafafa',
  borderRadius: '0.25rem',
  fontFamily: 'Open Sans, sans-serif',
};
```

**Comment by CANHBK** [comment]
> I ran into this issue because I was trying to import `styled`, provide it a theme interface, then reexport it [as described here](https://www.styled-components.com/docs/api#define-a-theme-interface), but using the babel macro instead of the root package.
> 
> If this is your use case, I think I found a solution. Instead of having the extra `styled-components.ts` file mentioned in the docs, you can re`declare` the `"styled-components/macro"` module using your Theme interface, then `import styled from 'styled-components/macro'` directly. This solves the file-only problem.
> 
> Here's what I have in my `global.d.ts` (`ITheme` is my theme interface located in a different file):
> 
> ```ts
> declare module 'styled-components/macro' {
>     import { ThemedStyledComponentsModule } from 'styled-components';
>     import { ITheme } from 'typings';
> 
>     const ModuleInterface: ThemedStyledComponentsModule<ITheme>;
> 
>     export const createGlobalStyle: typeof ModuleInterface.createGlobalStyle;
>     export const css: typeof ModuleInterface.css;
>     export const keyframes: typeof ModuleInterface.keyframes;
>     export const isStyledComponent: typeof ModuleInterface.isStyledComponent;
>     export const ServerStyleSheet: typeof ModuleInterface.ServerStyleSheet;
>     export const StyleSheetManager: typeof ModuleInterface.StyleSheetManager;
>     export const ThemeConsumer: typeof ModuleInterface.ThemeConsumer;
>     export const ThemeContext: typeof ModuleInterface.ThemeContext;
>     export const ThemeProvider: typeof ModuleInterface.ThemeProvider;
>     export const withTheme: typeof ModuleInterface.withTheme;
>     export default ModuleInterface.default;
> }
> ```
> 
> Then, make this change everywhere you imported `styled` previously:
> 
> ```diff
> - import styled from './styled-components.ts';
> + import styled from 'styled-components/macro';
> ```
> 
> I don't know if the above could be achieved more elegantly, but would love feedback!

Thank you! That works for me!

**Comment by maksnester** [comment]
That is what worked for me eventually, inspired by @esetnik answer

```ts
// some-declarations-file.d.ts

import type { ThemeType } from './styles/theme';

// even despite I use import styled from 'styled-components/macro' in components
// that declaration works fine for me
declare module 'styled-components' {
  export interface DefaultTheme extends ThemeType {}
}
```

Then styled-components have proper types for theme. Theme is must be passed to provider.

```tsx
// your app providers file
import { ThemeProvider } from 'styled-components/macro';
// ...
<ThemeProvider theme={theme}>
```

and for styled components the theme is typed now

```ts
// some-styled.ts
import styled from 'styled-components/macro';

export const FooBar = styled.div`
  background-color: ${(props) => props.theme.any.prop.from.the.theme};
`;
```
