### ISSUE TITLE
Is there a way to console.log the output of the generated css ?

### ISSUE THREAD

**Issue by kopax** [styled-components/styled-components#237]
Is there a way to console.log the output of the styled component css ?
I find debugging not intuitive when you have a lot's of theme configuration variable and some of them missing.

**Comment by mxstbr** [comment]
```JS
import styleSheet from 'styled-components/lib/models/StyleSheet'

styleSheet.rules().map(rule => rule.cssText).join('\n')
```

This should work I think?

**Comment by kopax** [comment]
Sorry I might not have been accurate enough : 

    Form.propTypes = propTypes;
    Form.defaultProps = defaultProps;

    export default Form;
    console.log(Form.rules().map(rule => rule.cssText).join('\n'));

Throw error: 

    2016-11-23 14:09:18.736 index.js:60 TypeError: Form.rules is not a function(…)

Is there a way to log the generated css here ? 

     // eslint-disable-next-line no-class-assign
     Form = styled(Form)` 
         height: ${(props) => props.theme.atoms.Form['$input-height']};
     `

What was the line you give me for ?

**Comment by mxstbr** [comment]
You can't map over a specific components CSS, you can only log all the CSS at the moment I'm afraid!

**Comment by kopax** [comment]
Excuse me but I didn't get the sens, what do you mean by 'mapping over ' a css ?
You say that I "can only log all the css at the moment", what moment ?

**Comment by mxstbr** [comment]
There is a way to log over the whole CSS of _all_ styled components on a page with this three line snippet:

```JS
import styleSheet from 'styled-components/lib/models/StyleSheet'

console.log(styleSheet.rules().map(rule => rule.cssText).join('\n'))
```

Copy and paste this into after your `ReactDOM.render()` call and you should see _all_ your generated styles.

But there is no way to log over the generated CSS of a _single_ styled component.

**Comment by vdanchenkov** [comment]
@kopax You can temporary add some custom property for debug. Any name starting with double dash will work.  

```jsx
Form = styled(Form)` 
         height: ${(props) => props.theme.atoms.Form['$input-height']};
         --label: Form;
     `
```

After that you will be able to grab list of all rules and filter them by presence of property value

```jsx
// after ReactDOM.render()
import styleSheet from 'styled-components/lib/models/StyleSheet'
console.log(styleSheet.rules().map(rule => rule.cssText).filter(text => ~text.indexOf('--label: Form')).join('\n'))
```

**Comment by thany** [comment]
Any way to make this work in 2023?
