### ISSUE TITLE
Like my tweet for a contest!

### ISSUE THREAD

**Issue by zamarrowski** [styled-components/styled-components#2373]
https://twitter.com/zamarrowski/status/1093543087496982528

**Comment by mxstbr** [comment]
Reported as spam internally, good bye! :wave:

**Comment by zamarrowski** [comment]
Ou sorry :(

It was a joke for a contest: some tickets for frontfest event in Madrid...

I'm sorry again

**Comment by mxstbr** [comment]
Oh sorry, I did not realise the joke. Nevermind! :pray:
