### ISSUE TITLE
Workaround to problem "Cannot find a StyleSheet instance"

### ISSUE THREAD

**Issue by OsmanCure** [styled-components/styled-components#2374]
For those who still have have the problem in the following link:

[https://github.com/styled-components/styled-components/blob/master/src/utils/errors.md#10](url)

I have figured out a workaround.  Setting 'SC_DISABLE_SPEEDY' variable as follows solves the problem.

webpack.DefinePlugin({
  SC_DISABLE_SPEEDY: true,
});

It is introduced in version "v4.1.0 - 2018-11-12" which you can find in the link below:

[https://github.com/styled-components/styled-components/blob/master/CHANGELOG.md](url)

Briefly, the error is only produced in "production" mode. It is due to a method in the library trying to create "speedy" tags and failing to find a stylesheet.

On the other hand, in "development" mode, tag creation is done with another method.

I hope the workaround will work for everyone having a trouble with this error. It has caused me serious problems.

**Comment by probablyup** [comment]
This issue is more likely to be due to library duplication in node_modules.

**Comment by OsmanCure** [comment]
I am pretty sure that I don't have duplication in node_modules. As I said, the error is thrown in the "production" mode due to the so called "speedy" method not in "development" mode.

In my case, I am removing some elements from the dom and reinjecting them. In second injection, the error is thrown. 

The library tries to create <style> element to put into <head> but while doing, it is not able to find any stylesheet of the element. Therefore it throws an error.

**Comment by leoyli** [comment]
@OsmanCure Oh man! You really save my day, I was bumping my head to think about a weird bug only popping up in my production build of the storybook app...

My case was due to I rearranging `<style>` blocks to ensure styled-component injected CSS will always gives the highest specificity (to use together with Material-UI's JSS)...

Thanks!!!!

**Comment by evankim390** [comment]
I ran into this problem when trying to implement Turbolinks on my team's website. I believe the Turbolinks merge algorithm disrupts the `style` tags on the page, causing them to lose their `sheet` reference. In my limited understanding, this is why the problem manifests with speedy, which takes advantage of sheets, and not with the default mode, which I think simply uses style tags.

In my case, the solution was to use `data-turbolinks-permanent` to persist the `style` tags across page renders.
