### ISSUE TITLE
Use new Constructable Stylesheets API?

### ISSUE THREAD

**Issue by chaffeqa** [styled-components/styled-components#2376]
Chrome just introduced some new API, looks like they are trying to address issues with injected stylesheets and it made me think of SC 😍 

https://blog.chromium.org/2019/02/chrome-73-beta-constructable.html

☝️ Think this could be of any use for SC?

**Comment by mxstbr** [comment]
😍😍😍😍

This is probably highly relevant for #2357, we should be able to leverage that there!

**Comment by chaffeqa** [comment]
haha awesome! i was actually thinking of referencing that when creating this issue.  Let me know if there is any way I can help.

As always you guys rock! love SC!

**Comment by probablyup** [comment]
@mxstbr realistically how useful is this to us if it's only in Blink and brand new, so not implemented in any other browsers for some time

**Comment by mxstbr** [comment]
Not super useful but still nice to have in the future! `const sheet = CSSStyleSheet ? new CSSStyleSheet() : injectTag().sheet`

**Comment by chaffeqa** [comment]
If it matters, I would say it's a really simple feature detection and minimal implementation it's totally worth it. Chrome's marketshare is enough to make the impact worthwhile plus they are excellent with their release cycle (I looove the chrome slack 😍)

If it's a higher amount of work, only do it if someone has the bit between their teeth. Otherwise it's enough to keep a pulse on the movement of the standard and see if other browsers latch on

**Comment by chaffeqa** [comment]
any movement on this? just read the new chrome updates, specifically https://developers.google.com/web/updates/2020/06/devtools#css-in-js

Looks like some really cool CSS in JS support using constructed stylesheets.

**Comment by kitten** [comment]
This isn't worth implementing if I'm not missing anything 😅

As long as we need to support evergreen browsers that don't implement this (so indefinitely, and also IE11) we need to add a `style` Tag manually. We'd also need this code for non-CSSOM injection.

So all that this addition of constructable Stylesheets achieves is being able to skip this step, so realistically we don't need to support this.

**Comment by chaffeqa** [comment]
gotcha thx for the info!  I honestly didnt know the pros / cons, but that makes sense.

I think the only thing that im curious about still is if using CS vs `style` element can expose and current/future optimizations from the browser engine itself (less rebuilding of cached CSS trees, ect).  That would be the only reason I see currently for supporting this (maybe as a feature?)

FYI the way I think of it is: many webapps at this point should be moving to x2 bundles: modern and legacy... building x2 webpack bundles, similar to nextJS approach.

This would be one of the features I think you would add to the `modern` bundle (along with things like css variable support, ect).

Going to close this tho to prevent noise, thanks again @kitten !
