### ISSUE TITLE
Babel macro conflicts w/ TS

### ISSUE THREAD

**Issue by mAAdhaTTah** [styled-components/styled-components#2378]
#### System:
 - OS: macOS 10.14.1
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 163.83 MB / 16.00 GB
 - Shell: 5.0.2 - /usr/local/bin/bash
#### Binaries:
 - Node: 11.9.0 - /usr/local/bin/node
 - Yarn: 1.13.0 - /usr/local/bin/yarn
 - npm: 6.5.0 - /usr/local/bin/npm
#### npmPackages:
 - styled-components: ^4.1.3 => 4.1.3

## Reproduction

Create a new CRA-based app w/ TypeScript. Add `@types/styled-components` & `styled-components`, and update App.tsx to look like the following:

```jsx
import React, { Component } from 'react';
import styled, { DefaultTheme } from 'styled-components/macro';
import logo from './logo.svg';
import './App.css';

const Link = styled.a``;

class App extends Component<{ theme: DefaultTheme }> {
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <p>
            Edit <code>src/App.tsx</code> and save to reload.
          </p>
          <Link
            className="App-link"
            href="https://reactjs.org"
            target="_blank"
            rel="noopener noreferrer"
          >
            Learn React
          </Link>
        </header>
      </div>
    );
  }
}

export default App;
```

Note that we're importing a type, `DefaultTheme`, from `styled-components/macro`, but otherwise, nothing special here.

## Steps to reproduce

Run `npm run build`.

## Expected Behavior

The build completes successfully.

## Actual Behavior

Build errors with the below:

```
Creating an optimized production build...
Failed to compile.

./src/components/views/EmployeeDetail/Charts/CompensationHistory.tsx
MacroError: Invalid import: DefaultTheme. You can only import default, css, keyframes, createGlobalStyle, isStyledComponent, ThemeConsumer, ThemeContext, ThemeProvider, withTheme, ServerStyleSheet, StyleSheetManager, __DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS from 'styled-components/macro'.
```

The error appears somewhat related to [this change](https://github.com/kentcdodds/babel-plugin-macros/pull/96) in babel-plugin-macros but it's also directly caused by the validation done by the macro [here](https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/macro/index.js#L17-L23).

My current theory is the macros PR changed the order the macros were being run, so the styled-components macro is being run against an AST that still contains imported types. The macro then finds an identifier it's not expecting (in this case, `DefaultTheme`) and bombs out.

Couple potential solutions (happy to PR any of them):

1. Remove the identifier validation completely.
2. Warn & skip if invalid identifier is found.
3. Silently skip if invalid identifier is found
4. Enable providing a list of "expected identifiers" that the macro should ignore.
5. Add TS types to "expected identifiers"  and skip.

**Comment by probablyup** [comment]
We don't maintain the TS types in this repo, they're in DefinitelyTyped. I'd recommend opening an issue over there.

**Comment by mAAdhaTTah** [comment]
@probablyup this isn't an issue with the types. It's an issue with the macro when importing a type.
