### ISSUE TITLE
@font-face in injectGlobal on server side

### ISSUE THREAD

**Issue by diegohaz** [styled-components/styled-components#238]
Related to #124 

## Version
1.1.0

## Reproduction
https://github.com/0xsven/arc-temp

## Steps to reproduce
Run `npm run dev`, open the index route on Chrome. Then change the route by clicking the sample page link.

- `injectGlobal` with `@font-face` is on `src/components/App.js`;
- the font files are in `public/`.

## Expected Behavior
Render the page properly with the font.

## Actual Behavior
It's downloading the font again and making it transparent.
https://www.evernote.com/shard/s37/sh/ec9b3b65-83bd-4722-b53f-62664ba64649/236d8b945475f298/deep/0/

**Comment by mxstbr** [comment]
That's really weird. Not sure if this is a bug on our side though?

**Comment by diegohaz** [comment]
I'm also not sure. It might be something on Chrome or on my server side implementation. I want to see if other people with different ssr implementations have the same problem.

**Comment by geelen** [comment]
So I heard about weird shit with `style` tags and `@font-face`. Never seen it go transparent, but definitely double-download. I can't remember who was talking about it though, one of the other CSS-in-JS projects I think.

@mxstbr it occurs to me that we're _always_ generating more CSS on the client even when there's already styles there from SSR. I wonder if this problem is just that or something deeper...

**Comment by mxstbr** [comment]
> @mxstbr it occurs to me that we're always generating more CSS on the client even when there's already styles there from SSR. I wonder if this problem is just that or something deeper...

Yes, we're actually running into this problem with `react-boilerplate`! See [here](https://github.com/mxstbr/react-boilerplate/pull/1236) /cc @tomazy

**Comment by nicohartto** [comment]
Any workaround for this? Besides putting the font in <style> element in the head or something similar?

**Comment by diegohaz** [comment]
@nicohartto I'm currently using `<style>`. Are you also facing this bug (fonts going transparent)?

**Comment by diegohaz** [comment]
I tested it again with 1.4.1 and 1.4.2.

The problem persists on 1.4.1, but is solved on 1.4.2 (with adaptations mentioned in #423).
