### ISSUE TITLE
Conditional statement doesn't with props doesn't work in react-native !

### ISSUE THREAD

**Issue by hayanisaid** [styled-components/styled-components#2380]
## My code
```
const StyledButton=styled.TouchableHighlight`
 width:250px;
 background-color:${props=> props.primary? 'red': '#f3f8ff'};
 padding:15px;
border:${props => (props.primary)? "4px solid red ": 0}
 justify-content:center;
 margin-bottom:20px;

 border-radius:24px
`
export const Button=(props)=>{
  console.log('buutton props>>>>>>',props.primary)// true
  return(
    <StyledButton onPress={props.onPress} props>
     <StyledTitle>{props.title}</StyledTitle>
       </StyledButton>
   
  )
 
}
```
* It should change the background color to red !

## Environment

`
## System:
 - OS: macOS 10.14.2
 - CPU: (4) x64 Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz
 - Memory: 60.34 MB / 8.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 11.6.0 - /usr/local/bin/node
 - Yarn: 1.13.0 - /usr/local/bin/yarn
 - npm: 6.7.0 - ~/Desktop/ATM/RN/peleton/node_modules/.bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^4.1.3 => 4.1.3 `

**Comment by mxstbr** [comment]
You need to spread the props.

```JSX
<StyledButton onPress={props.onPress} {...props}>
```
