### ISSUE TITLE
Enable custom styling overrides of specific components in themes

### ISSUE THREAD

**Issue by ScottStevenson** [styled-components/styled-components#2381]
We'd love to see a mechanism that allows component styles to be completely overridden from a theme or theme-like level. 

MUI (built around JSS) enables this as follows:
```
const theme = createMuiTheme({
  overrides: {
    MuiButton: { // Name of the component ⚛️ / style sheet
      text: { // Name of the rule
        color: 'white', // Some CSS
      },
    },
  },
});
```

https://material-ui.com/customization/themes/#customizing-all-instances-of-a-component-type

Use case:
We're attempting to use styled-components for all of our styling, while also giving our customers control of the theme for white-labeling. The problem is that we can't parameterize every possible variation of our styles for them to input. We would like to provide some basic theme variables (like primaryColor, secondaryColor), but we'd also allow a more traditional complete override of our component styles.

Traditional white-labelling often just allowed a customer to specify their own higher precedence stylesheet. It is unclear how to best accomplish this level of customization with SC - although I may easily be missing something.

One obvious workaround is to specify classNames for each component and inject a stylesheet using some other method - but would love to avoid creating classNames and using two methods to manage styles.

**Comment by probablyup** [comment]
What is `ThemeProvider` not solving for you? https://www.styled-components.com/docs/api#themeprovider

**Comment by ScottStevenson** [comment]
I may be mistaken on this - but all of the examples of SC themeing I have seen rely on individual CSS attributes being made into theme parameters. What if someone wants to define a whole new custom style for a component (adding new attributes), from the theme level? This can be done in MUI/JSS.

Eg. Can something like this be done?
```
const Button = styled.button`
  { $props => props.theme.overrides.Button }
`
```

**Comment by ScottStevenson** [comment]
Ah - a helpful person on spectrum shared that you can do something exactly like this. Case closed? Would love to see an example of this somewhere in the documentation though.

https://spectrum.chat/styled-components/general/how-to-allow-arbitrary-overriding-of-component-styles-in-themes~dd419469-093d-4ab1-995e-1284322ddd25?m=MTU1MDA3OTgwMzE0Mw==

**Comment by probablyup** [comment]
Sounds like you found a solution, so going to close. If you'd like to help improve the docs, that's always welcome over at https://github.com/styled-components/styled-components-website
