### ISSUE TITLE
Dependency in @types/styled-components on @types/react-native causes issues with projects who depend on @types/node 

### ISSUE THREAD

**Issue by EdwardDrapkin** [styled-components/styled-components#2383]
@types/react-native should be a peerDependency not a dependency, ffs.

**Comment by probablyup** [comment]
We don't maintain the types, file against DefinitelyTyped.

**Comment by fabb** [comment]
Related issue: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33015
