### ISSUE TITLE
Error: Cannot create styled-component for component: [object Object].

### ISSUE THREAD

**Issue by aakhan89** [styled-components/styled-components#2384]
```
import styled from 'styled-components';

export const Badge = styled({
  fontSize: 0,
  px: 2,
  py: 1,
  mx: 1,
  color: 'white',
  bg: 'blue',
  fontWeight: 'bold',
  borderRadius: 2
}, {
  WebkitFontSmoothing: 'antialiased',
  display: 'inline-block',
  verticalAlign: 'middle'
})


export default Badge;
```

![image](https://user-images.githubusercontent.com/38126236/52766793-27812900-304a-11e9-9bef-8ef6f0ca17dd.png)

**Comment by probablyup** [comment]
That's not a valid syntax, should be something like:

```js
export const Badge = styled.div({
  fontSize: 0,
  px: 2,
  py: 1,
  mx: 1,
  color: 'white',
  bg: 'blue',
  fontWeight: 'bold',
  borderRadius: 2
}, {
  WebkitFontSmoothing: 'antialiased',
  display: 'inline-block',
  verticalAlign: 'middle'
})
```

**Comment by aakhan89** [comment]
> ```js
> export const Badge = styled.div({
>   fontSize: 0,
>   px: 2,
>   py: 1,
>   mx: 1,
>   color: 'white',
>   bg: 'blue',
>   fontWeight: 'bold',
>   borderRadius: 2
> }, {
>   WebkitFontSmoothing: 'antialiased',
>   display: 'inline-block',
>   verticalAlign: 'middle'
> })
> ```

Thank you for your reply @probablyup but I would like to share some different way too , but I followed yours :)

import styled from 'styled-components';

export const Badge = styled.a`
  background-color: blue;
  color: white;
  display: inline-block;
  position: relative;
  border-radius: 4px;
  padding: 4px 8px;
  transition: all 0.2s ease 0s;
  cursor: pointer;
  &:hover {
    background-color: green;
  }`

export default Badge;

**Comment by testacode** [comment]
Oh my god my eyes
