### ISSUE TITLE
styled-theming not working with TypeScript

### ISSUE THREAD

**Issue by borisyordanov** [styled-components/styled-components#2386]
## System:
 - OS: Windows 10
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 2.23 GB / 15.74 GB
## Binaries:
 - Node: 8.12.0 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.12.1 - C:\Users\by\AppData\Roaming\npm\yarn.CMD
 - npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

## package.json
    "@types/styled-theming": "^2.2.0",
    "styled-theming": "^2.2.0"

## Steps to reproduce
I tried to use the code from [the docs](https://github.com/styled-components/styled-theming#example):
```
import theme from 'styled-theming';
const backgroundColor = theme('mode', {
    light: '#fff',
    dark: '#000'
 });
```
## Expected Behavior
@jamiebuilds Sorry if this isn't the right place for this issue, but you don't have issue tracking set up at [the repo](https://github.com/styled-components/styled-theming)

## Actual Behavior
As soon as i added the `theme()` i got this type error:
```
styled_theming_1.default is not a function
TypeError: styled_theming_1.default is not a function
```

**Comment by probablyup** [comment]
As you said, this is not the same repo. I recommend reaching out via twitter since that seems to be where he's most active.

**Comment by borisyordanov** [comment]
@probablyup His twitter is suspended, so i messaged him on Linkedin. Looks like he's not active there. If you can, please reach out to him and refer him to this issue.

**Comment by probablyup** [comment]
Here’s the latest one: https://twitter.com/jamiebuild
