### ISSUE TITLE
Global styles best practices or accessing generated classNames from styled components

### ISSUE THREAD

**Issue by ChiefORZ** [styled-components/styled-components#2387]
## Prolog

We try to make `styled-components` work with other libraries which are responsible for the logic of an component, but not the styling.

For example [rc-dropdown](https://github.com/react-component/dropdown).
These are very useful, because they are not opinionated on styling - this is up to your application.

The problem is, that these **helper-libraries** append their own classes to their divs - for example `.rc-dropdown`, `.rc-dropdown-menu`, `.rc-dropdown-menu-item`.

So we tried many solutions to make this possible...

- creating a styled wrapper element

```js
const StyledDropdown = styled.div`
  .rc-dropdown {}
`;
```
> isn't working because it generates css with its own css class before. `.iGnaZ .rc-dropdown {}`
> and the **helper-libraries** need to target each other's classes `.rc-dropdown > .rc-menu {}`

- accessing the generated className from styled components

```js
import Dropdown from 'rc-dropdown'

const DropdownStyles = styled(Dropdown)``;

const StyledDropdown = () => (
  <DropdownStyles prefixCls={StyledDropdown.componentStyle.componentId} />
)
```
> isn't working because sometimes there are more than one class appended to the styles.
> i don't even know exactly whats happening here, but i think it has something to do with https://www.styled-components.com/docs/faqs#why-do-my-dom-nodes-have-two-classes

- appending the css to global with [createGlobalStyle](https://www.styled-components.com/docs/api#createglobalstyle)

this is where we stand and it actually working pretty fluently and was straight-forward.
but it has a minor flaw...

## Reproduction

https://codesandbox.io/s/jz4njw8855

in the simple example the component with the global styles is only rendered once and therefore works perfectly.
but in the stateful example, as soon as you change the value of the input a change in the state is triggered and therefore a refresh of the global style is triggered...

![](http://g.recordit.co/hPIzQXEktW.gif)

## Solutions

- While writing this issue i tried **memoizing** the `createGlobalStyle` so it will only be rendered once

```js
import React, { memo } from 'react';

const DropdownStyles = memo(createGlobalStyle`
  .own-dropdown {}
`);
```
> It seem to fix the refreshing of the generated css.
> But is this a viable way of doing it, or will this bring other risks of breaking other things?

- Should we consider memoizing / comparing the props (aka **shouldComponentUpdate**)

i dug in in the source code and saw that the global styles are always re-rendered, even though the props haven changed since the last render [here](https://github.com/styled-components/styled-components/blob/9b81695d35074974c42b943a82456c9ae4b42500/packages/styled-components/src/models/GlobalStyle.js#L42).
> could we create a way of comparing the new props to the latest, to prevent the unnecessary re-render.

- Do you have a more reliable solution for us, in the way **styled-components** is intended to be used?

Thanks for your help!

**Comment by probablyup** [comment]
A `styled()` wrapper around the component seems like the best solution, rather than `createGlobalStyle` for this use case.

> isn't working because it generates css with its own css class before. `.iGnaZ .rc-dropdown {}`
and the **helper-libraries** need to target each other's classes `.rc-dropdown > .rc-menu {}`

I'm not sure I really understand the issue? You can use normal CSS classNames with styled-components, s-c just autogenerates a className for any styles itself is responsible for.
