### ISSUE TITLE
React Native Invariant Violation Invalid Prop 'Color'

### ISSUE THREAD

**Issue by MrSparklle** [styled-components/styled-components#2388]
## System:
 - OS: macOS 10.14.3
 - CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
 - Memory: 24.50 MB / 8.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
 - Yarn: 1.13.0 - /usr/local/bin/yarn
 - npm: 6.8.0 - ~/.nvm/versions/node/v10.15.1/bin/npm
## npmPackages:
 - styled-components: ^4.1.4-alpha.5 => 4.1.4-alpha.5 

## Reproduction
**Button.js**
```
import React from 'react';
import styled from 'styled-components/native';
import PropTypes from 'prop-types';

const Button = ({ textColor, text, fontSize }) => (
  <ButtonText color={textColor} fontSize={fontSize}>
    {text}
  </ButtonText>
);

const ButtonText = styled.Text`
  color: ${props => props.textColor};
  font-size: ${props => props.fontSize};
`;

Button.propTypes = {
  textColor: PropTypes.string.isRequired,
  text: PropTypes.string.isRequired,
  fontSize: PropTypes.number.isRequired
};

export default Button;
```

**HomeScreen.js**
```
import React from 'react';
import { View } from 'react-native';
import Button from '../../components/shared/Button';

// import styles from './styles';

const HomeScreen = () => (
  <View>
    <Button textColor="#242424" text="This is a Styled Text" fontSize="20" />
  </View>
);

export default HomeScreen;
```
## Expected Behavior
The color property needs to be passed to component.

If I replace the prop.textColor by a fixed value, it works:
```
const ButtonText = styled.Text`
  color: mediumseagreen;
  font-size: ${props => props.fontSize};
`;
```

## Actual Behavior

![image](https://user-images.githubusercontent.com/992049/52892320-7e851c00-3178-11e9-9480-6e3bd3f29838.png)

**Comment by probablyup** [comment]
`<ButtonText>` takes a prop called `textColor`, not `color` in your example.

**Comment by Alaaeldin1993** [comment]
chick all your files where you have put colors and make sure your colors code are correct 
that is how i fixed mine
