### ISSUE TITLE
How to avoid re-rendering children when updating props in the Styled Component?

### ISSUE THREAD

**Issue by Steffi3rd** [styled-components/styled-components#2398]
Hi, 

Someone knows why updating props in a styled component, fire a `children` is re-rendered, even with `useMemo()`?

when I use ```<div windowheight={positionTop}>{children}</div>```
`children`  is not re-rendered

but when I use ```<Board windowheight={positionTop}>{children}</Board>``` 
`children` is rendered

I also tried this solution :
```const BoardWrapper = styled(({ windowHeight, ...props }) => <section {...props } />)```

It doesn't work, I think maybe because of the `useRef()`

How to fix this using styled component please?
https://codesandbox.io/s/81q2kmzkml

**Comment by probablyup** [comment]
When you change props and are using props in your styling, it will generate a new `className`. We then need to rerender the children with the new `className` so the styling is applied.

**Comment by snovos** [comment]
Is there any workaround?
