### ISSUE TITLE
Theme not passed to dependency

### ISSUE THREAD

**Issue by Gisleburt** [styled-components/styled-components#2399]
This is a bit of an odd one, I can't find anyone else having the same issue, so I'm sure it's a mistake on my end.

We've built several apps with a common "styleguide" module, which contains all of our shared reusable components. We're trying to shrink down the size of our build files by making the styleguide a UMD so that it can be loaded once, the same way in all of our applications. It's big, but then users only need to get it once.

If we use webpack dev server to simply serve up empty html with all of the js included (including the styleguide umd), it actually works perfectly. However, we're using Express to populate the html first, and when we try to do the same thing on the server side, it crashes because our `theme` object is empty. 

Weirdly this is only the case for components in the styleguide. If we look at components that are specifically part of the application, they have the correct theme.

Is there something obvious I've missed? I don't see anything in the Reacts Context API documentation about it not working acorss modules. Any feedback would be greatly appreciated.

**Comment by kitten** [comment]
Have you checked whether you're accidentally duplicating the styled-components dependency on the server?

As far as I know, React keeps some state on the context object itself, so in the new context API, duplicating a dependency with context can make it seem like it disappears in dependencies.

**Comment by Gisleburt** [comment]
Wow, I had commented out `styled-components` from the externals list in the library build. Putting it back fixed it.

Thank you!
