### ISSUE TITLE
flowtyped props, how?

### ISSUE THREAD

**Issue by steida** [styled-components/styled-components#240]
Is this right?

```jsx
/* @flow */
import React from 'react';
import styled from 'styled-components';

type Props = {
  bold?: bool,
};

const Text = styled.span`
  color: ${props => props.theme.colors.black};
  font-family: ${props => props.theme.fontFamily};
  font-size: ${props => props.theme.fontSize.text};
  font-weight: ${props => props.bold ? props.theme.fontWeight : 'normal'};
  line-height: ${props => props.theme.lineHeight};
`;

export default (props: Props) => <Text {...props} />;
```

**Comment by mxstbr** [comment]
That LGTM, I wonder if flow understands `propTypes`? /cc @ryyppy @relekang 

```JS
const Text = styled.span`
  color: ${props => props.theme.colors.black};
  font-family: ${props => props.theme.fontFamily};
  font-size: ${props => props.theme.fontSize.text};
  font-weight: ${props => props.bold ? props.theme.fontWeight : 'normal'};
  line-height: ${props => props.theme.lineHeight};
`;

Text.propTypes = {
  bold: React.PropTypes.bool,
}
```

**Comment by relekang** [comment]
> I wonder if flow understands propTypes?

It does. However, flowtype is more powerful than proptypes is. Especially when working with functions. There is a bit of info in the react part of flowtype docs. https://flowtype.org/docs/react.html#the-reactcreateclass-factory

**Comment by ryyppy** [comment]
@steida's example is not even a class (but a stateless function component), so yeah, flow can deal with that

**Comment by steida** [comment]
@mxstbr No, flow 0.33 for some reason can't understand proptypes, while flow types work.

**Comment by dbertella** [comment]
@steida your solution seems working fine, I'm wondering, do you know why you have to wrap the `styled-component` in a functional one to make it working with `flow`?
