### ISSUE TITLE
Inline SVG's can cause compilation error

### ISSUE THREAD

**Issue by antoniomiotto** [styled-components/styled-components#2400]
## Environment
```
## System:
 - OS: macOS 10.14.3
 - CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
 - Memory: 456.71 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 11.9.0 - ~/.nvm/versions/node/v11.9.0/bin/node
 - Yarn: 1.13.0 - /usr/local/bin/yarn
 - npm: 6.5.0 - ~/.nvm/versions/node/v11.9.0/bin/npm
 - Watchman: 4.7.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^4.1.3 => 4.1.3
```

## Reproduction

Look at the following [Code Sandbox link](https://codesandbox.io/s/4kj9r7plx). If you inspect the page you'll notice the rendered div with the class `test2` has no styles according to the chrome inspector.

It looks like it might be an issue with the escaping in the SVG, as removing one of them fixes it, as does base64 encoding the svg inline.

**Comment by probablyup** [comment]
There are some problems with your SVGs, namely the attributes don't have quotes so things like viewBox will be broken since there are unguarded spaces. The best practice for embedding svg is something like this:

```jsx
const svg = '<svg viewBox="0 0 10 10"><path /></svg>';

const Thing = styled.div`
  background-image: url("data:image/svg+xml;,${encodeURIComponent(svg)}");
`;
```
