### ISSUE TITLE
Question about multiple instances of styled-components

### ISSUE THREAD

**Issue by aaryn101** [styled-components/styled-components#2401]
Assuming that each instance of styled-components is at a different version >= 4.0, are there any known issues with having multiple instances active on a single page?

**Comment by probablyup** [comment]
Nope, should be fine since the stylesheets are effectively isolated by version 👍 

The only thing you might run into is specificity issues if components are being targeted by both versions using indirect selectors (e.g. `> *`, `div`, etc)
