### ISSUE TITLE
Tons of caught "Typeerror: chunk is not a constructor" in flatten() make debugging difficult

### ISSUE THREAD

**Issue by kheyse-oqton** [styled-components/styled-components#2402]
This bit of code uses a try catch, where an error being thrown seems to be the expected execution path in many cases.
https://github.com/styled-components/styled-components/blob/c3eedbeb79621acd668e15ed2d63107528ed81c3/packages/styled-components/src/utils/flatten.js#L61-L68

This may work as expected, but it makes debugging anything in chrome with "pause on caught exceptions" practically impossible.
(In my case, rendering a single component triggers this error multiple times.)

Can this be implemented without try catch? Or is there an easy way to avoid this error to be thrown?

**Comment by probablyup** [comment]
Can't unfortunately :/ there's no way to know if a function is a normal function or a SFC ahead of time
