### ISSUE TITLE
Failed to parse declaration fontFamily having multiple fonts

### ISSUE THREAD

**Issue by sirajulm** [styled-components/styled-components#2403]
I'm working on a project using `react-native-web` and `styled-components`, where i'd need to specify fallback fonts for web. I'm unable to add fallback fonts using `font-family`, only one font is supported at a time.

## Environment

 styled-components: 3.5.0-0
 react-native-web: ^0.8.x
 OS: macOS 10.14.2
  Node: 8.11.0
  Yarn: 1.10.1
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 3.3 AI-182.5107.16.33.5199772

## Steps to reproduce

This snippet works fine in ios, android and web: 
```
import styled from 'styled-components/primitives'

export const SomeText = styled(Text)`
    font-family: CustomFontFamily;
`
```
but adding fallback font especially to web doesnt work and throws the below error
```
export const SomeText = styled(Text)`
    font-family: CustomFontFamily, FallbackFamily;
`
```

Error:
```
Error: Failed to parse declaration "fontFamily: CustomFontFamily, FallbackFamily"
```

adding quotes around the family names doesnt also help.

even using the `Platform` as below doesnt work either
```
export const SomeText = styled(Text)`
    ${Platform.select({ web: css`font-family: CustomFontFamily, FallbackFamily` })};
`
```
## Expected Behavior
Multiple font families as fallback fonts should be supported for web.

## Actual Behavior
Only one font family can be applied at a time.

**Comment by sirajulm** [comment]
This seems to be working with `React` and `styled-components` but not with `react-native-web`.

**Comment by jpstrikesback** [comment]
I encountered this and worked around it by quoting the declaration:

```css
export const SomeText = styled(Text)`
    font-family: 'CustomFontFamily, FallbackFamily, Another FontFamily';
`
```

**Comment by sirajulcb** [comment]
@jpstrikesback This really works. Thank you :)
