### ISSUE TITLE
can i use `createGlobalStyle` in every component.

### ISSUE THREAD

**Issue by sumantaparida** [styled-components/styled-components#2406]
## createGlobalStyle
<-- Can i use `createGlobalStyle` if need component style -->

`import { createGlobalStyle } from 'styled-components';
  const global = createGlobalStyle`
    span {
        color: red 
    }`;
export { global };
`
<-- just like that -->

**Comment by ahtee** [comment]
https://www.styled-components.com/docs/api#createglobalstyle

**Comment by sumantaparida** [comment]
Yes, but local development are very slow,
Because of hot reload are enable in development "HRM" Issues.

**Comment by rradoychev** [comment]
Just make a variable which fills in the createGlobalStyle.
Then use the createGlobalStyle in only one place, but with imported styles from other ones.
