### ISSUE TITLE
Attrs get overidden by props

### ISSUE THREAD

**Issue by sarneeh** [styled-components/styled-components#2408]
## Environment
```
## System:
 - OS: Linux 4.15 Ubuntu 18.04.2 LTS (Bionic Beaver)
 - CPU: (8) x64 Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz
 - Memory: 5.02 GB / 15.61 GB
 - Container: Yes
 - Shell: 5.4.2 - /usr/bin/zsh
## Binaries:
 - Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
 - Yarn: 1.13.0 - /usr/bin/yarn
 - npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
## npmPackages:
 - babel-plugin-styled-components: 1.8.0 => 1.8.0 
 - styled-components: ^4.1.3 => 4.1.3
```

## Reproduction

https://codesandbox.io/s/ly8kn5y0qq

## Steps to reproduce

1. Create a `styled.button` with hardcoded `disabled: true` in `attrs`
2. Pass `disabled={false}` to the component

## Expected Behavior

`attrs` take precedence over incoming props, so I'd expect this example to work the same way.

## Actual Behavior

The `button` is not disabled.

**Comment by sarneeh** [comment]
Also the [.attrs example](https://www.styled-components.com/docs/basics#attaching-additional-props) in `styled-components` docs is not working (note that the inputs are not getting the `type` attribute).

**Comment by probablyup** [comment]
attrs do not take precedence over props, the resolution order is:

props > attrs > defaultProps

I just noticed that this isn't specifically mentioned in our docs though, so definitely open to a PR there!

**Comment by sarneeh** [comment]
@probablyup Wait a second, what? :smile: Recently I did a little bit of playing around with `attrs` to understand it properly and [noted my thoughts in one of the issues here](https://github.com/styled-components/styled-components-website/issues/56#issuecomment-459686917). @mxstbr actually confirmed that `attrs` takes precedence over `props`. And that's how it works... sometimes.

Take a look at this example:

```js
const A = styled.button.attrs({
  color: "red",
  disabled: true
})`
  color: ${props => props.color};
  :disabled {
    border: 2px solid red;
  }
`;
```

Now, when you pass `color="blue"` prop, the button will still have red text (attrs take precedence). But when you do `disabled={false}`, You won't get a red border (props take precedence).

Reproduction: https://codesandbox.io/s/716133j20j

This is really confusing :smile:

**Comment by psixdev** [comment]
I would like to fully understand how everything works. I am confused by this @mxstbr comment:

https://github.com/styled-components/styled-components/pull/2258#issuecomment-444782161
