### ISSUE TITLE
Interpolation functions are called twice

### ISSUE THREAD

**Issue by ackvf** [styled-components/styled-components#2409]
Interpolation functions are called twice for every render in current version `4.3.1`
While trying to reproduce, I cloned some existing example that, by chance, used an older version `2.1.0` that did not exhibit this behaviour.

### v2.1.0 _is not called twice_
![image](https://user-images.githubusercontent.com/2313018/53243376-ede29a80-36a7-11e9-9f7f-85e2357eaf78.png)

### v.4.3.1 _is called twice_
![image](https://user-images.githubusercontent.com/2313018/53243390-f8049900-36a7-11e9-89e9-ae4b71b2dab9.png)

## Steps to reproduce

https://codesandbox.io/s/v014z5jnll

Put a console.log inside css template.

    const Title = styled.article`
      ${() => console.debug("called")}
      ...

## Actual Behavior

The "called" will be called twice for every render.

## Expected Behavior

Expected is that it is only called once as in version 2.1.0.

**Comment by aczekajski** [comment]
While in codesandbox it is indeed called twice every time you click the button, the same code run in my dev environment behaves even stranger. On first render I get
```
= rendered =
inner
called
nested
```
on first button click I get
```
= rendered =
inner
called
nested
called
nested
```
and all consecutive clicks give only single "called" and "nested".

**Comment by probablyup** [comment]
This is going away with https://github.com/styled-components/styled-components/pull/2428, keep an eye out for 4.2.0 coming soon!
