### ISSUE TITLE
How to reset our components with sanitize

### ISSUE THREAD

**Issue by kopax** [styled-components/styled-components#241]
I am writing a `<Form />` component.

By looking at a form at here : http://getbootstrap.com/css/#basic-forms , I can see with my debugger that form has `user agent stylesheet` applied in Google Chrome Version 54.0.2840.100 (64-bit) linux.

![image](https://cloud.githubusercontent.com/assets/1866564/20552717/3fe2ff50-b180-11e6-8f18-da69baa5c8c4.png)

According to this answer : http://stackoverflow.com/questions/12582624/what-is-user-agent-stylesheet#answer-12582723

This is because we should reset the css for each browsers.

I am using react-boilerplate 3.3.3, I saw @mxstbr's video about scalling react js https://vimeo.com/168648012 

I thought for each component a css reset was applied with sanitize. 

So is this a manual step or is this automatic ?

Should I import `import 'sanitize.css/sanitize.css';` in every styled components I wan't to be reset ?

**Comment by mxstbr** [comment]
> Should I import import 'sanitize.css/sanitize.css'; in every styled components I wan't to be reset ?

No, just do this once for your entire application! (or put it into your HTML file with a `<link>`)
