### ISSUE TITLE
Pass props down nested Component.extend`..`

### ISSUE THREAD

**Issue by ScottAgirs** [styled-components/styled-components#2410]
**What will it allow you to do that you can't do today?**

Make chained styles taking advantage of props <StyledComponents /> in the following way:
Define conditional styles based on props passed in
- `<Parent />`
apply additional styles and pass down props to **Parent**, to apply conditional styles based on props on **Parent**
- `<ParentSquare />`

In styles.jsx:

```
const Parent = styled.button`
  width: ${props => props.small ? "32px" : "64px"}
`

const ParentSquare = extend.button`
  width: ${props => props.small && "32px" }
`
```

**Usage:**
`<ParentSquare small={true} />`

Currently - when `small` is passed as props, it will affect in `<ParentSquare />`, but not `<Parent />`, resulting in `<ParentSquare />`'s width being 32px, and `<Parent />`'s height being 64px.

**Comment by probablyup** [comment]
I think what you're asking for is achievable today:

```
const Parent = styled.button`
  width: ${props => props.small ? "32px" : "64px"}
`

const ParentSquare = styled(Parent)`
  width: ${props => props.small ? "32px" : '' };
`
```

Setting the rule in the override style to nothing means the previous style will take effect from Parent.

**Comment by ScottAgirs** [comment]
> I think what you're asking for is achievable today:
> 
> ```
> const Parent = styled.button`
>   width: ${props => props.small ? "32px" : "64px"}
> `
> 
> const ParentSquare = styled(Parent)`
>   width: ${props => props.small ? "32px" : '' };
> `
> ```
> Setting the rule in the override style to nothing means the previous style will take effect from Parent.

Sorry, looks like I've overlooked something, I had a quite feature-rich button component, the props didn't take affect at first, but after scratching all and starting fresh appears that I'm indeed able to achieve this.

Thank you for your answer @probablyup

**Comment by rexsohw** [comment]
Hi @ScottAgirs, may i know if you resolve the problem using probablyup suggested approach?

My situation is similar, I have a props-rich base component that has been wrapped with other styles.

`const StyledButton = styled(BaseButton)``
      styles: value;
      styles: value;
``
function myComponenet() {
  return (
     <StyledButton size={1} color={red}>My Button</StyledButton>
  )
}
`
the props `size` and `color` are not passed to the BaseButton as expected.

**Comment by sayjeyhi** [comment]
@probablyup how much levels of extend props go throw ?
