### ISSUE TITLE
React.createElement type is invalid

### ISSUE THREAD

**Issue by jasonlbw** [styled-components/styled-components#2416]
`
// Button component 
import styled from 'styled-components';

const Button =styled.button`
  background: #1FB6FF;
  border: none;
  border-radius: 2px;
  color: #FFFFFF;
  cursor: pointer;
  display: inline-block;
  font-size: 16px;
  line-height: 40px;
  font-weight: 200;
  margin: 8px 0;
  outline: none;
  padding: 0 12px;
  text-transform: uppercase;
  transition: all 300ms ease;
  &:hover {
    background: #009EEB;
  }
`;

export default Button;

// App.js
const App = ({ name }) => {
  return (
    <div>
      <h1>Hello, {name}!</h1>
      <Button>Click Me!</Button>
    </div>
  );
};

`
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `App`.

**Comment by ThakurKarthik** [comment]
Most of the times it is due to incorrect imports.Works fine here [Demo](https://codesandbox.io/s/4j1m88yk40?fontsize=14)

**Comment by probablyup** [comment]
Make sure your copy of `react-is` is up to date with your react version! Both should be >= 16.4
