### ISSUE TITLE
Is it possible to support multiple themes in a single app? 

### ISSUE THREAD

**Issue by mpkelly** [styled-components/styled-components#2417]
Hello, 

As the title says, I would like to know if there is a way to run multiple themes in a single app?

As a library developer I would like to make use of ThemeProvider to theme my component library. However, this will not work if the app that consumes the library is also running a ThemeProvider as the theme props will clash. The only workaround I know is to specify the correct theme on the library components but I am hoping there is another way. 

What I am hoping to do might look something like this:

```JavaScript
<ThemeProvider themes={{app: AppTheme, lib:LibTheme})>
...

const LibraryComponent = styled.div`
 color: ${props => props.themes.lib.accentColor};
`
```

Thanks
Mike

**Comment by Caryyon** [comment]
You can just put 2 ThemeProviders with a theme in each.

**Comment by mpkelly** [comment]
Hi @Caryyon  

I'm not sure how that would work. Which theme does App get? It can only get one as far as I can see. However, I would need to have two themes available. I think the solution would be to implement my own ThemeProvider which supports passing down a theme props to remain compatible but also passes down and a themes prop (as shown above) that can hold the library theme.

**Comment by Caryyon** [comment]
@mpkelly the app would get both themes on the `props.theme` object. The outer ThemeProvider theme object would be applied to the global theme object and then as the second ThemeProvider gets your library theme object and then apply that as well to the global theme object.

**Comment by luistak** [comment]
What if there are two different libraries with different `themeProvider`s? is there any way to differentiate them?

**Comment by Caryyon** [comment]
The providers are all written differently, but if both libraries where using stock styled-components ThemeProviders then this method would still work.
If you just want to merge JSON themes together you could just make a new object and spread the other JSON themes in the correct over-riding order? `{ ...themeOne, ...themeTwo }`
If you were to pass this to a ThemeProvider it wouldn't know the difference between the themes because they would be one happy object.

**Comment by adamkss** [comment]
Hi @mpkelly, I am in the same situation as you are at the moment. What solution did you go with in the end? Thanks!
