### ISSUE TITLE
Improve Typescript support for `as` property

### ISSUE THREAD

**Issue by nicgirault** [styled-components/styled-components#2419]
I'm struggling on the following use case:

I defined a link component:

```typescript
const Link = styled.a`
color: pink;
`
```

And for outbound links I use a custom component. Let say:

```typescript
const OutboundLink: React.FC<{to: string} & AnchorHTMLAttributes<HTMLAnchorElement>> = ({to, ...props}) => <a {...props} href={to} />
```

If I'm right, this is a typical use case of the prop `as` available in styled-components v4.
So when adding an outbound link, I write:

```typescript
const MyLink = () => <Link as={OutboundLink} to='https://www.styled-components.com/' />
```

But typescript raises an error: Property 'to' does not exist on type `IntrinsicAttributes & Pick<DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>>`.

For now I am dealing with this case like this:

```typescript
const SomeLink = styled(Link)<OutboundLinkProps>``
```

Do you have any recommendation on how to handle this use case? Or any plan to support this use case in the future?

Thanks for your help

**Comment by probablyup** [comment]
Please feel free to open this over at DefinitelyTyped, but we do not maintain the types here.

**Comment by clemgrim** [comment]
Your solution works if Link and OutboundLink share the same props.
You'll also lose the custom props needed by the initial component, ex:

```tsx
const Link = styled.a<{ color: string }>`
  color: ${props => props.color};
`

const SomeLink = styled(Link)<OutboundLinkProps>``

<SomeLink to="/" /> // -> error, color is missing
```

I use this to solve the issue (works with components and elements)

```tsx
export function GetComponentAs<T extends keyof JSX.IntrinsicElements | React.ComponentType<any>, P extends object>(
  component: StyledComponent<any, any, P>,
  as: T
) {
  return (component as any) as StyledComponent<T, any, P>;
}
```

usage

```tsx
const SomeLink = GetComponentAs(Link, OutboundLink)
```
