### ISSUE TITLE
Flatten function performance issue v4

### ISSUE THREAD

**Issue by mariel9999999** [styled-components/styled-components#2424]
Having recently tried to upgrade our styled-components from v3 to v4 in a relatively large react app - we've ran into a strange performance issue that seems to be tied to the flatten function. When commenting out this part of flatten, the issue seems to resolve:

https://github.com/styled-components/styled-components/blob/9b81695d35074974c42b943a82456c9ae4b42500/packages/styled-components/src/utils/flatten.js#L59-L72

Here are screenshots of performance snapshots run with chrome dev tools when performing the same action in our app on v3 vs. v4:

**v3**
![screen shot 2019-03-04 at 11 06 48 am](https://user-images.githubusercontent.com/45567051/53746279-da38f000-3e6e-11e9-9afb-3b043b33372f.png)

**v4**
![screen shot 2019-03-04 at 10 59 45 am](https://user-images.githubusercontent.com/45567051/53746293-df963a80-3e6e-11e9-9c2f-84061da69a8b.png)

Strangely, we have not been able to reproduce this in a clean slate react app.

## System:
 - OS: macOS High Sierra 10.13.6
 - CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
 - Memory: 2.29 GB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 8.14.0 - /usr/local/bin/node
 - Yarn: 1.13.0 - /usr/local/bin/yarn
 - npm: 6.5.0 - /usr/local/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.4.0 => 1.10.0
 - styled-components: ^4.1.3 => 4.1.3

## Reproduction

Unable to reproduce with a basic react app created via `create-react-app`. 

## Expected Behavior
Performance is as good if not better than v3.

## Actual Behavior
Performance is sluggish, significantly slower than v3.

**Comment by alansouzati** [comment]
I'm wanting to give a try and fix this. do you have a way to reproduce this outside your app? can you publish something that I can clone and try?

**Comment by probablyup** [comment]
You can trigger that code path by passing a non-styled component SFC into a style interpolation.

**Comment by alansouzati** [comment]
let my try to create something that reproduces it in codesandbox. I usually like to reproduce the problem first before trying to attack it.

**Comment by mariel9999999** [comment]
@alansouzati Unfortunately I've not been able to reproduce this outside our app. I'll keep you updated if I can reproduce / make any progress.

**Comment by alansouzati** [comment]
@mariel9999999 are you using the "component selector" [pattern](https://www.styled-components.com/docs/advanced#referring-to-other-components)?

```
const Icon = styled.svg`
  flex: none;
  transition: fill 0.25s;
  width: 48px;
  height: 48px;

  ${Link}:hover & {
    fill: rebeccapurple;
  }
`;
```

see the `Link`  component inside the Icon interpolation?

**Comment by mariel9999999** [comment]
@alansouzati Yes.

**Comment by alansouzati** [comment]
just as a test, if you remove it, does the problem go away too? I'm trying to debug what is going on but I'm pretty new to their source code.

**Comment by mariel9999999** [comment]
@alansouzati Nope. It is still laggy after removing all component selectors.

**Comment by aczekajski** [comment]
I couldn't pin-point my problems down to `flatten` function, but we're experiencing the same issue - after upgrading relatively big project to v4, it performs about two times slower than with v3.

**Comment by probablyup** [comment]
@mariel9999999 can you try `styled-components@4.1.4-alpha.6` (@alansouzati's fix) and let me know if it improves your graphs at all?

**Comment by mariel9999999** [comment]
@probablyup Yup that fixes it.

Here's what it looks like when performing the same action (left = `styled-components@4.1.4-alpha.6`  and right = `4.1.3`):
![screen shot 2019-03-05 at 1 29 34 pm](https://user-images.githubusercontent.com/45567051/53828137-d24e7e00-3f4a-11e9-886b-ee937385d3a2.png)

@alansouzati Thanks for fixing this!
