### ISSUE TITLE
Issues when creating a library from Styled-Components 

### ISSUE THREAD

**Issue by eugeneross** [styled-components/styled-components#2432]
## Environment

```
## System:
 - OS: macOS 10.14
 - CPU: (8) x64 Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz
 - Memory: 73.44 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 11.6.0 - /usr/local/bin/node
 - Yarn: 1.13.0 - /usr/local/bin/yarn
 - npm: 6.5.0 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
```

## Reproduction
1. Clone my library from the `issue` branch: [https://github.com/eugeneross/library/tree/issue](https://github.com/eugeneross/library/tree/issue) 
Run `yarn` to install dependencies.

2. Clone an app that uses Next.js (or use your own): [https://github.com/eugeneross/app](https://github.com/eugeneross/app)
Run `yarn` to install dependencies.

The library uses Styled-Components for styling of elements such as a Button found in `lib/elements/Button.js` which then is outputted in `build/elements/Button.js`. Styled-Components is defined in both `peerDependencies` and `devDependencies` as per the documentation. 

The app also uses Styled-Components for app-level styles defined in `dependencies`.

## Steps to reproduce

3. In the library's directory, use `yarn link` to enable linking.

4. In the app directory, use `yarn link numie-lib` to link the package you just enabled. (I called it numie-lib). Whatever name you chose, be sure it's the same as the one found in `pages/index.js`, for example: `import { Button } from 'numie-lib'`

5. In the library, run `yarn build:watch` to have code compiled and ready for hot-reload.

6. In the app, run `yarn dev`, then navigate to `localhost:3000`

7. While both projects are running, in the library, go ahead and change the background property of the button in `lib/elements/Button.js`. You should see the change reflected immediately in the browser.
 
8. Now, refresh the browser and you should notice the button loses its styles. Open up the console and you should see two things below. 

## Actual Behavior

What I see:

<img width="911" alt="screen shot 2019-03-05 at 5 30 22 pm" src="https://user-images.githubusercontent.com/174520/53842383-4bf76380-3f6d-11e9-97bf-e0dafb9ea9d0.png">

First off, In both the app and the library, I've included the styled-components babel plugin, and enabled `ssr: true` So I'm not sure why the first warning is happening. 

Secondly, I'm not wrapping my button using `styled()`, however, the `Button.js` file overwrites default `<a>` styles from the Bulma framework since it's an anchor tag... but I wouldn't think that would be conflicting. 

## Expected Behavior

There shouldn't be any errors as I'm just linking another directory. 

I've found a way around this issue but it's not ideal, as I should be able to just link a directory. If you're interested, the steps are below:

1. In `pages/index.js`, change the button import statement to `import { Button } from '@lib'`

2. Go to `babel.config.js` and swap out the alias I made for `@lib` and change it to the path wherever the library package is.

3. Restart both the library and the app

4. Change a property of the Button within the library and you should see it change.

5. Refresh the screen and open the console and you see no errors or warnings.

... I know this was a lot but this is a really interesting issue and I think it's worth addressing. Let me know if I need to be more clear in any of my steps.

**Comment by probablyup** [comment]
Yeah I see this using nextjs as well actually. The warning seems to be a red herring, the styling works as expected in my experience.

**Comment by eugeneross** [comment]
Do you think the issue is related to nextjs?

**Comment by probablyup** [comment]
I think it has to do with `react-loadable` that nextjs uses
