### ISSUE TITLE
Cannot pass "muted" prop to styled.video

### ISSUE THREAD

**Issue by eslachance** [styled-components/styled-components#2439]
## Environment
```
## System:
 - OS: Windows 10
 - CPU: (4) x64 Intel(R) Xeon(R) CPU E3-1225 v3 @ 3.20GHz
 - Memory: 3.13 GB / 15.94 GB
## Binaries:
 - Node: 10.14.1 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
 - npm: 6.8.0 - C:\Program Files\nodejs\npm.CMD
```
(Note: this seems to be reproducible on any system, as seen on repl.it, I've also reproduced on Ubuntu 18.04 with node 11 and react 16.8).

## Reproduction
Code: https://repl.it/@evie_codes/StyledComponentsVideoMuted
Output: https://styledcomponentsvideomuted--evie-codes.repl.co/

## Steps to reproduce
Create a styled-component `styled.video`
Add this component with the `muted` property.

## Expected Behavior
The `muted` prop is passed to the `<video>` tag in output.

## Actual Behavior
`muted` does not appear.
Both `autoPlay` and `loop` properties work perfectly well, only `muted` seems to disappear.
An attempt was made to set it up using `attrs()` but that did not produce any result (code for that is already in the repl).

**Comment by eslachance** [comment]
This might actually be a react bug: https://github.com/facebook/react/issues/10389  
Will wait for confirmation of a contrib here, however, to confirm whether or not styled-components can fix it in the lib itself (perhaps as a dirty temporary fix until react gets their stuff together)

**Comment by probablyup** [comment]
We just pass it along to the element and let React do it's thing, so I don't think there's anything for us to do here.
