### ISSUE TITLE
Merging themes more easily

### ISSUE THREAD

**Issue by wmertens** [styled-components/styled-components#244]
We've been experimenting with the themes, and one of the uses we think is very nice is the ability to have local themes for forms.

So given input components that have a label on the left or at the top, the theme could decide where it should go and you can just wrap the form in a themeprovider for the current layout.

```js
<ThemeProvider theme={topLabels}><MyForm/></ThemeProvider>
```

Taking this further, there could be tweaks to a specific form for tablet use, but not for all forms. Then we use another theme.

Now we have to merge those themes before we pass them on.

```js
<ThemeProvider theme={theme => merge({}, theme, topLabels(theme), tablet(theme))}>
  <MyForm/>
</ThemeProvider>
```

How about instead giving the theme provider an array of themes and a merge flag? E.g.

```js
<ThemeProvider theme={[topLabels, tablet]} merge/>
```

If `theme` gets an array, all its members get merged (after de-thunking). If the `merge` flag is set, the resulting theme is deep-merged with the outer theme.

**Comment by mxstbr** [comment]
So I don't think merging an array of themes would be a hard thing to implement. I definitely see the value in being able to do that!

I'm not sold on the `merge` prop though. We merge nested themes already:

```JSX
<ThemeProvider theme={topLabels}>
  <ThemeProvider theme={tablet}>
    {/* The two themes will be merged here */
  </ThemeProvider>
</ThemeProvider>
```

which essentially just does this:

```JS
{ ...topLabels, { ...tablet } }
```

Let's just merge arrays of themes the same way. That should be fine for the 95% use case, and if users do need to merge differently they can always do it themselves, something like `theme={deepMerge(topLabels, tablet)}`. That way our API surface stays small and useful whilst being flexible!

**Comment by wmertens** [comment]
Oh I didn't know about the merging. Isn't it counter intuitive to use simple merging? If you make a nice theme object with colors in a subobject, setting a different color removes all the others. I doubt that the performance impact of a deep merge will be noticeable?

**Comment by mxstbr** [comment]
I think it's more intuitive to be honest, just like `Pure.Component` in React does a shallow equal. I wouldn't expect that to do a deep merge.

**Comment by wmertens** [comment]
On Thu, Nov 24, 2016 at 3:09 PM Max Stoiber <notifications@github.com>
wrote:

> I think it's more intuitive to be honest, just like Pure.Component in
> React does a shallow equal. I wouldn't expect that to do a deep merge.
>

I beg to differ :) A theme is like a configuration, which means that there
should be a value for everything that expects a value. If you group similar
definitions together (colors, sizes, urls…) and you want to override a
single value, it seems logical to only have to "configure" that single
value => deep merge for objects.

For arrays though, imho they would be singular values to be replaced whole.

**Comment by mxstbr** [comment]
Yeah alright, I can see that. Let's add support for this then!

**Comment by A-gambit** [comment]
Is it still help wanted? Or somebody has just tried to resolve this issue? If it doesn't, can I try to help?

**Comment by wmertens** [comment]
@A-gambit I haven't had time to make a nice PR with tests, but this is basically what I would like the merging function to do:

```js
const merge = (old, cur) => {
	const res = {...old}
	for (const key of Object.keys(cur)) {
		const val = cur[key]
		if (
			res[key] == null ||
			typeof val !== 'object' ||
			typeof res[key] !== 'object' ||
			Array.isArray(val)
		) {
			res[key] = val
		} else {
			res[key] = merge(res[key], val)
		}
	}
	return res
}

export const mergeThemes = (...themes) => parent => {
	for (const theme of themes) {
		parent = merge(parent, theme)
	}
	return parent
}
```

Relies on Array.isArray, not sure about support for that one either.

So if you can build on this (or your own of course), that would be great! If not, I'll get to it eventually.

**Comment by k15a** [comment]
Array.isArray is ES5.1 and is supported pretty good.

**Comment by wmertens** [comment]
hmmm that's not good enough, so we need a polyfill, or we should recommend
one and make the test optional, or even ignore the array case altogether. I
can't think of a good use case for arrays in the theme anyway.

**Comment by mxstbr** [comment]
We can just use lodash's `isArray` which works just as well?

**Comment by wmertens** [comment]
That's great too :)

**Comment by wmertens** [comment]
Actually, in the mean time we changed how we use themes, and we don't really need deep merges any more. Since deep merges are more resource intensive, it might be better to not have them be the default.

This is the solution we have now:

```js
import {ThemeProvider as ThemeProviderBase} from 'styled-components'

export const mergeThemes = (...themes) => parent => {
	for (const theme of themes) {
		parent = merge(parent, theme)
	}
	return parent
}

const ThemeProvider = ({themes, theme, children}) => {
	const mergedTheme = themes ? mergeThemes(...themes, theme) : theme
	return <ThemeProviderBase theme={mergedTheme}>{children}</ThemeProviderBase>
}
ThemeProvider.propTypes = {
	themes: PropTypes.arrayOf(PropTypes.object),
	theme: PropTypes.object,
	children: PropTypes.any,
}
export default ThemeProvider
```

So with this `ThemeProvider`, you can pass an array of `themes` (or a single one) and they will get deep merged.

Maybe I'm over-optimizing here.

**Comment by probablyup** [comment]
I think the function variant of the theme prop should be sufficient to implement whatever type of merging you want!

```jsx
<ThemeProvider theme={() => mergeThemes([theme1, theme2])}>
  {stuff}
</ThemeProvider>
```
