### ISSUE TITLE
[FEATURE REQUEST] Memoize flatten

### ISSUE THREAD

**Issue by alansouzati** [styled-components/styled-components#2440]
For context, I've observed that throughout my app I have very repetitive constructs, and I never use children to style my components. So, imagine this structure:

```
const Box = styled.div`...`;
const Text = styled.span`...`;

// for example, I never do:
const Test = styled.span`
  ${props => props.children && '...'}
`;

<Box>
  <Box>
      <h1>VM1</h1>
  </Box>
  <Text>online</Text>
</Box>
```
I've noticed that `flatten` function is called a LOT of times. Most of times the function returns the same styles. So, that got me thinking, I must be able to memoize [this](https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/models/ComponentStyle.js#L58).

The problem is that if I memoize based on `executionContext` children will be there and it is always different.

Initially I thought that this logic would be outside styled-components, possible a custom styled function. But based on #2436, it seems there is space for this inside styled-components core.

This issue has been created to brainstorm about possible solutions to this.

**Comment by mxstbr** [comment]
As I said in #2436, in two years (or however long its been) I have never seen anybody adjust the styling based on children, and I have seen _a lot_ of styled-components. If that is the only hangup, it should certainly be possible to cache and/or memoize the result of `flatten`.

What exact approach are you thinking, and can you demonstrate the perf impact by publishing a fork under your name? That would be awesome :pray:

**Comment by alansouzati** [comment]
sure let me work on that today.

**Comment by probablyup** [comment]
Do we still want to memoize flatten or are the changes from #2428 enough?

**Comment by probablyup** [comment]
Closing since there hasn't been any action on this since 4.2
