### ISSUE TITLE
Minor tweaks in reusable styled-components

### ISSUE THREAD

**Issue by l-easwar-akiyama** [styled-components/styled-components#2441]
I've started using `styled-components` in one of my projects. I wanted to know the **recommended** way to override/extend them in the containers that use it. I had read a previously tracked [issue][2] but could not come to a solution.

Eg:

A reusable `Button` component :

    const Button = styled.button`
      background: transparent;
      border-radius: 3px;
      border: 2px solid red;
      color: red;
    `;

Now suppose I am using this in a flexbox, but need to right align. I can do this in a couple of ways:

**Extend:**

    const NewButton = styled(Button)`
      margin-left: auto;
    `;
**Inline Style:**

    <Button style={{marginLeft: 'auto'}}>Normal Button</Button>

Extend looks like the best way to go if there are more than 3,4 rules to override. 

But say for a single rule like `margin`, `padding`,`display: none` or basically any other similar layouting rules which may occur very frequently, creating a new wrapper each time adds to a lot of boilerplate. Inline styles work well on that aspect, but they have their own [pitfalls][1].

What is the optimal approach that can scale well across large apps ? 

  [1]: https://stackoverflow.com/questions/12013532/inline-style-tags-vs-inline-css-properties
  [2]: https://github.com/styled-components/styled-components/issues/1554

**Comment by probablyup** [comment]
Using another `styled()` wrapper is just fine. If you're using the babel plugin, you can also make use of the `css` prop which does the same thing under the hood 😃 https://www.styled-components.com/docs/api#css-prop
