### ISSUE TITLE
FOUC when using SSR with styled-components-based library

### ISSUE THREAD

**Issue by rogerhutchings** [styled-components/styled-components#2442]
I'm experiencing FOUCs when trying to SSR a component library using styled-components. I initially thought this was an issue with Grommet, but after building a test library just with SC I'm seeing the same issue.

Both SC and Grommet are working fine when consumed directly by the app.

## Environment

```
## System:
 - OS: macOS 10.14.3
 - CPU: (4) x64 Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz
 - Memory: 1.48 GB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
 - Yarn: 1.13.0 - /usr/local/bin/yarn
 - npm: 6.9.0 - ~/.nvm/versions/node/v10.15.1/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: ^1.10.0 => 1.10.0
 - styled-components: ^4.1.3 => 4.1.3
```

## Reproduction

Minimal repro: https://github.com/rogerhutchings/fouc-example

## Steps to reproduce

1. Clone the repo
1. `npm install`
1. `npm run build`
1. `npm run start`
1. Open `http://localhost:3000/`

## Expected Behavior

Styles for `foo` and `bar` should be rendered on the server (add red and blue backgrounds respectively)

## Actual Behavior

Styles for `foo` and `bar` aren't collected on the server, so they're loaded on the client and result in a FOUC.

Possibly related - #1860, but basic SSR with styled components is working fine, and I'm not using global styles here.

**Comment by rogerhutchings** [comment]
Ah - this is actually a dupe of #2322

**Comment by vongohren** [comment]
@rogerhutchings Hi! Did this duplicated issue solve things for you?
How did you solve it because you were doing workspaces, which hoits packages, the package is basically shared anyway.

Did you find any smart thoughts around that anywhere?
