### ISSUE TITLE
Github release version 4.1.2 - NPM version 4.1.3

### ISSUE THREAD

**Issue by mrowe009** [styled-components/styled-components#2447]
On the NPM registry, the latest styled-components tag is 4.1.3, but Github only has 4.1.2 as the latest release

**Comment by ahtee** [comment]
Looks like it was skipped by mistake. the version not yet released is 4.1.4 which is in alpha.

**Comment by probablyup** [comment]
Thanks! https://github.com/styled-components/styled-components/releases/tag/v4.1.3
