### ISSUE TITLE
Styled Components not passing props when using `as` prop

### ISSUE THREAD

**Issue by whoisryosuke** [styled-components/styled-components#2449]
Having an issue where I can't pass props from a Styled Component to the component it's wrapping when I use the `as` prop. 

Not sure if this has been addressed before (gets hard to search for with all the vague-ish keywords).

### System:
 - OS: macOS High Sierra 10.13.6
 - CPU: (4) x64 Intel(R) Core(TM) i5-2400S CPU @ 2.50GHz
 - Memory: 81.78 MB / 12.00 GB
 - Shell: 3.2.57 - /bin/bash
### Binaries:
 - Node: 9.8.0 - /usr/local/bin/node
 - npm: 6.4.0 - /usr/local/bin/npm
### npmPackages:
 - styled-components: ^4.1.3 => 4.1.3 

## Reproduction

CodeSandbox: https://codesandbox.io/s/ym1qzo2vn1

In my example I do my own implementation of the `as` prop (into a `<Tag>` component) -- but if you just remove the `<Tag>` and make it a `<div>` it still doesn't work.

The only time the props work is if I remove the `as` prop from the Styled Component used in the app.

## Steps to reproduce

1. Make a React component that uses Styled `as` prop and "custom" props (like `dropHeader`).

```js
import React from "react";
import styled from "styled-components";

class Dropdown extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      open: false
    };
  }
  toggleDropdown = e => {
    console.log("toggling dropdown");
    const open = !this.state.open;
    this.setState({ ...this.state, open });
  };
  render() {
    const { as: Tag, className, children, dropHeader } = this.props;
    console.log(this.props);
    console.log("dropdown rendering");
    // comment
    return (
      <Tag className={className}>
        <h2 onClick={this.toggleDropdown}>{dropHeader}</h2>
        {this.state.open && children}
      </Tag>
    );
  }
}

Dropdown.defaultProps = {
  as: "nav"
};
```

2. Wrap the component in Styled.

```js
const StyledDropdown = styled(Dropdown)`
  color: red;
`;

export default StyledDropdown;
```

3. Use the component:

```js
        <Dropdown as="li" dropHeader="Dashboard">
          <ul>
            <li>Analytics</li>
            <li>E-Commerce</li>
          </ul>
        </Dropdown>
```

4. Try accessing the custom props in the original, wrapped component:

```js
// ...<Dropdown> React.Component
  render() {
    const { as: Tag, className, children, dropHeader } = this.props;
    console.log(this.props);
    console.log("dropdown rendering");
    // can't grab props, doesn't even run console logs here
```

## Expected Behavior

* Passes props
* Runs any functions in render.

## Actual Behavior

* Doesn't pass props.
* Doesn't run any console logs in the original component.

**Comment by probablyup** [comment]
I'd rename the `as` prop inside `Dropdown` to something else like `$as` to get around this, as the `styled()` wrapper also accepts `as` and since in your example `styled(Dropdown)` is wrapping a custom component, the whole underlying component is swapped out in favor of rendering a simple `li` tag. We're working on a couple different strategies to mitigate this in the future, just an edge case to be aware of for now.

**Comment by adam-s** [comment]
It is a little inconvenient however following @probablyup 's comment I made it work and using the spread operator simplified it. Here is a working example.

````
import React from 'react';
import styled from 'styled-components';
import {
  Dropdown,
  Image,
  Menu,
} from 'semantic-ui-react'

const StyledHeader = styled.div`
  height: ${({ theme }) => theme.headerHeight};
  width: 100%;
  background: blue;
  position: fixed;
  z-index: 1000;
`;

const StyledMenu = styled(Menu)`
  &&& {
    height: ${({ theme }) => theme.headerHeight};
    background: transparent;
  }
`;

const MenuItem = ({ $as, ...rest}) => {
  return <Menu.Item as={$as} {...rest}/>
};

const StyledAnimatedMenuItem = styled(MenuItem)`
  &&& {
    width: ${({ theme }) => theme.sidebarWidth};
  }
`;

const DashboardHeader = () => {
  return (
    <StyledHeader>
      <StyledMenu fixed='top' inverted>

        <StyledAnimatedMenuItem $as='a' header>
          <Image size='mini' src='/logo.png' style={{ marginRight: '1.5em' }} />
          Project Name
        </StyledAnimatedMenuItem>

        <Menu.Item as='a'>Home</Menu.Item>
        <Dropdown item simple text='Dropdown'>
          <Dropdown.Menu>
            <Dropdown.Item>List Item</Dropdown.Item>
            <Dropdown.Item>List Item</Dropdown.Item>
            <Dropdown.Divider />
            <Dropdown.Header>Header Item</Dropdown.Header>
            <Dropdown.Item>
              <i className='dropdown icon' />
              <span className='text'>Submenu</span>
              <Dropdown.Menu>
                <Dropdown.Item>List Item</Dropdown.Item>
                <Dropdown.Item>List Item</Dropdown.Item>
              </Dropdown.Menu>
            </Dropdown.Item>
            <Dropdown.Item>List Item</Dropdown.Item>
          </Dropdown.Menu>
        </Dropdown>
      </StyledMenu>
    </StyledHeader>
  )
};

export default DashboardHeader;
````
