### ISSUE TITLE
issue with duplicate props in styled components

### ISSUE THREAD

**Issue by sjc5182** [styled-components/styled-components#2451]
Here is the code:

import React from 'react';
import styled from 'styled-components';

const StyledTest = styled.div${(props) => props.TestVar ? console.log("hi") : console.log("bye")};;
class App extends React.Component {
render() {
return (

);
}
}
export default App;

So the issue is my console always display "hi" twice, I just created a new react app just to test this issue, can someone explain to me why, as my original code requires passing specific props, now I can't make it work because everything is displaying twice.

**Comment by sjc5182** [comment]
inside of return is 
StyledTest TestVar={true}

**Comment by probablyup** [comment]
Sorry but this issue isn't actionable. Feel free to make a new one and use our issue template to supply a codesandbox with a working reproduction thanks!
