### ISSUE TITLE
Styled-components v3 - CSS Grid not autoprefixed

### ISSUE THREAD

**Issue by rradoychev** [styled-components/styled-components#2455]
## System:
 - OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
 - CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
 - Memory: 5.07 GB / 15.62 GB
 - Container: Yes
 - Shell: 4.4.19 - /bin/bash
## Binaries:
 - Node: 8.4.0 - /usr/local/bin/node
 - Yarn: 1.13.0 - /usr/bin/yarn
 - npm: 5.3.0 - /usr/local/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.8.0 => 1.9.1 
 - styled-components: ^3.4.10 => 3.4.10

## Reproduction
Add css-grid properties in a styled component.

## Expected Behavior
Add -ms- prefixes.

## Actual Behavior
No prefixes at all.

**Comment by probablyup** [comment]
See https://github.com/thysultan/stylis.js/issues/119

**Comment by mjmonline** [comment]
@probablyup forwarding the problem to Stylis is not a solution. What if they never solve this? Not being able to support CSS Grid is a deal breaker
