### ISSUE TITLE
Cannot override iOSUIKIT React Native with Styled-Component

### ISSUE THREAD

**Issue by Steffi3rd** [styled-components/styled-components#2457]
I would like to override color of iOSUIKIT. So I have this : 

```
import { iOSUIKit } from 'react-native-typography';
``` 

```
const TitleList = styled(Text)`
    color: red;
    text-transform: uppercase;
`;
```

```
<TitleList style={iOSUIKit.footnoteEmphasized}>Profil</TitleList>
```

This text is black and stays black instead red :/
But `text-transform` works fine.

**Comment by probablyup** [comment]
They might just not allow this customization :/ not all RN components are style-able unfortunately
