### ISSUE TITLE
Cannot use local variables in template functions

### ISSUE THREAD

**Issue by fabb** [styled-components/styled-components#2460]
I'd like to use both values from my theme, and local variables in a template literal function:

```
const MyComponent = ({special}) => {
    return <div
        css={css`
            color: ${p => special ? p.theme.color.special : p.theme.color.defaultText};
        `}
    >
        Am I special?
    </div>
}
```

This compiles fine but throws an error at runtime: `ReferenceError: special is not defined`.

When I modify the template literal function to this, it would work:

```
const MyComponent = ({special}) => {
    return <div
        css={css`
            color: ${special ? '#123456' : 'black'};
        `}
    >
        Am I special?
    </div>
}
```

But I'd like to use the color from the theme, without an `withTheme` HOC workaround.

**Comment by probablyup** [comment]
The `css` prop gets hoisted to a different scope, so it wouldn't be available. You could pass `special` as a prop to the `<div>` with the `css` prop on it though.

**Comment by fabb** [comment]
Hm, but why does it work in the second case then?

It is very unfortunate that this compiles fine with TypeScript, but produces a runtime error. I guess TypeScript cannot know that babel will transform the css prop in a way that makes surrounding variables unavailable. Meh.

When I want to pass `special` as a prop to the div I guess I either need to write a TypeScript interface, or use `attrs`.

**Comment by fabb** [comment]
> You could pass special as a prop to the <div> with the css prop on it though.

Nope, the typings of `cssprop.d.ts` do not make the `<div>` props available in template functions:

```
declare module "react" {
  interface Attributes {
      // NOTE: unlike the plain javascript version, it is not possible to get access
      // to the element's own attributes inside function interpolations.
      // Only theme will be accessible, and only with the DefaultTheme due to the global
      // nature of this declaration.
      // If you are writing this inline you already have access to all the attributes anyway,
      // no need for the extra indirection.
      /**
       * If present, this React element will be converted by
       * `babel-plugin-styled-components` into a styled component
       * with the given css as its styles.
       */
      css?: CSSProp;
  }
}
```

Looks like the comment `you already have access to all the attributes anyway` is wrong, at least in the case of template functions that also need to access the theme.

**Comment by fabb** [comment]
Since we cannot pass random props to `<div>` when using Typescript, these are the only solutions I found:

1.
```
const MyComponent = ({special}) => (
   <StyledSpecialContainer special={special}>
        Am I special?
    </StyledSpecialContainer>
)

interface SpecialContainerProps {
    special: boolean
    children: React.ReactNode
    className?: string
}

const SpecialContainer = (props: SpecialContainerProps) => <div className={props.className}>{props.children}</div>

const StyledSpecialContainer = styled(UpsellingGroupContainer)`
    color: ${p => p.special ? p.theme.color.special : p.theme.color.defaultText};
`
```

2.
```
const MyComponent = ({special}) => (
   <SpecialContainer special={special}>
        Am I special?
    </SpecialContainer>
)

interface SpecialContainerProps {
    special: boolean
    children: React.ReactNode
}

const SpecialContainer = styled.div<SpecialContainerProps>`
    color: ${p => p.special ? p.theme.color.special : p.theme.color.defaultText};
`
```

Neither makes me happy, but there seems to be no way using the `css` prop in TypeScript.

**Comment by fabb** [comment]
@probablyup maybe this could be resolved by making the `css` template function take parameters?

Something like this:
```
const MyComponent = ({special}) => {
    return <div
        css={css({special})`
            color: ${p => p.special ? p.theme.color.special : p.theme.color.defaultText};
        `}
    >
        Am I special?
    </div>
}
```

**Comment by fabb** [comment]
I experimented a little (with just js, leaving away the typing problems from TypeScript for now), and all of these cases do not work:
```
const NotWorking1 = ({special, children}) => (
  <div css={css`color: ${p => special ? 'red' : 'blue'};`}>{children}</div>
)

const NotWorkingt2 = ({special, children}) => (
  <div css={css`color: ${p => p.special ? 'red' : 'blue'};`}>{children}</div>
)

const NotWorking3 = ({special, children}) => (
  <div specialInner={special} css={css`color: ${p => p.specialInner ? 'red' : 'blue'};`}>{children}</div>
)

const NotWorking4Style = (props) => css`color: ${p => props.special ? 'red' : 'blue'};`
const NotWorking4 = ({special, children}) => (
  <div css={css`${NotWorking4Style}`}>{children}</div>
)
```

Only these worked (as described in previous comments):
```
const UnstyledWorking1 = ({special, className, children}) => (<div className={className}>{children}</div>)
const Working1 = styled(UnstyledWorking1)`
  color: ${p => p.special ? 'red' : 'blue'};
`

const WorkingButNoThemeAccess2 = ({special, children}) => (
  <div css={css`color: ${special ? 'red' : 'blue'};`}>{children}</div>
)
```

I tried to understand the hoisting more, and looked at the compiled code.
In case of `WorkingButNoThemeAccess2`, compiled code looks like this:
```
V = function(e) {
    var t = e.special,
        r = e.children
    return H(
        'div',
        { css: E('color:', t ? 'red' : 'blue', ';') },
        r
    )
}
```
Without knowing React details, I guess on every render, `V` is executed anew, and therefore `t` (=`special`) in `css` can use the most recent value.

In case of `NotWorking1`:
```
G = function(e) {
    var t = e.special,
        r = e.children
    return H(
        'div',
        {
            css: E(
                'color:',
                function(e) {
                    return t ? 'red' : 'blue'
                },
                ';'
            ),
        },
        r
    )
}
```
The template function is converted into a function which takes `e`, which contains the props. I do not really understand why `t` cannot be resolved in that case, because it correctly references the `t` defined at the top of the function body of `G`.

When I execute the above examples in emotion, I get the following error message in console:

```
Functions that are interpolated in css calls will be stringified.
If you want to have a css call based on props, create a function that returns a css call like this
let dynamicStyle = (props) => css`color: ${props.color}`
It can be called directly with props or interpolated in a styled call like this
let SomeComponent = styled('div')`${dynamicStyle}`
```
I found the source of the error message here:
https://github.com/emotion-js/emotion/blob/master/packages/serialize/src/index.js#L189

What I wonder is how/why the stringification of the css function that references `t` does not stringify the **resolved value** of `t`. Shouldn't js replace `t` with the current value even before functions `E` or `H` are called? At runtime the text is neither red nor blue, so I guess the inner function throws.

@probablyup I'm really sorry to bother you, but could you explain to me why stringification of the css function behaves that way? Or point me in the right direction? I'd really like to find better workarounds.
