### ISSUE TITLE
Rendering a styled input will cause the Component to unmount / delete the node on every letter I type in.

### ISSUE THREAD

**Issue by SelfDevTV** [styled-components/styled-components#2461]
Hi guys,

so I stumbled upon an issue in my trello clone application. I have this code (part of it):

```
const StyledInput = styled.input`
    width: 100%;
    border: none;
    outline-color: blue;
    border-radius: 3px;
    margin-bottom: 3px;
    padding: 5px;
  `;
const renderEditInput = () => {
    return (
      <StyledInput 
        type="text"
        value={listTitle}
        onChange={handleChange}
        autoFocus
        onFocus={handleFocus}
        onBlur={handleFinishEditing}
      />
    );
  };

```

When I render it and I toggle the edit mode of the input the text is focused and also  selected (like it should be). But as soon as I start typing, it only shows one letter in and it also reselects this letter. 

I did a bit of debugging and I saw that on every letter I type in the component unmounts and deletes the whole node in the dom tree. So ofc it always reFocuses and reSelects the letter. 

On hours of research I tried out to just render a normal input (not a styled one). And see there, everything works as intended. The component won't unmount and works like expected. 

Now I also now why my other textareas and input field where so slow when you hold a key and type in a letter (it was laggy). Because everytime it remounts everything. 

You can see it very clearly here (very minimum example where you can see the problem): https://codesandbox.io/s/4w546k8n6x

Is this a bug or am I doing something wrong?

**Comment by SelfDevTV** [comment]
When I create the Styled Input outside of the component it will work. Is this related to this part of the docs: https://www.styled-components.com/docs/basics#coming-from-css

"Define Styled Components outside of the render method". But technically it's not in the render method? Or is it because a stateless functional component is indeed a render method?

**Comment by diondiondion** [comment]
> Or is it because a stateless functional component is indeed a render method?

Exactly.

**Comment by probablyup** [comment]
@diondiondion is correct, the entire body of a SFC is essentially a render() function. Make sure you write your styled-components in a static scope, ideally in the top level of your file to avoid these issues.
