### ISSUE TITLE
Theme fallback using defaultProps does not work

### ISSUE THREAD

**Issue by ikhudo** [styled-components/styled-components#2464]
I'm no sure its a bug or i'm doing it wrong... 🤔 

I have a component lib than can be used in project with ThemeProvide and without it, so I need to fallback theme in my lib to some default theme.
Used the theme prop in defaultProps but it seem to not work properly 😕 

the code example https://codesandbox.io/embed/ql495xr7jj

**Comment by probablyup** [comment]
`MyLibComponent` is underneath the `styled()` layer and like other HOC libraries we do not hoist React-specific statics. If you move the `defaultProps` assignment to `Text`, it works as expected.
