### ISSUE TITLE
Functions inside of style objects, using multiple selectors

### ISSUE THREAD

**Issue by ryaninvents** [styled-components/styled-components#2468]
## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`
> ### System:
>  - OS: macOS High Sierra 10.13.6
>  - CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
>  - Memory: 86.22 MB / 16.00 GB
>  - Shell: 5.6 - /usr/local/bin/zsh
> ### Binaries:
>  - Node: 10.15.0 - /usr/local/bin/node
>  - Yarn: 1.5.1 - ~/.local/share/npm/bin/yarn
>  - npm: 6.8.0 - ~/.local/share/npm/bin/npm
>  - Watchman: 4.9.0 - /usr/local/bin/watchman

## Reproduction

See [CodeSandbox][repro]

[repro]: https://codesandbox.io/s/817wl8l08l

## Steps to reproduce

- Create an object style using comma-separated tags, and a property implemented as a function. See `BrokenStyle`, below:

```js
const WorkingStyle = createGlobalStyle`
  h1, h2, h3, h4, h5, h6 {
    font-family: ${({theme}) => theme.fonts.heading};
  }
`;

const BrokenStyle = createGlobalStyle({
  'h1, h2, h3, h4, h5, h6': {
    fontFamily: ({theme}) => theme.fonts.heading,
  },
});
```

## Expected Behavior

- The two implementations `WorkingStyle` and `BrokenStyle` are equivalent.

## Actual Behavior

- When using `BrokenStyle`, it seems as though `styled-components` stringifies my function and subsequently attempts to parse that as CSS. This new syntax is _amazing_, but not quite what I was expecting. Check out the output from the [above CodeSandbox][repro] (newlines added for clarity here):

```
h1 font-family:function fontFamily(_ref2),
h2 font-family:function fontFamily(_ref2),
h3 font-family:function fontFamily(_ref2),
h4 font-family:function fontFamily(_ref2),
h5 font-family:function fontFamily(_ref2),
h6 font-family:function fontFamily(_ref2){
  -webkit-var:theme = _ref2.theme;
  -moz-var:theme = _ref2.theme;
  -ms-var:theme = _ref2.theme;
  var:theme = _ref2.theme;
  return:theme.fonts.heading;
}
```

## Submitter note

If you'd like help with a fix, I'd love to tackle it; this is right up my alley. I'm not looking to enable my use case _per se_, I'd just like to prevent the next person from going through the same 20 minutes I did 😄 

I could see this being resolved in a few ways:

- Update `styled-components` so my sample works as I had expected
- Add a small note to the docs: "don't do this!" (Check out the implementation of `WorkaroundStyle` [in the CodeSandbox][repro]; technically this performs better, but there's no impact anyways since it usually runs once at page load time.)
- Implement a warning or safeguard to prevent this edge case (probably with an accompanying docs note)
- Something else?

**Comment by probablyup** [comment]
Oh hmm, maybe we don't have object styles set up for cGS. @imbhargav5?

**Comment by d7my11** [comment]
This happens with `styled({...})` as well

```
const BrokenStyle = styled.div({
  'h1, h2, h3, h4, h5, h6': {
    fontFamily: ({theme}) => theme.fonts.heading,
  },
});
```

generates:

```
.cZjCTX h1 font-family:function fontFamily(_ref2),.cZjCTX h2 font-family:function fontFamily(_ref2),.cZjCTX h3 font-family:function fontFamily(_ref2),.cZjCTX h4 font-family:function fontFamily(_ref2),.cZjCTX h5 font-family:function fontFamily(_ref2),.cZjCTX h6 font-family:function fontFamily(_ref2){-webkit-var:theme = _ref2.theme;-moz-var:theme = _ref2.theme;-ms-var:theme = _ref2.theme;var:theme = _ref2.theme;return:theme.fonts.heading;}
```


Will send a PR to fix that.
