### ISSUE TITLE
Dynamicly update theme on react-storybook with knob

### ISSUE THREAD

**Issue by clempat** [styled-components/styled-components#247]
## Version
1.0.5

## Reproduction
https://github.com/clempat/styled-component-theming

## Steps to reproduce
- See the repo above
- See the result there: http://piano-tuner-larry-61732.netlify.com/

## Expected Behavior
- When updating the color on react-storybook-knob. it should update the button color

## Actual Behavior
- It get out of sync and display the color previously selected

I am not sure it is a problem with styled-components but if I take a look into the react dev tool I see the theme there correctly updated.

**Comment by rudin** [comment]
Same here. When feeding a different theme to the 'ThemeProvider', with some components (strangely not all) the theme lags behind: the previously selected theme is being applied.

**Comment by rudin** [comment]
As a temporary *fix* I take the whole tree of components of the screen to force all of it to rerender.

`  constructor(props) {
    super(props);
    this.resetForceUpdate = this.resetForceUpdate.bind(this);
    this.state = {
      forceUpdate: false
    }
  }

  resetForceUpdate() {
    this.setState({forceUpdate: false});
  }

  componentDidUpdate(prevProps) {
    if (prevProps.theme.title != this.props.theme.title) {
      this.setState({forceUpdate: true});
      setTimeout(this.resetForceUpdate, 10);
    }
  }`

...and don't render a thing when state.forceUpdate === true...

**Comment by mxstbr** [comment]
I think this will be fixed by #253? Would you mind trying that?

**Comment by clempat** [comment]
I will try this evening

**Comment by clempat** [comment]
It works I tested with my repo and it works as expected... Great

**Comment by mxstbr** [comment]
Awesome, closing then and shipping #253!

**Comment by mxstbr** [comment]
Released as `styled-components@1.1.2`! 🎉
