### ISSUE TITLE
Styled Components in TypeScript 3.4.1 works much slower that in 3.3.4000

### ISSUE THREAD

**Issue by EugeneDraitsev** [styled-components/styled-components#2470]
I created an [issue](https://github.com/Microsoft/TypeScript/issues/30663) in TypeScript repo, but looks like this is related to styled-components. Tcs in new version of typescript work super slow if I add styled-components to my react project. You can find all details on typescript repo issue, but I also will add steps to reproduce and demo link here.

## Environment

```
## System:
 - OS: Windows 10
 - CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
 - Memory: 2.74 GB / 15.94 GB
## Binaries:
 - Node: 11.6.0 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
 - npm: 6.5.0-next.0 - C:\Program Files\nodejs\npm.CMD
```

## Reproduction

Reproducible demo here: https://repl.it/@EugeneDraitsev/slow-tsc-341

3.3.4000:
![image](https://user-images.githubusercontent.com/16540432/55279780-c02ee800-531c-11e9-9678-933feeddc926.png)

3.4.1:
![image](https://user-images.githubusercontent.com/16540432/55279650-1e5acb80-531b-11e9-85b1-198a2d21cca3.png)

## Steps to reproduce

```bash
yarn create react-app my-app --typescript
cd my-app
yarn add styled-components @types/styled-components 
```
add to `src/index.tsx`: 
```jsx
import styled from 'styled-components'
const Styled = styled.div``
```
add in package json tsc script in scripts section:
```
"tsc": "tsc"
```

run `yarn tsc`

if you'll downgrade typescript version to 3.3.4000 or comment 2 lines of code in `src/index.tsx` it will work 20 times faster

**Expected behavior:**

Tsc should works with same acceptable time 

**Actual behavior:**

Tsc works 20 times+ slower

**Comment by efreitasn** [comment]
+1 Same thing here.

**Comment by jazzfog** [comment]
I just spend couple hours trying to figure this out, narrowed down to Styled Components and TypeScript that enabled me to find this issue :)

**Comment by probablyup** [comment]
We don’t maintain the types. Make an issue over on DefinitelyTyped.

**Comment by jazzfog** [comment]
I ca't be sure that this issue is on Styled Component's side, it shouldn't be actually on `@types` side either, types are just virtual entities... plus I just rolled back TS version keeping types and it solved the issue.
I guess there is something wrong with TypeScript itself...

**Comment by jazzfog** [comment]
Actually OP already posted there
https://github.com/Microsoft/TypeScript/issues/30663
