### ISSUE TITLE
Wrapping react-bootstrap component overwrites bootstrap class

### ISSUE THREAD

**Issue by eylonronen** [styled-components/styled-components#2471]
Hi, we have a react application in which we use both react-bootstrap and styled-components to further style the components.
We are developing our app for about a year, and suddenly all our app went bad because all the components wrapped by styled-components "lost" their bootstrap class.
Can someone please explain either why this is happening to me, or how does the className providing works?
I couldn't understand the way the className is given to the child component and i think it might help me understand.

Thanks :)

**Comment by D-Mitt** [comment]
This also happened to me - currently resorting to using inline styles on the react-bootstrap component.

**Comment by probablyup** [comment]
Hmm they might not be handling passed in `className` well.

**Comment by probablyup** [comment]
In any case, there isn't enough info here to take action. Providing a codesandbox with a minimal reproduction would be quite helpful. Going to close this issue but feel free to reopen using our issue template.
