### ISSUE TITLE
Styled component and webpack production mode and React lazy throw error

### ISSUE THREAD

**Issue by WebTravel** [styled-components/styled-components#2473]
Hello. I use styled component in my project. When I run build in my porduction mode I get message in my console. 
```
Uncaught error: Additional arguments undefined 
```
I can say this error appear when I use production mode in webpack config.
```
"scripts": {
    "build": "webpack --mode production --config ./assets/webpack",
}
...
"dependencies": {
    "react": "^16.8.1",
    "styled-components": "^4.1.1",
}
```

I try look for resolve this problem and I discovered this become problem after I start to use `React.lazy` in my project. I use suspense in router file, it recomended in react documentation: https://reactjs.org/docs/code-splitting.html#route-based-code-splitting
My code: 
```
import React, { Suspense, lazy } from 'react';
const Home = lazy(() => import('@pages/Home'));
const RoutesList = () => (
  <Suspense fallback={<div>Loading...</div>}>
    <Switch>
      <Route exact path="/" component={props => <Home {...props} />} />
    </Switch>
  </Suspense>
)

export const Routes = withRouter(RoutesList);
```

I don't understand why styled component doesn't work ONLY production mode.

**Comment by them4g** [comment]
I have the same issue. Any workaround?

**Comment by them4g** [comment]
I have the same issue. Any workarounds?

**Comment by whiterook6** [comment]
I get the same error. In webpack you can force sourcemaps even in prod mode, so I was able to narrow it down to a styled-styled-component -- that is, I exported a styled component and then styled that component to create a more specific component. This bug doesn't appear until I'm in production mode using React's lazy() function.

**Comment by probablyup** [comment]
Weird, but I don't see what this has to do with styled-components? Make sure you're using an updated version of `react-is`, that usually causes all sorts of issues with the newer APIs interoperating with each other.

**Comment by WebTravel** [comment]
@probablyup because error call in this code's fragment:
```
if (process.env.NODE_ENV === 'production') {
      var _this = possibleConstructorReturn(this, _Error.call(this, 'An error occurred. See https://github.com/styled-components/styled-components/blob/master/src/utils/errors.md#' + code + ' for more information. ' + (interpolations ? 'Additional arguments: ' + interpolations.join(', ') : '')));
    } 
```

**Comment by martinratinaud** [comment]
Hi everyone.
Anybody found a solution for this ?

**Comment by WebTravel** [comment]
This issue needs to reopen

**Comment by fabdotnet** [comment]
same issue here
```
Uncaught Error: An error occurred. See https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/utils/errors.md#1 for more information. Additional arguments: undefined
    at new StyledComponentsError (bundle.edf203af.js:1)
    at constructWithOptions (bundle.edf203af.js:1)
    at styled (bundle.edf203af.js:1)
    at Module.<anonymous> (bundle.edf203af.js:843)
    at __webpack_require__ (bundle.edf203af.js:1)
    at Module.<anonymous> (bundle.edf203af.js:157)
    at __webpack_require__ (bundle.edf203af.js:1)
    at Module.<anonymous> (bundle.edf203af.js:1610)
    at __webpack_require__ (bundle.edf203af.js:1)
    at Object.<anonymous> (bundle.edf203af.js:1565)
```
```
const Icon = styled(BaseComponent)``;

**Comment by fabdotnet** [comment]
also this happens only on production mode

**Comment by adrianalonso** [comment]
Any update?

**Comment by WebTravel** [comment]
@probablyup, sorry, but it's styled component problem. Please, check it.

**Comment by probablyup** [comment]
I use it with nextjs and don't see any issues. Providing a reproduction case would be helpful.

**Comment by whiterook6** [comment]
What's the easiest way to set up a reproduction? JS Fiddle? I haven't really done this before, but I can try.

**Comment by lynndylanhurley** [comment]
Same issue:
```
Error: An error occurred. See https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/utils/errors.md#1 for more information. Additional arguments: undefined bundle.71c440eb.js:1:5243
    StyledComponentsError http://localhost:3333/build/bundle.71c440eb.js:1
    constructWithOptions http://localhost:3333/build/bundle.71c440eb.js:1
    styled http://localhost:3333/build/bundle.71c440eb.js:1
    <anonymous> http://localhost:3333/build/bundle.71c440eb.js:30
    __webpack_require__ http://localhost:3333/build/bundle.71c440eb.js:1
    <anonymous> http://localhost:3333/build/bundle.71c440eb.js:25
    __webpack_require__ http://localhost:3333/build/bundle.71c440eb.js:1
    <anonymous> http://localhost:3333/build/bundle.71c440eb.js:30
    __webpack_require__ http://localhost:3333/build/bundle.71c440eb.js:1
    <anonymous> http://localhost:3333/build/bundle.71c440eb.js:114
    __webpack_require__ http://localhost:3333/build/bundle.71c440eb.js:1
    render http://localhost:3333/build/bundle.71c440eb.js:136
    <anonymous> http://localhost:3333/build/bundle.71c440eb.js:136
    __webpack_require__ http://localhost:3333/build/bundle.71c440eb.js:1
    <anonymous> http://localhost:3333/build/bundle.71c440eb.js:75
    __webpack_require__ http://localhost:3333/build/bundle.71c440eb.js:1
    <anonymous> http://localhost:3333/build/bundle.71c440eb.js:1
    <anonymous> http://localhost:3333/build/bundle.71c440eb.js:1
```

Only happens in production.

**Comment by neil-gebbie-smarterley** [comment]
I had this problem and I fixed it by correcting a circular dependency as many of my Button Components shared the same base styles.

**Comment by chasemgray** [comment]
Also seeing this error only in production mode. We might have circular dependencies, so I'll check that. Anybody else have other workarounds?

**Comment by WebTravel** [comment]
> I had this problem and I fixed it by correcting a circular dependency as many of my Button Components shared the same base styles.

Thanks, it's really work for me. I fixed all circular dependencies and it helps me.

**Comment by MaxSvargal** [comment]
The same problem. I checked circular dependencies with madge.js and there are nothing.
Any other ideas?

**Comment by wintercounter** [comment]
I started to have this issue with latest RC. With beta-11 it was fine.

**Comment by IAmNatch** [comment]
@WebTravel or others, how did you go about finding these circular dependancies? My error is occurring in quite a large and similar to the errors above, the errors I'm seeing do not specify which component or file the issue is resulting from.

Thanks

**Comment by neil-gebbie-smarterley** [comment]
@IAmNatch You could try commenting out components in your Tree and rebuilding to see if the error still occurs

**Comment by IAmNatch** [comment]
@neil-gebbie-smarterley Thanks for the response.

I've tried commenting out my entire tree, with no difference. Any other ideas?

**Comment by neil-gebbie-smarterley** [comment]
@IAmNatch search your base directory for all your components that extend base components `styled(SomeBaseStyledComponent)` - thats where my problem was.

**Comment by IAmNatch** [comment]
@neil-gebbie-smarterley Thanks again. I've replaced every single styled(component) with the required styled(props => <Component {...props}/>) but with no change. I'll continue investigating and report back here if I have any luck.

**Comment by andreaserafinqmi** [comment]
I have the same problem! ONLY in production and only because i put react lazy in routes.
I have this error in the console: 
styled-components.browser.esm.js:1329 Uncaught Error: An error occurred. See https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/utils/errors.md#1

If i remove the react lazy in routes then everything works. I used create-react-app and i dont understand what is the problem. Anyone solved?

**Comment by 0duaht** [comment]
In our case, we added a custom webpack loader that ran *.min.js through file-loader. Once we took that out, the issue got resolved

**Comment by mihaigabriel1992** [comment]
> In our case, we added a custom webpack loader that ran *.min.js through file-loader. Once we took that out, the issue got resolved

could you provide that webpack content please?

**Comment by DebOM** [comment]
I was facing this same issue as well! It was mainly happening on production build, and I was unable to reproduce the bug locally!! I found no solution after several hours googling. At the end, I was running the production build locally and discovered I had circular dependent styled component on my split(lazy-load) pages and when one page was loading it didn’t have reference to the exported styled component defined on another page. It works locally because we have webpack running.
**So the best practice is to move the styled components to a separate un-split file**. Try not to export a styled component from a split page that needed reference on another page.
