### ISSUE TITLE
invariant violation with HashRouter and Switch

### ISSUE THREAD

**Issue by worc** [styled-components/styled-components#2474]
when rendering a react app with a styled-component wrapping a `<Switch/>` block i get an invariant violation error. specifically:

>Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

this is the setup that caused the error:

```
import React from 'react'
import { render } from 'react-dom'
import { HashRouter, Switch, Route } from 'react-router-dom'
import styled from 'styled-components'
import NotFound from './not_found'

render(
  <HashRouter>
    <Styling>
      <Switch>
        <Route path='*' component={ NotFound } />
      </Switch>
    </Styling>
  </HashRouter>, document.getElementById('app'))

const Styling = styled.div``
```

if i change the `<Styling/>` component back into a react `<div/>` the error goes away. i've been digging through the issues and i thought i saw something related to the new react Contexts api causing issues, but haven't been able to find it again. if i move Styling inside Switch, i do get a reference to Context.Consumer.

## Environment

**System**:
 - OS: macOS 10.14.3

**Binaries**:
 - Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
 - Yarn: 1.13.0 - ~/.nvm/versions/node/v10.15.1/bin/yarn
 - npm: 6.8.0 - ~/.nvm/versions/node/v10.15.1/bin/npm

**npmPackages**:
 - styled-components: ^4.2.0 => 4.2.0
 - react-router: ^5.0.0
 - react-router-dom: ^5.0.0

**Comment by worc** [comment]
still chipping away on this one. `createGlobalStyle` styled-components also cause this invariant violation. digging deeper, i found that styled-components are not considered valid element types in this particular case. and specifically, when `createElementWithValidation` is called for a styled-component, `type` is `undefined`, which is never considered a valid element type.

## react.development.js v16.8.6 ##

### createElementWithValidation ###
```
function createElementWithValidation(type, props, children) {
  var validType = isValidElementType(type);

  // We warn in this case but don't throw. We expect the element creation to
  // succeed and there will likely be errors in render.
  if (!validType) {
    var info = '';
    if (type === undefined || typeof type === 'object' && type !== null && Object.keys(type).length === 0) {
      info += ' You likely forgot to export your component from the file ' + "it's defined in, or you might have mixed up default and named imports.";
    }

    var sourceInfo = getSourceInfoErrorAddendum(props);
    if (sourceInfo) {
      info += sourceInfo;
    } else {
      info += getDeclarationErrorAddendum();
    }

    var typeString = void 0;
    if (type === null) {
      typeString = 'null';
    } else if (Array.isArray(type)) {
      typeString = 'array';
    } else if (type !== undefined && type.$$typeof === REACT_ELEMENT_TYPE) {
      typeString = '<' + (getComponentName(type.type) || 'Unknown') + ' />';
      info = ' Did you accidentally export a JSX literal instead of a component?';
    } else {
      typeString = typeof type;
    }

    warning$1(false, 'React.createElement: type is invalid -- expected a string (for ' + 'built-in components) or a class/function (for composite ' + 'components) but got: %s.%s', typeString, info);
  }
```

### isValidElementType ###
```
function isValidElementType(type) {
  return typeof type === 'string' || typeof type === 'function' ||
  // Note: its typeof might be other than 'symbol' or 'number' if it's a polyfill.
  type === REACT_FRAGMENT_TYPE || type === REACT_CONCURRENT_MODE_TYPE || type === REACT_PROFILER_TYPE || type === REACT_STRICT_MODE_TYPE || type === REACT_SUSPENSE_TYPE || typeof type === 'object' && type !== null && (type.$$typeof === REACT_LAZY_TYPE || type.$$typeof === REACT_MEMO_TYPE || type.$$typeof === REACT_PROVIDER_TYPE || type.$$typeof === REACT_CONTEXT_TYPE || type.$$typeof === REACT_FORWARD_REF_TYPE);
}
```

**Comment by probablyup** [comment]
This is almost always an issue with react-is. Make sure it’s fully upgraded
in your project and no extra versions are kicking around.

React hot loader can mess around with this too

**Comment by worc** [comment]
oof, it turned out to be both a simple and subtle problem. the clue was that the styled component's type was `undefined`. it wasn't that the type was directly undefined, _the entire function/component_ was undefined.

wherever my root-level module is bootstrapped into, it's not triggering hoisting like you would expect. the declaration for `Styling` isn't hoisted to the top and isn't resolved before the render call. so naturally, it's undefined.

moving the styled component declaration above the render call is the fix in this case:
```
import React from 'react'
import { render } from 'react-dom'
import { HashRouter, Switch, Route } from 'react-router-dom'
import styled from 'styled-components'
import NotFound from './not_found'

const Styling = styled.div``

render(
  <HashRouter>
    <Styling>
      <Switch>
        <Route path='*' component={ NotFound } />
      </Switch>
    </Styling>
  </HashRouter>, document.getElementById('app'))
```

which is just weird though. you usually expect that whenever a module is imported, the declarations are hoisted. that's the assumption i've used with react modules that also use styled components. hoisting let's you declare out of order and lets you put the default export at the top with a long tail of styled components trailing after.

@probablyup yeah, i have to wonder now if this is a react hot loader issue of some kind. maybe the way the app is bootstrapped into memory leaves some things unhoisted in the entry file. i do have a workaround though, so i'll close this particular issue.

**Comment by apurvis** [comment]
ran into this same issue with react 17, styled components 5.2, running in `webpack-dev-server`.   New project so the code was an extremely minimal example, basically the code from [here](https://doc.babylonjs.com/resources/babylonjs_and_reactjs) but with a trivial styled component instead of a `<div>` as in their example:
```js
class App extends React.Component {
    render() {
        return <MainContainer>
            <SceneComponent antialias onSceneReady={onSceneReady} onRender={onRender} id='my-canvas' />
        </MainContainer>
    }
}
```

Thankfully same workaround worked for me...  FWIW i am not using `react-hot-loader`, though i am using webpack's hot loader as well as `hard-source-webpack-plugin`.  I'm putting my dependencies and webpack config here in case any future generations are trying to debug this.

```json
    "dependencies": {
        "@babylonjs/core": "^4.1.0",
        "babel-loader": "^8.1.0",
        "babylonjs": "^4.1.0",
        "babylonjs-hook": "0.0.9",
        "npm": "^6.14.8",
        "react": "^17.0.0",
        "react-dom": "^17.0.0",
        "styled-components": "^5.2.0"
    },
    "devDependencies": {
        "@babel/core": "^7.12.3",
        "@babel/preset-env": "^7.12.1",
        "@babel/preset-react": "^7.12.1",
        "babel-plugin-styled-components": "^1.11.1",
        "css-loader": "^5.0.0",
        "file-loader": "^6.1.1",
        "hard-source-webpack-plugin": "^0.13.1",
        "html-loader": "^1.3.2",
        "html-webpack-plugin": "^4.5.0",
        "prettier": "^2.0.4",
        "style-loader": "^2.0.0",
        "ts-loader": "^8.0.6",
        "typescript": "^4.0.3",
        "webpack": "^4.42.1",
        "webpack-cli": "^3.3.11",
        "webpack-dev-middleware": "^3.7.2",
        "webpack-dev-server": "^3.11.0",
        "webpack-hot-middleware": "^2.25.0"
    },
```

here's my webpack config:

```js
module.exports = {
    mode: 'development',
    entry: ['./src/client/index.js'],
    devtool: 'eval-cheap-module-source-map',
    target: 'web',
    module: {
        rules: [
            {
                test: /\.js$/,
                use: 'babel-loader',
                exclude: [/node_modules/, /dist/],
            },
            {
                test: /\.tsx?$/,
                use: 'ts-loader',
                exclude: /node_modules/,
            },
            {
                test: /\.html$/,
                use: [
                    {
                        loader: 'html-loader',
                    }
                ]
            },
        ]
    },
    output: {
        path: path.join(__dirname, '..', '..', '..', 'dist'),
        filename: 'main.js',
    },
    plugins: [
        new HtmlWebPackPlugin({
            template: './src/index.html',
            filename: './index.html',
            excludeChunks: ['server']
        }),
        new webpack.HotModuleReplacementPlugin(),
        new webpack.NoEmitOnErrorsPlugin(),
        new HardSourceWebpackPlugin(),
    ],
    performance: {
        maxEntrypointSize: 1024000,
        maxAssetSize: 1024000
    },
    devServer: {
        publicPath: '/',
        compress: true,
        port: 9000,
        hot: true,
    },
};
```
