### ISSUE TITLE
Understanding Spooky Ghosts

### ISSUE THREAD

**Issue by DannyBrown** [styled-components/styled-components#2475]
I was wondering if it would be possible for the `styled-components` team to answer a few product focused questions I have about the `__DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS` export?

Prior to asking these questions I have read the following existing issues and their associated comments:
* https://github.com/styled-components/styled-components/issues/1487
* https://github.com/styled-components/styled-components/issues/1660

At [defty](https://www.defty.com) we are building a WYSIWYG static site generator in order to bring cheap, easy to build websites to small businesses and individuals who currently wouldn't know how to build a website or who wouldn't otherwise have the time or money to do so.

Our static sites are generated by rendering react elements to html using the `ReactDOMServer.renderToStaticMarkup();` function. This doesn't in any way handle CSS. We would like to use `styled-components` because we love the API and it has good mindshare amongst potential future employees.

At the moment to extract the CSS required for a site we use the following code snippet:
```javascript
import styled, {
  __DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS as styledComponentsInternals,
} from 'styled-components';

const { StyleSheet } = styledComponentsInternals;
StyleSheet.reset(false);
const bodyHTML = ReactDOMServer.renderToStaticMarkup(/* A styled.body with children */);
const styles = StyleSheet.instance.toHTML();
```

The name `__DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS` makes it clear that this is not a use-case you fully support at the moment and that we should expect breaking changes at any time. However, we have looked into alternatives such as `linaria` (which is much more static site focused, but doesn't allow quite enough dynamism for us), and none of them stack up to the ease of the code snippet above.

Some of the answers to these questions may be obvious, but I would rather be explicit:

1. Do you have existing plans to change the `StyleSheet` or `__DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS` export in ways which would break this set up?
2. If not, is this a use case you will consider in future when making decisions about backwards compatibility? 
3. What kind of warning would the community receive before a breaking change was made to `StyleSheet` or `__DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS`? Would it be none/very little because this is explicitly considered internal and marked as such by the fun export name?
4. What suggestions would you make to user such as ourselves and the OP of https://github.com/styled-components/styled-components/issues/1487 in regards to continued use of `styled-components` for this use case or an alternative (if you know of one)? 
5. Would you accept pull requests which explicitly improve the situation for this use case, or is this a use case which `styled-components` as a project has no interest in? (which is fine 👍)

Thanks to all contributors for their work on `styled-components`. Even if this use case is not supported going forward the library allowed us to get a MVP together very quickly, and we are very grateful! We hope we can work together with the `styled-components` team going forward to improve `styled-components` for the static site generation use case if this is something they are interested in exploring.

Thanks
Danny

**Comment by mxstbr** [comment]
I think as long as you lock the version of styled-components you depend on you should be fine!

I don't know if we want to guarantee that this will not break in the future (/cc @styled-components/core), but if we do ever break it and you notice during a routine upgrade we would definitely accept a PR to fix it again.

**Comment by DannyBrown** [comment]
> I think as long as you lock the version of styled-components you depend on you should be fine!

Agreed, we just don't want to get to a state in a year or so where we're X many versions behind `styled-components` because we cannot upgrade 😅 

> I don't know if we want to guarantee that this will not break in the future (/cc @styled-components/core), but if we do ever break it and you notice during a routine upgrade we would definitely accept a PR to fix it again.

Will be good to see what @styled-components/core have to say. Thanks for tagging them. As long as you guys are willing to accept PRs to fix this functionality going forward then I am happy 👍 Looking forward to seeing confirmation from core.

**Comment by mxstbr** [comment]
> Looking forward to seeing confirmation from core.

I am @styled-components/core and I will accept PRs that fix that! :wink: I just tagged the GitHub team in case anybody disagrees, but I doubt anybody will since we added the export in the first place and need it for `jest-styled-components`.

I will close this for now since it seems resolved, good luck with your project!

**Comment by DannyBrown** [comment]
@mxstbr My bad, thank you for `styled-components` and your help here!
