### ISSUE TITLE
React hooks do not overwrite styles [TypeScript]

### ISSUE THREAD

**Issue by nachbarshund** [styled-components/styled-components#2477]
#### System:
 - OS: macOS 10.14.4
 - CPU: (4) x64 Intel(R) Core(TM) i5-6287U CPU @ 3.10GHz
 - Memory: 166.97 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
#### Binaries:
 - Node: 10.15.2 - /usr/local/bin/node
 - Yarn: 1.15.2 - /usr/local/bin/yarn
 - npm: 6.9.0 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
#### npmPackages:
 - babel-plugin-styled-components: ^1.10.0 => 1.10.0 
 - styled-components: ^4.1.3 => 4.1.3 

## Reproduction
I import a file which is a React Hook and want to override the color. But there is no effect on that 😢

``` js
// Modules
import React, { Fragment } from "react";
import styled from "styled-components";

// Hook
const MyHookTitle = () => {
  const InternalTitle = styled.h1`
    color: purple;
  `;
  return <InternalTitle>MyHookTitle</InternalTitle>;
};

// Styles
const StyledHook = styled(MyHookTitle)`
  color: red;
`;

export const App = () => {
  return (
    <Fragment>
      <MyHookTitle />
      <StyledHook />
    </Fragment>
  );
};
```
## Expected Behavior
Color of title is `red`.
![image](https://user-images.githubusercontent.com/188901/55864394-b14a0000-5b7c-11e9-8ba9-7ddad0b5f2e0.png)

## Actual Behavior
Color is `purple`
![image](https://user-images.githubusercontent.com/188901/55864350-9c6d6c80-5b7c-11e9-95a3-782dab6a17e1.png)

**Comment by blainekasten** [comment]
Defining styled components during the render lifecycle is a bad idea. The docs even say so. You should use prop interpolation to do this.

So something like:

```jsx
// components/Title.tsx
const StyledTitle = styled.h1`
  color: ${props => props.color || props.theme.light};
`;

// Example.tsx
export const Example = () => {
  const isActive = true;

  return (
    <Fragment>
      <StyledTitle color="red label="Example" />
    </Fragment>
  );
};

**Comment by nachbarshund** [comment]
@blainekasten I totally agree. Sorry this was just a try for my side. I'll fix it in the original. But the problem ist still the same. I am not able to overwrite existing attributes with `styled(ComponentName)` 😢

**Comment by blainekasten** [comment]
I'm guessing it's because you were wrapping the css declaration as a string, but css does not need strings.

```jsx
  const SuperStyledTitle = styled(Title)`
    color: "red" // <- "red" should be just red
  `;
```

**Comment by EugeneDraitsev** [comment]
@nachbarshund You also need to pass className prop to your component
```jsx
// components/Title.tsx
export const Title = (props: Props) => {
  const { label, className } = props;
  return <StyledTitle className={className}>{label}</StyledTitle>; // <- className here
};
```

**Comment by nachbarshund** [comment]
That's not the problem 😞
Here a better example:
``` js
// Modules
import React, { Fragment } from "react";
import styled from "styled-components";

// Hook
const MyHookTitle = () => {
  const InternalTitle = styled.h1`
    color: purple;
  `;
  return <InternalTitle>MyHookTitle</InternalTitle>;
};

// Styles
const StyledHook = styled(MyHookTitle)`
  color: red;
`;

export const App = () => {
  return (
    <Fragment>
      <MyHookTitle />
      <StyledHook />
    </Fragment>
  );
};

```


### Result
![image](https://user-images.githubusercontent.com/188901/55864314-852e7f00-5b7c-11e9-98f1-5442884fa074.png)

But the second one should be red.

**Comment by epilande** [comment]
@nachbarshund `InternalTitle` is still in the render lifecycle. As mentioned in https://github.com/styled-components/styled-components/issues/2477#issuecomment-479510128, we shouldn't be doing that. `InternalTitle` needs to be moved outside of `MyHookTitle` and the `className` needs to be passed down in order for `StyledHook`'s styles to apply. 

```jsx
// Modules
import React, { Fragment } from "react";
import styled from "styled-components";

const InternalTitle = styled.h1`
  color: purple;
`;

// Hook
const MyHookTitle = ({ className }) => {
  return <InternalTitle className={className}>MyHookTitle</InternalTitle>;
};

// Styles
const StyledHook = styled(MyHookTitle)`
  color: red;
`;

const App = () => (
  <Fragment>
    <MyHookTitle />
    <StyledHook />
  </Fragment>
);
```

Here's a codesandbox of the above code https://codesandbox.io/s/9ol8molq4o

**Comment by nachbarshund** [comment]
@epilande Oh man big thanks. No I'll get the point here. Thanks for helping 🚀
