### ISSUE TITLE
Missing helper for <details-menu /> tag

### ISSUE THREAD

**Issue by quentinvernot** [styled-components/styled-components#2479]
Hello,

I'd like to add a helper for the `<details-menu />` tag, it's not very common but it's a valid html5 element and it turns out it's even used on this page -> the user menu in the top-right of github uses the details/summary/details-menu combo.

I'm guessing I need to add `detailsMenu` to the list in `packages/styled-components/src/utils/domElements.js`, is there another file that needs to be updated anywhere?

Cheers!

**Comment by njenia** [comment]
Hi,
This solves it: https://github.com/styled-components/styled-components/pull/2491

**Comment by quentinvernot** [comment]
Well... I just stumbled upon this: [github/details-menu-element](https://github.com/github/details-menu-element). So... `<details-menu />` is actually a custom element that github uses. Not quite sure why I found other sources saying that it's normal html, but that would explain why it's not in `domElement.js`.

Close?

**Comment by probablyup** [comment]
Yeah it's custom, thanks
