### ISSUE TITLE
borderRadius property not generated when using border-radius

### ISSUE THREAD

**Issue by jh3y** [styled-components/styled-components#248]
## Version
1.1.1

## Steps to reproduce
This is quite possibly a regression between `1.0.11` and `1.1.1`. If you create a `styled-component` using `styled-components/native` with `border-radius` the border radius is no longer applied to your native components.

The properties `borderTopLeftRadius`, `borderTopRightRadius`, `borderBottomRightRadius` and `borderBottomLeftRadius` are set but `borderRadius` is __not__.

I came to this conclusion by creating a simple Image which would previously have rendered as a circle;

```js
import styled from 'styled-components/native'

const RoundImage = styled.Image`
  border-radius: 25;
  height: 50;
  width: 50;
`
```

When I inspect it in the simulator, all the props are set apart from `borderRadius`. If I render it with an explicit inline style for `borderRadius` I get the desired outcome;

```js
<RoundImage style={{borderRadius: 25}} source={imageSrc}/>
```

I rolled back my version of `styled-components` to `1.0.11` and all was back to normal.

I'm assuming this could be an issue with the `css-to-react-native` as a dependency?

Probably best to post an issue there but thought no harm in raising awareness here too :neckbeard: 

## Expected Behavior
That the `borderRadius` prop is being set on the component.

## Actual Behavior
It isn't but the other `borderRadius` props are set but have no effect.

## Update
So I've nailed this down to being part of `css-to-react-native` in file `src/grammar.ne` line `147`. I've played around with `borderTopLeftRadius` etc. within the simulator and these have no effect on components. So it may just be best to revert this to only outputting `borderRadius` and let people specify the others explicitly if needed. I'll open an issue up over there and submit a PR.

**Comment by mxstbr** [comment]
Closing in favor of styled-components/css-to-react-native#11
