### ISSUE TITLE
When importing "styled-components" VSCode IntelliSense will fall into infinite loading

### ISSUE THREAD

**Issue by ouweiya** [styled-components/styled-components#2482]
When importing "styled-components", VSCode IntelliSense will fall into infinite load, the language server seems to have crashed, I tried either 4.2.0 and 4.1.3, but it didn't get better.

```js
import React, { Component } from "react";

import styled from "styled-components";

const Title = styled.h1`
    font-size: 1.5em;
    text-align: center;
    color: palevioletred;
`;

class App extends Component {
    render() {
        return <Title>Hello World!</Title>;
    }
}

export default App;
```

![Snipaste_2019-04-05_19-40-49](https://user-images.githubusercontent.com/28357731/55625229-bacd1400-57da-11e9-8cb1-5d63b0243253.png)

**Comment by pathikdevani** [comment]
I am also facing the same issue. vscode version ```1.33.0``` and styled-component version ```4.2.0```.

**Comment by pathikdevani** [comment]
@ouweiya problem with vscode version ```1.33.0```, I just revert back with ```1.32.3```. As of now, it's working fine.

**Comment by ouweiya** [comment]
I took a closer look and found that VSCode will point styled-components to the type definition file. Importing the module requires specifying an absolute path.

```js
import styled from "../node_modules/styled-components";
```

**Comment by pathikdevani** [comment]
@ouweiya Thanks. Looks like revert back is a good option for me as of now.

**Comment by probablyup** [comment]
Going to close as this is not actionable from our side.

**Comment by cbdeveloper** [comment]
@pathikdevani the same is happening to me. VScode v1.33 and styled-components v4.1 (same on v4.2) . How can I revert VSCode to v1.32? Do I need to uninstall before reinstalling? Do I lose preferences and extensions? Sorry to use this issue for this, but my issue here is very similar and I never did this before.

**Comment by probablyup** [comment]
https://twitter.com/probablyup/status/1115996048806293505?s=20

**Comment by probablyup** [comment]
Does not seem to tamper with prefs and extensions from when I did it

**Comment by cbdeveloper** [comment]
@probablyup Is this problem gone on VSCode 1.35? I'm still using 1.32 since it happened.

**Comment by pathikdevani** [comment]
I am not facing an error on 1.32.3. Looks like solved. @cbdeveloper

**Comment by cbdeveloper** [comment]
@pathikdevani @probablyup The 1.32.3 is the version I've downgraded to, in order to get rid of the problem. Have you updated your VSCode since? I'm still using 1.32.3.

**Comment by pathikdevani** [comment]
@cbdeveloper i am using latest now without any issue.
