### ISSUE TITLE
Feature Request: Remove global (createGlobalStyles) styles on unmount

### ISSUE THREAD

**Issue by sattaman** [styled-components/styled-components#2487]
I am implementing a web-app using `single-spa` and as part of this we have different react apps load in to our html document as the user navigates between sub-apps. 

Ideally the use of `createGlobalStyles` would only persist while the component defining these props was mounted, and they would be removed when this component (and in my case the app loading them) is removed.

**Comment by nathggns** [comment]
I'm unsure why this was closed but this feature would be super useful.

**Comment by leoyli** [comment]
Me too, for some part of the app, I want a special global style injection (e.g. to prevent over-scroll in the body element). But it is an one-time only special case and I don't want to enforce this in other places...

**Comment by uriklar** [comment]
+1 for reopening this

**Comment by jon64digital** [comment]
I'm surprised that Styled COmponents doesn't do this. Does thins mean that as users navigate around my NextJS app I'm adding new global styled on every page and they're never being removed? That doesn't seem Ideal.

**Comment by probablyup** [comment]
> I'm surprised that Styled COmponents doesn't do this. Does thins mean that as users navigate around my NextJS app I'm adding new global styled on every page and they're never being removed? That doesn't seem Ideal.

We do remove it, not sure what's going on for the OP but we absolutely do remove it on unmount. https://github.com/styled-components/styled-components/blob/main/packages/styled-components/src/constructors/createGlobalStyle.ts

**Comment by jon64digital** [comment]
Ah OK, that's great. Assumed from the number of likes that this thread has got that it was not happening. Good to know it is.
