### ISSUE TITLE
Feature Request: Framer X Implementation

### ISSUE THREAD

**Issue by jsargeim** [styled-components/styled-components#2488]
Feature Request for Framer X's new API.

I haven't found any issues that were opened on this. My team uses `styled-components` heavily, and we love it. We also use a product known as Framer X to help prototype. Framer X is still developing as they have been out less than a year, but something that would be incredibly helpful is to add Framer X support. I understand there may not be a _huge_ market for it, but it would be awesome for my team.

Here's what I mean: 

Here you can find the [Framer API](https://www.framer.com/api/) Understanding these docs will be crucial in this implementation. They're still in Beta, so I understand it'll be down the road. 

They have something called a Frame, which implements an HTML structure in a fancier way. They have lots of props, and you can animate things easier than basic CSS. This would introduce a new dependency, so maybe having a `styled-framer` or something would be useful as to not clog up the classic styled for those who don't need it. 

My thinking is it would look something like this:

``` 
  styled.frame`
      size="40%"
      z=${100}
      rotate=${90}
      scale=${1.2}
      skew=${15}
  `
```

It would align our code, so things stay uniform - and help declutter. I think it would be imperative for anyone using Framer X and `styled` -- which is a lot among the Framer Community.

**Comment by probablyup** [comment]
Something like this would never land in the core repo, as it's too specific to an unrelated technology. You're welcome to wire something up and contribute it to the `styled-components` organization though!

**Comment by armand1m** [comment]
A Frame is a react component like any other, so in theory you can do such as `styled(Frame)` =)
