### ISSUE TITLE
Using `as` prop don't keep the styles defined by the component

### ISSUE THREAD

**Issue by Lucasdsk** [styled-components/styled-components#2494]
### System:
 - OS: Linux 4.18 Ubuntu 18.04.2 LTS (Bionic Beaver)
 - CPU: (4) x64 Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz
 - Memory: 191.34 MB / 7.70 GB
 - Container: Yes
 - Shell: 4.4.19 - /bin/bash
### Binaries:
 - Node: 11.13.0 - /usr/bin/node
 - Yarn: 1.15.2 - /usr/bin/yarn
 - npm: 6.7.0 - /usr/bin/npm
### npmPackages:
 - styled-components: ^4.1.3 => 4.2.0 

## Reproduction

https://codesandbox.io/s/xjk57mlmr4
The `styled-components` version in the reproduction is the: `4.2.0`

## Expected Behavior
The expected behavior is what is described in the [doc](https://www.styled-components.com/docs/api#as-polymorphic-prop), that if I want just change the HTML element but keep all the defined styles I can use the `as` prop.

## Actual Behavior
When I create a styled component that renders an `p` HTML element:

> Text.js
```javascript
const StyledText = styled.p`
  margin: 0;
  color: blue;
  font-size: 20px;
`;

const Text = ({ style, as, className, children }) => (
  <StyledText style={style} as={as} className={className}>
    {children}
  </StyledText>
);
```

I create another component that applies other styles to the `Text` component and uses it. What happens is that the `StyledLabel` lost the `Text` style if I use the `as` prop:

> Example.js
```javascript
const StyledLabel = styled(Text)`
  font-weight: bold;
`;

const Example = () => (
  <div>
    <div>
      <h3>Example</h3>
    </div>
    <StyledLabel as="label">
      This text should be inside the label tag with styles: blue, bold, and with
      font-size: 20px
    </StyledLabel>
    <StyledLabel>
      {
        'But what happens is that after using the "as" prop, it lost the <Text /> styles'
      }
    </StyledLabel>
  </div>
);
```

**Comment by Flydiverny** [comment]
Ran into this as well, what happens makes sense tho.
Using your example above setting as on `StyledLabel` will replace the component, in this case `Text` with `label`.
But what you are trying to do is set the inner components `as` prop, ie you don't want the first styled component to consume it. Kind of like good ol `ref` vs `innerRef`, if you were to make an `innerAs` and use that in your text component everything would work as expected.

Code sandbox example:
https://codesandbox.io/s/2xj2kw2q5n

**Comment by Lucasdsk** [comment]
Oh, I got it.
The point is that I was passing the `as` prop to the first level of the styled component instead to pass to the last component.

It does total sense, thank you so much @Flydiverny
