### ISSUE TITLE
Safari paints multiple focus states together

### ISSUE THREAD

**Issue by seejamescode** [styled-components/styled-components#2497]
### System:
 - OS: macOS 10.14.3
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 91.81 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
### Binaries:
 - Node: 8.7.0 - ~/.nvm/versions/node/v8.7.0/bin/node
 - Yarn: 1.12.3 - /usr/local/bin/yarn
 - npm: 5.4.2 - ~/.nvm/versions/node/v8.7.0/bin/npm
### npmPackages:
 - babel-plugin-styled-components: ^1.8.0 => 1.9.1
 - styled-components: ^4.1.1 => 4.1.1

## Reproduction
![Apr-12-2019 16-17-25](https://user-images.githubusercontent.com/7519029/56066846-b6ef4380-5d3e-11e9-8ea8-989012f794cd.gif)

https://codesandbox.io/s/rjwx2y58q?fontsize=14

## Steps to reproduce

1. Write an focus outline the following way inside a Styled Component:
```
&:focus::after {
    height: 100%;
    content: "";
    left: 0;
    outline: 2px solid blue;
    outline-offset: -2px;
    position: absolute;
    top: 0;
    width: 100%;
  }
```
2. Enable tabbing in Safari by going to Preferences.
3. Tab the elements on the page.

I could not reproduce this bug with vanilla CSS. I have also included a selector that does work in the CodeSandbox. It is isolated to Safari.

I wouldn’t call this urgent since there are other ways of writing the selector, but thought the bug may affect other selectors.

## Expected Behavior

Only one focus outline is viewable at all times.

## Actual Behavior

Focus outlines painted to not go away.

**Comment by probablyup** [comment]
It appears to be a safari bug of some sort. When I removed the div wrapper in the sandbox and put the position relative on the button directly things worked 🤷‍♂️
