### ISSUE TITLE
Extending a styled component that lacks a trailing semicolon breaks styles on the extending component

### ISSUE THREAD

**Issue by JustinLovinger** [styled-components/styled-components#2499]
## Environment

- styled-components: 4.2.0

### System:
 - OS: Windows 10
 - CPU: (8) x64 Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
 - Memory: 18.31 GB / 31.87 GB
### Binaries:
 - Node: 9.3.0 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.12.3 - C:\Users\JLove\AppData\Roaming\npm\yarn.CMD
 - npm: 6.5.0 - C:\Program Files\nodejs\npm.CMD

## Reproduction

https://codesandbox.io/s/8zyq6vp74j

## Steps to reproduce

1. Create a styled component with css lacking a trailing ;
2. Create a styled component extending the previous styled component

## Expected Behavior

The extending styled component should have the styles of the extended component and its own styles.

## Actual Behavior

The extending styled component lacks the last style from the extended component and the first of its own styles. The last style of the extended component is concatenated to the first style of the extending component, with a semicolon, such as `padding: 4embackground: papayawhip;`, thereby breaking both styles.

**Comment by probablyup** [comment]
We don't guarantee semicolon insertion, sorry.

**Comment by JustinLovinger** [comment]
Perhaps it should? It seems to me that styling a styled component should guarantee that the new component has the styles of the original in addition to its own.

**Comment by probablyup** [comment]
We do guarantee that the styles are transferred, but we make no promises that the base styles you wrote are valid. At the end of the day it’s just CSS and CSS needs semicolons.

**Comment by JustinLovinger** [comment]
CSS with no trailing semicolon is valid CSS. To clarify, I am referring to the last style missing a semicolon and have updated the example. It is common for minifiers to remove the trailing semicolon. I discovered this issue with styled-components by using a library that generates CSS, which happens to minify the result. The issue here is that styled-components does not guarantee that styles are transferred for valid CSS.
