### ISSUE TITLE
Wrong component being used in development and production mode

### ISSUE THREAD

**Issue by bmtdh** [styled-components/styled-components#2503]
## System:
 - OS: macOS Mojave 10.14.4
 - CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
 - Memory: 75.52 MB / 8.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 10.11.0 - /usr/local/bin/node
 - Yarn: 1.10.1 - /usr/local/bin/yarn
 - npm: 6.4.1 - /usr/local/bin/npm
## npmPackages:
 - styled-components: ^4.0.3 => 4.1.3

## Reproduction
Run a nextJS project in development mode using "npm run dev"
[edit] Also realised upon deploy that this is happening in production too

## Steps to reproduce
Navigate to affected page

## Expected Behavior
I have a styled component called ContentSummary and another one called FormStepWrapper. The styles within each component are completed different they live in different directories within a styles directory. I have a form with various items wrapped in my FormStepWrapper component which is a styled div. In development mode when I refresh the page manually I would expect the FormStepWrapper to be used.

## Actual Behavior
When I refresh the page manually the styled component called ContentSummary gets used instead. I am not referencing this component, I am explicitly referencing FormStepWrapper
<img width="211" alt="Screenshot 2019-04-16 at 15 58 20" src="https://user-images.githubusercontent.com/44874175/56220549-8837dc80-6060-11e9-9d74-84a5073d866f.png">

However when I look at the source of the page the ContentSummary component is being used.
![Screenshot 2019-04-16 at 16 00 22](https://user-images.githubusercontent.com/44874175/56220684-c2a17980-6060-11e9-82f3-e8e134479271.png)

If I go into the FormStepWrapper file and save it then the page is updated via the hot reloading in nextJS and it reverts to using the correct component, but if I manually refresh the page again it is back to using the wrong component.

I am a bit stumped here as I have no idea why it randomly decides to use a random component from elsewhere in the project.

Looking for any help or to be pointed in the right direction.

Thanks!

**Comment by probablyup** [comment]
This is almost certainly an issue with your environment. I've been using s-c in dozens of projects with different build systems and haven't seen the behavior. If you can create a minimal reproduction in a codesandbox though I'd be interested to see.

**Comment by filingroove** [comment]
@bmtdh 

Hey :) Have you found what was wrong? I'm facing the same issue with Next.js

**Comment by bmtdh** [comment]
@filingroove unfortunately not, it appears to be a quirk with using styled components and next.js. I got round it by slightly delaying the render which wasn't ideal...
