### ISSUE TITLE
displayName and forwardRef not handled as described in React docs

### ISSUE THREAD

**Issue by MrLoh** [styled-components/styled-components#2507]
I think that displayName might not handled correctly. 

I am not seeing the display names of styled components in the react profiler. 

<img width="809" alt="Screen Shot 2019-04-17 at 17 05 49" src="https://user-images.githubusercontent.com/1285032/56324788-84c25500-6135-11e9-9ee5-1608e40905b8.png">

I think this issue is related to how the display name is set here: 
https://github.com/styled-components/styled-components/blob/c098fd7deb610717fa0fbc33d6ec2f9cf0e69edc/packages/styled-components/src/models/StyledComponent.js#L280-L288

As per the [React docs](https://reactjs.org/docs/forwarding-refs.html#displaying-a-custom-name-in-devtools) the displayName should be set on the function passed to `React.forwardRef` and not on its return value. See also [this issue](https://github.com/facebook/react/issues/13703)

## System:
 - OS: macOS 10.14.4
 - CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
 - Memory: 416.54 MB / 32.00 GB
 - Shell: 2.7.1 - /usr/local/bin/fish
## Binaries:
 - Node: 10.15.0 - /usr/local/bin/node
 - Yarn: 1.13.0 - /usr/local/bin/yarn
 - npm: 6.5.0 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: ^1.10.0 => 1.10.0 
 - styled-components: ^4.2.0 => 4.2.0 
 - react: 16.8.3
 - react-native: 0.59.2

**Comment by probablyup** [comment]
Send a PR, thanks!
