### ISSUE TITLE
Preserve non-standard CSS on production build

### ISSUE THREAD

**Issue by oguzgelal** [styled-components/styled-components#2511]
My question is about a very specific use case.

I'm building a data driven PDF report with React using [PrinceXML](https://www.princexml.com/) and styled-components. Prince is a user-agent for rendering css paged media, and it uses some rules that are (probably) not in the standard css specifications, or are still a [working draft](https://www.w3.org/TR/css-page-3/). 

Anyway, the report renders perfectly on development mode, but I noticed that some of the rules gets lost on the production build (for example `position: running(header)`) and I'm struggling to understand why.

As a side note, Prince Javascript engine sucks so I'm having [puppeteer](https://github.com/GoogleChrome/puppeteer) render the page first, and hand over the resulting html to Prince, with all styles attached to the head. Then I proceed to run Prince with Javascript disabled. However, the way styled-components inserts production css into the page is by using the CSSOM api instead of injecting them into the head (as it is in dev mode), which doesn't work with the puppeteer - prince approach. Therefor I came up with the following trick:

```javascript
// only do this on production mode, on development mode
// styled-components already inserts styles into head
if (process.env.NODE_ENV !== 'production') return;

// grab the style tag inserted by styled-components
const el = document.querySelector('style[data-styled]');

// get css sheet rules and concatanate them into a single string
const css = Object.values(el.sheet.rules).reduce((acc, r) => acc + r.cssText, '');

// create and populate the container style tag element to
// receive the css properties
const styleContainer = document.createElement('style');
styleContainer.setAttribute('type', 'text/css');
styleContainer.innerHTML = css;

// append style container to head
document.head.appendChild(styleContainer);
```

I'm trying to understand at which step those rules gets lost, but my guess is that they are lost at this step. Styled-components tries to insert the rules into the page using the CSSOM api, Chrome (puppeteer in my case) won't insert rules that it doesn't understand / support, so when I grab them they are already gone.

So is there a way to force styled components to insert rules into the head in prod mode like it is in dev mode ? Or perhaps get the css string directly from styled-components without involving chrome ? or any ideas why this might be happening ?

Thanks!

**Comment by probablyup** [comment]
It's likely because [stylis](https://github.com/thysultan/stylis.js) (our runtime CSS processor) doesn't support the syntax yet. I'd open an issue over there, as we don't really touch the CSS itself much inside of styled-components core.

**Comment by oguzgelal** [comment]
@probablyup disabling speedy worked! turns out browser was rejecting the styles.. Thank you!!
