### ISSUE TITLE
As prop not working

### ISSUE THREAD

**Issue by jordiviva** [styled-components/styled-components#2515]
## System:
 - OS: Windows 10
 - CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
 - Memory: 8.31 GB / 15.92 GB
## Binaries:
 - Node: 11.14.0 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
 - npm: 6.7.0 - C:\Program Files\nodejs\npm.CMD

The version of the library:
"styled-components": "3.3.3",

## Reproduction

I tryed to use as prop, same line as docs:
```
const TomatoButton = styled(Button)`
  color: tomato;
  border-color: tomato;
`;
<TomatoButton as="a" href="/">Link with Tomato Button styles</TomatoButton>
```

The result is :

`<button class="pages__TomatoButton-s1tdnz4k-0 ikJeDL sc-htpNat dnNxFB" as="a" href="/" font-size="1" font-weight="bold">Link with Tomato Button styles</button>`

The as prop is being shown on Html tag, and button is not being reemplaced by a.

**Comment by elijah1210** [comment]
Based on [this link here](https://www.styled-components.com/docs/api#as-polymorphic-prop), it looks like it was added in v4.

Updating your styled-components should fix it.

**Comment by jordiviva** [comment]
ok seems it works on last version yep sry, all fine then.
