### ISSUE TITLE
Feature request: overwrite the autogenerated className

### ISSUE THREAD

**Issue by KevinGervais** [styled-components/styled-components#2520]
It would be interesting if we could set custom class in our styled components that would overwrite the auto-generated class.

The justifications:
- We doesn't need always random classes
- for reusable components like button, input from a form library, it is more convenant to use custom class if we want to overwrite some styles
- Random classNames can be confusing when we are searching for components in the DOM tree
- overwriting class instead of just adding a class is cleaner in the DOM tree

Example code for the feature:
```
const Button = styled.div.overwriteClass('button')`
  display: flex;
  justify-content: center;
  align-items: center;
  height: 30px;
  padding: 0 20px;
  border-radius: 15px;
`
```

Thanks you for reading my request!

**Comment by probablyup** [comment]
Use the styled-components babel plugin, it labels the elements in the DOM more nicely! Can't see us adding support for fully customizing the className behavior though as we need control of it internally to prevent collisions.
