### ISSUE TITLE
Styled attributes composition className

### ISSUE THREAD

**Issue by RahulKatariya** [styled-components/styled-components#2521]
## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`

### System:
 - OS: macOS 10.14.4
 - CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
 - Memory: 54.75 MB / 8.00 GB
 - Shell: 5.7.1 - /usr/local/bin/zsh
### Binaries:
 - Node: 11.14.0 - /usr/local/bin/node
 - Yarn: 1.15.2 - /usr/local/bin/yarn
 - npm: 6.9.0 - /usr/local/bin/npm
### npmPackages:
 - styled-components: ^4.2.0 => 4.2.0

## Steps to reproduce
```js
export const ProgressBar = styled.div.attrs({
  className: `progress-bar`,
  style: { role: "progressbar" }
})`
  background-color: ${props => props.theme.colors.primary} !important;
`;
export const ProgressBarStriped = styled(ProgressBar).attrs({
  className: `progress-bar-striped`
})``;
```
## Expected Behavior
The expected behaviour is when using the component _ProgressBarStriped_, it should have both the classes in order `progress-bar` and `progress-bar-striped`

## Actual Behavior
The css class associated with _ProgressBarStriped_ is `progress-bar-striped`.

Is there any other way to achieve this kind of functionality?

**Comment by probablyup** [comment]
You need to use the functional version of `attrs` to append the previous className:

```js
export const ProgressBarStriped = styled(ProgressBar).attrs(props => ({
  className: `${props.className} progress-bar-striped`,
}))``;
```
