### ISSUE TITLE
Document or clearer support for use of @import in createGlobalStyle

### ISSUE THREAD

**Issue by sidhuko** [styled-components/styled-components#2526]
### System:
 - OS: macOS Mojave 10.14.4
 - CPU: (4) x64 Intel(R) Core(TM) i5-5287U CPU @ 2.90GHz
 - Memory: 281.36 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
### Binaries:
 - Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
 - Yarn: 1.15.2 - /usr/local/bin/yarn
 - npm: 6.9.0 - ~/.nvm/versions/node/v10.15.3/bin/npm## Reproduction

## Steps to reproduce
The issue is only visible within production usage but the code provided will show the error.
https://codesandbox.io/s/q950z30qr6?fontsize=14

* Create local repository based on example above.
* Run webpack in production mode with recommended settings.

## Expected Behavior
The styles created with `createGlobalStyle` are visible by hoisting imports to top-level OR the css specification is followed in this case and an error is shown to advise the user @import will not be supported within css element selectors when using `createGlobalStyle`.

## Actual Behavior
In production, it does not display any styles created with `createGlobalStyle` when `@import` is used within a CSS element. 

It's not a critical issue I know but as you extend the CSS specification with helpful utilities it is not immediately obvious this is not a supported pattern. Other [users](https://stackoverflow.com/questions/54841288/why-are-my-globalstyles-not-working-after-deploying-with-styled-components) have run into the issue and it can take sometime to narrow down potential causes because it only happens in production builds and I don't think it has been raised as an issue here before. Even if you close as won't fix hopefully it will save someone time!

Thanks for your great work.

**Comment by kitten** [comment]
In general, we don't support `@import` in our global styles. It may work, but #3146 is a potential blocker. I personally don't really see the point of using `@import` when you already have a CSS file URL and can embed it into the HTML/DOM directly. I'm open to merge any PR on styled-components-website that does add documentation for this, if it doesn't exist already, but for now I'm closing this issue due to its age.
