### ISSUE TITLE
Augmenting children when defining styled components

### ISSUE THREAD

**Issue by sami616** [styled-components/styled-components#2529]
Im trying to closely couple a ```<fieldset>``` with my styled form component by wrapping passed children in it - however the following example doesn't seem to work.

```
export const StyledForm = styled.form.attrs(({ children, disabled }) => ({
  children: <fieldset disabled={disabled}>{children}</fieldset>,
}))`
  /* styles */
  fieldset {
    /* styles */
  }
`
```

I did notice however, that using a different prop name (ie - not ```children```) seems to work as expected.

```
export const StyledForm = styled.form.attrs(({ myChildren, disabled }) => ({
  children: <fieldset disabled={disabled}>{myChildren}</fieldset>,
}))`
  /* styles */
  fieldset {
    /* styles */
  }
`
```

Is this expected behaviour? is the children prop not working because this is discouraged? would be really nice to use it instead of passing a custom prop!

**Comment by sami616** [comment]
For reference I have created an example here which uses this approach to build a custom checkbox here: https://codesandbox.io/s/q7r29042lq

**Comment by probablyup** [comment]
Doesn't look like this reproduction exists anymore. We changed some behavior of attrs in later v5 RCs that will likely fix your issue. Please feel free to reopen with a new reproduction if not.

**Comment by sami616** [comment]
yup, totally solves my problem. thanks!
