### ISSUE TITLE
Using styled component as selector with ":focus" attribute

### ISSUE THREAD

**Issue by BjoernRave** [styled-components/styled-components#2530]
## Steps to reproduce

Paste the following code : 

```jsx
import React from 'react';
import styled from 'styled-components';

const StyledInput = styled.input``;

const StyledBox = styled.div`
  background-color: blue;
  padding: 20px;

  ${StyledInput}:focus & {
    border: 5px solid green;
  }
`;

const Example = () => {
  return (
    <StyledBox>
      <StyledInput />
    </StyledBox>
  );
};

export default Example;

```

## Expected Behavior

When I focus the input it should add a border to the `StyledBox`

## Actual Behavior

Nothing happens when I focus the input

**Comment by BjoernRave** [comment]
I just found this: https://spectrum.chat/styled-components/general/target-parent-from-child-event~060e9d4f-1da8-45a9-ada4-ed2b14a175b1 . Will close this issue, seems like I need to use state to accomplish this

**Comment by Badial5** [comment]
Yes nothing happenes

**Comment by pecet3** [comment]
If someone still has this issue, use _focus-within_ instead _focus_
