### ISSUE TITLE
Make css tagged template produce valid styles for react-native 

### ISSUE THREAD

**Issue by mgcrea** [styled-components/styled-components#2533]
I've been using styled-components with react-native for a while and found out the current `css` export (tagged template) does not produce valid react-native styles.

For instance this code does not work:

```jsx
<View
  style={css`
   background-color: red;
   padding: 8px;
  `}
/>
```

Would be great and quite easy to produce a valid StyleSheet object (eg. `{backgroundColor: 'red', etc.}` in that case so that we can use inline css styles with react-native as well.

Can work on a PR if there is consensus on the feature.

Thanks!

**Comment by probablyup** [comment]
We very likely won't do this because the `css` export is meant to be used as an interpolation in styled-components, not as a standalone style generator.

**Comment by mgcrea** [comment]
Ok, maybe another helper specific to react-native and using another name, or do you think it's not aligned with the project's goals? Have a working version that could be released as a standalone tool if you don't consider it worthy of the official project. Thanks!

**Comment by probablyup** [comment]
Check out emotion, I think they do something like this.
