### ISSUE TITLE
Regression with `withComponent` and `defaultProps`

### ISSUE THREAD

**Issue by clentfort** [styled-components/styled-components#2534]
There is a regression between Styled Components 3.4.10 and 4.2.0 in which the behavior of `defaultProps` changes when used in combination with `withComponent`.

## Steps to reproduce

The following code works in [3.4.10](https://codesandbox.io/s/0m1zp6k7pw
) and crashes in [4.2.0](https://codesandbox.io/s/7j12406oyj).

```jsx
import React from "react";
import { render } from "react-dom";
import styled from 'styled-components';

const STYLES = {
  fallback: {
    color: 'red',
  },
}

const A = styled.div`
  color: ${({styling}) => STYLES[styling].color};
`

A.defaultProps = {
  styling: 'fallback',
}

const B = ({...props}) => <div {...props} />
const C = styled(A.withComponent(B))``; 

render((<C>text</C>), document.getElementById("root"));
```

## Expected Behavior

The component to render `text` in a red font. 

https://codesandbox.io/s/0m1zp6k7pw

## Actual Behavior

The execution crashes with error `STYLES[styling] is undefined`. This is because `styling` is `undefined` instead of `fallback` (as specified in the `defaultProps` of `A`), leading to an access of `STYLES[undefined].color`.

https://codesandbox.io/s/7j12406oyj

**Comment by konojunya** [comment]
@clentfort Although it is not directly related to this issue, it seems safer to implement it with another method because withComponent is deprecated.

https://www.styled-components.com/docs/api#withcomponent

**Comment by clentfort** [comment]
@konojunya This is an undocumented regression in version 4 of styled-components. A regression in the world of software describes the appearance of a bug which was absent in a previous revision.

I am aware that `withComponent` is a candidate for deprecation, it is not deprecated yet. Therefore it should work in v4 as it did in v3.

**Comment by StevenLangbroek** [comment]
@clentfort there's work in progress to add an `innerAs` prop, which would allow you to correctly propagate an `as` prop down to the root styled component, would that solve your use-case? I think people are generally reluctant to work on features they know are not long for this world, so if we can find a different code path that works for your use-case, that would prevent unnecessary work on our side.

**Comment by StevenLangbroek** [comment]
@clentfort would #2573 solve your problem?

**Comment by clentfort** [comment]
We solved it by exporting the `defaultProps` and re-assigning these at the places were our app broke. I know people don't want to work on soon to be deleted stuff and I don't expect anyone too. I think this breaking change should be better documented though. :)

**Comment by probablyup** [comment]
Open to a PR

**Comment by probablyup** [comment]
Closing, feel free to make a documentation PR against the website!
