### ISSUE TITLE
Different results between "style.View" and "View" from react native

### ISSUE THREAD

**Issue by felipesdias** [styled-components/styled-components#2537]
## System:
 - OS: Windows 10
 - CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
 - Memory: 4.72 GB / 15.92 GB
## Binaries:
 - Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
 - npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

## Problem

Page with two containers:
![image](https://user-images.githubusercontent.com/24731835/57496427-4f7ad400-72a9-11e9-9be6-9f7becce71d4.png)
```
import styled from 'styled-components/native';

export const Container = styled.View`
  flex: 1;
  background: #cccccc;
`;

export const LogoContainer = styled.View`
  flex: 1;
  background: #ddd;
  justify-content: center;
  align-items: center;
`;

export const Logo = styled.View`
  width: 150px;
  height: 150px;
  background: #eee;
`;

export const FormContainer = styled.View`
  flex: 1;
  background: #000;
  justify-content: center;
  align-items: center;
`;
```

In the TwoButtons component:
![image](https://user-images.githubusercontent.com/24731835/57496473-98328d00-72a9-11e9-8d52-02699f258892.png)
```
import styled from 'styled-components/native';

export const Container = styled.View``;

export const Button = styled.Button`
  width: 100px;
  height: 30px;
  background: #fff;
  margin-top: 10px;
`;
```

When I use "Container" a got this (Incorrect):
![image](https://user-images.githubusercontent.com/24731835/57496495-b13b3e00-72a9-11e9-826c-a81dce521c75.png)

If I replace "Container" with "View" direct from react, I got this (Correct):
![image](https://user-images.githubusercontent.com/24731835/57496506-cadc8580-72a9-11e9-95fd-b4d6787942e9.png)

Thanks.

**Comment by probablyup** [comment]
@felipesdias would you mind trying the v5 beta and let us know if that changes anything? The way RN is required is slightly different which might have an effect.
