### ISSUE TITLE
_styledComponents.default.svg is not a function

### ISSUE THREAD

**Issue by yasser17** [styled-components/styled-components#2539]
Hi, I can not use svg component on react-navite app. I'm new working with react-native and styled components, maybe I did something wrong.

Packages version:

"react": "16.8.3",
"react-native": "0.59.5",
"styled-components": "^4.2.0"

```
import styled from 'styled-components'
import { getStatusBarHeight } from 'react-native-iphone-x-helper'

export const Container = styled.Viewpadding-top: ${getStatusBarHeight()}px; height: 300px; background: #007FFF; width: 100%;;

export const BaseCurve = styled.svg`
width: 100%;
flex: none;`
```

```
import React from 'react';

import {
Container, BaseCurve
} from './styles'

export default function Header () {

return (
    <Container>            
        <BaseCurve viewBox="0 0 20 20"> 
            <path d="M1125,954.6v-74.3c-137.2,40.6-338.3,66.2-562.5,66.2S137.2,920.9,0,880.3v74.3H1125z" />
        </BaseCurve>
    </Container>
);
}
```

Chrome's console showed this error:

ExceptionsManager.js:74 _styledComponents.default.svg is not a function

**Comment by probablyup** [comment]
In react-native you can only use components that react-native provides. Here's the list: https://github.com/styled-components/styled-components/blob/4115a1f8e4814b3843d781ce84d686c998ddfd3e/packages/styled-components/src/native/index.js#L23-L29
