### ISSUE TITLE
Several instances of 'styled-components' initialized in this application.

### ISSUE THREAD

**Issue by zeeshanaligold** [styled-components/styled-components#2543]
Error: Trying to insert a new style tag, but the given Node is unmounted!

- Are you using a custom target that isn't mounted?
- Does your document not have a valid head element?
- Have you accidentally removed a style tag manually?

Having this issue. any one help me to fix?

**Comment by probablyup** [comment]
You probably have two instances of the same version of s-c on the page at
once. We’re tolerant of multiple versions as of v4 but not multiple of the
same version. Try and utilize deduping via your package manager

**Comment by zeeshanaligold** [comment]
@probablyup  here is the app structure. I'm just installing in client via npm i -s ../localmodule
/client
/localmodule/

**Comment by zeeshanaligold** [comment]
here is localmodule webpack.config.js

var path = require('path')

module.exports = {
  entry: './src/index.js',
  output: {
    path: path.resolve(__dirname, 'build'),
    filename: 'index.js',
    libraryTarget: 'commonjs2',
  },
  module: {
    rules: [
      {
        test: /\.(js|jsx)$/,
        include: path.resolve(__dirname, 'src'),
        exclude: /(node_modules|bower_components|build)/,
        use: {
          loader: 'babel-loader',
        },
      },
    ],
  },
  resolve: {
    extensions: ['*', '.js', '.jsx'],
    alias: {
      'styled-components': require.resolve('styled-components'),
    },
  },
  externals: {
    react: {
      commonjs: 'react',
      commonjs2: 'react',
      amd: 'React',
      root: 'React',
    },
    'react-dom': {
      commonjs: 'react-dom',
      commonjs2: 'react-dom',
      amd: 'ReactDOM',
      root: 'ReactDOM',
    },
    'styled-components': {
      commonjs: 'styled-components',
      commonjs2: 'styled-components',
      amd: 'styled-components',
    },
  },
}

**Comment by zeeshanaligold** [comment]
@probablyup 
I already did try deduping. Also in styled component documentation it is mentioned that

> npm dedupe doesn't work well with symlinked folders (i.e., when you use npm link)

**Comment by snowy-dong** [comment]
@zeeshanaligold  you  can  try  version 3.0.0 ~ 3.1.6

**Comment by probablyup** [comment]
See this FAQ article for more info: https://www.styled-components.com/docs/faqs#why-am-i-getting-a-warning-about-several-instances-of-module-on-the-page

**Comment by jamime** [comment]
> We’re tolerant of multiple versions as of v4 but not multiple of the
same version

This has been such a headache for me. It would be great to see this mentioned explicitly in the docs especially as micro-frontends become more prevalent.

**Comment by jacktan165** [comment]
For people who have a mono-repo with a shared library, just move `styled-components` from your dependencies to devDependencies and peerDependencies.

**Comment by mattvb91** [comment]
Does anyone have a solution getting this to work with typescript? None of the above solutions work in any way. The FAQ article doesnt help either

**Comment by wakaztahir** [comment]
I couldn't fix this issue either , have been at it for two days , Here's my stackoverflow question

https://stackoverflow.com/questions/76672848/several-instances-of-styled-components-initialized-in-this-application

I am using gatsby. The code is available at https://github.com/Qawaz/qal-ui/
