### ISSUE TITLE
Function with parameters doesn't work inside Styled Component with destructured props

### ISSUE THREAD

**Issue by dawidk92** [styled-components/styled-components#2547]
### System:
 - OS: macOS 10.14.4
 - CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
 - Memory: 141.54 MB / 8.00 GB
 - Shell: 3.2.57 - /bin/bash
### Binaries:
 - Node: 10.4.0 - ~/.nvm/versions/node/v10.4.0/bin/node
 - Yarn: 1.13.0 - ~/.nvm/versions/node/v10.4.0/bin/yarn
 - npm: 6.9.0 - ~/.nvm/versions/node/v10.4.0/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
### npmPackages:
 - babel-plugin-styled-components: ^1.10.0 => 1.10.0 
 - styled-components: ^4.2.0 => 4.2.0 

## Reproduction

https://codesandbox.io/s/z61p9434mm?fontsize=14

## Expected Behavior
I want to use functions with parameters (i.e. padding() from `polished`) inside Styled Component with **DESTRUCTURED** props.

## Actual Behavior
When function has parameters it breaks returned CSS.

In provided [reproduction](https://codesandbox.io/s/z61p9434mm?fontsize=14) broken component returns:
```
background: ,red,;
```

and in case with `polished` padding function it returns:
```
[object Object]: ;
```

**Comment by konstantin-chukharev** [comment]
@dawidk92 you have to use `css` helper when you use this approach:
```javascript
const BrokenComponent = styled.div(
  ({ fontSize, align }) =>`
    ${stylesWithParams("red")};
    font-size: ${fontSize};
    text-align: ${align};
  `
);
```
Should be:
```javascript
const BrokenComponent = styled.div(
  ({ fontSize, align }) => css`
    ${stylesWithParams("red")};
    font-size: ${fontSize};
    text-align: ${align};
  `
);
```

Here is the fixed example: https://codesandbox.io/s/ps6z3?fontsize=14

**Comment by dawidk92** [comment]
@konstantin-chukharev thank you very much! :)
