### ISSUE TITLE
How to override react-admin <Create /> css

### ISSUE THREAD

**Issue by kopax** [styled-components/styled-components#2548]
Hi everyone!

I am using `react-admin` that use material-ui inside.

I'd like to understand how I can override style when the component is nested.

I have tried to set a prefix, but the sub components that I do not possess within the `<Create />` doesn't help with their dynamic classes.

example:

```js

const createStyles = {
  card: {
    boxShadow: 'none',
    borderRadius: 0,
  },
  toolbar: {
    root: {
      backgroundColor: 'transparent',
    },
  },
};

const Create = styled(withStyles(createStyles)(function Create({ classes, ...rest }) {
  return (
    <CreateDefault
      classes={{
        card: classes.card,
        MuiToolbar: classes.toolbar
      }}
      {...rest}
    />
  );
}))`
  && {
    background: blue;
    input {
      border: 2px solid red;
    }
  }
`;

```

I am playing with both material ui and styled, to get sub components styled in a way I desire, but I am not able to because:

- generated classe names change in production
- I don't know how to edit jss within `<Create />`, I keep trying
- no possibility to add classname except to the root component.

How should I target what's within the `<Create />`?

Thanks a lot for ideas.

**Comment by probablyup** [comment]
Can you provide a codesandbox? Hard to help without some sort of easy reproduction case.
