### ISSUE TITLE
Needs a tool to automatically translate sass to styled components.

### ISSUE THREAD

**Issue by zhangriyueming** [styled-components/styled-components#2549]
In many situations, we got a project with sass, and we want to migrate it to styled component. Because we ❤️ styled components.

But often there are more than hundreds lines of sass codes. 

And I know there is an approach to translate variables from sass by  `sass-extract` and `sass-extract-js`. But is there any automatic tool to translate the sass codes which using these variables. i.e. `color: $sass-font-color;` => `color: ${props => props.theme.sassFontColor}` in all sass files? Before do it by self implementing a very simple and basic tool, I just think this should be a commonly needs, and if there was a handy and powerful tool to completely translate sass to styled-component would be an absolutely lifesaver.

**Comment by StevenLangbroek** [comment]
So, adding this code to sass should be relatively straightforward, I'm just not sure what the value of it would be over, say, a custom IDE snippet... What you end up with is invalid sass, and you'd need to carefully copy-paste your sass-code over to js or ts files anyway... It's definitely out of scope for styled-components itself, but if you want to take a stab at it, this sounds like something we'd love to link to in [awesome-styled-components](/styled-components/awesome-styled-components).
