### ISSUE TITLE
Flow errors about react-native and fbjs

### ISSUE THREAD

**Issue by ggregoire** [styled-components/styled-components#255]
Hey!

Version: 1.1.1

I still got errors about react-native and fbjs, even with the recent commits.

![screen shot 2016-11-24 at 13 24 29](https://cloud.githubusercontent.com/assets/591804/20608663/6f135f80-b249-11e6-9e88-02aa4361545e.png)

It's a problem already invoked [here](https://github.com/styled-components/styled-components/issues/177#issuecomment-259429331) (fbjs) and [here](https://github.com/styled-components/styled-components/issues/177#issuecomment-259641792) (react-native).

My `.flowconfig`

```
[ignore]
<PROJECT_ROOT>/node_modules/fbjs/.*                       // needed for create-react-app
<PROJECT_ROOT>/node_modules/styled-components/src/.*

[options]
unsafe.enable_getters_and_setters=true
suppress_comment=.*\\$FlowIssue
```

Not sure but maybe we could just add `\\$FlowIssue` to fix those last errors?

Thanks for the help.

**Comment by relekang** [comment]
You also need to add some settings to the `libs` section. See [flow-support docs][] for more info

[flow-support docs]: https://github.com/styled-components/styled-components/blob/master/docs/flow-support.md

**Comment by ggregoire** [comment]
I had tried these settings but without installing `flow-typed`. 😅

So now that fixes the `react-native` errors but I still have the `fbjs` errors.

For your info: there are several types missing in the `Lodash` types definition (I got errors on `find` and `map`). These types are also missing in the original file. I'll submit a PR on [flowtype/flow-typed](https://github.com/flowtype/flow-typed).

**Comment by relekang** [comment]
Could you post the whole `.flowconfig`?

**Comment by ggregoire** [comment]
Here it is:

```
[ignore]
<PROJECT_ROOT>/node_modules/fbjs/.*
<PROJECT_ROOT>/node_modules/styled-components/src/.*

[libs]
flow-typed
node_modules/styled-components/flow-typed/react-native.js
node_modules/styled-components/flow-typed/glamor_vx.x.x.js
node_modules/styled-components/flow-typed/inline-style-prefixer_vx.x.x.js

[options]
unsafe.enable_getters_and_setters=true
suppress_comment=.*\\$FlowIssue
```

And the errors:

![screen shot 2016-12-01 at 23 37 56](https://cloud.githubusercontent.com/assets/591804/20824098/451c73e8-b81f-11e6-936e-e30bd4fd6aa8.png)

**Comment by hongymagic** [comment]
You should also add:

```
node_modules/styled-components/flow-typed/fbjs_vx.x.x.js
```

This should probably land in docs as well.

**Comment by ggregoire** [comment]
Actually this line

```
[ignore]
<PROJECT_ROOT>/node_modules/fbjs/.*
```

is [not needed anymore with Create-React-App](https://github.com/facebookincubator/create-react-app/pull/1152#discussion_r90945524).

By removing this line, I got rid of the errors.

I think we can close! 🎉
