### ISSUE TITLE
Styled components wrapping react components

### ISSUE THREAD

**Issue by LaraMo** [styled-components/styled-components#2550]
Is there a way to wrap React components with a Styled component so that the style of the Styled component will apply to its children?

for ex: <StyledComponent> has `color:white` as style, therefore, <ReactComponent > and <AnotherReactComponent > will also have white text

```javascript
<StyledComponent>
   <ReactComponent />
   <AnotherReactComponent / >
<StyledComponent>
```

**Comment by ahtee** [comment]
Should be default behavior unless your children components have styles, with CSS the style will be applied to all children that have a matching selector or element.

**Comment by Avi98** [comment]
@LaraMo  if I'm understanding right you can create a global style like this ```javascript
import { createGlobalStyle } from 'styled-components'

const GlobalStyle = createGlobalStyle`
  body {
    color: ${props => (props.whiteColor ? 'white' : 'black')};
  }
`

// later in your app

<React.Fragment>
  <GlobalStyle whiteColor />
  <Navigation /> {/* example of other top-level stuff */}
</React.Fragment>

```

**Comment by probablyup** [comment]
@ahtee is correct. Just make a parent styled component with `color: white;` in the style:

```js
const Parent = styled.div`
  color: white;
`;
```
