### ISSUE TITLE
Support loading property for Image

### ISSUE THREAD

**Issue by AjayPoshak** [styled-components/styled-components#2552]
## Feature Request

Chrome announced support of `loading` attribute to allow lazy loading of images natively.  While using the loading attribute on images styled using styled-components, this attributes is not passed to DOM.  Hence, we're not able to utilise this capability.

## Expected Behavior
const Image = styled.img ``

`<Image src='abc.com/image/1.jpg' alt='image' loading='lazy' />`

## Actual Behavior
const Image = styled.img ``

`<Image src='' alt='image'  />`

Reference: https://addyosmani.com/blog/lazy-loading/

**Comment by probablyup** [comment]
Hey there, we use the `@emotion/is-prop-valid` package for this. Feel free to make a PR against them to get this supported. Here's the relevant file: https://github.com/emotion-js/emotion/blob/master/packages/is-prop-valid/src/props.js

**Comment by AjayPoshak** [comment]
Cool, will do that.

**Comment by Andarist** [comment]
@probablyup would love your input on https://github.com/emotion-js/emotion/issues/1362#issuecomment-495873283
