### ISSUE TITLE
-webkit-overflow-scrolling: touch;

### ISSUE THREAD

**Issue by rwieruch** [styled-components/styled-components#2556]
As far as I know, styled-components uses stylis.js to apply PostCSS. Is this still the case? 

In my application, I would love to have a PostCSS addition to get the momentum scrolling back on iOS devices.  Without PostCSS, you can set `-webkit-overflow-scrolling: touch;` to give your `overflow-y: auto;` a smooth scroll experience (e.g. on iOS iPad). 

PostCSS offers this [as plugin](https://github.com/solversgroup/postcss-momentum-scrolling) and I am wondering whether this is available in stylis.js (in case this is still used in styled-components) as well. If yes, I might need to open an issue over there too.

**Comment by probablyup** [comment]
We haven't used postcss for a while actually. In v5 we will probably have a more customizable setup for providing your own stylis plugins though that could do something like this.
