### ISSUE TITLE
Issue with SSR styling order

### ISSUE THREAD

**Issue by mahadazad** [styled-components/styled-components#2559]
## Environment
 - OS: macOS 10.14.3
 - CPU: (8) x64 Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
 - Memory: 198.23 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 10.5.0 - ~/.nvm/versions/node/v10.5.0/bin/node
 - Yarn: 1.12.1 - ~/.yarn/bin/yarn
 - npm: 6.1.0 - ~/.nvm/versions/node/v10.5.0/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman

## Reproduction
https://codesandbox.io/s/withstyledcomponents-720sb

## Steps to reproduce
- Integrate styled-components SSR with nextjs

## Expected Behavior
- The global styles render first.

## Actual Behavior
- The global styles render in the last.

**Comment by StevenLangbroek** [comment]
Can you explain what issues this is causing? Is there a flash of unstyled / misstyled content?

**Comment by mahadazad** [comment]
I was having some css overriding issue that I am not able to reproduce here. I will close the issue until I encounter the issue again.
