### ISSUE TITLE
Usage of ThemeProvider in styled components

### ISSUE THREAD

**Issue by puru0019** [styled-components/styled-components#2560]
I was using theme provider to check some conditions and rendering css properties based on the condition
Following is approach i was following 

```
const options = {
    type: 'switch',
    required: true,
 };
```

```
<ThemeProvider theme={options}>
     <StyledFormGroup>
           <StyledFormField/>
     </StyledFormGroup>
</ThemeProvider>
```

```
const StyledFormGroup= styled.div`
  display: ${({ theme }) => (theme.type !== 'switch') && 'flex'};
  flex: ${({ theme }) => (theme.type === 'switch') && '1'};
`;
```

Is this way of using theme is against the styled component principles. I can see in lot examples that theme is only used for colors or the background colors.

But the above example is different from that.

@mxstbr or anyone can please suggest on this approach

**Comment by StevenLangbroek** [comment]
Nope this is fine. We do this a lot, and are planning a dark/light theme switch based on this type of behavior. The only caveat, keep these functions pure, and not depending on `window` / `window.matchMedia` for example, as it can lead to unexpected results if you do server-side renderiing.
