### ISSUE TITLE
External bundle/extension make style lost

### ISSUE THREAD

**Issue by andyyou** [styled-components/styled-components#2562]
## System:
 - OS: macOS 10.14.5
 - CPU: (4) x64 Intel(R) Core(TM) i7-4650U CPU @ 1.70GHz
 - Memory: 55.93 MB / 8.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 10.15.0 - ~/.nvm/versions/node/v10.15.0/bin/node
 - Yarn: 1.16.0 - ~/.nvm/versions/node/v10.15.0/bin/yarn
 - npm: 6.9.0 - ~/.nvm/versions/node/v10.15.0/bin/npm
## npmPackages:
 - styled-components: ^4.2.0 => 4.2.0

## Reproduction

https://github.com/andyyou/styled-components-issue-demo

## Steps to reproduce

In this example, app.js represent the role of a site, and extension.js represents an extension from the third party. Both using styled-components.

You can use `npm start` to run the demo. At first it's work fine, then when you add extension.js no matter by `<script src="extension.js"></script>` or `document.body.appendChild()` in componentDidMount of app.js, even by `content script` of chrome extension It will broke B's style.

More information is described in [README](https://github.com/andyyou/styled-components-issue-demo/blob/master/README.md)

## Expected Behavior

Style should exists.

## Actual Behavior

Some style missed.

**Comment by probablyup** [comment]
The same version of the styled-components runtime added multiple times to the same page will clobber each other. It's recommended in this use case to make a DLL bundle that provides styled-components or use the CDN version. https://www.styled-components.com/docs/faqs#running-multiple-applications-on-one-page
