### ISSUE TITLE
How can webpack resolve assets url to a path rather than import them manually?

### ISSUE THREAD

**Issue by Coder-JJ** [styled-components/styled-components#2564]
How can webpack resolve assets url to a path rather than import them manually?

```js
import styled from 'styled-components'

let Div = styled.div`
  background-image: url('./images/test.png')
`
```

because converts all assets to base64 code will increase the bundle size, especially those big images.

**Comment by StevenLangbroek** [comment]
This is outside of scope of `styled-components`, but you can use `url-loader` instead of `file-loader` and set a limit to how big a file can be before it switches to file instead of base64:

https://webpack.js.org/loaders/url-loader

**Comment by StevenLangbroek** [comment]
Closing issue, if you'd like help implementing this, there's plenty of helpful folks over at our [Spectrum](https://spectrum.chat/styled-components/) that can point you in the right direction ✌️
