### ISSUE TITLE
What is the expected bundle size of styled-components for production (Using Webpack) ?)

### ISSUE THREAD

**Issue by talentedandrew** [styled-components/styled-components#2566]
**styled-components version  4.2.0** 
What's the expected bundle size of styled-components for production when bundling using webpack. I'm getting 23.6 KB. Is there any scope to further reduce the bundle size for production using any webpack plugin? Please find below the bundle analysis for reference.

<img width="500" alt="Screenshot 2019-05-29 at 3 28 34 PM" src="https://user-images.githubusercontent.com/15646138/58548519-176f0d00-8227-11e9-92f1-03d3ab291ea0.png">

**Comment by StevenLangbroek** [comment]
Do you inject `NODE_ENV` as `production` using something like `DefinePlugin`? It's supposed to be about 15kb / 16kb if I recall correctly?

**Comment by StevenLangbroek** [comment]
I'd also take a look at the docs' Tooling section, as it has tips for how to further reduce your bundle size: https://www.styled-components.com/docs/tooling#minification
