### ISSUE TITLE
Vim syntax highlight

### ISSUE THREAD

**Issue by sylvainbannier** [styled-components/styled-components#257]
Here's a very basic workaround to support CSS syntax highlighting in vim inside styled components blocks. I intend to do better, but it is none the less an usable solution.

Add this to you `.vimrc`
```
function! EnableStyledComponentsCSS() abort
  if exists('b:current_syntax')
    let s:current_syntax=b:current_syntax
    unlet b:current_syntax
  endif
  syntax include @CSS syntax/css.vim
  if exists('s:current_syntax')
    let b:current_syntax=s:current_syntax
  else
    unlet b:current_syntax
  endif
  syntax region textSnipcss matchgroup=StyledComponents start=/styled.*`/ end="`" contains=@CSS
endfunction

autocmd FileType javascript.jsx call EnableStyledComponentsCSS()
```

Please be aware that vim CSS syntax will only work if CSS rules are enclosed in brackets. You can achieve it like that : 
```
const MyComponent = styled.div`&{
  color:black
}`
```

**Comment by fleischie** [comment]
I would also like to see syntax and indentation support for vim. I would like to try out the above-mentioned solution from @sylvainbannier and remove the default-workaround `&{ ... }`.

**Comment by fleischie** [comment]
Hey.

I created a super simple vim-bundle for syntax highlighting and indentation: [vim-styled-components](https://github.com/fleischie/vim-styled-components). It more or less copies all the main CSS syntax highlighting and indentation to files, where `import .. from ... 'styled-components'` is present.

I'd love it if you came by and gave notes. :smile:

**Comment by mxstbr** [comment]
@garetmckinley might be interested in the above too!

**Comment by mxstbr** [comment]
Hmm, doesn't seem to be working for me in MacVim with https://github.com/jordwalke/VimBox... 😕

![screen shot 2016-12-04 at 09 49 34](https://cloud.githubusercontent.com/assets/7525670/20865042/0427c4f2-ba07-11e6-8d31-6c5a4334824b.png)

**Comment by garetmckinley** [comment]
It works in my neovim setup fairly well. There's a few syntax anomalies present in my 'complex' demo, but it's certainly a great start—and a **ton** better than having no highlighting at all. I feel like my vim setup is finally viable for working on my `styled-components` projects 😍

![screen shot 2016-12-04 at 11 07 35 am](https://cloud.githubusercontent.com/assets/1624279/20867445/7952e8aa-ba12-11e6-8fda-8d410870d725.png)

**Comment by fleischie** [comment]
@mxstbr do you mean my bundle? And did you install it via NeoBundle? I had some troubles using the default install hooks of VimBox and had to install the bundle manually.

**Comment by mxstbr** [comment]
I did use NeoBundle, I put this in `~/.vim/vimrc.custom.after`:

```vim
NeoBundle 'fleischie/vim-styled-components'
```

**Comment by fleischie** [comment]
I check how VimBox handles NeoBundles tomorrow and report back as soon as I know, where the problem might be.

Did you have this problem with any other plugins so far?

**Comment by mxstbr** [comment]
Nope, all the others work perfectly fine...

**Comment by sylvainbannier** [comment]
@fleischie thanks, your plugin works for me (vim8/ubuntu)

**Comment by garetmckinley** [comment]
@mxstbr is this only happening in MacVim or in the cli as well?

**Comment by mxstbr** [comment]
@fleischie that's just because I looked if I had a `styled-components` option in the menu, but I don't even have that option 😢

**Comment by fleischie** [comment]
@mxstbr sorry to be persistent on this: Do you have any other plugins in `~/.vim/vimrc.custom.after`?

I have tried this out (again shout-outs to my gf for putting up with me, occupying her Mac 😚), and this doesn't install any plugins (of course I'm no expert at VimBox). But I managed to get it installed, when I put `https://github.com/fleischie/vim-styled-components` in the `~/.vim/bundlesVimRc.custom`.

Additionally, do you have `vim-styled-components` in `~/.vim/bundles`?

Thank you all for your feedback. 🙏 😄

**Comment by mxstbr** [comment]
Ahh, with in `bundlesVimRc.custom` it worked! 🎉

The color scheme seems to be a bit wonky though, do you know why?

<img width="1067" alt="screen shot 2016-12-07 at 07 40 53" src="https://cloud.githubusercontent.com/assets/7525670/20957506/8d081006-bc50-11e6-83e3-96190c5d1fc8.png">

**Comment by fleischie** [comment]
Yes, I know about this.

There are several issues so far because of different reasons: first own public project, first VimL project, very early release, CSS and JS syntax in same file.

I am going to improve the highlighting and indentation whenever I find time to work on it. I'm glad it works at all for you, which was my first priority as of now (making it work). :smile:

**Comment by sylvainbannier** [comment]
another workaround is to direcly toggle between syntax with `:set ft=css` & `set ft=javascript.jsx` (maybe with a mapping). It requires the `&{}` workaround too though

**Comment by fleischie** [comment]
@mxstbr the wonkiness should have decreased with the latest official update.
@sylvainbannier the indentation sadly did not. I still have to figure out how to sensibly extend `javascript.jsx` without introducing new issues.

**Comment by fleischie** [comment]
@sylvainbannier I just updated the plugin, which includes a major re-implementation of the indentation definitions. I basically thought the indentation process through, instead of copying the CSS definitions and hoping for the best. :stuck_out_tongue_winking_eye: 

So feel free to review the changes if you have time. :smile:

**Comment by mxstbr** [comment]
Seeing as @fleischie has done a great job with the plugin I'll close this issue. Thank you!
