### ISSUE TITLE
Product version of Styled-Components when render with Rendertron

### ISSUE THREAD

**Issue by AJ-7885** [styled-components/styled-components#2577]
https://stackoverflow.com/questions/56394337/issue-on-product-version-of-styled-components-when-render-with-rendertron

have very simple sample app which build Create React App + Styled-Components to prove this issue. But I have real big application which I am facing this issue which I am going to explain it below.

I would like to pre-render this app with Rendertron for SEO/GoogleBots and etc. But the problem is when I build PRODUCTION version of React App which use Styled-Components . all the style will be missing on static version which Rendertron produced, but from other side if I try the same workflow with dev-server of app , everything looks fine .

So far I know there is different on PROD version and DEV version of my application when I render it with Rendertron . But I am not sure what cause this issue and how I can fix this issue .

I am looking for solution or idea which can help me to solve this issue .

Here is my sample code which I peppered for test .

https://github.com/AJ-7885/test-styled-component-with-rendertron

Here is screen shot from different version of Rendered version by Rendertron base on PROD or DEV version of the same application .

![Screenshot 2019-05-31 at 13 30 12](https://user-images.githubusercontent.com/42003122/58704847-ac9c0e00-83ad-11e9-9cd4-e508c9f144bb.png)
![Screenshot 2019-05-31 at 13 28 05](https://user-images.githubusercontent.com/42003122/58704848-ad34a480-83ad-11e9-894b-a15e87c4e8ff.png)

**Comment by probablyup** [comment]
You probably need to disable speedy mode for prerendering purposes. Try building your app with this environment variable: `SC_DISABLE_SPEEDY=true`

**Comment by AJ-7885** [comment]
<img width="895" alt="Screenshot 2019-05-31 at 20 56 13" src="https://user-images.githubusercontent.com/42003122/58728151-978fa100-83e6-11e9-91bd-3e18785f6003.png">

I did not see any improvement even when I try to build it with this variable

**Comment by StevenLangbroek** [comment]
And if you leave out rendertron, but instead just run your app in production mode and access it directly? Everything works then?

**Comment by AJ-7885** [comment]
> And if you leave out rendertron, but instead just run your app in production mode and access it directly? Everything works then?

Yes , everything work fine , if I do not pass it to Rendertron, but because we like to client able to access to client version directly and google bots access to Rendertron version till Google can see our app/page correctly and able to index it page correctly we find this issue .

**Comment by probablyup** [comment]
If it's still not working with CSSOM injection turned off I have no idea. Our library is functioning as intended, must be a quick of how Rendertron works. I'd recommend opening an issue over there instead.

**Comment by AJ-7885** [comment]
Do you have any idea how we can disable Speedy mode in Create-React-App , because I did try your solution and seem the Speedy mode still active and not working .

**Comment by probablyup** [comment]
If you’re using CRA, environment variables have a special prefix. You’ll
have to wait for
https://github.com/styled-components/styled-components/pull/2501 to land
