### ISSUE TITLE
Passing theme explicitly in props

### ISSUE THREAD

**Issue by Schedulaar** [styled-components/styled-components#2578]
Feature request
=============================
Similar to https://github.com/styled-components/styled-components/issues/294, I would like to be able to pass a theme directly to a styledComponent (overriding the one supplied by ThemeProvider if existent).
Back then, this was fixed in https://github.com/styled-components/styled-components/commit/14c1c29deb7244129621a0333b2dc06b669f2f0d, but I suppose, this change was reverted by refactorings.

I imagine sth like:
```jsx
       {/* All children of this component will be red */}
        <ThemeProvider theme={redTheme}>
            <div>
                <Button>I'm red!</Button>
                <Button theme={yellowTheme}>I'm yellow!</Button>
            </div>
        </ThemeProvider>

```

This makes it easier to override the theme for single components and better testing.
Are there any caveats for having this?

Thanks

**Comment by probablyup** [comment]
That test still exists in v4 and it's passing...

**Comment by Schedulaar** [comment]
Hmm... 
For me the following sample: 
```js
const View = styled.View`
  ${props => {
    console.log(props.theme)
  }}
`

export default () => {
  return <View theme={{my: {theme: {}}}} />
}
```

logs an empty object instead of `{my: {theme: {}}}`

Does it make a difference that I use `styled-components/native`?

**Comment by probablyup** [comment]
Oh it could definitely matter if you're using react native, styledcomponent and stylednativecomponent are totally different implementations and have different sets of tests. Open to a PR for this!

**Comment by probablyup** [comment]
This also just got merged which might affect it https://github.com/styled-components/styled-components/pull/2567

**Comment by Schedulaar** [comment]
Yep, seems that was exactly what I was asking for! Awesome!

Is there any plan on when the next release is going to be?

Thanks :)

**Comment by probablyup** [comment]
Maybe this weekend, there are a couple other pending PRs

**Comment by probablyup** [comment]
This is out as of 4.3.x
