### ISSUE TITLE
Page flashes (re-renders) when using styled component 4.2.1

### ISSUE THREAD

**Issue by TheoMer** [styled-components/styled-components#2579]
os: Windows 10 Pro,   
Browser: Chrome version 73.0.3683.103 (Official Build) (64-bit),   
next: 8.1.0,    
styled-components: 4.2.1,   
babel-plugin-styled-components: 1.7.1   

So, when a route is selected (see attached gifs) it appears that font assets are re-requested, which in turn causes the page to flash (re-render).

**When using styled-component 4.2.1**

![styled-component-4 2 1](https://user-images.githubusercontent.com/15969262/58749621-1be23280-8480-11e9-98bd-bba31009a4e7.gif)

**When using styled-component 3.4.9**

![styled-component-3 4 9](https://user-images.githubusercontent.com/15969262/58749639-4cc26780-8480-11e9-93db-24b3b2aa354a.gif)

The issue is only visible on styled-components version 4.2.1 when the site has been deployed to production, not in development. As shown in the above gif, 3.4.9 does not display this issue.

The only difference in code is from using `injectGlobal` to using `createGlobalStyle`, as shown below.

What's the issue here?

styled-component 4.2.1

```
const GlobalStyle = createGlobalStyle`
  @font-face {
    font-family: 'radnika_next';
    src: url('/static/radnikanext-medium-webfont.woff2') format('woff2');
    font-weight: normal;
    font-style: normal;
  }
  html {
    box-sizing: border-box;
    font-size: 10px;
  }
  *, *:before, *:after {
    box-sizing: inherit;
  }
  body {
    padding: 0;
    margin: 0;
    font-size: 1.5rem;
    line-height: 2;
    font-family: 'radnika_next';
  }
  a {
    text-decoration: none;
    color: ${theme.black};
  }
  button {  
    font-family: 'radnika_next';
    color: ${theme.black};
  }
`;

const Page = props => {
  return (
    <ThemeProvider theme={theme}>
      <StyledPage>
        <GlobalStyle />
        <Meta />
        <Header />
        <Inner>{props.children}</Inner>
      </StyledPage>
    </ThemeProvider>
  );
}

export default memo(Page);
```

styled-component 3.4.9

```
injectGlobal`
  @font-face {
    font-family: 'radnika_next';
    src: url('/static/radnikanext-medium-webfont.woff2') format('woff2');
    font-weight: normal;
    font-style: normal;
  }
  html {
    box-sizing: border-box;
    font-size: 10px;
  }
  *, *:before, *:after {
    box-sizing: inherit;
  }
  body {
    padding: 0;
    margin: 0;
    font-size: 1.5rem;
    line-height: 2;
    font-family: 'radnika_next';
  }
  a {
    text-decoration: none;
    color: ${theme.black};
  }
  button {  
    font-family: 'radnika_next';
    color: ${theme.black};
  }
`;

const Page = props => {
  return (
    <ThemeProvider theme={theme}>
      <StyledPage>
        <Meta />
        <Header />
        <Inner>{props.children}</Inner>
      </StyledPage>
    </ThemeProvider>
  );
}
```

**Comment by StevenLangbroek** [comment]
Yeah this is "correct" behavior. You need to make sure your fonts have a correct caching policy (e.g., `max-age` header).

**Comment by TheoMer** [comment]
Hi @StevenLangbroek

> make sure your fonts have a correct caching policy

did you mean something like this?

```
res.setHeader('Cache-Control', 'must-revalidate, max-age: 86400');
```
