### ISSUE TITLE
Use warn & error from React when 16.9 drops

### ISSUE THREAD

**Issue by probablyup** [styled-components/styled-components#2584]
If 16.9 comes out before v5 is released, it'd be awesome to use these [new utils](https://github.com/facebook/react/pull/15170) that give more useful information like the component stack.

**Comment by ecreeth** [comment]
The `React.warn` and `React.error` were deleted. See [#16126](https://github.com/facebook/react/pull/16126)

**Comment by probablyup** [comment]
Damn that sucks. Thanks for the heads-up @ecreeth
