### ISSUE TITLE
Exclamation point (!) in block comment unapplies hydrated CSS

### ISSUE THREAD

**Issue by exogen** [styled-components/styled-components#2591]
## Reproduction

This repo demonstrates the issue:

https://github.com/exogen/styled-components-comment-hydration-bug

## Steps to reproduce

See above repo.

When a styled component is created with CSS like the following:

```js
const Styled = styled.div`
  /*! hello */
  .selector { color: red; }
`;
```

…then the style will seemingly be applied correctly during SSR, but upon hydration it will be unapplied.

The descendant selector makes a difference.

Additional details:
* Removing the `!` will make it start to work.
* If SSR is skipped so that it only renders client-side, it works fine.
* It seems similar to this issue: https://github.com/styled-components/styled-components/issues/888, except I tried both `minify: true` and `minify: false` and it's broken both ways.
* Broken in both production and development mode.

## Expected Behavior

Valid CSS syntax should not cause issues.

I noticed Stylis had a release some time ago with “support legal block comments `/*! */`” in it.

That makes me suspect it's not a Stylis parsing issue but rather something to do with SC's hydration.

## Actual Behavior

The style is unapplied when hydrated.

### System:
 - OS: macOS 10.14.5
 - CPU: (8) x64 Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz
 - Memory: 326.80 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
### Binaries:
 - Node: 8.9.4 - ~/.nvm/versions/node/v8.9.4/bin/node
 - Yarn: 1.16.0 - /usr/local/bin/yarn
 - npm: 6.9.0 - ~/.nvm/versions/node/v8.9.4/bin/npm
### npmPackages:
 - babel-plugin-styled-components: ^1.10.0 => 1.10.0
 - styled-components: ^4.2.1 => 4.2.1

**Comment by StevenLangbroek** [comment]
So, `stylis.js` definitely has a test in place for this:

![image](https://user-images.githubusercontent.com/296796/58808659-bb3b2d00-861a-11e9-8f88-e7c6c7135f73.png)

Will need to investigate further where this is happening. Thanks for submitting a full repro 🙇

**Comment by mxstbr** [comment]
@exogen can you try with `styled-components@canary-sheet`? We reworked the core stylesheet infrastructure for v5, I would love to know if that fixes it.

**Comment by probablyup** [comment]
It seems fixed with the alpha when I pulled down the repo and upgraded. Super weird issue.
