### ISSUE TITLE
Unable to load styled component styles at the end of the <head/> tag

### ISSUE THREAD

**Issue by puru0019** [styled-components/styled-components#2592]
Hi

I was using RMWC library with styled components. When I import few component from rmwc, the css files are loading after my styled components styles. How can I load my styled component styles at the end of the head tag?

![image](https://user-images.githubusercontent.com/23036485/58780912-055ee700-85f8-11e9-97a6-64938162d613.png)

**Comment by StevenLangbroek** [comment]
You can't really, it's determined by load order (judging by a quick scan both SC and RMWC append). Is this causing issues in your project, and if so, can you describe them?

**Comment by probablyup** [comment]
This might help: https://github.com/styled-components/styled-components/pull/2463

**Comment by puru0019** [comment]
> You can't really, it's determined by load order (judging by a quick scan both SC and RMWC append). Is this causing issues in your project, and if so, can you describe them?

I have two repositories, One repository which has all the common components and the other repository uses these common components by importing them
I have used `npm link` to import common code to to current project(The screenshot above refers). The style tags which you see above and below styled component tag are coming from my common repository

Following is my webpack file

[webpack.config.js.zip](https://github.com/styled-components/styled-components/files/3250910/webpack.config.js.zip)

**Comment by puru0019** [comment]
> This might help: #2463

I believe PR is not merged yet.

**Comment by StevenLangbroek** [comment]
> I believe PR is not merged yet.

Correct. If you can't wait you can use a git commit reference in your package.json.

**Comment by puru0019** [comment]
> > I believe PR is not merged yet.
> 
> Correct. If you can't wait you can use a git commit reference in your package.json.

When will this PR get merged?

**Comment by probablyup** [comment]
It's not high priority so probably will be a 5.1 candidate PR

**Comment by GFwer** [comment]
I have the same problem. It's work correct with my own `Webpack` config. I find this problem after I migrate to `create-react-app`.

![image](https://user-images.githubusercontent.com/14303098/58942274-0b97c380-87b0-11e9-9a76-0c767575d59d.png)

**Comment by puru0019** [comment]
> I have the same problem. It's work correct with my own `Webpack` config. I find this problem after I migrate to `create-react-app`.
> 
> ![image](https://user-images.githubusercontent.com/14303098/58942274-0b97c380-87b0-11e9-9a76-0c767575d59d.png)
@GFwer can you share your webpack file

**Comment by puru0019** [comment]
> It's not high priority so probably will be a 5.1 candidate PR

Any update on this? Is it available in 5.1?

**Comment by kulazhenkoa-digicode** [comment]
Don't think that this is still actuall, but for me this solution fixed the problem. At the point of initialization ThemeProvider and Styles Provider here is injectFirst flag:

`<StylesProvider injectFirst>`

which is move all default styles of mui to top of the head. Found solution here: https://gist.github.com/Danilo-Araujo-Silva/2ce11fd0540dcc7eb3ad3e67fd75d02a#gistcomment-2935337

**Comment by florianmartens** [comment]
Still having the problem in Sep. 2021
