### ISSUE TITLE
Styled component overwrite react-bootstrap component class 

### ISSUE THREAD

**Issue by Link-69** [styled-components/styled-components#2593]
Hi, following this issue https://github.com/styled-components/styled-components/issues/2471
I have the same problem but I'm able to reproduce it. If I understood correctly the MenuLink styled component should inherit NavLink's class "nav-link" but doesn't.

## Reproduction
https://codesandbox.io/s/styled-components-od166?fontsize=14

Have I missed something from the doc or is that an actual issue? Thanks!

**Comment by probablyup** [comment]
Not sure why 4.2.1 is behaving weirdly, but I see the className working properly in my fork that just updates styled-components to latest: https://codesandbox.io/s/styled-components-zb1lo?fontsize=14

**Comment by Link-69** [comment]
Weird but thanks, gonna update my package!
