### ISSUE TITLE
keyframes/animations not working in IE11

### ISSUE THREAD

**Issue by joeattardi** [styled-components/styled-components#2594]
I have a simple CSS animation in a component using the `keyframes` helper. The animations work in all browsers except IE11, where they simply do not run. IE gives no error.

## Environment

```
## System:
 - OS: macOS 10.14.5
 - CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
 - Memory: 141.27 MB / 16.00 GB
 - Shell: 5.6.2 - /usr/local/bin/zsh
## Binaries:
 - Node: 8.11.4 - ~/.nvm/versions/node/v8.11.4/bin/node
 - Yarn: 1.15.2 - ~/.nvm/versions/node/v8.11.4/bin/yarn
 - npm: 6.5.0 - ~/.nvm/versions/node/v8.11.4/bin/npm
## npmPackages:
 - styled-components: ^4.2.0 => 4.2.1
```
## Reproduction

Relevant code is in this file: [https://github.com/joeattardi/react-snackbar-alert/blob/master/src/Snackbar.js](https://github.com/joeattardi/react-snackbar-alert/blob/master/src/Snackbar.js)

## Steps to reproduce

- Add some keyframes using the `keyframes` helper
- Use those keyframes in an animation in a styled component further down in the file
- View page in IE11

## Expected Behavior

Animations run

## Actual Behavior

Animations do not run

**Comment by probablyup** [comment]
Please provide a codesandbox :)

**Comment by joeattardi** [comment]
Ok, will try to get one set up.

**Comment by joeattardi** [comment]
Here is a codesandbox:

https://codesandbox.io/s/styled-components-n2tkl

Problem is, codesandbox currently isn't working in IE11, there are a bunch of JS errors in the console when trying to load the sandbox.

**Comment by probablyup** [comment]
Remade it in another client that supports IE11 and the animation seems fine: https://stackblitz.com/edit/react-q8xss1

Might just be your setup.

**Comment by joeattardi** [comment]
Ok. I'll have to take a closer look at my setup. Sorry for the bogus issue.

**Comment by probablyup** [comment]
No worries, it happens!
