### ISSUE TITLE
Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'nonce

### ISSUE THREAD

**Issue by TheoMer** [styled-components/styled-components#2596]
# Bug report

## Describe the bug
I continually get a nonce violation error, which for the life of me I cannot figure out why. On initial sever start both the nonce values in the `<Style />` tags and `style-src` are the same, but still the violation is issued. If I specify the `nonce` within the script-src attribute of csp, then no warnings are issued. What am I overlooking?

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

server.js
```
app.prepare().then(() => {
  server.get('*', function(req,res,next) {
    if(req.headers['x-forwarded-proto'] != 'https' && process.env.NODE_ENV === 'production')
    res.redirect('https://'+req.hostname+req.url)
    else
    next()
  });

  csp(server);

  server.get('/', (req, res) => ssrCache({ req, res, pagePath: '/' }));

  server.get('*', (req, res) => handle(req, res));

  server.listen(port, err => {
    if (err) throw err
    console.log(`> Ready on http://localhost:${port}`);
  })
})
```

csp.js
```
const helmet = require('helmet')
const uuidv4 = require('uuid/v4');

module.exports = function csp (server) {
    server.use((req, res, next) => {
    global.__webpack_nonce__ = res.locals.styleNonce = Buffer.from(uuidv4()).toString('base64');
    next()
    });

    const nonce = (req, res) => `'nonce-${res.locals.styleNonce}'`;
    const styleSrc = [nonce, "'self'"];
    const scriptSrc = ["'self'", 'https://*.stripe.com'];

    if (process.env.NODE_ENV !== 'production') {
        scriptSrc.push("'unsafe-eval'", "'unsafe-inline'");
    }

    server.use(helmet.contentSecurityPolicy({
        directives: {
            defaultSrc: ["'none'"], 
            scriptSrc, 
            connectSrc: ["'self'", 'localhost:4444', 'https://*.stripe.com'],
            imgSrc: ["'self'", 'https://*.cloudinary.com', 'data:', 'https://*.stripe.com'],
            styleSrc,
            fontSrc: ["'self'", 'data:'],
            objectSrc: ["'none'"], 
            formAction: ["'self'", 'https://*.stripe.com'],
            baseUri: ["'self'"],
            frameSrc: ["'self'", 'https://*.stripe.com'],
            frameAncestors: ["'none'"],
            reportUri: 'https://sentry.io/api/xxxxxx/security/?sentry_key=xxxxxx',
            upgradeInsecureRequests: true
        }
    }));
}
```

_document.js
```
const inlineScript = (body, nonce) => (
  <script
    type='text/javascript'
    dangerouslySetInnerHTML={{ __html: body }}
    nonce={nonce}
  />
)

  static async getInitialProps (ctx) {
    const sheet = new ServerStyleSheet()
    const originalRenderPage = ctx.renderPage

    try {
      ctx.renderPage = () =>
        originalRenderPage({
          enhanceApp: App => props => sheet.collectStyles(<App {...props} />)
        })

      const initialProps = await Document.getInitialProps(ctx)
      const { styleNonce } = ctx.res.locals

      return {
        ...initialProps,
        styleTags: (
          <>
            {initialProps.styles}
            {sheet.getStyleElement()}
          </>
        ),
        styleNonce
      }
    } catch (error) {
      //handle error
      console.error(error)
    } finally {
      sheet.seal()
    }
  }

  render() {
    const { styleTags, styleNonce } = this.props;
    return (
      <Html lang="en">
        <Head nonce={styleNonce}>
          {styleTags}
          {inlineScript(`console.log('Inline script with nonce')`, styleNonce)}
        </Head>
        <body>
          <Main />
          <NextScript nonce={styleNonce} />
        </body>
      </Html>
    );
  }
```

## Expected behavior

I expected a comparison of nonce values to facilitate proper loading of the site. 

## Screenshots

![csp-error](https://user-images.githubusercontent.com/15969262/58765068-c3d22b80-8566-11e9-8761-93378c64f459.jpg)

## System information

- OS: Windows 10 Pro
- Browser: Chrome Version 73.0.3683.103 (Official Build) (64-bit)
- Next.js: 8.1.0
- Styled components: 4.2.1
- uuid: 3.3.2
- helmet: 3.16.0

**Comment by TheoMer** [comment]
So, the issue and resolution I obtained from the following:

https://blogs.dropbox.com/tech/2015/09/csp-the-unexpected-eval/

> One issue we hit is that sometimes our client-side code downloads the template after the page load. Since the server-side generates a new nonce each time, the nonce on the template downloaded after page load would be different from the nonce for the main page. To mitigate this issue, we modified our code at the server side. Instead of creating a random nonce on each load, the script nonce for our pages is the hash of the CSRF tokens (note that the CSRF tokens are already random, unguessable values). This reduces the security of the nonce to the security of the CSRF token, but if an attacker knows the CSRF token, they can already take arbitrary actions for the user via CSRF attacks.

**Comment by brennanculture** [comment]
> So, the issue and resolution I obtained from the following:
> 
> https://blogs.dropbox.com/tech/2015/09/csp-the-unexpected-eval/
> 
> > One issue we hit is that sometimes our client-side code downloads the template after the page load. Since the server-side generates a new nonce each time, the nonce on the template downloaded after page load would be different from the nonce for the main page. To mitigate this issue, we modified our code at the server side. Instead of creating a random nonce on each load, the script nonce for our pages is the hash of the CSRF tokens (note that the CSRF tokens are already random, unguessable values). This reduces the security of the nonce to the security of the CSRF token, but if an attacker knows the CSRF token, they can already take arbitrary actions for the user via CSRF attacks.





https://linq-to-entitiescontempl.github.io/jcarousel718/
