### ISSUE TITLE
CSS-variables passed by styled-components applied to antd-component dissapears after compiling by webpack in production mode

### ISSUE THREAD

**Issue by RellaxxDev** [styled-components/styled-components#2599]
I'm using Ant-design with styled-components and want to theming my app by css-variables.

package.json:
```
"dependencies": {
...
"antd": "^3.19.1",
"styled-components": "^4.2.1",
...
}
..."webpack": "^4.29.6",
"babel-plugin-styled-components": "^1.10.0",
```
.babelrc:
```
{
  "plugins": [
    [
      "@babel/plugin-proposal-class-properties",
      {
        "loose": true
      }
    ],
    ["styled-components", {
      "minify": false,
      "ssr": false,
      "pure": true
    }]
  ],
  "presets": ["@babel/preset-env", "@babel/preset-react"]
}
```
App.js:
```
import { Input } from "antd";
import styled from "styled-components";
const StyledInput = styled(Input)`
  && {
    background-color: var(--primaryColor, #fff);
  }
`;
```
When i run my app in "development" webpack mode - everything ok,
i explore my input css in chrome:
`background-color: var(--primaryColor,#fff);`
then i changing webpack mode to "production", result is:
`background-color: #fff;`

If i tring add styles in style Input parameter and use webpack mode to "production" - result is ok:
```
 <StyledInput
        type="text"
        placeholder={placeholder}
        value={inputValue}
        style={{
             backgroundColor: var(--primaryColor,#fff);
        }}
      ></StyledInput>
```
result:
`background-color: var(--primaryColor,#fff);`

So, this is styled-components behavior.

I tried all options of babel-plugin-styled-components - it doesn't help me at all.
How can i fix it? Help me please.

**Comment by RellaxxDev** [comment]
P.S. It turns out the problem is more serious. I can't pass most of css parameters(border for example) with css-variables at all, in this context. With default value or without.

**Comment by probablyup** [comment]
This is likely a CSSOM issue if it works in development.

**Comment by RellaxxDev** [comment]
> This is likely a CSSOM issue if it works in development.
If i don't use SC there aren't any problems. For example i can put css-variable in style prop of component.
And i can join css with css-variables - it works too. Problems only if i use SC((

**Comment by probablyup** [comment]
Relevant related issue on the topic: https://github.com/jhildenbiddle/css-vars-ponyfill/issues/23

**Comment by RellaxxDev** [comment]
This is CSSOM bug. SC knows this but doesn't consider it under the hood. Solution is adding 'style' tag... or adding style props... or adding css-file.... Crutches.

**Comment by ChristopherHButler** [comment]
@RellaxxDev Could you share your final configuration to get styled components working with react, webpack and antd? I am also having issues and would really appreciate being able to compare :)
