### ISSUE TITLE
::placeholder not prefixed

### ISSUE THREAD

**Issue by k15a** [styled-components/styled-components#260]
IIRC styled-components automatically vendor prefix rules. Unfortunately it looks like that it doesn't add prefixes to ::placeholder.

# Reproduction
http://www.webpackbin.com/VkbbM0Mfz

**Comment by rtsao** [comment]
This is an upstream issue: https://github.com/rofrischmann/inline-style-prefixer/issues/104

**Comment by jaydenseric** [comment]
Can this issue be reopened so it's back on the radar? It's still a problem and the upstream guys are not working on it because they don't feel it is in their scope.

**Comment by jaydenseric** [comment]
Related Glamor issue: https://github.com/threepointone/glamor/issues/14. It seems they [fixed it recently](https://github.com/threepointone/glamor/pull/179#issuecomment-273022476). I'm not familiar with how styled-components uses Glamor; does this mean we get the fix for free?

**Comment by SephReed** [comment]
It really would be nice if this happened

**Comment by mxstbr** [comment]
I'm very certain this has been fixed by now given we've switched that entire parsing pipeline.
