### ISSUE TITLE
how to use '@import-normalize' in createGlobalStyle

### ISSUE THREAD

**Issue by waryong322** [styled-components/styled-components#2600]
A few days ago, create-react-app v3 released.

create-react-app recommand '@import-normalize' for appling IE9~

I started through 'yarn create react-app project --typescript'

I configured global style through 'createGlobalStyle'

global-style.ts
```
import {createGlobalStyle} from 'styled-components';

const GlobalStyle = createGlobalStyle`
   @import-normalize;

   html {
      body {
      
      }
   }
`
```

this is create-react-app official example

because I didn't use index.css or index.scss,

I should import in createGlobalStyle

@import 'normalize' is answser;

but I wonder why create-react-app recommand @import-normalize

help me I wonder reaseon

thank you

**Comment by StevenLangbroek** [comment]
I think that's a question the folks over at `create-react-app` would gladly answer for you. It probably works because of some `css-loader` magic. Can you open a ticket with them (or ask on StackOverflow or some such). Good luck!
