### ISSUE TITLE
Can I get the final className before render

### ISSUE THREAD

**Issue by markstock7** [styled-components/styled-components#2601]
````
const Wrapper = styled.div`
  border: 1px solid blue;
 
  &__btn {
     color: red;
  }
`

class extends React.PureComponent<Props> {
  public render() {
    const wrapperClsName: string = (Wrapper as any).componentStyle.lastClassName
    const cls = bemClsFactor(wrapperClsName)
    return(
      <Wrapper>
        <button className={cls('btn')}>Hello World</button>
      </Wrapper>
    )
  }
}
````

LIke the code before, I want to using styled-components and bem together, I don't want every component inside the Wrapper styled. But the first time render I can't get lastClassName.
is there any other way to do this?

**Comment by probablyup** [comment]
`Wrapper.styledComponentId` will give you the static className of the component, but I don't really recommend using styled-components in this way.

What exactly are you trying to accomplish here? A reproduction in a codesandbox would be helpful.
