### ISSUE TITLE
[Request] Optional invariant violation when `theme` not found in props

### ISSUE THREAD

**Issue by haldunanil** [styled-components/styled-components#2605]
## Background

First off, great job with the library! We use `styled-components` for our internal component library and as a result, a lot of end users of our library don't know the implementation details of our components (and nor should they). The problem, however, is that because almost all components use the `theme` prop, not including the `ThemeProvider` at the top level of the application results in errors that appear like "Cannot find `colors.primary` of undefined". This isn't super clear to users who aren't familiar with how our library is structured (or that it even uses `styled-components` under the hood) and results in a lot of confused Slack messages.

## Request / Idea

Similar to how `react-router-dom` handles it (i.e. `Error: Invariant failed: You should not use <Route> outside a <Router>`), it would be great if there was a way to enable invariant violations when the `theme` prop is not found. Ideally, the error message itself would be customizable since in our case, we don't use the `ThemeProvider` component directly but as part of another component.

If there is any interest in adding a feature like this, I could get a PR going. Lmk!

**Comment by probablyup** [comment]
I'm fine with adding this behind a "not production" check. Want to add it against the canary branch?

**Comment by haldunanil** [comment]
Sounds good, I'll open a PR here once I have something tangible

**Comment by probablyup** [comment]
Ok I think I misunderstood what you meant. I thought you were talking about throwing if you use `ThemeProvider` but don't pass a theme. If you're talking about enforcing a certain prop for styled-components, that's much better enforced via a linting rule and doesn't belong in core.

**Comment by haldunanil** [comment]
The potential problem with linting might be that it's difficult to have it be aware of the internals of the styled-component (i.e. answering the question "is `theme` referenced?") when checking for props. That's the functionality I wanted to introduce here.

**Comment by probablyup** [comment]
I hear you, but core is reserved for generally-applicable functionality. Stuff that's specific to your own workflow belongs in userland

**Comment by haldunanil** [comment]
Just for my own understanding, why do you think it's not more generally applicable? I'm probably missing some sort of edge case here 😳

**Comment by probablyup** [comment]
I rarely see components using styled-components that pass a theme prop to the component instead of just using `<ThemeProvider>` by itself.

**Comment by haldunanil** [comment]
The goal here was to catch the scenario where a user has a styled component, let's say `styled.div` that references a `theme` prop but that prop isn't passed anywhere. Similar to what you said, my goal here was to alert the user when they _should_ be using a `<ThemeProvider>` but aren't, yet referencing a `theme` that doesn't exist in a downstream styled-component. If you still don't think that's valuable, I'll let it go.

**Comment by probablyup** [comment]
Hmm ok, let me think about this some more

**Comment by Kadajett** [comment]
@haldunanil I think it's very valuable as it is potentially a speed bump for new users!

**Comment by phucanhapril** [comment]
@probablyup is there a way to disable this message? we store our `theme` object in a separate directory, and import `theme` into a file to use like
```
const Thing = styled.div`
  font-size: ${theme.font.size.l};
  position: absolute;
  right: ${theme.space.xxs};
  top: ${theme.space.s};
`;
```
we prefer this method since it takes up less space than `${props => props.theme.space.xxs}`. but now our test logs are getting clogged up with these warning messages, and i'd like to disable that please 😢

**Comment by probablyup** [comment]
@phucanhapril we removed the message in a later patch release
