### ISSUE TITLE
[Question] Why isn't a progressive enhancement approach recommended?

### ISSUE THREAD

**Issue by sgb-io** [styled-components/styled-components#2616]
In the documentation, under [Media Queries](https://www.styled-components.com/docs/advanced#media-templates), the primary example given shows some styling which is then overridden on mobile using a media query.

The approach displayed appears to be against the progressive enhancement thinking that many of us have come to consider the de-facto way of styling responsive components/apps for the web. It is not a new approach. Expanding into available space (in a single direction) is a much safer and faster approach than attempting to start at desktop, go down to mobile, and potentially the other way. I believe this is a well understood problem by now.

**My specific question is: why is a progressive enhancement approach not shown or explicitly recommended when using `styled-components`? Is this an intentional choice? Is there some background context that developers should have around this issue?**

For additional context, I have unfortunately stumbled into this problem first hand, where I have inherited code that styles many components in this "inverse" way, and it's very difficult to maintain.

**Comment by mxstbr** [comment]
We should get rid of that section, it is really an out-of-place recommendation for us to make. People should style their apps however they please.

I would love a PR that removes that entire section!

**Comment by lukyth** [comment]
Sounds easy. I'm gonna help you with this.
