### ISSUE TITLE
Single quote broken styled execution

### ISSUE THREAD

**Issue by lksilva** [styled-components/styled-components#2618]
## Reproduction

When put a single quote into css propertie, this component compute hash key but don't apply style for component and broken all styled-component in tree
```js
const TopContainer = styled.div`
  min-height: 175px'
`;
```

## Expected Behavior

In my opinion the correct behavior is throw a exception!

## Actual Behavior

The component generates unique class name but not apply style for any component
<img src="https://i.imgur.com/4iK4z8b.png" >

**Comment by probablyup** [comment]
Great issue to raise for stylis. We don’t process the styles at this level
in styled-components core.

**Comment by lksilva** [comment]
There is a way to contribute and I resolve this problem? I mean, do you have any suggestion

**Comment by probablyup** [comment]
Like I said it’s not a thing in our repository. Processing of the styles
happens in stylis.js

**Comment by lksilva** [comment]
Ohh Thanks! I will open a issue in stylis lib
