### ISSUE TITLE
Arithmetic operations not working with variables in css

### ISSUE THREAD

**Issue by imkrunal** [styled-components/styled-components#2619]
## System:
 - OS: macOS 10.14.1
 - CPU: (4) x64 Intel(R) Core(TM) i7
 - Memory: 24.42 MB / 8.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 12.3.1 - /usr/local/bin/node
 - Yarn: 1.16.0 - /usr/local/bin/yarn
 - npm: 6.9.0 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: ^1.10.0 => 1.10.0
 - styled-components: ^4.3.1 => 4.3.1

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`

## Reproduction
```
<div
  css={css`
    max-width: ${maxWidth + 80}px;
  `}
>
{children}
</div>
```

## Steps to reproduce
1. import { css } from 'styled-components'
2. Pass random or default maxWidth 

## Expected Behavior
it should increase max-width by 80. suppose maxWidth is 720 then it should give 800px

## Actual Behavior

instead of that if I pass maxWidth 720 the output is 72080px.

if I do something like this it's working
```
${720 + 80}px;
```

**Comment by probablyup** [comment]
@imkrunal maxWidth is probably coming in as a string and a string + a number stringifies the number and just appends the strings. Try this:

```css
max-width: ${parseInt(maxWidth, 10) + 80}px;
```

**Comment by probablyup** [comment]
When you write your JSX if you do `<Component maxWidth="720" />` that's what causes this btw. If you want it to be a number, do `<Component maxWidth={720} />` instead
