### ISSUE TITLE
Extending Styled Components seems doesn't work in beta releasing.

### ISSUE THREAD

**Issue by mustafa-alfar** [styled-components/styled-components#2626]
I'm moving to use styled component and everything goes well except that extending style doesn't work at all, 
I'm trying to rewrite my styled component ( Button ) by using 
const NewButton = styled(Button)`
  // some new style 
`
but nothing is applied on my style ? 
Is there any suggestion ?

**Comment by jbsmith731** [comment]
@mustafa-alfar I'm having the same issue and I'm getting a client-server mismatch warning for the classNames

**Comment by probablyup** [comment]
Really can't help you at all if you don't use the issue template and provide _some_ sort of reproduction case

**Comment by jbsmith731** [comment]
@probablyup https://codesandbox.io/embed/hello-world-f364c

**Comment by mustafa-alfar** [comment]
I figured out the problem,
I've wrapped the styled component by another component.
////////////
import styled from "styled-components";
import colors from "../../styles/colors";

```
const Btn = styled.button`
    font-size: 14px;
    font-weight: 100;
    border: 0.8px solid ${colors.blue};
    border-radius: 4px;
    min-height: 42px;
    display: flex;
    justify-content: center;
    align-items: center;
    cursor: pointer;
    outline: none;
    flex-basis: ${props => props.basis};
    color: ${props => (props.blue ? colors.white : colors.blue)};
    background-color: ${props => (props.blue ? colors.blue : colors.white)};
    &:hover {
        opacity: 0.9;
    }
`;
const Button = ({ children, blue, basis }) => (
    <Btn blue={blue} basis={basis}>
        {children}
    </Btn>
);

export default Button;
```

so I convert the code to >>

```
export default styled.button`
    font-size: 14px;
    font-weight: 100;
    border: 0.8px solid ${colors.blue};
    border-radius: 4px;
    min-height: 42px;
    display: flex;
    justify-content: center;
    align-items: center;
    cursor: pointer;
    outline: none;
    flex-basis: ${props => props.basis};
    color: ${props => (props.blue ? colors.white : colors.blue)};
    background-color: ${props => (props.blue ? colors.blue : colors.white)};
    &:hover {
        opacity: 0.9;
    }
`;
```

and that work fine.
Thank you
