### ISSUE TITLE
5.0.0-beta.2 browser builds erroneously include "stream" module

### ISSUE THREAD

**Issue by billyjanitsch** [styled-components/styled-components#2627]
## npmPackages:
 - babel-plugin-styled-components: ^1.10.1 => 1.10.1 
 - styled-components: 5.0.0-beta.2 => 5.0.0-beta.2 

## Steps to reproduce

1. Inspect either the [CJS](https://unpkg.com/styled-components@5.0.0-beta.2/dist/styled-components.browser.cjs.js) or [ESM](https://unpkg.com/styled-components@5.0.0-beta.2/dist/styled-components.browser.esm.js) browser builds. (Links to unpkg.)
2. Search for `require('stream')`.
3. Find a single instance of `require('stream')` (mapping to [this code](https://github.com/styled-components/styled-components/blob/df2c947e0a2a61e739b391cd8a47a787a56f6f5b/packages/styled-components/src/models/ServerStyleSheet.js#L71)).
3. Cry, softly.

## Expected Behavior

It seems like this bit of code is SSR-only and supposed to be eliminated by Rollup at build time. I notice [a changelog entry](https://github.com/styled-components/styled-components/blob/master/CHANGELOG.md#v341---2018-08-04) for v3.4.1 about ensuring that this was the case. The [latest stable builds](https://unpkg.com/styled-components@4.3.1/dist/styled-components.browser.esm.js) (v4.3.1) do not include this code, so this seems like a v5 regression.

## Actual Behavior

Bundlers will either inject an enormous stream polyfill, or be unable to resolve the module and crash.

P.S. Thank you for your work building & maintaining this library. ❤️

**Comment by probablyup** [comment]
Oh FFS lol. That stupid rollup plugin will be the death of me.

**Comment by probablyup** [comment]
Oh nvm, we changed how we're using the library. Will fix, thanks for reporting!

**Comment by probablyup** [comment]
Fixed in 5.0.0-beta.3, sorry about that!

**Comment by longjoel** [comment]
I am still running into this in 5.1.0.

I have to use the `replace` plugin and replace `"import 'stream';` with an empty string.
