### ISSUE TITLE
Feature: Dropping duplicate css when chaining prop's

### ISSUE THREAD

**Issue by jamesslock** [styled-components/styled-components#263]
When using multiple props they will override the main style ones leaving them in the outputted code.

It would be great if they could be stripped out as this would potentially save additional class weight for components with many props/overrides.

<img width="184" alt="screen shot 2016-11-27 at 14 43 07" src="https://cloud.githubusercontent.com/assets/202605/20651312/f049a4ba-b4b0-11e6-8dd4-630b7cb05a92.png">

💖

**Comment by mxstbr** [comment]
Hmm, I don't think that really matters. The amount of CSS you inject is pretty irrelevant, while there is a "maximum" it's so huge that you should never be able to reach that point.

I can see us removing duplicate properties like so through https://github.com/styled-components/babel-plugin-styled-components:

```JS
const div = styled.div`
  padding: 0;
  padding: 1em;
`
```

but I think it's a pretty small enhancement that will require a lot of work and be very finnicky to be honest 😊
