### ISSUE TITLE
Error when using styled-component macro with gatsby

### ISSUE THREAD

**Issue by dephiros** [styled-components/styled-components#2630]
## System:
 - OS: macOS 10.14.5
 - CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
 - Memory: 386.38 MB / 16.00 GB
 - Shell: 5.6.1 - /usr/local/bin/zsh
## Binaries:
 - Node: 10.16.0 - ~/.volta/tools/image/node/10.16.0/6.9.0/bin/node
 - Yarn: 1.16.0 - ~/.volta/tools/image/yarn/1.16.0/bin/yarn
 - npm: 6.9.0 - ~/.volta/tools/image/node/10.16.0/6.9.0/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^5.0.0-beta.3 => 5.0.0-beta.3 

## Steps to reproduce
- start a project with gatsby starter
- install styled-component. same error on v4 and v5
- In a component, try:
```
import styled from "styled-components/macro";
const RedDiv = styled.div`
  color: red;
`;
```
## Expected Behavior
- No error when running `gatsby develop`

## Actual Behavior
- I see this error in the console: `error There was an error trying to load the config "styledComponents" for the macro imported from "styled-components/macro. Please see the error thrown for more information.`
- The code still compiles and works

**Comment by dephiros** [comment]
Adding config section to `package.json` fixed it

**Comment by asiop** [comment]
above fix also works with create-react-app 🙏

**Comment by Hurtak** [comment]
Are you sure this is the proper fix? Why is not the pure: true config inside of the styledComponents package itself, why do I need to add it to my app package.json?

**Comment by cyrus-za** [comment]
Encountered this after upgrading from CRA 3.0.1 to 3.1.0
I get a whole load of console errors duplicating this message (in my terminal) on build time (with `react-scripts start`) but it seems to compile and note those only as warnings. The duplicated messages are most likely one per module import. 

@dephiros' above solution does fix it, but I'd like to stay away from configuring babel or babel-macros inside package.json with CRA. 

@kentcdodds please let us know if this is something that can be solved by Dan & co in CRA's internal babel config or if this is a styled-components issue.

**Comment by prakash118** [comment]
> Adding config section to `package.json` fixed it
> 
> ```
>   "babelMacros": {
>     "styledComponents": {
>       "pure": true
>     }
>   }
> ```

documentation mentions it in https://www.styled-components.com/docs/tooling#babel-macro but I don't know if it is a correct approach.

**Comment by djnorrisdev** [comment]
> > Adding config section to `package.json` fixed it
> > ```
> >   "babelMacros": {
> >     "styledComponents": {
> >       "pure": true
> >     }
> >   }
> > ```
> 

This fixed it for me also. It's strange I wasn't getting these errors on new projects until two days ago.

**Comment by linvain** [comment]
Got same errors for `babel-plugin-relay` with CRA. Reverting to CRA v3.0.0 helped

**Comment by cburkins** [comment]
Seeing same problem, package.json addition suppressed my errors as well, but it doesn't feel like a proper fix to me, feels like this issue should not be closed

**Comment by wontem** [comment]
I should notice that the empty object in configuration works as well:
```
  "babelMacros": {
    "styledComponents": {}
  }
```
So the problem is literally as indicated in the error: babel (I suppose) cannot find config for the macro

**Comment by acidoxee** [comment]
@linvain: I second @wontem's sayings. Adding a `.babel-plugin-macrosrc.yml` (or whatever extension cosmiconfig supports) with the following content solves the problem:

```yml
relay: ~
```

**Comment by dimaqq** [comment]
It would be really nice if config was optional...
