### ISSUE TITLE
v5 SSR Returning Empty Style Tags

### ISSUE THREAD

**Issue by rtymchyk** [styled-components/styled-components#2637]
## System:
 - OS: macOS High Sierra 10.13.4
 - CPU: (4) x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
 - Memory: 254.39 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
 - Yarn: 1.6.0 - /usr/local/bin/yarn
 - npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
 - Watchman: 4.7.0 - /usr/local/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: ^1.10.1 => 1.10.1
 - styled-components: ^5.0.0-beta.3 => 5.0.0-beta.3

## Steps to reproduce
Within the context of an Express middleware:
```javascript
const sheet = new ServerStyleSheet()
const reactTree = (
  <StyleSheetManager sheet={sheet.instance}>
    <Router location={req.url} />
  </StyleSheetManager>
)

const html = ReactDOMServer.renderToString(reactTree)
const css = sheet.getStyleTags()
const { js } = flushChunks(clientStats, { chunkNames: flushChunkNames() })

res.status(200)
res.render('base', { html, css, js })
```

Base is just a Handlebars template, but it's not relevant. Can just print out contents of `css` here.

Within the context of my `.babelrc`:
```
"development": {
      "plugins": [
        "react-hot-loader/babel",
        [
          "styled-components",
          {
            "minify": false,
            "ssr": true,
            "displayName": true,
          }
        ]
      ]
    },
```

## Expected Behavior
Style tag (`css` above) in rendered HTML contains classes.

On server (and client hydration):
```javascript
<style data-styled data-styled-version="5.0.0-beta.3">
.kxoUDN{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-flex-direction:column-reverse;-ms-flex-direction:column-reverse;flex-direction:column-reverse;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-box-pack:end;-webkit-justify-content:flex-end;-ms-flex-pack:end;justify-content:flex-end;width:100vw;
</style>
```

## Actual Behavior
On Server:
```javascript
<style data-styled data-styled-version="5.0.0-beta.3"></style>
```

On Client Hydration:
```javascript
<style data-styled data-styled-version="5.0.0-beta.3">
.kxoUDN{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-flex-direction:column-reverse;-ms-flex-direction:column-reverse;flex-direction:column-reverse;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;-webkit-box-pack:end;-webkit-justify-content:flex-end;-ms-flex-pack:end;justify-content:flex-end;width:100vw;
</style>
```

## Notes
`sheet.getStyleElement()` is the same result, a style tag that has `dangerouslySetInnerHTML: { _html: '' }`

**Comment by probablyup** [comment]
@rtymchyk what version are you upgrading from? you don't need to use `StyleSheetManager` for SSR.

Should just be:

```jsx
const sheet = new ServerStyleSheet();
const html = ReactDOMServer.renderToString(
      sheet.collectStyles(
        <Router location={req.url} />
      )
);
const css = sheet.getStyleTags()
```

**Comment by rtymchyk** [comment]
@probablyup I am upgrading from `4.2.0`. I'll need to rule out the possibility that there may have been an issue in 4.3.0.

As for your second point, the documentation speaks to these 2 APIs as being equivalent for SSR, so I prefer to use the declarative one:
>The collectStyles method wraps your element in a provider. Optionally you can use the StyleSheetManager provider directly, instead of this method. Just make sure not to use it on the client-side.

**Comment by probablyup** [comment]
Ok I think I found the issue... there's a backward compat fix that needs to be added because during the refactor the internal variable got renamed for some reason. Will fix.

**Comment by rtymchyk** [comment]
@probablyup Glad to hear :) I can confirm that the latest v4 is working fine.

**Comment by probablyup** [comment]
Released in https://github.com/styled-components/styled-components/releases/tag/v5.0.0-beta.4

**Comment by rtymchyk** [comment]
Fix is good. Seeing a server vs. client mismatch on class names, but this looks like a separate issue.

**Comment by probablyup** [comment]
@rtymchyk the mismatches are in dev or prod mode? If it's dev yeah we have a PR in progress to change a few internal behaviors

**Comment by steve-taylor** [comment]
I'm getting empty style tags in 5.0.0-beta.8, so I had to switch back to 4.3.2.

**Comment by nobulirakli** [comment]
This is happening on CRA as well. The style tags have content on local development but are empty on deployment.

**Comment by ilanp13** [comment]
might [this](https://stackoverflow.com/questions/53486470/react-styled-components-stripped-out-from-production-build/54738834#54738834) post help?

**Comment by FraukeVdz** [comment]
I'm having the same problem.

This is my code: 
`var React = require("react");
const ReactDOMServer = require('react-dom/server');
const { ServerStyleSheet } = require('styled-components');
const { Button }  = require("swirl"); // external component library using styled components

const html = (locals) => {
  const sheet = new ServerStyleSheet();
  let html = '';
  let styleTags = '';
  try {
    html = ReactDOMServer.renderToString(
      sheet.collectStyles(<Button>This is a button</Button>)
    );
    styleTags = sheet.getStyleTags();
  } catch (error) {
    console.error(error)
  } finally {
    sheet.seal()
  }
  
  return html
}

export default html;`

I use StaticSiteGeneratorPlugin from webpack to render this staticly.

The HTML looks just fine:
`<button class="sc-bdnxRM bBXhOB" type="button"><span>This is a button</span></button>`

But the variable css is always empty.
I'm not sure what I'm doing wrong. Could someone help me please?
