### ISSUE TITLE
Child component styled component not being rendered

### ISSUE THREAD

**Issue by hammaduzair** [styled-components/styled-components#2638]
So we are in the progress of migrating our next from 5 to 8. 
We have  a page let's say x which contains styled components

`import { StyledX } from "components/x/styled-components";
render() {
return (...
<StyledX> <Card></Card><Styled>
...)}`

and Card component as follows: 

`import { StyledY } from "components/y/styled-components";
render() {
return <StyledY> <Something></Something><Styled>}`

The StyledX styles are rendered properly. However StyledY styles are present in the html and hence not being rendered.

This is working fine on Next5

**Comment by probablyup** [comment]
Can't help you without a reproduction, also strongly recommend looking at the [styled-components integration example](https://github.com/zeit/next.js/tree/canary/examples/with-styled-components) as a lot has changed since next v5.
