### ISSUE TITLE
React Native + TypeScript + StyledComponents issue

### ISSUE THREAD

**Issue by tomacotuna** [styled-components/styled-components#2642]
Hey, so this is more of a how to question or what did I fucked up type of thing. I am trying to work with React Native Typescript and Styled Components together, but I keep getting weird issues.

## Steps to reproduce
So I am using the Ignite Boilerplate Bowser (https://github.com/infinitered/ignite-bowser), and I added the `styled-components`. But when I created a Flex components and wanted to add some login before using it, I keep getting this weird error. The error is on the last line where I make use of the **FlexWrapper** and get this => `'FlexWrapper' refers to a value, but is being used as a type here.ts(2749)`

```ts
import styled from "styled-components/native"
import { flex, space, color, border } from "styled-system"

const FlexWrapper = styled.View`
  ${flex};
  ${color};
  ${space};
  ${border};
`

const Flex = () => <FlexWrapper /> 
```

package.json (just the relevant ones)

```json
"react": "16.8.3"
"react-native": "0.59.3"
"typescript": "3.2.4"
"@types/styled-components": "^4.1.16"
"styled-components": "^4.2.1"
```

**Comment by probablyup** [comment]
@tomacotuna thanks but we don't maintain the types for v4+, please feel free to reopen this over at `DefinitelyTyped`

**Comment by just0110** [comment]
Whats the problem to create interface for it?
