### ISSUE TITLE
defaultProps.theme does not work with global styles (v5)

### ISSUE THREAD

**Issue by arimah** [styled-components/styled-components#2646]
Hi! :wave: Firstly, I would like to commend you on v5 thus far – it is splendid in so many ways. Very impressive work! Alas, v5 is not completely bug-free (yet):

### System:

 - OS: Windows 10
 - CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
 - Memory: 8.43 GB / 15.88 GB

### Binaries:

 - Node: 10.11.0 - C:\Program Files\nodejs\node.EXE
 - npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD

(As well as `styled-components@5.0.0-beta.5` and `babel-plugin-styled-components@1.10.0`, which failed to show up in the envinfo output for mysterious reasons.)

## Reproduction

https://codesandbox.io/s/verdy

![Sandbox UI with light theme selected](https://user-images.githubusercontent.com/30327355/60043703-f8965600-96c0-11e9-9a6d-b2e67b9ed308.png)  
![Sandbox UI with dark theme selected](https://user-images.githubusercontent.com/30327355/60043746-12d03400-96c1-11e9-8f89-5a9d71606189.png)

## Steps to reproduce

1. Create some global styles with `createGlobalStyle`.
2. Assign to `defaultProps` an object with the key `theme` set to some appropriate value.
3. Render the global styles inside a `<ThemeProvider>` set to another theme.

## Expected Behavior

The `ThemeProvider`'s theme should override the default property value.

This works in v4, and with "regular" styled components (see the `<Wrapper>` and `<Title>` components in the example).

## Actual Behavior

The theme from `defaultProps` always has precedence, overriding any `ThemeProvider` that may exist higher up in the tree.

**Comment by probablyup** [comment]
Released in https://github.com/styled-components/styled-components/releases/tag/v5.0.0-beta.6
