### ISSUE TITLE
Cannot apply further styles upon importing component

### ISSUE THREAD

**Issue by erikras** [styled-components/styled-components#265]
Greetings all. Apologies if this is a known issue, but it has bitten me several times already.

## Version
1.1.2

## Reproduction
WebpackBin is malfunctioning at the moment, but it's pretty trivial to reproduce:

---

```jsx
// Title.js
import React from 'react'
import styled from 'styled-components'

// Apply styles to h1
const StyledTitle = styled.h1`
  font-size: 1.5em;
  text-align: center;
  color: palevioletred;
`

// Component renders styled component
const TitleComponent = props =>
  <StyledTitle>{props.children}</StyledTitle>

export default TitleComponent
```

---

```jsx
// HelloWorld.js
import React from 'react'
import styled from 'styled-components'

// Import title component
import Title from './Title'

// Attempt to apply further styles (THIS WON'T WORK)
const BorderedTitle = styled(Title)`
  border: 1px solid blue;
  color: teal;
`

const HelloWorld = () => (
    <div>
      <Title>Regular Title</Title>
      <BorderedTitle>Should have a border and be teal</BorderedTitle>
    </div>
  )

export default HelloWorld;
```

---

## Steps to reproduce
1. Create a React component that renders a styled component
2. Import said component and try to style it further with the `styled(MyComp)` syntax

## Expected Behavior
The component should have both the styles in its original component, but also the ones applied to it when imported.

## Actual Behavior
The styles applied in step 2 will not be applied.

**Comment by rovansteen** [comment]
I'm having the same issue but weirdly enough only on some elements. Not sure yet what the difference is that is causing this to not work for some of them.

**Comment by k15a** [comment]
Wouldn't it be great if styled components could be further styled with template strings?

I imagine something like this:

```JS
import styled from 'styled-components'

const Box = styled.div`
	padding: 2em;
`

const BoxWithMargin = Box`
	margin: 3em;
`
 
// You can now use both Box and BoxWithMargin like normal React components
<Box />
<BoxWithMargin />
```

**Comment by rudin** [comment]
And what happens when you directly export the 'styled component'? A 'styled component' includes props.children by default, right?

```
// Title.js
import React from 'react'
import styled from 'styled-components'

// Apply styles to h1
const StyledTitle = styled.h1`
  font-size: 1.5em;
  text-align: center;
  color: palevioletred;
`

export default StyledTitle
```

But that's probably not going to help you when you want to do more magic with props...

**Comment by erikras** [comment]
> But that's probably not going to help you when you want to do more magic with props...

Yeah, I'm not wrapping it in a component for arbitrary reasons. 😄 

---

### Possible Workaround

I'd test this on WebpackBin, but it's still screwy. Can someone else confirm this?

If I change this:
```jsx
const TitleComponent = props =>
  <StyledTitle>{props.children}</StyledTitle>
```
To this:
```jsx
const TitleComponent = props =>
  <StyledTitle className={props.className}>{props.children}</StyledTitle>
```
Then it will get styles from both places.

---

Still, this strikes me as something that the library should handle. When you go all in on `styled-components`, you should never have to use a `className` prop.

**Comment by mxstbr** [comment]
No we cannot avoid this. See the [styled-components documentation](https://github.com/styled-components/styled-components/blob/master/docs/existing-css.md).

Did you expect `styled-components` to FORCE ATTACH THE CLASSNAME TO THE COMPONENTS DOM NODE YOU MOTHERFUCKERSSSSSSSSSS? 

Yeah we can't do that, sorry. All `styled-components` does is pass in `className`s as props, so if you don't take that and attach it there's nothing we can do to help you I'm afraid! Sorry!

**Comment by erikras** [comment]
Yeah, I understand now. Makes total sense. Glad I figured out the workaround.

**Comment by rovansteen** [comment]
Whoops, excuse me. I just totally missed that for one component.

By the way @erikras the way I do this is by using the spread operator, which I think is quite an elegant solution, allowing you to pass all kinds of prop down if you please.

```
const TitleComponent = ({ children, ...other }) =>
  <StyledTitle {...other}>{children}</StyledTitle>
```

**Comment by erikras** [comment]
@rovansteen Oh yeah, I'm well versed in the spread operator. I was just being explicit. In your example, you don't even need to separate out the children.
