### ISSUE TITLE
Performance analysis compared to other libraries 

### ISSUE THREAD

**Issue by Carduelis** [styled-components/styled-components#2653]
Hi there! We're using styled-components in our project and we love your library. 
Also, I tried to popularize the library on top-1 Russian IT-resource (habr.com), doing [the translation](https://habr.com/ru/users/carduelis/posts/) of Medium article about v5.0.
I hope, I've made some contribution to the popularity of styled-components.

But one of the guys shared a link to [benchmarks](https://codesandbox.io/s/cssinjsbenchmarks-yin1g) where the performance of styled-components is horrible (**more than 100x slower**). 
I checked it and realized that there is an example of **the wrong usage of styled-components** (it even prints a warning to the console).

**But** I [forked the benchmark](https://codesandbox.io/s/cssinjs-benchmarks-u9lji) and put something more adequate. Even in this case, styled-components is slower than the others. (*Btw, I tried to remove any nested `& > &` selectors - the same slowdown*)

How can we optimize styled-components even more? 

The other example (can't give a reproduction right now) is where I tried to render 100 the same Styled.div's inside autocomplete component (it make sense to render such amount of components and do not use virtual scrolling). When I changed `StyledDiv` to `<div style={{}}/>` there was significant time boost. Note: all of these StyledDivs had the same set of props.

### Questions

1. Could you please provide some benchmarks, that are sensible and reliable? (*if so, I'd be glad to share it among Russian IT-community*)
2. Do you have any tips to optimize render speed, maybe `React.Memo()` should help, or other memoization tools could be helpful

### Environment
```
#### System:
 - OS: Linux 4.19 Debian GNU/Linux 9 (stretch) 9 (stretch)
 - CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
 - Memory: 1.96 GB / 62.70 GB
 - Container: Yes
 - Shell: 4.4.12 - /bin/bash
#### Binaries:
 - Node: 10.16.0 - /usr/local/bin/node
 - Yarn: 1.16.0 - /usr/local/bin/yarn
 - npm: 6.9.0 - /usr/local/bin/npm
#### npmPackages:
 - styled-components: 4.3.2 => 4.3.2
```
### Reproduction
Original benchmarks https://codesandbox.io/s/cssinjsbenchmarks-yin1g
My forked ones with more sensible examples: https://codesandbox.io/s/cssinjs-benchmarks-u9lji

### Thank you for your efforts!

**Comment by Carduelis** [comment]
@probablyup, could you comment it, please. I'd really want to popularize the library if it's really fast. Thank you!

**Comment by probablyup** [comment]
I'd recommend using [our set of benchmarks](https://github.com/styled-components/styled-components/tree/canary/packages/benchmarks).
