### ISSUE TITLE
Upgrading from 4.1.2 to 5.0.0-beta.5 causes font issue on every page load

### ISSUE THREAD

**Issue by epgui** [styled-components/styled-components#2654]
## Environment
```
## System:
 - OS: macOS 10.14.5
 - CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
 - Memory: 64.03 MB / 8.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 8.16.0 - ~/.nvm/versions/node/v8.16.0/bin/node
 - Yarn: 1.17.0 - /usr/local/bin/yarn
 - npm: 6.4.1 - ~/.nvm/versions/node/v8.16.0/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.8.0 => 1.10.1 
 - styled-components: ^5.0.0-beta.5 => 5.0.0-beta.5
```

I'm also using system fonts on the whole website, it's not like there is an expected delay to allow for fonts to load:
`font-family: -apple-system, BlinkMacSystemFont, Helvetica, Segoe, sans-serif;`

The default font stack is applied with `createGlobalStyle()` in my Header component:

```
    <Fragment>
      <Helmet />
      <GlobalStyle />
      <AuthenticationHandler
        receiveAuthenticationStatus={receiveAuthenticationStatus}
      />
      <ContextProvider
        location={location}
        isLoggedIn={isLoggedIn}
        heroHasCTA={heroHasCTA}
      >
        <Navigation />
      </ContextProvider>
    </Fragment>
```

and:

```
export const GlobalStyle = createGlobalStyle`
  // font stack in here
`
```

## Actual Behavior

![bug report](https://user-images.githubusercontent.com/1992822/60288372-e981f480-98c8-11e9-8e71-f2123b300704.gif)

**Comment by probablyup** [comment]
@epgui thanks for reporting but really need some sort of reproduction sandbox to be able to help

**Comment by epgui** [comment]
I'm very sorry I'm unable to spend more time on this, we're reverting to v4 for the moment.

**Comment by epgui** [comment]
I appreciate your work! Love styled components. Keep it up :)

**Comment by epgui** [comment]
Turns out we weren't using `gatsby-plugin-styled-components`, but this is a gatsby site... Is the gatsby plugin supposed to be compatible with v5?

**Comment by probablyup** [comment]
The plugin should be compatible with v5 unless it was using secret internals

**Comment by kitten** [comment]
Hm that's odd. I've just set a new Gatsby site up with styled-components v5 and didn't run into this, but then again I did start from scratch. Have you upgraded the babel plugin as well and used 'yarn list' or sth else to check that only one version of styled-components is in use?

**Comment by probablyup** [comment]
I also haven't seen this behavior and I've worked on a few gatsby projects recently for unrelated bug stuff. Going to close, but feel free to reopen if you can provide a reproduction case.
