### ISSUE TITLE
React Native : Image does not support borderTopColor

### ISSUE THREAD

**Issue by MatthieuLemoine** [styled-components/styled-components#266]
## Version
1.1.2

## Reproduction
```javascript
const Image = styled.Image`
  border-color  : ${props => props.theme.colors.LIGHT_GREY};
`;
```

## Expected Behavior
Generated inline style  : 

```javascript
{
  "borderColor": "#dee1e2"
}
```

## Actual Behavior
Generated inline style  : 

```javascript
{
  "borderTopColor": "#dee1e2",
  "borderRightColor": "#dee1e2",
  "borderBottomColor": "#dee1e2",
  "borderLeftColor": "#dee1e2"
}
```

which throws the following warning :   ``Ìnvalid props.style key 'borderTopColor' supplied to'Ìmage'``

**Comment by MatthieuLemoine** [comment]
I opened this issue here because it seems that #254 fix the same issue with border-radius.

**Comment by mxstbr** [comment]
Ah, good call actually! Will reopen, thanks @MatthieuLemoine!

**Comment by jacobp100** [comment]
PR out to fix this.

Out of interest, is this for iOS or Android? I noticed that individual corner radii seems to be supported for Android, just not iOS.

**Comment by MatthieuLemoine** [comment]
I only tried on iOS

**Comment by mxstbr** [comment]
This has been fixed for a long time IIRC, if you're still running into this issue feel free to open a new one with a reproduction with the latest version of styled-components!

**Comment by jacobp100** [comment]
@robinclaes you'll need to provide more information about what components you're using and exactly what the issue is

**Comment by robinclaes** [comment]
We're getting it when adding `borderColor` on `styled.Image` (React Native) - which is exactly what OP had.
He opened a PR to fix this, but I think the code got lost in 6.0.0.

**Comment by jacobp100** [comment]
What version of RN and what platform? I was sure they’d fixed the issue

**Comment by MosefAsad** [comment]
We've encountered this issue with RN version 0.72.4 on both IOS and Android.

**Comment by nazmeln** [comment]
Hey @jacobp100,
I've also encountered this issue.
```
"styled-components": "6.1.0",
"react-native": "0.72.5",
```
