### ISSUE TITLE
client rendering react component in browser with styles

### ISSUE THREAD

**Issue by shmilyoo** [styled-components/styled-components#2660]
I have a development requirement, I need to render the React component in the client browser, generate it to  html string and send it to the backend's puppeteer headless browser, puppeteer convert the html to a pdf file and send it back to the front end for printing or other purpose. So I must distill or collect the styles and send it with the html string.  For some reason, all the render work must be down in client side.

I noticed SC have an api have server render ability . And it also have some trick to do it in client.
```
const {StyleSheet} = require('styled-components').__DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS
StyleSheet.reset(true)
```
But it also have a warning it is not encouraged to use it in frontend, and may cause some problem.

## Expected Behavior
Can I collect the styles in the client side?

## Actual Behavior
only can do it with the 
 **__DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS** tricks

**Comment by probablyup** [comment]
> I need to render the React component in the client browser, generate it to html string and send it to the backend's puppeteer headless browser

Sounds like a good use case for our [server-side rendering](https://www.styled-components.com/docs/advanced#server-side-rendering) implementation. It's a little odd to use it in the browser, but it's possible.

**Comment by shmilyoo** [comment]
> > I need to render the React component in the client browser, generate it to html string and send it to the backend's puppeteer headless browser
> 
> Sounds like a good use case for our [server-side rendering](https://www.styled-components.com/docs/advanced#server-side-rendering) implementation. It's a little odd to use it in the browser, but it's possible.

thanks, and there is two addtional question:
1. is there any api can achieve my purpose(render react component to html with styles) in client browser side.
2. if I use   `const {StyleSheet} = require('styled-components').__DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS` . Wil it cause some ghost thing as the document said ?

**Comment by probablyup** [comment]
Yes I just answered that, use the server-side rendering code. In the top of your app, when you're going to use `ReactDOM.render` wrap the JSX with this:

```jsx
import React from 'react';
import { renderToString } from 'react-dom/server';
import { ServerStyleSheet, StyleSheetManager } from 'styled-components';

import App from './yourApp';

const stylesheet = new ServerStyleSheet();

const html = renderToString(
  <StyleSheetManager sheet={stylesheet.instance}>
    <App />
  </StyleSheetManager>
);

const css = stylesheet.getStyleTags() // <- do something with the styles
```

**Comment by shmilyoo** [comment]
> ```js-jsx
> import React from 'react';
> import { renderToString } from 'react-dom/server';
> import { ServerStyleSheet, StyleSheetManager } from 'styled-components';
> 
> import App from './yourApp';
> 
> const stylesheet = new ServerStyleSheet();
> 
> const html = renderToString(
>   <StyleSheetManager sheet={stylesheet.instance}>
>     <App />
>   </StyleSheetManager>
> );
> 
> const css = stylesheet.getStyleTags() // <- do something with the styles
> ```

still the error message to the line ` const stylesheet = new ServerStyleSheet();`
```
Error: The clone method cannot be used on the client!
- Are you running in a client-like environment on the server?
- Are you trying to run SSR on the client?
```
I run the code on client side . So, must I use the `__DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS ` trick? Is there any possible api I can render and collect the style with SC?
