### ISSUE TITLE
Media Query Selectors don't work on extended component

### ISSUE THREAD

**Issue by alexandercerutti** [styled-components/styled-components#2661]
Hi, I was trying to insert media queries in my SCs and found the following behavior a bit weird to me.
I tried to apply my media queries like below, and it worked perfectly:

```javascript
const myComponent = styled.div`
    @media (max-width: 300px) {
        width: 80px !important;
        height: 80px !important;
    }
`;
```

Instead, if I try to extend a component, it does not give me any error and it does not get added to the DOM element's styles if I resize my window:

```javascript
const extendedComponent = styled(originalComponent)`
    @media (max-width: 300px) {
        width: 80px !important;
        height: 80px !important;
    }
`;
```

Can someone please explain me why this happens and if this is an expected or unexpected behavior?
It is weird because, in my opinion, it should be the same and work at the same way and apply the `@media` only to the extended component.

Thank you very much.

**Comment by diondiondion** [comment]
Does your wrapped component forward the `className` prop to the element you want to style?

**Comment by alexandercerutti** [comment]
@diondiondion I didn't know that, but yes, it is forwarding:

My current situation is this (with real code) is this:

```javascript
// File 1
// The hideOnSmallWidth has another purpose
export const GenericButton = styled.div<GenericButtonProps>`
  opacity: ${props => props.visible ? 1 : 0};
  visibility: ${props => props.visible ? "visible" : "hidden"};
  transition: opacity .2s ease-in-out;

  ${props => props.hideOnSmallWidth && css`
    @media ${maxWidthRule(300)} {
      display: none;
    }`
  }
`;

export function ActionButton(props: ActionButtonProps): JSX.Element {
  ...

  return (
    <GenericButton
      visible={props.visible || false}
      onClick={props.onClick}
      style={props.style || {}}
      className={props.name}
      hideOnSmallWidth={props.hideOnSmallWidth || false}
    >
        <SVGInline svg={icons[props.name]} {...(props.svgStyle || {})}/>
    </GenericButton>
  );
}

// File 2

const StyledCentralButton = styled(ActionButton)`
  @media (max-width: 300px) {
    width: 80px !important;
    height: 80px !important;
  }
`;

render() {
    ...
    <StyledCentralButton
        visible
        name={midIcon}
        onClick={this.onStatusChange}
    />
   ...
}
```

`midIcon` is a string ("play", "pause", "restart") which I use to determine which icon, inside `GenericButton` content, to choose. And I chose to pass it also as className even if it does not have any real css attached.
So, yes, it forwards the className.

**Comment by dmytro-lymarenko** [comment]
In `ActionButton` you don't pass `className` prop but `name` one:
```js
className={props.name}
```

Instead you want to do this:
```js
className={props.className}
```

**Comment by alexandercerutti** [comment]
I see... I misunderstood. The fact is that I use name as a className because I use it also for icon name. But I think I might also use className as name to represent the icons.

Thank you very much!!
