### ISSUE TITLE
Problem testing third party components

### ISSUE THREAD

**Issue by FinnWinchester** [styled-components/styled-components#2662]
I happen to have a "third party" library created by me where I am using styled components 4.3.2 as a peerDependency so in my main project I am having no conflicts with it.

It turns out that when I create some testings with Jest and Enzyme and I want to test, let's say, the Login Scene where I have a LoginForm as a child of the scene and some icons and buttons coming from this UI library as a child of the LoginForm. Everything is wrapped by a ThemeProvider and, of course, a theme.

It happens that when I run the mount method over the scene, the components coming from the UI library don't receive the theme I am passing through the ThemeProvider. However, the components created on my main project using styled components they do receive the theme as a prop.

This is driving me nuts. Any idea? Thanks!

**Comment by probablyup** [comment]
It's very likely an issue of styled-components not being deduped properly by the package manager. If you're using yarn, try this in your package.json:

```json
"resolutions": {
  "styled-components": "^4.3.2"
}
```

**Comment by FinnWinchester** [comment]
I am not using yarn. However I tried to add it to my package.json anyway and still the same.

**Comment by probablyup** [comment]
Haha well it's a yarn-specific hint so that would make sense...

When you run `npm list styled-components` do you see more than one copy in the tree?

**Comment by FinnWinchester** [comment]
Yes, I can see exactly 2 copies of styled components, one from my UI library (which has it as devDependency and peerDependency) and the other from my main project which has it as devDependency. All of them with the same version though.

Also, my UI library has styled components as external, bundled with webpack.

And to the second question yes, they are symlinked together.

**Comment by probablyup** [comment]
Gotcha yeah that'll be your problem. s-c like React is a singleton library and shouldn't have multiple copies being used. I'm sure it works fine built for production because the bundler will dedupe it but locally with the symlink the devDependency in your other library is treated as a second copy.

If you're using jest, you can force resolution for specific libraries/modules via config. Something like this should work:

```json
"moduleNameMapper": {
  "styled-components": "<rootDir>/node_modules/styled-components"
}
```

**Comment by FinnWinchester** [comment]
It totally works!!! Thank you very much!!! I am not an expert of NPM, how can I avoid having more than 1 copy of styled components or any other library?

**Comment by FinnWinchester** [comment]
However, I am not an expert of NPM, how can I avoid having more than 1 copy of styled components or any other library?

**Comment by FinnWinchester** [comment]
Cool, much appreciated! 😄
