### ISSUE TITLE
Comparison with emotion

### ISSUE THREAD

**Issue by nhooyr** [styled-components/styled-components#2664]
Now that styled components supports the css prop, it's not clear to me what the difference is between the two libraries and which I should choose.

They seem pretty much identical through and through. They both support react native, the css prop, object styling, jest utilities, the styled API etc.

What are the differences?

**Comment by nhooyr** [comment]
Ok so one difference is that emotion is 27kb minified whereas styled-components is 44kb.

See [https://bundlephobia.com/result?p=@emotion/core@10.0.14) and [@emotion/styled](https://bundlephobia.com/result?p=@emotion/styled@10.0.14) and then [styled-components](https://bundlephobia.com/result?p=styled-components@4.3.2).

**Comment by probablyup** [comment]
@nhooyr need to add emotion-theming as well to get a fair comparison. And technically we also ship some of the server code which would make our bundle slightly bigger. We made a lot of changes in v5 to get that size down: https://bundlephobia.com/result?p=styled-components@5.0.0-beta.8

**Comment by probablyup** [comment]
The main difference between the libraries is ergonomics. emotion has a confusing array of packages you need to consume to arrive at a similar API to what styled-components offers from a single import.

We also go out of our way to provide useful dev errors/warnings to avoid pitfalls, etc.

**Comment by nhooyr** [comment]
Nice. It'd be cool if you guys added a page to the docs comparing the two, I think it'd definitely help people figure what they want to use.

**Comment by probablyup** [comment]
@nhooyr want to add an FAQ entry to the website? 😉
