### ISSUE TITLE
Export StyleComponent class for easy Storybook Info Addon exclude

### ISSUE THREAD

**Issue by dcecile** [styled-components/styled-components#2665]
By default the [Storybook Info Addon](https://github.com/storybookjs/storybook/tree/master/addons/info) shows "No propTypes defined!" for the `StyledComponent` and `ThemeProvider` components:

![image](https://user-images.githubusercontent.com/311866/60677785-7b9d7600-9e50-11e9-85fa-6a311070832a.png)

The info addon can be configured to completely hide these two components by supplying class objects via the [`propTablesExclude `](https://github.com/storybookjs/storybook/tree/master/addons/info#options-and-defaults) option.

However, [the `StyledComponent` class is not exported](https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/models/StyledComponent.js#L44). Currently the following workaround is needed to get the class object:

```ts
import styled from "styled-components"
import { ThemeProvider } from "styled-components"

const StyledComponent: any = (styled('div')`` as any).render().type

addDecorator(withInfo({
    propTablesExclude: [
        StyledComponent,
        ThemeProvider
    ]
}))
```

Would it make sense to export the `StyledComponent` class for this use case?

---

_Side note: [`StyledComponent` is exported in `@types/styled-components`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/styled-components/index.d.ts#L157), but only as a type not a value, and `propTablesExclude` needs an actual value._

**Comment by probablyup** [comment]
This isn't possible because in v5+ we generate everything on the fly as SFCs, unfortunately.
