### ISSUE TITLE
inline svg as background image?

### ISSUE THREAD

**Issue by smakosh** [styled-components/styled-components#2666]
## Details
I'd love if you could make this work like it works just fine with CSS

```
body {
  background-image: 
        url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' width='10' height='10'><linearGradient id='gradient'><stop offset='10%' stop-color='%23F00'/><stop offset='90%' stop-color='%23fcc'/> </linearGradient><rect fill='url(%23gradient)' x='0' y='0' width='100%' height='100%'/></svg>");
}
```

**Comment by probablyup** [comment]
2 things:

1) omit the "utf8" part and just do an empty comma, e.g. `data:image/svg+xml;,...`
2) run the svg HTML through `encodeURIComponent`

**Comment by smakosh** [comment]
I escaped it and managed to make it work

**Comment by philgruneich** [comment]
@smakosh How is your final SVG?

**Comment by smakosh** [comment]
> @smakosh How is your final SVG?

- https://github.com/smakosh/gatsby-theme-portfolio/blob/master/theme/src/components/landing/Intro/styles.js#L6
- https://gatsby-theme-portfolio.netlify.app
