### ISSUE TITLE
Feature request: Support CSS object arrays as the first argument

### ISSUE THREAD

**Issue by wagerfield** [styled-components/styled-components#2667]
I would like Styled Components to support CSS object _arrays_ as the _first argument_ to:

- `css`
- `styled`
- `createGlobalStyle`

Currently, these functions only support a single CSS object as the first argument—while an array of CSS objects can be passed as the second argument:

```js
import styled, { css } from "styled-components"

const styleArray = [{ color: "red" }, { color: "blue" }]
const styleFunc = () => styleArray

const css1 = css({}, styleArray) // Works
const css2 = css(...styleArray) // Works
const css3 = css(stylesFunc) // Works
const css4 = css(styleArray) // Doesn't work. Only { color: "red" } is applied

const Div1 = styled.div({}, styleArray) // Works
const Div2 = styled.div(...styleArray) // Works
const Div3 = styled.div(stylesFunc) // Works
const Div4 = styled.div`${styleArray}` // Works
const Div5 = styled.div`${stylesFunc}` // Works
const Div6 = styled.div(styleArray) // Doesn't work. Only { color: "red" } is applied
```

Given that an array of CSS objects can be used as the _only argument_ in a tagged template literal as demonstrated in `Div4` and can also be returned from an interpolation function as demonstrated in `css3` and `Div3`—it would make sense for Styled Components to support an array of CSS objects as the first argument as demonstrated in `css4` and `Div6`.

This small change would make for a more intuitive API when using CSS objects. For those of us that prefer to use CSS objects, the current implementation is a bit of a gotcha.

I am working on a library called [onno](https://onnojs.com) which is based on some of the ideas introduced by Styled System and Theme UI. Onno's `css` function takes a CSS object or an array of CSS objects and returns an array of CSS objects. The function signature for onno's `css` function looks like this:

    function css(styles: CSSObject | CSSObject[]): CSSObject[]

Consistently returning the same type from this function makes it easier to map/reduce/compose the results without having to check whether the result is an array or object. Working with CSS object arrays also allows for styles to be predictably overridden and applied as demoed with the 2 color styles in the example above.

In order for `onno` to work gracefully with Styled Components, the css/styled/createGlobalStyle functions would need to support an array of style objects as the first argument. 

With the current implementation, I need a section in the onno docs outlining the variations that do work and those that don't as demonstrated above.

I have written some integration tests for [Styled Components](https://github.com/wagerfield/onno/blob/version/2.0/packages/onno/test/libraries/styled-components.test.ts#L8) and [Emotion](https://github.com/wagerfield/onno/blob/version/2.0/packages/onno/test/libraries/emotion.test.ts#L8) with onno's `css` and `props` functions. As you will see, Emotion's `css` and `styled` functions are compatible with the result of onno's `css` and `props` functions while Styled Components requires a superfluous empty object to be passed first.

Introducing this proposed change would allow me to remove the empty object passed as the first argument to Styled Components' `css` and `styled` functions.

Thank you for your consideration.

**Comment by probablyup** [comment]
I'm ambivalent... @mxstbr, @kitten?
