### ISSUE TITLE
& + & breaks when extending a component using styled()

### ISSUE THREAD

**Issue by nathggns** [styled-components/styled-components#2668]
## Environment

codesandbox.io

## Reproduction

https://codesandbox.io/s/styled-components-sibling-selector-bug-vq0wb

## Steps to reproduce

Define a styled components which makes use of the self selector (`&`) and the direct sibling selector (`+`) together (`& + &`), to style a component only if it is directly preceeded by itself. 

Extend that component using the `styled(MyComponent)` api. 

Mix and match the extended style component with the original styled component

## Expected Behavior

The sibling and self selectors should work regardless of what combination of base and extended components you use.

## Actual Behavior

The sibling and self selectors only work if you use extended component after the base component. It does not work the other way around. 

## Example

```js

const Item = styled.div`
  &:not(:first-child):after {
    content: "Sibling selector does not work";
  }

  &:after {
    font-weight: bold;
  }

  & + &:after {
    content: "Sibling selector does work" !important;
  }
`;

const ExtendedItem = styled(Item)``;

function App() {
   return (
        <ExtendedItem />
        <Item />
    );
}
```

You will see sibling selector does not work.

**Comment by probablyup** [comment]
What do you think @mxstbr? We would make this work by keeping track of the componentId associate with a rule and feeding that into stylis vs assuming a self reference is always to the final folded component.

**Comment by arminyahya** [comment]
I look at @nathggns codsandbox and when i check classes i think figured out why:





![+ codesandbox2](https://user-images.githubusercontent.com/35793921/68024041-36823700-fcbe-11e9-9a4a-7b149ab600a6.jpg)




ExrendedItem::after take Item's className + Refrence className:after

@probablyup why not using Refrence className  + Refrence className:after?

**Comment by probablyup** [comment]
I'm not sure we can fix this in a way that makes sense. In this case `ExtendedItem` is referring to itself with "&" and `Item` is not an instance of `ExtendedItem`, but `ExtendedItem` is an instance of `Item` since it extends `Item`.
