### ISSUE TITLE
v5 createGlobalStyles does not work on production with 2 global styles

### ISSUE THREAD

**Issue by chriserickson** [styled-components/styled-components#2670]
# Environment
## System:
 - OS: macOS 10.14.5
 - CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
 - Memory: 489.05 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 10.15.1 
 - Yarn: 1.16.0 
 - npm: 6.9.0
## npmPackages:
 - styled-components: ^5.0.0-beta.8 => 5.0.0-beta.8

# Reproduction
I have 2 global styles, however on production only the second one loads. (The class names appear fo the first, but no styles are applied.)

```
import { createGlobalStyle } from 'styled-components/macro';

const GlobalStyling = createGlobalStyle`
html {
  height: 100%;
}

:global(#root) {
  min-height: 100%;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  flex: 1;
}

body {
  min-height: 100%;
  margin: 0;
  padding: 0;
  display: flex;
  flex-direction: column;
  flex: 1;

  max-width: 100vw;
}

button {
  cursor: pointer;
}

main, section {
  display: block;
}

hr {
    margin: 48px 0;
    border-bottom: 1px solid gray;
    border-top: none;
    border-left: none;
    border-right: none;
  }

*:focus {
  outline: 1px solid blue;
}
}`
```
```
const GlobalFontStyling = createGlobalStyle`...`;
```

```
ReactDOM.render(
  <div>
    <GlobalStyling />
    <GlobalFontStyling />
    <ErrorBoundary>...
   </ErrorBoundary
  </div>,
  document.getElementById('root')
);
```

## Expected Behavior
Styles from both global styles will appear

## Actual Behavior
Only styles from `GlobalFontStyling` appear.

**Comment by chriserickson** [comment]
Looks like it may be a red herring -- I tried combining styles and global styles into a single block. 

Things like html/body/hr don't load. That is, until I click the element for the global style in the react dom inspector. Then they suddenly load. Investigating still....

**Comment by mattcosta7** [comment]
I've actually come across the same issue today, but with only a single createGlobalStyle element.  Will try to investigate later on today if I can

**Comment by marvwhere** [comment]
Not sure if related, but I want to leave it here as a note, as I workaround it: 

In my app, I sometimes need to rerender the whole app.

    render(<App />, mountNode);

With v3, v4 it worked without any problems. With v5, I had the issue, that the createGlobalStyles went missing after the rerender of the root element of the app in the style object. All other styles are ok.

My workaround, I call:

    unmountComponentAtNode(mountNode);

before the new render.

I tried to reproduce it with the sandbox example app, but I couldn't, that's why I didn't create an issue.

**Comment by Evalon** [comment]
I observed this bug in storybook when select different stories and go back to previous story. V4 works fine.

**Comment by mattcosta7** [comment]
Looking into this a little more - 

The styles are properly output into the bundled scripts, and they're definitely being interpolated correctly.  The styles are not applied.   If I open up devtools (with react devtools installed), and click on the element in the component inspector, then I do see the styles applied. 

a quick check at debugging (don't have time to dig through deeply now). 

If I add a local state and use effect to force a re-render after initial mounting, the styles apply when that re-render occurs

**Comment by selbekk** [comment]
I'm experiencing this one as well. Weird!

**Comment by shalanah** [comment]
I have this issue as well but with only one `createGlobalStyles`. Even odder, Firefox seemed to apply the styles fine but Safari and Chrome would not.

**Comment by jonkwheeler** [comment]
Just wanted to bump this. Not having the ability to use Global Styles with confidence is a large reason not to switch to v5.

**Comment by probablyup** [comment]
So there's one bug we're keeping an eye on re: rules

**Comment by probablyup** [comment]
@shalanah this is _very likely_ due to a subtle bug we're trying to track down re: vendor-prefixed selectors. You can use tooling like this to find and remove them for the time being: https://stylelint.io/user-guide/rules/selector-no-vendor-prefix

**Comment by probablyup** [comment]
cc @kitten

**Comment by yuliia007naumenko** [comment]
createGlobalStyles doesn't work on server side (next.js v8) but works on client

**Comment by probablyup** [comment]
It’s something with your setup, I use it in 5 separate nextjs projects and
it works.

**Comment by jonkwheeler** [comment]
That’s interesting. I’m using it on a fresh Next.js 9 repo. Global styling with S-C 5 on a page to page basis is not reliable. Styling seems to unload, even if the component is included on all pages. S-C 4 does not have this issue. The SSR setup has not changed either. If you have more info, let me know.

**Comment by probablyup** [comment]
Did you follow the next-styled-components example in the nextjs repo?

**Comment by jonkwheeler** [comment]
Sure did.

**Comment by probablyup** [comment]
Interesting. Do you have multiple libs using s-c that are consumed in the same app? Two copies loading at once can cause some interesting collisions.

**Comment by jonkwheeler** [comment]
That I can confirm. 2 libs. Our Design System runs on S-C. And some other packages we use. Seems like you’re onto something.

**Comment by probablyup** [comment]
Make sure the design system labels s-c as a peer dependency and they’re
both running on the same version. The betas use a nonstandard semver range
so it doesn’t dedupe properly unless it’s the same.

**Comment by jonkwheeler** [comment]
I totally remember the peer dependency quark. However, interestingly I found the DS having S-C set as a dependency AND peer dependency. 😑

**Comment by abraxxas** [comment]
We have the same problem in a next.js project. I checked our dependencies and our package-lock.json and we are only using 1 version of styled-components

**Comment by sbrichardson** [comment]
@probablyup I was able to confirm within our app that a vendor prefixed selection rule was causing the GlobalStyle issue.

Removing this rule resolved:

```css
   /* Gecko Browsers */
  ::-moz-selection {
    background: #C9F6F8;
  }
```

I was looking at the SC v5 source code, it looks like a few changes were made in how the css is being parsed/generated in GlobalStyle, I haven't dug in yet. I also noticed that the GlobalStyle component has about 50% higher rendering duration times, after upgrading from v4 to v5 (just within our app/not tested extensively).

**Comment by jonkwheeler** [comment]
This is an interested find @sbrichardson.

I'm using both `::-moz-selection` and `::selection` in my global style injection. I 100% think you're onto something. 🐴

**Comment by fabb** [comment]
I'm not using any vendor prefixes in our global styles, but still have the issue that they are not loaded all the time.

**Comment by sbrichardson** [comment]
@jonkwheeler @fabb I'm thinking that the `::-` and `:-` cases may be causing an issue in some way, but there may be other cases that are causing bugs also. 

I was still looking at the source, but I noticed this call to `window` in the constructor vs typically in `ComponentDidMount` in [createGlobalStyle.js](https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/constructors/createGlobalStyle.js#L43)

```js
const { globalStyle, styledComponentId } = this.constructor;

if (IS_BROWSER) {
  window.scCGSHMRCache[styledComponentId] =
    (window.scCGSHMRCache[styledComponentId] || 0) + 1;
}

/**
 * This fixes HMR compatibility. Don't ask me why, but this combination of
 * caching the closure variables via statics and then persisting the statics in
 * state works across HMR where no other combination did. ¯\_(ツ)_/¯
 */
this.state = {
  globalStyle,
  styledComponentId,
};
```

**Comment by sbrichardson** [comment]
Slightly unrelated, an update to my comment above about global styles performance in v5.

It was caused by unnecessary re-renders of the GlobalStyle component, since `createGlobalStyle` returns a functional component. Wrapping the `GlobalStyleComponent` that it returns in `React.memo` resolved it (inside `createGlobalStyle` v5 source). It was calling `globalStyle.renderStyles(context, styleSheet);` on each render.

**Comment by sbrichardson** [comment]
@probablyup  @jonkwheeler I was able to resolve this for our app, including the ::- vendor prefix bug. Although the actual cause is still unknown.

All I did was edit `createGlobalStyle` in v5 beta8. I wrapped the stateless functional component that it returns with React.memo.

```js
return React.memo(function GlobalStyleComponent(props) {
  const styleSheet = useStyleSheet();
  const theme = useContext(ThemeContext);
  // ...
```

This resolved the performance problems also, since it was running a few extra times unnecessarily during our app's initial loading. The call to `globalStyle.renderStyles(context, styleSheet);` is expensive.

**Comment by umitkucuk** [comment]
@probablyup 

I am also having this issue too. I am using only one `createGlobalStyle` but it doesn't affect on production mode.

_CRA: 3.1.1
styled-components: 5.0.0-beta.9_

**Comment by jenseralmeida** [comment]
Hi, I am having exactly the same issue, with a single global style. With the development builds, it works, but no style is generated on the release builds.

I have noticed the "needs more info" label even with the detailed https://github.com/styled-components/styled-components/issues/2670#issuecomment-532399875 comment.

Please, let me know what kind of info you need for this issue.

**Comment by wildpow** [comment]
Same issue beta 11

**Comment by probablyup** [comment]
Can you try `styled-components@test` and let me know if it fixes it for you?

**Comment by wildpow** [comment]
@probablyup It seems to be working in both dev and prod.

**Comment by Ako92** [comment]
What Should we do to solve this weird problem?
  I Have :root { } for implement my global colours on it. Should I remove it? is it the solution?

**Comment by fabb** [comment]
@probablyup I checked our project with `styled-components@test` (`5.0.0-beta.11-cgsmulti`), and it is unfortunately **still broken**.

**Comment by Ako92** [comment]
To fix the problem I removed createGlobalStyle and added general styles to a css file then imported that file to my project main jsx/tsx file.

**Comment by jonkwheeler** [comment]
To fix `createGlobalStyle`, you removed it? That is a "work around" some could use. But that is the same as saying, my car is broke, and to fix it I road the bus to work today. (Kidding of course) 🤠

**Comment by umitkucuk** [comment]
@Ako92 but you didn't fixed it. You just stopped using it. 😄

**Comment by Ako92** [comment]
@umitkucuk yes. thanks for you comment. I will edit my answer. but i didn't find any other solution to fix.

**Comment by Ako92** [comment]
> To fix `createGlobalStyle`, you removed it? That is a "work around" some could use. But that is the same as saying, my car is broke, and to fix it I road the bus to work today. (Kidding of course) cowboy_hat_face
:-))
I prefer one place for my globalStyles not two different files and two different locations.because of that i removed createGlobalStyle. if someday this problem got fixed I will come back to createGlobalStyle.

**Comment by fabb** [comment]
Maybe the remaining bug on `styled-components@test` is related to next.js and hydration? I need to investigate more.

**Comment by jonkwheeler** [comment]
I wonder if it's possible this is related to a Next.js bug I filed which demonstrates re-hydration of the `Head`. See here - https://github.com/zeit/next.js/issues/9070

**Comment by probablyup** [comment]
@jonkwheeler very interesting... could be.

**Comment by fabb** [comment]
Ok I found out more. cGS seems to work properly, except in combination with the next.js `Head`.

We currently have in our `_document.tsx` the styles included in the Head:
```
<Head>
    <MyGlobalStyles />
</Head>
```

The weird thing is that in the `getInitialProps` of the `_document.tsx`, we collect the styles only of our `App` component:
```
ctx.renderPage = () => originalRenderPage({
    enhanceApp: App => props => sheet.collectStyles(<App {...props} />),
})
```

So why did that work at all in sc 4? My guess would be that sc 4 did not collect global styles at all, where as sc 5 does - am I on the right track? ❓ 

-----

So I dug some further, and even when I move the `<MyGlobalStyles />` out of the `<Head>` directly as a regular child of the component tree in `_document.tsx`, it also does not apply the styles in sc 5 whereas in sc 4 they are applied nonetheless. This would substantiate the suspicion that global styles were not collected in sc 4 whereas they are in sc 5.

-----

When I move the `<MyGlobalStyles />` component to anywhere in my `App` component or further down, it gets applied correctly. 🎉 

But when I put it inside a `<Head>` component inside my `<App>` component, I get a runtime error:
```
TypeError: Cannot destructure property `styles` of 'undefined' or 'null'.
    at Head.render (.next/server/static/development/pages/webpack:/node_modules/next/dist/pages/_document.js:18:1)
```

So it seems sc's `collectStyles` has a bug in combination with the `<Head>`.

-----

I'll do some more checks to see if we are really ready for upgrade to sc 5 now when I just move the global styles out of `Head` and `_document.tsx`. Should I create a new bug issue for the problems I found in combination with the `<Head>` component?

**Comment by fabb** [comment]
@probablyup I think it would be helpful to add these things 👆 as breaking changes to the v5 release notes, what do you think? Something along these lines:
> BREAKING CHANGE: global styles are now collected like regular component styles, therefore they need to be accessible for collection. For example in case of next.js, it is no longer possible to render them in `_document.js` or as `<Head>` children anywhere in the application. Rather move them to `_app.js` or further down to components that need them.

Note that the part about style collection is just guesswork on my side, based on evidence of the behavior in v5. It would be interesting to hear if this is actually the case, or which other change caused the new behavior.

**Comment by jonkwheeler** [comment]
I'll give the release candidate a shot, but I'm 99% positive none of my `createGlobalStyles` are inside `_document` or `<NextHead>`.

**Comment by mareksuscak** [comment]
Yeah, ours is in the `_app.js` outside of `NextHead` and `Helmet` and we were seeing this issue until we downgraded.

**Comment by probablyup** [comment]
The position shouldn’t matter as long as it is being rendered during the
gIP collection phase. If the Head is being rendered after gIP that would
explain why the styles aren’t there.

**Comment by jenseralmeida** [comment]
I believe that this should be a blocker for the version 5 release. I am pasting below a complete react index.js which is not working as desired. 

The first image is the result of a developer build.

![image](https://user-images.githubusercontent.com/660075/68075689-5a01bc00-fd68-11e9-8406-1ba0558ed78c.png)

Now, this is the result of a production build.

![image](https://user-images.githubusercontent.com/660075/68075720-bf55ad00-fd68-11e9-8173-5c1ee5589339.png)

I am starting with react and I could not understand any of the workarounds that could be used and I can not make createGlobalStyle works properly on version v5. Fun-fact, the colors are being applied, but not the fonts. So, this shows that some point the style was rendered by styled-components, and later removed.


index.js
```
import "./index.css";
import React from "react";
import ReactDOM from "react-dom";
import { ThemeProvider, createGlobalStyle, css } from "styled-components";

const GlobalStyle = createGlobalStyle`
${props => props.theme.fonts.titleFace}
${props => props.theme.fonts.bodyFace}
${props => props.theme.fonts.iconsFace}

body {
    font-family: ${props => props.theme.fonts.body}, sans-serif;
}

button {
    color: ${props => props.theme.colors.color};
    background: ${props => props.theme.colors.background};
    border-color: ${props => props.theme.colors.border};
    font-family: ${props => props.theme.fonts.body}, sans-serif;
}

button:hover {
    background: ${props => props.theme.colors.highlightedBackground};
    color: ${props => props.theme.colors.highlightedColor};
    border-color: ${props => props.theme.colors.highlightedBorder};
}

button:after {
    font-family: ${props => props.theme.fonts.icons};
}
`;

const theme = {
    colors: {
        color: "#fafafa",
        background: "#181753",
        border: "#181753",
        highlightedColor: "#dfdfdf",
        highlightedBackground: "#181753",
        highlightedBorder: "#181753"
    },
    fonts: {
        title: "Muli",
        titleFace: css`
            @font-face {
                font-family: "Montserrat";
                font-style: normal;
                font-weight: 400;
                src: local("Montserrat Regular"), local("Montserrat-Regular"),
                    url(https://fonts.gstatic.com/s/montserrat/v13/JTUSjIg1_i6t8kCHKm459Wlhyw.woff2)
                        format("woff2");
                unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC,
                    U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122,
                    U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
            }
        `,
        body: "Montserrat",
        bodyFace: css`
            @font-face {
                font-family: "Montserrat";
                font-style: normal;
                font-weight: 400;
                src: local("Montserrat Regular"), local("Montserrat-Regular"),
                    url(https://fonts.gstatic.com/s/montserrat/v13/JTUSjIg1_i6t8kCHKm459Wlhyw.woff2)
                        format("woff2");
                unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC,
                    U+02C6, U+02DA, U+02DC, U+2000-206F, U+2074, U+20AC, U+2122,
                    U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD;
            }
        `,
        icons: "icomoon",
        iconsFace: css`
            @font-face {
                font-family: "icomoon";
                src: url("./fonts/IcoMoon-Free.ttf") format("truetype");
                font-weight: normal;
                font-style: normal;
            }
        `
    }
};

function App() {
    return (
        <ThemeProvider theme={theme}>
            <GlobalStyle theme={theme} />
            <HomePage />
        </ThemeProvider>
    );
}

function HomePage() {
    return <button>Continue</button>;
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

index.css
```
body {
    font-size: 16px;
    font-weight: bold;
    overflow-x: hidden !important;
    position: relative;
}

button {
    color: #fff;
    font-size: 20px;
    font-weight: bold;
    padding: 11px 60px 11px 50px;
    border-radius: 80px;
    position: relative;
    cursor: pointer;
    box-shadow: 0 10px 16px 0 rgba(0, 0, 0, 0.2),
        0 6px 20px 0 rgba(0, 0, 0, 0.19);
    border: 3px solid;
}

button:focus {
    outline: none;
}

button:active {
    outline: none;
}

button:hover {
    cursor: pointer;
}

button:after {
    content: "\ea3c";
    speak: none;
    font-style: normal;
    font-weight: normal;
    font-variant: normal;
    text-transform: none;
    line-height: 1;
    position: absolute;
    right: 10px;
    top: 28%;
    -webkit-font-smoothing: antialiased;
}
```

**Comment by probablyup** [comment]
It will always be empty in production because we use the cssom injection
APIs that browsers don’t surface in dev tools for some reason

**Comment by jenseralmeida** [comment]
Thanks for the clarification. But, still, the visual end results are different.

**Comment by 5h5ong** [comment]
# npmPackages:
- "styled-components": "^4.4.0
- "styled-reset": "^4.0.2

My SC version is not V5, but I have a similar problem for that. `createGlobalStyle` works very well as all, but only `*` part does not apply. IN PRODUCTION BUILD!
Font, `box-sizing`, `background-color`... that things all inside `*`, but is not applied.

```javascript
export default createGlobalStyle`
  ${reset}
  * {
    @import url('https://fonts.googleapis.com/css?family=Roboto&display=swap');
    font-family: 'Roboto', sans-serif !important;
    box-sizing: border-box;
    background-color: red;
  }
  body {
    min-height: ${props => props.theme.minHeight};
    padding-top: ${props => props.theme.headerPadding};
  }
`;
```

**Comment by jonkwheeler** [comment]
@5h5ong what happens if you change it to `html * {`

**Comment by 5h5ong** [comment]
@jonkwheeler Do you mean inside of css file? If then, Yes. Styles works fine in css file. I separated styles in css and html to solve this problem.

**Comment by jonkwheeler** [comment]
@5h5ong I was referring to the createGlobalStyle snippet you posted. Does changing `* {` to `html * {` fix anything?

**Comment by 5h5ong** [comment]
@jonkwheeler Oh..!
```css
html * {
  ...
}
```
Does that mean? Thanks for the advice but nothing has changed.

**Comment by jonkwheeler** [comment]
Hmm alright. I was just curious if the css parser couldn't understand something. Thanks for trying. Maybe it's the `@import`. Odd indeed.

**Comment by GiovanniFrigo** [comment]
The issue is still present in `@storybook/react v5.2.5`

I can also confirm that the issue is caused by the `@import` statement inside the global style. Removing that, the rest of the style is correctly applied to the node.

This is my globalStyle: 
```js
import { createGlobalStyle } from 'styled-components';

export const GlobalStyles = createGlobalStyle`
  body {
    @import url('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css');
    @import url('https://rsms.me/inter/inter.css');
    font-family: 'Inter', sans-serif;
    *, *::before, *::after {
      box-sizing: border-box;
    }
  }
`;
```

**Comment by PhEEP** [comment]
We are experiencing a similar issue on `v4.4.0`, here's what we found: Loading Klaviyo `analytics.js` file caused our global styling to disappear. If you're experiencing this issue, try blocking the file in your developer tools network panel. Here's the file for reference: `https://a.klaviyo.com/media/js/analytics/analytics.js` https://github.com/styled-components/styled-components/issues/2254#issuecomment-579441145

**Comment by kitten** [comment]
@GiovanniFrigo `@import` is not supported by styled-components so you should probably look into injecting that separately. BTW, it’s also not supposed to be scoped, since it’s an at-rule.

On this note, `@font-face` is also not supported. This is due to our lack of hoisting them. We skipped adding support for this for now since it’s tricky to make it work dynamically and with SSR. It’s easy enough to inject extra CSS through a multitude of other ways, so that’s why it’s been omitted 

I’m pretty sure another bug in this issue that’s being mentioned, vendored rules is not occurring anymore, since we’ve fixed it.

I also saw `:global` which shouldn’t be used inside a global component. I’m not sure whether stylis supports it, but either way, it’s redundant in a global styles component.

@PhEEP yes, third party scripts can often mess with our style tags when they’re moving our unmount if the node, or even editing it 😱 

All in all these issues in this thread all different and either in my list above or unrelated. So I’ll close and lock this issue, please create separate threads so we can track your problems and help you separately! ♥️
