### ISSUE TITLE
Using props.theme inside an interpolation

### ISSUE THREAD

**Issue by sauzy34** [styled-components/styled-components#2671]
I'm creating a styled component `<Tab active={true}>`, unable to access theme object inside it.

``` 
const Tab = styled(Link)`
  padding: 10px 0;
  width: 50%;
  display: flex;
  justify-content: center;
  position: relative;
  ${props =>
    props.active &&
    `
    ::after {
    content: '';
    height: 2px;
    background:${props => props.theme.primary};
    width: 100%;
    position: absolute;
    bottom: 0;
  }
  color:${props => props.theme.primary};
  font-weight: 600;
  
  `};
`
```

**Comment by atothek1** [comment]
@sauzy34 this is more something for the spectrum community.
but as help you need to use the css method like
`
import styled, {css} from "styled-components";

const Tab = styled(Link)`
  padding: 10px 0;
  width: 50%;
  display: flex;
  justify-content: center;
  position: relative;
  ${props =>
    props.active &&
    css`
    ::after {
    content: '';
    height: 2px;
    background:${props => props.theme.primary};
    width: 100%;
    position: absolute;
    bottom: 0;
  }
  color:${props => props.theme.primary};
  font-weight: 600;
  
  `};
`
`

**Comment by probablyup** [comment]
@atothek1 is correct, need to use the `css` named export to receive props as function arguments inside interpolations when nesting conditional styles

**Comment by Idanatiya** [comment]
Did u managed to solve it @jeanlambert17 ?
i have the same issue
