### ISSUE TITLE
5.0.0-beta.8 in npmjs may not be marked latest beta

### ISSUE THREAD

**Issue by leantide** [styled-components/styled-components#2675]
FYI. I suspect that styled-components@5.0.0-beta.6-ej4 is still marked as the latest for the beta line within npmjs, even though beta.8 has superseded it.

Having beta.6-ej4 installed, `npm update` does not indicate I need to upgrade to beta.8.

After manually installing beta.8, `npm update` indicates I need to downgrade to beta.6-ej4.

**Comment by probablyup** [comment]
Closing as we've pushed several builds since and the beta tag is now on `beta.11`
