### ISSUE TITLE
The react Native componets sounds not work

### ISSUE THREAD

**Issue by suntearinheart** [styled-components/styled-components#2676]
The latest version:

the error messages:
Invariant Violation: "barStyle" is not a valid style property.
StyleSheet generated: {
"barStyle": "'dark-content'"
}
Valid style props: [
"alignContent",
"alignItems",
"alignSelf",
"aspectRatio",
"backfaceVisibility",
"backgroundColor",
"borderBottomColor",
"borderBottomEndRadius",
"borderBottomLeftRadius",
"borderBottomRightRadius",
"borderBottomStartRadius",
"borderBottomWidth",
"borderColor",
"borderEndColor",
"borderEndWidth",
"borderLeftColor",
"borderLeftWidth",
"borderRadius",
"borderRightColor",
"borderRightWidth",
"borderStartColor",
"borderStartWidth",
"borderStyle",
"borderTopColor",
"borderTopEndRadius",
"borderTopLeftRadius",
"borderTopRightRadius",
"borderTopStartRadius",
"borderTopWidth",
"borderWidth",
"bottom",
"color",
"decomposedMatrix",
"direction",
"display",
"elevation",
"end",
"flex",
"flexBasis",
"flexDirection",
"flexGrow",
"flexShrink",
"flexWrap",
"fontFamily",
"fontSize",
"fontStyle",
"fontVariant",
"fontWeight",
"height",
"includeFontPadding",
"justifyContent",
"left",
"letterSpacing",
"lineHeight",
"margin",
"marginBottom",
"marginEnd",
"marginHorizontal",
"marginLeft",
"marginRight",
"marginStart",
"marginTop",
"marginVertical",
"maxHeight",
"maxWidth",
"minHeight",
"minWidth",
"opacity",
"overflow",
"overlayColor",
"padding",
"paddingBottom",
"paddingEnd",
"paddingHorizontal",
"paddingLeft",
"paddingRight",
"paddingStart",
"paddingTop",
"paddingVertical",
"position",
"resizeMode",
"right",
"rotation",
"scaleX",
"scaleY",
"shadowColor",
"shadowOffset",
"shadowOpacity",
"shadowRadius",
"start",
"textAlign",
"textAlignVertical",
"textDecorationColor",
"textDecorationLine",
"textDecorationStyle",
"textShadowColor",
"textShadowOffset",
"textShadowRadius",
"textTransform",
"tintColor",
"top",
"transform",
"transformMatrix",
"translateX",
"translateY",
"width",
"writingDirection",
"zIndex"
]
This error is located at:
in StyledNativeComponent (created by Styled(StatusBar))
in Styled(StatusBar) (at App.tsx:96)
in RCTView (at View.js:45)
in View (created by Context.Consumer)
in StyledNativeComponent (created by Styled(View))
in Styled(View) (at App.tsx:92)
in ApolloProvider (at App.tsx:91)
in App (at withExpoRoot.js:20)
in RootErrorBoundary (at withExpoRoot.js:19)
in ExpoRootComponent (at renderApplication.js:35)
in RCTView (at View.js:45)
in View (at AppContainer.js:98)
in RCTView (at View.js:45)
in View (at AppContainer.js:115)
in AppContainer (at renderApplication.js:34)

node_modules/react-native/Libraries/StyleSheet/StyleSheetValidation.js:78:4 in styleError
node_modules/react-native/Libraries/StyleSheet/StyleSheetValidation.js:35:17 in validateStyleProp
node_modules/react-native/Libraries/StyleSheet/StyleSheetValidation.js:56:8 in validateStyle
node_modules/react-native/Libraries/StyleSheet/StyleSheet.js:355:43 in create
node_modules/styled-components/native/dist/styled-components.native.cjs.js:5941:39 in generateStyleObject
node_modules/styled-components/native/dist/styled-components.native.cjs.js:6228:61 in
node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:12671:25 in updateContextConsumer
node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:17276:21 in performUnitOfWork
node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:17316:41 in workLoop
node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:17417:15 in renderRoot
node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:18423:17 in performWorkOnRoot
node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:18324:24 in performWork
node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:18285:14 in performSyncWork
node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:18169:19 in requestWork
node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:17969:16 in scheduleWork
node_modules/react-native/Libraries/Renderer/oss/ReactNativeRenderer-dev.js:6934:17 in enqueueSetState
node_modules/react/cjs/react.development.js:335:31 in setState
src/App.tsx:75:16 in handleFinishLoading
node_modules/expo/build/launch/AppLoading.js:31:20 in _callee$
node_modules/@babel/runtime/node_modules/regenerator-runtime/runtime.js:45:44 in tryCatch
... 14 more stack frames from framework internals
the env :
"dependencies": {
"@expo/vector-icons": "^10.0.3",
"@types/d3-ease": "^1.0.8",
"@types/react-native-vector-icons": "^6.4.1",
"@types/styled-components": "^4.1.18",
"apollo-boost": "^0.4.3",
"apollo-cache-inmemory": "^1.6.2",
"apollo-link-schema": "^1.2.3",
"eslint-plugin-import": "^2.18.0",
"expo": "^33.0.7",
"expo-cli": "^2.20.10",
"graphql": "^14.4.0",
"graphql-tools": "^4.0.5",
"native-base": "^2.12.1",
"react": "^16.8.6",
"react-apollo": "^2.5.8",
"react-dom": "^16.8.6",
"react-move": "^6.0.0",
"react-native": "https://github.com/expo/react-native/archive/sdk-33.0.0.tar.gz",
"react-native-keyboard-aware-scroll-view": "^0.8.0",
"react-native-web": "^0.11.4",
"react-navigation": "^3.11.0",
"styled-components": "^4.3.2"

my codes:
const Barstatus = styled(StatusBar)barStyle: 'dark-content';

const Container = styled.Viewflex: 1; background-color: white; justify-content: center; align-items: center;

const Title = styled.Textfont-size: 20px; font-weight: 500; color: palevioletred;

Problem: for the Text, View work fine. But Barstatus comes with error.

**Comment by hery** [comment]
That's because `barStyle` (or the hypothetical CSS equivalent `bar-style`) does not exist. You need to use valid CSS properties.
