### ISSUE TITLE
StyleSheetManager not support with ie9 - ie10

### ISSUE THREAD

**Issue by cyyyyyyyyy** [styled-components/styled-components#2684]
project use shims  for outdated browsers。
if use style components StyleSheetManager component have error with browsers console.

**Comment by probablyup** [comment]
We follow React's browser support matrix: https://reactjs.org/docs/react-dom.html and babel-transpile to the default for `@babel/preset-env`

> Sidenote, if no targets are specified, @babel/preset-env will transform all ECMAScript 2015+ code by default.

There might be some syntax we're using that doesn't overlap with preset-env perhaps... or an additional polyfill is needed above whatever React recommends. Opting styled-components into babel transpilation for your project (e.g. babel's `include` option) might be what you need.
