### ISSUE TITLE
CSS code for multiplication-x doesn't work as a value of content property

### ISSUE THREAD

**Issue by ron4ex** [styled-components/styled-components#2685]
`styled-components` doesn't seem to be applying styles when `content: "\2715"` property is used. Does it have to do with parsing since commenting that property doesn't work either? It only works if I completely remove that line. However, it is not the case with `content: "\00a9"` which is for copyright symbol. It works for some codes but doesn't for others.

I've double checked the css code for it, that doesn't seem to be an issue: https://www.toptal.com/designers/htmlarrows/symbols/multiplication-x/

## Reproduction

Check the demo here *(Removing content property applies other styles, commenting the line doesn't work)*: https://codesandbox.io/s/proud-forest-x6r8w

Here is the [corresponding stackoverflow thread](https://stackoverflow.com/questions/57095386/css-code-for-multiplication-x-doesnt-work-as-a-value-of-content-property) with some suggestions that seem to work but not universally.

**Comment by probablyup** [comment]
@ron4ex the issue is because this is a JS tagged template literal, you need to use the unicode escape value. This is one edge case where things are slightly different from regular CSS unfortunately, but easily fixed.

`content: "\u2715";` works
