### ISSUE TITLE
Disappearing property of styled button

### ISSUE THREAD

**Issue by denvash** [styled-components/styled-components#2686]
## Environment
Codesandbox.

## Reproduction

[![Edit Q-57098095](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/styled-antd-react-starter-mgule?fontsize=14)

```react
const StyledButton = styled.button``;

const id = 42;

function StripedButton({ stripeid }) {
  return (
    <StyledButton
      onClick={event => {
        event.persist();
        console.log(event.target);
      }}
      id={stripeid}
      stripeid={stripeid}
    >
      Select
    </StyledButton>
  );
}
```

## Steps to reproduce
1. Press Styled Select button
2. Press Normal Button for comparison

## Expected Behavior

The styled button will log `<button id="42" stripeid="42" class="sc-gisBJw kDlVKO">Select</button>`

## Actual Behavior

The styled button logging `<button id="42" stripeid="42">Select</button>`

**Comment by probablyup** [comment]
@denvash Hey there, I think you're saying `stripeid` isn't showing up in the sandbox right? When you use a styled DOM primitive like `styled.button` we try and filter out things we know aren't real DOM attributes to avoid React's warnings on the subject. For arbitrary data you're not using for styling it's recommended to use data attributes instead.
