### ISSUE TITLE
Invariant Violation: Minified React error #321; when trying to use styled-components as dependency on published npm package

### ISSUE THREAD

**Issue by alesanchezr** [styled-components/styled-components#2690]
## Environment

Here is the codesanbox of the bug:
https://codesandbox.io/s/agitated-mirzakhani-q0jmv?fontsize=14

## Reproduction

I'm creating a calendar component and publishing it via NPM as a package. 
This is the current code of the component, it works on storibooks on the same repositoy perfectly:
https://github.com/alesanchezr/bc-react-calendar

But when I try to use it on another project (importing it thru NPM) I get an error: `Invariant Violation: Minified React error #321; `

If I remove styled components from the library and I use css-in-js instead, everything works fine and the calendar is rendered.

The bug may be occuring because styled-components needs to remove react from the bundle and add it as peer dependency instead.

## Expected Behavior

I expected styled components to work when used on npm packages.

## Actual Behavior

styled-components only work when used in the same project.

**Comment by mmarkelov** [comment]
@alesanchezr this is not **styled-component** bug, this is bug of **react**:
https://reactjs.org/docs/error-decoder.html/?invariant=321
In you case I think this is because of it:
```
3. You might have more than one copy of React in the same app
```
And in your **package.json** React is one of dependency:
https://github.com/alesanchezr/bc-react-calendar/blob/0f199f01b2ecdc5f09d8eef4ad99ff3deb654b3f/package.json#L57-L65
I suppose move it to **peerDependencies** section should help

**Comment by 1597403461** [comment]
我也遇到了相同的问题，请问如何解决呢？

**Comment by lapongua** [comment]
For me, it has worked to move to peerDepencies the packages of the npm library. In my other project, to leave the packages as dependencies.

**Comment by sravanitriniti** [comment]
@lapongua, How did you solve the issue, can you elobarate? As I also getting this error in case of material ui components are being used and nothing helped me to solve the problem.

**Comment by estebanborai** [comment]
Im having the same issue here!

I have `react`, `react-dom` and `styled-components` in my `peerDependencies` and `devDependencies`.

The following is my `webpack.config.js`:
```
const path = require('path');

module.exports = {
  mode: 'production',
  entry: './src/index.ts',
  devtool: 'source-map',
  output: {
    path: path.resolve(__dirname, './dist'),
    filename: 'index.js',
    libraryTarget: 'umd',
    library: 'theme'
  },
  externals: [
    'react',
    'react-dom',
    'styled-components',
  ],
  module: {
    rules: [
      {
        test: /\.tsx?$/,
        loader: 'ts-loader',
        options: {
          configFile: 'tsconfig.json'
        },
        exclude: /node_modules/,
      }
    ]
  },
  resolve: {
    extensions: ['.ts', '.tsx', '.js']
  }
};
```

I'm trying to build a UI library using `styled-components`, the error happens when I import a component made with `styled-components` otherwise it doesn't happens.

Thanks in advance!

**Comment by alentor** [comment]
Hello, experiencing exact same issue with version 5.1.0

**Comment by kitten** [comment]
@estebanborai How are you importing from that library? You may still have duplication if you’re using `yarn link` or `npm link` to test it.

The easiest way to find out whether you have any duplication is to check manually whether your project and library resolve different versions of the packages by checking both’s `node_modules` structure in the target project

**Comment by estebanborai** [comment]
I think that is important to point out that Im using `lerna` to link the local package that I made for UI components with styled-components.

I'm linking my packages using the following command
```sh
lerna add <package> --scoped=<target-package>
```

I found a way around this using `webpack` alias configuration as follows:

```js
// some webpack configuration
  alias: {
    'styled-components': path.resolve(__dirname, 'node_modules', 'styled-components'),
    // ...
  }
// ...
```

I made sure that no `styled-components` directory exists inside my linked package's `node_modules` directory. Anyway, I think this is more related to how `lerna` configure linked packages?

Thanks for your advice @kitten!

**Comment by alentor** [comment]
There is seem to be some breaking changes between 4.4.1 and version 5 and up

dependencies on app which imports styled component lib

> "devDependencies": {
        "@babel/core": "^7.0.0",
        "@babel/plugin-proposal-class-properties": "^7.8.3",
        "@babel/plugin-proposal-decorators": "^7.8.3",
        "@babel/plugin-transform-runtime": "^7.9.6",
        "@babel/preset-env": "^7.9.6",
        "@babel/preset-react": "7.9.4",
        "@babel/runtime": "^7.9.6",
        "babel-loader": "^8.1.0",
        "clean-webpack-plugin": "^3.0.0",
        "css-loader": "^3.5.3",
        "cssnano": "^4.1.10",
        "file-loader": "^5.1.0",
        "html-webpack-plugin": "^4.3.0",
        "mini-css-extract-plugin": "^0.9.0",
        "optimize-css-assets-webpack-plugin": "^5.0.3",
        "sass": "^1.26.5",
        "sass-loader": "^8.0.2",
        "webpack": "^4.20.2",
        "webpack-cli": "^3.1.1",
        "webpack-dev-server": "^3.1.11"
    },
    "dependencies": {
        "axios": "^0.19.2",
        "core-js": "^3.6.5",
        "mobx": "4.15.4",
        "mobx-react": "^6.2.2",
        "react": "^16.13.1",
        "react-dom": "^16.13.1"
    }

dependencies of styled components lib

> "devDependencies": {
    "@babel/core": "^7.2.2",
    "@babel/preset-env": "7.9.6",
    "@babel/preset-react": "^7.0.0",
    "babel-loader": "8.1.0",
    "babel-plugin-styled-components": "^1.10.7",
    "css-loader": "3.5.3",
    "file-loader": "^6.0.0",
    "react": "16.8",
    "react-dom": "16.8",
    "react-is": "16.8",
    "sass": "^1.26.5",
    "sass-loader": "8.0.2",
    "style-loader": "^0.23.1",
    "url-loader": "^1.1.2",
    "webpack": "^4.28.3",
    "webpack-cli": "^3.2.0"
  },
  "dependencies": {
    "styled-components": "4.4.1"
  }


when I bump styled component version to 5, doesn't matter what version, it get the following error:

`styledComponent.js?a47f:9 Uncaught Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. `

**Comment by sandinosaso** [comment]
My problem was that I was creating an npm package library and as @mmarkelov said in his solution, moving to peerDependencies `react` and `react-dom` and also (because I am using webpack) you should add them as `externals` (https://webpack.js.org/configuration/externals/) this way webpack would not bundle them while making a build

**Comment by jordanjlatimer** [comment]
@sandinosaso This was my problem, your solution worked for me.

**Comment by DylanP97** [comment]
Hi there, 
For me this error message : Error: Minified React error #321; visit https://reactjs.org/docs/error-decoder.html?invariant=321 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.

Was caused by the extension : Loom – Screen Recorder & Screen Capture

When disabling it, the error disappeared

**Comment by jaypal-tagline** [comment]
The above solution resolved my error.
I just disabled the loom extension and the error was gone.
Thank you @DylanP97
