### ISSUE TITLE
SSR class mismatch

### ISSUE THREAD

**Issue by focux** [styled-components/styled-components#2691]
## System:
 - OS: macOS 10.14.5
 - CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
 - Memory: 61.79 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 10.15.1 - /usr/local/bin/node
 - npm: 6.9.0 - /usr/local/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.10.0 => 1.10.0
 - styled-components: ^4.3.2 => 4.3.2

## Reproduction

Using NextJS, for some reason, this produces a class mismatch between server and client:

```javascript
export const Text = styled(Box)<TextProps>(
  props => props.truncate ? 'white-space: nowrap; text-overflow: ellipsis; overflow: hidden;' : '',
  fontFamily,
  fontWeight,
  textAlign,
  lineHeight,
  letterSpacing
);
```

But if I use template string as its below, it works fine:
```javascript
export const Text = styled(Box)<TextProps>`
  ${props => props.truncate ? 'white-space: nowrap; text-overflow: ellipsis; overflow: hidden;' : ''}
  ${fontFamily}
  ${fontWeight}
  ${textAlign}
  ${lineHeight}
  ${letterSpacing}
`;
```

I'm okay using the template string version, I just wanted to post it here because I think both ways should work.

## Expected Behavior

Class name to be equal in server and client.

## Actual Behavior

Class name mismatch between server and client

**Comment by probablyup** [comment]
@focux are you only seeing this in dev?

**Comment by vitortalaia** [comment]
I'm facing the same issue, but only happens in dev environment.

**Comment by probablyup** [comment]
If it only happens in dev, please try the v5 beta. We made a lot of changes that address the problem.

**Comment by kkis** [comment]
Hello guys. Iam not sure if it is a nextjs or styled-component thema, so i also ask here.

Here is the Codesandbox example of my problem with the class mismatch. (https://codesandbox.io/s/next-typescript-app-f2k0y)

index.tsx
``` 
import * as React from "react";
import styled from "../lib/styledComponents";

const Wrapper = styled.div`
  min-height: 100vh;
`;

export default function IndexPage() {
  return <Wrapper>WrapperContent2</Wrapper>;
}

```
lib/styledComponents.tsx
```
import * as styledComponents from "styled-components";
import { ThemedStyledComponentsModule } from "styled-components";

import { Theme } from "./defaultTheme";

const {
  default: styled,
  css,
  createGlobalStyle,
  ThemeProvider,
  ThemeConsumer,
  keyframes
} = (styledComponents as any) as ThemedStyledComponentsModule<Theme>;

export {
  css,
  createGlobalStyle,
  keyframes,
  ThemeProvider,
  ThemeConsumer,
  Theme
};

export default styled;

``` 

lib/defaultTheme.tsx
```
export const defaultTheme = {
  backgroundColor: "#ffffff",
  borderRadius: "5px",
  breakpoints: ["576px", "768px", "992px"],
  color: "#666666"
};

export type Theme = Readonly<typeof defaultTheme>;
export const Theme = defaultTheme;
export default defaultTheme as Theme;

```

You can see that the error appear when i use custom theming. I would be really appreciate if someone knows how to solve the problem. I stuck since 2 weeks

**Comment by angelomichel** [comment]
I have a similar issue, also using 1.10(.7).

Both in development and in production in combination with nextjs (no special config, just default installment of the latest nextjs)

**Comment by zdila** [comment]
I also experience this problem. styled-components 5.3.0. We use custom SSR solution.
