### ISSUE TITLE
styled-components in different bundles

### ISSUE THREAD

**Issue by justnewbee** [styled-components/styled-components#2692]
### System:
 - OS: macOS 10.14.6
 - CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
 - Memory: 514.93 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
### Binaries:
 - Node: 12.6.0 - /usr/local/bin/node
 - Yarn: 1.17.3 - /usr/local/bin/yarn
 - npm: 6.9.0 - /usr/local/bin/npm
### npmPackages:
 - styled-components: ^4.3.2 => 4.3.2

## Reproduction

On one page, there might be more than 1 bundles with styled-components (which cannot be compromised..).

Let's say `app-base.js` and `app.js` (one does NOT know a nother).

And there might be one package (say, `icon`) using styled-component, bundled inside both`app-base.js` and `app.js`. 

## Steps to reproduce

Some times, it works fine.

However, sometimes, it will break by throwing error as below: 

```
Error: "An error occurred. See https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/utils/errors.md#10 for more information."
```

## Expected Behavior

`styled-components` in different bundles shall NOT interfere with others (at least shall NOT throw error).

## Actual Behavior

It breaks, and caused it not possible to use if there's need of different bundles in one page.

**Comment by justnewbee** [comment]
the error was given by the code below

```
/* retrieve a sheet for a given style tag */
var sheetForTag = function sheetForTag(tag) {
  // $FlowFixMe
  if (tag.sheet) return tag.sheet;

  /* Firefox quirk requires us to step through all stylesheets to find one owned by the given tag */
  var size = document.styleSheets.length;
  for (var i = 0; i < size; i += 1) {
    var sheet = document.styleSheets[i];
    // $FlowFixMe
    if (sheet.ownerNode === tag) return sheet;
  }

  /* we should always be able to find a tag */
  throw new StyledComponentsError(10);
};
```

**Comment by michelson** [comment]
same issue here , I'm trying to build an embeddable component with uses styled component . The idea is to import the script like regular embeds. This limitation makes styled-components unusable for this kind of contexts. 

is there any way to tackle this ?

**Comment by probablyup** [comment]
Hey there, please see this FAQ article: https://www.styled-components.com/docs/faqs#why-am-i-getting-a-warning-about-several-instances-of-module-on-the-page

This error is generally due to multiple copies of s-c being bundled in the same app and conflicting with each other.

**Comment by michelson** [comment]
Hi @probablyup , I'm aware of the problem of multiple bundles explanation, but I think the issue is precisely about that.
Is practically imposible to load 2 applications with styled components. The use case for this limitation is when you import an external script with styled components already bundled , like: embeds widgets

I just ported my project to emotion-styled and it works fine

**Comment by probablyup** [comment]
@michelson we are a singleton library like React, so this is to be expected. There are various strategies to support the "microfrontend" pattern like loading styled-components from CDN for the browser instead of directly bundling it.

**Comment by justnewbee** [comment]
my brilliant co-worker came up with this solution however, by adding a webpack plugin the minimum of webpack plugin snippet is like below:

```
new webpack.DefinePlugin({
  'process.env.REACT_APP_SC_ATTR': JSON.stringify('data-styled-__YOUR_APP_NAME__'),
  'process.env.SC_ATTR': JSON.stringify('data-styled-__YOUR_APP_NAME__')
})
```

fill `__YOUR_APP_NAME__` with the ID of your app

the 2  `process.env.REACT_APP_SC_ATTR` and `'process.env.SC_ATTR` is referred in the code:

```
var SC_ATTR = typeof process !== 'undefined' && (process.env.REACT_APP_SC_ATTR || process.env.SC_ATTR) || 'data-styled';
```

that does the magic!

i have used it with style-component@4.4.1 and tested it in my environment where multiple instances from different buddles occur

and... with all due respect, i don't really think react is a singleton, our bundles have their own react

it is not possible to use one single react or styled-components due to various reasons

hope this will help those who have the same problem out there

**Comment by justnewbee** [comment]
the solution i gave previously might not work for 5.1 versions
so i made some changes and committed a pull request, if that PR is finally merged, we can still use webpack's DefinePlugin as below:

```
new webpack.DefinePlugin({
  'process.env.SC_CLASS_PREFIX': JSON.stringify(_a_very_short_but_specific_prefix_)
})
```
