### ISSUE TITLE
Invariant Violation: Invalid hook call when using useRef hook with component selector

### ISSUE THREAD

**Issue by muscat1** [styled-components/styled-components#2693]
## Environment
Sandbox where the behavior is reproduced:
https://codesandbox.io/embed/affectionate-cherry-muhoh

## Reproduction
I am currently creating a component A that uses the `useRef` hook. I import A in a different location and, when styling a containing component, B, I use a selector to target A and I get the following error:
```
Invariant Violation Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.
```

I don't seem to violate any of the hook rules and if I use a className to target the component, rather than the component selector, the behavior no longer reproduces.

## Expected Behavior

Use component selector to target components that use hooks (useRef).

## Actual Behavior

I get an error and have to use className instead.

**Comment by probablyup** [comment]
You must be trying to use a non-styled component as a selector.

**Comment by muscat1** [comment]
I tried selecting a styled component as well, the behavior was the same

**Comment by adamborowski** [comment]
Any explanation why we get this error? I also faced this issue recently
