### ISSUE TITLE
Media queries  not working with 'styled-components/primitives'

### ISSUE THREAD

**Issue by bidah** [styled-components/styled-components#2695]
When using Expo for web if you are styling with Styled Components the media query functionality does not work.

I made a tagged template literal to overcome this limitation. but feels hacky if you have styled components supporting media queries.

```
const isDesktop = (strings, ...values) => {
  if (
    !["ios", "android"].includes(Platform.OS) &&
    Dimensions.get("window").width >= 1024
  ) {
    return strings.reduce((result, string, i) => {
      return `${result}${string}${values[i] || ""}`;
    }, "");
  }

  return "";
};
```

## Environment
Expo Snack

## Reproduction
https://snack.expo.io/@bidah/expo-web-with-desktop-views

## Expected Behavior
media queries to work when using styled-components or styled-components/primitives with Expo for web.

## Actual Behavior
media queries  not working

**Comment by probablyup** [comment]
Your expo has nothing to do with the OP... going to close.
