### ISSUE TITLE
Referring to other components with react native doesn't seem to work

### ISSUE THREAD

**Issue by ivansantosz** [styled-components/styled-components#2696]
## System:
 - OS: macOS 10.14.5
 - CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
 - Memory: 516.02 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 10.16.0 - /usr/local/bin/node
 - Yarn: 1.17.3 - /usr/local/bin/yarn
 - npm: 6.9.0 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^4.3.2 => 4.3.2

## Reproduction
Expected to be able to do something like:

```
import { css } from 'styled-components/native';
import { StyledButton } from '../../../components/Button';

const fluidCSS = css`
    display: flex;

    ${StyledButton} {
        flex-grow: 1;
    }
`;
```

## Expected Behavior
Would like to apply custom styles to children that belongs to the type of component I passed.
## Actual Behavior
It doesn't work with react native

**Comment by probablyup** [comment]
Yup this is valid, react-native styling gets desugared into inline styles so there's no way to actually do component selectors. The docs should be updated to reflect that it's a web-specific API.

Would you be interested in contributing this to https://github.com/styled-components/styled-components-website ?

**Comment by pragmaticivan** [comment]
I was able to work around by iterating through children components but was not able to translate the children into styled-components again. I was kinda forced to pass `style` props for that. 

There was also not a way to extract the current styles of a styled component to convert it to an object, maybe that's something could be added to the docs?

I would be interested in contributing to the website.
