### ISSUE TITLE
Enable styling of AMP components by whitelisting amp attributes

### ISSUE THREAD

**Issue by the-architect** [styled-components/styled-components#2698]
AMP component have different attributes than the standard DOM elements. Since StyledComponents filters attributes it is currently not possible to use StyledComponents with AMP components.

Solution: Whitelist amp component custom attributes.

**Comment by the-architect** [comment]
Are you using the @emotion/is-prop-valid package to filter for valid props? Then its better to open the issue over there instead. 👷🏻‍♂️

**Comment by probablyup** [comment]
Yup you'd want to do it over there

**Comment by the-architect** [comment]
@probablyup alrighty :) closing

**Comment by the-architect** [comment]
so it turns out emotion can pass arbitrary props using `shouldForwardProp`. Is something like this possible with StyledComponents? emotion issue: https://github.com/emotion-js/emotion/issues/1453
