### ISSUE TITLE
`createGlobalStyle` fails with an error

### ISSUE THREAD

**Issue by RobinKnipe** [styled-components/styled-components#2699]
# `createGlobalStyle` fails with an error
The following simple example shows the problem when trying to add a basic global style. It's pretty much what's in your docs, so if I'm missing something, they might need an update.

## Reproduction
- a _codes and box_ example: https://codesandbox.io/embed/styled-components-157vh

## Steps to reproduce
The error occurs when the app is rendered, no special steps are needed, just look at the output window.

## Expected Behavior
The `font-family: Arial, Helvetica, sans-serif;` style is applied to the `body` element, and no error occurs.

## Actual Behavior
An error breaks the app, nothing is rendered:
```
Error
Cannot create styled-component for component: 
  body {
    font-family: Arial, Helvetica, sans-serif;
  }
```

**Comment by imbhargav5** [comment]
Please install styled-components@4.0.0+ and also. CreateGlobalStyle is a named export. So replace the import with this. 
`import {createGlobalStyle} from 'styled-components'`
