### ISSUE TITLE
Debugging Tips & Tools

### ISSUE THREAD

**Issue by santaclauze** [styled-components/styled-components#270]
Been working with styled components for a bit more than a months. I often encounter errors related to the css I inject and end up with some very vague errors. 

Some minor mistakes end up affecting the rendering of css and make it a lot harder to debbug.

I was wondering if there are commands or certain steps that may help in this process apart from the typical console logging? 

## Version
1.1.2

**Comment by mxstbr** [comment]
We can definitely improve on our logging, I'd love to have a better debugging experience in relation to badly formatted CSS. (see #234 too)

**Comment by AlexLeung** [comment]
In addition to better logging, it would be neat if someone wrote a Chrome Developer Tools plugin specifically for this library. The tool could transform the name of the generated CSS class to show which component file it originated from.

**Comment by mxstbr** [comment]
> The tool could transform the name of the generated CSS class to show which component file it originated from.

`v2` + our babel plugin will do this for you 😉

**Comment by AlexLeung** [comment]
Ooo sweet! Thank you!

**Comment by mxstbr** [comment]
Since v2 and the babel plugin are now out I'll close this issue. If you have any further ideas on how to improve the debugging experience feel free to open a new one!
