### ISSUE TITLE
themed-styling: fallback theme key styles

### ISSUE THREAD

**Issue by DannyJoris** [styled-components/styled-components#2700]
In the following example with 3 theme key variations I'd like to be able to set a fallback for code simplicity. In this scenario Beta looks almost identical to Alpha (the default) except it has different base variables for colors, but it has the occasional style override. Charlie also has a range of color variables, but each component looks very different than the default. I'm expected to write different styles or overrides for all components with Charlie. I have the following to simplify it, but I was thinking it would be great that when I leave out Beta, it would fall back to the default styles of Alpha.

Currently I have this, but if I leave out the Beta definition, they will remain unstyled.

```
const defaultButtonStyles = css`
    font-size: 20px;
    background: ${({ theme }) => theme.colors.primary};
    color: #fff;
`;

const buttonStyles = theme('kind', {
  alpha: css`
    ${defaultButtonStyles}
  `,
  beta: css`
    ${defaultButtonStyles}
  `,
  charlie: css`
    padding: 5px 10px;
    font-size: 25px;
    border: ${({ theme }) => theme.colors.secondary} 5px solid;
    border-radius: 5px;
    background: ${({ theme }) => theme.colors.primary};
    color: #fff;
  `,
});
```

Ideally I'd like to write something that looks like the following, where if they key is set to Beta and the styles aren't defined, it would use the default alpha styles:
```
const buttonStyles = theme('kind', {
  alpha: css`
    font-size: 20px;
    background: ${({ theme }) => theme.colors.primary};
    color: #fff;
  `,
  charlie: css`
    padding: 5px 10px;
    font-size: 25px;
    border: ${({ theme }) => theme.colors.secondary} 5px solid;
    border-radius: 5px;
    background: ${({ theme }) => theme.colors.primary};
    color: #fff;
  `,
});
```

Or maybe a generic `default` key could be useful:
```
const buttonStyles = theme('kind', {
  default: css`
    font-size: 20px;
    background: ${({ theme }) => theme.colors.primary};
    color: #fff;
  `,
  charlie: css`
    padding: 5px 10px;
    font-size: 25px;
    border: ${({ theme }) => theme.colors.secondary} 5px solid;
    border-radius: 5px;
    background: ${({ theme }) => theme.colors.primary};
    color: #fff;
  `,
});
```

**Comment by probablyup** [comment]
Hey there, `ThemeProvider` is the right way to handle this. You can have multiple instances in your component tree to supply the right theme parameters for your subtrees as needed. You can also use the function variant of the `theme` prop in `ThemeProvider` to override the top-level theme if you're just making small adjustments: https://www.styled-components.com/docs/advanced#function-themes
