### ISSUE TITLE
After build, nested pseudo classes does not work as expected

### ISSUE THREAD

**Issue by wxjzeke** [styled-components/styled-components#2710]
## System:
 - OS: macOS 10.14.1
 - CPU: (4) x64 Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz
 - Memory: 77.45 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
 - Yarn: 1.7.0 - /usr/local/bin/yarn
 - npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
 - Watchman: 4.9.4 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^5.0.0-beta.8 => 5.0.0-beta.8
 - react: ^16.8.6

## Reproduction
my code:
```js
const StyledInput = styled.input`
  width: 160px;
  border-radius: 2px;
  height: 20px;
  margin: 0 10px;
  padding: 0 5px;
  border: 1px solid #8793ab;
  text-align: center;
  font-size: 14px;
  color: #000;
  &::placeholder {
    color: red;
  }
  &:focus {
    background: rgb(220, 229, 246);
    outline: none;
    &::placeholder {
      color: rgba(0, 0, 0, 0);
    }
  }
`
```

## Steps to reproduce
```bash
yarn build
serve -s build
```

## Expected Behavior
- everything works fine in dev.

![image](https://user-images.githubusercontent.com/8022227/62762306-68b73a80-babb-11e9-94b6-a548975d4b8b.png)

and focus:
![image](https://user-images.githubusercontent.com/8022227/62762324-71a80c00-babb-11e9-87cd-adc4cf7aa314.png)

#### but after  build, focus styles does not work

![image](https://user-images.githubusercontent.com/8022227/62762541-f004ae00-babb-11e9-8263-81800b59ca86.png)

focused:
![image](https://user-images.githubusercontent.com/8022227/62762636-25a99700-babc-11e9-924e-eed337f96217.png)

and if I put `&::placeholder` later the `&:focus`
```
  &:focus {
    background: rgb(220, 229, 246);
    outline: none;
    &::placeholder {
      color: rgba(0, 0, 0, 0);
    }
  }
  &::placeholder {
    color: red;
  }
```
the later `placeholder { color: red;}`  does not work, but `focus` is ok.
![image](https://user-images.githubusercontent.com/8022227/62762437-acaa3f80-babb-11e9-9eb0-c755bfae82cc.png)
focused:
![image](https://user-images.githubusercontent.com/8022227/62762116-ecbcf280-baba-11e9-86b3-183d2d1df166.png)
#
btw, the `style` tag is empty.
![image](https://user-images.githubusercontent.com/8022227/62763252-ad43d580-babd-11e9-9390-de0216ec759d.png)

**Comment by tommedema** [comment]
I'm also experiencing issues with nested pseudo selectors.

This applies the orange color, but not the :after content:

```
const TextInput = styled.input`
  &::placeholder {
    color: orange;

    &:after {
      content: " *";
      color: red;
    }
  }
}
```

![Screen Shot 2019-09-23 at 3 41 48 PM](https://user-images.githubusercontent.com/331833/65468360-afb58100-de18-11e9-8573-3da7e7af4e3a.png)


I've tried variations like `&::after`, `:after`, `::after` too, with no success.

**Comment by probablyup** [comment]
placeholder can’t have pseudocontent
