### ISSUE TITLE
Top and Bottom (all around) box shadow on React Native components 

### ISSUE THREAD

**Issue by akedalat** [styled-components/styled-components#2712]
Hi, everyone!

I'm trying to add box-shadow on `Styled.View` but looking to apply shadow on all sides of a component.
In pure CSS it would be like this: 

`box-shadow: 5px 5px 8px red, -5px -5px 8px blue;`

but this solution crashes on React Native! 

Any idea?

**Comment by kristerkari** [comment]
Hi @akedalat!

Sorry about the delayed response, but the reason for this is that React Native only supports setting a single `box-shadow` on an element, so multiple box shadows separated with commas can not be supported.
