### ISSUE TITLE
There was an error trying to load the config "styledComponents" for the macro imported from "styled-components/macro. Please see the error thrown for more information.

### ISSUE THREAD

**Issue by Hurtak** [styled-components/styled-components#2713]
## System:
 - OS: macOS 10.14.5
 - CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
 - Memory: 90.07 MB / 8.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 10.16.0 - /usr/local/bin/node
 - Yarn: 1.17.3 - /usr/local/bin/yarn
 - npm: 6.9.0 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: 4.3.2 => 4.3.2 

# Problem

When using styled-components/macro inside create-react-app latest `3.1.0` it shows following warnings during start and build commands. Did not happen in `3.0.1`.

```
There was an error trying to load the config "styledComponents" for the macro imported from "styled-components/macro. Please see the error thrown for more information.
```

Probably related https://github.com/styled-components/styled-components/issues/2630

**Comment by cburkins** [comment]
Seeing same issue

**Comment by probablyup** [comment]
Oh cute, that must be a recent breaking change.

**Comment by Dagurmart** [comment]
Is there a workaround or should I just wait for the fix?

**Comment by probablyup** [comment]
The workaround is to put the empty config object in your package json

**Comment by Dagurmart** [comment]
I tried adding
`"styledComponents": {},`
to package.json but it had no effect

**Comment by lucleray** [comment]
This was tackled in version 2.7.1 of babel-plugin-macros (see https://github.com/kentcdodds/babel-plugin-macros/pull/136).

To fix it, you can just update babel-plugin-macros with `yarn add babel-plugin-macros --dev`.

With this fix, the workaround of putting an empty config in package.json is not necessary anymore 🙂
