### ISSUE TITLE
Suspected bug: `ref` doesn't execute when passed through `.attrs({})`.

### ISSUE THREAD

**Issue by thecalliopecrashed** [styled-components/styled-components#2714]
## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`

```
## System:
 - OS: macOS 10.14.6
 - CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
 - Memory: 43.69 MB / 8.00 GB
 - Shell: 3.0.2 - /usr/local/bin/fish
## Binaries:
 - Node: 12.1.0 - ~/.nodenv/shims/node
 - Yarn: 1.16.0 - /usr/local/bin/yarn
 - npm: 6.9.0 - ~/.nodenv/shims/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^4.3.2 => 4.3.2 
```

## Reproduction

https://codesandbox.io/s/styled-components-hsufl

## Expected Behavior

On initial render, the `autoResizeHeight` function is only called for `DynamicHeightText`,
not for `MultilineText`. This is because the `ref` attribute passed into `styled.textarea.attrs` isn't getting picked up and run. It is only run when passed in by a parent component.

This behavior is inconsistent with other `attrs({})` passed in to the styled-component, as demonstrated by the `onChange` attr which functions as expected.

## Actual Behavior

Both components should resize properly on their initial render.

**Comment by probablyup** [comment]
@thecalliopecrashed can you try this with v4.4, I think it should be fixed with the change to correctly override props with attrs. Example sandbox: https://codesandbox.io/s/styled-components-yr4rs
