### ISSUE TITLE
`sheet.seal()` Documentation Question

### ISSUE THREAD

**Issue by chaffeqa** [styled-components/styled-components#2715]
The [documentation example](https://www.styled-components.com/docs/advanced#example) and the note in further down don't seem to agree:

```typescript
import { renderToString } from 'react-dom/server'
import { ServerStyleSheet } from 'styled-components'

const sheet = new ServerStyleSheet()
try {
  const html = renderToString(sheet.collectStyles(<YourApp />))
  const styleTags = sheet.getStyleTags() // or sheet.getStyleElement();
} catch (error) {
  // handle error
  console.error(error)
} finally {
  sheet.seal()
}
```

> If rendering fails for any reason it's a good idea to use try...catch...finally to ensure that the sheet object will always be available for garbage collection. Make sure sheet.seal() is only called after sheet.getStyleTags() or sheet.getStyleElement() have been called otherwise a different error will be thrown.

In the example, if `const html = renderToString(sheet.collectStyles(<YourApp />))` throws, `sheet.getStyleTags()` would not have been called.  The note above states that you should only call `.seal()` if `sheet.getStyleTags()` or equiv is called.  So which is it?  Should the sample be:

```typescript
import { renderToString } from 'react-dom/server'
import { ServerStyleSheet } from 'styled-components'

const sheet = new ServerStyleSheet()
let needsSealing = false;
try {
  const html = renderToString(sheet.collectStyles(<YourApp />))
  needsSealing = true;
  const styleTags = sheet.getStyleTags() // or sheet.getStyleElement();
} catch (error) {
  // handle error
  console.error(error)
} finally {
  if (needsSealing) {
    sheet.seal()
  }
}
```

Or should the note be updated to something different?

**Comment by jepser** [comment]
Hey, `getStyleTags` internally calls `seal()` and `seal()` does a check if the instance is already sealed.

So even if it throws before calling `getStyleTags`, it the testing condition is not needed.

Here the class definition: https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/models/ServerStyleSheet.js

**Comment by chaffeqa** [comment]
oh great, so the code sample was correct, the documentation was a lil misleading imo
