### ISSUE TITLE
Accessibility Linting using Styled Components

### ISSUE THREAD

**Issue by daraclare** [styled-components/styled-components#2718]
Hi, and thanks for a great library! I'm not sure if the below falls under usage or feature request, but I can't find anything in your issues that relates to the below, and the only related stackoverflow question I could find is unanswered: https://stackoverflow.com/questions/56461352/eslint-plugin-to-detect-accessibility-problems-of-react-components-written-with

I am trying to implement accessibility linting using `tslint-react-a11y` on a project that uses Styled-components. However, the linting will not work on styled components, only plain jsx/html elements. The plugin doesn't recognise the styled components as any html element and so does not apply the error/warning.

Would it be possible to implement some kind of built in linting for accessibility, or is there a work around for this I haven't found? Any advice would be great :)

**Comment by daraclare** [comment]
Anyone have any advice on the above? Would like to provide some kind of a11y linting for styled-components.

**Comment by probablyup** [comment]
This is a great topic. We don't provide anything like this at the library level, but there definitely have been attempts to do linting of styled-components: https://github.com/styled-components/stylelint-config-styled-components for example

> However, the linting will not work on styled components, only plain jsx/html elements.

That's interesting... my armchair guess is the linting is based on referred types and for whatever reason the types presented by DefinitelyTyped don't match or something. We don't deal with TS in this repo, so I'd recommend engaging that community specifically. SO & Spectrum are great places to start.

**Comment by daraclare** [comment]
I guess the issue is more with linting and accessibility, rather than Typescript, I just used `tslint-react-a11y` as an example of a a11y linter that is blocked by styled-components. Is there another accessibility linter that works with styled-components? I couldn't get anything that could accurately read styled-components and warn if accessibility issues would arise. Is it possible that styled-components could have a rule that could be switched on/off that warns if an element is missing accessibility attributes? Otherwise, is using styled-components hurting accessibility?

**Comment by brendanmorrell** [comment]
I've been working on an eslint plugin to solve this issue in my spare time.You can use it now if you clone the repo, but I want to make it more robust/add more tests before releasing it on npm to make sure it's solid enough for production use. If anyone is interested in helping out to expedite the process, here is the repo: https://github.com/brendanmorrell/eslint-plugin-jsx-a11y-styled-components

It handles all 4 methods styled components uses to create components. All of these would show the error `Visible, non-interactive elements with click handlers must have at least one keyboard listener.`

1) <code>const Div = styled.div\`\`;</code>   
<code>&lt;Div onClick={() => null}/>. </code>

2) <code>const Div = styled.div.attrs({ onClick: () => null})\`\`;<code/>
<code>&lt;Div /></code>
3) <code>const StyledDiv = styled(Div)\`\`;</code>
<code>&lt;StyledDiv onClick{() => null} /></code>
4)<code>const ButtonAsDiv = styled.button\`\`;  </code>
<code>&lt;ButtonAsDiv as="div" onClick={() => null} /></code>

**Comment by brendanmorrell** [comment]
Wasn't sure if anyone would see this, but I guess people are. so here are some updates:

1) published the package to npm under `eslint-plugin-styled-components-a11y` (npm.com still seems to have it listed under the old name eslint-plugin-jsx-a11y-styled-components, but downloading the package uses `eslint-plugin-styled-components-a11y`

2) added a brief readme to the github repo and changed the name as well to `eslint-plugin-styled-components-a11y`

3) added an example repo for how to set up the linter as it currently requires the rules to be explicitly specified in the eslintrc

Will try to keep working on this and add more info, but have a lot going on with work etc. so not a ton of additional time to put into this right now. Thanks!

**Comment by peraltafederico** [comment]
> Hey, I made a pretty cool plugin for this (hopefully). It found 6,567 errors in one of my repos that were undiscovered using airbnb/jsx-a11y rules. Please give it a star so we can get more people interested, using it, and contributing to make a more accessible internet for all.
> 
> Here’s the [github repo](https://github.com/brendanmorrell/eslint-plugin-styled-components-a11y) it covers all 4 styled components/emotion syntaxes
> 
> Existing a11y linting has become significantly less useful (personally, 99% of the components I need linted are styled.). Each scenario below would display the error
> 
> ```
> Visible, non-interactive elements with click handlers must have at least one keyboard listener.`
> ```
> 
> ```
> const Div = styled.div``;
> <Div onClick={() => null}/>
> ```
> 
> ```
> const Div = styled.div.attrs({ onClick: () => null})``;
> <Div />
> ```
> 
> ```
> const Div = styled.div.attrs({ onClick: () => null})``;
> const StyledDiv = styled(Div)``;
> <StyledDiv />
> ```
> 
> ```
> const ButtonAsDiv = styled.button``;
> <ButtonAsDiv as="div" onClick={() => null} />
> ```
> 
> It’s not perfect (no linters are), but it’s super useful, and with a little time and community support, it could be even better.

Just want to say thank you! Awesome job!!

**Comment by brendanmorrell** [comment]
Thanks @peraltafederico! Glad you like it. It's nice to know people are finding it useful. Gives me more motivation to improve on it moving forward. Thanks again!
