### ISSUE TITLE
Provide easier way to access the theme outside 'styled' components

### ISSUE THREAD

**Issue by brunolemos** [styled-components/styled-components#272]
It's easy to get the `theme` from components that are created using the `styled` way:

```jsx
const StyledView = styled.View`
    color: ${({ theme }) => theme.color};
`;
```

But how to get from **normal components** or apply it for **different properties**? Example:

```jsx
<ThemeProvider theme={{ color: 'red' }}>
    <Main />
</ThemeProvider>
```
```jsx
<View>
    <Card aCustomColorProperty={PASS COLOR FROM THEME HERE} />
</View>
```
> Notice how the property that needs the theme is called `aCustomColorProperty`, not `style`

We can use this issue to discuss the topic and provide different solutions.
I'll post mine in the next comment.

_This was originally posted on [stackoverflow](http://stackoverflow.com/q/40796973/2228575) and [asked by @mxstbr](http://stackoverflow.com/questions/40796973/how-to-get-the-theme-outside-styled-components#comment68961671_40848211) to be posted here_

**Comment by brunolemos** [comment]
This is the current solution I'm using to solve this:

Create a **Higher Order Component** (HoC) that will be responsable to subscribe to the theme changes pass a `theme` prop to any component:

```jsx
import React from 'react';
import { CHANNEL } from 'styled-components/lib/models/ThemeProvider';

export default Component => class extends React.Component {
  static contextTypes = {
    [CHANNEL]: React.PropTypes.func,
  };

  state = {
    theme: undefined,
  };

  componentWillMount() {
    const subscribe = this.context[CHANNEL];
    this.unsubscribe = subscribe(theme => {
        this.setState({ theme })
  });
  }

  componentWillUnmount() {
    if (typeof this.unsubscribe === 'function') this.unsubscribe();
  }

  render() {
    const { theme } = this.state;

    return <Component theme={theme} {...this.props} />
  }
}
```

Then, call it on the component you need to access the `theme`:
```jsx
import Themable from './Themable.js'
   
const Component = ({ theme }) => <Card color={theme.color} />

export default Themable(Component);
```

`Styled-components` could provide something like this inside the library.

**Comment by danieldunderfelt** [comment]
@brunolemos awesome, I'm stealing this! Thanks :D

**Comment by degroote22** [comment]
I had to create another wrapper to pass the theme around in the context. I don't think this HOC is needed but a clear naming convention for the theme provider that's in use would do it and we'd use react's contexType to get it etc

**Comment by wmertens** [comment]
This could be a decorator, e.g.

```js
import {withTheme} from 'styled-components'

@withTheme
class ... {
  render() {
    const {theme} = this.props
    ...
  }
}
```

**Comment by brunolemos** [comment]
Yeah I use it as a decorator (`@Themable`), it's great.

I was thinking, if the `styled` also passed the `theme` props, that could work. But, all components would rerender when the theme updates, even if it's not using the theme. So it's probably not worth it. 
 
About the use of context, this is a good read about its problems: https://medium.com/@mweststrate/how-to-safely-use-react-context-b7e343eff076

Waiting for more opinions! I could do a PR if you think this solution is fine.

**Comment by mxstbr** [comment]
> About the use of context, this is a good read about its problems: https://medium.com/@mweststrate/how-to-safely-use-react-context-b7e343eff076

We fix all of those already, don't worry 😉

> I could do a PR if you think this solution is fine.

I think a `withTheme` wrapper would be helpful, please do submit a PR!

Don't use decorator notation in the docs though, as that's just unnecessarily confusing – not everybody knows how they work, and this works just the same but is clearer:

```JS
import { withTheme } from 'styled-components'

class Component extends React.Component {
  render() {
    const {theme} = this.props
  }
}

export default withTheme(Component)
```

Now people who know decorators know they can use it as a decorator, and people who don't know decorators also know how to use it without! Win-win 🎉

**Comment by mgan59** [comment]
Was looking for an example like this on the docs/website and couldn't find it.  Eventually the right google search led me here, but this needs to get surfaced up further into the docs for advanced/themes

**Comment by zhaluza** [comment]
@mgan59 The ["Advanced" section of the docs](https://styled-components.com/docs/advanced) discusses how to do this with `useContext`, although it's admittedly buried in there. I think it should have its own header in the sidebar, because I almost missed it myself.

**Comment by kitten** [comment]
@zhaluza It's under: "Theming" -> "Getting the theme without styled components." I believe that that can't get clearer if we consider that any given sub-topic isn't more important than another. Please do consider that the site has a search, issues do, and if that fails maybe we can avoid your search next time by getting you a quicker community answer on Spectrum 🙌 If all else fails, although issues _aren't_ the right place for questions most of the time, it would guarantee a quicker answer.

Anyway, I'll have to lock this, since this is **four** years old, so this pings a lot of unrelated people, on an issue that implemented part of this sub-topic, but not even all of it. Sorry!
