### ISSUE TITLE
Components with same props and css generating duplicate classes

### ISSUE THREAD

**Issue by andybflynn** [styled-components/styled-components#2720]
## System:
 - OS: macOS Sierra 10.12.6
 - CPU: (8) x64 Intel(R) Core(TM) i7-4960HQ CPU @ 2.60GHz
 - Memory: 1.12 GB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 8.6.0 - ~/.nvm/versions/node/v8.6.0/bin/node
 - npm: 5.4.2 - ~/.nvm/versions/node/v8.6.0/bin/npm
## npmPackages:
 - styled-components: ^4.3.2 => 4.3.2

### demo.js
```
import * as React from 'react';
import styled, {css} from 'styled-components';

const boxStyles = css`
  width: 100px;
  height: 100px;
  border: 1px solid black;
  background-color: peachpuff;
`

const Box = styled.div`
  ${boxStyles}
`;

const OtherBox = styled(Box)``;

export default () => (
  <>
    <Box></Box>
    <OtherBox></OtherBox>
  </>
)
```

## Steps to reproduce
Import and render the demo.js file above.

## Expected Behavior
Box and OtherBox share the same props and the CSS generated will be the same, therefore one dynamic class should be created and shared by both Box and OtherBox.

## Actual Behavior
Two classes are generated, each with all of the properties in.

Box:
![image](https://user-images.githubusercontent.com/7392812/63178759-9a437f00-c042-11e9-819e-3aeb057fb845.png)

OtherBox:
![image](https://user-images.githubusercontent.com/7392812/63178779-a6c7d780-c042-11e9-837a-fc1d6c1f4331.png)

**Comment by andybflynn** [comment]
This issue seems to only be present in versions 4+ as going back to v3.4.10 places the styles into one CSS class as expected.

**Comment by probablyup** [comment]
The hasher takes a variety of data into account when generating a unique style className, so in an extended component scenario you'd never get a deduplicated style for this reason.

https://github.com/styled-components/styled-components/blob/9893aa0f75b128534a2200a27e7f445273193b1b/packages/styled-components/src/models/ComponentStyle.js#L56
