### ISSUE TITLE
How can I use styled-components v4 with react 16.2

### ISSUE THREAD

**Issue by shmilyoo** [styled-components/styled-components#2722]
I have some projects dependencd with react 16.2.0, so  when I use styled-components v4.x, ther are errors like `TypeError: Object(...) is not a function ` in console . I know styled-components4 suggests use react version >= 16.3. But the projects cannot update the react version now. 
Is there any good idea to use >=16.3 react version with styled-components v4. How can I polyfiil it?

**Comment by wojtekmaj** [comment]
Perhaps a more detailed call stack would shed more light onto the error you're facing.

**Comment by shmilyoo** [comment]
I have change my code and downgrade styed-compnents from v4 to v3 to fit react 16.2.
