### ISSUE TITLE
Styled-Component input losing focus defined outside and imported

### ISSUE THREAD

**Issue by cbryant24** [styled-components/styled-components#2723]
I have a `Field` component I've created with creates an `input` field using `styled-component`. The issue I'm seeing is when I type in the input field the focus is lost as a new `Field` component is rendered on each value input. I've looked at similar issues raised [here](https://github.com/styled-components/styled-components/issues/1166) But I'm not defining the styled-component in the render method as I'm using functional components and importing the `Field` component but I'm still seeing the re-render lost focus issue. I've also created a repo [here](https://github.com/cbryant24/react-form) if more details are needed. 

## Reproduction
https://codesandbox.io/embed/react-styled-component-issue-fd3n0

## Steps to reproduce
Type in input to see field lose focus

## Expected Behavior
Focus should stay within input field when typing

## Actual Behavior
Focus is lost on each input value change

**Comment by probablyup** [comment]
Hm I'm not seeing the bug you're describing in that sandbox.
