### ISSUE TITLE
Local fonts not loading properly

### ISSUE THREAD

**Issue by ottoo** [styled-components/styled-components#2728]
## System:
 - OS: macOS 10.14.6
 - CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
 - Memory: 517.05 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 10.16.0 - /usr/local/bin/node
 - Yarn: 1.17.0 - /usr/local/bin/yarn
 - npm: 6.9.0 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: 5.0.0-beta.8 => 5.0.0-beta.8

## Reproduction

I'm getting weird issues fonts not always being applied to the components correctly. The whole font file is not loaded in some cases. In this example I was using 5.0.0-beta.8 but this happened with the latest 4.x too.

In the codesandbox below, I have a very simple example where I add a `@font-face` in `createGlobalStyle` and then reference that font in a `styled.div` component and the font is not loading.

This happened on my and co-workers machine as well in very basic CRA projects.

What am I missing here?

https://codesandbox.io/s/distracted-williams-y2s87

## Steps to reproduce

Add a local font as a @font-face to `createGlobalStyle` and then apply that as a `font-family` on a styled component somewhere and the font isn't loading, at least not for me.

## Expected Behavior

Font-families should be loading correctly when added in styled components.

## Actual Behavior

Font family is not recognized and not even loaded down the wire according to the network tab.

**Comment by probablyup** [comment]
Looks ok to me

![Screen Shot 2020-01-02 at 1 01 31 PM](https://user-images.githubusercontent.com/570070/71683249-03acfb80-2d60-11ea-99d3-f352a52c88c4.png)
