### ISSUE TITLE
parent component styles overriding all children styles

### ISSUE THREAD

**Issue by kyazdani42** [styled-components/styled-components#2729]
### System:
 - OS: Linux 5.2 Manjaro Linux
 - CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
 - Memory: 10.66 GB / 15.44 GB
 - Container: Yes
 - Shell: 5.7.1 - /usr/bin/zsh
### Binaries:
 - Node: 11.15.0 - /usr/bin/node
 - Yarn: 1.17.3 - /usr/bin/yarn
 - npm: 6.10.3 - /usr/bin/npm
### npmPackages:
 - styled-components: ^4.3.2 => 4.3.2

## Reproduction
I have an issue with one project, since i switched from a multiple repos with parcel bundling my projects to a monorepo with webpack bundling projects depending on environment variables. \
Styled-components suddenly started generating all styles from the style of one component.
![Screenshot from 2019-08-30 18-45-25](https://user-images.githubusercontent.com/23156099/64038160-b02f6480-cb57-11e9-8362-7a45ff3c7d2e.png)
![Screenshot from 2019-08-30 18-45-49](https://user-images.githubusercontent.com/23156099/64038165-b4f41880-cb57-11e9-80f0-940199610ab6.png)
LoginWrapper: \
![Screenshot from 2019-08-30 18-46-43](https://user-images.githubusercontent.com/23156099/64038172-b7567280-cb57-11e9-9591-90918d88cce1.png)
LoginPaper: \
![Screenshot from 2019-08-30 18-46-55](https://user-images.githubusercontent.com/23156099/64038181-bb829000-cb57-11e9-8847-02024dd3c844.png)

and it goes like this until the end of the component tree. \
my webpack configuration: \
```javascript
const path = require('path');
const webpack = require('webpack');
const HtmlWebpackPlugin = require('html-webpack-plugin');
const { CleanWebpackPlugin } = require('clean-webpack-plugin');

module.exports = env => {
  const mode = env.ADMIN ? 'admin' : 'client';
  const port = env.ADMIN ? 5000 : 4000;
  return {
    mode: 'development',
    devtool: 'source-map',
    entry: {
      index: `./${mode}/index.tsx`
    },
    output: {
      path: path.resolve(__dirname, 'dist'),
      filename: '[name].[hash].js',
      publicPath: '/'
    },
    resolve: {
      extensions: ['.ts', '.tsx', '.json', '.js', '.jsx'],
      alias: {
        '~': __dirname
      }
    },
    devServer: {
      contentBase: './dist',
      hot: true,
      port
    },
    module: {
      rules: [
        {
          test: /\.ts(x?)$/,
          exclude: /node_modules/,
          use: { loader: 'swc-loader' }
        },
        {
          enforce: 'pre',
          test: /\.js$/,
          loader: 'source-map-loader'
        },
        {
          test: /\.(png|jpe?g|gif)$/,
          use: { loader: 'file-loader' }
        },
        {
          test: /\.css$/i,
          use: ['style-loader', 'css-loader']
        }
      ]
    },
    plugins: [
      new HtmlWebpackPlugin({ template: path.resolve(__dirname, `html/index.${mode}.html`) }),
      new webpack.HotModuleReplacementPlugin(),
      new CleanWebpackPlugin(),
      new webpack.DefinePlugin({
        'process.env': {}
      })
    ]
  };
};
```

## Expected Behavior
it should render the styles properly

**Comment by probablyup** [comment]
Dedupe your styled-components install

**Comment by kyazdani42** [comment]
ok, it appears swc-loader is the cause of this mess.

**Comment by kyazdani42** [comment]
works fine with ts-loader

**Comment by kyazdani42** [comment]
for those using swc-loader, you must target at least es2016 to fix this.
