### ISSUE TITLE
A cleaner way to access the props multiple times

### ISSUE THREAD

**Issue by k15a** [styled-components/styled-components#273]
I would like to suggest another syntax to access the props multiple times in a styled-component. It would look like this:

```JS
import styled from 'styled-components'

const Button = styled.button(props => `
  height: ${props.height};
  width: ${props.width};
  color: ${props.theme.fontColor};
  background-color: ${props.theme.backgroundColor};
`)
```

I would be happy to create a PR for this.

**Comment by carlosepp** [comment]
I've been working with styled components lately and found a very interesting pattern, I call them prop receivers for lacking of a better term, this syntax has proven to be very useful and highly reusable, essentially, what they do is inherit the prop values from the component calling such functions. A code sample would be better to describe how the pattern works:
```js
export const sizeProps = props =>`
  ${props.width && `width: ${props.width || '100%'}`};
  ${props.height && `height: ${props.height || '100%'}`};
  ${props.maxWidth && `max-width: ${props.maxWidth || '100%'}`};
  ${props.maxHeight && `max-height: ${props.maxHeight || '100%'}`};
`;
```
So essentially you get the syntax you propose as a composable function that can be reused in any component you want it to receive those props, helping you to keep your stylebase dry, you can then consume it in this way:
```js
const Button = styled.button(props => `
  ${props => sizeProps(props)}
`)
```
then you can nicely use your button component passing the sizeProps you want like so:

```js
<Button width="100%" maxWidth="300px" />
```

I'd be very interested in knowing what you think about this.

**Comment by carlosepp** [comment]
I'd be very interested in knowing what you think about this. do you see any performance implications with this approach? cc @mxstbr

**Comment by mxstbr** [comment]
Thanks for kicking off this discussion @k15a! We certainly though about doing this, the reason we didn't go this way is that it doesn't work.

You need to use a _tagged_ template literals, just template literals don't work. By using tagged ones, we can get access to the interpolations and evaluate them – otherwise JavaScript just `toStrings` them. This makes it possible for us to add object (and function, though that'd be redundant) support. (see [my recent blog post](mxstbr.blog/2016/11/styled-components-magic-explained) explaining how tagged template literals work)

What you would need to do to make this work is _always_ use the `css` helper like so to make it a tagged template literal again:

```JS
import styled, { css } from 'styled-components'

const Button = styled.button(props => css`
  height: ${props.height};
  width: ${props.width};
  color: ${props.theme.fontColor};
  background-color: ${props.theme.backgroundColor};
`)
```

But at that point you lose so much of the ergonomics again that we decided against it, instead going with the function syntax.

**Comment by k15a** [comment]
@mxstbr Thanks for the explanation. I didn't know that you support objects in interpolations otherwise I would have known that you can't support that.

**Comment by k15a** [comment]
That doesn't look as beautiful and I think linting is not supported but it should work^^
```JS
const Text = styled.div`${props => `
  height: ${props.height};
  width: ${props.width};
  color: ${props.theme.fontColor};
  background-color: ${props.theme.backgroundColor};
`}`
```

**Comment by mxstbr** [comment]
Add the `css` helper to get syntax highlighting and linting:

```
const Text = styled.div`${props => css`
  height: ${props.height};
  width: ${props.width};
  color: ${props.theme.fontColor};
  background-color: ${props.theme.backgroundColor};
`}`
```

**Comment by geelen** [comment]
Actually @carlosepp got really close to a nice pattern for smart reusable chunks, it's just a bit simpler than he realised:

```js
export const sizeProps = props => css`
  ${props.width && `width: ${props.width}`};
  ${props.height && `height: ${props.height}`};
  ${props.maxWidth && `max-width: ${props.maxWidth}`};
  ${props.maxHeight && `max-height: ${props.maxHeight}`};
`;
```
```js
import { sizeProps } from './utils'

const Button = styled.button`
  ${sizeProps}
`
```

Simple!

**Comment by carlosepp** [comment]
I really like it @geelen did not see that the props were already exposed 🙊will try it out tomorrow. Seems good for inheriting props.
