### ISSUE TITLE
passing props to styled component gives error, yet seems to work anyway

### ISSUE THREAD

**Issue by Tycholiz** [styled-components/styled-components#2731]
I'm trying to pass down a prop to a styled component, then use that prop to render the color. Here is my code: 
```
const ColoredText = styled.span`
  font-family: 'Gloria Hallelujah', cursive;
  color: ${props => props.color};
`

const HomePage = () => {
  return (
    <>
      <ColoredText color={palette('secondary', 1)}>Travel</ColoredText>
      <ColoredText color={palette('tertiary', 1)}>Your</ColoredText>
      <ColoredText color={palette('primary', 1)}>Way</ColoredText>
    </>
}
```
The error I'm getting is this: 
`Invalid value for prop color on <span> tag. Either remove it from the element, or pass a string or number value to keep it in the DOM`

not sure why this is happening, doesn't seem to happen in other areas of my application where I follow this pattern.

**Comment by probablyup** [comment]
It's because "color" is a real HTML attribute. Use a camelCased (e.g. `textColor`) property name so the attributes are not passed down to the DOM. https://www.styled-components.com/docs/faqs#why-am-i-getting-html-attribute-warnings
