### ISSUE TITLE
styled-components didnot work with React@16.9.0

### ISSUE THREAD

**Issue by Zwe1** [styled-components/styled-components#2733]
Today, I update my React version from 16.7.0 to 16.9.0 for using hooks. Then I found some error occurs in my SPA. It seems the problem with React when used in styled-components, and I guess the react version did not match styled-components, then I update the styled-components version, but it did not work at all, please help me.
![image](https://user-images.githubusercontent.com/22523201/64319089-23b8f200-cfee-11e9-881a-72ccf8d49644.png)
![image](https://user-images.githubusercontent.com/22523201/64319111-329fa480-cfee-11e9-9aaf-2c8c4965572d.png)

## Environment
development
## System:
 - OS: macOS High Sierra 10.13.6
 - CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
 - Memory: 92.86 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 10.16.0 - /usr/local/bin/node
 - Yarn: 1.7.0 - /usr/local/bin/yarn
 - npm: 6.9.0 - /usr/local/bin/npm
## npmPackages:
 - react:  ^16.9.0,
 - babel-plugin-styled-components: ^1.10.6 => 1.10.6
 - styled-components: ^4.3.2 => 4.3.2

## Reproduction
1. update react from 16.7.0 -> 16.9.0
2. update react-dom from 16.7.0 -> 16.9.0

then error happens

**Comment by probablyup** [comment]
Make sure you upgrade `react-is` as well!
