### ISSUE TITLE
How to control inline 'style' property dynamically with 'attrs' function in jsx ?

### ISSUE THREAD

**Issue by jasonOramo** [styled-components/styled-components#2734]
I try to do some small testing when learning styled-component which is a div element follow the mouse position. Basically all the things are OK except the div position, Since the position is always changing and I try to use the 'attrs' function to change the position style dynamically. 
I haven't found a way to implement it. Here is the sampe code:

	const MouseDom = styled.div.attrs((props)=>({
		name: 'mouseDiv',
		style: (props)=>({left: props.mouse.x + 'px', top: props.mouse.y + 'px'})
	}))`
		position: absolute;
		background-color: black;
		border: 5px solid;
	`;

Error shows as followed:
The `style` prop expects a mapping from style properties to values, not a string. For example, style={{marginRight: spacing + 'em'}} when using JSX.
    in div (created by Context.Consumer)
    in StyledComponent (created by styled.div)

And I try the style part directly without the function, it works. 

	const MouseDom = styled.div.attrs((props)=>({
		name: 'mouseDiv',
		style: {left:'10px'}
	}))`
		position: absolute;
		background-color: black;
		border: 5px solid;
	`;

How to control the inline style dynamically ?

**Comment by jasonOramo** [comment]
directly using styled is not recommended because of the performance issue.

**Comment by probablyup** [comment]
@jasonOramo the second-level attrs function syntax isn't supported anymore, you'll want to do this:

```js
const MouseDom = styled.div.attrs(p => ({
  name: 'mouseDiv',
  style: {
     left: p.mouse.x + 'px',
     top: p.mouse.y + 'px',
  },
}))`
	position: absolute;
	background-color: black;
	border: 5px solid;
`;
```
