### ISSUE TITLE
Global styles lost on Gatsby routing with v5

### ISSUE THREAD

**Issue by robinmetral** [styled-components/styled-components#2739]
On routing with Gatsby, global styles created with `createGlobalStyle` are lost.

I can confirm that this is a v5 error. To reproduce, simply route between pages on the demos:
- [v5 demo with :bug:](https://gatsby-globalstyle-routing.netlify.com/)
- [v4 demo without :bug:](https://5d7346a2093ee6000a1d56d6--gatsby-globalstyle-routing.netlify.com/)

_Note that this might be linked to #2670 (particularly to some comments), but in my case I have a single `createGlobalStyle` declaration and I'm using Gatsby, so I thought I'd open a new issue :slightly_smiling_face:_ 

## Environment
**System:**
 - OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
 - CPU: (4) x64 Intel(R) Core(TM) i5-4260U CPU @ 1.40GHz
 - Memory: 1.04 GB / 7.73 GB
 - Container: Yes
 - Shell: 4.4.20 - /bin/bash

**Binaries:**
 - Node: 12.9.0 - ~/.nvm/versions/node/v12.9.0/bin/node
 - Yarn: 1.17.3 - /usr/bin/yarn
 - npm: 6.10.2 - ~/.nvm/versions/node/v12.9.0/bin/npm

**npmPackages:**
 - babel-plugin-styled-components: ^1.10.6 => 1.10.6 
 - styled-components: ^5.0.0-beta.8 => 5.0.0-beta.8-groupsizefix 

## Reproduction

**:bug: Reproduce the bug (with v5)**
- Repo: https://github.com/robinmetral/gatsby-globalstyle-routing
- Demo: https://gatsby-globalstyle-routing.netlify.com/

**:nail_care: Reproduce the expected behavior (with v4)**
- Repo: https://github.com/robinmetral/gatsby-globalstyle-routing/tree/with-v4
- Demo: https://5d7346a2093ee6000a1d56d6--gatsby-globalstyle-routing.netlify.com/

## Steps to reproduce

- visit the v5 demo
- navigate from the index to the second page

**Reproduce locally:**
- clone the repo
- `yarn`
- `yarn develop`
- http://localhost:8000

## Expected Behavior

The background should still be `forestgreen` (declared in global styles).

## Actual Behavior

The background is white because global styles are lost.

**Comment by SolderHQ** [comment]
I noticed the same behavior with `styled-components 5.0.0-beta.8` and downgraded to `4.3.2` to make sure global styles persist after navigating to another page.

**Comment by sbrichardson** [comment]
I added notes to https://github.com/styled-components/styled-components/issues/2670#issuecomment-532399875 if you wanted to test this solution.

**Comment by probablyup** [comment]
Want to send a PR? :)

**Comment by sbrichardson** [comment]
I reviewed further, it seems that any time there is a re-render, this code below is the offender.
While adding in the React.memo improves performance, and fixes some cases, the v5 example above (https://github.com/robinmetral/gatsby-globalstyle-routing) will re-render on every route (un-optimally) since it's lower down in a functional component. 

Disabling [this line](https://github.com/styled-components/styled-components/blob/v5.0.0-beta.8/packages/styled-components/src/constructors/createGlobalStyle.js#L64) in `createGlobalStyle.js`

```js
if (window.scCGSHMRCache[styledComponentId] === 0) {
  // globalStyle.removeStyles(styleSheet);
}
```

So it seems there are 3 separate issues (in v5 beta8): 

1. Any time a GlobalStyleComponent re-renders, it will take down the global stylesheet.
2. If there are any vendor prefixed styles in the global style, any css below them won't be processed in a production react build.
3. The createGlobalStyle could be optimized by wrapping the returned GlobalStyleComponent in React.memo.

**Comment by sbrichardson** [comment]
It looks like it may just be a logic issue. 2 potential solutions I could think of:

1. In useEffect, only decrement the scCGSHMRCache counter if it is > 1
2. Also in the render function, only call 
     `globalStyle.renderStyles(STATIC_EXECUTION_CONTEXT, styleSheet)`
    when necessary, a naive check could be scCGSHMRCache < 1.

Doing this below resolves for this repo, and prevents expensive call to renderStyles. It may need other work though, and the non-static (context/theme) logic needs to be updated. 

```js
if (globalStyle.isStatic) {
  if (!window.scCGSHMRCache[styledComponentId]) {

    window.scCGSHMRCache[styledComponentId] = 
      (window.scCGSHMRCache[styledComponentId] || 0) + 1

    globalStyle.renderStyles(STATIC_EXECUTION_CONTEXT, styleSheet);
  }
}


useEffect(function () {
  if (IS_BROWSER) {
    return function () {
      if (window.scCGSHMRCache[styledComponentId] > 1) {
        window.scCGSHMRCache[styledComponentId] -= 1;
      }

      if (window.scCGSHMRCache[styledComponentId] === 0) {
        globalStyle.removeStyles(styleSheet);
      }
    };
  }
  return undefined;
}, []);
```

**Comment by probablyup** [comment]
@robinmetral can you try `styled-components@test`? We're working on fixing some issues with cGS now for v5 prior to release.

**Comment by robinmetral** [comment]
@probablyup will try this tonight 🙂 Thank you for looking into this!

**Comment by robinmetral** [comment]
@probablyup It seems to works! At least this fixed my [demo](https://gatsby-globalstyle-routing.netlify.com/) of the error. As you can see the background color is persisted on routing :tada:

**Comment by robinmetral** [comment]
Feel free to close the issue when the fix is merged :slightly_smiling_face:

**Comment by robinmetral** [comment]
@probablyup so can I get the fix in `styled-components@beta`? :smiley:

**Comment by probablyup** [comment]
I have a couple other pending PRs but we’ll cut another beta this week!

**Comment by robinmetral** [comment]
Great! Let me know when it's released, can't wait to get back to using the beta :blush: 

Thanks for your work on v5! :rocket:

**Comment by peduarte** [comment]
Same here, thanks for raising this @robinmetral 👍

**Comment by hayyaun** [comment]
In my case, `gatsby-plugin-minify` was making this problem, which led the production build to reload all styles after a page was loaded completely in the production build.
