### ISSUE TITLE
Not sure it always makes sense to create a new component for small styling changes

### ISSUE THREAD

**Issue by adjnor** [styled-components/styled-components#274]
I find this library great for creating components like buttons, input fields, etc. that look a particular way and which may or may not be customized via passed props / theme. 

However, I find myself needing to keep creating new components in order to add small styling like margins or padding in specific cases. When creating those new components, it doesn't really make sense to me to think about reuse because if all I want is to style one particular component in one specific place using a bit of margin e.g. `margin-bottom: 10px;`, then creating a new component that I'm probably never going to reuse seems a bit overkill. 

Here is a simple use case to better explain myself:
-I have one Button component which I have styled with styled-components
-I have a Card component. In my Card, there are multiple Button components, and one of them needs to have a bit of margin, however in terms of the look of the Button I don't want to change anything. I am forced to create a new Button component with styled-components for this particular Button where I need the margin to add one line of styling `margin-bottom: 10px;`. 

Is that the styled-components way or am I just doing it wrong?
Thanks!

**Comment by k15a** [comment]
How about using a prop called margin and using .defaultProps?

**Comment by adjnor** [comment]
@k15a Yes I did think about doing so, I'm just wary of making components that aren't actually meant to be used as is and which instead act as building blocks that need to be customized (as I add more and more prop-based styling). That doesn't sound bad actually but just not sure if that's a good way to go
