### ISSUE TITLE
Styled-components with Next.js results in a brief flash of no styled

### ISSUE THREAD

**Issue by haydennyyy** [styled-components/styled-components#2741]
## System:
 - OS: macOS 10.14.5
 - CPU: (4) x64 Intel(R) Core(TM) i5-4310U CPU @ 2.00GHz
 - Memory: 681.24 MB / 8.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
 - Yarn: 1.17.3 - ~/.yarn/bin/yarn
 - npm: 6.10.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.10.6 => 1.10.6 
 - styled-components: ^4.3.2 => 4.3.2 

## Reproduction
https://playroles.now.sh/

## Steps to reproduce
Just go to the page.

## Expected Behavior
The styles will load directly in for the whole site.

## Actual Behavior
There is a brief flash of time where the site loads without any styling, before loading them in afterwards.

## Notes
I'm using Next.js for this, and it uses SSR (obviously) but I also have the Babel plugin so I'm not sure how to fix this.

**Comment by davidexns** [comment]
Have you extended Next's Document component by creating an override `_document.js` file, as seen here? https://github.com/zeit/next.js/blob/canary/examples/with-styled-components/pages/_document.js

**Comment by probablyup** [comment]
What @davidexns said :) ideally copy this setup: https://github.com/zeit/next.js/tree/canary/examples/with-styled-components
