### ISSUE TITLE
Can generated classNames be used for analytics? 

### ISSUE THREAD

**Issue by remi2j** [styled-components/styled-components#2742]
Hi,

We're setting up an analytics the analytics for our app. The tool we're using needs HTML classes of certain elements (buttons, links etc.) to track the events on the page.

Can we use the classNames that were generated by styled-components? Or do they get regenerated after each CSS change?

**Comment by probablyup** [comment]
Highly recommend not to do this as we optimize for smallest output and don't guarantee human-readable names.

If you need to identify a particular type of element the best practice is to use data attributes for labeling... e.g. `data-type="checkout button"`
