### ISSUE TITLE
Global styles created with createGlobalStyle are lost in CRA

### ISSUE THREAD

**Issue by mukeshmandiwal** [styled-components/styled-components#2744]
Using with create-react-app, global styles created with createGlobalStyle are lost in build(production).

## npmPackages
`npx create-react-app` 
 `styled-components@5.0.0-beta.8`

## Reproduction

https://quirky-ptolemy-25fb93.netlify.com
https://github.com/mukeshmandiwal/globalstyle

## Expected Behavior
The background should be gray in build production (declared in global styles).
## Actual Behavior
The background is white because global styles are lost.

**Comment by sbrichardson** [comment]
I also ran into this issue, currently debugging.

It only happens on the production build for me also.

**Comment by sbrichardson** [comment]
Added more details in https://github.com/styled-components/styled-components/issues/2670#issuecomment-532399875

**Comment by sbrichardson** [comment]
Added more details in https://github.com/styled-components/styled-components/issues/2670#issuecomment-532025112 if you wanted to test.

**Comment by probablyup** [comment]
Looking into this, seems like there are a variety of issues with cGS in the v5 beta due to rerendering...

**Comment by mukeshmandiwal** [comment]
Working fine in development mode. but the issue in production build

**Comment by floric** [comment]
I get the same bug when hydrating for SSR. I might have some time to search for the reason.

**Comment by probablyup** [comment]
This should be fixed in the later betas!
