### ISSUE TITLE
There is no way to have stylis plugins applied globally

### ISSUE THREAD

**Issue by wintercounter** [styled-components/styled-components#2746]
From the docs it seems like I would need to wrap every styled-component to have a stylis plugin run through it.

We have our UI-kit implmented with styled-components. It wasn't a plan before, however the request arrised to support IE11, but we're using CSS variables. I wanted to write a stylis plugin so I can replace `var` declarations to a specific value, but I cannot find a way to apply the plugin globally.

Am I missing somthing or it's indeed impossible to have a globally applied plugin?

UPDATE:
Seems like if I wrap a styled component in StyleSheetManager I'll get the same error:

https://codesandbox.io/s/styled-components-dv43z

I guess I'm doing something wrong but this kind a copy paste of the documentation of `s-c` and `stylis`.

**Comment by probablyup** [comment]
This is a new v5 feature! Please try out the beta and feel free to leave feedback :)
