### ISSUE TITLE
Typescript - React component props lost after wrapping with styled() when props contains indexer

### ISSUE THREAD

**Issue by donotcodeit** [styled-components/styled-components#2747]
I don't have a time to create a pull request with an issue, but I can provide an easy way to reproduce. Example may be created with Create React App. I'm using VS Code.

## System:
 - OS: Windows 10
 - CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
 - Memory: 7.52 GB / 15.94 GB
## Binaries:
 - Node: 8.16.1 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.17.3 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
 - npm: 6.10.3 - C:\Program Files\nodejs\npm.CMD

### Related dependencies from package.json
```
"@types/react": "^16.8.25"
"@types/styled-components": "^4.1.19"
"react": "^16.8.6"
"styled-components": "^4.3.2"
"typescript": "^3.5.3"
```

### Example.tsx code
```
import React from "react";
import styled from "styled-components";

interface IProps {
	[key: string]: string;
	foo: string;
}

const Component = (p: IProps) =>
	<div>{p.foo}</div>;

const StyledComponent = styled(Component)``;

export const Example = () =>
	<React.Fragment>
		<Component foo="test" />
		<StyledComponent foo="test" />
	</React.Fragment>;
```

`Component` contains props as expected. I can, for example, navigate to definition of `foo`.
But it does not work with `StyledComponent`.

**Comment by probablyup** [comment]
Sorry but we don't maintain any TS integration stuff in this repo, you'll want to open an issue over at DefinitelyTyped.
