### ISSUE TITLE
Styled components macro on non CRA project

### ISSUE THREAD

**Issue by TDMarko** [styled-components/styled-components#2748]
## System:
 - OS: macOS 10.14.6
 - CPU: (4) x64 Intel(R) Core(TM) i7-7567U CPU @ 3.50GHz
 - Memory: 3.37 GB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 10.15.3 - /usr/local/bin/node
 - Yarn: 1.15.2 - /usr/local/bin/yarn
 - npm: 6.10.2 - /usr/local/bin/npm
## npmPackages:
 - styled-components: ^4.3.2 => 4.3.2 

## Reproduction

1) New project with following dependencies:
`    "dependencies": {
        "@types/html-webpack-plugin": "^3.2.1",
        "@types/react": "^16.9.2",
        "@types/react-dom": "^16.9.0",
        "@types/styled-components": "^4.1.19",
        "@types/webpack": "^4.39.1",
        "awesome-typescript-loader": "^5.2.1",
        "babel-plugin-macros": "^2.6.1",
        "react": "^16.9.0",
        "react-dom": "^16.9.0",
        "styled-components": "^4.3.2",
        "ts-node": "^8.3.0",
        "tslint-react": "^4.0.0"
    },
    "devDependencies": {
        "@babel/core": "^7.5.5",
        "@babel/preset-env": "^7.5.5",
        "@babel/preset-react": "^7.0.0",
        "babel-loader": "^8.0.6",
        "html-webpack-plugin": "^3.2.0",
        "tslint": "^5.20.0",
        "typescript": "^3.6.3",
        "webpack": "^4.39.3",
        "webpack-cli": "^3.3.8",
        "webpack-dev-server": "^3.8.0"
    }`
2) index.tsx file with:
`import React from "react";
import ReactDOM from "react-dom";
import styled from "styled-components/macro";

const StyledTitle = styled.div`
    font-size: 1.5em;
    text-align: center;
    color: palevioletred;
`;

const App: React.FC = () => {
    return (
        <React.Fragment>
            <StyledTitle>Hello, I'm React with a Typescript ;)</StyledTitle>
        </React.Fragment>
    );
};

ReactDOM.render(<App />, document.getElementById("root"));

`
3) Running project with:
`webpack-dev-server --port 3000 --open --config webpack.config.ts`

## Expected Behavior
Class names have component names when inspecting an element

## Actual Behavior
Javascript error:
`Uncaught TypeError: macro_1.default.div is not a function
    at eval (index.tsx:13)
    at Object../src/index.tsx (main.js:5416)
    at __webpack_require__ (main.js:20)
    at eval (webpack:///multi_(:3000/webpack)-dev-server/client?:2:18)
    at Object.0 (main.js:5427)
    at __webpack_require__ (main.js:20)
    at main.js:84
    at main.js:87`

**Comment by probablyup** [comment]
Using the macro requires having the babel macros toolchain set up as it does replacements behind the scenes: https://github.com/kentcdodds/babel-plugin-macros
