### ISSUE TITLE
Transform Children Attribute

### ISSUE THREAD

**Issue by Undistraction** [styled-components/styled-components#2749]
How about adding a 'transformChildren' attribute to styled components' `attrs` object?

This would be a function that received the component's `children` prop as an argument.

Example:

I have a function called `preventWidows` which adds a nbsp between the last two words of a sentence. I have a series of Title components that are styled components. At the moment I have to do:

```javascript
<PageTitle>{preventOrphans(title)}</title>
```

With `transformChildren`:

```javascript
const PageTitle = styled.h1.attrs({transform children: preventOrphans})``

<PageTitle>{title}</PageTitle>
```

The only other option is to mess around with HOCs, but this seems unnecessarily verbose:

```javascript
import React from 'react'
import PropTypes from 'prop-types'
import styled from 'styled-components'
import { preventWidows } from '../../../utils'

const PreventWidowsHoc = WrappedComponent => {
  const Wrapper = ({ children, ...rest }) => (
    <WrappedComponent {...rest}>{preventWidows(children)}</WrappedComponent>
  )

  Wrapper.propTypes = {
    children: PropTypes.node.isRequired,
  }

  return styled(Wrapper)``
}

export default PreventWidowsHoc

```

**Comment by probablyup** [comment]
We won't add something like this but we are pushing out a bugfix soon such that you can modify children via `.attrs` (in the current latest release attrs is not correctly overriding props.)

**Comment by Undistraction** [comment]
@probablyup Thanks. Is the previous release (4.3.1) bug-free as far as that behaviour goes?

**Comment by Undistraction** [comment]
Looks like this has never worked with `children`.

**Comment by probablyup** [comment]
Please re-read my message. The bug fix isn’t out yet.

**Comment by Undistraction** [comment]
@probablyup Sorry. I read it as 'It was working, but in the current release attrs is not correctly overriding props', so I thought I might be able to find a working release if I rolled back.

**Comment by Undistraction** [comment]
@probablyup 2.4.0 works perfectly. Thank you.
