### ISSUE TITLE
Remove null css properties

### ISSUE THREAD

**Issue by adjnor** [styled-components/styled-components#275]
As I customize my components, I find myself wanting to only modify some css properties if a particular prop is being passed. Example:

```
const MyButton = styled(StyledButton)`
  background-color: ${(props) => (props.primary ? 'blue' : null)};
`;
```

In this example, the problem I have is that I am extending the StyledButton component which already has a background-color attribute defined, and I only want to override the background-color if the primary prop has been passed. The code I wrote above works, but the problem is that useless css is being injected, e.g. `background-color: ;` if the primary prop is not passed.

One way to avoid this would be to write something like: 
`${(props) => (props.primary && 'background-color: blue')};`

However, it makes the code look inconsistent and I also lose the linting. Would there be a way for styled-components to automatically remove styling attributes with null or empty values?

**Comment by mxstbr** [comment]
> Would there be a way for styled-components to automatically remove styling attributes with null or empty values?

Not really as long as PostCSS doesn't do that. What's so harmful about injecting an empty rule?

**Comment by justinpincar** [comment]
I run into this all the time when trying to layer styles. I end up having to just duplicate the base styles in the wrapper class, which really sucks. Is there a better way to approach this?

**Comment by philpl** [comment]
@justinpincar there are a couple of helpers that abstract this away quite nicely. I recommend you to go through those. You can also write the entire declaration into an interpolation instead to avoid it being overridden with an empty value.

Btw please go to Spectrum, Gitter, or open a new issue, instead of commenting on a really old one, as it's easier for us to track the "demand" of a specific feature this way :smile:

**Comment by justinpincar** [comment]
I'll check out the helpers, thanks for pointing me in that direction.

BTW - I didn't see a Gitter or Spectrum link anywhere, so had no idea you do support through there.

**Comment by philpl** [comment]
@justinpincar We added a link to Spectrum to the readme recently :wink: Check it out: https://spectrum.chat/styled-components
