### ISSUE TITLE
how can i decide whether or not to load SC at run time ?

### ISSUE THREAD

**Issue by gilm123** [styled-components/styled-components#2750]
we are using SC for several years now, and it's awesome.
we recently started work on an SDK, basically, 1 js file you are adding to your HTML to render react components to the screen. we are using SC of course.

when I ship this JS file I cannot assume specific dependencies exist. that leads to bundling everything we need including SC.
to give a bit more context, this JS file should work on any website, even html file without any dependencies, Angular websites, etc. We are completely decoupled from our hosts.

one of my clients is using SC too, and we are experiencing weird behaviors loading these two to the same page.
**I read quite a few posts/issues of how to avoid it**
includes this one 
https://www.styled-components.com/docs/faqs#i-am-a-library-author-should-i-bundle-styledcomponents-with-my-library
but couldn't find any similar to my case.

we had the exact same issue with babel-polyfill, a good solution we found here https://www.npmjs.com/package/idempotent-babel-polyfill
before loading it, at runtime, there is a check whether or not babel-polyfill was already loaded. if yes, it skips loading it again. saying that, we enforced the hosting website to use that version of the polyfill too.

as far as I see, my options are:

1. to do the same as idempotent-babel-polyfill, assuming there is sort kind of SC global which I can check that has already beed loaded. not even sure how to start releasing such thing myself.

2. on each release, i'll bundle 2 versions, 
one - for websites **without** SC (means my JS will bundle SC), 
second - for websites **with** SC, a bundle of mine without SC bundled. which makes my SDK loading a bit complicated, I have to wait for the website to be loaded before evaluating my SDK, and assume it has SC on all of it's pages.

3. in theory, I could extract SC to a separate bundle, but i want to release one single bundle to my client. so this option isn't really an option imo.

i'd appreciate more opinions on the above.

**Comment by probablyup** [comment]
@gilm123 I suppose you could detect if `styled-components` is present on the page by looking for `window.styled` and async load the script if it isn't... I'm not sure how you'd pause script execution though without wrapping your React bootstrapping in a thenable.
