### ISSUE TITLE
not friendly to react native Components?

### ISSUE THREAD

**Issue by hlipeter** [styled-components/styled-components#2752]
I Found it's not friendly to RN View 、Text...  For example:
```
import styled from "styled-components/native"; 
// import styled from "styled-components";

...

const Thing = styled.View`
  color: blue;
  .something {
    border: 1px solid;
    display: block;
    color:red;
  }`

render(
  <Thing>
    <Text htmlFor="foo-button" className="something">Mystery button</Text>
    <Text id="foo-button">What do I do?</Text>
  </Thing>
)
```

and the color attribute is not work to the View、Text tag, also , className something not work too,
Another example，::before 、 && .etc not work either！but only support basic grammar.

by the way，my code has no error!  just useless .

Is that any solution ？show me please.

Thanks!

**Comment by probablyup** [comment]
I think part of the confusion here is RN doesn't allow for selector cascade; all styles are effectively inline due to how RN works. Stuff like className doesn't do anything in RN, you need to pass styling props and adapt to them via interpolations.

**Comment by hlipeter** [comment]
I see, Thanks a lot.
