### ISSUE TITLE
In React native, an error occurs if there is no px in margin.

### ISSUE THREAD

**Issue by bugtype** [styled-components/styled-components#2755]
## Environment

```
## System:
 - OS: macOS 10.14.6
 - CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
 - Memory: 631.96 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 10.15.3 - /usr/local/bin/node
 - Yarn: 1.15.2 - /usr/local/bin/yarn
 - npm: 6.9.0 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: ^1.10.6 => 1.10.6 
 - styled-components: ^4.3.2 => 4.3.2 
```

## Reproduction

https://www.webpackbin.com/bins/-KeeZCr0xKfutOfOujxN
https://codesandbox.io/s/rkmNRByE4

Could not find module in path: 'styled-components' relative to '/Wrapper.js' ...

### This is an error.

```
import styled from 'styled-components/native';

const Section = styled.View`
  margin: 16;
  margin-top: 8;
  margin-bottom: 8;
`;
```

### This is not an error.

```
const Section = styled.View`
  margin: 16px;
  margin-top: 8;
  margin-bottom: 8;
`;
```

## Expected Behavior

I think it should work without the px in margin props.

## Actual Behavior

error
```
Error: Failed to parse declaration "margin: 16"

This error is located at:
    in StyledNativeComponent (created by Styled(View))
    in Styled(View) (at HaulerServiceItem.tsx:27)
    in RCTView (at View.js:45)
    in View (at TouchableHighlight.js:397)
  ...
```

**Comment by probablyup** [comment]
Needs the units. This is css

**Comment by bugtype** [comment]
Oh, I see. Thank you.
But… The margin-top and margin-bottom works normally without the unit.
When there is no unit, shouldn't there be an error?

**Comment by ScreamZ** [comment]
I'm experiencing the same issue. using margin-top and others, styled-component is passing through its internal checks. but it seems like margin: 16; it is going through the normal pipeline

**Comment by probablyup** [comment]
@bugtype I think this is a bug in css-to-react-native... I would consider opening an issue there. styled-components itself does not manipulate the CSS you provide
