### ISSUE TITLE
Duplicate class hash names [5.0.0-beta.8]

### ISSUE THREAD

**Issue by alex-nishikawa** [styled-components/styled-components#2756]
## System:
 - OS: macOS 10.14.6
 - CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
 - Memory: 1.03 GB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 10.15.3 - /usr/local/bin/node
 - Yarn: 1.16.0 - /usr/local/bin/yarn
 - npm: 6.9.2 - /usr/local/bin/npm
## npmPackages:
 - styled-components: 5.0.0-beta.8 => 5.0.0-beta.8 

## Expected Behavior
There should be no duplicate class hash names regardless of casing
## Actual Behavior

<img width="308" alt="Screen Shot 2019-09-18 at 8 20 33 PM" src="https://user-images.githubusercontent.com/3360238/65211914-263b3300-da55-11e9-9117-f2a4885cbdd9.png">

**Comment by alex-nishikawa** [comment]
Using 'babel-plugin-styled-components' to get around this.

**Comment by probablyup** [comment]
CSS class names are actually case sensitive per the spec :)

**Comment by alex-nishikawa** [comment]
@probablyup

Just to confirm:  Chrome is out of spec?  Because Chrome is not respecting class name casing.

**Comment by alex-nishikawa** [comment]
@probablyup
@katekourbatova

SOLVED:  The browser was in quirk mode due to missing DOCTYPE
