### ISSUE TITLE
styled-component/macro imports are undefined in test.js files

### ISSUE THREAD

**Issue by joemaffei** [styled-components/styled-components#2757]
## System:
 - OS: Windows 10
 - CPU: (8) x64 Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz
 - Memory: 6.97 GB / 15.85 GB
## Binaries:
 - Node: 12.2.0 - C:\Program Files\nodejs\node.EXE
 - npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

styled-components^4.3.2
create-react-app@3.1.2

## Reproduction
I tried creating a codesandbox for this issue, but got a different error there.
```
import { css } from 'styled-components/macro';

test('css from styled-components/macro should not err out', () => {
    expect(css).not.toBeUndefined();
});
```
This test fails because css is undefined.

I noticed this because a deep child of one of the components I was trying to test uses `css` from styled-components/macro, and Jest throws an error saying `TypeError: (0 , _macro.css) is not a function`

## Steps to reproduce
In a create-react-app project, create the simple test above and run it in isolation.

## Expected Behavior
The test should pass, because `css` should be a function.

## Actual Behavior
The test fails, because `css` is undefined.

**Comment by probablyup** [comment]
@joemaffei do you know if the macros babel plugin is set up in jest for CRA? That import should be getting transpiled to `import { css } from 'styled-components';` by babel...

**Comment by joemaffei** [comment]
@probablyup Aha, that seems to be the problem. babel-plugin-macros is not set up in CRA:
- https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/config/jest/babelTransform.js
- https://github.com/facebook/create-react-app/blob/05f7924398d175429825c4b680d18e6c253435a9/packages/react-scripts/config/webpack.config.js#L419

I'll send them a feature request and possibly make a PR for it. In the meantime, I'm stuck with overriding their default settings using [craco](https://github.com/sharegate/craco) or some other tool.
