### ISSUE TITLE
Prop style utilities

### ISSUE THREAD

**Issue by spen** [styled-components/styled-components#276]
I've been writing a couple of util functions while playing around with styled-components in my latest project and thought I'd share here, hopefully to get some thoughts from the community.
I'm planning to put together a gist or a pen once these are polished a little more so I'll update when/if that happens but for now, here goes:

```js
const propValue = ( prop, defaultValue ) => props => {
    return props[ prop ] != null ? props[ prop ] : defaultValue;
}

const optionalRule = ( rule, prop ) => props => {
    const style = propValue( prop, null )( props );

    return ( rule && style !== null ) ? `${ rule }: ${ style };` : '';
}
```
### usage
```js
const someStyles = css`
    backgroundColor: ${ propValue( 'bgColor', 'tomato' ) } ;
    ${ optionalRule( 'color', 'textColor' ) }
`;
```

I might be barking up the wrong tree with this and I have just seen @k15a 's Issue #273 which might be a nicer solution but depending on feedback I'd love to open a PR to make these utils available to all :D

**Comment by mxstbr** [comment]
Nice, these could be helpful in `polished`! Would you mind starting off a discussion there? https://github.com/styled-components/polished
