### ISSUE TITLE
Export problem. Cannot create styled-component for component: undefined

### ISSUE THREAD

**Issue by ReTWi** [styled-components/styled-components#2762]
When importing svg component and trying to style it, i've got error:
```
Uncaught Error: Cannot create styled-component for component: undefined.
    at new StyledComponentsError (styled-components.browser.esm.js:232)
    at constructWithOptions (styled-components.browser.esm.js:1367)
    at styled (styled-components.browser.esm.js:2259)
    at eval (Loading.js:13)
    at Module../src/components/Loading.js (app.js:1075)
    at __webpack_require__ (app.js:20)
    at eval (index.js:3)
    at Module../index.js (app.js:991)
    at __webpack_require__ (app.js:20)
    at eval (Main.js:5)
```

Few months ago there was no problem.

## System:
 - OS: Windows 10
 - CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
 - Memory: 8.12 GB / 15.89 GB
## Binaries:
 - Node: 12.10.0 - C:\Program Files\nodejs\node.EXE
 - npm: 6.10.1 - C:\Program Files\nodejs\npm.CMD

## Works
```
const SvgCircle = forwardRef((props, ref) => {
  return (
    <svg viewBox='0 0 120 120' version='1.1' xmlns='http://www.w3.org/2000/svg'>
      <circle cx='60' cy='60' r='50' />
    </svg>
  )
})

const Loading = () => {
  return <SvgCircle />
}

const StyledSvgCircle = styled(SvgCircle)``
```
 
## Not working
```
// external file, frontend allias
export const SvgCircle = forwardRef((props, ref) => {
  return (
    <svg viewBox='0 0 120 120' version='1.1' xmlns='http://www.w3.org/2000/svg'>
      <circle cx='60' cy='60' r='50' />
    </svg>
  )
})
```

```
import { SvgCircle } from 'frontend'

const Loading = () => {
  return <SvgCircle />
}

const StyledSvgCircle = styled(SvgCircle)`` // without styled components imported icon shows fine
```

package.json:
"@babel/core": "^7.6.0",
    "@babel/plugin-transform-runtime": "^7.6.0",
    "@babel/preset-env": "^7.6.0",
    "@babel/preset-react": "^7.0.0",
    "@tippy.js/react": "^2.2.3",
    "babel-loader": "^8.0.6",
    "babel-plugin-styled-components": "^1.10.6",
    "css-loader": "^3.2.0",
    "dompurify": "^2.0.1",
    "esm": "^3.2.25",
    "fastify": "^2.8.0",
    "fastify-cookie": "^3.1.0",
    "fastify-rate-limit": "^2.3.0",
    "fastify-static": "^2.5.0",
    "marked": "^0.7.0",
    "module-alias": "^2.2.1",
    "moment": "^2.24.0",
    "node-cron": "^2.0.3",
    "node-fetch": "^2.6.0",
    "pg": "^7.12.1",
    "pino": "^5.13.3",
    "pino-pretty": "^3.2.1",
    "pm2": "^3.5.1",
    "react": "^16.9.0",
    "react-datepicker": "^2.9.6",
    "react-dom": "^16.9.0",
    "react-router": "^5.0.1",
    "react-router-dom": "^5.0.1",
    "style-loader": "^1.0.0",
    "styled-components": "^4.3.2",
    "tippy.js": "^4.3.5",
    "use-debounce": "^3.0.1",
    "webpack": "^4.40.2",
    "webpack-bundle-analyzer": "^3.5.1",
    "webpack-cli": "^3.3.9"

**Comment by probablyup** [comment]
It’s definitely not on our end

**Comment by ReTWi** [comment]
Hm, will try to ask on webpack then, thx.

**Comment by testacode** [comment]
Hi @ZiiMakc can you share your webpack issue??

**Comment by ZiiMakc** [comment]
@testcode sorry, i don't remember how it was solved

**Comment by kitten** [comment]
It was likely a circular import.
Also please don't revive old issues; if you're searching for some, I believe I've left comments about circular imports a couple of times. Basically the easiest way to get into trouble is to import from an index file that also imports/exports all siblings and the component itself since this will create an import loop after two components import each other via that index file.
