### ISSUE TITLE
Base is being overwritten by as prop and no longer extending

### ISSUE THREAD

**Issue by JDansercoer** [styled-components/styled-components#2763]
Not entirely sure if this is actually a bug, or more a choice by design, but wanted to get your opinion on this usecase.

Using the `styled(Component)` syntax, you extend another (styled) component. And with the `as` prop, you influence the element that is eventually renderend. However, I noticed that when using these two in combination, the base component is no longer used and is completely overwritten by the `as` prop. I even tried the `forwardedAs` prop, but I might not be using how it was meant to be used..

## Reproduction

https://codesandbox.io/embed/sharp-edison-4sexm

## Steps to reproduce

Have a component that extends another component and pass in an `as` prop as well.

## Expected Behavior

Have a combination of the extended component and the generated tag.

## Actual Behavior

Only the generated tag is changed, but the styling from the extended component is no longer applied.

**Comment by probablyup** [comment]
This is only the case with customer components wrapped with styled(). When
you wrap another styled component we know everything about it and are able
to “fold” the tree so there isn’t an extra component layer that does
nothing.

When you wrap a non-styled component we have no knowledge of its
implementation and “as” swaps it out with the desired other component or
JSX primitive.

**Comment by etienne-martin** [comment]
I'm having the exact same issue. @JDansercoer Did you find a solution?
