### ISSUE TITLE
Theme warning in 4.4.0

### ISSUE THREAD

**Issue by alexandernanberg** [styled-components/styled-components#2766]
## Environment
styled-components v4.4.0

## Reproduction

https://codesandbox.io/s/holy-pond-951mv?fontsize=14

## Steps to reproduce

Go to the sandbox and check the console output

## Expected Behavior

No console warning. I think this is a valid use-case and I don't really see the reason why we have to log a warning. Our codebases imploded with these warnings after upgrading. 

## Actual Behavior

A warning is logged

**Comment by probablyup** [comment]
This will be removed in 4.4.1
