### ISSUE TITLE
ThemeProvider causes all styled-components to re-render even if not used

### ISSUE THREAD

**Issue by iDVB** [styled-components/styled-components#2767]
ThemeProvider causes all styled-components to re-render even if context is not used in it? 
This seems odd? 

If we just setup our own ContextProvider and handle it manually than ONLY the components that we pass the prop into require a re-render.

Is this true/intended?

**Comment by probablyup** [comment]
@iDVB I wouldn't say it's intended, but we also tend to not memoize too aggressively in case there's a mix of the old and new context system in use (old context doesn't update as eagerly as it should in some implementations.) I did make a change to TP for the v5 beta that will ship with the next release which should help a bit though.
