### ISSUE TITLE
StyleSheetManager with disableVendorPrefixes in jest

### ISSUE THREAD

**Issue by blukai** [styled-components/styled-components#2768]
## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`

## System:
 - OS: macOS Mojave 10.14.6
 - CPU: (8) x64 Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz
 - Memory: 1.02 GB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
 - Yarn: 1.17.3 - ~/.nvm/versions/node/v12.10.0/bin/yarn
 - npm: 6.10.3 - ~/.nvm/versions/node/v12.10.0/bin/npm
## npmPackages:
 - styled-components: ^5.0.0-beta.9 => 5.0.0-beta.9

## Reproduction

https://github.com/blukai/styled-components.StyleSheetManager

## Steps to reproduce
create a styled componnet
```js
const Flower = styled.div`
  display: flex;
`;
```
create a TestRenderer instance with `StyleSheetManager` with `disableVendorPrefixes` prop
```js
const tree = render.create(
  <StyleSheetManager disableVendorPrefixes>
    <Flower />
  </StyleSheetManager>
).toJSON();
```
let the jest to generate snapshot
```js
expect(tree).toMatchSnapshot();
```

## Expected Behavior
I expected to get snapshot of element and it's styles without vendor prefixes.
Something like this
```
.c0 {
  display: flex;
}

<div
  className="c0"
/>
```
## Actual Behavior
I got a snapshot without styles at all.
```
<div
  className="sc-AykKC htpBwX"
/>
```

## Story
In attempt to upgrade to styled-components 5 beta I faced an issue:
when I use `StyleSheetManager` with `disableVendorPrefixes` prop and try to generate snapshot - all the styles are being completely removed from existing snapshots.
note that `StyleSheetManager` without `disableVendorPrefixes` prop doesn't remove styles and work just fine.

So, I went to styled-components repo in attempt to find the cause.
The root of evil is [here](https://github.com/styled-components/styled-components/blob/canary/packages/styled-components/src/models/StyleSheetManager.js#L66)
I tried to provide options that are responsible for disabling vendor prefixes to `masterSheet` without providing `disableVendorPrefixes` to `StyleSheetManager`, and it worked fine.
So when the sheet gets reconstructed `reconstructWithOptions` something is getting broken.

**Comment by taikn** [comment]
Using `disableVendorPrefixes` with SSR seem to return empty stylesheets for me as well.

**Comment by probablyup** [comment]
@taikn that should be fixed with the latest RC

**Comment by probablyup** [comment]
@blukai can you try with the latest RC? Made some stylesheet internal changes that should resolve the issue. Thanks!

**Comment by probablyup** [comment]
Checked against your repro and this is fixed with the latest rc and also latest beta of jest-styled-components
