### ISSUE TITLE
Feature Request: Replacing styles that are injected by injectGlobal

### ISSUE THREAD

**Issue by dotcarls** [styled-components/styled-components#277]
I've read the docs and see that even using injectGlobal in the first place is not recommended, however my use-case requires it for `styled-components` to be truly viable. 

One of the requirements of the product I'm working on is to be able to brand the entire app, which includes things like font-faces and the like. I've already implemented the ThemeProvider, however we have many stylesheets for our currently implemented brands and we are constantly receiving new stylesheets as development continues, so it would be impractical to process them all. 

As such, I would like to do the following:

```javascript
export class BrandingProvider extends React.PureComponent { 
  getChildContext() {
    return { branding: this.props.brandings[this.props.brand] };
  }
  render() {
    injectGlobal`${this.props.brandings[this.props.brand].globalStyle}`;

    return (
      <ThemeProvider theme={this.props.brandings[this.props.brand]} key={this.props.brand}>
        {React.Children.only(this.props.children)}
      </ThemeProvider>
    );
  }
}
```

In this scenario, `injectGlobal` uses a template string that is passed in through the props. It actually kind of works, somewhat, but as I toggle back and forth between the brandings the styles just get appended to the same `<style></style>` block. It would be nice to be able to replace this style block rather than append it, either via this function or a separate one like `replaceGlobal`. 

Would this be a trivial thing to implement, or is there a deeper reason why styles must be appended that I'm missing?

Thank you!

**Comment by k15a** [comment]
IIRC correctly styled-components never removes styles.

**Comment by dotcarls** [comment]
It seems to 'lazy load' styles in normal circumstances by appending them to the stylesheet block when components are rendered for the first time, using a hash of the contents of the style properties for the classname so that it can appropriately select the element. This is fine for most cases, especially when component styles aren't dynamic. This is what allows `ThemeProvider` to work -- when an element is rerendered with a different style value, its class name will be different due to the new hash. 

My issue is that when using `injectGlobal`, it can't and shouldn't be scoped by a class name which means that any styles passed to it just get appended to the style block over and over again, effectively only allowing for one change should the different stylesheets share elements. It would be nice if there were perhaps two style blocks, one for regular components and one that is only used by `injectGlobal`.  Whenever `injectGlobal` is called, clear out the dedicated style block and voila you're in business.

**Comment by mxstbr** [comment]
Interesting for sure, I don't remember why we did it this way. Is this a glamor thing or a styled-components thing @threepointone @geelen?

**Comment by threepointone** [comment]
No one really deletes global rules, so this didn't become a requirement until single page apps + CSS in js became a thing. I had a similar question in glamor, and I have a possible solution with a  jquery inspired hack https://github.com/threepointone/glamor/issues/102#issuecomment-260587051

**Comment by dotcarls** [comment]
Thanks for the input, that comment on glamor looks very much like what I'm trying to do! 😀 

I'm working on a very large application, so something I'm currently considering is the case where a user has navigated deep within the app, generating many, many unique styles / selectors, then the theme is switched and they continue navigating, theme is switched again, rinse and repeat. Because we are looking to support over 20+ brandings, this would ultimately result in a huge stylesheet with tons of unused selectors.

I was reading [this report on CSS selector performance](https://benfrain.com/css-performance-revisited-selectors-bloat-expensive-styles/) and found this interesting:

(The test put a large number of unused selectors above the one that is being used)

> This provides some interesting figures. For example, Firefox was 1.7X slower to complete this test than it was with its slowest selector test (test 6). Android 4.3 was 1.2X slower than its slowest selector test (test 6). Internet Explorer was a whopping 2.5X slower than it’s slowest selector!

> You can see that things dropped down considerably for Firefox when half of the styles were removed (approx 1500 lines). The Android device came down to around the speed of its slowest selector at that point too.

So I was wondering, would it make sense to remove selectors when `componentWillUnmount`? Or perhaps if you're using `ThemeProvider`, you could clear out all styles when `componentWillReceiveProps` or `componentWillUpdate`? 

I'm pretty new to this stuff so please forgive me if these are dumb questions!

**Comment by pencilcheck** [comment]
Just wondering if there is a replacement for this feature?

**Comment by pencilcheck** [comment]
I know this has a lot of big dependencies but I hope this will serve as a useful reference/solution for this issue...

```
import React from 'react'
import hoistNonReactStatic from 'hoist-non-react-statics'
import { injectGlobal } from 'styled-components'
import postcss from 'postcss'
import postcssJs from 'postcss-js'
import { css as c, select as $ } from 'glamor'

export default (...styles) => Component => {
  class Enhanced extends React.Component {
    classNames = []

    _createStyled = css => {
      let root = postcss.parse(css)
      let style = postcssJs.objectify(root)
      // Assuming the css imported are from normal css files which means
      // no rules that are not contained within a class
      return c.apply(this,
        Object.keys(style).map(key => $(`& ${key}`, style[key])))
    }

    componentWillMount = () => {
      if (process.browser) {
        this.classNames = styles.map(this._createStyled)
        this.classNames.forEach(className => document.body.classList.add(className))
      }
    }

    componentWillUnmount = () => {
      if (process.browser) {
        this.classNames.forEach(className => document.body.classList.remove(className))
      }
    }

    render() {
      return <Component ref="component" {...this.props} />
    }
  }

  hoistNonReactStatic(Enhanced, Component)
  return Enhanced
}
```

**Comment by aganglada** [comment]
I will say **theming** is one of the solutions you can use.

Is your issue solved @dotcarls? If so, what was your final one/can we close this one?

**Comment by probablyup** [comment]
> So I was wondering, would it make sense to remove selectors when `componentWillUnmount`

In the case of styled-components, this wouldn't be a good idea. We'd basically have to implement a reference counting scheme, since there could be multiple instances of the same component on a page or many other components composing the one that was unmounted.

It's not impossible, but I think it's out of scope. One thing you could do is a `querySelector` for `[data-styled-components-is-local="false"]`, which are the globally-injected styles and then remove them as needed.

**Comment by PopeOnARope** [comment]
I have a similar use case, but I need be able to add and delete @import statements on the fly. Is there a built in way to do this? We are using insertRule with success, but we need to be able to delete rules as well to avoid having a bunch of duplicates.

Thanks!

**Comment by mxstbr** [comment]
Ref #1514 and #1416

**Comment by probablyup** [comment]
This will be handled by the upcoming [`createGlobalStyle` API](https://github.com/styled-components/styled-components/issues/1333) in v4 https://github.com/styled-components/styled-components/issues/1694
