### ISSUE TITLE
Ways to avoid generating too many classes

### ISSUE THREAD

**Issue by cheuksing** [styled-components/styled-components#2772]
Sometimes I need to insert props to have a custom style for a widely used components. A very common usage is an **Container component** with **width**. Especially when it has **multiple** dynamic props. While the specific props may not be constantly changing within one single component, they may have **more than 20 of them in one page**, resulting generating too many classes.

It maybe related to issue #134 , but I don't think we should use inline styles across each **xxxContainer Components** in this case.

example situation 1:

```
  const Utils = styled.div`
    ${width}
    ${margins}
    ${paddings}
 `
 const xxxContainer = styled(Utils)`
  // blablabla
`
```
**OR**

example situation 2:

```
  const utils = styled.css`
    ${width}
    ${margins}
    ${paddings}
 `
 const xxxContainer = styled.div`
  ${utils}
  // blablabla
`
```
I think a simple solution can be allow user to compose 2 separate classes into one?
e.g.

```
  const utisRules = styled.setOfRules`
   // many many dynamic rules
 `

 const AnyComponents = styled.div`
    // many many dynamic rules
 `

  // So AnyComponents.className = 'utils-class any-component-class'
```

**Comment by mxstbr** [comment]
I am not sure what you are asking. The option you suggest is exactly the same as the second option, except it doesn't support dynamic styles. 🤔 I don't think we'll introduce an API like that.
