### ISSUE TITLE
New notation: styled.div(Component)`...`

### ISSUE THREAD

**Issue by lcswillems** [styled-components/styled-components#2773]
# Feature request

## Issue

I often want to style a component I made. So I always start writing this:

```
const StyledComponent = styled(Component)`
  ...
`
```

and I realize it will not work because I don't give the `className` to a specific element in my component. So I go to my component, wrap everything that is rendered in a `div` and then give the class name to this `div`.

There are 2 issues by doing this:

1. It is painful to do it every time.
2. The design of the `Component` now depends on what wraps it, and I am not fan of this.

## A solution

I would be so nice if I could write something like:

```
const StyledComponent = styled.div(Component)`
  ...
`
```

and that it automatically wraps my `Component` into a `div` and give to this `div` the good class name.

Thank you so much for this great library!
Kind regards,
Lucas Willems

**Comment by mxstbr** [comment]
> The design of the Component now depends on what wraps it, and I am not fan of this.

I disagree with this statement. Passing on a `className` is something you would do whether you use styled-components to adjust the styles of the component or not. (`styled(Component)` vs. `<Component className="bla" />`) There is nothing styled-components specific about that!

I think adding another wrapping layer would introduce more problems, as at that point it will mess with the layout if you're using Flexbox or grid. Passing through the classname is a much more general solution that'll work for all use cases, so I doubt we're going to introduce it.

I hope that makes sense!

**Comment by lcswillems** [comment]
I don't understand why you closed this so fast, so fast that you are not even sure that you well understand what I propose...

> I disagree with this statement. Passing on a `className` is something you would do whether you use styled-components to adjust the styles of the component or not. (`styled(Component)` vs. `<Component className="bla" />`) There is nothing styled-components specific about that!

I have not said it is specific to styled-components... This is not what I said. I just said that my component now depends on the fact that its parent wants to style it.

> I think adding another wrapping layer would introduce more problems, as at that point it will mess with the layout if you're using Flexbox or grid. Passing through the classname is a much more general solution that'll work for all use cases, so I doubt we're going to introduce it.

What I propose is not a replacement for `styled(Component)`, it is an addition!!

People who want to wrap their `Component` inside a `div` for styling could do `styled.div(Component)`.

**Comment by mxstbr** [comment]
> I just said that my component now depends on the fact that its parent wants to style it. I don't like this idea.

But... you want to style the component from the parent 🤔 That is literally exactly what you want to do. If your component should allow that, it should pass the `className`. If it shouldn't, then it shouldn't?

I am not sure what you're trying to say.

**Comment by lcswillems** [comment]
I want to style my component `Component` without having to modify my `Component`.

Currently, if I want to style `Component`, I need to modify it, i.e. to add a `className` property and to add it to one of its children.

With the solution I propose, there is no need for this.

Does it make sense?

**Comment by lcswillems** [comment]
@mxstbr Does it make sense?

**Comment by joeytwiddle** [comment]
Would there be any way to pass the className down to the child, without us having to write it explicitly?

For example, at the moment, this component won't be styled because we forgot to add `className` to the props and use it in the `<button>`:

```js
const MyButton = styled(
  ({ text, onClick }) => <button onClick={onClick}>{text}</button>
)`
  background: magenta;
`;
```

I suspect this is styled-components biggest gotcha.

Would it be possible for `styled()` to magically pass `className` into the `<button>` so that we don't have to do it ourselves?

Is it impossible? Or would it be considered a hack which hides the true flow of data, and confuses consumers?
