### ISSUE TITLE
new RTL Plugin stylisRTLPlugin not working with padding/margin  Shorthand Property

### ISSUE THREAD

**Issue by Adidi** [styled-components/styled-components#2777]
#  Environment

## System:
 - OS: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
 - CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
 - Memory: 1.05 GB / 15.41 GB
 - Container: Yes
 - Shell: 5.4.2 - /bin/zsh
## Binaries:
 - Node: 12.10.0 - /usr/bin/node
 - Yarn: 1.19.0 - /usr/bin/yarn
 - npm: 6.10.3 - /usr/bin/npm

## Reproduction

https://codesandbox.io/s/styled-components-1yzo2

## Expected Behavior
should convert `<Title />  padding: 0 10px 0 300px;` to ` padding: 0 300px 0 10px;`
You can see it in the tests of stylis-rtl repo:
https://github.com/FindHotel/stylis-rtl/blob/master/src/stylis-rtl.test.js

## Actual Behavior
Not working if you set `padding` or `margin` Shorthand Property `top right bottom left`

**Comment by probablyup** [comment]
This should be working with rc3 and the new stylis-plugin-rtl (note the change of package name.) https://codesandbox.io/s/styled-components-hebjp
