### ISSUE TITLE
new RTL Plugin stylisRTLPlugin not working with /* @noflip */ comment

### ISSUE THREAD

**Issue by Adidi** [styled-components/styled-components#2778]
## System:
 - OS: Linux 5.0 Ubuntu 18.04.3 LTS (Bionic Beaver)
 - CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
 - Memory: 417.05 MB / 15.41 GB
 - Container: Yes
 - Shell: 5.4.2 - /bin/zsh
## Binaries:
 - Node: 12.10.0 - /usr/bin/node
 - Yarn: 1.19.0 - /usr/bin/yarn
 - npm: 6.10.3 - /usr/bin/npm

## Reproduction
https://codesandbox.io/s/styled-components-gwm9x

## Expected Behavior
if `/* @noflip */` remark is above rule this rule should not flip to rtl mode
You can see it in the tests of stylis-rtl repo:
https://github.com/FindHotel/stylis-rtl/blob/master/src/stylis-rtl.test.js

## Actual Behavior
its not working with the `/* @noflip */` comment and it this example it should stay `margin-right: 40px;` and not `margin-left: 40px;`

**Comment by Adidi** [comment]
Maybe styled component strip the comments cause it think its regular css comment...

**Comment by ROUDALI** [comment]
i'm sorry, this is an off topic, but usin StyleSheetManager on the SSR does not produce a FOUC for you?

**Comment by probablyup** [comment]
I think this is a bug in the plugin itself... I wrote a quick failing test to debug and it does appear we're passing the CSS into stylis correctly.

The plugin tests don't use `stylis` directly, so perhaps there's an integration issue?

**Comment by probablyup** [comment]
This should be working now with rc3 + the new `stylis-plugin-rtl` (note that the package name has changed)

**Comment by Lpaydat** [comment]
Excuse me, noob here, nstylisRTLPlugin not working with `styled-components/native`, right?
