### ISSUE TITLE
Feature Request: Share ThemeProvider with JSS

### ISSUE THREAD

**Issue by tracker1** [styled-components/styled-components#2779]
Just thought it would be a cool idea, if possible to share the [ThemeProvider](https://www.npmjs.com/package/theming) that JSS uses.  In this way, someone wanting to use the same theme for JSS and styled-components (such as with material-ui) would be able to do so more easily.

**Comment by probablyup** [comment]
Interesting idea, but probably not something we will pursue for a few reasons:

1. The library is kind of big for what it is ([2.2 kB gzipped](https://bundlephobia.com/result?p=theming@3.2.0))
2. It gives up control of how we use theming, which is not ideal
3. We would need to use it as a direct dependency not a peer dependency to follow our current strategy of one-import-for-all, which in an interop scenario means you could have many versions of this package in your tree bloating your bundles
