### ISSUE TITLE
Bug with calc()

### ISSUE THREAD

**Issue by santaclauze** [styled-components/styled-components#278]
## Version
1.0.10

## Reproduction
http://www.webpackbin.com/4ymSgAOzM

## Steps to reproduce
Use `calc()` in a Styled Component, then check css output

## Expected Behavior

css output = 
```
.card-img-top {      
    border-top-right-radius: calc(.25rem - 1px);
    border-top-right-radius:-webkit-calc(.25rem - 1px);
    border-top-right-radius:-moz-calc(.25rem - 1px);
    border-top-left-radius: calc(.25rem - 1px);
    border-top-left-radius:-webkit-calc(.25rem - 1px);
    border-top-left-radius:-moz-calc(.25rem - 1px);
}
```

## Actual Behavior

```
.card-img-top {      
    border-top-right-radius: calc(.25rem - 1px);
    borderTopRightRadius:-webkit-calc(.25rem - 1px);
    borderTopRightRadius:-moz-calc(.25rem - 1px);
    border-top-left-radius: calc(.25rem - 1px);
    borderTopLeftRadius:-webkit-calc(.25rem - 1px);
    borderTopLeftRadius:-moz-calc(.25rem - 1px);
}
```

As you can see, css output gives us a cameledCase rule when a browser vendor is present. That is only when the function `calc()` is used in a Styled Component.

I tried injecting the `calc()` function in `injectGlobal` and it gave me the right css output (not cameledCase)

**Comment by mxstbr** [comment]
@jacobp100 is this related to your workarounds?

**Comment by jacobp100** [comment]
Not related to my workarounds. I think it might be [here](https://github.com/styled-components/styled-components/blob/master/src/utils/autoprefix.js#L14)

**Comment by mxstbr** [comment]
But we do this later on? https://github.com/styled-components/styled-components/blob/0f5262ee1cea306f027e66973fc77b01e8df81de/src/utils/autoprefix.js#L21

**Comment by jacobp100** [comment]
Actually, also looking, it’s 1.0.10. Could we check whether it’s occurring on the current version?

**Comment by santaclauze** [comment]
After upgrading to the newest version, it seems to be working ;).
