### ISSUE TITLE
Update css-to-react-native

### ISSUE THREAD

**Issue by jacobp100** [styled-components/styled-components#2782]
Just an issue to note that there is a new major version of css-to-react-native, and it would be good to include this in the next major of styled components

The updates for this are,

* Fixed issue with percentage flex basis in `flex` shorthand
* Will now warn when omitting units on properties that require them (`top`, `width` etc.)
* Removed support for unitless line height in `font` shorthand

**Comment by probablyup** [comment]
Sounds good, thanks @jacobp100! Want to send a PR and annotate those changes in a changelog entry?

**Comment by jacobp100** [comment]
Sorry, I totally meant to do this. Just added myself a reminder for when I get back from work

**Comment by thexpand** [comment]
@jacobp100 Did you have the chance to do this?

**Comment by jacobp100** [comment]
I commented in the other thread - I wasn't able to install the dependencies via `yarn` when I cloned the repo. I tried on Windows and MacOS, and both failed on a native code dependency

If someone is able to do this, it would help a lot!

**Comment by omBratteng** [comment]
@jacobp100 see PR #2811

**Comment by jacobp100** [comment]
Thanks 😄

**Comment by probablyup** [comment]
@jacobp100 can you guys ship a changelog please?

**Comment by jacobp100** [comment]
I've done a github release [here](https://github.com/styled-components/css-to-react-native/releases/tag/v3.0.0)

**Comment by probablyup** [comment]
Thanks @jacobp100

**Comment by probablyup** [comment]
Will ship in rc0 👍
