### ISSUE TITLE
v5 styled components 2x slower than using classes

### ISSUE THREAD

**Issue by funwithtriangles** [styled-components/styled-components#2785]
## Sandbox
https://codesandbox.io/s/sc-v5-perf-tests-umi0l

## Reproduction (production mode)
https://csb-umi0l-7lck1lfj3.now.sh/ (classes, 300 boxes)
https://csb-umi0l-purcx3xdj.now.sh/ (styled components, 300 boxes)

## Steps to reproduce
- Start recording in Chrome profiler
- Click "show boxes"
- Stop recording
- Compare times of mounting in both examples

## Expected Behavior
Mounting the components shouldn't be much slower

## Actual Behavior
Styled components is 2x slower than using classes

Is this the sort of expected benchmarks we should be seeing? I understand if that's the case. I love the styled components API and was wondering if there is any way I can export static class names for certain components? My app is very performance focused as it uses WebGL visuals with music, so I'm trying my best to avoid frame drops.

**Comment by rahul3103** [comment]
Profiling not supported.
Profiling support requires either a development or production-profiling build of React v16.5+.
