### ISSUE TITLE
Styled-components theme maxWidth props not working

### ISSUE THREAD

**Issue by rshah9** [styled-components/styled-components#2786]
## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`

## Reproduction

https://www.webpackbin.com/bins/-KeeZCr0xKfutOfOujxN
https://codesandbox.io/s/rkmNRByE4

**Comment by lekterable** [comment]
Hey, @rshah9 you're not making it easier by not posting a reproduction, I tried something like this and it totally works:
https://codesandbox.io/s/styled-components-v0xrj
Let me know if that's what you had in mind.

**Comment by probablyup** [comment]
Going to close due to lack of repro, thanks for helping with the example @lekterable
