### ISSUE TITLE
V5 Unreported Style Mismatch

### ISSUE THREAD

**Issue by rtymchyk** [styled-components/styled-components#2790]
## Environment
```
## System:
 - OS: macOS High Sierra 10.13.4
 - CPU: (4) x64 Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
 - Memory: 82.61 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
 - Yarn: 1.6.0 - /usr/local/bin/yarn
 - npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
 - Watchman: 4.7.0 - /usr/local/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: ^1.10.6 => 1.10.6
 - styled-components: ^5.0.0-beta.9 => 5.0.0-beta.9
```

## Reproduction
I am using this component:
```javascript
export const Container = styled.button`
  border: 3px solid;
  border-image-source: linear-gradient(315deg, green, red);
  border-image-slice: 1;
`
```

Server SSR:
```javascript
const sheet = new ServerStyleSheet()
const reactTree = (
  <StyleSheetManager sheet={sheet.instance}>
    <Router location={req.url} />
  </StyleSheetManager>
)

const html = ReactDOMServer.renderToString(reactTree)
const css = sheet.getStyleTags()
const { js } = flushChunks(clientStats, { chunkNames: flushChunkNames() })

res.status(200)
res.render('base', { html, css, js })
```

Client Hydration:
```javascript
const client = getApolloClient()
const store = createStore(...)

function render(renderFunction, Router) {
  const reactRoot = document.getElementById('react-root')

  renderFunction(
    <ApolloProvider client={client}>
      <ActionCableProvider>
        <AppContainer>
          <ReduxProvider store={store}>
            <Router />
          </ReduxProvider>
        </AppContainer>
      </ActionCableProvider>
    </ApolloProvider>,
    reactRoot
  )
}

render(hydrate, Router)
```

.babelrc (environment doesn't really matter here)

```json
"development": {
      "plugins": [
        "react-hot-loader/babel",
        [
          "styled-components",
          {
            "minify": false,
            "ssr": true,
            "displayName": true
          }
        ]
      ]
    },
```

## Steps to reproduce
Render only with SSR by disabling JavaScript. Then enable JavaScript so hydration can kick in.

## Expected Behavior
Identical CSS for the component rendered. 

## Actual Behavior
**From server:**
![Screen Shot 2019-10-07 at 2 46 38 PM](https://user-images.githubusercontent.com/3498278/66340084-77329e80-e912-11e9-9372-ffc23ceaabce.png)

**After hydration kicks in:**
![Screen Shot 2019-10-07 at 2 47 06 PM](https://user-images.githubusercontent.com/3498278/66340082-77329e80-e912-11e9-813e-b367030c63ab.png)

There is no checksum mismatch.

**Comment by rtymchyk** [comment]
Just realized, the button renders in a disabled state. That seems to trip this bug.

**Comment by topaxi** [comment]
Do you render differently based on whether you are on the server or client? If so, you might need to do this depending on state and not a global variable. This would trigger a tiny rerender on the client though, but should keep styles/attributes in sync.

React, as far as I know, leaves attributes unchanged on rehydration.

**Comment by rtymchyk** [comment]
@topaxi I believe the rerender is triggered by redux/form logic being mounted and that toggles the button to the disabled state. I guess this makes the issue of why does the styling disappear with the disabled state and not so much a mismatch.

**Comment by probablyup** [comment]
Going to close since it appears this is a SSR rehydration mismatch outside our control

**Comment by rtymchyk** [comment]
@probablyup OK so I dug a bit deeper into this and have a reproduction in sandbox: https://codesandbox.io/s/example-server-side-rendering-fsq6v

Please take a look and let me know what you think. The disabled state being different between client/server was a red herring. The CSS is just different between server and client.

**Comment by rtymchyk** [comment]
@probablyup Is it better for me to open up a new issue given the reproduction?
