### ISSUE TITLE
v5 keyframe animations in production mode not working in IE11

### ISSUE THREAD

**Issue by vsangk** [styled-components/styled-components#2791]
I'm currently using `styled-components: ^5.0.0-beta.9` in a project and I'm seeing that keyframe animations aren't working in IE11 when using webpack to bundle the code in production mode. This is reproducible on physical machines and emulators such as Browserstack. The keyframe animations do work in IE11 if webpack is bundled in development mode. Also if downgrading back to styled-components v4 it works as well. 

Any help is much appreciated and the full details are below.

### System:
 - OS: macOS Mojave 10.14.6
 - CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
 - Memory: 88.37 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
### Binaries:
 - Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
 - Yarn: 1.12.3 - ~/.yarn/bin/yarn
 - npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
### npmPackages:
 - styled-components: ^5.0.0-beta.9 => 5.0.0-beta.8-groupsizefix

## Reproduction

If you open https://vsangk.github.io/sc-ie-animation/ in IE11 you'll notice that the text `Hi` is not rotating but if opening in Chrome or Safari it does rotate.

index.jsx
```
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import styled, { keyframes } from 'styled-components';

const rotate = keyframes`
  from {
    transform: rotate(0deg);
  }

  to {
    transform: rotate(360deg);
  }
`;

const RotatingDiv = styled.div`
  font-size: 36px;
  display: inline-block;
  animation: ${rotate} 2s linear infinite;
`;

const Hello = () => <RotatingDiv>Hi</RotatingDiv>;

ReactDOM.render(<Hello />, document.getElementById('app'));
```

webpack.config.js
```
module.exports = {
  mode: 'production',
  entry: './index.jsx',
  output: {
    filename: 'bundle.js',
  },
  resolve: {
    extensions: ['.js', '.jsx'],
  },
  module: {
    rules: [
      { test: /\.(js|jsx)$/, exclude: /node_modules/, loader: 'babel-loader' },
    ],
  },
};
```

babel.config.js
```
const presets = ['@babel/env', '@babel/preset-react'];

module.exports = { presets };
```

Full source code can be found at https://github.com/vsangk/sc-ie-animation.

## Steps to reproduce
* Add any animations with keyframes using `keyframes` exported by `styled-components`
* Bundle the project using webpack production mode
* View page in IE11

To run locally with the source code from the GitHub repo
* Clone repo
* `npm install`
* `npm run build` if any changes are made to `index.jsx`
* `npx http-server dist` to serve the files
  * Or use any other http server and serve the `dist` folder
* View page in IE11 

## Expected Behavior
Animations should work with production bundled code in IE11

## Actual Behavior
Animations do not work with production bundled code in IE11

**Comment by probablyup** [comment]
@kitten debugged this and looks like we're getting back an `IndexSizeError` during `insertRule`

**Comment by probablyup** [comment]
Maybe for this if insertion fails we need to just straight-up drop the rule from the set and decrement the index as if it never happened:

https://github.com/styled-components/styled-components/blob/canary/packages/styled-components/src/sheet/GroupedTag.js#L51-L55

**Comment by kitten** [comment]
@probablyup Was just about to say just that; I forgot to decrement the index there, when the insertion fails. Maybe it's better just to rewrite this as a `while` loop so it doesn't confuse us again https://github.com/styled-components/styled-components/blob/canary/packages/styled-components/src/sheet/GroupedTag.js#L52-L54

**Comment by humblehumans** [comment]
Running into the same issue, downgrading to v4.4.0 seems to solve the issue but has its drawbacks. Any chance this fix is going to be pushed anytime soon (and or can I implement on my end ) @kitten @probablyup ? Thank you for all you do to support this project, sincere respect.

**Comment by probablyup** [comment]
I'm trying to do a beta release for @kitten's fix but my computer is being annoying. Hopefully will get something out later today

**Comment by probablyup** [comment]
@vsangk this should be working with beta 11
