### ISSUE TITLE
StyleSheetManager on the SSR ( FOUC )

### ISSUE THREAD

**Issue by ROUDALI** [styled-components/styled-components#2794]
Hi everyone , i'm using StyleSheetManager in a Next.js project in order to call stylisRTLPlugin
example :  (i'm using styled_components in componentStepper )
![image](https://user-images.githubusercontent.com/29419489/66406243-3c4c6b80-e9e3-11e9-9123-ede0851d08d9.png)

the problem is when i load the page in first ms it shows the page without style , then the style is loaded.
Anyone one please know how can i solve this problem , Thank's :)

**Comment by probablyup** [comment]
Hey there, unfortunately without a reproduction sandbox of some kind it's pretty hard to help. Feel free to reopen if you can provide one.

**Comment by ROUDALI** [comment]
@probablyup thank's for your response 
example : https://codesandbox.io/s/hello-world-1urec here 
got https://1urec.sse.codesandbox.io/about and start refreshing the page (FOUC)
