### ISSUE TITLE
:before content doesn't escape /a as breakline

### ISSUE THREAD

**Issue by eldyvoon** [styled-components/styled-components#2795]
I can't escape ```content``` value with ```\a```

This 
```
const Title = styled.div`
  &:before {
    content: "Hello \a World"; /*not working*/
    white-space: pre-wrap;
  }
`;
```

is not equivalent to 

```
.title2:before {
  content: "Hello \a World";
  white-space: pre-wrap;
}
```
Demo: https://codesandbox.io/s/styled-components-njovq

**Comment by probablyup** [comment]
@eldyvoon I think this is mostly a consequence of using javascript template literals. If you add a second escape it works as expected. Not sure there's anything we can do in the library to handle this since it's a general language behavior.

**Comment by eldyvoon** [comment]
wow nice catch there, double escape does worked! anyway, thanks!
