### ISSUE TITLE
ReactNative compatibility

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components#28]
This might be the killer feature. Making it possible to reuse CSS across platforms would be epic!

**Comment by geelen** [comment]
What might that look like? ``styled(x)`y:z;` `` for some x y and z

**Comment by mxstbr** [comment]
Same API, except with `ReactNative` primitives?

```JS
styled.View`
border: 1px solid red;
`;
```

**Comment by geelen** [comment]
From discussion, the idea is to provide the same API at two endpoints

```js
import styled, { css, ... } from 'styled-components'
import styled, { css, ... } from 'styled-components/native'
```

The difference is that the DOM one supports nesting, media queries etc, and generates `className`. The native one doesn't and generates a `styles` object. We could even not call it the 'native' endpoint but 'inline' instead, since that's all it's doing...

**Comment by geelen** [comment]
Just thinking about this, if we are going to supply `styled.View` (as apposed to only allowing `styled(View)` that means our project is going to depend on `react-native` just so we can match up our imported symbols. Is there any way around that, or is that not too much of a problem?

**Comment by mxstbr** [comment]
> Is there any way around that, or is that not too much of a problem?

Why not make it a `peerDep`?

Also, I've been thinking about this – we could not only have `/native`, but also `/choo`, `/glimmer`, even `/dom`. What if we returned a _representation_ of a generic component from `styled` calls, and then we could (or collaborators could contribute) more adapters for this thing?

**Comment by geelen** [comment]
Yeah right that's what peerDeps are for, right? I just thought they would complain if they were unfulfilled, so every time you `npm i` you get a warning that you're missing `react-native`?

**Comment by mxstbr** [comment]
> I just thought they would complain if they were unfulfilled, so every time you npm i you get a warning that you're missing react-native?

Ah yeah crap, good point. Probably `optionalDependency` then!

**Comment by geelen** [comment]
Closing in favour of #53
