### ISSUE TITLE
Importing into tag (SSR) failing to import URL from webpack

### ISSUE THREAD

**Issue by gear4s** [styled-components/styled-components#2800]
# Environment

## System:
 - OS: Windows 10
 - CPU: (4) x64 Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz
 - Memory: 674.73 MB / 3.78 GB
## Binaries:
 - Node: 10.16.0 - ~\Node.JS 10.161\node.EXE
 - npm: 6.9.0 - ~\Node.JS 10.161\npm.CMD

Pre-requisite:
- Clone https://gitlab.com/aaronleem/personalwebsite
- `npm install`

## Steps to reproduce

Working:
- `npm start`
- Visit http://localhost:3000
- Background pattern appearing

Broken:
- `npm run build`
- `node server/bootstrap.js`
- Visit http://localhost:8080
- No background pattern; background-image url() is empty

## Expected Behavior

Background SVG should be in the background-image URL

## Actual Behavior

Background SVG does not appear in the background-image URL; call has empty content

**Comment by jepser** [comment]
It looks like it's more a configuration problem, which is the error that you're seeing? @gear4s

**Comment by gear4s** [comment]
It was a configuration problem, I've fixed the problem.

Thank you for pointing out that it was a configuration problem, helped me figure it out.
