### ISSUE TITLE
Styles are not applied when using <custom-tags>

### ISSUE THREAD

**Issue by pmualaba** [styled-components/styled-components#2802]
## Environment

`## System:
 - OS: Linux 4.15 Ubuntu 18.04.1 LTS (Bionic Beaver)
 - CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
 - Memory: 18.15 GB / 31.27 GB
 - Container: Yes
 - Shell: 5.4.2 - /usr/bin/zsh
## Binaries:
 - Node: 10.15.2 - /usr/bin/node
 - Yarn: 1.15.2 - /usr/bin/yarn
 - npm: 6.11.3 - /usr/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.10.0 => 1.10.6 
 - styled-components: ^5.0.0-beta.9 => 5.0.0-beta.9 `

## Reproduction

https://codesandbox.io/s/custom-tags-framer-motion-with-styled-components-wgg17

## Steps to reproduce
In this codesandbox, change "custom-tag" to "div" and you can see that the styles are correctly applied. If you change it back to "custom-tag" the styles are lost...

## Expected Behavior
"custom-tag" should be rendered in the DOM with styles applied.

## Actual Behavior
"custom-tag" is correctly rendered in the DOM, but the element loses its styles.

**Comment by d7my11** [comment]
This is not styled-components, this is JSX.

If you inspected the element, you will find styled-components classes are applied correctly but for `classname` instead of `class`

you can try this and you will find the same result

```jsx
<custom-element className='my-class'> Hi there </custom-element>
```

will result

```html
<custom-element classname='my-class'> Hi there </custom-element>
```

**Comment by pmualaba** [comment]
In which npm package should this be fixed? is it 'react' or one of its dependencies?

**Comment by d7my11** [comment]
This is not a bug, custom component/tags is not well supported in react.
and if you want to use styles with custom components/tags you have to specify `class` attribute instead of `class` as mentioned here in [react docs for web components](https://reactjs.org/docs/web-components.html)

> One common confusion is that Web Components use “class” instead of “className”.

**Comment by probablyup** [comment]
@d7my11 is correct... I'm not sure how to fix this really since there isn't an easy way to tell if a tag is custom or not during SSR.

**Comment by kitten** [comment]
@pmualaba Out of curiosity, what are you trying to achieve with this custom elemenet? Are you integrating a custom web component or web component library? It is indeed not well supported in React and I'm surprised this is an issue at all actually.

I've left a comment on @probablyup's PR which details why I think this may be an issue we wouldn't want to fix in styled-components, tl;dr it's a case that I wouldn't expect styled-components to be used for (albeit obviously every case being 100% valid) and I'm not sure whether this is something the React team should address first (if they haven't already in a statement / issue)

Cheers! 🙌 

https://github.com/styled-components/styled-components/pull/2819#issuecomment-544354001
