### ISSUE TITLE
Styles aren't editable in devtools 

### ISSUE THREAD

**Issue by o-t-w** [styled-components/styled-components#2805]
I like to make edits in browser devtools when I'm developing (_designing in the browser_).  Why is this not possible with styled components?

**Comment by mxstbr** [comment]
This is possible as long as you are running styled-components in development mode. Unfortunately, Google Chrome has a bug where styles inserted the most performant way (via the CSSOM; which we use in production mode for maximum perf) cannot be edited in DevTools.

If you want to edit styles in production, I'd recommend trying another browser.
