### ISSUE TITLE
Redundant style in v4

### ISSUE THREAD

**Issue by MrunalShidurkar** [styled-components/styled-components#2809]
In reference to [comment](https://github.com/styled-components/styled-components/pull/1962#issuecomment-419090550),

```
const StaticStyledLink = styled.a`
… // 10 static style properties
`

const DynamicStyledLink = styled(StaticStyledLink)`
  color: ${props => props.color};
`
```
If I have a static component `StaticStyledLink ` and 100 `DynamicStyledLink ` which just changing the color for each component then the style created for each component will be redundant.

Calculating the style properties, the properties created as 

v4  --> 10 static  * 100 inherited component  + 100  dynamic properties = 1100 properties
v3  --> 10 static + 100  dynamic properties = 110 properties

This is gradually increasing the size of CSS. This was optimized and was working fine in v3 And this is only happening in v4 (merged styles of its ancestors)

Environments like AMP which has style size limit will be affected by these changes.

**Comment by probablyup** [comment]
It gets gzipped away, not something we're going to change.

**Comment by MrunalShidurkar** [comment]
@probablyup. Can you please elaborate how can i avoid this to reduce the size of style. As I am seeing huge difference between 1100 properties and 110 properties.
