### ISSUE TITLE
how to use styled.div`${str}` make css valid?

### ISSUE THREAD

**Issue by lz-lee** [styled-components/styled-components#2813]
## System:
 - OS: macOS Mojave 10.14.5
 - CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
 - Memory: 201.75 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
 - Yarn: 1.19.1 - ~/.nvm/versions/node/v10.16.0/bin/yarn
 - npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
## npmPackages:
 - styled-components: ^4.4.0 => 4.4.0

## Reproduction

https://codesandbox.io/s/styled-components-base-4p1d4

## Steps to reproduce
```
// Title.js
const str = `
font-size: 1.5em;
text-align: center;
color: ${props => props.name ? 'red' : 'palevioletred'};
`
export default styled.h1`${str}`;
```

## Expected Behavior
css and props both valid
## Actual Behavior
css is invalid, and props is invalid

**Comment by wonism** [comment]
You should use `css` instead of that.
```js
import styled, { css } from 'styled-components';

const str = css`
  font-size: 1.5em;
  text-align: center;
  color: ${props => props.name ? 'red' : 'palevioletred'};
`;

export default styled.h1`${str}`;
```

---
It should be good if you refer this [link](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals).

**Comment by lz-lee** [comment]
> You should use `css` instead of that.
> 
> ```js
> import styled, { css } from 'styled-components';
> 
> const str = css`
>   font-size: 1.5em;
>   text-align: center;
>   color: ${props => props.name ? 'red' : 'palevioletred'};
> `;
> 
> export default styled.h1`${str}`;
> ```
> 
> It should be good if you refer this [link (Tagged templates)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals).

thanks your answer. but i has another question, that is css style `xxx` must start with  styled-components api like `css`. i mean ` font-size : 1.5em; ` as a variable like
```js
const strContent = `
  font-size: 1.5em;
  text-align: center;
  color: ${props => props.name ? 'red' : 'palevioletred'};
`
```
and use with 
```js
import styled, { css } from 'styled-components';

const str = css`${strContent}`
```
[for example](https://codesandbox.io/s/styled-components-base-4p1d4) the style still invalid.
because `strContent` and `tagName` are dynamically generated with split a long string template。
```js
const longString = `
    div.HeaderText {
        color: red;
        font-size: 20px;
        background-color: ${props => props.name ? '#ccc' : ''};
        .foo {
            font-size: 20px;
        }
    }
    div.Avatar {
        .test {
            display:inline-block;
            border: 1px solid red;
            border-radius: 50%;
            font-size: 12px;
            &:hover{
                font-size:20px;
                border-color: black;
                color: red;
                transition: all ease-in 0.3s;
            }
        }
    }
`
```
