### ISSUE TITLE
Consider adding the object syntax to the README

### ISSUE THREAD

**Issue by dandv** [styled-components/styled-components#2814]
Even though SC added this feature [ages ago](https://twitter.com/mxstbr/status/999918627997470724), some [were](https://spectrum.chat/styled-components/general/styled-components-vs-emotion~47206c1b-a688-424e-9e96-6f265993587e) and are [still not aware of it](https://github.com/jsjoeio/styled-components-vs-emotion/issues/2#issuecomment-543576040), and it's been [mentioned by CSS tricks](https://css-tricks.com/the-fragmented-but-evolving-state-of-css-in-js/) as one way in which SC's API has converged towards emotion.

**Comment by probablyup** [comment]
PR welcome for the canary branch!

**Comment by ashr81** [comment]
@probablyup Added about the usage of object syntax into Readme documentations.
