### ISSUE TITLE
Using encoded svg in content: url() breaks styling of extended components (v4 +)

### ISSUE THREAD

**Issue by JonShort** [styled-components/styled-components#2815]
Since upgrading to styled components 4.x multiple svgs have broken in cases where the component has been extended.

This issue also seems to exist in the latest 5.x version

## Environment

CodeSandbox, react + styled components 4.4.0 (issue also exists in latest beta)

## Reproduction

Sandbox showing issue:
https://codesandbox.io/s/styled-components-encoded-svg-issue-t446o

Sandbox showing same code in v3 without issue:
https://codesandbox.io/s/styled-components-encoded-svg-in-v3-wlgo0

## Steps to reproduce
> Please see the attached codesandbox links for more information

- Encode an svg, one with clipPath or transforms typically causes this bug
- Use this encoded svg as `content: url()` or `background-image: url()`
- Extend the component
- Extension styles will be erroneously applied wherever the encoded svg was used

<details>
<summary>
Web GUI to encode svg
</summary>
<a href="https://yoksel.github.io/url-encoder/" target="_blank" rel="noopener noreferrer">https://yoksel.github.io/url-encoder/</a>
</details>

<details>
<summary>
SVG used in these examples
</summary>
<p>

```svg
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24.04 19.5">
	<defs>
		<style>.cls-1{fill:none;}.cls-2{clip-path:url(#clip-path);}.cls-3{fill:#2fac00;}</style>
		<clipPath id="clip-path" transform="translate(-9 -7)">
			<rect class="cls-1" width="42.04" height="27.5"></rect>
		</clipPath>
	</defs>
	<title>Available Feature</title>
	<g id="Layer_2">
		<g id="Layer_1-2">
			<g class="cls-2">
				<path class="cls-3"
					  d="M17.24,26.5a1.27,1.27,0,0,1-.6-.1h-.1l-.1-.1c-.1,0-.2-.1-.3-.2L16,26l-6.6-7.5a1.72,1.72,0,0,1,.1-2.4,1.61,1.61,0,0,1,1.1-.5,1.85,1.85,0,0,1,1.2.5l5.4,6.2,13-14.8a1.66,1.66,0,0,1,1.2-.5,1.61,1.61,0,0,1,1.1.5,1.82,1.82,0,0,1,.1,2.4L18.34,26.1c-.1.1-.2.2-.3.2h-.1l-.1.1a1.27,1.27,0,0,1-.6.1"
					  transform="translate(-9 -7)"></path>
			</g>
		</g>
	</g>
</svg>
```
</p>
</details>

## Expected Behavior
- Extended styles are applied to the correct DOM of the root component

## Actual Behavior
- Extended styles are applied wherever the encoded svg has been included

**Comment by JonShort** [comment]
By changing the svg code, the styling seems to function as expected (see diff below):

```diff
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 24.04 19.5">
    <defs>
-       <style><!--.cls-1{fill:none;}.cls-2{clip-path:url(#clip-path);}-->.cls-3{fill:#2fac00;}</style>
+       <style>.cls-3{fill:#2fac00;}</style>
-         <clipPath id="clip-path" transform="translate(-9 -7)">
-           <rect class="cls-1" width="42.04" height="27.5"/>
-         </clipPath>
    </defs>
    <title>Available Feature</title>
-    <g id="Layer_2">
-       <g id="Layer_1-2">
-            <g class="cls-2">
                <path class="cls-3"
                      d="M17.24,26.5a1.27,1.27,0,0,1-.6-.1h-.1l-.1-.1c-.1,0-.2-.1-.3-.2L16,26l-6.6-7.5a1.72,1.72,0,0,1,.1-2.4,1.61,1.61,0,0,1,1.1-.5,1.85,1.85,0,0,1,1.2.5l5.4,6.2,13-14.8a1.66,1.66,0,0,1,1.2-.5,1.61,1.61,0,0,1,1.1.5,1.82,1.82,0,0,1,.1,2.4L18.34,26.1c-.1.1-.2.2-.3.2h-.1l-.1.1a1.27,1.27,0,0,1-.6.1"
                      transform="translate(-9 -7)"
                      />
-            </g>
-        </g>
-    </g>
</svg>
```

Codesandbox example of the above working in 4+ - https://codesandbox.io/s/styled-components-svg-issue-no-clip-path-ugqs3

So it seems that there might be an issue with how the encoded version of the original svg is interpreted. `clipPath` definitely seemed to cause issues 🤔

I'll keep thinking about this and update this issue 

Resources:
<details>
<summary>
Minified svg code for using with encoder
</summary>

```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24.04 19.5"><path d="M8.24 19.5a1.27 1.27 0 01-.6-.1h-.1l-.1-.1c-.1 0-.2-.1-.3-.2L7 19 .4 11.5a1.72 1.72 0 01.1-2.4 1.61 1.61 0 011.1-.5 1.85 1.85 0 011.2.5l5.4 6.2L21.2.5a1.66 1.66 0 011.2-.5 1.61 1.61 0 011.1.5 1.82 1.82 0 01.1 2.4L9.34 19.1c-.1.1-.2.2-.3.2h-.1l-.1.1a1.27 1.27 0 01-.6.1" fill="#2fac00"/></svg>
```
</details>

**Comment by probablyup** [comment]
FWIW this is a known stylis bug

**Comment by JonShort** [comment]
🎉  Ah great catch. I've had a look at the stylis issue and it's definitely related - https://github.com/thysultan/stylis.js/issues/123

I'll bump their issue, linking to this one.

For the time being in my repository I'll just create a helper which replaces in the encoded string:
- `(` with `%28`
- `)` with `%29`

Here's a sandbox showing that the above works - https://codesandbox.io/s/styled-components-encoded-svg-use-encoded-brackets-grbgd

Feel free to deal with this issue as you wish, it's only hit me today as I updated to v4 recently.

Thanks for your time 👍

**Comment by probablyup** [comment]
@JonShort I generally use `encodeURIComponent` on the svg markup before interpolating it. That might work for you.
