### ISSUE TITLE
[5.0] Styles for search input corrupted in certain conditions

### ISSUE THREAD

**Issue by wojtekmaj** [styled-components/styled-components#2816]
In production, and production only, certain CSS regarding input type="search" gets corrupted.

## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`

## Reproduction

Stupidly simple, no-config app built by parcel-bundler (I don't think that matters though).

In the example below:
- First input will be broken
- Second input will be fine
- Third input will be fine

```
import React from "react";
import ReactDOM from "react-dom";
import styled, { css } from "styled-components";

const Input1 = styled.input`
  &::-ms-clear {
    display: none; width: 0; height: 0;
  }

  &::-webkit-search-decoration,
  &::-webkit-search-cancel-button,
  &::-webkit-search-results-button,
  &::-webkit-search-results-decoration {
    -webkit-appearance: none;
  }
`;

const Input2 = styled.input`
  &::-webkit-search-decoration,
  &::-webkit-search-cancel-button,
  &::-webkit-search-results-button,
  &::-webkit-search-results-decoration {
    -webkit-appearance: none;
  }
`;

const Input3 = styled.input`
  &::-webkit-search-decoration,
  &::-webkit-search-cancel-button,
  &::-webkit-search-results-button,
  &::-webkit-search-results-decoration {
    -webkit-appearance: none;
  }

  &::-ms-clear {
    display: none; width: 0; height: 0;
  }
`;

function App() {
  return (
    <div className="App">
      <Input1
        type="search"
        defaultValue="areallylongtexttoshowhowthetextiscutoff"
      />
      <Input2
        type="search"
        defaultValue="areallylongtexttoshowhowthetextiscutoff"
      />
      <Input3
        type="search"
        defaultValue="areallylongtexttoshowhowthetextiscutoff"
      />
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

## Expected Behavior

All inputs having webkit-specific stuff removed from input search.

![image](https://user-images.githubusercontent.com/5426427/67120308-55c29400-f1e9-11e9-8d0d-ce690057a14b.png)

## Actual Behavior

First input broken:

![image](https://user-images.githubusercontent.com/5426427/67120280-43e0f100-f1e9-11e9-958f-46c791e67638.png)

## Reproduced in...
| Version | Reproduced? |
| --- | --- |
| 5.0.0-beta.9 | ✅ |
| 5.0.0-beta.8 | ✅ |
| 5.0.0-beta.5 | ✅ |
| 5.0.0-beta.4 | ✅ |
| 5.0.0-beta.0 | ✅ |
| 5.0.0-alpha.0 | ✅ |
| 4.4.0 | ❌ |

**Comment by probablyup** [comment]
Could you provide a sandbox for this please?

**Comment by probablyup** [comment]
I can't reproduce it using your example code: https://codesandbox.io/s/brave-darwin-p24wo?fontsize=14

**Comment by wojtekmaj** [comment]
Of course you can't reproduce it. I said it's in production mode only.

**Comment by probablyup** [comment]
Actually it looks fine in production as well: https://csb-p24wo.netlify.com/
