### ISSUE TITLE
How to extend the props when using TypeScript?

### ISSUE THREAD

**Issue by EddyVinck** [styled-components/styled-components#2817]
Ideally I'd like to have something like this:

```ts
interface MyProps extends OriginalProps {
  myCustomProp?: boolean
}

const NewsLetterFormStyles = styled.div((props: MyProps) => ({ /* my styles */ });
```

![image](https://user-images.githubusercontent.com/23434753/67148619-c5945580-f2a1-11e9-8a81-59a5dda4c1ff.png)

The type annotation here is too vague and I can't figure it out by diving in the types myself unfortunately.

**Comment by probablyup** [comment]
Please post in DefinitelyTyped or another help forum, thanks!
