### ISSUE TITLE
Styled-theming prevents usage of custom themes

### ISSUE THREAD

**Issue by daviddelusenet** [styled-components/styled-components#2821]
Since `styled-theming` doesn't allow opening issues I'll open one here.

So, I'm building an UI library with React and Styled Components. We first had pretty extensive theming using the default `ThemeProvider` setup.

Since this was getting out of hand we decided the implement `styled-theming`. We now have a bunch of declarations like these:

```jsx
const borderRadius = theme('layout', {
    [themeLayouts.basic]: '8px',
    [themeLayouts.compact]: '6px',
});

const chipColor = theme('mode', {
    [themeModes.basic]: grey100,
    [themeModes.dark]: white,
    [themeModes.light]: black,
});

export const StyledChip = styled.button`
    border-radius: ${borderRadius};
    color: ${chipColor};
`;
```

However, now we want to add support for the consumer of the library to add their own layout/mode. While using the default way of theming this was really use to achieve. However, because of the usage of `styled-theming` I don't see any way on how this is possible since the layouts/modes are hardcoded inside of the UI library.

So my question is: is it correct that `styled-theming` prevents the consumer of the UI library to add their own custom theming? If so, I'll remove it.

**Comment by probablyup** [comment]
That library isn’t maintained here

**Comment by daviddelusenet** [comment]
@probablyup but it's in the Styled Components repo and the package itself doesn't have the option to open issues?

**Comment by probablyup** [comment]
I believe it was contributed to our org by the original author but is community maintained. 

@mxstbr can we get issues turned on for it?

**Comment by daviddelusenet** [comment]
Just for future reference if everyone ever ends up here, this is how I've solved it now:

- Changed the import `theme from 'styled-theming'` to `styledTheming from 'styled-theming'`.
- This was how I had the primary color in my UI kit defined:

```jsx
const colorPrimary = styledTheming('mode', {
    [themeModes.basic]: purple100,
    [themeModes.dark]: white,
    [themeModes.light]: black,
});
```

I changed that to this:

```jsx
const colorPrimary = styledTheming('mode', {
    [themeModes.basic]: ({ theme }) => theme.colorPrimary || purple100,
    [themeModes.dark]: white,
    [themeModes.light]: black,
});
```

I did this for all of my variables used by `styled-theming`. In this way the user of my UI kit can overwrite the `basic` theme by passing properties to the `ThemeProvider`.
