### ISSUE TITLE
Can’t pass a union type as `styled-component`’s type argument

### ISSUE THREAD

**Issue by smockle** [styled-components/styled-components#2823]
### System:
 - OS: macOS 10.15
 - CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
 - Memory: 8.08 GB / 32.00 GB
 - Shell: 5.7.1 - /bin/zsh
### Binaries:
 - Node: 12.12.0 - /usr/local/bin/node
 - npm: 6.11.3 - /usr/local/bin/npm
### npmPackages:
 - styled-components: ^4.4.0 => 4.4.0 

## Reproduction

[TypeScript playground](https://www.typescriptlang.org/play/?jsx=2&ssl=31&ssc=35&pln=31&pc=57#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChRJY4BnGATwBskATObXA2xlgWjV0gA7JIJjV8AblKkA9DLgAVOmCTVyopFEzokiFMEF0AIijoAFHGGpwA3qTgO49FQC44AIij7D7qY5oAFhAA7gCqIABGRAwMKACS-IJuERAQTCiCUgC+6jCa2mi6AMoAroKGJuaW1nb+zkhu7tRlPn6O1EHBpYLUaEQiCRBJcClpqJmkOfVwAOqoMAGaM8DMAOZIMBYQVnAAvHoGxqZbOwA+cN0Vx9VSsvIActAgKAxw-OBDImKkmGUYwENZvNFlBlmsNgAKMDVNxzFALJYrdabaoASjcACkigANAB0AFEmCAvrZ7I4mPBgkiNm5aFADKs9h4qeCYL5pP5gJg4FDqrjprtBR4vId3KjSf5-CzkUzodtqLiOiFwlEkDF4ok4AB+DyAIDJAPB-7jgjRKkWisXZ-iycDV1F0XJ5cqs-OUukF+yaLToYolkoc0o2sr5Sq6ZV6-UEg0E2o8gD4NwAvu0bGs0en0kCJLY4cmSHEQYCUoNGADzMYAANwAfMhiZFNHA6BAC7YAzAsgBCIsyUuV7KkJAAD0o8EStAOVzoAGEBJ9REyi3CEaDqfB6rtPN5vYFlWa1bEo7sbDAoCUkNaZBWpAOh28hqPLkdJ9PhLP9vPgYjWU5XWuUz4t6HUwjfdD2PU84HPW45AuegmFYd4hC+NQR3gIoYJYBcQTBGV9i4WCIQwj9kVRAADYi+0HaBh1vFC0OYBAN0qKcPmfeBX1Q7hmAIpdP1XddRX-FVzQ1IYDyPE8zwvcjr2Q6COPvRinxJNjaK4rDA1439NxDbpw3TSNElE0CJIkIA)

<details>
<summary><b>Source</b>, in case the TypeScript playground link above doesn’t work</summary>

```TypeScript
import React from 'react'
import styled from 'styled-components';

// Types
interface RainyDayProps {
    type: "rainy";
    showUmbrellaIcon: boolean;
}
interface SunnyDayProps {
    type: "sunny";
    showSunscreenIcon: boolean;
}
type WeatherWidgetProps = RainyDayProps | SunnyDayProps;

// Normal components
function WeatherWidget(props: WeatherWidgetProps): JSX.Element {
    let widget: string = "widget";

    if (props.type === "rainy") {
        widget = props.showUmbrellaIcon ? "☂️" : "umbrella";
    } else if (props.type === "sunny") {
        widget = props.showSunscreenIcon ? "🧴" : "sunscreen";
    }

    return <div>Remember your {widget}!</div>;
}
export const RainyDayComponent = <WeatherWidget type="rainy" showUmbrellaIcon={true} />;
export const SunnyDayComponent = <WeatherWidget type="sunny" showSunscreenIcon={true} />;

// Styled components
const StyledWeatherWidget = styled(WeatherWidget)``
export const StyledRainyDayComponent = <StyledWeatherWidget type="rainy" showUmbrellaIcon={true} />;
export const StyledSunnyDayComponent = <StyledWeatherWidget type="sunny" showSunscreenIcon={true} />;
```
</details>

## Steps to reproduce

When a union type is passed as `styled-component`’s type argument, the TypeScript compiler errors. See the TypeScript playground link above—`StyledWeatherWidget` has red squiggles.

## Expected Behavior

Both interfaces in the union type are valid contracts for the type of the styled React component’s props. As shown in the playground, the unwrapped React component accepts either set of props. Wrapping the React component with `styled-components` should not cause a TypeScript compiler error.

## Actual Behavior

```sh
index.tsx:37:4 - error TS2322: Type '{ type: "rainy"; showUmbrellaIcon: boolean; }' is not assignable to type 'IntrinsicAttributes & Pick<Pick<WeatherWidgetProps, "type"> & Partial<Pick<WeatherWidgetProps, never>>, "type"> & { theme?: any; } & { as?: "symbol" | "object" | "big" | ... 173 more ... | undefined; }'.
  Property 'showUmbrellaIcon' does not exist on type 'IntrinsicAttributes & Pick<Pick<WeatherWidgetProps, "type"> & Partial<Pick<WeatherWidgetProps, never>>, "type"> & { theme?: any; } & { as?: "symbol" | "object" | "big" | ... 173 more ... | undefined; }'.

37   <StyledWeatherWidget type="rainy" showUmbrellaIcon={true} />
      ~~~~~~~~~~~~~~~~~~~

index.tsx:40:4 - error TS2322: Type '{ type: "sunny"; showSunscreenIcon: boolean; }' is not assignable to type 'IntrinsicAttributes & Pick<Pick<WeatherWidgetProps, "type"> & Partial<Pick<WeatherWidgetProps, never>>, "type"> & { theme?: any; } & { as?: "symbol" | "object" | "big" | ... 173 more ... | undefined; }'.
  Property 'showSunscreenIcon' does not exist on type 'IntrinsicAttributes & Pick<Pick<WeatherWidgetProps, "type"> & Partial<Pick<WeatherWidgetProps, never>>, "type"> & { theme?: any; } & { as?: "symbol" | "object" | "big" | ... 173 more ... | undefined; }'.

40   <StyledWeatherWidget type="sunny" showSunscreenIcon={true} />
      ~~~~~~~~~~~~~~~~~~~
```

**Comment by probablyup** [comment]
We don't maintain the types, sorry. Please try DefinitelyTyped

**Comment by smockle** [comment]
Thanks for the quick response @probablyup. 👍 Opened an issue in the DefinitelyTyped repo: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/39300.
