### ISSUE TITLE
Accessing auto generated`props.className` inside `styled()` template

### ISSUE THREAD

**Issue by kilianc** [styled-components/styled-components#2825]
```js
const StyledDiv = styled.div`
  ${(props) => `
    .${props.className}-some-element {
      ...
    }
  `}
`
```

At the moment the `className` prop is undefined

**Comment by probablyup** [comment]
Please open at the appropriate typing repo, we don’t maintain the types.

**Comment by kilianc** [comment]
@probablyup I removed the types, but the question has nothing to do with typescript!

**Comment by ali** [comment]
This seems to work: https://codesandbox.io/s/styled-components-using-classname-prop-dynamically-7dkeh

**Comment by probablyup** [comment]
@ali's example works... what exactly are you trying to do @kilianc?

**Comment by kilianc** [comment]
Where is this documented? And my example was with a custom component. Let me see if I can repro.

**Comment by kilianc** [comment]
I can confirm this does not work with custom components: https://codesandbox.io/s/styled-components-using-classname-prop-dynamically-stqcb

**Comment by ali** [comment]
I think the confusion is that an interpolated function only receives the direct prop values of the rendered component, and it doesn't receive the generated className for the instance of the styled component. Here's a Sandbox that shows that behavior more directly: https://codesandbox.io/s/styled-components-using-classname-prop-dynamically-8ky16

From my perspective it seems like the behavior is working as intended, but I'm merely a user of styled-components and not a maintainer :)

**Comment by kilianc** [comment]
@ali I think there is a thin line, the balance between using CSS as they were supposed to be used and everything components. It is quite impractical that I have to create a component to set a margin or a couple of properties. This is particularly annoying when prototyping and changing styles around. Passing inline styles seems to be the current best approach to this but looking at this beautiful API that we have, honestly: *why not*?

Every `className` that starts with a dash can be scoped using the generated `className` as prefix. I am sure it gets complicated when there are more than one `className` attached but the last "generated" one should work.

**Comment by probablyup** [comment]
@kilianc if you want to make a couple adjustments but not a whole component, that's the general idea behind the "css prop". https://www.styled-components.com/docs/api#css-prop

**Comment by kilianc** [comment]
@probablyup very close, but still not ideal, as it couples the structure to the styles. Is it possible to pass a new prop called `styledClassName` (or something similar) to the template? This would unlock few patterns and best practices that I think are valuable.

```js
const Picture = ({ className }) => (
  <div className={className}>
    <div className={`${className}-foo`}>hi!</div>
  </div>
)

const scn = (className) => ({ styledClassName }) => `${styledClassName}-${className}`

const StyledPicture = styled(Picture)`
  .${scn('foo')} {
    /* this is isolated now */
  }
`
```

**Comment by dsktschy** [comment]
See also https://github.com/styled-components/styled-components/issues/2113
