### ISSUE TITLE
Consider making GlobalStyleComponent a PureComponentt

### ISSUE THREAD

**Issue by ncphillips** [styled-components/styled-components#2827]
I'm one of the maintainers of [TinaCMS](https://tinacms.org), a site editing toolkit for modern React-based sites (e.g. Gatsby and Next.js).

Tina runs in development mode and allows editors to update content from their website. While working on our own [site](https://github.com/tinacms/tinacms-site) we noticed that the website and interface became incredibly sluggish, very quickly. 

After some digging around, we discovered the problem was `createGlobalStyles`. On each edit, the `createGlobalStyles` component was being destroyed and re-created, even though no changes were made. When this would happen, all global styles would be removed and re-added to the DOM. Because of all the recalculation that was happening, **the framerate in Firefox and Safari would drop to 6fps**.

To get around this issue, we simply [memoized the component](https://github.com/tinacms/tinacms-site/blob/master/src/components/foundations/reset/components/GlobalStyles.tsx#L13):

```js
const GlobalStyles = createGlobalStyle`
  // ...
`;

export default React.memo(() => <GlobalStyles />);
```

This does the trick for now and we will provide documentation informing users of this issues.

**Would it make sense to make `createGlobalStyles` return a `PureComponent`?**

**Comment by probablyup** [comment]
This is fixed in the v5 beta
