### ISSUE TITLE
Numbers in objects don't get a unit appended

### ISSUE THREAD

**Issue by kitze** [styled-components/styled-components#283]
I'm trying to migrate my app from aphrodite (which uses objects) to 💅, but I have some issues. 

For example [this object](https://i.imgur.com/4wfwMMa.png) gets compiled to [this](https://i.imgur.com/BSp2c3K.png).

The problem is it's not adding "px" where it's supposed to.

@mxstbr suggested [this tool](https://jsbin.com/gesaniseto/edit?js,output) for easier migration but it's also not converting the syntax [properly](https://i.imgur.com/gw6lMch.png).

**Comment by fabb** [comment]
emotion automatically appends `px` to numbers, would be cool if styled-components could do this too
https://emotion.sh/docs/object-styles#numbers

**Comment by probablyup** [comment]
Pretty sure we do

**Comment by fabb** [comment]
At least not in 4.1.3, I tried.
