### ISSUE TITLE
Didn't pass the on prop down to the the element

### ISSUE THREAD

**Issue by danhuang1202** [styled-components/styled-components#2833]
## Environment
```
## System:
 - OS: macOS Mojave 10.14.6
 - CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
 - Memory: 12.51 GB / 32.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 10.16.0 - /usr/local/bin/node
 - Yarn: 1.17.3 - /usr/local/bin/yarn
 - npm: 6.9.0 - /usr/local/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.5.1 => 1.10.6
 - styled-components: ^4.2.0 => 4.3.2
```

## Reproduction
```js
  const StyledDiv = styled.div`
      display: inline-block;
      width: 36px;
      height: 36px;
      background-color: red;
  `

  const Sample = ({className}) => (
      <StyledDiv 
        className={className} 
        on="tap:AMP.navigateTo(url='http://google.com')"
      />
  )
```

## Expected Behavior
Should render Html element with `on` props
```
<div class="gmZad" on="tap:AMP.navigateTo(url='http://google.com')">
```

## Actual Behavior
No `on` props in Html element
```
<div class="gmZad">
```

## Work Round
```js
const Div = ({className}) => (
  <div 
    className={className} 
    on="tap:AMP.navigateTo(url='http://google.com')"
  />
)

const StyledDiv = styled(Div)`
  display: inline-block;
  width: 36px;
  height: 36px;
  background-color: red;
`
```

Why the `on` prop didn't pass down ?
Is there a best practice to pass `on` prop ?

**Comment by probablyup** [comment]
@danhuang1202 it's because that isn't a standard HTML attribute. We purposefully don't pass unknown attributes down for simple components (e.g. `styled.div`) since they may just be used for styling purposes. Generally speaking, you should use data attributes for any arbitrary DOM content/behaviors attached to nodes.

**Comment by danhuang1202** [comment]
I'm try to use styled-component to style AMP element, and the `on` attributes is generally  used as event handler in AMP. I know I should use data attributes in normal cases. But it seams there is no way to pass `on` props to simple components by styled-components.  Thanks for your reply.

ref: https://amp.dev/documentation/guides-and-tutorials/learn/amp-actions-and-events/

**Comment by probablyup** [comment]
This just got merged into the prop filtering library, so I imagine they’ll
cut a new version soon.

**Comment by probablyup** [comment]
Actually it’s already out: https://github.com/emotion-js/emotion/releases/tag/%40emotion%2Fis-prop-valid%400.8.4

Use your package manager to update the subdependency!

**Comment by danhuang1202** [comment]
Cool, Thanks a lot !
