### ISSUE TITLE
styled.webview supported in styled-components?

### ISSUE THREAD

**Issue by muscaiu** [styled-components/styled-components#2834]
**Is the webview tag supported in styled-components?**
It's an Electron app with Chromium and i'm supposed to use webview.

```
const StyledWebview = styled.webview(`
  height: 955px;
`);
```
Error:
```
styled_components__WEBPACK_IMPORTED_MODULE_3___default.a.webview is not a function
```

**Comment by probablyup** [comment]
It’s not in our element list but you can try styled(‘webview’) if it’s an
html element inside the electron DOM

**Comment by muscaiu** [comment]
This answers my question. Thank you!
