### ISSUE TITLE
Move contributor auto invitation flow to GitHub actions

### ISSUE THREAD

**Issue by lekterable** [styled-components/styled-components#2836]
Hey, just curious, is this part from [CONTRIBUTING.md]( https://github.com/styled-components/styled-components/blob/master/CONTRIBUTING.md ) still valid? 🤔 
> If your Pull Request is merged, regardless of content, you're eligible for push access to the organization on GitHub. This is checked for on pull request merges and an invite is sent automatically. (thanks to an Aeryn instance that @mxstbr runs)

I got my PR https://github.com/styled-components/styled-components/pull/2787 merged a couple of days ago and I don't think that I received any invite.

**Comment by probablyup** [comment]
I don't think so - I haven't seen that run in some time.

**Comment by lekterable** [comment]
Was it stopped on purpose? If so, should we remove it from the docs? It's a question directly to @mxstbr I suppose

**Comment by mxstbr** [comment]
No we still want that, however something is amiss with our Aeryn setup. We should probably just move that logic to GitHub actions, that should make it relatively easy to re-build and less expensive to run!

**Comment by lekterable** [comment]
Sounds like a fun thing to get to know actions better, I'll try to tackle this

**Comment by lekterable** [comment]
@mxstbr @probablyup 
UPDATE:
I've worked on it for a while, and I almost made it work [(repo)](https://github.com/lekterable/inclusive-organization-action), but [apparently](https://stackoverflow.com/questions/58737785/github-actions-empty-env-secrets) you cannot access secrets from a workflow triggered by a PR merged to the main repo if the user who opened it doesn't have a write access, which makes me believe that this cannot be done using GitHub actions. 
Do you have any ideas on how to work around it?

**Comment by mxstbr** [comment]
What if we ran the action on commits to `master` instead? Those have to be triggered by a contributor by write access. We could check if the commit is a merge commit, and if it is run the PR steps to invite people.

Could that work?

**Comment by lekterable** [comment]
I've tried running the action on `push` event to the `master` branch, and I do have access to the secrets which is great, but it's now significantly harder to determine:
- if the commit is a merge commit?
- who is the author of the PR?

I've logged the whole [context](https://gist.github.com/lekterable/eb208d5217cbbc163e0221ce9a08e9e4), but I can't think of a satisfying way to answer those two questions.
One way would be looking at the `message` of the `head_commit`, if it starts with `Merge pull request` then its a merge commit and parse it to get the PR's author name. This obviously kinda sucks, as changing the commit message would break it.

Any suggestions?

**Comment by mxstbr** [comment]
I am asking internally at GitHub, will reply back! Thank you so much for digging into this @lekterable 👍

**Comment by mxstbr** [comment]
Apparently we can figure out which one is the merge commit by running these commands:

```sh
# Merge commit
$ git --no-pager show 7f4238d71c13a77c442b79739955f58c6438d9e6 --merges | grep -q .
$ echo $?
0

# Non-merge commit
$ git --no-pager show 1df7e9f5693c2cef20baef86a13dd582d88905f4 --merges | grep -q .
$ echo $?
1
```

Can you work with that @lekterable?

**Comment by lekterable** [comment]
any clues why am I getting `fatal: bad object 4a147552fcd9e26d78f2c23752af9c0cd5bc3ec9` when trying to run this command on any of the ids or sha from the [payload](https://gist.github.com/lekterable/eb208d5217cbbc163e0221ce9a08e9e4) I've posted before?

**Comment by mxstbr** [comment]
I think you want to use the `id`, not the `tree_id` (which 4a147552fcd9e26d78f2c23752af9c0cd5bc3ec9 is).

**Comment by lekterable** [comment]
It's the same for the `id`, I just posted latest error I had as I was trying everything 😛

**Comment by lekterable** [comment]
Okay, I've figured out a way how to tell if a given commit is a merge commit, merge commits have at least two parents, so I'm just grabbing the commit's sha from the payload, fetching more info from Github's API and checking that. 
Now the question is, how to tell who opened a PR? 
I'll read the docs a little as it might also be that easy, but if you have any ideas, they would be greatly appreciated :)

**Comment by lekterable** [comment]
yahooo, I've figured this out as well and created an open source repo with this [action](https://github.com/lekterable/inclusive-organization-action), may I open a PR to use it for styled-components?

**Comment by mxstbr** [comment]
Amazing!!! Yes please @lekterable!!!!

**Comment by lekterable** [comment]
alrighty then, PR created - https://github.com/styled-components/styled-components/pull/2867 I will need you @mxstbr to create a personal access token with `admin:org`rights and save it as a repository secret named `ACCESS_TOKEN`(or whatever name works for you as I can change it in the PR). After that, It should be ready to merge 🤞 🤞
