### ISSUE TITLE
className attrs don't append when styling a styled component

### ISSUE THREAD

**Issue by three60five** [styled-components/styled-components#2839]
There was a breaking change with regard to how className `attrs` behave in styled-components. This change really makes the DX for using something like Tachyons or TailwindCSS that much worse. I've loved mixing Tachyons and Styled Components ever since `attrs` were introduced. Indeed, I think using utility classes was an inspiration for implementing the `attrs` functionality. 

It used to be I could write a simple component like: 
```
export const Title = styled.h1.attrs({
  className: "orange f1 sans-serif"
})``;
```
and then if I need to bespoke style it, I would just append new classes on to it like so:
```
export const AltTitle = styled(Title).attrs({
  className: "serif"
})``;
```

Since the appended classes would come after the first classes, I could also override classes provided through `attrs` this way as well. 

I think the new paradigm is a significant step backward as far as DX for using className `attrs`.

## Reproduction
Previous `styled-components` behavior:
https://codesandbox.io/s/styled-components-base-uujje

Updated behavior:
https://codesandbox.io/s/styled-components-base-57ibz

## Expected Behavior
classNames in `attrs` are appended in order when styling a styled component like:
https://codesandbox.io/s/styled-components-base-uujje

## Actual Behavior
classNames are dropped when styling a styled-component like:
https://codesandbox.io/s/styled-components-base-57ibz

**Comment by probablyup** [comment]
@mxstbr @kitten what do you guys think? I'm not sure if there's a specific reason this sort of auto-merging doesn't happen anymore for `className` and `style`

**Comment by three60five** [comment]
Using CodeSandbox, I was able to track this down as a breaking change between 3.x and 4.x.

**Comment by probablyup** [comment]
@three60five this will be fixed in v5, thanks for reporting!

**Comment by three60five** [comment]
@probablyup Thanks so much. Looking forward to all the hotness of v5.

**Comment by probablyup** [comment]
Fixed in v5 rc2
