### ISSUE TITLE
Compress css, remove comment when using production build

### ISSUE THREAD

**Issue by kopax** [styled-components/styled-components#284]
I am using react boilerplate 3.3.3 and styled-components 1.1.2.

I have executed a production build with the command `npm run start:production` and checked in the generated css `<style type="text/css">` tag, the css is still uncompressed with their comments.

 I would like to know if it's in react-boilerplate webpack plugin that I should take care of the compression, or if I should check on styled-components side.

Also, it would be great to validate the generated css in some way.

**Comment by k15a** [comment]
The css in the style tag is injected at runtime so it doesn't matter how big it is. A babel-plugin which compresses the template strings in production mode would be a good addition.

You can "validate" you css with style-lint. (https://github.com/styled-components/styled-components#linting)

**Comment by kopax** [comment]
I have tried the following for installing : 

    $ npm install --save-dev stylelint-processor-styled-components stylelint stylelint-config-standard

I've created the `.stylelintrc`

```json
{
  "processors": ["stylelint-processor-styled-components"],
  "extends": "stylelint-config-standard",
  "syntax": "scss"
}
```

I've added this run command to my `package.json`:

     "lint:css": "stylelint './app/components/**/*.js'"

This gave me the following error : 

	dka@dev-01:[/workspace/github.com/mxstbr/react-boilerplate]: npm run lint:css

	> react-boilerplate@3.3.3 lint:css /workspace/github.com/mxstbr/react-boilerplate
	> stylelint './app/components/**/*.js'


	app/components/bootstrap/atoms/A/index.js
	 5:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/A/tests/index.test.js
	 5:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Alert/index.js
	 6:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Alert/messages.js
	 6:10  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Alert/tests/index.test.js
	 5:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Breadcrumb/index.js
	 5:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Breadcrumb/tests/index.test.js
	 4:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Button/index.js
	 5:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Button/tests/index.test.js
	 4:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/ButtonGroup/index.js
	 5:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/ButtonGroup/tests/index.test.js
	 4:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Close/index.js
	 1:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Close/messages.js
	 6:10  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Close/tests/index.test.js
	 5:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Code/index.js
	 6:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Code/tests/index.test.js
	 4:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Col/index.js
	 1:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Col/tests/index.test.js
	 5:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Container/index.js
	 1:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Container/tests/index.test.js
	 5:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/ContainerFluid/index.js
	 1:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/ContainerFluid/tests/index.test.js
	 5:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Form/index.js
	 7:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Form/tests/index.test.js
	 5:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/H1/index.js
	 1:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/H1/tests/index.test.js
	 4:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/H2/index.js
	 1:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/H2/tests/index.test.js
	 4:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/H3/index.js
	 1:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/H3/tests/index.test.js
	 4:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/H4/index.js
	 1:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/H4/tests/index.test.js
	 4:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/H5/index.js
	 1:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/H5/tests/index.test.js
	 4:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/H6/index.js
	 1:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/H6/tests/index.test.js
	 4:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Hr/index.js
	 1:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Hr/tests/index.test.js
	 4:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Img/index.js
	 8:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Img/tests/index.test.js
	 1:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Input/index.js
	 1:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Input/tests/index.test.js
	 5:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/IssueIcon/index.js
	 1:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/IssueIcon/tests/index.test.js
	 1:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Kbd/index.js
	 6:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Kbd/tests/index.test.js
	 4:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Label/index.js
	 1:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Label/tests/index.test.js
	 5:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Li/index.js
	 5:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Li/tests/index.test.js
	 5:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Pre/index.js
	 6:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Pre/tests/index.test.js
	 4:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Row/index.js
	 1:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Row/tests/index.test.js
	 5:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Table/index.js
	 6:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Table/tests/index.test.js
	 4:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Tag/index.js
	 3:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Tag/tests/index.test.js
	 4:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Tbody/index.js
	 5:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Tbody/tests/index.test.js
	 5:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Td/index.js
	 4:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Td/tests/index.test.js
	 5:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Tfoot/index.js
	 4:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Tfoot/tests/index.test.js
	 5:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Th/index.js
	 4:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Th/tests/index.test.js
	 5:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Thead/index.js
	 4:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Thead/tests/index.test.js
	 5:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Tr/index.js
	 4:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Tr/tests/index.test.js
	 5:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Ul/index.js
	 9:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/atoms/Ul/tests/index.test.js
	 5:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/molecules/DropDown/index.js
	 5:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/molecules/DropDown/tests/index.test.js
	 5:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/molecules/Nav/index.js
	 6:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/molecules/Nav/messages.js
	 6:10  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/molecules/Nav/tests/index.test.js
	 5:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/molecules/NavBar/index.js
	 5:1  ✖  Unknown word   CssSyntaxError

	app/components/bootstrap/molecules/NavBar/tests/index.test.js
	 5:1  ✖  Unknown word   CssSyntaxError

	app/components/kopax/atoms/Fa/index.js
	 1:1  ✖  Unknown word   CssSyntaxError

	app/components/kopax/atoms/Fa/tests/index.test.js
	 5:1  ✖  Unknown word   CssSyntaxError

	app/components/kopax/atoms/LoadingButton/index.js
	 1:1  ✖  Unknown word   CssSyntaxError

	app/components/kopax/atoms/LoadingButton/tests/index.test.js
	 1:1  ✖  Unknown word   CssSyntaxError

	app/components/kopax/atoms/LoadingIndicator/Circle.js
	 1:17  ✖  Unknown word   CssSyntaxError

	app/components/kopax/atoms/LoadingIndicator/index.js
	 1:1  ✖  Unknown word   CssSyntaxError

	app/components/kopax/atoms/LoadingIndicator/tests/Circle.test.js
	 1:1  ✖  Unknown word   CssSyntaxError

	app/components/kopax/atoms/LoadingIndicator/tests/index.test.js
	 1:1  ✖  Unknown word   CssSyntaxError

	app/components/kopax/atoms/LoadingIndicator/tests/Wrapper.test.js
	 1:1  ✖  Unknown word   CssSyntaxError

	app/components/kopax/atoms/LoadingIndicator/Wrapper.js
	 1:1  ✖  Unknown word   CssSyntaxError

	app/components/kopax/atoms/Tremble/index.js
	 1:18  ✖  Unknown word   CssSyntaxError

	app/components/kopax/atoms/Tremble/tests/index.test.js
	 5:1  ✖  Unknown word   CssSyntaxError

	app/components/kopax/molecules/LoginForm/index.js
	 8:1  ✖  Unknown word   CssSyntaxError

	app/components/kopax/molecules/LoginForm/messages.js
	 6:10  ✖  Unknown word   CssSyntaxError

	app/components/kopax/molecules/LoginForm/tests/index.test.js
	 1:1  ✖  Unknown word   CssSyntaxError

	app/components/kopax/molecules/TwitterFeed/index.js
	 6:1  ✖  Unknown word   CssSyntaxError

	app/components/kopax/molecules/TwitterFeed/tests/index.test.js
	 1:1  ✖  Unexpected empty source   no-empty-source

	app/components/kopax/organisms/NavTop/index.js
	 1:1  ✖  Unknown word   CssSyntaxError

	app/components/kopax/organisms/NavTop/messages.js
	 6:10  ✖  Unknown word   CssSyntaxError

	app/components/mxstbr/atoms/Grid/index.js
	 3:1  ✖  Unknown word   CssSyntaxError

	app/components/mxstbr/atoms/Grid/tests/index.test.js
	 1:1  ✖  Unknown word   CssSyntaxError

	app/components/mxstbr/atoms/Toggle/index.js
	 7:1  ✖  Unknown word   CssSyntaxError

	app/components/mxstbr/atoms/Toggle/Select.js
	 1:1  ✖  Unknown word   CssSyntaxError

	app/components/mxstbr/atoms/Toggle/tests/index.test.js
	 1:1  ✖  Unknown word   CssSyntaxError

	app/components/mxstbr/atoms/Toggle/tests/Select.test.js
	 1:1  ✖  Unknown word   CssSyntaxError

	app/components/mxstbr/atoms/ToggleOption/index.js
	 7:1  ✖  Unknown word   CssSyntaxError

	app/components/mxstbr/atoms/ToggleOption/tests/index.test.js
	 1:1  ✖  Unknown word   CssSyntaxError

	app/components/mxstbr/molecules/LoginForm/index.js
	 9:1  ✖  Unknown word   CssSyntaxError

	app/components/mxstbr/molecules/LoginForm/messages.js
	 1:10  ✖  Unknown word   CssSyntaxError

	app/components/mxstbr/molecules/LoginForm/tests/index.test.js
	 1:1  ✖  Unknown word   CssSyntaxError

	app/components/mxstbr/organisms/FormPageWrapper/index.js
	 5:1  ✖  Unknown word   CssSyntaxError

	app/components/mxstbr/organisms/FormPageWrapper/messages.js
	 6:10  ✖  Unknown word   CssSyntaxError

	app/components/mxstbr/organisms/FormPageWrapper/tests/index.test.js
	 1:1  ✖  Unknown word   CssSyntaxError


	npm ERR! Linux 3.16.0-4-amd64
	npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "lint:css"
	npm ERR! node v6.5.0
	npm ERR! npm  v3.10.9
	npm ERR! code ELIFECYCLE
	npm ERR! react-boilerplate@3.3.3 lint:css: `stylelint './app/components/**/*.js'`
	npm ERR! Exit status 2
	npm ERR! 
	npm ERR! Failed at the react-boilerplate@3.3.3 lint:css script 'stylelint './app/components/**/*.js''.
	npm ERR! Make sure you have the latest version of node.js and npm installed.
	npm ERR! If you do, this is most likely a problem with the react-boilerplate package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     stylelint './app/components/**/*.js'
	npm ERR! You can get information on how to open an issue for this project with:
	npm ERR!     npm bugs react-boilerplate
	npm ERR! Or if that isn't available, you can get their info via:
	npm ERR!     npm owner ls react-boilerplate
	npm ERR! There is likely additional logging output above.

	npm ERR! Please include the following file with any support request:
	npm ERR!     /workspace/github.com/mxstbr/react-boilerplate/npm-debug.log


The syntax it's complaining for is things like that : 

	// eslint-disable-next-line no-class-assign
	A = styled(A)`
	  ${(props) => `
	    color: ${props.theme.bootstrap.atoms.A['$link-color']};
	    text-decoration: ${props.theme.bootstrap.atoms.A['$link-decoration']};
	  
	    ${hoverFocus( // <====== here
	      props.theme.bootstrap.atoms.A['$enable-hover-media-query'],
	      `
	        color: ${props.theme.bootstrap.atoms.A['$link-hover-color']};
	        text-decoration: ${props.theme.bootstrap.atoms.A['$link-hover-decoration']};
	      `
	    )};
	    
	    &:focus {
	      ${tabFocus()}
	    }
	    
	    /* The next classes are not part of Bs4, added for rendering of DocBootstrapPage */
	    &.hidden-sm-up{
	     ${getVisibilityUtilities(props.theme.bootstrap.atoms.A['$grid-breakpoints'])}
	    }
	  `}
	`;

**Comment by mxstbr** [comment]
See https://github.com/styled-components/babel-plugin-styled-components/issues/12!
