### ISSUE TITLE
Duplicate identifier 'FormData'.  TS2300

### ISSUE THREAD

**Issue by Belka383** [styled-components/styled-components#2842]
## System:
 - OS: Windows 10
 - CPU: (8) x64 Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz
 - Memory: 1.37 GB / 7.89 GB
## Binaries:
 - Node: 10.14.1 - C:\Program Files\nodejs\node.EXE
 - npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
## npmPackages:
 - styled-components: 4.4.1 => 4.4.1

## Steps to reproduce
**Step 1 - Create component:**

`import React from 'react';
import { Link } from 'react-router-dom';
import styled from 'styled-components';

const StyledLink = styled(Link)`
    text-decoration: none;

    &:focus, &:hover, &:visited, &:link, &:active {
        text-decoration: none;
    }
`;

export default (props) => <StyledLink {...props} />;`

**Step 2 - Use component:**
`<Tab component={StyledLink} to={'/'} label='Home' />`
## Expected Behavior
Open application in browser without errors

## Actual Behavior
Error:
`TypeScript error in C:/Users/Игорь/Desktop/reactproject/GiverStamps/GiverStamps/ClientApp/node_modules/@types/react-native/globals.d.ts(40,15):
Duplicate identifier 'FormData'.  TS2300

    38 | interface Blob {}
    39 | 
  > 40 | declare class FormData {
       |               ^
    41 |     append(name: string, value: any): void;
    42 | }
    43 |`

**Comment by probablyup** [comment]
Whatever that is has nothing to do with styled-components

**Comment by AubreyHewes** [comment]
It is true it is not _this_ project but it is this project's typescript definition `@types/styled-components`. The (at the time of writing 4.4.0) [npm package dependencies](https://www.npmjs.com/package/@types/styled-components/v/4.4.0) have both `react` and `react-native` types and so overlap.

See https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34882

@Belka383 a workaround, for yarn,  https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33311#issuecomment-494477593

**Comment by probablyup** [comment]
Sure, but we also don't maintain the typings.
