### ISSUE TITLE
Regression: Styled Components 5 has Arrow Functions in the Compiled Code which Breaks IE11

### ISSUE THREAD

**Issue by fabb** [styled-components/styled-components#2845]
## Environment

5.0.0-rc.0, the issue was not there in 4.x

See styled-components.browser.esm.js:

```
const isObject = val => {
  return typeof val === 'function' || (typeof val === 'object' && val !== null && !Array.isArray(val));
};

const isValidKey = key => {
  return key !== '__proto__' && key !== 'constructor' && key !== 'prototype';
};
```

This breaks IE 11 compatibility.

**Comment by fabb** [comment]
I think the issue is that you use babel preset-env but actually do not specify the env via `"targets"` or `.browserslistrc`. This defaults to ECMAScript 2015+ 😱
https://babeljs.io/docs/en/babel-preset-env

**Comment by probablyup** [comment]
Probably mixin-deep, switched it after the last beta

**Comment by fabb** [comment]
Yepp, that should be the culprit: https://github.com/jonschlinkert/mixin-deep/blob/master/index.js

**Comment by probablyup** [comment]
Alright, I'm just going to revert that change for the moment.

**Comment by probablyup** [comment]
Fixed in https://github.com/styled-components/styled-components/releases/tag/v5.0.0-rc.1 thanks for reporting!
