### ISSUE TITLE
Feature request: flip RTL

### ISSUE THREAD

**Issue by HosseinAlipour** [styled-components/styled-components#2847]
When designing RTL views, sometimes we don't want turn all the templates into RTL, e.g., JSS does this by [flip](https://github.com/alitaheri/jss-rtl#opting-out-for-an-entire-sheet). any ideas?

**Comment by HosseinAlipour** [comment]
I found the [solution](https://github.com/cssjanus/cssjanus#preventing-flipping).

**Comment by HosseinAlipour** [comment]
it seems the [solution](https://github.com/cssjanus/cssjanus#preventing-flipping) has not been implemented yet, so, I reopen the issue.

**Comment by probablyup** [comment]
The stylis-rtl plugin uses the "PROPERTY" phase of stylis which strips out the trailing semicolon on CSS rules. I made a PR against stylis-rtl to use an earlier phase which should avoid this issue: FindHotel/stylis-rtl#4

**Comment by probablyup** [comment]
This should be fixed in rc3 + the new `stylis-plugin-rtl`, thanks!
