### ISSUE TITLE
forwardedAs rendering as="tag" html attribute

### ISSUE THREAD

**Issue by greypants** [styled-components/styled-components#2848]
##  Environment
```
## System:
 - OS: macOS High Sierra 10.13.6
 - CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
 - Memory: 21.19 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
 - Yarn: 1.19.1 - /usr/local/bin/yarn
 - npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
```

Present on both v4 and v5

## Reproduction

https://codesandbox.io/s/styled-components-base-qv8kt?fontsize=14

## Steps to reproduce
1) create a `styled.td`
2) Extend it with with `styled()`
3) Pass `forwardedAs="th"`

## Expected Behavior
render a `<th>`

## Actual Behavior
renders `<td as="th">`

## Notes
`as` vs `forwardedAs` usage is somewhat confusing. The docs say:

> If you choose to wrap another component with the styled() HOC that also accepts an "as" prop, use "forwardedAs" to pass along the desired prop to the wrapped component.

On first read, that led me to do this:

```jsx
const TableCell = styled.td`
  background-color: ${props => props.bgColor};
  padding: 8px;
`;

const MyStyledTableCell = styled(TableCell)`
  color: red;
`;

const MyTableCell = ({ as, ...props }) => {
  // "forwardedAs" is problematic here
  return <MyStyledTableCell forwardedAs={as} {...props} />;
};


render(
  <table>
    <tr>
      <MyTableCell bgColor="orange" as="th">
        {`Uh oh.. this rendered as <td as="th"> instead of <th>`}
      </MyTableCell>
    </tr>
  </table>
);
```
However, the results were unexpected as seen below. 

![image](https://user-images.githubusercontent.com/647549/68056523-c24d9080-fcc9-11e9-8535-8d75c091c007.png)

Turns out `forwardedAs` _is only needed if the what's being `styled()` isn't a Styled Component_. Otherwise `as` should be used. Changing `MyTableCell` to use `as` instead of `forwardedAs` fixes the rendering. 

Not sure if this should be solved with documentation, or if this is a bug. Seems like `as="th"` shouldn't end up in the html markup either way.

**Comment by probablyup** [comment]
From the docs:

> If you choose to wrap another component with the `styled()` HOC that also accepts an "as" prop, use "forwardedAs" to pass along the desired prop to the wrapped component.

So as you mentioned in an update to your post, "as" is the correct prop to use in this scenario. Since you used `forwardedAs` on a generic element type "td" it was converted into "as" and was successfully passed through to the DOM since "as" is a real attribute: https://github.com/emotion-js/emotion/blob/c53646d5ddf453a480da1cd4428773bddc93c30f/packages/is-prop-valid/src/props.js#L34
