### ISSUE TITLE
Remove autoprefixer in dev mode?

### ISSUE THREAD

**Issue by kitze** [styled-components/styled-components#285]
When debugging flex in the Chrome dev tools, it's a bit of a hassle to go through all the autoprefixed properties, turn them off/on and play with their values.

Example 👉 https://i.imgur.com/4gtJj0X.png
Is there a way that autoprefixer can be turned off in dev mode?

**Comment by jaydenseric** [comment]
Unfortunately there is not a browser on the market that will render everything properly without using at least some prefixes; turning it off entirely is not desirable. If the auto-prefixing is adding redundant prefixes, then that is an issue ideally solved for development _and_ production.

**Comment by mxstbr** [comment]
I think this will be quite a bit of effort for not a lot of benefit, so I'll close this for now. #286 will improve the autoprefixing a bit!

**Comment by PsiXdev** [comment]
Disabling of autoprefixer would be a convenient feature. Very strange and pitiful that you are against this

**Comment by philpl** [comment]
@PsiXdev this might be possible in the future once we segregate our CSS pipeline from the main project. This *might* make it possible to configure this through a babel plugin

The plan for this is outlined here: https://github.com/philpl/sweetsour

Once — let's say if — this happens I'll reopen this issue :wink:

**Comment by gitowiec** [comment]
So what about disabling vendor prefixes in development mode? Any moves bringing us closer to this awesome (and very needed) feature? Do you remember this picture? It is hard to develop with such a mess on screen

![image](https://user-images.githubusercontent.com/1553195/86887377-bd629b80-c0f8-11ea-9556-9d5cd90b472d.png)

**Comment by kitten** [comment]
@gitowiec thats a thing now if you use the `StyleSheetManager` provider: https://github.com/styled-components/styled-components/blob/f0a84f418e2625a0c2a4adf73dc42e93c8992f67/packages/styled-components/src/models/StyleSheetManager.js#L10
