### ISSUE TITLE
ButtonProps not supporting in ReactNative

### ISSUE THREAD

**Issue by abhimanyuPatil** [styled-components/styled-components#2850]
Created a styled component in React-Native. but when hovered on **InvertedButton** it shows following error:
 **_Type '{ TouchableComponent?: ComponentClass<{}, any> | undefined; ViewComponent?: ComponentClass<any, any> | undefined; buttonStyle?: StyleProp<ViewStyle>; title: string | undefined; ... 50 more ...; useForeground?: boolean | undefined; }' is not assignable to type 'Pick<Pick<ButtonProps & RefAttributes<Button> & { buttonStyle: { backgroundColor: string; borderRadius: number; borderWidth: number; borderColor: string; }; }, "style" | "title" | "TouchableComponent" | ... 52 more ... | "ref"> & Partial<...>, "style" | ... 55 more ... | "ref">'._**
Looks like its not supporting ButtonProps from react-native-elements
```
type IButtonType = 'inverted' | 'full' | 'flex';
interface IButton extends ButtonProps{
  btnType:IButtonType[]
}
export const LinearGradientButton = (
  props:IButton
) => {
  const {btnType, ...rest} = props;
  const buttonStyles = [StyleSheet.flatten([btnType.map(e => getType(e))])];
      <InvertedButton
        containerStyle={buttonStyles}
        title={props.title}
        titleStyle={{color: '#ff6700'}}
        {...rest}
      />
    );
};
const GradientButton = styled(Button).attrs(() => ({
  ViewComponent: LinearGradient, // Don't forget this!
  linearGradientProps: {
    colors: ['#ffa200', '#ff6600'],
    start: {x: 0, y: 0.5},
    end: {x: 1, y: 0.5},
  },
  buttonStyle: {
    borderRadius: 0,
  },
}))``;
```

**Comment by probablyup** [comment]
Please repost this in DefinitelyTyped, we don't maintain the types in this repo. Thanks for using styled components!
