### ISSUE TITLE
'disabled' attribute on input element is not functioning on v4.4.0 and above 

### ISSUE THREAD

**Issue by sxxhlx** [styled-components/styled-components#2851]
## System:
 - OS: macOS 10.15.1
 - CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
 - Memory: 6.28 GB / 32.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 12.6.0 - /usr/local/bin/node
 - Yarn: 1.16.0 - /usr/local/bin/yarn
 - npm: 6.9.0 - /usr/local/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.5.1 => 1.10.6 
 - styled-components: ^4.4.0 => 4.4.0 

## Reproduction
`<Input
      name='mobile'
      onChange={(e) => this.handleChange(e)}
      value={this.state.mobile}
      disabled={true}
      readOnly={'readonly'}
      type='tel'
      maxLength={11}
/>`
## Steps to reproduce
just use it 
## Expected Behavior
this <input /> element should be disabled 
## Actual Behavior
this <input /> element has no disabled attribute on it .

**Comment by probablyup** [comment]
Looks fine to me, probably something with your custom `Input` component I see there. https://codesandbox.io/s/styled-components-base-1rs7o
