### ISSUE TITLE
v5 Regression: css not applied in IE11 only

### ISSUE THREAD

**Issue by fabb** [styled-components/styled-components#2853]
## System:
 - OS: macOS 10.15.1
 - CPU: (4) x64 Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz
 - Memory: 63.27 MB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
 - npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: ^1.10.6 => 1.10.6 
 - styled-components: beta => 5.0.0-rc.1 

We use next 9.1.1.

## Reproduction

Unfortunately I'm just tracking the problem down and don't have a reproduction scenario yet. It happens in this code:

```
        const lazyload = typeof window !== 'undefined'
```

```
        {lazyLoad ? (
            <img
                css={css`
                    flex-shrink: 0;
                `}
                data-flickity-lazyload={src}
                alt={alt}
            />
        ) : (
            <img
                css={css`
                    flex-shrink: 0;
                `}
                src={src}
                alt={alt}
            />
        )}
```

## Steps to reproduce

Unfortunately none yet, we have a component which contains the code above. Not yet sure if it is related to the `window` check.

## Expected Behavior

It should work the same as with SC v4.

## Actual Behavior

* The SSR output looks good, the correct css rules (including autoprefixed ones) are generated in the `<head>` and the correct css class name is set on the `<img>` element.
* The css rule is correctly there on Chrome
* This single css rule is missing on IE11

**Comment by topaxi** [comment]
Sounds similar to an Issue we had: https://github.com/styled-components/styled-components/issues/2770

**Comment by taikn** [comment]
Same happening to me using MS Edge 18 and styled-components 5.0.0-rc.1, styles are being generated on the server side, but disappear completely on the client after rehydration.

**Comment by fabb** [comment]
In my case the bug does not happen in Edge (checked Edge 15, 16, 17, 18), it only happens in IE11.

**Comment by probablyup** [comment]
Hmm you have conditional rendering logic that is different between server
and client. That’s likely screwing things up. It’s better to mount the
image in a zero dependency useEffect instead so there isn't a discrepancy
between environments when rendering.

**Comment by fabb** [comment]
It‘s probable, and I‘ll check if it is related. But still it is only broken in v5 on IE11 which is weird. I fear that some of these bugs where someone does some conditional rendering might creep in because it compiles and even works correctly on Chrome. So it would be good if we could fix that directly in SC.

**Comment by probablyup** [comment]
I think this is actually just a React thing that’s more noticeable in IE.
Any time there’s a rehydration difference (especially relating to HTML
attributes) things don’t always update correctly until the next render
pass.

**Comment by fabb** [comment]
I tried setting `const lazyload = true` and `const lazyload = false`, and both resolved the issue. So it really seems to be related to hydration. That leaves some questions:

* Why does this work in other browsers?
* Why does this work in SC v4?
* During hydration, when the SSR `<img>` is hidden and the  CSR `<img>` is shown, shouldn't the css from the `css` prop of the CSR `<img>` be added to the CSSOM StyleSheet?
* Do you think this is something that should be fixed in SC, or in user land? (I'd say SC because it behaves inconsistently across browsers and SC versions)

**Comment by fabb** [comment]
Btw. I tried setting the `key` prop of both `<img>`es to the same string, but it did not help.

**Comment by fabb** [comment]
hrm, we need to have different SSR and CSR also for dynamic rendering, so we do not render everything in SSR to save some cpu and improve response times.

**Comment by probablyup** [comment]
> I tried setting const lazyload = true and const lazyload = false, and both resolved the issue.

Yes this is because it will be the same value for both environments, so there will be no rehydration difference.

From the React docs (https://reactjs.org/docs/react-dom.html#hydrate):

> There are no guarantees that attribute differences will be patched up in case of mismatches.

**Comment by fabb** [comment]
Hm true, I noticed that the rehydration is also wrong on Chrome and other browsers, and I guess that SC v4 just caused more rerenders which "fixed" the faulty hydration. So yes, we need to fix this in our application.
