### ISSUE TITLE
In v5, nested components are receiving an empty object for `theme` when using `dive()`

### ISSUE THREAD

**Issue by thatmarvin** [styled-components/styled-components#2854]
## Steps to reproduce

1. Open these sandboxes (the only difference is the installed version of styled-components):
    - https://codesandbox.io/s/peaceful-swartz-sc4-hdzh5 (v4.4.1)
    - https://codesandbox.io/s/serene-hill-sc5-4e86v (v5.0.0-rc.1)
1. Click on the "Tests" tab on the right preview panel to run the tests
1. Observe that the tests pass for v4.4.1, but fails for v5.0.0-rc.1.

## Expected Behavior

When `dive()`-ing into a nested component, the component should receive the `theme` object passed by `ThemeProvider`.

## Actual Behavior

The `theme` prop receives an empty object.

**Comment by probablyup** [comment]
There are probably two instances of styled components active at once.
That’s the most common culprit for a missing theme prop

**Comment by thatmarvin** [comment]
@probablyup Even in codesandbox? Note that this works fine at run time, just not in Jest, for the specific situation when using `dive()`-ing _into a child component_. 

```jsx
<Thing>
  <Child> // `theme` is correct here
    <Text /> // `theme` is incorrect here
  </Child>
</Thing>
```

**Comment by probablyup** [comment]
I assume there's an enzyme bug related to `useContext`, as that's the only meaningful context change between v4 and v5.

**Comment by andi1984** [comment]
@probablyup Yes they have: https://github.com/airbnb/enzyme/issues/2176
