### ISSUE TITLE
in v5   when use  disableVendorPrefixes at ssr style is empty

### ISSUE THREAD

**Issue by straxico** [styled-components/styled-components#2857]
## System:
 - OS: Windows 10
 - CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
 - Memory: 2.57 GB / 7.88 GB
## Binaries:
 - Node: 12.4.0 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.15.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
 - npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
## npmPackages:
 - babel-plugin-styled-components: ^1.10.6 => 1.10.6
 - styled-components: ^5.0.0-rc.1 => 5.0.0-rc.1

## Reproduction

https://codesandbox.io/s/styled-components-base-wd3de

**Comment by probablyup** [comment]
@straxico That sandbox is the default one, do you have an example reproduction of your actual issue?

**Comment by straxico** [comment]
https://codesandbox.io/s/with-styled-components-dybcj?fontsize=14

**Comment by probablyup** [comment]
This should be fixed in rc3!
