### ISSUE TITLE
Changing theme on React Native resets the navigation state

### ISSUE THREAD

**Issue by plahteenlahti** [styled-components/styled-components#2858]
Hi!
I'm currently in the process of rewriting my React Native app to use styled-components. I've made an additional dark theme to which the user change from the settings. However, when changing the theme, it seems to reset my navigation state (using React Navigation). I've wrapped the app with themeprovider and use Redux to keep track of the selected theme.

Is this intended behavior, or have I done something wrong?

Thanks for the great library!

**Comment by probablyup** [comment]
@plahteenlahti interesting... there shouldn't be any affect there. Perhaps try putting the ThemeProvider under the ReduxProvider?

**Comment by plahteenlahti** [comment]
@probablyup It is already because I'm using Redux storing the theme variable. I did some further testing and it seems that the theme actually changes before the navigation state resets so it might be that I'm doing something wrong in my project. I will try to reproduce this in another project.

**Comment by probablyup** [comment]
Gotcha, very likely not an issue of styled-components then so I'm going to close this for the time being.
