### ISSUE TITLE
Styled-components didn't trigger media queries correctly

### ISSUE THREAD

**Issue by yuuta1999** [styled-components/styled-components#2873]
## System:
 - OS: Windows 10
 - CPU: (4) x64 Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz
 - Memory: 1.04 GB / 7.90 GB
## Binaries:
 - Yarn: 1.19.1 - C:\Users\yuuta\AppData\Roaming\npm\yarn.CMD
 - npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD

## Reproduction
https://codesandbox.io/s/thirsty-jang-oiyup

## Expected Behavior
The texts should be green in small-screen devices and red in large-screen devices.
## Actual Behavior
I got the opposite result. I've already tested on other computers, on different operating systems (both real OS and VM). I also switched to using normal `className` and it worked well. Have any ideas what happened here? Any comments are appreciated.

**Comment by kitten** [comment]
This is expected behaviour. Since the first rule with red comes first it’s overwritten but he second one with green.

On large screen sizes the second rule still matches so keep that in mind and you’ll be fine :)
