### ISSUE TITLE
Allow npm packages that use styled-components to safely isolate themselves

### ISSUE THREAD

**Issue by ncphillips** [styled-components/styled-components#2876]
## Steps to reproduce

* Create an npm package that uses `styled-components`
* Install that package in an app that uses a different version of `styled-components`
* Try to run the app

## Expected Behavior

Both versions of `styled-components` run side by side without a problem

## Actual Behavior

The app breaks because of the two different versions.

The current suggestions ([1](https://www.styled-components.com/docs/faqs#duplicated-module-in-node_modules), [2](https://www.styled-components.com/docs/advanced#avoiding-conflicts-with-thirdparty-styles-and-scripts)) put the onus of fixing this on the package _user_ rather the package _creator_. IMO this is not acceptable. As a package maintainer I do not think that people using our packages need to know about `styled-components` at all, let alone that they need do some weird things to their environment variables or run some de-duplication script. 

Maybe this is already possible but I can't see how

**Comment by spbyrne** [comment]
I second this 👍 

Styled-components solves the CSS encapsulation issue and replaces it with an issue that's more frustrating for package authors. You shouldn't have to worry about what version of SC is used by a project that includes your package nor should they have to worry about the inner CSS-in-JS workings of a given package.

**Comment by probablyup** [comment]
The issue is that s-c like react has a runtime. It’s not straightforward to
“unify” multiple runtimes
