### ISSUE TITLE
prototype.isReactElement throws errors on old versions of Chrome (v49)

### ISSUE THREAD

**Issue by leerob** [styled-components/styled-components#2889]
## Environment
- Google Chrome `v49`
- styled-components `v4.4.0`

## Reproduction

When upgrading to version `4.4.0` of styled-components, we noticed a regression affecting early versions of Google Chrome (less then `v57`). It appears the root cause is [here](https://github.com/styled-components/styled-components/blob/c22b95f13762796ae171a0ede31a23f83d434e35/packages/styled-components/src/utils/isStatelessFunction.js#L7) or [here](https://github.com/styled-components/styled-components/blob/c3eedbeb79621acd668e15ed2d63107528ed81c3/packages/styled-components/src/utils/isDerivedReactComponent.js#L3):

```js
test.prototype.isReactComponent
```

It's hard to find any information about `isReactComponent`. Dan said [here](https://twitter.com/dan_abramov/status/787739945301635073):

>  `.isReactComponent` is an implicit detail and we reserve the right to change it in the future.

He also mentioned it throws for [arrows that don't have prototypes](https://twitter.com/dan_abramov/status/787740274441261056).

![image](https://user-images.githubusercontent.com/9113740/69298363-38f7f280-0bd3-11ea-98d3-002f823bc2ed.png)

We don't know _exactly_ where the root of this is coming from in our application, but we're wondering if there's a better way to handle this on the styled-components side that could prevent throwing errors. Something to make it more resilient. 

## Steps to reproduce

I tried to reproduce in CodeSandbox inside Chrome 49 in BrowserStack, but I don't know if CodeSandbox even supports Chrome 49 😢A basic CRA + styled-components example wasn't working.

## Expected Behavior

Ideally, this wouldn't throw an error.

## Actual Behavior

It's currently throwing an error.

I know it's a long shot to ask for Chrome support this far back, but it appears something between `v4.1.2` and `v4.4.0` changed. For large applications, we still have a small percentage of users on old versions of Chrome.

At the least, do you have any suggestions of how we could mitigate this on our side? Our current strategy was to revert styled-components back to `v4.1.2`. 

Any thoughts or ideas are helpful 🙏

**Comment by probablyup** [comment]
This is curious, if you look at the actual sites where it's used, we're checking for the existence of prototype before calling the function:

https://github.com/styled-components/styled-components/blob/921e14f7af063ea7518145860bac8135d79040d5/packages/styled-components/src/utils/isStatelessFunction.js

https://github.com/styled-components/styled-components/blob/921e14f7af063ea7518145860bac8135d79040d5/packages/styled-components/src/utils/isDerivedReactComponent.js

**Comment by kitten** [comment]
A stack trace here would be nice. But I’ll close this for now due to inactivity 😅
