### ISSUE TITLE
5.0.0-rc2 mixes up classes in production

### ISSUE THREAD

**Issue by wmertens** [styled-components/styled-components#2892]
## System:
 - OS: macOS Mojave 10.14.6
 - CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
 - Memory: 58.39 MB / 8.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 10.16.0 - ~/.nix-profile/bin/node
 - Yarn: 1.19.1 - ~/bin/node_modules/.bin/yarn
 - npm: 6.9.0 - ~/.nix-profile/bin/npm
 - Watchman: 4.9.0 - /Users/wmertens/.nix-profile/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: 1.10.6 => 1.10.6 
 - styled-components: ^5.0.0-rc.2 => 5.0.0-rc.2 

v5 beta was working nicely for me in dev, but now in production, I have a table with a simple `thead` that I add some styling to, and SSR works fine, but then it hydrates and it gets a class from another component.

Thoughts on how this could happen? I can't create a repro right now.

**Comment by mxstbr** [comment]
Sounds like a SSR checksum mismatch potentially? Differing DOM structures between client & server. Still shouldn't happen in that way though...

**Comment by wmertens** [comment]
And whoever just pushed v5.0.0-regexrehydrate fixed it 😄 🎉

**Comment by probablyup** [comment]
Hmm that build is the same as rc2 lol

**Comment by wmertens** [comment]
🤔 indeed, only the version name changed… that's really weird. I'll keep an eye on it for sure.

**Comment by wmertens** [comment]
actually, now that I think about it, it could be that there were different package versions on the server and client (not styled-components, but others). That could explain rehydration differences, maybe.
