### ISSUE TITLE
React Native Pseudo element not working, getting node of type rule not supported

### ISSUE THREAD

**Issue by AjitZK** [styled-components/styled-components#2893]
## System:
 - OS: Linux 5.0 Ubuntu 19.04 (Disco Dingo)
 - CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz
 - Memory: 6.15 GB / 15.53 GB
 - Container: Yes
 - Shell: 5.5.1 - /usr/bin/zsh
## Binaries:
 - Node: 12.13.1 - /usr/bin/node
 - Yarn: 1.19.1 - /usr/bin/yarn
 - npm: 6.13.1 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^4.4.1 => 4.4.1 
`

## Reproduction

Using react native, styled-components@4.4.1, neither Style Objects or the regular way works... Please help!!

**Does not work**
```
const box = styled.View(props => ({
	flex: "1",
	borderColor: props.borderColor,
	"&::before": {
		content: "''",
		width: "0px",
		height: "0px",
		alignSelf: "'center'",
		borderWidth: "12px",
		borderRightColor: "'transparent'",
		borderBottomColor: "'transparent'",
		borderTopColor: "'transparent'",
	},
}));
```

**Does not work**
```
const box = styled.View`
	flex: 1;
	border-color: ${props => props.borderColor};

	&::before {
		content: "";
		width: 0;
		height: 0;
		align-self: "center";
		border-width: 12;
		border-right-color: "transparent";
		border-bottom-color: "transparent";
		border-top-color: "transparent";
	}
`;
```

## Expected Behavior
CSS to render a triangle

## Actual Behavior
`Node of type rule not supported as an inline style`

**Comment by kitten** [comment]
There are no pseudo elements in React Native 😅  Similarly you won't be able to use:

- Any unsupported positioning
- Some `transform`s don't have transformations afaik
- Child / Children / Sibling selectors
- Media queries or other at rules

Sorry about that! React Native is very focused on their style system, in the sense that they don't support full CSS but only CSS-like StyleSheets, so all that is done on RN in `styled-components` is some thin conversions to `StyleSheet`s
