### ISSUE TITLE
RTL Example with SSR

### ISSUE THREAD

**Issue by aganglada** [styled-components/styled-components#2894]
v5 has support for `stylisPlugins` and one of them is right to left support.

I've managed to make it work on the client, but in the server, style generation fail if I pass the `stylisRTLPlugin` onto `StyleSheetManager`.

server.tsx
```
<StyleSheetManager
   stylisPlugins={features.ft_rtl ? [stylisRTLPlugin] : null}
     sheet={sheet.instance}
 >
    <HelmetProvider context={helmetContext}>
        <App> 
            {routes}
         </App>
    </HelmetProvider>
</StyleSheetManager>

...

// Getting chuncks (dynamic imports) from @loadable
const chuncks = extractor.collectChunks(<BaseApp />)
const jsx = sheet.collectStyles(chuncks)
const body = renderToString(jsx)

...
```

client.tsx
```
<StyleSheetManager
   stylisPlugins={features.ft_rtl ? [stylisRTLPlugin] : null}
 >
    <HelmetProvider context={helmetContext}>
        <App> 
            {routes}
         </App>
    </HelmetProvider>
</StyleSheetManager>
```

Works without the plugin.

Could you provide an example code or a hint on what I may be doing wrong?

**Comment by probablyup** [comment]
This should be working properly now with https://github.com/styled-components/styled-components/releases/tag/v5.0.0-rc.3.
