### ISSUE TITLE
createGlobalStyle does not clean up styles using React.StrictMode

### ISSUE THREAD

**Issue by perjansson** [styled-components/styled-components#2895]
## System:
 - OS: macOS 10.15.1
 - CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
 - Memory: 857.00 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
 - Yarn: 1.16.0 - /usr/local/bin/yarn
 - npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
## npmPackages:
 - styled-components: ^4.4.1 => 4.4.1 

## Reproduction

https://codesandbox.io/s/wonderful-hill-6glof

## Steps to reproduce

1. Load the[ code sandbox](https://codesandbox.io/s/wonderful-hill-6glof)
2. Click the button Toggle several times and notice how the background changes between white and black
3. Change to render `<App />` using StrictMode by uncommenting `ReactDOM.render(<React.StrictMode><App /></React.StrictMode>, rootElement);``
4. Click the button Toggle several times

## Expected Behavior

The should change between black and white

## Actual Behavior

The background stays black after the first press on the toggle button. The global CSS (rendered by `GlobalStyle` in `ComponentOne`) is never removed when unmounting when in Strict Mode. This is perhaps related to [Strict Mode "intentionally double-invoking" some lifecycle methods to determine side effects that could be a problem in the upcoming async mode in React](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects).

**Comment by probablyup** [comment]
I think it's exactly what you suspect re: React double-calling methods internally in development. FWIW v5 does not have this issue.

**Comment by perjansson** [comment]
> I think it's exactly what you suspect re: React double-calling methods internally in development. FWIW v5 does not have this issue.

Great that v5 doesn’t have it, really looking forward to that! 👍

But indeed, React will make double calls in strict mode to make sure side effects don’t cause problems, like this one I guess where to global styles are not removed. And styled-components v4 is supposed to be having “Full StrictMode compliance for React” https://medium.com/styled-components/announcing-styled-components-v4-better-faster-stronger-3fe1aba1a112, which is why I assumed it’s a bug in v4.

**Comment by perjansson** [comment]
@probablyup Why did this get closed, if the v4 of styled-components is supposed to be fully compatible with React StrictMode I think this is a bug, or?
