### ISSUE TITLE
Destructuring props in the styled components

### ISSUE THREAD

**Issue by pedronauck** [styled-components/styled-components#290]
Hi, first of all, congratulations, your lib is awesome 👏

I liked so much the idea to write components by the style of them. And I think that the lib covers a lot of situations. Really, I have just a simple idea to can destructuring the props inside the style, I think that write `props.something` can be very repetitive and if have a other way to do that, can be usuful.

My idea is something like that:

```js
import styled from 'styled-components';

const Button = styled.button(({ backgroundColor }) => `
  background: ${backgroundColor};
`)
```

The good thing is you can't deprecate nothing, is just a other way to write the styled components.

What you think about that?

Cheers

**Comment by k15a** [comment]
https://github.com/styled-components/styled-components/issues/273

**Comment by mxstbr** [comment]
Thanks @k15a 😉
