### ISSUE TITLE
box-shadow only works in iOS (React Native)

### ISSUE THREAD

**Issue by fedebabrauskas** [styled-components/styled-components#2901]
Hi there!

I'm using the property `box-shadow` in a View component to create a card look, but my shadow is only being applied in iOS, not in Android 😢.

React Native has different properties for iOS/Android to create a shadow:
```
// Shadow in iOS
shadowColor: 'black',
shadowOpacity: 0.26,
shadowOffset: { width: 0, height: 2 },
shadowRadius: 8

// Shadow in Android
elevation: 5,
```

Maybe `box-shadow` is not applying the `elevation` property correctly?

Thanks!

**Comment by kitten** [comment]
Sorry for the lack of documentation on this one. Box shadows cannot be converted 1:1 so you’ll have to specify them separately.

Have a look at the upstream issue at: https://github.com/styled-components/css-to-react-native/issues/119 👍
