### ISSUE TITLE
Extending a styled component from a different file breaks Jest

### ISSUE THREAD

**Issue by shamilovtim** [styled-components/styled-components#2902]
## System:
 - OS: macOS 10.15.1
 - CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
 - Memory: 329.85 MB / 16.00 GB
 - Shell: 3.0.2 - /usr/local/bin/fish
## Binaries:
 - Node: 12.4.0 - /usr/local/bin/node
 - Yarn: yarn install v0.21.3
 - [1/4] Resolving packages...
 - [2/4] Fetching packages...
 - [3/4] Linking dependencies...
 - [4/4] Building fresh packages...
 - Done in 7.41s. - /usr/local/bin/yarn
 - npm: 6.13.0 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: ^1.10.6 => 1.10.6
 - styled-components: v5.0.0-rc.2 => 5.0.0-rc.2

## Reproduction
1. Simply extend a component from a different file
```typescript
import { Caption2 } from '../components/UI/Typography';

const DisclaimerText = styled(Caption2)`
  padding-top: 8;
`;
```

2. run `jest`

Throws error: 
```typescript
TypeError: Cannot read property 'rules' of undefined

      53 | `;
      54 |
    > 55 | const DisclaimerText = styled(Caption2)`
         |                     ^
      56 |   padding-top: 8;
      57 | `;
      58 |
 at createStyledNativeComponent (node_modules/styled-components/native/dist/styled-components.native.cjs.js:5467:45)
      at templateFunction (node_modules/styled-components/native/dist/styled-components.native.cjs.js:5555:12)
      at Object.<anonymous> (screens/SettingsScreen.tsx:55:21)
      at Object.<anonymous> (navigation/SettingsStack.tsx:5:1)
```

3.  Confirm the cause by bringing the component inline into your file rather than import:
```typescript
const Caption2 = styled(Text)`
  color: #8e8e93;
  font-weight: 400;
`;

const DisclaimerText = styled(Caption2)`
  padding-top: 8;
`;
```

4. Error is gone

**Comment by kacianoghelere** [comment]
I'm having the same issue in my project...

@shamilovtim did you found any solution to this?

**Comment by shamilovtim** [comment]
inlined the component into the file i wanted to extend it from

**Comment by kacianoghelere** [comment]
@shamilovtim well, that's not gonna work for me, but thanks anyway

**Comment by kacianoghelere** [comment]
After a few hours trying, I've found an "elegant" way to solve the problem: wrapping the imported styled in a exclusive component. Hope that helps.

```jsx
import React from 'react'

import * as Typography from '~/styles/typography'

const PlainText = ({ children, ...props }) => (
  <Typography.PlainText {...props}>{children}</Typography.PlainText>
)

export default PlainText
```
