### ISSUE TITLE
Slow rehydration

### ISSUE THREAD

**Issue by grebenyuksv-preply** [styled-components/styled-components#2904]
**Problem** 
Dear maintainers, `styled-components` is awesome, but I have to migrate my NextJS project away from it due to its painfully slow rehydration, which is blocking my main thread. 

**Suggestion**
I was thinking, would it make sense to split the rehydration into non-blocking asynchronous steps e.g. with using `requestAnimationFrame`? Is there an assumption that `StyleSheet.prototype.rehydrate` should get executed synchronously or at any specific moment?

I would be happy to contribute, including coding any of your ideas.

Additional info: here's [my page](https://preply.com/en/skype/english-tutors?ssr), it's obfuscated so you can only find a `rehydrate` function call by name deep inside the performance report. It consists of many `insertRule` and `appendChild` calls (not visible in our production bundle though). It takes around 100ms on my top MacBook, which means a couple of seconds on a $200 Android phone.

**Comment by probablyup** [comment]
Have you tried v5?

**Comment by grebenyuksv-preply** [comment]
Yeah, that was the first thing I tried, and it seemed to have only made it worse (couple weeks ago). Your question sounds valid though, makes sense to first wait for a non-canary v5 release. Closing this for now, sorry!

**Comment by probablyup** [comment]
> it seemed to have only made it worse

That's interesting, rehydration in our testing has been much faster in v5. I'd be curious to see some sort of performance analysis there... any chance you could instrument it and share a chrome profiling session with the v5 update?
