### ISSUE TITLE
RTL conversion  on shorthand styles

### ISSUE THREAD

**Issue by HosseinAlipour** [styled-components/styled-components#2909]
[cssjanus](https://cssjanus.github.io/#input/margin%3A%200%20900px%200%200%20%3B) converts shorthands corectly. but [this sandbox](https://codesandbox.io/s/react-pp89r) demonstrates that no rtl conversion is done on shorthands.

**Comment by probablyup** [comment]
Honestly I'm not convinced that plugin actually works... https://github.com/FindHotel/stylis-rtl/issues/3

**Comment by probablyup** [comment]
Tracked this down to a bug in cssjanus: https://github.com/cssjanus/cssjanus/issues/81

**Comment by probablyup** [comment]
This should be fixed with https://github.com/styled-components/styled-components/releases/tag/v5.0.0-rc.3 + stylis-plugin-rtl (note the new npm package name.)
