### ISSUE TITLE
SSR Memory Leak with v5 release candidate 2

### ISSUE THREAD

**Issue by brad-decker** [styled-components/styled-components#2913]
### Default, Baseline
```
## System:
 - OS: macOS 10.15
 - CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
 - Memory: 3.11 GB / 32.00 GB
 - Shell: 5.6.2 - /usr/local/bin/zsh
## Binaries:
 - Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
 - Yarn: 1.19.1 - ~/****/****/applications/site/node_modules/.bin/yarn
 - npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.10.0 => 1.10.6
 - styled-components: ^4.0.0 => 4.4.1
```

### After upgrade to RC 2
```
## System:
 - OS: macOS 10.15
 - CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
 - Memory: 3.11 GB / 32.00 GB
 - Shell: 5.6.2 - /usr/local/bin/zsh
## Binaries:
 - Node: 10.15.1 - ~/.nvm/versions/node/v10.15.1/bin/node
 - Yarn: 1.19.1 - ~/****/****/applications/site/node_modules/.bin/yarn
 - npm: 6.4.1 - ~/.nvm/versions/node/v10.15.1/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.10.0 => 1.10.6
 - styled-components: ^5.0.0-rc.2 => 5.0.0-rc.2
```

Notes: Both environments use TypeScript, Next.JS and latest versions of react

## Steps to Reproduce
1. Use the `_document.js` file found in the `with-styled-components` example of next.js.
2. Have styled-components 4.4.1 installed.
3. Run application using N|Solid from nodesource. Also could probably get this information by attaching chrome inspector to node. 
4. Run `npx loadtest -c 5 --rps 10 -k -t 90 http://localhost:8080/`
5. See that memory usage has peaks and valleys, RSS and Heap memory allocation move together. External memory barely moves. 
6. install release candidate 2
7. repeat the steps above.
8. See that Heap allocation remains consistent, MORE consistent than in 4.4.1, but RSS and External memory allocation seem to climb indefinitely until the application crashes under load.
9. Look at memory snapshot and see that ServerStyleSheet is massive, at around 2 gigabytes, and the server is holding onto array buffers and strings that seem to reference styles.

### Memory Timeline In N|Solid on version 4.4.1
[heapsnapshot](https://drive.google.com/file/d/1pZLTW4tDuPLRsahBk2zBlVuTQz_F4Bkz/view?usp=sharing)
![image](https://user-images.githubusercontent.com/4448075/70098761-94be7480-15f2-11ea-8a2b-f28f7aeba396.png)

### Memory Timeline in N|Solid on Version 5 RC 2
[heapsnapshot](https://drive.google.com/file/d/12NDJ8Eup_jy0HbIo7V3bzvUa9thm9SSH/view?usp=sharing)
![image](https://user-images.githubusercontent.com/4448075/70098886-03033700-15f3-11ea-9992-f090c6e75c0d.png)

### Comparison of Heap snapshots
![image](https://user-images.githubusercontent.com/4448075/70098999-4493e200-15f3-11ea-99e5-84fd0ab75fcb.png)

RC 2 is on the left. The snapshots were taken as close to the same point as possible (immediately following the load test that was run with the same stats: 5 concurrent threads, keep-alive connections, 10 requests per second for 90 seconds). The only change between the two is upgraded to RC 2.

**Comment by brad-decker** [comment]
If you'd like me to provide heap snapshot dumps or screen recordings of the two tests I can, but I doubt GitHub would like me much trying to attach here. :)

**Comment by probablyup** [comment]
Some sort of profiling would definitely be helpful, thanks.

**Comment by brad-decker** [comment]
@probablyup how would you like me to send?

**Comment by brad-decker** [comment]
@probablyup updated the issue description to include links to heapsnapshots.

**Comment by floric** [comment]
@brad-decker  I had the same issue with v5. My memory leak was caused by global styles. I replaced them by static generated CSS for now. Not sure though if this is connected with your problem.

**Comment by kitten** [comment]
Like @floric says, this could be due to some usage patterns and specific things that aren’t being used correctly.

I can take a look at the heap snapshot but I’d suspect that that won’t actually tell us much about what’s going on.

It’s probably a good idea to check whether you’re creating dynamic StyledComponents over and over again inside the render function which would lead to this sort of memory profile.

**Comment by fabb** [comment]
> Like @floric says, this could be due to some usage patterns and specific things that aren’t being used correctly.

@kitten what if my global styles depend on some component prop? How would I do that safely without leaking?

**Comment by mxstbr** [comment]
@fabb that is exactly why we switched from the old `injectGlobal` to the new `createGlobalStyle` API:

```JSX
const GlobalStyles = createGlobalStyle`
  background: ${props => props.bg};
`

<GlobalStyles bg="red" />
```

**Comment by fabb** [comment]
@mxstbr I wasn‘t aware of the former, but yes, we use exactly the latter pattern inside FunctionComponents, or in the render function of regular Components. So we DO create new dynamic StyledComponents all the time:

> It’s probably a good idea to check whether you’re creating dynamic StyledComponents over and over again inside the render function which would lead to this sort of memory profile.

So... what else to do?

**Comment by fabb** [comment]
@mxstbr ah ok, so instead of calling `createGlobalStyle` inside render functions, create them on top level and parametrize them with props. I‘ll check my usages. Would be helpful though if an unsafe usage of `createGlobalStyle` could somehow produce a compiler/linter error or at leased a console error.

**Comment by mxstbr** [comment]
That's correct, definitely should not be re-created every render that would definitely lead to a memory leak!

@probablyup @kitten reckon we can add a warning when it's used like that?

**Comment by kitten** [comment]
@mxstbr yep, we probably can add a warning about but it’d be based on React internals

**Comment by brad-decker** [comment]
@kitten we are using global styles using the new api and not inside a render method. As far as creating many styled components in render wouldn’t that have had a similar adverse effect in v4?

**Comment by mxstbr** [comment]
> As far as creating many styled components in render wouldn’t that have had a similar adverse effect in v4?

It would still be detrimental to performance, although it might not lead to a memory leak as quickly. Definitely do not create your styled components in the render cycle!!

**Comment by brad-decker** [comment]
@mxstbr if we are, which I doubt, it would be a user error rather than a chosen pattern. Any tips on hunting down where this could be happening at?

**Comment by brad-decker** [comment]
I have confirmed @kitten and @mxstbr that the only two instances of createGlobalStyles in our application are used in files to export components that are consumed in JSX, we are not calling createGlobalStyles in render methods.

**Comment by jaslakson** [comment]
Just today we bumped our prod instance up to RC2 after having passed our automated and manual regression tests in our staging environment. Approx 1hr after releasing, we saw a spike in memory usage that brought our site down. We restarted the dynos and all was well until another hour had passed - did this twice while investigating the problem. Found this thread and reverted our version change and the problem has gone away.

we use next.js and we do use `createGlobalStyle` - here's a snippet of how it's used in our `_app.js` file:
```
//...other imports removed for brevity
import { createGlobalStyle } from 'styled-components';
import { reset } from '../config/css';

const GlobalStyle = createGlobalStyle`${reset}`;

class MyApp extends App {
  //...code removed for brevity

  render() {
    const {
      Component,
      pageProps,
      queryParams,
      store,
      url,
    } = this.props;

    return (
      <Provider
        store={store}
      >
        <ErrorBoundary>
          <GlobalStyle />
          <Component
            {...pageProps}
            queryParams={queryParams}
            url={url}
          />
        </ErrorBoundary>
      </Provider>
    );
  }
}
```

The `reset` import is an exported template string that's basically:
```
import styledNormalize from 'styled-normalize';

const reset = `
  ${styledNormalize}
  html {
  ...some css here
  }
`;

export default reset;
```

Please let me know if there's a better/alternate way to use `createGlobalStyle`.

Here's a snapshot of our metrics dashboard, showing memory usage - the vertical line just after 9 and during the final spike are when we released/rolled back the RC2 change:
<img width="313" alt="Screen Shot 2019-12-11 at 3 56 08 PM" src="https://user-images.githubusercontent.com/17276211/70659851-e9837000-1c2e-11ea-8ed4-0348f20bbf95.png">

**Comment by probablyup** [comment]
> we bumped our prod instance up to RC2

From what version?

**Comment by jaslakson** [comment]
`"styled-components": "4.3.2"` - to be safe, we just reverted to this version instead of the latest on 4.x

was looking through the changes for the 5.x branch and the only thing that stuck out to me as a possible memory leak is:

`useEffect(() => () => globalStyle.removeStyles(instance, styleSheet), []);`

could the runtime beholding onto a reference to `instance` or `styleSheet` unexpectedly - I'm certainly not an expert in the subtleties here, but is there a difference between an arrow fn and a standard `function` that could be at fault? I don't see anything else in the change that stood out (speaking about this one https://github.com/styled-components/styled-components/pull/2824/files). The reason this stood out is that it's a cleanup/callback setup, which sometimes can be a source of memory leaks if they reference something that should have been garbage collected.

**Comment by probablyup** [comment]
Hmm I'd hope React would drop that since during SSR unmount effects will never be called... might be a bug on their end.

**Comment by probablyup** [comment]
If you wanted to try patching the code, you could surround that effect in an "if browser" sort of check so it doesn't get run on the server

**Comment by jaslakson** [comment]
That's a good idea - I'll look into that - might be able to patch it and run some load tests on our staging servers over the course of a few hours to verify.

**Comment by fabb** [comment]
Wait, I thought `useEffect` won‘t be called at SSR at all, same as `componentDidMount`?

**Comment by probablyup** [comment]
Supposedly

**Comment by brad-decker** [comment]
It's not supposedly. it is not called on SSR.

**Comment by brad-decker** [comment]
what can I do to remove the needs more info? What additional information can I provide?

**Comment by fabb** [comment]
Could it be that the increased memory use stems from overuse of `useMemo` (e.g. in `StyleSheetManager` or `ThemeProvider`)?


As I read here (https://kentcdodds.com/blog/usememo-and-usecallback), `useMemo` needs to keep references to **previous** elements of both its result and its dependency array, which could cause memory growth:

> As a related note, if you have dependencies then it's quite possible React is hanging on to a reference to previous functions because memoization typically means that we keep copies of old values to return in the event we get the same dependencies as given previously. The especially astute of you will notice that this means React also has to hang on to a reference to the dependencies for this equality check (which incidentally is probably happening anyway thanks to your closure, but it's something worth mentioning anyway).

**Comment by probablyup** [comment]
Oh interesting. Does useRef have the same issue?

**Comment by fabb** [comment]
No, `useRef` does not take a dependency array and therefore cannot do such memoizing.

**Comment by probablyup** [comment]
Definitely open to a PR against v5 switching over the use of `useMemo`!

**Comment by fabb** [comment]
On the other hand, v4 was using `memoize-one` exactly where v5 uses `useMemo`, so I‘m not sure this is the cause for the memory leaks of the OP.

**Comment by probablyup** [comment]
@fabb we're doing a lot more in StyleSheetManager for v5 using those hooks, it's worth some exploration.

**Comment by fabb** [comment]
Hm, the only additional thing I see memoized in `StyleSheetManager` is the `disableCSSOMInjection` dependency which should not change too often anyways I guess:

https://github.com/styled-components/styled-components/blob/canary/packages/styled-components/src/models/StyleSheetManager.js#L76
vs.
https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/models/StyleSheetManager.js#L30

**Comment by fabb** [comment]
Ah, I looked at the `canary` branch instead of the `v5` branch 🙈

**Comment by fabb** [comment]
Also very interesting: https://github.com/facebook/react/issues/15278

**Comment by fabb** [comment]
The `useMemo` suspect probably is a red herring, I wrote a unit test to verify if previous values are kept and could not verify that: [Codesandbox](https://codesandbox.io/s/usememo-test-ks1er?fontsize=14&hidenavigation=1&module=%2Fsrc%2F__tests__%2FuseMemo.test.tsx&theme=dark)

**Comment by chaffeqa** [comment]
FYI we've been using `5.0.0-rc.3` in prod and we definitely had memory leak issues w SSR

**Comment by probablyup** [comment]
If you can do some profiling to help figure it out, that would be great. We
don’t have any obvious leads at the moment.

**Comment by chaffeqa** [comment]
unfort we werent able to get great info... looks like the sourcemaps werent working.

Here's a sentry we were getting: https://sentry.io/share/issue/cb04aca756984f7a87c9ed8391083eb7/

in case you cant see that:

```
RangeError: Array buffer allocation failed
  ?, in new ArrayBuffer
  ?, in new Uint32Array
  File "app:///styled-components.cjs.js", line 417, col 25, in DefaultGroupedTag.insertRules
    this.groupSizes = new Uint32Array(newSize);
  File "app:///styled-components.cjs.js", line 654, col 19, in StyleSheet.insertRules
    this.getTag().insertRules(getGroupForId(id), rules);
  File "app:///styled-components.cjs.js", line 1644, col 16, in GlobalStyle.createStyles
    styleSheet.insertRules(id, id, css);
  File "app:///styled-components.cjs.js", line 1655, col 10, in GlobalStyle.renderStyles
    this.createStyles(instance, executionContext, styleSheet);
  File "app:///styled-components.cjs.js", line 1684, col 19, in GlobalStyleComponent
    globalStyle.renderStyles(instance, STATIC_EXECUTION_CONTEXT, styleSheet);
  File "app:///react-dom-server.node.production.min.js", line 36, col 498, in d
    '{snip} vedStateFromProps){var w=h.getDerivedStateFromProps.call(null,d.props,e.state);null!=w&&(e.state=k({},e.state,w))}}else if(O={},e=h(d.props,
  File "app:///react-dom-server.node.production.min.js", line 39, col 16, in Za
    typeof h)break;d(f,h)}return{child:a,context:b}}
  File "app:///react-dom-server.node.production.min.js", line 44, col 476, in a.b.render
    '{snip} turn N(f);if(this.previousWasTextNode)return"\x3c!-- --\x3e"+N(f);this.previousWasTextNode=!0;return N(f)}b=Za(a,b,this.threadID);a=b.child;
  File "app:///react-dom-server.node.production.min.js", line 44, col 18, in a.b.read
    w="";try{w+=this.render(l,e.context,e.domNamespace)}catch(t){if(null!=t&&"function"===typeof t.then)throw Error(r(294));throw t;}finally{}h. {snip}
  File "app:///react-dom-server.node.production.min.js", line 54, col 462, in renderToStaticMarkup
    '{snip} rToStaticMarkup:function(a){a=new $a(a,!0);try{return a.read(Infinity)}finally{a.destroy()}},renderToNodeStream:function(a){return new bb(a,
  File "app:///react-ssr.cjs.js", line 38, col 16, in process
    var html = renderFunction(_react.default.createElement(ApolloContext.Provider, {
  File "internal/process/task_queues.js", line 93, col 5, in processTicksAndRejections
  File "internal/process/task_queues.js", line 62, col 3, in runNextTicks
  File "internal/timers.js", line 412, col 9, in processImmediate
```

lemme know if that helps

**Comment by chaffeqa** [comment]
Our SSR looks like:

```tsx
export default class Document extends React.Component<Props, {}> {
  public static async getInitialProps({ assets, data, renderPage }: any) {
    const sheet = new ServerStyleSheet();
    try {
      const page = await renderPage((App: any) => (props: Props) => sheet.collectStyles(<App {...props} />));
      const styleTags = sheet.getStyleElement();
      return {
        assets, data, ...page, styleTags,
      };
    } finally {
      sheet.seal();
    }
  }

  public render() {
    const {
      css,
      styleTags,
    } = this.props as Props;
    return (
      <html>
        <head>
          {css && <style id="jss-server-side">{css}</style> || null}
          {styleTags}
        </head>
        <body>
        </body>
      </html>
    );
  }
}
```

**Comment by kitten** [comment]
This is most likely to happen when you create StyledComponents dynamically. There’s an explanation of this here: https://github.com/styled-components/styled-components/issues/2753#issuecomment-533073888

I suspect this is the same issue, but it’s hard to know for sure. We haven’t put in any warnings for this case yet, since it’s hard to pin down a heuristic for when this usage pattern comes up.

If you’re creating a lot of unique components inside your render method (calling `styled` repeatedly/dynamically in render or otherwise) you’ll eventually generate enough IDs to cause an overflow. This has also been an issue in v4 but wouldn’t lead to a catastrophic error, but instead just be very slow.

It may also be caused by calling `withComponent` dynamically or other ways of recreating a lot of `StyledComponent` instances.

Hope this is the issue; maybe you could monkey patch `styled` to see whether this is what’s going on?

**Comment by chaffeqa** [comment]
if it helps, we have been explicit to *not* create dynamic `styled` components in our application for that reason.  We rarely even pass in props and rely on class names to toggle behavior.

With that information I'd say it has to be something else?

**Comment by kitten** [comment]
@chaffeqa if I create a branch that explicitly errors on creation when the uint max limit is reached,  do you think you can pin down where it may be happening?

Since we’re seeing a growing amount of memory and eventual errors when that maximum length of our array buffer is reached, it’s probably safe to assume _something_ may be allocating these IDs

So maybe with an early error we’ll be able to investigate the stack trace?

**Comment by probablyup** [comment]
I think I know what it is... figuring out how to address it.

https://github.com/styled-components/styled-components/blob/dff9510b0b0c7da1dfd4f5794906ca7c63df4c28/packages/styled-components/src/constructors/createGlobalStyle.js#L22

This is fine client side but on the server I think this is incrementing unbounded, which eventually runs out of memory.

**Comment by probablyup** [comment]
Can y'all try out `styled-components@5.0.0-cgsmem` and let me know how it goes?

**Comment by brad-decker** [comment]
i'm going to give this a shot tomorrow and will report back asap.

**Comment by sammysaglam** [comment]
With rc2 & rc3 I was getting the same error as https://github.com/styled-components/styled-components/issues/2913#issuecomment-571259068

I tried the `@5.0.0-cgsmem` and seems to have stabilized (but it usually takes 12-24hrs for the crash to occur, so will post here if i see it again).

however `@5.0.0-cgsmem` seems to have swapping out the theme on `<ThemeProvider theme={theme}>` broken => theme changes, but some styles seem to not. not sure if related or if is a know issue. let me know if i can provide a running example that reproduces issue.

**Comment by jaslakson** [comment]
I will see what I can do to get a release going with `cgsmem` - I will have to test it on our staging servers and then push it to prod for a "real" test. Will report back with results when possible.

**Comment by probablyup** [comment]
There were no changes to theme propagation in that build. Might want to use
yarn resolutions to ensure the same exact version of the library is used
everywhere, etc

**Comment by jaslakson** [comment]
Was able to get the `vsmem` build into production this afternoon and so far, so good. We had previously seen errors after about an hour - release has been out for just about 2 hours and memory usage is completely flat. Will continue to monitor and post here if there is any change. For now it looks fixed. Thank you so much!

**Comment by probablyup** [comment]
Thanks @jaslakson! @chaffeqa @brad-decker have you folks been able to test out this fix build yet?

**Comment by brad-decker** [comment]
Building the application with the cgsmem now. I'll report back soon, sorry for the delay @probablyup

**Comment by brad-decker** [comment]
![image](https://user-images.githubusercontent.com/4448075/72278164-0c6fbe00-35f9-11ea-88ca-99b5d00952b9.png)

Great work, @probablyup -- definitely resolved. Not only is it resolved, but this is also *lower memory use on the server than version 4*

**Comment by probablyup** [comment]
![giggity](https://media1.tenor.com/images/2d092a38b027431aadf6041ec8f54e2a/tenor.gif?itemid=4084933)

**Comment by probablyup** [comment]
And with that, v5 is ready ^_^

**Comment by chaffeqa** [comment]
You guys rock! Especial thanks to @probablyup  and @brad-decker ... wish we coulda helped more but its the thick of NFL playoff time so we had to be reserved... cant wait to try this out again

**Comment by homoky** [comment]
I've run to the same issue with stable v5.

Hope this helps somehow:

```
RangeError: Source is too large
10:02:24 PM
    at Uint32Array.set (<anonymous>)
10:02:24 PM
    at DefaultGroupedTag.insertRules (/zeit/3e6ffca4/node_modules/styled-components/dist/styled-components.cjs.js:336:23)
10:02:24 PM
    at StyleSheet.insertRules (/zeit/3e6ffca4/node_modules/styled-components/dist/styled-components.cjs.js:579:19)
10:02:24 PM
    at ComponentStyle.generateAndInjectStyles (/zeit/3e6ffca4/node_modules/styled-components/dist/styled-components.cjs.js:1290:20)
10:02:24 PM
    at useInjectedStyle (/zeit/3e6ffca4/node_modules/styled-components/dist/styled-components.cjs.js:1463:120)
10:02:24 PM
    at useStyledComponentImpl (/zeit/3e6ffca4/node_modules/styled-components/dist/styled-components.cjs.js:1490:28)
10:02:24 PM
    at Object.Styled(Styled(styled.span)) [as render] (/zeit/3e6ffca4/node_modules/styled-components/dist/styled-components.cjs.js:1543:12)
10:02:24 PM
    at a.b.render (/zeit/3e6ffca4/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:46:105)
10:02:24 PM
    at a.b.read (/zeit/3e6ffca4/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
10:02:24 PM
    at renderToString (/zeit/3e6ffca4/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
10:02:24 PM
Error occurred prerendering page "/404.html" https://err.sh/zeit/next.js/prerender-error: RangeError: Source is too large
10:02:24 PM
    at Uint32Array.set (<anonymous>)
10:02:24 PM
    at DefaultGroupedTag.insertRules (/zeit/3e6ffca4/node_modules/styled-components/dist/styled-components.cjs.js:336:23)
10:02:24 PM
    at StyleSheet.insertRules (/zeit/3e6ffca4/node_modules/styled-components/dist/styled-components.cjs.js:579:19)
10:02:24 PM
    at ComponentStyle.generateAndInjectStyles (/zeit/3e6ffca4/node_modules/styled-components/dist/styled-components.cjs.js:1290:20)
10:02:24 PM
    at useInjectedStyle (/zeit/3e6ffca4/node_modules/styled-components/dist/styled-components.cjs.js:1463:120)
10:02:24 PM
    at useStyledComponentImpl (/zeit/3e6ffca4/node_modules/styled-components/dist/styled-components.cjs.js:1490:28)
10:02:24 PM
    at Object.Styled(Styled(styled.span)) [as render] (/zeit/3e6ffca4/node_modules/styled-components/dist/styled-components.cjs.js:1543:12)
10:02:24 PM
    at a.b.render (/zeit/3e6ffca4/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:46:105)
10:02:24 PM
    at a.b.read (/zeit/3e6ffca4/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:44:18)
10:02:24 PM
    at renderToString (/zeit/3e6ffca4/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:54:364)
10:02:25 PM
> Build error occurred
10:02:25 PM
Error: Export encountered errors
10:02:25 PM
    at _default (/zeit/3e6ffca4/node_modules/next/dist/export/index.js:19:788)
10:02:25 PM
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
10:02:25 PM
    at async build (/zeit/3e6ffca4/node_modules/next/dist/build/index.js:21:145)
10:02:25 PM
error Command failed with exit code 1.
10:02:25 PM
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
10:02:25 PM
Error: Exited with 1
10:02:25 PM
    at ChildProcess.child.on (/zeit/66bccc9681510b2b/.build-utils/.builder/node_modules/@now/next/dist/index.js:47095:24)
10:02:25 PM
    at emitTwo (events.js:126:13)
10:02:25 PM
    at ChildProcess.emit (events.js:214:7)
10:02:25 PM
    at maybeClose (internal/child_process.js:925:16)
10:02:25 PM
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

**Comment by brad-decker** [comment]
@homoky that's probably not he same issue and should be opened in a new issue report. We never received that error message, only a node out of memory error after so many requests from the loadbalance test.

**Comment by robbue** [comment]
@homoky We started receiving the same error on our Next.js setup after upgrading to v5. Did you resolve the issue?

**Comment by homoky** [comment]
> @homoky We started receiving the same error on our Next.js setup after upgrading to v5. Did you resolve the issue?

Hey @robbue,

we moved large codebase from CRA to Next, did a lot of refactoring and after that the error is not present anymore. But I have no clue what resolved the issue.

We only know about one "big" refactor that maybe have performance effect on Styled-components:

```
// This nested components in components

const Component = () => {

  const Container = styled(Box)`
    background: blue;
  `

  const Text = styled.span`
    color: red;
  `

  return <Container><Text>Hello Robbue</Text></Container>
  
}

// Styled components are outside component, I've somewhere reads it is better for performance, had no idea if this solved the issue

const Component = () => <Container><Text>Hello Robbue</Text></Container>;

const Container = styled(Box)`
    background: blue;
  `

const Text = styled.span`
    color: red;
  `
```

**Comment by fabb** [comment]
Yeah, never call `styled` from render functions.

**Comment by kitten** [comment]
@homoky im currently working on adding a warning for this, so people won’t accidentally run into that again https://github.com/styled-components/styled-components/pull/2998

**Comment by homoky** [comment]
Thanks, we had no clue it is anti-pattern.

**Comment by ivadimko** [comment]
We've faced the same issue with stable v5: `Source is too large`. You can see memory usage increased between deploys. After rolling back to v4 there is a stable memory utilization (04.02).
I can guarantee we don't have dynamically created SC, but we use dynamic loading feature in nextjs framework. 
![image](https://user-images.githubusercontent.com/29413892/73823412-d93bdb80-4800-11ea-94ab-a29fa56a4f66.png)

**Comment by robbue** [comment]
We did not call `styled` from render, but we used (one) `@import`, so after removing it and upgrading to styled-components@5.0.1, we have not experienced the error `RangeError: Source is too large`, yet.

We do however experience the memory leak as @ivadimko and https://github.com/zooniverse/front-end-monorepo/issues/1469 (and have for a long period) as displayed on this graph:
![Skjermbilde 2020-02-06 10 08 53](https://user-images.githubusercontent.com/1470041/73922289-2e432480-48c9-11ea-93d6-7f059f2f5301.png)
1 week selection. The drops are deploys.

We will look into https://github.com/styled-components/styled-components-website/issues/209 to see if that is a case for our project.

**Comment by madeinspace** [comment]
@robbue I'm having the same exact issue, did you get rid of that memory leak eventually?

**Comment by robbue** [comment]
> @robbue I'm having the same exact issue, did you get rid of that memory leak eventually?

No, but it got better after we removed `createGlobalStyle`. But we are still experiences memory leak, though its hard to say where the problems is (could be other packages then Next.js as well). And for now we are able to run with the current memory leak. It is not optimal, but the best solution for now. My issue is still open with people experience the same: https://github.com/styled-components/styled-components/issues/3022

**Memory usage over 18 days**
<img width="1011" alt="Skjermbilde 2020-05-05 10 16 01" src="https://user-images.githubusercontent.com/1470041/81047039-e75dce80-8eb9-11ea-8e97-be21ee9c4b7c.png">

**Gotchas**
- using the css helper when composing styling partials to be interpolated into a styled component (see https://github.com/styled-components/styled-components-website/issues/209)
- not to use @import inside `createGlobalStyle` or `createGlobalStyle` at all
- not dynamically create components

**Comment by probablyup** [comment]
@robbue thanks for posting your findings. Going to lock this since it's relating to an old build that has had many changes since that affect these performance patterns. 5.0.x has had a few releases related to memory leaks, so let's do a new issue with updated environment and setup etc if there continue to be problems.
