### ISSUE TITLE
Extend Style with different HTML tag (feature)

### ISSUE THREAD

**Issue by y-sumanth** [styled-components/styled-components#2914]
Is it possible to extend style and also change the tag.
Example:
```
const Container = styled.div`
    max-width: ...,
    ....,
`;

```
I want to extent with `footer` tag as,
```
const Footer = styled(Container).footer`
    ....
`;
```

basically, to extend only style of styled-component

**Comment by mikestopcontinues** [comment]
This should work...

```js
const  Footer = styled(Container).attrs({as: 'footer'})`
  ...
`;
```

**Comment by probablyup** [comment]
Correct, that's what the ["as" prop](https://www.styled-components.com/docs/api#as-polymorphic-prop) is for.
