### ISSUE TITLE
Styled not applied when fragment is excluded from initial render (typescript)

### ISSUE THREAD

**Issue by alsco77** [styled-components/styled-components#2915]
## Environment
 - OS: Linux 5.0 Pop!_OS 19.04
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 14.83 GB / 31.25 GB
 - Container: Yes
 - Shell: 5.0.3 - /bin/bash
## Binaries:
 - Node: 10.15.3 - ~/tooling/node-10.15.0/lib/node_modules/node/bin/node
 - Yarn: 1.17.3 - ~/tooling/node-10.15.0/lib/node_modules/node/bin/yarn
 - npm: 6.11.3 - ~/tooling/node-10.15.0/lib/node_modules/node/bin/npm

## Reproduction
I am using create-react-app with Typescript (.tsx) files. When I create a basic component like this and run, the styles do not get applied to the button. If I remove the timeout and just render the StyledButton.. it seems to work. Not sure if this is a usage issue or what

```
const StyledButton = styled.button`
  background: black;
`

function TestComponent(props) {
  const [x, setX] = useState(true)

  useEffect(() => {
    const timeout = setTimeout(() => {
      setX(false)
    }, 600)
    return () => {
      clearTimeout(timeout)
    }
  }, [])
  if (x) {
    return <>{'test'}</>
  }
  return <StyledButton>test</StyledButton>
}
```

## Steps to reproduce
Create a basic component with a conditionally rendered fragment like this

## Expected Behavior
Button to render with black background after 600ms

## Actual Behavior
Button has no colour

EDIT: Seems to only be an issue with Brave browser. Working fine in Chrome. Not sure why this would be the case as I imagined it to be a compile time issue..

**Comment by probablyup** [comment]
Seems fine for me in Chrome https://codesandbox.io/s/long-browser-nf1wv
