### ISSUE TITLE
Weird CSS nesting bug re: inline SVG + pseudo elements

### ISSUE THREAD

**Issue by zackphilipps** [styled-components/styled-components#2916]
## System:
 - OS: Windows 10 10.0.17763
 - CPU: (8) x64 Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
 - Memory: 16.21 GB / 31.58 GB
## Binaries:
 - Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
 - npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
## npmPackages:
 - babel-plugin-styled-components: ^1.10.6 => 1.10.6
 - styled-components: ^4.4.1 => 4.4.1

## Reproduction
Here is the beginning of a custom checkbox component, which is what alerted me to the issue. You can see that the `::before` pseudo-element is rendered on screen, but `::after` is not showing up. If you inspect the CSS generated by styled-components, you'll see why. (More details in "Actual Behavior" below.)
https://codesandbox.io/s/styled-components-base-bb48k

## Steps to reproduce
Attempt to use inline SVG in CSS in `::before` pseudo element and then add styles directly after it.

## Expected Behavior
Should work with no issues.

## Actual Behavior
styled-components treats all following CSS as being nested, i.e. instead of:

```scss
.foo::before {
  ...
}

.next {
  ...
}
```

you get:

```scss
.foo::before {
  ...
}

.foo::before .next {
  ...
}
```

**Comment by probablyup** [comment]
It looks to be the parenthesis that are the issue for some reason, if you do `.replace(/\(/g, '%28').replace(/\)/g, '%29')` on the encoded URL it works as expected. I suspect this is a stylis bug, it has a lot of open issues related to parens.

**Comment by probablyup** [comment]
I'm going to close this since it isn't solvable from our end. Feel free to open an issue in the stylis repo itself: https://github.com/thysultan/stylis.js/issues
