### ISSUE TITLE
Feature Request [prps]

### ISSUE THREAD

**Issue by alex-cory** [styled-components/styled-components#2918]
I've got an idea that I **almost** have working. Check out this [codesandbox](https://codesandbox.io/s/styled-components-prps-04423). The idea is this:

```jsx
import styled, { prps } from 'styled-components'

const GreenText = styled.div`
  color: ${prps.theme.colors.blue};
`
```

Basically, `prps.theme.colors.blue` -> `props => props.theme.colors.blue` via a js Proxy.

There's 2 problems I have left to solve.
1. There's a check when parsing the tagged template literal arguments where you check to see if each variable is a function, if so, pass it props. We would need to change this to identify if it's `prps`.
2. Right now, it's mutable, so I you can't use it in multiple places without overwriting each place.

**Comment by alex-cory** [comment]
@imbhargav5 what do you think?

**Comment by imbhargav5** [comment]
I am not familiar with Proxies as much 😅. So I don’t know how well it will work cross browser.

**Comment by probablyup** [comment]
They’re not able to be polyfilled unfortunately

**Comment by alex-cory** [comment]
So, I can make this a standalone library for this, but can I make a PR that would allow this lib to work here? As in, I need a fix for problem 1 above.

**Comment by alex-cory** [comment]
I just feel like this syntax looks so clean.

**Comment by probablyup** [comment]
It’s not something we can accept in core, sorry.

**Comment by alex-cory** [comment]
Just curious, but why not.

**Comment by probablyup** [comment]
Because it can’t be polyfilled and we follow React’s browser support matrix
which includes IE

**Comment by alex-cory** [comment]
Yeah, I'm talking about adjusting the part where you check `isFunction` to be `isFunctionOrProxy` that's it

**Comment by mxstbr** [comment]
You can achieve the same thing in userland with a similarly clean API without having to resort to proxies by using lodash's `_.get`:

```JS
import prop from 'my-lib'

const GreenText = styled.div`
  color: ${prop('theme.color.blue')};
`
```

Where `prop` returns a function directly, no need for us to change anything 👍

**Comment by alex-cory** [comment]
How is my solution a hack @mxstbr?

Also I mean this in the nicest way possible, but I think most people would agree that `prps.theme.color.blue` is much cleaner than `prop('theme.color.blue', '#0000FF')`.  I would actually prefer to do `props => props.theme.color.blue` over `prop('theme.color.blue', '#0000FF')`.
