### ISSUE TITLE
flexGrow is not a valid property in react-native

### ISSUE THREAD

**Issue by juvasquezg** [styled-components/styled-components#292]
Hi everybody,

Thank you!

## Version
1.1.2

## Reproduction
```js
const StyledView = styled.View`
  flex-direction: row;
  border-width: 1;
  justify-content: center;
  align-items: center;
  flex: 1;
  background-color: purple;
`
```

## Steps to reproduce
```js
<StyledView>
</StyledView>
```

## Actual Behavior

**flexGrow  is not a valid property.**

**Comment by nhducit** [comment]
React native use `flex: <number>` instead of `flexGrow: <number>`. I think we have to ignore transpile `flex` to `flexGrow` in react native.

**Comment by jacobp100** [comment]
flexGrow is an accepted property, and is [documented](https://facebook.github.io/react-native/docs/layout-props.html#flexgrow). What version of React Native are you using? And @mxstbr what’s the stance on older RN versions?

**Comment by mxstbr** [comment]
None yet, what do you think should it be?

**Comment by jacobp100** [comment]
Hard to say. There are a few inconsistencies with their CSS engine that are being fixed (border-radius in images). What do we do with the workarounds when they are fixed?

**Comment by mxstbr** [comment]
> Hard to say. There are a few inconsistencies with their CSS engine that are being fixed (border-radius in images). What do we do with the workarounds when they are fixed?

¯\_(ツ)_/¯ Can we just leave them in or will those break too?

**Comment by jacobp100** [comment]
You can leave them in, but then the shorthands won’t work.

**Comment by mxstbr** [comment]
Ugh that's annoying! I can't think of a good way to handle this 😕

**Comment by jacobp100** [comment]
I don’t suppose there’s a reliable way to get the RN version used? Look in its package.json or something?

**Comment by mxstbr** [comment]
I don't know, maybe ReactNative exposes the version used in some env variable?

**Comment by juvasquezg** [comment]
Hi everybody,

I use react-native 0.27.2. When I use StyleSheet with react-native I don't get an error...

```js
import { 
  StyleSheet,
  Text,
  TextInput,
  View,  
 } from 'react-native'

...

const styles = StyleSheet.create({
  Login: {
    flexDirection: 'row',
    borderWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
    flex: 1,
    backgroundColor: 'purple'
  }
})
```

**Comment by juvasquezg** [comment]
Hi,

Maybe it is the version 0.27.2 It is so old, I will update react-native version...

Thank you.

**Comment by jacobp100** [comment]
I think this is fixed, but feel free to reopen if it isn't!
