### ISSUE TITLE
font-feature-settings are not properly working with styled-components v5.0.0-rc.2

### ISSUE THREAD

**Issue by iamskok** [styled-components/styled-components#2920]
I use `createGlobalStyle` to include [`Inter var`](https://rsms.me/inter/) font and apply various `font-feature-settings` properties. With styled-component v4 everything works as expected, but after upgrading to `v5` `font-feature-settings` are behaving oddly.

```js
import { createGlobalStyle } from 'styled-components'
import { normalize } from 'polished'

export default createGlobalStyle`
  ${normalize()}

  @import url('https://rsms.me/inter/inter.css');

  html {
    font-family: ${({ theme }) => theme.fonts.defaultLegacy};
  }

  @supports (font-variation-settings: normal) {
    html {
      font-family: ${({ theme }) => theme.fonts.default};
      font-feature-settings: "tnum", "zero", "frac", "cpsp", "salt", "ss02";
    }
  }
`
```

## Screenshots

* [v4 screenshot](https://monosnap.com/file/sSjcQwPFjHmK35siF70HkwEpuYa3dq)
* [v5 screenshot](https://monosnap.com/file/EGOJ8aQLGkCI8hcQDeIdGU8ftXkFm3)

## Environment

```
## System:
 - OS: macOS Mojave 10.14.6
 - CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
 - Memory: 155.12 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 11.14.0 - ~/.nvm/versions/node/v11.14.0/bin/node
 - Yarn: 1.19.2 - ~/.nvm/versions/node/v11.14.0/bin/yarn
 - npm: 6.11.3 - ~/.nvm/versions/node/v11.14.0/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.10.6 => 1.10.6
 - styled-components: ^5.0.0-rc.2 => 5.0.0-rc.2
```

**Comment by andyngo** [comment]
@iamskok This seems like a bug with `@import` in `createGlobalStyle` as far as I'm aware of. Ran into this myself and there's an ongoing thread here about it: https://github.com/styled-components/styled-components/issues/2670

Also, if you look at the v4 vs v5 screenshots, you'll notice that everything after `@import` is not loaded correctly. Instead of loading Inter I believe the typeface in the v5 screenshot is San Francisco / `-apple-system` / `BlinkMacSystemFont`. I don't think this is a `font-feature-settings` issue.

**Comment by probablyup** [comment]
Any chance you could provide a reproduction codesandbox?

**Comment by xsigik** [comment]
I find out when I use "@supports" with v5, my global styles in dev build are missing, it may be related.

**Comment by probablyup** [comment]
Can you provide a reproduction codesandbox?

**Comment by robilars-amazon** [comment]
I was curious about this as well and made a codesandbox
https://codesandbox.io/s/nostalgic-sun-zi7lj

Does not seem to reproduce the bug.

**Comment by xsigik** [comment]
@probablyup finally, we made a reproduction #2946

**Comment by probablyup** [comment]
If it's the same bug as #2946, you can try out `styled-components@5.0.0-cgsmem` which includes the fix. It'll go out with rc4
