### ISSUE TITLE
[Feature Request] Release v5

### ISSUE THREAD

**Issue by Matelasse** [styled-components/styled-components#2922]
What's it being blocked by? Looks like everyone's happy with it

**Comment by HosseinAlipour** [comment]
I'm using v5 for a few weeks now and there are a lot of problems:
- StyleSheetManager component doesn't rerender on stylisPlugins prop change. (which I found out a few days ago)
- When RTL is enabled. It doesn't provide a way to `noflip` styles.  [issue](https://github.com/styled-components/styled-components/issues/2847) 
- Also, CSS shorthands don't get converted by RTL plugin. [issue](https://github.com/styled-components/styled-components/issues/2909)
I think this project needs more contributor.

**Comment by probablyup** [comment]
Hossein use a key prop on StyleSheetManager that you change when you want
to change the plugins

**Comment by probablyup** [comment]
I have a PR opened to stylis-rtl to fix the latter two issues. Looking into the first one as well.
