### ISSUE TITLE
React Native TextInput loses focus on call hook from useState

### ISSUE THREAD

**Issue by chervyakovru** [styled-components/styled-components#2925]
## Environment
react-native: "0.61.5",
 "styled-components": "4.4.1"

## Reproduction
Snack example: https://snack.expo.io/rkUHWjlRr

## Steps to reproduce
type something in styled TextInput

## Expected Behavior
Just plain typing

## Actual Behavior
lost focus

**Comment by probablyup** [comment]
The issue in your expo is that you're creating a styled component inside of the main render function (in the case of SFC, the whole function is the render function.) Here's the FAQ section on this: https://www.styled-components.com/docs/faqs#why-should-i-avoid-declaring-styled-components-in-the-render-method
