### ISSUE TITLE
Several instances of styled-components on the same application (microfrontends)

### ISSUE THREAD

**Issue by can-kayacan** [styled-components/styled-components#2927]
https://www.styled-components.com/docs/faqs#why-am-i-getting-a-warning-about-several-instances-of-module-on-the-page

I have already read this page. Basically the suggestion here is to use one styled-components for multiple applications. This is against what we want to achieve. We want to have the flexibility of using different libraries/versions for different applications (microfrontends). At the moment the only library causing an issue is styled-components. Is there by any chance a workaround to prevent misbehaviour of loading multiple styled-components in the same application?

**Comment by probablyup** [comment]
Not in the near term future, though it's something I want to spend time on after the v5 release. At the moment the easiest way to support your use case is to either do a "DLL bundle" including styled-components or to load it from CDN and configure your microfrontends to reference `window.styled` instead during bundling.
