### ISSUE TITLE
LICENSE file should be included in npm bundle

### ISSUE THREAD

**Issue by nappy** [styled-components/styled-components#2928]
The license text is currently not provided with the npm bundle.
In order to allow automation tools like `license-webpack-plugin` to pick it up, it should be included there.
Also the license states: The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
This includes the npm registry.

**Comment by probablyup** [comment]
We use the `license` package.json field which should be sufficient.

**Comment by nappy** [comment]
- No its not sufficient, the license requires the license text in all copies or substantial portions of the software, which an npm package definitely is.
- This is actually a regression, since you moved to monorepo structure.
- 90% of the packages I (indirectly) depend on already do it this way, so its the best practice.
- If you do not include the license text, how much sense make it to you to require it from your dependents which bundle/distribute that code?

**Comment by probablyup** [comment]
The MIT license is not modifiable without ceasing to be that license, so
stating we use it is legally sufficient without having to directly include
the text.

Feel free to submit a PR against the v5 branch if you feel strongly about it
