### ISSUE TITLE
Docs for using third party style libraries

### ISSUE THREAD

**Issue by declanelcocks** [styled-components/styled-components#293]
I'd just like to request some documentation or a heads up on how you would use `styled-components` with a UI library like Bootstrap, Material Design or something else which is often the case when starting to scaffold out your app.

After taking a look at your `react-boilerplate` project, I saw that you just imported `sanitize.css` and `global-styles.js` into the entry file and used these two imports as your app's starting point. I just wanted to check with you what your best practice would be with using this library with one of the UI libraries mentioned. Here is what I'm doing so far:

Entry point (`index.js`):
```javascript
import 'sanitize.css/sanitize.css';
import './styles/imported-styles.scss';
import './styles/global-styles';
```

`imported-styles.scss`:
```sass
$bootstrap-sass-asset-helper: true;
@import "~bootstrap-sass/assets/stylesheets/_bootstrap.scss";
```

`global-styles.js`:
```javascript
import { injectGlobal } from 'styled-components';

injectGlobal`
  body {
    margin: 0;
  }
`;
```

From here on in, I would just follow the standard `styled-components` practices/templates shown in the docs and in `react-boilerplate`. Is this the sort of setup you would recommend for using a UI library with `styled-components`?

**Comment by mxstbr** [comment]
Yes that sounds right! You can always attach more classes to `styled-components`:

```JS
const Button = styled.button``

<Button className="bootstrap-button" />
```

**Comment by declanelcocks** [comment]
Great, this is how I would've done it without `styled-components` so just wanted to double check 👍

**Comment by eric-burel** [comment]
The loading order of the style seems tricky though. I am working on a app using both `styled-components` and Bootstrap 4, and Bootstrap's styling override my component style, eventhough the contrary should happen.

Did someone had similar issues with third party libs ?

**Comment by GGAlanSmithee** [comment]
@eric-burel just a thought, but since styled-components doesn't inline styles, if the styles from bootstrap has a higher [specificity](https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity)

**Comment by garetmckinley** [comment]
@GGAlanSmithee I'm not sure about @eric-burel, but I have had similar issues, even when using an identical specificity. I don't have an example I can currently share, but I recall being left scratching my head. I think it has to do with the order that it applies `styled-components` classes to the element. I wish I had an example to share, if I face the same issue again before it's resolved I'll add it to this discussion. I just wanted to +1 this issue

**Comment by eric-burel** [comment]
Hi @GGAlanSmithee, they are of the same specificity in this case, this is really a load order issue (changing the position of the bootstrap import quickfixed it, eventhough the import is done in a completely different file).

The imports are called in the correct order by the application but the `<style>` tags order is different, there do not seems to be a understandable rule.

**Comment by alukach** [comment]
I do think it would be beneficial to have these steps explicitly mentioned in the documentation (likely in the Getting Started section) as I imagine many people wonder this same question.

**Comment by GGAlanSmithee** [comment]
@alukach see https://github.com/styled-components/styled-components-website/issues/187
