### ISSUE TITLE
styled copies propTypes from forwardRef component

### ISSUE THREAD

**Issue by TrevorBurnham** [styled-components/styled-components#2930]
## Environment

I'm able to reproduce in all styled-components versions from 4.3.0 up through 5.0.0.rc2.

## Reproduction

https://codesandbox.io/s/styled-components-copies-proptypes-from-forwardref-component-mh88i

## Steps to reproduce

1. Create a `forwardRef` component that has an `isRequired` entry in its `propTypes` that's satisfied by a corresponding `defaultProps` entry
2. Pass that component into `styled` and instantiate the styled component

## Expected Behavior

No prop type warnings should occur.

## Actual Behavior

React warns that the required prop is unsatisfied. This is because the `propTypes` from the `forwardRef` component are copied to the styled component, but the `defaultProps` are not.

---

In earlier versions of styled-components, the `propTypes` were not copied to the styled-component. Additionally, I don't see `propTypes` being copied from components that weren't created with `forwardRef`. So this strikes me as a very curious edge case.

**Comment by probablyup** [comment]
Fixing this just FYI. Here's a test build off a change to the v5 branch: https://codesandbox.io/s/styled-components-copies-proptypes-from-forwardref-component-ozv4h

**Comment by probablyup** [comment]
Closing as it's fixed in the v5 branch, thanks for reporting!

**Comment by TrevorBurnham** [comment]
Thanks for fixing! Any chance of backporting this change to the v4 branch?

**Comment by TrevorBurnham** [comment]
@probablyup ^ For context, we're trying to upgrade a large codebase from v3 to v5. Because v5 introduces breaking changes that v4 warns about, we're upgrading to v4 first and addressing console warnings. But this bug in v4 creates a lot of console noise for us, obscuring the important warnings. So, backporting this patch to v4 would help clear our upgrade path to v5!

**Comment by kmvan** [comment]
> Fixing this just FYI. Here's a test build off a change to the v5 branch: https://codesandbox.io/s/styled-components-copies-proptypes-from-forwardref-component-ozv4h

But what's the `props` type? Use `HTMLAttributes<HTMLDivElement>`?
```js
const ForwardRefComponent = React.forwardRef((props: ??<??>, ref) => (
```

**Comment by Hiuyi** [comment]
@probablyup Faced another issue use forwardRef with styled-component, server render classname not match in client render.

Envrionment:
Node v13.0.1
React v16.13.0
Styled-Components: v5.0.1

Error message:
Warning: Prop `className` did not match. Server: "StyledComponents__StyledLabel-n84ura-0 uhwhy item" Client: "StyledComponents__StyledLabel-n84ura-0 kAtygU item"
    in span (created by Label)
    in Label (created by StyledComponents__StyledLabel)
    in StyledComponents__StyledLabel (created by Label)
    in Label (created by ForwardRef)
    in ForwardRef (created by WithTheme(undefined))
    in WithTheme(undefined) (created by ForwardRef)
    in ForwardRef (created by NavBarTopItem)
    in a (created by NavBarTopItem)

Code: (NeptuneComp is a wrapper styled component)
const combineNeptuneStyledComp = NeptuneComp => (dataLayerTag) => {
    const DatalayerTagProxy = React.forwardRef(({ children, dataAttributes = {}, ...props }, ref) => (
        <NeptuneComp ref={ref} {...props} dataAttributes={{ ...dataAttributes, ...dataLayerTag }}>
            {children}
        </NeptuneComp>
    ));

    DatalayerTagProxy.propTypes = {
        children: PropTypes.any,
        dataAttributes: PropTypes.object,
        props: PropTypes.any
    };

    return DatalayerTagProxy;
};
