### ISSUE TITLE
Which composition method is being the fastest?

### ISSUE THREAD

**Issue by wintercounter** [styled-components/styled-components#2932]
I'd like to know which way of composition/usage is the fastest way. I couldn't find any relevant info this. I could untagle the codebase myself or make some test, but I think the core developers have the most experience on this and I'd like to ask their opinion about it.

We're building a somewhat similar solution as `styled-system` which relies on highly dynamic composition. There are more ways to do this:

## Template strings
```js
const Styled = styled.div`
    height: ${({ height }) => height}px;
`
```

## Style objects
```js
const Styled = styled.div(({height}) => {
    return {
        height: `${height}px`
    }
})
```

## String
```js
const Styled = styled.div(({height}) => {
    return `
        height: ${height}px;
    `
})
```

Let's assume I'm using also the babel-plugin to optimize further. Which option would be the fastest? In which way I'm helping the engine the most?

I understand these are mostly considered as micro-optimizations but I think on a bigger scale this can make a difference.

It also might be helpful for some to point out in the docs which way is the most optimal.

**Comment by probablyup** [comment]
Honestly they're all about the same and not relevant to the general performance of the whole. You can jsperf them if you'd like, but there shouldn't be a significant difference.
