### ISSUE TITLE
Help with project source - How can I invoke the CSS parser in isolation?

### ISSUE THREAD

**Issue by alshdavid** [styled-components/styled-components#2933]
I am digging through the source trying to understand how the CSS parser works and finding it a little challenging.

I'm not sure how the parsing logic works but I am essentially looking for an internal function which takes CSS and flattens/processes it like:

```typescript
import { parse } from './???'

const css = `
   div {
      &:before {
         content: 'Hello World';
      }
   }
`

const result = parse(css)
```

```css
// result
div:before {
   content: 'Hello World';
}
```

does that exist in that form, or where should I start looking to find this?

**Comment by mxstbr** [comment]
Here you go: https://github.com/thysultan/stylis.js
