### ISSUE TITLE
Psuedo-selector behavior differs when newlines present in selector in DOM

### ISSUE THREAD

**Issue by r4j4h** [styled-components/styled-components#2935]
# Bug: Psuedo-selector behavior differs when newlines present in selector in DOM

Important pieces:

- pseudo-selector is required to exhibit behavior
- newlines in selector (without commas) are required to exhibit behavior
- styled-component references work cleanly, but were removed to keep the example concise. See proof at end. [1]
- a Styled Component div that styles children is being used

## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`

```
root@fc813044d77f:/w/styled-components-bug# npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard
npx: installed 1 in 3.208s

*** Clipboard option removed - use clipboardy or clipboard-cli directly ***


## System:
 - OS: Linux 4.14 Debian GNU/Linux 9 (stretch) 9 (stretch)
 - CPU: (3) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
 - Memory: 1.19 GB / 7.79 GB
 - Container: Yes
 - Shell: 4.4.12 - /bin/bash
## Binaries:
 - Node: 11.14.0 - /usr/local/bin/node
 - Yarn: 1.15.2 - /usr/local/bin/yarn
 - npm: 6.7.0 - /usr/local/bin/npm
## npmPackages:
 - styled-components: ^4.4.1 => 4.4.1 
```

## Reproduction

Here is a codesandbox, note that it auto-formats the css which fixes the bug when it moves this test case's simple selector to one line because it fits. Copy/paste the relevant portion from the sample below to properly re-produce in codesandbox:

https://codesandbox.io/s/focused-glitter-uyiy4

Here's a near identical single-script vanilla node.js demo of how it is the nesting:

```
root@fc813044d77f:/w/styled-components-bug# cat index.js 
var {default: styled, ServerStyleSheet, StyleSheetManager } = require('styled-components');
var reactDOM = require('react-dom/server');
const { renderToString } = reactDOM;
const { createElement } = require('react');

const SomeStyledComponent = styled.div`
  color: red;
`;

const SoapNoteFormStyle = styled.div`

  .a:not(.b) .b .c {
    color: red;
  }


  .a:not(.b)
   .b
    .c {
    color: green;
  }

  .a .b .c {
    color: darkred;
  }


  .a
   .b
    .c {
    color: darkgreen;
  }


`;

console.log("rules:");
console.log(SoapNoteFormStyle.componentStyle.rules.join(''));


let sheet = new ServerStyleSheet();

let dummyInner = createElement("div", null, "Dummy");
let dummy = createElement(SoapNoteFormStyle, null, dummyInner);

try {
  const html = renderToString(
    createElement(StyleSheetManager, {sheet: sheet.instance}, dummy)  )
  const styleTags = sheet.getStyleTags() // or sheet.getStyleElement();

console.log("styles:");
console.log(styleTags);

} catch (error) {
  // handle error
  console.error(error)
} finally {
  sheet.seal()
}
```

### codesandbox

1. Visit sandbox (see above for URL)
2. Copy/paste the relevant portion from the sample above to fix formatter
3. Look at console output
4. Ctrl+f for "red" or "green" and look at corresponding sandbox's generated <style> block's contents

### Script

1. Run the above script
2. Copy and paste the CSS output inbetween `<style />` tags into a code formatter
3. Compare to the outputted and joined sheet strings

## Expected Behavior

I expect the output to not break.

## Actual Behavior

The pseudo-selector breaks things.

## Actual Result and Expected Result (I added this section)

```
root@fc813044d77f:/w/styled-components-bug# node index.js 
rules:


  .a:not(.b) .b .c {
    color: red;
  }


  .a:not(.b)
   .b
    .c {
    color: green;
  }

  .a .b .c {
    color: darkred;
  }


  .a
   .b
    .c {
    color: darkgreen;
  }



styles:
<style data-styled="jenUvT" data-styled-version="4.4.1">
/* sc-component-id: sc-bwzfXH */
.jenUvT{.a:not(.b) .b;} .jenUvT .a:not(.b) .b .c{color:red;} .jenUvT .c{color:green;} .jenUvT .a .b .c{color:darkred;} .jenUvT .a .b .c{color:darkgreen;}</style>
```

After formatting, this looks like:

```
/* sc-component-id: sc-bwzfXH */
.jenUvT {
. a: not(. b) . b;
}

.jenUvT .a:not(.b) .b .c {
    color: red;
}

.jenUvT .c {
    color: green;
}

.jenUvT .a .b .c {
    color: darkred;
}

.jenUvT .a .b .c {
    color: darkgreen;
}
```

Note how the first style is parsed successfully, but when used in the DOM is broken in the generated stylesheet.

Specifically:

```
.jenUvT {
. a: not(. b) . b;
}
```

Note also how it is not broken when all on one line, specifically:

```
.jenUvT .a .b .c {
    color: darkgreen;
}
```

I would expect the outputted stylesheet to look more like:

```
/* sc-component-id: sc-bwzfXH */
.jenUvT .a:not(.b) .b .c {
    color: red;
}

.jenUvT .a:not(.b) .b .c {
    color: green;
}

.jenUvT .a .b .c {
    color: darkred;
}

.jenUvT .a .b .c {
    color: darkgreen;
}
```

## Appendix

[1] Proof of styled-component references working cleanly:
```
/* sc-component-id: sc-bwzfXH */
.jZwJrr {
. a: not(. b) . b . sc-bdVaJa . test;
. a: not(. b) . b;
}

.jZwJrr .a .b .sc-bdVaJa.test .c {
    color: red;
}

.jZwJrr .a .b .sc-bdVaJa.test .c {
    color: green;
}

.jZwJrr .c {
    color: red;
}

.jZwJrr .a:not(.b) .b .sc-bdVaJa.test .c {
    color: green;
}

.jZwJrr .a .b .sc-bdVaJa.test .c {
    color: green;
}

.jZwJrr .a .b .sc-bdVaJa.test .c {
    color: red;
}

.jZwJrr .a:not(.b) .b .c {
    color: red;
}

.jZwJrr .c {
    color: green;
}
```

[2] Related Bug Reports:

- https://github.com/styled-components/styled-components/issues/2504

    - Forwarded to `stylis`. I do not think this issue is stylis' fault. See the output that parses correctly. Although it was removed, see also the proof of involving styled-components. Those work in the outputted style (as well as after "rules:" gets printed which I believe is post-stylis). I could be wrong here though. I think this has more to do with the div as styled component itself. I did not test it here, but I am curious how this would behavior around a global style element.

**Comment by r4j4h** [comment]
I forgot to  mention this in the post itself, but here are some related issues:

- https://github.com/styled-components/styled-components/issues/2504

    - Forwarded to `stylis`. I do not think this issue is stylis' fault. See the output that parses correctly. Although it was removed, see also the proof of involving styled-components. Those work in the outputted style. I could be wrong here though. I think this has more to do with the div as styled component itself. I did not test it here, but I am curious how this would behavior around a global style element.

**Comment by kitten** [comment]
This is likely an issue with how `stylis` perceives your input there. I believe the upgrade to `stylis@4` may fix this though once it's dropped into styled-components. For now, I'll go ahead and close this, since there's not much we can do to fix this on our end. But rest assured, you're not doing anything wrong, it's likely stylis that in v3 can't parse this.
