### ISSUE TITLE
Strange behaviour within bit.dev

### ISSUE THREAD

**Issue by luqezman** [styled-components/styled-components#2938]
## System:
 - OS: Windows 10 10.0.18362
 - CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
 - Memory: 1.75 GB / 7.97 GB
## Binaries:
 - Node: 12.13.1 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.19.2 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
 - npm: 6.12.1 - C:\Program Files\nodejs\npm.CMD
## npmPackages:
 - styled-components: ^4.4.1 => 4.4.1

## Steps to reproduce
Im using CRA + SC to configure theme and also I have bit components(each components has SC installed as dependency)

## Expected Behavior

I expect my bit components working together on local development without errors and each one having SC installed as dependency.

When I use without bit everything works like a charm.

## Actual Behavior

```
./src/components/typography/dist/node_modules/styled-components/dist/styled-components.browser.esm.js
  Line 143:64:   'SC_DISABLE_SPEEDY' is not defined                                     no-undef
  Line 1374:5:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1382:7:   Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1536:3:   Definition for rule 'flowtype-errors/show-errors' was not found        flowtype-errors/show-errors
  Line 1820:27:  'stream' is not defined                                                no-undef

Search for the keywords to learn more about each error.
```

**Comment by kitten** [comment]
I’m not sure why bit.dev is but these are purely linter warnings based on imports that are safe to use with Webpack, for example this one where we’re checking whether a global is defined: https://github.com/styled-components/styled-components/blob/921e14f7af063ea7518145860bac8135d79040d5/packages/styled-components/src/constants.js#L15

If you have a longer active on `node_modules` it’s probably advisable to disable it for all dependencies

**Comment by luqezman** [comment]
@kitten probably I need to import components without `dist`, I need to use tsx files instead of compiled files.

**Comment by probablyup** [comment]
Going to close as this is definitely a third-party issue and not something wrong with the library itself.
