### ISSUE TITLE
Overriding the theme via explicitly passing one from the props

### ISSUE THREAD

**Issue by gwmaster** [styled-components/styled-components#294]
Have a feature request  
=======================
overrideTheme
if i pass theme to component apply 'overrideTheme' no the 'redTheme'

## Reproduction
const overrideTheme = {
    main : 'yellow'
}           

           {/* All children of this component will be red */}
            <ThemeProvider theme={redTheme}>
                <div>
                    <Button>I'm red!</Button>
                    <Button theme={overrideTheme}>I'm yellow!</Button>
                </div>
            </ThemeProvider>

**Comment by gwmaster** [comment]
ok new ThemeProvider do the trick :)
 <ThemeProvider theme={newTheme}>
                <div>
                    <Button>I'm red!</Button>
                    <ThemeProvider theme={overrideTheme}>
                        <Button>I'm Yellow!</Button>
                    </ThemeProvider>
                </div>
            </ThemeProvider>

**Comment by mxstbr** [comment]
That's it, you got it! I think that the above should also work though, from an API perspective. What do you think @geelen?

**Comment by k15a** [comment]
Shouldn't it currently work?

IIRC the theme from ThemeProvider get's only taken when there isn't a prop called theme.
https://github.com/styled-components/styled-components/blob/master/src/models/StyledComponent.js#L66

**Comment by mxstbr** [comment]
I can replicate this doesn't work atm, we should fix this: http://www.webpackbin.com/EyiArbWmz

**Comment by k15a** [comment]
It's only working when you update the props:
http://www.webpackbin.com/EkAOUb-QG

The first button doesn't update because you need to publish the bugfix of the ThemeProvider^^

**Comment by mxstbr** [comment]
Fixed by the amazing @k15a! Will publish very soon!
