### ISSUE TITLE
Question about using 5.x rc

### ISSUE THREAD

**Issue by dimaqq** [styled-components/styled-components#2944]
According to npmjs.com, `5.0.0-rc.3` is the newest in the 5.x series:

<img width="697" alt="Screenshot 2020-01-06 at 10 41 55" src="https://user-images.githubusercontent.com/662249/71789938-2b0e0c00-3071-11ea-8e8a-ddca94aeb50a.png">

Then when I add that, yarn appears to use somewhat older version:
```
styled-components@^5.0.0-rc.3:
  version "5.0.0-regexrehydrate"
  resolved "https://registry.yarnpkg.com/styled-components/-/styled-components-5.0.0-regexrehydrate.tgz#897ced99abad29ce50fa507f5305ed8ae7543c90"
  integrity sha512-aq6kkk1CAdiOG6gUua2snWLn0BJYN+1wzNkBP1sLUv+5G5F6s+y2cBtOgTTIOyaTGIiAlQsFWJ4M2f+th8JsIQ==
  dependencies:
    "@babel/helper-module-imports" "^7.0.0"
    "@babel/traverse" "^7.4.5"
    "@emotion/is-prop-valid" "^0.8.3"
    "@emotion/stylis" "^0.8.4"
    "@emotion/unitless" "^0.7.4"
    babel-plugin-styled-components ">= 1"
    css-to-react-native "^3.0.0"
    shallowequal "^1.1.0"
    stylis-rule-sheet "^0.0.10"
    supports-color "^5.5.0"
```

I'm guessing it's because `rc` doesn't carry special meaning for `yarn` and `re[gex...]` is alphabetically after `rc`, isn't it?

I guess I ought to pin the exact version and re-pin on every rc update too?

Is there a cleaner way out?

**Comment by probablyup** [comment]
If you just use the "beta" tag in your package.json it should use the pinned verison

**Comment by dimaqq** [comment]
Yay it works! :) 
I don't quite understand how it works, but I guess YOLO ¯\_(ツ)_/¯
