### ISSUE TITLE
Trouble when adding a string with an inline function result as a property value

### ISSUE THREAD

**Issue by cbdeveloper** [styled-components/styled-components#2945]
## Environment

CodeSandbox

![image](https://user-images.githubusercontent.com/43407798/71813280-1cbff000-3071-11ea-89ae-c6f41a3dd5eb.png)

## Reproduction

https://codesandbox.io/s/frosty-hill-7h5kr

```
import React from "react";
import ReactDOM from "react-dom";
import styled from "styled-components";

const LS = {};

LS.Div1_DIV = styled.div`
  width: 50px;
  height: 50px;
  border: ${props => "2px solid " + (props.someBoolean ? "red" : "blue")};    /* WORKS */
  background-color: lightblue;
`;

LS.Div2_DIV = styled.div`
  width: 50px;
  height: 50px;
  border:  "2px solid " + ${props => props.someBoolean ? "red" : "blue"};    /* DOESN'T WORK */
  background-color: lightblue;
`;

function App() {
  const someBoolean = true;
  return (
    <React.Fragment>
      <LS.Div1_DIV someBoolean={someBoolean}>Div 1</LS.Div1_DIV>
      <LS.Div2_DIV someBoolean={someBoolean}>Div 2</LS.Div2_DIV>
    </React.Fragment>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

## Steps to reproduce

Just run the SandBox.

## Expected Behavior

Border would show on both cases.

![image](https://user-images.githubusercontent.com/43407798/71814145-788b7880-3073-11ea-8342-c36c04047fa6.png)

## Actual Behavior

Border only shows if you add the string part inside the inline function.

Shouldn't it work in both cases? Or am I missing something?

![image](https://user-images.githubusercontent.com/43407798/71814117-64e01200-3073-11ea-94fa-eee2b902a173.png)

**Comment by kevin940726** [comment]
When you run the following code

```js
LS.Div2_DIV = styled.div`
  width: 50px;
  height: 50px;
  border: "2px solid " + ${props => (props.someBoolean ? "red" : "blue")}; /* DOESN'T WORK */
  background-color: lightblue;
`;
```

It actually produce the following stylesheet.

```css
.fAKdiO {
  width: 50px;
  height: 50px;
  border: "2px solid " + red;
  background-color: lightblue;
}
```

Note the `"2px solid " + red` part, you are accidentally including js expression inside tagged template literals. Instead, you should do something like this.

```diff
 LS.Div2_DIV = styled.div`
   width: 50px;
   height: 50px;
-  border: "2px solid " + ${props => (props.someBoolean ? "red" : "blue")}; /* DOESN'T WORK */
+  border: 2px solid ${props => (props.someBoolean ? "red" : "blue")}; /* DOESN'T WORK */
   background-color: lightblue;
 `;
```

Which correctly output the expected stylesheet.

See more at [the tagged-template-literals doc](https://www.styled-components.com/docs/advanced#tagged-template-literals). Perhaps this issue should belong to stackoverflow though 🙂.
