### ISSUE TITLE
Client hydration breaks styles with nesting media or support queries v5.0.0-rc.3

### ISSUE THREAD

**Issue by Davidoseq** [styled-components/styled-components#2946]
## System:
 - OS: macOS 10.15.2
 - CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
 - Memory: 82.75 MB / 8.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 11.1.0 - ~/.nvm/versions/node/v11.1.0/bin/node
 - Yarn: 1.19.1 - /usr/local/bin/yarn
 - npm: 6.4.1 - ~/.nvm/versions/node/v11.1.0/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.10.6 => 1.10.6 
 - styled-components: 5.0.0-rc.3 => 5.0.0-rc.3 

## Reproduction
https://codesandbox.io/s/styled-components-v5-rc3-nesting-problem-dvmf3

## Steps to reproduce
Refresh inner codesandbox browser window. You will see breaking styles after client hydratation (style of `h1` is lost).

## Expected Behavior
Server and client styles should be the same.

## Actual Behavior
SSR will render page with the correct styles. After client is hydrated, all the styles that are below nested `@media` or `@supports` queries are removed. For an error to occur, the `@media` queries must be set smaller _(max-width: 300px)_ or larger _(min-width: 3000px)_ than the browser window.

**Comment by probablyup** [comment]
Looks like there's a missing closing brace in those nested media queries.

**Comment by Davidoseq** [comment]
> Looks like there's a missing closing brace in those nested media queries.

Thank you for the warning. I fixed the missing closing brace, but the bug still persisting.

**Comment by probablyup** [comment]
This will be fixed in the next rc, thanks! (in the meantime you can try out `styled-components@5.0.0-cgsmem` which includes the fix.)
