### ISSUE TITLE
SSR. wrong css priority using styled.css

### ISSUE THREAD

**Issue by ddalpange** [styled-components/styled-components#2950]
### System:
 - OS: macOS Mojave 10.14.6
 - CPU: (4) x64 Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz
 - Memory: 39.66 GB / 56.00 GB
 - Shell: 5.3 - /bin/zsh

### Binaries:
 - Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
 - Yarn: 1.17.3 - ~/Projects/class101/node_modules/.bin/yarn
 - npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm

## Reproduction

There are two buttons using styled.css.

ContainButton = ContainButton Css > CommonButtonCss 
AnchorButton = AnchorButtonCss > CommonButtonCss 

If render only ContainButton in server side. AnchorButton is broken in client side.

because CommonButtonCss is created in index.html(header css). (server side).
so CommonButtonCss priority is bigger than AnchorButtonCss priority.

how can I fix it?

you can check button '결제하기' here.

https://class101.net/products/t0xqIJItJNxhobu1MAjH/confirmOrder (o)
https://ssr.class101.net/products/t0xqIJItJNxhobu1MAjH/confirmOrder (x)

I'm using @class101/ui. 

## Steps to reproduce

1. use @class101/ui
2. render only ContainButton in server side. and render only AnchorButton in client side.
3. you can see ugly button :( 

## Expected Behavior

CommonButtonCss should have difference classNames for each components.

## Actual Behavior

CommonButtonCss should have same classNames for each components.

**Comment by probablyup** [comment]
You need to render the same component tree between SSR and client for things to work properly. Do any client-specific changes in a mount effect to ensure it happens after rehydration. React does not handle server vs client differences during hydration smoothly.
