### ISSUE TITLE
CSS class order is mixed up when I extend a conditional rendered component's style in SSR.

### ISSUE THREAD

**Issue by cheolee** [styled-components/styled-components#2952]
## Environment

```
## System:
 - OS: macOS Mojave 10.14.6
 - CPU: (12) x64 Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz
 - Memory: 12.55 GB / 32.00 GB
 - Shell: 2.7.1 - /usr/local/bin/fish
## Binaries:
 - Node: 12.14.0 - /usr/local/bin/node
 - Yarn: 1.12.3 - /usr/local/bin/yarn
 - npm: 6.13.4 - /usr/local/bin/npm
```

## Reproduction

I made a minimal reproducible example using razzle and nextjs.
https://github.com/cheolee/styled-components-ssr-order-issue

- AnchorOrBasicButton renders one of two components(AnchorButton, BasicButton) depending on `useAnchorTag` prop.
- StyledButton extends AnchorOrBasicButton.
- If the StyledButton that use BasicButton is rendered on the server side and later the StyledButton that use AnchorButton is rendered on the client side, the AnchorButton's style overrides the StyledButton's style.

### razzle example

1. Run project with `yarn start` and open localhost:3000.

2. Click `AnchorButtonPage` link.

3. AnchorButton will be red even though the color is specified.

### nextjs example

1. Run project with `yarn dev` and open localhost:3000.

2. Click `AnchorButtonPage` link.

3. AnchorButton will be red even though the color is specified.

## Expected Behavior

- `Yellow AnchorButton` should have yellow background-color as computed value
<img width="226" alt="image" src="https://user-images.githubusercontent.com/5275823/71929629-662d4e00-31dd-11ea-99a4-9bbc01e09eb8.png">

<img width="493" alt="image" src="https://user-images.githubusercontent.com/5275823/71929638-6af20200-31dd-11ea-899e-ea3cd690430d.png">

```
<a class="sc-iwsKbI ctruER sc-gZMcBi ciAlfw">Yellow AnchorButton</a>
```

```
<style data-styled="" data-styled-version="4.4.1">
/* sc-component-id: sc-iwsKbI */
.ctruER{background-color:red;}
/* sc-component-id: sc-gZMcBi */
.ciAlfw{background-color:yellow;}
/* sc-component-id: sc-gqjmRU */
.iRDvLn{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;}
/* sc-component-id: sc-bdVaJa */

/* sc-component-id: sc-bwzfXH */
.jQqDzw{background-color:red;}
/* sc-component-id: sc-htpNat */
.ixTnDd{background-color:yellow;}
/* sc-component-id: sc-bxivhb */
.cDFCAd{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;}
</style>
```

(If you reload page on the AnchorButtonPage, the AnchorButton will be have the expected style.)

## Actual Behavior
- `Yellow AnchorButton` is red because the `AnchorButton`'s style override the `StyledButton`'s style.

<img width="223" alt="image" src="https://user-images.githubusercontent.com/5275823/71929543-2b2b1a80-31dd-11ea-8ec2-2acce615003e.png">

<img width="495" alt="image" src="https://user-images.githubusercontent.com/5275823/71929485-10f13c80-31dd-11ea-9366-dca343df89ce.png">

```
<a class="AnchorOrBasicButton__AnchorButton-sc-45s1st-1 bKGOEd StyledButton-d4balg-0 bODuMQ">Yellow AnchorButton</a>
```

```
<style data-styled="" data-styled-version="4.4.1">
/* sc-component-id: AnchorOrBasicButton__BasicButton-sc-45s1st-0 */
.liXwYB{background-color:red;}
/* sc-component-id: StyledButton-d4balg-0 */
.dVxTbB{background-color:blue;}.bODuMQ{background-color:yellow;}
/* sc-component-id: sc-global-2077997936 */
html,body,#root{height:100%;}
/* sc-component-id: App__PageContainer-w3z3iu-0 */
.frUrmC{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;}
/* sc-component-id: AnchorOrBasicButton__AnchorButton-sc-45s1st-1 */
.bKGOEd{background-color:red;}
</style>
```

**Comment by kitten** [comment]
I’ve taken a quick look and I’m not quite sure yet which files to focus on and give a more thorough read.

However, have you tried the v5 RC version? It may actually just resolve this issue as it makes stronger and more solid guarantees around style ordering

**Comment by cheolee** [comment]
Thanks for the quick confirmation.
I tried with v5.0.0-rc.3 but unfortunately it still happens.


For additional explanation of the code,

https://github.com/cheolee/styled-components-ssr-order-issue/blob/master/nextjs/components/AnchorOrBasicButton.js
- AnchorOrBasicButton renders one of two components(AnchorButton, BasicButton) depending on useAnchorTag prop.
- Each button components have red color by default.

https://github.com/cheolee/styled-components-ssr-order-issue/blob/master/nextjs/components/StyledButton.js
- StyledButton extends AnchorOrBasicButton to specify color depending on prop.

https://github.com/cheolee/styled-components-ssr-order-issue/blob/master/nextjs/pages/index.js
- index page renders `<StyledButton color="blue" useAnchorTag={false}>`.
- StyledButton renders the AnchorOrBasicButton with blue color and AnchorOrBasicButton renders BasicButton.
- I'll call it `Blue BasicButton`.

https://github.com/cheolee/styled-components-ssr-order-issue/blob/master/nextjs/pages/anchor-button-page.js
- anchor-button-page renders `<StyledButton color="yellow" useAnchorTag={true}>`.
- StyledButton renders the AnchorOrBasicButton with yellow color and AnchorOrBasicButton renders AnchorButton.
- I'll call it `Yellow AnchorButton`.

If `Blue BasicButton` is rendered on the server-side and `Yellow AnchorButton` is rendered later on the client-side, Yellow AnchorButton will be red because the AnchorButton's style(red) override the StyledButton's style(yellow).

Conversely, if `Yellow AnchorButton` is rendered on the server side and `Blue BasicButton` is rendered on the client side, `Blue BasicButton` turns red.

**Comment by KevinOl** [comment]
I am also facing an issue with the CSS class ordering being messed up a bit. In my code I am using code splitting with @loadable/components though. I am not sure if it is related.

So what's the outcome of this?

**Comment by probablyup** [comment]
> I am using code splitting with @loadable/components though. I am not sure if it is related.

That's possible. If stuff is loading in at different times, that can affect the order CSS is injected in. My recommendation would be to use precedence-boosters (&& { }) around styles that might conflict with other components.

**Comment by probablyup** [comment]
@cheolee it sounds like you might actually be running into React hydration issues. My guess is if you look at dev tools the props and such will be right. React explicitly does not change HTML attributes during rehydration (which includes "class".) You need to render the same thing consistently on both server & client side, and then update to the desired style via `useEffect` on mount.

**Comment by KevinOl** [comment]
@probablyup 

Thanks for replying. Actually that's what I ended up doing and it worked.
