### ISSUE TITLE
Using the "as" prop with an intermediate React component doesn't apply styles correctly

### ISSUE THREAD

**Issue by erikshestopal** [styled-components/styled-components#2953]
I may be misunderstanding something (please correct me if I'm wrong!) but when I use an intermediate component (see example below) with the `as` polymorphic prop, the styles are not getting applied like I expect them to. The Code Sandbox illustrates the issue that I'm having. 

Thanks for your help. 

## Environment
```
## System:
 - OS: macOS Mojave 10.14.6
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 1.58 GB / 32.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
 - Yarn: 1.21.1 - ~/.yarn/bin/yarn
 - npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^4.0.0 => 4.4.0
```
## Reproduction
https://codesandbox.io/s/winter-sunset-26p65

## Steps to reproduce
```jsx
// base component
const StyledButton = styled.button`
  background: red;
  color: white;
  display: flex;
`;

// intermediate component
const Button = ({ children, ...rest }) => (
  <StyledButton {...rest}>{children}</StyledButton>
);

const Link = styled(Button)`
  font-size: 30px;
`;

export default function App() {
  return (
    <>
      <Link>Styling applied</Link>
      <Link as="a">Styling not applied using "as" prop</Link>
    </>
  );
}

```
## Expected Behavior
I expect the `Link` component with the `as="a"` prop to render the styles of the base component `StyledButton`

## Actual Behavior
My expectations are not met: the `Link` component with the `as` prop doesn't get the styles applied from `StyledButton`.

**Comment by probablyup** [comment]
You need to use “forwardedAs” and consume “as” inside your custom component

**Comment by erikshestopal** [comment]
@probablyup ah, that did it! thanks!
