### ISSUE TITLE
Restyling a component bugs when using `()`, e.g.: `url('<svg fill="rgba()" />')`

### ISSUE THREAD

**Issue by laurenskling** [styled-components/styled-components#2956]
## System:
 - OS: macOS Mojave 10.14.6
 - CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
 - Memory: 864.51 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 12.9.1 - /usr/local/bin/node
 - Yarn: 1.19.1 - ~/.yarn/bin/yarn
 - npm: 6.10.2 - /usr/local/bin/npm
 - Watchman: 4.7.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^4.4.1 => 4.4.1 

## Reproduction

https://codesandbox.io/s/styled-components-base-konoi

## Steps to reproduce
It's a combination of restyling the component (```styled(Title)`color: green`;```), using a child selector (```Title`span {}`;```), and using `()` in the styling rules of this selector. In my case, the `fill=` of the SVG. 

## Expected Behavior
I expect the _Title_ to get `color: green`

## Actual Behavior
the _span_ gets `color: green`

**Comment by probablyup** [comment]
This is an unfortunate bug in stylis regarding parenthesis handling. If you replace the parens inside the SVG with their URL-encoded counterparts, things work as expected: https://codesandbox.io/s/styled-components-base-7g0qo

**Comment by laurenskling** [comment]
Thanks for sharing. It's kind of sad we need to do this, but at least there's a fix.

**Comment by probablyup** [comment]
I agree. Thankfully it looks like the author of the lib is working on a new version that doesn’t have this issue.
