### ISSUE TITLE
Delay execution for styled component

### ISSUE THREAD

**Issue by dtuyenle** [styled-components/styled-components#2958]
In order to improve Time To Interactive and First CPU Idle 

Is there a way to delay the execution for styled component on client side ?

**Comment by probablyup** [comment]
Not at this time. Try v5 though, it's much faster!

**Comment by Sawan1994** [comment]
@probablyup v5 also doesn't seem to be fast in real projects. Plus, it seems to break applications that were created with v4.x. especially when using dynamic import in Next.js and when using typeof window outside useEffect.
