### ISSUE TITLE
Finding your div from browser in code [Best practice]

### ISSUE THREAD

**Issue by patsadow2** [styled-components/styled-components#2959]
Hello, I've problem that sometimes i spent a lot of time search for appropiated div when i have very granular components and there is a lot of components let say 1000.

Do you know some best practice to add some attributes to each component to find it easy in code from browsered html (chrome).

I was trying to use data-testid but it is a little bit weird that in some cases i don't see data-testid attribute in chrome  ? Any ideas what could be a problem ? Any other ideas how to solve the problem ?

**Comment by probablyup** [comment]
If you use the Babel plugin it’ll name the static css classes more nicely

**Comment by patsadow2** [comment]
i use styled components

**Comment by probablyup** [comment]
https://github.com/styled-components/babel-plugin-styled-components
