### ISSUE TITLE
Why doesn't this work: composition with existing classes

### ISSUE THREAD

**Issue by mschipperheyn** [styled-components/styled-components#296]
I'll just start with an example

	import React from 'react';
	import cx from 'classnames';

	export class NoBorderPanel extends React.Component {
		render() {
			return (
		  <div className={cx('panel', 'panel-trans')}>
			  {this.props.children}
		  </div>
			);
		}
	}

	const MarginPanel = styled(NoBorderPanel)`
	  margin-top: 10px;
	`;

	export class SomeClass extends React.Component {

		render(){
			return (
				<MarginPanel/>
			);
		};
	}

output:

	<div class="panel panel-trans">

	</div>

I would expect the MarginPanel to receive a custom class that applies the margin-top.

**Comment by k15a** [comment]
You need to pass the className by yourself:

```JS
import React from 'react';
import cx from 'classnames';

export class NoBorderPanel extends React.Component {
	render() {
		return (
	  <div className={cx('panel', 'panel-trans', this.props.className)}>
		  {this.props.children}
	  </div>
		);
	}
}


const MarginPanel = styled(NoBorderPanel)`
  margin-top: 10px;
`;

export class SomeClass extends React.Component {

	render(){
		return (
			<MarginPanel/>
		);
	};
}

````
