### ISSUE TITLE
Default theme for components without parent ThemeProvider

### ISSUE THREAD

**Issue by alexkrolick** [styled-components/styled-components#2960]
**Problem**: When you are using styled-components to create a component library that supports themes, the components require a ThemeProvider in the tree. This can be undesirable if the components are meant to be standalone, and would result in a breaking change if they currently do not require a parent component.

This is where the theme provider is set up:

https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/models/ThemeProvider.js#L15

```ts
export const ThemeContext: Context<Theme | void> = React.createContext();
```

Note that the context is created without a default value (`React.createContext(defaultValue)`), which would be used by any context consumers when they don't have a parent.

**Possible Solutions**

1. Create a library constructor module that re-exports the whole library scoped to a custom context: ```const {styled, ThemeProvider} = createStyledComponents(defaultTheme)```
2. Allow anything that subscribes to context to take a custom context reference as a prop, which could be set to a custom context that does have a default value. This is what Redux does for connected components.

**Comment by probablyup** [comment]
I don't think it's unreasonable to put in the docs for your component library that you need to add a `<ThemeProvider>`. You can also ship one from your library to make it easy.

It's pretty unlikely we'd support an API like the first solution. It's just too convoluted and would make it hard to do static optimizations via the babel plugin. The second one I suppose is possible... we already support passing a "theme" prop to styled components.

**Comment by eps1lon** [comment]
> I don't think it's unreasonable to put in the docs for your component library that you need to add a <ThemeProvider>. 

I don't think it's about whether it's unreasonable or not. Requiring a provider is another mistake one could make and that could be avoided if there was a way to  create a separate theming context for library styles with a sensible default value. That way we could set our own default value.

Right now styled-components assumes a single theme in the tree. If you'd use a 3rd party component library based on styled components and have your separate theme for in-house components you need to make sure these themes don't conflict.

`jss` has helpers to create a separate theming context: [createTheming](https://cssinjs.org/react-jss/?v=v10.1.1).

**Comment by rajuashok** [comment]
> > I don't think it's unreasonable to put in the docs for your component library that you need to add a .
> 
> I don't think it's about whether it's unreasonable or not. Requiring a provider is another mistake one could make and that could be avoided if there was a way to create a separate theming context for library styles with a sensible default value. That way we could set our own default value.
> 
> Right now styled-components assumes a single theme in the tree. If you'd use a 3rd party component library based on styled components and have your separate theme for in-house components you need to make sure these themes don't conflict.
> 
> `jss` has helpers to create a separate theming context: [createTheming](https://cssinjs.org/react-jss/?v=v10.1.1).


Hey @eps1lon did you figure out a solution for this? How are you creating a default theme for your component library? I'm also creating a component library and would like the library to work out of the box with a default theme (user doesn't have to provide a ThemeProvider).

**Comment by rajuashok** [comment]
Hmm, this is actually quite relevant: https://spectrum.chat/styled-components/help/theming-a-ui-library-using-themeprovider~8d3ce01a-d0e9-4b30-ab3d-319ada5fe877

**Comment by robertwbradford** [comment]
This also makes it hard to introduce theming to a large component library without requiring a major version bump in each component since they all now depend on a new `ThemeProvider` parent. I wish I could help contribute a solution but haven't been able to think of one yet...

**Comment by alexkrolick** [comment]
@robertwbradford that's exactly the use case / dilemma that prompted this issue

**Comment by robertwbradford** [comment]
Something that works but that I don't love:
```js
export const myDefaultTheme = {
  background: "dodgerblue",
  // ...
};

export function applyDefaultTheme({ theme = {}, ...props }) {
  // Since styled-components defaults the `theme` prop to an empty object
  // inside of the styled component if a ThemeProvider is not present,
  // we check against the number of keys.
  return {
    ...props,
    theme: Object.keys(theme).length === 0 ? myDefaultTheme : theme,
  };
}
```
Then in a component you could do one of two things:
```js
import { applyDefaultTheme } from "../somewhere";

const OneApproach = styled.div.attrs(applyDefaultTheme)`
  background: ${props => props.theme.background};
`
const AnotherApproach = styled.div`
  background: ${props => applyDefaultTheme(props).theme.background};
`
```
It's somewhat burdensome for authors, but it does allow existing library maintainers to implement theming in a backwards-compatible manner. I don't like that the `OneApproach` approach is kind of highjacking another feature.

Another thought I had was for something that could be implemented in styled-components as minor update:

```js
import styled from "styled-components";
import { myDefaultTheme } from "../somewhere";

const NeedsADefaultTheme = styled.withDefaultTheme(myDefaultTheme).div`
  background: ${props => props.theme.background};
`;
```
While it would still be great to only set the default theme in one place, I'm not seeing how that is possible in a backwards-compatible manner for styled-components. The `withDefaultTheme` method on the default export would still be a little tedious for authors, but it could be done as a minor update to styled-components. Some of the other helpers may also be able to support the default theme in a backwards-compatible manner:

```js
createGlobalStyle.withDefaultTheme(myDefaultTheme)``;
```
```js
withTheme(MyComponent, myDefaultTheme);
```
```js
import { ThemeConsumer } from 'styled-components'

export default class MyComponent extends React.Component {
  render() {
    return (
      <ThemeConsumer defaultTheme={myDefaultTheme}>
        {theme => <div>The theme color is {theme.color}.</div>}
      </ThemeConsumer>
    )
  }
}
```
@probablyup Just some thoughts on how it might be implemented in a backwards-compatible manner.

**Comment by sonhanguyen** [comment]
> I don't think it's unreasonable to put in the docs for your component library that you need to add a `<ThemeProvider>`.

@probablyup
A lot of people use theme to pass design tokens and don't necessarily need theming capability. We can have a debate about weather theme should be used that way but for those component libraries (that don't care about theme-ability), it feels weird that every single component can't work standalone and need a theme.

**Comment by httpete** [comment]
I had a similar issue developing a component-library in a monorepo. I wanted the typings to work for the components outside of the <ThemeProvider> independently, but also work underneath the ThemeProvider. 

The solution is to have an ambient delcaration styled.d.ts file inside your component-library [(just as the s-c docs show)](https://styled-components.com/docs/api#create-a-declarations-file) in addition to the same module declaration directly in the file from which you export your theme.  The external consumers will pick it up when they wrap their <ThemeProvider> and you get it inside the CL with the .d.ts.
