### ISSUE TITLE
CDN reference issue. Execution error

### ISSUE THREAD

**Issue by hdham1** [styled-components/styled-components#2961]
got below error while referencing cdn version:
 Cannot use 'in' operator to search for 'default' in undefined
being refered on a page as -
script crossorigin  src="https://unpkg.com/styled-components/dist/styled-components.min.js" ></script>

## Reproduction

https://codesandbox.io/s/styled-components-base-gc367

**Comment by probablyup** [comment]
You need to bring in react-is from CDN. It’s a new requirement for v5

**Comment by probablyup** [comment]
Example: https://codesandbox.io/s/styled-components-v5-from-cdn-qqu8m (see index file for script tags)
