### ISSUE TITLE
Allow themes to be associated to media queries 

### ISSUE THREAD

**Issue by mohsen1** [styled-components/styled-components#2963]
Dark Mode with SSR is broken in styled-components. Browsers have a way of picking the right styles based on user preference using media queries. Either with `media` attribute on `<link>` elements or using media queries in CSS files. As far as I know styled-component has no way of extracting CSS files so the only choice is to repeat our CSS once in default theme and once in dark theme but wrapped with a `@media` directive in generated `<style>` element. 

Currently it is suggested that we have a dark theme and decide if user prefers dark or light theme and then pass a proper theme to `<ThemeProvider>`. This breaks in the server where we don't know what user preference is. 

I'm suggesting that we extend the `<ThemeProvider />` in a way that it can accept multiple themes and each theme is associated with a media query. The resulting CSS will be sum of all generated CSS, each theme's generated CSS wrapped in its associated media query. 

### The `themes` prop on `<ThemeProvider />`

Instead of a single theme object, let there be a themes prop that accepts a map of media query to theme objects. The default theme property key can be a Symbol exported from styled-components module:

Example:

```ts
import { ThemeProvider, DEFAULT_KEY_SYMBOL } from 'styled-components'

<ThemeProvider themes={{
  [DEFAULT_KEY_SYMBOL]: {
    theme: {
      colors: { color: 'black', background : 'white' },
    },
  },
  dark: {
    theme: {
      colors: { color: 'white', background : 'black' },
    },
    media: "(prefers-color-scheme: dark)",
  }
}}>

</ThemeProvider>

```

* With this when calling `sheet.getStyleElement()` we will get both themes's CSS. 
* In client this will be unnecessary because we can use JavaScript `window.matchMedia` API to pick the right theme.
* In future if browsers send [User-Agent Client Hint](https://wicg.github.io/ua-client-hints/) to indicate dark mode preference (or any other media query) we can use that to pick a theme.
* Ideally styled-componetns should allow extracting CSS files and sending CSS with `<link>` elements which would avoid shipping unnecessary CSS 

Related https://github.com/styled-components/styled-components/issues/2880

**Comment by probablyup** [comment]
> With this when calling sheet.getStyleElement() we will get both themes's CSS.

Doable but rather expensive if the app has a large amount of styles & components. It's also likely there will be repeated, unnecessary CSS since isolating specific rules that use `theme` is not something we do. There will also probably be styling collisions depending on the implementation method since it would emit more classNames at the same specificity level for the same component.

> In client this will be unnecessary because we can use JavaScript window.matchMedia API to pick the right theme.

It's not quite this simple. Differences between SSR and client during rehydration causes all sorts of side effects and broken rendering since React doesn't reconcile rehydrated DOM attributes. We'd end up with a mount effect to switch the styles, which is exactly what I recommended in the linked issue.

Rather than this proposal, I can see a userland implementation that looks something like this:

```jsx
import { ThemeProvider } from 'styled-components'
import { DEFAULT_KEY_SYMBOL, MEDIA_KEY_SYMBOL } from 'userland-theming'

<ThemeProvider theme={{
    themes: {
        [DEFAULT_KEY_SYMBOL]: {
            color: 'black',
        },
        dark: {
            color: 'white',
            [MEDIA_KEY_SYMBOL]: "(prefers-color-scheme: dark)",
        }
    },
    otherThemeProperty: 'blah',
}}>
  ...
</ThemeProvider>
```

```jsx
import { createVariants } from 'userland-theming'

const DarkModeAwareLink = styled.a`
  text-underline: none;

  ${createVariants`
     color: ${p => p.theme.color /* maps to the active theme.color */};
  `}
`
```

And `createVariants` emits both sets of CSS to look like this:

```css
color: 'black';

@media (prefers-color-scheme: dark) {
  color: 'white';
}
```

So essentially you opt specific components into media-matching vs doing the switching at the theme level. This ensures only what is necessary is actually emitted.

**Comment by mohsen1** [comment]
In my own project I ended up using CSS variables for dark theme colors:

```ts
// defaultTheme.ts
export default {
  text: "var(--color-text)",
  bg: "var(--color-bg)"
}
```

```ts
// globalStyles.ts
export default createGlobalStyle`
  :root {
    --color:text: black;
    --color-bg: white;
   }
   @media (prefers-color-scheme: dark) {
      :root {
          --color:text: black;
          --color-bg: white;
       }
   }
`
```

**Comment by probablyup** [comment]
@mohsen1 yeah that definitely is a viable solution too for newer browsers

**Comment by kitten** [comment]
I think implementing something that automatically generates media queries is beyond the scope of this project, but interesting! I personally don't think that styled-components is at the right level of abstraction to achieve this, but it'd be interesting to explore this.
