### ISSUE TITLE
v5.0.0 attrs not being overwritten

### ISSUE THREAD

**Issue by LouiseReid** [styled-components/styled-components#2967]
This update breaks attrs being overwritten for input types.

I have this input component

```
export const Input = styled.input.attrs({
  type: "text"
})`
  ${formControl}
`;
```

which then gets overwritten in other instances with `type=number`.

This update doesn't respect the overwrite.

This is shown in this snapshot change where the only difference is moving from v4.3.2 to v5

```
          id="financeValue"
          name="financeValue"
          placeholder="eg. 1938"
        - type="number"
        + type="text"
```

## System:
 - OS: macOS Mojave 10.14.6
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
 - Memory: 20.82 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 12.13.0 - /usr/local/bin/node
 - npm: 6.12.0 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: 1.10.6 => 1.10.6
 - styled-components: 5.0.0 => 5.0.0

**Comment by oeduardoal** [comment]
See that https://styled-components.com/docs/basics#attaching-additional-props

**Comment by oeduardoal** [comment]
Now, this

```javascript
export const Input = styled.input.attrs(props => ({
  type: "text"
}))`
  ${formControl}
`;
```

**Comment by LouiseReid** [comment]
Thanks @oeduardoal, I assume you meant this as in your example props isn't being used 

```
export const Input = styled.input.attrs(props => ({
  type: props.type || "text"
}))`
  ${formControl}
`;
```

This however still has the same issue with the input never taking the alternate type

**Comment by tomasfrancisco** [comment]
I recognize the same issue here.
Additionally, the `as` prop is not overridden by 
```
attrs(props => ({
  as: props.as || "a"
}))
```
As `.attrs()` doesn't have `as` on it's typescript definitions.

**Comment by probablyup** [comment]
This was a bug that was fixed in v4 as well. The precedence order is as follows:

attrs > props > defaultProps

If you want to optionally use the passes prop in `attrs`, you'd want to use an attrs function and return the prop using whichever conditional logic you choose:

```jsx
styled.input.attrs(p => ({ type: p.type === 'number' ? p.type : 'text' })`
  color: red;
`
```

**Comment by tomasfrancisco** [comment]
It doesn't seem to work the same way for `as` prop.
Here's a reproduction of the behavior: https://codesandbox.io/s/xenodochial-wu-fx58w

**Comment by siddharthkp** [comment]
@tomasfrancisco @probablyup Same, can reproduce: https://codesandbox.io/s/purple-frost-dljjx?file=/src/App.tsx

The as prop isn't compossible after 1 level. repro ^

Can we re-open this issue?
