### ISSUE TITLE
Version 5.0.0 doesn't work properly with npm link

### ISSUE THREAD

**Issue by jhackett1** [styled-components/styled-components#2969]
I'm making a library of components that uses `styled-components`. I have styled components installed as a dependency in the app, but I'm using externals in `rollup` to make sure they don't get packaged up.

When I `npm link` a local version of the library so I can work on it, and install it in an example app, I get the warnings about "multiple versions of styled-components". This makes a proper dev workflow for making a React component npm package very difficult.

It works fine when I `npm install` normally, so I imagine this is something to do with how `npm link` works.

I would just remove `styled-components` from my library and list it as a peer dependency only, but I need it to make my library's storybook work.

I thought this was a Storybook issue for a while, until I saw that **the problem doesn't occur in some older versions of `styled-components`, such as 4.1.3.** Here's an issue I opened there: https://github.com/storybookjs/storybook/issues/9466

## Steps to reproduce

Make some styled components in one place, package it up and `npm link` it.

In an example app, install and import that package with `npm link [packagename]` and you should find the error. 

## Expected Behavior

I don't see any errors because `styled-components` is correctly removed from the built module like I'm specifying in my `rollup` config.

## Actual Behavior

Somehow `styled-components` is leaking out of my library anyway and getting mixed up with the version running in the main example app?

**Comment by probablyup** [comment]
`npm link` actually creates a second instance of the library for most bundlers because they treat a symlinked module as a separate library version. Check this article out: https://styled-components.com/docs/faqs#how-can-i-fix-issues-when-using-npm-link-or-yarn-link
