### ISSUE TITLE
Issue with material-ui TextField

### ISSUE THREAD

**Issue by wer32** [styled-components/styled-components#297]
Hi everbody,
I found issue with material-ui component http://www.material-ui.com/#/components/text-field

I created 

**TextFieldFullWidth.js**

```
import RaisedButton from "material-ui/RaisedButton";
import styled from "styled-components";

export default styled(RaisedButton)`
  width: 100%;
  margin-top: 10px;
`;
```

**LoginPage.js**

```
import React from 'react';
import TextField from 'material-ui/TextField';
import TextFieldFullWidth from '../../components/TextFieldFullWidth';

export default class Login extends React.PureComponent { // eslint-disable-line react/prefer-stateless-function
    doLogin(e) {
        debugger;
    }

    render() {
        return (
            <div>
                <TextField
                    ref="loginInput"
                    type="text"
                    name="j_username"
                />
                <TextFieldFullWidth 
                    ref="passwordField" 
                    type="password" 
                    name="j_password"
                />
                <RaisedButtonFullWidth 
                    onClick={this.doLogin.bind(this)}
                />
            </div>
        );
    }
}
```

when debugger breakpoint spops in doLogin then I see next scene in chrome debug
![clip2net_161208014413](https://cloud.githubusercontent.com/assets/262981/20990033/136e6928-bce8-11e6-922f-04a74bc1674a.png)

There is actually "222" value in passwordField TextField. 
I think the problem that StyledComponent is a wrapper above TextField and it is impossible to call method getValue().

So I see one workaround how to resolve this is get instance to wrapped TextField and call getValue().

Is it possible to do this? I haven't found any way to get wrapped element.

Can you also propose another way to resolve this situation?

**Comment by diegohaz** [comment]
Hey, @wer32. See if it helps you: https://github.com/styled-components/styled-components/issues/102#issuecomment-254475851

**Comment by wer32** [comment]
Perfect. @diegohaz Thank you!!
