### ISSUE TITLE
Freezes when calling server-side methods on the client-side in v5

### ISSUE THREAD

**Issue by donaldpipowitch** [styled-components/styled-components#2972]
### System:
 - OS: macOS 10.15.2
 - CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
 - Memory: 1.98 GB / 32.00 GB
 - Shell: 3.2.57 - /bin/bash
### Binaries:
 - Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
 - Yarn: 1.21.1 - ~/.yarn/bin/yarn
 - npm: 6.9.0 - ~/.nvm/versions/node/v10.16.0/bin/npm

## Reproduction

https://github.com/donaldpipowitch/styled-components-v5-bug

## Steps to reproduce

Inside the given repo run:

```
$ yarn add styled-components@^5.0.0
$ yarn start
# visit http://localhost:4200 - BROWSER FREEZES
```

## Expected Behavior

Works like v4. Everything is rendered correctly. You see _"If you see this, everything is working."_ in your app.

## Actual Behavior

Browser freezes. You see the loading state forever.

**Comment by probablyup** [comment]
You're using v4 in that project?

**Comment by danieldunderfelt** [comment]
I'm also seeing major freezes in an app where v4 worked flawlessly. It's when I ask it to render a lot of items, not sure if there is a specific style that it fails on. But the styles that it should render have many interpolations.

As it is now, I cannot upgrade to v5 as it is unusable.

**Comment by probablyup** [comment]
I'm sorry to hear that, without more info (ideally a reproduction or detailed Chrome devtools trace) there's really no way to help you.

**Comment by danieldunderfelt** [comment]
@probablyup while I can probably create a reproduction, there is already a reproduction in the  OP which I suspect is the same issue that I'm seeing. If that doesn't cover it I'll whip something up.

**Comment by probablyup** [comment]
A more minimal repro that didn't include TS would be helpful. There's a lot in that project.

**Comment by donaldpipowitch** [comment]
If TypeScript is a problem for the debugging process I'll try to remove it 👍

**Comment by donaldpipowitch** [comment]
@probablyup I removed TypeScript and other stuff. I also tested `v5.0.1`. Same results.

**Comment by kitten** [comment]
So I've looked into this and I'll have to check why this stopped working, but to have a preliminary finding: Your reproduction has a server-side component that's called client-side. Now that's not great and pretty much an anti-pattern from a React and styled-components standpoint. But I'm looking into why this has stopped working right now.

@danieldunderfelt It sounds like your issue is possibly unrelated. We can't tell because we don't have a reproduction, but creating your own issue with a reproduction would probably lead to some clarity.

**Comment by danieldunderfelt** [comment]
@kitten indeed, I don't have any server-side styled-components. I'll create a new issue and a reproduction!

**Comment by kitten** [comment]
@donaldpipowitch I've narrowed this down to malformed CSS that is generated by stylis that doesn't work well with our Rehydration code. Ironically a different method of rehydration would've worked well here but was scrapped, so it comes down to a regex that we'll need to fix.

If you don't mind, I'll open a separate issue that's more specific. I'll link it back to this one 🙌 

cc @probablyup

**Comment by kitten** [comment]
@danieldunderfelt So your bug may actually be related if you're seeing a freeze during rehydration after SSR and your SSR'd CSS includes a `/*!` comment.

**Comment by donaldpipowitch** [comment]
Thank you for looking into this 👍👋

**Comment by probablyup** [comment]
Could y'all give this build a try? `styled-components@5.0.1-revisedssr`

**Comment by donaldpipowitch** [comment]
> Could y'all give this build a try? `styled-components@5.0.1-revisedssr`

The error is gone with that build. 👍🥳

> Your reproduction has a server-side component that's called client-side. Now that's not great and pretty much an anti-pattern from a React and styled-components standpoint.

Thanks for the feedback. Can you point me to the exact component you think of...? I thought it was quite a common use case to prerender my components the way I did...?

> I'm not sure why you're not using a `css-loader` there though?

I'm pretty sure I ran into https://github.com/webpack-contrib/mini-css-extract-plugin/issues/73.
