### ISSUE TITLE
useTheme is undfined

### ISSUE THREAD

**Issue by vasilich6107** [styled-components/styled-components#2975]
I'm using `styled-components` with `react-native` 0.60.4

When I try

`import { useTheme } from 'styled-components';`

`useTheme` is undefined.

**Comment by kitten** [comment]
What version of styled-components are you using? It's likely older than expected.

Please follow our issue template, which does account for problems like this :) https://raw.githubusercontent.com/styled-components/styled-components/master/.github/ISSUE_TEMPLATE.md

**Comment by probablyup** [comment]
Actually `useTheme` was never added to the native export looks like... want to make a PR @vasilich6107?

**Comment by jladuval** [comment]
#2982 should fix this

**Comment by probablyup** [comment]
This is fixed in 5.0.1, thanks for reporting!
