### ISSUE TITLE
Dropdown in semantic ui can't be made of multiple selection type when wrapped with styled-components

### ISSUE THREAD

**Issue by NLSVTN** [styled-components/styled-components#2977]
Please, see `stackoverflow` thread. I posted the question on there, but it may be an issue with the `styled-components`:

https://stackoverflow.com/questions/59846128/dropdown-in-semantic-ui-cant-be-made-of-multiple-selection-type-when-wrapped-wi

System characteristics:

> ## System:
>  - OS: macOS Mojave 10.14.6
>  - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
>  - Memory: 75.88 MB / 16.00 GB
>  - Shell: 3.2.57 - /bin/sh
> ## Binaries:
>  - Node: 11.9.0 - ~/.nvm/versions/node/v11.9.0/bin/node
>  - npm: 6.5.0 - ~/.nvm/versions/node/v11.9.0/bin/npm
> ## npmPackages:
>  - babel-plugin-styled-components: ^1.5.1 => 1.5.1 
>  - styled-components: ^2.2.3 => 2.4.1

**Comment by probablyup** [comment]
Looks fine to me: https://codesandbox.io/s/trusting-mountain-imd28
