### ISSUE TITLE
CSS broken in v5 (only in production, not locally)

### ISSUE THREAD

**Issue by rathesDot** [styled-components/styled-components#2978]
## System:
 - OS: Linux 4.4 Ubuntu 16.04.3 LTS (Xenial Xerus)
 - CPU: (8) x64 Intel(R) Core(TM) i7-6700T CPU @ 2.80GHz
 - Memory: 18.21 GB / 31.86 GB
 - Container: Yes
 - Shell: 5.1.1 - /usr/bin/zsh
## Binaries:
 - Node: 13.5.0 - /usr/bin/node
 - Yarn: 1.3.2 - /mnt/c/Program Files (x86)/Yarn/bin/yarn
 - npm: 6.13.4 - /usr/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.10.6 => 1.10.6
 - styled-components: ^5.0.0 => 5.0.0

## Reproduction

You can find the issue when checking out this branch: https://github.com/rathesDot/rathes.me/pull/229

The deployed version of it: https://deploy-preview-229--dreamy-brahmagupta-b6f0be.netlify.com/about

Apparently, some CSS classes are getting mixed up in v5 and only in production. If I downgrade to 4.4.1 (and remove the `useTheme()` hook), then it works as expected

## Expected Behavior

It should look like this (Screenshot from dev environment)

![2020-01-21](https://user-images.githubusercontent.com/6367520/72833988-3758b280-3c88-11ea-99e7-0ed9b3898e96.png)

## Actual Behavior

It looks like this (production)

![2020-01-21 (1)](https://user-images.githubusercontent.com/6367520/72833964-2b6cf080-3c88-11ea-97b7-e26a745da4dd.png)

If I check the code, I see that the class `crxDCE` with styles for the navigation is added to other elements as well.

So the styles generated for 

```js
<Box display="flex" alignItems="center" element="nav" />
```
 are also applied for 

```js
<Box {...props} /> // props is empty here
```

and

```js
<Box element="ul" />
```

Since I am not super familiar with Styled Components it could also be that my `Box` component is just broken.

```js
const Box = ({
  alignItems,
  backgroundColor,
  backgroundTint = "default",
  children,
  display,
  element,
  flexDirection,
  justifyContent,
  textColor,
  textTint = "default",
  ...props
}) => {
  const Element = styled(element || "div")`
    ${props =>
      textColor
        ? `color: ${props.theme.colors[textColor][textTint]};`
        : undefined}
    ${props =>
      backgroundColor
        ? `background-color: ${props.theme.colors[backgroundColor][backgroundTint]};`
        : undefined}
    display: ${display ? `${display};` : "block"};
    ${flexDirection ? `flex-direction: ${flexDirection}` : undefined};
    ${justifyContent ? `justify-content: ${justifyContent}` : undefined};
    ${alignItems ? `align-items: ${alignItems}` : undefined};
  `

  return <Element {...props}>{children}</Element>
}
```

**Comment by rathesDot** [comment]
Looks like this last commit fixed it:
https://github.com/rathesDot/rathes.me/pull/229/commits/01f4301831755a605701f82a91660e1f1e3ff9d7

So changing from 

```js
display: ${display ? `${display};` : "block"};
```
to
```js
display: ${display ? `${display};` : undefined};
```

Can anybody explain to me what is wrong with the first definition?

**Comment by kitten** [comment]
Creating a `StyledComponent` in another `render` method / function component is not allowed, so this will always lead to unexpected behaviour :) We're working on more warnings once we find a reliable way to detect this.

If you're looking to use props to style your component differently then please resort to using function interpolations: https://styled-components.com/docs/basics#adapting-based-on-props

**Comment by rathesDot** [comment]
> Creating a StyledComponent in another render method/function component is not allowed

Alright, this is the main point that I missed. That means I might have more unexpected behaviour that I just didn't find yet.

Thanks for your support @kitten!

**Comment by rathesDot** [comment]
Moving all StyledComponents out of the render function resolved the issue! Thanks for the help!
