### ISSUE TITLE
styled-components v5 adds multiple unused classes to elements

### ISSUE THREAD

**Issue by bennetthardwick** [styled-components/styled-components#2980]
## Environment

Code sandbox

## Reproduction

https://codesandbox.io/s/romantic-rubin-jibhw

## Steps to reproduce
1. Create styled component
2. Create second styled component inheriting from first

## Expected Behavior
Rendered element has one class

## Actual Behavior
Rendered element has three classes, with only one class in `<style>`.

Rendered output looks like so:
```html
<style>
.cOXgHl { 
  background:red;
  width:100%;
  height:100%;
}
</style>
<div class="sc-AykKC sc-AykKD cOXgHl"></div>
```

This behaviour breaks [jest-styled-components](https://github.com/styled-components/jest-styled-components) since the two unused classes don't get swapped for `.cX`

**Comment by probablyup** [comment]
Those are static class names used for component selector targeting. It’s expected.

**Comment by bennetthardwick** [comment]
Ah okay, it seems this is already being tracked on jest-styled-components as well: styled-components/jest-styled-components#276. Thanks!
