### ISSUE TITLE
Why is it required to use peerDependencies for library authors?

### ISSUE THREAD

**Issue by zzarcon** [styled-components/styled-components#2981]
Hi There! 

First of all, thanks so for the library, I have been using it over 3 years ❤️.

As I'm mostly using it for libraries, rather than in an app, I see myself having to declare styled-components as peerDependency, as defined in [I am a library author should I bundle styled-components with my library](https://styled-components.com/docs/faqs#i-am-a-library-author-should-i-bundle-styledcomponents-with-my-library).

This has caused quite some pain to the consumers of my components, due to them having to be on the same major version of styled-components as my components are.  

My question here, why is this the case? To my understanding, the styled-components contract it's different than the React contract is; aka, if you are a React library author and a consumer uses your component, it has to be on the same version since the consumer is instantiating your component, typically by using `ReactDOM.render`. But with styled-components, there is no such thing happening, or maybe I'm just ignorant about it :).

I have seen other css-in-js libraries not having this limitation and I was wondering why is it happening here.

Thanks!

**Comment by probablyup** [comment]
styled-components is a singleton library like React because it has a runtime (see our stylesheet implementation), that's why we enforce using the same version across the stack
