### ISSUE TITLE
Dynamic styles with css are overridden

### ISSUE THREAD

**Issue by javialon26** [styled-components/styled-components#2984]
## Environment

```
## System:
 - OS: macOS 10.15.2
 - CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
 - Memory: 39.75 MB / 8.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 10.16.0 - /usr/local/bin/node
 - Yarn: 1.17.3 - /usr/local/bin/yarn
 - npm: 6.9.0 - /usr/local/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.10.6 => 1.10.6 
 - styled-components: ^5.0.0 => 5.0.0 
```

## Reproduction

https://codesandbox.io/s/react-example-v3xl0?fontsize=14&hidenavigation=1&theme=dark

## Expected Behavior
Each button must have a unique class with unique styles.

## Actual Behavior
Now each button has a unique class but dynamic styles are overridden, I think the primary button must have a class without background and color overridden, only with the styles of this class.

I don't know if this is the correct behaviour but in the home page of styled component this works different, see the GitHub and Documentation button (https://styled-components.com/), the Github button has a class with uniques styles without an override.

**Comment by kitten** [comment]
This seems to be working as expected, or is this not what you expect?

Can you go into more detail on what you're looking for please? :)

<img width="300" alt="Screenshot 2020-01-23 at 20 25 15" src="https://user-images.githubusercontent.com/2041385/73020957-8cc6c800-3e1e-11ea-9faf-40e92144b5cf.png">

**Comment by javialon26** [comment]
@kitten The blue button has these styles applied:

```
.fHQyBW {
    display: inline-block;
    border-radius: 3px;
    padding: 0.5rem 0;
    margin: 0.5rem 1rem;
    width: 11rem;
    background: blue;
    color: white;
    border: 2px solid white;
```

and the red one:

```
.eeYwJU {
    display: inline-block;
    border-radius: 3px;
    padding: 0.5rem 0;
    margin: 0.5rem 1rem;
    width: 11rem;
    background: blue;
    color: white;
    border: 2px solid white;
    background: red;
    color: yellow;
```

I think the eeYwJU class must have only one background and one color. In this case, background: red and color: yellow.

Thank you!

**Comment by kitten** [comment]
That’s not how styled-components works, at least right now. You should try treating it’s output as an implementation detail right now.

Basically splitting dynamic and static output is not trivial and during SSR it’s mostly gripped away so we deprioritised previous investigation work to address this :)
