### ISSUE TITLE
<video> tag does not working properly with SC

### ISSUE THREAD

**Issue by luiz504** [styled-components/styled-components#2988]
Sc version: 4.4.1 
Bug report - >  using the tag video throw the SC the attribute  *disablePictureInPicture* does not work.

export const Player = styled.video``;

<Player
      id="video-viewer"
      controls
      height={files.original.height}
      width={files.original.width}
      disablePictureInPicture
    >.... 

using the pure HTML tag video its work fine.

**Comment by probablyup** [comment]
It needs to be added here: https://github.com/emotion-js/emotion/blob/master/packages/is-prop-valid/src/props.js
