### ISSUE TITLE
Support for all HTML element names using Proxies.

### ISSUE THREAD

**Issue by samholmes** [styled-components/styled-components#2992]
The issue arrises when a developer wants to use `styled.content` in order to create a styled `<content>` element. This element name is not included in [domElements.js](https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/utils/domElements.js) so therefore it'll throw an error if attempted by a developer. The only solution is:

```jsx
const Content = styled(({ className, children }) => (
	<content className={className}>{children}</content>
))`
	padding: 1em;
	flex: 1 0 auto; // Pushes footer to bottom
	background: #fff;
`
```

I'll add commentary that this is ugly AF.

 I understand that a set of domElements is supported and that's that. But, a better developer experience would allow for all current and future elements to be supported. So an idea is to use [Proxies](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) to allow for any domElement to be supported. I have yet to do the research to figure out how this could be implemented, but I'm sure it can be done. The question is whether such a PR would be accepted or considered for the project? Does it not align with project guidelines? Does adding proxies remove certain platform support or could Proxies be easily shimmed?

Thanks for reading. Look forward to discussing this suggestion/feature request.

**Comment by probablyup** [comment]
Definitely something we'd like to do eventually. Unfortunately IE11 is still a support target and you can't really polyfill ES6 Proxies.

**Comment by probablyup** [comment]
What you can do in the meantime is this: 

```js
styled('content')`some css`
```

**Comment by samholmes** [comment]
Thanks for your replies @probablyup.

Is there a reason why 'content' is omitted from the domElement.js exported array?

**Comment by probablyup** [comment]
Anything that’s not in there was also not in the former ReactDOMFactories
file (from React before v16) that’s where it was copied from
