### ISSUE TITLE
Low limit of groups throws error (around 5888)

### ISSUE THREAD

**Issue by Ketler13** [styled-components/styled-components#2994]
## System:
 - OS: macOS Mojave 10.14.6
 - CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
 - Memory: 68.19 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 10.16.2 - ~/.nvm/versions/node/v10.16.2/bin/node
 - Yarn: 1.19.1 - /usr/local/bin/yarn
 - npm: 6.13.1 - ~/.nvm/versions/node/v10.16.2/bin/npm
## npmPackages:
 - styled-components: ^5.0.0 => 5.0.0 

## Reproduction
Please, take a look at created repo for this issue:
https://github.com/Ketler13/styled-components-test/blob/master/README.md

Here is _app.js component example:
```
class MyApp extends App {
  static async getInitialProps() {
    if (!isBrowser()) {
      try {
        await getDataFromTree(
          <GlobalStyle theme={{}} />,
          {}
        );
      } catch (error) {
        console.error('Error while running `getDataFromTree`', error);
      }

      if (!process.browser) {
        Head.rewind();
      }
    }
    return {};
  }

  render() {
    const { Component } = this.props;
    return (
      <Container>
        <Head>
          <title>Test Component</title>
          <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        </Head>
        <ThemeProvider theme={{}}>
          <GlobalStyle theme={{}} />
          <Component />
        </ThemeProvider>
      </Container>
    );
  }
}
```
GlobalStyle component is run twice. First - when getting data for apollo in getDataFromTree, second - in render. **I understand** that current problem is caused by one redundant instance of GlobalStyle, but couldn't this issue be reproduced under more real conditions?

## Steps to reproduce
Preconditions: next.js + styled-components + react-apollo.

Latest code of styled-components(5.0 version) is placed in vendor/styled/components. There are a few additional console.logs. This file is taken from the styled-components/dist/styled-components.cjs.js.

This problem is related to a coommit https://github.com/styled-components/styled-components/commit/aca9186920dd4adddb44b76063b75ab1147b480a . There was new counter mechanism introduced to improve SSR handling of multiple instances of global styles components. But under some conditions this mechanism can be broken.

There are 2 logs added: 1 - to detect size of Uint32Array created for groups https://github.com/styled-components/styled-components/blob/147b0e9a1f10786551b13fd27452fcd5c678d5e0/packages/styled-components/src/sheet/GroupedTag.js#L41
2 - to detect istance counter value https://github.com/styled-components/styled-components/blob/147b0e9a1f10786551b13fd27452fcd5c678d5e0/packages/styled-components/src/constructors/createGlobalStyle.js#L31

To reproduse issue, please install all modules and run npm run dev. When server is started, please make big number of requests to index page. Script for loading the server from terminal for ((i=1;i<=5000;i++)); do curl -v --header "Connection: keep-alive" "localhost:3000"; done

You will see incrementing of global style instance number. This is used in registering new id of the group
https://github.com/styled-components/styled-components/blob/147b0e9a1f10786551b13fd27452fcd5c678d5e0/packages/styled-components/src/models/GlobalStyle.js#L45

Then this id will be passed to the GroupIDAllocator and if counter is incremented on each request - created id will never be found in the registry and total groups counter will be increased https://github.com/styled-components/styled-components/blob/147b0e9a1f10786551b13fd27452fcd5c678d5e0/packages/styled-components/src/sheet/GroupIDAllocator.js#L18

Then this counter is used when new rules inserted -
https://github.com/styled-components/styled-components/blob/147b0e9a1f10786551b13fd27452fcd5c678d5e0/packages/styled-components/src/sheet/Sheet.js#L94

When if condition (https://github.com/styled-components/styled-components/blob/147b0e9a1f10786551b13fd27452fcd5c678d5e0/packages/styled-components/src/sheet/GroupedTag.js#L36) is satisfied, new Uint32Array is created https://github.com/styled-components/styled-components/blob/147b0e9a1f10786551b13fd27452fcd5c678d5e0/packages/styled-components/src/sheet/GroupedTag.js#L39

This bitwise operation
```const newSize = BASE_SIZE << ((group / BASE_SIZE) | 0);```
 will return next results under such conditions: 
- When group equals 5362 (5632 requests to the server), newSize will be 1073741824
- When group equals 5888 (5632 requests to the server), newSize will be -2147483648 (Range error comes).

## Expected Behavior
No huge memory consumption

## Actual Behavior
Significant memory consumption (~1-2 GB)

**Comment by kitten** [comment]
First of all, don't use global styles without having a `ServerStyleSheet`. This will indeed cause a leak that isn't fixable on our end. Simply leave it out in `getDataFromTree` or wrap your element there with a `ServerStyleSheet` as well.

The other issue in here, the overflow of available groups, is something I've seen before. I think it's two fold. Our limit of groups is accidentally too low, and we're not throwing a great error if we reach this limit. I've got a fix for this incoming.

I'll rename your issue to reflect the second issue, since the first issue is a usage error :)

**Comment by kitten** [comment]
@Ketler13 You should be able to test the fix out from the test version we've just published as a prerelease :) https://github.com/styled-components/styled-components/pull/2996#issuecomment-580361308
