### ISSUE TITLE
No styles applied in production app unless speedy mode is disabled

### ISSUE THREAD

**Issue by jordyvandomselaar** [styled-components/styled-components#2995]
## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`

## System:
 - OS: macOS Mojave 10.14.6
 - CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
 - Memory: 47.49 MB / 8.00 GB
 - Shell: 3.0.2 - /usr/local/bin/fish
## Binaries:
 - Node: 13.6.0 - ~/.nvm/versions/node/v13.6.0/bin/node
 - npm: 6.13.4 - ~/.nvm/versions/node/v13.6.0/bin/npm
## npmPackages:
 - styled-components: ^5.0.0 => 5.0.0 

## Reproduction

I've updated styled-components from 3.4.2 to 5.0.0 and for some reason when running `npm build` there are no styles. The elements do get `SC-*` classes but no styling is applied.

When adding `REACT_APP_SC_DISABLE_SPEEDY=true` to `.env` the styles work properly again.

There are no console errors or warnings and reading the changelog we don't use anything that uses any deprecated stuff.

An example of how we use styled-components:

Weird enough these styles work
```
const StyledApp = styled.div`
  @import url("https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700");

  *,
  & {
    box-sizing: border-box;
    font-family: ${theme.font.family};
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
    -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
  }

  position: absolute;
  left: 0;
  top: 0;
  right: 0;
  bottom: 0;
  color: ${theme.color.gray.darkest};
  transition: all 0.3s ease-out;
`;
```

But anything other than the above styling does not.
```
const StyledTitle = styled.h3`
  font-size: 26px;
  text-align: center;
  margin-bottom: 60px;
  color: ${theme.color.body.base};

  &:after {
    ${pseudoShape()};
    left: 50%;
    transform: translateX(-50%);
    width: 150px;
    height: 3px;
    margin-top: 10px;
    background-color: ${theme.color.body.base};
  }
`;
```

## Expected Behavior

Styles are applied.

![image](https://user-images.githubusercontent.com/12712484/73363170-7b5f3f00-42a8-11ea-9193-6fd8c17f03a5.png)

## Actual Behavior

No styles are applied.

![image](https://user-images.githubusercontent.com/12712484/73363357-e0b33000-42a8-11ea-9c5f-941042534742.png)

**Comment by probablyup** [comment]
>   @import url("https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700");

That should be put in a separate stylesheet. Ideally use react-helmet or something like that since it will never change.

**Comment by jordyvandomselaar** [comment]
@probablyup thanks! I'll see if that makes a difference and keep you posted =)

**Comment by jordyvandomselaar** [comment]
@probablyup can confirm that that fixes it. Thanks! In the breaking changes I read about not being able to `@import` inside global styles, not in components styles. 

It might make sense to throw an error or add a FAQ, I'll try to do it if you'd like

**Comment by admmasters** [comment]
Just got burned by this as well - the issue here I think is that its weird for something to work in dev but not production. If anything would rather this broke in dev as well. The lack of any kind of warning or error was also very frustrating.

**Comment by kitten** [comment]
@admmasters we’ve introduced a warning for this in 5.0.1 that should log when an `@import` at-rule is inserted 👍

**Comment by admmasters** [comment]
Thanks!
