### ISSUE TITLE
styleSheetManager in expo

### ISSUE THREAD

**Issue by zeitamin** [styled-components/styled-components#2999]
[adding StyleSheetManager](https://snack.expo.io/@prloand/c424c6) cause `element type is invalid: expected a string...` error. how do i use in the expo?

**Comment by probablyup** [comment]
That API is web-only

**Comment by zeitamin** [comment]
then how's it possible to flip direction in native?

**Comment by probablyup** [comment]
Currently you can't :/ we're thinking through solutions for this.
