### ISSUE TITLE
Requirements checklist

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components#3]
_This is a living document to figure out how we compare vs. the requirements outlined in `/spec`_

☑️ work well for open source components that are themeable and not opinionated about build requirements (`styled(LibStyledComp)`)
☑️ has a good solution for overriding styles on child elements (`styled(StyledComp)`)
☑️ server side rendering
☑️ don’t break inline styles (untried, but likely true)
☐ fast at runtime (pre-buildable?)
☑️  styles are colocated with components
☑️ isolated as much as possible (styles == component)
☑️ overridable and preferably not opinionated about how (we’re talking about CSS after all)
☑️ supports css stuff like :hover, media queries (i.e. you shouldn’t be blocked from doing anything you can do with css)
❌ doesn’t create a bunch of wrapper components
☑️ small and lightweight enough that you don't think twice about having it as a dependency

**Comment by geelen** [comment]
On SSR, we're building on top of Glamor which means it should be ok, we just need an example to demonstrate how it works.

**Comment by geelen** [comment]
Fast at runtime would need some wild hax to extract the static parts of a project into a separate CSS file. TOTALLY DOABLE though, but not on the roadmap for the moment.
