### ISSUE TITLE
Correct way to pass in a prop and use it as a type to be matched against a case?

### ISSUE THREAD

**Issue by yzhaopost** [styled-components/styled-components#3001]
I have a styled component `WordArtContainer` as follows. 
![image](https://user-images.githubusercontent.com/45929614/73775293-76800c80-473a-11ea-970b-b3b18b6bef65.png)

And `handleWordArtType` is a function:
![image](https://user-images.githubusercontent.com/45929614/73774661-39674a80-4739-11ea-911d-704e2806680f.png)

Here is my rendering:
`<WordArtContainer wordArtType="T22">Example</WordArtConatiner>` 

My questions is how to pass in this `wordArtType` as a prop correctly. Should I use the `{` and `}` as follows? or something? 
![image](https://user-images.githubusercontent.com/45929614/73775023-f063c600-4739-11ea-9917-49124d62feb0.png)

Any suggestions are welcome! Thank you.

**Comment by probablyup** [comment]
Yup the way you’re passing in the prop looks ok to me. You don’t need to
add the vendor prefixed version, we’ll do that for you. You might need to
use the “css” import to wrap the inner style strings.

**Comment by yzhaopost** [comment]
@probablyup Thank you for your prompt reply and thank you for your suggestion! 
It works. But the only concern is that it looks confusing as the code shows a bracket pair in different color. I am using "Bracket Pair Colorizer" and "vscode-styled-components" extensions. 
![image](https://user-images.githubusercontent.com/45929614/73778042-5dc62580-473f-11ea-8788-39ce555f0b77.png)

Maybe the passed in prop  `wordArtType`  confuses the extension? This is the first time I see a pair of bracket showing in different color but it is working. Thank you.

**Comment by probablyup** [comment]
Yeah I think it might just be a bug with the syntax highlighter

**Comment by yzhaopost** [comment]
@probablyup Yeah. That's what I am thinking. We can close this issue. Thanks again!
