### ISSUE TITLE
Styles passed into styled(Component) do not overwrite base styles.

### ISSUE THREAD

**Issue by PooyaDel** [styled-components/styled-components#3002]
```

const AppHeading2Styled = styled.h2`
    color: ${props => props.theme.color.primaryText};
    font-family: ${props => props.theme.font.family.tertiary};
    font-style: ${props => props.theme.font.style.primary};
    font-size: ${props => props.theme.font.size.header2};
`;

const AppHeading2Styled = styled(AppHeading2)`
  text-align: center;
  text-transform: uppercase;
`;
```
No, priority has nothing to do with it! even with &&&!
version: 5.0.0

Yes, I did read other threats that were too long so it was closed (same title).
If I add a class using .attrs({...}) I can find it in the styled components <style> tag, however it does NOT add that the class name the element.

**Comment by probablyup** [comment]
Going to need some sort of reproduction to be able to help you, can't tell what your issue is from this post sorry. Feel free to reopen with an updated issue using the template.
