### ISSUE TITLE
Plugin registration failed due to minification

### ISSUE THREAD

**Issue by yordis** [styled-components/styled-components#3005]
I am not sure if this is a bug since you described the fix. What I am concern is that this is a common thing to happen, I am not sure why to rely on `Function.name` for it.

### System:

- OS: macOS 10.15.2
- CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
- Memory: 963.95 MB / 16.00 GB
- Shell: 5.7.1 - /bin/zsh

### Binaries:

- Node: 10.16.1 - ~/.asdf/installs/nodejs/10.16.1/bin/node
- Yarn: 1.21.1 - ~/Developer/app/node_modules/.bin/yarn
- npm: 6.9.0 - ~/.asdf/installs/nodejs/10.16.1/bin/npm
- Watchman: 4.9.0 - /usr/local/bin/watchman

### npmPackages:

- styled-components: 4.4.1 => 4.4.1

## Reproduction

The problem is that required a package to be compiled and minified for this to
happen, I will try to give the full scope of the setup.

The following code belongs `@org/jsskit` package.

```ts
import * as React from "react";
// notice the usage of the plugin here
import stylisPluginExtraScope from "stylis-plugin-extra-scope";
import { StyleSheetManager } from "styled-components";

export const ScopeProvider: React.FC<{
  scope: string;
}> = props => {
  const stylisPlugins = React.useMemo(() => {
    return [stylisPluginExtraScope(props.scope)];
  }, [props.scope]);

  return (
    <StyleSheetManager stylisPlugins={stylisPlugins}>
      {props.children}
    </StyleSheetManager>
  );
};
```

This following code belongs to my app

```tsx
import { ScopeProvider } from "@org/jsskit";

// ... later on

function MyApp() {
  return <ScopeProvider scope="#app-scope">....</ScopeProvider>;
}
```

## Steps to reproduce

1. Build a library that usage `stylis-plugin-extra-scope`, and creates a
   `ScopeProvider` as before
2. Compile your lib using webpack and minification tool
3. Use `ScopeProvider` from that library in your app
4. Application fails

## Expected Behavior

It should work

## Actual Behavior

![image](https://user-images.githubusercontent.com/4237280/73979983-2775db00-48e4-11ea-8d6a-8ceb9e8f9149.png)

### Context

- https://github.com/Andarist/stylis-plugin-extra-scope/blob/0cdbd9e9342a240cff46eb094dd609a735cb19a8/src/index.js#L5
- https://github.com/Andarist/stylis-plugin-extra-scope/blob/0cdbd9e9342a240cff46eb094dd609a735cb19a8/src/index.js#L24

When `@org/jsskit` is compiled, the previous function is removed and the
compiler (webpack) inlined `extraScopePlugin` to the return using an anonymous
function.

Therefore, `extraScopePlugin.name` is not defined, and this will fail https://github.com/styled-components/styled-components/blob/d0e8eab8cf391630294c6ac9e81f206eb64e5e53/packages/styled-components/src/utils/stylis.js#L98

**Comment by probablyup** [comment]
Try using Object.defineProperty to set it to something at runtime!

**Comment by yordis** [comment]
@probablyup I did that to be able to move forward following the error message.

what I am worry is that we required to do that, should this be done at the stylint plugin level? Is this requirement only related to SC or stylint?

**Comment by probablyup** [comment]
it’s a new thing we’re requiring for v5. If you check out the
implementation for stylis-plugin-rtl you can make a PR against the plugin
to introduce a minification-safe way to add it

**Comment by yordis** [comment]
Roger
