### ISSUE TITLE
I'd like to run styles through a custom function

### ISSUE THREAD

**Issue by wintercounter** [styled-components/styled-components#3007]
I have a very unique situation here and I'm pretty much sure this won't be resolved for me. Anyway, I try.

To simplify, I'd like to add support for custom properties for example and I'd need to access styles to apply my modifications. Checking through the code it seems like the best place for me would be the `css` constructor, because that'd work in every scenario. No way to monkey patch it :)

Is there any chance/idea how to make this happen? Stylis plugin is not really an option for me, I don't want to process it for performance reasons, I'd need full StyleObjects, strings, and template literals before any flattening/interpolation being applied.

I'd happy to make a PR after a successful discussion here.

**Comment by probablyup** [comment]
Why not a stylis plugin? From your needs it sounds like you’d need to touch
or at least see all the styles anyway

**Comment by wintercounter** [comment]
I don't want to do extra processing. For strings I'd need of course but in my case StyleObjects would be first class citizens.

Example component:
```js
const Component = styled.div({
  w: 100,
  h: 100
})
```

What I have with stylis:
```
-1 "w: 100px;h: 100px;" [".kszQrK"] [".kszQrK"] 1 1 0
1 "w:100px" [".kszQrK"] [] 1 9 0
1 "h:100px" [".kszQrK"] [] 1 17 8
2 "w:100px;h:100px;" [".kszQrK"] [] 1 18 16
-2 ".kszQrK{w:100px;h:100px;/*|*/}" [".kszQrK"] [".kszQrK"] 1 18 30
```

From this I'd need to transform back to the original object.

I'd like to add out-of-the-box CCSS support: https://github.com/wintercounter/ccss

I already did it through monkey patching, but it's 100% and I'd like to support `css` prop also.

Btw this would also solve the problem of why `xstyled` cannot support `css` prop also for example.

**Comment by kitten** [comment]
Maybe take a look at how the styles-system library does it? That’d be a prop-based approach.

Or you could wrap styled-components?

Either way, I think this solution may lie outside of our realm, sorry! 😅

**Comment by wintercounter** [comment]
We can to the same for sure (and we actually do), but we would have preferred a way where we can `css={{ w: 100 }}` instead of `css={ccss({ w: 100 })}`. Thanks anyway.

**Comment by kitten** [comment]
@wintercounter that’s probably not a good idea since the css prop is also picked up by the Babel plugin.

But you could still implement a `ccss` prop by making that helper of yours an interpolation.
