### ISSUE TITLE
Webpack 2: Unable to load without workaround

### ISSUE THREAD

**Issue by code-punkt** [styled-components/styled-components#301]
I'm trying to use `styled-components` in `react-universally` boilerplate by @ctrlplusb and get the well known error that quite a few others have experienced before - most prominently discussed in #115

```
Uncaught TypeError: _styledComponents2.default.div is not a function(…)
```

The webpack 2 babel plugin configuration includes `['latest', { es2015: { modules: false } }]`, so module transpilation is done by webpack, not by babel. Webpack 2 loads `lib/index.js`, neither using the `jsnext:main` nor the `module` definitions.

I can fix this by applying the `alias` workaround described in #115 - but that seems like a very hacky way to do so:

```javascript
resolve: {
  alias: {
    // @see https://github.com/styled-components/styled-components/issues/115
    'styled-components$': 'styled-components/lib/index.js',
  }
}
```

Any thoughts?

**Comment by k15a** [comment]
How did you configure Babel?

**Comment by code-punkt** [comment]
@k15a That seems to be an option aswell - not sure why though. Without the alias in my initial post, but with `babelrc: false` it works, without it it doesn't.

When debugging into `babel-loader`, the options given to the transpiler, especially the `presets` part, are exactly the same in both cases. I'm confused. What is happening?

**Comment by k15a** [comment]
Babel is looking for a `.babelrc` and using the preset specified there if you're not specifically saying that you don't want to inherit from the `.babelrc` with `babelrc: true`. You probably have a `.babelrc` with ` {"presets": ["latest"]} ` so you actually don't want to inherit from the `.babelrc` otherwise webpack can't treeshake.

Webpack doesn't know about that so if you're debugging you are only seeing the options Webpack is passing.

**Comment by code-punkt** [comment]
I don't understand. Whether or not i set `babelrc: false`, the options given to the transpiler inside of the `babel-loader` are the same. Still, settings `babelrc: false` fixes my problem.

My `.babelrc`has `"presets": [ ["env", { "targets": { "node": true } }] ]`, but that is not what gets used by `babel-loader` even when *not* setting `babelrc: false` in webpack config. So why is this working?

**Comment by k15a** [comment]
I think `babel-core` is using the combining your config from the `babel-loader` and the `.babelrc` if you didn't specified `babelrc: false`. So if you're debugging babel-loader you see the same options because the inheriting comes from `babel-core`.

Someone else can confirm that this is correct?

**Comment by LorbusChris** [comment]
@code-punkt I believe this bug has been fixed on webpack master already (see https://github.com/webpack/webpack/issues/3168).

For the time being, you can pull in the webpack repo directly. 

Alternatively you could do `const styled = require('styled-components).default`, which should also work

**Comment by k15a** [comment]
He should use `babelrc: false` because otherwise Webpack will not treeshake which will increase his bundle size.
