### ISSUE TITLE
css prop incompatible with TypeScript/Flow

### ISSUE THREAD

**Issue by jedwards1211** [styled-components/styled-components#3012]
The `css` prop babel macro is cool, but adding `css` to arbitrary elements causes type errors:

```tsx
import * as React from 'react'
import Paper from '@material-ui/core/Paper'

const Foo = (): React.ReactNode => <Paper css="color: red;" />

```

```
$ tsc --noEmit
src/index.tsx:4:43 - error TS2769: No overload matches this call.
  Overload 1 of 2, '(props: PaperProps, context?: any): ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<...>)> | Component<...> | null', gave the following error.
    Type '{ css: string; }' is not assignable to type 'IntrinsicAttributes & PaperProps'.
      Property 'css' does not exist on type 'IntrinsicAttributes & PaperProps'.
  Overload 2 of 2, '(props: PropsWithChildren<PaperProps>, context?: any): ReactElement<any, string | ((props: any) => ReactElement<any, string | ... | (new (props: any) => Component<any, any, any>)> | null) | (new (props: any) => Component<...>)> | Component<...> | null', gave the following error.
    Type '{ css: string; }' is not assignable to type 'IntrinsicAttributes & PaperProps & { children?: ReactNode; }'.
      Property 'css' does not exist on type 'IntrinsicAttributes & PaperProps & { children?: ReactNode; }'.

4 const Foo = (): React.ReactNode => <Paper css="color: red;" />
                                            ~~~
```

Is there a way to deal with this in TypeScript and Flow?  Maybe there would be a better solution than a babel macro, for example a wrapper element that clones its child to add `className`?

```tsx
const Foo = (): React.ReactNode => <Styles css="color: red;"><Paper /></Styles>
```

**Comment by jedwards1211** [comment]
There is a workaround for TypeScript described in this analogous Emotion issue:
https://github.com/emotion-js/emotion/issues/693

However, I don't think there's any such workaround for Flow.  I don't feel great about tacking arbitrary props onto React elements for an API...

**Comment by probablyup** [comment]
Please file against DefinitelyTyped, thanks

**Comment by jedwards1211** [comment]
Are there plans for an alternative API that's less invasive and compatible with Flow?

**Comment by probablyup** [comment]
No, we don’t design functionality to appease type systems.

**Comment by jedwards1211** [comment]
Okay, `@types/styled-components` supports this but I had to dig into issues to find out how: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/31245#issuecomment-446011384

I'll make a PR to the docs for the `css` prop to note this for people

**Comment by axhamre** [comment]
@jedwards1211 What did you do to make this work?

**Comment by jedwards1211** [comment]
I can't speak from experience because I was just looking into what the consequences of Material UI switching to styled-components would be.  The comment I linked recommends how to solve it

**Comment by finnmerlett** [comment]
For me the `/// <reference ...` didn't work, and I had to use `import {} from 'styled-components/cssprop';` instead. Then reading a little further down I realised I could just copy the `cssprop.d.ts` file into my module augmentation folder, and it works globally without anything else.
