### ISSUE TITLE
default as prop not being overwritten in 5.0

### ISSUE THREAD

**Issue by coreybruyere** [styled-components/styled-components#3013]
## System:
 - OS: macOS High Sierra 10.13.5
 - CPU: (8) x64 Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
 - Memory: 1.23 GB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 12.13.0 - /usr/local/bin/node
 - Yarn: 1.7.0 - /usr/local/bin/yarn
 - npm: 6.12.0 - /usr/local/bin/npm
## npmPackages:
 - styled-components: ^5.0.1 => 5.0.1

## Reproduction
Take a look at the Text component specifically in the example below. Before, when using pre styled-components 5.0 I was able to declare a default `as` prop as so:
```
export const Text = styled(Box).attrs(() => ({
  as: "p"
}))<TextProps>`
  ${fontWeight};
  ${lineHeight};
  ${textAlign}
`;
```

https://codesandbox.io/s/styled-components-base-gc367

Now after upgrading to 5.0 in a separate repo that consumes the library with the example files in the codesandbox above I'm noticing overwriting the `as` prop is no longer working as expected. 

I'm just now seeing in the release notes that 5.0 "Removed the "subfunction" attrs syntax that was deprecated in v4". Should using the new syntax fix my issue?

## Steps to reproduce
Upgraded from `4.4.1` to `5.0.1`

## Expected Behavior
I should be able to override default `as` prop that's declared when importing and using said component.

## Actual Behavior
`as` prop now not being overwritten

**Comment by probablyup** [comment]
When you use attrs you need to check if the prop is passed when you
override it. Attrs has precedence over props.

**Comment by coreybruyere** [comment]
Sorry @probablyup, not sure what you mean by that. Care to share an example?

**Comment by probablyup** [comment]
attrs(p => ({ as: p.as || “something” }))

**Comment by coreybruyere** [comment]
Ah I see. Thanks for the explanation!

**Comment by coreybruyere** [comment]
Arguably a different issue or question, but now I'm getting typescript errors since as property doesn't exist on `ThemedStyledProps`. Any idea where to find type support for the as prop? Using the latest version of SC and @types/styled-components

**Comment by kitten** [comment]
I think the TtpeScript types are maintained in the DefinitelyTyped repo and not by us as they became increasingly complex (basically as hard to maintain as styled-components itself 😂)

I think they may just be out of date and may not list `as` as a possible internal prop on all the defined interfaces
