### ISSUE TITLE
Styled Components doesn't work after "npm run build" in a local build folder.

### ISSUE THREAD

**Issue by EntaltsevSN** [styled-components/styled-components#3014]
Hey!
I'm using the create-react-app with styled-components. I'm running index.html from the build folder(using "homepage": "." in the package.json) and it's running with styled-components but without any styles for sc classes. I've found solutions with `react-app-rewired`, `styled-components-babel-macros` and it's not help me to solve it. I don't want to use the eject for my CRA, so help me please with the solution to fix it.

**Comment by probablyup** [comment]
https://styled-components.com/docs/tooling#babel-macro

**Comment by EntaltsevSN** [comment]
@probablyup I've already test it and it's not working for me. Can you please clarify or provide me with the example of code which works after building?

**Comment by EntaltsevSN** [comment]
@probablyup Also, I tried to deploy it to the Netlify and still has same issue.

**Comment by kitten** [comment]
Sorry but first and foremost please post usage questions on StackOverflow or our Spectrum as listed in our issue template.

Also as you’ve found: Babel Macros work in CRA, so you can use our Babel Macro.

Now I do want to help and would love to resolve this quickly for you, but I have nothing to go on 😔 So you’ve said it isn’t working for you, what do you mean by that? You said you think you need to use our Babel plugin I assume? But you haven’t said why you think so.

> I’m running Index.html from the build folder

So you’ve built your CRA app with the `build` script? Does it work in development when you just `start` the app though or what happens instead?

The issue template still gives you a good guide on how to write an issue that helps me help you 🙌 maybe check whether you can describe what you’re seeing, what you’ve done and tried, and what you expect?

**Comment by EntaltsevSN** [comment]
The issue is fixed. It was happened because the createGlobalStyle component was added before the app body. I've placed it in the end of the app component and it works now.
