### ISSUE TITLE
How can I eject the styles from styled component?

### ISSUE THREAD

**Issue by EntaltsevSN** [styled-components/styled-components#3019]
I have a styled component like this:
```
const Container = styled.div`
  width: 100%;
  max-width: 1200px;
`;

export default Container;
```
How can I eject the styles from the `Container` to have it in another constant?

For example,:
```
let containerStyles = `
  width: 100%;
  max-width: 1200px;
`;

**Comment by kitten** [comment]
I have to honestly say, I’m a little disappointed after having posted this: https://github.com/styled-components/styled-components/issues/3014#issuecomment-585012306

> please post usage questions on StackOverflow or our Spectrum as listed in our issue template.

Again, we’re happy to help and answer questions on GitHub, but It’s still mainly intended to file bugs and other source code related requests. We’re not a large team and face a lot of work just triaging and sorting through issues. 😔

You can use the `css` helper to reuse blocks of CSS https://styled-components.com/docs/api#css
