### ISSUE TITLE
Click event is not fired or prevented

### ISSUE THREAD

**Issue by nicugorea** [styled-components/styled-components#3023]
## Reproduction
https://codesandbox.io/s/yqm230kx49 

## Steps to reproduce
Update styled-components to the latest version

Click an item in the dropdown

## Expected Behavior
The item click is handled

## Actual Behavior
The item click event is not handled

**Comment by nik72619c** [comment]
Is this issue free to work on ?

**Comment by nicugorea** [comment]
> Is this issue free to work on ?

It is.

**Comment by kitten** [comment]
Sorry for the delay. I haven’t had time yet to look into this but this seems like a usage issue with the atlaskit library instead of styled-components.
