### ISSUE TITLE
missing semi-colon is handled differently in version 5.0.1

### ISSUE THREAD

**Issue by adamkingletgo** [styled-components/styled-components#3025]
## System:
 - OS: macOS 10.15.3
 - CPU: (4) x64 Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz
 - Memory: 403.66 MB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 12.14.1 - /usr/local/bin/node
 - Yarn: 1.10.1 - /usr/local/bin/yarn
 - npm: 6.13.4 - /usr/local/bin/npm
## npmPackages:
 - styled-components: 5.0.1 => 5.0.1 

## Reproduction

v5.0.1: https://codesandbox.io/s/upbeat-lederberg-7l9yz ❌ 
v4.4.1: https://codesandbox.io/s/jovial-newton-rutj6 ✅ 

## Steps to reproduce
* style a component and omit the semi-colon in the template string eg:
```
styled.div`
  min-width: ${({ minWidth }) => (minWidth ? `${minWidth}px` : "")} // missing semi-colon here
`;
```

## Expected Behavior
It can still parse the styles

## Actual Behavior
It doesn't parse the styles correctly:
```
    min-width: 80px max-width:500px;
```

**Comment by probablyup** [comment]
We've never supported omitting semicolons, if it worked before it was a fluke. styled-components only supports valid CSS, style objects, and interpolations.

**Comment by xxn520** [comment]
v4 use stylis directly, and set `semicolon: false`, this means "autocomplete missing semicolons". But v5 use @emotion/stylis and set `options.semicolon: true`, this is a breaking change. It is recommended to write to ChangeLog.

**Comment by tomasswood** [comment]
Is there an eslint or ts rule that we can apply to find these automatically?

**Comment by adibsaad** [comment]
> We've never supported omitting semicolons; if it worked before it was a fluke. styled-components only supports valid CSS, style objects, and interpolations.

How do you explain https://github.com/styled-components/styled-components/pull/1532 ?

**Comment by jamime** [comment]
@probablyup please reconsider this issue.

**Comment by makotot** [comment]
> Is there an eslint or ts rule that we can apply to find these automatically?

If we use PostCSS and interpret it as a CSS AST, we would be able to statically parse it as incorrect CSS syntax, as like  [this](https://astexplorer.net/#/gist/d989304ca602a702e5ea490b0c2fdd42/e6e3fdc804dd71bb8e6beeb28ad261e4d0c62b14).
There is also [postcss-styled-syntax]( https://github.com/hudochenkov/postcss-styled-syntax), which handles css-in-js syntax like styled-components in PostCSS.

I feel this is the best way to detect the lack of semicolon, but I'd like to know if I'm missing a consideration 🤔
