### ISSUE TITLE
HOCs do not work in Next.js production builds

### ISSUE THREAD

**Issue by dminkovsky** [styled-components/styled-components#3026]
## Summary

I have an HOC that takes CSS input and returns a button component. Please see the listing at https://github.com/dminkovsky/next-styled-broken-prod/blob/master/pages/index.js. In devlopment, the HOC works. In production, the HOC only produces one result.

I have reproduced this in Next.JS default production build settings. Not sure if it affects other "production" configurations.

## System:
 - OS: macOS Mojave 10.14.6
 - CPU: (4) x64 Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz
 - Memory: 2.48 GB / 16.00 GB
 - Shell: 4.4.23 - /usr/local/bin/bash
## Binaries:
 - Node: 13.4.0 - /usr/local/bin/node
 - Yarn: 1.21.1 - /usr/local/bin/yarn
 - npm: 6.13.4 - /usr/local/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.10.7 => 1.10.7 
 - styled-components: 5.0.1 => 5.0.1

## Reproduction

Clone https://github.com/dminkovsky/next-styled-broken-prod and install dependencies.

## Steps to reproduce

1. `yarn run dev` and go to localhost:3000, observe dev result: 

<img width="161" alt="Screen Shot 2020-02-17 at 2 17 08 PM" src="https://user-images.githubusercontent.com/218725/74681478-7f88c900-5191-11ea-8971-a42da9a02c4d.png">

2. `yarn run build` && `yarn run start` and go to localhost:3000, observe prod result:

<img width="233" alt="Screen Shot 2020-02-17 at 2 17 55 PM" src="https://user-images.githubusercontent.com/218725/74681519-94fdf300-5191-11ea-9bf8-bf87d3238f1d.png">

## Expected Behavior

Dev and prod builds should be the same.

## Actual Behavior

Dev and prod builds are different.

**Comment by dminkovsky** [comment]
This does not happen using v4, but in v5. Please see: https://github.com/zeit/next.js/issues/10561

**Comment by dminkovsky** [comment]
Possibly related/dupe of #2962.

**Comment by probablyup** [comment]
Perhaps `hoist-non-react-statics` rearing its ugly head again. We had a homebrewed solution in v4 and reverted back to the library in v5.

**Comment by kitten** [comment]
The reproduction here is broken, I believe, but I doubt that it's still an issue.

**Comment by dminkovsky** [comment]
@kitten this is still an issue as of 5.2.1. The repro is broken?

**Comment by Bilb** [comment]
Still an issue for me too

**Comment by jademh** [comment]
seeing this issue when using nextjs getLayout and have styled-components in the layout component
styles in the layout file are not present on prod build
styles in child components of pages that use the layout are fine
downgrading to v4 fixed issue

**Comment by dminkovsky** [comment]
@kitten closing an issue doesn't solve it. 

@probablyup I'm not saying this needs to be fixed (or course it doesn't), but I took the time to create this repro, the least you can do is keep it open. 

@jademh If you're working on a new project, might I recommend migrating to emotion? It's too late for me, but my impression is that styled-components is sort of abandoned. A workaround for this behavior is to use functions in your interpolations:

```
// works:
const Component = function buildComponent(css) {
  return styled.div`
    ${() => css} /* <-- a function */
  `
}

// does not work:
const Component = function buildComponent(css) {
  return styled.div`
    ${css}
  `
}
```

**Comment by dminkovsky** [comment]
I improved the title to "Components returned from functions are broken in production" because that really is all it is.

**Comment by kitten** [comment]
> @dminkovsky: closing an issue doesn't solve it.
> @kitten: The reproduction here is broken, I believe

Yes, hence me saying.... Like, I understand your frustration, but what am I supposed to do here in your opinion?

**Comment by dminkovsky** [comment]
@kitten 

In my opinion:

1) Try the reproduction again—it's not broken. I've tested it, it works. If something is confusing, ask for clarification.
2) Even if the repro is broken (it's not), re-open the issue, because others are confirming this is still a problem.

**Comment by jademh** [comment]
@dminkovsky FYI the repro https://github.com/dminkovsky/next-styled-broken-prod is a 404 for me, perhaps this is why @kitten is saying it is broken - is it a private repo?

**Comment by dminkovsky** [comment]
But for posterity, I've put it back up at https://github.com/dminkovsky/next-styled-broken-prod @5.1.1, the last version I tested it with where it was broken. 

Steps for repo:

1) yarn install
2) yarn run dev

Observer the two buttons looks different

3) yarn run build
3) yarn run start

Observe the two buttons look identical.

**Comment by jademh** [comment]
ah thank you @dminkovsky will try it at 5.3.3!

**Comment by dminkovsky** [comment]
Yeah it's good to know that workaround I mentioned above is no longer necessary. Thanks @jademh.

**Comment by kitten** [comment]
I'll run through it again in the old version and new version and I'll try to see what caused it so we can avoid regressions 👍

**Comment by jademh** [comment]
@kitten fwiw i was seeing the issue at `5.2.1` (the repro repo is 5.1.1) but @dminkovsky mentioned above that it was still an issue for them at 5.2.1 - just wanted to add it was for me too

**Comment by nathanhere** [comment]
I landed here because I was experiencing the same issue. Using v5.3.3. Will try v4 and report back.
