### ISSUE TITLE
Props are duplicated across different styled components

### ISSUE THREAD

**Issue by schuylr** [styled-components/styled-components#3029]
## Environment

deploy@jewlr4_container:/var/www/apps/jewlr4/current$ npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown
npx: installed 1 in 1.224s

## System:
 - OS: Linux 5.3 Ubuntu 16.04.6 LTS (Xenial Xerus)
 - CPU: (12) x64 Intel(R) Xeon(R) E-2176M  CPU @ 2.70GHz
 - Memory: 5.97 GB / 30.99 GB
 - Container: Yes
 - Shell: 4.3.48 - /bin/bash
## Binaries:
 - Node: 8.16.1 - /usr/bin/node
 - Yarn: 1.17.3 - /usr/bin/yarn
 - npm: 6.11.3 - /usr/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.10.6 => 1.10.6
 - styled-components: ^5.0.0-rc.2 => 5.0.0-regexrehydrate

I've also upgraded to 5.0.1 with the same issues.

## Reproduction

I'm going to try and be as minimal as possible with the reproduction, but this bug seems to only occur on our Rails Webpacker environment with `NODE_ENV=production` for the compiled assets.

### Steps to reproduce

Given this JSX:

```jsx
import React from "react"
import styled from "styled-components"

const Paragraph = styled.p`
  font-size: 12px;
`

// color is actually ${props => props.theme.colors.primary} in case it matters
const Link = styled.a`
  color: blue;
`

const Example = () => (
  <Paragraph>
    This is an example{" "}
    <Link href="/example1">
      link
    </Link>{" "}
    and another
    <Link href="/example2">
      {" "}
      link here
    </Link>
  </Paragraph>
)

export default Example
```

The resulting DOM from React comes out like this:

```
<p class="sc-18zuc55-0 f01d7y-4 iKAUGv">This is an example <a href="/example2" class="sc-1ibrsg0-0 dQyVDf">link</a> and another<a href="/example2" class="sc-1ibrsg0-0 dQyVDf"> link here</a></p>
```

Notice that the `href` of the first link contains the contents of the second link.

This also happens for other props like `id`.

This isn't reproducible in the sandbox, so let me know what configurations (i.e. Babel) I need to share to try and get a reproduction somewhere else. I also have no idea where the prop duplication is coming from since there's very little I can do to debug the production environment.

### Expected Behavior

For the `href` and other props to be correct for each styled element.

## Actual Behavior

The props are incorrect. In the React DevTools Components inspector, the props are correct in the Virtual DOM, yet the real DOM has incorrect props.

I can show screenshots but Github is having trouble right now.

**Comment by schuylr** [comment]
The workaround to fix this is to split the styled components into `Link` and `Link2` - with the same CSS attributes in each of them.

**Comment by ludwighogstrom** [comment]
We experience a similar issue(?). 

When building for production a hashed class name that belongs to another component get set on other elements as well (works fine when building for development).

Our site uses SSR.

**Comment by schuylr** [comment]
Not the same as my issue unfortunately - also I tried going to raw `<a>` JSX and saw the issue still persisted, so I suspect an issue is happening with React itself. Closing since this means it's not from styled components.
