### ISSUE TITLE
using `createGlobalStyle` in jest tests might throw error occasionaly

### ISSUE THREAD

**Issue by macrozone** [styled-components/styled-components#3030]
we use storyshots to make snapshots from all storybook stories (https://github.com/storybookjs/storybook).

We decorated all our stories with a component that contains a component made with `createGlobalStyle`

running snapshot tests _sometimes_ throw an error in react-dom:

`TypeError: Cannot read property 'createEvent' of null`  in react-dom. After doing additional debugging i found out that this error was thrown in the component created with `createGlobalStyle`

## System:
 - OS: macOS 10.15.3
 - CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
 - Memory: 32.00 GB / 64.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
 - Yarn: 1.21.1 - ~/git/panter/veloplus/veloplus-shop/veloplus-shop-fe/node_modules/.bin/yarn
 - npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: ^1.10.0 => 1.10.6
 - styled-components: ^5.0.1 => 5.0.1

## Steps to reproduce

its probably hard to reproduce, i could not trigger this error consistenty. Its probably easier to look why this happens. According to https://github.com/facebook/create-react-app/issues/3482 this error happens in non-dom environments, when some async function triggers a state-update or similar of an already unmounted component. This makes sense that this might happen in tests, because components get mounted and unmounted very rapidly. And in our case we mounted and unmounted a `createGlobalStyle` in every test.

my guess is that it happens somewhere here: https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/constructors/createGlobalStyle.js#L68

## Expected Behavior

react-dom should not need to throw that error there ;-)

## Actual Behavior

it throws ;-)

## workaround and thoughts

 I simply removed the `createGlobalStyle`-Component when doing tests as a workaround. I would probably not bother about this edge case too much, but when it happens it leads to hard to track errors, so i leave this here as reference to others. 

also other issues around `createGlobalStyles` like https://github.com/styled-components/styled-components/issues/3022 might indicate, that there is something wrong with cleaning up these global styles

**Comment by probablyup** [comment]
We don't use the `createEvent` API so not sure how this could be a styled-component issue. Perhaps there's a bug or sequencing issue in how the testing software runs useEffect unmount hooks.
