### ISSUE TITLE
Some CSS properties not working with styled.th

### ISSUE THREAD

**Issue by hmessProf1** [styled-components/styled-components#3034]
## System:
 - OS: Windows 10
 - CPU: (8) x64 Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz
 - Memory: 8.78 GB / 15.86 GB
## Binaries:
 - Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
 - npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD
## npmPackages:
 - styled-components: ^5.0.0 => 5.0.0

## Reproduction
I'm finding that `styled.th` isn't handling text or vertical alignment, even as it's handling italics and background color. I'm also using text-align with `styled.td`, and that's working fine. 

This code using a `th` tag directly gives me right- and bottom-aligned column headings in italics on a yellow background:
```
export function TableColumnHeader({
    label,
    fieldName,
    fieldType,
    sortState,
    handleClick
}) {
    const sortAttributes = { };
    if (sortState === 1) {
        sortAttributes.role = 'columnheader';
        sortAttributes['aria-sort'] = 'ascending';
    } else if (sortState === -1) {
        sortAttributes.role = 'columnheader';
        sortAttributes['aria-sort'] = 'descending';
    }

    return (
        <th style={{
            backgroundColor: 'yellow',
            verticalAlign: 'bottom',
            textAlign: 'right',
            fontStyle: 'italic'
            }} scope="col" {...sortAttributes}>

            {label}
        </th>
    );
}
```
![without-styled-th](https://user-images.githubusercontent.com/52576600/75086803-2d83d280-5506-11ea-9707-f5ee4fb3c381.jpg)

When I make use of a `styled.th`, I get italics on a yellow background, but the text-alignment and vertical-alignment are being ignored:
```
export function TableColumnHeader({
    label,
    fieldName,
    fieldType,
    sortState,
    handleClick
}) {
    const sortAttributes = { };
    if (sortState === 1) {
        sortAttributes.role = 'columnheader';
        sortAttributes['aria-sort'] = 'ascending';
    } else if (sortState === -1) {
        sortAttributes.role = 'columnheader';
        sortAttributes['aria-sort'] = 'descending';
    }

    const SortableColumnHeader = styled.th`
        background-color: yellow;
        vertical-align: bottom;
        text-align: right;
        font-style: italic;
    `;

    return (
        <SortableColumnHeader scope="col" {...sortAttributes}>
            {label}
        </SortableColumnHeader>
    );
}
```
![with-styled-th](https://user-images.githubusercontent.com/52576600/75086866-0083ef80-5507-11ea-90b0-b0574964c425.jpg)

## Expected Behavior
I'm expecting styled.th to reflect the alignment properties as well as the background and italicization..

## Actual Behavior
I'm getting only the background and italicization.

## Addendum
I'm remembering that at one point I had padding-left in there and it was also ignored.

**Comment by hmessProf1** [comment]
For kicks, I gave this a try:
```
    return (
        <th scope="col" {...sortAttributes}>
            <div style={{
                backgroundColor: 'yellow',
                verticalAlign: 'bottom',
                textAlign: 'right',
                fontStyle: 'italic'
            }}>
                {label}
            </div>
        </th>
    );
```
I expected that only the `divs` inside the `th`s would be yellow (because the padding on the `th`s wouldn't be, and that I would have vertical alignment because vertical-align doesn't apply to `div`s. But I did expect, and got, right alignment.

Then I did this:
``` 
  const SortableColumnHeaderDiv = styled.div`
        background-color: yellow;
        vertical-align: bottom;
        text-align: right;
        font-style: italic;
    `;

    return (
        <th scope="col" {...sortAttributes}>
            <SortableColumnHeaderDiv>
                {label}
            </SortableColumnHeaderDiv>
        </th>
    );
```

and got exactly the same result, with the right alignment working.

Then I added left padding:

```    const SortableColumnHeaderDiv = styled.div`
        background-color: yellow;
        vertical-align: bottom;
        text-align: right;
        font-style: italic;
        padding-left: 150px;
    `;
```
and the padding appeared as well, whereas it hadn't when I applied it to styled.th.

**Comment by probablyup** [comment]
Have you tried styling the th with inline styles? Certain table related
html elements don’t take CSS directly unless you set display: table-header
or something like that. Finicky legacy stuff

**Comment by hmessProf1** [comment]
As I showed above, I got the result I expected when I coded the styles directly into the JSX `th` tag. Do you mean something else by "directly"? It's when I move them to `styled.th` that *some* of them break.

**Comment by kitten** [comment]
It’s also probably worth noting that you shouldn’t define StyledComponents inside other components render method or function components.

If you upgrade to 5.0.1 there’s a new warning that’ll tell you about that 👍

**Comment by hmessProf1** [comment]
SOLVED: I'm embarrassed that I hadn't checked the DOM being generated before, instead of just looking at what was displayed in the browser. The properties were being applied to the generated class--but there was another rule with higher specificity. I manufactured my own class name for this component and recoded it as

const SortableColumnHeader = styled.th.attrs({ className: 'sortableColumnHeader' })`
    &&.sortableColumnHeader {
        background-color: yellow;
        vertical-align: bottom;
        text-align: right;
        font-style: italic;
    }
`;
````

This generates the following DOM:

![new-version](https://user-images.githubusercontent.com/52576600/75115247-9b291f00-562a-11ea-8735-504af46fa5e8.jpg)

And this now my headers are displaying as I'd expected. Sorry for the goose chase.
