### ISSUE TITLE
Bug using SSR with version 5. Crashes with "More hooks than previous render" when running Google Audit / Lighthouse

### ISSUE THREAD

**Issue by MatsDahlin** [styled-components/styled-components#3036]
Site with Styled Components 4 and SSR is working great, but when upgrading to Styled Components 5, we can put the app in an erroneous state by running Google Audit in Chrome.

## Steps to reproduce
Use Styled Components 5 or 5.0.1.
Setup SSR according to "Advanced usage" on Styled Components homepage.
Render components with some styled components.

## Expected Behavior
Page should render without problem every time.

## Actual Behavior
Manual pageloads gets rendered fine, but when running Google Audit, the Node server running SSR crashes and must be restarted.

**Comment by kitten** [comment]
We can’t debut or help with this unfortunately without a reproduction or more information.

Based on the version having been tested thoroughly though, by us and by users, it may be the case that this is a usage issue, in which case StackOverflow or Spectrum may be more helpful. 🙏

Please do post a reproduction though and I’ll take a look 👍

**Comment by MatsDahlin** [comment]
You were correct, this was a case of usage error. The issue is resolved, and it was not because of Styled Components. Thanks for the quick response though =)
