### ISSUE TITLE
@import url(...) inside of createGlobalStyle causes styles other than global disappear in builded version

### ISSUE THREAD

**Issue by arkadiuszbachorski** [styled-components/styled-components#3038]
### System:
 - OS: Windows 10 10.0.18363
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
 - Memory: 7.31 GB / 15.92 GB
### Binaries:
 - Node: 10.16.3 - C:\Program Files\nodejs\node.EXE
 - npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
### npmPackages:
 - styled-components: ^5.0.1 => 5.0.1

Project was created with create-react-app --typescript

## Steps to reproduce

To reproduce bug you have to import font in createGlobalStyle. Then you need to build your project and run it. It works properly when runned with `npm run start`.

``
createGlobalStyle`
    @import url('https://fonts.googleapis.com/css?family=Ubuntu&display=swap&subset=latin-ext');
`
``

## Expected Behavior

Font should be imported, all global and styled.components should be styled.

## Actual Behavior

Font is imported, global styles are working but any styled.component styles are lost. No errror is shown anywhere.

**Comment by PaulACoroneos** [comment]
It is actively discouraged to use @imports inside your global style and a warning was added as of 5.0.1 https://styled-components.com/releases#v5.0.1

**Comment by arkadiuszbachorski** [comment]
Release notes mention something about "dev-time warnings". Where do they appear? I didn't notice any warnings. 

Release notes aren't your first choice when you run into this kind of problem. I think it shoud be mentioned as "note" somewhere around createGlobalStyle.

**Comment by probablyup** [comment]
They appear in your developer console.

**Comment by williammustaffa** [comment]
I faced this issue and was able to workaround it returning it in a string, such as:
`${`@import url('font-url')`}`

**Comment by Storken** [comment]
May I ask, what is the encouraged way to import fonts globally now if we can't import them in the global style?

**Comment by ibqn** [comment]
I would like to know this as well, how should google fonts should be imported?

**Comment by arkadiuszbachorski** [comment]
Since there is no possibility to import fonts inside `createGlobalStyles`, then we have to choose between plain CSS approaches:

* using `@import` inside plain `.css` file
* using `<link>` with the font url directly
