### ISSUE TITLE
forwardedAs renders style props as attributes

### ISSUE THREAD

**Issue by webcoderkz** [styled-components/styled-components#3039]
## System:
 - OS: macOS 10.15.3
 - CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
 - Memory: 291.51 MB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
 - Yarn: 1.22.0 - /usr/local/bin/yarn
 - npm: 6.13.6 - ~/.nvm/versions/node/v12.10.0/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^5.0.1 => 5.0.1

## Reproduction

https://codesandbox.io/s/styled-components-base-8xzdn?fontsize=14&hidenavigation=1&theme=dark

## Steps to reproduce
Inspect the button in chrome dev tools, and you'll see the following markup for this button:

```
<a mr="5px" class="sc-AykKG hmgWQJ btn btn-danger btn-sm" href="">Click me, bro!</a>
```

Prop `mr="5px"` passed as attribute, though it was passed just like a common prop for the styles.

## Expected Behavior

`mr="5px"` shouldn't be rendered as button attribute, because it's prop, it shouldn't be there:

```
<a class="sc-AykKG hmgWQJ btn btn-danger btn-sm" href="">Click me, bro!</a>
```

**Comment by probablyup** [comment]
Yes when you render a custom component instead of a HTML primitive, e.g. "div" we don't filter props. This is documented: https://styled-components.com/docs/basics#passed-props
