### ISSUE TITLE
[React Native] Failed to parse box-shadow

### ISSUE THREAD

**Issue by robertmylne** [styled-components/styled-components#3042]
Error message:

`Error: failed to parse declaration "boxShadow: rgba(15, 51, 83, 0.02) 0px 4px 12px 0px`

Code:

```
const CardView = styled.View`
    background-color: rgb(255, 255, 255);
    width: 100%;
    box-shadow: rgba(17, 51, 83, 0.02) 0px 4px 12px 0px;
    border-radius: 6px;
    border-width: 1px;
    border-style: solid;
    border-color: rgb(236, 239, 241);
`
```

**Comment by probablyup** [comment]
Check this thread out: https://github.com/styled-components/styled-components/issues/709

Box shadow doesn't work the same as web in react native unfortunately because of how the platform is designed (out of our hands basically.)
