### ISSUE TITLE
`TypeError: Cannot read property 'createEvent' of null` on updating to 5.0.1

### ISSUE THREAD

**Issue by teo029** [styled-components/styled-components#3043]
## System:
 - OS: macOS 10.15.3
 - CPU: (16) x64 Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz
 - Memory: 369.03 MB / 32.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 13.8.0 - /usr/local/bin/node
 - npm: 6.14.1 - ~/.../node_modules/.bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: 5.0.1 => 5.0.1 

## Steps to reproduce
Update to styled-components@5.0.1 (from 4.4.1)
Update to jest-styled-components@7.0.0 (from 6.3.4),
Run tests that worked before updating these two packages.

## Expected Behavior

Tests run as expected.

## Actual Behavior

Smoke test (just rendering a component that makes use of styled components) fails with:

```
/node_modules/react-test-renderer/cjs/react-test-renderer.development.js:2076
      throw error;
      ^

TypeError: Cannot read property 'createEvent' of null
    at Object.invokeGuardedCallbackDev (.../node_modules/react-test-renderer/cjs/react-test-renderer.development.js:11724:26)
...
```

The test:
```
it('renders', function() {
    expect.assertions(1)
    const { getByText } = render(<Intro componentId="foo" />)
    expect(getByText('login:intro.title')).not.toBeNull()
})
```

**Comment by probablyup** [comment]
This has nothing to do with styled-components
