### ISSUE TITLE
[TypeScript] Does not overwrite Props when supplying it to constructor

### ISSUE THREAD

**Issue by danielkov** [styled-components/styled-components#3044]
Hello 👋 

I am submitting this issue here, because the `types` repo has over 3k open issues and also this ties into how SC handles props. Perhaps my understanding is wrong and in that case the typings are correct.

## Environment

* `styled-components@5.0.1`
* `@types/styled-components@5.0.1`
* `typescript@3.7+`

## Reproduction

[Here's a simple reproduction](https://codesandbox.io/s/vigorous-worker-bkfsm).

## Steps to reproduce

Try to override the prop definition on the return value (actual component) of Styled Constructor.

```ts
import styled from "styled-components";
import { func } from "prop-types";

type ExampleProps = { color: Function };

const Example = styled.div<ExampleProps>`
  width: 100px;
  height: 100px;
  color: ${({ color }) => color()};
`;

Example.propTypes = {
  color: func
};

type ExtractPropTypes<T> = T extends React.WeakValidationMap<infer P>
  ? P
  : never;

// `type Err = string & Function` instead of `type Err = Function`
type Err = ExtractPropTypes<typeof Example.propTypes>["color"];

// `type S = Function & string` is the reason why it behaves like this.
type S = (ExampleProps & { color: string })["color"];
```

## Expected Behavior

I believe the type of `Props` here should be overridden by whatever the user supplied, because that's how it works. In my example the behaviour is as expected.

## Actual Behavior

The typings are merging the types of the two into a definition that makes little sense: `string & Function`.

## Reason

Since in my example the `color` property does not actually land on the DOM node, it makes no sense to still enforce validity towards the constraint inherited from `DetailedHTMLProps`.

Alternatively the `color` property should have landed on the DOM node and this is an issue with `styled-components` as well as the typings (because in that case the type should be `string | Function` instead of `string & Function`).

I am happy to submit a PR, once I know what the correct behaviour should be.

**Comment by probablyup** [comment]
Please file against DefinitelyTyped, we don't maintain the types.
