### ISSUE TITLE
Styled-components version 5+ causes invalid hook call errors when trying to import styled-components based package

### ISSUE THREAD

**Issue by lawrenz1337** [styled-components/styled-components#3045]
## System:
 - OS: macOS 10.15.2
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 231.07 MB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 10.15.3 - /usr/local/bin/node
 - Yarn: 1.21.1 - /usr/local/bin/yarn
 - npm: 6.9.0 - ~/.npm-packages/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: ^1.10.7 => 1.10.7
 - styled-components: ^5.0.1 => 5.0.1

## Description
I am trying to create an UI-kit like npm package using react and styled-components. For some weird reason starting from version 5.0.0 When I import the simplest package I get a react hook error. The same code works fine as an import in different package with styled-components version 4.4.1. Here is the UI component:
```
import React, { Component } from "react";
import styled from "styled-components";

const Test = styled.div`
  width: 100px;
  height: 100px;
  background-color: red;
`;

export default class DummyComponent extends Component {
  render() {
    return (
      <div>
        <Test />I am a dummy react npm module
      </div>
    );
  }
}
```

Here is how I import it in CRA default app:
```
import React from 'react';
import logo from './logo.svg';
import './App.css';
import Button from 'dummy-react-npm-module';

function App() {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
        <p>
          Edit <code>src/App.js</code> and save to reload.
        </p>
        <a
          className="App-link"
          href="https://reactjs.org"
          target="_blank"
          rel="noopener noreferrer"
        >
          Learn React
        </a>
        <Button>test</Button>
      </header>
    </div>
  );
}

export default App;
```

This is the error I get with v5.0.1:
![image](https://user-images.githubusercontent.com/9716493/75862948-61b19a00-5e08-11ea-8d0c-38741cf2e97a.png)

The issue does seem related to this one #3037 and this PR #2390 

## Expected Behavior
The library should work correctly as an import and not cause react hook errors.

**Comment by billcreative** [comment]
I've not upgraded to v5 yet so don't know if these will solve your problem but I've had similar issues elsewhere.

You need to make sure you only have one version of Styled Components so make sure it's a peerDependency and devDependancy in your package. See [FAQs](https://styled-components.com/docs/faqs#i-am-a-library-author-should-i-bundle-styledcomponents-with-my-library)

You'll need to make sure you only have one version of React so may need to symlink to your packages version of React. See [Duplicate React](https://reactjs.org/warnings/invalid-hook-call-warning.html#duplicate-react) and React [issue #13991](https://github.com/facebook/react/issues/13991)

**Comment by lawrenz1337** [comment]
I import my own library and I am 100% sure that both `react`, `react-dom`, `react-is`, `styled-components` are all in devDeps and peerDeps. Thanks for the heads up tho

**Comment by CyrilQuandalle** [comment]
Hi,
I've got the same issue in 4.4.1 everything works fine but in 5.0.1 it doesn't.
FYI: I had  to add the folling in the resolve part of my webpack.config.js to make it work.
`alias: {
        react: path.resolve('./node_modules/react')
      }`

**Comment by probablyup** [comment]
Generally this sort of thing occurs when there is library duplication in your dependencies. @CyrilQuandalle's fix works because it forces a single version of React to be used but using functionality like yarn's "resolutions" package.json field will achieve the same goal.

**Comment by lawrenz1337** [comment]
@probablyup Here is my package.json. Are there any duplications there?

```
{
  "name": "example-uikit",
  "version": "0.0.1",
  "description": "Put a description here",
  "main": "build/index.js",
  "peerDependencies": {
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-is": "^16.12.0",
    "styled-components": "4.4.1"
  },
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "start": "webpack --watch",
    "build": "webpack",
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook",
    "dsm-storybook:publish": "dsm-storybook publish",
    "dsm-storybook:preview": "dsm-storybook preview"
  },
  "devDependencies": {
    "@babel/cli": "^7.8.4",
    "@babel/core": "^7.8.4",
    "@babel/plugin-proposal-class-properties": "^7.8.3",
    "@babel/plugin-proposal-object-rest-spread": "^7.8.3",
    "@babel/plugin-transform-runtime": "^7.8.3",
    "@babel/preset-env": "^7.8.4",
    "@babel/preset-flow": "^7.8.3",
    "@babel/preset-react": "^7.8.3",
    "@invisionapp/dsm-storybook": "^0.0.127",
    "@storybook/addon-a11y": "^5.3.14",
    "@storybook/addon-actions": "^5.3.14",
    "@storybook/addon-backgrounds": "^5.3.14",
    "@storybook/addon-centered": "^5.3.14",
    "@storybook/addon-docs": "^5.3.14",
    "@storybook/addon-knobs": "^5.3.14",
    "@storybook/addon-links": "^5.3.14",
    "@storybook/addon-options": "^5.3.14",
    "@storybook/addons": "^5.3.14",
    "@storybook/react": "^5.3.14",
    "babel-eslint": "^10.1.0",
    "babel-loader": "^8.0.6",
    "babel-plugin-add-module-exports": "^1.0.2",
    "babel-plugin-dev-expression": "^0.2.2",
    "babel-plugin-flow-runtime": "^0.19.0",
    "babel-plugin-macros": "^2.8.0",
    "babel-plugin-react-intl": "^5.1.18",
    "babel-plugin-styled-components": "^1.10.7",
    "eslint": "6.3.0",
    "eslint-config-airbnb-base": "14.0.0",
    "eslint-config-defaults": "9.0.0",
    "eslint-config-prettier": "6.3.0",
    "eslint-config-xo": "0.26.0",
    "eslint-loader": "3.0.0",
    "eslint-plugin-flowtype": "4.3.0",
    "eslint-plugin-flowtype-errors": "4.1.0",
    "eslint-plugin-import": "2.18.2",
    "eslint-plugin-jest": "22.17.0",
    "eslint-plugin-jsx-a11y": "6.2.3",
    "eslint-plugin-prettier": "3.1.0",
    "eslint-plugin-react": "7.14.3",
    "eslint-plugin-react-hooks": "2.0.1",
    "eslint-plugin-require-path-exists": "1.1.9",
    "flow-bin": "^0.119.1",
    "prettier": "1.19.1",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-is": "^16.12.0",
    "styled-components": "4.4.1",
    "webpack": "^4.41.6",
    "webpack-cli": "^3.3.11"
  }
}


```

**Comment by probablyup** [comment]
There’s no way to tell from package.json alone. You have to debug it with your package manager. The easiest way is to use the yarn “resolutions” package.json field which will consolidate the installed version of a package accordingly.

**Comment by samheutmaker** [comment]
I'm having a similar issue with 5.0.1. I downgrade my application and external component library to 4.4.1 and now none of the styles are rendering. Any ideas?

**Comment by delijah** [comment]
Actually we are facing this issue when using webpack and try to import a module (via `require.context`) that uses `styled-components` inside a `useMemo` call.

```
const pluginsContext = require.context(
    './plugins',
    true,
    /\/index\.(js|ts|tsx)$/,
);

const getPluginModulePath = (pluginName) =>
    pluginsContext
        .keys()
        .find(
            (path) =>
                path.endsWith(`/${pluginName}/index.js`) ||
                path.endsWith(`/${pluginName}/index.ts`) ||
                path.endsWith(`/${pluginName}/index.tsx`)
        );

const getPluginModule = (name) => {
    const modulePath = getPluginModulePath(name);

    if (modulePath) {
        const module = pluginsContext(modulePath);

        if (typeof module.default === 'function') {
            return module.default;
        }
    }
};

const plugin = useMemo(() => getPluginModule('paragraph'), []);
```

**Comment by lipeavelar** [comment]
I'm facing this same issue.

I'm creating a pretty simple component library using `styled-components` and it works if I publish it and add on my testing project, but if I link or install the local package, it throws the invalid hook call error.

I tried all solutions above and I'm not using hooks on my lib. Any news about this issue?

**Comment by EduardAkhmetshin** [comment]
@lipeavelar when you install local packages, they are just being copied without filtering with their node_modules folders inside. So you need to manually remove them.
<img width="249" alt="Снимок экрана 2020-04-23 в 15 06 48" src="https://user-images.githubusercontent.com/13064367/80097584-34fe4100-8574-11ea-8228-34f52beeb204.png">

**Comment by ryuk3t** [comment]
Thanks @lipeavelar
works solution:
when we use yarn to install local packages
```json
# package.json
  "dependencies": {
    "@bit/scope.test": "file:./components/test"
  },
```
- after `yarn` 
- remove the unused packages under `./components/test/node_modules` based on `./components/test/package.json`
- then `yarn && yarn start`

**Comment by oncet** [comment]
Same issue here using `styled-components@5` and `enzyme`'s `shallow()`. Switched to `mount()` and is working fine.

**Comment by dale-french** [comment]
Same issue here with `styled-components@5` and `next@9`

**Comment by gmonte** [comment]
Same issue here with styled-components v5

**Comment by alexmassicott** [comment]
This same problem happened with me trying to use a local component library.

I solved it by linking the react package from the site folder 
And linking it in the component library folder.

Npm link react

Problem happened because local packages are using two different versions of react, running npm link fixes that issue.

**Comment by ElongatedMusketeer** [comment]
> @lipeavelar when you install local packages, they are just being copied without filtering with their node_modules folders inside. So you need to manually remove them.
> <img alt="Снимок экрана 2020-04-23 в 15 06 48" width="249" src="https://user-images.githubusercontent.com/13064367/80097584-34fe4100-8574-11ea-8228-34f52beeb204.png">

On unix it creates an alias using ``ln`` command when using packages locally. Deleting unused ``node_modules`` affects the source since it's not "copied" and far from ideal.

```json
"dependencies": {
    "@scope/package-name": "file:.."
}
```

**Comment by Carrein** [comment]
Same issue here. Trying to build a local component library to use with my local application.
Everything works fine i.e. `rollup`, `yarn link` until I add the `styled-component` library.
Currently as some users mentioned above, deleting the `node_module` folder is the only way I could get it to work.

**Comment by enginustun** [comment]
Same issue here. I am creating a component library and testing it locally by linking. 
My temporary solution is: 

- Rename the `node_modules`  file as `node_modulesx` in component library, 
- **restart** other project which uses linked component library. 
- Rename `node_modulesx` to `node_modules` again and continue development and build phases in component library project. 
- Refresh the page and test components on other project's ui.

**Comment by cieldon32** [comment]
this issue is not ok, cant be closed.
I change the version to 4.4.1, everything is ok

**Comment by sadnessOjisan** [comment]
I have same trouble with styled-components v5.2.0. 
Now I'm creating component library.
after publish, imported component emit that error (invalid hook call errors...)

**Comment by chshouyu** [comment]
> this issue is not ok, cant be closed.
> I change the version to 4.4.1, everything is ok

+1，I am developing a react package and use npm link in another project to test it. 4.4.1 work well. does this look like a bug in version 5?

**Comment by probablyup** [comment]
The issue is one or more libraries are being duplicated due to the symlink (node doesn't understand that a linked version of a library and a normal one are the same.) Using a hard link instead would fix the issue, though I'm not sure any package managers other than what pnpm do so

**Comment by alexmassicott** [comment]
> The issue is one or more libraries are being duplicated due to the symlink (node doesn't understand that a linked version of a library and a normal one are the same.) Using a hard link instead would fix the issue, though I'm not sure any package managers other than what pnpm do so


You can do it also with webpack 

With aliases, resolve react to be the path of your node_modules/react in your project directory

**Comment by probablyup** [comment]
@alexmassicott That should definitely help, if you alias react, react-dom, and potentially react-is.
