### ISSUE TITLE
Flow errors in types for styled-components@5.0.1

### ISSUE THREAD

**Issue by mark-mullins** [styled-components/styled-components#3048]
## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`

## System:
 - OS: macOS Mojave 10.14.6
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 450.89 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 12.10.0 - ~/.nvm/versions/node/v12.10.0/bin/node
 - Yarn: 1.22.0 - /usr/local/bin/yarn
 - npm: 6.13.7 - ~/.nvm/versions/node/v12.10.0/bin/npm
## npmPackages:
 - styled-components: ^5.0.1 => 5.0.1 

## Steps to reproduce
Run `flow-typed install styled-components@5.0.1` in the terminal.

## Expected Behavior

Flow typed are created with no errors.

## Actual Behavior

The following Flow errors are present: 
`Cannot resolve name `React`. Flow(InferError)[102, 16]`
`Cannot resolve name `P`. Flow(InferError)[422, 32]`
`Cannot resolve module `styled-components`. Flow(InferError)[448, 10]`

**Comment by probablyup** [comment]
We don't ship flow types from this library, please find the relevant typing repository.
