### ISSUE TITLE
time to breaking DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS

### ISSUE THREAD

**Issue by mochorak** [styled-components/styled-components#3049]
**is it time to breaking?**
The name DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS makes it clear that this is not a use-case fully support at the moment and that you should expect breaking changes at any time.

I think that breaking happened in version 5, what should be we do about the migration when we need that in the config because without that I get the error "JavaScript heap out of memory" I running snapshot test with jest in react.

`
__DO_NOT_USE_OR_YOU_WILL_BE_HAUNTED_BY_SPOOKY_GHOSTS.StyleSheet.reset(true);
`

**Comment by mochorak** [comment]
Thank you for the response soon.
I can't find any documentation about this change. let me know the new name, please.

**Comment by probablyup** [comment]
We don’t document it because it’s not part of the public API. You can
easily inspect the source code on github

**Comment by chorakchi** [comment]
Nice, I find that and that change to "__PRIVATE__" name
and StyleSheet object is in it but reset method is not on there
 needed that for reset the internal "master" instance to avoid get the error out of memory when running snapshot test

I guess that method removed.
is there any alternative for that?

I need a thing same that >> `__PRIVATE__.StyleSheet.reset(true);`

**Comment by mochorak** [comment]
Nice, I find that and that change to` __PRIVATE\__` name
and StyleSheet object is in it but reset method is not on there
needed that for reset the internal "master" instance to avoid get the error out of memory when running snapshot test

I guess that method removed.
is there any alternative for that?

I need a thing same that >> `__PRIVATE__.StyleSheet.reset(true);`

**Comment by probablyup** [comment]
Use `masterSheet.reset(true)`

If you're using jest, there is a styled-components integration that should do this for you.

**Comment by mochorak** [comment]
### The reset method does not exist also in masterSheet object !

```javascript
 FAIL  src/modules/components//TimeSelector.component.test.js
  ● Test suite failed to run

    TypeError: _styledComponents.__PRIVATE__.masterSheet.reset is not a function

      1 | import { __PRIVATE__ } from "styled-components";
      2 | 
    > 3 | __PRIVATE__.masterSheet.reset(true);
        |                         ^
      4 | import Enzyme from "enzyme";
      5 | import Adapter from "enzyme-adapter-react-16";
      6 | 
```
