### ISSUE TITLE
Css prop - media queries doesn't work.

### ISSUE THREAD

**Issue by alekslario** [styled-components/styled-components#3050]
## System:
 - OS: Windows 10 10.0.18362
 - CPU: (4) x64 Intel(R) Core(TM) i5-4200M CPU @ 2.50GHz
 - Memory: 1.85 GB / 7.88 GB
## Binaries:
 - Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
 - npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
## npmPackages:
 - babel-plugin-styled-components: ^1.10.6 => 1.10.6
 - styled-components: ^5.0.1 => 5.0.1

## Reproduction
This one doesn't work
```
css={`@media (min-width: 768px) : {
            color: red;
        }
`}
```
and this works ok
```
css={`color: red;`}
```
intended?

**Comment by alekslario** [comment]
Also
```
css`@media (min-width: 768px) : { color: red; }`
```
 doesn't work yet object syntax 
```
{'@media (min-width: 768px)': { color: 'red' }}
```
works. Am I missing something?

**Comment by probablyup** [comment]
There shouldn’t be a colon before the brace

**Comment by alekslario** [comment]
Thanks. :pray:
Works now, apart from pseudo elements. Couldn't figured how to make `&::before` , `&::after` work with css\`\`

**Comment by alekslario** [comment]
nvm...Thanks again.
