### ISSUE TITLE
Typescript types not being inferred correctly when extending a component

### ISSUE THREAD

**Issue by uriklar** [styled-components/styled-components#3051]
I'm extending a component with types (and even providing the props directly to the styled component) and the props are not being inferred correctly.

Thanks!

## Environment
Typescript Codesandbox

## Reproduction
https://codesandbox.io/s/styled-components-extend-typescript-kkwdl

## Expected Behavior
Should show a type error

## Actual Behavior
No type error

**Comment by probablyup** [comment]
Please file this with DefinitelyTyped, we don’t ship the types
