### ISSUE TITLE
[RFC] Remove prop filtering

### ISSUE THREAD

**Issue by probablyup** [styled-components/styled-components#3054]
With the two new API primitives in `shouldForwardProp` and [transient props](https://github.com/styled-components/styled-components/pull/3052) we could drop prop filtering and potentially cut out a decent chunk of bytes from the library.

Codemodding this would be difficult at best... any ideas for how to enable a migration path are appreciated! Ideally we'd want to convert any props that don't match the valid HTML attribute whitelist to transient equivalents, e.g. `color` ➡️`$color`

**Comment by mxstbr** [comment]
I'm not sure this is worth it, the ecosystem churn would be pretty big and it suddenly requires a lot more work for developers using styled-components. I'd prefer we stick with the sensible defaults with escape hatches as we have now. 

That being said, we could expose the un-filtered version as `styled-components/unfiltered` and let developers choose to go down that route if they want to?

**Comment by cloud-walker** [comment]
@probablyup what will potentially be the actual cut in bundle size?
