### ISSUE TITLE
css property broken for React Native

### ISSUE THREAD

**Issue by likern** [styled-components/styled-components#3056]
## System:
 - OS: Linux 5.5 Fedora 31 (Workstation Edition) 31 (Workstation Edition)
 - CPU: (8) x64 Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz
 - Memory: 4.33 GB / 15.56 GB
 - Container: Yes
 - Shell: 5.0.11 - /bin/bash
## Binaries:
 - Node: 10.19.0 - ~/.local/opt/node-v10.19.0-linux-x64/bin/node
 - Yarn: 1.22.0 - ~/.local/opt/node-v10.19.0-linux-x64/bin/yarn
 - npm: 6.13.4 - ~/.local/opt/node-v10.19.0-linux-x64/bin/npm
 - Watchman: 4.9.0 - /usr/bin/watchman
## npmPackages:
 - styled-components: 5.0.1 => 5.0.1 

## Reproduction
I'm using **styled-components** for React Native by utilizing css-prop feature.
So my components looks like this
```typescript
<Text
  css={`
    font-family: Gilroy-SemiBold;
    font-size: 17px;
    color: rgba(68, 82, 95, 1);
    text-align: ${iconName !== undefined ? 'left' : 'center'};
    text-align-vertical: top;
    margin-left: ${iconName !== undefined ? 4 : 0}px;
    margin-right: ${iconName !== undefined ? 20 : 0}px;
  `}>
  {label}
</Text>
```
this worked very well in production until I started adding tests.
Some tests failed with message `Error: [ERROR]: properties [className] are not supported`

In production css props were transpiled (as should be for React Native, which doesn't support **className**) into **style** object which used inside custom components.

But somehow on some tests **css property is transpiled into className**.
This is a link to reproduction https://github.com/likern/styled-components-classname-property

## Expected Behavior
css properties should always be converted into **style** objects for React Native.

## Actual Behavior
sometimes css props are converted into **className** which is not supported by React Native.

Originally submitted bug report styled-components/css-to-react-native#136

**Comment by kitten** [comment]
I believe the `css` prop generally isn't supported in React Native, and the differing import is what's messing up here, but you can request it to be supported on the Babel plugin's repo: https://github.com/styled-components/babel-plugin-styled-components
