### ISSUE TITLE
Feature Request - apply existing classes

### ISSUE THREAD

**Issue by lukejoliat** [styled-components/styled-components#3057]
It might be nice to be able to combine the generate class with any other classes the element has. For example:

`<div class="xasdfs button>Click</div>`

`const StyledButton = styled.div'
   & {
      background: green;
   }
';`

would result in :

`.xasdfs.button { background: green; } `

In the browser. This would be helpful when extending existing libraries to overwrite their stylesheets. Preventing the developer from having to do this explicitly:

`const StyledButton = styled.div'
   &.button {
      background: green;
   }
';`

**Comment by probablyup** [comment]
Not something we’ll build into the library as it’s too specific a use case
and there isn’t enough desire for it.
