### ISSUE TITLE
Upgrade Stylis to v4 once released?

### ISSUE THREAD

**Issue by karlhorky** [styled-components/styled-components#3060]
Would the `styled-components` team be open to upgrading to Stylis v4?

This would allow for things such as correct prefixing of `background-clip: text`, such as the issue reported here: https://github.com/styled-components/styled-components/issues/2237#issuecomment-596564848

The API has apparently "changed dramatically", according to @Andarist's comment: https://github.com/thysultan/stylis.js/issues/132#issuecomment-596570974

**Comment by probablyup** [comment]
Yeah we’ll definitely have a look when it’s ready

**Comment by karlhorky** [comment]
Ok thanks for the answer! If you can advise what would make sense for you, I'm fine with either leaving this open as a placeholder for later or just closing this as "answered".

**Comment by arditti** [comment]
@probablyup do you have update on this issue?
There are some critical bugs in stylis which was fixed in v4

**Comment by probablyup** [comment]
The stylis upgrade is done in the v6 branch

**Comment by arditti** [comment]
> The stylis upgrade is done in the v6 branch
Thanks for the replay!, is there ETA for v6 release?

**Comment by probablyup** [comment]
Not presently, some time next year. Depends on when I have time.

**Comment by kitten** [comment]
Sorry, I'll have to close this for now due to inactivity. In general, this is also an issue that's unrelated to the codebase in this repository itself, so there's not really any way forward to resolve this. In other words, this issue is potentially open-ended, since its resolution is a release / upgrade that's already happened.
