### ISSUE TITLE
[Feature Request] Use the new Nexts js 9.3 static export methods for static CSS generation at build time.

### ISSUE THREAD

**Issue by arpit73** [styled-components/styled-components#3065]
The current way to do server side rendering in Next js requires creating a `_document.jsx` file in the pages directory, it uses Next's `getInitialProps` method which runs at eacg request.

In their latest release [Next 9.3](https://nextjs.org/blog/next-9-3#next-gen-static-site-generation-ssg-support) Next has introduced methods to do static site generation.

Can we use this new functionality to create our `<styles>` at build time.

This would allow the app to render for the first time without any flickers(the app initially loads without any styles and CSS is injected later).

**Comment by kitten** [comment]
This is more of an issue (or question?) for the next.js repository as it doesn’t affect our development. As far as I know the styles-components example on their repository will be unaffected and hasn’t / won’t block static optimisations as the `ServerStyleSheet` is typically only used on the server-side `_document.js`
