### ISSUE TITLE
nesting bug: CSS with inline SVG + pseudo elements or data-attributes selector 

### ISSUE THREAD

**Issue by nevolgograd** [styled-components/styled-components#3074]
## System:
 - OS: macOS 10.15.3
 - CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
 - Memory: 294.83 MB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 10.11.0 - /usr/local/bin/node
 - Yarn: 1.10.1 - /usr/local/bin/yarn
 - npm: 6.9.0 - /usr/local/bin/npm
## npmPackages:
 - styled-components: ^5.0.1 => 5.0.1

You can see that the ::before pseudo-element are rendered on each button, but on the second button not showing up. If you inspect the CSS generated by styled-components, you'll see why. (More details in "Actual Behavior" below.)

https://codesandbox.io/s/styled-components-base-2opl8

## Expected Behavior

```
button::before {
  content:"";
  ...
}

button[data-name="like"]::before {
  background-image: url(here LIKE encoded inline SVG);
}

button[data-name="dislike"]::before {
  background-image: url(here is DISLIKE encoded inline SVG);
}
```

## Actual Behavior

```
button::before {
  content:"";
  ...
}

button[data-name="like"]::before {
  background-image: url(here LIKE encoded inline SVG);
}

button[data-name="like"]::before[data-name="dislike"]::before{
  background-image:url(here is DISLIKE encoded inline SVG);
}
```

I used this SVG encoder, so there are no special characters in a string.
https://yoksel.github.io/url-encoder/

![photo_2020-03-25 11 59 33](https://user-images.githubusercontent.com/17023612/77524841-b9d03f00-6e90-11ea-9eb0-1489490f9aeb.jpeg)

**Comment by nevolgograd** [comment]
It works as expected with non svg urls, but i can't understand what's wrong with encoded one.
What characters can brake parser?

**Comment by nevolgograd** [comment]
Same nesting bug happens with any attribute selector even without pseudo elements:

```
&[data-rate="like"] {
    background-image: url(here is LIKE encoded inline SVG);
}

&[data-rate="dislike"] {
    background-image: url(here is DISLIKE encoded inline SVG);
}
```

![photo_2020-03-25 12 15 26](https://user-images.githubusercontent.com/17023612/77525891-63fc9680-6e92-11ea-88ff-7904569676c9.jpeg)

**Comment by OttlikG** [comment]
You can get around the issue by using `extending styles feature` for the pseudo-elements into Like and Dislike components.

Here is a working example:
https://codesandbox.io/s/styled-components-base-4moi8?file=/index.js

**Comment by nevolgograd** [comment]
@OttlikG Yeah, i know, but in that case i don't need data attributes at all. 

I don't want to write conditions in reusable button rendering, when i can just pass the data-attribute right to the styles. 
Is there any other workaround for it? Is it styled-components issue at all?

**Comment by kitten** [comment]
This is likely an issue with how `stylis` perceives your input there. Generally, you can try to base64 encode with `url('...')` values for instance, but otherwise there isn't much we can do to resolve this. I believe the upgrade to `stylis@4` may fix this though once it's dropped into styled-components.

For now, I'll go ahead and close this, since there's not much we can do to fix this on our end. But rest assured, you're not doing anything wrong, it's likely stylis that in v3 can't parse this.
