### ISSUE TITLE
Latest create-react-app TypeScript and styled-components results in empty theme object

### ISSUE THREAD

**Issue by gabrielrusslq** [styled-components/styled-components#3085]
## System:
 - OS: Windows 10 10.0.18362
 - CPU: (8) x64 Intel(R) Core(TM) i7-2600K CPU @ 3.40GHz
 - Memory: 5.83 GB / 15.96 GB
## Binaries:
 - Node: 12.13.0 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.17.3 - ~\AppData\Roaming\npm\yarn.CMD
 - npm: 6.13.0 - C:\Program Files\nodejs\npm.CMD
## npmPackages:
 - styled-components: ^5.0.1 => 5.0.1

## Reproduction

https://codesandbox.io/s/styled-components-base-gc367

## Steps to reproduce
- `npx create-react-app test-project --template typescript`
- `npm install --save styled-components @types/styled-components`
- Follow TypeScript steps from documentation [HERE](https://styled-components.com/docs/api#typescript)
    - Create a declarations file
    - Create a theme
- Now try and style any component with one of the properties you added in the theme

## Expected Behavior
props.theme should have the properties you added
## Actual Behavior
props.theme is an empty object

**Comment by probablyup** [comment]
I don't see any TS in your linked sandbox, so I assume it's the boilerplate one. We don't maintain the types here, they're over at DefinitelyTyped. I'd recommend filing an issue there or using a help forum like StackOverflow.
