### ISSUE TITLE
Style is broken on a Next.js app 

### ISSUE THREAD

**Issue by lcswillems** [styled-components/styled-components#3086]
## Reproduction

Click on "Miple" on the top left. The page is completely broken:

![image](https://user-images.githubusercontent.com/5437552/78643680-e8004680-78b4-11ea-8963-c29ae420b4bf.png)

If the page is reloaded, it displays correctly:

![image](https://user-images.githubusercontent.com/5437552/78643733-fea69d80-78b4-11ea-95fa-d6a6183de476.png)

## Environment

I use styled-components v5 with Next.js 9.3. The bug was not present in v4

**Comment by probablyup** [comment]
That page doesn't look to be accessible, the link brings me to a login screen that looks ok

**Comment by lcswillems** [comment]
Yes, you are right... I forgot I was login. I will try to create a reproduction

**Comment by dmytro-lymarenko** [comment]
I have the same problem with styled-components@5 and next js: when the app is built (SSR) the styles are not loaded but with styled-components@4 they worked.

**Comment by lcswillems** [comment]
@probablyup I have found another way to show the issue that doesn't require to be logged in. I have updated the issue.

**Comment by ChristopherLMiller** [comment]
experiencing the same thing, havent' backdated to 4 yet but noticed I'm getting unstyled content flash with 5 on my next app.

**Comment by eugeneross** [comment]
@lcswillems Can you share your `_app.js` and `_document.js`?

**Comment by lcswillems** [comment]
I close this issue as I don't have this issue anymore (I did nothing special except updating my code...). I will open a new issue if it happens again and have a real reproduction.
