### ISSUE TITLE
Overriding styles of third party components

### ISSUE THREAD

**Issue by yn5** [styled-components/styled-components#309]
I understood from the following part of the docs: https://github.com/styled-components/styled-components#third-party-components that I should be able to override the styles of a non-styled 'third party' component. This does not seem to have any effect at all.

## Version
1.1.3

## Reproduction
https://github.com/yn5/styled-components-override

## Steps to reproduce
Clone the example repo. Run npm install and npm start.

## Expected Behavior
As coded in `App.js` I would expect the div with the text 'test' to have a red background. Or, if I misunderstood the docs it may be they should be amended.

## Actual Behavior
The style applied to the 'third party' component is not applied.

**Comment by diegohaz** [comment]
Just pass `className` down:
```js
import React from 'react';

export default ({ className }) => (
  <div className={className}>Test</div>
);
```

**Comment by thisguychris** [comment]
@yn5 The 3rd party component should have at least be able to accept a className props. see @diegohaz 's code.

**Comment by yn5** [comment]
@thisguychris @diegohaz Thanks! Missed that.
