### ISSUE TITLE
Prop name 'loading' gives a warning about non-boolean attribute

### ISSUE THREAD

**Issue by davidohlin** [styled-components/styled-components#3090]
I have a button component that I pass a prop called `loading` to. In that component, I use the `loading` prop in a `styled` function. It works, but gives the following warning:
```
Warning: Received `false` for a non-boolean attribute `loading`.
```
What's strange is that naming the prop something else, like `isLoading` or `foo` gives no warning.

Is this a bug? I'll rename the prop `isLoading` for now, but would really like to know why this is happening.

Reproduction: [https://codesandbox.io/s/little-water-ptwjr](https://codesandbox.io/s/little-water-ptwjr)

Thanks!

### System:
 - OS: macOS 10.15.3
 - CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
 - Memory: 2.65 GB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
### Binaries:
 - Node: 10.14.2 - /usr/local/bin/node
 - Yarn: 1.22.4 - /usr/local/bin/yarn
 - npm: 6.13.7 - /usr/local/bin/npm
### npmPackages:
 - styled-components: ^5.0.1 => 5.0.1 

## Reproduction
https://codesandbox.io/s/little-water-ptwjr

## Steps to reproduce
Pass `loading={true}` or `loading={false}` as a prop to a component. Use the passed prop in a styled component.

## Expected Behavior
A usable prop without any warnings.

## Actual Behavior
Styled components gives warning `Warning: Received 'false' for a non-boolean attribute loading'...`

**Comment by probablyup** [comment]
It's not a bug, it's a valid HTML attribute so we allow it pass through to the DOM: https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/loading

When you use camelCased props we generally filter those out because there are only a handful of valid React ones we need to pay attention to.

Relevant docs page: https://styled-components.com/docs/faqs#why-am-i-getting-html-attribute-warnings

**Comment by davidohlin** [comment]
@probablyup My bad, I was quick on the trigger here. Didn't know about the `loading` attribute. Sorry!
