### ISSUE TITLE
Implement shouldForwardProp for native

### ISSUE THREAD

**Issue by probablyup** [styled-components/styled-components#3093]
https://github.com/styled-components/styled-components/releases/tag/v5.1.0

Currently `shouldForwardProp` is only implemented on the web-side of the library. Let's get it added to native as well and add tests. The default prop validator for native can be a function that just returns `true`.

**Comment by yamov** [comment]
That would be amazing. 🙏 

Took me a while to understand it is not yet supported in native. Couldn't get what I was doing wrong.
Can also make sense to add a note about this in the above mentioned ☝️ release notes.

Will apply some workaround for now.

**Comment by macintoshhelper** [comment]
Hi, I've submitted a PR for this. Might make sense to leave the default web prop validator I think? Incase custom/primitives React renderers use commonly used `styled-components` props like `color` or `fontSize` internally, that they then get filtered out.

**Comment by kabala** [comment]
> Hi, I've submitted a PR for this. I've published a temporary fork under `@elemental-design/styled-components` incase anyone's blocked by this and needs to do a Webpack/Babel alias.
> 
> Might make sense to leave the default web prop validator I think? Incase custom/primitives React renderers use commonly used `styled-components` props like `color` or `fontSize` for their internal component API, that they then get filtered out.

Hi

**Comment by kabala** [comment]
> Hi, I've submitted a PR for this. I've published a temporary fork under `@elemental-design/styled-components` incase anyone's blocked by this and needs to do a Webpack/Babel alias.
> 
> Might make sense to leave the default web prop validator I think? Incase custom/primitives React renderers use commonly used `styled-components` props like `color` or `fontSize` for their internal component API, that they then get filtered out.

...
