### ISSUE TITLE
`createGlobalStyle` generate the same id and global style is missing.

### ISSUE THREAD

**Issue by ykan** [styled-components/styled-components#3097]
# Environment
## System:
 - OS: macOS 10.15.3
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 56.37 MB / 32.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 10.19.0 - /usr/local/bin/node
 - Yarn: 1.22.0 - ~/.yarn/bin/yarn
 - npm: 6.13.4 - /usr/local/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.10.6 => 1.10.6
 - styled-components: ^4.3.2 => 4.4.1

## Reproduction
https://codesandbox.io/s/styled-components-base-9w9x5

```tsx

const Style1 = createGlobalStyle`
${props => css`
  .test {
    color: #999;
  }
`}
`;

const Style2 = createGlobalStyle`
${props => css`
  .test {
    background: #000;
  }
`}
`;

const App = () => (
  <div>
    <Style2 />
    <Style1 />
    <div className="test">test</div>
  </div>
);
```
You will see only Style1 is rendered, Style2 is missing.

I found in `styled-components`, the `createGlobalStyle`, the `id` of GlobalStyle is generated by `JSON.stringify(rules)`, if you pass functions, you will see `rules` like this `['\n', f..., '\n']`, and `JSON.stringify(rules)` will return the same `["\n  ",null,"\n"]`.

## Expected Behavior
different rules generate different id.

## Actual Behavior
different rules generate the same id.

## Solution

```tsx

const Style1 = createGlobalStyle`
// add id of this global style using comment, id * global style name *
${props => css`
  .test {
    color: #999;
  }
`}
`;
```

**Comment by xxn520** [comment]
hulp!

**Comment by littlecold233** [comment]
same problem

**Comment by natterstefan** [comment]
Short excursion: Do you also experience this issue https://github.com/styled-components/styled-components/issues/3076? I just wanna know if other developers see this too. Thanks :)

**Comment by ykan** [comment]
> Short excursion: Do you also experience this issue #3076? I just wanna know if other developers see this too. Thanks :)

We have not upgraded to v5 yet.
