### ISSUE TITLE
Objects are not valid as a React child when not using backticks after .attrs

### ISSUE THREAD

**Issue by MelMacaluso** [styled-components/styled-components#3099]
I tried to search the docs, asked StackOverflow and searched the issues but I didn't come up with a satisfactory answer (maybe is me doing something silly ahah). 

Context:
```
    "styled-components": "^5.0.1",
    "@babel/core": "^7.9.0",
    "@storybook/addon-actions": "^5.3.18",
    "@storybook/addon-knobs": "^5.3.18",
    "@storybook/addon-links": "^5.3.18",
    "@storybook/addons": "^5.3.18",
    "@storybook/preset-create-react-app": "^2.1.1",
    "@storybook/react": "^5.3.18",
    "babel-loader": "^8.1.0",
    "css-loader": "^3.5.0",
    "react": "^16.13.1",
    "react-dom": "^16.13.1",
    "sass-loader": "^8.0.2",
    "style-loader": "^1.1.3"
```

I have the following simple `styled-component`:

```js
const Button = styled.bytton.attrs(({primary}) => ({
  className: primary ? 'something' : 'something-else'
})
```

Now for some reason unless I append the backticks in the ed such as:

```js
const Button = styled.bytton.attrs(({primary}) => ({
  className: primary ? 'something' : 'something-else'
})`` // here
```

I will get an error from storybook:

>Objects are not valid as a React child (found: object with keys {$$typeof, render, attrs, >componentStyle, displayName, foldedComponentIds, styledComponentId, target, withComponent, >warnTooManyClasses, toString}). If you meant to render a collection of children, use an array >instead.

Ideally, I would like to avoid inserting an empty template literal in the codebase just to suppress the error...

**Comment by endway** [comment]
@MelMacaluso `styled()` returns a template function, which needs to be executed. And backticks are doing that (that's not a simple template string, it's tagged template).
You can try to call it instead, like so `styled()({})`. But it still necessary AFAIK.

**Comment by kitten** [comment]
Yep, the above is the right answer here.
`attrs` is a method that in turn doesn’t return a new `StyledComponent` (there’s no static `attrs` method on those) but a styled function that creates that component

**Comment by unicornware** [comment]
> Yep, the above is the right answer here. `attrs` is a method that in turn doesn’t return a new `StyledComponent` (there’s no static `attrs` method on those) but a styled function that creates that component

@kitten that being said, is it not possible to use `attrs` with [style objects][1]?:

```typescript
const Input = s.input.attrs<Props>(attrs)<Props>(styles, system)
```

**all** of my imports are correct, but anytime i run my test suites i get the following error:

```zsh
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

the error isn't consistent across components either. if i run the same tests again, i'll get errors in different component tests. 

[1]: https://styled-components.com/docs/advanced#style-objects
