### ISSUE TITLE
Feature request: option to prepend style rules with component names

### ISSUE THREAD

**Issue by synchronos-t** [styled-components/styled-components#3103]
The `displayName` option is great and helps the DOM readability a lot. However, currently the actual style rules, the CSS, is outputted using only the hashed names. E.g., if I have a component, it's in the DOM as something like this:
```
<div class="myFile__MyComponent-asdf12 qwer98">
```
But the CSS will look like this:
```
.qwer98 {
  /* rules */
}
```
It would be easier to read the styles in the browser, if they'd also get prepended with the component name, as that's the one I've written in the code and that's what my eye tries to seek, not a random hash, when I'm debugging. For instance, when overriding Material UI components, the rule list is full of different classes and rules, so it's not always trivial to find the one you've put the with styled-components.

Naturally, this could be an opt-in option that you could set in the .babelrc, and only for development, if one so wishes (probably does).

**Comment by kitten** [comment]
I don't think this is something we'd particularly want to do. Generally, the names are always available and a class always corresponds with a single component, which you'll likely have available if you're looking at the rules. This is of course unless you're looking at CSS output. However, I believe looking at the CSS output of styled-components without the HTML/DOM contents isn't going to be a particularly pleasant experience.
