### ISSUE TITLE
Trouble with event bubbling

### ISSUE THREAD

**Issue by sldone** [styled-components/styled-components#3115]
Hi everyone! I have problem with passing events in styled component. When I pass two handlers `onClick` for parent and child component. Will trigger both of them and I need pass somethinkk like that 
```
<SomeComponent onClick={(event) => {
    event.stopPropagation();
    ...
}}/>
```

I think it's not typical behavior for React components based on `styled-components`

## System:
 - OS: macOS 10.15.4
 - CPU: (4) x64 Intel(R) Core(TM) i5-6267U CPU @ 2.90GHz
 - Memory: 247.02 MB / 8.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 12.7.0 - ~/.nvm/versions/node/v12.7.0/bin/node
 - Yarn: 1.21.1 - /usr/local/bin/yarn
 - npm: 6.10.0 - ~/.nvm/versions/node/v12.7.0/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman

## Reproduction

https://codesandbox.io/s/vigorous-monad-tf89h?file=/src/TestComponent.jsx

## Steps to reproduce

1. Click to Child component

## Expected Behavior

Trigger event only for a child component

## Actual Behavior

Trigger events for child and parent components

**Comment by iDuuck** [comment]
That is the typical behavior how the DOM works. You may need to check if the inner component was clicked, based on the `event`'s target. But this is a case for Stackoverflow.

**Comment by sldone** [comment]
I know about how DOM works. But I thought that in React we don't need to use something like `event.stopPropagation()`. It's my mistake. I think I'll close the issue.
