### ISSUE TITLE
Doesn't support passing of react native's Animated.Value

### ISSUE THREAD

**Issue by resting** [styled-components/styled-components#3119]
I have the below component, but the bottom value never gets updated.
Might save time for others trying to do the same thing.

```javascript
<StyledView as={Animated.View} bottomValue={value} {...props}>
</StyledView>

const StyledView = styled.View`
  position: absolute;
  height: 300;
  bottom: ${p => p.bottomValue.__getValue()};
  background-color: ${Styles.navBgColor};
  width: 100%;
  elevation: 3;
  border-top-left-radius: 20;
  border-top-right-radius: 20;
  shadow-color: #ccc;
  shadow-offset: {
    width: 1;
    height: 1;
  }
  shadow-opacity: 0.8;
  shadow-radius: 2px;
`;
```

Using `Animated.View` with inline style worked.

```javascript
    <Animated.View
      style={{
        position: 'absolute',
        height: props.bottomHeight,
        bottom: props.value,
        backgroundColor: Styles.navBgColor,
        width: '100%',
        elevation: 3,
        borderTopLeftRadius: 20,
        borderTopRightRadius: 20,
        shadowColor: '#ccc',
        shadowOffset: {
          width: 1,
          height: 1,
        },
        shadowOpacity: 0.8,
        shadowRadius: 2,
      }}>
```

**Comment by BennoDev1** [comment]
I have got the same issue..

**Comment by gsevla** [comment]
Same here! =/

**Comment by kitten** [comment]
Long standing issue, as the implementation is currently frozen for the RN feature, which may have to eventually become a separate package, if it is to implement new features of its own. I know this isn't resolved, but it's unlikely to be addressed as its a known limitation of the current implementation.

The current implementation needs to stringify CSS before it processes it, which means that all dynamic values become strings, including animated values. Hence, they still have to be passed as separate styles.
