### ISSUE TITLE
border-left (bottom, top or right) shorthand doesn't work like border shorthand in RN + SC

### ISSUE THREAD

**Issue by hadnet** [styled-components/styled-components#3127]
I'm using RN + SC. But when I'm using border-left (bottom, top or right) shorthand like this `border-left: 1px solid red;` it doesn't work like border shorthand (border: 1px solid red) and I got an error. I need to do border-left-color: red; border-left-style: solid; border-left-width: 1px;. Why not make it like it works in border shorthand?

**Comment by kitten** [comment]
I'm not sure whether this was reported or resolved there, but issues regarding the CSS transformation in React Native are resolved and filed here: https://github.com/styled-components/css-to-react-native/issues?q=is%3Aissue+border+shorthand+is%3Aclosed
