### ISSUE TITLE
Feature Request: Allow two different elements with the same styles

### ISSUE THREAD

**Issue by rwacarter** [styled-components/styled-components#3128]
I have a `Button` component (in React) which can either be a `button` or an `a` element, depending on if a `href` prop is passed to the component. Something similar to below:
```
const Button = ({ children, href, onClick }) => {
    if(href) {
        return <a href={href} onClick={onClick}>{children}</a>;
    }

    return <button type="button" onClick={onClick}>{children}</button>;
};
```
I previously used Sass to style these components, but am now attempting to move over to styled-components. However, I have come across an issue where these two elements require the same styles, but the syntax of styled-components would require me to create to separate variables - `styled.button` and `styled.a`, with duplicated styles for each.

I would propose being able to pass a function with an element's props as the first argument, to allow a developer to decide which element should be used. Something similar to this:
```
const StyledButton = styled((props) => props.href ? 'a' : 'button')`
    ...
`;
```
An important feature of CSS is that styles and elements are not tied together. The example above shows that styled-components currently does have this issue, but I believe that my solution (or something similar) would allow for separation of element and styles.

**Comment by konstantin-chukharev** [comment]
You could use `as` prop: https://styled-components.com/docs/api#as-polymorphic-prop

Or use `className` prop:
```
const Button = ({ className, children, href, onClick }) => {
    if(href) {
        return <a href={href} className={className} onClick={onClick}>{children}</a>;
    }

    return <button type="button" className={className} onClick={onClick}>{children}</button>;
};

...

const StyledButton = styled(Button)`
    ... styles
`;
```
