### ISSUE TITLE
Feature request: Rewrite Styled Components to use TypeScript instead of Flow

### ISSUE THREAD

**Issue by dawidk92** [styled-components/styled-components#3129]
Since the vast majority of developers have projects written in TypeScript instead of Flow, I would like to start a discussion about rewriting Styled Components to use TypeScript natively.

Right now we have typings written in DefinitelyTyped repository but they are maintained by a different team and thus it has its issues. When the new release of Styled Components comes out, we as the developers have to wait quite a long time for DefinitelyTyped team to catch up with it so we could finally implement it in our projects.

Besides that, there's a lot of issues that probably could be caught and resolved on time of development, if we would have the project written in TypeScript. Right now DefinitelyTyped has over 40 issues related to Styled Components. For example one of them is over 1 year old, has over 130 votes and is still open: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33311

I'm aware that rewriting the whole project to use TS is a big task but since TypeScript is becoming a major programming language in web development and Styled Components is the biggest CSS-in-JS library maybe it will be worthy of consideration to rewrite it and release in some future major version?

Because of that developers:
- could implement Styled Components immediately after release in their projects and catch some potential issues on early stages
- would have a better experience working with TypeScript
- wouldn't switch to another CSS-in-JS library because of that issue anymore

**Comment by filipcro** [comment]
Somebody seriously needs to fix DefinitelyTyped/DefinitelyTyped#33311 Otherwise this library is almost useless with typescript projects.

**Comment by techieshark** [comment]
As someone who uses Flow (as well as TS), I really have no problem with this library using Flow. ;-)

**Comment by kitten** [comment]
Rewriting something isn't a feature request. While we are currently working on a TypeScript rewrite that's neither a feature nor a simple request 😅 Closing and locking, since I know we do get a lot of TS-related issues re. the typings in definitely-typed, which isn't controlled from this repo.
