### ISSUE TITLE
Overwrite rules instead of duplication of rules.

### ISSUE THREAD

**Issue by iamrane** [styled-components/styled-components#313]
This is a feature suggestion that instead of duplication of rules when overriding styled-components should overwrite them.

Ex:
```
const Button = styled.button`
   height: 10px;
   background: red;
`;
const BlueButton styled(Button)`
   background: blue;
`;
```

The result on the BlueButton should be
```
height: 10px;
background: red;
```

Today its

```
height: 10px;
background: red;
background: blue;
```

This is just a suggestion. Makes the result a little bit nicer :)

**Comment by k15a** [comment]
Isn't that something like this?
https://github.com/styled-components/styled-components/issues/263

I don't think it's really worth the work unless it's really easy to implement :)
