### ISSUE TITLE
[docs] API Reference - TypeScript React-Native example

### ISSUE THREAD

**Issue by dakshshah96** [styled-components/styled-components#3131]
_I haven't used the bug report template here since this is not really a bug but something that can be improved in the documentation._

# Problem

I'm currently trying to setup styled-components on a React Native TypeScript project. The [documentation](https://styled-components.com/docs/api#typescript) on setting this up seems very convoluted in its current state—especially for React Native.

For example, this is the code block for React Native under the heading **Create a theme**:

```js
// styled-components.ts
import * as styledComponents from "styled-components/native";

import ThemeInterface from "./theme";

const {
  default: styled,
  css,
  ThemeProvider
} = styledComponents as styledComponents.ReactNativeThemedStyledComponentsModule<ThemeInterface>;

export { css, ThemeProvider };
export default styled;
```

Here, a reader doesn't know what `ThemeInterface` or the `./theme` file is since these names haven't be used in the previous steps. I haven't been able to set this up myself since I don't know what these are.

# Proposed solution

In my opinion, it'd be really helpful for beginners if the docs can have separate sections for React and React Native TypeScript setups.

If the maintainers agree, I'd also be happy to contribute to the docs.

**Comment by dakshshah96** [comment]
I'll open this issue on the styled-components docs website repo. Sorry about this!

**Comment by wmonk** [comment]
@dakshshah96 did you get setup in the end, I'm struggling with this too.

**Comment by dakshshah96** [comment]
@wmonk Nope, I lost hope and dropped it. Let me know if you manage to get this running somehow!

**Comment by ManAnRuck** [comment]
@wmonk @dakshshah96 you can try to downgrade typescript to 3.8.3 to fix this issue.
I did reproduce this issue by upgrading from 3.8.3 to 3.9.3 after downgrading, it works again.
