### ISSUE TITLE
using the `as` prop breaks typescript typings.

### ISSUE THREAD

**Issue by hainessss** [styled-components/styled-components#3133]
#2338  Environment
 - OS: macOS 10.15.2
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
 - Memory: 38.19 MB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 13.7.0 - /usr/local/bin/node
 - Yarn: 1.22.4 - ~/Code/parsable-ui/node_modules/.bin/yarn
 - npm: 6.13.6 - /usr/local/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.10.7 => 1.10.7 
using styled-components@5.1.0 
@types/styled-components": "5.1.0
vscode 1.44

I am not sure this is the right place for this. But I have tried everything and do not know how to proceed.

Problem: 
using the `as` prop seems to break typescript typings.

## Reproduction

```
interface Props {
  color?: 'blue' | 'red';
};

interface WithBoxy {
  as?: keyof JSX.IntrinsicElements | React.ComponentType<any>;
}

const Boxy = styled.div<Props>`
  width: 50px;
  height: 50px;
`;
 
const WithBoxy = ({ as = 'div' } : WithBoxy) => {
  return <Boxy as={as} color='blue'>hey</Boxy>;
};
```

## Expected Behavior
I should see type populate:
![image](https://user-images.githubusercontent.com/6373177/81035727-17bd5280-8e51-11ea-9aca-2061f8eb0966.png)

## Actual Behavior
I see this instead:
![image](https://user-images.githubusercontent.com/6373177/81035758-3facb600-8e51-11ea-86c8-909a03f5931c.png)

**Comment by melihberberolu** [comment]
@hainessss what is your solution fixing as type error ?
I'm try to add type like ```as?: keyof JSX.IntrinsicElements | React.ComponentType<any>;```
but getting type error.
