### ISSUE TITLE
Severe slowdown in hydrate in SC5

### ISSUE THREAD

**Issue by perenstrom** [styled-components/styled-components#3138]
We're experiencing some severe slowdowns on our site when switching to Styled Components 5. The Hydrate call in react is going from about 500ms when running environment=development, to a whopping 5-6 seconds when switching to production.
In development we saw a small decrease in render time when switching to SC5, but when switching to production the times went through the roof.

We have a node+express SSR react app running React 16.13.1. And see the same in both node 8 and 10.

Any input into why this might happen?

### Binaries:
 - Node: 10.19.0 - ~/.nvm/versions/node/v10.19.0/bin/node
 - Yarn: 1.21.1 - ~/.yvm/versions/v1.21.1/bin/yarn
 - npm: 6.13.4 - ~/.nvm/versions/node/v10.19.0/bin/npm
### npmPackages:
 - babel-plugin-styled-components: ~1.10.6 => 1.10.6
 - styled-components: 5.1.0 => 5.1.0

**Comment by probablyup** [comment]
Honestly not sure, most people upgrading report the opposite so I suspect it has something to do with your application setup or how you're using s-c.

**Comment by perenstrom** [comment]
Any pointers to what kind of application setups or usage that might be worse to use?

**Comment by kitten** [comment]
No, it looks to me like you’ll have to profile and benchmark this, because it’s; as far as we know, an outlier result.

It may be beneficial to just record the load time and investigate the stack trace in production to see what’s going on.

**Comment by kitten** [comment]
The latest reply regarding rehydration performance is here, and there's one larger issue in Chromium that basically throws the numbers off and will make this a little bit of a tricky picture. See: https://github.com/styled-components/styled-components/issues/3518#issuecomment-888356417
