### ISSUE TITLE
<Styled(undefined)... and new styling not being applied

### ISSUE THREAD

**Issue by IljaDaderko** [styled-components/styled-components#314]
I've tried overwrite / add styling to existing component in the following way:

```
const StyledImageUploadInput = styled(ImageUploadInput)`
  height: 200px;
`;
```

And added Styled component where appropriate, it renders the component fine, but doesn't seem to apply new styling, I think related issue is that using react tools to inspect it, it seems like `ImageUploadInput` is undefined for styled i.e

![Example](http://i.imgur.com/D7YEIBr.png)

**Comment by k15a** [comment]
Did you passed the className down?

**Comment by mxstbr** [comment]
This definitely sounds like a case of not-passing-the-classname-down. 😉 What's undefined in the React DevTools here is the `displayName` of the `ImageUploadInput` – try setting `ImageUploadInput.displayName` and you should see it in there!

**Comment by tulanowski** [comment]
I've encountered the same problem. Here is example:
```javascript
const styled = styled.default;

class SomeComponent extends React.PureComponent {
  render() {
    return (<span>some component</span>);
  }
}

const StyledSomeComponent = styled(SomeComponent)`
   background-color: red;
`;

const StyledDiv = styled.div`
   background-color: green;
`;
                               
ReactDOM.render(
   <div><StyledSomeComponent /><StyledDiv>div</StyledDiv></div>, 
   document.getElementById("root")
);
```

It renders green background under div, but no red background under 'some component'. I think that real problem here is that the styles are not applied. `Styled(undefined)` is not a problem, because it's caused by missing `displayName`.

**Comment by k15a** [comment]
Just pass the className down to the component.

```JS
class SomeComponent extends React.PureComponent {
  render() {
    return (<span className={this.props.className}>some component</span>);
  }
}
```

**Comment by tulanowski** [comment]
Ah! Thanks! :)
