### ISSUE TITLE
Use Media Query with `styled-components/native`

### ISSUE THREAD

**Issue by heshamabdallah** [styled-components/styled-components#3141]
we are working on a base code for both web and mobile and we use RN components as a shared package between them, I used `styled-components/native` for components styling but the **Media Queries** doesn't work for web! I know RN is aimed to be used for mobile only but nowadays we have [React Native Web](https://github.com/necolas/react-native-web) which makes possible to use RN with React Dom! I see there is a PR here #489 to use **Media Queries** with `styled-components/native` and we really need this feature! would you plz fix this issue ?

**Comment by wagnercsfilho** [comment]
I need this feature, too!

**Comment by kitten** [comment]
We aren't really interested currently in adding non-StyleSheet-based APIs to styled-components' react-native implementation. If anything, it's currently being considered as an "outlier" feature that should probably become its own package, at which point these kinds of things would become more interesting and achievable.
