### ISSUE TITLE
boolean prop needs to be declared explicitly

### ISSUE THREAD

**Issue by EliasTouil** [styled-components/styled-components#3143]
I think I found a bug. 

## Environment
CRA
```json
"dependencies": {
    "...":"...",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "styled-components": "^5.1.0",
  }
```

## Steps to reproduce

```javascript
const StyledNav = styled.nav`{
    color: ${props => props.truthValue ? "white" : "black"}
}
```

```javascript
const Nav = () => <StyledNav truthValue />
```

## Expected Behavior
I should be able to use props.truthValue in styled component

## Actual Behavior
I can't 

It will work if I declare it explicitly
```javascript
const Nav = () => <StyledNav truthValue={truthValue} />
```

Thank You <3

**Comment by Junoburger** [comment]
Shouldn't it be wrapped in backticks instead of brackets?

```
 const StyledNav = styled.nav`
    color: ${props => props.truthValue ? "white" : "black"}`
```

**Comment by Junoburger** [comment]
When I reproduce it, the styled-component gives a 
`Parsing error: Unterminated template`

**Comment by EliasTouil** [comment]
Hello @Junoburger thanks you for the fast answer ! 

I just realized the mistake I made.
I can't set truthValue to false, writing truthValue as a tag attribute will always result in truthiness.
