### ISSUE TITLE
styled-components not working with create-react-library

### ISSUE THREAD

**Issue by RoyPog** [styled-components/styled-components#3145]
Here is my stackoverflow question: https://stackoverflow.com/questions/61854712/styled-components-not-working-with-create-react-library

I'm trying to import styled-components in a create-react-library module. However, when i run it I get the following error message:

```
Error: 'typeOf' is not exported by node_modules\react-is\index.js, imported by node_modules\styled-components\dist\styled-components.browser.esm.js

at C:\Users\roypo\Projects\Web Development\wiit-ui\node_modules\styled-components\dist\styled-components.browser.esm.js:1:9

1: import { typeOf, isElement, isValidElementType } from 'react-is';
            ^
2: import React, { useState, useContext, useMemo, useEffect, useRef, createElement, useDebugValue } from 'react';
3: import shallowequal from 'shallowequal';
```
I import styled-components like:

`import styled from 'styled-components'`

I added it to both the peerDependencies and devDependencies (and the regular dependencies) as follows:

```
//code above

"peerDependencies": {
        "react": "^16.0.0",
        "styled-components": "^5.1.0"
    },
    "devDependencies": {
        "microbundle-crl": "^0.13.10",
        "babel-eslint": "^10.0.3",
        "cross-env": "^7.0.2",
        "eslint": "^6.8.0",
        "eslint-config-prettier": "^6.7.0",
        "eslint-config-standard": "^14.1.0",
        "eslint-config-standard-react": "^9.2.0",
        "eslint-plugin-import": "^2.18.2",
        "eslint-plugin-node": "^11.0.0",
        "eslint-plugin-prettier": "^3.1.1",
        "eslint-plugin-promise": "^4.2.1",
        "eslint-plugin-react": "^7.17.0",
        "eslint-plugin-standard": "^4.0.1",
        "gh-pages": "^2.2.0",
        "npm-run-all": "^4.1.5",
        "prettier": "^2.0.4",
        "react": "^16.13.1",
        "react-dom": "^16.13.1",
        "react-scripts": "^3.4.1",
        "styled-components": "^5.1.0"
    },
    "dependencies": {
        "styled-components": "^5.1.0"
    }

```

(it's not intended, it's just a formatting problem)

It works fine when I use just create-react-app.

How can I fix it? Thanks in advance

**Comment by poteirard** [comment]
You have `styled-components` in `dependencies` in `devDependencies`. Maybe that's the issue? I think it should be in "dependencies" unless you are creating a react component library which then it should be in "peer" and "devDeps"

You can try creating a repo to reproduce it. I did a small code sandbox and it seems it works as expected.

**Comment by RoyPog** [comment]
Did you mean `dependencies` and in `devDependencies`?

**Comment by poteirard** [comment]
Sorry. I edited the comment.

**Comment by shpyo** [comment]
Do you have `react-is` installed? What `npm list react-is` gives in terminal?

**Comment by PraveenVerma17** [comment]
@shpyo  Did you solve this issue? I am also facing same issue also updated react-is but still getting same error. Its really frustrating.

**Comment by shpyo** [comment]
> @shpyo Did you solve this issue? I am also facing same issue also updated react-is but still getting same error. Its really frustrating.

You have to install `react-is` SC requires it. I don't have such issue.

**Comment by PraveenVerma17** [comment]
@shpyo i installed react-is also but still getting same issue.

**Comment by jestrickler** [comment]
I'm having the same issue with styled-components and create-react-library or specifically microbundle-crl (rollup?)

```
> microbundle-crl --no-compress --format modern,cjs

Error: 'typeOf' is not exported by node_modules/react-is/index.js, imported by node_modules/styled-components/dist/styled-components.browser.esm.js

at /Users/stri40/Development/react-components/node_modules/styled-components/dist/styled-components.browser.esm.js:1:9

1: import { typeOf, isElement, isValidElementType } from 'react-is';
            ^
2: import React, { useState, useContext, useMemo, useEffect, useRef, createElement, useDebugValue } from 'react';
3: import shallowequal from 'shallowequal';
```
react-is is in node_modules/ and it looks like typeOf is exported
```
$ npm ls react-is
react-components@1.0.0 /Users/stri40/Development/react-components
├─┬ prop-types@15.7.2
│ └── react-is@16.13.1 
├─┬ react-bootstrap@1.3.0
│ └─┬ prop-types-extra@1.1.1
│   └── react-is@16.13.1  deduped
├─┬ react-scripts@3.4.1
│ └─┬ jest@24.9.0
│   └─┬ jest-cli@24.9.0
│     └─┬ jest-config@24.9.0
│       └─┬ pretty-format@24.9.0
│         └── react-is@16.13.1  deduped
└─┬ styled-components@5.1.1
  └─┬ hoist-non-react-statics@3.3.2
    └── react-is@16.13.1  deduped
```


I did find that if I ONLY included it in peerDependencies, the library would build, and I could use it an external app, but then you can't have tests for the components in the library.

**Comment by jestrickler** [comment]
Try removing it from dependencies, so it is only in peerDependencies and devDependencies. I finally got it working this way. You probably also have to remove node_modules and package-lock.json and redo npm install.

**Comment by RoyPog** [comment]
Thanks everyone!

**Comment by cieldon32** [comment]
but :
error  'styled-components' should be listed in the project's dependencies, not devDependencies

**Comment by maxdelia** [comment]
I'm still having this issue, and I've `styled-components` as a normal dependency!
