### ISSUE TITLE
Styles out of order when when using "&"

### ISSUE THREAD

**Issue by stonebk** [styled-components/styled-components#3147]
## Reproduction

https://codesandbox.io/s/styled-components-ampersand-2g05o?file=/src/App.js

Component A defines styles using "&":

```
const A = styled.div`
    & {
        color: red;
    }
`;
```

Component B extends A:

```
const B = styled(A)`
    color: blue;
`;
```

## Expected Behavior

B styles should override A styles. B should be blue.

## Actual Behavior

A styles override B styles. B is red.

## Explanation

Why the "&"? This comes up when I want to define an attribute for multiple states without repeating the attribute, for example the default state and hover state:

```
&,
&:hover {
    color: red;
}
```

**Comment by stonebk** [comment]
This can be reproduced without extending:

https://codesandbox.io/s/styled-components-ampersand-simplified-2g05o?file=/src/App.js

```
const A = styled.div`
    & {
        color: red;
    }
    color: blue;
`;
```

Expected: Blue
Actual: Red

**Comment by kitten** [comment]
This is expected behaviour. When you use `&` styled-components addds the current class name twice which doubles the specificity

**Comment by stonebk** [comment]
@kitten it should only add the current class name twice if you have two ampersands, `&&`. If you look at the styles generated, it only generates one for the current component:

![Screen Shot 2020-05-19 at 8 06 19 AM](https://user-images.githubusercontent.com/1432010/82343688-03786a00-99a8-11ea-88dc-1944279b65a2.png)

Two ampersands are used in the styled-components documentation to generate two classes:
https://styled-components.com/docs/basics#pseudoelements-pseudoselectors-and-nesting

![Screen Shot 2020-05-19 at 8 09 59 AM](https://user-images.githubusercontent.com/1432010/82343843-2dca2780-99a8-11ea-9030-4fe216ef325c.png)
![Screen Shot 2020-05-19 at 8 10 05 AM](https://user-images.githubusercontent.com/1432010/82343849-302c8180-99a8-11ea-8f07-9d8c2d8df5b4.png)

**Comment by stonebk** [comment]
After further examination, it looks like this is actually a bug with [stylis](https://stylis.js.org/):

![Screen Shot 2020-05-19 at 8 31 33 AM](https://user-images.githubusercontent.com/1432010/82346434-50aa0b00-99ab-11ea-8b6b-8686c27d99bf.png)

**Comment by stonebk** [comment]
Here's a more "real-world" example of this happening with styled-components:
https://codesandbox.io/s/styled-components-ampersand-real-world-w65kh?file=/src/App.js

**Comment by stonebk** [comment]
So it turns out the stylis behavior is by design as nested rules will always be turned into a new rule that follows the rule for direct children. But that still doesn't explain the styled-components behavior in the [real world example](https://codesandbox.io/s/styled-components-ampersand-real-world-w65kh?file=/src/App.js) I created.

We create a `Button` component:

 ```js
const Button = styled.button`
  /** override global styles to make active state match base state */
  &,
  &:active {
    background-color: #5cb85c;
    border-color: #4cae4c;
  }

  &:hover {
    background-color: #449d44;
    border-color: #398439;
  }
`;
 ```

This creates two `<style>` blocks because there are two nested rules:

<img width="221" alt="Screen Shot 2020-05-19 at 12 05 43 PM" src="https://user-images.githubusercontent.com/1432010/82367749-25ceaf80-99c9-11ea-8494-b528f3ac6b27.png">
<img width="221" alt="Screen Shot 2020-05-19 at 12 06 46 PM" src="https://user-images.githubusercontent.com/1432010/82367800-3d0d9d00-99c9-11ea-9bb0-d8994767231f.png">

Then we create a new `CautionButton` that extends `Button`:

```js
const CautionButton = styled(Button)`
  background-color: red;
  border-color: red;

  &:hover {
    background-color: #c9302c;
    border-color: #ac2925;
  }
`;
```

This is where things don't make sense, as it creates a new `<style>` block for the red styles, however it comes after the base styles:

<img width="224" alt="Screen Shot 2020-05-19 at 12 09 32 PM" src="https://user-images.githubusercontent.com/1432010/82368255-f9fff980-99c9-11ea-8d89-ca7636e89247.png">

I'm not exactly sure what is happening under the covers of styled-components, but I would have thought since they both use the same class, it would be basically merging the new styles with the base styles and running that through stylis, effectively something like this:

```js
const CautionButton = styled(Button)`
  &,
  &:active {
    background-color: #5cb85c;
    border-color: #4cae4c;
  }

  &:hover {
    background-color: #449d44;
    border-color: #398439;
  }

  background-color: red;
  border-color: red;

  &:hover {
    background-color: #c9302c;
    border-color: #ac2925;
  }
```

If that was the case, then based on the stylis logic (as explained in the closed ticket: https://github.com/thysultan/stylis.js/issues/219), the red styles should definitely come first:

![Screen Shot 2020-05-19 at 12 16 21 PM](https://user-images.githubusercontent.com/1432010/82368618-975b2d80-99ca-11ea-9b67-deae4c19937a.png)

This seems like another case where extended component styles don't override the base styles (https://github.com/styled-components/styled-components/issues/1816).

@kitten any thoughts?

**Comment by stonebk** [comment]
Nevermind, styled-components is doing exactly what I thought it was doing, and that's why the caution styles are before the base button styles in the stylesheet, which means they come after the base button styles in specificity.

**Comment by MyGuySi** [comment]
@stonebk this seems to be similar to an issue that I'm currently experiencing, trying to debug why this input component is rendering a blue border when focused instead of no border.

```js
const CommonInput = styled.input` 
  ${(props: InputProps) => {
    const secondaryBlueBase: string = props.theme?.colors?.secondary?.blue?.base ?? '#0079D1';
    return `
      &:focus {
        border: 1px solid ${secondaryBlueBase};
      }
    `;
  }}
`;

const Input = styled(CommonInput)`
  &:focus {
    border: none;
  }
`;
```

I'm not sure I fully understand your example though so I'm struggling to get my head around what is happening here.

**Comment by stonebk** [comment]
@MyGuySi take a look at this thread: https://github.com/styled-components/styled-components/issues/1816
