### ISSUE TITLE
dynamic class generated not unique

### ISSUE THREAD

**Issue by brendonco** [styled-components/styled-components#3148]
anyone having a collision of dynamic class generated by styled-components when you shared Navigation. The navigation is using a styled-component.  Also I'm using webpack module federation to share components.

https://github.com/webpack/webpack/issues/10352#issuecomment-631499667

Example:

app1 nav content style:

```
import styled from 'styled-components';

export const ContentWrapper = styled.div`
  margin: -1.5em -1.5em 0;
`;
```

![image](https://user-images.githubusercontent.com/6521691/82455841-05484780-9ae6-11ea-88b8-63e850137a34.png)

app2 using app1 navigation:

```
import styled from "styled-components";

export const Container = styled.div`
  padding-top: 1rem;
  box-shadow: 0 5px 10px 0 rgba(0, 0, 0, 0.1);
`;

```

![image](https://user-images.githubusercontent.com/6521691/82456360-b6e77880-9ae6-11ea-88d9-2a7a9da516d1.png)

Webpack config (App1):

```
      exposes: {
        SideNavigation: "./src/common/components/SideNavigation/index",
        Widget: "./src/App",
      },
        shared: [
        "react",
        "react-dom",
        "react-router-dom",
        // workaround to ensure code is provided before booting app
        "./src/common/components/SideNavigation/index"
      ]
```

**Comment by tu4mo** [comment]
Yes, I have the same issue with multiple React apps in a single page. styled-components does not generate unique class names.

**Comment by kitten** [comment]
Are you using our Babel plugin? That should make collisions way less likely.
And if you're already sharing `react`, `react-Dom`, etc it's highly advisable to also share `styled-components` between app bundles. It doesn't currently play well with multiple instances being active.

**Comment by tu4mo** [comment]
Can the plugin be used when building a component library, or do the users of the lib have to use the plugin in their apps? What does it do to make collisions less likely?

**Comment by kitten** [comment]
Yes, you can apply the plugin to component libraries. When the `SSR` option is active it'll add a `componentId` based on the component's file.

**Comment by tu4mo** [comment]
Thanks! I'll give it shot.

**Comment by probablyup** [comment]
@tu4mo did @kitten's suggestion work for you?

**Comment by tu4mo** [comment]
@probablyup I've setup the plugin and I'm now waiting for my users' feedback whether the issue still arises. Unfortunately I haven't been able to reproduce the issue myself. However, the collision happened with the dynamic class name, so I'm not sure how the plugin will help, since it only seems to affect the static class name (?).

**Comment by kitten** [comment]
I think we had several changes here that'd fix the hashing approach and should guarantee more unique classes, but let's observe this further as we go.
