### ISSUE TITLE
Full code sharing between multiple platforms (web, native, ...)

### ISSUE THREAD

**Issue by brunolemos** [styled-components/styled-components#315]
After using styled-components in a native app, I got thinking "the web styling will be very, very similar...". 

Some problems:
- Imports are from different files (`styled-components` vs `styled-components/native`)
- Different components (`div` vs `View`, ...)
- Style properties that might be available in web css but not on native and vice-versa

What is the current recommend approach for sharing styles between web and native?

I believe styled-components has the potential for full code sharing between multiple platforms, not sure if similarly or differently from `react-native-web`. 

Is that aligned with the core maintainers vision? Next steps?

**Comment by mxstbr** [comment]
> Imports are from different files (styled-components vs styled-components/native)

Apparently we could solve this by [adding a `"react-native"` directive to our `package.json`](https://twitter.com/intelligibabble/status/809190896876957696)! (according to @lelandrichardson, though I don't have a canoncial source on that)

I haven't really thought about this too much yet since I don't have the use case, so I can't say if this is something we want to do or not. What are your ideas for problems 2 and 3?

**Comment by LorbusChris** [comment]
Interesting. Refs https://github.com/facebook/react-native/commit/b86f14738ee8bcb925ad447e0daf58d7ee95f5bb

**Comment by lelandrichardson** [comment]
You might want to be careful. I think it's great to write cross-platform code, and using the `react-native` directive is a good way to do this, but i think if you do this you should make sure you are exporting the *exact same* API in each platform. For instance, `styled.div` is part of your API, but wouldn't be in the RN case. In this case, I think it might make more sense to actually name them differently.

**Comment by kopax** [comment]
Isn't it possible to convert the div to something else (view)?

**Comment by mxstbr** [comment]
> Isn't it possible to convert the div to something else (view)?

That's so much magic I don't even want to think about doing that.

> In this case, I think it might make more sense to actually name them differently.

You are right, we don't export the exact same API on all platforms so this doesn't really make sense. The `import styled from 'styled-components/native'` thing actually works quite nicely to make that distinction clear!

**Comment by brunolemos** [comment]
Closing because [react-native-web](https://github.com/necolas/react-native-web) solves this pretty well.

**Comment by brunolemos** [comment]
Closing because [react-native-web](https://github.com/necolas/react-native-web) already solves this pretty well.
