### ISSUE TITLE
Will duplicate css appear when using createGlobalStyle?

### ISSUE THREAD

**Issue by bihongbin3027** [styled-components/styled-components#3153]
![image](https://user-images.githubusercontent.com/15045200/82883900-a23b3280-9f75-11ea-8021-e14d4a13e1c5.png)
![image](https://user-images.githubusercontent.com/15045200/82883933-ab2c0400-9f75-11ea-9bee-7cbba761e936.png)

**Comment by grace-snow** [comment]
Are you running in development or production environment? I think if you do a production build this duplication will disappear.

**Comment by bihongbin3027** [comment]
> 您在开发或生产环境中运行？我认为，如果您进行生产构建，此重复将消失。

I'm in a development environment, I try with production build。

**Comment by EBuyuran** [comment]
Any update on that? I'm having this issue.

**Comment by bihongbin3027** [comment]
> Any update on that? I'm having this issue.

Build production and packaging to see if the production environment has this problem。

**Comment by damiangreen** [comment]
Is there a reason this bug was closed?
