### ISSUE TITLE
Redundant css vendor prefix for letter-spacing

### ISSUE THREAD

**Issue by aszx87410** [styled-components/styled-components#3157]
## System:
 - OS: macOS Mojave 10.14.4
 - CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
 - Memory: 130.60 MB / 8.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 10.13.0 - ~/.nvm/versions/node/v10.13.0/bin/node
 - Yarn: 1.22.4 - /usr/local/bin/yarn
 - npm: 6.4.1 - ~/.nvm/versions/node/v10.13.0/bin/npm
 - Watchman: 4.1.0 - /usr/local/bin/watchman

## Reproduction

https://codesandbox.io/s/styled-components-8vwwu?file=/index.js

## Steps to reproduce

1. open the project on codesandbox above
2. right click on `Inspect me` element -> Choose `Inspect`
3. check the css of `Inspect me`

## Expected Behavior

For `letter-spacing`, there should be no vendor prefix because it's not needed.

## Actual Behavior

`letter-spacing` with multiple vendor prefixes:

``` css
.gwkepo {
  -webkit-letter-spacing: 1px;
  -moz-letter-spacing: 1px;
  -ms-letter-spacing: 1px;
  letter-spacing: 1px;
}
```

![螢幕快照 2020-05-29 下午11 45 46](https://user-images.githubusercontent.com/2755720/83279187-51db0380-a207-11ea-9b72-1b27dfb49964.png)

Actually it's a bug in [stylis.js](https://github.com/thysultan/stylis.js) v3, but recently stylis has upgrade to v4 and resolve this issue. There is an issue asking about upgrade to v4: https://github.com/styled-components/styled-components/issues/3060 but it seems no follow-up.

I found that `styled-components` depends on `@emotion/stylis` and there is a PR to upgrade the stylis library to v4. https://github.com/emotion-js/emotion/pull/1817

But it will be a breaking change for emotion, which means after it gets upgrade, we can't simply update our dependencies and follow up. 

IMO, there are three possible ways to solve this problem:

1. Use stylis v4 instead of `@emotion/stylis` and make necessary changes. But maybe for styled components it's also a breaking change because we can't use existing stylis v3 plugin in v4, `stylisPlugins` props on `StyleSheetManager` need to be changed.
2. Write our own stylis plugin to remove this prefix, we can add a plugin in `packages/styled-components/src/utils/stylis.js` to fix this problem.
3. Ask stylis to fix this bug in v3 and release a new version, and `@emotion/stylis` also need to update, then we can update our dependencies. 

If you think the second way sounds good, I can try to submit a PR for it. Please let me know if there is anything not clear or need more information, thanks!

**Comment by probablyup** [comment]
Yeah we'll need to switch to v4 for sure, but it'll have to be the next major version.

**Comment by kitten** [comment]
For now, I'll go ahead and close this, since there's not much we can do to fix this on our end. But rest assured, you're not doing anything wrong, it's likely stylis@^4 will fix this
