### ISSUE TITLE
Not possible to extend createGlobalStyle?

### ISSUE THREAD

**Issue by lekoaf** [styled-components/styled-components#3160]
## System:
 - OS: Linux 4.9 Debian GNU/Linux 9 (stretch) 9 (stretch)
 - CPU: (8) x64 Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
 - Memory: 3.31 GB / 15.59 GB
 - Container: Yes
 - Shell: 5.3.1 - /bin/zsh
## Binaries:
 - Node: 12.16.3 - /usr/bin/node
 - Yarn: 1.22.4 - /node_modules/.bin/yarn
 - npm: 6.14.4 - /usr/bin/npm

## Reproduction

https://codesandbox.io/embed/cool-bash-gu6yi

## Expected Behavior
The scrollbar should be red, yellow and narrower

## Actual Behavior
Only the original styles are applied, not the extended.

I'm not sure if this is how it is supposed to be. But I found it odd since you can extend every other styled component. My use case is that I'm importing a GlobalScrollBar from a library but would like to tweak it a bit for my application.

**Comment by kitten** [comment]
These are two unrelated APIs and this is unsupported. Also the use of the global style component isn’t particularly encouraged so that’s why the API is pretty barebones and minimal

**Comment by lekoaf** [comment]
Fair enough. Thanks for your answer. :+1:

**Comment by fijisoo** [comment]
So how can I extend/overwrite global styles?
