### ISSUE TITLE
Typescript definitions have been broken for over a year

### ISSUE THREAD

**Issue by dmihal** [styled-components/styled-components#3162]
I just wanted to bring some more attention to this issue with the Typescript definitions.

Adding support for React Native has broken the @types/styled-components package since February 2019. It's causing pain for lots of users, myself included.

Most users have frozen the package version at 4.1.8 or found other hacky workarounds.

See:
DefinitelyTyped/DefinitelyTyped#33311

**Comment by Mario-Eis** [comment]
And https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33015

**Comment by probablyup** [comment]
We don't maintain the types, so closing. Get people interested in working on it via twitter, etc
