### ISSUE TITLE
stylis plugin not working for keyframes since 5.0.0-rc3 #2936

### ISSUE THREAD

**Issue by mzvast** [styled-components/styled-components#3163]
## System:
 - OS: macOS 10.15.5
 - CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
 - Memory: 69.18 MB / 8.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 10.21.0 - ~/.nvm/versions/node/v10.21.0/bin/node
 - Yarn: 1.22.4 - ~/.nvm/versions/node/v10.21.0/bin/yarn
 - npm: 6.14.4 - ~/.nvm/versions/node/v10.21.0/bin/npm

## Reproduction
I wrote a stylis plugin to transform px to vm.
It works fine before following commit:

![image](https://user-images.githubusercontent.com/8097465/83751693-d6130800-a699-11ea-97fb-8f8bbf54131a.png)

My plugin stop working when it encounters @keyframes mark, which can't receive any input then.

### Working
 [workspace](https://codesandbox.io/s/styled-components-working-example-6hjr3)
![image](https://user-images.githubusercontent.com/8097465/83749118-c72a5680-a695-11ea-91ab-bca97d4f07ee.png)

### Broken
[workspace](https://codesandbox.io/s/styled-components-borken-example-r6xy7?file=/index.js)
![image](https://user-images.githubusercontent.com/8097465/83748935-87636f00-a695-11ea-95f6-cf04d470759f.png)

## Steps to reproduce
change styled-components version to greater than rc3 .
## Expected Behavior
My plugin should receive @keyframes input.
## Actual Behavior
 My plugin didn't receive @keyframes input.

## My attempts
I used binary searching to accurately allocate the first breaking commit.
And I spend some time to compare the behavior and output between fine version and broken version.
However, I'm not quite sure how it works, especially on following lines.
https://github.com/styled-components/styled-components/blob/37f472da70af60ff3e02e7f9a0073c895db4eb04/packages/styled-components/src/models/Keyframes.js#L20-L24

I add a debugger right here, and hit refresh.
![image](https://user-images.githubusercontent.com/8097465/83750940-a0215400-a698-11ea-93e9-909d5be89533.png)

To my surprise, the break point didn't hit at all. But still injected @keyframes to style tag as below.
![image](https://user-images.githubusercontent.com/8097465/83751055-ccd56b80-a698-11ea-8f94-fa3f56203769.png)

Then I comment out this line as below.And hit refresh.
![image](https://user-images.githubusercontent.com/8097465/83751104-e1196880-a698-11ea-9e1a-33ad2e19df43.png)

Oh my god, it did HIT!
![image](https://user-images.githubusercontent.com/8097465/83751223-102fda00-a699-11ea-9bfb-4ed52a0f112b.png)

Finally, I god mad at what happened.

Maybe you think I should put a break point at https://github.com/styled-components/styled-components/blob/37f472da70af60ff3e02e7f9a0073c895db4eb04/packages/styled-components/src/sheet/Sheet.js#L79-L82

It behaves strangely as well.

I need you help:)

**Comment by probablyup** [comment]
@mzvast this will be fixed by #3239
