### ISSUE TITLE
Repositioning style tag in head to contend with existing custom style overrides (IE11)

### ISSUE THREAD

**Issue by informa** [styled-components/styled-components#3164]
## System:
 - OS: Linux 4.4 Ubuntu 16.04.6 LTS (Xenial Xerus)
 - CPU: (3) x64 Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz
 - Memory: 818.72 MB / 29.96 GB
 - Container: Yes
 - Shell: 4.3.48 - /bin/bash
## Binaries:
 - Node: 11.14.0 - /opt/nvm/versions/node/v11/bin/node
 - npm: 6.7.0 - /opt/nvm/versions/node/v11/bin/npm
## npmPackages:
 - styled-components: ^5.1.1 => 5.1.1 

## Reproduction

https://test-override-sc.glitch.me
Edit: https://glitch.com/edit/#!/test-override-sc

## Context
I help maintain a react UI library, wanting to move to style components.
Currently, our UI library is installed in react apps with various style overrides having been applied over the years via className props with a variety of methods, css, csx, css-modules and probably more. I understand that the nature of styled-components is to apply a style tag at run time to the bottom of the head which increases specificity over style tags imported in the react app.
By doing this the UI library will override existing custom style overrides that would have been applied.
Ideally, we would like the existing custom overrides to appear at the bottom of the head and therefore still work.
We found a possible solution in your issues whereby adding `<style data-styled="active"></style>` into the head and style-components adds it's runtime styles underneath this.  This seems to do what we need, but in IE11 although the DOM looks correct IE doesn't seem to recognise this and style-components overrides the existing custom style.

Is this a official solution for repositioning the style tag in the head? 
ie adding `<style data-styled="active"></style>`

Adding specificity to existing custom styles would also solve this issue but not at the cost of the UI library maintainer but the app maintainers, and would be difficult to sell as an idea.

## Steps to reproduce
- Create react app
- Using a styled component library (recise-ui) as test case only.
- Added two Badge components to the page
- Add className to second Badge component
- Added css to App.css to override the background-color to hotpink
- Added <style data-styled="active"></style> to the index.html to reposition the style tag order in the head

## Expected Behavior
In browsers the second Badge component is hotpink

## Actual Behavior
In Chrome, Firefox, Safari, Edge the second Badge component is hotpink 👍 
<img width="734" alt="Screen Shot 2020-06-04 at 10 56 33 pm" src="https://user-images.githubusercontent.com/726265/83759310-b63e0d00-a6b6-11ea-86a5-08bd36e875cc.png">

In IE11 the second Badge component is orange which is default 👎 
<img width="737" alt="Screen Shot 2020-06-04 at 10 56 49 pm" src="https://user-images.githubusercontent.com/726265/83759336-bccc8480-a6b6-11ea-83c4-9cb0f6c1ff0a.png">

Would love your input.

**Comment by kitten** [comment]
> Is this a official solution for repositioning the style tag in the head?
> ie adding <style data-styled="active"></style>

Yes, that's an intentional feature, which is also important for SSR to work, since we can't be sure where a `style` tag will end up otherwise.

> but in IE11 although the DOM looks correct IE doesn't seem to recognise this and style-components overrides the existing custom style.

I'm not aware of any issues with IE11, but without more details I can't really tell what may be happening, especially if we don't know whether the DOM looks correct, i.e. does the element end up in the same place as in other browsers?

You can likely look into this by investigating what this code does in IE11, which is what determines the positioning: https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/sheet/dom.js#L9-L41

**Comment by informa** [comment]
Thank you @kitten for your response.

Firstly, thank you for confirming the use of `<style data-styled="active"></style>`

To the second point, thanks for pointing me to this code. I'll try to debug in IE11.
But in essence from the image of inspecting the element in IE11 it looks like the generated style tag has been positioned in the right place (next to the <style data-styled="active"></style>).
<img width="821" alt="Screen Shot 2020-07-09 at 12 18 23 pm" src="https://user-images.githubusercontent.com/726265/86989938-da719a00-c1de-11ea-9d18-957e8db957e2.png">

But for some reason, the code underneath this which is a style override is not read in this order and style-components styles override it. This is not the case in other browsers, whereby the override, overrides style-components.

To overcome this I have moved the style components style tag in the dom after load, which seems to wake IE11 up and the cascade seems to work.

If you go to the link https://test-override-sc.glitch.me. in IE11 and then in chrome you can see what I mean.

**Comment by informa** [comment]
Working example whereby in IE11 I am moving the styletag, and IE11 cascade seems to kick in.

https://test-override-sc-ie11.glitch.me/

```
const isIE11 = window.navigator.userAgent.indexOf('Trident/') > 0;
const customStyleTag = document.querySelector('style[title="custom-style"]');

const reorderStyleTag =
  isIE11 &&
  customStyleTag &&
  setInterval(() => {
    const styledComponentStyleTag = document.querySelector(
      'style[data-styled-version]'
    );
    if (styledComponentStyleTag) {
      styledComponentStyleTag.parentNode.insertBefore(
        styledComponentStyleTag,
        customStyleTag
      );
      clearInterval(reorderStyleTag);
    }
  }, 100);
```
