### ISSUE TITLE
Can i render a react styled component through the pseudo element, content property?

### ISSUE THREAD

**Issue by DodoTrip** [styled-components/styled-components#3165]
I was wondering if it is possible to have some kind of a work around to do something like this

```
import SvgComp from "../icons/SvgComp";

const SvgCompWrap = styled(SvgComp)``;

const AComponent = styled.div`
    &:before{
        content: "${SvgCompWrap}";
        width: 15px;
        height:15px;
        fill: red;
    }
`;
```
The result should be the rendering of the svg and not a string as in the above example...I know the content property isn't supposed to be working with html , but i was thinking since its an svg it may have some way to work around it, even though i could not find it :/

**Comment by probablyup** [comment]
This isn't possible as far as I know, that field only supports simple text content. https://developer.mozilla.org/en-US/docs/Web/CSS/content

**Comment by dieguezz** [comment]
You cannot do that, but you can use a base64 version of the image along with [mask-image](https://developer.mozilla.org/en-US/docs/Web/CSS/mask-image)

Something like: 

```
"&::before": {
    content: '""',
    maskImage: "var(--vars-icons-openInNew)",
    width: 12,
    height: 12,
    backgroundColor: (theme) => theme.palette.primary.main,
    ml: 0.5,
}
```

Where. your var is something like `url(data:image/svg+xml,...`
