### ISSUE TITLE
TypeError: MODULE_2__.default.View is not a function

### ISSUE THREAD

**Issue by ShaikhahMaasher** [styled-components/styled-components#3167]
## Environment

```
## System:
 - OS: macOS 10.15.4
 - CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
 - Memory: 56.95 MB / 8.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 10.15.1 - /usr/local/bin/node
 - Yarn: 1.22.4 - /usr/local/bin/yarn
 - npm: 6.13.7 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^5.1.0 => 5.1.0 
```
## Reproduction

```
import React from "react"
import styled from "styled-components"

const Card = ({ image, title, logo, caption, subtitle }) => (
  <Container>
    <Cover>
      <Image source={image} />
      <Title>{title}</Title>
    </Cover>
    <Content>
      <Logo source={logo} />
      <Wrapper>
        <Caption>{caption}</Caption>
        <SubTitle>{subtitle}</SubTitle>
      </Wrapper>
    </Content>
  </Container>
)

export default Card

let Container = styled.View`
  width: 315px;
  height: 280px;
  box-shadow: 0 5px 15px rgba(0, 0, 0, 0.15);
`
const Cover = styled.View`
  width: 100%;
  height: 200px;
  overflow: hidden;
`
const Image = styled.Image`
  width: 100%;
  height: 100%;
`
const Title = styled.Text`
  top: 50px;
  color: white;
  width: 170px;
`
const Content = styled.View`
  display: flex;
  flex-direction: row;
`
const Wrapper = styled.View`
  margin-left: 10px;
`
const Logo = styled.Image`
  width: 44px;
  height: 44px;
`
const Caption = styled.Text`
  font-size: 20px;
`
const SubTitle = styled.Text`
  color: blue;
`

```

## Behavior
```
TypeError: styled_components__WEBPACK_IMPORTED_MODULE_2__.default.View is not a function

  19 | 
  20 | export default Card
  21 | 
> 22 | let Container = styled.View`
  23 |   background: white;
  24 |   width: 315px;
  25 |   height: 280px;
```

__webpack_require__
`/webpack/bootstrap:725`

```
  722 | };
  723 | 
  724 | // Execute the module function
> 725 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  726 | 
  727 | // Flag the module as loaded
  728 | module.l = true;
```

**Comment by probablyup** [comment]
Import from `styled-components/native`

**Comment by stark1996** [comment]
thank you!! it took a day to understand the error. 😄

**Comment by sarambanks** [comment]
Test returning   TypeError: macro_1.default.h2 is not a function

This is all new to me. I have been taking pieces from videos, blogs, etc., to try and create this test. I am attempting to test that BlogFAQ renders with children. 

This component calls axios, useQuery to read .json.  It uses styled-components to style headings. 

 TypeError: macro_1.default.h2 is not a function

       8 | }
       9 |
    > 10 | export const ViewHeader = styled.h2<HeaderProp>`
         |                                  ^
      11 |   color: ${({ titleColor }) => titleColor};
      12 |   font-family: Fjalla One, sans-serif;
      13 |   text-align: center;


BlogFAQ.test.tsx
` import React from "react";
import { renderHook, waitFor } from "@testing-library/react";

/* component being tested */
import BlogFAQ from "../../../src/views/OCVBlogFAQ/OCVBlogFAQ";

import {
  QueryClient,
  QueryClientProvider,
  useQuery,
} from "@tanstack/react-query";

import "styled-components/native";
import "jest-styled-components";

/* mock call to query */
export function useCustomHook() {
  return useQuery({ queryKey: ["customHook"], queryFn: () => "Hello" });
}

describe("Blog FAQ", function () {
  it("renders children when rendered", async function () {
    const queryClient = new QueryClient();

    const wrapper = () => (
      <QueryClientProvider client={queryClient}>
        <BlogFAQ
          viewData={{}}
          link={{}}
          anchorID={{}}
          showSearch={{}}
        />
      </QueryClientProvider>
    );

    const { result } = renderHook(() => useCustomHook(), { wrapper });

    await waitFor(() => expect(result.current.isSuccess).toBe(true));
  });
});`



ViewStyle.tsx   

`import styled from "styled-components/macro";

interface HeaderProp {
  titleColor: string;
}
interface TextProp {
  textColor: string;
}

export const ViewHeader = styled.h2<HeaderProp>`
  color: ${({ titleColor }) => titleColor};
  font-family: Fjalla One, sans-serif;
  text-align: center;
  text-transform: uppercase;
  margin: 0;
  font-size: 2.25rem;
  @media (max-width: 768px) {
    font-size: 1.5rem;
  }
`;`


BlogFAQ.tsx  

`export default function BlogFAQ({
  viewData,
  anchorID,
  link,
  showSearch,
  showHeading,
}: Record<string, any>): JSX.Element { 


 return (
    <section
      style={{
        padding: "3rem",
      }}
      id={anchorID}
    >
      {showHeading ? (
        <ViewHeader titleColor="black">{viewData.title}</ViewHeader>
      ) : null}`




I don't know much about dependencies, config,  or packages. I do have a package.json. 


"jest": {
    "moduleFileExtensions": [
      "html",
      "ts",
      "tsx",
      "js",
      "jsx"
    ],
    "displayName": "Features-Web",
    "testEnvironment": "jsdom",
    "transform": {
      "^.+\\.(ts|tsx|js|jsx)$": "ts-jest"
    },
    "moduleNameMapper": {
      "\\.(css|less)$": "identity-obj-proxy",
      "styled-components": "<rootDir>/node_modules/styled-components/dist/styled-components-macro.cjs.js"
    },
    "setupFilesAfterEnv": [
      "<rootDir>/src/setupTests.ts"
    ]
  },

"dependencies": {
    "@chakra-ui/icons": "^2.0.11",
    "@chakra-ui/react": "^2.4.1",
    "@craco/craco": "^6.4.5",
    "@emotion/react": "^11.10.5",
    "@emotion/styled": "^11.10.5",
    "@react-google-maps/api": "^2.17.1",
    "@react-google-maps/marker-clusterer": "^2.16.1",
    "@tanstack/react-query": "^4.2.1",
    "@tanstack/react-query-devtools": "^4.2.1",
    "@types/googlemaps": "^3.43.3",
    "@types/markerclustererplus": "^2.1.33",
    "@types/node": "^15.12.2",
    "@types/react": "18",
    "@types/react-datepicker": "^2.11.0",
    "@types/react-dom": "18",
    "@types/react-filepond": "^7.1.0",
    "@types/react-flatpickr": "^3.8.1",
    "@types/react-helmet": "^5.0.15",
    "@types/react-image-gallery": "^1.0.5",
    "@types/react-lazyload": "^3.1.0",
    "@types/react-modal": "^3.10.5",
    "@types/react-router-dom": "^5.1.8",
    "aws-amplify": "4.3.30",
    "axios": "1.2.2",
    "color": "^4.2.3",
    "dayjs": "^1.11.5",
    "dom-parser-react": "^0.3.0",
    "dompurify": "^3.0.0",
    "filepond": "^4.28.2",
    "filepond-plugin-image-preview": "^4.6.6",
    "filepond-polyfill": "^1.0.4",
    "framer-motion": "^7.6.2",
    "react": "18",
    "react-app-polyfill": "^2.0.0",
    "react-content-loader": "^6.0.3",
    "react-datepicker": "^4.1.1",
    "react-dom": "18",
    "react-filepond": "^7.1.1",
    "react-ga4": "^1.4.1",
    "react-google-maps": "^9.4.5",
    "react-helmet": "^5.2.0",
    "react-hook-form": "^7.39.4",
    "react-iframe": "^1.5.0",
    "react-image-gallery": "^1.2.9",
    "react-lazyload": "^3.2.0",
    "react-lite-youtube-embed": "^2.3.1",
    "react-loading": "^2.0.3",
    "react-modal": "^3.11.2",
    "react-scripts": "5.0.0",
    "react-smartbanner": "^5.1.3",
    "styled-components": "^5.3.5",
    "typescript": "^4.3.2",
    "typestyle": "^2.0.1"
  },


I am unsure what the error message means or what I need to correct it.
