### ISSUE TITLE
How to create a css class (to use in React -> className) 

### ISSUE THREAD

**Issue by bolanos-m** [styled-components/styled-components#3168]
Hi team, I'm using AntD library, and specifically, this framework has a method to create a `modal` that can be stylish using a className (There is not another way). The AntD creates an element in the body so I cannot attach the style to any existing element or parent.

AntD Modal Method (Styled only with ClassName):
https://ant.design/components/modal/#Modal.method()

I'm struggling to try to do this with Styled Components, but I cannot find the way.
https://codesandbox.io/s/gifted-engelbart-wf7p6?file=/src/App.js

In the bottom line; it's exists a way to create a style `class-name` using JS?

I posted a similar question in StackOverflow:
https://stackoverflow.com/questions/62094597/styled-components-vs-emotion-how-to-reapplicate-cssstyle-function-on-styled

And also I'm trying to use the method `css` to create an inline style, but doesn't work.

Any other approach or workaround? - easily I just can manage using `Emotion` library or pure CSS... but I just want to have one library. Regards!

**Comment by probablyup** [comment]
We don't currently support this way of composing styles. Emotion might be a better choice for you if you need that specific DX
