### ISSUE TITLE
Is `pure` needed?

### ISSUE THREAD

**Issue by dimaqq** [styled-components/styled-components#3169]
#### Question / comment

Here's the space saving achieved by turning on `pure` bit in babel macro config for styled components:

```c
  144.14 KB         build/static/js/2.0127f623.chunk.js
  51.69 KB (-18 B)  build/static/js/main.1da2e05f.chunk.js
  771 B             build/static/js/runtime-main.70182e92.js
```

Whole `18 bytes` saved!

I wonder... does it mean that I'm using almost every feature of styled-components?
Or is something else wrong in my setup / build / config?
Or is this setting not very useful?

**Comment by dimaqq** [comment]
Diffing the beautified output showed me the culprit - I had 1 unused component...
(eslint thought it was used because `.propTypes` was set)
Maybe `pure` is primarily useful if same codebase can be built into different targets? Like a multi-paged app or translated app where each language is its own build bundle?

**Comment by probablyup** [comment]
Yeah it's more for component libraries. Where only some parts are used
