### ISSUE TITLE
Is there advised way to handle common styles?

### ISSUE THREAD

**Issue by benesva4** [styled-components/styled-components#3170]
Hello, thank you for the best css library around.
I am looking for an advice on how to store some common styles in my app. Let say, I need to set some simple and styles (like flex, align-items, justify-content, maybe some queries) again and again. I can think of three solutions and I am not sure which one is the right one.
1) Setup a component and extend it:
```
const Flex = styled.div`
    /* some styles */
`;

const NewComponent = styled(Flex)`
    /* more styles */
`;
```
I can see an advantage as this can be used on it's own as a `<Flex>...</Flex>`. But it has to be imported if you want to use it and it's a div.

2) constant holding a few styles:
```
const flex = css`
    /* some styles */
`

const NewComponent = styled.div`
    ${flex};
`
```
This seems like a best way to me. But it need to be imported if you want to use it.

3) Put these styles inside a theme.
```
const theme = {
    flex: css`
         /* some styles */
    `;
}

const NewComponent = styled.div`
    ${p => p.theme.flex};
`
```
This seems really convenient to use as it doesn't need to be imported and it's always at hand, but it feels wrong to put such thing in a theme. Is there a preferred or advised way to do such thing? 
Thank you very much for help.

**Comment by probablyup** [comment]
Closing as the issue tracker is meant for bugs and feature requests. Please use StackOverflow, Twitter, etc for advice. More people will see it :)
