### ISSUE TITLE
How to nest styles as children to a parent component?

### ISSUE THREAD

**Issue by moritzsalla** [styled-components/styled-components#3171]
Let's say you've set up an imaginary typographic hierarchy using styled components, which goes something like this:

```
const Header = styled.h1`
  font-size: 2rem;
  line-height: 1;
  color: blue;
`

const Paragraph = styled.p`
  font-size: 1rem;
  line-height: 1.25;
`

const Small = styled.span`
  font-size: 0.8rem;
`
```

How would you integrate existing styles in a markdown component? CSS snippets, global styling and extending styles all seem unclean but perhaps my approach is flawed altogether?

```
const Markdown = styled.div`
  h1 {
    ${Header} ???
  }
`

<Markdown dangerouslySetInnerHTML={{ __html: html }} />
```

**Comment by diondiondion** [comment]
You'd have to do it as shown below. Currently, there's no way to get to the source CSS of an already defined styled component – there used to be an issue where this was discussed but I can't find it anymore; I don't think the s-c team had an interest to implement it.

```js
const headerStyles = css`
  font-size: 2rem;
  line-height: 1;
  color: blue;
`

const paragraphStyles = css`
  font-size: 1rem;
  line-height: 1.25;
`

const smallStyles = css`
  font-size: 0.8rem;
`

const Header = styled.h1`
  ${headerStyles}
`

const Paragraph = styled.p`
  ${paragraphStyles}
`

const Small = styled.span`
  ${smallStyles}
`

const Markdown = styled.div`
  h1 {
    ${headerStyles}
  }

  p {
    ${paragraphStyles}
  }
`
```

**Comment by kitten** [comment]
Hiya 👋 I do remember that issue too and I’m not sure where it’s gone. I think the last standing argument was that the above, as you’re showing in your code example is possible, and there aren’t any unique use-cases to the reverse.

Some people kind of expressed some “meta coding wishes” for which this API would’ve been useful. But the complexity of such was never addressed, so I think that’s why the discussion didn’t progress

**Comment by moritzsalla** [comment]
Thats a little more code than I had hoped for. Makes sense though, thank you  🙏
