### ISSUE TITLE
conditional css reruns css for whole component tree in development mode.

### ISSUE THREAD

**Issue by ajit-hi** [styled-components/styled-components#3172]
I have a component where i am setting visibility and opacity conditionally in styled.ul, something like - 

```
const DropDownList = styled.ul`
    list-style: none;
    position: absolute;
    right: 0;
    z-index: 5;
    transition-duration: 0.5s;
    border: 1px solid #e6e8eb;
    border-radius: 4px;
    box-shadow: 0 14px 20px rgba(0,0,0,0.1);
    padding: 14px 20px;
    background-color: white;
    &:hover {
        visibility: visible;
        opacity: 1;
    }

    ${Button}:hover ~ & {
        visibility: visible;
        opacity: 1;
    }

    visibility: ${props => props.visible ? 'visible' : 'hidden'};
    opacity: ${props => props.visible ? '1' : 0} 
`
```

But when I'm changing visible prop, it is reloading an background image of one of parent component.
Is it a bug or intentional feature?  This issue do not appears in production build. 
Thank you.

**Comment by Kadchenko** [comment]
Same question, very interested in what for such behavior in development mode?

**Comment by lysyiandrii** [comment]
Faced the same issue. Are there any updates?

**Comment by kitten** [comment]
This is an issue in Chromium actually, and it's been filed, but until then we can't really do much about it. https://bugs.chromium.org/p/chromium/issues/detail?id=1216451

In general, although we're using the CSSOM API, Chromium will mostly reevaluate all rules of a given `style` element, if a new rule is inserted. This isn't the intended behaviour of the CSSOM API and inconsistent with other browsers. That said, in terms of images and fonts, this can be worked around by having a proper `Cache-Control` header present on them in production, which is how many sites actually don't experience this issue without realising.
