### ISSUE TITLE
Force VSCode (or other IDEs) to understand that styled components are React components. CMD-clicked Styled Component should go to the component implementation.

### ISSUE THREAD

**Issue by shamilovtim** [styled-components/styled-components#3175]
Screen grab shows what happens you CMD click a styled component. Typically with React / React Native, this would go to where the component itself is defined. However, VSCode doesn't understand that Styled Components are React components. So instead, it tries to go to the definition of the Styled Components library itself (index.d.ts). Instead, VSCode should default to the actual implementation of the components. There does exist a separate shortcut which does this but **so too should the CMD-click shortcut**.  So it's worth asking: is there any way of the styled components library indicating to VSCode that a styled component should go to the definition of the component when CMD-clicked, not the definition of the library itself? 

<img width="996" alt="Screen Shot 2020-06-15 at 2 45 21 PM" src="https://user-images.githubusercontent.com/3495974/84694515-50078480-af17-11ea-9130-50ffdd51d224.png">

**Comment by shamilovtim** [comment]
Related library (maybe): https://github.com/styled-components/vscode-styled-components @julienp

**Comment by kitten** [comment]
Hiya,

Sorry, but I’ll have to go ahead and close this.
It’s not related to our implementation, nor an issue report. I think if you’d ask this question on StackOverflow or on Spectrum someone may know why this isn’t working. Possibly it’s related to the TypeScript typings on DefinitelyTyped, but it isn’t part of the library itself.

On a side note; this has often worked for me. It just seems that you requested the definition not of the component itself but the styled call maybe?
