### ISSUE TITLE
box-shadow not working on Android (react-native)

### ISSUE THREAD

**Issue by stilllife00** [styled-components/styled-components#3177]
## System:
 - OS: macOS 10.15.5
 - CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
 - Memory: 51.84 MB / 8.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
 - Yarn: 1.22.4 - /usr/local/bin/yarn
 - npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman

## Reproduction
https://snack.expo.io/wd8zKyB4z

## Steps to reproduce
Compare the web version with the Android version of the snack. 

## Expected Behavior
On Android I see the box-shadow

## Actual Behavior
On Android there is no box-shadow

If this is a limitation of Android please document some workaround.

**Comment by kitten** [comment]
`box-shadow` isn’t supported on Android (including all the separate props) but only on iOS. You’ll have to use `elevation` for Android: https://reactnative.dev/docs/shadow-props#reference
