### ISSUE TITLE
How to prepend instead of append to target node?

### ISSUE THREAD

**Issue by wintercounter** [styled-components/styled-components#3180]
Currently I'm facing with an edge case where on a site there are some classic CSS loaded using `link` and these CSS should be loaded after styled components for higher specifity. However the link tags are already there when `styled` is injecting the target node. Currently using `StyleSheetManager` this is not possible. I'd like to discuss a possible solution for this so I can make a PR.

Options:
- If target is a style tag already, use that instead of inserting it's own (currently it ends up having style inside style).
- Introduce prop `injectMethod={prepend|append}`.
- Same method without extra prop: `target={[$el, 'prepend']}`

One is uglier than the other :) Any possible issues with the first option?

**Comment by kitten** [comment]
See: https://github.com/styled-components/styled-components/issues/3181#issuecomment-654869829

You can add a placeholder style tag (like what happens with SSR to determine the location of styles-components' style tag)
