### ISSUE TITLE
How to insert style before body tag

### ISSUE THREAD

**Issue by brendonco** [styled-components/styled-components#3181]
Is there a way to insert ```<style data-styled="active" data-styled-version="5.1.1">``` at the end before body or head tag?  The reason is I'm doing a micro frontend, where I have App1(host), App2(standalone with 3rd party library ag-grid), App3(standalone).  All App are using styled-components. App2 have a custome styling of ag-grid.

I would like something like:

![image](https://user-images.githubusercontent.com/6521691/85392042-93986900-b57d-11ea-8e22-460f2e5a154b.png)

Is this possible in styled-components ?

**Comment by kitten** [comment]
Yes, there's some logic in here: https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/sheet/dom.js#L10-L21

This will allow you to create a `<style data-styled></style>` tag after which the new style tag will be inserted.
If you're not using SSR you can even determine in your JSX where the styles will end up by wrapping everything in a `StyleSheetManager`: https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/models/StyleSheetManager.js#L13

But do take care that having multiple instances of `styled-components` on one page will most definitely lead to issues and in most cases it's advisable to avoid this and share one version of `styled-components` globally.
