### ISSUE TITLE
Styled component - how to pass React.HTMLProps

### ISSUE THREAD

**Issue by snizemic** [styled-components/styled-components#3182]
I cannot find satisfactory solution. I want to pass default HTML props to styled component but I get an typescript error. Is it possible to do that or how can I do it right way, please?

```
import styled from 'styled-components';

export const StyledInput = styled.input<React.HTMLProps<HTMLInputElement>>`
`;
```

```
import * as React from 'react';
import { StyledInput } from './StyledInput';

interface IInputProps extends React.HTMLProps<HTMLInputElement> {
}

export const Input = (props: IInputProps): React.ReactElement => {
	return (
		<StyledInput {...props} />
	);
};
```
![image](https://user-images.githubusercontent.com/7950752/85556395-14f80600-b627-11ea-9041-5cc56b148063.png)

**Comment by kitten** [comment]
See: https://github.com/styled-components/styled-components/issues/3191#issuecomment-654859655

You'll likely have to pass a props generic to your `StyledInput` with the appropriate props type.
