### ISSUE TITLE
Error when using through CDN with SystemJS Import Map: styled_components__WEBPACK_IMPORTED_MODULE_1___default.a.div is not a function

### ISSUE THREAD

**Issue by ahmedshaaban00** [styled-components/styled-components#3184]
I'm having a problem with the library when importing it through cdn using systemjs import map.
It throws an error when I try to use it as the following:
```
import styled from 'styled-components`;

const Container = styled.div``;
```

However, if I used it like this, it works:
```
import styled from 'styled-components`;

const Container = styled.default.div``;
```

## Steps to reproduce
Import styled-components using cdn in a SystemJS import map

## Expected Behavior
The library should work regularly as any other UMD package when importing it as a default.

## Actual Behavior
The library doesn't work as expected and throws the following error: `styled_components__WEBPACK_IMPORTED_MODULE_1___default.a.div is not a function`

**Comment by ardeois** [comment]
@ahmedshaaban00 I'm using `styled-components` with SystemJS and it works fine for me.
However I had to properly configure my webpack, typescript and babel.

If you create a repo with minimal reproduction I can maybe take a look

**Comment by ahmedshaaban00** [comment]
> @ahmedshaaban00 I'm using `styled-components` with SystemJS and it works fine for me.
> However I had to properly configure my webpack, typescript and babel.
> 
> If you create a repo with minimal reproduction I can maybe take a look

@ardeois Can you submit a reference code please? I've made a workaround to make that work but it's not working fine when wrapping another styled component.
I'll appreciate if you can give an example or a jsfiddle pin. Thanks!

**Comment by ardeois** [comment]
@ahmedshaaban00 I would prefer you provide a reproduction for you problem and I'll try to suggest how to fix it.
It will take me some time to create a reference from scratch, and I don't have it right now

**Comment by ahmedshaaban00** [comment]
@ardeois NVM. I just found a SystemJS version for styled-components created by @esm-bundles bot. It works perfectly.
You can find it [here](https://github.com/esm-bundle/styled-components).

I'm closing this as it's no longer a problem.

**Comment by totszwai** [comment]
@ahmedshaaban00 latest version no longer work with SystemJS?
Tried these:
- https://www.jsdelivr.com/package/npm/styled-components
- https://www.jsdelivr.com/package/npm/@esm-bundle/styled-components
