### ISSUE TITLE
Animated.interpolate (react-native) not working correct with styled-components

### ISSUE THREAD

**Issue by BennoDev1** [styled-components/styled-components#3185]
## System:
 - OS: Windows 10 10.0.18362
 - CPU: (4) x64 Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz
 - Memory: 5.62 GB / 15.96 GB
## Binaries:
 - Node: 12.13.0 - C:\1Programs\DeveloperPrograms\NodeJS\nodejs\node.EXE
 - npm: 6.12.0 - C:\1Programs\DeveloperPrograms\NodeJS\nodejs\npm.CMD
## npmPackages:
 - styled-components: ^5.1.1 => 5.1.1

## Steps to Reproduce
1) Create a new TypeScript react-native project with **npx react-native init MyApp --template react-native-template-typescript**
2) Install **styled-components** and **@types/styled-components**
3) Replace the code of the App.tsx with 

```js
import React, {useRef} from 'react';
import {
  View,
  Animated,
  Button,
} from 'react-native';
import styled, {ThemeProvider} from 'styled-components/native';


const App = () => {

// Animation
  const boxAnimation = useRef(new Animated.Value(0)).current;
  const moveIn = () => {
    Animated.timing(boxAnimation, {
      toValue: 1,
      duration: 2000,
      useNativeDriver: false,
    }).start();
  };
  const moveOut = () => {
    Animated.timing(boxAnimation, {
      toValue: 0,
      duration: 2000,
      useNativeDriver: false,
    }).start();
  };
  const fadeAnim = boxAnimation.interpolate({
    inputRange: [0, 1],
    outputRange: [0, 1],
  });
  const moveAnim = boxAnimation.interpolate({
    inputRange: [0, 1],
    outputRange: [0, -50],
  });

  return (
    <ThemeProvider theme={{}}>
      <AnimatedBox opacity={fadeAnim} pos={moveAnim}/>
      <View style={{marginTop: 100}}>
        <Button title={'MoveIn'} onPress={() => moveIn()}/>
        <Button title={'MoveOut'} onPress={() => moveOut()}/>
      </View>
    </ThemeProvider>
  );
};

const Box = styled.View`
  position: absolute;
  top: 0;
  left: ${props => props.pos}px;
  width: 50px;
  height: 50px;
  opacity: ${props => props.opacity};
  background-color: red;
`;
const AnimatedBox = Animated.createAnimatedComponent(Box);

export default App;
```

## Expected Behavior
The Box (colored View) should fade in and move into the screen if you click the **MoveIn** Button and should fade out and move out if you click the **MoveOut** Button

## Actual Behavior
The Box will always stay at the position -50.. and fades out by clicking MoveOut and fades in by clicking MoveIn..
(See if you set the pos to 0)
-> The interpolate function only works with the output range of **0, 1** or **1, 0** which shouldn't be so..
If you are using the normal react-native StyleSheet the interpolate method works as expected.

**Comment by kitten** [comment]
Animated styles can currently not be passed through the styles of styled-components directly, so make sure that you wrap an Animated component (calling `createAnimatedComponent` and not wrapping it with `styled` won't work) and pass on your animated styles using the `style` prop.

Also please make sure to format your issue properly (three-backticks create a code block) and keep questions to StackOverflow or Spectrum where they'll likely be answered more quickly :)

**Comment by BennoDev1** [comment]
ok.. thank you
I am doing it the same way u suggested it a while now and it is working perfect..
But it is still an issue.
