### ISSUE TITLE
[Feature] Prefix hash class

### ISSUE THREAD

**Issue by gcoombe** [styled-components/styled-components#3186]
I'm hoping to add a prefix to the generated hash classes. Would this be something that you would consider accepting as a PR? 

Our use case is that we integrate with a tool called pendo (https://www.pendo.io/) for user analytics. They have tools to allow non-developers to tag parts of our app. These tools will auto-generate a css selectors to target the feature. For obvious reasons we wouldn't want them to use styled component generated classes in the css selector so need to be able to provide known patterns of classes that are auto generated ex: sc-*.

A potential solution: add an environment variable `process.env.SC_HASH_PREFIX` which we could prepend to the hash classname:

Ex:
```
// Add process.env.SC_HASH_PREFIX = 'prefix-'

// Results in
<div class="sc-xyz prefix-mnb">
```

**Comment by TianlunXiong** [comment]
+1, i would like to have a similar method to replace the default prefix 'sc' too, for example: 
```javascript
import styled from 'styled-components'
styled.config.SC_HASH_PREFIX = 'prefix' // => <div class="prefix-xyz">
```

**Comment by tu4mo** [comment]
This would be a very welcome feature. My use-case is a component library built with styled-components. Sometimes the library is used in multiple React apps in one page and we are getting classname collisions/conflicts. Having the ability to prefix the class name would solve the issue. Any thoughts or workarounds, @kitten?

**Comment by probablyup** [comment]
There's a feature in the Babel plugin for this purpose: https://styled-components.com/docs/tooling#namespace

**Comment by probablyup** [comment]
> Would be better if sc just produced unique classes automatically.

We do, but there are tradeoffs between different methods of hashing and we chose ours primarily balancing for performance.

**Comment by natearmagost** [comment]
@probablyup The namespace seems to change the first class... usually the `sc-` prefix.

```
styledComponents: {
  "namespace": "MYPREFIX"
}
```
Results in:
```
<div class="App__Thing-MYPREFIX__cobd8z-0 fUSGm">
```
We are having issues with the 2nd class `fUSGm`. Is there any way to prefix that class like @gcoombe's example:
`<div class="sc-xyz prefix-mnb">`?

**Comment by mattleonowicz** [comment]
@probablyup Please reopen. I think it's a bug that `sc_xxx` get's prefixed instead of the other class (more random one) `sc-` doesn't really contain any styles so it's name is not that crucial as the other one.

**Comment by seahorsepip** [comment]
@mxstbr 
Please reopen this ticket after closing the sub repo ticket.

We're running into collisions without the option to prefix the hash e.g.

Our new frontend html generated by styled:
```html
<div class="sc-pYdTs fa-DacA">Hello world!</div>
```

Our old frontend global css in the same project:
```css
[class^="fa-"], [class*=" fa-"] {
    font-family: 'fontawesome' !important;
    speak: none;
    font-style: normal;
    font-weight: normal;
    font-variant: normal;
    text-transform: none;
    line-height: 1;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
```

**Comment by zelongc** [comment]
Facing the same problem here, any update on this issue?

**Comment by elektronik2k5** [comment]
I believe this is possible in Emotion, which shares 95% of the API surface with styled and can be migrated to easily.

**Comment by binzydev** [comment]
Ran into colliding class names statically compiling using reactSnap and this would solve it
