### ISSUE TITLE
Conditional rendering with css block

### ISSUE THREAD

**Issue by leobastiani** [styled-components/styled-components#3189]
I realized that in this jsfiddle, this boolean prop `isSelected` works with an inverted logic
```javascript
const Component = styled.div`
  background: blue;
  color: white;
  transition: 2s;
  
  &:hover, &${props => props.isSelected} {
    color: red;
    background: white;
  }
`;
```
https://jsfiddle.net/fs4x7ao9/4/

How do I solve it?

**Comment by barabba9174** [comment]
I have the same issue.

**Comment by kitten** [comment]
you're not actually excluding the rules for this block, instead this will evaluate to:

```js
& {
  background: blue;
  color: white;
  transition: 2s;
}
  
&:hover, & {
  color: red;
  background: white;
}
```

for `isSelected={false}`. Instead you'll want to use a `css` helper for that as even shown on the homepage: https://styled-components.com/

```js
import styled, { css } from 'styled-components';

const Component = styled.div`
  background: blue;
  color: white;
  transition: 2s;
  
  &:hover {
    color: red;
    background: white;
  }

  ${props => props.isSelected && css`
    color: red;
    background: white;
  `}
`;
```

Please keep questions to Stackoverflow or Spectrum btw :)
