### ISSUE TITLE
styled <use> element

### ISSUE THREAD

**Issue by gex** [styled-components/styled-components#3196]
hey,

i think my issue qualifies for i don't know, probably a feature request? i'd like to style some `<use>` elements. i thought i'm just overlooking something but after checking the code it seems like it's missing from the [list of styleable dom elements](https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/utils/domElements.js).

i checked the issues but haven't found anything related to styling a use element.

## Steps to reproduce

```js
const StyledUse = styled.use`
  width: 100;
  height: 100;
  fill: blue;
`
```

## Expected Behavior

having a styled `<use>` element :)

## Actual Behavior

i get an error: `styled.use is not a function`

**Comment by jian263994241** [comment]
```js
const StyledUse = styled('use') `
  width: 100;
  height: 100;
  fill: blue;
`
```

**Comment by probablyup** [comment]
Can `use` accept className? If so then you can just use `styled('use')` instead of `styled.use`.
