### ISSUE TITLE
Complex selectors with ampersands break after the component is extended.

### ISSUE THREAD

**Issue by EduardAkhmetshin** [styled-components/styled-components#3206]
## Reproduction
https://codepen.io/eduardakhmetshin/pen/ZEQmyNd

## Steps to reproduce
1. Create a styled component with a complex selector with ampersands. For example:
`& + & {}`. Every ampersand in the rule corresponds to a different class that is assigned to the component.
2. Extend this component.

## Expected Behavior
All classes remain for extending components and complex rules with ampersands don't break. In this example, all divs after the first should have red borders.

## Actual Behavior
Some classes are dropped for extending components which breaks rules. In this example, the last div remains black.

**Comment by probablyup** [comment]
The fix here is to use the base folded component static class for composition. Will make a PR this weekend
