### ISSUE TITLE
Different class order when component update

### ISSUE THREAD

**Issue by Seresigo** [styled-components/styled-components#3207]
## System:
 - OS: macOS 10.15.4
 - CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
 - Memory: 177.04 MB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 10.16.0 - /usr/local/bin/node
 - Yarn: 1.17.0 - /usr/local/bin/yarn
 - npm: 6.14.6 - /usr/local/bin/npm

## Reproduction

Just create styled component and after that styled it with styled() function

```
const H2 = styled.h2`
  color: rgb(0, 0, 0);
    font-size: 24px;
    font-weight: 600;
    line-height: 32px;
    margin: 0px;
    padding: 0px;
`;

const HeaderCounter = styled(H2)`
  color: rgb(179, 77, 0);
    margin-left: 8px;
`;
<Header>
  <H2>{header}</H2>
  <HeaderCounter>{counter}</HeaderCounter>
</Header>
```

## Expected Behavior
First time component's style render
<img width="322" alt="Снимок экрана 2020-07-21 в 19 07 09" src="https://user-images.githubusercontent.com/30799665/88079982-1dd8ea80-cb87-11ea-89f7-33cd0fc5a7a6.png">

## Actual Behavior
Component's styles after re-render
<img width="325" alt="Снимок экрана 2020-07-21 в 19 07 48" src="https://user-images.githubusercontent.com/30799665/88079996-216c7180-cb87-11ea-86a0-d4d03faf315c.png">

**Comment by probablyup** [comment]
Need a reproduction sandbox to help you
