### ISSUE TITLE
How to format css code in `createGlobalStyle`?

### ISSUE THREAD

**Issue by kmvan** [styled-components/styled-components#3208]
## System:
 - OS: Linux 5.7 Manjaro Linux
 - CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
 - Memory: 733.60 MB / 15.50 GB
 - Container: Yes
 - Shell: 5.0.18 - /bin/bash
## Binaries:
 - Node: 12.17.0 - /usr/bin/node
 - Yarn: 1.22.4 - /usr/bin/yarn
 - npm: 6.14.5 - ~/.node_modules/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.10.7 => 1.10.7 
 - styled-components: ^5.1.1 => 5.1.1 
## Editor
- Vscode
## Extensions
- vscode-styled-components

## Reproduction
The code:
```js
const GlobalStyle = createGlobalStyle`
.a{display:none;}b{display:none;}
`
```
dosen't format.

## Steps to reproduce

Format or save document.

## Expected Behavior

```js
const GlobalStyle = createGlobalStyle`
.a {
  display:none;
}
b {
  display:none;
}
`
```

## Actual Behavior

```js
const GlobalStyle = createGlobalStyle`
.a{display:none;}b{display:none;}
`
```

------
styled.div\`\` works, css\`\` works, but createGlobalStyle\`\` doesn't format.

**Comment by kitten** [comment]
This is likely an issue you'll have to take up with `prettier` or `vscode-styled-components`, depending on what actually does the formatting (it's likely Prettier), but I suppose it's unlikely they'll want to support all of styled-component's API 😅

**Comment by kmvan** [comment]
Got it. Thanks.
