### ISSUE TITLE
How to type the nested objects of a theme 

### ISSUE THREAD

**Issue by LauraBeatris** [styled-components/styled-components#3209]
I read a lot of issues related to how to type a theme and I have been using the following solution: 

```
const theme = {
  {...}
  fonts: {
    families: {
      medium: "Roboto-Medium",
      regular: "Roboto-Regular",
      bold: "Roboto-Bold",
      light: "Roboto-Light",
    },
    sizes: {
      base: 24,
    },
  },
};

export type ThemeTypes = typeof theme;

export default theme;
```

The problem is when it gets to a point when there's a lot of nested objects and I want to access an index with given props. 

```
export const Title = styled.Text<TypographyProps>`
  ${({
    theme,
    fontSize,
    fontWeight = "bold",
  }) => css`
    font-family: ${theme.fonts.families[fontWeight]}; // Accessing a index with a given prop 
    font-size: ${fontSize || theme.fonts.sizes.base}px; 
    color: ${theme.colors.dark};
  `}
`;
```

But in order to do it, the indexes need to be typed, for instance: 
```
{ [index: key]: string | number } 
```

But this still doesn't work and the following error occurs: 

![Screenshot at Jul 25 09-43-26](https://user-images.githubusercontent.com/48022589/88457256-5b759600-ce5b-11ea-93ab-3762c95d5401.png)

How can be possible to type nested objects of a theme constant?

**Comment by JamesInCode** [comment]
Have you followed the steps outlined [here](https://styled-components.com/docs/api#create-a-declarations-file)? I ask as I notice that your `theme` object has no declared type.

**Comment by LauraBeatris** [comment]
Yup! I forgot to add the snippet of the module too: 
```

import { ThemeTypes } from "../styles/theme";

declare module "styled-components" {
  export interface DefaultTheme extends ThemeTypes {}
}
```

**Comment by JamesInCode** [comment]
What type are you assigning to `fontWeight` inside of `TypographyProps`?

I'm guessing you either need to specify a type for it other than string, or you need to allow string indexing e.g:

`[K: string]: string;`

Here is a small working example:

```
type Font = 'REGULAR';

const theme: DefaultTheme = {
  fonts: {
    families: {
      REGULAR: 'Arial',
    },
  },
};

const StyledComponent = styled.div<{ font: Font }>`
  font-family: ${({ theme, font }) => theme.fonts.families[font]};
`;
```

**Comment by LauraBeatris** [comment]
I'm assigning string to ``fontWeight`` inside of ``TypographyProps`` 

```
interface TypographyProps {
  fontSize?: number;
  fontFamily?: string;
  fontWeight?: string;
  color?: string;
}

```

Would be better to allow string indexing? But how can I apply it to the ``ThemeTypes``?

```
const theme = {
  colors: {
  {...}
  },
  fonts: {
    families: {
      medium: "Roboto-Medium",
      regular: "Roboto-Regular",
      bold: "Roboto-Bold",
      light: "Roboto-Light",
    },
    {...},
  },
};

export type ThemeTypes = typeof theme & {[K: string]: string};
```

By the way, setting a string literal type to the ``fontWeight`` prop worked successfully! 
```
type FONT_WEIGHT = "bold" | "regular" | "light"

interface TypographyProps {
  fontSize?: number;
  fontFamily?: string;
  fontWeight?: FONT_WEIGHT;
  color?: string;
}
```

**Comment by LauraBeatris** [comment]
Now I'm exporting the type of the theme object and also the string literal type of the font weights available: 

```
export type FONT_WEIGHT = keyof typeof theme.fonts.families;

export type ThemeTypes = typeof theme;
```

**Comment by probablyup** [comment]
Just FYI we don't maintain the types, this might be better-suited for DefinitelyTyped.

**Comment by kitten** [comment]
Sorry, I'll have to close this.

We don't maintain any TypeScript typings in the main repository and are not updating the ones that live in `definitely-typed`, so we can't offer any help on this here. It's possible that if you browse past issues you'll find similar questions, but overall this repository's issues are not the right place to report these issues or to discuss them.
