### ISSUE TITLE
How to use CSS Entities with styled component ? 

### ISSUE THREAD

**Issue by Nikhil-devloper** [styled-components/styled-components#3210]
How to use CSS Entities with styled component ? 

https://codesandbox.io/s/divine-flower-ui5d0?file=/src/App.js

## Steps to reproduce
```
const Label2 = styled.span`
  background-color: red;
  color: black;
  border: 2px solid white;
  border: 2px solid white;
  border-radius: 5px;
  padding: 4px;
  &:after {
    content: " \0234";
  }
`;

export default function App() {
  return (
    <div className="App">
      <Label2> My Label 2 </Label2>
    </div>
  );
}
```

## Expected Behavior
Should Render Css Entitie

## Actual Behavior
Not Rendering Css Entitie

**Comment by kitten** [comment]
When you use escape characters like a backslash in JS strings (including tagged template literals) then they'll be processed as part of the JS string instead of the CSS string. Therefore you'll need to use a double backslash to escape the backslash in JS, I.e. `\\`

**Comment by Nikhil-devloper** [comment]
yes sir, this is working, I haven't found any reference for this on the Internet. Thank you for this awesome lib. amazing work.

Working Snippet for future devs.

  &:after {
    content: " \\222";
  }
