### ISSUE TITLE
Not an ISSUE issue, but just curious

### ISSUE THREAD

**Issue by t1amat9409** [styled-components/styled-components#3212]
# Is there a way, one would implement this for a react custom renderer?

1. Do you have a usage question?
=============================
- Want to try or create a custom renderer for React-NativeScript? https://react-nativescript.netlify.com/

2. Think you found a bug?
=============================
- NOPE

3. Do you have a feature request?
=============================
- NOPE

## Steps to reproduce
Create a PR?
## Expected Behavior
Same as ReactJS or RN
## Actual Behavior
Not started

**Comment by probablyup** [comment]
Hmm, I'm open to a PR if you want to take a crack at it.

**Comment by t1amat9409** [comment]
Hey @probablyup, thanks I'd appreciate that
