### ISSUE TITLE
'content' property can't be CSS Code, e.g. content: '\2022'; throws error

### ISSUE THREAD

**Issue by andrekovac** [styled-components/styled-components#3218]
**Bug**: CSS Code can't be used in the `content` property, for example `content: '\2022';` doesn't work

For a [bullet](https://www.toptal.com/designers/htmlarrows/punctuation/bullet/) I can't use `\2022` as I do in normal CSS. It however works with the character itself `● ` (i.e. `content: '●';`) which is even better. It just is not the way you do it in CSS. I moved some CSS to styled-components and it took me a while to realize what's going on...

## Reproduction

https://codesandbox.io/s/styled-components-playground-5hcj9?fontsize=14&hidenavigation=1&theme=dark

## Steps to reproduce

Just open the codesandbox link and you'll see the error in the line `content: '\2022';`

## Expected Behavior

Should render a bullet point

## Actual Behavior

Throws an error

**Comment by kitten** [comment]
You'll have to escape the backslash so it's not evaluated in JS. There's a prior issue for this here: https://github.com/styled-components/styled-components/issues/3210#issuecomment-663869829
