### ISSUE TITLE
Spacing props on styled components are passed through to underlying DOM element.

### ISSUE THREAD

**Issue by cbadger85** [styled-components/styled-components#3220]
## System:
 - OS: macOS Mojave 10.14.6
 - CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
 - Memory: 680.33 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 12.18.2 - /usr/local/bin/node
 - Yarn: 1.22.4 - /usr/local/bin/yarn
 - npm: 6.14.5 - /usr/local/bin/npm
## npmPackages:
 - styled-components: ^5.1.1 => 5.1.1 

## Reproduction

https://codesandbox.io/s/infallible-rgb-95llg?file=/src/App.js

## Steps to reproduce

 1. Add a spacing prop to a styled component.
 2. Inspect the element with browser dev-tools to notice a spacing attribute.

## Expected Behavior

The spacing prop on the styled component will not get passed through to the underlying element.

## Actual Behavior

When creating a styled component with a spacing prop, that prop gets passed through to the underlying DOM element as a spacing attribute.
 
<img width="522" alt="div element with spacing attribute" src="https://user-images.githubusercontent.com/42970983/89747714-9bf12880-da85-11ea-9a0e-7b5fdba4c5ad.png">

**Comment by kitten** [comment]
A prop is passed on when it also is somehow associated to an existing HTML attribute. You have three options now on how to handle this:

- Rename the prop and use a different name
- Prefix the prop with `$` as `$spacing` which means it'll never be passed on (https://github.com/styled-components/styled-components/pull/3052)
- Add a `shouldForwardProp` function (https://github.com/styled-components/styled-components/pull/3006)

**Comment by cbadger85** [comment]
Unless I'm mistaken, there is no spacing html attribute though? I've googled around and found no reference to one. MDN doesn't mention a spacing attribute either.

https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes
