### ISSUE TITLE
Possible bug with referring to other components

### ISSUE THREAD

**Issue by gergobalogh** [styled-components/styled-components#3222]
## System:
 - OS: Linux 5.4 Ubuntu 18.04.5 LTS (Bionic Beaver)
 - CPU: (4) x64 Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz
 - Memory: 449.05 MB / 15.52 GB
 - Container: Yes
 - Shell: 4.4.20 - /bin/bash
## Binaries:
 - Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
 - npm: 6.14.5 - ~/.nvm/versions/node/v14.4.0/bin/npm
## npmPackages:
 - styled-components: ^5.1.1 => 5.1.1 

## Reproduction
Hover of child does not apply to parent:
I have a div which has an svg as first child. On hover of the svg I want the parent div to have a border top. 
I have attached a screenshot of my own IDE how I tried: 
![image](https://user-images.githubusercontent.com/31627579/89858457-70fef580-dba7-11ea-99aa-39056002523e.png)

## Steps to reproduce
https://codesandbox.io/s/styled-components-dsz24

## Expected Behavior
Change the style of the Nav div on hover of the Scissor svg. 

## Actual Behavior
Nothing happens.

**Comment by kitten** [comment]
If I'm reading this screenshot right then you have a selector that says `${Scissor}:hover &` on `Nav` but your DOM structure has `Nav` wrapping `Scissor`.

This means that your hover rule is reversed and won't apply, since `Scissor` is a child of `Nav` but the selector targets the opposite relationship.

**Comment by gergobalogh** [comment]
Yep. You're right. After reading through many stackoverflow issues I now realise that this is not possible through simple CSS (as the name states: it's Cascading Style Sheets), so it will not go up in selectors. 
As it's not an issue with styled components I'm closing this. 
Thank you very much for your answer!
