### ISSUE TITLE
React error (rules-of-hooks) on createStyledComponent

### ISSUE THREAD

**Issue by jjoselv** [styled-components/styled-components#3226]
## System:
 - OS: macOS 10.15.6
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
 - Memory: 85.31 MB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 8.17.0 - ~/.nvm/versions/node/v8.17.0/bin/node
 - npm: 6.13.4 - ~/.nvm/versions/node/v8.17.0/bin/npm

## Reproduction
When using a library that I developed with styled-components in my project, this error happens:

Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://fb.me/react-invalid-hook-call for tips about how to debug and fix this problem.

It is talking about this line:
https://github.com/styled-components/styled-components/blob/2aa15b3da64d3e799e0fde6634300f9893a4c1c3/packages/styled-components/src/models/StyledComponent.js#L243

**Comment by kitten** [comment]
Have you duplicated react or react-Dom in your library bundles or dependencies by any chance?

**Comment by jjoselv** [comment]
Probably now that you ask...
But I'm curious about that piece of code, is it agains rules-of-hooks?

**Comment by Anenth** [comment]
I am also facing the same issue, As soon as I as `styled-components`, I get this same error.

**Comment by kitten** [comment]
As pointed out above, this is caused by build issues and/or duplicate packages. See prior issues on the subject:

- https://github.com/styled-components/styled-components/issues/2608
- https://github.com/styled-components/styled-components/issues/3045
- https://github.com/styled-components/styled-components/issues/3187

**Comment by Anenth** [comment]
The issue was the built, I was using rollup to built and it was creating 2 versions of react in the bundle. I fixed it by adding in the rollup config.

```
  external: [
    'react',
    'react-dom',
  ],
```
