### ISSUE TITLE
Styled-components's Overflow does not work on safari.

### ISSUE THREAD

**Issue by alakdam07** [styled-components/styled-components#3227]
In my react app, There is one aside chatbox. I have used `overflow:hidden` and `overflow-y: auto;`. It works fine in Chorme and Firefox but In safari it does not work. I have checked styled-components documentation but did not find any where how to specify for safari. 

`.comments-wrapper {
    overflow: hidden; # does not work in safari
    overflow-y: auto; # does not work in safari
    padding: 20px;
    flex: 1 1 50px;
    width: 100%;
    position: relative;
    z-index: 1;
   margin:20px;
  }`

**Comment by AdamSiekierski** [comment]
Does the `overflow` property show up in the inspector? If yes, it's not a problem with styled-components.

**Comment by alakdam07** [comment]
Yes it does show. 
<img width="390" alt="Untitled 2" src="https://user-images.githubusercontent.com/47625626/90304223-2b4f6f00-debe-11ea-8d07-13b998f3da54.png">

Does styled components have special syntax for browser site. So I can styling manually for the safari.

**Comment by AdamSiekierski** [comment]
I don't think so. But why would you want to do that. I think that it's just the problem with your CSS. Maybe replace

```css
overflow: hidden;
overflow-y: auto;
```

with

```css
overflow-x: hidden;
overflow-y: auto;
```

**Comment by alakdam07** [comment]
No sir, it did not help 😔.

**Comment by AdamSiekierski** [comment]
> No sir, it did not help 😔.

Or maybe just replace both with `overflow: auto`?

**Comment by AdamSiekierski** [comment]
The thing is that it for sure isn't a problem with styled-components 😉

**Comment by kitten** [comment]
This is indeed not a problem with styled-components but a CSS question 😅 You also haven't submitted enough markup and information to check what's going on.

Please ask a question on Stackoverflow, where you'll likely get help quicker ✌️
