### ISSUE TITLE
[React Native] Pressable styling

### ISSUE THREAD

**Issue by GfxKai** [styled-components/styled-components#3228]
## Intro

`Pressable`, a new component in React Native 0.63, is a `View` under the hood with some pre-defined event handlers for touch interactions. It also passes a `pressed` boolean to both its `style` and `children` props, which can be used to adjust styling/content based on the pressed state of the component.

## Standard Example
```jsx
<Pressable
  onPress={doSomething}
  style={({ pressed }) => ({
    backgroundColor: pressed
      ? 'rgb(210, 230, 255)'
      : 'white'
  })}
>
  {({ pressed }) => (
    <Text style={styles.text}>
      {pressed ? 'Pressed!' : 'Press Me'}
    </Text>
  )}
</Pressable>
```

## Issue
So far I've failed to implement this component without explicitly passing the `pressed` prop into a child `View` and styling _that_ with styled-components, which feels like an unnecessary step:

```jsx
<Pressable onPress={onPress}>
  {({ pressed }) => (
    <StyledView pressed={pressed}>
      ...
    </StyledView>
  )}
</Pressable>
```
The `style` prop for `Pressable` is defined as:
`style={typeof style === 'function' ? style({pressed}) : style}`

 Is it possible to style the `Pressable` component directly, using this `pressed` state, via the styled-components API ?

**Comment by jong-hui** [comment]
I got same problem, I think it needs to be fixed.

**Comment by tkow** [comment]
I found keep compatibility hatch.

```tsx
import React, { useMemo } from 'react'
import styled from 'styled-components/native'
import {
  Pressable as RNPressable,
  PressableProps as RNPressableProps,
} from 'react-native'

type MergePressableStylesFn = (
  style?: RNPressableProps['style'],
) => RNPressableProps['style']

const mergePressableStyles: MergePressableStylesFn = (style) => {
  if (typeof style === 'function') return style
  if (Array.isArray(style)) {
    return (state) => {
      return style.map((sty: any) => {
        return typeof sty === 'function' ? sty(state) : sty
      })
    }
  }
  return style
}

export const Pressable: React.FC<RNPressableProps> = ({
  style,
  ...props
}: RNPressableProps) => {
  const _style = useMemo(() => mergePressableStyles(style), [style])
  return <RNPressable style={_style} {...props} />
}

export const Button = styled(Pressable)<RNPressableProps>`
  display: flex;
  flex-direction: row;
  justify-content: center;
  align-items: center;
`

```

Above Pressable and Button both stylings form outside props and styled extension work without changing type  of native components' props.

**Comment by PedroAlmeidaFetchly** [comment]
import styled from 'styled-components'
import { Pressable } from 'react-native'

const PressableStyleded= styled(Pressable)``

**Comment by nelsonprsousa** [comment]
> import styled from 'styled-components' import { Pressable } from 'react-native'
> 
> const PressableStyleded= styled(Pressable)``

OP is trying to know how to control the Pressable styling based on the `pressed` property, not how to use styled components.
