### ISSUE TITLE
Proposal: Access to generated class names for building selectors

### ISSUE THREAD

**Issue by erikras** [styled-components/styled-components#323]
What I am about to describe here is something I've run into a few times in converting my project from SCSS to `styled-components`. It might not be remotely feasible, but it's an idea I had so I'm throwing it out there.

### SCSS

When the element with the `A` class _also_ has the `B` class, it should be red, and the element inside it with the `C` class must be blue. Pretty straightforward:

```scss
.A {
  color: black;
  &.B {
    color: red;
    & > .C {
      color: blue;
    }
  }
}
.C {
  color: yellow;
}
```

### Styled Components

It's my understanding that this is currently not possible in `styled-components` without passing whatever conditional that turns `B` on to _both_ the `A` and `C` elements. Like so:

```jsx
const A = styled.div`
  color: black;
  ${props => props.conditional && css`
    color: red;
  `}
`
const C = styled.div`
  color: yellow;
  ${props => props.conditional && css`
    color: blue;
  `}
`
```

...and then...

```jsx
<A conditional={someState}>
  blah
  <C conditional={someState}/>
</A>
```

This seems suboptimal.

------

Disclaimer: I have no idea if what follows is genius, idiotic, feasible or impossible.

------

## Proposal

The reason that we have to pass the conditional to the inner `C` element is because we don't know the class name that will be generated to represent the styles of `C`. But what if we did?

Something like this, perhaps:

```jsx
const A = styled.div`
  color: black;
  ${props => props.conditional && css`
    color: red;
      & > ${C.selector} { // <------------------------ 💥 THERE'S THE MAGIC 💥
        color: blue;
      }
  `}
`
const C = styled.div`
  color: yellow;
`
```

...where `C.selector` is set to its generated class name before all the template literals are processed.

See how that reads much more like the SCSS? Would something like this be possible? Or even desirable?

**Comment by k15a** [comment]
Duplicate: https://github.com/styled-components/styled-components/issues/142

**Comment by erikras** [comment]
Ha! Glad to see I'm not crazy. 👍
