### ISSUE TITLE
Duplicated classNames

### ISSUE THREAD

**Issue by Mattese** [styled-components/styled-components#3230]
## System:
 - OS: Windows 10 10.0.18362
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 6.90 GB / 15.86 GB
## Binaries:
 - Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
 - npm: 6.14.2 - C:\Program Files\nodejs\npm.CMD
## npmPackages:
 - babel-plugin-styled-components: ^1.10.7 => 1.10.7
 - styled-components: ^5.1.0 => 5.1.1

## Reproduction

https://codesandbox.io/s/styled-components-base-gc367

Package.Json setup: 
"dependencies": {
    "@material-ui/core": "^4.10.0",
    "@sentry/browser": "^5.17.0",
    "@sentry/node": "^5.17.0",
    "@sentry/webpack-plugin": "^1.11.1",
    "@types/classnames": "^2.2.10",
    "@types/cors": "^2.8.6",
    "@types/express": "^4.17.6",
    "@types/express-http-proxy": "^1.6.1",
    "@types/morgan": "^1.9.0",
    "@types/styled-components": "^5.1.0",
    "@types/yup": "^0.29.0",
    "@zeit/next-source-maps": "^0.0.3",
    "babel-plugin-styled-components": "^1.10.7",
    "classnames": "^2.2.6",
    "cookie": "^0.4.1",
    "cors": "^2.8.5",
    "cross-env": "^7.0.2",
    "dayjs": "^1.8.28",
    "express": "^4.17.1",
    "express-http-proxy": "^1.6.0",
    "lodash-es": "^4.17.15",
    "morgan": "^1.10.0",
    "next": "9.4.2",
    "next-i18next": "^4.4.2",
    "next-redux-wrapper": "^5.0.0",
    "react": "16.13.1",
    "react-calendar": "^3.1.0",
    "react-dom": "16.13.1",
    "react-google-maps": "^9.4.5",
    "react-hook-form": "^5.7.2",
    "react-icons": "^3.10.0",
    "react-number-format": "^4.4.1",
    "react-redux": "^7.2.0",
    "react-tabs": "^3.1.1",
    "redux": "^4.0.5",
    "redux-devtools-extension": "^2.13.8",
    "redux-thunk": "^2.3.0",
    "reselect": "^4.0.0",
    "styled-components": "^5.1.0",
    "swr": "^0.2.2",
    "url": "^0.11.0",
    "yup": "^0.29.0"
  },
  "devDependencies": {
    "@types/node": "^14.0.5",
    "@types/react": "^16.9.35",
    "@types/react-redux": "^7.1.9",
    "@typescript-eslint/eslint-plugin": "^3.3.0",
    "@typescript-eslint/parser": "^3.3.0",
    "babel-plugin-inline-react-svg": "^1.1.1",
    "eslint": "^7.2.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-prettier": "^3.1.4",
    "eslint-plugin-react": "^7.20.0",
    "prettier": "^2.0.5",
    "ts-node": "^8.10.2",
    "typescript": "^3.8.3"
  }

## Expected Behavior
ClassNames are unique.

## Actual Behavior

In my Next.js project we have an issue, that after every production build some parts of css are missing on not correctly rendered. We have found out that it happens, because some classNames are duplicated. However we dont know what causes this behavior and how to fix it.  
![image](https://user-images.githubusercontent.com/43894914/90894459-eac18b00-e3c0-11ea-9b24-57678c5952b3.png)

Has anyone encountered this ?

**Comment by Mattese** [comment]
https://github.com/styled-components/styled-components/issues/3125 Here they recomend downgrade styled-components to v 4.4.1

**Comment by linxianxi** [comment]
Oh!. Is there only one solution to reduce the version to 4.4.1?   :(

**Comment by kitten** [comment]
This is a duplicate as mentioned above, however no reporter has yet to add any details or investigate this thoroughly, so both issues are rather stale 😅

**Comment by inside** [comment]
Hi @Mattese 
Can you provide a reproduction repo or codesanbox?
I don't see the issue in the link (https://codesandbox.io/s/styled-components-base-gc367) provided in the description.
Thanks in advance

**Comment by jonkwheeler** [comment]
Just a reminder, this issue only exists in `production` environments. Thus, no codepen / sandbox will be able to reproduce it, making it worse to debug. This thread, https://github.com/styled-components/styled-components/issues/3125, has more information.
