### ISSUE TITLE
VSCode and Typescript-very much inhibits intelligent processing

### ISSUE THREAD

**Issue by gromov-io** [styled-components/styled-components#3231]
```
## System:
 - OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
 - CPU: (4) x64 Intel(R) Pentium(R) CPU G4600 @ 3.60GHz
 - Memory: 2.52 GB / 15.53 GB
 - Container: Yes
 - Shell: 5.0.17 - /bin/bash
## npmPackages:
 - @types/styled-components: ^5.1.2 => 5.1.2 
 - styled-components: ^5.1.1 => 5.1.1 
 - typescript: ^3.8.3 => 3.9.7
```
## Steps to reproduce
`yarn add @types/styled-components`

## Expected Behavior
Adding types to styled-components

## Actual Behavior
VS Code smart lighting takes 3-5 seconds.
Before installing ' @types/styled-components`, it was 100-200ms

I know that this problem is not on your side. But with such performance drawdowns-the product can not be used, now we have to delete it from the project 'styled-conponents' as the search for a solution to this problem was not found.

We really hope that you can help us find a solution to this performance problem.

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/34391

**Comment by mgcrea** [comment]
Not sure if related but another issue I encountered is that `@types/styled-components` does have `@types/react-native` as a dependency. For web projects it gets auto-loaded and breaks some unrelated typings (from [`@types/react-native/globals.d.ts](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-native/globals.d.ts)). Does not look like you can exclude a specific `@types` package from `tsconfig.json`.

**Comment by probablyup** [comment]
Hi there, we don't maintain the types... they're community-supported at DefinitelyTyped. Please feel free to move this issue there!
