### ISSUE TITLE
Lets DISABLE All runtime processing?

### ISSUE THREAD

**Issue by MaxmaxmaximusAWS** [styled-components/styled-components#3249]
Lets DISABLE All runtime preprocessing?
===

Final goal
-

Allow to generate FILES of css styles, at the compilation stage with webpack, which will be loaded into the browser as a separate file, in a separate parallel http2 stream, and put only dynamic pieces of css code in the javascript bundle. And also accelerate the runtime to cosmic speeds. That is, almost completely remove overhead.

by the way, actually prefixes and preprocessors SHOULD be processed ONLY at compile time. doing this runtime, some kind of madness.

those who need prefixes can always run their code through the babel plugin, which will find all the styled stringtags and pass them through the css transpilers like postcss, stylus and auto-prefixers, etc.

I don't understand why you brought this to runtime o_O

The very fact of using React ALREADY implies the use of a preprocessor. (For JSX at least) If we see React, then we automatically understand that there is Babel or Typescript there. This means that we have full control over the compilation, and we can add plugins.

How to turn off all unnecessary runtime activity?

For example, you can add support for the following syntax:

```js
const Button = styled.button`
:host {
  color: red
}
:host:hover {
  color: blue
}
`
```
`:host` its like `&`. If we add support for this syntax to the runtime, then it will be easy to add babel plugins that generate the necessary code in advance.

In addition, support for such a syntaxis is orders of magnitude faster than the `stylis` runtime transpiler.

Let's discuss this concept of avoiding runtime computing. This will give people more flexibility and customization. It will also speed up styled-components. 

Moreover, we can come up with some kind of format that is convenient for runtime processing, and force our babel plugin to compile all string tags into this pre-parsed format, like this:

```js
const Button = styled.button`
  color: red;
  width: ${ 100 + 'px' };

  &:hover{
    width: ${ 300 + 'px' };
  }
`
```
compiles to:

```js
const Button = styled.ast({
  tag: "button",
  selectors: [
    {
      selector: ":host"
      parts: ["color: red;\n  width: ", ";"],
      interpolations: [100 + 'px']
    },

    {
      selector: ":host:hover"
      parts: ["    width: ", ";\n"],
      interpolations: [300 + 'px']
    },
]
})
```

By the way
--

Here we have the following code:
```js
const Button = styled.button`
  color: red

  ${props => props.blue && css`
     color: blue;
     font-size: 2em;
  `}
`
```

We can parse it by babel and webpack and create one css file:

```css
.main {color: red}
.modificator {color: blue; font-size: 2em}
```
and js data for styleed-components runtime:
```js
const Button = styled.ast({
  tag: "button",
  class: "main",
  interpolations: [props => props.blue &&
     styled.ast.classModificator("modificator")
  ]
})
```

And if only babel could not cope and parse our file, then only in those rare cases, the runtime will be used. For example like this:

Babel was able to parse:
-
```js
const mainColor = css'color: red'

const Button = styled.button`
  ${ mainColor }
`
```
compile to:

css:
```css
.modificator{ color: red }
```

js:
```js
const mainColor = styled.ast.classModificator("modificator")

const Button = styled.ast({
  tag: "button",
  class: ""
  interpolations: [mainColor]
})
```

Babel wasnt able to parse
-
```js
import { mainColor } from './constants.js'

const Button = styled.button`
  color: ${ mainColor }
`
```
compile to:

```js
import { mainColor } from './constants.js'

const Button = styled.ast({
  tag: "button",
  class: ""
  interpolations: [mainColor]
})
```

Then mainColor will not be included in the css file but will exist as a runtime construction `css'color: red'`

Summary
-
Of course, all these optimization layers can be increased, for example, if two different components, in different files, have two modifier classes that add red, for example 

css
```css
.modif_1{ color: red; font-size: 2em; }
.modif_2{ color: red; }
```

some additional webpack plugin can compress this css even more:

```css
.modif_1{ font-size: 2em; }
.modif_1, .modif_2{ color: red; }
```

Let's discuss =)
-

P.S. I created an issue for a convenient api for creating plugins for the `babel-plugin-styled-components` plugin, f anyone is interested, read https://github.com/styled-components/babel-plugin-styled-components/issues/300

**Comment by kitten** [comment]
I think this is completely outside of what styled-components the library can pivot to. Maybe check out Linaria or Astroturf. But what you're proposing in short is a new library, not an option, due to the scale of this, and those other libraries exist. 😉

**Comment by MaxmaxmaximusAWS** [comment]
@kitten in that case they are better than styled-components and you want to live with that?

**Comment by kitten** [comment]
Yes. This is not a competition or a race. `styled-components` is essentially an API for runtime-based CSS-in-JS and Linaria and Astroturf are mostly static-based.

Whether our feature set and implementation will shift in the future to enable similar features is a point of speculation and not competitiveness.

Either way, there's little to be discussed. In one case it becomes a feature in styled-components, in another the approach is different so new projects attempt to solve it which is what's happened here. I also know the maintainers of Linaria for instance.

So, no, I don't think any of us core contributors have or should have a problem with another project having a different feature set with different trade offs.

**Comment by MaxmaxmaximusAWS** [comment]
> Yes. This is not a competition or a race.
Open source it is

**Comment by MaxmaxmaximusAWS** [comment]
@kitten 
Why we cant join to ways, runtime and compile time?

**Comment by kitten** [comment]
I mean, I won't explain why it's not a competition, so let's leave it at that.

> Why we cant join to ways, runtime and compile time?

As I've written above:

> there are similar issues in our repo around static extraction, where I've written previously about why unfortunately these features are somewhat incompatible with some of our other features and mechanisms right now.

It has to do with how we handle interpolations, specificity, rule ordering, and composition. So the incompatibility of both ideas runs pretty deep.

**Comment by MaxmaxmaximusAWS** [comment]
@kitten can we add runtime other preprocessors?

**Comment by kitten** [comment]
No, that doesn't work because of interpolations. Please just look up past issues and discussions on this.

If we even get very specific. This is just a duplicate of past discussions.

There was an entire effort around statically analysing CSS-in-JS code with interpolations and all. It's not trivial.

You also can't just allow any preprocessor. That's not how interpolations can be handled. Not to say why we'd even want any preprocessing. Only a fraction of people would even be interested in that since it has no added value.

**Comment by MaxmaxmaximusAWS** [comment]
@kitten You are right, you know what I know, and you know even more. You are always one step ahead. Thanks for your time StyledComponents is a great library that has benefited a lot of people. Thank you for your work. And for a competent interpolation mechanism. And I apologize if I made a duplicate.

**Comment by kitten** [comment]
No worries! It's getting harder to find the older discussions the older the project becomes. I just did a little digging. Basically there are lots of comments here and there and a lot of internal discussions that probably didn't go around.

But if you want to skip that here's a document that just addresses one problem. If we had a parser and/or all means to do static extraction then what happens to dynamic v static rules? And the answer isn't pretty https://gist.github.com/kitten/7b8a021f19ead2ec534091976a1ff6dc

**Comment by MaxmaxmaximusAWS** [comment]
@kitten flag and settings can be used to maintain backward compatibility. who wants - will use the old style, who wants, locally, will be able to enable the new behavior. why not do this?

**Comment by kitten** [comment]
Because first of all, the issue above isn't reconcilable as is in a any logical way. And second of all, maintaining a hodgepodge of flags or options is a good sign that API design isn't great — although that'd still assume we'd have a solution here.

So anyway, stick to Linaria, maybe this will change if we find new research around the predictability of atomic styles that still work well with our current mechanisms.

But overall what we're aiming for is predictability, and not solving all distinct use cases in one.
