### ISSUE TITLE
PR: Migration to Jest

### ISSUE THREAD

**Issue by amilajack** [styled-components/styled-components#325]
Would a migration to Jest be welcome?

**Comment by mxstbr** [comment]
Yes, please!!

**Comment by rolfea** [comment]
Hi @amilajack, are you still working on this migration? I'd be interested in helping out. 
I'm new to Jest and styled-components and interested in digging into the source code

**Comment by amilajack** [comment]
I actually forgot to do this! Thanks for the reminder! And yea, sure. I'll create a branch on my fork that you can commit to

**Comment by rolfea** [comment]
@amilajack is that your fix-ci-config branch?

**Comment by amilajack** [comment]
I actually didn't create a branch yet because I wanted to merge the updates branch first.

https://github.com/styled-components/styled-components/pull/380

Turns out that there were a number of complications that prevent it from moving forward quickly. I'll create  new branch and let you know about it

**Comment by jacobp100** [comment]
Happy to help with this if needed!

**Comment by mxstbr** [comment]
Yes?! We want this!

**Comment by amilajack** [comment]
@jacobp100 I'm running low on time these days so i haven't been able to implement this. Would be great if you could give it a go!

**Comment by jacobp100** [comment]
Will do!

**Comment by mxstbr** [comment]
v2 I guess?
