### ISSUE TITLE
There is no possibility to set DISABLE_SPEEDY=true when process.env.NODE_ENV != production

### ISSUE THREAD

**Issue by ctretyak** [styled-components/styled-components#3253]
If process.env.NODE_ENV === "development" (or other different from "production") you always have DISABLE_SPEEDY===false even if you set SC_DISABLE_SPEEDY = false this statement will return true

https://github.com/styled-components/styled-components/blob/e56952a7d77be17dac9307dcee50e6eae5cd783f/packages/styled-components/src/constants.js#L17

**Comment by fastfedora** [comment]
FYI, I just submitted PR #3289 to fix this issue.

**Comment by kitten** [comment]
Closing since it's resolved.

Please don't forget to be a good netizen on GitHub and revisit issues, especially ones that have been resolved and need to be closed, or ones that have received replies ❤️
