### ISSUE TITLE
Elevation not unitless when returned as object from interpolations 

### ISSUE THREAD

**Issue by klase** [styled-components/styled-components#3254]
## Reproduction
In React Native, when returning an object with the elevation prop from an interpolation the value gets converted to a string with a px unit leading to a warning: 
Warning: Expected style "elevation: 2px" to be unitless.

https://codesandbox.io/s/little-cdn-jh396?file=/src/App.js

Even though the above codesandbox is not React native, you can see the behaviour is the same:
<img width="300" alt="Screenshot 2020-09-03 at 16 38 17" src="https://user-images.githubusercontent.com/1711650/92129706-29653580-ee04-11ea-91fd-dd6e351b56d9.png">

if elevation is set to a string rather than a number it is left unitless.

## Steps to reproduce
See codesandbox

## Expected Behavior
Elevation remains unitless ("2").

## Actual Behavior
Elevation is converted to "2px"

**Comment by dkoprowski** [comment]
Thanks for the workaround with string.

```js
const Container = styled(Box)(() => ({
  elevation: '7',
}))
```

This removed the warning. 

Unfortunately for normal StyleSheet (without styled-components) we have to use `number` as `string` throws an error. This generates non consistent code and leads to mistakes. It would be nice to fix this in the package.

**Comment by kitten** [comment]
As far as I can tell, this has been resolve in `css-to-react-native`: https://github.com/styled-components/css-to-react-native/blob/4f96cf6bb81b48894b53bce041512d495de715ba/src/devPropertiesWithoutUnitsRegExp.js#L5

**Comment by Weegle99** [comment]
Experiencing it too with all libs up to date, any news ?

**Comment by johnpatrickmorgan** [comment]
I'm also experiencing this issue with up-to-date libs.

> As far as I can tell, this has been resolve in css-to-react-native: https://github.com/styled-components/css-to-react-native/blob/4f96cf6bb81b48894b53bce041512d495de715ba/src/devPropertiesWithoutUnitsRegExp.js#L5

@kitten It looks to me like that list of properties is used to (correctly) determine if a warning should be shown. I think the real issue - the unwanted appending of `px` to elevation properties that triggers that warning - happens in [this function](https://github.com/styled-components/styled-components/blob/30dab74acedfd26d227eebccdcd18c92a1b3bd9b/packages/styled-components/src/utils/addUnitIfNeeded.ts#L10-L12). As far as I can tell, it relies on `@emotion/unitless`, which [does not list elevation as a unitless property](https://github.com/emotion-js/emotion/blob/d25316393639232df16ba836b407e3678eea5e4d/packages/unitless/src/index.js), which means it appends `px` as the default unit. I'm not sure if the fix should be applied in `styled-components` or upstream in `@emotion/unitless` - what do you think?

**Comment by janpe** [comment]
@kitten perhaps this should be reopened? I'm seeing this problem with aspectRatio as well.

**Comment by ineswq** [comment]
Also seeing this problem with `shadowOpacity`
