### ISSUE TITLE
is it possible to attach stylesheet directly to the componentId?

### ISSUE THREAD

**Issue by rajzik** [styled-components/styled-components#3255]
I have a question according to the functionality of the styled components.
If [styledComponentId](https://github.com/styled-components/styled-components/blob/d4b9ee8a3c1514cac57e22209bcd6102e10f79b1/packages/styled-components/src/models/StyledComponent.js#L180) is provided is it possible to omit [generatedClassName](https://github.com/styled-components/styled-components/blob/d4b9ee8a3c1514cac57e22209bcd6102e10f79b1/packages/styled-components/src/models/StyledComponent.js#L181).

reference [function](https://github.com/styled-components/styled-components/blob/d4b9ee8a3c1514cac57e22209bcd6102e10f79b1/packages/styled-components/src/models/StyledComponent.js#L119).

__Related [issue](https://github.com/styled-components/babel-plugin-styled-components/issues/299)__

I am not really sure about how this should work, but if styledComponentId is present shouldn't we omit generatedClassName? 

## Reproduction

https://codesandbox.io/s/brave-gates-5mhqi

## Steps to reproduce

- Currently styled component will attach two classNames: `src__Div-my-app__adb5uh-0 gTItGB`.
- But only the hash(generatedClassName) part has attached the styles.

## Expected Behavior

- Generated className should only contain `src__Div-my-app__adb5uh-0`
   ```html
   <style>.src__Div-my-app__adb5uh-0{color:pink;}</style>
   ```
- Or styles should be attached to both classes.
   ```html
   <style>
      .src__Div-my-app__adb5uh-0,.gTItGB{color:pink;}
      // OR
      .src__Div-my-app__adb5uh-0.gTItGB{color:pink;}
    </style>
   ```
## Actual Behavior

- Current stylesheet:
   ```html
    <style>.gTItGB{color:pink;}</style>
   ```

**Comment by rajzik** [comment]
@probablyup @kitten @geelen @mxstbr you are most active contributors, can you give some feedback about this?

**Comment by mxstbr** [comment]
The empty class name (component ID) is global to a _component_, the class name with the styles is local to an _instance_ of a component (or more specifically, a set of props).

Having the component ID classname is useful to edit the styles for e.g. your `<Button />` in DevTools. If we only provided the generated instance classname, you could only edit e.g. all your `<Button primary />` at once but all other buttons would stay unaffected.

However, if you add styles to the component ID classname, all `<Button />`s will have those styles applied no matter which props you pass to different ones! 👍
