### ISSUE TITLE
Error: 'typeOf' is not exported by node_modules/react-is/index.js, imported by node_modules/styled-components/dist/styled-components.esm.js

### ISSUE THREAD

**Issue by cieldon32** [styled-components/styled-components#3256]
my technology stack: rollup + styled-components
when I run build,  I got the error:
Error: 'typeOf' is not exported by node_modules/react-is/index.js, imported by node_modules/styled-components/dist/styled-components.esm.js

and I run "npm list react-is"
@ywfe/ywd@0.0.1 /Users/xiayun/yw/ywd
├─┬ @storybook/addon-actions@6.0.21
│ └─┬ prop-types@15.7.2
│   └── react-is@16.13.1  deduped
├─┬ @types/jest@25.2.3
│ ├─┬ jest-diff@25.5.0
│ │ └─┬ pretty-format@25.5.0
│ │   └── react-is@16.13.1  deduped
│ └─┬ pretty-format@25.5.0
│   └── react-is@16.13.1  deduped
├─┬ antd@4.6.2
│ ├─┬ rc-collapse@2.0.0
│ │ └── react-is@16.13.1  deduped
│ └─┬ rc-util@5.2.1
│   └── react-is@16.13.1  deduped
├─┬ jest@26.4.2
│ └─┬ @jest/core@26.4.2
│   └─┬ jest-config@26.4.2
│     └─┬ pretty-format@26.4.2
│       └── react-is@16.13.1  deduped
├── react-is@16.13.1 
├─┬ styled-components@5.1.1
│ └─┬ hoist-non-react-statics@3.3.2
│   └── react-is@16.13.1  deduped
└─┬ ts-jest@26.3.0
  └─┬ @types/jest@26.0.13
    └─┬ pretty-format@25.5.0
      └── react-is@16.13.1  deduped

my package.json:
`
{
  "name": "@ywfe/ywd",
  "version": "0.0.1",
  "description": "ui framework base on antd",
  "main": "lib/ywd.cjs.js",
  "module": "lib/ywd.esm.js",
  "scripts": {
    "build": "NODE_ENV=production rollup -c",
    "build:type": "tsc -p ./tsconfig.type.json",
    "publish:npm": "npm publish --access public",
    "dev": "rollup -c -w",
    "lint": "NODE_ENV=development eslint . --cache --ext .js,.jsx,.ts,.tsx",
    "lint-fix": "yarn --silent lint --fix; exit 0",
    "test": "jest --coverage",
    "storybook": "start-storybook -p 6006",
    "build-storybook": "build-storybook"
  },
  "repository": {
    "type": "git",
    "url": "http://gitlab.ywwl.com/yfe/ywd.git"
  },
  "keywords": [
    "ui"
  ],
  "author": {
    "name": "YWFE",
    "email": "ywfe@ywwl.com",
    "url": "http://ywfe.com"
  },
  "license": "MIT",
  "devDependencies": {
    "@babel/core": "^7.9.6",
    "@babel/plugin-proposal-class-properties": "^7.10.4",
    "@babel/plugin-proposal-object-rest-spread": "^7.11.0",
    "@babel/plugin-transform-runtime": "^7.11.0",
    "@babel/preset-env": "^7.11.0",
    "@babel/preset-react": "^7.10.4",
    "@storybook/addon-actions": "^6.0.21",
    "@storybook/addon-essentials": "^6.0.21",
    "@storybook/addon-links": "^6.0.21",
    "@storybook/cli": "^6.0.21",
    "@storybook/react": "^6.0.21",
    "@types/jest": "^25.2.3",
    "@types/node": "^14.0.5",
    "@types/react": "^16.9.49",
    "@typescript-eslint/eslint-plugin": "^3.10.1",
    "@typescript-eslint/parser": "^3.0.0",
    "babel-eslint": "^10.1.0",
    "babel-loader": "^8.1.0",
    "babel-plugin-import": "^1.13.0",
    "babel-plugin-styled-components": "^1.11.1",
    "eslint": "^7.1.0",
    "eslint-config-airbnb": "^18.2.0",
    "eslint-config-airbnb-typescript": "^9.0.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-loader": "^4.0.2",
    "eslint-plugin-flowtype": "^5.1.0",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-jsx-a11y": "^6.3.1",
    "eslint-plugin-prettier": "^3.1.3",
    "eslint-plugin-react": "^7.20.6",
    "eslint-plugin-react-hooks": "^4.1.0",
    "getstorybook": "^1.7.0",
    "husky": "^4.2.5",
    "jest": "^26.0.1",
    "lint-staged": "^10.2.6",
    "prettier": "^2.0.5",
    "react-is": "^16.13.1",
    "rollup": "^2.10.8",
    "rollup-plugin-babel": "^4.4.0",
    "rollup-plugin-commonjs": "^10.1.0",
    "rollup-plugin-eslint": "^7.0.0",
    "rollup-plugin-node-resolve": "^5.2.0",
    "rollup-plugin-sourcemaps": "^0.6.2",
    "rollup-plugin-terser": "^7.0.1",
    "rollup-plugin-typescript": "^1.0.1",
    "rollup-pluginutils": "^2.8.2",
    "ts-jest": "^26.0.0",
    "tslib": "^2.0.0",
    "typescript": "^3.9.3"
  },
  "dependencies": {
    "@ywfe/hook-subscription": "^0.0.1",
    "antd": "^4.6.2",
    "react": "^16.13.1",
    "styled-components": "^5.1.1"
  },
  "husky": {
    "hooks": {
      "pre-commit": "lint-staged"
    }
  },
  "lint-staged": {
    "*.{ts,js}": [
      "eslint -c .eslintrc.js"
    ],
    "*.{ts,js,json}": [
      "prettier --write"
    ]
  }
}

`

my rollup.config.js:
`
import pkg from "./package.json";
import typescript from "rollup-plugin-typescript";
import sourceMaps from "rollup-plugin-sourcemaps";
import resolve from "rollup-plugin-node-resolve";
import commonjs from "rollup-plugin-commonjs";
import babel from "rollup-plugin-babel";
import { terser } from "rollup-plugin-terser";
import { eslint } from "rollup-plugin-eslint";
import * as Antd from "antd";

const isDev = process.env.NODE_ENV !== "production";

export default {
  input: "./components/index.ts",
  output: [
    {
      format: "cjs",
      file: pkg.main,
      sourcemap: true,
    },
    {
      format: "es",
      file: pkg.module,
      sourcemap: true,
    },
  ],
  external: ["antd"],
  plugins: [
    typescript({
      exclude: "node_modules/**",
      typescript: require("typescript"),
    }),
    sourceMaps(),
    resolve(),
    commonjs(),
    eslint({
      throwOnError: true,
      throwOnWarning: false,
      include: ["components/**"],
      exclude: ["node_modules/**"],
    }),
    babel({
      exclude: "node_modules/**",
      runtimeHelpers: true,
      plugins: ["babel-plugin-styled-components"],
      presets: ["@babel/env", "@babel/preset-react"],
    }),
    !isDev && terser(),
  ],
};

`

my .babelrc:
`
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "loose": true,
        "modules": false
      }
    ],
    ["@babel/preset-react",
    {
      "modules": false,
      "useBuiltIns": "usage",
      "corejs": "2.6.10",
      "targets": {
        "ie": 11
      }
    }]
  ],
  "plugins": [
      ["babel-plugin-styled-components"],
      ["@babel/plugin-transform-runtime"],
      [
        "@babel/plugin-proposal-class-properties",
        {
          "loose": true
        }
      ],
      ["@babel/plugin-proposal-object-rest-spread"],
      ["import", {"libraryName": "antd", "libraryDirectory": "lib", "style":"css"}],
  ],
  "ignore": [
      "node_modules/**"
    ]
}

`

**Comment by cieldon32** [comment]
when I use     "styled-components": "^4.3.2", it's work

**Comment by cieldon32** [comment]
use "styled-components": "5.1.0", it's work

but

use "styled-components": "5.1.1", not work

**Comment by hare451g** [comment]
got same issue here, i use  "styled-components": "5.1.1", "5.1.0", and "5.2.0" not work

#### .babelrc
```js
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ],
  "plugins": [
    "babel-plugin-styled-components"
  ]
}
```

#### rollup.config.js

```js
import babel from 'rollup-plugin-babel';
import resolve from 'rollup-plugin-node-resolve';
import commonjs from 'rollup-plugin-commonjs';

import packageJson from './package.json'

export default {
  input: "src/common/index.js",
  output: [
    {
      file: packageJson.main,
      format: "cjs",
      sourcemap: true
    },
    {
      file: packageJson.module,
      format: "esm",
      sourcemap: true
    }
  ],
  plugins: [
    babel({
      exclude: "node_modules/**"
    }),
    resolve(),
    commonjs()
  ],
};
```

**Comment by kitten** [comment]
This issue is related to how you set up Rollup. The `commonjs` plug-in attempts to convert a CommonJS module to ESM, which is necessary for all React packages which don't ship with ESM bundles.

I personally would set it up like so:

```
  commonjs({
    ignoreGlobal: true,
    include: /\/node_modules\//,
    namedExports: {
      react: Object.keys(require('react')),
      'react-is': Object.keys(require('react-is')),
    },
  }),
```

I'd also recommend that you set up Rollup's `external` setting to prevent all these modules from being bundled (both React and styled-components shouldn't be bundled)
I may maintain a pretty complex Rollup setup here, so please feel free to have a look: https://github.com/FormidableLabs/urql/blob/baa76ae785e99dd42765ef689353d00a9ee69c92/scripts/rollup/settings.js#L44
