### ISSUE TITLE
Typescript - adding onClick prop to anchor

### ISSUE THREAD

**Issue by dalisalvador** [styled-components/styled-components#3258]
Hi!

I can't find a way to make this work:

```
const Insert = styled.a`flex: 1;   padding: 0.3rem;  padding-left: 0.6rem;`

<Insert onClick={handleInsert}>
```

`No overload matches this call.
  Overload 1 of 2, '(props: Pick<Pick<Pick<DetailedHTMLProps<AnchorHTMLAttributes<HTMLAnchorElement>, HTMLAnchorElement>, "slot" | ... 262 more .............`

Can't find the proper way to add `Insert` props types
Thanks!

**Comment by Heiiji** [comment]
Hi,
I've the same problem but i've found that : https://stackoverflow.com/questions/61979237/styled-components-attrs-w-typescript

I hope is good solution ^^

**Comment by kitten** [comment]
Sorry, I'll have to close this.

We don't maintain any TypeScript typings in the main repository and are not updating the ones that live in `definitely-typed`, so we can't offer any help on this here. It's possible that if you browse past issues you'll find similar questions, but overall this repository's issues are not the right place to report these issues or to discuss them.
