### ISSUE TITLE
className error with tagged template literals

### ISSUE THREAD

**Issue by bethany-dawn** [styled-components/styled-components#3259]
## System:
 - OS: macOS 10.15.6
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 1.32 GB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 12.18.3 - /usr/local/bin/node
 - npm: 6.14.6 - /usr/local/bin/npm
## npmPackages:
 - styled-components: ^5.1.1 => 5.1.1 

## Steps to reproduce
```
import styled from 'styled-components';

const url = 'http://some.url';
const SectionWrapper = styled.div`
	background: transparent url(${url});
`;

export default function Section() {
	return (
		<SectionWrapper />
	);
}
```

## Expected Behavior
There should be no js errors

## Actual Behavior
react-dom.development.js:88 Warning: Prop `className` did not match. Server: "SlackGifs__SectionWrapper-qaav9b-0 iHZGCN" Client: "SlackGifs__SectionWrapper-qaav9b-0 dmoTdH"
    in div (created by SlackGifs__SectionWrapper)
    in SlackGifs__SectionWrapper (at SlackGifs.js:54)
    in SlackGifs (at pages/index.js:93)
    in div (created by pages__PageWrapper)
    in pages__PageWrapper (at pages/index.js:55)
    in Home (created by App)
    in App
    in ErrorBoundary (created by ReactDevOverlay)
    in ReactDevOverlay (created by Container)
    in Container (created by AppContainer)
    in AppContainer

**Comment by justAdevTV** [comment]
@bethany-dawn are you using Nextjs or any other SSR approach by any chance?

**Comment by bethany-dawn** [comment]
Yes, I'm using NextJs. I should also mention this only happens if you are using a variable, it's working fine everywhere else.

**Comment by justAdevTV** [comment]
I believe this is happening not because of SSR, but because you're not providing dimensions for `width` & `height`.

When you have an empty `<div />` the default dimensions are 0x0.

You need to set it like this first:
```JS
const SectionWrapper = styled.div`
  background: transparent url(${url});
  // I added this part
  width: 100%;
  height: 100%;
`;
```

Alternatively, you can also give `SectionWrapper` `children` props like this and it'll match the size of the children:
```JS
<SectionWrapper>Hello!</SectionWrapper>
```

**Comment by bethany-dawn** [comment]
I'm not sure what this has to do with width and height? I have both set, actually, this was a bare bones example to show the error. Everything is displaying properly, it just gives the above error in the console.

**Comment by justAdevTV** [comment]
Ahh I gotcha. It works in my development environment. I think your config might be off. 

**Questions:**
1. Do you have `babel-plugin-styled-components` in your `devDependenies`? 
2. And do you also have this in your `.babelrc`:
```JS
{
  "presets": ["next/babel"],
  "plugins": [["styled-components", { "ssr": true }]]
}
```
3. Is your style injection logic correct? Check out my mini-guide here:
https://stackoverflow.com/questions/49288987/styled-components-with-components-in-nextjs/63805372#63805372

**Comment by bethany-dawn** [comment]
Unfortunately none of the above steps solved the issue.

**Comment by justAdevTV** [comment]
The warning you posted is a known issue on Nextjs ([see here](https://github.com/vercel/next.js/issues/7322)). That being said because it's a warning can't be the cause of your template literal issue. An error would break your code. 

Is there anything else you can provide? Maybe a sandbox link? I have no clear view of why it's breaking.

**Comment by bethany-dawn** [comment]
I'll close this issue, and follow the one in NextJs. Thanks!
