### ISSUE TITLE
How to share a styled component

### ISSUE THREAD

**Issue by kopax** [styled-components/styled-components#326]
@mxstbr , I've started using react-boilerplate and styled-components with this as my only experience with webpack so I come to ask some help in order to support the ecosystem.

I really wan't to share some work made using styled components, but I can't get my webpack configuration to work.

I have folders of components using for example has import :

```jsx
import React from 'react';
import styled from 'styled-components';
import cn from 'classnames';
import defaultThemeProps from 'styled/themes/bootstrap/atoms/Abbr';
import React from 'react';
import styled from 'styled-components';
import cn from 'classnames';
import Close from 'components/bootstrap/atoms/Close';
import defaultThemeProps from 'styled/themes/bootstrap/atoms/Alert';
import { alertVariant } from 'styled/helpers/bootstrap/mixins/alert';
import { borderRadius } from 'styled/helpers/bootstrap/mixins/border-radius';
import { srOnly } from 'styled/helpers/bootstrap/mixins/screen-reader';
import onClickOutside from 'react-onclickoutside';
import defaultThemeProps from 'styled/themes/bootstrap/molecules/DropDown';
import { borderRadius } from 'styled/helpers/bootstrap/mixins/border-radius';
import { boxShadow } from 'styled/helpers/bootstrap/mixins/box-shadow';
import { navDivider } from 'styled/helpers/bootstrap/mixins/nav-divider';
import { hoverFocus, plainHoverFocus } from 'styled/helpers/bootstrap/mixins/hover';
import { buttonGroup } from 'styled/helpers/bootstrap/utilities/buttonGroup';
```

All the bootstrap mixins and components are rewritten in a react-boilerplate app.

Every component have 100% unit test using the exact same config as `react-boilerplate`.

I also have all the documentation with example using our  Bootstrap styled-component, with some adjustment for fitting the need of `styled-components`.

_For example, we don't use reset, and we have a few utilities that need and can be injected using the injectGlobal and an utility. It's convenient and completely customization._

My idea was to start new components only from that lib that own the basic css and customization I need for styling.

I would like to be able to import my component like this : 

```jsx
import A from 'bootstrap-styled/A'
import Link from 'bootstrap-styled/Link'
import Dropdown from 'bootstrap-styled/Dropdown'
import { fade } from 'bootstrap-styled/helpers/mixins/animation'
```

I use to create npm package in ES5, this become a bit to hard to start with the webpack documentation. Would anyone share a webpack gist so I can start building my component for dist?

**Comment by nelix** [comment]
If you are using react-boilerplate (so all your webpack tooling is setup), we can call this package bootstrap-styled. So anything you export default from your index.js will be whats at the root.


 `node_modules/bootstrap-styled/index.js`
``` javascript 
export default 'hello';
```

`->`

``` javascript 
import thing from 'bootstrap-styled';
console.log(thing); // => 'hello'
```

So if you want 'bootstrap-styled/Link', well that is just a file system path. so you can place Link.js next to index.js and anything you export from there will be as desired. Which would look like this.

 `node_modules/bootstrap-styled/Link.js`
``` javascript 
export default () => (
  <div> Hi! </div>
);
```

`->`

``` javascript 
import thing from 'bootstrap-styled';
React.render(<thing/>); // => <div> Hi! </div>
```

Check out [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export) for decenent but brief documentation.

**Comment by kopax** [comment]
@nelix, thanks for your answer, I got all that first part, but I didn't get how you exported Link.

Did you mean `import thing from 'bootstrap-styled/Link';` ?

I was looking at this plugin https://github.com/kadirahq/react-cdk but I wasn't able to configure it to work the same as in react boilerplate :/

So if you tell me I can use the exact same projet, this will be much easier

**Comment by nelix** [comment]
I mean in your library, the filename is literally Link.js.

If your library's entry point had 
Lol.js bah.js index.js

then you could import 'libname/filename' (with or without the .js extension) or import 'libname' to get the index

I honestly would try reading an article or the new webpack docs, the boiler plate can shelter you from solving some hard to learn problems the burn you when you have a big technical debt an cannot do any fault isolation.

**Comment by kopax** [comment]
@nelix , I have try to read docs and articles but most of them are not up to date or/and use a bunch of different plugins.
If you have good article that could help me understand the 3.3.3 / 3.4 of the boilerplate, I would be happy to read it.

**Comment by kopax** [comment]
@nelix, I am just thinking that the way it is configured, webpack only build one chunked file, so I guess the options of building with the current webpack configuration is not possible.

Is there any other alternative ? Would it be possible to have a documentation for that ? I think this is somehow important for everyone.

**Comment by k15a** [comment]
Why are you not exporting them as named export in your entry file?
```JS
export { A } from './A.js'
export { Link } from './Link.js'
```
So you can import them like:
```JS
import {
  A,
  Link
} from 'styled-bootstrap'
```

If you're using webpack@2 you can find really good documentation at https://webpack.js.org/. You're probably searching for the [externals option](https://webpack.js.org/configuration/externals/#externals) so `React` and `styled-components` aren't included in your bundle.

**Comment by kopax** [comment]
can we reopen this ?

> Why are you not exporting them as named export in your entry file?

I have more than just components (tags), I also have all the mixins and helpers bootstrap have.
I have functionalities that can be used to inject part of bootstrap, for examples to `injectSpacing` to be used in `injectGlobal`.

Thing like this, exporting everything in one file is not very conveniant.

I have copied the react-boilerplate configuration and removed everything I though it wasn't usefull for that.

I need to reorganize the folders and import while making it as a module so I've just added the A components and all the mixins, would you mind have a look to my webpack config and see how I could prepare this for releasing it correctly ?

**Comment by kopax** [comment]
I forgot the link https://github.com/kopaxgroup/bootstrap-styled
