### ISSUE TITLE
Syntax error in regular expression on IE11

### ISSUE THREAD

**Issue by N1cc3** [styled-components/styled-components#3266]
## Environment

IE11

## Reproduction

Syntax error appears instantly when opening page using styled-components@5.2.0 in IE11.

`Syntax error in regular expression`

Most probably caused by dd6b3028f91dbbf1c026f7ee58d1ec1bea76b765.

`/([A-Z])/g` works but `new RegExp(/([A-Z])/, 'g');` breaks.

**Comment by kitten** [comment]
True; I believe I've missed that the `RegExp` constructor in IE11 only accepts strings, although I did suggest to just expand the regex to a standard literal regex.
