### ISSUE TITLE
Getting Error while using styled-components with CDN

### ISSUE THREAD

**Issue by Kilims** [styled-components/styled-components#3272]
Currently i am using styled-components via CDN , and react-is has been added

CDNs:
```
<script src="https://unpkg.com/react-is@16/umd/react-is.production.min.js"></script>
<script src="https://unpkg.com/styled-components/dist/styled-components.min.js"></script>
```
page shows ok and could get `window.styled` object in console

but after deployment, i 've got this error in console:
```
Uncaught TypeError: Cannot use 'in' operator to search for 'default' in undefined
```

any suggestion to remove this error?

![image](https://user-images.githubusercontent.com/22916814/93090471-62888a00-f6cf-11ea-9ce6-e05b3c762546.png)

**Comment by Summer-andy** [comment]
have you soloved?

**Comment by zlaja1983** [comment]
any update or workaround for this?

**Comment by ChristopherHButler** [comment]
+1 - Any progress on this?

**Comment by christemple** [comment]
After going through the v5 release notes [1] it seems that if you're loading from the CDN you need to make sure you're loading the `react-is` dependency prior to loading styled-components

Example:
https://unpkg.com/react-is@17.0.2/umd/react-is.production.min.js
https://unpkg.com/styled-components@5.2.3/dist/styled-components.js

[1] https://github.com/styled-components/styled-components/releases/tag/v5.0.0

**Comment by kitten** [comment]
I think since `react-is` has been dropped as a dependency there's little chance this will come back. To the submitter, please don't forget to include reproductions ❤️  In this case, it would have been a single HTML file, which really saves time in documenting how the issue changes over time and when/how it's resolved or can be resolved.
