### ISSUE TITLE
Dynamically generated styles don't get added to a popup window

### ISSUE THREAD

**Issue by dmt0** [styled-components/styled-components#3274]
## Environment

 - OS: macOS 10.15.6
 - Node: 12.13.1 - ~/.nvm/versions/node/v12.13.1/bin/node
 - Yarn: 1.22.5 - /usr/local/bin/yarn
 - npm: 6.12.1 - ~/.nvm/versions/node/v12.13.1/bin/npm

### Steps to reproduce

Using [react-new-window](https://github.com/rmariuzzo/react-new-window), create a popup. The popup includes a styled-component (say, a toggle). Everything is displayed properly (as the initial styles get copied from parent to popup on initialization) until you try to interact with a component in a way that changes its state. At that point the newly generated CSS class gets added to the `<head>` of the parent window, instead of the popup, so the component appears unstyled in the popup.

### Expected Behavior

CSS gets added to current window

### Actual Behavior

CSS gets added to parent window

**Comment by kitten** [comment]
Hiya, this is expected behaviour. Styles will always be added to styled-components' default style tag instead of anywhere else.

You may want to look into the `StyleSheetManager` provider to add an alternative style tag for a sub tree.

**Comment by dmt0** [comment]
Thanks @kitten, worked like a charm! My solution ended up looking something like this:

```javascript
import React from 'react';
import styled, {StyleSheetManager} from 'styled-components';
import NewWindow from 'react-new-window';

class Parent extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      showPopout: false,
    };
    this.nwRef = React.createRef();
  }

  render () {
    ... some stuff
    this.state.showPopout && (
    <StyleSheetManager target={this.nwRef.current}>
      <NewWindow
        title="Title"
        features={{width: '960px', height: '600px'}}
        onUnload={() => this.setState({showPopout: false})}
      >
        <div ref={this.nwRef}>
          <Popout isPopout={true}>
            ... popup stuff
          </Popout>
        </div>
      </NewWindow>
    </StyleSheetManager>
  )}
}
```
