### ISSUE TITLE
v5.2.0 minify break me

### ISSUE THREAD

**Issue by xingyibiao** [styled-components/styled-components#3275]
v5.2.0 minify break me. can minify output other file? like, xxx.min.js, not default file. anyone want use premini load this file.

**Comment by kitten** [comment]
Sorry, you'll have to add some details here.

I'm aware that we changed a minor setting in our Rollup build in this release. I won't exclude the possibility that it may have broken something, and I was planning to refactor it soon, but without details we can't help you

**Comment by xingyibiao** [comment]
My webpack config can`t resolve file by minify(I don`t know why).   

v5.2.0 output default min file by tersa, it break me. so I have to use v5.1.1. I`m sorry for my english. except someone can change rolllup config, don`t set minify by default.  except xxx.min.js

**Comment by kitten** [comment]
What exactly can't it resolve?

**Comment by xingyibiao** [comment]
If not output no minify, I hava to lock v5.1.1

**Comment by xingyibiao** [comment]
I thank terser plugin should used by user but not lib. If someone use lib by script tag,  may they need minify ouput

**Comment by xingyibiao** [comment]
another question break my another project!   
```js
he=/([A-Z])/,pe=new RegExp(he,"g")
```
![image](https://user-images.githubusercontent.com/24382926/93975869-a9027680-fdaa-11ea-9980-ecd6847779eb.png)
[mdn](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp)

In ie9 or chrome 39, It will throw a error,  does v5.2.0 lib just support es6?

**Comment by Ginhing** [comment]
https://github.com/styled-components/styled-components/blob/df94ac41323209a2037475e2a491e19e327c7e08/packages/styled-components/src/utils/hyphenateStyleName.js#L9

found the source location of exception above. It is a bug of  babel plugin somehow?

**Comment by kitten** [comment]
I think that may have not been published as a fix yet; I'll have to double check that

**Comment by Ginhing** [comment]
It seems to be fixed on 5.2.1
