### ISSUE TITLE
Selecting Pseudo Elements of a Child

### ISSUE THREAD

**Issue by varlevi** [styled-components/styled-components#3276]
Hello. I have a quick question that doesn't seem to have been addressed anywhere. My question is, how do I select an element's child's pseudo elements (specifically, ::before and ::after)?

To be more specific, here's my code. I'm trying to create a link with a dynamic underline that's triggered by the parent element being hovered on.

```
const MainLink = styled.div`
  height: 250px;
  background: url(${props => props.imageUrl || "none"}) no-repeat right;
  display: flex;
  justify-content: center;
  flex-direction: column;
  &:hover ${PaddedLinkText}::after {
    width: 90%;
    transition: 0.3s ease all;
  }
`

const PaddedLinkText = styled.p`
  margin-left: 15%;
  color: #000;
  font-weight: 400;
  font-family: 'Inter';
  text-decoration: none;
  position: relative;
  &:hover {
    cursor: pointer;
    color: ${props => props.inputColor || "#333"};
  }
  &::after {
    top: 65%;
    height: 2px;
    width: 0%;
    left: 5%;
    background-color: rgba(255, 255, 255, 0.6);
    transition: 0.5s ease all .3s;
`

<MainLink imageUrl={smackdownImage}>
      <PaddedLinkText inputColor="#222731">See Good News Smackdowns</PaddedLinkText>
</MainLink>

```

**Comment by maxsbelt** [comment]
Hi @varlevi. Actually there are a couple of issues with your code:
- `PaddedLinkText` should be declared before `MainLink`
- missing `}` bracket at the end of `PaddedLinkText` declaration
- pseudo element `::after` requires `content: ''` to be displayed in the page and `position: absolute` for `top,left` attributes.

I created codesandbox example that solves your issues.
https://codesandbox.io/s/spring-dew-orlyb?file=/src/App.js

**Comment by varlevi** [comment]
@maxsbelt Thanks for pointing out those issue. It seems to have mostly fixed the problem. The only issue left is that declaring `width: 90%` is making the ::after element 90% of the width of `MainWidth` element. Is there a simple way to fix this?

**Comment by maxsbelt** [comment]
I think you just need to add `align-items: flex-start` to `MainLink`:

![fix](https://user-images.githubusercontent.com/950216/93856384-a1b36e00-fcc1-11ea-85e4-b3099b8bed07.gif)

**Comment by varlevi** [comment]
@maxsbelt Thanks so much for your help! That seems to have resolved everything!
