### ISSUE TITLE
Remove logo animation that makes people feel sick at least when users have said in their OS settings that they don't want such animations

### ISSUE THREAD

**Issue by jfhector** [styled-components/styled-components#3278]
## Context

- Quality websites meet the Web Content Accessibility Guidelines 2.1 level AA at a minimum, in order to unnecessarily exclude or disable people.
- In particular, [if you show things that animate automatically, and if it lasts for more than 5 seconds, people need to be able to easily stop the animation](https://www.w3.org/WAI/WCAG21/Understanding/pause-stop-hide.html).
  - You should ensure that's the case. But the rest of my ticket is about another accessibility barrier, caused by the same visual element:
- Also, if you show scrolling that is fast, big, and users' brains don't expect, you can cause motion sickness.
  - The logos on the website home page do that. They make me feel sick.
  - Operating systems let people who are motion sensitive (like me) request that web pages don't show animations that are likely to make them feel sick.
  - All developers have to do, is to disable potentially triggering animations using the `prefers-reduced-motion` media query. [Here's how, and why](https://css-tricks.com/revisiting-prefers-reduced-motion-the-reduced-motion-media-query/).
- Please, if you're going to show animations that can make people feel sick, honour user's preferences to not see those, by using the `prefers-reduced-motion` media query. Or better still, don't show animations that can make people feel sick.

## Environment

https://styled-components.com/ on any operating system

## Steps to reproduce

1. In macOS > System Preferences > Accessibility > Display, tick 'Reduce motion'

<img width="780" alt="Screenshot 2020-09-18 at 18 54 40" src="https://user-images.githubusercontent.com/30028540/93629585-76d6ca80-f9e0-11ea-8286-8e54219171ce.png">

2. Go to https://styled-components.com/
3. Scroll down a bit until you see this:

<img width="1763" alt="image" src="https://user-images.githubusercontent.com/30028540/93629443-3bd49700-f9e0-11ea-9a95-4e8007fb1122.png">

## Expected Behavior

The animation does not happen.

## Actual Behavior

The logos animate fast and continuously.

**Comment by niraj8** [comment]
[styled-components/styled-components-website](https://github.com/styled-components/styled-components-website) would be a better place to open this issue?

Should I move this there and raise a pull for needed changes?

**Comment by jfhector** [comment]
@niraj8 yes please, thanks a lot!

**Comment by marcelscruz** [comment]
The PR fixing the issue can be found [here](https://github.com/styled-components/styled-components-website/pull/731).
