### ISSUE TITLE
Typescript is enforcing color to be a type string when passed to a Styled Component

### ISSUE THREAD

**Issue by MylesWardell** [styled-components/styled-components#3279]
### System:
 - OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
 - Memory: 2.57 GB / 15.36 GB
 - Container: Yes
 - Shell: 5.0.17 - /bin/bash
### Binaries:
 - Node: 10.19.0 - /usr/bin/node
 - npm: 6.14.4 - /usr/bin/npm
### npmPackages:
 - styled-components: 5.1.1 => 5.1.1

## Example Bugged Keyword - color 
```typescript
import React from 'react'
import styled from 'styled-components'

interface Props {
  color: {
    main: string
    background: string
  }
}

const Container = styled.div<Pick<Props, 'color'>>`
  color: ${({ color }) => color.main};
  background-color: ${({ color }) => color.background};
`

const FooBox = (props: Props) => {
  const { color } = props
  return (
    <Container color={color}></Container>
  )
}
```

#### Error
```
No overload matches this call.
  Overload 1 of 2, '(props: Pick<Pick<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "style" | "title" | ... 252 more ... | "is"> & { ...; } & Pick<...>, "style" | ... 254 more ... | "is"> & Partial<...>, "style" | ... 254 more ... | "is"> & { ...; } & { ...; }): ReactElement<...>', gave the following error.
    Type '{ main: string; background: string; }' is not assignable to type 'string & { main: string; background: string; }'.
      Type '{ main: string; background: string; }' is not assignable to type 'string'.
  Overload 2 of 2, '(props: StyledComponentPropsWithAs<"div", any, Pick<Props, "color">, never>): ReactElement<StyledComponentPropsWithAs<"div", any, Pick<Props, "color">, never>, string | ... 1 more ... | (new (props: any) => Component<...>)>', gave the following error.
    Type '{ main: string; background: string; }' is not assignable to type 'string & { main: string; background: string; }'.
      Type '{ main: string; background: string; }' is not assignable to type 'string'.ts(2769)
index.d.ts(1694, 9): The expected type comes from property 'color' which is declared here on type 'IntrinsicAttributes & Pick<Pick<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "style" | ... 253 more ... | "is"> & { ...; } & Pick<...>, "style" | ... 254 more ... | "is"> & Partial<...>, "style" | ... 254 more ... | "is"> & { ...; } & { ...; }'
index.d.ts(1694, 9): The expected type comes from property 'color' which is declared here on type 'IntrinsicAttributes & Pick<Pick<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "style" | ... 253 more ... | "is"> & { ...; } & Pick<...>, "style" | ... 254 more ... | "is"> & Partial<...>, "style" | ... 254 more ... | "is"> & { ...; } & { ...; }'
```

## Not Bugged Keyword - Colour
```typescript
import React from 'react'
import styled from 'styled-components'

interface Props {
  colour: {
    main: string
    background: string
  }
}

const Container = styled.div<Pick<Props, "colour">>`
  color: ${({ colour }) => colour.main};
  background-color: ${({ colour }) => colour.background};
`;

const FooBox = (props: Props) => {
  const { colour } = props;
  return <Container colour={colour}></Container>;
}

export default FooBox
```

#### Error
No Error

## Steps to reproduce
Copy the code in the snippet to a new VS Code window set to Typescript React with styled-components installed. The error should come up via the typescript compiler

## Expected Behaviour
I could not find any existing default key of color in the [mozzila docs](https://developer.mozilla.org/en-US/docs/Web/API/HTMLDivElement) so I would expect it to pass the color prop through to the styled div

## Actual Behavior
Typescript seems to expect color to be a string rather than the type I set it via the props interface, I am still quite new to react typescript so there may be a reason to this behaviour.

**Comment by maxsbelt** [comment]
Hey @MylesWardell. The styled component extracts properties available for `div` element using `React.ComponentProps<'div'>` method. As you can see in [DefinitelyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L1791) `color` property is declared and has `color?: string` type (maybe because `color` was allowed long time ago in `<font>` tag.

You can provide your own interface that way:
```tsx
type Type = React.FC<Omit<React.ComponentProps<'div'>, 'color'>>;
type Props = {
  color: {
    main: string;
    background: string;
  };
};
const Container = styled<Type>(('div' as unknown) as Type)<Props>`
  color: ${({ color }) => colour.main};
  background-color: ${({ color }) => colour.background};
`;

const FooBox = (props: Props) => {
  return <Container color={props.color}></Container>;
}

```

But in such case `color` attribute will be passed to the generated DOM element which is not good:

<img width="514" alt="Screenshot 2020-09-21 at 10 54 36" src="https://user-images.githubusercontent.com/950216/93744369-639f4700-fbfa-11ea-91b0-4f1f34ff0394.png">

The recommended way to work with attributes that shouldn't be passed to the generated DOM is to use `transient props`:

```tsx
type Props = {
  $color: {
    main: string;
    background: string;
  };
};
const Container = styled.div<Props>`
  color: ${({ color }) => colour.main};
  background-color: ${({ colour }) => colour.background};
`;

const FooBox = (props: Props) => {
  return <Container $color={props.color}></Container>;
}
```

More about transient props you can read [in this article](https://medium.com/@probablyup/introducing-transient-props-f35fd5203e0c).

**Comment by MylesWardell** [comment]
> Hey @MylesWardell. The styled component extracts properties available for `div` element using `React.ComponentProps<'div'>` method. As you can see in [DefinitelyTyped repo](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L1791) `color` property is declared and has `color?: string` type (maybe because `color` was allowed long time ago in `<font>` tag.
> 
> You can provide your own interface that way:
> ```tsx
> type Type = React.FC<Omit<React.ComponentProps<'div'>, 'color'>>;
> type Props = {
>   color: {
>     main: string;
>     background: string;
>   };
> };
> const Container = styled<Type>(('div' as unknown) as Type)<Props>`
>   color: ${({ color }) => color.main};
>   background-color: ${({ color }) => color.background};
> `;
> 
> const FooBox = (props: Props) => {
>   return <Container color={props.color}></Container>;
> }
> 
> ```
> 
> But in such case `color` attribute will be passed to the generated DOM element which is not good:
> 
> <img width="514" alt="Screenshot 2020-09-21 at 10 54 36" src="https://user-images.githubusercontent.com/950216/93744369-639f4700-fbfa-11ea-91b0-4f1f34ff0394.png">
> 
> The recommended way to work with attributes that shouldn't be passed to the generated DOM is to use `transient props`:
> 
> ```tsx
> type Props = {
>   $color: {
>     main: string;
>     background: string;
>   };
> };
> const Container = styled.div<Props>`
>   color: ${({ $color }) => $color.main};
>   background-color: ${({ $color }) => $color.background};
> `;
> 
> const FooBox = (props: Props) => {
>   return <Container $color={props.color}></Container>;
> }
> ```
> 
> More about transient props you can read [in this article](https://medium.com/@probablyup/introducing-transient-props-f35fd5203e0c).

Thankyou for the assistance with a detailed explaination! I'll definatly take a look at transient props.

**Comment by kitten** [comment]
Sorry, I'll have to close this.

We don't maintain any TypeScript typings in the main repository and are not updating the ones that live in `definitely-typed`, so we can't offer any help on this here. It's possible that if you browse past issues you'll find similar questions, but overall this repository's issues are not the right place to report these issues or to discuss them.
