### ISSUE TITLE
Is it possible to use the other symbols like () instead of ` ?

### ISSUE THREAD

**Issue by jettangs** [styled-components/styled-components#328]
Is it possible to use the other symbols like () instead of ` ?

**Comment by dreamorosi** [comment]
Wouldn't that break the use of template literals for props and other stuff?

**Comment by vdanchenkov** [comment]
Why would you need it? Strictly speaking, you can always replace template literal with an equivalent function call, but you will loose magic of template literals.

```jsx
styled.div`color: red;` === styled.div([ 'color: red;' ])

styled.div`color: ${someColor};` === styled.div([ 'color: ', ';' ], someColor)
```

**Comment by jettangs** [comment]
@vdanchenkov I got it, thx!

**Comment by mxstbr** [comment]
See here for an explanation of why exactly we use tagged template literals: mxstbr.blog/2016/11/styled-components-magic-explained
