### ISSUE TITLE
Discriminated union props types are broken when inheriting styles.

### ISSUE THREAD

**Issue by AngusMorton** [styled-components/styled-components#3280]
Using TypeScript, if you have a component that can be restyled and has a discriminated union type as a prop when you try to restyle it using the `styled(MyComponent)` syntax the types don't work as expected.

Attached is a code sandbox, that is a bit contrived but highlights the issue we're having in our codebase: https://codesandbox.io/s/styled-components-discriminated-union-issue-1nswg

**Comment by maxsbelt** [comment]
Hey @AngusMorton. You need to pass props during the styled component initialization:

![fix](https://user-images.githubusercontent.com/950216/93855721-a1ff3980-fcc0-11ea-9262-4e24674b8277.gif)

**Comment by AngusMorton** [comment]
Maybe I'm misunderstanding something about how `styled` works, but I don't think specifying the props type should be required here... I feel like the default behaviour should be the `styled(Status)<StatusProps>` behaviour.

**Comment by kitten** [comment]
The typescript types for styled-components aren't maintained by us currently and haven't been for a while.

As far as I know they simply haven't been taken care of for a while since they're very complex but `definitely-typed` is the repository where you may want to pick up work on this 😅

**Comment by AngusMorton** [comment]
Thanks for your help.

Moved to https://github.com/DefinitelyTyped/DefinitelyTyped/issues/47963
