### ISSUE TITLE
Extra info section Typescript / Create a theme / React-Native

### ISSUE THREAD

**Issue by larsfoll** [styled-components/styled-components#3281]
The snippet about implementing a theme in React-Native with TypeScript in [the docs](https://styled-components.com/docs/api#create-a-theme) is rather confusing to me.

```
// styled-components.ts
import * as styledComponents from "styled-components/native";

import ThemeInterface from "./theme";

const {
  default: styled,
  css,
  ThemeProvider
} = styledComponents as styledComponents.ReactNativeThemedStyledComponentsModule<ThemeInterface>;

export { css, ThemeProvider };
export default styled;
```

I presume you always import styled, css and ThemeProvider from `./styled-components` instead of `styled-components/native`?

In an older project this was implemented without this file and imports would come from `styled-components/native`, which also seemed to work fine.

It would be great to have some extra documentation as to why this should be implemented and what additional benefits this brings.

PS: Thanks for the great work on this library!

**Comment by kitten** [comment]
Sorry, I'll have to close this.

We don't maintain any TypeScript typings in the main repository and are not updating the ones that live in `definitely-typed`, so we can't offer any help on this here. It's possible that if you browse past issues you'll find similar questions, but overall this repository's issues are not the right place to report these issues or to discuss them.

If you'd like to make a suggestion for the docs please check https://github.com/styled-components/styled-components-website
