### ISSUE TITLE
createGlobalStyle continuously adding to the server sheet.

### ISSUE THREAD

**Issue by markwoodward23** [styled-components/styled-components#3282]
## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`

## System:
 - OS: macOS 10.15.5
 - CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
 - Memory: 593.47 MB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 12.18.2 - ~/.nvm/versions/node/v12.18.2/bin/node
 - Yarn: 1.19.1 - ~/.yarn/bin/yarn
 - npm: 6.14.5 - ~/.nvm/versions/node/v12.18.2/bin/npm
## npmPackages:
 - babel-plugin-styled-components: 1.10.7 => 1.10.7
 - styled-components: 5.1.0 => 5.1.0

## Steps to reproduce

Don't create a new ServerStyleSheet on each request, and watch the global styles mount up. 

## Actual Behavior

This is user error, but I'm posting for interest. 

Context: we had a SSR-ing React application which uses styled-components. It powers https://www.sky.com/watch, amongst other pages. 

```js
const assetsHost = getAssetsHost();
const sheet = new ServerStyleSheet(); // created outside the function which is called to actually render the app.

export const renderApp = ({ App, config, appName, contextCookies = {} }) => (ctx, next) => {
  const statsFile = path.resolve(__dirname, '../../../dist/loadable-stats.json');

  const extractor = new ChunkExtractor({
    statsFile,
    entrypoints: [appName],
    publicPath: assetsHost
  });

  const component = (
    <ChunkExtractorManager extractor={extractor}>
      <StyleSheetManager sheet={sheet.instance}>
        <App
        etc.
```

App goes on to generate HTML and pass back to client etc.. 

The above code clearly doesn't follow the readme which suggested creating a new ServerStyleSheet on each page render, but interesting this came in as rising response time on the NodeJS app 
<img width="1143" alt="Screenshot 2020-09-22 at 20 34 27" src="https://user-images.githubusercontent.com/16290165/93929376-adc81b80-fd13-11ea-97e2-9c3080883fc4.png">

Digging through that led to an increase in HTML size: 
![image (22)](https://user-images.githubusercontent.com/16290165/93929473-d223f800-fd13-11ea-91b1-a23407fc39fd.png)

And trusty web archive led us here: `view-source:http://web.archive.org/web/20200914232107/https://www.sky.com/watch`

The main highlight here being the 31953 attempts to colour the background white:

```
body{background-color:white;}/*!sc*/
--
  | data-styled.g32027[id="sc-global-czvqin31953"]{content:"sc-global-czvqin31953,"}/*!sc*/
```

The last release we did which caused this to creep up starts using createGlobalStyle, but the offending code had been around in production way before that. 

A fix is landing shortly to create a fresh sheet each time, but in the meantime, is it expected that createGlobalStyle would continuously add to the same sheet, if a fresh sheet isn't instantiated each time?

**Comment by kitten** [comment]
This is expected behaviour based on the reproduction steps:

> Don't create a new ServerStyleSheet on each request, and watch the global styles mount up.

It's required that each render (so each request) has its own `ServerStyleSheet` 😅
