### ISSUE TITLE
Component crashes when css prop is used on component with dot notation `Comp.C`

### ISSUE THREAD

**Issue by sourabhv** [styled-components/styled-components#3287]
## System:
 - OS: macOS Mojave 10.14.6
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
 - Memory: 555.61 MB / 16.00 GB
 - Shell: 5.3 - /bin/zsh
## Binaries:
 - Node: 14.11.0 - /usr/local/bin/node
 - Yarn: 1.22.5 - /usr/local/bin/yarn
 - npm: 6.14.8 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: ^1.10.7 => 1.10.7
 - styled-components: ^5.2.0 => 5.2.0

## Reproduction

https://codesandbox.io/s/styled-components-css-macro-forked-voqno?file=/src/Hello.js

## Steps to reproduce

`Menu.Item` fails with error `Menu is not defined` if css prop is used, if the component is in another file, works fine if it is in same file

## Expected Behavior

It crashes

## Actual Behavior

it shouldn't crash

**Comment by kitten** [comment]
This is resolved, See: https://github.com/styled-components/babel-plugin-styled-components/blob/b7b4b3f6a3a25f7e7e64aa64b030a31fba2a2059/test/fixtures/transpile-css-prop/code.js#L90-L94
