### ISSUE TITLE
Targetting a [role="main"]

### ISSUE THREAD

**Issue by jeanmichelcote** [styled-components/styled-components#329]
I tried doing this but it didn't work:

```
const Block = styled.section[role="main"]`
...
`;
```

It may sound naive but how can I target with precision?

**Comment by kopax** [comment]
You can try : 

```jsx
const Block = styled.section`
  & [role="main"] {
    ...
  }
`;
```

I think the & will be replaced with the vendor prefix.

If you wan't to check the generated result, there is a <styles> tag injected at the header containing all the styled css.

**Comment by jeanmichelcote** [comment]
Makes sense, thanks!
