### ISSUE TITLE
Conflict with Webpack's 5 Federated Modules (Invalid hook call)

### ISSUE THREAD

**Issue by oncet** [styled-components/styled-components#3302]
When trying to consume a federated module that uses `styled-components`, React throws the "Invalid hook call" error.

### System
 - OS: macOS Mojave 10.14.6
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 1.13 GB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash

### Binaries
 - Node: 12.16.1 - /usr/local/bin/node
 - npm: 6.13.4 - /usr/local/bin/npm

### Dependencies
* react@16.13.1
* styled-components@5.2.0

## Reproduction

See this repository for reproduction code:

* https://github.com/oncet/federated-modules-styled-components

It contains 2 `npm` projects. Do `npm install` on both and start them in order (first `foo` then `shell`). Once everything is running, if you navigate to `/foo` you should see that the app crashes.

## Steps to reproduce

1. Create an `npm` project which exposes a component that uses `styled-components`.
2. Create another `npm` project that consumes and renders the federated module.

## Expected Behavior

React should be able to render the `styled` component.

## Actual Behavior

React throws a `Invalid hook call` error on the console when trying to render the `styled` component.

**Comment by ScriptedAlchemy** [comment]
You probably need to share react, or some context dependency of styled components. Make sure that these things are registered as singletons. If you post a repo somewhere I can take a look. Pretty sure we've seen this one before already at webpack. 

Check all the relevant repos, hosts and remote are sharing react and react dom, singletons. 

Make sure they share styled components. If you're using dynamic imports, that's best. If this is a static import it's sub-optimal. 

What it sounds like is either another copy of react is being pulled across, or there's two separately theme or context providers being created.

**Comment by ScriptedAlchemy** [comment]
Actually just checking your repo. The issue is you're sharing react too simply. Check my module federation example repo again and you'll see I'm configured differently. 

Use semver on react. Webpack probably doesn't know what to do and your using beta 16 style config. You want to specify react more explicitly with a semver value. React as a string. Webpack doesn't know how to handle, so sometimes it will guess or it might just not take the risk on unversioned modules that require singletons 


Here's all my latest changes to every example in my repo. This is the optimal solution. I'd recommend 

https://github.com/module-federation/module-federation-examples/pull/426

There's also advanced api examples for more sophisticated things.

**Comment by ScriptedAlchemy** [comment]
```

new ModuleFederationPlugin({
      name: "shell",
      filename: "remoteEntry.js",
      remotes: {
        order: "order@http://localhost:3002/remoteEntry.js",
        dashboard: "dashboard@http://localhost:3001/remoteEntry.js",
        profile: "profile@http://localhost:3004/remoteEntry.js",
        shell: "shell@http://localhost:3000/remoteEntry.js",
      },
      exposes: {
        "./Shell": "./src/Shell",
        "./Service": "./src/Service",
      },
      shared: [
        {
          ...deps,
          react: {
            singleton: true,
            requiredVersion: deps.react,
          },
          "react-dom": {
            singleton: true,
            requiredVersion: deps["react-dom"],
          },
        },
        // Workaround explaination: https://www.youtube.com/watch?v=-LNcpralkjM&t=540
        "./src/Service",
      ],
    }),

```

**Comment by oncet** [comment]
Thank you very much for your support. With this information I was able to solved the problem.

I only added `react` as a singleton in `foo/webpack.config.js` and it seems to be working fine.


```
new ModuleFederationPlugin({
      name: 'foo',
      filename: 'remoteEntry.js',
      exposes: {
        './Foo': './src/App',
      },
      shared: [{ react: { singleton: true } }],
    })
```

I couldn't make the `publicPath: 'auto'` config work though.

**Comment by ScriptedAlchemy** [comment]
You need to remove scripts from html if you have them. Also make sure to share react dom as well. Don't want multiple react instances loading.

**Comment by oncet** [comment]
I removed the linked scripts from the HTML already. I didn't share `react-dom` because I'm only using it on the `shell` (going for a single entry point approach).

Still trying out this wonderful new feature.

**Comment by ScriptedAlchemy** [comment]
If you don't share it though then remotes will download their own copy. Trust me you want to share it if it's installed on anything else. If it's not. Then you're good

**Comment by joeheyming** [comment]
I'm seeing this issue too.  I really would like to use module federation.
I'm on 

"react": "16.13.1",
"react-dom": "16.13.1",

Using styled components is ok for me, but when I use ant design, it crashes with 
react.development.js:1465 Uncaught Error: Invalid hook call. Hooks can only be called inside of the body of a function component.

**Comment by sagho0or** [comment]
Hi guys. Do you find any solution??

**Comment by sarathcakurathi** [comment]
I am facing the same problem, any solution for this?

**Comment by mumiao** [comment]
> 
Hi guys. Do you find any solution??

**Comment by necpoctt** [comment]
I am facing the same problem, any solution for this?

**Comment by aaronshaf** [comment]
Same issue

**Comment by glp** [comment]
+1

**Comment by eml-c2829** [comment]
.... hopeless

**Comment by ScriptedAlchemy** [comment]
Share react jsx runtime and dev runtime.
