### ISSUE TITLE
Update to 5.2.0 breaks IE11 compatibility

### ISSUE THREAD

**Issue by Link2Twenty** [styled-components/styled-components#3304]
### System:
 - OS: Windows 10 10.0.19041
 - CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
 - Memory: 20.57 GB / 31.92 GB
### Binaries:
 - Node: 12.18.3 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.22.5 - ~\AppData\Roaming\npm\yarn.CMD
 - npm: 6.14.8 - ~\AppData\Roaming\npm\npm.CMD
### npmPackages:
 - styled-components: ^5.2.0 => 5.2.0

## Steps to reproduce
Write some code with styles and build for IE

## Expected Behavior
Should work with polyfills

```js
import "react-app-polyfill/ie9";
import "react-app-polyfill/ie11";
import "jspolyfill-array.prototype.findIndex";
import "element-matches-polyfill";
```

## Actual Behavior
Returns an error
![image](https://user-images.githubusercontent.com/3534427/95653833-7919d980-0af3-11eb-9f52-5d7bdae3de1d.png)

```js
inject = (styleSheet: StyleSheet, stylisInstance: Stringifier = masterStylis) => {
    const resolvedName = this.name + stylisInstance.hash;

    if (!styleSheet.hasNameForId(this.id, resolvedName)) {
      styleSheet.insertRules(
        this.id,
        resolvedName,
        stylisInstance(this.rules, resolvedName, '@keyframes')
      );
    }
  };
```

This is the function the error points to

**Comment by koba04** [comment]
@Link2Twenty This has been fixed as https://github.com/styled-components/styled-components/pull/3267, but the fix is still not released. So you have to avoid using 5.2.0 and wait for a new release.
