### ISSUE TITLE
Declare generics on styled

### ISSUE THREAD

**Issue by bnayae** [styled-components/styled-components#3306]
When using styled component (which I really love) it force me to close my generics component into known types.
As result I'm loosing major part of the generics strength.

```js
interface IProps<T> {
  value: T;
  present: (val: T) => string;
}

export const Comp = <T extends unknown>({ value, present }: IProps<T>) => (
  <h1>{present(value)}</h1>
);
export const StyledComp = styled((p) => <Comp {...p} />)`
  justify-self: center;
  color: red;
`;

export const Comp1 = () => (
  <>
    {/* implicit generics (infer from the properties) */}
    <Comp value={{ x: 10 }} present={(m) => `${m.x}`} />
    <StyledComp value={{ x: 10 }} present={(m) => `${m.x}`} />
    {/* explicit generics */}
    <Comp<{ x: 10 }> value={{ x: 10 }} present={(m) => `${m.x}`} />
    <StyledComp<{ x: 10 }> value={{ x: 10 }} present={(m) => `${m.x}`} />
  </>
);
`;

```

Styled component swallow the generics.

![image](https://user-images.githubusercontent.com/3382669/95729109-0ccedf80-0c85-11eb-8146-91b89ca0e901.png)

**Comment by kitten** [comment]
Sorry, I'll have to close this.
We don't maintain any TypeScript typings in the main repository and are not updating the ones that live in definitely-typed.

I can't point you at a definitive place to ask this question; but there are also past issues about this
