### ISSUE TITLE
Uncaught TypeError: Cannot use 'in' operator to search for 'default' in undefined

### ISSUE THREAD

**Issue by Summer-andy** [styled-components/styled-components#3309]
hello， I clone this project in my local, and then i exec npm run dev， but in console errors come，``` Uncaught TypeError: Cannot use 'in' operator to search for 'default' in undefined  ```

**Comment by Summer-andy** [comment]
![image](https://user-images.githubusercontent.com/30104912/95807949-fa64ac80-0d3d-11eb-87e9-a33652428601.png)

**Comment by koba04** [comment]
@Summer-andy Have you read the [CONTRIBUTING.md](https://github.com/styled-components/styled-components/blob/master/CONTRIBUTING.md#code-contributions)? This project uses `yarn` instead of `npm`.

**Comment by Summer-andy** [comment]
I use yarn in this project. 1. ``` cd package/styled-components  ``` 2. ```yarn dev``` 3.throw error 
![image](https://user-images.githubusercontent.com/30104912/96198900-a13c8900-0f88-11eb-8f45-227f35fc051a.png)

**Comment by koba04** [comment]
@Summer-andy Thank you. I can reproduce its, I had to install `@babel/node` to run `yarn dev` though.

**Comment by zlaja1983** [comment]
any update on the fix here?

**Comment by Summer-andy** [comment]
> any update on the fix here?

Maybe it's still being solved

**Comment by koba04** [comment]
This script and the example have been removed in https://github.com/styled-components/styled-components/commit/c16cea5e57009531d0b5f24c9cc0cb731b9d8c36, so this can be closed.

**Comment by Summer-andy** [comment]
ok, thanks ~

**Comment by EvroHQ** [comment]
how did u solve it ? i've the same error

**Comment by Summer-andy** [comment]
https://github.com/styled-components/styled-components/commit/c16cea5e57009531d0b5f24c9cc0cb731b9d8c36
