### ISSUE TITLE
A little more elaborated example

### ISSUE THREAD

**Issue by buunguyen** [styled-components/styled-components#331]
I'm new to this and a bit confused. Let's say I have this component:

```js
() => {
  return (
    <div style='...'>
      <button style='...'>
      <input style='...'>
    </div>
  )
}
```

Now, in order to use styled-components, is it right I have to factor out each child component, style it, then compose? Like:

```js
const sdiv = styled.div``
const sbutton = styled.button``
const sinput = styled.input``

() => {
  return (
    <sdiv>
      <sbutton>
      <sinput>
    </sdiv>
  )
}
```

Is there a better way?

**Comment by JamieDixon** [comment]
Hi @buunguyen, good question and yes you're right, that's the way to do it.

What you get back from something like `styled.div` is a new component that you can use, export etc. One of the great benefits of doing this, and one of the many things I really like about styled-components, is that it gives you an opportunity to convert your usual `div`, `button`, `input` into something more descriptive:

```
const ForgottenPassword = styled.div``
const EmailAddressField = styled.input``;
const SendPasswordButton = styled.button``;
```

```
() => {
  return (
    <ForgottenPassword>
      <EmailAddressField />
      <SendPasswordButton />
    </ForgottenPassword>
  )
}
```

Much more semantic and a lot easier to understand the purpose of the components at a glance.
