### ISSUE TITLE
5.2.0 console error in IE11. RegExp issue

### ISSUE THREAD

**Issue by MichaelKapustey** [styled-components/styled-components#3310]
styled-components.browser.esm.js now contains next code:
`he=/([A-Z])/,pe=new RegExp(he,"g")`
This is not valid regexp syntax in IE11. Steps to reproduce:
0. Open your dist/styled-components.browser.esm.js and make sure it contains the line I'm talking about
1. Open IE11 cosole
2. Paste next line `var he=/([A-Z])/;var pe=new RegExp(he,"g")`
3. Enjoy "Syntax error in regular expression"

This compiled line comes from next file:
https://github.com/styled-components/styled-components/blob/master/packages/styled-components/src/utils/hyphenateStyleName.js
```
const uppercaseCheck = /([A-Z])/;
const uppercasePattern = /([A-Z])/g;
```
But your bundler is doing some weird optimisation that breaks IE11

**Comment by kitten** [comment]
We're aware; there's been another issue and this is already fixed but not released https://github.com/styled-components/styled-components/pull/3267

Please check prior issues before opening new ones please 😅
