### ISSUE TITLE
[Typescript] styled component memoization don't pass it's props type

### ISSUE THREAD

**Issue by beqramo** [styled-components/styled-components#3317]
Hi, I want to create  styled component  like so
```tsx
type TitlePropsType = {
   fontSize:number
}
const H1 = styled.h1<TitlePropsType>`
  font-size:${({fontSize}) => fontSize}px;
`;
```

and I want to memoize it like so:
```tsx
type TitlePropsType = {
   fontSize:number
}
const H1 = React.memo(styled.h1<TitlePropsType>`
  font-size:${({fontSize}) => fontSize}px;
`);
```
and when I use it, it doesn't show me its props that should be passed and shows me this: 
![image](https://user-images.githubusercontent.com/40486471/97280572-e3ea4500-1855-11eb-9c91-c32cf65af69e.png)

without the memo, everything works as expected.
where is the problem can you help me?
thanks

**Comment by kitten** [comment]
Sorry, I'll have to close this.

We don't maintain any TypeScript typings in the main repository and are not updating the ones that live in `definitely-typed`, so we can't offer any help on this here. It's possible that if you browse past issues you'll find similar questions, but overall this repository's issues are not the right place to report these issues or to discuss them.
