### ISSUE TITLE
Self-reference (& + &) bug in 5.2.0 

### ISSUE THREAD

**Issue by adbutterfield** [styled-components/styled-components#3318]
## System:
 - OS: macOS 10.15.7
 - CPU: (8) x64 Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz
 - Memory: 288.05 MB / 8.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 12.19.0 - ~/.nvm/versions/node/v12.19.0/bin/node
 - npm: 6.14.8 - ~/.nvm/versions/node/v12.19.0/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.11.1 => 1.11.1 
 - styled-components: ^5.2.0 => 5.2.0 

## Reproduction
https://codesandbox.io/s/styled-components-base-forked-v70yr?file=/components.js

## Steps to reproduce
Switching from v5.1.1 to v5.2 causes additional white space above the "Inline checkbox" label, due to top margin being applied, which should not. The top margin comes from lines 18-20 of components.js. Strangely enough, the styles from lines 13 and 14 are also applied, so it's not like there is an error in logic and the wrong block of styles is being applied.

## Expected Behavior
There should not be the extra white space caused by top margin being applied.

## Actual Behavior
There is extra white space caused by top margin being applied.

**Comment by garyee** [comment]
Could you maybe be a duplicate of #3265 ?

**Comment by adbutterfield** [comment]
@garyee it looks like probably yes. Sorry for not checking the current open issues more thoroughly.

p.s. this is an awesome library.

**Comment by adbutterfield** [comment]
To follow up on this. I had fixed my version to v5.1.1 because of this issue. I just upgraded to v5.3.0, and it's working correctly.
