### ISSUE TITLE
[Suggestions] Loop/Restart feature

### ISSUE THREAD

**Issue by feRpicoral** [styled-components/styled-components#3322]
I will not be providing any examples since this is pretty straight forward.

I believe there should be an option to set the carousel on loop, i.e. go back to the first page if the user tries to go to the next page from the last page (or it's on autoplay and is currently at the last page).

The same should be true if the user tries to go back from the first page - they should then go to the last page if the loop option is turned on.

**Comment by kitten** [comment]
I suppose this is for a different repo or completely misfiled on this repo?

**Comment by feRpicoral** [comment]
> I suppose this is for a different repo or completely misfiled on this repo?

My bad, had too many repos open at the same time and ended up posting this here and not on slick sliders
