### ISSUE TITLE
React Native typing correction

### ISSUE THREAD

**Issue by mehmetnyarar** [styled-components/styled-components#3324]
The following line is problematic due to [wrong typing](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/51599b9fb62469ad98f59ea3200e95d50d8b54b0/types/styled-components/native.d.ts#L237), given the example in the current [documentation](https://styled-components.com/docs/api#typescript).

```ts
} = styledComponents as styledComponents.ReactNativeThemedStyledComponentsModule<ThemeInterface>;
```
`DefaultTheme` should be replaced with `T`.

```ts
declare const styled: ReactNativeStyledInterface<DefaultTheme>;
```

Temporary solution would be adding **as unknown** before **as styledComponents** .

- "styled-components": "^5.2.1",
- "@types/styled-components": "^5.1.4",

**Comment by kitten** [comment]
Sorry, I'll have to close this.

We don't maintain any TypeScript typings in the main repository and are not updating the ones that live in `definitely-typed`, so we can't offer any help on this here. It's possible that if you browse past issues you'll find similar questions, but overall this repository's issues are not the right place to report these issues or to discuss them.
