### ISSUE TITLE
Couldn't use the same classname across components. CSS is not being scoped inside a style component

### ISSUE THREAD

**Issue by abrehamgezahegn** [styled-components/styled-components#3325]
## System:
 - OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
 - CPU: (8) x64 Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz
 - Memory: 2.49 GB / 11.59 GB
 - Container: Yes
 - Shell: 5.0.17 - /bin/bash
## Binaries:
 - Node: 10.17.0 - ~/.nvm/versions/node/v10.17.0/bin/node
 - Yarn: 1.22.1 - ~/.nvm/versions/node/v10.17.0/bin/yarn
 - npm: 6.11.3 - ~/.nvm/versions/node/v10.17.0/bin/npm
## npmPackages:
 - styled-components: ^5.1.1 => 5.2.0 

The problem I am having seems to defeat the very purpose of CSS in JS. I am using styled-components. And when I tried to use a class name that is being used somewhere up in the react tree inside a styled component. The upper component class name styles somehow get applied to the class name I used down (very) the tree.

## Steps to reproduce

Render `UpperComponent` anywhere in a react project.

```
const StyledContainer = styled.div`
  .title {
    color: red;
    margin-bottom: 32px;
  }
`;

const UpperComponent = () => {
  return (
    <StyledContainer>
      <FirstComponent />
      <h4 className="title"> text inside upper component </h4>
    </StyledContainer>
  );
};


const FirstStyledContainer = styled.div``;

const FirstComponent = () => {
  return (
    <FirstStyledContainer>
      <h4 className="title">text inside first component</h4>
      <SecondComponent />
    </FirstStyledContainer>
  );
};

const SecondComponent = () => {
  return (
    <div>
      <h4 className="title">text inside second component</h4>
      <ThirdComponent />
    </div>
  );
};

const ThirdComponent = () => {
  return (
    <div>
      <h4 className="title">text inside second component </h4>
    </div>
  );
};

```
## Expected Behavior

`title` classname in the `UpperComponent` should not affect it's descendants' elements with the same classname. It should be scoped only to ` <h4 className="title"> text inside upper component </h4>`

## Actual Behavior

`  .title {
    color: red;
    margin-bottom: 32px;
  }` class styles get applied to all the components inside UpperComponent. `title` somehow makes it down to `ThirdCompoent` which is nested inide two components.

Is this expected behavior or am I missing something basic (best practice)?

**Comment by kitten** [comment]
> title classname in the UpperComponent should not affect it's descendants' elements with the same classname. 

That's not possible. Either you'll have to write `${Component}.title` / `&.title`. If you write `.title` it's expanded as `& .title` which means "any `.title` element below this component's instance", which is why you're seeing this behaviour. So it doesn't have anything to do with scoping but with what specific CSS selectors generate in the absence of an explicit `&` reference 😅
