### ISSUE TITLE
Cannot get theme in ReactDOM.render method

### ISSUE THREAD

**Issue by TingzhouJia** [styled-components/styled-components#3326]
## Environment
React > 16.3
styled-components: >5

## Reproduction
```ts
const div = document.createElement('div');
document.body.appendChild(div);

const A=styled.div`
color:${props=>props.theme.colors.primary}
`
ReactDOM.render
            <A>aaaa</A>,
            div,
  );
```
```ts
TypeError: Cannot read property 'primary' of undefined
```
I have wrapper the ThemeProvider in app, but cannot get theme when rendering components

Is there any solution to it?

**Comment by kitten** [comment]
In the above code sample you have _not_ wrapped anything above `A`with a `ThemeProvider`. A provider must always be above the element that uses it but in the same React render root. When you call `render` in any capacity, that's a new tree. In your example `A` is the topmost element.

For questions please go to Stackoverflow as this isn't a great place to answer these kinds of questions ✌️
