### ISSUE TITLE
[React Native] TextInput duplicates characters on android when 'text-transform:capitalize;' is set 

### ISSUE THREAD

**Issue by Vanluren** [styled-components/styled-components#3327]
## Issue
When inputting text in a `<TextInput />` component, where  `text-transform: capitlize;` is added as style - the input repeats the first character, and in some cases the entire string. This only occurs on android.

### System:
 - OS: macOS 10.15.7
 - CPU: (4) x64 Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz
 - Memory: 17.48 MB / 8.00 GB
 - Shell: 5.7.1 - /bin/zsh
### Binaries:
 - Node: 12.18.0 - ~/.nvm/versions/node/v12.18.0/bin/node
 - Yarn: 1.22.5 - ~/.yarn/bin/yarn
 - npm: 6.14.4 - ~/.nvm/versions/node/v12.18.0/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
### npmPackages:
 - styled-components: ^5.2.1 => 5.2.1

## Reproduction

![Reproduction](https://user-images.githubusercontent.com/3931039/98920331-44bd8280-24d0-11eb-9dab-a28564e01155.gif)

```ts
import React from 'react';
import { View } from 'react-native';
import styled from 'styled-components/native';

const CustomInputField = () => {
  return (
    <View>
      <StyledTextInput />
    </View>
  );
};

const StyledTextInput = styled.TextInput`
  height: 60px;
  width: 100px;
  text-transform: capitalize;
`;

export default CustomInputField;
```

## Expected Behavior
The first character in the string is not repeated.

**Comment by kitten** [comment]
I think this seems to me like it may be a `react-native` issue rather. See: https://github.com/facebook/react-native/issues/3294
