### ISSUE TITLE
About require().default dynamic creation of components caused by problems

### ISSUE THREAD

**Issue by bihongbin3027** [styled-components/styled-components#3328]
## Reproduction

https://codesandbox.io/s/style-components-dynamic-forked-y3xmr?file=/src/App.js

## Steps to reproduce

Open the above address.

## Expected Behavior

When I use require().default to create components and use styled-components, a warning appears.

## Actual Behavior

Console display：
The component styled.div with the id of "sc-bdnylx" has been created dynamically.
You may see this warning because you've called styled inside another component.
To resolve this only create new StyledComponents outside of any render method and function component.

**Comment by bihongbin3027** [comment]
![image](https://user-images.githubusercontent.com/15045200/99025860-ca126700-25a4-11eb-9982-252c89108766.png)

**Comment by bihongbin3027** [comment]
In actual development, the page will collapse：

![image](https://user-images.githubusercontent.com/15045200/99025994-0f369900-25a5-11eb-94d8-429de26fbf81.png)

**Comment by kitten** [comment]
This is a limitation. It's not desireable to create a component during the render-time of another and we have a simple check to make sure this doesn't happen. I'd recommend to adopt an async-import like approach here (`import(...)` which is asynchronous) and make sure to delay rendering/importing, even _if_ you have dynamic requires. If you don't need dynamic requires however, it's probably better to avoid them entirely.
