### ISSUE TITLE
TypeScript, react-native, styles

### ISSUE THREAD

**Issue by KidsKilla** [styled-components/styled-components#3331]
## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`

## System:
 - OS: macOS 11.0.1
 - CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
 - Memory: 745.73 MB / 16.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 12.18.4 - ~/.nvm/versions/node/v12.18.4/bin/node
 - Yarn: 1.10.1 - /usr/local/bin/yarn
 - npm: 6.14.6 - ~/.nvm/versions/node/v12.18.4/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^5.1.1 => 5.2.0

styled-components "version": "5.1.4",

## Reproduction

```ts
import React from 'react'
import { View, ViewStyle } from 'react-native'
import styled from 'styled-components/native'

const TestComp = styled.View({})

export const Image: React.FC<{
  style: ViewStyle
}> = ({ style }) => {
  return (
    <View style={style}> {/* OK */}
      <TestComp style={style} /> {/* TS Error */}
    </View>
  )
}
```

## Expected Behavior

Types should match.

## Actual Behavior

```
(JSX attribute) style?: StyleProp<ViewStyle>
No overload matches this call.

  Overload 1 of 2, '(props: Pick<Pick<ViewProps & RefAttributes<View>, "ref" | "style" | "hitSlop" | "onLayout" | "pointerEvents" | "removeClippedSubviews" | "testID" | ... 48 more ... | "key"> & Partial<...>, "ref" | ... 54 more ... | "key"> & { ...; } & { ...; } & { ...; }): ReactElement<...>', gave the following error.
    Type 'ViewStyle' is not assignable to type 'StyleProp<ViewStyle>'.
      Type 'import("./node_modules/@types/react-native/index").ViewStyle' is not assignable to type 'import("./node_modules/@types/styled-components/node_modules/@types/react-native/index").ViewStyle'.
        Types of property 'backgroundColor' are incompatible.
          Type 'string | typeof import("./node_modules/@types/react-native/index").OpaqueColorValue | undefined' is not assignable to type 'string | typeof import("./node_modules/@types/styled-components/node_modules/@types/react-native/index").OpaqueColorValue | undefined'.
            Type 'unique symbol' is not assignable to type 'string | unique symbol | undefined'.

  Overload 2 of 2, '(props: StyledComponentPropsWithAs<typeof View, DefaultTheme, {}, never>): ReactElement<StyledComponentPropsWithAs<typeof View, DefaultTheme, {}, never>, string | ... 1 more ... | (new (props: any) => Component<...>)>', gave the following error.
    Type 'ViewStyle' is not assignable to type 'StyleProp<ViewStyle>'.
      Type 'import("./node_modules/@types/react-native/index").ViewStyle' is not assignable to type 'import("./node_modules/@types/styled-components/node_modules/@types/react-native/index").ViewStyle'.ts(2769)

index.d.ts(2522, 5): The expected type comes from property 'style' which is declared here on type 'IntrinsicAttributes & Pick<Pick<ViewProps & RefAttributes<View>, "ref" | "style" | "hitSlop" | "onLayout" | "pointerEvents" | ... 50 more ... | "key"> & Partial<...>, "ref" | ... 54 more ... | "key"> & { ...; } & { ...; } & { ...; }'

index.d.ts(2522, 5): The expected type comes from property 'style' which is declared here on type 'IntrinsicAttributes & Pick<Pick<ViewProps & RefAttributes<View>, "ref" | "style" | "hitSlop" | "onLayout" | "pointerEvents" | ... 50 more ... | "key"> & Partial<...>, "ref" | ... 54 more ... | "key"> & { ...; } & { ...; } & { ...; }'
```

The origin of the issue is that there is separate `@types/react-native` module in `styled-components`
```
    "dependencies": {
        "@types/hoist-non-react-statics": "*",
        "@types/react": "*",
        "@types/react-native": "*",
        "csstype": "^3.0.2"
    },
```
Should `@types` be in `peerDependencies`?

PS, the issue is only with `yarn`. 
`npm` does not add `node_modules` inside `styled-components`

**Comment by kitten** [comment]
Sorry, I'll have to close this.

We don't maintain any TypeScript typings in the main repository and are not updating the ones that live in `definitely-typed`, so we can't offer any help on this here. It's possible that if you browse past issues you'll find similar questions, but overall this repository's issues are not the right place to report these issues or to discuss them.

**Comment by pt-br** [comment]
@kitten that's just stupid and a lot of people agree with me

**Comment by kitten** [comment]
@pt-br You're welcome to maintain them in repo.
The above actually looks like it's solved by deduplicating the `@types/react-native` package using `yarn-deduplicate` or `npm dedupe` on a second look over the error message.

This essentially brings me to the issue itself, we can even have a rewrite in TS and have perfect typings in a perfect world, but we'd still get issues that are essentially usage questions and we can't answer them all as is either. We simply don't have the bandwidth to do everything we'd love to do.

There are plenty of issues we get that are simply usage issues or questions and I sometimes try to answer as many of them as possible. But even with a TypeScript rewrite being on the horizon and a possibility to being the next major release, we'd still not have the bandwidth to answer questions and address all edge cases in our issues, so we have to decline some of them and set a line somewhere.

Now, on another note, I'd like to ask you to please have a read through the code of conduct and adhere to it going forward ✌️ https://github.com/styled-components/styled-components/blob/main/CODE_OF_CONDUCT.md#our-standards
