### ISSUE TITLE
Could I create a mapping file for classes?

### ISSUE THREAD

**Issue by guidiego** [styled-components/styled-components#3335]
## Question
There is any way to map my final compiled value with the real classname? Example:

```css
.myClass {

}
```
```jsx
<div className={styles['myClass']} />
```

At the end my classname will be a "randomically name", example: `i28esa-sp`. I want to create a .json file with something like:
```json
{
  "myClass": "i28esa-sp"
}
```

**Comment by kitten** [comment]
I'm not really sure what the full question here is, sorry!
