### ISSUE TITLE
Port typings to flow-typed?

### ISSUE THREAD

**Issue by ryyppy** [styled-components/styled-components#334]
As discovered in this [Tweet-Storm](https://twitter.com/lbljeffmo/status/813130316441354244) ... it might be better to opt for `flow-typed` libdefs to prevent further problems with breaking flow versions etc....

@relekang @mxstbr

**Comment by relekang** [comment]
👍 We might want to have the latest version of the libdef for the latest version of flow as index.flow.js as well? Do we still want to type the source code?

**Comment by relekang** [comment]
Same here, when we added it we found a few bugs tho, any thoughts @mxstbr?

**Comment by BLamy** [comment]
Would really like to see this. Styled-components seems to be the only library that is giving me problems with flow.

**Comment by ryyppy** [comment]
@BLamy does this even work?

**Comment by BLamy** [comment]
I was able to get the types to partly work but would almost always have warnings from inside the library. I'm new to flow first project I ever tried moving to it so maybe that's the problem. Ultimately, ended up defining an any module this so the linter would ignore it. 

![image](https://cloud.githubusercontent.com/assets/324928/21720503/8ddd0d98-d3f1-11e6-91a8-1631c85f9aa3.png)

**Comment by ryyppy** [comment]
yeah, it cannot work, because `flow-typed` files are library definition files, which have a special syntax and do not contain any implementation ... we only ship `js.flow` files, which are different :-)

Currently there are a lot of conferences coming up,... maybe in februrary I find time to finally write a flow-typed version for `styled-components` ... unless someone beats me to it.

**Comment by relekang** [comment]
I'll hopefully have time to do it in the next few days.

**Comment by mxstbr** [comment]
Let's do it! Can we somehow check the types in the library and make sure they're consistent with our flow-typed version?

**Comment by avaragado** [comment]
I'm Impatient Zero for that original tweetstorm. I'd certainly appreciate an official flow-typed set of types, as styled-components (1.3.0) is still causing problems for me.

It's frustrating, as a pure consumer of the module, that I need to modify my own .flowconfig file to use styled-components. (Selfishly: I shouldn't have to care how a third-party module arranges itself; and when it rearranges itself, I'll probably see new and confusing errors and have to start caring/swearing all over again :)

Some of these issues might be issues with flow itself rather than styled-components. Maybe flow should take a module's own .flowconfig into account, for example, and/or improve its recommendations for module authors.

FYI with 1.3.0 I see these errors, with my .flowconfig configured according to the current instructions (and with additional lines to work around issues with other third-party modules):

```
node_modules/styled-components/dangerfile.js:3
  3: import { danger, warn, fail, message } from 'danger'
                                                 ^^^^^^^^ danger. Required module not found

node_modules/styled-components/flow-typed/npm/express_v4.x.x.js:5
  5: import type { Server } from 'http';
                   ^^^^^^ Named import from module `http`. This module has no named export called `Server`.

node_modules/styled-components/lib/models/StyledNativeComponent.js.flow:24
 24:   class StyledNativeComponent extends ParentComponent {
                                           ^^^^^^^^^^^^^^^ identifier `ParentComponent`. Expected polymorphic type instead of
 24:   class StyledNativeComponent extends ParentComponent {
                                           ^^^^^^^^^^^^^^^ string

node_modules/styled-components/lib/utils/flatten.js.flow:32
 32:     return ruleSet.concat(isPlainObject(chunk) ? objToCss(chunk) : chunk.toString())
                                                               ^^^^^ number. This type is incompatible with the expected param type of
  7: export const objToCss = (obj: Object, prevKey?: string): string => {
                                   ^^^^^^ object type

node_modules/styled-components/lib/utils/flatten.js.flow:32
 32:     return ruleSet.concat(isPlainObject(chunk) ? objToCss(chunk) : chunk.toString())
                                                               ^^^^^ string. This type is incompatible with the expected param type of
  7: export const objToCss = (obj: Object, prevKey?: string): string => {
                                   ^^^^^^ object type
```

**Comment by Augustin82** [comment]
This is the problem mentioned in #302 (which should be reopened, IMO).

**Comment by relekang** [comment]
@ryyppy Have you had any progress on this? I have been occupied with other stuff lately, but I can help out now if you want me to 🙂

**Comment by ryyppy** [comment]
@relekang currently I am fighting with GraphQL / Apollo / Relay related stuff... I didn't do anything useful yet ^^ ... would be keen to work on a shared Gist or something?

**Comment by relekang** [comment]
Yeah, we can do that 👍

**Comment by mgmcdermott** [comment]
Not sure what the status is here or if this will help, but here's what I've been using:
https://gist.github.com/mgmcdermott/3d858a04a7efc39dbbbf00596bdba8cd

**Comment by relekang** [comment]
@mgmcdermott Cool, do you mind creating a PR against [flow-typed][] with that libdef?

[flow-typed]: https://github.com/flowtype/flow-typed

**Comment by jacobk** [comment]
@mgmcdermott FWIW I just tried the gist and it seems like a great start but ThemeProvider is missing.

**Comment by mgmcdermott** [comment]
Yes, definitely missing a good chunk of the api, but I'm not using ThemeProvider just yet 😄

**Comment by mgmcdermott** [comment]
@ryyppy I'd like to wait until it's a little more polished first.

**Comment by ryyppy** [comment]
@mgmcdermott I was planning to prepare a PR for flow-typed today... I am not sure about your timezone :-) .. maybe let's sync up? I added you on twitter

**Comment by mgmcdermott** [comment]
I'm in NYC (it's 10:30am right now). I'll ping you when I'm free to work on this later today.

**Comment by relekang** [comment]
@ryyppy @mgmcdermott [I started on something here](https://github.com/flowtype/flow-typed/compare/master...relekang:styled-components)

**Comment by keplersj** [comment]
@relekang Love it! That alone would make my Nuclide life much happier. If you just put `any`-stubs for all the other utility functions and PR'd it in I'd be happy to PR patches to further type it later.

**Comment by relekang** [comment]
PR is open at flowtype/flow-typed#745, if anyone knows how to deal with the last error any tips will be appreciated ✌️

**Comment by relekang** [comment]
flowtype/flow-typed#745 was merged 🙂

**Comment by relekang** [comment]
Also, I will create a PR with updated docs later tonight.
