### ISSUE TITLE
v5.2.0 duplicates same classes for & + & on route change

### ISSUE THREAD

**Issue by so99ynoodles** [styled-components/styled-components#3341]
### System:
 - OS: macOS Mojave 10.14.6
 - CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
 - Memory: 101.90 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
### Binaries:
 - Node: 14.4.0 - ~/.nvm/versions/node/v14.4.0/bin/node
 - Yarn: 1.21.1 - /usr/local/bin/yarn
 - npm: 6.14.5 - ~/.nvm/versions/node/v14.4.0/bin/npm

## Reproduction

https://codesandbox.io/s/styled-components-base-forked-rg0xc?file=/index.js

## Steps to reproduce
1. Go to '/' and check the styles of commented `ContentWrapper` at `Home` component
![image](https://user-images.githubusercontent.com/46433895/100864201-074d8300-34d9-11eb-98e0-cd452d949ab4.png)

2. Go to '/about' and return to '/'. Then check again the styles of the same component.
![image](https://user-images.githubusercontent.com/46433895/100864373-411e8980-34d9-11eb-8a93-feb349bc2185.png)

↑ The same classes are duplicated.
A more complex styled-component reproduces more duplicated styles.
↓
![image](https://user-images.githubusercontent.com/46433895/100860352-c141f080-34d3-11eb-908e-9b8ed211e7c0.png)

Sometimes, dynamically duplicated styles override the default behavior, causing broken user interfaces.

## Expected Behavior

explained above.

## Actual Behavior

explained above.

**Comment by kitten** [comment]
This is a combination of two issues. The first being #3265,
the second part (why is it creating too many rules?) is likely related to a page's chunk being instantiate repeatedly if it's dynamically imported, which shouldn't be an issue in production.
