### ISSUE TITLE
Unable to target attribute selector with string containing "&"

### ISSUE THREAD

**Issue by maxnathaniel** [styled-components/styled-components#3343]
## System:
 - OS: macOS 10.15.7
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
 - Memory: 4.22 GB / 32.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 15.3.0 - /usr/local/bin/node
 - Yarn: 1.22.10 - /usr/local/bin/yarn
 - npm: 6.14.9 - /usr/local/bin/npm

## Issue Description

Trying to target `div` with `data-attribute` passed as a prop that contains special characters such as `&`. Had tried to escape `&` with backslash `\`, but did not seem to work. However, it seems to work with other special characters such as `%` or `$`.

## Reproduction

Component
```
<InputWrapper data-size="large&fullwidth">
   <input type="text" onChange={handleChange} />
<InputWrapper />
```
Styled Component without backslash
```
const InputWrapper = styled.div`
  position: relative;

  &[data-size='large&fullwidth'] {
    height: 20px;
  }
`
```

OR 

Styled Component with backslash
```
const Input = styled.div`
  position: relative;

  &[data-size='large\&fullwidth'] {
    height: 20px;
  }
`
```
## Expected Behavior

Should be able to target the `div` with `data-size='large&fullwidth` and set height of `20px`.

## Actual Behavior

Unable to set height.

## Codepen

https://codesandbox.io/s/styled-components-playground-forked-23lws?file=/src/index.js

**Comment by maxnatho** [comment]
## Update

Replacing `&` with other special characters like `$` or `%` seems to work as expected.

**Comment by kitten** [comment]
I believe this is an issue in Stylis 3. I'm not sure whether it'll still be an issue in Stylis 4, but it may be worth checking. It seems that `&` inside the data attribute string is swapped out for the component's ID, as if the `&` was part of a selector. There's not really anything that we can do against that though

**Comment by myteax** [comment]
I have been able to solve this for you 
check -https://codesandbox.io/s/styled-components-playground-forked-rq5r5

**Comment by myteax** [comment]
I have been able to solve this for you
check -https://codesandbox.io/s/styled-components-playground-forked-rq5r5

**Comment by kitten** [comment]
This is likely an issue with how `stylis` perceives your input there. Generally, you can try to base64 encode with `url('...')` values for instance, but otherwise there isn't much we can do to resolve this. I believe the upgrade to `stylis@4` may fix this though once it's dropped into styled-components.

For now, I'll go ahead and close this, since there's not much we can do to fix this on our end. But rest assured, you're not doing anything wrong, it's likely stylis that in v3 can't parse this.
