### ISSUE TITLE
How styled-components interact with inline styles created by dangerouslySetInnerHTML?

### ISSUE THREAD

**Issue by samandera** [styled-components/styled-components#3347]
It's a question, but not the usage one, rather the "how does it work" type. It might be a bug report.
I pass a html with inline styles string to `dangerouslySetInnerHTML` inside the jsx element. Later on that component is used as a descendant of a several styled components and the inline styles vanish. Does in any point during creating a styled component, inline styles may be overwritten? How can I keep these styles?

**Comment by kitten** [comment]
Yea, this is more of a question, so may be better for Stackoverflow / Spectrum in the future. But I recognise that you weren't sure whether it was related to styled-components, so no worries :+1:

Basically, `styled-components` has nothing to do with this. If you have children / parents that are rendered then a `StyledComponent` like usual in React's paradigms doesn't control or know anything about them. So it's not possible for this problem to be directly related to our components.

I don't obviously know why you're doing this and injecting CSS this way, but I'd start at looking whether the element actually has the styles you expect it to have (I assume it's just a `style` tag with `dangerouslySetInnerHTML`?) and then check if the rules are there whether you've introduced some specificity issues.
