### ISSUE TITLE
hover width property applies for all Components

### ISSUE THREAD

**Issue by sanjipun** [styled-components/styled-components#3351]
I might be just dumb but when I hover on ICON, scaling applies individually but width applies for all ICON components.
Link to [Sandbox](https://codesandbox.io/s/nostalgic-merkle-8d0yy?file=/src/App.js)

**Comment by sorosora** [comment]
Because you are using flex layout, [align-items](https://developer.mozilla.org/en-US/docs/Web/CSS/align-items) is defaulted to normal, if you use `align-items: flex-start`, you should be able to achieve the desired effect. This has nothing to do with styled-components.

**Comment by sanjipun** [comment]
> Because you are using flex layout, [align-items](https://developer.mozilla.org/en-US/docs/Web/CSS/align-items) is defaulted to normal, if you use `align-items: flex-start`, you should be able to achieve the desired effect. This has nothing to do with styled-components.
Well, that solves it! thank you
