### ISSUE TITLE
Wrapped styled-components don't update on Fast Refresh of imported modules

### ISSUE THREAD

**Issue by jrmyio** [styled-components/styled-components#3355]
When changing a wrapped styled component from another module, react-refresh does not seem to update their children. You require an F5, or changing the children directly in order to see their updated styles.

This is a copy of https://github.com/vercel/next.js/issues/16326 .

Let me know if this is not on styled-components but on react-refresh so i can make an issue there.

## Environment
Styled-components@5.2.1

## Reproduction
https://codesandbox.io/s/wrapped-styled-component-doesnt-fast-refresh-0zmvk?file=/src/App.tsx

## Steps to reproduce
Change the border width or color in the BaseButton.

## Expected Behavior
The children should update their styles.

## Actual Behavior
The children do not update their styles, only if they get modified themselves directly.

**Comment by kitten** [comment]
There's likely not much we can do on our end, so closing in favour of the linked issue: https://github.com/vercel/next.js/issues/16326
