### ISSUE TITLE
Inference HTML attributes by 'forwardedAs' prop

### ISSUE THREAD

**Issue by socker210** [styled-components/styled-components#3359]
## Environment
System:
 - OS: macOS 10.15.7
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
 - Memory: 143.16 MB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh

Binaries:
 - Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
 - Yarn: 2.3.3 - /usr/local/bin/yarn
 - npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm

npmPackages:
 - styled-components: ^5.2.1 => 5.2.1 

## Reproduction
https://codesandbox.io/s/goofy-lake-60y4s?file=/src/App.tsx

## Expected Behavior
Work 'forwardedAs' like 'as' prop. (Inference HTML attributes by forwardedAs prop.)

## Actual Behavior
Occurred typescript error.

## P.S
Sorry for my bad English.

**Comment by socker210** [comment]
I close this issue

**Comment by aaavakian** [comment]
Hey @socker210!
What was the solution? I can't fully understand proper typing with `forwardedAs`. I have something like this:

```tsx
const A = styled(B).attrs({ forwardedAs: 'input' })`
  /* Some CSS */
`;

// ...

// I get an error in TSX that property `value` doesn't exist:
return <A value={value} onChange={(e) => handleChange(e.target.value)} />
```

How did you solve your issue?
