### ISSUE TITLE
Autocomplete displays function options instead of react-native components

### ISSUE THREAD

**Issue by FelipeBohnertPaetzold** [styled-components/styled-components#3360]
## System:
 - OS: Linux 5.4 Ubuntu 20.04.1 LTS (Focal Fossa)
 - CPU: (4) x64 Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
 - Memory: 2.52 GB / 15.51 GB
 - Container: Yes
 - Shell: 5.8 - /usr/bin/zsh
## Binaries:
 - Node: 12.20.0 - /usr/local/bin/node
 - Yarn: 1.22.4 - /usr/local/bin/yarn
 - npm: 6.14.8 - ~/projetos/paliari/petis/mobile/clinic/node_modules/.bin/npm
## npmPackages:
 - styled-components: ^5.1.1 => 5.2.1

## Steps to reproduce
When importing `styled-components/native`, the autocomplete options suggest that the imported module is a function

## Expected Behavior
It should show the react-native components (View, TextInput, ...)

## Actual Behavior
Displays options for a function (apply, arguments, bind, ...)
![styled-import](https://user-images.githubusercontent.com/15256199/102886504-fa66e400-4433-11eb-966a-9637ed777091.png)

**Comment by kitten** [comment]
Does this happen with the new typings? https://styled-components.com/docs/faqs#missing-declarations-for-styledcomponentsnative

Either way, the bindings are not maintained in this repo. Please open an issue on definitely-typed :)
