### ISSUE TITLE
Global don't pass props to dom.

### ISSUE THREAD

**Issue by The-Code-Monkey** [styled-components/styled-components#3375]
What will it allow you to do that you can't do today?

It will allow us to set a list of props that we never want pushing onto the dom, rather than doing `transient` or `shouldForwardProps`. 

How will it make current work-arounds straightforward?

It will remove a load of extra coding on the users side meaning less chance for errors.

What potential bugs and edge cases does it help to avoid?

It will help avoid unwanted dom properties without a load of extra boilerplate per component.

**Comment by kitten** [comment]
I'm not really sure what this is about. Sorry!
