### ISSUE TITLE
Old way of overriding styles quit working

### ISSUE THREAD

**Issue by Yamaha32088** [styled-components/styled-components#3377]
We are using version 4.4.1 of styled-components and would like to upgrade to the latest. However we noticed several of our styles are broken after an upgrade. It appears precedence of styles changed between versions.

Here is a code sandbox of what is happening currently on the new version where we try to override the button style background-color to be red rather than blue.
https://codesandbox.io/s/late-dew-yt3o2?file=/src/App.js

Here is version 4.4.1 working as we expect.
https://codesandbox.io/s/agitated-rgb-m9ih5?file=/src/App.js

What is the proper way of overriding styles with the newer version?

**Comment by Yamaha32088** [comment]
I should note that I know about the `&&` but if we had to do that for every styled component we would be changing hundreds of files and ideally we would avoid having to do something like that.

**Comment by RowanDZ** [comment]
Both codesandboxes have the same result??

**Comment by Yamaha32088** [comment]
Not sure why it is acting up like that. I tried to make a new one and got the same result. The only way I can make the code sandbox work as I described is to change something in the App.js file. For example if you change the color from red to green and save it will appear blue.

**Comment by powerOFMAX** [comment]
That's quite interesting. A workaround could be to use `!important`

**Comment by kitten** [comment]
If you import a CSS/SCSS file and the likes there's not really any way to control where they're inserted and hence what precedence their rules will take. The same goes for styled-components, if it's just used then there's no way to determine its precedence.

In general, with styled-components you can insert a placeholder element to determine where its style tag goes in the DOM, but apart from that you'll also have to ensure that your dynamic CSS chunks have a consistent place to go to.

See: https://github.com/styled-components/styled-components/issues/3532#issuecomment-895232472
