### ISSUE TITLE
Support SVG symbols?

### ISSUE THREAD

**Issue by wmertens** [styled-components/styled-components#338]
I just realized that SVG symbols and inlined CSS are two very similar problems with very similar solutions. I wonder if styled-components can be made to handle SVG symbol management as well.

[SVG symbols are very useful](https://css-tricks.com/svg-symbol-good-choice-icons/), they give you scalable icons that can be styled/colored with CSS, with low bandwidth use. To use them, there needs to be a symbol definition somewhere in the page, and then where you want to use it you put a `<svg><use xlinkHref={iconId}/></svg>`. The `svg` can be styled with CSS to change colors etc.

So how about something like

```js
import ArrowSvg from '../icons/arrow.svg'

export const Arrow = styled.svgSymbol(ArrowSvg)`
  ${p => p.left && "transform: rotate(180deg);"}
  &:hover { fill: "yellow"; }
`
```
and later
```js
<p><Arrow/> Styled-components is awesome! <Arrow left/></p>
```
which becomes this DOM:
```html
<head><style>.a {...}.b{...}</style></head>
<body>
  <svg><symbol id="s">...</symbol></svg>
  <p>
    <svg class="a"><use xlink:href="#s"/></svg>
     Styled-components is awesome! 
    <svg class="b"><use xlink:href="#s"/></svg>
  </p>
</body>
```

So behind the scenes, styled-components would maintain the `<svg/>` block with the symbol definitions and come up with a global `iconId` for the `<use/>`.
The `ArrowSvg` content could be from loading with https://github.com/jhamlet/svg-react-loader or something similar.

**Comment by geelen** [comment]
This is cool, but shouldn't this be possible as a stand-alone library? We could add some hooks into the core Styled Components code if we need to, but I don't think we'd need to:

```js
import ArrowSvg from '../icons/arrow.svg'
import styledSymbols from 'styled-symbols'

const Arrow = styledSymbols(ArrowSvg)`
  /* ... */
`
```

`toSymbol` would be implemented something like:

```js
import styled from 'styled-components'

const numInjections = 0
const toSymbol = svg => {
  const symbolId = `styled-symbol-${numInjections++}`

  class SymbolComponent extends React.Component {
    componentWillMount() {
      this.elem = document.body.insertAdjacentHTML('afterbegin', `
        <svg style="display: none;"><symbol id="${symbolId}">${svg}</symbol></svg>
      `)
    }

    componentWillUnmount() {
      this.elem.remove()
    }

    render() {
      const { className } = this.props
      return <svg className={className}><use xlink:href={`#${symbolId}`}/></svg>
    }
  }

  return styled(SymbolComponent)
}
```

It might not be quite that simple but that's my first thought. Certainly worth experimenting with!

**Comment by nelix** [comment]
I have a little example of an svg symbol cache I made on top of react http://codepen.io/nelix/pen/PPvWOb

I figure you can just apply styled to the use components it returns?
If interested I can make the above into a library

**Comment by wmertens** [comment]
@nelix I forked your example to be more like what I have in mind, the symbols are rendered separately. http://codepen.io/wmertens/pen/mRPMOO?editors=0010

Also, I would just cache entire svg drawings using a single id, they would not have props, but I left that part as-is.

**Comment by vdanchenkov** [comment]
Given I do not use SSR, are there any benefits of using symbols compared to inline SVG?

**Comment by wmertens** [comment]
@geelen your example is nice and simple, but there should only be one symbol insertion per svg icon, and the mounted symbols should be tracked for SSR.

So this would require consistent naming without clashes and a registry component; for SSR, it needs  to generate a string much like the css generated by styled-components.

**Comment by wmertens** [comment]
@vdanchenkov if you have a bunch of the same icons in the page, I suppose that the browser will take less memory if they all refer to a few symbols vs when they are all copies of the same svg.

**Comment by jaydenseric** [comment]
Why does this need special treatment? SVG symbols work fine:

```jsx
import React from 'react'
import styled from 'styled-components'
import icons from './icons.svg'

const Icon = styled.svg`
  fill: currentColor;
`

export default () => (
  <Icon>
    <use xlinkHref={icons + '#heart'} />
  </Icon>
)
```

For old browsers make sure your app loads [the polyfill](https://github.com/Keyamoon/svgxuse).

**Comment by wmertens** [comment]
@jaydenseric the problem is not the fact that `use` works, but the management of the symbols in the page without bundling all your icons in one big svg. In fact, that polyfill is only needed for references to external SVG…

**Comment by oyeanuj** [comment]
@wmertens Given that this was almost an year ago, I'm curious how are you dealing with this today?

**Comment by wmertens** [comment]
@oyeanuj, we're using svg-sprite-loader (I think, on phone). However, we're using v0.3 because the current v3 makes assumptions about webpack that clash with our setup.

Basically, it's currently w

**Comment by wmertens** [comment]
@oyeanuj, we're using svg-sprite-loader (I think, on phone). However, we're using v0.3 because the current v3 makes assumptions about webpack that clash with our setup.

Basically, it's currently w

**Comment by jaydenseric** [comment]
These days IMO best way to handle SVG/icons is with react components:

```jsx
const Icon = ({ size = '1em', color = 'currentColor', title, children }) => (
  <svg width={size} height={size} viewBox="0 0 32 32">
    <title>{title}</title>
    {children}
    <style jsx>{`
      svg {
        vertical-align: middle;
        fill: ${color};
      }
    `}</style>
  </svg>
)

export const MenuIcon = props => (
  <Icon title="Menu icon" {...props}>
    <path d="" />
  </Icon>
)

export const UserIcon = props => (
  <Icon title="User icon" {...props}>
    <path d="" />
  </Icon>
)
```

This way tree-shaking, code-splitting, etc. can ensure only the icons that are being used on a given view are downloaded.

You can then use props to configure any details of the icon (such as colors) on the fly.

Unlike with `<use>`, icons load instantly with the rest of the view from SSR.

`<use>` blinks terribly when anything causes your parent component to re-render, for example global header logos/icons when transitioning routes.

Your JSX linting can cover the SVGs.

Lots of benefits.

**Comment by wmertens** [comment]
Huh, why does <use> blink? Do you have an example online somewhere?

**Comment by wmertens** [comment]
Also note that if using full svg as react components,  with SSR you might
be shipping 50 copies of an SVG used for a bullet, for example. With <use>,
only one.

**Comment by jaydenseric** [comment]
> Huh, why does <use> blink?

Even when the SVG file is cached, anytime the surrounding DOM is manipulated/rerendered, the browser throws away the image and renders it all over again. This looks like a blink where for a few milliseconds the image collapses/becomes invisible, then displays again. If you use Next.js, and have a logo in a global header component in your page components, when routing between pages the browser re-render the logo with a blink every transition.

Even if browsers optimized this behavior, SVG components will always look better when first loading a SSR page. They don't load with a blink after the page displays like with `<use>`.

I don't have a blinking demo handy sorry, because I refactored `<use>` to SVG components accross our site a few months ago.

> if using full svg as react components,  with SSR you might
be shipping 50 copies of an SVG used for a bullet

True, but gzip handles repetition really well making it a non-issue.

1 "bullet":

<img width="628" alt="screen shot 2017-11-17 at 10 19 58 am" src="https://user-images.githubusercontent.com/1754873/32921597-62e9d574-cb82-11e7-9349-1fa08a81e28d.png">

30 "bullets":

<img width="633" alt="screen shot 2017-11-17 at 10 19 37 am" src="https://user-images.githubusercontent.com/1754873/32921601-65b99d3e-cb82-11e7-9b72-3a4d6c19855b.png">

If you are using `<use>` the traditional way, with a large-ish static `icons.svg` file pulled in globally only to use a few icons on the two pages a visitor views, there is more sent down the wire than if you just repeated a few inline SVGs (which often don't repeat anyway).

At the end of the day, there are things you can do with SVG components you simply can't with `<use>`, like dynamic content, animations and styles.

**Comment by Bilb** [comment]
Hey, sorry if this is not the correct place to ask, but 
I am printing svgs like this:
```
const Svg = styled.svg<StyledSvgProps>`
  width: ${props => props.width};
  height: ${props => props.height};
  preserveAspectRatio: xMinYMin
`;
```

but no matter how I try to use the preserveAspectRatio, it never gets applied. Any idea?
Thanks
