### ISSUE TITLE
Types not passed to component with Typescript + React Native

### ISSUE THREAD

**Issue by gwendall** [styled-components/styled-components#3380]
When typing a styled-component, the types don't get picked. 

In the following example, the `width` var in the callback returns a `Binding element 'width' implicitly has an 'any' type` error:

```
type Props = { width: number; };

const StyledView = styled.View<Props>`
  width: ${({ width }) => width}px;
`;
```

I already have `@types/styled-components-react-native` installed.

Any fix ?

**Comment by hanselabreu** [comment]
Wouldn't `width` be inside the `theme` object? `width: ${({ theme }) => theme.width}px;`

**Comment by gabrielpetersson** [comment]
Having the same issue

**Comment by kitten** [comment]
Sorry, I'll have to close this.

We don't maintain any TypeScript typings in the main repository and are not updating the ones that live in `definitely-typed`, so we can't offer any help on this here. It's possible that if you browse past issues you'll find similar questions, but overall this repository's issues are not the right place to report these issues or to discuss them.
