### ISSUE TITLE
styled-components/native style prop breaks if it's allowed function type

### ISSUE THREAD

**Issue by tkow** [styled-components/styled-components#3384]
Pressable of react-native strictly doesn't have compatibility with styled(Pressable). If styled(Pressable) used directly, dynamic style function can't be used. See examples as follows. Maybe though Pressable don't be registered still .d.ts file, 
styled.Pressable same as see [it](https://github.com/styled-components/styled-components/blob/72a6f642c3dedbcee91a2b5d76f96b93f345b86f/packages/styled-components/src/native/index.js
).

## Environment

```
"styled-components": "^5.2.1"
```

## Reproduction

```tsx
import React, { useMemo } from 'react'
import styled from 'styled-components/native'
import {
  Pressable as RNPressable,
  PressableProps as RNPressableProps,
  Text
} from 'react-native'

type MergePressableStylesFn = (
  style?: RNPressableProps['style'],
) => RNPressableProps['style']

const mergePressableStyles: MergePressableStylesFn = (style) => {
  if (typeof style === 'function') return style
  if (Array.isArray(style)) {
    return (state) => {
      return style.map((sty: any) => {
        return typeof sty === 'function' ? sty(state) : sty
      })
    }
  }
  return style
}

export const Pressable: React.FC<RNPressableProps> = ({
  style,
  ...props
}: RNPressableProps) => {
  const _style = useMemo(() => mergePressableStyles(style), [style])
  return <RNPressable style={_style} {...props} />
}

export const Button = styled(Pressable)<RNPressableProps>`
  display: flex;
  flex-direction: row;
  justify-content: center;
  align-items: center;
`


export const WrongButton = styled(RNPressable)<RNPressableProps>`
  display: flex;
  flex-direction: row;
  justify-content: center;
  align-items: center;
`

<Button
      style={(state) => {
        return {
          opacity: state.pressed ? 0.4 : 1,
        }
      }}
      accessibilityRole="button"
      {...rest}
 >
    <Text> ok </Text>
</Button>

<WrongButton
      style={(state) => {
        return {
          opacity: state.pressed ? 0.4 : 1,
        }
      }}
      accessibilityRole="button"
      {...rest}
 >
    <Text> Bad </Text>
</WrongButton>
```
WrongButton doesn't response against opacity prop. If styled-components support components like Pressable, special patch needs [here](https://github.com/styled-components/styled-components/blob/72a6f642c3dedbcee91a2b5d76f96b93f345b86f/packages/styled-components/src/native/index.js) as I wrote https://github.com/styled-components/styled-components/issues/3228.

**Comment by stay7** [comment]
Try to upgrade `@types/styled-components-react-native` latest version.
I added `Pressable` component type few days ago. Finally It's merged today

**Comment by tkow** [comment]
@stay7 Thank you for reply. I confirmed styled.Pressable inferred, but function style prop doesn't work as I expected.
I reproduce it in [repo](https://github.com/tkow/ReactNativeWebPlayGround), try 
```
yarn install 
yarn storybook
```
then, I may try to fix it and pr.

**Comment by tkow** [comment]
https://github.com/styled-components/styled-components/pull/3388
https://github.com/styled-components/styled-components/pull/3389

Is there anyone can review them?
Sorry to hurry for this, but this is clearly bug, and I'm grad to fix them asap although we can patch.
