### ISSUE TITLE
[typescript] react union types props is broken by @types/styled-components ?

### ISSUE THREAD

**Issue by ka2jun8** [styled-components/styled-components#3385]
## Environment

- macOS Big Sur 11.1
- node v14.3.0
- npm: 6.14.11

## Reproduction

Example:
https://codesandbox.io/s/dazzling-sun-2drq9

## Steps to reproduce

1. create typescript styled-components project ( install @types/styled-components etc. )
2. define a union object type, like this.

```
type Props = {
  type: "a";
  hoge: number;
} | {
  type: "b";
  hoge: string;
};
```

3. create react component using `Props`, like this.

```
const Component: React.FC<Props> = () => <div />
```

4. wrap it in styled-components, like this.

```
const StyledComponent = styled(Component)``;
```

5. use component, like this.

```
    <StyledComponent type="a" hoge={1} />     // <- OK: type is correct 
    <StyledComponent type="a" hoge="str" /> // <- NG: should types error
```

## Expected Behavior

The component props type should be inferred, and report type error, same as normal react component.

```
    <Component type="a" hoge="string" />
    ...
    Type '{ type: "a"; hoge: string; }' is not assignable to type '(IntrinsicAttributes & { type: "a"; hoge: number; } & { children?: ReactNode; }) | (IntrinsicAttributes & { type: "b"; hoge: string; } & { ...; })'.
  Types of property 'hoge' are incompatible.
    Type 'string' is not assignable to type 'number'.

```

## Actual Behavior

It does not occur types error.

## Why it is happened

I think it is occurred by using `Omit` in `StyledComponentProps`.

- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/styled-components/index.d.ts#L73-L82
- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/styled-components/index.d.ts#L308-L310

Typescript `Omit` make union type changed other type.

```
type AorB = {
  type: "a";
  hoge: number;
} | {
  type: "b";
  hoge: string;
};

type A = Omit<AorB, never>
const a: A = {type: "a", hoge: "str"}; // not error: 
```

Type `A` is inferred following type by typescript.

```
type A = {
    type: "a" | "b";
    hoge: React.ReactText;
}
```

So `hoge` is allowed number and string regardless of `type: "a"`.

## Suggestion

- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/styled-components/index.d.ts#L73-L82

If type `A` is `never`, can it avoid `Omit` ?

```
type IsExtendsNever<T> = T extends never ? true : false;

export type StyledComponentProps<
    // The Component from whose props are derived
    C extends string | React.ComponentType<any>,
    // The Theme from the current context
    T extends object,
    // The other props added by the template
    O extends object,
    // The props that are made optional by .attrs
    A extends keyof any
> =
    // Distribute O if O is a union type
    O extends object
        ? WithOptionalTheme<
            false extends IsExtendsNever<A> ?    //  <- If A is not never then use Omit
              Omit<
                  ReactDefaultizedProps<
```

- https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/styled-components/index.d.ts#L308-L310

`WithOptionalTheme` does not use Omit.

```
type WithOptionalTheme<P extends { theme?: T }, T> = P & { theme?: T };
```

**Comment by henrikra** [comment]
@ka2jun8 Great research! This is very annoying bug imo!

Can you make PR about your suggestion so we get this problem solved?

**Comment by ka2jun8** [comment]
@henrikra 

Thank you.
I send the PR:
Please review it.

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51252

**Comment by kitten** [comment]
I'll just post my usual TypeScript snippet here for reference:

> We don't maintain any TypeScript typings in the main repository and are not updating the ones that live in `definitely-typed`, so we can't offer any help on this here. It's possible that if you browse past issues you'll find similar questions, but overall this repository's issues are not the right place to report these issues or to discuss them.

@ka2jun8 In general, I see that the above has been merged and closed. Please don't forget to close issues here as well, especially if it doesn't end up relating to the main repo. 🙏 Cheers!
