### ISSUE TITLE
Enhace: Add margin: 0 auto; class to TW

### ISSUE THREAD

**Issue by carlosmori** [styled-components/styled-components#3390]
Hey guys, an amazing library, congrats.

Do you think margin: 0 auto; can be added as a class m-0-auto . 

If you think is a good idea and like it I would like to send a PR it would be my first contribution!

Thanks!

**Comment by kitten** [comment]
Incorrect repo, I suppose? 😅

**Comment by carlosmori** [comment]
OMG sorry @kitten  😅
