### ISSUE TITLE
Nested global styles crashing the app in styled-components 5.2.x

### ISSUE THREAD

**Issue by wojtekmaj** [styled-components/styled-components#3391]
Nesting global styles crashes the app in styled-components 5.2.x and 5.3.x. To be precise, 5.2.0-test.6 seems to be the last version unaffected. 5.2.0-test.7 crashes already.

## Reproduction

https://codesandbox.io/s/styled-components-nested-global-styles-bug-w9yl3

Note that downgrading to 5.1.1 fixes the issue without any further changes to the repo.

## Steps to reproduce

1. 
```js
import { createGlobalStyle } from 'styled-components';

const a = createGlobalStyle``;

export default createGlobalStyle`
  ${a};

  body {
    color: blue;
  }
`;
```

2. 💥 

## Expected Behavior

Styles from 1st and 2nd createGlobalStyle nicely merged and applied

## Actual Behavior

```
Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

**Comment by kitten** [comment]
You cannot interpolate a global styles _component_ into another's rule set. The error occurs because the interpolation is being executed as if it was a function. So, in other words, you can only interpolate `css` tagged template literals into `createGlobalStyle`.

**Comment by luizwhite** [comment]
Then how we extend a global style?

**Comment by tibotiber** [comment]
A bit late but it'll serve the next person. You should replace `createGlobalStyle` by `css` (also imported from styled-components) when defining the nested style, the outside style should continue to use `createGlobalStyle `.
