### ISSUE TITLE
Passing props to Styled Component doesn't work in v5.2.1

### ISSUE THREAD

**Issue by ezeikel** [styled-components/styled-components#3392]
```
  border: ${({ active }) => (active ? "1px solid red" : "")};
```

This didn't work in 5.2.1 and `active` always seemed to be `true` even if I set `active={false}` on the component. Downgrading back to 5.1.1 fixed the issue.

**Comment by haneenmahd** [comment]
Can you give me a link on codesandbox.So that i could check the code...

**Comment by stevenocchipinti** [comment]
Just had a similar issue except we found that there were conflicting styles generated with the same classname.

It seems like it could be the same underlying issue as #3376.
There is [a reproduction in that issue](https://codesandbox.io/s/javascript-forked-0sjtn?file=/index.js) that produces similar results.

**Comment by kitten** [comment]
If you have a codesandbox, then we could take a look, however if this is a usage question, I'd suggest Stackoverflow for these kinds of issues. Without a full issue filled out there's not much we can say about this.
