### ISSUE TITLE
react@next changed behavior of invalid hook call message

### ISSUE THREAD

**Issue by eps1lon** [styled-components/styled-components#3394]
## Environment

Codesandbox with 
styled-components: 5.2.1
react: 0.0.0-dc27b5aaa (current `react@next`)

## Reproduction

https://codesandbox.io/s/invalid-hook-call-consoleerror-o0cvq?file=/src/index.js

## Steps to reproduce

Create a styled-component

## Expected Behavior

No console.error call

## Actual Behavior

`console.error` logs:

```
Warning: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)

2. You might be breaking the Rules of Hooks

3. You might have more than one copy of React in the same app

See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.
```

## Context

React recently switched from throwing an error with this message to logging it with `console.error`: https://github.com/facebook/react/pull/20604

**Comment by tema1411** [comment]
I have it problem too with:
 "react": "^17.0.1", 
 "styled-components": "^5.2.1",
