### ISSUE TITLE
`__webpack_nonce__` is not picked up in CRA builds

### ISSUE THREAD

**Issue by torgeirsk** [styled-components/styled-components#3414]
## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`

## System:
 - OS: macOS 10.15.7
 - CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
 - Memory: 1.46 GB / 16.00 GB
 - Shell: 5.8 - /usr/local/bin/zsh
## Binaries:
 - Node: 15.10.0 - ~/.nvm/versions/node/v15.10.0/bin/node
 - Yarn: 1.22.10 - ~/.nvm/versions/node/v15.10.0/bin/yarn
 - npm: 7.5.3 - ~/.nvm/versions/node/v15.10.0/bin/npm
## npmPackages:
 - styled-components: ^5.2.1 => 5.2.1

## Reproduction

https://codesandbox.io/s/styled-components-base-gc367

## Steps to reproduce
1. create an empty cra and add styled-components
2. set `window.__webpack_nonce__ = "secret" ` anywhere
3. yarn start or yarn build

## Expected Behavior
`<style>` tags should have a `nonce` attribute

## Actual Behavior 
`<style>` tags dont have a `nonce` attribute

Confirmed that replacing `__webpack_nonce__` with `window.__webpack_nonce__` fixes the problem. I can submit a PR if desired.

**Comment by kitten** [comment]
Potentially resolved given the PR? 

Please don't forget to be a good netizen on GitHub and revisit issues, especially ones that have been resolved and need to be closed, or ones that have received replies ❤️
