### ISSUE TITLE
How to handle updating of versions in webpackbin examples

### ISSUE THREAD

**Issue by relekang** [styled-components/styled-components#342]
The versions in the linked examples of webpackbin is currently configured with version 0.2.2, 0.4.2 and 1.0.0 for different examples. 
How do we want to deal with this? I guess they should be fairly up to date because it is likely to be the base of examples in bug reports etc.
Should we update them when we remember to or can we somehow configure them to use latest?

Should I provide a PR with updated links to examples with 1.2.1?

**Comment by mxstbr** [comment]
Yes please @relekang, the problem is that you have to completely recreate the webpackbin to update the version – if you just update the version it doesn't save that change. (that's a bug in webpackbin)

Would love to have up-to-date demos!

**Comment by relekang** [comment]
Seems like the bug is fixed, got a new url when i updated the version number and clicked save :v:
