### ISSUE TITLE
Feature request - add yarn 2 support 

### ISSUE THREAD

**Issue by wdfinch** [styled-components/styled-components#3435]
When trying to use yarn 2 with styled-components, I get the following error:

Module not found: styled-components tried to access react-is (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.

I believe this is because yarn 2 has stricter requirements regarding referencing dependencies not present in package.json. The current workaround is to manually adjust the dependencies using the packageExtensions features in .yarnrc.yml.

**Comment by joealden** [comment]
@wdfinch do you have `react-is` installed? `styled-components@5.x.x` requires it as a peer dep.

**Comment by kitten** [comment]
Just adding on here as said above that the error is saying that styled-components **ancesotr**, meaning either your package or any package, may use it without installing / depending on react-is, or also defining it as a peer. Hence, this will work if you start depending on react-is, especially if you're working on an app repo. If you're working on a library repo and you need to handle peer dependencies, then add a peer dependency on a package yourself and install it as a dev dependency.

**Comment by wdfinch** [comment]
Yes, I do have a workaround. I was just wondering if there was a way to not have this occur on install as it doesn't appear to happen in other package managers. Why would `styled-components` not include `styled-is` as a dependency?

It might be helpful to add something in the docs about this as other users using yarn 2 will face this issue by default.
