### ISSUE TITLE
defaultProps theme is overriding ThemeProvider theme

### ISSUE THREAD

**Issue by diegohaz** [styled-components/styled-components#344]
## Version
1.2.1

## Reproduction
http://www.webpackbin.com/EyaDeRzHG

## Expected Behavior

Text color to be green, which is the color defined in `ThemeProvider`

## Actual Behavior

Text color is red, which is the color defined in `Text.defaultProps`

If I remove `defaultProps`, text color becomes green.

**Comment by diegohaz** [comment]
This bug was introduced in v1.1.3 (v1.1.2 works).

Maybe related to #295 

cc/ @k15a

**Comment by k15a** [comment]
Hey,

why do you consider this a bug? In my opinion this is the correct behavior.

**Comment by diegohaz** [comment]
Hi, @k15a 

If I understand well, according to [Theming/defaults](https://github.com/styled-components/styled-components#defaults), `theme` in `defaultProps` should be used only if there is no `ThemeProvider`. Currently, that button example is broken.

Also, it doesn't make sense `defaultProps` taking precedence in this case. Consider you are writing a components library with `styled-components`. You should be able to set a default theme for the component, but you will want the user to be able to override that with `ThemeProvider`.

**Comment by k15a** [comment]
That makes sense to me.

**Comment by diegohaz** [comment]
How would you handle this?
> You should be able to set a default theme for the component, but you will want the user to be able to override that with ThemeProvider.

**Comment by k15a** [comment]
I would change the current behavior to your suggested behavior or you can also do:

```JS
const ShareButton = styled.button`
  color: ${({ theme }) => theme.color || 'red'};
`
```

**Comment by diegohaz** [comment]
That is not a good solution when you have a theme like this:
```js
{
    fonts: {
      primary: 'sans-serif'
    },
    colors: {
      grayscale: { 0: '#222', 1: '#555' },
      primary: { 1: '#2196f3' }
    }
}
```

With your suggestion:
```js
const ShareButton = styled.button`
  color: ${({ theme }) => theme.colors && theme.colors.grayscale && theme.colors.grayscale[1] || '#555'};
`
```

I'm not suggesting a change. On the contrary, until `v1.1.3` it had been working this way (`ThemeProvider` taking precedence over `defaultProps`). It was a breaking change.

**Comment by k15a** [comment]
That's a good point. I would like to get this fixed.

**Comment by flavordaaave** [comment]
I still have the problem, that the defaultProps seem to have higher prio over the theme from `<ThemeProvider>`.

I have an Image component that looks something like this:
```
const ImageWrapper = styled.div`
  width: ${props => (props.circular && props.width ? props.width : 'initial')};
  height: ${props =>
    props.circular && !props.width ? props.height : 'initial'};
  padding-bottom: ${props =>
    props.circular && props.width ? props.width : 'initial'};
  padding-right: ${props =>
    props.circular && !props.width ? props.height : 'initial'};
  position: relative;
  display: inline-block;
`

const ImageObject = styled.img`
  object-fit: cover;
  position: ${props => (props.circular ? 'absolute' : 'initial')};
  width: ${props => (props.circular ? '100%' : props.width)};
  height: ${props => (props.circular ? '100%' : props.height)};
  border-radius: ${props => (props.circular ? '50%' : 0)};
  border: ${props =>
    props.bordered
      ? `${props.theme.border_width} solid ${props.theme.border_color}`
      : 'none'};
`

const Image = props =>
  props.circular ? (
    <ImageWrapper {...props}>
      <ImageObject {...props} />
    </ImageWrapper>
  ) : (
    <ImageObject {...props} />
  )

Image.propTypes = {
  ...
  theme: Proptypes.objectOf(Proptypes.string),
}

Image.defaultProps = {
  ...
  theme: {
    border_color: '#ffffff',
    border_width: '6px',
  },
}

export default Image
```

No matter if I wrap the `<Image>` component within a `<ThemeProvider>` or not, it always uses the defaultProps.theme.

(`"styled-components": "2.2.3"`)

**Comment by ryxle** [comment]
I agree with @flavordaaave. I'm also having this exact issue. Do we have a solution for this? @k15a appreciated your feedback on this.

**Comment by k15a** [comment]
@flavordaaave @ryxle For me it's working how it should work: https://codesandbox.io/s/m7l9p9wv2y. Could you create a new Issue with a reproduction?

**Comment by philpl** [comment]
@flavordaaave @ryxle if the issue persists, can you please open a new issue? This is for v1 so likely unrelated :smile:

**Comment by rwet9614** [comment]
@k15a I updated your code according to mine. The way I've done it, I still get the problem. Can you explain what's the problem please?.

@philpl my apologies. Based on @k15a answer I'll definitely open a new issue.

**Comment by k15a** [comment]
I've simplified your example here: https://codesandbox.io/s/vj7nl039jl

The problem is that you're basically passing the theme as a component explicitly. That's because you don't have the defaultProps on the styled-components directly.

The order of which theme get's selected is: props > ThemeProvider > defaultProps.

**Comment by rwet9614** [comment]
@k15a, so what you mean is `defaultProps` only applied to single styled-components that I export directly, yes?

**Comment by k15a** [comment]
You have to attach the default props to the styled-component if you want that we ignore them.

**Comment by rwet9614** [comment]
@k15a awesome! thank you for your explanation. 🙏

**Comment by berikiushi** [comment]
Hi. I have the same problem.
I created a simple example here: [https://codesandbox.io/embed/rrlyvjz2nm](https://codesandbox.io/embed/rrlyvjz2nm)
can anyone help with this?

**Comment by donifer** [comment]
Has anyone figured out how to do this with typescript? In order to get `defaultProps` working for styled components with typescript you need to wrap the styled component in a class component. 

In that case you are passing the props directly so its overriding whatever its set by ThemeProvider.

Any suggestions?

**Comment by prathick** [comment]
I still have this issue when I try to override style-component styles and pass it default props. 
for instance:

`const StyledInput = styled(Input)'
background: ${({ theme }) => theme.palette.background};
' // here input is already a styled-component

StyledInput.defaultProps = {
theme: { palette: {background: 'red'}}
}
`

Now if I pass a different theme using Themeprovider,  I still see the default props. 

Any help guys?
