### ISSUE TITLE
every hot module replacement in development after change the styles are not replaced but appended to the style tag，what is this used for?

### ISSUE THREAD

**Issue by hotbearnie** [styled-components/styled-components#3442]
![image](https://user-images.githubusercontent.com/24648812/112427862-4009b480-8d75-11eb-9ede-91ef65a7521e.png)

**Comment by kitten** [comment]
All styles in styled-components are additive, and never subtractive, i.e. unmounting a component doesn't remove its styles. See: https://github.com/styled-components/styled-components/issues/3105#issuecomment-895250512
