### ISSUE TITLE
Missing style class names after being built in NextJS

### ISSUE THREAD

**Issue by keerthivasanclumzo** [styled-components/styled-components#3443]
## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`
### System:
 - OS: Linux 5.8 Ubuntu 20.10 (Groovy Gorilla)
 - CPU: (2) x64 Intel(R) Pentium(R) CPU G630 @ 2.70GHz
 - Memory: 207.72 MB / 3.74 GB
 - Container: Yes
 - Shell: 5.0.17 - /bin/bash
### Binaries:
 - Node: 15.11.0 - ~/.nvm/versions/node/v15.11.0/bin/node
 - Yarn: 1.22.10 - ~/.nvm/versions/node/v15.11.0/bin/yarn
 - npm: 7.6.0 - ~/.nvm/versions/node/v15.11.0/bin/npm
### npmPackages:
 - styled-components: ^5.2.1 => 5.2.1 
 
## Steps to reproduce

 - Create a simple App using NextJS
- I think this step is what's causing the problem. Create a component that looks like this:  
```
import sc from 'styled-components'

export function Elem(width, content) {
 const elem = sc.div`margin-right:4vw;width:${width};padding:5vw` // a variable is used inside the styling?
 return <elem>Hello world</elem>
}
``` 
In `pdt/index.js`:
```
import { Elem } from '..path'

export default function Home() {
 return (<div>
  <Elem width="5vw"/>  
  <Elem width="15vw"/>  
</div>)
}

```

Run `next dev` and in another terminal tab `next build && next export` and serve the `out` directory in a port 

Open the two different ports and compare them

## Expected Behavior

Dev and Production (Build) Version should look the same.

## Actual Behavior

From some bit of looking around in the browser, styled-components generates a Id for the class as usual but there is no mention of that id in any of the css produced. Hence the class has no styling and the dev and build versions look different

**Comment by keerthivasanclumzo** [comment]
I have tried the website again after losing the variables in the style and it still doesn't generate a style for the class id it generated.

**Comment by kitten** [comment]
There's no reproduction here for me to look at, however, I'm seeing that you're creating a StyledComponent _dynamically_ inside another component, which is disallowed. You may even get a warning about that (check the console)

Please try StackOverflow for usage questions if you have a bit more code and details to provide. It'd be much faster to get an answer there ❤️ Here, you've basically submitted a bug template issue for something that's a usage issue on your end
