### ISSUE TITLE
Upgrading 5.2.1 to 5.2.2 breaks SSR and Static render (in at least NextJS) as `window` is not defined

### ISSUE THREAD

**Issue by mduleone** [styled-components/styled-components#3447]
## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`

```sh
## System:
 - OS: macOS 10.15.7
 - CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
 - Memory: 47.51 MB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 12.21.0 - /usr/local/bin/node
 - Yarn: 1.22.10 - /usr/local/bin/yarn
 - npm: 6.14.11 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: ^1.12.0 => 1.12.0
 - styled-components: ^5.2.2 => 5.2.2
```

## Reproduction

Dependabot PR branch fails at static-build time with the error (bits that are related to `styled-components`, at least)

```sh
ReferenceError: window is not defined
    at k (/tmp/build_7c8142a2/node_modules/styled-components/dist/styled-components.cjs.js:1:7161)
    at e.getStyleElement (/tmp/build_7c8142a2/node_modules/styled-components/dist/styled-components.cjs.js:1:22622)
```

When running it locally (the environment represented in the **Environment** section above), I get the same error but with absolute paths matching my local setup rather than our build environment.

## Steps to reproduce

I assume, attempt to statically/server render anything

## Expected Behavior

Static CSS renders properly without `window` object

## Actual Behavior

Builds fail

**Comment by douglaslb** [comment]
I just updated [styled-components](https://github.com/styled-components/styled-components/tree/v5.2.3) to version 5.2.3 and it worked like a charm.

**Comment by mduleone** [comment]
Ahh! I see this was [resolved yesterday](https://github.com/styled-components/styled-components/issues/3444), but our dependabot process ran before 5.2.3 was released. Manually updating to 5.2.3 and closing this issue. Thank you!
