### ISSUE TITLE
StyleSheetManager target prop not injected styles in the node

### ISSUE THREAD

**Issue by nobulirakli** [styled-components/styled-components#3448]
Currently I'm running this on latest CRA with ant design.
My main intention is to clone a node with style element inside to be used on third party websites.

The `target` prop does not respect any other node outside of `document.body`. Is it because it's outside of React influence? Would be great if I could inject the styles as children because targeting them with `querySelector` is not optimal.

Side note. Grabbing the style node on localhost worked fine, but when I build and deploy CRA, style element is empty, but the styling is applied.

**Comment by kitten** [comment]
There's no reproduction or details here for me to look at it respond to unfortunately. But maybe look at my response for this issue: https://github.com/styled-components/styled-components/issues/3548

Another note, the style element may not be empty. Check it's CSSOM rules, which the browser will not display as text in the devtools.

Also, if it works with a query selector, there's a good chance you simply haven't passed it a DOM element references in your regular non-queried variant of your code
