### ISSUE TITLE
Question: Is it possible to reduce generated class name length?

### ISSUE THREAD

**Issue by M1ck0** [styled-components/styled-components#3449]
Is it possible to do something like [next-optimized-classnames](https://www.npmjs.com/package/next-optimized-classnames) does with modules?

I want to reduce class names in production. If it is not supported by default, which probably isn't because I couldn't find any resource for it, it would be cool if we could make something like that. 

I think it would really reduce the size of pages since currently, classes look like `style__StyledButton-sc-1m71lfi-0 blKlMR` which is ok if you have few elements on a page but the reality is different.

Any tips or ideas will be gladly accepted.

**Comment by kitten** [comment]
It's not supported. Currently class names mut either be based on a hash or on a component ID. We do have an internal group and numbering system and we're playing with the idea (in another issue I can't find right now) to replace the hashes. There are some problems with that however.

The component's rules are ordering dependent. That means that if you create components, you'll always create them in order. This is then also the order that they'll adhere to when they're mounted. This then becomes tricky with SSR however, when the app is split up into several dynamically loaded parts. Even then SC has to rehydrate their order and group numbering and preserve it on the client-side.

This is further complicated by the fact that we use these names to then check which rules have already been inserted. So, long story short, there are a lot of things to take care of and update that'd ultimately lead to a tiny benefit, which may not make sense in development, where we'd want classes that are based on readable names.

So for now, I don't think we'll change this approach given the SSR constraints
