### ISSUE TITLE
[Feature Suggestion] Helper functions for common use cases?

### ISSUE THREAD

**Issue by sbacic** [styled-components/styled-components#3453]
Would there be any interest in adding helper functions such as:

```JSX
const Component = styled.button`
    color: green;

    ${has('alternate')`
        color: yellow;
    `}

    ${is('alternate', 'danger')`
        color: red;
    `}
`;

<Component alternate />
<Component alternate="danger" />
```

I keep running into situations where I need to apply several styles based on props or prop values and this would make the resulting code more readable.

Would there be any interest in merging something like this if I were to submit a PR?

**Comment by evandavis** [comment]
Kinda reminds me of this: https://github.com/eveningkid/pretty-components

fwiw, I've been handling this by creating a simple wrapper component that is just a `switch` to return different variations, e.g.

```js
// The Button from the last section without the interpolations
const Button = styled.button`
  color: palevioletred;
  font-size: 1em;
  margin: 1em;
  padding: 0.25em 1em;
  border: 2px solid palevioletred;
  border-radius: 3px;
`;

// A new component based on Button, but with some override styles
const TomatoButton = styled(Button)`
  color: tomato;
  border-color: tomato;
`;

render(props) {
  switch (props.kind) {
    case 'tomato':
      return <TomatoButton>Tomato Button</TomatoButton>;
    default:
      return <Button>Normal Button</Button>;    
  }
}
```

I'd love a way to do this without adding additional nodes to the tree!

**Comment by sbacic** [comment]
@evandavis 

I've basically solved this by writing a set of helpers that I can just import into projects as needed: 

https://github.com/sbacic/styled-components-helpers

Though I still think it should be part of the core library.

**Comment by kitten** [comment]
I'll close this for now, since you have a library of your own to address this. I'd basically say that an excessive amount of small helpers doesn't actually _help_ the average user (ha 😅)

It'd increase the API surface for something that's essentially quite small, and it'd then become questionable what the appropriate way to write a certain interpolation is as there'd be more than one idiomatic approach
