### ISSUE TITLE
Failed compile when using union type to styled-components wrapped component props.

### ISSUE THREAD

**Issue by sottar** [styled-components/styled-components#3454]
Hey, I think this is a bug when we using union type to component props wrapped by styled-components.
Is there any workaround?

## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`

## System:
 - OS: macOS 10.15.2
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
 - Memory: 569.39 MB / 64.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 14.15.4 - ~/.nodenv/versions/14.15.4/bin/node
 - Yarn: 1.21.1 - /usr/local/bin/yarn
 - npm: 7.6.3 - ~/.nodenv/versions/14.15.4/bin/npm
## npmPackages:
 - styled-components: ^5.2.3 => 5.2.3

## Reproduction

https://codesandbox.io/s/elastic-bell-3tgie?file=/src/App.tsx:466-544

## Expected Behavior

path compile

## Actual Behavior
compile failed

**Comment by kitten** [comment]
I'm not quite sure the description here is sufficient, however, we don't maintain the TypeScript typings in this repo currently. They may become part of the main library with a TyoeScript rewrite, however currently they're maintained in and sourced from definitely-typed 

So if it's an issue with the typings we wouldn't be able to fix it in this repo, and if it isn't I unfortunately don't have the immediate bandwidth to fix this with you or debug the typings.

I can only advice you to look at the inferences and errors carefully and investigate whether all inferred types are what you expect, and correct things from there on
