### ISSUE TITLE
Bug - conditionally rendered styles via the css helper function return incorrect property values

### ISSUE THREAD

**Issue by wdfinch** [styled-components/styled-components#3455]
## System:
 - OS: Linux 5.8 Ubuntu 20.04.2 LTS (Focal Fossa)
 - CPU: (20) x64 Intel(R) Core(TM) i9-10900KF CPU @ 3.70GHz
 - Memory: 20.23 GB / 31.23 GB
 - Container: Yes
 - Shell: 5.8 - /usr/bin/zsh
## Binaries:
 - Node: 15.14.0 - /usr/bin/node
 - Yarn: 2.4.1 - /usr/bin/yarn
 - npm: 7.7.6 - /usr/bin/npm

styled-components version: 5.2.3

## Reproduction
https://codesandbox.io/s/musing-fermi-s0d9z?file=/src/App.js

## Steps to reproduce
Open developer tools and observe the styles present on the `Text` element. Notice that the color property is incorrectly outputted as:

`color: ,green,; `

## Expected Behavior
**If**
1. The user conditionally renders styles using the `css` helper function
_and_
2. Returns a CSS property via a function  (ex. `const getColor = () => 'green'`)

**Then:**
The property should be the same as what we returned. It should not be wrapped in commas. (ex. the css generated should be `green` not `,green,`).

## Actual Behavior
It seems that:

**If**
1. We conditionally render styles that are generated via the `css` helper function
_and_
2. A property value is returned from a function (ex. `const getColor = () => 'green'`)

**Then**
The property returned from the function will be wrapped with commas and therefore will not be rendered by the browser as it's an incorrect property value.

**Comment by kitten** [comment]
You've used a regular template literal to embed a `css` tagged template literal. You can embed a template literal directly, but if you embed a `css` tag you basically can't stringify it and expect the correct output. It'll have an intermediate representation that isn't a plain string

**Comment by wdfinch** [comment]
Ok well, this would be very useful assuming there isn't a better way to mix in code other than using the `css` helper. For example, I often have a bunch of styles that I want to share between components and sometimes these shared styles have template literals in them (to control what get's rendered via props). I want to be able to render these styled anywhere and sometimes I want to only render them conditionally in other components. It would be awesome if that was possible. If there's some better way to do this, could you please share it?

**Comment by kitten** [comment]
Ok, maybe I wasn't clear on this 😅 You _can share_ `css` annotated CSS, i.e. **tagged** template literals. But if you interpolate the return value of `css` into a _regular_ template string then you'll get invalid output, i.e.:

```js
css`${css``}` // this works
`${css``}` // this does not work
```

**Comment by wdfinch** [comment]
Ok thanks I'll try that out.
