### ISSUE TITLE
I got different classname by same css

### ISSUE THREAD

**Issue by sp0033212000** [styled-components/styled-components#3456]
## System:
 - OS: macOS 11.2.3
 - CPU: (8) x64 Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz
 - Memory: 101.36 MB / 16.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 14.16.0 - /usr/local/bin/node
 - Yarn: 1.22.10 - /usr/local/bin/yarn
 - npm: 6.14.11 - /usr/local/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman

## Reproduction

https://codesandbox.io/s/xenodochial-liskov-bhsd2?file=/src/App.tsx

## Steps to reproduce

Passing same css into two components.

## Expected Behavior

Got same classname by same css.

## Actual Behavior

Got different classname by same css

**Comment by rkingon** [comment]
IMO, that feels like expected behavior...

**Comment by kitten** [comment]
Yes, that's expected. Different components are expected to insert different rules, which necessitates them having different names and generated classes. This comes down to specificity and CSS rule ordering.
