### ISSUE TITLE
`createGlobalStyle` is not exported by `node_modules/styled-components/dist/styled-components-macro.esm.js`

### ISSUE THREAD

**Issue by nbhargava** [styled-components/styled-components#3458]
## System:
 - OS: macOS 10.15.7
 - CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
 - Memory: 2.05 GB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
 - Yarn: 1.22.10 - /usr/local/bin/yarn
 - npm: 6.14.10 - ~/.nvm/versions/node/v14.15.4/bin/npm
## npmPackages:
 - styled-components: ^5.2.1 => 5.2.3 

## Reproduction

We're using `rollup` to package our library, and when we try to use `import { createGlobalStyle } from "styled-components/macro";`, in accordance with the example from [the docs](https://styled-components.com/docs/tooling#babel-macro), we see:
```
[!] Error: 'createGlobalStyle' is not exported by node_modules/styled-components/dist/styled-components-macro.esm.js, imported by src/styles/GlobalStyle.ts
```

## Steps to reproduce

See above.

## Expected Behavior

`createGlobalStyle` should be correctly exported.

## Actual Behavior

When we peer into `styled-components-macro.esm.js`, it does in fact seem like the `createGlobalStyle` export is missing despite the symbol being present in `styled-components-macro.cjs.js`.

**Comment by pjg** [comment]
I was unable to fix this issue in my setup (React v17, but not create-react-app), despite googling a lot. However, I found the following workaround, by telling eslint to ignore missing named exports from styled-components. In my `.eslintrc.js` I added:

```
module.exports = {
  ...
  settings: {
    ...
    'import/ignore': ['./node_modules/styled-components'],
```
