### ISSUE TITLE
Input on a width of 100% goes out of bounds.. 

### ISSUE THREAD

**Issue by satish-rajnale** [styled-components/styled-components#3462]
## Reproduction

https://codesandbox.io/s/magical-dubinsky-kz78b?file=/src/App.js

## Steps to reproduce
As given in the codesandbox For InputName styled components width value.

## Expected Behavior
 -Expected it to cover all the `width` inside the InputContainer .

-Well it gets  fixed when the `width` is set to `inherit`, but then when I give the InputName a padding-left:30px 
it shifts the whole InputName to the right by 30px out-of-component scope rather applying padding to the inner text.

![input](https://user-images.githubusercontent.com/76589507/114768167-25c86280-9d86-11eb-90f1-54cd507dc2e5.PNG)

**Comment by satish-rajnale** [comment]
### I fixed the padding and width issue with  ::-webkit-input-placeholder { } 
### But the InputContainer which is div triggers this behavior on a width of 100%;

**Comment by MdUsmanAnsari** [comment]
@satish-rajnale 

remove  position: fixed; from InputName.

**Comment by MdUsmanAnsari** [comment]
@satish-rajnale 
simply, remove position: fixed; from InputName. because position: fixed; is positioned relative to the viewport.

**Comment by satish-rajnale** [comment]
Thank you
