### ISSUE TITLE
SSR hydration error when using attrs and props

### ISSUE THREAD

**Issue by caribou-code** [styled-components/styled-components#3464]
## System:
 - OS: macOS 11.2.3
 - CPU: (8) x64 Apple M1
 - Memory: 88.90 MB / 16.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 14.16.0 - ~/.nvm/versions/node/v14.16.0/bin/node
 - npm: 6.14.11 - ~/.nvm/versions/node/v14.16.0/bin/npm
## npmPackages:
 - babel-plugin-styled-components: 1.10.0 => 1.10.0 
 - styled-components: 5.2.1 => 5.2.1 

## Reproduction

See below

## Steps to reproduce

1. Define a styled component that applies `attrs` follow by a function (that could be used for destructuring):
    ```
    const Foo = styled.div.attrs({ as: 'p' })(() => `display: block;`);
    ```

2. Use the component in a Next.js application that uses server side rendering: `<Foo />`

## Expected Behavior

Nothing should be different between the server side rendered version and the client side version. There should be no console errors regarding this.

## Actual Behaviour

The follow console error: 
```
Warning: Prop `className` did not match. Server: "sc-kYrkKh Ycxsm" Client: "sc-dacFzL bnynnM"
```

This is due to classnames generated during server side rendering not matching the classnames applied by the client - so something changes in this process. Removing the `attrs` fixes the problem:
```
const Foo = styled.div(() => `display: block;`);
```

## Notes

For anyone wondering why I might write the syntax like my example, here's something more complex but valid (for framer motion):

```
const Foo = styled.div.attrs(
  ({ theme }) => ({
    transition: {
      duration: theme.animation.duration,
    },
    variants: {
      visible: { opacity: 1 },
      hidden: { opacity: 0 },
  })
)(
  ({ theme }) => css`
    color: ${theme.colors.primary};
  `,
);
```

**Comment by kitten** [comment]
This isn't really supported syntax output, so my guess is that the `babel-plugin-styled-components` application you may have on Babel's end to facilitate stable SSR names isn't working once you use a syntax it doesn't support. Similarly, if you don't have _any static CSS_ in your tagged template, then there's no consistent temporary hash that the library can generate, so the result won't be consistent.

I'll close this for now due to inacitviy, but also because it's unsupported syntax for the most part.

**Comment by caribou-code** [comment]
@kitten thanks for the reply. Just to confirm is it unsupported syntax because `.attrs` is for applying HTML attributes not React props?

**Comment by kitten** [comment]
@caribou-code I'd rather suspect that the Babel plugin's targeting wouldn't pick up on styled-components that have been constructed with just a function as an argument.

**Comment by caribou-code** [comment]
@kitten Sorry for the late reply. Am I correct in saying you're referring to this syntax:

```
const Foo = styled.div(
  ({ theme }) => css`
    color: ${theme.colors.primary};
  `,
);
```

Because if so, this does work (including with SSR). The issues I've encountered are specifically when `.attrs` is added to the mix.
