### ISSUE TITLE
[SSR] className did not match server

### ISSUE THREAD

**Issue by luizeboli** [styled-components/styled-components#3474]
I have a hero section that changes it's background image randomly every time the component renders, but I'm getting this error during SSR:

```
Warning: Prop `className` did not match. Server: "styles__HeroImage-sc-10m5c3u-0 kfAGDo" Client: "styles__HeroImage-sc-10m5c3u-0 keApON"
```

## System:
 - OS: Linux 5.4 KDE neon 5.21
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
 - Memory: 2.43 GB / 15.49 GB
 - Container: Yes
 - Shell: 5.8 - /usr/bin/zsh
## Binaries:
 - Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
 - Yarn: 1.22.10 - ~/.nvm/versions/node/v14.15.4/bin/yarn
 - npm: 7.6.3 - ~/.nvm/versions/node/v14.15.4/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.12.0 => 1.12.0 
 - styled-components: ^5.2.3 => 5.2.3 
## Reproduction

I've created [a repository](https://github.com/luizeboli/styled-components-ssr) to reproduce this behavior. I'm using NextJS.

The code that triggers the error during SSR is in `/pages/index.js`

## Steps to reproduce

Have a dynamic content passed to styled-component

## Expected Behavior

SSR should be able to handle correctly a dynamic content 

## Actual Behavior

The page is rendered on server-side but the image flashes after loading due styles mismatch

**Comment by lucashfreitas** [comment]
Please check: 

- https://styled-components.com/docs/advanced#server-side-rendering.
- https://medium.com/swlh/server-side-rendering-styled-components-with-nextjs-1db1353e915e


You need to add this code block to `pages/__document.tsx`:

```
export default class MyDocument extends Document {
  static async getInitialProps(ctx) {
    const sheet = new ServerStyleSheet();
    const originalRenderPage = ctx.renderPage;

    try {
      ctx.renderPage = () =>
        originalRenderPage({
          enhanceApp: (App) => (props) =>
            sheet.collectStyles(<App {...props} />),
        });

      const initialProps = await Document.getInitialProps(ctx);
      return {
        ...initialProps,
        styles: (
          <>
            {initialProps.styles}
            {sheet.getStyleElement()}
          </>
        ),
      };
    } finally {
      sheet.seal();
    }
  }
}
```

**Comment by luizeboli** [comment]
@lucashfreitas I have already setup a custom document.  This error online happens in this situation.

Please check my file [here](https://github.com/ufersa/plataforma-sabia/blob/master/packages/web/pages/_document.js)
