### ISSUE TITLE
Bug?  Rules silently ignored depending on where CSS variable with inline SVG is defined

### ISSUE THREAD

**Issue by beorn** [styled-components/styled-components#3485]
## Environment & reproduction

See code sandbox: https://codesandbox.io/s/styled-components-base-forked-lmxnz?file=/index.js

I've also inlined the code at the end since it's so small.

## Steps to reproduce & actual behavior

If the CSS variable containing the SVG is defined inside of the `h1 {}` scope, then none of the following h1 scoped rules are used - they are all silently ignored.

The example CSS variable:

`--svg: url('data:image/svg+xml; utf8, <svg xmlns="http://www.w3.org/2000/svg" width="12" height="11" viewBox="0 0 12 11"><circle cx="6" cy="5.5" r="3.5" fill="hsl(0deg 0% 93%)" /></svg>');`

## Expected Behavior

1. It wouldn't matter if I defined the CSS variable in the root scope (line 7) or h1 scope (line 9); all rules, including the `papayawhip` background color rule, would work independently of where I defined the CSS variable.
2. If I'm making a mistake, there would be some kind of error somewhere, not just silently eating rules.

## Code

```js
import React from "react";
import { render } from "react-dom";
import styled from "styled-components";

const Wrapper = styled.section`
  /* It works if you defined --svg here in the root scope */

  h1 {
    --svg: url('data:image/svg+xml; utf8, <svg xmlns="http://www.w3.org/2000/svg" width="12" height="11" viewBox="0 0 12 11"><circle cx="6" cy="5.5" r="3.5" fill="hsl(0deg 0% 93%)" /></svg>');
    /* But if it is deifned here, inside of the h1 scope,
     * all remaining h1 rules (the background rule below)
     * are ignored, but not other rules (like the outline rule)
     */
    padding: 3em;
    &::after {
      content: var(--svg);
      background-color: red;
    }
  }
  h1 {
    background: papayawhip;
  }
  outline: solid 1px rebeccapurple;
`;

const App = () => (
  <Wrapper>
    <h1>Hello World!</h1>
  </Wrapper>
);

render(<App />, document.getElementById("root"));
```

**Comment by kitten** [comment]
This is likely an issue with how `stylis` perceives your input there. Generally, you can try to base64 encode this, but otherwise there isn't much we can do to resolve this. I believe the upgrade to `stylis@4` may fix this though once it's dropped into styled-components.

For now, I'll go ahead and close this, since there's not much we can do to fix this on our end. But rest assured, you're not doing anything wrong, it's likely stylis that in v3 can't parse this.
