### ISSUE TITLE
An issue with syntax highlighting when ts interface is multiline

### ISSUE THREAD

**Issue by Newbie012** [styled-components/styled-components#3486]
## System:
 - OS: macOS 11.2.2
 - CPU: (8) arm64 Apple M1
 - Memory: 827.30 MB / 16.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
 - npm: 6.14.13 - ~/.nvm/versions/node/v12.22.1/bin/npm

## Reproduction

https://codesandbox.io/s/styled-components-base-forked-78b8h

## Steps to reproduce

1. Open vscode
2. Install Night Owl extension theme.
3. Copy the code inside codesandbox into a typescript file,
4. See the syntax highlighting (an example in Actual behavior)

Unfortunately, I wasn't able to reproduce this specific issue in code sandbox, but you could see a different issue there that the CSS itself is not highlighted.

## Expected Behavior

![image](https://user-images.githubusercontent.com/10504365/117639525-af543000-b18c-11eb-8c0b-8e86b02c3d53.png)

## Actual Behavior

![image](https://user-images.githubusercontent.com/10504365/117639359-803dbe80-b18c-11eb-8e78-fc65ab374b0c.png)

**Comment by kitten** [comment]
This isn't a styled-components issue, but an issue dependent on your editor and setup.
Please don't report problems with your development environment in a repo dedicated to the library's codebase and its development 😅  If anything, `vscode-styled-components` may be able to help you, but issues aren't really meant for usage questions, so they're obviously not obligated to.

In other words, no change in this repository has any chance of resolving this, as it's unrelated, which makes this issue open-ended potentially. So, I'll have to close this for now
