### ISSUE TITLE
referring to component doesn't work when used from built component library

### ISSUE THREAD

**Issue by Adam-Collier** [styled-components/styled-components#3494]
Hi guys, a bit of a weird one here which I can't get my head around. I am trying to use https://styled-components.com/docs/advanced#referring-to-other-components to position the carousel arrows differently depending on whether the carousel is wrapped by the Blogposts wrapper or not. Everything works fine in the component libraries dev environment but when the library has been built and used in a different project it seems to totally ignore the reference and applies those styles regardless of the blogpost wrapper reference.

For clarification the arrows should be positioned at the top right for the blogposts carousel and at the bottom right for every other use of the carousel like the below:
![image](https://user-images.githubusercontent.com/20065745/118122489-d740cf00-b3ea-11eb-8935-5c6ebe6cac1a.png)

Here's a codesandbox to show you how it looks when the component library is used: https://codesandbox.io/s/shy-water-841rr?file=/src/App.jsx (notice how the top carousel's buttons are now at the top even though it isn't wrapped by the blogposts wrapper)

Here's the link to the component library: https://github.com/Adam-Collier/vite-storybook 
and where the refferring is being done: https://github.com/Adam-Collier/vite-storybook/blob/main/src/components/Carousel/index.jsx#L62

Even looking at the built component files (I havent minified it to make it easier to see what's going on) everything looks like it should work fine, so I'm unsure whether there is a bug hidden in there. If you could shed some light on whats potentially happening here that would be great as I'm kinda baffled why it would have this behaviour

**Comment by probablyup** [comment]
@Adam-Collier I'm a bit confused by the codesandbox, you have a src directory containing components but `App.jsx` doesn't use them?

**Comment by Adam-Collier** [comment]
@probablyup sorry thats my bad all of the components have been moved out of there into the component library. I've updated the codesandbox now so it should be more clear for you

**Comment by kitten** [comment]
> have been moved out of there into the component library.

There's no clear reproduction here, so I have unfortunately no clear advice on how to resolve this. That said, it is more of a usage issue and problem, so there's also not much we can do on our end. What I'd say is, maybe check whether you have a single version of styled-components installed and in your app's bundle. When using external component libraries and setting them up it's really easy to accidentally duplicate dependent libraries.

I did take a look at your sandbox, but I unfortunately also don't quite know what to expect from it or to look for. The links to your codebase you've got there are also not stable, i.e. don't contain a commit hash, so they're broken now 😅 Typically, when a question is asked, we don't really accept usage questions and answer them here and instead recommend other platforms like Stackoverflow. I still try to answer as many of them as possible, but when the reproduction isn't minimal (one or two files) it'd force me to take a look for much longer if I were to answer them. Sorry I couldn't give more advice than that!
