### ISSUE TITLE
Class create be styled component automatically adding to another div/component. (In cloud front). Works fine in local 

### ISSUE THREAD

**Issue by Surajbisht15** [styled-components/styled-components#3500]
I have created a styled component and added to a file like `<Something></Something>`
When  class is created dynamically by styled component, let's say 'abcd', this class is automatically adding to another `div` on run time.
![issue-sc](https://user-images.githubusercontent.com/48348715/119353685-d0566e00-bcc0-11eb-941c-e74f20c89973.png)

**### In image _red circle_ is wrongly added class.**

Please help!

**Comment by kitten** [comment]
This is expected behaviour, as far as I can tell. The `sc-` class will always preresent the component's identity or ID, and the additional class are the dynamically inserted styles.

Please keep in mind that without explaining a problem or posting code or following the issue template this is an invalid issue, and if you're asking a question you may get help quicker on StackOverflow, since we mostly use issues to track bugs and questions will sit around longer :v:

**Comment by Surajbisht15** [comment]
Red circle in image, `jvCTkj` classname should not be there! 
E.g., 
<LoginFieldWrapper>
                <h2>DUmmy</h2>
</LoginFieldWrapper>
Green Circle in image representing correct class. 
Why this same class is appending above(red circle in image) while I am not using `LoginFieldWrapper` there!!

**Comment by Surajbisht15** [comment]
Opened a new issue [here] (https://github.com/styled-components/styled-components/issues/3501)

**Comment by kitten** [comment]
@Surajbisht15 Please don't just create a new issue. You're still able to respond to a closed one. However, as I said, this is a _question_ and not an issue, meaning that it's likely something that you can clear up by asking a more precise question or posting code, but even in that case an issue tracker is not a board for questions.

Please don't circumvent responses by creating another issue. They'll still just show up for us maintainers, and frankly creating a duplicate is just disrespectful.

I'm happy to take a look at what your problem may be if you post a codesnippet or a reproduction in a codesandbox, but our issue template is very clear about what we need to even offer help:

> 🚨HOLD UP PLEASE, BEFORE DELETING THIS TEMPLATE!🚨😁
> Thank you for contributing and please follow this guide before creating an issue! 🙌
> - Don't forget to 👉PROVIDE A REPRODUCTION PLEASE 😉 (Codesandbox links are provided and most useful, repositories are ok)

**Comment by jonasfelipe95** [comment]
I have the same problem. When building my application, styled components are putting styles from one component to another. He's getting lost in element references somehow. In my case I have an architecture with micro frontend and the parent component and the child component have styled components.

**Comment by Alphavader** [comment]
+ 1 still having this issue! (Gatsby 3)
