### ISSUE TITLE
TypeScript config for the theme does not work on “styled” helper

### ISSUE THREAD

**Issue by meissam** [styled-components/styled-components#3507]
Hi Guys.
when I configured my theme based [on the documentation](https://styled-components.com/docs/api#create-a-declarations-file), the vs code's autocompleting functionality works like a charm when I'm using "createGlobalStyle" and "css" helpers. When I use "styled" helper, it doesn't work. How can I cope with this issue? 
![01](https://user-images.githubusercontent.com/69047033/120342586-2a80b000-c30d-11eb-942e-332ad5f27d1d.png)
![02](https://user-images.githubusercontent.com/69047033/120342592-2d7ba080-c30d-11eb-98d7-839cd1a2891a.png)

**Comment by jnthnk** [comment]
Same here... theme autocomplete doesn't works using the styled function inside the ThemeProvider.
But it compiles fine.

**Comment by meissam** [comment]
@jnthnk 
thanks for sharing. I tried this before. Currently, I have a declaration file in my project, but it doesn't work and the issue still exists.

**Comment by kitten** [comment]
The styled-components typings are currently actually not maintained in the mainline repository but are located in DefinitelyTyped. Hence, we unfortunately don't maintain them directly here, but they're maintained by different people, until we settle on whether we can release a Typescript rewrite with better typings baked in
