### ISSUE TITLE
Enhancement: Optionally output Atomic classes

### ISSUE THREAD

**Issue by soluml** [styled-components/styled-components#351]
In the linked [WebpackBin example on the homepage](http://www.webpackbin.com/V1VNoINA-), you create two components: `<Wrapper>` and `<Title>`.

They produce this stylesheet:
```
<style type="text/css">.⏏ 🙉 🌃 ⛄ { 
  font-size: 1.5em;
  text-align: center;
  color: palevioletred;
 }.🔸 😊 ☄ { 
  padding: 4em;
  background: papayawhip;
 }</style>
```

This works really well for smaller web apps, but additional byte savings can be achieved in larger apps by using atomic classes.

If we were to manually approach the above example using Atomic CSS principles, we'd have the resulting sheet:

```
<style type="text/css">
.⏏ { 
  font-size: 1.5em;
}
.🙉 {
  text-align: center;
}
.🌃 {
  color: palevioletred;
}
.🔸 {
  padding: 4em;
}
.😊 { 
  background: papayawhip;
}
</style>
```
While larger than the traditional method in this small example, over the course of a large web app many properties will likely be reused over and over again and the resulting atomic stylesheet can actually be significantly smaller.

I've been using a tool called [Atomizer](https://github.com/acss-io/atomizer/) to help in authoring my stylesheets and while I enjoy the output size, the authoring isn't nearly as developer friendly as style-components.

Would the maintainers be open to a pull request with atomic classes as the output?  My initial thought for the PR would be to do it both ways, compare the size, and the resulting class(es) would then be passed into the className for the component.

Thoughts?

**Comment by geelen** [comment]
Not sure why you immediately closed this issue @soluml but it's a worthwhile suggestion. However, given the [permissive approach](https://github.com/styled-components/styled-components/blob/master/docs/css-we-support.md) to CSS features that we adopted, you can't reliably translate from atomic to non-atomic CSS.

There are some restricted cases where it can work ok (eg, a server-rendered HTML page with inlined CSS can be reliably rewritten to minify the CSS portion) but it's not something we're looking at. Feel free to reopen if you'd like to discuss more.

**Comment by soluml** [comment]
Yea sorry about that! I closed the issue because the byte benefits of the atomic approach would be primarily centered on a pre-built version (either server or build) and I wasn't sure if that was a strong enough use case but if you think it is then I'll go ahead and reopen.

The permissive approach wouldn't be a problem and is my primary draw to styled components. Atomizer handles [combinators, pseudo classes](http://acss.io/guides/syntax.html), and media queries as well and I'd approach the resulting output much the same they do.  I'm not sure if you'd consider it "Atomic" at that point, but Atomizer is maintained by the guys who popularized the concept so I consider it so :)

**Comment by soluml** [comment]
If you guys are open to it, I'd be more than happy to start working on a PR.. just didn't want to waste the dev hours if there was no interest.

I'd probably eventually pair it with a babel-plugin of sorts that could generate .css style sheets from the JSX template literals and swap in the resulting class name(s).  That's the primary draw for me with Atomizer.  Tiny and highly maintainable files.

**Comment by geelen** [comment]
Happy to have the discussion, but no I don't think there's much benefit to this approach. The key complexity comes around nesting & source ordering:

```js
const X = styled.div`
  color: red;
  > * {
    color: blue;
  }
`

const Y = styled.div`
  color: green;
`

<X><Y/></X>
```

In this, `.a1b2c3 > * { color: blue; }` and `.d4e5a6 { color: green; }` have the same specificity so depending on which order they're injected into the DOM one will override the other ([see this example](http://codepen.io/geelen/pen/VPwxmG)). But the source order is _only_ important if a `Y` is directly nested inside an `X` above, and that can't be known until render time.

We do a lot of work inside SC to ensure that the source ordering of the resulting CSS is the same as it was written in the JS, which is why we've always generated classes with the full set of declarations rather than trying to output atomic classes. Feel free to try, but I don't think you'll get very far, sorry!

**Comment by soluml** [comment]
Good point, I didn't consider that!

This is avoided in Atomizer by making sure that a single property is only set once.  If you're not mindful of that, similar specificity issues arise.  In a build tool, you could issue warnings but I don't think that makes much sense here.

Thanks for being my sound board!  I'd still like the marry the two concepts somehow but that won't be a good fit here.

**Comment by k15a** [comment]
You might checkout [cxs](http://jxnblk.com/cxs/) and their implementation. I don't think that this is a good fit currently because styled-components doesn't support server side rendering well and the on the client it doesn't really matter how much CSS you inject. Do you have some benchmarks that prove that atomic styles bring much size improvements over gzip?

**Comment by soluml** [comment]
As I've thought about it more tonight and I've largely come to the same conclusions as you @k15a. I think what I'm after is more of a babel-plugin / build tool than something that's bundled into the project. Something with the same syntax stylings of styled-components that generates CSS during a build and swaps in the resulting class names.

As for benchmarks, it depends completely on the project size and design. In my cases, I've found it to save me bytes in my CSS/HTML but I wouldn't consider it a macro optimization by any means although I would argue that a static cacheable CSS file will bring quite a few perf benefits over CSS authored by JS at runtime.

As for gzipping, I've gotten a benefit regardless with Atomic, but it's more pronounced with gzipping turned off obviously.

**Comment by AbinashGoMMT** [comment]
(Commenting Only for Discussion purpose)

Now that Styled Components has SSR support as well, what would be your stand in terms of Atomic Class support for generated classes
Specificity being a counter issue to this, the upside can not be denied. In large scale applications such as desktop web landscape, atomic class generation and usage is certain to reduce doc size for SSR'ed pages (React Native Web stylesheet approaches this in a unique way)
Would love to know your update-ed thoughts on this ? (cc @mxstbr )
(note: not able to find more relevant and recent discussions on this, hence commenting here)

**Comment by probablyup** [comment]
Not something we’re looking to do, but thanks for the thought. There are a
few other css-in-js libraries that do this if you’re interested in that
particular functionality.
