### ISSUE TITLE
react-is still showing up as a dependency even after being dropped

### ISSUE THREAD

**Issue by AlexEBall** [styled-components/styled-components#3513]
## System:
 - OS: macOS 10.15.6
 - CPU: (8) x64 Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz
 - Memory: 7.89 GB / 32.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 10.16.3 - ~/.nvm/versions/node/v10.16.3/bin/node
 - npm: 6.9.0 - ~/.nvm/versions/node/v10.16.3/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^5.3.0 => 5.3.0 

## Reproduction

When using a 3rd party [Bit](https://bit.dev/) to create/maintain composable components in React with `styled-components`. Upon trying to install styled components via CI in GitHub actions this error occurs:

```
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-is' in '/home/runner/Library/Caches/Bit/capsules/75686f8f8efb7cd87e0bfd4d0591d3ffb67e7571/node_modules/.pnpm/registry.npmjs.org/styled-components@5.3.0_react-dom@17.0.2+react@17.0.2/node_modules/styled-components/dist'
ModuleNotFoundError: Module not found: Error: Can't resolve 'react-is' in '/home/runner/Library/Caches/Bit/capsules/75686f8f8efb7cd87e0bfd4d0591d3ffb67e7571/node_modules/.pnpm/registry.npmjs.org/styled-components@5.3.0_react-dom@17.0.2+react@17.0.2/node_modules/styled-components/dist'
```

for some reason `react-is` is here as a peer dependency so it doesn't get loaded with its other dependencies of `styled-components`. Even though this recent [commit](https://github.com/styled-components/styled-components/commit/8165cbe994f6f749236244f6f7017c2f0b9afcfe) to the `styled-components` project drops `react-is`

## Expected Behavior

`styled-components` shouldn't reference `react-is` anymore

## Actual Behavior

`styled-components` still has `react-is` as a dependency in the latest build `^5.3.0`

**Comment by KutnerUri** [comment]
yes it seems to have been removed here: 8165cbe994f6f749236244f6f7017c2f0b9afcfe, even though it is still used. This means we have to add `react-is` as a dependency to our project / package just to use styledComponents. :S

I don't see any issue about it, why was it removed?

**Comment by emilystanek** [comment]
I am also having this issue when building a library with Bit

**Comment by pchhetri** [comment]
The commit to remove `react-is` as a dependency - https://github.com/styled-components/styled-components/commit/8165cbe994f6f749236244f6f7017c2f0b9afcfe - is date May 11. The latest version as of this writing - [v5.3.0](https://github.com/styled-components/styled-components/commits/v5.3.0) - was cut and released on May 4th.

I think this explains why `react-is` still shows up as a peer dependency.

**Comment by brickpop** [comment]
Same problem without Bit.
I try to build my project on gitHub CI and the build breaks because `react-is` is not available

**Comment by jnthnk** [comment]
Same here

**Comment by wesdollar** [comment]
For Bit, make sure `react-is` is listed in the `peerDependencies` section of `workspace.jsonc`. Run `install`, `compile`, then `tag`, and you should be good to go.

**Comment by kitten** [comment]
react-is has never been fully dropped. (Consult the changelog rather than commits for summaries of what's going on)

However, it's true that we tried to drop it but hit some roadblocks along the way. https://github.com/styled-components/styled-components/pull/3371

But with the recent commit, with the next release this will likely change, as work on this is ongoing from @probablyup

**Comment by TerrySlack** [comment]
I'm using  styled-components 5.3.5  and yarn v3.2.3 and get the following error:
```
Module not found: Error: styled-components tried to access react-is (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.
```
Looks like it's still a dependency.

**Comment by therb1** [comment]
Failed to compile.
./node_modules/styled-components/dist/styled-components.browser.esm.js
Cannot find module: 'react-is'. Make sure this package is installed.

**Comment by maakep** [comment]
This is not solved, using latest version of styled-components results in the same error in pipeline (GCP Cloud Build) but not locally. (using npm, 8.19.3)

**Comment by amalv** [comment]
Same problem here, using node `16.15.0` and npm `7.16.0` (also tested with npm `8.19.3`:

```shell
ERROR in ./node_modules/styled-components/dist/styled-components.browser.esm.js 1:0-73
Module not found: Error: Can't resolve 'react-is' in 'C:\Users\user\project\node_modules\styled-components\dist'
```

**Comment by sbland** [comment]
I think this can also be caused by having multiple versions of styled-components installed. I came across this issue using Bit where I had a package that depended on `5.3.6` and one that depended on `^5.3.6`.

**Comment by sandaruny** [comment]
I changed my node version to LTS and used Yarn. Yarn seems to be installing the dependencies which are needed.

**Comment by ianchanning** [comment]
I got this error with yarn but not with npm.
