### ISSUE TITLE
Hot reloading based on changes in SC is affected by the nature of its import/export

### ISSUE THREAD

**Issue by dabljues** [styled-components/styled-components#3514]
## System:
 - OS: Windows 10 10.0.19042
 - CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
 - Memory: 2.19 GB / 15.92 GB
## Binaries:
 - Node: 14.16.0 - C:\Program Files\nodejs\node.EXE
 - npm: 6.14.11 - C:\Program Files\nodejs\npm.CMD
## npmPackages:
 - styled-components: ^5.3.0 => 5.3.0

## Reproduction

I've setup a simple example here: https://codesandbox.io/s/young-sea-i5i8n. It mimics the thing I am trying to do in my project.

## Expected Behavior

After making a change in `Foo` and saving the file, the change should appear on the screen - both in my project (bootstrapped with `create-react-app`) and on codesandbox.

## Actual Behavior

The changes are not being made until I refresh the page - both in my project and here on codesandbox. And the file save on codesandbox can be loosely interpreted as hot reloading in react apps - not the same thing, but most of the time works the same. And by the way, I think the hot reload happens - I can see it when I work on my project: Ctrl+S -> and body and html tags flash in Dev Tools.

Now for the fun part:

* I've added `FooInTheSameFile` - making changes causes the changes to appear instantly
* I've also added and commented out `FooCss` - it also works

So the only problem was that the option with `Foo` and `Bar1` didn't work. But when I was creating this example, I've stumbled upon something odd. When I was exporting `Foo` as the only thing from `Foo.tsx`  - so a default export via `export default Foo` - it didn't work. As soon as I've added `FooCss` and exported it as well - `export {Foo, FooCss}` - suddenly, the changes made to `Foo` started working without a refresh.

Now I don't know if that's an issue of default export or import, but I am pretty damn sure it's one of them.

Please check it yourself - don't event use `FooCss`, just uncomment it and export in alongside `Foo`, like `export { Foo, FooCss }`. This change alone makes it so changing `Foo` automatically updates the view. And another funny thing - if `FooCss` were to be a `styled.<something>` - exporting it doesn't help. It seems like exporting a `css` variable makes the difference here - or actually anything, I've even created a dummy react component. The only thing that doesn't work is exporting the `styled.<something>` alone - doesn't trigger the updates.

Do you guys know how to handle this? Cuz I love my hot reloading when I develop React apps

**Comment by kitten** [comment]
Sorry, I'll have to close this for now due to inactivity. In general, this is also an issue that's unrelated to the codebase in this repository itself, so there's not really any way forward to resolve this. In other words, no change in this repository has any chance of resolving this, as it's unrelated, which makes this issue open-ended potentially.
