### ISSUE TITLE
Duplicated styling with -webkit-image-set

### ISSUE THREAD

**Issue by Romybron** [styled-components/styled-components#3519]
## System:
 - OS: Windows 10 10.0.17763
 - CPU: (16) x64 AMD Ryzen 7 3700X 8-Core Processor
 - Memory: 15.30 GB / 31.93 GB
## Binaries:
 - Node: 15.0.0 - C:\Program Files\nodejs\node.EXE
 - npm: 7.0.2 - C:\Program Files\nodejs\npm.CMD
## npmPackages:
 - styled-components: ^5.3.0 => 5.3.0
### Reproduction:
- Add a `-webkit-image-set` styling with multiple sizes and it duplicated the style as shown on the screenshot.

### Code: 
```
const Badge = styled.span`
  background: url(${(props) => props.url}/1);
  background-image: -webkit-image-set(url(${(props) => props.url}/1) 1x, url(${(props) => props.url}/2) 2x, url(${(props) => props.url}/3) 4x);
`
```

![](https://i.imgur.com/QWslbNM.png)

**Comment by probablyup** [comment]
I think this is an issue with `stylis`, specifically version 3. It should be fixed in v6 (which uses stylis v4 and shouldn't have this sort of issue.)
