### ISSUE TITLE
Consider adding a warnings for incorrect tagged template literal usage in development

### ISSUE THREAD

**Issue by cesarandreu** [styled-components/styled-components#352]
I was adding styled-components to an app and global styles weren't showing up. There weren't any errors and it wasn't immediately obvious what I was doing wrong. It turned out I was using `injectGlobal` wrong:

```js
// wrong: calling injectGlobal as a function. oops.
injectGlobal(`html { color: red; }`)

// correct: using a tagged template literal
injectGlobal`html { color: red; }`
```

The first argument of tagged template literals includes a [`raw` property](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#Raw_strings). Adding a check in development to prints out an error when `strings.raw` is missing would help catch this kind of mistake. I'm not sure how frequently this happens, but considering the relative rarity of tagged template literal usage, I figure it wouldn't hurt.

```js
if (process.env.NODE_ENV !== 'production' && !('raw' in strings)) {
  console.error('...')
}
```

**Comment by vdanchenkov** [comment]
I would suggest to check it slightly different way. `injectGlobal` and other helpers expect array in first argument. So, let's check for it.

Something like.
```JS
if (process.env.NODE_ENV !== 'production' && !(Array.isArray(strings))) {
  console.error('...')
}
```

On the other hand, we could support incorrect usage? 
```JS
injectGlobal(`html { color: red; }`) 
// will be equivalent to
injectGlobal([ `html { color: red; }`])
// or 
injectGlobal`html { color: red; }`
```

**Comment by mxstbr** [comment]
This seems reasonable. Whatever we can do to avoid people adding bugs to their apps 👍

**Comment by iamsolankiamit** [comment]
I'll take this one. Just to clarify, we want to allow incorrect usage or show error when incorrectly used?

**Comment by mxstbr** [comment]
Introducing an error now would be a breaking change, so let's just log a warning?

**Comment by beautyfree** [comment]
Is it still open?

**Comment by chengjianhua** [comment]
@maksugr Could you make a PR for your completed commits?

**Comment by maksugr** [comment]
@chengjianhua it is right [here](https://github.com/styled-components/styled-components/pull/1202)

**Comment by probablyup** [comment]
Yup
