### ISSUE TITLE
Breaking rules of hooks in React Native but not ReactJS web

### ISSUE THREAD

**Issue by aVileBroker** [styled-components/styled-components#3520]
In web ReactJS, I can use hooks inside styled-components, but in React Native SC I get a rule of hooks error using the same code. This may be an antipattern or discouraged but if it is I haven't seen anything saying so. If hooks inside styled components aren't encouraged it may be good to at least align RN and React web.

I can put together a codesandbox and expo snack to compare the two if that would help - I'd really like to keep my code looking as close as possible between web and RN.

## Reproduction
Any styled component in React Native which uses hooks inside.

```js
export const ButtonContainer: string & StyledComponentBase<any, {}, ButtonContainerProps> = styled.View`
  ${() => {
    const { colors } = useTheme();

    return `
      border-radius: 8px;
      background-color: ${colors.grayDark};
      ...
```
```js
export function useTheme(): FoundryContextType {
  const theme = useContext(FoundryContext);
  return theme;
}
```

If I remove the `useTheme()` line, it compiles and runs great on RN.

## Expected Behavior
Styled components to compile with hooks in both RN and React web

## Actual Behavior
Styled components gives a rules of hooks failure in React Native

**Comment by probablyup** [comment]
You're using a hook outside of the React rendering flow, which would cause that issue. You can use a simple interpolation to get access to the theme inside of your styles:

```tsx
export const ButtonContainer: string & StyledComponentBase<any, {}, ButtonContainerProps> = styled.View`
  border-radius: 8px;
  background-color: ${p => p.theme.colors.grayDark};
```

**Comment by aVileBroker** [comment]
I understand I can use props (which is what I did as a work around) but this works currently in web styled components. Should by switching to props there as well?

Thanks!

**Comment by probablyup** [comment]
> I understand I can use props (which is what I did as a work around) but hooks work currently in web styled components. Should I be switching to props there as well?
> 
> Thanks!

Yes that would be my recommendation
