### ISSUE TITLE
Next.js 11 issue with styled components

### ISSUE THREAD

**Issue by mike667** [styled-components/styled-components#3522]
1. ## System:
 - OS: macOS 11.4
 - CPU: (8) arm64 Apple M1
 - Memory: 93.88 MB / 8.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
 - Yarn: 1.22.10 - ~/.nvm/versions/node/v15.14.0/bin/yarn
 - npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm

2. ## System:
 - OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
 - CPU: (2) x64 AMD EPYC Processor (with IBPB)
 - Memory: 87.25 MB / 1.89 GB
 - Container: Yes
 - Shell: 5.0.17 - /bin/bash
## Binaries:
 - Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
 - Yarn: 1.22.10 - ~/.nvm/versions/node/v15.14.0/bin/yarn
 - npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm

I as a next js newbie started developing my first app last week. (next.js 11 was released in just a couple of days). As I read styled components works stably with next.js and I decided to use that. The problems started after the development of the 2nd and 3rd pages. The symptoms are very strange, so I will describe all my experiments.

I deployed via docker image - https://nextjs.org/docs/deployment#docker-image

1. I made the first page - everything works well.
2. I added a second page. Everything works fine for me on macos in dev mode and in build / start mode. But when an image is built on ubuntu, the styles are replaced in some elements. I couldn't solve the problem in any way and as a quick solution I moved the application to vercel.app. This solved the problem, but it turned out to be temporary.
3. I added a 3rd page to the site. Then, in general, all the styles were mixed and the elements were not displayed correctly.

Then I already checked that the next.js 11 release was only a few weeks ago and it is not stable, rolled back next.jx to version 10 and everything works well.

I used https://styled-components.com/docs/advanced#nextjs to install.
I also tried adding "styled-componets: ssr" to .babelrc, it doesn't help.
I can't figure out if the problem appears after the amount of css code written or pages generated, that's why it's very strange.

Working example on next.js 10: https://captain-ukraine-frontend-8ack12i0r-erive.vercel.app/
Issue example on next.js 11: https://captain-ukraine-frontend-glhcs4uly-erive.vercel.app/
Pages:
- /casting/  ('кастинг' in menu)
- /casting/1/ ('кастинг' in menu)
- /contacts/ ('трипільська пошта' in menu)

**Comment by MonstraG** [comment]
It seems that your next.js 10 app is build in dev mode, and next.js 11 is in prod

**Comment by joealden** [comment]
@mike667t see https://github.com/vercel/next.js/tree/canary/examples/with-styled-components

**Comment by kitten** [comment]
I think given that we have an issue on Next.js, let's go ahead and close this one. https://github.com/vercel/next.js/issues/26799

As far as I'm aware, setting up styled-components with Next.js hasn't really changed and isn't really "unexpected" given the template that @joealden has posted, which is a Next.js-supported first-party example. If that doesn't work as expected, I'd refer to the Next.js team first and then we can always check whether anything went wrong on our end. But given that nothing has changed on our end, I'd refer to fixes as they come in to Next's `with-styled-components` example.

In general, it actually sounds like something's wrong with the `babel-plugin-styled-components` application, or with duplicate versions of the `styled-components` package. But the description ("the styles are replaced in some elements") isn't really detailed enough for me to tell, and a live site wouldn't be enough to investigate more than the 'symptoms' of the issue

**Comment by theskillwithin** [comment]
it looks like `next-plugin-custom-babel-config` is not longer maintained

**Comment by joealden** [comment]
@theskillwithin next supports a custom babel config out of the box: https://nextjs.org/docs/advanced-features/customizing-babel-config
