### ISSUE TITLE
No auto-complete and theme access with flowjs

### ISSUE THREAD

**Issue by huzaifaaak** [styled-components/styled-components#3526]
## System:
 - OS: macOS 10.15.7
 - CPU: (8) x64 Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz
 - Memory: 1.37 GB / 16.00 GB
 - Shell: 5.7.1 - /bin/zsh
## Binaries:
 - Node: 16.3.0 - /usr/local/bin/node
 - Yarn: 1.22.10 - /usr/local/bin/yarn
 - npm: 7.15.1 - /usr/local/bin/npm
 - Watchman: 2021.06.07.00 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: 5.2.1 => 5.2.1 

## Reproduction

I setup a project with default .flowConfig from [react-native facebook](https://github.com/facebook/react-native/blob/master/.flowconfig). I added up themeProvider from styled-components to top level. 
I created theme and added types to it.

I have also followed the flow types installation from [styled-components website](https://styled-components.com/docs/api#flow) 

```jsx      
      <ThemeProvider theme={myTheme}>
        <NavigationContainer ref={navigationRef}>
           //APP
        </NavigationContainer>
      </ThemeProvider>
````

## Steps to reproduce
I can setup a github repo if requested

## Expected Behavior
It should give style and theme auto-complete when style is imported from 'styled-components/native'

## Actual Behavior
It does not give any auto-complete when imported from 'styled-component/native'

> ![Screenshot 2021-07-02 at 6 58 15 PM](https://user-images.githubusercontent.com/52660166/124285724-a28a0200-db67-11eb-9302-1b590ef1e90e.png)

**Comment by probablyup** [comment]
Thanks for your issue but we don't maintain flow types here. You'll need to open an issue wherever those types come from
