### ISSUE TITLE
[Question] How to pass child node to styled() which receives non-child-accepting function?

### ISSUE THREAD

**Issue by yasuki0707** [styled-components/styled-components#3529]
I'm trying to create a component which contain `FontAwesomeIcon`, followed by text like this:

To do this, I prepared `LabelWithIcon` component
```
type Props = {
	icon: IconDefinition
}
const LabelWithIcon:React.FC<Props> = (props) => {
	const { children, icon } = props
	return (
		<>
			<FontAwesomeIcon icon={icon}/>
			{children}
		</>
	)
}

// call component
<LabelWithIconAtom icon={faCoffee}>how about coffee?</LabelWithIconAtom>
```
This works in a way, but doesn't look good in terms of both UI and source code:
![image](https://user-images.githubusercontent.com/23377394/125024724-520d2a00-e0bc-11eb-9bbe-d3446a1cb76a.png)

I might think there are some ways where this could be achieved, for example using `pseudo-element` to attach icon ahead of text.
So I tried the following way, but in vains:
```
export const LabelWithIcon:React.FC<Props> = (props) => {
	const { children, icon } = props
	return <LabelWithIconStyle>{children}</LabelWithIconStyle>
}

const LabelWithIconStyle = styled(FontAwesomeIcon)`
	&::before {
		font-family: "Font Awesome 5 Free";
		font-weight: 900;
		content: '\\uf0f4'
  	}
`

// call component
<LabelWithIconAtom icon={faCoffee}>how about coffee?</LabelWithIconAtom>
```
This generates an error:
```
No overload matches this call.
  Overload 1 of 2, '(props: Omit<Omit<FontAwesomeIconProps, never> & Partial<Pick<FontAwesomeIconProps, never>>, "theme"> & { ...; } & { ...; }): ReactElement<...>', gave the following error.
    Property 'icon' is missing in type '{ children: ReactNode; }' but required in type 'Omit<Omit<FontAwesomeIconProps, never> & Partial<Pick<FontAwesomeIconProps, never>>, "theme">'.
  Overload 2 of 2, '(props: StyledComponentPropsWithAs<(props: FontAwesomeIconProps) => Element, any, {}, never, (props: FontAwesomeIconProps) => Element, (props: FontAwesomeIconProps) => Element>): ReactElement<...>', gave the following error.
    Property 'icon' is missing in type '{ children: ReactNode; }' but required in type 'Omit<Omit<FontAwesomeIconProps, never> & Partial<Pick<FontAwesomeIconProps, never>>, "theme">'
```

Questions are:
- How to pass children to `FontAwesomeIcon` properly? Is it possible?
- Is There any way to create **LabelWithIcon** component?

Thank you in advance.

**Comment by jnthnk** [comment]
Hi. I think that using the pseudo way is overcomplicated.
How about using the children prop to pass one or more components?
In that way you can pass the text and the icon as children, in the order you want.

**Comment by kitten** [comment]
If you add an icon prop like that you'll also have to make sure that your props match the typings of what that font-awesome package expects. Remember, typings issues aren't just an "error", instead they're compile-time warnings. This means that you'll also have to consider whether the code you have does work in principle, ignoring the TS errors.

In terms of the icon, you can also try to play around with alignment first. If it's an inline block icon, you can see if vertical alignment and some manual positioning can get you where you want.

Also, I have to politely point out that usage questions, and general questions like these will find a better answer on platforms like StackOverflow ✌️
