### ISSUE TITLE
Not installing styled-componnets 

### ISSUE THREAD

**Issue by naxir** [styled-components/styled-components#3530]
While resolving: csnative@0.0.1
npm ERR! Found: react@16.13.1
npm ERR! node_modules/react
npm ERR!   react@"16.13.1" from the root project
npm ERR!   peer react@">= 16.8.0" from styled-components@5.3.0
npm ERR!   node_modules/styled-components
npm ERR!     styled-components@"*" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.2" from react-dom@17.0.2
npm ERR! node_modules/react-dom
npm ERR!   peer react-dom@">= 16.8.0" from styled-components@5.3.0
npm ERR!   node_modules/styled-components
npm ERR!     styled-components@"*" from the root project

  Version Details
 "react-native": "0.64.1",
 "react": "17.0.1",

**Comment by kitten** [comment]
Something about this error message seems really mangled and missing. I'm not quite sure what's going on but if you still need help, consider going to StackOverflow or describing what exactly you're doing in terms of executing commands, the package.json entries you have, and so on.

For instance, I've never seen `csnative`, so if that's your package then something is definitely going wrong there.
