### ISSUE TITLE
Color pick on vscode

### ISSUE THREAD

**Issue by Pedroabreu155** [styled-components/styled-components#3531]
Like when we use sample css on vscode we have a color picker and editor, but when I'm styling components with React and Styled Components this doesn't appear!

I think isn't a bug but this feature will helps a lot some of frontend React developers.

Some months ago I saw and read an issue about this but now I can't find to give my support and comment.

Thanks

**Comment by kitten** [comment]
This isn't related to styled-components, but there is a Viscose plugin for it where you can probably ask about it or search for past issues
