### ISSUE TITLE
Inconsistent CSS ordering in dev vs release when mixing styled-components with SCSS / LESS imports

### ISSUE THREAD

**Issue by olignyf** [styled-components/styled-components#3532]
It might not be a styled-components bug per say but so far I only see the different order with styled-component CSS. My current workaround is to not use styled-components. 

The problem happens when mixing LESS & SCSS styles declarations on styled-components. When building in release mode (yarn build), the result is different than what was seen in dev (yarn start).

People in the past have seen similar issues due to :
- cssnano when using z-index; 
- multiple entry points of css imports;
- styled-components beyond 4.4.1. But in my case downgrading to styled-components 4.4.1 didn't help.

## Steps to reproduce

react 16.13.1
react-scripts 3.4.4
webpack 4.3.3
styled-components 5.2.0
customize-cra 0.9.1

Building with yarn build that executes `yarn lint && react-app-rewired build`

config-overrides.js content: 

```
/* eslint @typescript-eslint/no-var-requires:0 */
const path = require('path');
const {
  override,
  addLessLoader,
  addWebpackAlias,
  overrideDevServer,
  addWebpackResolve,
  addWebpackModuleRule,
  useBabelRc,
  useEslintRc,
} = require('customize-cra');

const devURL = '10.65.11.203'; // ip address of a device for the proxy server';
const proxyObj = {
  target: 'https://' + devURL,
  secure: false,
};

const devServerConfig = () => (config) => {
  return {
    ...config,
    stats: {
      timings: true,
      chunks: false,
      assets: false,
    },
    headers: { 'Access-Control-Allow-Origin': '*' },
    https: false,
    proxy: {
      '/apis': proxyObj,
    },
  };
};

module.exports = {
  webpack: override(
    addLessLoader({
      strictMath: true,
      noIeCompat: true,
      localIdentName: '[local]--[hash:base64:5]',
    }),
    addWebpackAlias({
      ['react']: path.resolve(__dirname, './node_modules/react'),
    }),
    addWebpackResolve({
      extensions: ['.ts', '.tsx', '.jsx', '.mjs', '.js', '.json'],
    }),
    addWebpackModuleRule({
      test: /\.mjs$/,
      type: 'javascript/auto',
    }),
    addWebpackModuleRule({
      test: /\.svg$/,
      loader: 'svg-inline-loader',
    }),
    useBabelRc(),
    useEslintRc(path.resolve(__dirname, '.eslintrc')),
  ),

  jestOldUnusedConfig: (config) => ({
    ...config,
    moduleDirectories: ['node_modules', 'utils'],
  }),

  jest: (config) => {
    config.moduleDirectories = ['node_modules', 'utils'];
    if (!config.testPathIgnorePatterns) {
      config.testPathIgnorePatterns = [
        '/node_modules/',
        'notifications.spec',
      ]; /* notification requires SCSS to load properly to execute, use 'yarn jest' to execute with proper config */
    }
    config.transform = {
      '^.+\\.(js|jsx|mjs|tsx|ts)$': 'babel-jest',
      '^.+\\.svg$': 'jest-transform-file',
      '^.+\\.(css|styl|less|sass|scss)$': 'jest-transform-css',
    };
    return config;
  },
  devServer: overrideDevServer(devServerConfig()),
};
```

I cannot share the project unfortunately.

## Expected Behavior

CSS ordering in DEV vs RELEASE build should be similar / consistent.

## Actual Behavior

Some .less & .scss stylesheets have higher precedence in dev (yarn start), but in release mode (yarn build) the ordering is changed and the styled components take higher precedence, resulting in visual bugs in release that are not seen in development.

**Comment by itayganor** [comment]
I am very curious about the way you mixed up Styled Components and Less. May you please send a link to your reop? (alternatively, an explanation will be just as fine)

**Comment by kitten** [comment]
You should be able to address this by creating a "placeholder style tag", i.e. `<style data-styled></style>`. This tag will be picked up by styled-components' rehydration / initialisation code that creates its target style tag, and will be used to determine the position of the next style tag. I haven't tested this in a while, which means I can't 100% guarantee it still works, but let me know :v:
