### ISSUE TITLE
How check typo errors in styled components?

### ISSUE THREAD

**Issue by MenaiAla** [styled-components/styled-components#3533]
Let's say that I wrote this styled `header`:

```
import styled from "styled-components";

const styledHeader = styled.div`
  background-color: gray;
  width: fit-content;
  padding: 0%2rem;
  display: flex;
  height: fit-content;
`;

export { styledHeader };
```

Why I reload the page (`ctrl+s`), I expect to have a `padding` in the `styledHeader`, but it does not pad because there's a typo error which is : 

```css
padding: 0%2rem;
```

It  should be : 

```css
padding: 0.2rem;
```

Is there a way that let Styled Components prevent the execution until this issue is fixed.

**Comment by kitten** [comment]
If you really need that granularity of checks you could look into using stylelint: https://styled-components.com/docs/tooling#stylelint

This won't typically prevent execution, but it'll make catching errors easier
