### ISSUE TITLE
next.js macro error

### ISSUE THREAD

**Issue by BenXi630** [styled-components/styled-components#3534]
## System:
   - OS: macOS 11.4
   - CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
   - Memory: 3.39 GB / 16.00 GB
   - Shell: 5.8 - /bin/zsh
  ## Binaries:
   - Node: 14.16.1 - /usr/local/bin/node
   - Yarn: 1.22.10 - /usr/local/bin/yarn
   - npm: 6.14.12 - /usr/local/bin/npm
  ## npmPackages:
   - babel-plugin-styled-components: ^1.13.2 => 1.13.2 
   - styled-components: ^5.3.0 => 5.3.0 

## Steps to reproduce
The project uses `next.js`. Introducing `styled-components/macro` into `pages/index.tsx`
## Expected Behavior
```
import styled from 'styled-components'
import 'styled-components/macro'

const Title = styled.h1`
  font-size: 50px;
  color: ${({ theme }) => theme.primaryColor};
`

export default function Home() {
  return (
    <Title>
      My page
      <div
        css={`
          color: red;
        `}
      >
        2312
      </div>
    </Title>
  )
}

```
## Actual Behavior
![image](https://user-images.githubusercontent.com/38492283/125882318-08ac9d83-1bb4-4d7e-9477-9d6c28a4892f.png)

**Comment by kitten** [comment]
Have you actually set up `babel-plugin-macros`? This kind of looks to me like the package itself is being bundled and imported, which happens when the macro isn't being executed in Babel
