### ISSUE TITLE
CodeSandBox Link Inside: SC custom cursor bug in NextJs (work around with css module import -> className)

### ISSUE THREAD

**Issue by Milan-CiudadReal** [styled-components/styled-components#3536]
## Steps to reproduce
Work in NextJs with styled-components. Set a sub 128x128 image as the cursor. I used 64x64 and 32x32 png and svg images to test.
Expected the cursor to be the image given to the cursor css property when the mouse is inside the styled div container.
The custom cursor did not appear, went straight to fallback. 
The work around was to use  the css module import method

## Reproduction
https://codesandbox.io/s/styled-components-cursor-bug-report-vh9vg?file=/pages/index.js

## Environment
Dev Env:
System:
 - OS: macOS 11.2.3
 - CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
 - Memory: 2.57 GB / 32.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 16.1.0 - /usr/local/bin/node
 - npm: 7.12.1 - /usr/local/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.13.2 => 1.13.2 
 - styled-components: ^5.3.0 => 5.3.0

**Comment by kitten** [comment]
you're using a relative import to a file that won't be part of the module graph if it's simply referred to in the CSS template string, hence it won't be resolved 😅 Depending on your next setup you could try just importing/requiring the asset instead of hardcoding a relative path

**Comment by Milan-CiudadReal** [comment]
Hi thanks for the response, I believe I tried that as well `Import Cursor from '../relativePath;` and then in the styled component `cursor: ${Cursor}` but no avail. Is that the method you're suggesting? Apologies, I should have put that attempt in the sandbox.

**Comment by kitten** [comment]
I quickly took a look and forked your sandbox. Your import is creating an object on the default export, which exposes the asset under the `src` property; presumably with other properties for Next's built-in image support, so using an import and then using `.src` does what you expect :v: https://codesandbox.io/s/styled-components-cursor-bug-report-forked-hnjhk?file=/pages/index.js

**Comment by Milan-CiudadReal** [comment]
Ahhhh thank you!
