### ISSUE TITLE
Replace implicit extension behaviour with explicit mechanism

### ISSUE THREAD

**Issue by geelen** [styled-components/styled-components#354]
Right now, when you do a `styled(X)`, there's a bunch of special handling if `X` is a styled component or not. We should standardise it to the following:

`styled(X)` means "render `X` and pass `className` to it"

That means that if you have the following:

```js
const X = styled.div` ... `
const Y = styled(X)` ... `
```

You'd end up with a hierarchy of _both_ `X` and `Y`, rather than what we have now where the rules are merged.

This can be replaced with an explicit `extends` keyword... somehow. TBD.

**Comment by mxstbr** [comment]
This is done in the `v2` branch.
