### ISSUE TITLE
WebStorm warnings about required attributes

### ISSUE THREAD

**Issue by ArthurGoji** [styled-components/styled-components#3540]
## System:
 - OS: macOS 11.5.1
 - CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
 - Memory: 204.53 MB / 16.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 16.4.0 - ~/.nvm/versions/node/v16.4.0/bin/node
 - Yarn: 1.22.10 - ~/.nvm/versions/node/v16.4.0/bin/yarn
 - npm: 7.18.1 - ~/.nvm/versions/node/v16.4.0/bin/npm
 - Watchman: 2021.06.07.00 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^5.3.0 => 5.3.0 

## Reproduction

When I create a Styled component for react-native app that based on another styled component, I'm getting a warning that a lot of attributes are required. In the example they are string methods.

## Steps to reproduce

```
const BaseParagraph = styled.Text`
  font-family: ${({ weight }) => selectFont(weight)};
  color: ${({ theme, color }) => color || theme.colors.white};
`

const Paragraph = styled(BaseParagraph)`
  font-size: ${({ theme }) => theme.typography.paragraph.normal};
  line-height: 20.8px;
`
```

## Expected Behaviour

Clean console

## Actual Behaviour
![Image 2021-07-30 at 2 33 54 PM](https://user-images.githubusercontent.com/51791072/127647403-e9387caa-c54e-4962-b81e-af3728e98b91.jpg)

**Comment by kitten** [comment]
Sorry, I think there may be a Webstorm extension or something somewhere in a different repo, where this could maybe be addressed. But in either case, external tooling issues are unrelated to the main repo and package 😅
