### ISSUE TITLE
shouldForwardProp for Transient Props

### ISSUE THREAD

**Issue by itayganor** [styled-components/styled-components#3541]
I'm facing a not-so-uncommon situation.

Here is a demonstration of what I am trying to achieve (using a much simpler scenario):

```ts

interface ButtonAttrs {
    $isCompact?: boolean;
}

const Button = styled.button<ButtonAttrs>`
    padding: ${p => p.$isCompact ? '0.5em' : '1em'};
`;

const ScaledDownButton = styled(Button).withConfig({
    shouldForwardProp: (prop, defaultValidatorFn) => prop !== '$isCompact' && defaultValidatorFn(prop),
})<ButtonAttrs>`
    font-size: ${p => p.$isCompact ? '0.875em' : '1em'};
`;
```

As the demo shows, each of `Button` and `ScaledDownButton` has its own way of shrinking down the button; the first uses `padding`, and the latter uses `font-size`.

When I render `<ScaledDownButton $isCompact />`, I expect to only affect the `font-size` and not the `padding`. That's what I'm trying to do with the `shouldForwardProp`. But it turns out that transient props never reach the invocation of `shouldForwardProp`:

from [StyledComponent.ts, line 136](https://github.com/styled-components/styled-components/blob/main/packages/styled-components/src/models/StyledComponent.ts#L136):

```ts
  for (const key in computedProps) {
    if (key[0] === '$' || key === 'as') continue;
```

I strongly believe there should be a way to make transient props not pass to a wrapped styled component. It seems like `shouldForwardProp` should be related to making this possible, but I think it was designed for styled-to-html, and not styled-to-styled.

Let me know what you think. Making this possible will enable endless possibilities 😍

**Comment by kitten** [comment]
What's happening here is what we call "folding". As an optimisation, when you call `styled(OtherComponent)`, where the `OtherComponent` is also a styled component, the two are combined into one, which reduces work done on rendering it and inserting its styles. Generally, this also prevents some common mistakes and quirks with specificity, when the library is duplicated.

So in essence, when you use transitive props, both components become one, which means that both sets of rules will see this prop, no matter what the prop is, unless they're separated by another component.

Generally, I'd personally try to avoid this by covering this case with an explicit override, but other than that I unfortunately don't have any immediate other suggestions 😅 But I hope this explanation does clarify the behaviour here
