### ISSUE TITLE
Syled Div with props `cursor` => Warning: Received `true` for a non-boolean attribute `cursor`

### ISSUE THREAD

**Issue by innocentguy** [styled-components/styled-components#3542]
## System:
 - OS: macOS 11.2.3
 - Shell: 3.2.57
## Binaries:
 - Node: 14.16.1 
 - Yarn: 1.22.10 
 - npm: 6.14.12 
## npmPackages:
 - styled-components:  5.3.0 
 - react: 17.0.2

## Reproduction

I defined the component as below
```
const Container = styled.div<{ width: string; height: string; cursor: boolean }>`
  width: ${(props) => props.width};
  height: ${(props) => props.height};
  position: relative;
  cursor: ${(props) => (props.cursor ? 'pointer' : 'inherit')};
`
```
Then call the component in other place
```
<Container
  width={width ?? defaultWidth}
  onClick={onClick}
  height={height ?? defaultHeight}
  cursor={onClick !== undefined}
  className={clsx(classRoot)}
/>
```
I make sure that I had defined the prop `cursor` as boolean, but it shows me the below message
`Warning: Received 'true' for a non-boolean attribute 'cursor'. If you want to write it to the DOM, pass a string instead: cursor="true" or cursor={value.toString()}.`

## Expected Behavior

And the weird part is that once I rename `cursor` to `showCursor` would the warning disappear. 
Ref code.
```
const Container = styled.div<{ width: string; height: string; showCursor: boolean }>`
  width: ${(props) => props.width};
  height: ${(props) => props.height};
  position: relative;
  cursor: ${(props) => (props.showCursor ? 'pointer' : 'inherit')};
`

<Container
  width={width ?? defaultWidth}
  onClick={onClick}
  height={height ?? defaultHeight}
  showCursor={onClick !== undefined}
  className={clsx(classRoot)}
/>
```

**Comment by tu4mo** [comment]
`cursor` is passed to the underlying `div` probably because it's also a valid HTML attribute. You can rename the prop like you did or use [transient props](https://styled-components.com/docs/api#transient-props).

**Comment by innocentguy** [comment]
@tu4mo I guessed so and did the modification for the naming.

This is the reason why I feel the behavior is weird: 
I went through the docs and it shows that `cursor` is a CSS attribute but HTML attribute. So it should not be passed down to the `div` element.

**Comment by tu4mo** [comment]
`cursor` is an attribute for `svg` elements. I don't think styled-components makes a distinction between HTML elements and the attributes they accept.

**Comment by jnthnk** [comment]
I think this might be a bug. Cause actually SC does admit only valid html attributes depending on the html tag.

For example I can't use the type attribute in a div.styled component. This causes the error:

"Property 'type' does not exist on type 'IntrinsicAttributes & Omit<Omit<Pick<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "key" | keyof HTMLAttributes<..."

Cursor is not a valid attribute on divs, so this might be quoted as bug and need attention.

**Comment by tu4mo** [comment]
That sounds like a TypeScript error which is a different issue.

**Comment by jnthnk** [comment]
@tu4mo yes my mistake. A wrong type declaration

**Comment by kitten** [comment]
It's important to understand that the prop forwarding is a heuristic currently. There are some obscure HTML attributes that must be filtered and some that are filtered and shouldn't be (the latter being an issue, while the former is expected)

Overall, we don't differentiate between element types when filtering. It's a heuristic as such to save on bundle size, and currently maintained in a downstream package. The cursor attribute is actually also an obscure HTML attribute, hence why it's probably found its way into the filtering library: https://documentation.help/DHTML-zh/cursor.html

There are several ways around this. Personally, I'd always prefix styling props with `is` or `has` when the prop in question is existing terminology in CSS or HTML. 

However you can also prefix styling props with `$`, which will cause them to never be forwarded
