### ISSUE TITLE
iOS 15 Shadow DOM Speedy doesn't work when class names change

### ISSUE THREAD

**Issue by TLadd** [styled-components/styled-components#3544]
## System:
 - OS: macOS 11.2.3
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
 - Memory: 24.04 MB / 16.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
 - Yarn: 1.22.10 - /usr/local/bin/yarn
 - npm: 7.11.0 - ~/.nvm/versions/node/v14.15.1/bin/npm
 - Watchman: 2021.06.07.00 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: 5.2.3 => 5.2.3
 
 However, the real issue is with the [iOS 15 Beta](https://beta.apple.com/sp/betaprogram/) (Currently latest is beta release 4), which I'm testing using an iPhone SE.

I expect this is likely a bug in Safari rather than styled-components since this works in all other browsers I've tested (including current iOS Safari), but thought there might be some additional insight gained by filing an issue here in terms of how the styles ends up becoming detached. I have filed an issue in their [Feedback Assistant App](https://feedbackassistant.apple.com/) as well

## Reproduction

https://github.com/TLadd/styled-components-shadow-dom-ios15-beta-bug

## Steps to reproduce

Instructions in the README of the repo. To summarize what I'm seeing here, on the iOS 15
beta, an app that renders its styles to a shadow DOM and has SC_DISABLE_SPEEDY set to false (so how it behaves in production by default), any class names that change because of a prop change ends up losing their styles. The new class name is applied to the element but the styles associated with that class name aren't found.

In order to run it, you would need a device opted into the iOS 15 beta, which you can opt into [here](https://beta.apple.com/sp/betaprogram/).

## Expected Behavior

A new style name is generated and the styles are applied as normal.

https://user-images.githubusercontent.com/5084492/128089740-9921d8a2-3e36-43b8-bad1-10ac95b76567.mov

## Actual Behavior

When a new class name is generated, all styled associated with it are lost

https://user-images.githubusercontent.com/5084492/128090352-0cbfb5cc-a0b0-4853-ba6a-30e70ce56581.mp4

https://user-images.githubusercontent.com/5084492/128090375-154e3cf7-f73f-4b04-ad30-62fef01807e9.mov

**Comment by kitten** [comment]
I don't currently have an emulator or iPhone ready on the beta OS to test this out. But, it's probably safe to say this is a WebKit issue if it regressed, so it may be crucial to get a report in with them to prevent this from going out to the stable version, as afaik they don't ship WebKit upgrades outside of iOS upgrades.

**Comment by TLadd** [comment]
I did file an issue using Apple's feedback assistant (https://feedbackassistant.apple.com/feedback/9449844, not publicly viewable unfortunately) the same day this issue was filed. I've now filed an issue on Webkit as well here https://bugs.webkit.org/show_bug.cgi?id=228917.

**Comment by kitten** [comment]
Alright, I'll close this for now. But if the Safari/WebKit teams need anything, let me know and I'll probably be able to assist

**Comment by TLadd** [comment]
Just as a heads up, https://bugs.webkit.org/show_bug.cgi?id=228917 was fixed a few weeks ago but as of right now, the latest release candidate of iOS 15 still exhibits the broken behavior, so that version of webkit doesn't seem to have made it upstream. So I think it is likely that the bug will go out September 20 when iOS 15 is released to the general public. The workaround for the time being is to set `REACT_APP_SC_DISABLE_SPEEDY="true"`.
