### ISSUE TITLE
Getting several instances of 'styled-components' error when setting up project

### ISSUE THREAD

**Issue by areim3r** [styled-components/styled-components#3546]
System:

- OS: macOS Catalina 10.15.3
- CPU: 2.9 GHz Quad-Core Intel Core i7
- Memory: 16 GB 2133 MHz LPDDR3
- Shell: /bin/zsh

Binaries:

- Node: 12.3.1
- NPM: 6.9.0

NPM Packages:

- babel-plugin-styled-components: ^1.13.2
- styled-components: ^5.3.0

### Steps taken

I am setting up a basic application and getting the "several instances" warning in my console. I've followed the [recommended steps here](https://styled-components.com/docs/faqs#why-am-i-getting-a-warning-about-several-instances-of-module-on-the-page) but have had no luck resolving it.

Running `npm ls styled-components` returns
```
styled-components@5.3.0
```

I don't see any duplicates in webpack bundle analyzer, and adding "resolutions" to package.json had no effect either. Any idea what should be done in this case?

I have an [example repo here](https://github.com/areim3r/super-website). Thanks for any help!

**Comment by tu4mo** [comment]
Remove `<script defer src="app.js"></script>` from index.html. HtmlWebpackPlugin takes care of it. It's now appearing twice in your `dist/index.html`.

**Comment by areim3r** [comment]
@tu4mo  🤦 I had a feeling I was missing something obvious thanks for pointing that out!
