### ISSUE TITLE
Styled components not working on browser reload (next js dev mode)

### ISSUE THREAD

**Issue by tiagodinis33** [styled-components/styled-components#3556]
## Environment

```
## System:
 - OS: Linux 5.4 Ubuntu 20.04.2 LTS (Focal Fossa)
 - CPU: (16) x64 Intel(R) Xeon(R) CPU
 - Memory: 18.46 GB / 62.81 GB
 - Container: Yes
 - Shell: 5.0.17 - /bin/bash
## Binaries:
 - Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
 - Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.3/bin/yarn
 - npm: 6.14.13 - ~/.nvm/versions/node/v14.17.3/bin/npm
## npmPackages:
 - styled-components: ^5.3.0 => 5.3.0 
```

## Reproduction

https://github.com/PaTzMC/site/commit/6a284ffd86e1e4b7d706dd3a4347a94bffb158eb

## Steps to reproduce
Reload page
## Expected Behavior
Load the page with the styles
## Actual Behavior
When i reload the page it doesnt load the styled-components styles and just start working again if i change something in the files

**Comment by kitten** [comment]
It's likely related to a small rule that `stylis@3` cannot parse. I didn't take a longer look, but maybe try to narrow this down to the affected selector and see what ultimately breaks it. The upgrade to `stylis@4` may fix this though once it's dropped into styled-components.

**Comment by tiagodinis33** [comment]
its breaking in my Card component

**Comment by kitten** [comment]
I just took a look at the file structure and I believe you may have skipped some setup steps that are necessary for server-side rendering to work and load styles. If you take a look here, you can find a full example of setting up styled-components with Next.js: https://github.com/vercel/next.js/tree/canary/examples/with-styled-components
