### ISSUE TITLE
esm output can't works in browser

### ISSUE THREAD

**Issue by oMaten** [styled-components/styled-components#3560]
## Environment
I using `styled-components/dist/styled-components.browser.esm.js` in browser via import-map with `jspm` solution.
The exception message from `styled-components` is `Uncaught ReferenceError: process is not defined sandbox:1:1651`

I review the source code from esm output and the judging of `process` existing some problems. It always throw error without `process.env`
```js
"boolean" == typeof SC_DISABLE_SPEEDY
  ? SC_DISABLE_SPEEDY
  : "undefined" != typeof process &&
    void 0 !== process.env.REACT_APP_SC_DISABLE_SPEEDY &&
    "" !== process.env.REACT_APP_SC_DISABLE_SPEEDY
  ? "false" !== process.env.REACT_APP_SC_DISABLE_SPEEDY &&
    process.env.REACT_APP_SC_DISABLE_SPEEDY
  : "undefined" != typeof process &&
    void 0 !== process.env.SC_DISABLE_SPEEDY &&
    "" !== process.env.SC_DISABLE_SPEEDY
  ? "false" !== process.env.SC_DISABLE_SPEEDY && process.env.SC_DISABLE_SPEEDY
  : "production" !== process.env.NODE_ENV;

```

## Reproduction

Try this sandbox demo https://jspm.org/sandbox#H4sIAAAAAAAAA5VWW3faOBB+z69QvS/tFvlCS0II5JAmabZp2TShpEnfhD3E4siWa4kA6el/37FssxiIT/oAtjXffHOTZtR9FUhfLxMgoY7E8V63fAALjvcI6UagGfFDlirQPWumJ7RtGYHmWsDxKDbPoOvk3yuVmEXQsx45zBOZaov4MtYQI8WcBzrsBfDIfaDmo0F4zDVngiqfCeh5aKDr5B50xzJYGtZXlOKDkMvh1wG5gBhSpmVKPkUZPxmwxEjPA67J6OZLB+PRieo4zkMJtacqiWwunb9Gzdvw/uIsPGu76XL4dDkceeHn8+Tfb6etxeDs293g8OTpevaP/LG4vdv/wG5P9J1Ipp9Gwrs+/Qgqar31v7euQLSS0eiqNf15AerH4PJ61GpeR1c3Dx+a9/cnX75O3Ojjwwl6RakJQPkpTzTJkt2zuHE7YolJ5i/je7GorE6xgEspMF/jgrUKh63iiJOoY+R978B27aaDSbV5HMACIVajQuFM1YKmM6xWBH9Ct6ZWIVV6iVWnvkSXY6yrqiHdwvZb9jvbdQKutLMltMepnCtIbUx0xaRWgo9rzBh5v4nUnmPekWE/YzAEv3MeS/kygUqKd9CtiRHQh0hqLmOHK5qkMqGPTPCgxpPdCn3XbtvtPOqKYBWxP1XrEa+bjvCFP9WVbhOK5g7s97m5YuklhrJ68LpqbiBNVK3/a8nVS6zM4qxbqBfZKbEmoMJSuVZjK5QIpLGMqdnUVGmmuV9n8RmN/jvcUs3c7jOQHebleAoIYErxh7jGaAXXf297uHu3zvDLG0EbT65LmUhCRiHY991DbwK06TY998D1dneIkp3W1r2E9L1928vO2HNcKmRCyDn8nDFR1xXWYH2MGhvCiq0g+92oOaN1naV6fv8ouB2dtPRmr/zPfl0n7+dZ+y7GEzkfkoEMZgLIMOSR6pTDCdu8IokUywkXgkxwakUGpkixfRWZcx3KmSZ8TUPNEvPxGhNFYOEDTo/TMJURkPbh2zcbc4WpZewTlfq954IERXO7VGXu4Xnymlkds429IbMjHmehH2+GWRliuYaZYKT0/G90hJh0kgm6Wm7co92YS7W4yafLOroyrLY186qfropeqG6PpG1VMxcKfD5PjvLACHEc8j3lGjD3PC4KhLeWAG9GkEKDYNWQgBEFCcP7BDrMEZDVDRctzLtFmNYpH89QJmOiQyhZ8qTZxgzeg5QUYAv58NoE29jMRGMrwEbu95ujyr7rOvndCK9K5s72H+69N8zLCQAA

## Steps to reproduce
Open the link above

## Expected Behavior
No exception happened

## Actual Behavior
`Uncaught ReferenceError: process is not defined sandbox:1:1651`

**Comment by oMaten** [comment]
For avoiding the problem, I try to define global `process` in browser like `window.process = { env: { NODE_ENV: 'production' } }`.
But another error happened 
```
// https://ga.jspm.io/npm:styled-components@5.3.0/dist/styled-components.browser.esm.js?%20[sm]:formatted:468
Uncaught TypeError: C is not a constructor
```
Looking for reply

**Comment by mzvast** [comment]
You could use this source instead~

```
"styled-components": "https://ga.jspm.io/npm:styled-components@5.3.0/dist/dev.styled-components.browser.cjs.js"
```

**Comment by missing1984** [comment]
Should we reopen this? switch to use cjs is a workaround, the issue is still there.  esm build should probably remove `process.env` entirely.
