### ISSUE TITLE
Styles lost when passing `as` prop to SC extending React component that renders another SC

### ISSUE THREAD

**Issue by mrseanbaines** [styled-components/styled-components#3562]
I have a styled component...

```js
const Text = styled.p`
  font-family: cursive;
  font-size: 20px;
  text-decoration: underline;
`
```

...which is rendered in a React component...

```js
const TextComponent = ({ children, ...props }) => {
  return <Text {...props}>{children}</Text>
}
```

...which is extended by another styled component (spreading props to pass the `className`)...

```js
const RedText = styled(TextComponent)`
  color: red;
`
```

...which is then rendered and passed an `as` prop.

```js
<RedText as="h1">I'm a red h1 but lose my initial styles</RedText>
```

All of the original styles from the `Text` styled component are lost, but the `as` prop works and the extended styles are kept.

I realise that I'm _supposed_ to use the `forwardedAs` prop, rather than the `as` prop in this case, but I don't think passing an `as` prop should be losing all of the original styles(?). I'm not sure if the `as` props is even meant to work in this case, but somehow it does (even if I explicitly don't pass it along in the `TextComponent` React component).

This was an issue for me because I needed to refactor an existing styled component to be wrapped by a React component, and everything seemed okay at first, but then every now and then I started seeing styles being off in various places, and it took a lot of debugging to work out that the cause was due to passing an `as` prop instead of a `forwardedAs` prop.

## Environment
codesandbox

## Reproduction
https://codesandbox.io/s/heuristic-forest-3epo2?file=/src/App.js

## Steps to reproduce
Create a styled component with some styles, a React component that renders it, another styled component that extends that, and then render that and pass it an `as` prop.

## Expected Behavior
The styles in the first styled component remain, regardless of whether or not the `as` prop works (I think it's not supposed to work)

## Actual Behavior
The styles in the first styled component get lost and the `as` prop works

**Comment by kitten** [comment]
`as` replaces whatever is in `styled(X)`. It replaces the target, so if that's your component then it won't be mounted any longer

**Comment by mrseanbaines** [comment]
@kitten shouldn't it then also lose the styles if I extend the original styled component (instead of the React component) in that case? This seems to still work:

```js
const Text = styled.p`
  font-family: cursive;
  font-size: 20px;
  text-decoration: underline;
`

const RedText = styled(Text)`
  color: red;
`

<RedText as="h1">I'm a red h1 and keep my initial styles</RedText>
```

**Comment by kitten** [comment]
Not quite; in the case of "nesting" `StyledComponent`s all styles cascade and are combined. If you look at the render output you can see that the original component disappears and instead the wrapper composes its styles and combines them with the inner's styles

**Comment by mrseanbaines** [comment]
@emilioheinz I think the answer is to use `forwardedAs` instead of `as`

**Comment by emilioheinz** [comment]
Yess, I have tried it and it works fine. Just forgot to mention here. Thanks!
