### ISSUE TITLE
Styles added twice to browser with SSR

### ISSUE THREAD

**Issue by minisemi** [styled-components/styled-components#3578]
## System:
 - OS: macOS 11.1
 - CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
 - Memory: 305.83 MB / 16.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 15.14.0 - /usr/local/bin/node
 - Yarn: 1.22.10 - /usr/local/bin/yarn
 - npm: 7.7.6 - /usr/local/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^1.13.2 => 1.13.2 
 - styled-components: ^4.4.1 => 4.4.1

## Steps to reproduce

I am server rendering React on a Rails server with react_on_rails. The styles are managed with styled-components and works, but it seems the styles are added twice to the browser in my development environment. So I'm just wondering if this is intended by styled-components, or if I'm doing something wrong?

```
const sheet = new ServerStyleSheet()

const AppServer = (props, railsContext) => {
	const location = useLocation()
	const context = {}

	const markup = renderToString(
		<StyleSheetManager sheet={sheet.instance}>
			<App {...props} railsContext={railsContext}>
				<StaticRouter location={location} context={context}>
					<AppStructure {...props} />
				</StaticRouter>
			</App>
		</StyleSheetManager>,
	)
	const css = sheet.getStyleTags()

	return {
		renderedHtml: {
			componentHtml: markup,
			componentCss: css,
		},
	}
}
```

```
const AppClient = (props, railsContext) => {
	return () => (
		<App {...props} railsContext={railsContext}>
			<BrowserRouter>
				<AppStructure {...props} />
			</BrowserRouter>
		</App>
	)
}
```

The ThemeProvider wrapping AppStructure:
```
<ThemeProvider theme={theme}>
			<GlobalFonts />
			<GlobalStyle />
			<>{props.children}</>
		</ThemeProvider>
```

```
const GlobalStyle = createGlobalStyle`
  html {
    box-sizing: border-box;
  }
`
```

## Expected Behavior
![image](https://user-images.githubusercontent.com/4705200/132708550-785bab9f-cf39-402e-9f78-54159044682d.png)

## Actual Behavior
![image](https://user-images.githubusercontent.com/4705200/132706872-20713002-9619-4747-8969-d14963965476.png)

**Comment by fsrodrig** [comment]
I'm experiencing a similar issue while using themes. We have light/dark themes and when we switch, styles are being duplicated in the browser.

Env:
"styled-components": "^5.3.0"
"next": "11.1.0",
node v12.18.0 (npm v6.14.4)

![image](https://user-images.githubusercontent.com/22208107/133628781-0ac806fb-4d42-4f34-9079-637f87d60942.png)

![image](https://user-images.githubusercontent.com/22208107/133628848-f096826d-05c5-422f-87af-f8a66491d6fe.png)

**Comment by kitten** [comment]
It's likely related to you using an older version together with React StrictMode or something of the sort. Either way, I don't think I can accept any issues for v4 anymore especially given that with global styles these kinds of issues are more likely to occur and aren't showstoppers.

@fsrodrig That's completely unrelated and expected behaviour. Styles are additive

**Comment by minisemi** [comment]
I was running v5.3.1, but since I was getting the issues with global styles described [here](https://github.com/styled-components/styled-components/pull/3551#issuecomment-915929171), I needed to downgrade to v4.4.1.

My styles are still being added twice in v5.3.1 however. It seems the style coming from `en:80` in the image below is from the server-side generated styles, which are put in `<style data-styled="true" data-styled-version="5.3.1">` (as seen in the image further below). The duplicate style coming from `<style>` instead of `en:80`, comes from  `<style data-styled="active" data-styled-version="5.3.1">` instead which is generated on client side. So it seems Styled components, when rendering on the client, doesn't find the server side rendered `<style data-styled="true" data-styled-version="5.3.1">` to hydrate it, and instead creates this new `<style data-styled="active" data-styled-version="5.3.1">`.

![image](https://user-images.githubusercontent.com/4705200/133887938-3952a747-7eef-4f06-bfb3-eff7ba79ece8.png)


![image](https://user-images.githubusercontent.com/4705200/133887778-dddbbc4e-8172-41dc-bf78-777db8a2864a.png)

Not sure why it doesn't find it? It might not be a showstopper as you say, but the duplicate stylesheets can lead to bugs and make the <head> unnecessary long.

**Comment by damiangreen** [comment]
Still not working on 5.3.1

**Comment by justintemps** [comment]
Still have two style tags on next.js with styled-components 5.3.3

**Comment by thetw** [comment]
I can also confirm that this bug still exists with Next.js 12.0.10 and styled-components 5.3.3.

```html
<head>
    ...
    <style data-styled="active" data-styled-version="5.3.3"></style>
    <style data-styled="active" data-styled-version="5.3.3"></style>
    ...
</head>

**Comment by duveborg** [comment]
did anyone find a workaround? i have the same issue with next 12.1 and SC 5.3.3
