### ISSUE TITLE
Silent Typo?

### ISSUE THREAD

**Issue by tshinnic** [styled-components/styled-components#358]
Merely reading the code I noticed in [src/models/ThemeProvider.js](https://github.com/styled-components/styled-components/blob/23faf605d18470469b3348a89ffeac70a758283f/src/models/ThemeProvider.js#L15-L61) three mentions of 'outherTheme', alongside the many mentions of 'outerTheme'.  Since I'm not using the package I can't tell if this could ever be a significant typo. (might be just annotations for Flow?) But... that's what reading code is for, noticing possible erasable future glitches?

**Comment by k15a** [comment]
These are just flow annotations. But I think we could rename them to outerTheme to be correct.

**Comment by mxstbr** [comment]
PR welcome!
