### ISSUE TITLE
Prop Naming Issues in Styled-Components for React-Native, on Android Devices

### ISSUE THREAD

**Issue by MomoRazor** [styled-components/styled-components#3580]
## System:
 - OS: Linux 5.11 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
 - CPU: (4) x64 Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz
 - Memory: 13.42 GB / 31.29 GB
 - Container: Yes
 - Shell: 5.1.4 - /bin/bash
## Binaries:
 - Node: 16.9.0 - /usr/local/bin/node
 - Yarn: 1.22.5 - /usr/local/bin/yarn
 - npm: 7.21.1 - /usr/local/bin/npm
## npmPackages:
 - styled-components: ^5.3.1 => 5.3.1 

## Reproduction

Unsure if I can produce a reproduction, since it only seems to happen when the project is run on an Android device. 

## Steps to reproduce

- Simply create a styled-components of a View (the react-native core component) and pass it a prop named 'padding'. 
- Pass a value for the new padding prop.

## Expected Behavior

Allowing the name 'padding' as a prop, since I'm not extending any other interface which uses 'padding' already. If this not technically possible, maybe a better error that can allow for quicker debugging of this issue.

## Actual Behavior
The error 'Error while updating property 'padding' in shadow node of type: RCTView' will pop up.

Unsure if this is legitimiately a bug or not, but after having spent quite alot of time debugging, and finding evidence of this issue on the react-native project (https://github.com/facebook/react-native/issues/21002#issuecomment-789410539), I thought it would be a good idea to also place here in case investigation needs to happen from the side of styled-components. 

According to the comment linked above, this only happens on real android devices, something I can attest to, however having only tested on a real android device, I was not aware of the specificity of the problem.

 Will try to prepare a reproduction if required and apologies if this is misplaced.

**Comment by kitten** [comment]
This is likely happening because the prop is still being accepted as a deprecated legacy prop in the `View` component. However, it's likely that it's non-functional on iOS, as it's supposed to be, but half-broken on Android.

There's not really anything we can fix here as far as I know. However, on your end, make sure that you don't use props that overlap with styling names or with already existing prop names in Recat Native.
