### ISSUE TITLE
[Bug] Wrong regEx validation in fontFamily function of css-to-react-native

### ISSUE THREAD

**Issue by pedpess** [styled-components/styled-components#3581]
## System:
 - OS: macOS 11.5.2
 - CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
 - Memory: 828.52 MB / 32.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 12.13.0 - ~/.nvm/versions/node/v12.13.0/bin/node
 - Yarn: 1.22.10 - ~/.nvm/versions/node/v12.13.0/bin/yarn
 - npm: 6.12.0 - ~/.nvm/versions/node/v12.13.0/bin/npm
 - Watchman: 4.9.0 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^5.2.0 => 5.2.0 

## Reproduction
There seems to be an issue in the lib `css-to-react-native` that comes together with styled components. Specifically in `index.js` file and `fontFamily()` function. I have a font family that contains the special characters `+` plus sign in between letters. The problematic font family being **OctoberH+L-Black**, so the lib doesn't seem to parse it correctly.

Looking at `var identRe = (^-?[_a-z][_a-z0-9-]*$)` I changed to a valid regEx of `(^-?[_a-zA-Z][A-Z_a-z0-9+-]*$)` and that worked for me. You can also confirm that by using https://regex101.com/

Please let me know if this is the defacto solution, if it's, then I'm happy to open a PR to address that :)

## Expected Behavior
The app would display the correct font-family without crashing

## Actual Behavior
The app crashes with the error `Failed to parse declaration "fontFamily: OctoberH+L-Black"` that's invoked by `transformShortAndValue()` function.

**Comment by kitten** [comment]
I think you're already hinting at this being an issue in css-to-react-native, so I'm sure this may be safe to close in this repo. You could just move it over there if you'd like? https://github.com/styled-components/css-to-react-native

That said, it'd be great if you had a reproduction for them, like a failing unit test, a minimal usage example that fails, or some other summary that lets us and them see where the issue may be.

**Comment by pedpess** [comment]
Thanks for the guidance. I have just opened the new issue in the correct repo for the time travellers check it out :)

https://github.com/styled-components/css-to-react-native/issues/165
