### ISSUE TITLE
I can't run jest with styled-compoents in React Native

### ISSUE THREAD

**Issue by AilsonFreire** [styled-components/styled-components#3585]
## System:
 - OS: macOS 11.5.2
 - CPU: (8) arm64 Apple M1
 - Memory: 159.98 MB / 8.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 15.9.0 - ~/.nvm/versions/node/v15.9.0/bin/node
 - Yarn: 1.22.10 - ~/.nvm/versions/node/v15.9.0/bin/yarn
 - npm: 7.5.3 - ~/.nvm/versions/node/v15.9.0/bin/npm
 - Watchman: 4.9.0 - /opt/homebrew/bin/watchman
## npmPackages:
 - styled-components: ^5.3.1 => 5.3.1 
 
- When I run `yarn jest` i get this error:
<img width="663" alt="Captura de Tela 2021-09-19 às 11 19 45" src="https://user-images.githubusercontent.com/9551815/133931139-8836ba46-8ae5-4dfc-8cc2-311ec42c1553.png">

//test-utils.tsx
<img width="586" alt="Captura de Tela 2021-09-19 às 11 26 15" src="https://user-images.githubusercontent.com/9551815/133931205-bcfd4adb-81a2-437e-b00e-a18f77cbe84c.png">

//package.json

<img width="454" alt="Captura de Tela 2021-09-19 às 11 28 20" src="https://user-images.githubusercontent.com/9551815/133931286-9eef5d0c-f6b8-4e99-b686-8037775730d4.png">

//jest-config
<img width="529" alt="Captura de Tela 2021-09-19 às 11 29 16" src="https://user-images.githubusercontent.com/9551815/133931312-fc597b02-d871-4a94-bfef-af7f39290a7c.png">

//tsconfig.json
<img width="289" alt="Captura de Tela 2021-09-19 às 11 30 27" src="https://user-images.githubusercontent.com/9551815/133931333-534c4f0b-0ae8-4c43-8370-2b99b48ee71b.png">

**Comment by Sharcoux** [comment]
You can try [rn-css](https://www.npmjs.com/package/rn-css). It is designed for usage with React-Native, so maybe you'll get more luck with it. Your can just replace `styled-components` by `rn-css` within your code and it should be working.

**Comment by AilsonFreire** [comment]
Resolved by myself in [here](https://github.com/styled-components/jest-styled-components/issues/105#issuecomment-931239681)
