### ISSUE TITLE
End-to-end testing

### ISSUE THREAD

**Issue by geelen** [styled-components/styled-components#36]
We need some verification of our human-facing API. Basically, that

``` js
const X = styled.div`
  some: rule;
`
export default () => <X/>
```

renders the exact HTML and CSS we want. Things I'd like to be able to verify using this:
- [x] that multiple components' CSS gets injected in the correct order regardless of which order they're rendered in
- [x] that using function callbacks with a series of params gives us the result we want
- [x] that two components with the same CSS generates only one copy of CSS injected into the document
- [x] that JS style comments don't break the parser, in fact are potentially even detected and warned about
- [x] That `global` works and injects as we expect it to

Heaps more, too, but this is a start.

**Comment by geelen** [comment]
Also:

[] - That theme works as we expect (need nested components for this?)
[] - That components actually get the class names we're expecting!
[] - That native works

**Comment by bhough** [comment]
@geelen @mxstbr working on these additional tests (already merged global) What did you have in mind for Native?

**Comment by mxstbr** [comment]
We need to verify that `StyledNativeComponent` and `InlineSyles.js` do the same thing as `StyledComponent` and `ComponentStyles.js` for DOM, essentially! Would be awesome if you could look into that, but let's close this issue and track it in #94
