### ISSUE TITLE
Web components does not derive css from styled-components instance

### ISSUE THREAD

**Issue by surfer19** [styled-components/styled-components#3617]
## Reproduction
```
// does not work
const Description = (props: any) => (
    <custom-web-component {...props}></custom-web-component>
);
export const Description = styled(Description)`
  line-height: 18px;
`;
```

## Expected Behavior
Web component element should derive css defined in "styled``" block 

## Actual Behavior
`line-height` attribute does not apply on root of custom web component by default.

Is there any way how to do this please? I couldnt find anything in the docs either.

Thank you!!

**Comment by surfer19** [comment]
the only way how to make it work  in less clear way is:
```
export const Description = styled.span`
  custom-web-component {
    line-height: 18px;
 }
`;
      <Description>
        <custom-web-component >
        ...
        </custom-web-component >
      </Description>
```

**Comment by kitten** [comment]
Duplicate of #3179
