### ISSUE TITLE
Best practice to share components style for web and native

### ISSUE THREAD

**Issue by robbue** [styled-components/styled-components#362]
Hi there!

I am trying out styled-components for the first time and want to figure out how to share the styles for web and RN. Only the styles, not the components, at least not at this time (unless anyone have a good way for it).

Any suggestions of how to do this better?  #(https://github.com/styled-components/styled-components/issues/315) did not give my any answers

**Web**
```JSX
import styled from 'styled-components';
import styles from 'styles.js';

const Wrapper = styled.section`${styles.wrapper}`;
```

**React Native**
```JSX
import styled from 'styled-components/native';
import styles from 'styles.js';

const Wrapper = styled.View`${styles.wrapper}`;
```

**styles.js (shared for web and RN)**
```JS
const styles = {
  wrapper: {
    background-color: red;
  }
};

export default styles;
```

**Comment by robbue** [comment]
I see now that styled-components is supposed to be collocated, but what is the best way to share code for web and native?

**Comment by mxstbr** [comment]
```JS
import { css } from 'styled-components'

const wrapperStyles = css`
 background-color: red;
`
```

```JS
const Wrapper = styled.View`
  ${wrapperStyles}
`
```

```JS
const Wrapper = styled.div`
  ${wrapperStyles}
`
```

**Comment by robbue** [comment]
Thanks for answering, @mxstbr :)

That look like it will do the job, but not only am I wondering about the technical stuff, but best practice to create universal app. I'm starting on a new project with a almost identical web and native, and I want to get it right from the beginning so updating and changing the app on both platforms in the future will be easy :)

**Comment by brunolemos** [comment]
> #(#315) did not give me any answers

@robbue have you tried the [react-native-web](https://github.com/necolas/react-native-web) project?

**Comment by robbue** [comment]
@brunolemos I have not tried it, but definitely something I should look further into. Only concern is that it may not be a 1:1 solution(?) or that web and native will be so different in logic that the only thing to share is the styles. But for now this is what what I ended on (for future reference):

**styles.js**
```javascript
import { css } from 'styled-components'

// normalize function to give unitless dimensions in RN and px/rem on web
import { normalize } from '../../shared/helpers/commonFunctions' 

// env as a static variable (probably a better solution for this)
import settings from '../../settings' 

const styles = css`
  width: ${normalize(100)};
  height: ${normalize(100)};
  ${(settings.env === 'web') ? 'background: red;' : 'background: blue;'}
`

export default styles
```

**index.js**
```javascript
import styled from 'styled-components'
import styles from './styles'

export default Box = styled.div`${styles}`
```

**index.native.js (RN platform file extensions)**
```javascript
import styled from 'styled-components/native'
import styles from './styles'

export default Box = styled.View`${styles}`
```

**Comment by mxstbr** [comment]
We've announced an experimental release of `styled-components/primitives` which makes truly universal components possible.

Read the announcement blog post to learn more, I'll close this issue for now since it's resolved!  https://medium.com/styled-components/announcing-primitives-support-for-truly-universal-component-systems-5772c7d14bc7

**Comment by dennishansen** [comment]
Can we re-open this issue for support of react-native-web? Works for me by installing react-native-web and then wrapping react-native components with `styled(Text)`, however, it looks like all of my props are going straight to the DOM node, causing warnings like 

> React does not recognize the `propName` prop on a DOM element.

Anyway, great progress so far!

**Comment by tastafur** [comment]
react-primitives, is not the same as react-native-web, stylecomponents primitives is compatible with react-native-web? I do not see anywhere documentation documentation should be created so that people know how to use it.

a greeting

**Comment by dennishansen** [comment]
I agree this should be more clear in the documentation. Wrapping RNW components (aliased as RN components be default) with `styled()` does work, but there arise issues with prop whitelisting not working properly, which causes many props to be forwarded to the DOM. This has caused is all sorts of issues. Using a styled-system approach and especially [clean-tag](https://github.com/jxnblk/styled-system/tree/master/clean-tag) has fixed this and made our universal repo much more productive.

**Comment by tonycaputome** [comment]
> @brunolemos I have not tried it, but definitely something I should look further into. Only concern is that it may not be a 1:1 solution(?) or that web and native will be so different in logic that the only thing to share is the styles. But for now this is what what I ended on (for future reference):
> 
> **styles.js**
> 
> ```js
> import { css } from 'styled-components'
> 
> // normalize function to give unitless dimensions in RN and px/rem on web
> import { normalize } from '../../shared/helpers/commonFunctions' 
> 
> // env as a static variable (probably a better solution for this)
> import settings from '../../settings' 
> 
> const styles = css`
>   width: ${normalize(100)};
>   height: ${normalize(100)};
>   ${(settings.env === 'web') ? 'background: red;' : 'background: blue;'}
> `
> 
> export default styles
> ```
> 
> **index.js**
> 
> ```js
> import styled from 'styled-components'
> import styles from './styles'
> 
> export default Box = styled.div`${styles}`
> ```
> 
> **index.native.js (RN platform file extensions)**
> 
> ```js
> import styled from 'styled-components/native'
> import styles from './styles'
> 
> export default Box = styled.View`${styles}`
> ```
Awesome solution.
