### ISSUE TITLE
attributes not override by props

### ISSUE THREAD

**Issue by Karbone4** [styled-components/styled-components#3626]
## System:
 - OS: macOS 11.5
 - CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
 - Memory: 1.16 GB / 16.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 16.11.0 - /usr/local/bin/node
 - Yarn: 1.22.15 - ~/Documents/code/node_modules/.bin/yarn
 - npm: 8.0.0 - /usr/local/bin/npm
 - Watchman: 2021.10.11.00 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^5.3.3 => 5.3.3

## Reproduction

(only works for ios / android because it uses react native views)
https://snack.expo.dev/@karbone4/attrs-not-override-by-props

In this example, overriding style props works, but overriding contentContainerStyle props doesn't work.

`ScrollViewCustom3` should render the same as `ScrollViewCustom1` and `ScrollViewCustom2`

## Steps to reproduce

Style attributes of a view using styled-components and override / add new style through props

## Expected Behavior

Props should override / be added to styled-components's attributes

## Actual Behavior

Props are not override / added to styled-components's attributes

**Comment by AndriiHnedko** [comment]
It worked in your example.

```
const ScrollViewCustom3 = styled(ScrollView).attrs((props) => ({
  contentContainerStyle: [
    { padding: 40 },
    props.contentContainerStyle,
  ],
}))`
  flex: 1;
`;

/* even it works */
const ScrollViewCustom3 = styled(ScrollView).attrs((props) => ({
  contentContainerStyle:[
    [{ padding: 40 }, [[{marginTop: 80}]]],
    props.contentContainerStyle
  ],
}))`
  flex: 1;
`;
```

**Comment by Karbone4** [comment]
It works, thank you ! I didn't know that we can use arrays in styled components
