### ISSUE TITLE
gap property not working (React Native)

### ISSUE THREAD

**Issue by erisvaldojunior** [styled-components/styled-components#3628]
If I want to set a specific space between items on a flex container, I still need to set individual margin and/or padding to all children instead of simple using the new gap property on the flex container.

Something like this should work (center all MyFlexContainer children and set 10px between each):

```javascript
import { View } from 'react-native';
import styled from 'styled-components/native';

const MyFlexContainer = styled.View`
  flex-direction: column;
  justify-content: center;
  flex: 1;
  gap: 10px;
`
```

**Comment by wallid** [comment]
I have the same problem

**Comment by mlecoq** [comment]
We need this first

https://github.com/facebook/yoga/issues/812

**Comment by Dibendu-Saha** [comment]
I don't think 'gap' is a valid flex property in react native. I went thru the documentation – didn't find one.

**Comment by conor909** [comment]
I think this should be a feature request on the react-native StyleSheet

**Comment by Aakash-mistry** [comment]
Another hack on this is the following
     <View
        style={{
          display: 'flex',
          flexDirection: 'row',
          padding: 10,
          marginTop: 50,
        }}>
        <View style={{elevation: 5, padding: 10, flex: 1, marginRight: 10}}>
          <Text>1</Text>
        </View>
        <View style={{elevation: 5, padding: 10, flex: 1, marginLeft: 10}}>
          <Text>1</Text>
        </View>
      </View>

you can use this technique

**Comment by nandorojo** [comment]
Sadly there is no gap support yet for React Native.

**Comment by BishalSaha** [comment]
> Sadly there is no gap support yet for React Native.

Make it

**Comment by maxibenner** [comment]
Here is what I have been doing to simulate gaps. I basically create a margin on the children and then negate the margin with a negative padding on the parent. The only margin that remains is the one between the children.

```
const Component = () => {
  return (
    <View style={styles.container}>
      <View style={styles.child}></View>
      <View style={styles.child}></View>
    </View>
  );
};

// Gap you want to achieve
const gap = 8;

const styles = StyleSheet.create({
  container: {
    flexDirection: "row",
    paddingHorizontal: (gap / -2),
  },
  child: {
    marginHorizontal: gap / 2,
  },
});
```

**Comment by nandorojo** [comment]
Weird comments aside, I can share what I use for this. It has an imperfection though.

This is the API:

```tsx
<Gap gap={1}>
  <Child />
  <Child />
</Gap>
```

It also supports fragments:


```tsx
<Gap gap={1}>
  <>
    {active && <Child />}
    <Child />
  </>
</Gap>
```

You can also use a divider component:

```tsx
<Gap divider={<View />}>
  <Child />
  <Child />
</Gap>
```

Here is the code:

```tsx
import flattenChildren from 'react-keyed-flatten-children'
import { View, ViewStyle } from 'react-native'
import { Children } from 'react'

type Props = {
  gap?: number
  direction?: 'vertical' | 'horizontal'
  style?: ViewStyle
  flex?: number
  divider?: React.ReactNode
}

export function Gap({
  gap = 4,
  direction = 'vertical',
  style,
  flex =  direction == 'horizontal' ? 1 : undefined,
  divider
}) {
  const kids = flattenChildren(children)
  const { theme } = useDripsyTheme()
  const flexDirection = direction == 'vertical' ? 'column' : 'row'

  const styleKey = direction == 'vertical' ? 'height' : 'width'

  return (
    <View style={[{ flexDirection }, style]}>
      {Children.map(kids, (child, index) => {
        return (
          <>
            {index > 0
              ? divider || <View style={{ [styleKey]: gap }} />
              : null}
            <View style={{ flex }}>{child}</View>
          </>
        )
      })}
    </View>
  )
}
```

The only downside of this code is that, if the child component returns `null`, it will still add a gap. This is a limitation of React's top-down approach.

**Comment by SteffanEnnis** [comment]
+1 for implementing the gap attribute. Putting styles on each child component is not all that maintainable

**Comment by nandorojo** [comment]
> +1 for implementing the gap attribute. Putting styles on each child component is not all that maintainable 

Again, React Native doesn't support flex gap.

The right place to follow this is here: https://github.com/facebook/yoga/issues/812

**Comment by Hmoulvad** [comment]
I've updated the component above to make it more reuseable.
`
import React, { Children, memo, ReactNode, useState } from 'react';
import { StyleSheet, View } from 'react-native';
import { Metrics } from '~/app/models/Metrics';

type Props = {
  gap: number;
  itemPerRow: number;
  children: ReactNode;
  childrenAreSquared?: boolean;
};

export const Grid = memo(({ gap = Metrics.SmallNumber, itemPerRow, children, childrenAreSquared }: Props) => {
  const [containerWidth, setContainerWidth] = useState(0);
  const totalGapSize = itemPerRow * gap;
  const childWidth = (containerWidth - totalGapSize) / itemPerRow;
  const childHeight = childWidth;

  const Styles = StyleSheet.create({
    Container: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginHorizontal: -(gap / 2),
      marginVertical: -(gap / 2),
    },
    Child: {
      ...(childrenAreSquared && { height: childHeight }),
      marginHorizontal: gap / 2,
      marginVertical: gap / 2,
      width: childWidth,
    },
  });

  return (
    <View style={Styles.Container} onLayout={e => setContainerWidth(e.nativeEvent.layout.width)}>
      {Children.map(children, (child, index) => (
        <View key={index} style={Styles.Child}>
          {child}
        </View>
      ))}
    </View>
  );
});

`

**Comment by Hmoulvad** [comment]
Update the component above a bit. So it is more reusable.

```
import React, { Children, memo, ReactNode, useState } from 'react';
import { StyleSheet, View } from 'react-native';
import { Metrics } from '~/app/models/Metrics';

type Props = {
  gap: number;
  itemPerRow: number;
  children: ReactNode;
  childrenAreSquared?: boolean;
};

export const Grid = memo(({ gap = Metrics.SmallNumber, itemPerRow, children, childrenAreSquared }: Props) => {
  const [containerWidth, setContainerWidth] = useState(0);
  const totalGapSize = itemPerRow * gap;
  const childWidth = (containerWidth - totalGapSize) / itemPerRow;
  const childHeight = childWidth;

  const Styles = StyleSheet.create({
    Container: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginHorizontal: -(gap / 2),
      marginVertical: -(gap / 2),
    },
    Child: {
      ...(childrenAreSquared && { height: childHeight }),
      marginHorizontal: gap / 2,
      marginVertical: gap / 2,
      width: childWidth,
    },
  });

  return (
    <View style={Styles.Container} onLayout={e => setContainerWidth(e.nativeEvent.layout.width)}>
      {Children.map(children, (child, index) => (
        <View key={index} style={Styles.Child}>
          {child}
        </View>
      ))}
    </View>
  );
});

```

**Comment by jadshep** [comment]
Here's my approach (not thoroughly tested or super optimized).

Features:
- `null`s don't add extra gaps
- Supports `gapRow` and `gapCol` individually, falling back to `gap` if not set, falling back to `0` if none are set

Caveats:
- Gaps are added around fragments, even if they don't have any children
- `gapRow` always adds spacing to left and right, while `gapCol` always adds to top and bottom
  - This is different from CSS, which adds `row-gap` parallel to the flex direction, and `col-gap` perpendicular to the flex direction
  - This can easily be made to conform to CSS by conditionally swapping the row and col values based on the flex direction, though I personally prefer it as is

```
import React from 'react';
import { FlexStyle, StyleProp, View, ViewStyle } from 'react-native';

interface Props extends React.ComponentProps<typeof View> {
    flexDirection?: FlexStyle['flexDirection'];
    flexWrap?: FlexStyle['flexWrap'];
    alignItems?: FlexStyle['alignItems'];
    justifyContent?: FlexStyle['justifyContent'];

    gap?: number;
    gapRow?: number;
    gapCol?: number;

    contentWrapperStyle?: StyleProp<ViewStyle>;
}

export function GapContainer(props: React.PropsWithChildren<Props>) {
    const {
        flexDirection: propsFlexDirection,
        flexWrap: propsFlexWrap,
        alignItems: propsAlignItems,
        justifyContent: propsJustifyContent,

        gap: propsGap,
        gapRow: propsRow,
        gapCol: propsCol,

        contentWrapperStyle: propsContentWrapperStyle,

        ...passthroughProps
    } = props;

    const gap = propsGap ?? 0;
    const gapRow = propsRow ?? gap;
    const gapCol = propsCol ?? gap;

    const contentWrapperStyle: StyleProp<ViewStyle> = [propsContentWrapperStyle, {
        flexDirection: propsFlexDirection,
        flexWrap: propsFlexWrap,
        alignItems: propsAlignItems,
        justifyContent: propsJustifyContent,

        marginHorizontal: -gapRow / 2,
        marginVertical: -gapCol / 2,
    }];

    const childStyle: StyleProp<ViewStyle> = {
        marginHorizontal: gapRow / 2,
        marginVertical: gapCol / 2,
    };

    function renderChild(child: React.ReactNode) {
        if (child === null) {
            return null;
        }

        return (
            <View
                children={ child }
                style={ childStyle }
            />
        );
    }

    return (
        <View { ...passthroughProps }>
            <View style={ contentWrapperStyle }>
                { React.Children.map(props.children, renderChild) }
            </View>
        </View>
    );
}
```

**Comment by jadshep** [comment]
@Hmoulvad Semi-unrelated, but `memo()` is generally a bad idea for components that take children, as children will change for most/all renders in most situations.

**Comment by iway1** [comment]
Hey guys, whatever you do to solve this don’t use negative margins or padding. The behavior is undefined on android and will break on certain devices.

**Comment by iway1** [comment]
@nandorojo you can do a .filter on the children to filter out the nulls to fix the issue

**Comment by nandorojo** [comment]
that doesn't solve the problem if one of the child components returns `null`, since you're not evaluating a component's return type when looping over it

**Comment by timurcatakli** [comment]
Why not simply use a view? What am I missing? Similar to:
`            <View
              style={{
                height: 40,
              }}
            />
`

**Comment by jadshep** [comment]
@iway1 
> Hey guys, whatever you do to solve this don’t use negative margins or padding. The behavior is undefined on android and will break on certain devices. It’s troubling all of the most liked answers suggest this.
> 
> I’ve had it break the layouts of production apps before, it’ll happen to you too. Make sure your margins and padding are always greater than or equal to zero

Negative padding is disallowed in RN and CSS, but margin should be fine.

[The docs](https://reactnative.dev/docs/layout-props) just defer to Mozilla for [margin](https://developer.mozilla.org/en-US/docs/Web/CSS/margin) and [padding](https://developer.mozilla.org/en-US/docs/Web/CSS/padding).

Mozilla's docs for margin say:
> Negative values draw the element closer to its neighbors than it would be by default.

while the ones for padding say:
> Negative values are invalid.

Maybe RN treats it differently, but I couldn't find that in the docs, and I've used negative margins a fair amount on an app with an install base of ~30K without any issues popping up relating to this.

Though, I wouldn't be surprised if RN does yet another thing weird, so I am curious about this. Do you have an example of negative margins breaking things?

**Comment by TheEhsanSarshar** [comment]
I personally use a Gap component

``` js
export function Gap({ size, direction = 'horizontal' }: Props) {
  return <View style={{ [direction === 'horizontal' ? 'width' : 'height']: size }} />;
}
```

**Comment by timurcatakli** [comment]
```
import { Dimensions } from "react-native";

const { width, height } = Dimensions.get("window");

const guidelineBaseWidth = 375;
const guidelineBaseHeight = 812;
const horizontalScale = (size: number) => (width / guidelineBaseWidth) * size;
const verticalScale = (size: number) => (height / guidelineBaseHeight) * size;
const moderateScale = (size: number, factor = 0.5) =>
  size + (horizontalScale(size) - size) * factor;

export { horizontalScale, verticalScale, moderateScale };
```
`<Gap gap={verticalScale(config.vSpace1 / 2)} />`

This is my method...

**Comment by BATMAH69** [comment]
> We need this first
> 
> [facebook/yoga#1116](https://github.com/facebook/yoga/pull/1116)

it is completed now

**Comment by erisvaldojunior** [comment]
It's already on React Native. When will it be exposed through styled-components?

**Comment by atrombet** [comment]
Can confirm that the gap property is working in React Native 0.71
https://reactnative.dev/docs/layout-props#gap

I used the upgrade helper (for my app it was 0.70.6 -> 0.71) here
https://react-native-community.github.io/upgrade-helper/?from=0.70.6&to=0.71.0

**Comment by erisvaldojunior** [comment]
I confirm gap support is working well with styled-components after upgrading to RN 0.71!

**Comment by amresh-singh-qbs** [comment]
you have to pass gap in number format. Avoid using of px,rem, or any unit
`const MyFlexContainer = styled.View
  flex-direction: column;
  justify-content: center;
  flex: 1;
  gap: 10;
`

**Comment by Nagibaba** [comment]
`row-gap` works
