### ISSUE TITLE
Sorry to open this issue

### ISSUE THREAD

**Issue by CaptainJon** [styled-components/styled-components#3639]
First I'd like to apologize for openning this issue cause this is atually not an issue with style-components.

I have been using style-components in all my react-apps. However, recently with the recent release of vscode 1.63, the css folding function doesn't work anymore while using style-components, I know this is not a problem with style-components, I just want to know what folding extention do you guys use . I usually use "CSS-IN-JS FOLD" extention in vscode, but it doesn't work anymore after the updating of vscode.  I already posted an issue under the "CSS-IN-JS FOLD" community, it seems the author have been long gone without updating that libary. And vscode has claimed they have nothing to do with this problem.

If this post bothers the author, plz close it for your convenience.

**Comment by agriffis** [comment]
@CaptainJon Maybe ask on the chat? https://discord.gg/hfGUrbrxaU

**Comment by ola-dola** [comment]
For @CaptainJon  and others reading this:

The popular extension for syntax highlighting, code folding and others moved to a new account.

Install here: https://marketplace.visualstudio.com/items?itemName=styled-components.vscode-styled-components

**Comment by CaptainJon** [comment]
> For @CaptainJon and others reading this:
> 
> The popular extension for syntax highlighting, code folding and others moved to the official styled-components account on VScode marketplace.
> 
> Install here: https://marketplace.visualstudio.com/items?itemName=styled-components.vscode-styled-components

thx, that helps me a lot
