### ISSUE TITLE
display names no longer generated in babel-plugin-styled-components v2+using macro import

### ISSUE THREAD

**Issue by esetnik** [styled-components/styled-components#3645]
When upgrading npm or yarn package lock dependencies, babel-plugin-styled-components@2.0.2 is installed. But babel-plugin-styled-components doesn't generate `displayNames` after version `1.13.3`. 

And it looks like styled-components takes a dependency on babel-plugin-styled-components>=1.12.0 which resolves to 2.0.2.
<img width="2878" alt="Screen Shot 2021-12-16 at 12 30 55 PM" src="https://user-images.githubusercontent.com/664434/146421473-f33c2151-b3ca-495d-a0fa-b8c679fe1d1a.png">
<img width="2879" alt="Screen Shot 2021-12-16 at 12 31 20 PM" src="https://user-images.githubusercontent.com/664434/146421479-4d5926a5-6ed9-46c5-b335-843061ef2bc9.png">

## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`
```
## System:
 - OS: macOS 12.1
 - CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
 - Memory: 5.66 GB / 48.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
 - Yarn: 1.22.17 - ~/.nvm/versions/node/v16.13.1/bin/yarn
 - npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
## npmPackages:
 - styled-components: 5.3.3 => 5.3.3
 ```
## Reproduction
Reproducible in codesandbox below and in screenshots above

https://codesandbox.io/s/styled-components-base-forked-e7x8k?file=/index.js

## Steps to reproduce
Take a direct dependency or indirect dependency on babel-plugin-styled-components@2 or greater. Use a macro import e.g.

```
import styled from 'styled-components/macro;
```

## Expected Behavior

displayName should work whether v1.13.3 or v2+ of babel-plugin-styled-components is used with macro.

## Actual Behavior

displayName doesn't work after v2

**Comment by gbarkhatov** [comment]
Any updates on this? Latest CRA seems not displaying names after update to 5.0.0

**Comment by rockwotj** [comment]
Hey all I dug into the code here, and the options changed in V2, so this code: https://github.com/styled-components/styled-components/blob/e932038fffa1400c4ca68d04010b7d3f319298cb/packages/styled-components/src/macro/index.ts#L41 no longer works. The parameter name there needs to be renamed and support regex

**Comment by rockwotj** [comment]
The correct fix for macro users is to pin to v1 for now

**Comment by probablyup** [comment]
I fixed the macro recently in bpsc v2, let me know if this is still an issue

**Comment by davidcostadev** [comment]
It's working for me
