### ISSUE TITLE
Cannot resolve react-is

### ISSUE THREAD

**Issue by romain130492** [styled-components/styled-components#3650]
## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`

* `"styled-components": "^5.2.0"`
* Mac environment
* using reactJs

* `Cannot resolve react-is in dist`

## Reproduction

https://codesandbox.io/s/styled-components-base-gc367

## Steps to reproduce
* install ` "styled-components": "^5.2.0"` on a mac
* run start

<img width="1044" alt="Screen Shot 2021-12-22 at 12 18 41 PM" src="https://user-images.githubusercontent.com/57079606/147035052-c5323990-52f8-4616-94dd-2b0be06a7cbe.png">

**Comment by haneenmahd** [comment]
Try doing a clean install.
Just run this script
```sh
rm -rf node_modules
rm -rf package-lock.json # choose yarn.lock if you are using yarn
npm install
```

**Comment by agriffis** [comment]
@romain130492 Your provided codesandbox seems to work fine?
