### ISSUE TITLE
Intellisense Issue

### ISSUE THREAD

**Issue by kaushalmarakana** [styled-components/styled-components#3669]
Hello

I am facing intellisense issue with styled-components and typescript.

Description:

Let's see first working example. If I do something like this 

// component
export const FlexView = styled.div<FlexViewProps>(
   ( {width} )=> `width: ${width}px`;
);

// parent call
<FlexView width={200} /> // this is giving me auto suggestion (intellisense) of width prop.

Not let me describe **issue** with other approach.

// component
export const CustomRow = styled(Row)<RowProps>(
   ( {width} )=> `width: ${width}px`;
);

// parent call
<CustomRow width={200} /> // this is not giving me auto suggestion (intellisense) of width prop.

One solution [(Solution Link)](https://github.com/styled-components/styled-components/issues/630#issuecomment-462907177) I found is that 
export const CustomRow = styled(Row)<RowProps>(
   ( {width} )=> `width: ${width}px`;
) as React.FunctionComponent<RowProps>;

The above solution is working, but I don't think it is good way to fix this.

Can anyone please let me know the solution for this?

**Comment by kitten** [comment]
Sorry, I'll have to close this, since it's not an issue report, but a question / usage question, and not related to `styled-components` but to your editor setup and/or other setup issues.

Feel free to instead send this question into our Discord: https://discord.com/invite/hfGUrbrxaU
Or onto StackOverflow instead

**Comment by kaushalmarakana** [comment]
Okay, Thanks for your response. I will ask this in discord group.
