### ISSUE TITLE
#310 breaks innerRef when used like styled(MyStyledComponent)

### ISSUE THREAD

**Issue by IljaDaderko** [styled-components/styled-components#367]
I believe #310 broke innerRef, as a lot of components now return undefined for the refs.

Example:

```
const StyledInput = styled.input`background: red`;
const Input = ({ ...otherProps }) => (
  <StyledInput {...otherProps} />
);
```

And using it in other file

```
import Input from '../components/Input';
const StyledInput = styled(Input)`background: blue`;

class InputGroup extends Component {
  render() {
    return (
      <div>
        <StyledInput innerRef={input => this.input1 = input} />
        <StyledInput innerRef={input => this.input2 = input} />
      </div>
    )
  }
}  
```

After the update `this.input1` and `this.input2` are undefined. Where as previously they returned input elements.

**Comment by mxstbr** [comment]
Yep, I totally messed that up by not catching it. We should only delete the `innerRef` if it's a HTML Element, if it's a component we have to pass it on.

Would you mind submitting a PR fixing this? Good catch!

**Comment by IljaDaderko** [comment]
@mxstbr could do a PR, just to confirm, check for this within `/src/models/StyledNativeComponent.js` is `isStyledNativeComponent && !isTag(target)` ?

**Comment by IljaDaderko** [comment]
Hope that those are correct checks, let me know if they need updating
