### ISSUE TITLE
Element visually loses font when I interact with unrelated element (Example 2)

### ISSUE THREAD

**Issue by gmoniava** [styled-components/styled-components#3679]
## Environment

React: 17
Styled-components: 5.3.3

## Reproduction

[Demo](https://codesandbox.io/s/strange-orla-xm7lz?file=/src/Test.js).

1. You can see initially "Header" text has "Fraunces" font 
2. Inside `Test `component, uncomment `font-weight`:

```
let SectionLink = styled.a`
  font-weight: 700;
`;
```
3. Refresh. Now you will see the "Header" text from parent component visually lost "Fraunces" font. Why?

## Expected Behavior

I suppose the "Fraunces" should not disappear visually from "Header" text, when I interact with other element.

**Comment by kitten** [comment]
It's unfortunately not possible to add `@import` statements for external CSS files to random StyledComponent definitions. It also wouldn't scale that well

You can try to add it using a `createGlobalStyle` component, but you're better off just using a regular `link` tag for external CSS files.

The reason for this is that `@import` statements need to be arlt the top of style sheets. As other rules get added to your app, it may end up not being at the top anymore, which breaks your styles

**Comment by gmoniava** [comment]
@kitten is there some link to docs on best practice for importing fonts?

Reason I don't want link tag in this case, is following. I have demo project, which contains different components (say component A and B). Now, for component A, I want to have different fonts. For, component B different fonts. What is the way to go in such case?

My App.js always renders either A, or B component, never both.
