### ISSUE TITLE
Elements inside styled components are re-created on every render

### ISSUE THREAD

**Issue by saschagehlich** [styled-components/styled-components#369]
We're creating an application that uses a <canvas> element to render graphics through the whole lifetime of our application. It seems that every time a styled component is re-rendered, all child elements are re-created, which makes us lose the content.

## Version
1.2.1

## Reproduction
http://www.webpackbin.com/4kcEIM1LM

## Steps to reproduce
Open the website, see a blue rectangle on a red canvas. Wait for one second (component re-renders), blue rectangle is gone.

## Expected Behavior
Canvas element should not be re-created but instead re-used

## Actual Behavior
Canvas element is re-created, releasing all content

**Comment by vdanchenkov** [comment]
Kind of duplicate of #143, you are creating a new component on every render.

**Comment by saschagehlich** [comment]
Now that you say it, it totally makes sense - thanks for pointing this out. This is definitely something that should be in the README.

**Comment by vdanchenkov** [comment]
It's not a big problem for now, but in v2 every component will have its own id and class based on id, so given example would make stylesheet grow indefinitely on every render. 

Should we think of a way to detect this kind of misuse in runtime? @mxstbr

**Comment by mxstbr** [comment]
I'm not sure there's no valid reasons for having a styled-component being created on every render to be honest. Can't think of anything right now though...

**Comment by geelen** [comment]
Yeah I'd be reluctant to prohibit it, I think just seeing more examples (like the Egghead videos I'm working on) where the styled components live outside the Component that uses them will help a lot.
