### ISSUE TITLE
styled-components v6 alpha feedback

### ISSUE THREAD

**Issue by probablyup** [styled-components/styled-components#3696]
Use `alpha` tag in npm: `yarn add styled-components@alpha`

Example sandbox: https://codesandbox.io/s/styled-components-v6-alpha-sandbox-05bod1?file=/src/App.tsx

If you run into any bugs, please post reproductions and keep related discourse in this thread, thanks!

**Comment by binhpv** [comment]
Hey @probablyup , I wonder where is the TypeScript typing? I installed the alpha but didn't find it in the package, though it's mentioned that typing is included in this release :D

Thanks!

**Comment by probablyup** [comment]
> Hey @probablyup , I wonder where is the TypeScript typing? I installed the alpha but didn't find it in the package, though it's mentioned that typing is included in this release :D
> 
> 
> 
> Thanks!

Oh weird, will look into that today thanks for flagging!

**Comment by probablyup** [comment]
@binhpv should be fixed here, thanks: https://github.com/styled-components/styled-components/releases/tag/v6.0.0-alpha.1

**Comment by binhpv** [comment]
@probablyup  Thanks! I believe the "types" field is needed as well in package.json, since the index.d.ts is not at the root level.
Ref: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package

**Comment by probablyup** [comment]
Oh weird, I thought it autodetected those...

**Comment by probablyup** [comment]
Just published 6.0.0-alpha.2 with the added "types" fields thank you!

**Comment by probablyup** [comment]
Updated OP with a code sandbox

**Comment by kostiantyn-ccm** [comment]
```
declare module 'styled-components/native' {
  interface DefaultTheme extends Styles.Theme {}
}
```
Theme types are not working with React Native =(

**Comment by kostiantyn-ccm** [comment]
```
import styled, { css } from 'styled-components/native';

export const Test = styled.View(
  ({ theme }) =>
    css`
      color: ${theme.color.white};
    `
);
```
Such construction is not working any more

```
<html>TS2345: Argument of type '({ theme }: ExecutionContext &amp; ViewProps) =&gt; TemplateStringsArray | (Interpolation&lt;ExecutionContext | ViewProps&gt; &amp; { ...; })' is not assignable to parameter of type 'Styles&lt;ViewProps&gt;'.<br/>Type '({ theme }: ExecutionContext &amp; ViewProps) =&gt; TemplateStringsArray | (Interpolation&lt;ExecutionContext | ViewProps&gt; &amp; { ...; })' is not assignable to type 'StyleFunction&lt;ViewProps&gt;'.<br/>Type 'TemplateStringsArray | (Interpolation&lt;ExecutionContext | ViewProps&gt; &amp; { isCss?: boolean; })' is not assignable to type 'string | number | StyledObject | StyleFunction&lt;ViewProps&gt; | CSSConstructor&lt;ViewProps&gt;'.<br/>Type 'TemplateStringsArray' is not assignable to type 'string | number | StyledObject | StyleFunction&lt;ViewProps&gt; | CSSConstructor&lt;ViewProps&gt;'.<br/>Type 'TemplateStringsArray' is not assignable to type 'StyledObject'.<br/>Index signature for type 'string' is missing in type 'TemplateStringsArray'.
```

**Comment by probablyup** [comment]
Thank you! Will add this to my list along with looking into the React native issues

**Comment by kostiantyn-ccm** [comment]
The quick solution in styled-components.d.ts
```
import { Interpolation, Styles, CSSProp } from 'styled-components/native/dist/types';

declare module 'styled-components/native/dist/types' {
  interface DefaultTheme extends Styles.Theme {}
}

declare module 'styled-components/native' {
  function css<Props>(
    styles: Styles<Props>,
    ...interpolations: Interpolation<Props>[]
  ): Interpolation<CSSProp>[] & string;
}
```

**Comment by probablyup** [comment]
Oh right, I guess for native it would be declare module 'styled-components/native' since it's a different import

**Comment by esetnik** [comment]
> ```
> import styled, { css, ThemeProvider } from "styled-components/macro";
> import Theme from "./theme";
> 
> const Container = styled.div`
>   ${({ theme }) =>
>     css`
>       color: ${theme.primary};
>     `}
> `;
> ```
> 
> Such construction {using css``} is not working with typescript anymore https://codesandbox.io/s/styled-components-v6-alpha-sandbox-forked-dnxedn?file=/src/App.tsx
> 
> (parameter) theme: DefaultTheme Argument of type '({ theme }: ExecutionContext & ClassAttributes & HTMLAttributes) => TemplateStringsArray | (Interpolation<...> & { ...; })' is not assignable to parameter of type 'Interpolation<ClassAttributes & HTMLAttributes>'. Type '({ theme }: ExecutionContext & ClassAttributes & HTMLAttributes) => TemplateStringsArray | (Interpolation<...> & { ...; })' is missing the following properties from type 'IStyledComponent<any, any>': $$typeof, componentStyle, foldedComponentIds, target, and 3 more.ts(2345)

Has anyone found a solution for this issue which is still present in v6.0.0-alpha.5?

**Comment by The-Code-Monkey** [comment]
I think that the DefaultTheme object needs an optional generic adding to it, as i have a load of custom defaultStyles in my theme object and im sure other people would need the ability to add an extra prop or two that dont exist in the defaulttheme

**Comment by The-Code-Monkey** [comment]
> > ```
> > import styled, { css, ThemeProvider } from "styled-components/macro";
> > import Theme from "./theme";
> > 
> > const Container = styled.div`
> >   ${({ theme }) =>
> >     css`
> >       color: ${theme.primary};
> >     `}
> > `;
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Such construction {using css``} is not working with typescript anymore https://codesandbox.io/s/styled-components-v6-alpha-sandbox-forked-dnxedn?file=/src/App.tsx
> > (parameter) theme: DefaultTheme Argument of type '({ theme }: ExecutionContext & ClassAttributes & HTMLAttributes) => TemplateStringsArray | (Interpolation<...> & { ...; })' is not assignable to parameter of type 'Interpolation<ClassAttributes & HTMLAttributes>'. Type '({ theme }: ExecutionContext & ClassAttributes & HTMLAttributes) => TemplateStringsArray | (Interpolation<...> & { ...; })' is missing the following properties from type 'IStyledComponent<any, any>': $$typeof, componentStyle, foldedComponentIds, target, and 3 more.ts(2345)
> 
> Has anyone found a solution for this issue which is still present in v6.0.0-alpha.5?

Nope not currently i think it might just be the types that are off does //@ts-ignore work?

**Comment by The-Code-Monkey** [comment]
Another issue i have on my mono repo is after updating to the alpha release is that my tests no longer run.

they just sit there 

```
 RUNS  src/atoms/button/__test__/index.test.tsx
 RUNS  src/atoms/checkbox/__test__/index.test.tsx
 RUNS  src/atoms/grid/__test__/index.test.tsx
 RUNS  src/primatives/icon/__test__/index.test.tsx
 RUNS  src/atoms/table/__test__/index.test.tsx
 RUNS  src/atoms/input/__test__/index.test.tsx
 RUNS  src/atoms/divider/__test__/index.test.tsx

Test Suites: 0 of 7 total
Tests:       0 total
Snapshots:   0 total
Time:        168 s^C%      
```

**Comment by sirganya** [comment]
I'm trying to solve the `Component is not a styled component and cannot be referred to via component selector.` error.

With this code
```typescript
const StyledColorBox = styled.div<{
    value: any;
}>`
  background-color: ${(props) => props.value};
`;

const ColorBox = ({
    parentName,
    childName,
}: {
    parentName: keyof GetFilter_getFilter;
    childName: FilterElementChildTypes | undefined;
}): JSX.Element => {
    const value = values[childName];
    const colorBox = <StyledColorBox value={value} />;
    if (parentName === "colors") {
       // Argument of type 'Element' is not assignable to parameter of type 'WebTarget'
        return styled(colorBox)``
    }
    return <></>;
};
```

I get the TS error `Argument of type 'Element' is not assignable to parameter of type 'WebTarget'` with `styled(colorBox)`

**Comment by kylemh** [comment]
I'm extremely excited for this release.

I wanted to take a moment to suggest a drastic change since this is already a breaking change.

Specifically, that `styled-components` should only export one module: `createStyledComponentsConfig`. This would be very similar to what [Stitches](https://stitches.dev/) and [Vanilla Extract](https://vanilla-extract.style/) do. There are multiple benefits:

You can have multiple different themes with different keys and multiple theme providers, and NOT lose out on type safety. Today, and with [how v6 is shaping out](https://github.com/styled-components/styled-components/releases/tag/v6.0.0-alpha.4), it's not possible without some extra work. VS Code (and other editors that rely on a TSConfig) can potentially resolve different type definitions, but only in different folders, so if you have 2 theme providers in the same spot (lets say to support... federated modules with webpack module federation or to support multiple micro front-ends with different themes) you can't have typesafety for both of them. The simple fix is to _name_ your themes when you add types for them _and_ when you pass them to the ThemeProvider.

It also means you wouldn't need to [maintain this part of the documentation anymore](https://styled-components.com/docs/api#create-a-declarations-file). Setup would be easier because types simply come free of charge with your defined theme.

I'm not sure if this is desired, but it also means `styled-components` could start to do more opinionated things when people define their theme, like encourage adoption of the [SystemUI spec](https://system-ui.com/) via the theme type. I say encourage, because it can be optional and people can add whatever keys they want or ignore it completely.

This can also remove the need for `useTheme`. People can simply import the correct theme as the key of the exported object returned by the function. It's a portable object.

**Comment by popuguytheparrot** [comment]
On ts 4.7.2
ERROR in ./node_modules/styled-components/dist/styled-components.browser.esm.js 
export '__spreadArray' (imported as 'e') was not found in 'tslib'

**Comment by Newbie012** [comment]
It looks like there's a type issue with the following syntax:

```ts
const Container = styled.div`
  color: ${(p) => p.theme.primary};

  ${(props) => {
    if (props["as"] === "section") {
      return css`
        background-color: green;
      `;
    }

    return css``;
  }}
`;
```

```
Argument of type '(props: ExecutionContext & ClassAttributes<HTMLDivElement> & HTMLAttributes<HTMLDivElement>) => TemplateStringsArray | (Interpolation<...> & { ...; })' is not assignable to parameter of type 'Interpolation<ClassAttributes<HTMLDivElement> & HTMLAttributes<HTMLDivElement>>'.
  Type '(props: ExecutionContext & ClassAttributes<HTMLDivElement> & HTMLAttributes<HTMLDivElement>) => TemplateStringsArray | (Interpolation<...> & { ...; })' is missing the following properties from type 'IStyledComponent<any, any>': $$typeof, componentStyle, foldedComponentIds, target, and 3 more.ts(2345)
```

But in runtime, it seems to be ok, just like previous versions. Her'es a [reproduction](https://codesandbox.io/s/styled-components-v6-alpha-sandbox-forked-t03qvm?file=/src/App.tsx)

**Comment by steve-taylor** [comment]
> Error on build or dev of nextjs@12
> 
> ```
> Build error occurred
> TypeError: external_styled_components_.div is not a function
> at Object.8689 (/Users/iv0706/code/TechStack/platforms/react-cms/.next/server/chunks/529.js:829:58)
> at __webpack_require__ (/Users/iv0706/code/TechStack/platforms/react-cms/.next/server/webpack-runtime.js:25:42)
> at Object.7712 (/Users/iv0706/code/TechStack/platforms/react-cms/.next/server/pages/[table].js:22:11)
> at __webpack_require__ (/Users/iv0706/code/TechStack/platforms/react-cms/.next/server/webpack-runtime.js:25:42)
> at __webpack_exec__ (/Users/iv0706/code/TechStack/platforms/react-cms/.next/server/pages/[table].js:124:39)
> at /Users/iv0706/code/TechStack/platforms/react-cms/.next/server/pages/[table].js:125:66
> at Function.__webpack_require__.X (/Users/iv0706/code/TechStack/platforms/react-cms/.next/server/webpack-runtime.js:220:21)
> at /Users/iv0706/code/TechStack/platforms/react-cms/.next/server/pages/[table].js:125:47
> at Object.<anonymous> (/Users/iv0706/code/TechStack/platforms/react-cms/.next/server/pages/[table].js:128:3)
> at Module._compile (node:internal/modules/cjs/loader:1103:14) {
> type: 'TypeError'
> }
> ```
> 
> im not sure on how to fix this?

@The-Code-Monkey I'm getting the exact same issue with Next.js 12.2 and Styled Components 5.3.5 in my monorepo. `external_styled_components_` is the entire module instead of the default export.

**Comment by probablyup** [comment]
@Newbie012 just pushed a new alpha build that should hopefully fix the type issue you were seeing

**Comment by The-Code-Monkey** [comment]
@steve-taylor Have you found a way around this yet as currently it breaks not only my nextjs implementation but also my compiled component library?

**Comment by agriffis** [comment]
@probablyup Thanks for all your work on this! I'm finally getting around to trying it with a large codebase.

Here's a problem I'm hitting:

<img width="444" alt="image" src="https://user-images.githubusercontent.com/50637/188316021-136221a2-7bf5-4718-86e3-78d7c65d59bb.png">

Obviously some useless nested `css` invocations there, but they're not useless in my app, just in the sandbox, which you can find at https://codesandbox.io/s/exciting-lucy-zmrdep?file=/src/App.tsx

There are a few workarounds that I found. I can see that they're somehow resolving an inference conflict, but I don't understand how/why:

```ts
const moreStyles = () => css`` as any
```

OR

```ts
const moreStyles = () => css<any>``
```

OR

```ts
const Outer = styled.div(
  () => css`
    ${css<any>`
      ${Inner} {
        color: red;
      }
    `}
    ${moreStyles()}
  `,
)
```

Note the `any` in those workarounds.

**Comment by agriffis** [comment]
I'm not sure if this is a bug or intentional:

<img width="413" alt="image" src="https://user-images.githubusercontent.com/50637/188318983-43908a76-e140-447c-8df9-9bbe6bd429ef.png">

https://codesandbox.io/s/angry-darkness-oyu716?file=/src/App.tsx

I've previously used this sort of construction a lot:

```
${foo && css`...`}
```

but it doesn't like when foo is false, so I have to:

```
${foo ? css`...` : null}
```

**Comment by hadnet** [comment]
I'm trying React Native + SC v6 but something seems weird. When using the Box component I got no bg prop autocomplete, but if I type the prop name completely then I got autocomplete! It's like bg prop is hidden from the component props and thus does not show up on autocomplete, so I don't know why this is happening. On BoxBase same thing I got no autocomplete on align or justify, but on Box I got justify and align autocomplete but no bg.

https://user-images.githubusercontent.com/13828833/188333923-486f09f8-d36a-43e8-9f59-2941d96d7cee.mov

**Comment by hadnet** [comment]
I think I found out why the above is happening. In the PolymorphicComponentProps 

```ts
declare type PolymorphicComponentProps<R extends Runtime, ActualComponent extends StyledTarget<R>,
PropsToBeInjectedIntoActualComponent extends {},
ActualComponentProps = ActualComponent extends KnownTarget ?
 React.ComponentPropsWithRef<ActualComponent> : {}> = React.HTMLAttributes<ActualComponent> & 
// Here I replaced Omit for Exclude in order to work
Exclude<PropsToBeInjectedIntoActualComponent, keyof ActualComponentProps | 'as' | '$as'> & ActualComponentProps & ({
    $as: ActualComponent;
    as?: AnyComponent;
} | {
    as?: ActualComponent;
});
```
I'm not a TS wizard, but you do you think this can be the issue, @probablyup ?

**Comment by agriffis** [comment]
It looks like styled components don't emit an error on missing props:

```ts
import styled from 'styled-components'

const Foo = styled.div<{requiredProp: boolean}>``

export default () => <Foo /> // no error
```

Sandbox at https://codesandbox.io/s/gallant-sun-3jmu2o?file=/src/App.tsx

**Comment by agriffis** [comment]
@probablyup Would you prefer separate issues now that we're on beta?

**Comment by TmLev** [comment]
Seems like `styled-components@^6.0.0-beta.2` can't handle "inplace argument extension" (not sure what's the official name for that):

```ts
const StyledContainer = styled.div<{ clickable?: boolean }>`
  ${({ clickable }) => clickable && 'cursor: pointer;'}
`
```

Error:

```text
TS2345: Argument of type '({ clickable }: ExecutionContext & ClassAttributes<HTMLDivElement> & HTMLAttributes<HTMLDivElement> & { ...; }) => false | ... 1 more ... | undefined' is not assignable to parameter of type 'Interpolation<ExecutionContext & ClassAttributes<HTMLDivElement> & HTMLAttributes<HTMLDivElement> & { ...; }>'.   
  Type '({ clickable }: ExecutionContext & ClassAttributes<HTMLDivElement> & HTMLAttributes<HTMLDivElement> & { ...; }) => false | ... 1 more ... | undefined' is missing the following properties from type 'IStyledComponent<"web", any, any>': $$typeof, componentStyle, foldedComponentIds, inlineStyle, and 4 more.
```

Dependencies:
* React 18
* Typescript 4.3.5

**Comment by TmLev** [comment]
Okay, seems like it doesn't like possible `false` return value.

Explicit handling prevents Typescript from erroring out:

```ts
const StyledContainer = styled.div<{ clickable?: boolean }>`
  ${({ clickable }) => clickable ? 'cursor: pointer;' : ''}
`
```

Feels like a regression from v5.

<hr /> 

But when using `.attrs`, it definitely refuses to work:

```ts
const HideOnMobile = styled(HideOn).attrs({ device: 'mobile' })<{ gridColumn: number }>`
  grid-column: ${({ gridColumn }) => gridColumn};
`
```

Error:

```text
TS7031: Binding element 'gridColumn' implicitly has an 'any' type.
```

**Comment by agriffis** [comment]
> Okay, seems like it doesn't like possible `false` return value.

@TmLev This was mentioned above, see https://github.com/styled-components/styled-components/issues/3696#issuecomment-1236355978

and there is a PR for it, see #3799

**Comment by TmLev** [comment]
> > Okay, seems like it doesn't like possible `false` return value.
> 
> @TmLev This was mentioned above, see https://github.com/styled-components/styled-components/issues/3696#issuecomment-1236355978
> 
> and there is a PR for it, see #3799 
> 

Right, missed that, sorry.

Nevertheless, the latter issue (when using `.attrs`) persists.

**Comment by probablyup** [comment]
Hi folks, I've started a new thread for beta at #3800. Going to close this one for now. Thanks!

**Comment by probablyup** [comment]
(merged @agriffis's fix to allow `false` again as an interpolation, that'll go out with beta 3)
