### ISSUE TITLE
Not stable work pseudo elements for list

### ISSUE THREAD

**Issue by AleksRap** [styled-components/styled-components#3698]
Hello. I try to use this library for interactive create ordered list in my react project. But it works not stable. Sometimes number visible, sometimes not. There is no pattern i don't see. Variable "numberingKey" always come and always correct

In case when number don't visible - pseudo element has 1 prop: "font-weight". Other props are missing. In case when numbering visible - all props are there. In sandbox reproduce the bug fails

```
const Ol = styled.ol`
  list-style-type: none;
  counter-reset: ${(props: IStyledProps) => props.numberingKey};
`;

const NumCol = styled.div`
  justify-content: left;
  margin-right: 0.5em;
  &:before {
    font-weight: bold;
    counter-increment: ${({ numberingKey }: IStyledProps) => numberingKey};
    content: counters(${({ numberingKey }: IStyledProps) => numberingKey}, '.') '. ';
  }
`;
```

## Expected Behavior
Always transmitted all props to pseudo elements

## Actual Behavior
Sometimes transmitted props "counter-increment" and "content", sometimes not

**Comment by probablyup** [comment]
A few things, you can avoid composing `IStyledProps` a bunch of times by providing it at declaration:

```ts
const Ol = styled.ol<IStyledProps>`
  list-style-type: none;
  counter-reset: ${(props) => props.numberingKey};
`

const NumCol = styled.div<IStyledProps>`
justify-content: left;
  margin-right: 0.5em;
  &:before {
    font-weight: bold;
    counter-increment: ${({ numberingKey }) => numberingKey};
    content: counters(${({ numberingKey }) => numberingKey}, '.') '. ';
  }
```

The `counters()` CSS function looks a little odd to me. What's that extra `'. '` doing at the end?

```ts
content: counters(${({ numberingKey }) => numberingKey}, '.');
```

**Comment by probablyup** [comment]
Going to close this as it appears to be more of a usage question than a library bug or feature request.
