### ISSUE TITLE
styled-theme 💅🏿

### ISSUE THREAD

**Issue by diegohaz** [styled-components/styled-components#370]
Hi, guys.

I and people working with me were accustomed to Foundation, Bootstrap and other CSS libs out there. We loved the way we could customize the theme using only scss variables. So since we started to use `styled-components` on our projects we've been looking for ways to accomplish that.

In short, we've written some theming helpers and I decided to publish this as `styled-theme 💅🏿`: https://github.com/diegohaz/styled-theme

I'd love to see what you guys think about it and if it worths mentioning on `styled-components` README.

Play with it on [WebpackBin](http://www.webpackbin.com/EkYUuq0BG)

```js
import styled from 'styled-components'
import { font, palette } from 'styled-theme' 

const Text = styled.span`
  font-family: ${font('primary')};
  background-color: ${palette(1)};
  color: ${palette('grayscale', 0, true)};
`

Text.defaultProps = {
  palette: 'primary'
}
```

```jsx
<Text>Hello</Text>
```
![image](https://cloud.githubusercontent.com/assets/3068563/21835155/f92c4a74-d7a1-11e6-85c1-93d6e447f98a.png)

```jsx
<Text reverse>Hello</Text>
```
![image](https://cloud.githubusercontent.com/assets/3068563/21835169/18b3ea28-d7a2-11e6-8f3f-2fc76c706f45.png)

```jsx
<Text palette="secondary">Hello</Text>
```
![image](https://cloud.githubusercontent.com/assets/3068563/21835195/350f4514-d7a2-11e6-9095-4e30d04b3d61.png)

**Comment by mxstbr** [comment]
Hey, that's awesome! That's the power of JavaScript, letting you do things like that. Good work!
