### ISSUE TITLE
Currying Props to Styled Component

### ISSUE THREAD

**Issue by curtvict** [styled-components/styled-components#3702]
I'm trying to wrap a Styled Component in a regular component, using Typescript, and am having the darnedest time trying to figure out how to curry the supplied props from `SearchFormButton` down to the nested, styled `Button` component.

If possible, please solve for `WhatTheHeck`, below:

```tsx
const Button = styled.button`
  order: 1;
  background: none;
  border: 0;
  border-radius: 24px 0 0 24px;

  background: ${({ theme }) => theme.color.gray100};
  padding: ${({ theme }) =>
    [theme.spacing.x3, theme.spacing.x2, theme.spacing.x3, theme.spacing.x4].join(' ')};
`;

const ButtonIcon = () => <Icon size="16px">search</Icon>;

export const SearchFormButton = ({ ...buttonProps }: WhatTheHeck) => (
  <Button {...buttonProps}>
    <ButtonIcon />
  </Button>
);
```

**Comment by probablyup** [comment]
A minimal codesandbox reproduction would be good. At a glance I don't see anything wrong with this code

**Comment by probablyup** [comment]
Going to close this as its a usage question, which should go in Discussions or elsewhere. Thanks for using styled-components!

**Comment by Elvergas2** [comment]
2022-03-11 14:28 GMT-07:00, curtvict ***@***.***>:

**Comment by EloB** [comment]
I think what he is after is polymorphic components.`WhatTheHeck` needs to take in consideration of `as` and `forwardAs` and dynamically add these props from that passed component.

**Comment by curtvict** [comment]
`type WhatTheHeck = React.ComponentProps<typeof Button>` has been working for me

**Comment by EloB** [comment]
> `type WhatTheHeck = React.ComponentProps<typeof Button>` has been working for me

That doesn’t seem to be dynamic if you pass in as or forwardedProps.

**Comment by curtvict** [comment]
Do you have a code example?
