### ISSUE TITLE
Esbuild loader is used in the project. How can we use the function similar to Babel plugin styled components - class namespace

### ISSUE THREAD

**Issue by Wangggym** [styled-components/styled-components#3705]
## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`

## Reproduction

https://codesandbox.io/s/styled-components-base-gc367

**Comment by Wangggym** [comment]
<img width="927" alt="image" src="https://user-images.githubusercontent.com/26135370/158725069-cf7e0b84-358a-451c-8d16-4d10888d4b2b.png">
I just want to use this plugin. But I find my project used esbuild-loader.

**Comment by probablyup** [comment]
I believe it's a 3rd party plugin written by the community, best to contact them directly since we don't have any relationship
