### ISSUE TITLE
cannot find module node_modules/styled-components/postinstall.js

### ISSUE THREAD

**Issue by kprime21** [styled-components/styled-components#3706]
issue when installing styled-components through npm.

command:

`npm install styled-components`

error:
```
npm ERR! code 1
npm ERR! path /home/kp/Code/Javascript/blog-website/node_modules/styled-components
npm ERR! command failed
npm ERR! command sh -c node ./postinstall.js
npm ERR! node:internal/modules/cjs/loader:936
npm ERR!   throw err;
npm ERR!   ^
npm ERR! 
npm ERR! Error: Cannot find module '/home/kp/Code/Javascript/blog-website/node_modules/styled-components/postinstall.js'
npm ERR!     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:778:27)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
npm ERR!     at node:internal/main/run_main_module:17:47 {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: []
npm ERR! }
npm ERR! 
npm ERR! Node.js v17.7.1

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/kp/.npm/_logs/2022-03-24T13_48_17_174Z-debug-0.log
```

npx envinfo:

```
## System:
 - OS: Linux 5.15 Manjaro Linux
 - CPU: (8) x64 Intel(R) Core(TM) i3-10320 CPU @ 3.80GHz
 - Memory: 12.17 GB / 15.48 GB
 - Container: Yes
 - Shell: 5.1.16 - /bin/bash
## Binaries:
 - Node: 17.7.1 - /usr/bin/node
 - Yarn: 1.22.17 - /usr/bin/yarn
 - npm: 8.5.4 - /usr/bin/npm
```

**Comment by victorhenriqc** [comment]
same problem

**Comment by rnatto-gempe** [comment]
Fixed here by set to specific version, removing ^

`    "styled-components": "5.2.1",
`

**Comment by sampi** [comment]
`npm` and `yarn` both list `5.3.4` as `latest` when running:

```
> npm info styled-components
> yarn info styled-components
```

but there is no mention of that version here in the code nor on https://www.npmjs.com/package/styled-components and https://yarnpkg.com/package/styled-components

the latest version mentioned in the code is `5.3.3`, I suggest we use that for now.

**Comment by ethandaniel** [comment]
yarn install didn't work for any versions. Got the same error

**Comment by buniekwawa** [comment]
check my comment to pr
https://github.com/styled-components/styled-components/commit/ba9d732ca7da53f2a095e35450ecffd592c6f5ba

**Comment by ethandaniel** [comment]
How do we fix it then. Or is it only up to the devs?

**Comment by alexandre-bedos-upandgo** [comment]
> for a while you can install npm install styled-components@5.3.3

Worked for me. But I had to add resolutions field in package.json (I use yarn)
"resolutions" : {
  "styled-components": "5.3.3"
}

**Comment by w3nda** [comment]
I'm having the same issue, discovered when it started failing our CI.
Any official solution yet?

**Comment by jacekd** [comment]
same issue here

**Comment by xixxdev** [comment]
the same

**Comment by afsaneh871** [comment]
> > for a while you can install npm install styled-components@5.3.3
> 
> Worked for me. But I had to add resolutions field in package.json (I use yarn) "resolutions" : { "styled-components": "5.3.3" }

Thanks, solved my problem :)

**Comment by probablyup** [comment]
Fixed in 5.3.5 sorry about that

**Comment by probablyup** [comment]
Sure thing, I forgot to expose the file in the package.json config.

**Comment by huasx** [comment]
the same

**Comment by eglove** [comment]
We're still injecting politics into OSS?

https://security.snyk.io/vuln/SNYK-JS-STYLEDCOMPONENTS-3149924

**Comment by vantaboard** [comment]
> The absolute irony of labeling the issue that called this out as spam... facepalm
It is spam, and you're part of the problem. Slava Ukraini!

**Comment by probablyup** [comment]
“Abuse” lol, it’s a message that is only shown to Russian users. Get over yourself.
