### ISSUE TITLE
PeerDependency made with styled-component, how does it work ?

### ISSUE THREAD

**Issue by kopax** [styled-components/styled-components#373]
I have created a module that contains react components made with styled-components.

I have excluded react from the dependencies and added it to peerDependencies and devDependencies.

I have configured webpack so react is added as external to my umd module.

I have tried to do the same with styled-components, but it doesn't work

Here are the resources I am using : 

- https://webpack.github.io/docs/library-and-externals.html.

> `externals` allows you to specify dependencies for your library that are not resolved by webpack, but become dependencies of the output. This means they are imported from the environment during runtime

I have tried to add:

```js
  externals: {
    react: true,
    'react-dom': true,
    'styled-components': true,
  },
```

But when I import my module, using this deps:

```jsx 
  "peerDependencies": {
    "react": "^15.4.1",
    "styled-components": "^1.1.2"
  },
  "devDependencies": {
    "babel-core": "6.21.0",
    "babel-eslint": "7.1.1",
    "babel-loader": "6.2.10",
    "babel-plugin-dynamic-import-node": "1.0.0",
    "babel-plugin-react-intl": "2.2.0",
    "babel-plugin-react-transform": "2.0.2",
    "babel-plugin-transform-es2015-modules-commonjs": "6.18.0",
    "babel-plugin-transform-react-constant-elements": "6.9.1",
    "babel-plugin-transform-react-inline-elements": "6.8.0",
    "babel-plugin-transform-react-remove-prop-types": "0.2.11",
    "babel-preset-latest": "6.16.0",
    "babel-preset-react": "6.16.0",
    "babel-preset-react-hmre": "1.1.1",
    "babel-preset-stage-0": "6.16.0",
    "chai": "3.5.0",
    "chai-enzyme": "0.6.1",
    "circular-dependency-plugin": "2.0.0",
    "classnames": "2.2.5",
    "color": "1.0.3",
    "coveralls": "2.11.15",
    "css-loader": "0.26.1",
    "enzyme": "2.6.0",
    "eslint": "3.11.1",
    "eslint-config-airbnb": "13.0.0",
    "eslint-config-airbnb-base": "10.0.1",
    "eslint-import-resolver-webpack": "0.8.0",
    "eslint-plugin-import": "2.2.0",
    "eslint-plugin-jsx-a11y": "2.2.3",
    "eslint-plugin-react": "6.7.1",
    "eventsource-polyfill": "0.9.6",
    "exports-loader": "0.6.3",
    "file-loader": "0.9.0",
    "html-loader": "0.4.4",
    "image-webpack-loader": "2.0.0",
    "imports-loader": "0.6.5",
    "jest-cli": "18.0.0",
    "lint-staged": "3.2.1",
    "ngrok": "2.2.4",
    "node-plop": "0.5.4",
    "null-loader": "0.1.1",
    "plop": "1.7.3",
    "pre-commit": "1.1.3",
    "react": "15.4.1",
    "react-dom": "15.4.1",
    "react-addons-test-utils": "15.4.1",
    "react-onclickoutside": "5.8.3",
    "rimraf": "2.5.4",
    "shelljs": "0.7.5",
    "sinon": "2.0.0-pre",
    "style-loader": "0.13.1",
    "styled-components": "1.1.2",
    "url-loader": "0.5.7",
    "webpack": "2.2.0-rc.3",
    "webpack-dev-middleware": "1.9.0",
    "webpack-hot-middleware": "2.15.0"
  }
```

Should I fix the styled-components peer version ?

It's just react+styled components, I took the build from react-boilerplate and I feel I have a bit too much dependencies.

**Comment by mxstbr** [comment]
I don't quite understand why you would want to do this. If you move `styled-components` to the `devDependencies` and then deploy, you'll do a `npm install --production` and won't get the dependency installed?

Why not just use it normally?

**Comment by kopax** [comment]
It's not a server with web application but a library of Component build on top of react and styled.
This is why I needed to extract react and styled from the lib build.
I've just removed the `node_modules` folder and all the dll build part and I managed to create the lib with these two peerDependencies.

Would you recommend to fix the peerDependencie version in this case ? It depend of the update strategy, will you try to keep compatibility between versions ?

**Comment by mxstbr** [comment]
> It's not a server with web application but a library of Component build on top of react and styled.

But that component _depends_ on `styled-components`. No matter what your user does, you'll have to ship it with `styled-components` otherwise it will break, right?

**Comment by kopax** [comment]
@mxstbr I managed to just keep it as a peerDependencies and exclude it from the build.

If you want to use this library, you will have to install yourself styled-component in react.

**Comment by mxstbr** [comment]
Ahh now I understand what you want! Sorry, I've never done that, I'm glad you were able to figure it out!

**Comment by rbalicki2** [comment]
@kopax could you give more detail as to what you did? I'm having trouble excluding libraries myself using peerDependencies and externals

**Comment by vadivelkindhealth** [comment]
@kopax You should be using the below in your webpack config as cited (here)[https://webpack.js.org/configuration/externals/].
```
...
  externals: {
    react: 'React',
    'react-dom': 'ReactDOM',
    'styled-components': 'styled-components'
  }
```

**Comment by maufarinelli** [comment]
My 2 cents @kopax 
I was having the same problem as you. 
I was able to remove `styled-components` from my build.
```
externals: {
        // Don't bundle react, react-dom and styled-components   
        react: {
            commonjs: "react",
            commonjs2: "react",
            amd: "React",
            root: "React"
        },
        "react-dom": {
            commonjs: "react-dom",
            commonjs2: "react-dom",
            amd: "ReactDOM",
            root: "ReactDOM"
        },
        'styled-components': {
            commonjs: "styled-components",
            commonjs2: "styled-components",
            amd: "styled-components",
            root: "styled-components"
        }
    }
```
but then, when I was importing it into one app for testing, it was giving error because `styled-components` was undefined. 
You said before 

> If you want to use this library, you will have to install yourself styled-component in react.

 but I wasn't satisfied with this. Looks like you are installing a library and it has a bug which makes it totally impossible to use it. 
My solution was to put as:
```
"dependencies": {
    "styled-components": "^4.1.3"
  },
```
Then, when someone npm install my library, it will be installed for them and no errors shows up
