### ISSUE TITLE
Not clear how to use styled-components with third-party react libraries

### ISSUE THREAD

**Issue by bitIO** [styled-components/styled-components#374]
I'm using for a new project reactboilerplate and AntD as ui kit. And when using some components from AntD, I cannot find in the docs the appropriated way to style the components. Here's an example:

I'm using the [upload](https://ant.design/components/upload/) element from AntD
```js
<Upload
  className="avatar-uploader"
  name="avatar"
  showUploadList={false}
  action="/upload.do"
  beforeUpload={this.beforeUpload}
  onChange={this.handleChange}
>
  {imageUrl ?
    <img src={imageUrl} alt="" className="avatar" /> :
    <Icon type="plus" className="avatar-uploader-trigger" />
  }
</Upload>
```

which produces the following HTML tree

```html
<span class="avatar-uploader">
  <div class="ant-upload ant-upload-select ant-upload-select-text">
    <span tabindex="0" class="ant-upload" role="button">
      <input type="file" accept="" style="display: none;">
      <i class="anticon anticon-plus avatar-uploader-trigger"></i>
    </span>
  </div>
</span>
```

I've created a `StyledUpload` element but, I'm not sure this is the right approach:
```js
const StyledUpload = styled(Upload)`
      display: block;
      border: 1px dashed #d9d9d9;
      border-radius: 6px;
      cursor: pointer;
      > div {
        min-height: 150px;
        display: flex;
        align-items: center;
        justify-content: center;
      }
`;
```

**Comment by IljaDaderko** [comment]
Are you using your styled component afterwards? i.e. 

```
< StyledUpload
  className="avatar-uploader"
  name="avatar"
  showUploadList={false}
  action="/upload.do"
  beforeUpload={this.beforeUpload}
  onChange={this.handleChange}
>
  {imageUrl ?
    <img src={imageUrl} alt="" className="avatar" /> :
    <Icon type="plus" className="avatar-uploader-trigger" />
  }
</StyledUpload >
```

**Comment by bitIO** [comment]
@IljaDaderko yes, that's the point (I guess 😅). I use it and I made it work, but to me - and maybe to newcomers like me - it's not quite clear if this is the right way to style this kind of components.

**Comment by IljaDaderko** [comment]
@bitIO I know, It took me a good day of playing around with styled components to get this, but once you do, this approach to styling is very very very powerful!

**Comment by mxstbr** [comment]
We will update the documentation with v2 for using normal (and external) components, which will hopefully also resolve the whole `className` confusion.

Thanks for pointing this deficiency out!
