### ISSUE TITLE
Styled Not Working In General With Vite

### ISSUE THREAD

**Issue by ericwang401** [styled-components/styled-components#3744]
## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown --clipboard`
```
## System:
 - OS: Linux 5.4 Ubuntu 20.04.4 LTS (Focal Fossa)
 - CPU: (4) x64 AMD Ryzen 9 5900X 12-Core Processor
 - Memory: 13.65 GB / 15.73 GB
 - Container: Yes
 - Shell: 5.0.17 - /bin/bash
## Binaries:
 - Node: 18.2.0 - /home/laradock/.nvm/versions/node/v18.2.0/bin/node
 - Yarn: 1.22.19 - /home/laradock/.yarn/bin/yarn
 - npm: 8.9.0 - /home/laradock/.nvm/versions/node/v18.2.0/bin/npm
## npmPackages:
 - styled-components: ^5.3.5 => 5.3.5 
```

## Reproduction

I am running Docker version `20.10.16` `build aa7e414`. I am using Docker compose v1 because Docker compose v2 doesn't work with Laradock yet (**MAKE SURE TO DISABLE v2!!!**).

I containerized the backend and frontend in separate containers

1. Clone the fresh installation of Laravel from (USE THE `next` BRANCH!!) https://github.com/ericwang401/pastry-clicker/tree/next
2. Clone Laradock in the project folder using `git clone https://github.com/laradock/laradock.git`
3. CD to the Laradock folder and make `.env` file with `cp .env.example .env`
4. Inside `.env` file set `PHP_VERSION` to `PHP_VERSION=8.1` AND DO NOT EDIT MYSQL SETTINGS
5. Now edit `docker-compose.yml` inside `laradock`
Edit these specific lines

`I deleted the conflicting ports that conflicted with 3000 in this config. You can copy and paste this ports section directly into the docker-compose file`
```
### Workspace Utilities ##################################
    workspace:
    ....
      ports:
        - "${WORKSPACE_SSH_PORT}:22"
        - "${WORKSPACE_VUE_CLI_SERVE_HOST_PORT}:8080"
        - "${WORKSPACE_VUE_CLI_UI_HOST_PORT}:8000"
        - "${WORKSPACE_ANGULAR_CLI_SERVE_HOST_PORT}:4200"
        - 3000:3000
```
6. Now edit the Laravel environment file
```
DB_CONNECTION=mysql
DB_HOST=mysql
DB_PORT=3306
DB_DATABASE=default
DB_USERNAME=default
DB_PASSWORD=secret
```
7. Start up the Laravel app in `Laradock` folder using `docker-compose up -d nginx mysql`
8. Enter into bash mode in the Docker container `docker-compose exec workspace bash`
9. Run `npm i && composer i`
10. Run `npm run dev`
11. Now navigate to localhost in your browser and open console and the errors should be there

## Steps to reproduce

They are above

## Expected Behavior

A card should appear aligned center horizontally inside a div.

## Actual Behavior

Importing `css` from `styled-components/macro` results in this error in the browser console
```
Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/styled-components_macro.js?v=849f7612' does not provide an export named 'css' (at Container.tsx:1:1)
```

If I don't use the `css` macro and just import styled, I get this error in the browser console
```
Uncaught ReferenceError: process is not defined
    at node_modules/@babel/types/lib/definitions/core.js (core.js:23:17)
    at __require2 (chunk-5537U2Q2.js?v=849f7612:47:50)
    at node_modules/@babel/types/lib/definitions/index.js (index.js:70:1)
    at __require2 (chunk-5537U2Q2.js?v=849f7612:47:50)
    at node_modules/@babel/types/lib/validators/validate.js (validate.js:10:20)
    at __require2 (chunk-5537U2Q2.js?v=849f7612:47:50)
    at node_modules/@babel/types/lib/builders/validateNode.js (validateNode.js:8:17)
    at __require2 (chunk-5537U2Q2.js?v=849f7612:47:50)
    at node_modules/@babel/types/lib/builders/generated/index.js (index.js:259:21)
    at __require2 (chunk-5537U2Q2.js?v=849f7612:47:50)
```

At first, I went through all the docs for styled components and Vite, searched existing issues, and checked out various Stackoverflow threads that suggested certain Babel plugins.

I tried using `vite-plugin-babel-macros` in my `vite.config.ts` file. It worked, but I get type errors saying that `content` is a `non-boolean attribute`, which is wrong because I specified `content` as a `boolean or undefined` attribute in https://github.com/ericwang401/pastry-clicker/blob/c7d7af77603044cabb8715eee3b4281406d38c4f/resources/scripts/components/elements/Container.tsx

**Comment by lmiller1990** [comment]
I made a new React app with `yyarn create vite --template react react-styled-components` and created a minimal example and it worked okay for me. I wonder if this is something specific in your config?
