### ISSUE TITLE
Will Styling Inside a Component Impact Performance?

### ISSUE THREAD

**Issue by blackboardd** [styled-components/styled-components#3750]
Is there a performance difference between

```ts
const Foo = () => {
    const Wrapper = styled.div`
        display: flex;
    ';

    return (
        <Wrapper />
    )
}
```

and

```ts
const Wrapper = styled.div`
    display: flex;
';

const Foo = () => {
    return (
        <Wrapper />
    )
}
```

or does Styled Components extract the styles anyway. I just don't want it to do extra work on every render if it doesn't have to.

**Comment by alexandernanberg** [comment]
https://styled-components.com/docs/faqs#why-should-i-avoid-declaring-styled-components-in-the-render-method
