### ISSUE TITLE
Issue resolving package/installation (see #3356)

### ISSUE THREAD

**Issue by marcoXbresciani** [styled-components/styled-components#3751]
## System:
 - OS: Windows 10 10.0.19043
 - CPU: (12) x64 Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
 - Memory: 13.98 GB / 31.79 GB
## Binaries:
 - Node: 16.15.1 - C:\nodejs\node.EXE
 - npm: 8.12.1 - C:\nodejs\npm.CMD

**NOTE** (might not be the issue, but might even be worth mentioning): node+npm environment is managed through [NVM for Windows](https://github.com/coreybutler/nvm-windows).

## Reproduction
I can reproduce the problem everytime with these steps below.

## Steps to reproduce
* I've created a new React Native project from scratch, using
  ```shell
  npx react-native init AwesomeTSProject --template react-native-template-typescript
  ```
* I've installed `react-i18next` (_optional: I see the same error even without this step_) using 
  ```shell
  npm install react-i18next --save
  ```
The resulting `package.json` from these steps above is:
```JSON
{
  "name": "awesometsproject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx"
  },
  "dependencies": {
    "react": "17.0.2",
    "react-i18next": "^11.17.0",
    "react-native": "0.68.2"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "@types/jest": "^26.0.23",
    "@types/react-native": "^0.67.3",
    "@types/react-test-renderer": "^17.0.1",
    "@typescript-eslint/eslint-plugin": "^5.17.0",
    "@typescript-eslint/parser": "^5.17.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "^0.67.0",
    "react-test-renderer": "17.0.2",
    "typescript": "^4.4.4"
  },
  "resolutions": {
    "@types/react": "^17"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
}
```
* I've ran `npm install --save styled-components` to installa styled-components, as described in https://styled-components.com/docs/basics#installation

## Expected Behavior
Styled components should've been installed.

## Actual Behavior
Node/NPM unable to resolve dependency tree with this error:
```shell
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: awesometsproject@0.0.1
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR!   peer react@">= 16.8.0" from styled-components@5.3.5
npm ERR!   node_modules/styled-components
npm ERR!     styled-components@"*" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^18.1.0" from react-dom@18.1.0
npm ERR! node_modules/react-dom
npm ERR!   peer react-dom@">= 16.8.0" from styled-components@5.3.5
npm ERR!   node_modules/styled-components
npm ERR!     styled-components@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\marco.bresciani\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\marco.bresciani\AppData\Local\npm-cache\_logs\2022-06-09T06_37_45_051Z-debug-0.log
```
Further note: current experiments and errors are seen in a project with a space in the path, but it also happens with same sequence applied in a path without spaces.

Adding noted attachments:
* [eresolve-report.txt](https://github.com/styled-components/styled-components/files/8867636/eresolve-report.txt)
* [2022-06-09T06_37_45_051Z-debug-0.log](https://github.com/styled-components/styled-components/files/8867643/2022-06-09T06_37_45_051Z-debug-0.log)

Workarounds/solutions listed in #3356 are not working.

**Comment by marcoXbresciani** [comment]
Problem solved by running `npm install --save react-dom@17`.

**Comment by azadsarxanli** [comment]
For those, who can't figure out the problem: this is not `styled-components` error. As the console said it's an `NPM Error`. 
```npm
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
```
To solve this problem, you can run this command: 
         -    `npm install --save --legacy-peer-deps styled-components`
      
To understand better, I highly recommended to read [this stackoverflow](https://stackoverflow.com/a/68139353/19120939) article.
