### ISSUE TITLE
Styled-components not recognise the variable inside the media theme

### ISSUE THREAD

**Issue by zachxdc** [styled-components/styled-components#3754]
Guys, recently I encountered problems like this:

WORK case:
```
    ${media.breakpointDown(media.sm)`
      height: 50px;
    `}
```

NOT WORK case:
```
    ${media.breakpointDown(media.sm)`
      height: ${wrapperHeightMobile};
    `}
```

wrapperHeightMobile = "50px" has been passed in via props

Thanks

**Comment by falsepopsky** [comment]
theme ?

`    ${media.breakpointDown(media.sm)`
      height: ${({ theme }) => theme.wrapperHeightMobile};
    `}
`
props:

`    ${media.breakpointDown(media.sm)`
      height: ${(props) => (props.wrapperHeightMobile)};
    `}
`

[https://styled-components.com/docs/basics#adapting-based-on-props](url)
