### ISSUE TITLE
[v6] Upgrading from 5.1.1 to 6.0.0-beta.2 has broken babel-plugin-styled-components-css-namespace

### ISSUE THREAD

**Issue by marmite22** [styled-components/styled-components#3757]
## Environment
In the process of upgrading React to v18 we found that Styled-components was throwing an error about breaking the rule of hooks. Upgraded styled-components to the latest version it appears that the [babel-plugin-styled-components-css-namespace](https://github.com/QuickBase/babel-plugin-styled-components-css-namespace) recommended in the [styled-component docs](https://styled-components.com/docs/advanced#avoiding-conflicts-with-thirdparty-styles-and-scripts) no longer works correctly. I note that the plugin has not been updated in a few years and appears inactive.

## Steps to reproduce

Given the babel config
```
['@quickbaseoss/babel-plugin-styled-components-css-namespace', { cssNamespace: '.ssa-app' }],
```
and the code
```
  const StyledIcon = styled(IcomoonReact)`
    transform: ${(props) => (props.$flipx ? `scaleX(-1)` : 'none')};`
  `
  
  <StyledIcon $flipx={true}   />
  <StyledIcon $flipx={false}   />
```

## Expected Behavior

On version 5.1.1 the above would produce 2 styles and correctly assign the classnames to the elements in the DOM. (.ssa-app is the css prefix defined in babel-plugin-styled-components-css-namespace)

```
.ssa-app .lnugha {
    transform: none;
}

.ssa-app .hHOYwd {
    transform: scaleX(-1);
}
```

## Actual Behavior

Since updating to 5.3.5 the CSS is as follows and both elements have the same class of `sc-bczRLJ` and thus both look the same (flipped).

```
.ssa-app .sc-bczRLJ {
    transform: scaleX(-1);
}

.ssa-app .sc-bczRLJ {
    transform: none;
}

.ssa-app .sc-bczRLJ {
    transform: none;
}
```

I'm completely stuck as to how to achieve the global css namespace in 5.3.5.

**Comment by marmite22** [comment]
More specifically it looks like this issue was introduced in [5.2.0](https://github.com/styled-components/styled-components/releases/tag/v5.2.0)

**Comment by marmite22** [comment]
I spent a bit more time on it and replaced the babel plugin with a Stylis plugin (https://github.com/Andarist/stylis-plugin-extra-scope) and I'm getting the same result using this too!

In both cases it seems to take the CSS and apply it to the .sc-xxxxx class instead of the .xxxxx class when used with any SC version after 5.2.0.

Has anyone got a solution for adding a global scope/namespace class to the output of Styled components that works with the latest version?

**Comment by avaleriani** [comment]
I'm having the same issue with version 5.1.1, had to downgrade to 5.1.1

**Comment by marmite22** [comment]
@avaleriani Are you able to use 5.1.1 with React 18?

**Comment by avaleriani** [comment]
> @avaleriani Are you able to use 5.1.1 with React 18?

I haven't encountered any issue so far, only a warning about hooks but not sure if it's related.

**Comment by soluxos** [comment]
Hey I'm seeing this exact issue as well, I'm also using https://github.com/Andarist/stylis-plugin-extra-scope to prepend all of my styles. Could really do with a fix for this...

**Comment by marmite22** [comment]
I've managed to get as far as stepping through the stylis plugin line by line and so far as I can tell it does everything 'correctly'. It seems to be once the output from the Stylis plugin is handed over to Styled Components that things go wrong - somehow the generated CSS from styled components uses the sc-x classes instead of the other class that the Stylis plugin modifies. 

Is there anyone more familiar with the styled components codebase that can look into this?

**Comment by avaleriani** [comment]
any update on this?

**Comment by marmite22** [comment]
I've just updated to the latest beta of version 6 and this issue is still present and preventing us from upgrading to React 18.

Is there anything further I can do to assist someone more familiar with the codebase taking a look into this?

**Comment by fortinmike** [comment]
It may not be an ideal solution, but I noticed that using an ampersand namespace does work.

For example, if you omit `cssNamespace` (or use `{ cssNamespace: "&&" }` in the plugin configuration, `@quickbaseoss/babel-plugin-styled-components-css-namespace` will stop overwriting the same class over and over again instead of letting styled-components "adapt it based on props" like it's supposed to.

Instead of, say:

```
.ssa-app .sc-bczRLJ {
    transform: scaleX(-1);
}

.ssa-app .sc-bczRLJ {
    transform: none;
}
```

You'll get something like this:

```
.imlPel.imlPel {
    transform: scaleX(-1);
}

.hjyLhO.hjyLhO {
    transform: none;
}
```

...which may or may not have other implications based on your codebase. It's not as clean, compact (code-size-wise) and "safe" as a class or id-based namespace is, but it does work and should allow you to upgrade to react 18+.

If two ampersands is not enough, adding more should bump the styles to be more specific than whatever other external styles you're trying to override.

I'd really be interested in a proper fix of course.

Hope this helps!

**Comment by probablyup** [comment]
Probably can just add this functionality into StylesheetManager and thread it through into the stylis instance

**Comment by marmite22** [comment]
@probablyup thank you so much for this. Do you know when the next beta with the namespace functionality will be available?

**Comment by probablyup** [comment]
It’s in v6 now but I haven’t cut a new beta with it yet, perhaps next week

**Comment by marmite22** [comment]
I have tested and this appears to be working now in beta 9! Thank you so much.
