### ISSUE TITLE
@container is not working ....

### ISSUE THREAD

**Issue by usback** [styled-components/styled-components#3763]
i try to @container query  test   but is not woking
```
const View = styled.div`
  @container(max-width:700px) {   
            grid-template-columns: 1fr 1fr;
            grid-template-rows: 1fr 1fr;
            grid-gap:15px 15px;

            &>:nth-child(1){
                grid-row: 1 / span  2;
            }
     }
@media ( max-width: 3000){
 ... is working find 
}      
`
```

so how can i use   @container 
thank you

**Comment by probablyup** [comment]
Probably will need to use v6 alpha for this, stylis v3 didn't support a bunch of the newer syntaxes

**Comment by stijnvanderlaan** [comment]
I tried it with version `6.0.0-alpha.7` but it did not work.

**Comment by nielsvanoosterom-varias** [comment]
Chrome 105 just shipped which includes support for container queries. It would be really nice if this could also be supported by styled-components.

**Comment by PaulKiddle** [comment]
This appears to have been fixed in stylis and released as patch version [v4.1.3](https://github.com/thysultan/stylis/releases/tag/v4.1.3) (although they don't seem to have a changelog documenting this). The dependency version should be updated to guarantee styled-components users have access to this feature.

**Comment by probablyup** [comment]
Should be working in v6 beta

**Comment by nicolae536** [comment]
Does anyone have issues with this feature ? 🤔 in v `6.0.5` I cannot use it it doesn't generate the styles for `@container`.

**Comment by probablyup** [comment]
You have media twice in that conditional

**Comment by nicolae536** [comment]
@probablyup I know I put it there intentional. I tried with container and it doesn't work the styles are not generated at all.

**Comment by AbiHill** [comment]
Hi folks,

Does anyone have the correct syntax / example for me to see the solution to the above?

We are also still on `5.3.6` styled-components, could this be my problem?

Is the below logic incorrect for styled-components? 

Component:
`
<Parent>
   <Child className="child">
   </Child>
</Parent>

`

Styles:
`
const Parent = styled.div`
   @container (min-width: 700px) {
           .child {
                border: 1px solid red;
           }
   }
`


Many thanks in advance 🙏🏼

**Comment by agriffis** [comment]
> We are also still on `5.3.6` styled-components, could this be my problem?

AFAIK it only works in v6 which uses the newer stylis
