### ISSUE TITLE
styled components & className

### ISSUE THREAD

**Issue by lowfnm** [styled-components/styled-components#3767]
I would like to know how to apply styles when, for example, we use a component on a page and we need to set its indentation or positioning.

сode example: 
<img width="631" alt="image" src="https://user-images.githubusercontent.com/37019121/177560027-a0d8083d-8c9f-4520-ba71-cd623bf038ef.png">
How do I drop styles into a component like this? styled(componentName) doesn't work, thanks in advance
I use latest version of styled-components

**Comment by 86Magical** [comment]
You mean something like 

const NewButton = styled(OldButton)`

`

?
