### ISSUE TITLE
Cypress component tests fail to run when using @react-data-table-component -- ^7.5.2 @styled-components: ^5.3.5

### ISSUE THREAD

**Issue by manishagupta016** [styled-components/styled-components#3775]
### Current behavior

Running Cypress component tests (Cypress ^10.3.0) results in the following error message for all the tests:
```js
"Cannot read properties of undefined (reading 'REACT_APP_SC_ATTR')"

at <unknown> (http://localhost:3000/__cypress/src/node_modules/.vite/deps/react-data-table-component.js?v=22eeef94:649:56)
```

<img width="519" alt="image" src="https://user-images.githubusercontent.com/106742436/177316482-0d7179cb-fc07-427e-a16e-e1256d5312d1.png">

### Desired behavior

The cypress component tests should run correctly

### Test code to reproduce
```js
 "@cypress/react": "^6.0.0",
 "cypress": "^10.3.0",
 "vite": "^2.9.9",
"react": "^18.1.0",
"react-data-table-component": "^7.5.2",
 "styled-components": "^5.3.5",
```
 ### ISSUE COULD BE BECAUSE OF 
``` 
https://github.com/styled-components/styled-components/blob/main/packages/styled-components/src/constants.ts#L5
```
<img width="1298" alt="image" src="https://user-images.githubusercontent.com/106742436/180204377-81b98c9d-68b6-4311-b4d8-10d06ba64a7d.png">

_No response_

**Comment by kaungsithar** [comment]
Have you made cypress configuration for react with vite?

https://docs.cypress.io/guides/component-testing/component-framework-configuration#React-with-Vite

**Comment by manishagupta016** [comment]
yes

**Comment by kaungsithar** [comment]
Since Cypress runs in Browser environment, it does not have access to node.js's `process.env`. 
We can put virutal `process.env` variable for cypress tests. Since you are running component tests, we can put following workaround in /cypress/support/component.js

```
process = process || {env:{}};
process.env = process.env || {};
```

**Comment by manishagupta016** [comment]
I have added vite-define-envs-plugins
and added this in plugins
new viteDefineEnvs(["REACT_APP_SC_ATTR", "SC_ATTR"], "process.env")
