### ISSUE TITLE
How to use pseudo-elements in `attrs`

### ISSUE THREAD

**Issue by LIMPIX31** [styled-components/styled-components#3805]
## Environment
 - OS: Windows 10 10.0.19044
 - CPU: (4) x64 Intel(R) Core(TM) i5 CPU         750  @ 2.67GHz
 - Memory: 1.62 GB / 7.99 GB
## Binaries:
 - Node: 18.7.0 - C:\Program Files\nodejs\node.EXE
 - Yarn: 1.23.0-20220130.1630 - C:\Program Files\nodejs\yarn.CMD
 - npm: 8.17.0 - C:\Program Files\nodejs\npm.CMD
## Version
styled-components: 5.3.5

## Reproduction

https://codesandbox.io/s/sweet-glitter-81kbwu?file=/src/App.js

## Steps to reproduce
Just look

## Expected Behavior
after, before should work

## Actual Behavior
SC just ignores them

**Comment by LIMPIX31** [comment]
It seems to be related to React. Are there any workarounds?

**Comment by agriffis** [comment]
This is a misunderstand of how `.attrs` works. It adds or modifies props to the component. What you have created here is a `style` prop, and inline styles don't support pseudo elements (this isn't a React or styled-components thing, it's just how HTML/CSS works).
