### ISSUE TITLE
[Bug] Using as prop on styled function component does not correctly inherit all styles

### ISSUE THREAD

**Issue by crtl** [styled-components/styled-components#3808]
## Environment
```
"@types/styled-components": "5.1.26",
"react": "18.0.0",
"react-dom": "18.0.0",
"react-scripts": "4.0.3",
"styled-components": "5.3.5"
```
I have created a reproduction of the bug in codesandbox here: 
https://codesandbox.io/s/styled-components-inheritance-bug-mlpyjr?file=/src/App.tsx

## Reproduction

```typescript
import "./styles.css";
import styled, { css } from "styled-components";
import { FC, ReactNode } from "react";

// Base button
const ButtonInline = styled.button`
  display: block;
  padding: 0;
  background: none;
  border: none;
  white-space: no-wrap;

  background: blue;
  color: white;
`;

interface IconButtonProps {
  icon?: ReactNode;
}

const IconButton: FC<IconButtonProps> = (props) => {
  const { icon, children, ...rest } = props;

  return (
    <ButtonInline {...rest}>
      {icon && <div className="icon">{icon}</div>}
      {children}
    </ButtonInline>
  );
};

const StyledIconButton = styled(IconButton)`
  padding: 4px;
  margin: 4px 0;

  ${(props) =>
    props.icon &&
    css`
      display: flex;
      align-items: center;
    `}
`;

const PrimaryIconButton = styled(StyledIconButton)`
  // ... other styles
`;

export default function App() {
  return (
    <div className="App">
      <p>All buttons should have blue background and white color</p>
      <ButtonInline>ButtonInline</ButtonInline>
      <StyledIconButton icon="✌">StyledIconButton</StyledIconButton>
      <PrimaryIconButton icon="✌">PrimaryIconButton</PrimaryIconButton>
      <StyledIconButton icon="✌">StyledIconButton</StyledIconButton>
      <p>
        But when passing{" "}
        <code
          style={{
            fontFamily: "monospaced",
            fontSize: "1.2em",
            background: "lightgrey"
          }}
        >
          as
        </code>{" "}
        property styles are ommited
      </p>
      <PrimaryIconButton icon="✌" as="a" href="#">
        PrimaryIconButton Link
      </PrimaryIconButton>
    </div>
  );
}

```

## Expected Behavior
Components should inherit styles in their hirachy or there should be a warning about this behaviour in the docs.

## Actual Behavior
When using `as="a"` on `PrimaryIconButton` the implementation of `StyledIconButton` is not implemented and therefore styles from `ButtonInline` are ommited. If `as` is ommited everything works fine like in the example.

**Comment by LarsEjaas** [comment]
I get the same bug. However, if (referring to the above example) I would use the `StyledIconButton` directly in the component with polymorphism aka the `as` prop - it works just fine.

**Comment by crtl** [comment]
Ive left out some styles in this example but I have other styles for `PrimaryIconButton` too.

**Comment by agriffis** [comment]
@crtl This is not a bug, just a misunderstanding of how styled components works.

When you pass `as` you're overriding the wrapped component, replacing it entirely. If you want that to be handled by `StyledIconButton` instead of `PrimaryIconButton` then you can use [`forwardedAs`](https://styled-components.com/docs/api#forwardedas-prop)

If you don't want to leak those implementation details to callers (as `forwardedAs` inevitably does) then you can wrap it all in a function component that renames `as` to `forwardedAs`, or implements variants, or any number of approaches to abstract the implementation.

**Comment by LarsEjaas** [comment]
> @crtl This is not a bug, just a misunderstanding of how styled components works.
> 
> When you pass `as` you're overriding the wrapped component, replacing it entirely. If you want that to be handled by `StyledIconButton` instead of `PrimaryIconButton` then you can use [`forwardedAs`](https://styled-components.com/docs/api#forwardedas-prop)
> 
> If you don't want to leak those implementation details to callers (as `forwardedAs` inevitably does) then you can wrap it all in a function component that renames `as` to `forwardedAs`, or implements variants, or any number of approaches to abstract the implementation.

Thanks a lot for clearing that up @agriffis 😀
  
I simply didn't know (somehow missed that in the docs)! 

That's incredibly powerful - something I will use for sure  🥳

**Comment by agriffis** [comment]
@probablyup @kitten This could be closed.
