### ISSUE TITLE
Styled Components v6 types breaks react-docgen-typescript prop inference 

### ISSUE THREAD

**Issue by DavidReinberger** [styled-components/styled-components#3813]
Styled Components v6 now have their own type definitions, unfortunately it breaks props inference through react-docgen-typescript.

I've posted this also to the react-docgen-typescript repository however I'm not sure where is the right place, I'll be happy to look in to it more if someone can point me to the right direction.

### v6
**System:**

 - OS: macOS 12.5
 - CPU: (10) arm64 Apple M1 Pro
 - Memory: 108.22 MB / 32.00 GB
 - Shell: 5.8.1 - /bin/zsh

**Binaries:**
 - Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
 - Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
 - npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm

**npmPackages:**
 - styled-components: ^6.0.0-beta.2 => 6.0.0-beta.2 

### v5

**System:**
 - OS: macOS 12.5
 - CPU: (10) arm64 Apple M1 Pro
 - Memory: 99.06 MB / 32.00 GB
 - Shell: 5.8.1 - /bin/zsh

**Binaries:**
 - Node: 16.16.0 - ~/.nvm/versions/node/v16.16.0/bin/node
 - Yarn: 1.22.19 - ~/.nvm/versions/node/v16.16.0/bin/yarn
 - npm: 8.11.0 - ~/.nvm/versions/node/v16.16.0/bin/npm

**npmPackages:**
 - styled-components: ^5.3.5 => 5.3.5

## Reproduction

Here is a repository with v5 - https://github.com/DavidReinberger/storybook-typescript-react-doc-gen-styled-components-5, where it works flawless (even with default exports).
Here is a repository with v6 - https://github.com/DavidReinberger/storybook-typescript-react-doc-gen-styled-components-6

In both repositories, run `npm install && npm run storybook`

## Steps to reproduce
1. Open `ButtonStyled` story
2. Only `as` and `forwardedAs` props are visible3. 

## Expected Behavior
All props are inferred as with version 5.

## Actual Behavior
No props are inferred.

**Comment by DavidReinberger** [comment]
Fixed by #3815

**Comment by macko911** [comment]
It looks like there was a regression and this doesn't work anymore in `6.1.1`
Here's the updated repo, steps to reproduce are the same as in initial post.
https://github.com/macko911/storybook-typescript-react-doc-gen-styled-components-6
