### ISSUE TITLE
Stylesheet ordering issue

### ISSUE THREAD

**Issue by zsherman** [styled-components/styled-components#382]
I may be missing something here, but I'm seeing higher level classes override the styles of more deeply nested classes, I would think that the ordering in the generated stylesheet would match the order of divs within the DOM. Granted, I know that best practice is to apply styles only to the element directly but in some cases (say you're using an external library that generates markup you have no control over), this is not possible. Here's a simple example:

![screenshot 2017-01-17 17 23 43](https://cloud.githubusercontent.com/assets/1152279/22042798/b11196de-dcda-11e6-98ef-b344858a079b.png)

Note that event though the class `ixYHWp` is closer to the `button` element, it's styles are overridden by the `egxZiQ` class higher up the chain.

## Version
1.0.5

## Expected Behavior

More specific class styles should take precedence over styles that are higher up the tree.

## Actual Behavior

Classes higher up the tree take precedence over classes closer to the target element.

**Comment by geelen** [comment]
So, this is a damn complex issue, but what you describe as desirable just isn't possible reliably, sorry. Consider the following:

```js
const X = styled.div`
  button { ... }
`

const Y = styled.div`
  button { ... }
`

const Comp = ({ toggle }) => (
  toggle ?
    <X>
      <Y>
        <button/>
      </Y>
    </X>
    :
    <Y>
      <X>
        <button/>
      </X>
    </Y>
)
```

Depending on the ordering of the CSS, `X` or `Y` will _always_ override the other. So if you try to drive the ordering based on which is _rendered_ first, suddenly the output CSS is dependent on your `toggle` variable. So, potentially, you could have an app where the button looks one way until you refresh the page—suddenly the CSS is regenerated with a different value of `toggle` and the button changes appearance. Or visual bugs that only appear if you start at the homepage then go to login, but not if you click through from an email. Stuff like that. For Styled Components, if we're going to support nested selectors (which I believe are really important), we _have_ to guarantee CSS ordering.

We do that by injecting CSS in the order that the components are **defined**. So, in my above example, `X` comes before `Y` in the source code so _all_ the CSS for `X` are guaranteed to appear before any of the rules for `Y`. If you want to change the order of the CSS, change the order those components are defined or imported.

Thanks for the detailed bug report and screenshot, makes it a lot easier. I'm going to close this issue but feel free to continue the discussion—I have a feeling you won't be the last person to have this question so shoot through any further questions and I can explain.

**Comment by zsherman** [comment]
Ah makes sense, that definitely seems like a challenge to solve @geelen. Thanks for the detailed response! Will continue to think about some ways that this can be solved.

**Comment by geelen** [comment]
Might be worth having a read of #351 too. Also, the very first issue on this repo was me grappling with this problem: #1 😄 

CSS sometimes just doesn't play ball!

**Comment by shaman-apprentice** [comment]
First of all thanks for SC!

I have a very similar issue, where the rendering order is missleading. I want to change the appearance of some element, which is genereated by an external library and I know its class name in advance. Having these elements nested has surprising effects -  a simplified example is the following:

 ```
const StylesForExternalLib = styled.div`
	.someElemWithClassNameGeneratedFromExternalLib {
		color: ${ props => props.color};
	}
`; 

class SCNestedClasses extends React.Component {
	
	constructor(props) {
		super(props);
		this.state = {outerColor: 'blue'}
	}
	
	render() {
		return <StylesForExternalLib color={this.state.outerColor}>
			<div className="someElemWithClassNameGeneratedFromExternalLib"
			 	onClick={() => this.setState({ outerColor: 'red' })}
			>
				blue and onClick red
				
				<StylesForExternalLib color='green'>
					<div className="someElemWithClassNameGeneratedFromExternalLib">
						static green
					</div>
				</StylesForExternalLib>
			</div>
		</StylesForExternalLib>
	}
}; 
 ```

When clickling on the div, both change to red. The "SC-class" with red wasn't needed before and therefore is added at the end and overriding all nested elements - which is unfortune. 

I can help myself throug adding a prop like in the following, but that does only work for one nested elem and not a nested elem within a nested elem... (besides it is hacky / I don't like it)
`${ props => props.color} ${ props => props.isNested? '!important': '' };`
 
Some mechanism like `!!important` wins over `!important` would be nice...

Also this topic is close, maybe some idea / planed features for this kind of stuff? I am realy unsatisfied, that nesting is such error prone in css and hence also in SC :(

**Comment by mxstbr** [comment]
If you n eed more specificity use the `&&&` hack:

```JS
const StylesForExternalLib = styled.div`
  &&&& .someElemWithClassNameGeneratedFromExternalLib {
    color: ${ props => props.color};
  }
`;
```

This will add the components' className at the start three times, thus bumping the specificity a lot.

**Comment by shaman-apprentice** [comment]
Awesome. In the case that someone is interested in a trick like this: `${ props => '&'.repeat(props.importance) }` is exactly what I meant with 

> !!important wins over !important

(Also this feels somehow hacky to me, it does the trick). Thanks alot!
