### ISSUE TITLE
How to implement SSR rendering in Next.js 13? 

### ISSUE THREAD

**Issue by damassi** [styled-components/styled-components#3853]
Given the new layouts functionality where `_app` and `_document` are no longer used, how does one implement SSR rendering? There isn't a clear way to implement `ServerSideStylesheet`. 

Thoughts?

**Comment by manak1** [comment]
this might help you 👀
https://beta.nextjs.org/docs/styling/css-in-js#styled-components

**Comment by damassi** [comment]
Perfect @manak1! Just what I was looking for. Thanks; will close this.
