### ISSUE TITLE
Custom theme properties with typescript cause a TypeError

### ISSUE THREAD

**Issue by Sletheren** [styled-components/styled-components#3859]
I'm facing an issue when trying to use styled-components with typescript and gatsby,
to describe the issue, I have a theme with custom properties,

```
export type Theme = {
  cuteColor: string;
  typography: {
    fontFamily: string;
  }
  bgs: {
    black: string;
  }
}

const theme: Theme = {
  cuteColor: `#8E61FF`,
  bgs: {
    black: '#000'
  },
  typography: {
    fontFamily: 'monospace'
  }
};

export default theme;
```

I also have a definition type for styled-components, this is my `styled.d.ts`:

```
import 'styled-components';
import { Theme } from './styles/theme';

declare module 'styled-components' {
  export interface DefaultTheme extends Theme {}
}
```

I get this error: **`WebpackError: TypeError: Cannot read properties of undefined (reading 'black')`**

As you can notice, the error only happens when there is nested properties in the theme, the TS compiler doesn't know about them.

## Environment

 - OS: macOS 12.2
 - CPU: (10) arm64 Apple M1 Pro
 - Memory: 118.27 MB / 16.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
 - Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.2/bin/yarn
 - npm: 8.19.2 - ~/.nvm/versions/node/v16.14.2/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^2.0.7 => 2.0.7
 - styled-components: ^5.3.6 => 5.3.6
 - 
## Reproduction

[Github repo](https://github.com/Sletheren/gatsby-styled)

To reproduce I've created this repo, just clone it and run:
```
npx gatsby build
```

**Comment by probablyup** [comment]
Are you using `ThemeProvider` to provide your custom theme to your React component tree? It seems like the theme is missing from that error message.
