### ISSUE TITLE
Class added through DOM API gets removed when a styled-component prop changes

### ISSUE THREAD

**Issue by 50bbx** [styled-components/styled-components#3861]
This is a bug report.

## Environment
This bug is not related to an environment. Anyway, here's mine:
```## System:
 - OS: macOS 12.6
 - CPU: (8) arm64 Apple M1 Pro
 - Memory: 93.45 MB / 16.00 GB
 - Shell: 3.2.57 - /bin/bash
## Binaries:
 - Node: 16.14.2 - /usr/local/bin/node
 - Yarn: 1.22.19 - /opt/homebrew/bin/yarn
 - npm: 8.19.0 - ~/projects/shopify-store-theme/shopify-react/node_modules/.bin/npm
 - Watchman: 2022.09.05.00 - /opt/homebrew/bin/watchman
## npmPackages:
 - babel-plugin-styled-components: ^2.0.7 => 2.0.7 
 - styled-components: ^5.3.5 => 5.3.5 
```

## Reproduction
This is an interactive codesandbox, you can find steps inside the Codesandbox and down below

https://codesandbox.io/s/priceless-liskov-ofhzb7?file=/src/App.js

## Steps to reproduce
1. Add a class to any styled-component using the DOM API (`classList.add` for example)
2. Change a prop of the same styled-component
3. The class added in step one disappears

## Expected Behavior
Class added in step 1 should persist

## Actual Behavior
Class gets removed from the DOM element

I could not find any similar issue. 

My real-case scenario is a styled-component `img` tag using [lazysizes](https://github.com/aFarkas/lazysizes) with `lqip`. `lazysizes` adds a `.ls-is-cached` that is useful to avoid repeating the blur effect every time the image is shown on the screen. But since the `img` is a styled-component and `display` none/block is controlled through a prop, the `.ls-is-cached` class gets removed and the blur effect is show again and again

**Comment by probablyup** [comment]
This is a general React issue, not specific to styled-components. When you use libraries that modify the DOM outside of React, you always risk those changes being overwritten as React re-renders and detects an HTML attribute discrepancy. The  solution is to write some sort of adapter code so React is injecting the class itself.
