### ISSUE TITLE
TypeError: styled.button is not a function

### ISSUE THREAD

**Issue by keshavinvygo** [styled-components/styled-components#3862]
I am building a react ui library with styled-components, I am using rollup to build it. When i use the library with nextJs i get below error 

`TypeError: styled.button is not a function`

This is component i am exporting from the library.
```
export const StyledButton = styled.button`
  background-color: red;
`;
```

## System:
 - OS: macOS 12.3
 - CPU: (8) arm64 Apple M1 Pro
 - Memory: 71.52 MB / 16.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 16.18.0 - ~/.nvm/versions/node/v16.18.0/bin/node
 - Yarn: 1.22.19 - /usr/local/bin/yarn
 - npm: 8.19.3 - ~/.nvm/versions/node/v16.18.0/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^2.0.7 => 2.0.7 
 - styled-components: ^5.3.6 => 5.3.6 

## Steps to reproduce
Import the package in nextJs application, and use the above component.
## Expected Behavior
Component should render button.
## Actual Behavior
Throwing error
`TypeError: styled.button is not a function`

**Comment by keshavinvygo** [comment]
This is generated with i build the library
```
import * as React from 'react';
import styled from 'styled-components';

const StyledButton = styled.button`
  background-color: red;
`;

const Button = ({
  variant = 'primary'
}) => /*#__PURE__*/React.createElement(StyledButton, {
  variant: variant
}, "Submit");

export { Button };

```

**Comment by probablyup** [comment]
Probably something to do with how imports are resolved in your project setup :/

Pretty hard to help without more information and ideally a repo to look at

**Comment by StuartMorris0** [comment]
Did you resolve @keshavinvygo I have literally the same thing 👍

**Comment by janeksmielowski** [comment]
Same for me..

**Comment by keshavinvygo** [comment]
Hi, I solved the above issue by some hack. Check the below code.

```
import styled from 'styled-components';

const MyStyled: typeof styled = typeof styled === 'function' ? styled : styled.default;

export default MyStyled;
```

and then instead of importing styled from "styled-components" use below import

```
import styled from './MyStyled';
```

**Comment by mkossoris** [comment]
Also facing the same exact problem with our component lib.

**Comment by dgdosen** [comment]
the question is - why does:
`import { styled } from 'styled-components';`
work?

**Comment by aomini** [comment]
> the question is - why does: `import { styled } from 'styled-components';` work?

yeah
