### ISSUE TITLE
A vulnerability reported by OSSIndex - [sonatype-2022-2249] CWE-506: Embedded Malicious Code

### ISSUE THREAD

**Issue by albertwangnz** [styled-components/styled-components#3876]
## Reproduction

A vulnerability reported by OSSIndex - [sonatype-2022-2249] CWE-506: Embedded Malicious Code
https://ossindex.sonatype.org/component/pkg:npm/styled-components@5.3.6
https://ossindex.sonatype.org/vulnerability/sonatype-2022-2249?component-type=npm&component-name=styled-components

Below is a comment from OSSIndex developer.
https://github.com/OSSIndex/vulns/issues/328#issuecomment-1287175491
For sonatype-2022-2249:
The `styled-components` package has an Unintended Behavior. The `postinstall.js` file looks for users using a `ru` time-zone to show a political protest message using the `console.warn()` function. Also, the absence of this file in the 5.3.4 version causes a crash when the package is installed.

Can anybody have a look? Thank you.

**Comment by probablyup** [comment]
How is the code malicious, exactly? It’s console log with a vendored message. Nice try, Russia.
