### ISSUE TITLE
vulnerability in styled-components@5.3.6

### ISSUE THREAD

**Issue by juliocarneiro** [styled-components/styled-components#3879]
As Snyk accuses there are vulnerabilities in styled-components, would it be possible to fix them?

Affected versions of this package are vulnerable to Undesired Behavior via the postinstall.js file which looks for users using a ru time-zone to show a political protest message using the console.warn() function. Also, the absence of this file in the 5.3.4 version causes a crash when the package is installed.

https://security.snyk.io/package/npm/styled-components/5.3.6

**Comment by DavidReinberger** [comment]
Once again, not a vulnerability, just a statement ;)

**Comment by mikeglaz** [comment]
Yes, this security vulnerability needs to be fixed.
