### ISSUE TITLE
Support pseudo element?

### ISSUE THREAD

**Issue by rohmanhm** [styled-components/styled-components#388]
Hi are you support pseudo element like `::before` and `::after`?
I you not support, please give me a solution to keep use it.
Thanks

**Comment by k15a** [comment]
> Within a styled component, we support all of CSS, including nesting – since we generate an actual stylesheet and not inline styles, whatever works in CSS works in a styled component!

Should be supported.

**Comment by rohmanhm** [comment]
sorry my bad https://github.com/styled-components/styled-components/blob/master/docs/css-we-support.md

**Comment by brooksbecton** [comment]
Here is the updated link: https://www.styled-components.com/docs/api#supported-css

**Comment by LAITONEN** [comment]
I don't see any pseudo-elements there. Only pseudo-selectors.

**Comment by adamwgriffin** [comment]
Because I always forget how they work, and I always google, and always arrive on this page, here's how they work:

```javascript
const Example = styled.div`
  /* pseudo selectors work as well */
  &:hover {
    background: palevioletred;
  }
`
```

> Ampersands (&) get replaced by our generated, unique classname for that styled component

**Comment by nahankid** [comment]
Hi, do props work in pseudo elements?

**Comment by k15a** [comment]
Yes

**Comment by worc** [comment]
for anyone else landing here, pseudo selectors are not pseudo elements. and two, if your `&::before` or `&::after` pseudo-element blocks aren't rendering in the browser, add a content property to them.

**Comment by fabb** [comment]
Note that when you use `&::before` with `content`, you need to add quotes to the value of `content`, otherwise the text does not get applied correctly.

**Does not work:**
```
&::before {
    content: blah;
}
```
**Works:**
```
&::before {
    content: "blah";
}
```
**Does not work:**
```
&::before {
    content: ${p => 'blah'};
}
```
**Works:**
```
&::before {
    content: "${p => 'blah'}";
}
```

**Comment by mhssmnn** [comment]
Also note that if you're using [Style Objects](https://www.styled-components.com/docs/advanced#style-objects), you must wrap your content in extra quotes:

**Does not work:**
```js
{
  '&::before': {
    'content': 'blah'
  }
}
```

**Works:**
```js
{
  '&::before': {
    'content': '"blah"'
  }
}
```

**Comment by corysimmons** [comment]
@mhssmnn Actual hero. I never would've figured that out.

**Comment by ridoansaleh** [comment]
```js
export const Input = styled.input`
  display: block;
  padding: 8px;
  width: 24px;
  height: 24px;
  border: 1px solid
    ${props => (props.error ? COLORS.ERROR : COLORS.BORDER_FIELD)};
  font-size: 15px;
  &:checked {
    input:after {
      display: block;
    }
  }
`;
```
I am not sure, will this work. I put nested pseudo selector here.

**Comment by ygorbunkov** [comment]
Just in case someone uses object notation together with empty `content` of `:before` and `:after`, make sure you pass empty string all the way down:
**Won't work:**
```js
export const Input = styled.input(
   ..
   '&:before': {
      content: '',
      ..
   }
)
```
**Will work:**
```js
export const Input = styled.input(
   ..
   '&:before': {
      content: '""',
      ..
   }
)
```
