### ISSUE TITLE
Upgrading react dependency to 18.1

### ISSUE THREAD

**Issue by HainesR11** [styled-components/styled-components#3892]
Hi 

Im currently getting a dependency conflict issue with styled components. there is a small work around however it cause other issues for other dependencies.

Is there way that the styled component repo can upgrade its react dependent to use react 18.1 and not 16.8?

### System:
 - OS: macOS 12.6.1
 - CPU: (10) arm64 Apple M1 Pro
 - Memory: 84.59 MB / 32.00 GB
 - Shell: 5.8.1 - /bin/zsh
### Binaries:
 - Node: 18.9.0 - ~/.nvm/versions/node/v18.9.0/bin/node
 - Yarn: 1.22.19 - /opt/homebrew/bin/yarn
 - npm: 9.1.3 - ~/.nvm/versions/node/v18.9.0/bin/npm
 - Watchman: 2022.12.12.00 - /opt/homebrew/bin/watchman

## Reproduction

https://codesandbox.io/s/styled-components-base-gc367

## Steps to reproduce

1. create react native repo using latest react version
2. npm install styled components
3. observe behaviour 

## Expected Behavior

Install with no issues 

## Actual Behavior

dependancy issue with react, using '>=16.8.0' in styled components and 18.1.0 in personal repo

![image](https://user-images.githubusercontent.com/58213900/207601910-7e5be474-283e-418d-bb78-0059ecd54ead.png)

<img width="441" alt="image" src="https://user-images.githubusercontent.com/58213900/207604955-8add6912-a1d2-4629-81b0-8b079df52f75.png">

**Comment by probablyup** [comment]
It's quite a big project... the streaming bits are currently the most complicated portion that I haven't had time/energy to work on. #3658 #3765

**Comment by beamerrr2** [comment]
Im having the same issue how did you fix?

**Comment by beamerrr2** [comment]
This dependency worked for me: npm install react@latest react-dom@latest.

**Comment by macro0000** [comment]
![image](https://user-images.githubusercontent.com/25545246/218401937-7110c0a1-5d73-4123-9125-cc25f6426a61.png)
(￣m￣）whY

**Comment by berkdeveci** [comment]
I reinstalled with Yarn and it was fixed

**Comment by arnoldc** [comment]
im still encountering this issue
i dont think this is solved
