### ISSUE TITLE
Can't use <use> element with styled-components

### ISSUE THREAD

**Issue by aaroniker** [styled-components/styled-components#3896]
## Environment
```
## System:
 - OS: macOS 12.4
 - CPU: (8) arm64 Apple M1
 - Memory: 100.47 MB / 16.00 GB
 - Shell: 5.8.1 - /bin/zsh
## Binaries:
 - Node: 16.15.1 - /usr/local/bin/node
 - Yarn: 1.22.10 - ~/.npm-global/bin/yarn
 - npm: 8.11.0 - /usr/local/bin/npm
## npmPackages:
 - styled-components: ^5.3.6 => 5.3.6 
```
## Reproduction

Trying to use the `<use>` element with styled-components: `const Test = styled.use``;`

https://codesandbox.io/s/styled-components-base-forked-8n4idp

## Error
```
_styledComponents.default.use is not a function
```

**Comment by probablyup** [comment]
Can you add it to the list in [`domElements.ts](https://github.com/styled-components/styled-components/blob/main/packages/styled-components/src/utils/domElements.ts)`?
