### ISSUE TITLE
customSyntax for Stylelint v14+

### ISSUE THREAD

**Issue by karlhorky** [styled-components/styled-components#3897]
Hi there 👋 First of all, thanks again for all of your work maintaining Styled Components and the ecosystem, really amazing!

Given [the bleak situation with Stylelint v14+ and Styled Components / Emotion](https://github.com/styled-components/stylelint-processor-styled-components/issues/278) (TLDR: [`stylelint-processor-styled-components` is deprecated](https://github.com/styled-components/stylelint-processor-styled-components/issues/278) and archived, [`@stylelint/postcss-css-in-js` will probably be deprecated](https://github.com/stylelint/postcss-css-in-js/issues/225) ([second reference](https://github.com/stylelint/stylelint/issues/4761#issuecomment-962597291), [third reference](https://github.com/stylelint/stylelint-demo/issues/343#issuecomment-1358789510)), it seems that one of the next releases will probably mean the end of working Stylelint tooling for Styled Components and Emotion.

There's a lot of confusing information out there, but the best, least broken config for now is [`processors: ['stylelint-processor-styled-components']` + `customSyntax: 'postcss-scss'`](https://github.com/styled-components/styled-components/issues/3607#issuecomment-1000937952).

I would suggest the following things to avoid tooling breakages:

1. As a first step towards keeping a healthy ecosystem, I would ask that Styled Components maintainers consider unarchiving [the `stylelint-processor-styled-components` repo](https://github.com/styled-components/stylelint-processor-styled-components) - I'm not suggesting to provide any support for this - it can be maintained by selected community members, but @alexander-akait's [issue about deprecating the package](https://github.com/styled-components/stylelint-processor-styled-components/issues/278) does not seem valid anymore, now that [`@stylelint/postcss-css-in-js` will be deprecated](https://github.com/stylelint/postcss-css-in-js/issues/225)
   <img width="959" alt="Screenshot 2022-12-20 at 11 40 15" src="https://user-images.githubusercontent.com/1935696/208647831-07fe686b-f392-4427-9c00-a1c462ea0389.png">
2. In a concerted effort with Styled Components, Emotion and Stylelint maintainers, a new `customSyntax` should be developed for Stylelint v14+ (this is the main point of this issue) - this [may be potentially based on `postcss-lit`](https://github.com/stylelint/postcss-css-in-js/issues/225#issuecomment-1015444188), [@43081j even started on a `customSyntax` for Styled Components here](https://github.com/stylelint/postcss-css-in-js/issues/225#issuecomment-1237294191)
3. Re-archive [the `stylelint-processor-styled-components` repo](https://github.com/styled-components/stylelint-processor-styled-components) once there is a stable `customSyntax` option that is not `@stylelint/postcss-css-in-js`

cc @probablyup @alexandernanberg @SukkaW @mxstbr @agriffis (Styled Components maintainers) @emmatown @Andarist @srmagura (Emotion maintainers) @alexander-akait @ybiquitous @jeddy3 (Stylelint maintainers) @43081j (`postcss-lit` maintainer)

Prior art:

- https://github.com/styled-components/styled-components/issues/3607
- https://github.com/styled-components/styled-components/discussions/3707
- https://github.com/stylelint/stylelint-demo/issues/343
- https://github.com/emotion-js/emotion/issues/2695

## Reproduction

https://github.com/styled-components/styled-components/issues/3607#issuecomment-1321151513

## Steps to reproduce

Try to reliably set up Stylelint v14+ with Styled Components or Emotion

## Expected Behavior

It works reliably and easily with a non-deprecated, non-archived package

## Actual Behavior

It works partially with deprecated and/or archived packages (but will probably break in the future)

**Comment by 43081j** [comment]
I had a play around with the newly extracted css-in-js core and it seems to work. 

I don't have a styled components repo myself though so could do with some help there. 

We also need to decide where this package lives. Do the styled components maintainers want to own it in this monorepo? If not, I'm happy to own it. Although I don't use styled components myself.

**Comment by 43081j** [comment]
ok some christmas hackery lead to me just getting it done:

https://github.com/43081j/postcss-styled-components

if someone can try it out, that'd be super helpful. the readme should be fairly accurate on how to setup stylelint at least.

if the styled-components maintainers want to absorb the package into the monorepo some day, i'd probably be open to that.

**Comment by karlhorky** [comment]
Omg thanks so much @43081j ! 🙌 🎉 Best Christmas present ever! 🎁 🎄

> if someone can try it out, that'd be super helpful

I will switch over to this in [our Stylelint config](https://github.com/upleveled/eslint-config-upleveled/blob/main/templates/stylelint.config.cjs) that we also get our students to install! So starting in January, you'll have at least 30 new users haha

**Comment by 43081j** [comment]
what'll be interesting too is to understand the correct way to parse something like SASS (as in your current config).

@ai maybe you can shed some light on that? if i have a custom syntax for _extracting_ css-like source from non-css files (as in this case), where's the correct place to then tell postcss how to understand something like SASS? does it mean you'd need to chain two custom syntaxes? or should the SASS plugin _not_ be a custom syntax?

**Comment by ai** [comment]
@43081j do you mean that somebody put SASS into CSS-in-JS? Can you show me an example of this syntax?

**Comment by 43081j** [comment]
yes exactly @ai 

currently, postcss-lit and postcss-styled-components allow you to configure postcss with `customSyntax: "postcss-lit"` for example. this is really for the sole purpose of telling postcss how to pull CSS out of js-based syntaxes.

for example, the lit one understands stuff like this:

```ts
class MyElement extends LitElement {
  static styles = css`
    .foo { color: hotpink; }
  `;
}
```

the custom syntax extracts the `.foo { color: hotpink; }` stylesheet for postcss and stringifies it back into its original JS.

same for postcss-styled-components.

the bit im not sure of is what if someone has SASS or some other CSS-like syntax _inside_ their JS?

at that point, we want to tell postcss two things:

* how to understand JS files
* how to understand the CSS pulled out of those files (or out of a regular CSS file, could be a mixture)

**Comment by ai** [comment]
We need to create syntax for each language in CSS-in-JS. Something like `postcss-in-js/sass`.

Or you can configure your CSS-in-JS parser like `require('postcss-in-js')(require('postcss-scss'))`

All ways look too tricky in my opinion.

**Comment by 43081j** [comment]
in future it may be an idea to split the two concerns up in postcss:

* a "file syntax" for telling postcss how to read a particular file type
* a "css syntax" for telling postcss how to read a particular source string (which was extracted by a file syntax)

for now, maybe it would be sensible that custom syntaxes in these cases accept a sub-syntax.

i.e. someone using `postcss-lit` would have the option to specify an underlying syntax we should use (e.g. `postcss-scss`).

not sure the best place to expose that, though. since the `customSyntax` is a string, there's no obvious place to pass options into one without using JS.

**Comment by 43081j** [comment]
@karlhorky ive opened 43081j/postcss-js-core#1 to track this. until i figure that out, you may run into problems since it looks like you use SASS. switching to the syntax i published would likely cause that SASS support to vanish accidentally until i solve that issue.

will move that particular discussion over there for now

**Comment by 43081j** [comment]
@karlhorky ive published postcss-styled-components 0.2.0. if you could try that out, that'd be super helpful

basically you should be able to do this in theory, in your postcss config:

```ts
{
  "syntax": "postcss-styled-components/scss"
}
```

or in stylelint config:

```ts
{
  "customSyntax": "postcss-styled-components/scss"
}
```

i dont have a real world repo to test this stuff in right now so if someone can try it out, that'd be great

**Comment by karlhorky** [comment]
@43081j will do, I'll test it in [our Next.js example project](https://github.com/upleveled/next-js-example-fall-2022-vienna-austria/) (eg. installing the dependencies and changing [the `stylelint.config.cjs` file](https://github.com/upleveled/next-js-example-fall-2022-vienna-austria/blob/main/stylelint.config.cjs)) and let you know!

[The Stylelint check is built in to GitHub Actions](https://github.com/upleveled/next-js-example-fall-2022-vienna-austria/blob/main/.github/workflows/test-playwright-deploy-fly-io.yml#L42-L43C19)

**Comment by jeddy3** [comment]
> ok some christmas hackery lead to me just getting it done:

That's fantastic, thank you @43081j!

I'll update the [`stylelint@15.0.0` (out soon) migration guide](https://github.com/stylelint/stylelint/blob/v15/docs/migration-guide/to-15.md) to mention it as we're removing support for processors in it.

**Comment by 43081j** [comment]
no worries. once i get some more feedback from usage of it, ill push it towards 1.0. pretty happy with the test coverage etc but curious how well it works in the wild (in terms of ease-of-use too).

**Comment by karlhorky** [comment]
@43081j trying this out now, running into some first problems - I reached out to you on Twitter, but will also post about it in the PR for the new `less` / `scss` entrypoints:

- https://github.com/43081j/postcss-styled-components/pull/1

**Comment by hudochenkov** [comment]
I finally finished PostCSS syntax for CSS-in-JS like styled-components.

- Supports full spectrum of styled-components syntax.
- Interpolations in any places.
- Deeply nested interpolations.
- Parses TypeScript.
- Extensively tested.

https://github.com/hudochenkov/postcss-styled-syntax

**Comment by karlhorky** [comment]
Closing this, since there are now 2 actively-developed custom syntaxes for Stylelint v14+ 🙌
