### ISSUE TITLE
Issue with styled component using pnpm 7 version

### ISSUE THREAD

**Issue by YKalashnikov** [styled-components/styled-components#3898]
**What is happening?**

I have a monorepo (pnpm)
When i use pnpm version 7 and node version 18, the styled component are not able to access the theme object that is passed to `ThemeProvider`

 `<ThemeProvider theme={theme}>`

i can see that we are passing the theme object and the value, but when i console log the theme in the one of the styled components the theme object is empty

**Error message**

![Screen Shot 2022-12-21 at 3 18 58 PM](https://user-images.githubusercontent.com/26804486/209021690-febc834c-6098-4526-bc19-f68f241cddcb.png)

I don't face that issue if i use pnpm 6

**Comment by probablyup** [comment]
Hmm, I'd check that multiple versions of s-c aren't installed or something. That's the only matching scenario I can think of that would be the product of a bundler change.

**Comment by YKalashnikov** [comment]
I've tried it previously but still not working with pnpm 7
