### ISSUE TITLE
Mismatch between SSR and CSR results is incorrect className assignment

### ISSUE THREAD

**Issue by dianadobra-joy** [styled-components/styled-components#3899]
## System:
 - OS: macOS 13.0.1
 - CPU: (10) arm64 Apple M1 Max
 - Memory: 6.02 GB / 32.00 GB
 - Shell: 5.8.1 - /bin/zsh
## Binaries:
 - Node: 16.10.0 - ~/.nvm/versions/node/v16.10.0/bin/node
 - Yarn: 1.22.19 - /opt/homebrew/bin/yarn
 - npm: 7.24.0 - ~/.nvm/versions/node/v16.10.0/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^2.0.7 => 2.0.7 
 - styled-components: 5.3.6 => 5.3.6 

## Reproduction
If there is a mismatch between SSR and CSR (e.g. an error picked up while ssr but not on csr) and a component is loaded conditionally based on the mismatch data, then the server will not render the component, but the client will try to render it. In this case, instead of recompiling the css class of the missing component, csr uses the class of its sibling if the element type is the same, resulting in an incorrect class assignment.
This behavior is applied by styled components when dealing with csr and ssr mismatch.
Here is a code sandbox to emphasize the bug: https://codesandbox.io/s/black-voice-ghqr5u?file=/webpack.config.js

## Steps to reproduce
1. Setup SSR in react using react hydrate
2. Create 2 styled-components for the same html element, but with different properties
3. Assume there is an error during server rendering but not while client-side rendering. (Could come from an http request)
4. Render a styled component conditionally only during the client-side rendering

## Expected Behavior
1. Styled component A is missing on the server-side rendering
2. Styled component A  is rendered during client-side rendering
3. The css class of component A is attached correctly during client-side rendering

## Actual Behavior
1. Styled component A is missing on the server-side rendering
2. Styled component A  is rendered during client-side rendering
3. The css class of component A is attached incorrectly. Component A receives the class name of its closest sibling instead of its class name
4. Component A is rendered with incorrect styling.

**Comment by probablyup** [comment]
This isn't a bug, you need to render the same HTML server side and client side and do any modifications after mount.
