### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by geelen** [styled-components/styled-components#39]
This is really bugging me. How do we configure `styled-components`?

We need a way to use `className`-based styling vs `styled`-based styling for Native, but so far we talked about doing two entry points

```js
import styled from 'styled-components'
import styled from 'styled-components/native'
```

The first returns DOM-based aliases (`styled.div`, `styled.h1`) etc and uses `className` under the hood. The second will return Native aliases (`styled.View`) and use `styles` under the hood. That seems fine, but what about smaller changes like the classname generation?

Do we just do something like:

```js
import styled, { classNameGenerators } from 'styled-components'
styled.configure({
  classNames: classNameGenerators.emojis
})
```

I don't terribly like mutating stuff like this but it seems better than the alternatives. Perhaps we could raise an error if `configure` is called _after_ any styled components are rendered to avoid weird edge cases.

If something like `configure` was ok, we could drop the second entry point for `styled-components/native` and do something like:

```js
import styled from 'styled-components'
import { Text, View } from 'react-native'
styled.configure({
  inline: true,
  alias: [Text, View]
})
```

Not a terribly big fan of that either but it feels better than having a separate entry point for every configuration change. Thoughts?

**Comment by mxstbr** [comment]
One big thing is that configuration should only need to be done for edge cases, not have to be done for every app. I don't think we should have config at all, I'd much rather have strict defaults like Aphrodite. If you want to use emojis, vendor it in and change those two lines of code – I'd rather we do that them have config. 

I like the `/native` entry point thing for ease-of-use  and extendability.

**Comment by geelen** [comment]
Oh no emojis are opt out 🔥😎🔥

**Comment by geelen** [comment]
More to the point, you were talking about supporting non-react things like glimmer/choo. Would they be separate repos or `styled-components/framework` endpoints? I definitely agree that the default config should work for the majority of cases but it does sorta feel like the wider you want styled-components to be applicable the more use cases you're going to have to support.

Case in point, I think `import { StyleSheet, css } from 'aphrodite/no-important'` is particularly bad. Maybe just because the default should _not_ to use `!important` everywhere but partially because you have to specify `/no-important` every time you use the library. Surely there's a better way...

**Comment by geelen** [comment]
Just recording my chat in the Gitter room. Neither of us like this:

```js
// One time setup with default plugins and settings.
jss.setup(preset())
```

Because you have to do it every time. So we definitely want a zero config default.

Radium has a few different methods:

![](https://dl.dropboxusercontent.com/spa/a9i2yebxv7pg2ex/enj6g5g1.png)

Aphrodite has a zero-config approach but exports another entry point for `no-important`: https://github.com/Khan/aphrodite/blob/master/src/no-important.js

I still really dislike it because you have to specify it in every file, but I can't think of any other way to export a zero-config singleton by default and still allow customisation/experimentation. So, I think we should build SC so this is possible:

```jsimport Css from 'styled-components/lib/css'
import Styled from 'styled-components/lib/styled'
import Global from 'styled-components/lib/global'
import Keyframes from 'styled-components/lib/keyframes'

const css = new Css(...options)
const styled = new Styled(...options)
const global = new Global(...options)
const keyframes = new Keyframes(...options)

export { styled as default, css, global, keyframes }
```

This way people are effectively vendoring `index.js` and providing different config to the underlying pieces. We have to change our implementation to support it of course but I think it's worth it. It separates the singleton-export from the underlying functionality neatly.

Folks are left having to do `import styled from '../../styled-components.js'` or set up an alias or something but that's fine. It's the way JS is supposed to work anyway.

Also, we can now use this interface to provide React Native support:

```js
/* styled-components/native.js */
import Css from './constructors/css'
import StyledNative from './constructors/styledNative'

const css = new Css({ nesting: false })
const styled = new StyledNative()

export { styled as default, css }
```

(assuming RN doesn't need global or keyframes). This is good. I like this.

**Comment by geelen** [comment]
Ok yeah the use of `new Css` in my examples doesn't quite work (since it's truly stateless and just a wrapper around the interpolation fragment) but I think I can get the others going.
