### ISSUE TITLE
Feature Request: Issue with attrs.className ordering

### ISSUE THREAD

**Issue by radenkovic** [styled-components/styled-components#3912]
Hi folks,

I am using `styled-components` with tailwind to generate pre-defined components with some classes, however there is this unexpected behavior where instance className is **prepended** instead of **appended**. This prevents from overriding the css, IMO it makes more sense that instances override attrs (which are default values).

Fix should be trivial, if someone can point me to part of the code for `attrs` I can submit the PR with fix myself.

## Steps to reproduce

```js
// Define a styled component
const Btn = styled.button.attrs({ className: 'default-class' })``;

// In react component, omitted for clarity
<Btn className="appended-class">Test</Btn>
```

## Expected Behavior

pay attention the to order of the classes:

```
<button class="default-class appended-class">Test</button>
```

## Actual Behavior
```
<button class="appended-class default-class">Test</button>
```

**Comment by probablyup** [comment]
Here’s the relevant code: https://github.com/styled-components/styled-components/blob/d21a7af6435336f10b7e8d891eef253e1ad30051/packages/styled-components/src/models/StyledComponent.ts#L151

**Comment by Jittoqb** [comment]
hey @probablyup  can you just mention which lines are to be exchanged in the concat operation

**Comment by Jittoqb** [comment]
hey @probablyup can you just review the PR ?

**Comment by probablyup** [comment]
This should be fixed in latest beta

**Comment by EricWVGG** [comment]
When you say "latest beta," is that in reference to v5 or v6? I just encountered this again, I'm on 5.3.9

**Comment by probablyup** [comment]
v6
