### ISSUE TITLE
No politic

### ISSUE THREAD

**Issue by dehimer** [styled-components/styled-components#3929]
Wondered that you mixed politic in code (I just saw these version changes: https://github.com/styled-components/styled-components/releases/tag/v5.3.6)
I love your library and use it during of about 3-4 years, but as Russian I felt negative emotions when I saw that you added text with one-sidedly illuminating the situation about current world events.
To be fair, we should then add the text about the losses and suffering of civilians in the breakaway republics, which have been bombed since the Minsk agreements were concluded
Hope you will remove it

**Comment by ihorHaiduk** [comment]
@dehimer Wondered how one more fascist ruZZian man again tells how and to whom to do what. The creators of this package decide for themselves what they need and what is not. "I felt negative emotions" - is of no interest to anyone here.  Hey man, go to your fascist yandex Reich, create cheburnet and forget about the rest of the world. Your information of bombed need only for RT news, but not in this package. Bye, Z-boy!

**Comment by dehimer** [comment]
Мимо, Игорь

**Comment by dehimer** [comment]
Closing that issue. Because paid haters only will participate in that discussion
