### ISSUE TITLE
Props dependant Inheritance

### ISSUE THREAD

**Issue by alanzanattadev** [styled-components/styled-components#393]
Hi,

I've just discovered styled-components, and it's awesome, great job !
One very cool feature is the composable inheritance like ```const FlexRed = styled(Red)`display: flex` ```.

The thing is, we can set css attributs depending on props, but we can't choose the parent component depending on props.

For example I have an HorizontalLayout and a VerticalLayout, I want a ScrollableLayout component, but I don't want to make HorizontalScrollableLayout and VerticalScrollableLayout, I'd  like to do ```styled(props => props.horizontal ? HorizontalLayout : VerticalLayout)`overflow: auto;`;```

Composition would be so much more powerful with these kind of modularity.

What do you think ? I don't know how styled-components work so I don't know how complicated it is to add the feature

Thank you !

**Comment by k15a** [comment]
You could use the CSS helper.

```JS
import styled, { css } from 'styled-components'

const horizontalLayout = css`
  /* CSS */
`

const verticalLayout = css`
  /* CSS */
`

const ScrollableLayout = styled.div`
  ${props => props.horizontal ? horizontalLayout : verticalLayout}

  overflow: hidden;
`
```

Don't know if this helps you.

**Comment by alanzanattadev** [comment]
It's a workaround, but it doesn't let me reuse the intermediary components as standalone components :/

**Comment by k15a** [comment]
Actually your solution should work if I look twice.

**Comment by alanzanattadev** [comment]
Yes it is indeed :) Thank you !

**Comment by mxstbr** [comment]
That's an amazing solution @k15a!

We should add an example of this to the docs, people are going to love it. What do you think @geelen?
