### ISSUE TITLE
Styled components breaking in page reload on vercel prod

### ISSUE THREAD

**Issue by carlosdarwed** [styled-components/styled-components#3935]
## What is Happening ?

A strange bug is happening when I acess my React SPA application, when running it on localhost, the components there are styled with SC works like a charm, but when building it and delivering it to vercel, when refreshing the page (or pressing f5) some specific componentes lose all of his styles, inputs and buttons to exact.

### What I've tried

- Disabling speedy mode (I'm using create-react-app so i tried putting it on my env in local AND the vercel env variables)
- Changing webpack GENERATE_SOURCEMAP config
- Renaming the global css file written with "createGlobalStyle" function
- Downgrading Styled components version respectively to 5.3.0 and 5.2.3

None of the above worked

## Expected Behavior

When refreshing the page regardless of the content on it, it should keep the styles on components such as buttons and inputs

## Actual Behavior

The styles on buttons and inputs (specifically for some reason) are losing all styles and turning into plain html on page refresh

I can't really bring any code in this situation and is difficult to reproduce the bug since he only appears when pushing the app to production via Vercel, but I do can bring the version of the main tools

React - v18.0.1
Styled-components - v5.3.6
Radix primitives - v1.0.0 (Some of them are at 1.1.2, like radix-select)

Edit: We've noticed that most of the components breaking are inside of a radix modal, maybe there are incompatibilities ? 

I would be thankfull of any help in this issue

**Comment by probablyup** [comment]
@carlosdarwed if you're using nextjs 13 there is a known issue with the setup on their end when bundling for production. I'd recommend using nextjs 12 in the meantime and following their documentation for setting up styled-components when using the "pages" directory. You can see the setup in our sandbox project: https://github.com/styled-components/styled-components/blob/main/packages/sandbox/pages/_document.tsx
