### ISSUE TITLE
Adding style overrides in a theme

### ISSUE THREAD

**Issue by robertedjones** [styled-components/styled-components#3946]
Hi, I'm looking to do the same as asked in this closed issue:

https://github.com/styled-components/styled-components/issues/2381

The old issue referenced a solution that is no longer available so was wondering if anyone had an idea of how to do this?

Thanks in advance.

**Comment by probablyup** [comment]
@robertedjones check out xstyled, it pairs perfectly with styled-components and allows for this sort of thing
