### ISSUE TITLE
Incorrect justify-content autoprefixing in Safari

### ISSUE THREAD

**Issue by 0529bill** [styled-components/styled-components#3947]
## Environment
styled-components 5.3.6

## Reproduction

tested on Safari 15.x.x

https://codesandbox.io/s/red-tree-2ljps0?file=/src/App.js

## Expected Behavior

my code
```js
 display: flex;
 justify-content: end;
```

styled-components turned it into this
```js
display: flex;
-webkit-box-pack: end;
-webkit-justify-content: end;
-ms-flex-pack: end;
justify-content: end;
```

The correct styling should have been:

```js
-webkit-justify-content: flex-end;
-webkit-align-items: flex-end;
```

the problem is first found on issues #626, but now it's still missing the correct -webkit autoprefixed styles.

## Expected Behavior
Stylis autoprefixer should apply the correct -webkit autoprefixed styles

**Comment by probablyup** [comment]
Please check out v6 beta, v5 uses an older version of stylis which is no longer maintained
