### ISSUE TITLE
Attribute fetchpriority doesnt work on <img /> tag with styled object

### ISSUE THREAD

**Issue by Neon2022** [styled-components/styled-components#3948]
I am using styled-component with **STYLED OBJECT**! (so no template literals solution, pls)
Usually attributes pass thru. but in the case of the image (<img /> tag) that is not the case!?

Pls help!!

**Comment by probablyup** [comment]
Please try v6 beta, we no longer filter attributes you pass to your styled components outside of transient props ($ prefix.)
