### ISSUE TITLE
styled-component inline style doesn't match react native component type

### ISSUE THREAD

**Issue by cokepizza** [styled-components/styled-components#3949]
<version>
styled-component: v5.3.6
react: 18.2.0
react-native: 0.71.2

The inline style type of style-component does not match the component style type of react native.

The error is:

import(../node_modules/react-native/Libraries/StyleSheet/StyleSheetTypes").ViewStyle
doesn't match
import(../node_modules/@types/styled-components-react-native/node_modules/@types/react-native/index").ViewStyle

**Comment by thecogmel** [comment]
Same issue here

**Comment by miguelrochajr** [comment]
Same problem here. Since the new react native update, the components does not match anymore. Any solutions?

**Comment by probablyup** [comment]
`@types/styled-components-react-native` this is coming from DefinitelyTyped, you'll need to make your request there. If you use v6 beta we supply our own types there.
