### ISSUE TITLE
styled table not working properly

### ISSUE THREAD

**Issue by ensia96** [styled-components/styled-components#3954]
## Reproduction

explained below.

## Steps to reproduce

.../src/components/Table/index.jsx
```js
import styled from "styled-components";

const Table = styled.table``;

export default Table;
```

.../src/pages/test.js
```js
import Table from "components/Table";

const TestPage = () => {
  return (
    <Table {...{ rules: "rows", frame: "hsides" }}>
      <tr>
        <td>test 1</td>
        <td>test 2</td>
        <td>test 3</td>
        <td>test 4</td>
      </tr>
    </Table>
  );
};

export default TestPage;
```

## Expected Behavior

I thought the code above will work properly.

## Actual Behavior

But, when I gave rules and frame attributes to styled table, it weren't worked.

## Memo

And, when I made custom component with pure html tag, it worked.

I think your styled module not giving rules and frame attribute as props to table.

the code below will explain this case.

.../src/components/Table/index.jsx
```js
const Table = ({ frame, rules, children }) => (
  <table {...{ frame, rules }}>{children}</table>
);

/*
// the code above works just the same as below.

const Table = (props) => <table {...props} />;
*/

export default Table;
```

.../src/pages/test.js
```js
import Table from "components/Table";

const TestPage = () => {
  return (
    <Table {...{ rules: "rows", frame: "hsides" }}>
      <tr>
        <td>test 1</td>
        <td>test 2</td>
        <td>test 3</td>
        <td>test 4</td>
      </tr>
    </Table>
  );
};

export default TestPage;
```

**Comment by probablyup** [comment]
@ensia96 try using v6 beta, we removed the default prop validator which will allow all props to flow through without modification unless using the transient prefix ($)
