### ISSUE TITLE
Dynamic styles are broken for nested &

### ISSUE THREAD

**Issue by termosa** [styled-components/styled-components#3962]
### System:
 - OS: macOS 13.0.1
 - CPU: (8) arm64 Apple M1
 - Memory: 91.41 MB / 16.00 GB
 - Shell: 3.6.0 - /opt/homebrew/bin/fish
### Binaries:
 - Node: 16.19.1 - ~/.local/share/nvm/v16.19.1/bin/node
 - Yarn: 1.22.19 - ~/.local/share/nvm/v16.19.1/bin/yarn
 - npm: 9.5.0 - ~/.local/share/nvm/v16.19.1/bin/npm
### npmPackages:
 - styled-components: ^5.3.8 => 5.3.8 

## Reproduction

https://codesandbox.io/s/broken-styled-components-stylesheet-p89iqp

## Cause

This particular change has caused the issue. Reverting this code fixes the problem.

https://github.com/styled-components/styled-components/commit/44152caa199b0b322aeaf42713804b484208a3e1#diff-878f7ad907eff79126ad6d13a4b5880f894c856d0ee6cf508a3b83632641e7a2R46-R54

## Steps to reproduce

Starting from the version `5.2.0-test.1` this code won't work:
```js
const Title = styled.div`
  .app & {
    text-align: ${(p) => (p.centered ? "center" : "left")};
  }
`;
```

## Expected Behavior

Different rulesets are created for each value of `centered` property values and changing `className` property switches these rulesets.

*v5.2.0-test.0*
![v5.2.0-test.0](https://user-images.githubusercontent.com/494013/223855753-b52a83af-3120-4538-bb45-8dbb7ade0b89.gif)

## Actual Behavior

Both rulesets (with `center` and `left` value) are created and added to the stylesheet with the same class name making one overwrite the other one.

*v5.2.0-test.1*
![v5.2.0-test.1](https://user-images.githubusercontent.com/494013/223855003-2d12c33b-d234-4318-a137-1bf0222a77d0.gif)

**Comment by gopeter** [comment]
I have the same problem, but with a slightly different syntax:

```tsx
export const NavigationWrapper = styled.div<{ $isOpen: boolean; $sidebarWidth: number }>`
  box-sizing: border-box;
  border-right: 1px solid ${(props) => props.theme.palette.border};

  ${(props) => {
    if (!props.$isOpen) {
      return css`
        ${Title} {
          display: none;

          & + ul {
            margin-top: 24px;
          }
        }
    }
  }}
`
```

This works fine in v5, but not in v6, where the conditional css stays at the page, even if the prop has changed.

**Comment by probablyup** [comment]
@gopeter v6 includes a major parsing engine upgrade so if you could post this in #3800 instead that would be appreciated.

**Comment by probablyup** [comment]
This behavior has been removed in v6, please upgrade when you get the chance https://github.com/styled-components/styled-components/releases/tag/v6.0.0-rc.1
