### ISSUE TITLE
Will the styled component be affected if defaultProps is deprecated in react 18.3

### ISSUE THREAD

**Issue by walter-wang314** [styled-components/styled-components#3967]
According to PR https://github.com/facebook/react/pull/25699 in react, likey defaultProps will be deprecated in 18.3 in the Functional Component. Will the styled component be affected if defaultProps is deprecated in react 18.3. Then what is the suggested way to set the default pros since props defined by attrs method can't be overwritten by the prps in the components.

**Comment by probablyup** [comment]
Thanks for bringing this to my attention, I hadn't heard about it.

For `attrs` you can use the function variant syntax and simply spread-apply the props after your defaults so they always win:

```tsx
styled.div.attrs(props => ({ foo: 'bar', ...props }))``
```

**Comment by probablyup** [comment]
To answer your question though, styled-components doesn't make use of the `defaultProps` React feature in v6 (and I think v5 as well.)
