### ISSUE TITLE
Warning: Prop `className` did not match. Server...

### ISSUE THREAD

**Issue by MasterVVorm** [styled-components/styled-components#3996]
Hi! I have and issue with class names using styled with next.js. I have project with 3 workspaces, where one of workspaces is an components library. This library uses styled-components and imports in two other workspaces. I've tried nextjs [recomendations](https://styled-components.com/docs/advanced), tried different babel configurations, like

.bablerc
`{
  "presets": ["next/babel"],
  "plugins": ["babel-plugin-styled-components"]
}`

The issue is still here. Can you help?

**Comment by Sambhav399** [comment]
Use this configuration in your `.babelrc` file

`
{
    "presets": [
        "next/babel"
    ],
    "plugins": [
        [
            "babel-plugin-styled-components",
            {
                "ssr": true,
                "displayName": false,
                "fileName": false,
                "pure": true,
                "minify": true
            }
        ]
    ]
}
`

Also if you are using different repositories having styled-components and using all of them combined in one project then try to resolve alias for that.

For your NextJS project add this in your `next.config.js` file

`
webpack: (config) => ({
        ...config,
        resolve: {
            ...config.resolve,
            alias: {
                ...config.resolve.alias,
                'styled-components': require.resolve('styled-components')
            }
        }
    })
    `

**Comment by MasterVVorm** [comment]
Thank you! Seems it works!
