### ISSUE TITLE
BUG: Unable to resolve module postcss

### ISSUE THREAD

**Issue by andrefangeloni** [styled-components/styled-components#4017]
## System:
 - OS: macOS 13.3.1
 - CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
 - Memory: 53.34 MB / 16.00 GB
 - Shell: 5.9 - /bin/zsh
## Binaries:
 - Node: 16.20.0 - ~/.nvm/versions/node/v16.20.0/bin/node
 - Yarn: 1.22.19 - ~/.nvm/versions/node/v16.20.0/bin/yarn
 - npm: 8.19.4 - ~/.nvm/versions/node/v16.20.0/bin/npm
 - Watchman: 2023.03.13.00 - /usr/local/bin/watchman
## npmPackages:
 - styled-components: ^6.0.0-rc.1
 - react-native: 0.71.8

## Reproduction

Unable to resolve module postcss from <user_directory>/<app_name>/node_modules/styled-components/native/dist/styled-components.native.cjs.js: postcss could not be found within the project or in these directories.

PS: Same behavior on Android and iOS.

## Steps to reproduce

- Start a new project: `npx react-native init awesome_project`;
- Install styled-components `yarn add styled-components`.

## Expected Behavior
- Render the component.

## Actual Behavior
- App shows a red screen with the message below.

App.tsx

```ts
import React from 'react';
import styled from 'styled-components/native';

const Container = styled.View`
  flex: 1;
  align-items: center;
  justify-content: center;
`;

const Title = styled.Text`
  font-size: 28px;
`;

export const App = () => (
  <Container>
    <Title>App</Title>
  </Container>
);

```
![Simulator Screenshot - iPhone SE (3rd generation) - 2023-05-22 at 19 51 50](https://github.com/styled-components/styled-components/assets/51930261/ba075316-82dd-4ca8-a837-94dfe4d9af72)

**Comment by yzalvov** [comment]
`yarn add`ing the `postcss` as a workaround.

**Comment by probablyup** [comment]
Oops, will add it back. Sorry about that.

**Comment by yzalvov** [comment]
@probablyup, thank you! Please clarify how soon should the update be available?
