### ISSUE TITLE
Version 6.0.0-rc.2 regressions

### ISSUE THREAD

**Issue by DavidReinberger** [styled-components/styled-components#4019]
After installing the latest release candidate there are some regressions in term of typing results.

### System:
 - OS: macOS 12.6.5
 - CPU: (10) arm64 Apple M1 Pro
 - Memory: 168.86 MB / 32.00 GB
 - Shell: 5.8.1 - /bin/zsh
 
### Binaries:
 - Node: 18.13.0 - ~/.nvm/versions/node/v18.13.0/bin/node
 - Yarn: 1.22.19 - ~/.nvm/versions/node/v18.13.0/bin/yarn
 - npm: 9.4.2 - ~/.nvm/versions/node/v18.13.0/bin/npm

## Regressions

1. `ref` and HTMLAttributes inference is broken
     - `ref` typing is `any`
     - while using `as`, `ref` is not a valid prop
     - using `as="button"` on a `div` does not correctly infer `onClick` for instance
     - I've identified [this change](https://github.com/styled-components/styled-components/compare/v6.0.0-rc.1...v6.0.0-rc.2#diff-adc775db811d749ad367a5fd61454d85f453f549d088fd97ea1575c3eb3290f4R161-R163) by @justinbhopper as the cause. Rolling back the change solves the issue.

2. Prop inference from `css<props>` is not working on built components.

```typescript

const style = css<{prop?: boolean}>``;

const Box = styled.div`
    ${style}
`

const Usage = () => (
    <Box prop>something</Box>
)
```

In this case `prop` throws 'property does not exists on type...`.  Because the types are not generated correctly when built. Had the fix and lost it down the road 😩... 

3. The new `attrs` implementation by @justinbhopper breaks `css<Props>` with `.attrs` usage and HTML props within `.attrs` factory
    - `attrs` function props are not typed. In the below example `$textVariant` is `any`,
    ```typescript
    styled.label.attrs<TextProps>(({ $textVariant = 'footnote' }) => ({$textVariant}))
    ```
    - I've isolated the above problem to [this line](https://github.com/styled-components/styled-components/commit/d31b393c05947563e804b83b109b845d5fc00220#diff-330e887239a86c15b1f5d462583b1ac0f48a8cac1b2a12b0ea1dc015dc75757fR98) and fixed it by replacing the default typing to `((props: ExecutionContext & Props) => Props)`
    - The `css<Props>` problem, is caused by the same line and fixed by the same replacement
    - The HTML attributes within the factory are completely missing can be fixed by `Partial<OuterProps>` to the attrs params factory

Otherwise everything works as expected, can't tell if it is faster overall after the latest PRs. Prop inference with Storybook and `forwardRef` components still don't work...

**Comment by eugene1g** [comment]
One more thing for `rc.2`: it looks like event handlers are no longer typed:
```ts
import {styled} from "styled-components"
const NameField = styled.input``;
const r = <NameField
    defaultValue="test"
    onChange={ev => {   // <-- ev is typed as any
        console.log(ev.target)
    }}
/>
```

**Comment by justinbhopper** [comment]
1. That change appears to actually [have been made by](https://github.com/styled-components/styled-components/pull/4014/commits/83c4b83308cede523cb631ac31752448e5680034) @probablyup, so I want to give him a chance to suggest a fix if he has one in mind.  Reverting the change he made causes other test cases to break.  There's a lot of magic in the PolymorphicComponent type that I haven't wrapped my head around yet.
2. Should this remain a valid test case?  In your example, div doesn't have props defined, so should it inherit the props of the incoming styles without being defined on the div itself?  That doesn't seem correct to me, although admittedly it is allowed in v5.  
3. I agree, changing the `Factory` default to the following appears to fix the issue: `(props: ExecutionContext & Partial<OuterProps> & Props) => Partial<OuterProps & Props>`

**Comment by DonnyVerduijn** [comment]
I can confirm a regression concerning type inference from component props, inside both the attrs method and at consumer sites.

**Comment by probablyup** [comment]
Thanks, can you please add failing tests to https://github.com/styled-components/styled-components/blob/main/packages/styled-components/src/test/types.tsx?
