### ISSUE TITLE
npm ERR! Cannot read properties of null (reading 'edgesOut')

### ISSUE THREAD

**Issue by nishchay7pixels** [styled-components/styled-components#4020]
### System:
 - OS: Linux 5.4 Ubuntu 20.04.6 LTS (Focal Fossa)
 - CPU: (2) x64 Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz
 - Memory: 1.89 GB / 3.84 GB
 - Container: Yes
 - Shell: 5.0.17 - /bin/bash
### Binaries:
 - Node: 19.9.0 - ~/nvm/current/bin/node
 - Yarn: 1.22.19 - /usr/bin/yarn
 - npm: 9.6.3 - ~/nvm/current/bin/npm

## Reproduction
run 
`npm install styled-components `
or 
`npm install --save styled-components`

## Steps to reproduce
run 
`npm install styled-components `
or 
`npm install --save styled-components`

## Expected Behavior
Should start styled-components installation
## Actual Behavior
Getting below error,

> npm ERR! Cannot read properties of null (reading 'edgesOut')
> 
> npm ERR! A complete log of this run can be found in: /home/codespace/.npm/_logs/2023-05-25T20_47_19_271Z-debug-0.log

**Comment by nishchay7pixels** [comment]
Workaround is to specify the version for installation for eg,
`npm install styled-components@5.3.10`

**Comment by probablyup** [comment]
> npm ERR! Cannot read properties of null (reading 'edgesOut')

I've never seen a variable with that name in our codebase, could you provide a codesandbox or similar live reproduction?

**Comment by Sambhav399** [comment]
Issue already existed and resolved.
Please refer https://github.com/styled-components/styled-components/issues/3998.
Thanks.

**Comment by gpoole** [comment]
@probablyup I'm able reproduce by just running the command `npm i styled-components`, both in an existing project I was creating and then an empty directory. The issue occurred with Node 16, 17 and 18. I'm running macOS 12.6.3 on M1.

The stack trace I get with the error for Node 16 is:

```
45 timing idealTree Completed in 2508ms
46 timing command:install Completed in 2513ms
47 verbose stack TypeError: Cannot read properties of null (reading 'edgesOut')
47 verbose stack     at Arborist.[loadPeerSet] (/Users/greg/.nvm/versions/node/v16.13.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1282:38)
47 verbose stack     at async Arborist.[buildDepStep] (/Users/greg/.nvm/versions/node/v16.13.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:930:11)
47 verbose stack     at async Arborist.buildIdealTree (/Users/greg/.nvm/versions/node/v16.13.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:216:7)
47 verbose stack     at async Promise.all (index 1)
47 verbose stack     at async Arborist.reify (/Users/greg/.nvm/versions/node/v16.13.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:149:5)
47 verbose stack     at async Install.install (/Users/greg/.nvm/versions/node/v16.13.1/lib/node_modules/npm/lib/install.js:170:5)
```

I get a similar trace for 18:

```
53 verbose stack TypeError: Cannot read properties of null (reading 'edgesOut')
53 verbose stack     at [loadPeerSet] (/Users/greg/.nvm/versions/node/v18.16.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1307:38)
53 verbose stack     at async [buildDepStep] (/Users/greg/.nvm/versions/node/v18.16.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:929:11)
53 verbose stack     at async Arborist.buildIdealTree (/Users/greg/.nvm/versions/node/v18.16.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:207:7)
53 verbose stack     at async Promise.all (index 1)
53 verbose stack     at async Arborist.reify (/Users/greg/.nvm/versions/node/v18.16.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
53 verbose stack     at async Install.exec (/Users/greg/.nvm/versions/node/v18.16.0/lib/node_modules/npm/lib/commands/install.js:146:5)
53 verbose stack     at async module.exports (/Users/greg/.nvm/versions/node/v18.16.0/lib/node_modules/npm/lib/cli.js:134:5)
```

**Comment by probablyup** [comment]
Should be fixed now that "latest" is set to a normal semver version https://github.com/styled-components/styled-components/releases/tag/v6.0.0
