### ISSUE TITLE
Passing shorthand margin as a prop throw an error on react-native

### ISSUE THREAD

**Issue by dbertella** [styled-components/styled-components#403]
## Version
1.3.0

## Steps to reproduce
Create an element as in the example below and pass a margin prop to it with a string inside.
```
const Styled = styled.View`
    margin: ${props => props.margin};
`;

<Styled margin="50 0" />
```
As a workaround you can call the prop `m`, ex: `<Styled m="50 0" />` and it will work fine.

## Expected Behavior
Should work as expected as a margin shorthand
## Actual Behavior
Throw an error JSON value '50 0' of type NSString cannot be converted to NSNumber

**Comment by IljaDaderko** [comment]
@dbertella I think thats react native related, it doesn't expect string there, but wants numbers `50 0` in your case you could `margin={50}` and apply it as `margin-right / margin-left` a bit annoying, as `margin={50 0}` is invalid :/

**Comment by dbertella** [comment]
I know, but if you pass the props with another name ex `m` instead of `margin` it will work fine.
That's the thing that bugged me.

**Comment by mxstbr** [comment]
This is a bug in [`css-to-react-native`](https://github.com/styled-components/css-to-react-native), mind submitting an issue there? /cc @styled-components/css-to-react-native

**Comment by jacobp100** [comment]
I’m not so sure. I think what’s happening here is that the props used within the component are also passed down to the `<View>`.

React Native passes styles down as direct props, so `<View style={{ margin: 50 }} />` is (unofficially) the same as `<View margin={50} />`.

Effectively, we’re getting `<View style={{ marginTop: 50, marginRight: 0, marginBottom: 50, marginLeft: 0 }} margin="50 0" />`. React Native is trying to convert `margin`, which it can’t.

**Comment by dbertella** [comment]
That's what I thought! I wanted to try it with other css properties but I
didn't have time!

**Comment by dbertella** [comment]
Apparently it's an hidden feature in `react-native` this morning I tried this `<View margin={5} padding={80} borderWidth={10} backgroundColor="red">` and it's working fine as I was adding those styles inlines. I guess it's not a library's related issue then, should we close it?

**Comment by jacobp100** [comment]
It is a library issue. There’s currently very limited support distinguish between props used for styling (which should not be passed down to the target component), and props for the target component.  The current logic is to [filter out all non-DOM props for DOM elements](https://github.com/styled-components/styled-components/blob/19921545762126c750ccdb6735d2a085c6d6258a/src/models/StyledComponent.js#L90).

However, all other elements will have both the props intended for the component *and* styling props passed down.

**Comment by dbertella** [comment]
I think I found out what the problem is. `View` component has this possible `Layout props` https://facebook.github.io/react-native/docs/layout-props.html#props. I'm not sure you can filter them out and if it's what the final user always want though.

**Comment by jacobp100** [comment]
The layout props are intended to be used within in `style`s. It's just a quirk of React Native that they’ll sometimes work when used as direct props.

I’m pretty certain it’s a bug here. Regardless of the behaviour of RN, there will be other components this can affect.

**Comment by f0rr0** [comment]
Opened issue on RN: https://github.com/facebook/react-native/issues/12469

**Comment by f0rr0** [comment]
@mxstbr any updates on this?

**Comment by f0rr0** [comment]
@jacobp100 Any ideas on possible fixes?

**Comment by jacobp100** [comment]
It's hard, because you're ultimately going to have to make a trade-off between developer friendliness and correctness.

One suggestion would be for the developer to define propTypes on their component, and then we only pass on the properties outside of the defined propTypes.

```js
const StyledView = styled(View)`
  margin: ${props => props.margin};
`

StyledView.propTypes.margin = PropTypes.string
```

**Comment by f0rr0** [comment]
@jacobp100 Assuming that the upstream issue is not a bug, shouldn't styled-components match all props with LayoutProps and apply a css-to-react-native transform before passing them to the underlying component?

**Comment by jacobp100** [comment]
I'm not sure that addresses the fundamental issue.

**Comment by ssomnoremac** [comment]
It blew my mind to discover that layout props were actually props and not just styles. I came across [an issue trying to set position shorthands in my library with an array](https://github.com/hyrwork/react-native-row/issues/6). I am able to pass shorthands using arrays still for margin and padding like so: 

     <View margin={[2,4]} />

but not for position, because position is type-checked for the enum `["absolute", "relative"] or [0,1]`. But that's just in my library. Don't know if that kind of thing is even worth trying here.

**Comment by f0rr0** [comment]
There seem to be only 2 possible solutions at the moment:

1. `styled-componenets` asks developers to explicitly declare what props their component depends on and not passing those particular props to the underlying component that gets styled.
2. Apply transformations to all props that are style props and are type checked by `react-native` (e.g. `margin`, `padding` etc.) before passing them to the underlying component.

Implementing 2 would involve figuring out an exhaustive list of such props that are typechecked and maintaining it as new props are added upstream. 1 looks more foolproof and maintainable that way.

**Comment by jacobp100** [comment]
I thought of another way of defining properties in effectively the same way as my last comment. It mostly saves typing.

```js
const DynamicStyles = styled.div`
  @property color, margin;

  color: ${props => props.color};
  margin: ${props => props.margin};
`
```

**Comment by f0rr0** [comment]
@jacobp100 how would you go about defining styles based on a non style prop. 

const DynamicStyles = styled.div`
  @property propMyComponentNeedsToRender, margin;

  color: ${props => (props.propMyComponentNeedsToRender === 'a' ? : '#000000' : '#ffffff')};
  margin: ${props => props.margin};
`

if `propMyComponentNeedsToRender` is not passed to underlying component, it will break. If it is, then we have the same problem we started out with.

**Comment by jacobp100** [comment]
Moving discussion to #439

**Comment by wzup** [comment]
@IljaDaderko 

RN docs https://facebook.github.io/react-native/docs/layout-props.html#margin
It accepts `string`. At least it should.

![screenshot-facebook github io-2018 06 06-17-30-17](https://user-images.githubusercontent.com/3880497/41044666-6d701ece-69af-11e8-9e30-659ab31b949b.png)

**Comment by jacobp100** [comment]
Ya it accepts things like `"5%"` and `"auto"`
