### ISSUE TITLE
Sentry error in 6.0.0-rc.2: "t.flatMap is not a function"

### ISSUE THREAD

**Issue by NicHaley** [styled-components/styled-components#4031]
Our team recently upgraded to `6.0.0-rc.2` and are noticing an intermittent Sentry issue coming from the styled-components esm file: `t.flatMap is not a function`. We had previously been on `6.0.0-beta.11` where this had not been an issue.

## Environment
<img width="333" alt="SCR-20230531-lres" src="https://github.com/styled-components/styled-components/assets/9045634/a009ce32-150e-432d-8cbb-6a2b0a45aa02">

## Reproduction
I have not figured out how to reproduce.

## Steps to reproduce
NA

## Expected Behavior
There should be no Sentry error.

## Actual Behavior
See above.

**Comment by probablyup** [comment]
Needs a polyfill for your users: https://estada.ch/2019/6/10/javascript-arrayprototypeflatmap-polyfill/

You must have some older browsers visiting, support actually looks pretty good https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap
