### ISSUE TITLE
Support container queries

### ISSUE THREAD

**Issue by erikblomqvist-huma** [styled-components/styled-components#4032]
Since container queries are now supported in all major browsers, we've tried implementing it using styled-components. Unfortunately, the output doesn't seem to follow the same rules as media queries.

Example code:
```
const Box = styled.div`
    container-style: inline-size;

    background-color: blue;

    @container (max-width: 600px) {
        background-color: red;
    }
`
```

This results in the following output:
```
.boxClassName {
    container-style: inline-size;

    background-color: blue;
}

@container (max-width: 600px) {
    background-color: red;
}
```

With media queries, nesting styles within the query will correctly output the class name as well.

Is this something planned to be supported in the future?

**Edit:** Looked at the release notes for v6, and noticed that it's going to be supported. How lovely!

**Comment by probablyup** [comment]
Yup it's already supported in v6!
