### ISSUE TITLE
Version 6.0.0-rc.3 regressions

### ISSUE THREAD

**Issue by DavidReinberger** [styled-components/styled-components#4034]
Hey everyone, I think all of the points from `rc.2` were addressed (THANK YOU 🙏), however there are some new regressions I've found.

#### System:
 - OS: macOS 12.6.5
 - CPU: (10) arm64 Apple M1 Pro
 - Memory: 131.08 MB / 32.00 GB
 - Shell: 5.8.1 - /bin/zsh
#### Binaries:
 - Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
 - npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm

## Regressions

1.a Using `as` with `RuleSet<Props>` breaks props inference from the `RuleSet` in Factory components (`styled(Component)`)
https://codesandbox.io/p/sandbox/awesome-rumple-hqmhy3

1.b Prop inference from `RuleSet<Props>` is broken. You have to specify the props within the StyledComponent, therefore simple composability with using these.
https://codesandbox.io/p/sandbox/funny-heyrovsky-1plly2

For instance we are using styled-system and we would have to extend types all the times instead of using the interpolations to infer the types, which worked flawlessly in `beta.15`

2. HTMLProps are not properly carried over when using the following pattern
https://codesandbox.io/p/sandbox/fervent-cannon-4v8of6

I was trying to look for root causes, but the typings are beyond me completely and I barely have the time to put this list together....

**Comment by probablyup** [comment]
Yeah it looks like some of the things I fixed that were actually broken in the DefinitelyTyped version and were undone by the refactoring, namely resolution of `as` prop. Probably will need to roll the type changes in rc.3 back and investigate other fixes.

**Comment by lake2** [comment]
@probablyup autoprefixer seems not to working when I use v6

**Comment by probablyup** [comment]
> @probablyup autoprefixer seems not to working when I use v6

Did you enable it via StyleSheetManager? It's in the [migration guide](https://styled-components.com/docs/faqs#vendor-prefixes-are-omitted-by-default).

**Comment by probablyup** [comment]
Please test RC.5 when you get a chance! Thank you :)
