### ISSUE TITLE
Weak control of the component functionalities?

### ISSUE THREAD

**Issue by coodoo** [styled-components/styled-components#404]
Just had a quick look at the docs and wondering by writing component this way we are putting `styles` first and seems there's no way to write custom functions inside the styled components, is that correct?

For example:

```javascript
<MyStyledText onManulaSelection={handleSelection} onDblClick={handleDblClick} />
```

Is there suggested approach to handle `onManualSelection` and `onDblClick` within the component before triggering the passed in handlers? Thanks.

**Comment by wmertens** [comment]
@coodoo You need to make the component that handles the custom functions and then apply the style to that, e.g. "const MyStyledText = styled(SpecialText)`color: red;`". Remember to pass on the `className`.
