### ISSUE TITLE
There is no prompt for writing css in js

### ISSUE THREAD

**Issue by xiaozhangStuden** [styled-components/styled-components#4044]
## content 

I am a react learner, but today when I was writing css style with css in js, there was no code prompt, I was very painful, I tried many ways to ask the manual only model, search engine, and downgrade the editor can not deal with it, could you please help me? Thank you very much

![image](https://github.com/styled-components/styled-components/assets/94174307/e1fda298-da7f-486d-be43-7b2e445e5df5)

This is the effect without any tips when developing, and I have installed the plugin vscode-styled components, can you help me?

**Comment by usercao** [comment]
![image](https://github.com/styled-components/styled-components/assets/13760476/58a9f9fa-a061-42d9-b6bd-7c4f4ef978f8)
Have you installed this plugin?

**Comment by probablyup** [comment]
@xiaozhangStuden the VS Code plugin linked here is good, but the other option is to write your CSS as object styles:

```tsx
const AibiHeaderWrapper = styled.div({
  display: 'flex',
  width: '100%',
  height: '0.8rem',
  alignItems: 'center',
})
```
