### ISSUE TITLE
Cannot find namespace 'stylis' / Vite

### ISSUE THREAD

**Issue by dwojcik96** [styled-components/styled-components#4051]
Hi,
I'm trying to configure Styled Components V6 with Vite and Storybook and during the build, I get the below error:
```
node_modules/styled-components/dist/models/StyleSheetManager.d.ts:58:21 - error TS2503: Cannot find namespace 'stylis'.
58     stylisPlugins?: stylis.Middleware[];
```

Any solution? Thanks!

**Comment by probablyup** [comment]
Oh hmm I thought we had the types included but `yarn add -D @types/stylis` should take care of it

**Comment by probablyup** [comment]
Will fix it in the next release

**Comment by probablyup** [comment]
Should be fixed in https://github.com/styled-components/styled-components/releases/tag/v6.0.0-rc.6, thanks for using styled-components!

**Comment by twfarnam** [comment]
I am getting this error in 6.0.2, even after explicitly adding `@types/stylis`. I fixed it by adding this to StyleSheetManager.d.ts:

`import stylis from 'stylis';`

**Comment by MattIPv4** [comment]
👋 Also seeing this in 6.0.2
