### ISSUE TITLE
 it looks like an unknown prop "$size" is being sent through to the DOM, which will likely trigger a React console error.

### ISSUE THREAD

**Issue by KilianShen** [styled-components/styled-components#4058]
version:6.0.0
Warning messages still appear when using transient props (`$` prefix for automatic filtering.)
![image](https://github.com/styled-components/styled-components/assets/86402559/22b16117-5673-4c2a-8767-7a3779c84b6e)
![image](https://github.com/styled-components/styled-components/assets/86402559/bcff2443-7b17-4665-859f-29a4016be2c1)

**Comment by probablyup** [comment]
Well, that definitely should not be happening. Will take a look thanks.

**Comment by probablyup** [comment]
Should be fixed in https://github.com/styled-components/styled-components/releases/tag/v6.0.1
