### ISSUE TITLE
createGlobalStyle not working on v6 version.

### ISSUE THREAD

**Issue by sergeu90** [styled-components/styled-components#4060]
Hello everyone. After update from 5.3.11 to 6.0.0. In my code stopped working createGlobalStyle my components.

**Comment by probablyup** [comment]
Need a reproduction to be able to help

**Comment by sergeu90** [comment]
@probablyup  what do you mean two versions?

**Comment by probablyup** [comment]
https://styled-components.com/docs/faqs#duplicated-module-in-node_modules

**Comment by sergeu90** [comment]
<img width="465" alt="image" src="https://github.com/styled-components/styled-components/assets/7217517/91b18a88-1b46-4518-bf50-59c821cd325c">

**Comment by sergeu90** [comment]
If downgrade to v5 version, all work as excepted

**Comment by sergeu90** [comment]
@probablyup  I removed node modules and reinstall and fixed. But i have another issue. Early i passed my props like 
`
  <HiddenButton
          basic
          size="small"
          icon="setting"
          className="mr-0"
          hideOn={410}
        />
`

```
export default styled(({ hideOn, ...props }) => <Button {...props} />)`
  @media only screen and (max-width: ${({ hideOn }) => (hideOn ? `${hideOn}px` : screens.tabletEnds)}) {
    &.button {
      .icon {
        margin: 0!important;
      }

      span {
        display: none;
      }
    }
  }
`;
```

But now props not passed to Button component.

**Comment by sergeu90** [comment]
<img width="399" alt="image" src="https://github.com/styled-components/styled-components/assets/7217517/38574b5b-d94b-4824-940b-86aba77883fb">
if do this it is fixed issue but i have console React does not recognize the `isScrollable` prop on a DOM element. it is example

**Comment by probablyup** [comment]
See https://styled-components.com/docs/faqs#shouldforwardprop-is-no-longer-provided-by-default

**Comment by sergeu90** [comment]
@probablyup  I saw this post. but if i set how in documentation not all props pass to components.

**Comment by woodreamz** [comment]
> See https://styled-components.com/docs/faqs#shouldforwardprop-is-no-longer-provided-by-default

@probablyup I think this section is a little bit misleading because it's not completely restoring the v5 behaviour. v5 is checking the prop **and** the element to render according to [the v5 code](https://github.com/styled-components/styled-components/blob/legacy-v5/packages/styled-components/src/models/StyledComponent.js#L140):

```javascript
const isTargetTag = isTag(elementToBeCreated); // = typeof elementToBeCreated === 'string'
  const computedProps = attrs !== props ? { ...props, ...attrs } : props;
  const propsForElement = {};

  // eslint-disable-next-line guard-for-in
  for (const key in computedProps) {
    if (key[0] === '$' || key === 'as') continue;
    else if (key === 'forwardedAs') {
      propsForElement.as = computedProps[key];
    } else if (
      shouldForwardProp
        ? shouldForwardProp(key, validAttr, elementToBeCreated)
        : isTargetTag
        ? validAttr(key) // validAttr = isPropValid 
        : true
    ) {
      // Don't pass through non HTML tags through to HTML elements
      propsForElement[key] = computedProps[key];
    }
  }
```

isPropValid is only checking if the prop is valid for an HTML tag (and few React props) thus it stops any non HTML attributes.

To restore the v5 behviour, we should use:

```javascript
import isPropValid from '@emotion/is-prop-valid';
import { StyleSheetManager } from 'styled-components';


function MyApp() {
    return (
        <StyleSheetManager shouldForwardProp={(propName, elementToBeCreated) => {
        return typeof elementToBeCreated === 'string' ? isPropValid(propName) : true;
       }}>
            {/* other providers or your application's JSX */}
        </StyleSheetManager>
    )
}
```

I think, [this section](https://styled-components.com/docs/basics#passed-props) is also outdated as it refers to v5, in v6, all props are passed by to default (both HTML tag and react component).
