### ISSUE TITLE
v6 crashes `tsc` (OOM)

### ISSUE THREAD

**Issue by gineika** [styled-components/styled-components#4061]
## System:
 - OS: Linux 5.15 Ubuntu 22.04.2 LTS 22.04.2 LTS (Jammy Jellyfish)
 - CPU: (4) x64 AMD EPYC Processor
 - Memory: 5.66 GB / 7.57 GB
 - Container: Yes
 - Shell: 5.1.16 - /bin/bash
## Binaries:
 - Node: 20.3.0 - ~/.nvm/versions/node/v20.3.0/bin/node
 - Yarn: 1.22.19 - ~/.nvm/versions/node/v20.3.0/bin/yarn
 - npm: 9.7.1 - ~/.nvm/versions/node/v20.3.0/bin/npm
 - pnpm: 8.6.5 - ~/.nvm/versions/node/v20.3.0/bin/pnpm
## npmPackages:
 - styled-components: 6.0.0 => 6.0.0

## Steps to reproduce

```
npx tsc
```

v5 works, v6 crashes. Tested with TypeScript v5.1.5 and v5.0.4.

## Expected Behavior

No errors.

## Actual Behavior

```
<--- Last few GCs --->

[36408:0x6e45340]    38728 ms: Mark-Compact (reduce) 1881.5 (1966.8) -> 1881.5 (1919.3) MB, 1080.72 / 0.00 ms  (average mu = 0.400, current mu = 0.000) last resort; GC in old space requested
[36408:0x6e45340]    39784 ms: Mark-Compact (reduce) 1881.5 (1919.3) -> 1881.5 (1919.3) MB, 1055.64 / 0.00 ms  (average mu = 0.243, current mu = 0.000) last resort; GC in old space requested


<--- JS stacktrace --->

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: 0xc8e4a0 node::Abort() [node]
 2: 0xb6b8f3  [node]
 3: 0xeacb10 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
 4: 0xeacdf7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
 5: 0x10ad8ba v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 6: 0x1089bd6 v8::internal::Factory::AllocateRaw(int, v8::internal::AllocationType, v8::internal::AllocationAlignment) [node]
 7: 0x107b21c v8::internal::FactoryBase<v8::internal::Factory>::AllocateRawArray(int, v8::internal::AllocationType) [node]
 8: 0x107b384 v8::internal::FactoryBase<v8::internal::Factory>::NewFixedArrayWithFiller(v8::internal::Handle<v8::internal::Map>, int, v8::internal::Handle<v8::internal::Oddball>, v8::internal::AllocationType) [node]
 9: 0x13aa25d v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Allocate(v8::internal::Isolate*, int, v8::internal::AllocationType) [node]
10: 0x13aa303 v8::internal::OrderedHashTable<v8::internal::OrderedHashMap, 2>::Rehash(v8::internal::Isolate*, v8::internal::Handle<v8::internal::OrderedHashMap>, int) [node]
11: 0x14daf23 v8::internal::Runtime_MapGrow(int, unsigned long*, v8::internal::Isolate*) [node]
12: 0x7fa125e99ef6 
Aborted (core dumped)
```

**Comment by wadehammes** [comment]
Im also experiencing this

**Comment by thienandangthanh** [comment]
I also get the problem.
I currently don't know to how to make a correct reproduction.

I tried to create new project with the following info but don't get the error:
- vite and react-ts template
- styled-components, stylis
- a simple component use `styled` and `css`

**Comment by thienandangthanh** [comment]
> Can you post a reproduction please? There are too many variables for a simple issue to be helpful. If you aren't already, I'd recommend enabling skipLibCheck / skipDefaultLibCheck in your tsConfig

This approach doesn't work.

**Comment by probablyup** [comment]
The types are definitely heavier than most because of how much prop-merging we have to do internally. I'll continue trying to find ways to optimize it... it's been very challenging tbh.

**Comment by probablyup** [comment]
I did find though that deduping React types significantly sped up local compilation. If you have v17 and v18 types coexisting for example it made things like 5x slower

**Comment by probablyup** [comment]
We will need to start using react v18 types internally soon. Maybe will ship that as a patch

**Comment by gineika** [comment]
Yes, types use too much RAM. This worked:
```
npx --node-options="--max-old-space-size=4096" tsc
```

**Comment by probablyup** [comment]
> I did find though that deduping React types significantly sped up local compilation. If you have v17 and v18 types coexisting for example it made things like 5x slower

If someone with this OOM issue could try deduping their React types (using yarn resolutions or equivalent) and let me know if that helps I'd appreciate it. This issue seems to be very environment-specific.

**Comment by wadehammes** [comment]
How would one do this with PNPM, never had to do it before. Looking at the PNPM docs here https://pnpm.io/package_json

**Comment by wadehammes** [comment]
> We will need to start using react v18 types internally soon. Maybe will ship that as a patch or add it to peerDependencies with a permissive range so it dedupes better.

I like this idea

**Comment by probablyup** [comment]
> How would one do this with PNPM, never had to do it before. Looking at the PNPM docs here https://pnpm.io/package_json

pnpm.overrides I think

**Comment by wadehammes** [comment]
This seems like it could work as well? 

<img width="1007" alt="image" src="https://github.com/styled-components/styled-components/assets/222170/2e7f57c8-3e08-4da2-b85c-c0b7473009c6">

**Comment by wadehammes** [comment]
> > How would one do this with PNPM, never had to do it before. Looking at the PNPM docs here https://pnpm.io/package_json
> 
> pnpm.overrides I think

Let me give it a shot

**Comment by horaklukas** [comment]
> If someone with this OOM behavior could try deduping their React types (using yarn resolutions or equivalent) and let me know if that helps I'd appreciate it. This issue seems to be very environment-specific.

I tried to dedupe `@types/react` with yarn resolutions and it didn't help.

However I found out it first appeared in version **6.0.0**, version **6.0.0-rc.6 is fine** even with non-deduped `@types/react`

**Comment by seanmcquaid** [comment]
Seeing crashes on this as well on CI.

**Comment by kitajchuk** [comment]
Also TS is painfully slow in editor (VS Code) post `6.0.0-rc.6` release version.

**Comment by foucdeg** [comment]
I also have only one version of `@types/react` in my lockfile.

`tsc` is still taking ~30 seconds with v6 vs ~3 seconds with v5., using upwards of 6GB of RAM, and failing with OOM on CircleCI.

**Comment by probablyup** [comment]
Just want to let everyone know I'm going to continue looking into this, I've been moving houses this weekend so busy busy!

**Comment by slutske22** [comment]
> Also TS is painfully slow in editor (VS Code) post `6.0.0-rc.6` release version.

I have noticed this as well.  Just spent 2 hours trying to understand why my TS intellisense and webpack compilation timing were horrendously slow, finally tried downgrading styled-components back to v@^5, and that fixed my issue.  Not sure what's going on in v6, but it really screws with TS.

**Comment by probablyup** [comment]
> > Also TS is painfully slow in editor (VS Code) post `6.0.0-rc.6` release version.
> 
> I have noticed this as well. Just spent 2 hours trying to understand why my TS intellisense and webpack compilation timing were horrendously slow, finally tried downgrading styled-components back to v@^5, and that fixed my issue. Not sure what's going on in v6, but it really screws with TS.

That should be largely resolved in 6.0.2-onward

**Comment by kitajchuk** [comment]
> > > Also TS is painfully slow in editor (VS Code) post `6.0.0-rc.6` release version.
> > 
> > 
> > I have noticed this as well. Just spent 2 hours trying to understand why my TS intellisense and webpack compilation timing were horrendously slow, finally tried downgrading styled-components back to v@^5, and that fixed my issue. Not sure what's going on in v6, but it really screws with TS.
> 
> That should be largely resolved in 6.0.2-onward

Yes version 6.0.2 largely resolves the issues of slowness with TS in general. I’d say TS is still a bit less performant than it was before (I was on 5.3.2 I believe prior) so there’s probably further optimization that could be done.

**Comment by probablyup** [comment]
> I’d say TS is still a bit less performant than it was before (I was on 5.3.2 I believe prior) so there’s probably further optimization that could be done.

probably true, and there's a few outstanding bugs to be resolved. The v6 types actually do more in general than the v5 ones so it makes sense that they're somewhat slower (within reason.)

**Comment by reabreu** [comment]
Hi there, just wanted to chip in to tell I'm also running into this issue after upgrading to v6, is this still being worked on?  This is on a large project as well.

**Comment by JanderSilv** [comment]
Facing this issue as well.

typescript@^4.9.5
