### ISSUE TITLE
Array.from(e.querySelectorAll("style[".concat(f,"]"))).at is not a function.

### ISSUE THREAD

**Issue by dexbol** [styled-components/styled-components#4067]
First, Congratulations for v6 stable released.

v6.0.1 use `Array.at` method that only supported after chrome 92 and iOS 15.4 , the iOS version released in 2022 . **Just One Year Ago**.

So, I recommend everyone include `node_modules/styled-component` to the babel-loader to polyfill `Array.at` and `Array.flatMap` . And this should be in v6 upgrade guide.

**Comment by rockey2020** [comment]
same questions

![image](https://github.com/styled-components/styled-components/assets/64777114/c7a23018-a4c1-4bcf-9b06-a768d72ac0ea)

**Comment by probablyup** [comment]
Can replace it with ES5-compliant code, was hoping to be able to use the newer API but still too new I guess.

**Comment by probablyup** [comment]
Fixed in https://github.com/styled-components/styled-components/releases/tag/v6.0.2
