### ISSUE TITLE
[1.4.0] breaks react native at AppRegistry level

### ISSUE THREAD

**Issue by IljaDaderko** [styled-components/styled-components#409]
Upgrading to 1.4.0 causes following error in react-native v0.40

```
Cannot read property 'indexOf' of undefined
Module AppRegistry is not a registered callable module (calling runApplication)
```

Double tested, downgrading back to 1.3.1 fixes the issue, looks to me like something in last change is resolving to undefined, assumed #408 was the fix initially, but no luck. Was confused by lib folder not being present in master, but existing in installed node modules.

**Comment by mxstbr** [comment]
Sorry for all of this trouble with ReactNative, would you like to help us with #94?

Also, any ideas what the issue could be?

**Comment by IljaDaderko** [comment]
No worries :) just reporting these here as I believe styled-components are a sick tool for rn. Only idea I had was that one I submitted and closed my pr for :/ but that didn't work. If I had to guess it would be something resolving to undefined. Will have a look at #94 and see what I can do 👍

**Comment by mrpatiwi** [comment]
Same issue here with `1.4.0`, but works fine on `1.3.1`.

```text
undefined is not an object (evaluating 'argv.indexOf')
```

The error seems to come from:
```js
// node_modules/styled-components/lib/vendor/postcss/node.js:11
var _cssSyntaxError = require('./css-syntax-error');

//  node_modules/styled-components/lib/vendor/postcss/css-syntax-error.js:9
var _supportsColor = require('supports-color');

// node_modules/supports-color/index.js:4
var terminator = argv.indexOf('--');
```

**Comment by mxstbr** [comment]
Thanks for digging in @mrpatiwi and @lukehedger for submitting the PR—releasing as `v1.4.1` now, super sorry for all the troubles!
