### ISSUE TITLE
Issue when running `tsc` command after upgrading to `6.0.4`

### ISSUE THREAD

**Issue by DeadEnglish** [styled-components/styled-components#4093]
## System:
 - OS: macOS 13.3.1
 - CPU: (10) arm64 Apple M1 Pro
 - Memory: 75.03 MB / 16.00 GB
 - Shell: 5.9 - /bin/zsh
## Binaries:
 - Node: 20.2.0 - ~/.nvm/versions/node/v20.2.0/bin/node
 - npm: 9.6.6 - ~/.nvm/versions/node/v20.2.0/bin/npm
## npmPackages:
 - styled-components: ^6.0.4 => 6.0.4 

## Steps to reproduce
1. Upgrade `styled-components` to `6.0.4`
2. run `tsc`

## Expected Behavior
`tsc` should emit no errors. 

## Actual Behavior
Errors returned `styled-components` node modules folder.
```
> tsc --noEmit

node_modules/styled-components/dist/constructors/styled.d.ts:159:49 - error TS2694: Namespace 'React' has no exported member 'SVGLineElementAttributes'.

159     line: Styled<"web", "line", import("react").SVGLineElementAttributes<SVGLineElement>, import("../types").BaseObject>;
                                                    ~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/styled-components/dist/constructors/styled.d.ts:174:49 - error TS2694: Namespace 'React' has no exported member 'SVGTextElementAttributes'.

174     text: Styled<"web", "text", import("react").SVGTextElementAttributes<SVGTextElement>, import("../types").BaseObject>;
                                                    ~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/styled-components/dist/models/ServerStyleSheet.d.ts:13:34 - error TS2694: Namespace 'React' has no exported member 'JSX'.

13     getStyleElement: () => React.JSX.Element[];
                                    ~~~


Found 3 errors in 2 files.

Errors  Files
     2  node_modules/styled-components/dist/constructors/styled.d.ts:159
     1  node_modules/styled-components/dist/models/ServerStyleSheet.d.ts:13
```

**Comment by markrickert** [comment]
A little more context for those looking for it: I ran into this problem when doing a major upgrade from `styled-components@4.4.1` to `styled-components@6.0.8`.

The fix was to upgrade the `@types/react` and `@types/react-dom` packages to their latest versions. I'm still using React 17 so my new config for the latest types is, at the time of this comment:

```json
"@types/react": "17.0.65",
"@types/react-dom": "17.0.20",
```

They were both at `17.0.2`, causing this issue.
