### ISSUE TITLE
Migration problems from v5 to v6

### ISSUE THREAD

**Issue by nikitadubyk** [styled-components/styled-components#4096]
Hi!

Found a lot of bugs we have a lot of storybook components at work and after updating styled-components from `5.3.11` to `6.0.4` many of them broke. I did the transition strictly according to the documentation, also tried adding and removing `StyleSheetManager`, adding `shouldForwardProp={() => true}`, adding/removing `enableVendorPrefixes`. At first I thought it might be because of errors in the console as the props are passed to the DOM, in some elements fixed this problem, but the component did not work as it should. At the same time components are not changed in any way, to fix the problem I need to go back to `5.3.11`.

I went through most of the components and found the problems:
- no import of CSSProperties
- no import of FlattenSimpleInterpolation
- we have a sidebar that breaks when closed, inside for animation css transition group is used (see screenshot 1)
- :not(:first-child), :first-child, nth:child(2n+1), :before, :after stopped working correctly
- hover broke on many components, it was on parent components, but after the update it moved to child components.
- drag and drop component also breaks when clicked (see screenshot 2)
- transition also stopped working, there is no smoothness
- checkbox, radio broke, svg is no longer displayed if there is isChecked props.

Also I checked what props come to components, they are the same if I compare components with 5.3.11 and 6.0.4, that is not the problem.

Screenshot 1 - Broken sidebar
![Untitled](https://github.com/styled-components/styled-components/assets/73419198/dea7c711-0855-4b0b-b954-5f5ac22a68e4)

Screenshot 2 - Broken drag and drop
![Untitled1](https://github.com/styled-components/styled-components/assets/73419198/2d8ae43d-ca4c-453e-8f0d-aa2dad419bb7)

## Environment
- styled-components: 5.3.11 -> 6.0.4
- storybook: 7.1.0
- stylis: 4.3.0
- react: 18.2.0
## System:
 - OS: Windows 10 10.0.19045
 - CPU: (12) x64 Intel(R) Xeon(R) CPU E5-2640 0 @ 2.50GHz
 - Memory: 6.87 GB / 15.92 GB
## Binaries:
 - Node: 16.17.0 - C:\Program Files\nodejs\node.EXE      
 - npm: 8.15.0 - C:\Program Files\nodejs\npm.CMD

## Reproduction
I reproduced three problems, it's a problem with hover, :before and :after, :nth-child
https://codesandbox.io/embed/styled-components-base-forked-673g5g?fontsize=14&hidenavigation=1&theme=dark

## Steps to reproduce
In package.json, update the version of styled-components to 6.0.4
## Expected Behavior
It is expected that before, after, nth:child will work correctly
## Actual Behavior
Stopped working as it should, missing styles from the right elements

**Comment by oertels** [comment]
I found that `:first-child` does not work properly, it seems to copy the selector also to child components. 
Using testing-library, access to `document.stylesheets` does not work any more, it's empty.

**Comment by jwld** [comment]
Thought I was going crazy - also seeing these issues, particularly the hover and child selectors. v6 is totally unusable for us at the moment.

**Comment by radekfurman** [comment]
I'm not sure, but you could try to add "&"  before every pseudo class/element i.e `&::after`.
https://styled-components.com/docs/basics#pseudoelements-pseudoselectors-and-nesting
Looks like stylis preprocessor treats them differently then preprocessor used in v5, but I speculate.

**Comment by DatGreekChick** [comment]
> I'm not sure, but you could try to add "&" before every pseudo class/element i.e `&::after`. https://styled-components.com/docs/basics#pseudoelements-pseudoselectors-and-nesting Looks like stylis preprocessor treats them differently then preprocessor used in v5, but I speculate.

Thank you! This helped my styles across the board! 👏🏼
