### ISSUE TITLE
TS Error When Using `css` Interpolations in `styled(...)`

### ISSUE THREAD

**Issue by joealden** [styled-components/styled-components#4099]
## Environment
The `envinfo` command didn't work on my system, but I don't think it's too relevant here.

- `styled-components` version: `6.0.4`
- `typescript` version: `5.1.6`

## Reproduction

https://www.typescriptlang.org/play?jsx=4#code/JYWwDg9gTgLgBAbzgYwM6oDR1TAngGwFMATOAXzgDMoIQ4AiHAkgWmVsgDtDOZV6A3ACgheMITgBlPEWIAFGmFRwAvIjgASAG4BDKMB28AXNhj7OAc3LCh7TjmwALPSWnNlatKgA8b2QoglAD4AAyE4FAh8aBMNBDBFDyC4AAoEwNQAOm09A15VFTV6Yj0Aa3o4AH4GACN8HWRyuBN6AHdHYBhCegBKMmEQmzEJAGEOCG5eAKVVdWR69AA5HRBCSpMccwsBOC6cDbNgS2sROwcx8AmeGBMAJUIGmEyAMRHvC65r6dRktRSkeY6JYrQhYPbwMg9VTJBDhOBQQgwACuUE4cG8xGAWhQC1Qy1WKgQgOBqzIQQQ4LI3gA9JitEFhP0RIQAB6QWCRezwPwkD5XfJqJiyFJ8yYwHq+GQkb6hOFxVDOBHEHmoJmDIRAA

```tsx
import { css, styled } from "styled-components";

type StyledProps = { $variant: string };

const sharedStyles = css<StyledProps>`
  color: ${props => (props.$variant === "dark" ? "black" : "white")};
`;

type ComponentProps = { className?: string; test: string };

const Component: React.FC<ComponentProps> = ({ className, test }) => {
  return <div className={className}>{test}</div>;
};

export const StyledComponent = styled(Component)<StyledProps>`
  ${sharedStyles}; // this line shows a TS error
`;

```

## Steps to reproduce

1. Create a value to interpolate via the `css` function - this needs to be typed to require props.
2. Create a simple component that you can wrap with `styled`.
3. Wrap this component with `styled`, using the interpolation created above and it's types.
4. See TS error where interpolation is used.

FYI, this has been mentioned in https://github.com/styled-components/styled-components/issues/4062 too, but I thought it made sense for this to be a seperate issue.

## Expected Behavior

No TS errors (this worked before v6), or guidance on if there is some other way to do this now.

## Actual Behavior

TS error: `Argument of type 'RuleSet<X>' is not assignable to parameter of type 'Interpolation<Substitute<Y, X>>`

**Comment by laboskin** [comment]
Another example of the same problem (version 6.0.5):

```
import styled, { css } from "styled-components";

type Props = {
  $size: number;
  $color: string;
};

const sizeStyles = css<Pick<Props, "$size">>`
  font-size: ${(props) => props.$size}px;
`;

const Container = styled.div<Props>`
  color: ${(props) => props.$color};
  ${sizeStyles}; // TS error: argument of type 'RuleSet<Pick<Props, "$size">>' is not assignable to parameter of type 'Interpolation<Substitute<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, Props>>'.
`;

export const Component = () => (
  <Container $size={100} $color="red">
    Text
  </Container>
);

```

**Comment by HarshaHR1994** [comment]
Having same issue 😞  What was the solution ? @joealden
