### ISSUE TITLE
Testing mixins "branch not covered"

### ISSUE THREAD

**Issue by santaclauze** [styled-components/styled-components#410]
My test coverage is greatly impacted by my mixins & utilities.

I am using Jest (from the latest version of the react-boilerplate), when it comes to both mixins and utilities the testing shows me the following:

![test-screen](https://cloud.githubusercontent.com/assets/17665998/22317490/8d4f02d6-e3a6-11e6-80cc-55f4cfe2ad85.png)

As you can see the `Branches` at the top = 0% and it highlights my `default props` and tells me the `branch is not covered`. This is valid for any mixin/utility that uses defaultProps.

I can't have been having resolving this. Has anyone observed a similar behaviour?

## Version
    "styled-components": "^1.3.1"

**Comment by diegohaz** [comment]
You need to test the function both with and without arguments. But is that related to styled-components?

**Comment by santaclauze** [comment]
@diegohaz thanks man. I have been coding for a bit less than a year, I struggle to differentiate where the issues come from and how they relate to what part. 

Using Styled-components and default_props, I figured that that situation may have been encountered by some one using styled, therefore asking here.

<---Noob learning :)

**Comment by diegohaz** [comment]
Oh, no problem. Coding for a year, but already caring about tests and coverage.That's awesome. 👍

**Comment by diegohaz** [comment]
Just to state, to fully cover a function like that:
```js
function fn (param = 'default value') {
  return param
}
```
You need to call it in these two ways:
```js
expect(fn()).toBe('default value')
expect(fn('foo')).toBe('foo')
```

**Comment by santaclauze** [comment]
I will remember that :) Thanks bro!
