### ISSUE TITLE
React Native: Slider not part of core

### ISSUE THREAD

**Issue by apertureless** [styled-components/styled-components#4109]
Using styled-components in an expo app. Upgraded some dependencies and not it throws errors. 
After long debugging it seems to be a problem with styled components. As I am styling a slider. Which seems to be not part of rn core anymore. 

## Environment

```
"expo": "~49.0.5",
"react": "18.2.0",
"react-native": "0.72.3",
```

## System:
 - OS: macOS 12.6.7
 - CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
 - Memory: 107.14 MB / 16.00 GB
 - Shell: 5.8.1 - /bin/zsh
## Binaries:
 - Node: 16.17.1 - /usr/local/bin/node
 - Yarn: 1.22.19 - /usr/local/bin/yarn
 - npm: 8.15.0 - /usr/local/bin/npm
 - pnpm: 8.6.10 - /usr/local/bin/pnpm
## npmPackages:
 - styled-components: ^6.0.5 => 6.0.5
## Steps to reproduce

```js
import styled from 'styled-components/native'
export const ProgressSlider = styled.Slider`
  flex: 1 1 auto;
  margin-left: 20px;
  margin-right: 20px;
`
```

## Expected Behavior

Works.

## Actual Behavior

Invariant Violation: Slider has been removed from react-native core. It can now be installed and imported from '@react-native-community/slider' instead of 'react-native'. See https://github.com/callstack/react-native-slider, js engine: hermes

**Comment by krudos** [comment]
try 
```
import styled from 'styled-components/native'
export const ProgressSlider = styled(Slider)`
  flex: 1 1 auto;
  margin-left: 20px;
  margin-right: 20px;
`
```
