### ISSUE TITLE
Regression in styled-components v6 when compiling in production mode

### ISSUE THREAD

**Issue by guillaumebrunerie** [styled-components/styled-components#4113]
## System:
 - OS: macOS 13.3.1
 - CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
 - Memory: 22.09 MB / 16.00 GB
 - Shell: 5.9 - /bin/zsh
## Binaries:
 - Node: 20.2.0 - /usr/local/bin/node
 - npm: 9.6.6 - /usr/local/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^2.1.4 => 2.1.4
 - styled-components: ^6.0.7 => 6.0.7

## Reproduction

I have the following styled component:
```ts
const Thing = styled.div<{$side: "left" | "right"}>`
  position: absolute;
  width: 10px;
  height: 100%;
  cursor: ew-resize;
  left: ${props => props.$side == "left" && "-5px"};
  right: ${props => props.$side == "right" && "-5px"};
`;
```

It is used as follows
```ts
const Parent = () => {
  return (
    <div>
      <Thing $side="left"/>
      <Thing $side="right"/>
    </div>
  );
};
```

It is supposed to create two divs, the first one with style `left: -5px` and the second one with style `right: -5px`.

It worked fine with styled-components v5, and works fine in development mode with styled-components v6, but breaks in *production mode* with styled-components v6: they both get the same CSS class containing `left: -5px`, for some reason. I checked with the React DevTools and the second one does get the correct `$side: "right"`, so I have no clue what is happening.

I have now changed the left/right lines to
```ts
  ${props => props.$side == "left" && "left: -5px"}
  ${props => props.$side == "right" && "right: -5px"}
```
because the original version feels kind of weird (it relies on `left: ${props => false}` to be removed from the CSS), and it now works.

Is that a known regression?
I feel a bit worried about upgrading to styled-component v6 now, as production-only regressions are pretty hard to catch and to debug, and I don’t know if I use a similar pattern in other places in my project.

~I'd be happy to try to make a reproduction, but I’m not sure how to make the codesandbox compile in production mode?~
See below.

**Comment by guillaumebrunerie** [comment]
Here is a local reproduction. Create a folder with the following four files, run `npm i`, and then compare how the page looks when running `npm run dev` (development version, correct) and `npm run prod` (production version, incorrect).

`package.json`
```json
{
  "name": "styled-components-issue",
  "version": "0.0",
  "description": "Issue when building in production mode",
  "main": "index.js",
  "scripts": {
    "prod": "webpack serve --mode production",
    "dev": "webpack serve --mode development"
  },
  "type": "module",
  "author": "",
  "license": "",
  "devDependencies": {
    "@babel/core": "^7.22.5",
    "@babel/preset-react": "^7.22.5",
    "babel-loader": "^9.1.2",
    "html-webpack-plugin": "^5.5.3",
    "webpack": "^5.88.1",
    "webpack-cli": "^5.1.4",
    "webpack-dev-server": "^4.15.1"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "styled-components": "^6.0.7"
  }
}
```
`webpack.config.js`
```js
import path from "path";
import {fileURLToPath} from "url";
import HtmlWebpackPlugin from "html-webpack-plugin";

// Root directory (the one containing the present file)
const rootDir = fileURLToPath(new URL(".", import.meta.url));

export default {
  entry: {
    bundle: path.resolve(rootDir, "index.js"),
  },
  module: {
    rules: [
      {
        test: /\.jsx?$/,
        exclude: /node_modules/,
        loader: "babel-loader",
        options: {
          presets: [
            "@babel/preset-react",
          ],
          plugins: [
            "babel-plugin-styled-components",
          ],
        }
      },
    ]
  },
  plugins: [
    new HtmlWebpackPlugin({
      template: path.resolve(rootDir, "index.html"),
    }),
  ],
  performance: {
    hints: false,
  },
};
```
`index.html`
```html
<!DOCTYPE html>
<html>
<head>
  <title>Styled components issue</title>
</head>
<body>
  <div id="root"></div>
</body>
</html>
```
`index.js`
```js
import * as React from "react";
import * as ReactDOM from "react-dom/client";
import styled from "styled-components";

const Thing = styled.div`
  color: ${props => props.$part == "text" && "red"};
  background-color: ${props => props.$part == "background" && "red"};
`;

const App = () => {
  return (
    <div>
      <Thing $part="text">
        Red text
      </Thing>
      <Thing $part="background">
          Red background
      </Thing>
    </div>
  );
};

ReactDOM.createRoot(document.getElementById("root")).render(<App/>);
```

**Comment by radekfurman** [comment]
@guillaumebrunerie , I believe your issue has something to do with the way that Stylis treats & and && selectors.
Look at the && section and conditional styling: https://styled-components.com/docs/basics#pseudoelements-pseudoselectors-and-nesting
It looks, that your current styling applies to all instances of the components. You could try using pattern shown in docs, I mean, conditionally returning css`` with && selectors to narrow style to one instance.
I might be wrong though. I have similar problem and I couldn't find any workaround.

**Comment by guillaumebrunerie** [comment]
@radekfurman This section is about CSS nesting and using `&&` _inside the CSS string_, it has nothing to do with using the Javascript `&&` operator which is what I am using here.

**Comment by radekfurman** [comment]
@guillaumebrunerie , Yeah, I totally get difference between && in css and && in JS, I only wanted to suggest, that maybe result of JS expression is spread across all instances of component. But it's clearly not in your case. Sorry for misleading comment.

**Comment by bcole808** [comment]
I was able to re-create this problem using your example code, and confirm that this bug happens when in production mode but not in other modes. I've opened a PR which should fix this.
