### ISSUE TITLE
Use Styletron engine

### ISSUE THREAD

**Issue by quentin-sommer** [styled-components/styled-components#412]
Hi,

I think styled-components could really benefit using [styletron](https://github.com/rtsao/styletron). It creates atomic css classes to prevent duplication and limit the stylesheet size, it would be a nice addition to styled-components!

They already got a styletron-react plugin which is using a similar way of declaring styles as styled-components ([here](http://styletron.js.org/index.html)) so I guess it wouldn't be that big of a change.

Post explaining styletron : https://ryantsao.com/blog/virtual-css-with-styletron

What do you think?

**Comment by santaclauze** [comment]
I am thinking of all the components I am writing with the current syntax. Simple question, will the api still work if we change ?
I know they are working on a 2.0 that take care of css compression at some point.

**Comment by mxstbr** [comment]
We've trialled using atomic CSS classes, but the benefit is pretty small and the DX significantly worse. We also don't want to convert CSS strings back to objects just to use that engine, that'd have a pretty big performance impact.

I'm sure @geelen has some more insights on this, too.

**Comment by geelen** [comment]
Yep see #351 for a discussion on this exact issue.
