### ISSUE TITLE
Failed to Compile --Learn Apollo in Windows environment

### ISSUE THREAD

**Issue by ZanshinPost** [styled-components/styled-components#413]
I started with the Learn Apollo tutorial, using Windows Pc and got the following error message after npm start command.

Failed to compile.

Error in ./~/styled-components/lib/vendor/postcss/css-syntax-error.js
Module not found: Error: Cannot resolve module 'supports-color' in D:\apollo\react\pokedex\exercise-01\node_modules\styled-components\lib\vendor\postcss
 @ ./~/styled-components/lib/vendor/postcss/css-syntax-error.js 9:21-46

**Comment by marktani** [comment]
This is the repo in question: https://github.com/learnapollo/pokedex-react

**Comment by lukehedger** [comment]
Also getting this with `Error: Cannot find module 'supports-color'`

**Comment by marktani** [comment]
Has been reported on an React project though

**Comment by lukehedger** [comment]
Good point. Mine is a React project too though.

**Comment by mxstbr** [comment]
Releasing as `v1.4.1` now, super sorry for all the troubles!

**Comment by ZanshinPost** [comment]
I've retried and it does work!
Thanks for solving this issue.

**Comment by AndrewMorsillo** [comment]
This is happening to me now more than 2 years later on the latest styled-components! I am unable to make a reproduction of it however. It fails on my project but works fine on a bare `react-native init` with styled-components added.
