### ISSUE TITLE
Is @types/styled-components-react-native still needed post v6?

### ISSUE THREAD

**Issue by LA-Johan** [styled-components/styled-components#4168]
In the [migration document](https://styled-components.com/docs/faqs#what-do-i-need-to-do-to-migrate-to-v6) it is recommended to delete the @types/styled-components dependency. 

I did the same for the react native type dependency @types/styled-components-react-native and I'm seeing typescript errors. Just wanted to see if I @types/styled-components-react-native is still needed, or if I have some issue with my project to correctly move over to the new styled-component types.

**Comment by hadnet** [comment]
I'm using SC 6.1.1 and I'm getting error that there is no declaration? What happened?
