### ISSUE TITLE
Content attribute in ::before pseudoclass breaks all other styling

### ISSUE THREAD

**Issue by xNiallC** [styled-components/styled-components#4170]
## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown`

## System:
 - OS: macOS 13.5
 - CPU: (8) arm64 Apple M2
 - Memory: 48.55 MB / 16.00 GB
 - Shell: 5.9 - /bin/zsh
## Binaries:
 - Node: 20.6.1 - /opt/homebrew/bin/node
 - Yarn: 1.22.19 - /opt/homebrew/bin/yarn
 - npm: 9.8.1 - /opt/homebrew/bin/npm
## npmPackages:
 - styled-components: ^6.0.8 => 6.0.8

## Reproduction

https://codesandbox.io/s/styled-components-base-gc367

## Steps to reproduce

This requires using `styled-components 6+`; in `styled-components 5` and lower there are no issues.

To reproduce, create any styled default component (in our instance `styled.p`) with the following style, as an example:

`
&::before{
    font-family: "Icons";
    font-weight: 900;
    content: '\f059';
    color:#6f6d6d;
    margin-right:7px;
  }
`

## Expected Behavior

In the element's `::before`, a small question icon is rendered.

## Actual Behavior

A broken `::before` is applied to the element, so that every element that is rendered once the styling from the aforementioned component is rendered on the page.

You can see in [this codesandbox](https://codesandbox.io/s/styled-components-base-forked-22mnrw?file=/index.js) how this is happening - The child styles are not getting applied, and if you inspect the element of the paragraph, you can see a broken style is being applied to the `::before` pseudoclass. 

`
.kgJGLA::before {
    content: "00";}.bSwhtp{color:blue;};
}
`

**Comment by andi1984** [comment]
I can confirm. seems to happen on `::after` as well.

**Comment by brunouber** [comment]
I can reproduce the same issue also with version `styled-components: ^6.0.7`

**Comment by andi1984** [comment]
@brunouber @xNiallC I found the solution:

The issue is with the escaping of the backslash of the unicode CSS `content` value. The backslash needs to be escaped:

[This is the updated code-sandbox.](https://codesandbox.io/s/styled-components-base-forked-gwzg52?file=/index.js).
