### ISSUE TITLE
Nesting styled components with styled() and adding prop types does not work correctly

### ISSUE THREAD

**Issue by fabb** [styled-components/styled-components#4174]
### System:
 - OS: macOS 13.5.2
 - CPU: (10) arm64 Apple M1 Max
 - Memory: 49.19 MB / 64.00 GB
 - Shell: 5.9 - /bin/zsh
### Binaries:
 - Node: 18.17.0 - ~/.nvm/versions/node/v18.17.0/bin/node
 - Yarn: 1.22.19 - ~/.yarn/bin/yarn
 - npm: 9.6.7 - ~/.nvm/versions/node/v18.17.0/bin/npm
### npmPackages:
 - babel-plugin-styled-components: 2.1.4 => 2.1.4 
 - styled-components: 6.0.8 => 6.0.8 
 
## Reproduction

https://codesandbox.io/s/styled-components-base-forked-j8f2nt?file=/index.tsx

## Steps to reproduce

```
const Component1 = styled.a<{ prop1?: boolean }>``

const Component2 = styled(Component1)<{ prop2?: boolean }>``

const Component3 = styled(Component2)<{ prop3?: boolean }>``

const Component4 = () => <Component3 prop1={true} prop2={true} /> // compiles fine

const Component5 = () => <Component3 prop1={true} prop2={true} prop3={true} /> // compile error, prop2 does not exist
```

## Expected Behavior

Should compile.

## Actual Behavior

Component5 does not compile, `prop2` cannot be found.

**Comment by krudos** [comment]
i am getting same error with 6.0.8 . with 6.0.7 types are working

**Comment by seanmcquaid** [comment]
Seeing the same as well!

**Comment by krudos** [comment]
i think this is related to
https://github.com/styled-components/styled-components/issues/4165

**Comment by ViniDevBR** [comment]
6.0.8 is broken with types... USE 6.0.7

**Comment by krudos** [comment]
i think this got broken on this commit
https://github.com/styled-components/styled-components/commit/6ee6c23994b9ac41eba06b112a0f6670e41de757

**Comment by krudos** [comment]
i created this PR
https://github.com/styled-components/styled-components/pull/4190

**Comment by krudos** [comment]
try 6.1.0

**Comment by MarineP31** [comment]
I still got the same issue in 6.1.0 too

**Comment by macko911** [comment]
I've added failing tests to help fix this in https://github.com/styled-components/styled-components/pull/4219
