### ISSUE TITLE
Pseudo selectors no longer work without &

### ISSUE THREAD

**Issue by fabb** [styled-components/styled-components#4177]
### System:
 - OS: Linux 6.1 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
 - CPU: (2) x64 AMD EPYC
 - Memory: 1.20 GB / 2.01 GB
 - Container: Yes
 - Shell: 5.1.4 - /bin/bash
### Binaries:
 - Node: 16.17.0 - /usr/local/bin/node
 - Yarn: 1.22.19 - /usr/local/bin/yarn
 - npm: 8.15.0 - /usr/local/bin/npm
 - pnpm: 7.1.0 - /usr/local/bin/pnpm
 - Watchman: 20220528.183901.0 - /usr/local/bin/watchman
### npmPackages:
 - styled-components: 6.0.8 => 6.0.8 

## Reproduction

[
https://codesandbox.io/s/styled-components-base-gc367](https://codesandbox.io/s/styled-components-base-forked-2hkm4n?file=/index.js)

## Steps to reproduce

```
const StyledDiv = styled.div`
  /* does not work in styled-components 6 anymore */
  :before {
    content: "⚠️";
  }

  &:after {
    content: "✅";
  }
`;
```

## Expected Behavior

Pseudo selectors should work like in styled-components 5 with or without prefixed `&`.

## Actual Behavior

Pseudo selectors no longer work when not prefixed with `&`.

This affects e.g. `:before`/`:after`/`:focus`/`::placeholder`.

It looks like the root cause is that styled-components 6 adds an additional space between the generated class name and the pseudo selector:
![Screenshot 2023-09-25 at 13 46 58](https://github.com/styled-components/styled-components/assets/153960/4a7f7865-9eef-4f87-86ff-f412b0a1dd73)

**Comment by chuanqisun** [comment]
Minimum repro https://stackblitz.com/edit/stackblitz-starters-q4mqvr?file=src%2FApp.js

```jsx
import React from 'react';
import styled from 'styled-components';

export default function App() {
  return (
    <div>
      <div>
        <GoodDiv>Expect red background, actual red background</GoodDiv>
      </div>
      <div>
        <BadDiv>Expect red background, actual no background</BadDiv>
      </div>
    </div>
  );
}

const GoodDiv = styled.div`
&:first-child {
  background-color: red
}
`;

const BadDiv = styled.div`
:first-child {
  background-color: red
}
`;

```

**Comment by quantizor** [comment]
Appears to be another undocumented stylis v4 change. https://github.com/thysultan/stylis/issues/323

**Comment by quantizor** [comment]
Updated docs https://styled-components.com/docs/faqs#nested-syntax-handling
