### ISSUE TITLE
Using classNames instead of props

### ISSUE THREAD

**Issue by cchanna** [styled-components/styled-components#418]
Recently attempting the switch to styled components. Loving it so far, with a few quibbles. Here's one.

In my previous workflow, with plain old scss, I'd often do something like this:

```jsx
//component.js
import './component.scss';
import cx from 'classnames';

const Component = (props) => {
  const className = cx(props.className, 'component', {
    off: props.off,
    active: props.id == 0,
  });
  return (
    <div className={className}>'Some text'</div>
  );
}

//component.scss
.component {
  font-size: 20px;
  background: black;
  color: white;
  width: 20em;
  height: 10em;
  &.off {
    color: black;
    height: 0em;
  }
  &.active {
    background: blue;
    outline: 1px solid white;
    width: 30em;
    height: 20em;
  }
}
```

In styled components, all the examples look like this:

```jsx
//component.js
import styled from 'styled-components';

const height = (props) => {
  if (props.active) {
    return '20em';
  }
  else if (props.off) {
    return '0em';
  }
  return '10em';
}
const StyledComponent = styled.div`
  font-size: 20px;
  background: ${p => p.active ? 'blue' : 'black'};
  color: ${p => p.off ? 'black' : 'white'};
  width: ${p => p.active ? '30em' : '20em'};
  height: ${height};
  outline: ${p => p.active ? '1px solid white' : 'unset'};
`
const Component = (props) => {
  return (
    <StyledComponent off={props.off} active={props.id == 0}>'Some text'</div>
  );
}
```

But I see several problems with this. First off, it feels much more cluttered to me, and it's harder to see at a glance what exactly this component will look like in each state. But also, this component needs to be regularly re-parsed whenever those props change, which is a lot of extra unnecessary work.

Here's my workaround:

```jsx
//styled-classes.js
import React from 'react';
import cx from 'classnames';

export default const cz = (Component, ...names) => {
  return (props) => {
    const properties = Object.assign({}, props);
    let classNames = [];
    for (let i=0; i < names.length; i++) {
      const name = names[i];
      if (name in props) {
        if (props[name]) {
          classNames.push(name);
        }
        delete properties[name];
      }
    }
    const className = cx(props.className, classNames);
    delete properties.className;
    return (
      <Component className={className} {...properties}/>
    );
  }
}

//component.js
import styled from 'styled-components';
import cz from './styled-classes';

const StyledComponent = styled(cz('div', 'off', 'active'))`
  font-size: 20px;
  background: black;
  color: white;
  width: 20em;
  height: 10em;
  &.off {
    color: black;
    height: 0em;
  }
  &.active {
    background: blue;
    outline: 1px solid white;
    width: 30em;
    height: 20em;
  }
`
const Component = (props) => {
  return (
    <StyledComponent off={props.off} active={props.id == 0}>'Some text'</div>
  );
}

```

And honestly, this works great for me. But I do wonder if this sort of idea is something you want to propogate into the API somehow. I know this specific suggestion probably isn't possible, but it'd be so cool if I could write it something like this:

```jsx
const StyledComponent = styled.div`
  font-size: 20px;
  background: black;
  color: white;
  width: 20em;
  height: 10em;
  &${off} {
    color: black;
    height: 0em;
  }
  &${active} {
    background: blue;
    outline: 1px solid white;
    width: 30em;
    height: 20em;
  }
`
```

I don't know though! Any thoughts? Does anyone else have this complaint?

Edit by @diegohaz: added code highlight

**Comment by diegohaz** [comment]
Does it work for you?

```js
import styled, { css } from 'styled-components'

const StyledComponent = styled.div`
  font-size: 20px;
  background: black;
  color: white;
  width: 20em;
  height: 10em;
  ${props => props.off && css`
    color: black;
    height: 0em;
  `}
  ${props => props.active && css`
    background: blue;
    outline: 1px solid white;
    width: 30em;
    height: 20em;
  `}
`
```

Demo: http://www.webpackbin.com/4JNyEpQwz

**Comment by cchanna** [comment]
Hmm! That definitely is nicer. I suppose the only difference is that if you ever get around to pre-parsing components with static styles, that method wouldn't be treated as static while mine would.

**Comment by diegohaz** [comment]
That will create one different className for each combination of props you are using on your components (e.g. one for `off`, one for `active`, one for `active+off` and one for none, but only if you are rendering components with those states).

**Comment by cusxio** [comment]
@mxstbr I was wondering, when using `styled-components`, should the library `classnames` be used in conjunction with `styled-components`? or should we rely completely on [props](https://github.com/styled-components/styled-components/issues/418#issuecomment-275589908)  and the `css` function for composition?
