### ISSUE TITLE
Add support for "CSS Houdini" feature @property

### ISSUE THREAD

**Issue by kahoot-karl** [styled-components/styled-components#4185]
I would like to see support of a new CSS feature.

The [@property](https://developer.mozilla.org/en-US/docs/Web/CSS/@property) api is gaining wider browser support: 
<img width="772" alt="image" src="https://github.com/styled-components/styled-components/assets/64776986/bdc2ad72-a899-4802-a381-62a1b7bba269">

--- 

Currently there's not a good way of declaring these properties using styled components. This is a workaround:

```javascript

const MyDiv = styled.div`
@property --item-size {
  syntax: "<percentage>";
  inherits: true;
  initial-value: 40%;
}

--item-size: 20%;
`;

```
Unfortunately, the `--item-size` definition will clash with any other `--item-size` in the DOM, because it is not locally scoped, which is what we want when we use styled-components.

Would be great to discuss together what kind of api would fit here. Also please share if you know about any more robust workarounds.

**Comment by quantizor** [comment]
You'll want to open this over at [stylis](https://github.com/thysultan/stylis) (the preprocessor we use). It looks like the `<>` characters inside the string aren't being left alone.

**Comment by quantizor** [comment]
> Unfortunately, the --item-size definition will clash with any other --item-size in the DOM, because it is not locally scoped, which is what we want when we use styled-components.

I don't think this is possible, the rules are all [registered in a global cache](https://drafts.css-houdini.org/css-properties-values-api/#at-property-rule) so locally-scoped variants aren't really a thing.

**Comment by quantizor** [comment]
You could potentially make a stylis plugin that creates locally-scoped Houdini properties by appending the component hash to the property name and then substituting usage appropriately. Going to close this issue though since things are working according to spec.
