### ISSUE TITLE
Support for cssnext features?

### ISSUE THREAD

**Issue by tauren** [styled-components/styled-components#419]
I'm looking into how feasible it would be to migrate an app built using [css-modules](https://github.com/css-modules/css-modules), [postcss](http://postcss.org/), and [cssnext](http://cssnext.io/) to `styled-components`. I've heavily leveraged `cssnext` features such as `@apply`, `@nest`, `color()`, `calc()` with variables, and many more. 

Are these cssnext features even possible with `styled-components`? If so, what would be involved?

Here is some example CSS from the application that I would be migrating:

```
:root {
  --primaryBackgroundColor: color(red blackness(80%));

  --x0: {
    left: 0;
  }
  --x6: {
    left: 50%;
  }
  --y0: {
    top: 0;
  }
  --y6: {
    top: 50%;
  }
  --s6x6: {
    width: 50%;
    height: 50%;
  }
  --s12x12: {
    width: 100%;
    height: 100%;
  }
  --firstRow: {
    border-top-width: 0;
  }
  --lastRow: {
    border-bottom-width: 0;
  }
  --fistCol: {
    border-left-width: 0;
  }
  --lastCol: {
    border-right-width: 0;
  }
}

.grid {
  background-color: var(--primaryBackgroundColor);

  & header {
    display: none;
  }  

  @nest .fullscreen & {
    top: 0;
    left: calc(50vw - 16 / 9 / 2 * 100vh);
    width: calc(16 / 9 * 100vh);
    height: 100vh;

    @media (max-aspect-ratio: 16/9) {
      top: calc(50vh - (100vw * 9 / 16) / 2);
      left: 0;
      width: 100vw;
      height: calc(100vw * 9 / 16);
    }
  }
}

.grid1 {
  & > section {
    @apply --s12x12;
    @apply --x0;
    @apply --y0;
    @apply --firstRow;
    @apply --firstCol;
    @apply --lastRow;
    @apply --lastCol;
  }
  & > section:nth-of-type(n+2) {
    display: none;
  }
}

.grid2,
.grid3,
.grid4 {
  & > section {
    @apply --s6x6;
  }
  & > section:nth-of-type(1) {
    @apply --x0;
    @apply --y0;
    @apply --firstRow;
    @apply --firstCol;
  }
  & > section:nth-of-type(2) {
    @apply --x6;
    @apply --y0;
    @apply --firstRow;
    @apply --lastCol;
  }
  & > section:nth-of-type(3) {
    @apply --x0;
    @apply --y6;
    @apply --lastRow;
    @apply --firstCol;
  }
  & > section:nth-of-type(4) {
    @apply --x6;
    @apply --y6;
    @apply --lastRow;
    @apply --lastCol;
  }
  & > section:nth-of-type(n+5) {
    display: none;
  }
}

**Comment by mxstbr** [comment]
We don't do `cssnext` at all.

All of this would be possible to rewrite in `styled-components` of course, but you couldn't copy and paste it. Basically, all of these things are possible with Just JavaScript™️, but since they aren't right now there would need to be some rewriting.

**Comment by tauren** [comment]
@mxstbr Thanks for your response, but I think you may have misinterpreted my comment. I was hoping to have a conversation about possible approaches to take to bring `cssnext` support to `styled-components`. 

I do understand that [javascript can be used to our advantage](https://github.com/styled-components/styled-components/blob/master/docs/tips-and-tricks.md#using-javascript-to-our-advantage), and I'd like to use it to build cssnext support for anyone to use. I'm interested in contributing toward this goal. 

I have a few rough initial ideas on how to do this and am hoping you could add some input. If the first approach is something you wouldn't consider adding to `styled-components`, then I will focus on the second. Perhaps you'll have a much better solution.

### Plugin architecture

Add a plugin architecture to `styled-components`. For instance:

```
import styled from 'styled-components';
import colorPlugin from 'styled-plugin-color';
styled.use(colorPlugin);

const Button = styled.button`
  background: color(red blackness(80%));
`;
```

This would enable anyone to write plugins that add "native" support of `cssnext` features (or anything else for that matter). However, it would require parsing and transforming the CSS content.

### Helper library

Build a library of helper functions (or should they be called mixins, like in Sass?) For example:

```
import styled from 'styled-components';
import { color } from 'styled-components-cssnext';

const Button = styled.button`
  background: ${ color('red blackness(80%)') };
`;
```

This approach could be used today without changes to `styled-components`. An advantage is that parsing and transforming outside of what javascript template literals already provides isn't necessary. However CSS authors can't use pure css, so it's as clean. 

Support for `@apply` would be straightforward, but I'm not sure about `@nest`.

**Comment by mxstbr** [comment]
> Build a library of helper functions (or should they be called mixins, like in Sass?) For example:

Pssst, you hit the nail on the head—we're working on that 😉 Please contribute and help us finish it! https://github.com/styled-components/polished

**Comment by tauren** [comment]
Oh, cool! I hadn't discovered that project yet. Thanks, I'll check it out.
