### ISSUE TITLE
styled-components are not working with Next.js v14 SSR

### ISSUE THREAD

**Issue by jim-king-2000** [styled-components/styled-components#4199]
1. `styled-components` are not working with Next.js v14 SSR. It works with Next.js v13.x.x.
1. App router is used.
1. repro: <https://codesandbox.io/p/sandbox/heuristic-mclaren-crylc4>. Refresh the browser, the button would lose the style, then recover.
1. SSR settings reference: <https://nextjs.org/docs/app/building-your-application/styling/css-in-js#styled-components>

**Comment by akisvolanis** [comment]
Seems to be fixed by [this](https://github.com/vercel/next.js/pull/57784). It's been released with [v14.0.2-canary.1](https://github.com/vercel/next.js/releases/tag/v14.0.2-canary.1) for now.

**Comment by jim-king-2000** [comment]
Verified.
