### ISSUE TITLE
not finding the tar.gz file

### ISSUE THREAD

**Issue by amarkhakhkhar** [styled-components/styled-components#4201]
on doing npm i styled-components, it shows : 
E404
npm ERR! 404 Not Found - GET https://registry.yarnpkg.com/styled-components/ui/-/styled-components-5.3.6.tgz
npm ERR! 404
npm ERR! 404  'styled-components@https://registry.yarnpkg.com/styled-components/ui/-/styled-components-5.3.6.tgz' is not in this registry.        
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)

**Comment by probablyup** [comment]
Looks fine on npm https://www.npmjs.com/package/styled-components/v/5.3.6
