### ISSUE TITLE
Inconsistent CSS ordering when extending another styled component

### ISSUE THREAD

**Issue by BrianMwit** [styled-components/styled-components#4205]
## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown`
## System:
 - OS: Linux 6.1 Debian GNU/Linux 12 (bookworm) 12 (bookworm)
 - CPU: (2) x64 AMD EPYC
 - Memory: 351.36 MB / 2.01 GB
 - Container: Yes
 - Shell: 5.9 - /bin/zsh
## Binaries:
 - Node: 20.9.0 - /usr/local/bin/node
 - Yarn: 1.22.19 - /usr/local/bin/yarn
 - npm: 10.1.0 - /usr/local/bin/npm
## npmPackages:
 - babel-plugin-styled-components: ^2.1.4 => 2.1.4 
 - styled-components: 6.1.0 => 6.1.0

## Reproduction
https://codesandbox.io/p/sandbox/nextjs-with-styled-components-forked-4ctm34?file=%2Fpages%2Findex.js%3A14%2C42

## Steps to reproduce
See the browser. If it works as expected, try commenting/uncommenting Line 3, and/or 5-7 a few times.

## Expected Behavior
![image](https://github.com/styled-components/styled-components/assets/9075947/9e8c3ef8-a9a3-47a3-beb7-158fe079185e)

## Actual Behavior
![image](https://github.com/styled-components/styled-components/assets/9075947/70d54af9-a11e-4172-94b8-8063d14b18b8)

## Observations
So far, I can only semi-consistently reproduce this issue with NextJS 12-13 with babel-plugin-styled-components.
The base component (`const RedP = styled.p`) should be mounted server-side (and hydrated client-side)
The extended component (`const BlueP = styled(RedP)`) should only be mounted client-side, in this case via a single-use `useEffect` with 200ms delay.

Sometimes, the rendered CSS has the order swapped
```css
.efgyqS{ color: darkblue; } /* BlueP's override */
.eFuZaf{ color: darkred; background: lightgrey; } /* RedP's style */
```
With CSS for `BlueP` being above `RedP`, the `color` property from `RedP` takes precedent. Overrides defined in `BlueP` becomes ineffective.

We also find this behavior inconsistent. Commenting / uncommenting non-functional code, triggering a refresh, or restarting NextJS server can cause CSS to render in the correct order sometimes, wrong order the other times.
We have seen this issue both in NextJS built and dev mode.

This behavior applies to styled-component 6.x.x. It works fine in 5.3.11.

**Comment by probablyup** [comment]
Thanks for the repro, looks legit 👀

**Comment by BrianMwit** [comment]
Thanks Evan for the quick fix and release. Looks like the issue is resolved in the test demo repo.
We will confirm the fix in our main project in a week. Or feel free to close this issue otherwise

**Comment by probablyup** [comment]
Oh it is? I tried the update in the sandbox and it was still being weird...

**Comment by BrianMwit** [comment]
I updated it in https://codesandbox.io/p/sandbox/styled-components-6-1-1-test-xl63g9?file=%2Fpages%2Findex.js%3A5%2C1-7%2C3 and seems to work fine over multiple comments/uncomment cycles, unlike 6.1.0.
Have you restarted the sandbox's `dev` server after updating the package?

**Comment by probablyup** [comment]
Hmm I thought I did! Well glad to see it's fixed :)

**Comment by vamcs** [comment]
Oh amazing! Thanks for reporting and fixing this. I thought we were doing something stupid, because we've experienced this in production far too many times, and we had to start abusing the specificity bump `&&&` in many places. But good to know it was just because we're lagging behind some versions. Will update ASAP!
