### ISSUE TITLE
Nested ThemeProvider expects type of DefaultTheme

### ISSUE THREAD

**Issue by delijah** [styled-components/styled-components#4206]
We define a global theme for our app, but we also have themes for specific components. The data structure for the component theme differs from the default theme. This worked fine before version 6, now we get a TS error.

## System:
 - OS: macOS 12.6.1
 - CPU: (10) arm64 Apple M1 Max
 - Memory: 1.56 GB / 32.00 GB
 - Shell: 5.8.1 - /bin/zsh
## Binaries:
 - Node: 16.20.1 - /usr/local/bin/node
 - Yarn: 1.22.19 - /usr/local/bin/yarn
 - npm: 8.19.4 - /usr/local/bin/npm
## npmPackages:
 - babel-plugin-styled-components: 2.1.4 => 2.1.4
 - styled-components: 6.1.0 => 6.1.0

## Reproduction

https://codesandbox.io/s/peaceful-feather-dcxvlm?file=/index.tsx

## Steps to reproduce

Define a global theme and a theme for a specific component.

## Expected Behavior

No TS error

## Actual Behavior

TS error

**Comment by probablyup** [comment]
You're taking `typeof` of the original object which isn't made partial. If the Theme type is meant to have optional fields, you'll need to wrap `ThemeType` with Partial. The new behavior is more correct.

**Comment by delijah** [comment]
Hmmmm... but using Partial would mean that every prop on the theme could be undefined? Which means we have to use syntax like this all over our styled components (we have to use the `?` to check every nested key)?

```
const Component = styled.div`
    ${({ theme }) => theme.colors?.primary?.main};
`;
```

**Comment by quantizor** [comment]
Sorry for the late reply, did you know you can pass a function to `ThemeProvider` that receives the outer theme? That allows you to do something like this:

```tsx
<ThemeProvider theme={outer => ({...outer!, ...buttonTheme})}>
  <Button>Click me!</Button>
</ThemeProvider>
```

Then you don't need to use `Partial`.
