### ISSUE TITLE
Setting a CSS variable in `attrs` throws a TypeScript error

### ISSUE THREAD

**Issue by PatrickDeVries** [styled-components/styled-components#4209]
## System:
 - OS: macOS 13.4
 - CPU: (10) arm64 Apple M1 Pro
 - Memory: 52.38 MB / 16.00 GB
 - Shell: 5.9 - /bin/zsh
## Binaries:
 - Node: 18.16.0 - ~/.asdf/installs/nodejs/18.16.0/bin/node
 - Yarn: 4.0.1 - ~/.asdf/installs/nodejs/18.16.0/bin/yarn
 - npm: 9.5.1 - ~/.asdf/plugins/nodejs/shims/npm

(and code sandbox)
 
## Reproduction
[Codesandbox](https://codesandbox.io/p/sandbox/cranky-volhard-tx9zl5?file=%2Fsrc%2FApp.tsx%3A9%2C21)

## Steps to reproduce
- Try to set a CSS variable in `attrs`'s inline styles

## Expected Behavior
- Variable is set
- Variable is recognized as a valid entry

## Actual Behavior
- Variable is set
- TypeScript throws the following error:
```
Argument of type '({ dim }: ExecutionContext & FastOmit<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "dim"> & { ...; }) => { ...; }' is not assignable to parameter of type 'Attrs<Substitute<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, { dim: number; }>>'.
  Type '({ dim }: ExecutionContext & FastOmit<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "dim"> & { ...; }) => { ...; }' is not assignable to type '(props: ExecutionContext & FastOmit<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, "dim"> & { ...; }) => ExecutionProps & Partial<...>'.
    Call signature return types '{ style: { "--dim": string; }; }' and 'ExecutionProps & Partial<Substitute<DetailedHTMLProps<HTMLAttributes<HTMLDivElement>, HTMLDivElement>, { ...; }>>' are incompatible.
      The types of 'style' are incompatible between these types.
        Type '{ "--dim": string; }' has no properties in common with type 'Properties<string | number, string & {}>'.typescript(2345)
```
- The variable is set correctly and functions as seen in the sandbox, but there is a TS error

**Comment by probablyup** [comment]
Seems to be a general React issue https://stackoverflow.com/questions/52005083/how-to-define-css-variables-in-style-attribute-in-react-and-typescript
