### ISSUE TITLE
Warning: Failed %s type: %s%s, prop, Invalid prop `fontSize` of type `string` supplied to `Text`, expected `number`.

### ISSUE THREAD

**Issue by Bibinthayyil** [styled-components/styled-components#4220]
Hello Team,

I am getting the below error, please help me. 

Bad object: {
  "fontSize": "25",
  "fontWeight": "400",
  "fontFamily": "System",
  "color": "#222B45"
}, 
    at Text (http://192.168.1.141:19000/index.bundle//&platform=ios&dev=true&hot=false&strict=false&minify=false:81032:27)
    in Text
    in Wrapper (created by Text)
    in WrappingElement (created by LoginScreen)
    in RCTView (created by View)
    in View (created by LoginScreen)
    in RCTView (created by View)
    in View (created by LoginScreen)
    in RCTScrollContentView (created by ScrollView)
    in RCTScrollView (created by ScrollView)
    in ScrollView (created by ScrollView)
    in ScrollView (created by LoginScreen)
    in RCTView (created by View)
    in View (created by LoginScreen)
    in LoginScreen (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by CardContainer)
    in RCTView (created by View)
    in View (created by CardContainer)
    in RCTView (created by View)
    in View (created by CardContainer)
    in RCTView (created by View)
    in View
    in CardSheet (created by Card)
    in RCTView (created by View)
    in View
    in Unknown (created by PanGestureHandler)
    in PanGestureHandler (created by PanGestureHandler)
    in PanGestureHandler (created by Card)
    in RCTView (created by View)
    in View
    in Unknown (created by Card)
    in RCTView (created by View)
    in View (created by Card)
    in Card (created by CardContainer)
    in CardContainer (created by CardStack)
    in RNSScreen
    in Unknown (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by CardStack)
    in RNSScreenContainer (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by CardStack)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by CardStack)
    in CardStack (created by HeaderShownContext)
    in RCTView (created by View)
    in View (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by StackView)
    in RCTView (created by View)
    in View (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by StackView)
    in StackView (created by StackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by StackNavigator)
    in StackNavigator (created by Auth)
    in Auth (created by SceneView)
    in StaticContainer
    in EnsureSingleNavigator (created by SceneView)
    in SceneView (created by CardContainer)
    in RCTView (created by View)
    in View (created by CardContainer)
    in RCTView (created by View)
    in View (created by CardContainer)
    in RCTView (created by View)
    in View
    in CardSheet (created by Card)
    in RCTView (created by View)
    in View
    in Unknown (created by PanGestureHandler)
    in PanGestureHandler (created by PanGestureHandler)
    in PanGestureHandler (created by Card)
    in RCTView (created by View)
    in View
    in Unknown (created by Card)
    in RCTView (created by View)
    in View (created by Card)
    in Card (created by CardContainer)
    in CardContainer (created by CardStack)
    in RNSScreen
    in Unknown (created by InnerScreen)
    in Suspender (created by Freeze)
    in Suspense (created by Freeze)
    in Freeze (created by DelayedFreeze)
    in DelayedFreeze (created by InnerScreen)
    in InnerScreen (created by Screen)
    in Screen (created by MaybeScreen)
    in MaybeScreen (created by CardStack)
    in RNSScreenContainer (created by ScreenContainer)
    in ScreenContainer (created by MaybeScreenContainer)
    in MaybeScreenContainer (created by CardStack)
    in RCTView (created by View)
    in View (created by Background)
    in Background (created by CardStack)
    in CardStack (created by HeaderShownContext)
    in RNCSafeAreaProvider (created by SafeAreaProvider)
    in SafeAreaProvider (created by SafeAreaInsetsContext)
    in SafeAreaProviderCompat (created by StackView)
    in RCTView (created by View)
    in View (created by GestureHandlerRootView)
    in GestureHandlerRootView (created by StackView)
    in StackView (created by StackNavigator)
    in PreventRemoveProvider (created by NavigationContent)
    in NavigationContent
    in Unknown (created by StackNavigator)
    in StackNavigator (created by App)
    in EnsureSingleNavigator
    in BaseNavigationContainer
    in ThemeProvider
    in NavigationContainerInner (created by App)
    in ThemeProvider (created by StyleProvider)
    in MappingProvider (created by StyleProvider)
    in StyleProvider (created by ApplicationProvider)
    in ApplicationProvider (created by App)
    in App (created by withDevTools(App))
    in withDevTools(App)
    in RCTView (created by View)
    in View (created by AppContainer)
    in RCTView (created by View)
    in View (created by AppContainer)
    in AppContainer
    in main(RootComponent)
at node_modules\react\cjs\react-jsx-runtime.development.js:null in printWarning
at node_modules\react\cjs\react-jsx-runtime.development.js:null in error
at node_modules\react\cjs\react-jsx-runtime.development.js:null in checkPropTypes
at node_modules\react\cjs\react-jsx-runtime.development.js:null in validatePropTypes
at node_modules\react\cjs\react-jsx-runtime.development.js:null in jsxWithValidation
at node_modules\react\cjs\react-jsx-runtime.development.js:null in jsxWithValidationDynamic
at node_modules\@ui-kitten\components\ui\text\text.component.js:null in Text#render
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in finishClassComponent
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in updateClassComponent
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in beginWork
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in beginWork$1
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in performUnitOfWork
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in workLoopSync
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in renderRootSync
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in performSyncWorkOnRoot
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in flushSyncCallbacks
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in flushSyncCallbacksOnlyInLegacyMode
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in scheduleUpdateOnFiber
at node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:null in dispatchSetState
at node_modules\@react-navigation\core\src\useSyncState.tsx:null in useSyncState
at node_modules\@react-navigation\core\src\useNavigationBuilder.tsx:null in useNavigationBuilder
at node_modules\@react-navigation\core\src\useOnAction.tsx:null in onAction
at node_modules\@react-navigation\core\src\useNavigationHelpers.tsx:null in dispatch
at node_modules\@react-navigation\core\src\useNavigationCache.tsx:null in dispatch
at node_modules\@react-navigation\core\src\useNavigationCache.tsx:null in Object.keys.reduce$argument_0
at node_modules\@react-navigation\core\src\useNavigationCache.tsx:null in withStack
at node_modules\@react-navigation\core\src\useNavigationCache.tsx:null in withStack$argument_0
at Screen\SplashScreen.js:null in useEffect$argument_0
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:null in queueReactNativeMicrotask
at node_modules\react-native\Libraries\Core\Timers\JSTimers.js:null in _callTimer
- ... 8 more stack frames from framework internals

**Comment by quantizor** [comment]
Make the stringified numbers real numbers
