### ISSUE TITLE
Vendor prefix not working on client-side rendering (v6)

### ISSUE THREAD

**Issue by caaatisgood** [styled-components/styled-components#4222]
I'm upgrading SC from `v5.3.5` to `v6.1.1` on a Next.js app. As indicated in the [migration doc](https://styled-components.com/docs/faqs#vendor-prefixes-are-omitted-by-default), vendor prefixes are omitted by default starting from v6. Hence I had to manually enable it for now due to project needs and to make the migration a bit smoother.

The issue I ran into is that vendor prefixes seem to be applied on SSR only. If you go to [this example CSR page](https://nextjs-styled-components-vendor-prefix-bug.vercel.app/csr) which renders a paragraph with `user-select: none` and an icon that uses `mask-image`, you'll see that the prefixes are not being added. But if you go to the [this example SSR page](https://nextjs-styled-components-vendor-prefix-bug.vercel.app/ssr) which renders essentially the same mark up but on server-side, it works.

## Environment

`npx envinfo --system --binaries --npmPackages styled-components,babel-plugin-styled-components --markdown`

## System:
 - OS: macOS 13.1
 - CPU: (10) arm64 Apple M1 Max
 - Memory: 63.95 MB / 32.00 GB
 - Shell: 5.8.1 - /bin/zsh
## Binaries:
 - Node: 18.18.2 - ~/.asdf/installs/nodejs/18.18.2/bin/node
 - Yarn: 1.22.19 - ~/.asdf/installs/nodejs/18.18.2/bin/yarn
 - npm: 10.2.3 - ~/.asdf/plugins/nodejs/shims/npm
 - pnpm: 8.10.5 - ~/.asdf/installs/nodejs/18.18.2/bin/pnpm
## npmPackages:
 - styled-components: ^6.1.0 => 6.1.1

## Reproduction

Repo for reproducing this issue https://github.com/caaatisgood/nextjs-styled-components-vendor-prefix-bug
Live demo: https://nextjs-styled-components-vendor-prefix-bug.vercel.app/

## Steps to reproduce

1. Visit [/csr](https://nextjs-styled-components-vendor-prefix-bug.vercel.app/csr)
2. Inspect the paragraph and the icon. You'll see the vendor prefixes are missing.

### Additional experiments

If you visit [/csr](https://nextjs-styled-components-vendor-prefix-bug.vercel.app/csr) directly first. And then go to [/ssr](https://nextjs-styled-components-vendor-prefix-bug.vercel.app/ssr) or [/](https://nextjs-styled-components-vendor-prefix-bug.vercel.app/) which includes both CSR and SSR examples via client-side routing. All the vendor prefixes are missing.

But if you visit [/](https://nextjs-styled-components-vendor-prefix-bug.vercel.app/) or [/ssr](https://nextjs-styled-components-vendor-prefix-bug.vercel.app/ssr) first. The vendor prefixes works on all pages. Hence, I guess there're some issues with vendor prefixing client-side rendered UIs.

I also tested the same thing with v5, [branch `feature/sc-v5` is here](https://github.com/caaatisgood/nextjs-styled-components-vendor-prefix-bug/tree/feature/sc-v5), [live demo is here](https://nextjs-styled-components-vendor-prefix-o2pu6q2uu-caaatisgood.vercel.app). All seems to work fine.

## Expected Behavior

The vendor prefixes should be included in client-side rendering

## Actual Behavior

The vendor prefixes are missing and broke the styles

**Comment by quantizor** [comment]
Add another `StyleSheetManager` with `enableVendorPrefixes` in `_app` above `ThemeProvider`, the one in `_document.tsx` is only for SSR so you need a matching client-side provider.

**Comment by caaatisgood** [comment]
ah mb, thanks for the hint @quantizor!
