### ISSUE TITLE
Bug: Styles are leaking to whole application

### ISSUE THREAD

**Issue by pgsandstrom** [styled-components/styled-components#4224]
## Reproduction

Here is a codesandbox example using v6.1.1, I hope this is sufficient to show what is happening. The red row should not be styled since it is completely outside any styled-component.

https://codesandbox.io/s/styled-components-base-forked-krjsxn?file=/index.js

## Additional info

The syntax below is compiled in such a way as that the rule affecting `p` tags is placed outside the scope of the styled-component. It seems to be the combination of  a parent selector and pseudo-classes that trips styled-component up.

```
&.foo,
  p:not(:last-child) {
    background: red;
  }
```

**Comment by nohaibogdan1** [comment]
Perhaps it is a bug coming from styles.compile

**Comment by mcmgeomagic1** [comment]
Your styled component StyleThatLeaks has a CSS rule that targets p elements that are not the last child within their respective parent. The CSS rule specified in &.foo, p:not(:last-child) doesn't specifically require the p tags to be within a styled component to apply the styles. It affects all p tags that are not the last child within their parent, regardless of where they are in the DOM structure.

If you want to limit the scope of this CSS rule only to p elements within the StyleThatLeaks component, you might need to adjust your CSS rule or use a more specific selector to target only the desired p elements within that component. For example, you could prefix the p:not(:last-child) selector with .foo to restrict it to p elements within the StyleThatLeaks component with the foo class:

```
const StyleThatLeaks = styled.div`
  background: green;

  &.foo,
  &.foo p:not(:last-child) {
    background: red;
  }
`;
```

**Comment by pgsandstrom** [comment]
@mcmgeomagic1 that has to be written by an AI, right?

**Comment by quantizor** [comment]
Made an issue over on stylis https://github.com/thysultan/stylis/issues/321

**Comment by quantizor** [comment]
If you don't need container queries, you can try temporarily pinning your application using package.json `resolutions` or `overrides` to 4.0.10 or earlier per [this comment](https://github.com/thysultan/stylis/issues/321#issuecomment-1868128903)
