### ISSUE TITLE
Getting error "ReferenceError: Property 'CssSyntaxError' doesn't exist" while using styled-component in React native repack project.

### ISSUE THREAD

**Issue by jigaradesara01** [styled-components/styled-components#4226]
## Environment

"react": "18.2.0",
"react-native": "0.72.7",
"styled-components": "^6.1.1",
"@callstack/repack": "^3.6.0"

## Description

I'm trying to use styled-component in react native repack project but getting "Property 'CssSyntaxError' doesn't exist react native" while running the project.

Repack project sample:
https://github.com/callstack/repack

<img width="1018" alt="Screenshot 2023-12-05 at 8 44 52 AM" src="https://github.com/callstack/repack/assets/152942717/ebc5b0a5-b8ce-45b7-afc1-a3426b63827a">

![Screenshot_1701746204](https://github.com/callstack/repack/assets/152942717/3b974018-9121-4c17-b0e5-a272e0124511)

##LocalModule.tsx

````import React from 'react';
import { Text } from 'react-native';
import styled from 'styled-components/native';

const LocalModule = () => {
    return (
        <Container>
            <Text >React Native</Text>
        </Container>
    );
};

const Container = styled.View`
      flex: 1;
      background-color: white;
      align-items: center;
      justify-content: center;
    `;


export default LocalModule;
```

Thanks in advance.

**Comment by quantizor** [comment]
My guess is multiple versions of `postcss` are installed and it's causing issues. We could add `postcss` to `peerDependencies` so it dedupes better.

**Comment by quantizor** [comment]
Try `styled-components@6.1.5-rc.0` and let me know if that resolves it (adds `postcss` as a peer dependency)
