### ISSUE TITLE
Styled-components v6 typescript not recognizing default props type -  Parameter 'props' implicitly has an 'any' type

### ISSUE THREAD

**Issue by thegladysadjei** [styled-components/styled-components#4233]
## System:
 - OS: macOS 14.1.1
 - CPU: (12) arm64 Apple M3 Pro
 - Memory: 311.97 MB / 36.00 GB
 - Shell: 5.9 - /bin/zsh
## Binaries:
 - Node: 20.9.0 - /usr/local/bin/node
 - npm: 10.1.0 - /usr/local/bin/npm
## npmPackages:
 - styled-components: ^6.1.1 => 6.1.1 
 

I upgraded to styled-components v6 and running into an error I can't find a solution anywhere. I used tsdx and storybook to create a design system library.

I have this code
```
export const ThemeWrapper: React.FunctionComponent<IThemeWrapperProps> = (
  props
) => {
  return (
    <ThemeProvider theme={LightTheme}>
        <GlobalStyles />
        <main>
          {props.children}
        </main>
      </ThemeProvider>
  );
};

const GlobalStyles = createGlobalStyle`
  body {
    font-family:${(props) => `${props.theme.typography.fontFamily} !important`};
    .h-100 {
      height: 100%
    }
    .w-100 {
      width: 100%
    }
  }
`;
```
After upgrading to styled-components v6, when I run `npx tsdx build` I get the below error
`semantic error TS7006: Parameter 'props' implicitly has an 'any' type.`

**Comment by Martinocom** [comment]
Reading the docs, I think this is on purpose:
https://styled-components.com/docs/api#helpers

Inside the docs they explicitly specify the type.
```
/*      Explicit type here ⤵        */
createGlobalStyle<{ $whiteColor?: boolean; }>`
  body {
    color: ${props => (props.$whiteColor ? 'white' : 'black')};
  }
`
```

**Comment by quantizor** [comment]
@thegladysadjei do you have a module augmentation setup to provide the theme? https://github.com/styled-components/styled-components/blob/93ea0f339e5ba360db7ddd8c92b8c4d1ab0f9051/packages/styled-components/src/models/ThemeProvider.tsx#L11-L18
