### ISSUE TITLE
Cannot call a class as a function

### ISSUE THREAD

**Issue by pungggi** [styled-components/styled-components#424]
Hello i am trying to follo your example at https://github.com/styled-components/styled-components/blob/master/docs/tips-and-tricks.md#media-templates

I have a copy of this code
![image](https://cloud.githubusercontent.com/assets/5635709/22402879/dbd509ca-e606-11e6-8fcb-85d5b63a47da.png)

importing it like
![image](https://cloud.githubusercontent.com/assets/5635709/22402883/0dea580c-e607-11e6-810d-173577237783.png)

and using like this
![image](https://cloud.githubusercontent.com/assets/5635709/22402882/02ce6396-e607-11e6-9d80-399f893a4c73.png)

I am getting error:

![image](https://cloud.githubusercontent.com/assets/5635709/22402881/f79400da-e606-11e6-9a03-bb233137f9cc.png)

I am using version:
![image](https://cloud.githubusercontent.com/assets/5635709/22402894/34dc9376-e607-11e6-8f2f-9f9c9856c7a4.png)

**Comment by mxstbr** [comment]
We can't provide support for `inferno-compat`ed apps I'm afraid. That definitely sounds like a problem with your setup, as that code works perfectly fine in my standard React app.
