### ISSUE TITLE
Export the `toStyleSheet` function

### ISSUE THREAD

**Issue by TikiTDO** [styled-components/styled-components#4284]
[This function](https://github.com/styled-components/styled-components/blob/22e8b7f233e12500a68be4268b1d79c5d7f2a661/packages/styled-components/src/native/index.ts#L83) could be useful in a ReactNative app when doing something like this:

```
<ScrollView contentContainerStyle={[reactNativeStyles.flexSingle]}>
   ...
```

At the moment we have to keep a part of our styles config using `StyleSheet.create` because there's a few places that are not handled by the styled-component magic interpolation.

If this function was available to import, then it would allow us to use the same styling rules everywhere. 

If this is acceptable then I can submit a PR.

**Comment by krudos** [comment]
you can use like this

`
import {toStyleSheet} from 'styled-components/native';

`

**Comment by TikiTDO** [comment]
@krudos Are you sure about that?

![image](https://github.com/styled-components/styled-components/assets/326184/874854da-43b7-4420-8848-6f129124070e)

I tried checking if it's just the types, but even ignoring the type errors I don't see that sort of import:

![image](https://github.com/styled-components/styled-components/assets/326184/4b9f81c3-b465-4b65-91cd-ad73ed2ed689)

**Comment by TikiTDO** [comment]
Ah, I'm out of date. That would do it.
