### ISSUE TITLE
Issue with css function and TypeScript

### ISSUE THREAD

**Issue by levrik** [styled-components/styled-components#430]
## Version
1.4.2

## Steps to reproduce

1st example:
```javascript
const handheld = (...args) => css`
  @media (max-width: 420px) {
     ${css(...args)}
  }
`;
```

2nd example:
```javascript
function handheld<P>(strings: TemplateStringsArray, ...interpolations: Interpolation<P>[]) {
  return css`
    @media (max-width: 420px) {
      ${css(strings, ...interpolations)}
    }
  `;
}
```

3rd example:
```javascript
const handheld = () => css`
  @media (max-width: 420px) {
     ${css`
      background-color: #000;
    `}
  }
`;
```

## Expected Behavior
TypeScript is fine with it.

## Actual Behavior
TypeScript throws the following errors:

1st example:

```
Supplied parameters do not match any signature of call target.
```

2nd example:

```
Argument of type 'Interpolation<P>[]' is not assignable to parameter of type 'Interpolation<P>'.
  Type 'Interpolation<P>[]' is not assignable to type 'ReadonlyArray<string | number | InterpolationFunction<P>>'.
    Types of property 'concat' are incompatible.
      Type '{ (...items: Interpolation<P>[][]): Interpolation<P>[]; (...items: (string | number | Interpolati...' is not assignable to type '{ <U extends ReadonlyArray<string | number | InterpolationFunction<P>>>(...items: U[]): (string |...'.
        Type 'Interpolation<P>[]' is not assignable to type '(string | number | InterpolationFunction<P>)[]'.
          Type 'Interpolation<P>' is not assignable to type 'string | number | InterpolationFunction<P>'.
            Type 'ReadonlyArray<string | number | InterpolationFunction<P>>' is not assignable to type 'string | number | InterpolationFunction<P>'.
              Type 'ReadonlyArray<string | number | InterpolationFunction<P>>' is not assignable to type 'InterpolationFunction<P>'.
                Type 'ReadonlyArray<string | number | InterpolationFunction<P>>' provides no match for the signature '(props: StyledProps<P>): string | number | ReadonlyArray<Interpolation<P>>'
```

3rd example:

```
Argument of type 'Interpolation<{}>[]' is not assignable to parameter of type 'Interpolation<{}>'.
  Type 'Interpolation<{}>[]' is not assignable to type 'ReadonlyArray<string | number | InterpolationFunction<{}>>'.
```

**Comment by mxstbr** [comment]
cc @styled-components/typers

**Comment by Igorbek** [comment]
2nd and 3rd examples should've been fixed with #428 
1st is more related to TypeScript itself. You cannot prove that `handheld` wouldn't be used in inappropriate way. Allowing proper typing for this requires long-waited variadic kind feature in TypeScript.

**Comment by levrik** [comment]
Okay, I already thought that the first one is not related to this library but I'm very new to TypeScript so I wasn't sure. I will test out the current `master` and close this ticket if the issue is resolved :)

**Comment by sahilkhan99** [comment]
It is late to comment here I believe, but I'm new to typescript as well, and found the below solutions works for me for media queries in styled component 

```
import { css } from "styled-components";

export const breakpoints = {
  desktop: "(min-width: 1025px)",
  ipadProLandscape:
    "only screen and (min-device-width : 1024px) and (max-device-width : 1024px) and (min-device-height : 1366px) and (max-device-height : 1366px) and (min-width: 1366px) and (max-width: 1366px) and (orientation: landscape) and (-webkit-min-device-pixel-ratio: 2)",
  ipadProPortrait:
    "only screen and (min-device-width : 1024px) and (max-device-width : 1024px) and (min-device-height : 1366px) and (max-device-height : 1366px) and (min-width: 1024px) and (max-width: 1024px) and (orientation: portrait) and (-webkit-min-device-pixel-ratio: 2)",
  mobileTablet: "(max-width: 1024px)",
  mobile: "(max-width: 680px)",
  tablet: "(min-width: 681px) and (max-width: 1024px)",
  tabletDesktop: "(min-width: 681px)",
  screen: "(min-width: 1400px)",
  averageMobile: "(max-width: 480px)",
  extraSmallMobile: "(max-width: 320px)"
};

const getMediaBreakpoints = () => {
  const mediaquery = {} as Record<keyof typeof breakpoints, (l: TemplateStringsArray, ...args: any[]) => string>;
  Object.keys(breakpoints).forEach(breakpoint => {
    media[breakpoint] = (literals: TemplateStringsArray, ...args: any[]) => css`
      @media ${breakpoints[breakpoint]} {
        ${css(literals, ...args)};
      }
    `;
  });
  return mediaquery;
};

export const media = getMediaBreakpoints();

```

Then I use in all my react components as 

```
import { media } from "../../helpers/style-utils";

const LogoWrapper = styled.div`
  height: 50px;
  width: 180px;
  margin-right: auto;
  ${media.mobile`
    height: 40px;
    width: 144px;
  `}
`;
```

Hope this is helpful to others too.

**Comment by shiftsave** [comment]
@sahilkhan99 Thanks! I tried implementing this but I get
```TypeError: Cannot set property 'desktop' of undefined```

Any ideas as to why this is? I implemented exactly as you posted

**Comment by hodovani** [comment]
@shiftsave 
inside `getMediaBreakpoints` you should acess to variable  `mediaquery`
`
import { css } from "styled-components";

const breakpoints = {
  desktop: 730,
};

const getMediaBreakpoints = () => {
  const mediaquery = {} as Record<
    keyof typeof breakpoints,
    (l: TemplateStringsArray, ...args: any[]) => string
  >;
  Object.keys(breakpoints).forEach((breakpoint) => {
    mediaquery[breakpoint] = (
      literals: TemplateStringsArray,
      ...args: any[]
    ) => css`
      @media ${breakpoints[breakpoint]} {
        ${css(literals, ...args)};
      }
    `;
  });
  return mediaquery;
};

export const media = getMediaBreakpoints();
`

But for me, this does not work and generate broken CSS. 
Example:
`
      @media ,730, {
        ,font-size: ,4.5,rem,;
      }
`

**Comment by hodovani** [comment]
I need a solution to support the situation where I give media function variable.
That is worked for me now
realization
`
const sizes = {
  desktop: 730,
};
const initMedia = {
  desktop: (args: string) =>
    "@media (min-width: " + sizes[sizes.desktop] + "px) {" + args + "}",
};
const media = Object.keys(sizes).reduce((acc: any, label) => {
  acc[label] = (args: string) =>
    "@media (min-width: " + sizes[label] + "px) {" + args + "}";
  return acc;
}, initMedia);

export default media;
`
example of use
`
import media from "../helpers/createMediaQuery";

const Text = styled.div<{
  size: Size | Size[];
}>`
  ${({ size }) => {
    if (typeof size !== "string") {
      return (
        "font-size: " +
        size[0] +
        "rem;" +
        media.desktop("font-size: " + size[1] + "rem")
      );
    }
    return `font-size: ${size}rem;`;
  }};
`;
`

**Comment by hodovani** [comment]
The solution that worked with literals
```
import { css } from "styled-components";

const sizes = {
  desktop: 730,
};

const media = Object.keys(sizes).reduce(
  (acc, label) => {
    acc[label] = (literals: TemplateStringsArray, ...placeholders: any[]) =>
      css`
        @media (max-width: ${sizes[label]}px) {
          ${css(literals, ...placeholders)};
        }
      `.join("");
    return acc;
  },
  {} as Record<
    keyof typeof sizes,
    (l: TemplateStringsArray, ...p: any[]) => string
  >,
);

export default media;
```
based on https://stackoverflow.com/questions/49397538/typing-the-css-function-in-styled-components but with`.join("")`

**Comment by GraxMonzo** [comment]
> The solution that worked with literals
> 
> ```
> import { css } from "styled-components";
> 
> const sizes = {
>   desktop: 730,
> };
> 
> const media = Object.keys(sizes).reduce(
>   (acc, label) => {
>     acc[label] = (literals: TemplateStringsArray, ...placeholders: any[]) =>
>       css`
>         @media (max-width: ${sizes[label]}px) {
>           ${css(literals, ...placeholders)};
>         }
>       `.join("");
>     return acc;
>   },
>   {} as Record<
>     keyof typeof sizes,
>     (l: TemplateStringsArray, ...p: any[]) => string
>   >,
> );
> 
> export default media;
> ```
> 
> based on https://stackoverflow.com/questions/49397538/typing-the-css-function-in-styled-components but with`.join("")`

Why did you use `.join()`?
