### ISSUE TITLE
Change style based on React state

### ISSUE THREAD

**Issue by Ronnyrr** [styled-components/styled-components#431]
Hi there,

Is it possible to change the css based on a React components state including a transition? Currently I have the code as shown below. The state is changed, and my `<FooterElem />` did go to bottom `-50px`, but this is a "hard change". How can I let the transitions do it's job?

```javascript
class Footer extends Component {
  constructor(props) {
    super(props);
    this.state = { showFooter: true };
  }

  componentDidMount() {
    window.addEventListener('resize', () => {
      this.setState({ showFooter: window.innerHeight > 400 });
    });
  }

  render() {
    const FooterElem = styled.footer`
      position: fixed;
      bottom: ${this.state.showFooter ? '0' : '-50px'};
      left: 0;
      width: 100%;
      transition: bottom .5s ease-in;
    `;

    return (
      <FooterElem></FooterElem>
    );
  }
}
```

**Comment by mxstbr** [comment]
I'm 99% sure that this is not a problem with `styled-components` but with CSS 😉 

In general it's advised to only ever animate `transform` or `opacity`, as everything else has performance issues. (see [here](https://blogs.adobe.com/webplatform/2014/03/18/css-animations-and-transitions-performance/)) So your code would become:

```
    const FooterElem = styled.footer`
      position: fixed;
      bottom: 0;
      left: 0;
      width: 100%;
      transform: translateY(${props.visible ? '0px' : '-50px'});
      transition: transform .5s ease-in;
    `;

class Footer extends Component {
  constructor(props) {
    super(props);
    this.state = { showFooter: true };
  }

  componentDidMount() {
    window.addEventListener('resize', () => {
      this.setState({ showFooter: window.innerHeight > 400 });
    });
  }

  render() {
    return (
      <FooterElem visible={this.state.showFooter}></FooterElem>
    );
  }
}
```

> Note: I've also moved the `FooterElem` declaration out of the `render` method, otherwise you're re-creating that unnecessarily on every render.

Does that work for you?

**Comment by Ronnyrr** [comment]
Perfect, problem solved indeed. Only thing needed was `transform: translateY(${props => props.visible ? '0px' : '60px'});` or else `props` was undefined. Also thanks for the heads up about transitions.

**Comment by mxstbr** [comment]
> Only thing needed was transform: translateY(${props => props.visible ? '0px' : '60px'}); or else props was undefined.

Ah yeah, sorry about that! Updated the snippet for people finding this via search 😊

Very happy to help.

**Comment by VeeruSA** [comment]
Hi, I want to display data in cards, if I have only one record in DB, I need to display only one card with big size like post card size in the center, if 2 records then 2 post cards displaying side by side and if 3 records then need to display 3 cards smaller than the post card. My code is as below..Plz help me

import React, { Component } from 'react';
import Pagination from '../components/pagination';
import _ from 'lodash';
import { connect } from 'react-redux';
import * as actions from '../actions/index';

class Main extends Component {
  componentWillMount() {
    this.props.fetchStudents();
  }

  constructor() {
    super();

    this.state = {
      pageOfItems: []
    };
    
    this.onChangePage = this.onChangePage.bind(this);
  }

    onChangePage(pageOfItems) {
        this.setState({ pageOfItems: pageOfItems });
    }

    render() {
      return (
        <div>
        <div className="myHeader container">
          <h2>My Page Header</h2>
        </div>
          <div className="text-center container">
          {this.state.pageOfItems.map(student =>
              <div className="col-sm-2 col-md-2 col-lg-2 col-xs-4">
              {/*Card*/}
                <div className="view">
                  <li key={student.id} className="card">
                  <img className="img-fluid" src={student.photo} alt="Image Loading.." />
                    <div className="card-block">
                      <h4 className="card-title">ID: {student.id}</h4>
                      <p className="card-text">{student.firstName} {student.lastName}</p>
                      <p> Branch: {student.branch}</p>
                    </div>
                  </li>
                </div>
              </div>
          )}
          </div>
        <div className="pages">
          <Pagination items={this.props.students} onChangePage={this.onChangePage} />
        </div>
      </div>
      );
    }
  }

function mapStateToProps(state) {
  return { students: state.students.all };
}

export default connect(mapStateToProps, actions)(Main);

**Comment by mxstbr** [comment]
This question has been answered, please post your custom question on [StackOverflow with the `styled-components` tag](https://stackoverflow.com/questions/tagged/styled-components)!

I'm going to lock this issue since there's nothing to add here.
