### ISSUE TITLE
Styled-components nao trabalha no react-native 0.72.2

### ISSUE THREAD

**Issue by MuriloBarranco** [styled-components/styled-components#4334]
Currently, styled-components is not working correctly with "react": "18.2.0" and "react-native": "0.72.2". I am using Node.js version 18.20.4 and npm version 10.7.0.

package.json "
{
  "name": "teste",
  "version": "1.0.0",
  "main": "index.js",
  "scripts": {
    "start": "expo start --dev-client",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~51.0.20",
    "expo-status-bar": "~1.12.1",
    "react": "18.2.0",
    "react-native": "0.72.2"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}
"

Log error: 

npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: teste@1.0.0
npm error Found: react@18.3.1
npm error node_modules/react
npm error   react@"18.2.0" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react@"18.2.0" from react-native@0.72.2
npm error node_modules/react-native
npm error   react-native@"0.72.2" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error /Users/dev_barranco/.npm/_logs/2024-07-19T19_49_03_745Z-eresolve-report.txt

npm error A complete log of this run can be found in: /Users/dev_barranco/.npm/_logs/2024-07-19T19_49_03_745Z-debug-0.log

To get the package working, I need to use the command npm i styled-components --force. However, I prefer to avoid using --force to install libraries.

Thank you in advance for your attention. I would be very grateful if you could assist me.

**Comment by patrickpecegueiro** [comment]
same problem, any soluction?

**Comment by MuriloBarranco** [comment]
To fix the error, follow the steps below:

1 - Delete the node_modules folder

`rm -rf node_modules`

2 - Add styled-components to your package.json
Open your package.json file and add the following line to the dependencies section:

`"styled-components": "^5.1.1"`

3 - Update the react-dom version
In the package.json file, check the dependencies section
Replace the react-dom line with the following, using your current React version

`"react-dom": "[YOUR CURRENT REACT VERSION]"`

After making these changes, reinstall your dependencies:
`npm install`

If you need anything else, feel free to ask! 🤟🏻
