### ISSUE TITLE
[Feature Request] Make the generated classNames more semantic

### ISSUE THREAD

**Issue by viankakrisna** [styled-components/styled-components#435]
the current classNames are hash, it's actually a pain to navigate in the developer tools.

Proposal:

Prepend the classname with the display name of the component if the environment is development. 

example:

`class="eVnmAw"`

to

`class="App_eVnmAw"`

with this code:

```
const App = styled.div`
    margin: 0;
    padding: 0;
`;

App.displayName = 'App'

**Comment by mxstbr** [comment]
Coming in version two!

You can try it out by doing `npm install --save styled-components@next`, and then you can use the babel plugin (not released yet) by doing `npm install --save-dev babel-plugin-styled-components` to get semantic classNames without even having to do the `.displayName` stuff yourself 🙌

**Comment by viankakrisna** [comment]
great!

**Comment by joeshub** [comment]
Sweet, also is anyone keeping a v2 doc up to date or a list of v2 features somewhere? thanks

**Comment by mxstbr** [comment]
> Sweet, also is anyone keeping a v2 doc up to date or a list of v2 features somewhere? thanks

See the `v2` branch CHANGELOG.md!
