### ISSUE TITLE
[v2] absolute path urls not working

### ISSUE THREAD

**Issue by garmjs** [styled-components/styled-components#437]
# Version

styled-components@next or @2.0

# Steps to reproduce
```
styled(Link)`
  background-image: url('/static/media/img/logo.svg');
```

# Expected Behavior
it works like in v1

# Actual Behavior

```
.logo__LogoLink-15bytqr {
}
```

**Comment by k15a** [comment]
I think this is fixed with stylis 1.0.1.

**Comment by mxstbr** [comment]
Can you try with `npm install styled-components@2.0.0-1` @garmjs? If this is fixed in `stylis@1.0.1` then this should resolve the issue.

**Comment by garmjs** [comment]
@mxstbr checked and its working 🎉

**Comment by mxstbr** [comment]
Awesome, glad to hear!
