### ISSUE TITLE
onPress is not getting called in react-native

### ISSUE THREAD

**Issue by ritz078** [styled-components/styled-components#442]
## Version
1.4.2

## Steps to reproduce

```
const SwitchWrapper = styled.View`
  background-color: ${props => props.theme.main};
  width: 44;
  height: 24;
  border-radius: 12;
  padding: 2;
  position: relative;
`;

const SwitchBtn = styled.View`
  height: 20;
  width: 20;
  position: absolute;
  background-color: #fff;
  transform: translateX(0);
`

<SwitchWrapper onPress={this.handlePress}>
  <SwitchBtn/>
</SwitchWrapper>
```

## Expected Behavior

`this.handlePress` should get called.

## Actual Behavior

Its not getting called.

Is there anything I am missing ?

**Comment by mxstbr** [comment]
I'm pretty sure `onPress` only works for `Button`s, change your `SwitchBtn` to `styled.Button` and everything should be working perfectly fine hopefully?

**Comment by ritz078** [comment]
Thanks for the quick reply. You are right. Should have gone to stackoverflow. Sorry for that. :)

**Comment by mxstbr** [comment]
No worries, glad I could help!
