### ISSUE TITLE
Including styled-components when building Chrome extension with create-react-app results in loading error

### ISSUE THREAD

**Issue by drhayes** [styled-components/styled-components#443]
## Version
1.0.5

## Reproduction

https://github.com/drhayes/create-react-app-crx-issue

Chrome version: Version 55.0.2883.95 (64-bit)

## Steps to reproduce

1. Clone the above repo.
2. `npm install && npm run build`.
3. Load the contents of the `build` directory as an unpacked extension in Chrome.

## Expected Behavior

Extension loads normally.

## Actual Behavior

Chrome fails to load the extension with this error message:

> Could not load file 'src/js/main.XXXXX.js' for content script. It isn't UTF-8 encoded.

Removing the `styled-components` component and import from App.js and re-building the extension fixes the error. (You'll probably have to edit the `manifest.json` file to match the generated filename from the build process)

**Comment by zalmoxisus** [comment]
We're using `styled-components` inside Redux DevTools Extension without any issues. Most likely you should use UTF-8 as suggested above.

However, there should be any special characters here since emojis were removed.

**Comment by drhayes** [comment]
I should've been way more clear in the bug about this using `create-react-app`, and it's good to know that `styled-components` by itself works great in Chrome extensions.

We're not doing anything to *not* use UTF-8 is the thing. Since this is `create-react-app` we don't have any control over the config unless we eject. It's only inclusion of `styled-components` that causes Chrome to start complaining.

So I guess you haven't seen this outside of `create-react-app` then? It's reproducible in at least two dev environments (my computer and my coworker's).

**Comment by mxstbr** [comment]
> Version: 1.0.5

Please try with the current version, `1.4.x`, that might solve the issue?

**Comment by drhayes** [comment]
Updated to 1.4.3 and I'm still getting this error.

**Comment by mxstbr** [comment]
Maybe this helps? https://stackoverflow.com/questions/5237591/how-do-i-utf-8-encode-my-javascript-files-so-that-google-chrome-can-use-them-i#5237816

**Comment by drhayes** [comment]
I'm running on OSX using Sublime Text 3. The only source file I've modified from the base `create-react-app` provided project this one: https://github.com/drhayes/create-react-app-crx-issue/blob/master/src/App.js

There are no non-UTF8 characters in the `src` directory of my repository (when I do `ag '[^[:ascii:]]'` I get nothing). When I do the same search in styled-components `src` directory I get a bunch of hits from the `vendor/postcss` directory as well as `utils/generateAlphabeticName.js`. Looks like it's mostly emoji, smart quotes, and em- and en-dashes.

We ended up using iconv to strip out the characters ourselves, yeah. But this whole process kind of stunk. I don't know how actionable this is for y'all, but this is all here for posterity and future Googleables. :)

**Comment by zalmoxisus** [comment]
@drhayes [try `v2`](https://github.com/styled-components/styled-components/issues/453), it doesn't include `postcss`.

**Comment by mxstbr** [comment]
Sorry about that @drhayes, glad you could resolve it 😊

**Comment by rgcalsaverini** [comment]
Having the exact same issue

**Comment by davidagee** [comment]
I'm running into the exact same issue. I am trying to build a Chrome extension that injects a React app into a host page via a content script. Everything is set up and working as intended (CSP etc), but as soon as I attempt to use styled-components, the React app fails to mount - completely silently. There are no webpack warnings and no console errors.

This simple scenario is all that's needed to cause the app not to mount:
```
import styled from 'styled-components';
const x = styled.button`
  padding: 2px;
`
```

I'm not actually even using `x` in a render function or anywhere else, the declaration alone is enough to break things.
