### ISSUE TITLE
StyledComponent uses defaultProps for theme instead of theme provided by ThemeProvider after initial render

### ISSUE THREAD

**Issue by chadwatson** [styled-components/styled-components#445]
## Version
1.4.2

## Reproduction
http://www.webpackbin.com/4Jdl6JjwM

## Steps to reproduce

Click the button at least once and the click count text will turn from blue (the given value for `theme.color`) to red (the default prop for `theme.color`).

## Expected Behavior

`StyledComponent`s that are children of `ThemeProvider` should always use the provided `props.theme` instead of `defaultProps.theme`.

## Actual Behavior

On initial render `props.theme` is correct, every subsequent render `props.theme` is `defaultProps.theme`.

**Comment by chadwatson** [comment]
If you check the browser console on the linked webpackbin you will see that `Text` gets rendered once on the initial render and twice on every subsequent button click.

<img width="475" alt="screenshot 2017-02-01 10 10 57" src="https://cloud.githubusercontent.com/assets/5865074/22518808/9c48a716-e873-11e6-81fd-7fb96757a097.png">

**Comment by k15a** [comment]
@diegohaz Did we missed something in https://github.com/styled-components/styled-components/pull/345?

**Comment by xcoderzach** [comment]
I think the issue is that we need to do the same isDefaultTheme check that we do on line 56, on 72 as well 
https://github.com/styled-components/styled-components/blob/master/src/models/StyledComponent.js#L72

**Comment by xcoderzach** [comment]
I'm also curious why it would be double rendering.

**Comment by diegohaz** [comment]
Oh, we really missed that `setState` use case.

**Comment by k15a** [comment]
I think the double rendering is because of how ThemeProvider is working.

**Comment by xcoderzach** [comment]
@k15a yeah, I just checked, and it's because the theme object changes on every click (new object literal)

**Comment by garetmckinley** [comment]
+1 on this, I've tried upgrading a few different projects to the latest `1.x` release to make use of the `withTheme` HOC and was facing the same issue. Glad to see that it's nothing wrong with my codebase, anxiously awaiting a fix :+1:
