### ISSUE TITLE
Inline-flex converts to flex...

### ISSUE THREAD

**Issue by Shaxmatist** [styled-components/styled-components#446]
## Version
2.0.0-0

## Reproduction

This is only for second version! For 1.4.2. works correct. 
http://www.webpackbin.com/VyEF2-sDM
 
![image](https://cloud.githubusercontent.com/assets/6180887/22519036/f5d89f42-e8bf-11e6-885d-2d78f8e6170c.png)

**Comment by k15a** [comment]
@thysultan This is an upstream issue at stylis. Could you take a look?
http://www.webpackbin.com/EkLgWziwG

**Comment by k15a** [comment]
Should be fixed with the new stylis version.
