### ISSUE TITLE
Support width: '100%' in react-native

### ISSUE THREAD

**Issue by IljaDaderko** [styled-components/styled-components#456]
According to following: https://github.com/facebook/react-native/commit/3f49e743bea730907066677c7cbfbb1260677d11

it is now possible to use % for width / height and other parameters like so: `width: 100%`, however doing this through styled components yields an error

```
Invalid undefined `width` of type `string` supplied to `StyleSheet generated`, expected `number`.
StyleSheet generated: {
  "width": "80%",
```

**Comment by mxstbr** [comment]
I think we already have this in `v2`, any chance to backport this to v1 as a non-breaking change @jacobp100?

**Comment by jacobp100** [comment]
It’s available in non-shorthand properties. I think it’ll be too difficult to back port this.

**Comment by IljaDaderko** [comment]
How stable is v2 to use with react-native and could you also expand on what you mean by non-shorthand properties, i.e. `width: 100%` seems like a full one?

**Comment by jacobp100** [comment]
Shorthand properties are like `font`, because you can write: `font: bold 12/14 “Helvetica”`. `width` isn’t a shorthand property.

Would it be possible to get a screenshot of the red box error you’re getting?

**Comment by IljaDaderko** [comment]
Hey @jacobp100 can't currently upload it up, but this is full error from the redbox

```
ExceptionsManager.js:71 Unhandled JS Exception: Invalid undefined `width` of type `string` supplied to `StyleSheet generated`, expected `number`.
StyleSheet generated: {
  "width": "80%",
  "textAlign": "center",
  "marginTop": 21.8625,
  "fontWeight": "bold",
  "fontSize": 16,
  "color": "rgb(24, 24, 24)",
  "fontFamily": "Trajan Pro",
  "textShadowColor": "rgba(255, 255, 255, 0.2)",
  "textShadowOffset": {
    "width": 0,
    "height": 0.5
  }
}
```


generated by following code (`dimension.x` is essentially what I want to swap to percentages):
```
const SText = styled(Text)`
  width: 80%;
  text-align: center;
  margin-top: ${dimension.buttonWidth * 0.106};
  font-weight: bold;
  font-size: ${fontSize.big};
  color: rgb(${colour.darkBrown});
  font-family: ${'Trajan Pro'};
  text-shadow-color: rgba(${colour.white}, 0.2);
  text-shadow-offset: 0 0.5;
`;
```

**Comment by jacobp100** [comment]
It definitely seems to be passing in the correct arguments, and it's failing on the RN side. Either it's a bug there, or we have multiple versions on RN installed.

Could you try deleting your node_modules and then reinstalling?

If the error still occurs, could you see if the folder `./node_modules/styled-components/node_modules/react-native` exists. If it does, could you look in the `package.json` there and let us know what version it reports?

Thanks!

**Comment by IljaDaderko** [comment]
Alright, this is on a fresh init of react native, styled components doesn't have `node_modules` for me (works fine though, strange, is this expected?) version inside styled components package.json is 

```
"react-native": "^0.39.2",
```

under devDependencies, could this be an issue? I think `width: 100%` will only work in 0.41.x

**Comment by jacobp100** [comment]
So a new init worked fine?

**Comment by IljaDaderko** [comment]
Oh no no, I meant issue occurred on new init. Does it work for you? In this case I can dig deeper and see if it is something else on my end, but honestly this is as close to styled components as it gets I think.

I also tried it on `View` and `Image` components, to see if text wasn't supported perhaps, but still same issue

**Comment by jacobp100** [comment]
Mystery solved! You need react-native `0.42` (currently in release candidate).

**Comment by brunolemos** [comment]
`react-native@0.42` was just released with % support! https://github.com/facebook/react-native/releases/tag/v0.42.0

**Comment by crajeshwnp** [comment]
react-native-cli: 2.0.1
react-native: 0.42.3

But still not working :(

**Comment by jacobp100** [comment]
@crajeshwnp What error message are you getting? Could you screenshot it?

**Comment by crajeshwnp** [comment]
@jacobp100 sorry its working now. before i had just given 100%, now i gave '100%' its working.

Thanks

**Comment by RicardoBer** [comment]
If you put a percent for big image into a view the result is a white image (not paint image)

`<View Style={{ width: '100%', height: '150', flex: 1}}>
				<Image source={require('../images/reyes_magos.png')}  resizeMode="contain" style={{width: '90%', height: 150}}/>
</View>	`
