### ISSUE TITLE
Support keyframes defined in object notation format

### ISSUE THREAD

**Issue by majodev** [styled-components/styled-components#461]
Hi!

[Radium](https://github.com/FormidableLabs/radium/tree/master/docs/api#keyframes) and [Aphrodite](https://github.com/Khan/aphrodite#animations) define CSS keyframes in a specific object notation format and libraries like [react-animations](https://github.com/FormidableLabs/react-animations) expose keyframe definitions for several standard animations. 

Is there a way to reuse this special format with styled-components?

**Comment by mxstbr** [comment]
You can use this format in an interpolation perfectly fine: http://www.webpackbin.com/EJPGhi-_M

```JS
const rotate = keyframes`${{
  from: {
    transform: 'rotate(0deg)'
  },
  to: {
    transform: 'rotate(359deg)'
  }
}}
`;
```
