### ISSUE TITLE
[v2] injectGlobal break @next

### ISSUE THREAD

**Issue by garmjs** [styled-components/styled-components#462]
Im not using v2 but just tested and i see if you use minify option it break parsing.

ENV :
 `node v7.0.0`
`webpack ^2.2.1`
`webpack-dev-server 2.3.0`
`styled-components@next` with `babel-plugin-styled-components`

## Steps to reproduce
```
const Box = styled.div`
  background-color: orange;
  width: 100px;
  height: 100px;
`
```

## Actual Behavior
```.app__Box-75m7jb {}.dwklpT {background-color: orange;width: 100px;height: 100px;}```

i don't know if this is bug, because i think it has  to work with actual behavior !

![kapture 2017-02-05 at 22 01 48](https://cloud.githubusercontent.com/assets/5017156/22629859/0f1eb9c8-ebef-11e6-87ac-5ab52d19c4bf.gif)

**Comment by garmjs** [comment]
This is strange, It's not `styled-components` , i just removed && installed `node_modules` folder its working now!

**Comment by garmjs** [comment]
Found what this cause but i don't know why it break, when i `import './utils/globalCss'` wich is `injectGlobal` i get that behavior, now i have removed `import './utils/globalCss'` and its working fine.

**Comment by mxstbr** [comment]
> It's working fine!

That means that some code inside `normalize.css` breaks `stylis`. @thysultan are you aware of this issue?

**Comment by thysultan** [comment]
@mxstbr Will look into it.

**Comment by thysultan** [comment]
The problem is probably how stylis tries to remove comments when a block comment is inlined with a selector.

```javascript
button,
html [type="button"], /* 1 */
[type="reset"],
```

will push a patch for this soon.

**Comment by thysultan** [comment]
@mxstbr pushed a patch for this in v1.0.5 [changelog](https://github.com/thysultan/stylis.js/blob/master/CHANGELOG.md)... was related to comments and attribute selectors.

**Comment by garmjs** [comment]
@mxstbr  @thysultan i can say its not about comments, i have removed comments manually

**Comment by thysultan** [comment]
@garmjs Then it must be attribute selectors, found the comment issue when i was trying to narrow down the issue using an un-minified [normalize.css](https://raw.githubusercontent.com/necolas/normalize.css/master/normalize.css)

**Comment by astyfx** [comment]
when i debug this i found transition mixin fuction cause this bug

```
import { injectGlobal, css } from 'styled-components'

import normalize from './normalize'
import variables from './variables'

const globalStyles = () => injectGlobal`
  @import url(https://fonts.googleapis.com/css?family=Open+Sans:300,400);
  @import url(https://fonts.googleapis.com/css?family=Lato:300,400,700);

  ${normalize}

  html {
    height: 100%;
    box-sizing: border-box;
    line-height: 1;
  }

  *,
  *::before,
  *::after {
    box-sizing: inherit;
  }

  * {
    margin: 0;
    padding: 0;
  }

  body {
    font-family: 'Lato', "Helvetica Neue", helvetica, Arial, sans-serif;
    letter-spacing: 0;
    position: relative;
    height: 100%;

    background: #f7f8fa;
  }
`

const clearfix = () => css`
  &::after {
    content: "";
    display: table;
    clear: both;
  }
`

const transition = (...properties) => css`
  ${''/* transition: ${properties.join(', ')}; */}
`

const boxShadow = (...properties) => css`
  box-shadow: ${properties.join(', ')};
`

const borderRadius = (...properties) => css`
  border-radius: ${properties.join(', ')};
`

const cubicBezier = () => {
  return 'cubic-bezier(.16, .55, .42, 1)'
}

export {
  globalStyles,
  normalize,
  clearfix,
  transition,
  boxShadow,
  borderRadius,
  cubicBezier,
  variables,
}
```

**Comment by astyfx** [comment]
`intjectGlobal` is always appended after component styles.

**Comment by garmjs** [comment]
@astyfx its not that case here, but if you want to append before make sure to import `intjectGlobal ` before components

**Comment by astyfx** [comment]
@garmjs where is the proper place?

**Comment by astyfx** [comment]
i think injectGlobal must be on the top of other `<style>` in html

**Comment by philpl** [comment]
@garmjs @thysultan Do you know if this bug is still present in 2.0.0-15?

**Comment by thysultan** [comment]
This was patched stylis.

**Comment by philpl** [comment]
Alright, we can reopen the issue if this problem persists :tada:
