### ISSUE TITLE
[v2] line comments are incorrectly handled

### ISSUE THREAD

**Issue by wmertens** [styled-components/styled-components#469]
## Version
2.0.1

## Steps to reproduce
```js
styled.div`
   background-color: blue;
   // this comment will kill the next rule
   .foo { color: red; }
`
```

## Expected Behavior
Only the comment is removed

## Actual Behavior
The resulting CSS given to stylis is everything on one line, which breaks the CSS obviously.

Furthermore, in generateAndInjectStyles, there is a comment removal step, but it doesn't work because the rules were already de-newlined before that, and besides stylis already does it.

**Comment by wmertens** [comment]
Upon closer inspection, the babel plugin could be the reason the css has newlines removed.

**Comment by mxstbr** [comment]
>  the babel plugin could be the reason the css has newlines removed.

That is the case! /cc @vdanchenkov can we do something about this?

**Comment by wmertens** [comment]
Issue is at https://github.com/styled-components/babel-plugin-styled-components/issues/29
