### ISSUE TITLE
document click event does not fired

### ISSUE THREAD

**Issue by astyfx** [styled-components/styled-components#477]
## Version
2.0.0-3

## Example
```es6

componentDidMount() {
  document.addEventListener('click', this.onDocumentClick, false)
}
...
onDocumentClick(e) {
  console.log('odc', e)
}
...
handleMouseDown(e) {
  console.log('hmd', e)
}
...
const DropdownToggle = styled.div`
  position: relative;
  cursor: pointer;
`

<DropdownToggle
  onMouseDown={this.handleMouseDown}
  onTouchEnd={this.handleMouseDown}
/>
```

## Expected Behavior
  If i click on `DropdownToggle`, `'odc', MouseEvent`, `'hmd', MouseEvent` should appear at the same time.
## Actual Behavior
  only `'hmd', MouseEvent` appears

**Comment by astyfx** [comment]
i think global event handler not fired when click target is `StyledComponent` or `StyledComponent's children`

**Comment by mxstbr** [comment]
Can you try making it a `button` HTML node instead of a `div`?

**Comment by astyfx** [comment]
@mxstbr it works! but is there no way to enable document click by using `div` ?

**Comment by mxstbr** [comment]
You shouldn't really do that 😉 I don't know if this is a block on our side or on React's side, /cc @geelen?

**Comment by tgdn** [comment]
@mxstbr this is a block on your side, and not really something you should be doing.
React allows to ref to any component (including a div) and add an eventListener during `componentDidMount`. Here, you are blocking this functionality and limiting React and the DOM itself.
