### ISSUE TITLE
v2 cursor: grab; not prefixed anymore

### ISSUE THREAD

**Issue by k15a** [styled-components/styled-components#479]
## Version
2.0.0-3

## Reproduction
v1: http://www.webpackbin.com/VyRwSPHOz
v2: http://www.webpackbin.com/NkR-DDSOf

## Expected Behavior
```CSS
  cursor: -webkit-grab;
  cursor: -moz-grab;
  cursor: grab;
```

## Actual Behavior
```CSS
  cusor: grab;
```

As `cursor: grab;` is not standardized this might be actual the right behavior.

**Comment by philpl** [comment]
cc @thysultan

**Comment by thysultan** [comment]
@k15a That includes `zoom-out` & `zoom-in`

**Comment by thysultan** [comment]
added in stylis v1.1.1

**Comment by k15a** [comment]
Thank you very much.
