### ISSUE TITLE
[v2] & selector not behaving as expected

### ISSUE THREAD

**Issue by adjnor** [styled-components/styled-components#480]
# Version
v2.0.0-3

# Reproduction
v1: http://www.webpackbin.com/VyDUrjSuz
v2: http://www.webpackbin.com/NJzZGRcHdG

# Expected Behaviour
.generatedClassname.generatedClassname { css }

# Actual Behaviour
.generatedClassname1 {}
.generatedClassname2 {}

I usually use this selector (&&) when I need to override the specificity of global css classes

**Comment by thysultan** [comment]
@mxstbr patched [481](https://github.com/styled-components/styled-components/issues/481) and [479](https://github.com/styled-components/styled-components/issues/479) upstream v1.1.1

**Comment by k15a** [comment]
Awesome 👍

**Comment by mxstbr** [comment]
Will push a new version with the stylis update, thanks @thysultan!
