### ISSUE TITLE
Pseudo selector inside parent wrapper not applied

### ISSUE THREAD

**Issue by thundercat1** [styled-components/styled-components#481]
## Version
2.0.0-3

## Reproduction
http://www.webpackbin.com/Vyl4lVeU_M

## Steps to reproduce
This pseudo-selector for hover state doesn't apply correctly when wrapped in a parent class selector (sorry for my poor css terminology). This worked in previous styled-component versions, but looks like it's not working in v2.

```
const Title = styled.h1`
  .root-wrapper &{
    font-size: 1.5em;
    text-align: center;
    color: palevioletred;
    &:hover {
      color: black;
    }
   }
`;
```

thanks!

**Comment by thysultan** [comment]
```
.root-wrapper & {
```

as opposed to

```
& .root-wrapper {
```

Will promote the selector into a global selector because & will be replaced with the namespace and `#namespace .root-wrapper #namespace {` is a selector that will never match anything.

What did you intent to select with `.root-wrapper &{`?

**Comment by thysultan** [comment]
Yes it's a bug, the nested `&:hover {` should yield `.root-wrapper #namespace:hover {`, have pushed a patch for this in the compiler.

**Comment by k15a** [comment]
👍
