### ISSUE TITLE
is there a way to use postcss with styled-components?

### ISSUE THREAD

**Issue by Ajar-Ajar** [styled-components/styled-components#482]
Hi, is there a way to use postcss with styled-components? 
I'm using postcss plugins like px-to-rem and rucksack css responsive fonts which are amazing and I would hate to give those up. Is there a way to combine the two?

**Comment by k15a** [comment]
At the moment there is no way to use PostCSS with styled-components.

**Comment by Ajar-Ajar** [comment]
Thank you for the quick reply. Sad to hear that. It is quite an eco-system of plugins people worked hard to develop and rely on in their projects one would have to sacrifice for being able to use styled-components... a big price to pay... any ideas for work-arounds?

**Comment by k15a** [comment]
You can replace many PostCSS with functions. For example a function which calculates pixel to rem could be simple `const pixToRem = px => px / 16` or something like this. Other then that you could develop a babel plugin which pipes styled-components through PostCSS. The downside will be that only the static party gets transformed. With v2, styled-components relies on stylis as the CSS parser so https://github.com/thysultan/stylis.js#middleware could help you as well.

There was already a discussion at: https://github.com/styled-components/styled-components/issues/62 which might help you.

**Comment by Ajar-Ajar** [comment]
ok, just to be short about it, using your pixToRem function example, how would you integrate it into a styled-components based app? would you need to include it for each component individually? is there a central place you can pipe this function in? If this point is clear then I guess we can indeed strip out the functionality of the plugins we need and use them as functions.

**Comment by thysultan** [comment]
maybe styled-components can expose the `.use` function that the parser uses to register middleware, cc @mxstbr.

A px to rem converter might look something like.

```
stylis.use(function (context, property) {
    switch (context) {
        case 2: return property.replace(/(\d+)px/g, (match, group) => parseFloat(group)/16 + 'rem')
    }
});
```

**Comment by mxstbr** [comment]
> maybe styled-components can expose the .use function that the parser uses to register middleware

We probably won't do that 😊 the more configuration we allow, the less agility we have with our internals which we need to avoid.

> ok, just to be short about it, using your pixToRem function example, how would you integrate it into a styled-components based app? would you need to include it for each component individually? is there a central place you can pipe this function in?

```JS
// helpers.js

const px2rem = px => `${px / 16}rem`

export {
  px2rem
}
```

```JS
import { px2rem } from '../helpers'

const Button = styled.button`
  font-size: ${px2rem(16)};
`
```

We're working on a "standard library" that'll contain all sorts of useful functions like `px2rem`. This will be released soon, it's almost done!

**Comment by Ajar-Ajar** [comment]
@mxstbr excited to hear about the "standard library" and can't wait to see what you have cooking!
The import of px2rem example you've included though requires developers to actually call it everywhere as was the case with compass for sass offering such mixins and functions. 
I see a much greater value in the postcss plugin approach which removes the need to call this function at all! 
It will simply run over your code and do it for you and you may whitelist or blacklist css properties from being affected by the process. 
This approach saves so much time and effort during development and allows everyone to be MUCH more productive!
The helper looks like a step back in this sense... what do you think?
Thank you!
Ajar

**Comment by geelen** [comment]
@Ajar-Ajar that's a fair point, I _do_ think there is some value in an implicit conversion of units like px2rem, but unfortunately the cost to support such a thing in Styled Components is too high to justify it. The good news is that Styled Components offers _different_ (and imo far more valuable) abstractions over things like sizing:

```js
import { sizes } from 

const Button = styled.button`
  font-size: ${sizes.M};
  padding: ${sizes.S};
`
```

If you start to build up a suite of reusable constants throughout your app you might find it becomes far more visually consistent and maintainable. At least, that's been my experience.

**Comment by kettanaito** [comment]
Hello, everybody. Thank you for the answers.

I would also like to be able to apply additional transformation to the generated CSS, if possible. Alas, you can't cover everything with helper functions. For example, I would need to transform generated CSS with Autoprefixer to support CSS Grid for IE10-11 (styled-components don't do that, and the grid is broken).

What would you recommend for such use case?

**Comment by ooloth** [comment]
I'd also like to apply more transformations to the generated CSS than the default `autoprefixer`.

For example, I prefer using CSS custom properties for theming (since there's less boilerplate than when using `ThemeProvider`), but IE can't understand CSS custom property values. A simple solutions is the `postcss-custom-properties` plugin ([repo here](https://github.com/postcss/postcss-custom-properties)), which can automatically generate fallback values.

For use cases like this, it would be great to be able to customize the `postcss` config that run when our CSS is generated. Since `autoprefixer` is already being used, hopefully there's a way to make the plugins list configurable.

**Comment by xuyuanxiang** [comment]
I recently started using styled-components  at work.
I wrote a [Babel plugin](https://github.com/xuyuanxiang/babel-plugin-styled-components-px2rem) and a [TypeScript transformer](https://github.com/xuyuanxiang/typescript-styled-components-px2rem) to resolve this problem.
