### ISSUE TITLE
Adding support for browserslist

### ISSUE THREAD

**Issue by jalooc** [styled-components/styled-components#487]
A really nice feature that styled-components would benefit from is a support for [browserslist](https://github.com/ai/browserslist). As it's widely used by big css-related packages ([Autoprefixer](https://github.com/postcss/autoprefixer), [Stylelint](http://stylelint.io/) etc.), it became a de-facto standard for defining the desired set of browsers to support. Without it, some of us would pointlessly ship loads of prefixes for properties/values necessary for older browsers than those that we would like to eventually support. Moreover, it would co-operate nicely with packages like [babel-env-preset](https://github.com/babel/babel-preset-env), forming a complex solution for specific browser targetted builds.

**Comment by mxstbr** [comment]
> Without it, some of us would pointlessly ship loads of prefixes for properties/values necessary for older browsers than those that we would like to eventually support.

We apply all prefixes for all browsers support by React itself, not more and not less. (IE9+) Both modern and old browsers get the exact same minimal CSS, without any prefixes, and then get prefixed in the browser.

Neither loading time nor performance-wise does supporting browserlist make any sense, as it'll add a lot of package weight for everybody for a fringe use case of people only supporting a subset of the browsers React supports, who don't gain any benefit from actually applying that browserlist.

**Comment by jalooc** [comment]
Okay, that's a good point if the prefixing is done on the client side. Thanks for the quick answer.
