### ISSUE TITLE
style autofill style

### ISSUE THREAD

**Issue by macrozone** [styled-components/styled-components#492]
Chrome adds an ugly yellow background to autofilled form fields.
This can be customized with 

input:-webkit-autofill

(http://stackoverflow.com/questions/2338102/override-browser-form-filling-and-input-highlighting-with-html-css)

but unfortunatly, this does not work in styled-components. I tried

```
  &::-webkit-autofill {
    background-color: red;
  }
```

but this does not work. Any ideas?

**Comment by k15a** [comment]
@thysultan do you have an idea?

**Comment by thysultan** [comment]
can't say is this in v1 or v2?  `&::-webkit-autofill` is compiled as expected in stylis. 

@macrozone What is `&` trying to select, can you post the styled component?

**Comment by k15a** [comment]
Ahh I've assumed that's a problem with v2. So it might be fixed in v2. Could you test that @macrozone?

**Comment by marc-rutkowski** [comment]
@macrozone try something like this :
```
  &:-webkit-autofill,
  &:-webkit-autofill:hover,
  &:-webkit-autofill:focus,
  &:-webkit-autofill:active {
    -webkit-transition: "color 9999s ease-out, background-color 9999s ease-out";
    -webkit-transition-delay: 9999s;
  }
```

see: http://stackoverflow.com/a/32505530

works with v1 and v2

**Comment by mxstbr** [comment]
Thanks for confirming this isn't an issue on our side @marc-rutkowski!

**Comment by Brenont** [comment]
This does not work correctly, only is applied a delay to the autofill style. After the delay the default style return.

@marc-rutkowski this isn't the solution of the issue.

@mxstbr Could you reopen this issue?

**Comment by Tolo-Ran** [comment]
Hello, try to set a box shadow inset color.
 Change the "&" to "input" if your are not using neested styled component.
  &:-webkit-autofill {
    box-shadow: 0 0 0px 30px red inset !important;
  }
  &:-webkit-autofill:hover {
    box-shadow: 0 0 0p 30px red inset !important;
  }
  &:-webkit-autofill:focus {
    box-shadow: 0 0 0 30px red inset !important;
  }
I hope it will help!
