### ISSUE TITLE
[v2] @font-face breaks styles 

### ISSUE THREAD

**Issue by marc-rutkowski** [styled-components/styled-components#493]
## Version
2.0.0-3

## Reproduction
https://github.com/marc-rutkowski/styled-components-v2-font-face
(standard create-react-app)

## Steps to reproduce
```
git clone git@github.com:marc-rutkowski/styled-components-v2-font-face.git
yarn
yarn start
```

Dev server starts and the app home page displays a red background and use the Pangolin webfont.
`@font-face` is set by using the `injectGlobal` helper in [App.js](https://github.com/marc-rutkowski/styled-components-v2-font-face/blob/master/src/App.js#L8)

Now, switch to styled-components v2 :
```
yarn remove styled-components
yarn add styled-components@next
yarn start
```

## Expected Behavior
Same rendering than with styled-components v1.x

## Actual Behavior
`@font-face` breaks styling. The red background is not visible anymore and default font is used instead of the custom one.
If the  `@font-face` rule is removed the red background appears has before.

Maybe related to #462 ? 

ps: thanks for this great lib!

**Comment by thysultan** [comment]
Thanks, will push a patch for this.

**Comment by thysultan** [comment]
patched upstream(parser), cc @mxstbr.

**Comment by k15a** [comment]
Awesome ❤️

**Comment by marc-rutkowski** [comment]
@thysultan thank you for the very fast reply and fix! It works fine now.

@k15a maybe this issue should be stay open until deps are updated to stylis@1.1.2+ ?
Let me know if you want a PR for this...

ps: It took me awhile to understand that it was fixed by this [commit](https://github.com/thysultan/stylis.js/commit/b85da030a09bc2fea3edc7a4a6b1bec1eb0b88c9) ;-)

**Comment by k15a** [comment]
@marc-rutkowski Ahh. I thought that we are using version ranges so the patches are covered. OFC it should stay open then^^
