### ISSUE TITLE
[v2] suggestion: separate npm package for styled-components-native ?

### ISSUE THREAD

**Issue by IljaDaderko** [styled-components/styled-components#502]
I found myself debugging an issue today, which turned out to be a silly mistake related to including styled from `styled-components` instead of `styled-components/native`, this led me to think and ask question like, can these be decoupled into separate packages, similarly to how react-router@4 do theirs? (https://github.com/ReactTraining/react-router/tree/v4/packages)

Just an idea, might even strip down few kb's in native bundles?

**Comment by mxstbr** [comment]
We discussed about doing that or going with `/native` before we released the initial version. I can't remember why we went with `/native` right now though, /cc @geelen?

**Comment by mxstbr** [comment]
Planned for the next major release: https://github.com/styled-components/styled-components/issues/687
