### ISSUE TITLE
Utility classes

### ISSUE THREAD

**Issue by TrevorHinesley** [styled-components/styled-components#503]
Is there a way to do utility classes? For instance, in Bootstrap I can do:

`<button class='mt-0'>No margin on top</button>`

To remove margin-top from the button, and there are others for padding, margin, etc. This makes it extremely quick to adjust spacing for components. I know I can pass classes to className, but how would I go about creating such utility classes while remaining encapsulated like styled-components prefers?

**Comment by k15a** [comment]
You can use the css utility. For example:

```JS
const mt0 = css`
  margin-top: 0;
`

// How to use this?
const Header = styled.div`
  ${mt0}
  // other styles
`
```

Hope this helps you ;)

**Comment by TrevorHinesley** [comment]
Sure but what if only one element needs the margin or whatever? @k15a

**Comment by TrevorHinesley** [comment]
Basically, I'd like these utility classes to not be tied to the components. For instance, this works but I'm not sure if it's correct:

```
import React from 'react';
import styled from 'styled-components';
import SidebarSectionHeader from './SidebarSectionHeader';

const StyledSidebarSection = styled.div`
  margin-top: 2rem;
`

const SidebarSection = props =>
  <StyledSidebarSection {...props}>
    <SidebarSectionHeader>{props.header}</SidebarSectionHeader>
    {React.Children.toArray(props.children)}
  </StyledSidebarSection>

SidebarSection.propTypes = {
  header: React.PropTypes.string
}

export default SidebarSection;
```

Then I can pass a `className` to the SidebarSection.

**Comment by k15a** [comment]
I don't understand exactly what you want to do with this code.

As a side note: You don't have to convert props.children to an array to render them.
```{props.children}``` is working as well :)

**Comment by TrevorHinesley** [comment]
In other words, what is the proper way to pass global utility classes to components using styled-components? It's much easier and more sanitary than defining per-component utility classes that other libraries reusing the components may not use (such as the margin/padding utilities I referred to above).

Also, for the toArray piece: http://stackoverflow.com/a/32705370/981177

**Comment by k15a** [comment]
If you have you're utility classes defined globally what's wrong with className then? If you want to inject styles globally with styled-components you can use the injectGlobal function from styled components. You can't encapsulate 

Some examples which could help you:

```JS
function mt0(component) {
  return styled(component)`
    margin-top: 0;
  `
}

// Which could be used

const Header = styled.div`
  // styles
`

const HeaderWithoutMargin = mt0(Header)
```

```JS
const utility = css`
  ${props => props.mt0 && 'margin-top: 0;'}
  ${props => props.p0 && 'padding: 0;'}
`

// Which could be used

const Header = styled.div`
  ${utility}
  // more styles
`

<Header mt0 p0 />
```

Maybe someone else can help you more with this ;) Feel free to reopen this issue if you're question is still unanswered. :)

**Comment by mxstbr** [comment]
Using `classNames` (if they already exist) is perfectly fine @TrevorHinesley and will work exactly like you'd expect:

```HTML
<StyledSidebarSection className="mt0" />
```

**Comment by mxstbr** [comment]
Also @TrevorHinesley, regarding children, I recommend you read this piece I wrote recently: https://mxstbr.blog/2017/02/react-children-deepdive/

There's no need to convert them to an array, React handles whatever data structure `this.props.children` is perfectly fine.

**Comment by TrevorHinesley** [comment]
Thank you @mxstbr and @k15a!!

**Comment by carlosepp** [comment]
@TrevorHinesley I do something like this for working with utility classes, for lack of a better term I call them prop-receivers:

```js
export const marginProps = props => css`
  ${props.marginBottom && `margin-bottom: ${typeof (props.marginBottom) === "string" ? props.marginBottom : "1em"};`}
  ${props.marginTop && `margin-top: ${typeof (props.marginTop) === "string" ? props.marginTop : "1em"};`}
  ${props.marginLeft && `margin-left: ${typeof (props.marginLeft) === "string" ? props.marginLeft : "1em"};`}
  ${props.marginRight && `margin-right: ${typeof (props.marginRight) === "string" ? props.marginRight : "1em"};`}
  ${props.margin && `margin: ${typeof (props.margin) === "string" ? props.margin : "1em"};`}
`;
`
```
Then we can use it in any component we want like so:
```js
const SomeComponent = styled.div`
  ${marginProps}
`
```

So you can use this component in the following manner:
```js
<SomeComponent margin /> // Will add a default margin to the component, in this case is 1em
<SomeComponent margin="2em" /> // Will add 2em padding
<SomeComponent marginLeft marginRight /> // Will add the default margin-left and margin-right
```

This pattern has proven to be very useful for us, as it leads to flexible components and also improves reusability of code as we don't need to hardcode margins or any other property directly in the component, making it more flexible for future reuse.

Hope this helps
