### ISSUE TITLE
[v2] Missing media query

### ISSUE THREAD

**Issue by epilande** [styled-components/styled-components#505]
## Version
2.0.0-4

**Note:** Bug does not occur in v1.

## Reproduction
Using in https://github.com/epilande/yaris/blob/master/src/styles/global.js

Reproduced in http://www.webpackbin.com/E1xgOBppuf

![image](https://cloud.githubusercontent.com/assets/3210082/22998521/31a06418-f37b-11e6-9e6d-d27bc24b54c6.png)

Notice in the screenshot `@media (min-width: 35.5em)` is missing. 

## Expected Behavior
Should have both `@media (min-width: 35.5em)` & `@media (min-width: 64em)` in the output.

## Actual Behavior
Only getting `@media (min-width: 64em)` in the output.

**Comment by thysultan** [comment]
patched upstream(stylis). cc @mxstbr

**Comment by thysultan** [comment]
BTW @epilande I think `&:global(.active) {` should be `:global(.active) {`

**Comment by epilande** [comment]
Hah oops forgot to remove that when migrating from `css-modules` to `styled-components`.

BTW thanks for the quick fixes @thysultan! You've been killing it! 👍

**Comment by thysultan** [comment]
@epilande stylis does support `:global()` to escape name-spacing, i'll play with it to see if it makes sense to also allow it to escape nested parent selectors.

**Comment by k15a** [comment]
Thank you @thysultan 👍

**Comment by mxstbr** [comment]
If you run `npm install` again @epilande you should get the new (fixed) version of stylis!

**Comment by thysultan** [comment]
@epilande `&:global(.active) {` should work as well.

**Comment by epilande** [comment]
Awesome! Thanks guys ✌️
