### ISSUE TITLE
[v2] question about Newly added Component Selector

### ISSUE THREAD

**Issue by astyfx** [styled-components/styled-components#506]
is there way to do this

```es6
const StyledCard = styled.div`
  +${StyledCard} {
    margin-top: 20px;
  }
`
```

i need to use a `+` selector

__using `${ComponentName}` Selector by #142__

**Comment by k15a** [comment]
You can do

```JS
const StyledCard = styled.div`
  & + & {
    margin-top: 20px;
  }
`
```

**Comment by astyfx** [comment]
@k15a thanks 👍

**Comment by astyfx** [comment]
@k15a it dosen't work in v2.0.0-4

* Reproduce *
http://www.webpackbin.com/V1TM1LA_G

**Comment by k15a** [comment]
It's working in version 1. @thysultan could you look into this?

**Comment by thysultan** [comment]
@k15a patched `& + &` does `${StyledCard} + ${StyledCard}` generate `& + &` ?

**Comment by k15a** [comment]
`${StyledCard} + ${StyledCard}` should produce `.class + .class`

**Comment by thysultan** [comment]
I guess In this context it would not select anything...

```js
const StyledCard = styled.div`
  ${StyledCard} + ${StyledCard} {
    margin-top: 20px;
  }
`
```
will translate to...

```
.class .class + .class
```
unless the component selector implementation can identify when it is a self-reference and uses `& + &` instead.

**Comment by k15a** [comment]
Shouldn't this work then?
```JS
const StyledCard = styled.div`
  + ${StyledCard} {
    margin-top: 20px;
  }
`
```

**Comment by thysultan** [comment]
Yes that will work.

**Comment by k15a** [comment]
Thank you again for the quick fix 👍
@mxstbr should we change self referencing component selectors to `&` then?

@astyfx You can get the fixed version if you `npm install again` :)

**Comment by mxstbr** [comment]
> @mxstbr should we change self referencing component selectors to & then?

That seems reasonable, @geelen what do you think? Is that feasible?

**Comment by astyfx** [comment]
@k15a i uninstalled and install again `v2.0.0-4` but it seems to be not work

**Comment by geelen** [comment]
>> @mxstbr should we change self referencing component selectors to & then?
> That seems reasonable, @geelen what do you think? Is that feasible? 

Not sure what the point would be: that's literally what `&` is for.
