### ISSUE TITLE
Usage of withTheme with HoC

### ISSUE THREAD

**Issue by kopax** [styled-components/styled-components#507]
I have created the following HoC using `react-collapse`.

I want to swap the container of my collapsing content using `theme['$enable-transitions']`.

The react-collapse creator recommand for our use case to use a __<div>__ instead of a __<Collapse>__

## Version
1.4.3

## Steps to reproduce

This is my HoC that will take care of choosing the proper element : 

```jsx
import React, { PropTypes } from 'react';
import { withTheme } from 'styled-components';
import CollapseLib from 'react-collapse';
import bsTheme from 'theme';

export default function composeCollapse(CollapseLib) {
  class Collapse extends React.Component {

    static propTypes = {
      children: PropTypes.node,
      theme: PropTypes.object,
    };

    defaultProps = {
      theme: bsTheme,
    };

    render() {
      const { children, theme, ...props } = this.props;
      // extract keys for div
      const { isOpened, fixedHeight, springConfig, keepCollapsedContent, onRest, onHeightReady, ...rest } = props;
      console.log(theme);
      return theme['$enable-transitions'] ? (
        <CollapseLib {...props}>{children}</CollapseLib>
      ) : (
        <div {...rest}>{children}</div>
      )
    }
  }
  return withTheme(Collapse);
}
```

Unfortunately this throw the following error : 

    styled-components.es.js:104 Uncaught TypeError: Cannot call a class as a function(…)

Is there a standard practice to use withTheme and HoC ?

I haven't found more information in the [documentation](https://github.com/styled-components/styled-components/blob/master/docs/theming.md)

## Expected Behavior

Create a HoC that can be rendered

## Actual Behavior

Throw error : 

    styled-components.es.js:104 Uncaught TypeError: Cannot call a class as a function(…)

**Comment by creaux** [comment]
@kopax how did you resolve this?
