### ISSUE TITLE
Stricter typings

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components#51]
We need to tighten our flow typings. People will probably (even if we don't explicitly export them) start using them in their code, and it might break stuff.

**Comment by geelen** [comment]
Can I give this one to you? My flowfu is pretty low-fu...

**Comment by mxstbr** [comment]
@ryyppy and I will do this after launch together, this needs more time

**Comment by ryyppy** [comment]
I am definitely in for helping out here 👍

**Comment by jongold** [comment]
👋  I can help out on this if you want

**Comment by mxstbr** [comment]
Yes @jongold! Wanna pair with me and @ryyppy on this?
