### ISSUE TITLE
[v2] attrs constructor breaks syntax highlighting

### ISSUE THREAD

**Issue by bondz** [styled-components/styled-components#511]
In VSCode, syntax higlighting works for the following, in v1

```js
const StyledList = styled.li`
  &.red {
    background-color: red;
  }
  padding: 20px;
`
```

But now, that we can do, in v2

```js
const StyledList = styled.li.attrs({
  className: 'red',
})`
  &.red {
    background-color: red;
  }
  padding: 20px;
`
```

The styles are no longer highlighted 😢

**Comment by mxstbr** [comment]
Good point, didn't even think of that! @geelen this might be a bit of a pain…

**Comment by geelen** [comment]
Yeah damn, not sure how those syntax highlighters are written but it's still just a normal JS expression followed by a `` ` `` so surely it can be made to work...

But yeah it certainly complicates things. There could be `css` expressions inside attributes, too.

**Comment by mxstbr** [comment]
We've done everything we could to update most of them, if you still don't have syntax highlighting please open issues in the repos of the packages themselves!
