### ISSUE TITLE
[v2] `& ~ &` compiles to `className ~ &` 

### ISSUE THREAD

**Issue by mqklin** [styled-components/styled-components#515]
But should to `className ~ className`

v2.0.0-4

http://www.webpackbin.com/V1qV6mbFM

Works OK with v1

**Comment by k15a** [comment]
@thysultan did you fixed that as well? :)

**Comment by thysultan** [comment]
@k15a Yes.

**Comment by k15a** [comment]
Thank you 👍
@mqklin If you `npm install` again you should get the new version fixed version of stylis.

**Comment by mqklin** [comment]
@k15a how is it possible, last release (v2.0.0-4) was 3 days ago? I run `npm install` and nothing changed :(

**Comment by k15a** [comment]
Try to `rm -rf node_modules && npm install`. Normally npm will pick the latest version which is in styled-components version range.

**Comment by mqklin** [comment]
But the latest is `v2.0.0-4`, isn't it? In this version I found the bug.
I use `yarn`, from my `yarn.lock`: `styled-components@next: version "2.0.0-4"`.

**Comment by k15a** [comment]
Ahh with yarn that's a problem because they are using fixed version numbers. With NPM you can specify version ranges so styled-components can use the patch releases of stylis without a new release. Maybe we have to release a new version then.

If you want to have the fixed version faster you can switch back to NPM for a few days. Just keep your yarn.lock and you're good to go. Run `rm -rf node_modules && npm install` and in a few days if a new version of styled-components is released run `rm -rf node_modules && yarn install` to get back to yarn.

**Comment by mqklin** [comment]
Ok, I made `rm yarn.lock && rm -rf node_modules && npm i && npm start`. Still `iEUqLG ~ & {margin-top: 15px;}`

**Comment by mqklin** [comment]
From `node_modules/stylis/package.json`: `"version": "1.1.11"`

**Comment by k15a** [comment]
That's the latest version. Then this isn't fixed.

**Comment by mqklin** [comment]
but this
```
import stylis from 'stylis';
console.log(stylis('.qweee', '& ~ & { margin-top: 15px; }'));
```
logs `.qweee ~ .qweee {margin-top: 15px;}`

**Comment by k15a** [comment]
I've tested it with CRA and it's working.

**Comment by mqklin** [comment]
I've created the smallest repro https://github.com/mqklin/styled-components-- please look

**Comment by k15a** [comment]
That's because you're using Webpack 2 and it will choose the bundled ES2015 file.
@mxstbr I think we should exclude all dependencies from the ES2015 bundle or distribute transpiled files (without export statement) for Webpack to npm? What do you think?

**Comment by mxstbr** [comment]
No idea, why should we do that?

**Comment by k15a** [comment]
So we don't have to update our bundle every time a dependency updates because webpack will bundle the dependencies on it's own. As a bonus I could imagine some size improvents because webpack could treeshake better but I don't know if this will be much.

**Comment by mxstbr** [comment]
Sure, PR?
