### ISSUE TITLE
Modernizr and .no-flexbox class

### ISSUE THREAD

**Issue by mech** [styled-components/styled-components#524]
I know this is not the place to ask for usage question, but I struggle to find any example to do fallback on flexbox using S-C.

With Modernizr we can have class at the root element called ".no-flexbox" or we can use inline style with `Modernizr.flexbox`. Does S-C has any code example on doing that?

```js
const TabBarItem = styled.div`
  display: ${Modernizr.flexbox ? 'flex' : 'inline-block'};
`
```

I am wondering how does that work since `Modernizr.flexbox` is dynamic and determined at browser's run-time and S-C need to be compiled at webpack build-time to determine the final stylesheets.

**Comment by k15a** [comment]
styled-components is not compiled at webpack built time so as far as Modernizr.flexbox does return some truthy or falsy value this should work.

**Comment by mech** [comment]
In production mode, isn't ExtractTextPlugin going to generate single CSS file for it?

**Comment by k15a** [comment]
No that's not happening. You can use styled-components without webpack as well.

**Comment by mech** [comment]
Now I see it.. there is absolutely no CSS file generated. It is injected into <head> as one big blob of <style>. Is this intended? Will there be any option to use Webpack and generate a separate CSS file just for the sake of it?

**Comment by k15a** [comment]
Yeah that's intended and I don't think there will be an option to use Webpack and generate a CSS file in the near future. Basically it doesn't give you any improvements.

**Comment by mech** [comment]
Sure.. good to know that

**Comment by typeoneerror** [comment]
>styled-components is not compiled at webpack built time so as far as Modernizr.flexbox does return some truthy or falsy value this should work.

This does not appear to be true. For example, if you write something like:

```
const SpecItemWrapper = styled(SpecItem)`
  background-color: ${window.anUndefinedProperty ? 'red': 'purple'};
`;
```

The resulting build will have the following if anUndefinedProperty isn't defined:

```
.cWdkuF{background-color:purple;}
```

It is not evaluated at runtime, but built-time, so using Modernizr.flexbox will not be evaluated based on the browser that is running the code.
