### ISSUE TITLE
[v2] Child styling inside parent selector not applied

### ISSUE THREAD

**Issue by seanevd** [styled-components/styled-components#530]
## Version
2.0.0-4

## Reproduction
http://www.webpackbin.com/4J6emfuFG

## Steps to reproduce
This is the same issue as [481](https://github.com/styled-components/styled-components/issues/481) but with any other selector. Styling like this worked on 1.4:
```
const List = styled.ul`
  .root-wrapper & {
    background-color: red;
    li {
      color: white;
    }
  }
`;
```
In this snippet we should be seeing white text on a red background, but the `<li>` elements are not being styled because of this possible bug.

## Expected Behavior
Essentially, I would expect it to output CSS like this `.root-wrapper ul li { color: white;}` but it doesn't.

**Comment by thysultan** [comment]
Yes it should yield `.root-wrapper ul li {` without using`& li`, patched upstream(stylis)

**Comment by seanevd** [comment]
Any idea when we could get this into a new 2.0 release? @thysultan I assume you fixed the issue with stylis, right?

**Comment by thysultan** [comment]
@seanevd Yes.

**Comment by mxstbr** [comment]
Will publish a new release soon!
