### ISSUE TITLE
Discuss alternate way to apply props to css attribute using bindProp

### ISSUE THREAD

**Issue by gabewillen** [styled-components/styled-components#532]
```javascript
import styled, {bindProp} from 'styled-components';

// rough implementation details 'utils/bindProp.js'
//
// class BoundProperty {
//     name: string;
//     styleOnly: boolean;
//     defaultValue: Object;
//
//     constructor (name: string, styleOnly: boolean = false) {
//         this.name = name;
//         this.styleOnly = styleOnly;
//     }
//
//
//     // Optional just an idea
//     default(value: Object): BoundProperty {
//         this.defaultValue = value;
//         return this;
//     }
//
// }
//
//
// export default function bindProp(name: string, styleOnly: boolean): BoundProperty {
//     return new BoundProperty(name, styleOnly);
// }
//
// Inside the template interpolation function do an instanceof BoundProperty check.
// If true lookup the property name in the props object and insert the value.
// If value is undefined use defaultValue
// If the styleOnly flag is true remove the property from the props object after all attributes have been updated.

const Progress = styled.div`
    width: ${(props) => props.width};
    /* or */
    width: ${bindProp('width', true).default('100%')};
`;
```
This solves the issue of unwanted style properties being passed to components.  It could also slightly improve performance by reducing function calls during property updates. Just an idea I thought I would share.

**Comment by jacobp100** [comment]
I did think about something like this—you could make a proxy that records property access. It came down to an issue a single issue, which I think yours will still suffer from.

Just for example, we'll say you don't pass down any styling props. Now say you want to allow computed properties (which seems to be a common use case). This might look like this,

```js
const FineSoFar = styled.div`
  color: ${bindProp('active', active => active ? 'red' : 'blue')};
`
```

But what if your conditional now references another prop,

```js
const FineSoFar = styled.div`
  color: ${bindProp('active', active => active ? bindProp('primary') : bindProp('secondary')};
`
```

Until active has had all values, you do not know all styling props. This means that until you have exhausted all permutations of props, you will be passing down non-styling props.

**Comment by gabewillen** [comment]
@jacobp100 You make an excellent point.  How about this instead

```javascript
const Button = styled.div`
    ${bindProps("active", "primary", "secondary")
    color: ${(props) => props.active ? props.primary : props.secondary};
`
```

One declaration at the top.  It would simply populate a list upon interpolation and substitute its value as an empty string or simply be skipped.  It requires no custom css addons.

**Comment by jacobp100** [comment]
I'll copy this over into the other thread!

**Comment by gabewillen** [comment]
Cool thank you.
