### ISSUE TITLE
Styled-components and microdata

### ISSUE THREAD

**Issue by Lehakos** [styled-components/styled-components#533]
[Microdata attributes](http://schema.org) doesn't appears at the DOM node. 
Person - it's a styled component.
`<Person itemscope itemtype="http://schema.org/Person" />`
The attributes `itemscope` and `itemtype` not present in rendered DOM.

**Comment by edygar** [comment]
That's probably not StyledComponent's fault. In React, they should be spelled as `itemScope` and `itemType` (note the camelCase)

**Comment by Lehakos** [comment]
Oh, thx!
