### ISSUE TITLE
[Proposal] `withStyle` HoC

### ISSUE THREAD

**Issue by migueloller** [styled-components/styled-components#534]
👋 Hi there. Amazing work on this library!

I have a small proposal and was curious what people thought about this idea.

In our codebase we like to colocate our component code but at the same time try to keep separation of concerns by splitting it into multiple files. The directory structure of a component might look like this:
```
/MyComponent
  |-- index.js
  |-- styles.js
  |-- mapProps.js
  `-- connect.js
```
In our React Native projects we simply import the stylesheet from `styles.js` and then apply all HoCs using `compose` (`compose(connect, mapProps)(MyComponent)`). This allows us to make dumb components (markup) and then implement logic in `connect.js` (Redux) and `mapProps.js` (useful for mapping props to values relevant to the user).

In a CSS Modules project `styles.js` might simply become `styles.css`. For `styled-components`, though, we want to keep using `styles.js`.

This is the HoC we export:
```es6
import styled from 'styled-components';

 // anonymous `withStyle`
export default (component) => styled(component)`
  color: tomato;
`
```

Which we can later use like this:
```es6
import withStyle from './styles.js'

/* ... */

export default compose(connect, mapProps, withStyle)(MyButton);
```

To avoid having to write `(component) => styled(component)` every single time we abstracted this into a `withStyle` function that is as simple as this (basically just a parameter reversal):
```es6
const withStyle = (...args) => (component) => styled(component)(...args);
```
And can then be used like this:
```es6
export default withStyle`
  color: tomato;
`
```

My proposal is to add `withStyle` to `styled-components`. This would be a very small non-breaking addition to the public API.

Thoughts?

**Comment by migueloller** [comment]
Might be worth mentioning that the function is basically a "reverse" of the `styled` API.

From the README (but using `withStyles` HoC):
```es6
// Tomatobutton.js

import React from 'react';
import{ withStyles } from 'styled-components';

import Button from './Button';

const TomatoButton = withStyles`
  color: tomato;
  border-color: tomato;
`(Button);

export default TomatoButton;
```

**Comment by k15a** [comment]
There was already a discussion about this HOC at https://github.com/styled-components/styled-components/issues/316 and we decided that we don't want to support this syntax.

TL/DR:
> The core idea behind styled-components is that you couple DOM nodes to their styles to enforce the presentational/container component split. That styled components are React components under the hood is an implementation detail, not something you are concerned with. Treat them like any other DOM node!
