### ISSUE TITLE
domElement enhancement question

### ISSUE THREAD

**Issue by didierfranc** [styled-components/styled-components#536]
## Version
1.x
2.x

## Question

Is there a reason to use this list over a simple Object.keys(React.DOM) ?
https://github.com/styled-components/styled-components/blob/v2/src/utils/domElements.js

I made it like that in react-sc
👉 https://github.com/didierfranc/react-sc/blob/master/src/index.js#L6

**Comment by mxstbr** [comment]
Hah that's neat! /cc @geelen 

Mind submitting a PR for this against the `v2` branch? I reckon it'd kick down our package size by a lot!

**Comment by didierfranc** [comment]
I'll do it ;)

**Comment by didierfranc** [comment]
This will disappear in React 15.5/16
