### ISSUE TITLE
Default props (and maybe other statics) are mangled when overriding component styles

### ISSUE THREAD

**Issue by migueloller** [styled-components/styled-components#539]
## Version
1.4.3

## Reproduction
http://www.webpackbin.com/EJMPBMJqM

## Steps to reproduce
1. Create a styled component (`Component1`) and give it some default props.
2. Create another styled component (`Component2`) using the first one as base (`styled(Component1)`).

## Expected Behavior
`Component2` should keep the default props of `Component1`.

## Actual Behavior
`Component2` mangles the default props. It looks like this is happening [here](https://github.com/styled-components/styled-components/blob/e7cdf240997a6a67431cce5c69ddafed2fc620f7/src/models/StyledComponent.js#L19).

**Comment by mxstbr** [comment]
We're removing that behaviour in v2 in favor of an explicit extension syntax, see #518!
