### ISSUE TITLE
Styled input loose focus on change

### ISSUE THREAD

**Issue by const-g** [styled-components/styled-components#540]
## Version
1.4.3

## Steps to reproduce
1. Create Form component.
2. Within it, call a TextField Component, which is an inpunt within a div
3. Style the div around the input component with
```MaterialFormGroup = styled.div` ... `;```

## Expected Behavior
the input only is refreshed on typing (using onChange)

## Actual Behavior
When looking at the real-DOM, the form is refreshed, and so, the input loose focus at each key press

**Comment by k15a** [comment]
Could you post a more detailed reproduction please?

**Comment by theocar** [comment]
Hi there, i have the same issue.
This is a Pure React Component with a controlled styled input.
For each keystroke, focus is lost...

```
import React from 'react';
import styled from 'styled-components';

import Button from './Button';

export default function SearchBar(props) {

  const CustomInput = styled.input`
    font-size: 1em;
    text-align: left;
    border: 1px solid #EFEFEF;
    padding: 0.5em;
    width: 100%;
    border-radius: 10px;
  `;

  const SearchBarWrapper = styled.div`
    display: flex;
    align-items: stretch;
    width: 280px;
    animation: ${props.animation}
  `

  const PrimaryColumn = styled.div`
    flex: 2
  `
  const SecondaryColumn = styled.div`
    flex: 1
  `

  return (
    <SearchBarWrapper>
      <PrimaryColumn>
        <CustomInput
          type="text"
          placeholder="City"
          onChange={props.onChange}
          value={props.value}
        />
      </PrimaryColumn>
      <SecondaryColumn>
        <Button label="GO" primary/>
      </SecondaryColumn>
    </SearchBarWrapper>
);
}

``` 
![bug-styled-input](https://cloud.githubusercontent.com/assets/17475841/23509227/61a9f6ca-ff55-11e6-9f94-64a5fc8f7eac.gif)

**Comment by k15a** [comment]
@theocar If you move the styled components out of the SearchBar Component it should work.

```JS
import React from 'react';
import styled from 'styled-components';

import Button from './Button';


const CustomInput = styled.input`
    font-size: 1em;
    text-align: left;
    border: 1px solid #EFEFEF;
    padding: 0.5em;
    width: 100%;
    border-radius: 10px;
`;

const SearchBarWrapper = styled.div`
    display: flex;
    align-items: stretch;
    width: 280px;
    animation: ${props.animation}
`

const PrimaryColumn = styled.div`
    flex: 2
`
const SecondaryColumn = styled.div`
    flex: 1
`


export default function SearchBar(props) {
  return (
    <SearchBarWrapper>
      <PrimaryColumn>
        <CustomInput
          type="text"
          placeholder="City"
          onChange={props.onChange}
          value={props.value}
        />
      </PrimaryColumn>
      <SecondaryColumn>
        <Button label="GO" primary/>
      </SecondaryColumn>
    </SearchBarWrapper>
);
}
```

**Comment by narithtyty** [comment]
Thank you very much.

**Comment by samgos** [comment]
I keep running into a similar glitch when creating react hook-based components with UI frameworks which stacks rely on styled-components:

- First when using a combination of MatieralUI (MUI) components and intuitive styling using styled-components (ext lib)
- Secondly when using vanilla Bootstrap 

I'm baffled by this and can't seem to find the root of the problem, my last project used MUI without manually importing styled-components and I ran into no problems. If anyone has any ideas please do let me know, it's probably my biggest problem with hooks at this time and in environments effected by this I have to revert to refs.
