### ISSUE TITLE
[V2] Using anchor with react-router break styled <ThemeProvider />

### ISSUE THREAD

**Issue by kopax** [styled-components/styled-components#549]
I have found a bug in `v2.0.0-5`

When clicking on url that use an anchor, the `<ThemeProvider />` has no more effect.

Reverting to `v1.4.3` solve the issue.

## Version
2.0.0-5

## Reproduction
http://www.webpackbin.com/NJGs7ebqG
https://webpackbin.herokuapp.com/NJGs7ebqG

## Steps to reproduce

Use the anchroScroll method from here in your `react-router` : https://github.com/ReactTraining/react-router/issues/394#issuecomment-220221604

## Expected Behavior

To scroll to the anchor in question

## Actual Behavior

It scroll but It also break the `<ThemeProvider />` and use the theme from `defaultProps` instead.

**Comment by kopax** [comment]
@mxstbr This bug is a bit major. It does not only concern the `react-router`...

I also encounter issue ussing `<Provider />` and `react-redux`. On my LoginForm when I type in the `<input name="username" />`, the store get updated and the `<ThemeProvider />` also lose the theme

Almost all our apps use styled-components v2 and are impacted by this bug.

**Comment by santaclauze** [comment]
Seems to be the same issue : #574

**Comment by kopax** [comment]
Corrected and released in `2.0.0-9`.
