### ISSUE TITLE
How to apply the conditional expiration  

### ISSUE THREAD

**Issue by AnilGayakwad** [styled-components/styled-components#550]
Need to set the style property based on attribute value.

<pre> 
export const dynamicWidth = css`
${lengthXs}
${lengthSm}
${lengthMd}
${lengthLg}`;

export const fixedWidth = css`
  width: 17.1875rem;
`;

export const TileOrderList = styled.div`
    ${(props) => props.forpage === true ? fixedWidth : dynamicWidth}
    display: table-cell;
    vertical-align: middle;
    padding: 1.25rem;
    border: 0.0635rem solid #d6d6d6;
    float: left;
    background-color: #fff;
    margin-right: 1rem;
    margin-bottom: 1rem;
    border-radius: 0.3175rem;
    height: 7.375rem;
    overflow: hidden;
    flex-shrink: 0;
  `;
</pre>

<pre>
&#60;TileOrderList  forpage={true}&#62;
   This should be based on screen width  
&#60;/TileOrderList&#62;
</pre>

<pre>
&#60;TileOrderList  forpage={false}&#62;
   This should be based on screen width  
&#60;/TileOrderList&#62;
</pre>

**Comment by mxstbr** [comment]
What's the question here?

**Comment by AnilGayakwad** [comment]
@mxstbr 
<pre>
${(props) => props.forpage === true ? fixedWidth : dynamicWidth}
</pre>
is not working as expected, It is always 'fixedWidth'.

**Comment by mxstbr** [comment]
Can you make a reproduction on webpackbin? (just click one of the ones in the README and reproduce this) I doubt this is a mistake on styled-components' side.

**Comment by danielnass** [comment]
@AnilGayakwad you can use like this

```javascript
${({ forpage }) => !!forpage ? fixedWidth : dynamicWidth}
```
