### ISSUE TITLE
Idea: compose/extend global classes

### ISSUE THREAD

**Issue by AsaAyers** [styled-components/styled-components#551]
I have no strong opinion on what the syntax should look like, but the idea is to bundle a global class along with the generated class.

```js
const OrganizationHeader = styled.div`
    @compose(columns)
    align-items: center;
`
```

If implemented `<OrganizationHeader>` would generate `<div classNames="columns djWztg">` (or whatever the generated classname is).

**Comment by k15a** [comment]
I think the better way would be the css function:

```JS
import { styled, css } from 'styled-components'
const columns = css`
  // you columns styles
`

const OrganizationHeader = styled.div`
    ${columns}
    align-items: center;
`
```

Does this solve you use case?

**Comment by AsaAyers** [comment]
Sorry, I forgot to mention that `.columns` comes from http://bulma.io/

**Comment by k15a** [comment]
In version 2 there is the `.attr` constructor. I think you can use it like this:

```JS
const OrganizationHeader = styled.div.attrs({
  className: 'columns'
})`
   align-items: center;
`
```

You might find more information here: https://github.com/styled-components/styled-components/issues/291 and https://github.com/styled-components/styled-components/issues/291

**Comment by AsaAyers** [comment]
Thanks. I'm not sure which other issue you were trying to link to, they're both 291.

I'm closing this since this is definitely a duplicate.

**Comment by k15a** [comment]
I wanted to link to this PR https://github.com/styled-components/styled-components/pull/365
