### ISSUE TITLE
Override issue with component

### ISSUE THREAD

**Issue by JulienHe** [styled-components/styled-components#556]
Hi everyone,

my team and me are currently using styled-components for our project and we love it!
We are currently creating an icon component and wondering why we can't override this icon component style.

### Component
```
/**
*
* Icon
*
*/

import React from 'react';
import styled from 'styled-components';

import '!!style-loader!css-loader!assets/fonts/font.css';

const IconStyled = styled.i`
  font-size: inherit;
  color: black;
  color: ${(props) => props.white ? 'white' : 'inherit'};
  margin-right: 0px;
`;


function Icon(props) {
  return (
    <IconStyled className={`bc-${props.iconName}`} />
  );
}

Icon.propTypes = {
  iconName: React.PropTypes.string.isRequired,
};

export default Icon;

```

### Styling + Usage

```
const Icons = styled(Icon)`
  font-size: 50px; <-- This is not working
  margin-right: 5px; <-- This is not working
`;
```

Did someone already had this issue?

Thank you!

## Version
1.4.3

**Comment by mxstbr** [comment]
Does it work with `!important`?

**Comment by diondiondion** [comment]
You're not passing through the className prop to `IconStyled`, so styled-components can't do its job. ;)

If you pass it through, for example like this, it should work:
```
<IconStyled className={`${props.className ? props.className : ''} bc-${props.iconName}`} />
```

**Comment by mxstbr** [comment]
Thanks @diondiondion I totally missed that 😊

**Comment by JulienHe** [comment]
@diondiondion @mxstbr Thank you a lot! Works perfectly!
