### ISSUE TITLE
[v2] sometimes breaks if use with external minified styles

### ISSUE THREAD

**Issue by mqklin** [styled-components/styled-components#557]
This works:
```
import styles from 'react-redux-toastr/lib/css/react-redux-toastr.css';
injectGlobal`${styles}`;
```

But this not (notice **min**):
```
import styles from 'react-redux-toastr/lib/css/react-redux-toastr.min.css';
injectGlobal`${styles}`;
```

Repro: https://github.com/mqklin/styled-components--

Steps:
1) Click button
2) Try to close a toastr

![bug](https://cloud.githubusercontent.com/assets/9456433/23559132/d7f963b2-0057-11e7-8e24-7852724bfa96.gif)

As you can see on the gif, at start I can't close toasters. But after removing `min` from styles, all works well.

I can't use external *minified* styles?

BTW min styles works well with `style-loader` and `css-loader`

**Comment by thysultan** [comment]
patches this upstream(stylis v1.2.1) cc @mxstbr. The problem was how animation properties without semicolons i.e `... animation-name:bounceIn}` where treated.

**Comment by mxstbr** [comment]
Updating and pushing a new version.
