### ISSUE TITLE
[2.0.0-6] RN - Unexpected token type: word error

### ISSUE THREAD

**Issue by IljaDaderko** [styled-components/styled-components#559]
Updated `react-native@0.42.0` project to `styled-components@2.0.0-6` and started getting this error during initial boot of the app:

Not entirely sure what the cause is yet, going through the changelog

![img](http://i.imgur.com/y0W5pXa.png)

**Comment by jacobp100** [comment]
You were right with [issue 20](https://github.com/styled-components/css-to-react-native/issues/20#issuecomment-274074063). Although thinking about it, we need better errors!
