### ISSUE TITLE
Variables: build-time vs run-time

### ISSUE THREAD

**Issue by SimplGy** [styled-components/styled-components#560]
I think it's great that react-native's `StyleSheet` and this library both let us do run-time branching of styles in the same place we write our styles normally. I think it is a shame to lose the ability to do build-time abstractions. StyleSheet still lets you plug in variables at definition time, so they don't lose build-time configurability, but I don't see a way to do that with `styled-components`.

What do I mean?

On the web, I use SASS/LESS for build time abstraction. If I want a run-time abstraction I have to do some messy gluing to JS. At the very least the JS had to know about a css classname.

In `styled-components`, only run-time branching is supported:

```
const WarningMessage = styled.li`
  padding: 5px 10px;
  background-color: ${props => props.theme.colorWarn}; // color variable, could be a build-time decision
  color: 'white';
  box-shadow: 1px 2px 2px 0 ${props => props.theme.shade10 }; // color constant, could be a build-time decision;
  font-weight: ${props => props.important ? '"bold"' : '"normal"' }; // run-time decision, based on data about this particular message
  border-radius: ${props => props.theme.radiusSmall} // build-time would be better
`;
```

### Use cases for run-time abstractions:

* User or data influenced component state (eg: a todo `li` that is `done` or not)

### Better fit for build-time abstraction:

* button that is `primary` or not (since it's unlikely to change as a result of user input)
* Color variables
* Most applications of theming (counterargument: user selectable theme)
* UI constants (spacing, radius, some types of color definitions)

I'd argue that most of the use cases are build-time. Doing it all at run time means there is a perf impact (may be trivial) and there's a larger possibility for unexpected values to break my code.

I wonder: Is there a way to support both run-time and build-time branching? Is this a use case others find interesting?

**Comment by k15a** [comment]
Because styled-components isn't doing anything at built time (this would require you to specify a styled-components built step) we can't provide build-time branching of variables as far as I know.

**Comment by SimplGy** [comment]
Yes, I understand that. I guess I'm trying (in an open ended, not very specifically phrased way) to start two discussions:

1. Broadly: When the js community builds a new solution, are we losing some great capabilities from past solutions? Maybe we should be more transparent about tradeoffs in these situations?
2. Specifically: is there room for or interest in a 2-phase parsing approach? (in this case, it would be **parse time** and **run time**, rather than build time and run time.

A throwaway tactical approach to 2-phase parsing:

```js
// Maybe SASS style variables are filled in at "parse time" (not run time), and assumed to pull from the theme or other registry of props
const WarningMessage = styled.li`
  padding: 5px 10px;
  background-color: $colorWarn;
  color: 'white';
  box-shadow: 1px 2px 2px 0 $shade10;
  font-weight: ${props => props.important ? '"bold"' : '"normal"' }; // run-time decision, based on data about this particular message
  border-radius: $radiusSmall;
`;
```

**Comment by emusgrave** [comment]
_Disclaimer: I'm new to style-components, so I'm still wrapping my head around the best practices._ 

Are you looking to circumvent passing everything through the props/ThemeProvider? I've seen an [example](https://gist.github.com/carlosepp/112987c144fd6e301ca35940a675ae2e#file-helpers-jsx) where that was avoided by just making a central file that stores the theme and importing that file into each component. i.e.:

in theme.js
``` JSX
export const theme = {
  color: {
    primary: "#FFFFFF"
  }
};
```

in component.js
``` JSX
import theme from 'theme';
const { color } = theme;

export const Button = styled.button`
  background-color: ${color.primary};
`;
```

Does that fit with your notion of **parse time**? I'm interested to know if anyone sees any in's or out's with performance of this strategy versus the ThemeProvider???

**Comment by philpl** [comment]
I think we wouldn't want to go down the road of build time variables, since it increases complexity a lot. Also, the equivalent of these variables is just passing the actual variable in and not a function.

On the other hand, we're actually working on a build time parsing step, which allows you to optionally kick the parser (stylis) out of the bundle and parse in the babel plugin instead.

**Comment by geelen** [comment]
Yeah, I think _conceptually_ the styling block must be completely run-time. We can make build-time optimisations (like the babel step, ripping out the parser, server-side-rendering and rehydration, etc) all within that conceptual framework, as any performance issues are identified. But I don't want to introduce any new concepts that force a user to make a build-time/run-time decision, sorry.

**Comment by SimplGy** [comment]
No problem :)

I like the idea of keeping things simpler for the end user.

As a thought experiment, how could a compile/build step identify what variables are not able to change at run time?

Wouldn't it have to inspect the definition of variables across multiple modules, make sure they are never changed, and confirm there is no usage of their module that gives them visibility that could make them changeable? Seems like a difficult thing to get right in JS.

**Comment by philpl** [comment]
@SimplyGy It's actually quite simple to split these things, due to how styled components work. Variables that are functions will change, everything else won't. It's really straightforward once you have a babel plugin that already does some preprocessing :)

**Comment by SimplGy** [comment]
I'm unclear: do you mean how tagged template literals work? I thought if you did `x = foo`some string ${aVar} ${()=>bVar}` that `aVar` and the anon function that returns `bVar` are both evaluated at the time you call `x()`.

**Comment by philpl** [comment]
@SimplGy yes, they are evaluated at *run-time*, but we can still perform a split of them at *compile-time* in babel :)

**Comment by hitmands** [comment]
something like that could be achieved via [`Prepack`](https://github.com/facebook/prepack)
