### ISSUE TITLE
Webpackbin route invalid for Live Demo links

### ISSUE THREAD

**Issue by lol-russo** [styled-components/styled-components#561]
Just in case you weren't aware of this, the Live Demo links in the ReadMe and the website are throwing this error:

> The reason you see this page is that the route is invalid. You have probably clicked an old Webpackbin link. Please notify the author about moving their BIN to the new version of Webpackbin. In the meantime you can continue to the old version.

Clicking the `Continue To Bin` button just results in the same error - apparently I can't continue to the old version after all! The links were working late last week so it's only recently broken.

**Comment by diegohaz** [comment]
We need to copy the code from the `.herokuapp.com` versions to the new https://www.webpackbin.com

As now bins can be attached to a GitHub account, would it be better for @mxstbr or @geelen to create it?

Reference: https://github.com/christianalfoni/webpack-bin/issues/226

**Comment by mxstbr** [comment]
Will do ASAP!

**Comment by mxstbr** [comment]
Fixed, thanks for notifying me!
