### ISSUE TITLE
styled(ATTR_COMPO) doesn't retain the ATTR_COMPO's attributes.

### ISSUE THREAD

**Issue by f15gdsy** [styled-components/styled-components#562]
## Version
2.0.0-6

## Reproduction
http://jsbin.com/juwakuxula/1/edit?html,js,console,output

## Steps to reproduce
1. Create a styled component with attrs.
```
var Toggler = s.input.attrs({
  type: 'checkbox'
})`
  border: solid 1px red;
  background-color: red;
`;
```

2. Create another styled component based on the previous component.
```
var Toggler2 = s(Toggler)``;
```

3. Render them.
```
ReactDOM.render(
  <div>
    <h1>Styled Components</h1>
    <h2>toggler</h2>
    <Toggler></Toggler>
    
    <h2>toggler 2 </h2>
    <Toggler2></Toggler2>
  </div>,
  
  document.querySelector('#app')
);
```

## Expected Behavior
Expect both to have the same attributes.

## Actual Behavior
The 1st component has the declared attributes.
The 2nd component doesn't have the attributes.

**Comment by GGAlanSmithee** [comment]
I think this is the same behavior as I explained here https://github.com/styled-components/styled-components/pull/518#issuecomment-282600036

**Comment by geelen** [comment]
This is what's changed in #518. Try with `v2.0.0-7` which I just released, and do:

```js
var Toggler2 = Toggler.extend``
```

**Comment by f15gdsy** [comment]
Awesome!
