### ISSUE TITLE
Best practice for customizing/passing styles to components in a styled-components project

### ISSUE THREAD

**Issue by sherryxiao1988** [styled-components/styled-components#563]
It's a common use case that we built some small components that later want it to styled differently. Allowing passing a `style` prop is one way to do it. However, by doing this, we are eventually mixing inline style (when passing styles to the component) with styled-component styles.

Say we are styling a button, it's easy to classify it as either `large` or `small` button, so `size` could be passed in as prop, and we can then write styles differently inside a styled-component syntax. But how about container components, where we need to change the layout of a list of other components for example. Greater flexibility is needed in this case and then passing a `style` prop may be the best choice?

I am curious what's the community's approach/opinion towards this problem? I can't find many useful insights by Google search. 

Thanks in advance for answering my question!

**Comment by episode17** [comment]
I'm facing a similar issue where my components need to be highly customizable and ThemeProvider wouldn't cut it (the theme could be any css property; for each styled components).

The solution I'm currently testing out is inspired by [react-toolbox](https://github.com/react-toolbox/react-toolbox) and basically involves making styled components a dependency of your more complex components through a factory.

```js
// Thing.js
export function createThing({
    Wrapper,
    Header,
    Content
    Footer
}) {
    const Thing = ({ title, text }) => (
        <Wrapper>
            <Header>{title}</Header>
            <Content text={text} />
            <Footer />
        </Wrapper>
    );

    return Thing;
}


// Content.js
export function createContent({
    Wrapper,
    Box
}) {
    const Content = ({ text }) => (
        <Wrapper>
            <Box>I present you:</Box>
            {text}
        </Wrapper>
    );

    return Content;
}


// ThemedThing.js
import styled from 'styled-components';
import { createThing } from './Thing';
import { createContent } from './Content';

const ThemedThing = createThing({
    Wrapper: styled.div`
        ...
    `,
    Header: styled.header`
        ...
    `,
    Content: createContent({
        ... 
        ...
    }),
    Footer: styled.footer`
        ...
    `
});

export default ThemedThing;


// Use it
import ThemedThing from './ThemedThing';

ReactDOM.render(<ThemedThing title="Thing" text="Cool" />, ...);
```

Each component doesn't need to do all the creation, you could import a common `ThemedContent` and pass it on instead of creating it for `Thing` specifically.

The author of react-toolbox is currently experimenting with this method in [react-toolbox-airbnb](https://github.com/javivelasco/react-toolbox-airbnb).

This method works but I feel it requires a lot of boilerplate to get started and would perhaps even require validation of the dependencies. (Passing a `styled.div` to `Content` would fail because of the text prop).

**Comment by sherryxiao1988** [comment]
@episode17 Thanks for the information!

I really like this approach. [DatePicker](https://github.com/javivelasco/react-toolbox-airbnb/blob/master/src/Airbnb/DatePicker/DatePicker.js) is a good example.

This approach is closer to my original understanding of `styled-components`. _Naked components_ without styles should be easily wrapped with styles and then be plugged into other components.

However, here is the most common pattern that I found how people use styled-component(took from [react-adminlte-dash](https://github.com/zksailor534/react-adminlte-dash/blob/master/src/components/Sidebar.js)):

Define the styles used for each sub components:
```
const StyledSection = styled.section`
  height: auto;
  padding-bottom: 10px;
  display: block;
`;

const StyledAside = styled.aside`
  ...
`;
```

And then hardcode those styled components in `render` method of the main component:
```
const Sidebar = ({
  children,
  fixed = false,
  sidebarMini = false,
  sidebarCollapse = false,
}) => (
  <StyledAside
    fixed={fixed}
    collapse={sidebarCollapse}
    mini={sidebarMini}
  >
    <StyledSection name="sidebar-wrapper">
      {renderChildren(children, sidebarCollapse)}
    </StyledSection>
  </StyledAside>
);
```

The thought process of using styled-component this way is very similar to how we style components traditionally using classnames, but isn't it make reusing _naked components_ (components with pure functionality and no styling) harder? 

I do see the airbnb way introduces certain complexity/overhead, but I generally prefer it to the other approach. Any other thought?

**Comment by mdebbar** [comment]
I like the approach @episode17, it definitely works for a lot of cases. My only concern is that it forces the parent component to decide the markup in addition to the styles. The parent will decide whether it's a `div`, `section` or `p`, etc. Ideally, the parent should only decide the styles (e.g. `margin` and `outline`) and let the child decide which markup to use.

@mxstbr any ideas or patterns you can share?

**Comment by episode17** [comment]
@sherryxiao1988 The example you provided is perfectly valid and most common if want no/light theming (through ThemeProvider). In my case I can't know what css will be required by a theme so I can't use ThemeProvider like it's meant to be used. 

@javivelasco describes this in [this response](https://github.com/javivelasco/react-toolbox-airbnb/issues/1#issuecomment-285131587):

> The real theming ie changing primary colors and stuff like that should be delegated to the implementation so if you use styled components you can use ThemeProvider. This implementation should be 100% agnostic from the styles platform.

Basically a component says "give me styled components and implement your own theming solution if you want, I don't care"

**Comment by javivelasco** [comment]
Yep. I have half of a blogpost on this. I'm currently searching for an apartment in Barcelona and it's taking my whole days. I will link it here

**Comment by jonaskello** [comment]
I also find this interesting. I have some complex components in a library that needs to be styled differently for each application they are used in. With complex components I mean something similar to DatePicker, ie. a component that consists of several other components and a fair amount of logic for user interaction.

@javivelasco Did you find the time to complete the blogpost? Would be an interesting read :-).

**Comment by javivelasco** [comment]
Yeah I want to publish it with a couple of POCs and yesterday I finished a React Native implementation of an awesome DatePicker using the same core logic as react-toolbox :) I still want to build a very special web implementation for folks @ zeit. Hope to get it ready asap! Sorry for taking this long

**Comment by ms88privat** [comment]
@javivelasco can you please share it :)?

**Comment by mxstbr** [comment]
Going to close this issue since it's mainly about discussing approaches rather than anything tbd in the library itself, feel free to keep talking though!

**Comment by kceb** [comment]
@sherryxiao1988 I noticed that there is also this approach that you may be able to use: https://www.styled-components.com/docs/advanced#referring-to-other-components


Apologies for bumping an old thread, just providing a resource to future people that may come across this post.

**Comment by chrisregner** [comment]
Building on top of @episode17's suggestion, I've created [this higher-order function](https://gist.github.com/chrisregner/fb7c84fa8d59d22df9d93811b8736e92), customisableStyledComponents.

Usage:

```
import customisableStyledComponents from './customisableStyledComponents.js'

const defaultStyledComponents = {
  Wrapper: styled.div`background: red;`,
  Button: styled.div`background: yellow;`,
}

const myComponentFactory = ({ Wrapper, Button }) => {
  const MyComponent = () => (
    <Wrapper>
      <Button />
    </Wrapper>
  )
}

const CustomisableFactory = customisableStyledComponents(myComponentFactory, defaultStyledComponents)

const DefaultMyComponent = CustomisableFactory()
const CustomMyComponent = CustomisableFactory({
  Wrapper: x => x.extend`
    background: blue;
  `,
  Button: () => AnotherComponentAltogether,
})

```
