### ISSUE TITLE
TypeScript Props with css function

### ISSUE THREAD

**Issue by victorandree** [styled-components/styled-components#565]
This is arguably a usage question disguised as a request for documentation clarification. I'm struggling with adapting the `css` literals based on props, as I can't find a nice way of "hooking" in the generics.

The following throws a type error as the `css` function does not recoqnize the `props.primary` interpolation:

```typescript
import * as styledComponents from "styled-components";
import { ThemedStyledComponentsModule } from "styled-components";

interface Theme {
  primaryColor: string;
  secondaryColor: string;
}

const { css } = styledComponents as ThemedStyledComponentsModule<Theme>;

export const MyCss = css`
  color: ${(props) => props.theme.primaryColor};
  background: ${(props) => props.inverted ? props.theme.secondaryColor : props.theme.primaryColor};
`;
```

`css` does have a generic interface with regards to props, however, the following is a syntax error in TypeScript 2.2. I haven't seen any examples of how (or if) one can use generic tagged template literals in TypeScript -- which may be an issue with TypeScript (haven't seen one reported):

```typescript
interface Props {
  inverted: boolean;
}

export const MyCss = css<Props>`
  color: ${(props) => props.theme.primaryColor};
  background: ${(props) => props.inverted ? props.theme.secondaryColor : props.theme.primaryColor};
`;
```

A working solution is to explicitly give the type of props in the interpolated functions where it matters, which isn't so bad if you use an alias (badly named here, however).

```typescript
type P = ThemedStyledProps<Props, Theme>;

export const MyCss = css`
  color: ${(props) => props.theme.primaryColor};
  background: ${(props: P) => props.inverted ? props.theme.secondaryColor : props.theme.primaryColor};
`;
```

Could this be clarified in the docs? I can't see any examples of CSS adapting based on props -- only on theme.

**Comment by Igorbek** [comment]
Thanks @victorandree 👍 nice workaround, I also discovered it just recently. It definitely needs to be clarified in the docs.
However the most desirable syntax would be the one you pointed also, with explicit generic argument passed. It is not currently supported by TypeScript and being discussed here https://github.com/Microsoft/TypeScript/issues/11947. The feature is generally accepted by the TS team and they are accepting PRs :)
@styled-components/typers, does anyone want to update the docs? I could, probably, somewhen next week.

**Comment by patrick91** [comment]
@Igorbek I can write some docs tomorrow, I think that's better to document this way:

```ts
// this will be declared inside your custom theme definitions
type MyThemedProps<P> = ThemedStyledProps<P, MyTheme>;


// then inside your component you'll import it and use with you custom props:

interface Props {
  inverted: boolean;
}

export const MyCss = css`
  color: ${(props) => props.theme.primaryColor};
  background: ${(props: MyThemedProps<Props>) => props.inverted ? props.theme.backgroundColor : props.theme.primaryColor};
`;
```

What do you think?

**Comment by mxstbr** [comment]
@patrick91 did we ever update the docs?

**Comment by mxstbr** [comment]
Doesn't seem like it, closing in favor of https://github.com/styled-components/styled-components-website/issues/183

**Comment by fabb** [comment]
The code is very verbose compared to css/less variables. I'm not yet convinced of using styled components 😅

**Comment by dminkovsky** [comment]
From https://github.com/typescript-cheatsheets/react-typescript-cheatsheet#hooks

```
const ref1 = useRef<HTMLElement>(null!);
const ref2 = useRef<HTMLElement | null>(null);
```
