### ISSUE TITLE
Indicate that components must begin with an uppercase letter

### ISSUE THREAD

**Issue by yejodido** [styled-components/styled-components#573]
## Version
1.0.5

## Reproduction

https://www.webpackbin.com/bins/-KetgpNpXfRNnuPAzF9L

## Expected Behavior

<title/> renders down into div

## Actual Behavior

<title/> remains <title/>

**Comment by k15a** [comment]
This is a react specific behaviour.

**Comment by yejodido** [comment]
So not worth mentioning?

**Comment by yejodido** [comment]
I think a note that these are true .createClass components can go a long way, especially as there is no graceful failure. All the language in the docs refers to styled components as "styling components" and not component substitution adhering to React's core component-creation principles.
