### ISSUE TITLE
autocomplete css in js(babel) Sublime

### ISSUE THREAD

**Issue by jasan-s** [styled-components/styled-components#576]
This is not an issue but I just started using this lib and currently when i start typing a command the auto complete suggests he inline CSS instead of standard . ie **justifyContent** instead of **justify-content**. I'm using sublime, how can I turn off the inline auto complete for css and instead use standard css autocomplete.

**Comment by mxstbr** [comment]
We're working with @zertosh to land awesome support for `styled-components` in `babel-sublime`, coming soon!
