### ISSUE TITLE
[v2] [optimization] do not output empty classes for SSR

### ISSUE THREAD

**Issue by wmertens** [styled-components/styled-components#578]
While prerendering I get a lot of empty classes:

```
            .AddTextInput__InputField-lew40i {
            }

            .AddTextInput__PlusBtn-1yatb23 {
            }

            .ColumnsLayout__ColumnsWrapper-1u3y8xp {
            }

            .ColumnsLayout__Column-1he5qfk {
            }

            .ArrayInput__HorizLineBetween-1k50h5d {
```

it would be nice if fetching the styles for SSR removed those.

**Comment by mxstbr** [comment]
Yep, we create those to make the app easier to debug but we should only be doing this in dev, not in prod. I think @philpl has fixed that recently?

**Comment by philpl** [comment]
@mxstbr Unfortunately I just defer their creation. Let me get rid of them entirely in prod :smile:

**Comment by mxstbr** [comment]
I think we actually use those for component selectors, so we can just get rid of them I'm afraid :confused: 

Feel free to reopen if that's wrong @philpl, but I'm pretty certain we can't just not render them.
