### ISSUE TITLE
How dynamic should styled-components be used?

### ISSUE THREAD

**Issue by pierregee** [styled-components/styled-components#582]
Say, I want to abuse the dynamic nature of styled-components as such,
```JS
const bgColorChooser = (theme, type) => {
   if( theme ===light && type ==='primary') return 'white';
   else if (theme ==='dark' && type ==='primary') return 'black';
  {... more code }
}

const Button = styled.button`
background-color: ${bgColorChooser(props.theme.type, props.type)};
{... more dynamic values for each property }
`
```
From what I see from SC examples, ternary operators are used, but how about taking one step further like calling a function inside the tagged template literal for a more dynamic approach? I believe there's also a security concern here as stated in the documentation?

As you may have noticed, I'm asking these questions for the reason that I see it as too powerful library that would definitely have drawbacks.
 
Holistically, my concern is to how dynamic, styled components should be used with performance,  bundle size, css extraction in mind? Will it enforce a more restrictive approach in the future versions? What should be avoided and discouraged to use?

**Comment by siddharthkp** [comment]
@k15a @kopax @mxstbr I hope you guys don't me answering this (correct me if I am wrong)

You can totally use a function inside template literals, something like this:

```js
const bgColorChooser = (theme, type) => {
  if (theme === 'light' && type === 'primary') return 'white';
  else if (theme ==='dark' && type ==='primary') return 'black';
}

const Button = styled.button`
  background-color: ${props => bgColorChooser(props.theme, props.type)};
`

export default () => <Button theme='dark' type='primary'>click me</Button>
```

---

> security concerns

The [security concerns](https://github.com/styled-components/styled-components/blob/master/docs/security.md) stated are related to unsanitized user input, which might make you vulnerable to [XSS](https://www.owasp.org/index.php/Cross-site_Scripting_(XSS)). As long as you have control over the function does, you're good.

> performance

Adding a tiny function call is a tiny overhead over a ternary operator

      I did some benchmarking using [styled-components/benchmark](https://github.com/styled-components/benchmark) and the difference is easy to ignore

    ```
   Results for browser

    action        ternary        function     
    ------------  -------------  -------------
    render once   0.105±0.016ms  0.107±0.028ms
    prop changes  0.237±0.048ms  0.236±0.053ms
    ```

> bundle size

This completely depends on the amount of logic you put inside the function. If you write the same logic with a bunch of ternary operators, the size will be pretty much the same.

> Will it enforce a more restrictive approach in the future versions

styled-components 2.0.0 is just around the corner and it fully supports functions.

**Comment by k15a** [comment]
I think @siddharthkp answered you question pretty good.

I currently don't see how your code will actually work. For example I don't know where the `props.theme.type` in the `bgColorChooser`function call comes from. I think the correct version of the code would be the following (correct me please if I am wrong.)

```JS
const bgColorChooser = (theme, type) => {
	if ( theme === 'light' && type === 'primary') return 'white';
	else if (theme === 'dark' && type === 'primary') return 'black';
}

const Button = styled.button`
	background-color: ${props => bgColorChooser(props.theme.type, props.type)};
`
```

This way you're creating a function (the arrow function inside the styled-component) which does only call another function. In JavaScript functions are first class objects which means you can pass around the reference to the function as a value. In your example that's quite handy because you can rewrite your example as the following.

```JS
const bgColorChooser = ({ theme, type }) => {
	if ( theme.type === 'light' && type === 'primary') return 'white';
	else if (theme.type === 'dark' && type === 'primary') return 'black';
}

const Button = styled.button`
	background-color: ${bgColorChooser};
`
```

You won't get any performance issues here because you're basically writing the same code just a bit more descriptive.

In conclusion I don't see any performance and security problems with calling other functions in a styled-component.

**Comment by pierregee** [comment]
@k15a @siddharthkp Ohh, thanks for correcting the code, I should have added the arrow function. ✌️ Aaand there's even a benchmark! 👍 

Your responses completely make sense. Maybe I'm just being a little cautious on how I'm going push through with it and idk why. 🌵It's most likely because having javascript work with css in this way is just really scarily awesome. 

Awesome work! 
Anyway, please feel free to close the issue. 👍

**Comment by gevgeny** [comment]
Are there any disadvantages doing this 
```
const CurrencyValue = styled.span`
  color: ${({ isGreen }) => isPositive && myGreen};
  color: ${({ isRed }) => isNegative && myRed};
`;
```
for multiple choices ? 
SC generates exactly what i expect
```css
dMLUsr {}.gwKKUO{color:#52c41a;}.eYjnxx{color:#f5222d;}
```
