### ISSUE TITLE
Split into multiple packages and move to monorepo

### ISSUE THREAD

**Issue by jacobp100** [styled-components/styled-components#588]
In v2, we're going to be introducing a babel transform to perform some pre-parsing.

From my experience doing this, you'll find that most changes have to take place in both the styled-components and the babel plugin repos. Coordinating PRs between the two will be very difficult.

Not only this, but benchmarking (which is currently in styled-components) will also want to benchmark the results after running through the babel plugin. For this to work without cyclical dependencies, this would introduce yet a third coupled repo.

We should consider moving styled-components, babel-plugin-styled-components, and styled-components-benchmark into a Lerna monorepo for v2.

**Comment by geelen** [comment]
I fully support this. I really want `styled-components` the package to be stand-alone—you shouldn't get the babel plugin unless you choose to opt in. But for maintenance and perf testing it makes total sense for them to be developed together.

**Comment by jacobp100** [comment]
Would be good if we can keep git history. Does anybody know how to do this?

**Comment by philpl** [comment]
I think this is an awesome idea. It's quite easy to add the babel plugin repo as a subtree, to preserve most of its git history, actually.

**Comment by jacobp100** [comment]
Oh neat, [Lerna will do this for us](https://github.com/lerna/lerna#import)! I think the next step is that we'll need to pick a date to do this. We'll want to merge as many pending PRs before this, as it'll likely cause issues afterwards. I'm assuming this is v2 only?

**Comment by philpl** [comment]
@jacobp100 Ooh! I wasn't aware that they've got this built in now :)

**Comment by philpl** [comment]
@jacobp100 let's do this after v2, like prettier?

**Comment by jacobp100** [comment]
I'd say we want it for v2. If there's bugs in the babel transform that require cross project changes, it'll cause a lot of headaches.

**Comment by mxstbr** [comment]
We need to merge v2 into `master` first, before we can do this, but I agree we should do it before the official release.

**Comment by mxstbr** [comment]
Well, that didn't happen before the release, but let's do it now! PRs welcome to make this into a monorepo that contains `css-to-react-native`, the babel plugin, the website and, of course, the core package.

**Comment by k15a** [comment]
@mxstbr How about automatic changelog generation based on PR/Issuer labels with lerna-changelog like create-react-app does it?

**Comment by mxstbr** [comment]
Sure, that sounds awesome! We forget to do changelogs all the time haha

**Comment by philpl** [comment]
@mxstbr @k15a so who'd like to do this? I raise my arm for ~awareness~ volunteering for this task :P

**Comment by k15a** [comment]
I am happy to do this as well^^ After we switched to lerna it would be great to turn on prettier as well I think.

**Comment by jacobp100** [comment]
@mxstbr What's the benefit of including `css-to-react-native` in the monorepo?

**Comment by philpl** [comment]
@jacobp100 it's generally be favourable to include all repos that might affect SC and see part of our organisation. :) This way a PR that needs to change multiple repos doesn't need to be split up. It might be unlikelier for this repo, but it'd be convenient. It shouldn't have any adverse effects since we can import the git history with Lerna ;)

**Comment by mxstbr** [comment]
Yeah I'd just like to have all repos in one, but if you prefer to have `css-to-react-native` in a separate repo since you use it in other projects that's 100% fine with me!

@k15a happy for you to do the monorepo and then introduce prettier :blush:

**Comment by philpl** [comment]
@mxstbr @geelen Shall we talk about this again?

It'd be neat to have:

`styled-components-native` and `styled-components-primitives` to get rid of some root file entrypoints. That might of course mean, that we need a `styled-components-core` package, maybe.

**Comment by k15a** [comment]
@philpl I recently migrated our repos in my company to a monorepo so I am happy to give this another shot. Last time I had some problems with CI which I couldn't figure out how to solve.

**Comment by philpl** [comment]
@k15a I think we need some extensive planning first :( I'm not sure whether we're all on the same page yet

**Comment by k15a** [comment]
Just wanted to note that I am happy to help ;)

**Comment by mxstbr** [comment]
@philpl Yeah I think we want these packages in one repo:

- `styled-components`
- `styled-components-native`
- `styled-components-primitives`
- `babel-plugin-styled-components`

What I don't know is whether or not we should do the `react-router` thing and do:

- `styled-components`: Contains only shared code
- `styled-components-react` (or `styled-components-web` if we plan to stay react-only?): Contains the React code

That's what `react-router` did with `react-router-dom` and `react-router-native`, we could certainly go down that route, I wouldn't mind too much to do `import { injectGlobal } from 'styled-components-react'`. This would also make clear that APIs like `injectGlobal` are web-only.

**Comment by jacobp100** [comment]
CSS to react native could move there too which could give you more leeway when making changes

**Comment by geelen** [comment]
I think we could keep `styled-components` as it is and extract a `styled-components-core` that everything else depends upon?

**Comment by philpl** [comment]
@geelen @mxstbr I agree with Glen. I don’t think it makes sense to deviate from the original package’s name. At least for now

**Comment by mxstbr** [comment]
Sure, I don't particularly care 🤷‍♂️

**Comment by beautyfree** [comment]
Any new thoughts?

**Comment by Aaron-Pool** [comment]
just dropping a comment after @mxstbr made a note on https://github.com/styled-components/vue-styled-components/issues/39

I'd be glad to help with any chore leg work to get things moving here. I'm big fan of styled components and wish it could be extended to other frameworks more easily. Storybook has set a great precedent for other front-end libraries in to refactoring their core out to make it easily portable to any framework.

I'm a pretty capable developer, and a fairly quick study, but I don't have much knowledge of the internals going on here, so I might need some direction at first. I do have pretty decent familiarity with most modern JS front end frameworks, and pretty well-learned in javascript in general.

**Comment by probablyup** [comment]
I'm fine with this as long as the core styled-components library isn't split up into micro libs.

**Comment by mxstbr** [comment]
@makeupsomething I think the best place to start here would be to split the core `StyleSheet/StyleTags` abstraction into its own package. That leaves us with two packages:

- `styled-components-core` (or maybe `styled-sheet` or something like that to make it obvious it's not styled-components specific?): contains all (and only) the style sheet stuff so that other people can use the same code to create other APIs without duplication and we can iterate on the abstraction separately
- `styled-components`: contains all the other stuff and depends on `styled-components-core`

And then also move the Babel plugin to this repo for a total of three packages that live in this repo. The hardest part there will be to set up all the infrastructure around the monorepo, to move all the files around and to get the Babel plugin in here with its git history preserved—I'd love help with any of these!

> Making `-native` and `-primitives` separate packages isn't very urgent or important, we should just do that sometime after that initial split

**Comment by makeupsomething** [comment]
@mxstbr Thank you for the pointers for getting started! Haven't got so much experience with this kind of work but will start trying to `StyleSheet/StyleTags` abstraction into its their own package now.

**Comment by mxstbr** [comment]
Ace @makeupsomething! :100: Submit a WIP PR as soon as you have anything, we'll be happy to give more pointers as needed.

**Comment by probablyup** [comment]
And make sure to use the develop branch as your base

**Comment by mxstbr** [comment]
@makeupsomething any news yet? 👍

**Comment by makeupsomething** [comment]
@mxstbr Sorry, not yet. Was planning to get started this weekend! 🙏

**Comment by mxstbr** [comment]
Perfect :100:

**Comment by murbanowicz** [comment]
Is it going to move forward or not?
Recently I got issues in my project (yarn workspaces with backend and web ui) because of **React Native types**... All caused by the fact that in UI I am using styled components so I need types for them and @types/styled-components has to import React-native ...

**Comment by mxstbr** [comment]
We have a monorepo (thanks to @imbhargav5) but have not split the package into multiple ones.

**Comment by murbanowicz** [comment]
Would you consider it? It makes sense to split into core/web and Native at least.

**Comment by mxstbr** [comment]
We are reworking the core StyleSheet right now, which will live in a separate package: #2357 

I am not sure if splitting native if feasible, but I would be open to reviewing a PR that added `styled-components-native` as a separate package!
