### ISSUE TITLE
Formatting with Prettier

### ISSUE THREAD

**Issue by philpl** [styled-components/styled-components#589]
Now that we have an issue tracking a possible migration to a Lerna mono-repo, I'd like to start a discussion about [prettier](https://github.com/prettier/prettier)!

While I was working on my PR, I was noticing that the linting is not very strict, and thus a lot of different formatting issues arise. Argument alignment? Sometimes it's whitespace-aligned, sometimes not. Small details like these!

I guess we could just side-step the entire formatting / linting debate and get rid of all inconsistencies by jumping on the hype train, and using prettier 🥇

**Comment by k15a** [comment]
I would totally love to see prettier at styled-components to have a consistent code style. IIRC Max likes the idea as well.

**Comment by vernondegoede** [comment]
I'm currently experiencing some weird output when using prettier and styled-components. It's related to this issue: https://github.com/prettier/prettier/issues/786
