### ISSUE TITLE
What about SASS-like stuff

### ISSUE THREAD

**Issue by VicStor** [styled-components/styled-components#590]
Hi there, I've made some extension for my projects. Do you think it's useful?
Here is description
### Extend style-components with object of following shape
```JS
{
  vars: {
    variableName: 'Variable string value'
  },
  mixins: {
    flex: (flex) => `flex: ${flex}`
  }
}
```
#### Extension
variables are the strings, like **padding: #minSpace;**

mixins are the functions, like **@flex(1 1 auto);**

mixin accepts varible as argument, like **@margin(#minSpace)**

mixin accepts multiple arguments, like **@tint(#primaryRed, -10%)**

```JavaScript
styled.init({
  vars: {
    minSpace: '0.5em',
    primaryRed: 'red',
    'd:f': 'display: flex',
    'ff:rn': 'display: flex; flex-flow: row nowrap',
    'ff:cn': 'display: flex; flex-flow: column nowrap',
    'jc:sb': 'justify-content: space-between',
    'f:a': 'flex: auto'
  },
  mixins: {
    flex: (flex) => `flex: ${flex}`,
    margin: (margin) => `margin: ${margin}`,
    tint: (color, value) => coolTintColorFunctionFromOutside(color, value)
  },
});
```
#### Invocation
```JavaScript
const Wrapper = styled.div`
  padding: #minSpace;
  #ff:cn;
  #jc:sb;
  @flex(1 1 auto);
  @margin(#minSpace);
  background-color: @tint(#red, -10%);
`;
```

**Comment by k15a** [comment]
In my opinion the better way would be to have JS care about variables and mixins. What speaks against using JS for all this for you?

```JS
const minSpace = '0.5rem'
const primaryRed = 'red'
const df = css`display: flex;`
const ffrn = css`display: flex; flex-flow: ro nowrap;`
const ffcn = css`display: flex; flex-flow: column nowrap;`
cont jcsb = css`justify-content: space-between;`
const fa = css`flex: auto;`

const flex = flex => css`flex: ${flex};`
const margin = margin => css`margin: ${margin};`
const tint = (color, value) => coolTintColorFunctionFromOutside(color, value)


const Wrapper = styled.div`
  padding: ${minSpace};
  ${ffcn}
  ${jcsb}
  ${flex(1, 1, 'auto')}
  ${margin('minSpace')}
  background-color: ${tint(primaryRed, -10)};
`;
```

This way nobody has to learn a new pseudo CSS language and we don't have to bload the styled-components with things JS does very good.

**Comment by VicStor** [comment]
New pseudo CSS it's not the point here. You free to use variables as you like. 
The important difference here is that you instantiate your variables and mixins **only ones in your project** like this
```JS
import styled from 'styled-components'
styled.init({
  vars: {},
  mixins: {}
})
export styled;
```

then you use extended version of 'styled' in your project.
**So you don't need to import-export all that const jungle everytime you need it, the 'styled' singleton contains it.**

Here is actual code where I add new init method to styled. So idea was to use advantage of singleton
```JS
export default (styledComponent: Function) => {
  const styled = (tag: Target) =>
    (strings: Array<string>, ...interpolations: Array<Interpolation>) => {
// My part from here
      const { globalObject } = styled
      const newStrings = globalObject ? replaceVarsAndMixins(globalObject)(strings) : strings
// to here
      return styledComponent(tag, css(newStrings, ...interpolations))
    }

  // Shorthands for all valid HTML Elements
  domElements.forEach(domElement => {
    styled[domElement] = styled(domElement)
  })
 // Here is init method
  styled.init = (globalObject) => {
    styled.globalObject = globalObject
  }

  return styled
}
```

**Comment by philpl** [comment]
@VicStor the problems with this proposal are essentially two things:

You're trying to introduce a custom syntax here (not even some postcss var stuff) and for sth that we can already do with js. This goes against css-in-js, the idea of which is explicitly using what we're already "good at" to make css better. Variables are a part of that.

The second thing is, that you're introducing global and this is sth that we want to get rid of with css-in-js.

Overall this increases complexity, but doesn't buy us anything, and also goes against what styled-components stands for.

I hope this wasn't too direct :wink: thanks for the proposal nonetheless!

**Comment by VicStor** [comment]
@philpl 

> You're trying to introduce a custom syntax here
As I told before - you free to use variables as you like. I have AtomCSS background so use it this weird syntax. Let's stick to that you can just define project color palette globally.

> The second thing is, that you're introducing global and this is sth that we want to get rid of with css-in-js.
Still 'injectGlobal' is a part of 'styled-component'. So basically it's the same but more flexible, cause 'styled' will transpile it instead of inject directly to style sheet.

It's ok to argue to me, just feel free to say anything, Its absolutely ok, I just try to advocate my approach cause I found it easy to use and type less. 😉

**Comment by philpl** [comment]
@VicStor I'm sorry, but I meant globals as in variables in a global namespace. `injectGlobal` is an exception to what we normally do and we're very clear about this in the docs:

> We do not encourage the use of this. Use once per app at most, contained in a single file. This is an escape hatch. 

It's only for reset-like / normalize-like stylesheets.

The thing with adding sth like this is, while you're getting rid of import-statements for some variables, you're adding globals and changing the expected css syntax. I mean, stylis even supports `~~foo` and `var(~~foo)` similar to css's `--foo` and `var(--foo)`, but it's all custom and adds more mental overhead.

I'm not that concerned about the mental overhead however, but I'm more concerned that adding something like this would mean that we're departing from being a pure css-in-js approach.

For reference btw:
![download-1](https://cloud.githubusercontent.com/assets/2041385/24073677/34b71986-0bf3-11e7-9b20-690721028ca9.png)

Thanks btw, I always appreciate a good discussion 😃

**Comment by VicStor** [comment]
@philpl 
Looks like i confused you by my strange 'pseudo css' syntax and 'global' word I'd used.
It's actually not incline you to use any particular syntax nor create any global styles.
I'll try to explain what it actually does and how and we could start the discussion from blank sheet. Just give me sometime, and i come back with clear explanation.
