### ISSUE TITLE
innerRef support for withTheme() HOC

### ISSUE THREAD

**Issue by evan-scott-zocdoc** [styled-components/styled-components#591]
## Version
1.4.4

## Reproduction
https://www.webpackbin.com/bins/-KfSbgVyPqFmY7yJYVj0

## Steps to reproduce
Style a `withTheme()`-wrapped component and try to use the `innerRef` callback to grab the wrapped component instance.

## Expected Behavior
I would expect the `innerRef` callback to resolve to the deeply nested child.

## Actual Behavior
The `withTheme` HOC instance is returned by `innerRef()` and there's no way to get the wrapped child component.

**Comment by evan-scott-zocdoc** [comment]
Ugh accidentally overwrote my bin, hang on.

**Comment by brunolemos** [comment]
@evan-scott-zocdoc  Just to make sure... 

This is the [current output](https://www.webpackbin.com/bins/-KfY9iZeeXCfsAIOuyC2):
```
"this.child instanceof Child === false"
"this.child instanceof ThemedChild === true"
"this.child instanceof StyledThemedChild === false"
```

and you were expecting this:

```
"this.child instanceof Child === true"
"this.child instanceof ThemedChild === false"
"this.child instanceof StyledThemedChild === false"
```

Is that correct?

**Comment by evan-scott-zocdoc** [comment]
Yes that's correct.

**Comment by brunolemos** [comment]
I don't think it's related to `withTheme` because if you replace the following line:

```diff
-const ThemedChild = withTheme(Child);`
+const ThemedChild = styled(Child)``;
```

The output will be all `false`.

**Comment by evan-scott-zocdoc** [comment]
Ah the example should probably be tweaked, as you can't take a `ref` on a SFC. I'll do that now.

**Comment by evan-scott-zocdoc** [comment]
@brunolemos updated the example, your change will now reflect `Child` as the constructor as expected.

**Comment by mxstbr** [comment]
This should definitely be fixed! Thanks for the reproduction.

**Comment by philpl** [comment]
This PR should fix this :smile: https://github.com/styled-components/styled-components/pull/710

@evan-scott-zocdoc @mxstbr

**Comment by evan-scott-zocdoc** [comment]
Woot!

**Comment by philpl** [comment]
All done 😸

**Comment by denkristoffer** [comment]
I'm seeing this behaviour again with SC 3.2.5 (https://codesandbox.io/s/056wj1zmw), possibly because of https://github.com/styled-components/styled-components/pull/1414 ? Or am I doing something wrong here?

**Comment by kitten** [comment]
@denkristoffer That happens because your `InputWithRef` component (which shouldn't be necessary in the first place :wink:) tries to use the `ref` prop, which is a special prop and thus not accessible to you. tl;dr you can't pass `ref` and expect to receive it in the component. That's why we call it `innerRef`. Renaming it fixes
the problem: https://codesandbox.io/s/72m8xxy121

Btw it's not preferable to post comments on closed/stale/old issues (this issue is all of those three things 😅) It's easier to create a new issue or ask for help on Spectrum
