### ISSUE TITLE
innerRef is leaked as a prop to the wrapped component

### ISSUE THREAD

**Issue by evan-scott-zocdoc** [styled-components/styled-components#592]
## Version
1.4.4

## Reproduction
https://www.webpackbin.com/bins/-KfSW7ArY2ALUjC5qswH

## Steps to reproduce
Wrap any component in `styled()` and use the `innerRef` callback to access it.

## Expected Behavior
`innerRef` should not be leaked as a prop to the wrapped child component.

## Actual Behavior
`innerRef` is leaked as a prop to the wrapped child component.

**Comment by kopax** [comment]
Maybe it's related to [this](https://github.com/styled-components/styled-components/blob/v2.0.0-9/src/models/StyledComponent.js#L127)

Have you tried to clone styled and build your own version without it ?

**Comment by mxstbr** [comment]
This is the expected behaviour, how would you otherwise access the inner component with a ref? You couldn't.

**Comment by evan-scott-zocdoc** [comment]
Wait what? innerRef only is useful to the StyledComponent wrapper component. The eventual child has no use for it.

**Comment by mxstbr** [comment]
If you have `const Outer = styled(Inner)` and you render `<Outer />` how else would you get the non-styled-component node? If you did `<Outer ref={} />` the ref would refer to the styled-components wrapper element, not the actual DOM node, right?

**Comment by evan-scott-zocdoc** [comment]
I think you might be misunderstanding what the issue is.

innerRef is an ok pattern to use to access the wrapped child, but in that styled wrapper component it should be deleting the innerRef prop and not forwarding it to the child. That's what I'm trying to point out. innerRef is a styled-components implementation detail that shouldn't be leaked.

**Comment by mxstbr** [comment]
I'm not misunderstanding, I get what you're trying to tell me: Don't pass `innerRef` to wrapper child components.

I think what you're misunderstanding is that this would make some things impossible. Imagine this component:

```JS
const Input = ({ className }) => <input type="text" className={className} />

const WrappedInput = styled(Input)``;
```

Now when I render it, how can I focus the input?

```JS
<WrappedInput ref={comp => this.input = comp} />

// this.input is the styled-components wrapper, not the DOM node, so this doesn't work, right?
this.input.focus();
```

(I don't know if this is actually the case, but I think it is)

You can fix this with `innerRef` though:

```JS
const Input = ({ className, innerRef }) => <input type="text" ref={innerRef} className={className} />

const WrappedInput = styled(Input)``;
```

```JS
<WrappedInput innerRef={comp => this.input = comp} />

// Works!
this.input.focus();
```
