### ISSUE TITLE
Responsive font support for react-native

### ISSUE THREAD

**Issue by IljaDaderko** [styled-components/styled-components#594]
Hey guys, first off v2 runs beautifully for mu iOS react-native support, secondly I wanted to ask if `styled-component/native` offers solution for responsive fonts for rn? As at the moment only solution seems to be a switch statement with various screen sizes that returns different font values.

**Comment by mxstbr** [comment]
Since `polished` is now out I feel like we should push that there. Please chime into this issue with what you expect: https://github.com/styled-components/polished/issues/129
