### ISSUE TITLE
Proposal: theme isolation

### ISSUE THREAD

**Issue by Igorbek** [styled-components/styled-components#598]
I expect this topic has been raised a few times and I'm not really sure that my approach was not well discussed. The only related issue I found was _Theme adapters proposal_ #113 which didn't really address the problem I'm going to state.

## Problem

Currently, all the styled components share the same source of the theme in the context. That makes almost impossible to isolate different themes. The only offered solution, `ThemePropvider`'s `theme` prop as a function, doesn't solve that issue.

To be more precise, let's assume a UI library wants to use `styled-components` as its internal implementation details. It would just expose components along with its own version of `ThemeProvider`.

```js
import { CrazyThemeProvider, CrazyButton } from 'crzy-ui';

const crazyTheme = { carzyColor: 'papayawhip' };

const MyApp = () =>
  <CrazyThemeProvider theme={crazyTheme}>
    <div style={{ backgroundColor: 'green' }}>
      <CrazyButton label='yo' />
    </div>
  </CrazyThemeProvider>;
```

Now, if an app wants to use `styled-components` it will get into the issue:

```js
import { CrazyThemeProvider, CrazyButton } from 'crzy-ui';
import styled, { ThemeProvider } from 'styled-components';

const myTheme = { bgColor: 'green' };

const Container = styled.div`
  background-color: ${p => p.theme.bgColor};
`;

const crazyTheme = { carzyColor: 'papayawhip' };

const MyApp = () =>
  <ThemeProvider theme={myTheme}>
    <CrazyThemeProvider theme={crazyTheme}>
      <Container>
        <CrazyButton label='yo' />
      </Container>
    </CrazyThemeProvider>
  </ThemeProvider>;
```

Since, internally `CrazyThemeProvider` is just the same `ThemeProvider`, user's theme got lost.

I guess, such a use case would be exactly that if, for example, [`material-ui`](https://github.com/callemall/material-ui) chose `styled-components` as its styling engine.

To me, it seems very common use case for library authors.

## Proposed Solution

Similarly to what #113 proposed, each styled component should have a _theme resolver_, which is a function:

```ts
type ThemeResolver<TTheme> = (context: any) => ThemeSubscribable<TTheme> | undefined;
type ThemeSubscribable<TTheme> = (themeObserver: ThemeObserver<TTheme>);
type ThemeObserver<TTheme> = (nextTheme: TTheme) => void;

// sample implementation of a static theme:
const staticTheme = { ... };
function staticThemeResolver() {
  return (observer) => observer(staticTheme);
}
```

So that existing behavior will be achieved by the following resolver:

```js
const defaultThemeResolver = (context) => context[CHANNEL];
```

Obviously, it enables proper theme isolation, since the responsibility of theme resolving is not predefined and each component can have its own strategy.

## Developing the idea for convenient use

Of course, passing theme provider function to each individual styled component would be terribly inconvenient. Instead, I propose exposing a configuration API that would build a version of `styled-components` where all the strategies are encapsulated:

#### crazy-ui-styled-components.js
```js
import styledComponentsFactory, { channelThemeResolverFactory } from 'styled-components/factory';

const defaultCrazyTheme = { carzyColor: 'papayawhip' };
// pass channel name and optional configuration
const crazyThemeResolver = channelThemeResolverFactory('__crazy-ui__',
  { defaultTheme: defaultCrazyTheme });

// this is 'styled-components' module which produce styled components with custom theme resolver
const styledComponentsModule = styledComponentsFactory({
  themeResolver: crazyThemeResolver
});

const { default as styled, css, keyframes, injectGlobal, ThemeProvider, withTheme } = styledComponentsModule;

// re-export same functions as it were styled-components module
export default styled;
export { css, keyframes, injectGlobal, ThemeProvider, withTheme };
```

#### crazy-button.js
```js
//import styled from 'styled-components'; // was
import styled from './crazy-ui-styled-components'; // became

// theme resolver is already attached to styled function, so that it produces components with isolated theme
export const CrazyButton = styled.button`
  background-color: ${p => p.theme.carzyColor}
`;
```

Now, the implementation details of `crazy-ui` library are isolated for consumer and any other libraries/components that use `styled-components` would not interfere.

## Notes

- there could be many strategies of implementing theme resolvers (static theme, context-based with static channel name, context-based with auto-generated channel name, ...)
- proposed API is just an example; for example, theme resolver could accept more than just context, but also some props

/cc @mxstbr @geelen

**Comment by mxstbr** [comment]
We don't want to add configuration to `styled-components`. Wouldn't something [like this](https://github.com/styled-components/styled-components-experimentation/blob/master/component-libraries/shared-component-libraries.md) solve the issue?

**Comment by Volune** [comment]
It looks like styled-components requires React >=16.3, which supports the new context API.

Being able to provide the context when coding the component may be a solution to this issue (and would also be a workaround for my problem in #2179 )

Something like
```
const CrazyButton = styled.button(crazyContext)`
  background-color: ${p => p.theme.bgColor};
`;
```

(just an idea, I didn't spent time to think it deeply)

**Comment by mxstbr** [comment]
This is a really old issue so I am going to close it. @Volune I don't think we would introduce anything that would add a lot more manual work to the chore of writing components!
