### ISSUE TITLE
Comma separated pseudos

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components#6]
This currently only applies the styles on focus, but not on hover:

```JS
const Component = styled.div`
  background-color: blue;

  &:hover,
  &:focus {
    background-color: red;
  }
`;

**Comment by geelen** [comment]
hahahaha i'm so sorry I'll write a real parser one day I promise

**Comment by geelen** [comment]
It's the newline, not the comma, that's breaking things btw.

**Comment by maartenth** [comment]
Maybe this restriction could be added to the documentation in the meantime?
