### ISSUE TITLE
[Question] Where does the propTypes go

### ISSUE THREAD

**Issue by santaclauze** [styled-components/styled-components#604]
I would like to create a Table of my propTypes, it appear styled just move them. (I still have the warning if I send a wrong prop value)

Why do the propTypes get removed and where do they go ?

## Version
2.0.0-8

## Reproduction

https://www.webpackbin.com/bins/-KffrJNJSlKOr2zlr4Iu

## Steps to reproduce

Click on the link, the propTypes can't be read as soon as we pass it to styled component.

## Expected Behavior

No change

## Actual Behavior

propTypes are undefined.

**Comment by k15a** [comment]
They stay at the place you applied them, in you case at the `TitleWithPropTypes` component.
If you need them in your `TitleWithPropTypesWithStyled` component then apply the propTypes to it.

```JS

class TitleWithPropTypes extends React.Component {
   render () {
      return <h3 className={this.props.className}>{this.props.content}</h3> 
   }
}

const TitleWithPropTypesWithStyled = styled(TitleWithPropTypes)`
  color: purple;
  text-decoration: underline;
`;

TitleWithPropTypesWithStyled.propTypes = {
   content: React.PropTypes.string.isRequired 
}

TitleWithPropTypesWithStyled.defaultProps = {
   content: "my constructor should use propTypes"
}
```

**Comment by santaclauze** [comment]
@k15a https://github.com/styled-components/styled-components/issues/453#issuecomment-286095913

We were confronted with a similar issue where, after applying our own theme, and causing  a re-render, the `defaultTheme` would surcharge our `customTheme`. The issue was solved by moving the `defaultProps` before `styled()`.

We are still awaiting for an answer regarding that issue. This means that we would be applying the defaultProps (before styled()) at a different location than the propTypes (after styled()).

Anyhow, is there a reason why the propTypes were not passed to a styled component?

**Comment by k15a** [comment]
I think the main reason is that we don't want to inherit the propTypes and defaultProps from a component implicitly as this would be kind of confusing. Basically styled-components is nothing else then a HOC and they normally never inherit propTypes and defaultProps.

**Comment by maulerjan** [comment]
It would be great if there was some kind of global option for all the `styled(...)` HOCs to inherit propTypes. My IDE relies on propTypes for coding assistance and if I wrap my component like `const StyledButton = styled(Button)` then I don't get any prop suggestions for `StyledButton`. I'd like my IDE to suggest the props defined in `Button`'s `propTypes` for `StyledButton` as well.

Is it possible to have something like this implemented?

**Comment by hamer86** [comment]
@maulerjan Did you ever find a solution for this?
