### ISSUE TITLE
[v2] CSS doesn't get injected for second instance of a component

### ISSUE THREAD

**Issue by FrancescoA** [styled-components/styled-components#609]
Hi everyone!

A quick unrelated message: I've been using styled-components (in combination with next.js, thus using v2 and the experimental SSR API) and have really been loving it. Thanks for all the great work. Looking forward for all the SSR issues being squashed.

## Version
2.0.0-8

## Reproduction

In the demo I have a simple Spinner component that is just a styled-component. For some reason, when I use the component a second time with different props (and thus changing the styles, generating a new class name etc...) it seems that the CSS is not injected anywhere (at least Chrome can't find it).

If it is at all useful, I was able to fix this by redundantly using Spinner.extend to create a new component (for the second use).

## Steps to reproduce
Fortunately I was able to reproduce exactly:
[webpackbin](https://www.webpackbin.com/bins/-Kfqz_B7M5EeKpIzlSf_)

## Expected Behavior
Two styled divs

## Actual Behavior
Open Chrome dev tools:
Only one styled div and one unstyled div. Unstyled div has unique classname, but that class apparently doesn't exist in CSS.

**Comment by philpl** [comment]
@FrancescoA Wow! This was hard to spot. So, on the last line of your template literal there's an excessive closing parenthesis.

I'll investigate this further and see why this caused such a weird bug. It's probably because the generated rulesets end up being malformed.

**Comment by FrancescoA** [comment]
Wow I missed that! Thanks for taking a look. Closing.

**Comment by mxstbr** [comment]
We need to get better at highlighting errors in your CSS (/cc @thysultan), but I'll close this issue for now.
