### ISSUE TITLE
Making documentation on props passed in more clear

### ISSUE THREAD

**Issue by DaveyEdwards** [styled-components/styled-components#610]
So it was my first time trying to get the props working and found that the docs were not clear to a amateur programmer such as myself (took me about 3 hours in total to figure it out).  

Something along the lines of if you are using a styled-component within your component you MUST pass your styled component the props you want it to use.  After trying to think of how to explain it, I feel a example of this would probably be best for newcomers.

What I was trying to do (tried many different things to get it to work)
```
// Page component
<Page>
    <Header background={'red'} />
</Page>

// Header Component
const HeaderStyles = styled.div`
    background: ${props = props.background || 'none'};
`;
<HeaderStyles>
    <h1>{this.props.title}</h1>
</HeaderStyles>
```
**Solution:**
```
// Header Component
const HeaderStyles = styled.div`
    background: ${props = props.background || 'none'};
`;
<HeaderStyles bg={this.props.bg}>
    <h1>{this.props.title}</h1>
</HeaderStyles>
```

Thanks again for the awesome project!

**Comment by philpl** [comment]
Glad that you like it!

Why do you think this part of the readme is unclear? https://github.com/styled-components/styled-components#adapting-based-on-props

Maybe you can send a PR and show us how you'd explain it instead? :wink:

(Btw your examples are using equal signs instead of arrows in the interpolations)

**Comment by DaveyEdwards** [comment]
Yeah even after reading it again I don't think I would have figured it out from reading the docs.  As a amateur I usually need to see a single example of the exact way to do it for all the use cases.  Now I feel it has all the bases covered.  I am surprised I couldn't find other people having the issue, as I was about to give up and keep using inline styles.

Here's my first pull request!
#616

**Comment by philpl** [comment]
Forgot to close this issue. As mentioned on the PR, it's going to be addressed on the upcoming website / docs 

https://github.com/styled-components/styled-components-website/blob/master/components/basics/adapting-based-on-props.js
