### ISSUE TITLE
Global namespace

### ISSUE THREAD

**Issue by dapids** [styled-components/styled-components#613]
Hi guys!!

First of all thank you very much for `styled-components`. We're massively using it in our company and we're superhappy with it! Great job!!

Lately we were forced to start using a global namespace for our css and we noticed that `styled-components` does not really play well with it.

Here you can find a bin with a practical example: https://www.webpackbin.com/bins/-KfvQIyzL57v9tfNRauJ .

**Actual behaviour:**
The background is `green`.

**Expected behaviour:**
The background is `papayawhip`.

So far we're handling it by adding to each styled component a class `self` in order to style them in this way:
```
&.self {
  background: papayawhip;
}
```

But of course we're not satisfied with this solution.

We thought it would be useful to pass to the `ThemeProvider` a global namespace to use for increasing the `styled-components` selectors specificity.

Do you have any other suggestion/solution for such a case?

**Comment by thysultan** [comment]
maybe `:global()` or increment specificity `&&& {}` is what you're looking for?

**Comment by dapids** [comment]
Hi @thysultan, thanks a lot for your reply. :)

Increasing the specificity with `&&...` is a nice idea to avoid using a class for that purpose. But it still doesn't look neat to us to be forced to wrap each component's style in it.

Regarding `:global()`, I don't quite understand how it could help us. Would you mind providing a small example?

**Comment by thysultan** [comment]
I don't think i understand the problem yet. Is it a specificity issue? or selector issue? 

> Regarding :global(), I don't quite understand how it could help us. Would you mind providing a small example?

since `${A}` and `:global()` together `:global(${A})` could be used to select arbitrary components from outside of themselves i thought that might be it but maybe it's actually a specificity issue.

**Comment by dapids** [comment]
> I don't think i understand the problem yet. Is it a specificity issue? or selector issue?

It is a specificity issue. :)

**Comment by thysultan** [comment]
Does changing the point at which you are loading the external global css help?

**Comment by dapids** [comment]
No. The loading order does not influence the outcome.

Eventually `.namespace div` overrides `.h4sH`. :/

**Comment by geelen** [comment]
Yeah, if you've got specificity problems, the only way is more specificity, sadly. So `&&` is your way out, either that or use `!important` or inline styles 😒 

If you don't want to do one of those, you have to refactor your CSS to not have `.namespace div` rules setting things that the styled components is trying to override.

**Comment by dapids** [comment]
@geelen, thanks a lot for your reply.

In our case we can't refactor the namespaced CSS, so it seems that our only solution is to use `&&`.

We'll go for it until a better solution comes out. ;)

**Comment by nvanselow** [comment]
We've run into this same issue. I've opened a PR that uses babel-plugin-styled-components along with some minor changes to styled-components to allow for additional classes to be added to the selectors for styled components.

https://github.com/styled-components/styled-components/pull/1260
https://github.com/styled-components/babel-plugin-styled-components/pull/101

**Comment by nvanselow** [comment]
The PR referenced in the previous comment is now closed. Based on a suggestion by @philpl, I have created an independent babel plugin that will automatically add && or a list of specified classes to all the styled components. I will make that publicly available as soon as I get everything setup.
