### ISSUE TITLE
[Question] How to use "ref" to access the DOM when using styled.

### ISSUE THREAD

**Issue by kopax** [styled-components/styled-components#617]
I have a case where I click on a toggle `<Button />`, then I need to focus the `<Input />`.

The `<Input />` is a component made with styled-component v2.

I have the following code in the Component : 

```jsx

  componentDidUpdate() {
    if (this.search) {
      this.search.getDOMNode().focus();
    }
  }

  render() {
    return (
      <div className="input-group">
        <div className="input-group-add-on"><Fa search /></div>
        <Input ref={(search) => { this.search = search }} type="text" name="search" placeholder="$btn-primary"/>
      </div>
    )
  }
```

I have the following error: 

     this.search.getDOMNode is not a function

After some inspection, it appear I can't use this with styled. What is the recommended way to deal with this issue ?

## Version
2.0.0-8

**Comment by k15a** [comment]
You hav to use `innerRef` instead `ref`

**Comment by kopax** [comment]
I have changed to 

```jsx
  componentDidUpdate() {
    if (this.search) {
      this.search.focus();
    }
  }
```

and

```jsx
   <Input innerRef={(search) => { this.search = search }} type="text" name="search" placeholder="$btn-primary"/>
```

And I still have not access to my element : 

     this.search.focus is not a function

**Comment by mxstbr** [comment]
I'm running into this, seems to be a bug. :confused:

**Comment by k15a** [comment]
I can't reproduce this issue: https://www.webpackbin.com/bins/-KgcztCjQiBFVL6GQvOx

@kopax Am I missing something?

**Comment by kopax** [comment]
@k15a https://www.webpackbin.com/bins/-KgnwLjf_SXDxMDfideY

**Comment by kopax** [comment]
@k15a I am not sure if it is the same bug as @mxstbr. I got the reason of my bug here in https://github.com/styled-components/styled-components/issues/618

**Comment by philpl** [comment]
Does this work now in 2.0.0-12 possibly?
