### ISSUE TITLE
Is the client-side style injection configurable?

### ISSUE THREAD

**Issue by coltonTB** [styled-components/styled-components#627]
Hey, just starting to use styled-components here. Really impressed with this project so far, and I have some questions.

1. Are styles being injected into the head dynamically depending on which components are rendered? If so, is there any effort to pre-compile the CSS to avoid unnecessary DOM interaction?

2. In the case of server-rendered styles (which I managed to get working by using the 2.0 branch), there's duplication of the styles because the client is appending to <head />. Is there any way to turn that off? IMO, the best configuration would be to pre-render the page with styles added to head, with the client doing no style injection at all.

Thanks!!

**Comment by mxstbr** [comment]
> Are styles being injected into the head dynamically depending on which components are rendered?

Yes.

> If so, is there any effort to pre-compile the CSS to avoid unnecessary DOM interaction?

Yes, see https://github.com/styled-components/babel-plugin-styled-components. It's currently experimental but pre-parsing works with v2, and we're looking towards extraction of static CSS files. /cc @philpl 

> re-render the page with styles added to head, with the client doing no style injection at all.

We're looking into this, see #386 and linked issues for ongoing discussions. We definitely want to fix this until the proper release.
