### ISSUE TITLE
[V2] Universal app outputting two <style> tags

### ISSUE THREAD

**Issue by lauriejones** [styled-components/styled-components#628]
We are using styled-components for a handful of components in a fairly large universal js app. 

We are using the `<style dangerouslySetInnerHTML={{ __html: styleSheet.getCSS() }} />` method to server render the styles, and then resume on the client.

We are find that styled-components is outputting 2 separate style tags with duplicate styles.

The main reason this is an issue for us is that we are `injectGlobal`-ing a `font-face` and running into this chrome bug: https://bugs.chromium.org/p/chromium/issues/detail?id=602968 (_invisible fonts_).

## Version
2.0.0-10 

## Steps to reproduce
- Server render styles using `styleSheet` and `getCSS` method.
- Inspect the <head> of the document and see 2x `<style>` tags.

## Expected Behavior

One style tag to be added to the DOM, and hydrated with any additional styles from new components as the user navigates through the app.

## Actual Behavior

Server renders one style tag with all initial styles, client adds a second identical style tag. Second (client rendered) style tag is then hydrated with future styles.

e.g.

```
<head>
<style type="text/css">@font-face {font-family: 'nibdings';font-weight: normal;font-style: normal;src: url('public/files/1f674a6cc2ba32b64a73b5218353732c.eot');src: url('public/files/1f674a6cc2ba32b64a73b5218353732c.eot?#iefix') format('eot'),  url('public/files/a9aafbe28cb97db40ecc4af90960ab6b.woff') format('woff'),  url('public/files/1dbf742e49e6d9cf99a74f84f99ccc8a.ttf') format('truetype'),  url('public/files/6780ecc884d7520b8977c6fed0d0d1ef.svg#nibdings') format('svg');}.sc-bdVaJa {}.hgLecI {display: inline-block;font-size: inherit;font-style: normal;line-height: 1;text-rendering: auto;-webkit-font-smoothing: antialiased;-moz-osx-font-smoothing: grayscale;vertical-align: middle;font-size: 48px;color: #009623;}.hgLecI:after {font-family: 'nibdings';text-rendering: auto;-webkit-font-smoothing: antialiased;-moz-osx-font-smoothing: grayscale;vertical-align: middle;content: "\E035";}.sc-bwzfXH {}.sc-htpNat {}.sc-bxivhb {}.sc-ifAKCX {}.sc-EHOje {}.sc-bZQynM {}.sc-gzVnrw {}.sc-htoDjs {}</style>

<style type="text/css">@font-face {font-family: 'nibdings';font-weight: normal;font-style: normal;src: url('public/files/1f674a6cc2ba32b64a73b5218353732c.eot');src: url('public/files/1f674a6cc2ba32b64a73b5218353732c.eot?#iefix') format('eot'),  url('public/files/a9aafbe28cb97db40ecc4af90960ab6b.woff') format('woff'),  url('public/files/1dbf742e49e6d9cf99a74f84f99ccc8a.ttf') format('truetype'),  url('public/files/6780ecc884d7520b8977c6fed0d0d1ef.svg#nibdings') format('svg');}.sc-bdVaJa {}.hgLecI {display: inline-block;font-size: inherit;font-style: normal;line-height: 1;text-rendering: auto;-webkit-font-smoothing: antialiased;-moz-osx-font-smoothing: grayscale;vertical-align: middle;font-size: 48px;color: #009623;}.hgLecI:after {font-family: 'nibdings';text-rendering: auto;-webkit-font-smoothing: antialiased;-moz-osx-font-smoothing: grayscale;vertical-align: middle;content: "\E035";}.sc-bwzfXH {}.sc-htpNat {}.sc-bxivhb {}.sc-ifAKCX {}.sc-EHOje {}.sc-bZQynM {}.sc-gzVnrw {}.sc-htoDjs {}</style>
</head>
```

**Comment by bntzio** [comment]
I'm getting 3 <style> tags, I wonder why 🤔 in one I get my `injectGlobal` styles, on another one I get my other component styles (non-injectGlobal) and in the other one all mixed-up.

I think it's because of both the client-side and server-side css rendering, maybe.

**Comment by mxstbr** [comment]
Yep, this is currently the case but we'll fix it for the proper v2 release. See #386 and related issues for the ongoing discussions.
