### ISSUE TITLE
Style collisions when running multiple instances of styled-components

### ISSUE THREAD

**Issue by ryanheathers** [styled-components/styled-components#633]
I'm running into a serious issue (for my use-case) when using multiple instances of styled-components on a single page. I don't believe this is a styled-components bug per se, more like a current limitation that I would love to find a workaround for.

**Background:**
My React app is delivered as a third-party plugin that can be instantiated multiple times on a page. Each instance uses it own copy of styled-components.

When the page loads, styled-components populates the `<head>` with the `<style>` declarations for each instance. Importantly, styled-components does a few key things during that loading process:
- Sets the `<style>` tag order in `<head>` based on the order that the React apps were loaded. **This sets up a potential cascade between the apps.** Nothing can done about this step but it plays into the issue.
- Generates hashed classes by looking at the style rules and creating common hashes for blocks that share the same style rules. My understanding of that behavior is based on this thread: https://github.com/styled-components/styled-components/issues/167. ***The generated hashes are not unique per app, they appear to be shared across the page wherever that common set of style rules are used (provided that that DOM element uses styled-components of course).*** This is an especially big issue in my use-case because my plugins use common style sets that are not unique between apps.
- Populates empty class wrappers in the `<style>` tag for style rules that have not yet been generated. For example, I have a modal that is not yet rendered into the DOM on page load. Therefore styled-components does not generate the modal's styles on page load. Here's an example: 
```
.sc-ifAKCX {} <-- will be populated with style rules when my modal is opened
```

When I load up my page with two of my React apps running and then open the modal from the app that was loaded **first** on the page, I get a massive styling issue. This code block best illustrates the resulting issue:
```
Output from Chrome DevTools:

// Ooops! The default SVG styles from my SECOND app are overriding my first modal's style
.kSkIqR {
    color: inherit;
    fill: currentColor;
    width: inherit;
    height: inherit;
}

// SVG styles from my FIRST modal's styled-components
.kRvYQ {
    width: 15px;
    height: 15px;
    vertical-align: middle;
    pointer-events: none;
}

// default SVG styles that are applied on page load
// because an SVG is present in the DOM on page load
.kSkIqR { 
    color: inherit;
    fill: currentColor;
    width: inherit;
    height: inherit;
}
```

**Solutions**
One idea is to to have a way to, optionally, add a namespace to every styled-component's hash. Maybe this namespace could be set via the existing `theme` mechanism. That way each of my app's could set a unique identifier and all the shared styles would happily co-exist on the page.

I'm guessing I could also add some specificity boost to the "real" style blocks so that they overcome the default styling. But that is just awful and highly prone to bugs. Would love a different option.

Any other workarounds for this issue? It's currently a showstopper for my app and I'd love to hear any ideas.

**Comment by mxstbr** [comment]
This is an interesting use-case for sure. I can't think of a good solution right now, but I'll let this simmer in my brain and see what it cooks up :wink:

Maybe @geelen has an idea?

**Comment by wardpeet** [comment]
The problem here is that styled components doesn't generate it's own className depending on it's instance but than again it helps you debug styled components as well as each run triggers the same className.

Perhaps a static prop can be added to add an identifier (namespace) to the mix which is **sc-** by default.

Another option is to let your main application take care of the dependency and setup peer dependency for the plugins which is how you would do it when using a javascript bundler

**Comment by ryanheathers** [comment]
So far the only solution I've found for this is using the `&&` specificity hack. But it's not very scalable and prone to breaking. If a styled-component gets composed `n` layers deep, then it needs (n - 1) `&` selectors to have secure specificity. That's rough to maintain.

A namespacing solution would be amazing! I don't know enough of styled-component's internals yet to contribute a PR myself. Maybe in the future if no one is able to get to this.

>Another option is to let your main application take care of the dependency and setup peer dependency for the plugins which is how you would do it when using a javascript bundler

In my use case, I don't control the main application. Just the third-party plugins.

**Comment by philpl** [comment]
Updates are now in a new issue: https://github.com/styled-components/styled-components/issues/1032
