### ISSUE TITLE
Ability to normalize.css

### ISSUE THREAD

**Issue by garmjs** [styled-components/styled-components#64]
Congrats to Max and Glen! 🍻  styled components looks fantastic 🎉

What do you guys think if we add in API ability to [Normalize.css] (http://necolas.github.io/normalize.css/) maybe in injectGlobal .

**Comment by mxstbr** [comment]
I think that would unnecessarily boost package install size – if people want to use one of the many resets (reset.css, normalize.css, sanitize.css,...) they can easily do it themselves!

**Comment by garmjs** [comment]
Yes i agree!
