### ISSUE TITLE
[v2.0.0-12] Warning: Unknown prop `innerRef` on <div> tag

### ISSUE THREAD

**Issue by luisrudge** [styled-components/styled-components#641]
![image](https://cloud.githubusercontent.com/assets/941075/24590931/a9292f22-17cc-11e7-982a-5a197078c036.png)

> Warning: Unknown prop `innerRef` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop

**Comment by luisrudge** [comment]
this doesn't happen on `2.0.0-7`

**Comment by philpl** [comment]
It's currently being addresses in #639 and a regression after a refactor.

**Comment by luisrudge** [comment]
Alright, thanks! ❤️
