### ISSUE TITLE
Add TypeScript typings to v2

### ISSUE THREAD

**Issue by jupl** [styled-components/styled-components#646]
As discussed in Gitter, it sounds like typings are merged to master but not merged to v2.

**Comment by Igorbek** [comment]
ping @styled-components/typers

**Comment by seivan** [comment]
Any updates on this?

**Comment by patrick91** [comment]
I didn't have time to look at v2 yet, might do so in the weekend! I'll keep you posted :)

**Comment by Igorbek** [comment]
BTW, @patrick91 we could start with gathering all changes of API in v2 comparing to v1.

**Comment by philpl** [comment]
@Igorbek @patrick91 Maybe this problem will solve itself once we merge v2 back into master, which should be quite soon?

**Comment by seivan** [comment]
But V2 doesn't have any updated typings, so how would a merge back to master fix that?
Perhaps the definitions don't need to be updated?

**Comment by philpl** [comment]
It should be merged back now with the RC, but we'll need to update some things.
