### ISSUE TITLE
styled, 3rd party component, not working

### ISSUE THREAD

**Issue by klemieux** [styled-components/styled-components#647]
Style a custom made component loaded with import (or not) doesnt work.

Exemple: 

```JS
import React, { Component } from 'react';
import styled from 'styled-components';

function Test() {
  return <button>TEST BUTTON</button>;
}

const TestStyle = styled(Test)`
  color: red;
`;

export default class App extends Component {
  render() {
    return (
      <div>
        <TestStyle />
      </div>
    );
  }
}


```

doesn't change the color attribute at all. I know that if I had created the button with styled.button it would have worked. But all my components are already created or to complex to be dumb styled component. I need a way to wrap them with style(MyCustomComponent) to style style it

**Comment by k15a** [comment]
You need to pass down the className.

```JS
function Test(props) {
  return <button className={props.className}>TEST BUTTON</button>;
}
```
