### ISSUE TITLE
Optimize bundled size

### ISSUE THREAD

**Issue by ismay** [styled-components/styled-components#649]
I'm using styled-components, and am really happy with it. Currently I'm trying to get my app's bundle size down, and styled-components is among one of the bigger packages. When bundled with webpack, it's [90.6kB](https://travis-ci.org/ismay/ismaywolff.nl/builds/218441235#L496) minified (just for styled-components, including some webpack overhead).

When compared with the [167kB for a minified bundle](https://travis-ci.org/ismay/ismaywolff.nl/builds/218441235#L507) containing almost all my other vendor libs:

```
      'date-fns',
      'history',
      'load-script',
      'normalize.css',
      'normalizr',
      'react',
      'react-helmet',
      'react-dom',
      'react-medium-image-zoom',
      'react-redux',
      'react-router',
      'react-router-dom',
      'redux',
      'redux-thunk'
```

styled-components seems fairly heavy.

I still think it's worth it, but I'm wondering whether there's any known optimizations specific to styled-components for getting its bundled size down (outside of general stuff like gzipping, SSR, etc., which is of course not a styled-components specific issue). Any thoughts on this? Worth putting on the roadmap for a future version?

**Comment by k15a** [comment]
It's definitely on the roadmap for v2. We have a new parser which is much smaller and @philpl is currently developing a new babel-plugin which will remove the need of a run time parser completely. You can try is out with `npm install styled-components@next` and https://github.com/styled-components/babel-plugin-styled-components.

**Comment by ismay** [comment]
@k15a Great, that's good to hear! Will definitely try the v2 branch. Do you expect a lot of api changes for v2, compared to where it's at now? Because I might just switch my build over now if it works for me.

**Comment by k15a** [comment]
We expect that v2 will be backwards compatible for most of the apps.

**Comment by ismay** [comment]
@k15a , cool, thanks for the quick replies!

**Comment by ismay** [comment]
@k15a One final question. When checking out what makes up for styled-components' bundled size with Webpack Visualizer (https://chrisbateman.github.io/webpack-visualizer/) I get the following results:

styled-components-bundle total size:

![1](https://cloud.githubusercontent.com/assets/7355199/24710114/6a055832-1a1c-11e7-93fc-3e56ef9c56ff.png)

part of that bundle which actually contains styled-components:

![2](https://cloud.githubusercontent.com/assets/7355199/24710258/e6b05922-1a1c-11e7-91e1-b96acd7108a0.png)

remaining space usage of that bundle:

![3](https://cloud.githubusercontent.com/assets/7355199/24710265/eb403872-1a1c-11e7-884a-d27982b3b3fb.png)

Just to make sure, this isn't normal when bundling styled-components right? I assume react isn't a direct dependency. Any idea if this is related to styled-components? Because if not, I'm assuming that this is a webpack 2 bug (which should deduplicate react from this bundle, as it's already in a vendor bundle).

**Comment by k15a** [comment]
IIRC Webpack Visualizer is reporting the bundle sizes before any plugin is executed so nothing is minified or deduplicated here. You might checkout https://github.com/th0r/webpack-bundle-analyzer which is a similar tool but more accurate.

As far as I know React isn't bundled with styled-components so there shouldn't be any duplicate React code here.
