### ISSUE TITLE
Best practice for structuring

### ISSUE THREAD

**Issue by robbue** [styled-components/styled-components#650]
I really like styled-components, but on my current project I find myself using more time to create components/files, copying names and restructuring then actually creating styles. The project does not have a lot of reusable components because its a campaign site and not designed modular. Files are adding up to the hundres for a pretty small site and it's getting pretty time expensive to browse through all components, child-components, child-child-components etc.

@mxstbr gave an answer [here](https://stackoverflow.com/questions/42987939/styled-components-organization), but I'm looking to see if other people have successfully made components other ways without loosing too much control? Or if people deviates from the default in some cases.

I made an repo to try other structures: https://github.com/robbue/styled-components-structure

```
Default
  |-- Button.js
  |-- Header.js
  |-- Wrapper.js
  |-- index.js

MultipleComponentsOneStyleFile
  |-- Button.js
  |-- Header.js
  |-- Wrapper.js
  |-- styles.js
  |-- index.js

EverythingInOneFile
  |-- index.js
 
OneStyleFile
  |-- index.js
  |-- styles.js
```

**Comment by YasserKaddour** [comment]
I was using CSS Modules, and the feature that sold me to styled-components is collocation, meaning the style lives in the same file as the component. 

In your repo, I would only call `ModalBox` a component, the rest are only styles since they are not reused at all, and I would go with  `EverythingInOneFile`. 

However, in a real project `Button` would be a reusable component with some logic that would look something like this

```jsx
const StyledButton = styled.button`
  background: blue;
  color: {props => props.color};
`;

export default Button = ({ onClick, children, color }) => (
  <StyledButton color = {color} onClick = {onClick}>
      { children }
  </StyledButton>
)
```
This is a component collocated with its style and would be in a single file.

**Comment by j-jackson** [comment]
@YasserKaddour Does this approach scale well for larger applications? using bootstrap or bulma as an example, would you create a styled-component for everything (grid, columns etc)? 

My application is still fairly small but I already have a LOT of css inserted into the head and I'm wondering how this is going to look as the app grows.

**Comment by YasserKaddour** [comment]
@j-jackson For grid system and other collection of components you can regroupe them into one single file like `grid-styled` [does it](https://github.com/jxnblk/grid-styled/blob/master/src/Grid.js).
