### ISSUE TITLE
Alternative CSS API: objects

### ISSUE THREAD

**Issue by wmertens** [styled-components/styled-components#651]
[Glamourous](https://medium.com/@kentcdodds/introducing-glamorous-fb3c9f4ed20e) got me thinking, because the API looks like this: `glamorous.div({color: 'red'}, p => ({color: p.happy && 'green'}))`

How about something similar for S-C?

```js
import {styled, css} from 'styled'
const Alert = styled.div(
  css`color: red;`,  // static
  p => css`color: ${p.happy && 'green'};`,  // dynamic with string interpolation
  {'.whyNotBoth': {color: 'yellow'}}, // objects
  css`width: ${p => p.wide && '100%'};`, // dynamic with thunking
)
```

in other words, being able to provide multiple css sections with thunking in them and maybe even thunking in the thunking. Each section can be `css` output, a function taking props and returning anything a section can handle, and plain JS CSS objects.

If the `{styled}` export (as opposed to the `default` one) doesn't support calling as a tagged string, then the css parsing becomes optional and could be shaking out during build, resulting in parser-less S-C. The babel plugin could presumably follow functions and pre-run `css`, so that all that is left are objects.

This would make S-C super flexible with lots of optimization opportunities. (the dynamic with string interpolation looks like the toughest case though)

**Comment by mxstbr** [comment]
I'd prefer not to introduce another API that's just a different way of doing things, but doesn't enable any new use cases. In case it turns out there's a huge interest for this API I'm happy to revisit it in the future, but for now let's close this out to trim our issue tracker of some noise.
