### ISSUE TITLE
[v2] post-processing extraction: keyframe animation name error 

### ISSUE THREAD

**Issue by mschipperheyn** [styled-components/styled-components#653]
I'm experimenting with the new post processing extraction and SSR and I'm noticing some errors.

Without extraction

     animation: slide 15s linear infinite;

    @keyframes slide{ [...] }

With extraction
     animation: .idYUMSslide 15s linear infinite;

    @keyframes .idYUMSslide{ [...] }
babel

      ["styled-components", {
                    'ssr' : true,
                    'preprocess': true,
                    'displayName': false,
                    'minify': false
      }]

I'm assuming the dot is illegal

**Comment by thysultan** [comment]
Interesting, incase your passing this through stylis maybe `.idYUMS` is being passed as ` .idYUMS` 
 @philpl, though v2.0.2 now trims selectors if they have whitespace leading.

**Comment by philpl** [comment]
Hey, I'll need some more material to debug this :) can you post some raw js files and their babel transpiler counterparts, please?

**Comment by mschipperheyn** [comment]
I will set up something

**Comment by mxstbr** [comment]
Closing since there was no response, but please feel free to reopen with a reproduction!
