### ISSUE TITLE
[v2] post-processing extraction: all manual classnames are hexified

### ISSUE THREAD

**Issue by mschipperheyn** [styled-components/styled-components#654]
I'm experimenting with the new post processing extraction and SSR and I'm noticing some errors.

classNames that I manually add through the `classnames` library are all converted to hex values.

babel

  ["styled-components", {
                'ssr' : true,
                'preprocess': true,
                'displayName': false,
                'minify': false
  }]

**Comment by philpl** [comment]
Since we are just joining all classNames and don't pass them through any generator again, I'll need a sample for this as well to reproduce it 😉

**Comment by mxstbr** [comment]
No response, so I'll close this for now. If this is still reproducible please submit a reproduction repo and we'll take a look at the issue!
