### ISSUE TITLE
Angular.js causes styled-components to break on IE 11

### ISSUE THREAD

**Issue by dfrankland** [styled-components/styled-components#657]
## Version
1.4.4 (maybe a lot older too)

## Reproduction

Webpackbin doesn't work on IE 11... So here's a repo!
<https://github.com/dfrankland/styled-components-angular-ie-11-conflict>

## Steps to reproduce

Follow steps in linked repo.

## Expected Behavior

Work like normal.

## Actual Behavior

No CSS rules are applied to the style element.

## Why?

Angular will recompile all the individual DOM elements including those in the head. Normally, on Chrome and other browsers this isn't an issue, but on IE 11 this causes text nodes to lose their `parentNode`. This could occur due to anything though, it doesn't have to be Angular. The more longwinded explanation:

1.  Style elements and text nodes get inserted in [`ComponentStyle`](https://github.com/styled-components/styled-components/blob/master/src/models/ComponentStyle.js#L25)

2.  Afterwards, anything could mutate the DOM, such as Angular, causing issues later

3.  A styled component is ready to render so [`generateAndInjectStyles`](https://github.com/styled-components/styled-components/blob/master/src/models/ComponentStyle.js#L34) inside of [`ComponentStyle`](https://github.com/styled-components/styled-components/blob/master/src/models/ComponentStyle.js#L25) is called

4.  [`appendRule`](https://github.com/styled-components/styled-components/blob/master/src/vendor/glamor/sheet.js#L127) inside the [Glamor sheet](https://github.com/styled-components/styled-components/blob/master/src/vendor/glamor/sheet.js) tries to mutate a text node, but it has already been removed from the DOM, thus no styles are applied to the style tags created in step 1

## Fix

I propose to move the appending of text nodes to the style element DOM only once the component is ready to render, rather than doing it preemptively.

https://github.com/styled-components/styled-components/blob/master/src/vendor/glamor/sheet.js#L125
```diff
const textNode = document.createTextNode(rule)
- last(this.tags).appendChild(textNode)
- insertedRule = { textNode, appendRule: newCss => textNode.appendData(newCss)}
+ insertedRule = {
+   textNode,
+   appendRule: newCss => textNode.appendData(newCss),
+   appendNode: () => last(this.tags).appendChild(textNode),
+ };
```

https://github.com/styled-components/styled-components/blob/master/src/models/ComponentStyle.js#L39

```diff
const selector = nameGenerator(hash)
inserted[hash] = selector
const root = parse(`.${selector} { ${flatCSS} }`)
postcssNested(root)
autoprefix(root)
this.insertedRule.appendRule(root.toResult().css)
+ this.insertedRule.appendNode()
```

**Comment by garretruh** [comment]
Seeing the same issue with styled-components@1.3.0. Any components on a page with Angular (v1.6.4 in this case) that are rendered after Angular has initialized don't get their styles injected. The included patch does appear to resolve the issue.

**Comment by philpl** [comment]
We don't want to modify the vendored glamor module, however we can still defer the injection of the stylesheet. It's fairly simple, but is that stuff we want, @mxstbr @geelen?

**Comment by mxstbr** [comment]
This is @geelen expertise, there's a reason why we do it exactly the way we do.

I don't want to change that part of the code without having benchmarked it extensively to make sure we don't get less performant and I need @geelen to confirm this'll work so we avoid subtle ordering bugs like #1. (which are a pain)

**Comment by philpl** [comment]
@mxstbr Ah, yep, you're right. If we defer injection to the rendering, then the order of CSS is going to change to the order of rendering, not the order of imports. Looks like this is not sth we'll fix anytime soon :/

**Comment by dfrankland** [comment]
@mxstbr @philpl this is definitely true. Maybe the best option is just to do a check for if the `textNode` has lost its `parentNode` and throw warnings 🤔

**Comment by philpl** [comment]
It's not really sth that is a bug on our end, or sth that we can affect or fix unfortunately

**Comment by jasonalmaturner** [comment]
I've had this same problem with using styled-components in the angular/react app I'm working on. I found this snippet by @dfrankland that fixed my problem.

```javascript
angular.element(document).ready(() => {
  const bootStrapElement = (
    // BAD! Recompiles everything causing IE 11 to not work
    document

    // GOOD! Does not mess with the <head>
    // document.body
  );
  angular.bootstrap(bootStrapElement, ['blah'], {});
});
```

https://github.com/dfrankland/styled-components-angular-ie-11-conflict/blob/master/src/main.js

**Comment by HashemKhalifa** [comment]
@jasonalmaturner  Would u tell me what u changed?!

**Comment by mxstbr** [comment]
```diff
- angular.bootstrap(document, ['blah'], {});
+ angular.bootstrap(document.body, ['blah'], {});
```

**Comment by HashemKhalifa** [comment]
actually, I'm trying to fix my issue using this solution but I'm using react2angular to handle react components separately what I have to follow?!

**Comment by dfrankland** [comment]
@HashemKhalifa, using [`react2angular`][r2a] doesn't really affect the way the fix is implemented.

[Following the `react2angular` example][r2a example], you only need to add one line:
```diff
import { react2angular } from 'react2angular'

angular
  .module('myModule', [])
  .component('myComponent', react2angular(MyComponent, ['fooBar', 'baz']))
+ .bootstrap(document.body, ['blah'], {});
```

[r2a]:https://github.com/coatue-oss/react2angular
[r2a example]: https://github.com/coatue-oss/react2angular#2-expose-it-to-angular

**Comment by HashemKhalifa** [comment]
@dfrankland Thanks for your reply, .element here refer to what? 
this is my example but it didn't work.
`.component('hotelSearchMapComponent', react2angular(hotelSearchMapComponent, ['lat', 'lng', 'zoom', 'hotels', 'symbol', 'rate', 'from', 'to', 'onSelectHotel']))
  .element(document).ready(() => angular.bootstrap(document.body, [MODULE_NAME], {}))`

**Comment by HashemKhalifa** [comment]
getting these errors
![screen shot 2017-08-29 at 12 01 27 pm](https://user-images.githubusercontent.com/3355748/29810691-dbe73f8a-8cb1-11e7-9534-e2bef24a390d.png)
![screen shot 2017-08-29 at 12 01 36 pm](https://user-images.githubusercontent.com/3355748/29810690-dbe2001a-8cb1-11e7-954f-8b2b5a63ff29.png)

**Comment by philpl** [comment]
I think at this point you should consider opening an issue on their repo instead :wink:

**Comment by adamchenwei** [comment]
Hey everyone, someone even opened a repo regarding it, that when styled-component run with AngularJS in IE11, it breaks.
https://github.com/dfrankland/styled-components-angular-ie-11-conflict

Any fixes atm? really need it, super sad it happens...

**Comment by philpl** [comment]
@adamchenwei To quote myself:

> It's not really sth that is a bug on our end, or sth that we can affect or fix unfortunately

I don't really have time to look at it in detail, but the proposed fix confirmed it for me. If someone could explain why it happens and it turns out that it's a problem with our codebase, then we'd be able to actually fix it.

**Comment by byrekt** [comment]
Just a heads-up. If you use auto-bootstrapping with `ng-app` on the `html` tag of your index.html, you can try moving `ng-app` to the `body` tag. That resolved it for me.
