### ISSUE TITLE
Think about non-JSX users

### ISSUE THREAD

**Issue by jlongster** [styled-components/styled-components#66]
I don't use JSX, but libraries like [glamor](https://github.com/threepointone/glamor) are still a pleasure to use:

``` js
dom.div(
  { ...style({ border: "1px solid black" }) },
  children
)
```

The problem with styled-components is that is forces you to always create new components. So now I have to do something like this:

``` js
const Title = React.createFactory(styled.div`border: 1px solid black`);
Title({}, children);
```

Obviously not ideal. I don't know if you want to care about this or not, but it's definitely a blocker for me to use this library.

An option would be to re-export all of the tags, and have them automatically wrap the result in a `createFactory`. So I would import `styled-components/wrapped` or something instead, and I wouldn't have to use `createFactory`.

**Comment by jlongster** [comment]
fwiw, don't do this *just* for me, as I'm likely to stick to glamor for the time being. Let's see if there are any other non-JSX users. I'm still surprised there aren't more of them.

**Comment by geelen** [comment]
I think this would actually be pretty straightforward, right? This is where we define all our shorthands:

https://github.com/styled-components/styled-components/blob/master/src/constructors/styled.js

The important thing is here:

```js
  const styled = (tag: Target) =>
    (strings: Array<string>, ...interpolations: Array<Interpolation>) =>
      styledComponent(tag, css(strings, ...interpolations))
```

If we made line 3 return `React.createFactory(styledComponent(tag, css(strings, ...interpolations)))` wouldn't that be enough? Wanna fork it and give it a go, see if you end up liking use it?

**Comment by poke** [comment]
I think @jlongster would want to *avoid* having to call `React.createFactory` here (directly or indirectly). Something like this would be nice:

```
dom.div(css`
    border: 1px solid black;
`, children)
```

Or maybe a different syntax to allow passing other props.

But I can see this quickly become a performance problem. If the component style is created within a `render` function, it would probably become rather difficult to enable reuse of the style definitions. So I guess you would still want to define the components outside.

**Comment by geelen** [comment]
Why would calling `React.createFactory` be a bad thing if it was hidden inside the library? @jlongster maybe you could weigh in here?

**Comment by mxstbr** [comment]
Now that @jlongster [made prettier to help him write JSX for `styled-components`](https://twitter.com/jlongster/status/824733787397455872) and nobody else has asked for this use case I'll close this issue!
