### ISSUE TITLE
[TypeScript] Property rules does not exist

### ISSUE THREAD

**Issue by jupl** [styled-components/styled-components#669]
In TypeScript the following cannot be written due to lack of `rules` property:

```ts
const rules = styleSheet.rules().map(rule => rule.cssText).join('\n')
```

**Comment by Igorbek** [comment]
`StyleSheet` is not defined in TypeScript.

**Comment by mxstbr** [comment]
This doesn't exist in v2 anymore, so you can't do this anyway. I'm going to close this since it's an outdated issue!
