### ISSUE TITLE
Extending a styled component

### ISSUE THREAD

**Issue by sutkh** [styled-components/styled-components#672]
I have a question about the intended inheritance pattern for StyledComponents.

Say I have:
```
class MenuItem extends React.Component {
  render() { return <foo />; }
}
const StyledMenuItem = styled(MenuItem)`
  height: 10px;
`
```
I'd like to extend StyledMenuItem with a subclass, let's say Settings
```
class Settings extends StyledMenuItem {
  render() { return <bar />; }
}
const StyledSettings = styled(Settings)`
  width: 10px;
`
```

But this pattern doesn't seem to be functional, the render method of MenuItem is getting called rather than Settings. What's the best practice for extending React methods as well as styling? Right now it seems like I need to do it in two steps, extending MenuItem to Settings, and then applying the MenuItem and Settings styles.

**Comment by k15a** [comment]
You need to pass the className down to the component.

**Comment by sutkh** [comment]
The issue isn't that the styles aren't getting applied correctly, it's that the incorrect render method is being called. I oversimplified my example, I will modify it to include passing in the className as a prop.

**Comment by sutkh** [comment]
This seems like the shortest way to do this currently:
```
const MenuItemDiv = styled.div`
  height: 10px;
`;
class MenuItem extends React.Component {
  render() { return <MenuItemDiv />; }
}

const SettingsDiv = styled(MenuItemDiv)`
  width: 10px;
`;

class Settings extends MenuItem {
  render() { return <SettingsDiv />; }
}
```

**Comment by k15a** [comment]
Inheritance isn't a good pattern in React. Read more about that here: https://facebook.github.io/react/docs/composition-vs-inheritance.html

Personally I would rewrite your solution like this:

```JS
const MenuItemWrapper = styled.div`
  height: 10px;
`;

class MenuItem extends React.Component {
    render() {
        return (
            <MenuItemWrapper>
                {this.props.children}
            </MenuItemWrapper>
        );
    }
}

const SettingsWrapper = styled.div`
  width: 500px;
`;

class Settings extends React.Component {
    render() {
        return (
            <SettingsWrapper>
                {this.props.settings.map(setting => (
                    <MenuItem>
                        {setting}
                    </MenuItem>
                ))}
            </SettingsWrapper>
        );
    }
}
```

Hopefully that's what you want to accomplish ;)

**Comment by sutkh** [comment]
That's helpful feedback, thanks for the advice. Time to do a little bit of refactoring
