### ISSUE TITLE
[v2] classname ordering issue when using styled(Parent)

### ISSUE THREAD

**Issue by neilcarpenter** [styled-components/styled-components#676]
SC version 2.0.0-14

[This commit](https://github.com/neilcarpenter/styled-components/commit/2098688b832a7572533819aed1ce72d7db243276) on my fork make the necessary changes to `example/index.html` to reproduce the issue.

Seeing #518 I understand that there is now another way to extend styled components, but it's my understanding that `NewComponent = styled(Parent)` should still work?

The issue seems to be that the classnames are being injected in the incorrect order. Note this only affects the production build, so presumably something to do with the different stylesheet insertion logic between development / production builds.

**Comment by philpl** [comment]
I think my worst fear has been confirmed 😆  

https://github.com/styled-components/styled-components/issues/583#issuecomment-292986099

> I think unfortunately this might be a regression, that I've accidentally put in. We might want to build up more unit tests around rule ordering https://github.com/styled-components/styled-components/blob/v2/src/models/ComponentStyle.js#L27

Let me fix this in a few minutes ;)

**Comment by philpl** [comment]
@k15a https://github.com/styled-components/styled-components/pull/678

**Comment by geelen** [comment]
@neilcarpenter released styled-components@2.0.0-15 with this fix. Thanks for the quick fix, @philpl
