### ISSUE TITLE
Bundle Size

### ISSUE THREAD

**Issue by STRML** [styled-components/styled-components#68]
### Progress

|      | Bare | 1.0.0 | 1.0.3 |
|------|------|-------|-------|
| Size | 90kB | 1.1MB | 381kB |

### Original Issue

As a test, I integrated the (very minimal) CSS we use in `react-resizable` for use with `styled-components`.

https://github.com/STRML/react-resizable/tree/styled-components

This increases the bundle size from 90kB to 1.1MB. 

Is this intended for use in libraries, or is its goal more toward application use with an eventual extraction step to keep it out of the runtime?

**Comment by wmertens** [comment]
Would it be possible to generate everything at compile time? Using a Babel plugin that converts the tagged string call with just the calls needed to add the style?

**Comment by STRML** [comment]
https://github.com/styled-components/styled-components/commit/f624c4f857d54cb5f4e3ec24699575cf92c60d9b seems to have done some good work. Bundle size is down:

|      | Bare | 1.0.0 | 1.0.3 |
|------|------|-------|-------|
| Size | 90kB | 1.1MB | 381kB |

**Comment by mxstbr** [comment]
Yes, we messed up some dependencies, thankfully @threepointone helped us track down the issue. Bringing the size down further and writing that babel plugin (see #59) will be the main areas of focus for the coming time!

(Also, thanks for those numbers, very helpful @STRML!)

**Comment by STRML** [comment]
Mind keeping this open as a meta-issue for tracking the size? I think that'd be helpful to track progress.

**Comment by mxstbr** [comment]
Sure, sounds like a good idea!

**Comment by mxstbr** [comment]
Current status of the UMD build:

<img width="1668" alt="screen shot 2016-10-15 at 09 08 50" src="https://cloud.githubusercontent.com/assets/7525670/19408166/222fd830-92b7-11e6-8f47-7730ece6dd75.png">

Can't see any quick wins anymore, I think this is as small as we can go right now. 50% is PostCSS, let's see if #59 can do something about that!

**Comment by mxstbr** [comment]
As of 1.0.6 with #96, we've gotten an even smaller UMD build and a huge parsing performance jump! 

> The UMD build is 13% smaller (20,549 bytes gzipped down from 23,553) and parses roughly 60% quicker (~8ms in Chrome down from ~20ms, similar increase in Safari, less in Firefox)
