### ISSUE TITLE
Flow error when overriding styles (class type: existential)

### ISSUE THREAD

**Issue by esbenp** [styled-components/styled-components#680]
## Version
1.4.4

## Reproduction
```JS
const OverriddenComponent = styled(Component)`

`
```

## Steps to reproduce

`flow status`

## Expected Behavior

Not sure

## Actual Behavior

```
Creates flow error `class type: existential. This type is incompatible with the expected param type of
 31:     (baseComponent: React$Component<*, * , *>): StyledComponent,`
```

=== 

Okay, so when I override a component I get the error described above. I am assuming you are aware of this since the type test expects an error for a similar component (https://github.com/flowtype/flow-typed/blob/master/definitions/npm/styled-components_v1.4.x/test_styled-components_v1.4.x.js#L41)

I am unsure if there already was an issue made (I could not find it) or if this is expected behaviour? But I thought maybe this would be valuable to people that experience same error to document current workarounds etc.

I am assuming for now I have to add an annotation to ignore the component?

**Comment by relekang** [comment]
cc @styled-components/typers 

>Okay, so when I override a component I get the error described above. I am assuming you are aware of this since the type test expects an error for a similar component (https://github.com/flowtype/flow-typed/blob/master/definitions/npm/styled-components_v1.4.x/test_styled-components_v1.4.x.js#L41)

That expected error is because the variable sent in is a number.

@esbenp Do you have any more info about how `Component` is created?

**Comment by AntonPuko** [comment]
@relekang Hi, I have the same Flow error, with this;

```
const AffixText = styled.div`
  color: ${({ theme }: Object): string => theme.palette.alternateTextColor};
  font-weight: bold;
  text-transform: uppercase;  
`;

const TimeText = styled(AffixText)`
  font-size: 1.8em;
`;
```


the error: 
```
const TimeText = styled(AffixText)`
                             ^^^^^^^^^ class type: C. This type is incompatible with the expected param type of
 31:     (baseComponent: React$Component<*, * , *>): StyledComponent,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^ React$Component. See lib: flow-typed/npm/styled-components_v1.4.x.js:31

```

**Comment by onehorsetown** [comment]
I see the same thing in 2.0.0-15 (w/ the 1.4.x flowtype definitions; did not see any 2.0 type definitions).  Just a plain stateless React component throws a Flowtype error.

```
const Foo = () => <i>Hello</i>;

const Bar = styled(Foo)`
  color: red
`;
```

> arrow function This type is incompatible with the expected param type of React$Component

If I turn Foo into a "real" (AKA extends React.Component), I see the same error:

```
class Foo extends React.Component {
  render() {
    return <i>hello</i>;
  }
}

const Bar = styled(Foo)`
  color: red
`;
```

**Comment by relekang** [comment]
This should be fixed by https://github.com/flowtype/flow-typed/pull/806. If you have the time, please try it out.

**Comment by relekang** [comment]
Closing this as the flow-typed pr was merged.

**Comment by onehorsetown** [comment]
@relekang - Perfect.  Fixed!
