### ISSUE TITLE
Array.from is not polyfilled, but IE doesn't support it

### ISSUE THREAD

**Issue by eastwood** [styled-components/styled-components#684]
## Version
1.0.5

## Reproduction

```
$ npm install styled-components
$ grep -r Array\.from node_modules/styled-components/dist
```

## Question
Array.from is not supported in IE. Without poly-fills, applications importing `styled-components` will have to implement polyfills in order to support IE. Is this intended behaviour, or can we update the `babel-preset-env`?

**Comment by philpl** [comment]
This seems to be an issue on `v2` as well, even if it's using `Array.from`. Seems like we have to research this: https://unpkg.com/styled-components@2.0.0-15/dist/styled-components.es.js

Looks like we'll have to adjust `babel-preset-env`'s settings:

http://kangax.github.io/compat-table/es6/#test-Array_static_methods

**Comment by eastwood** [comment]
That's correct. I can take a look at this if everyone is happy :) It will just be a `babel-preset-env` change yep :)

**Comment by philpl** [comment]
@eastwood That'd be awesome :smile: Make sure to do the change on both `master` and the `v2` branch, and in `.babelrc` *and* `rollup.config.js`. Thanks a lot! 💟

**Comment by probablyup** [comment]
Alternatively, you can use `Array.prototype.slice.call(arrayLikeThing)`, which has very good support and should be fast enough.

**Comment by philpl** [comment]
In #717 I switched over to `babel-preset-env` in loose mode and noticed that only a single occurrence of `Array.from` was left. So I replaced it, and that PR should actually fix this
