### ISSUE TITLE
flow definition for keyframes is wrong (?)

### ISSUE THREAD

**Issue by pattard** [styled-components/styled-components#686]
The libdef in `flow-typed` has

```js
keyframes: (nameGenerator: NameGenerator) => (strings: Array<string>, ...interpolations: Array<Interpolation>) => string,
```
which is incorrect. At least if `keyframes` is used in the way it is in the Readme.

This

```js
keyframes: (strings: Array<string>, ...interpolations: Array<Interpolation>) => string,
```
looks correct and the code typechecks. I can add a PR to flow-typed but just wanted to see if I'm correct

**Comment by fsp** [comment]
Your definition fixes the issue for me. Thanks!

**Comment by relekang** [comment]
@pattard Looks like your suggested change is correct 👍

**Comment by jameskraus** [comment]
This issue can be closed now
