### ISSUE TITLE
Support Sublime Text syntax highlighting

### ISSUE THREAD

**Issue by Cap32** [styled-components/styled-components#69]
I want to subscribe when will this awesome library support Sublime Text syntax highlighting. 🙃

**Comment by mxstbr** [comment]
I will try adding support for it, but I'm not very well versed in syntax highlighting stuff so if somebody wants to lend a hand I'd much appreciate it!

**Comment by mxstbr** [comment]
There is now [a PR](https://github.com/babel/babel-sublime/pull/289) by @garetmckinley to add `styled-components` support to `babel-sublime`!

**Comment by Cap32** [comment]
Thank you, @mxstbr !  I'm going to use `styled-components` now! 👍🏿
