### ISSUE TITLE
Highlight unused components

### ISSUE THREAD

**Issue by mschipperheyn** [styled-components/styled-components#690]
I find that the number of components I use can increase quite a bit with more complex layouts and sometimes components become "unused" when I change something. I would like to have a visual indication (I use Atom) for components that are unused. Is there an Atom plugin that does that?

**Comment by k15a** [comment]
ESLint has an option where you can see unused variables. You can use that for components as well.
http://eslint.org/docs/rules/no-unused-vars and https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-uses-vars.md

**Comment by gargantuan** [comment]
Maybe I'm missing something, but I think @mschipperheyn is looking for something that highlights unused components in his project. 

If you're using webpack, this might work for you
https://github.com/tomchentw/unused-files-webpack-plugin

**Comment by mschipperheyn** [comment]
I was thinking more something visual. Like I used to have using Eclipse for Java development. It gives a yellow underline under unused members

**Comment by geelen** [comment]
I use WebStorm and it supports this out of the box. Definitely worth trying
out, imo.

**Comment by jzimmek** [comment]
I am using lint-eslint package and eslint-plugin-react to get this in my atom:

![bildschirmfoto 2017-04-14 um 13 31 15](https://cloud.githubusercontent.com/assets/40382/25042275/fdd77846-2116-11e7-9b5f-5ae8f74624b1.png)

Works for vanilla JS as well as react / styled-components
