### ISSUE TITLE
adapting based on props

### ISSUE THREAD

**Issue by geddski** [styled-components/styled-components#693]
Adapting a styled-component based on props creates a brand new component each time, so you only get `componentDidMount` and zero `componentDidUpdate` events for all descendants of the style. This means you can't optimize any parts of your app using `shouldComponentUpdate` if you use dynamic styles. Is there a way to do this without sacrificing React's primary optimization path?

**Comment by k15a** [comment]
Could you please post an example?

**Comment by philpl** [comment]
As you can see in the implementation, once you create a StyledComponent it is not recreated. It receives new props and recomputes the CSS, checking whether the result changed, and rerenders with a new className.

https://github.com/styled-components/styled-components/blob/master/src/models/StyledComponent.js

If you would like to prevent unnecessary rerenders you should do that at a higher component thstbpasses down your props to a styled component eventually, further down the tree.

If you need more help, feel free to post examples / questions here, or on Gitter. I'm currently rewriting the documentation and turning them into a website. Do you think a section on optimisations would help you?

**Comment by geddski** [comment]
Ahh I see what I was missing, that you need a function where props gets passed in as the first argument. I didn't pick up on that so I was creating the styled components inside of a parent component's render() function, which recreates them every time. 

Maybe the docs could spell this out so other noobs don't miss it.
