### ISSUE TITLE
babel-plugin-flow-react-proptypes still cause React 15.5 PropTypes deprecated warning

### ISSUE THREAD

**Issue by JYPark88** [styled-components/styled-components#694]
babel-plugin-flow-react-proptypes still cause React 15.5 PropTypes deprecated warning.

`import type { Interpolation } from '../types'`

transpiled to 

`var babelPluginFlowReactPropTypes_proptype_Interpolation = require('../types').babelPluginFlowReactPropTypes_proptype_Interpolation || require('react').PropTypes.any;`

**Comment by ismay** [comment]
I'm also still encountering prop-types warnings after adding styled-components. The babel-plugin-flow-react-proptypes package has fixed their prop-types usage in the 1.0.0 release:

https://github.com/brigand/babel-plugin-flow-react-proptypes/commit/192e12895759917898179ad7520157021d5e91fe

**Comment by ismay** [comment]
Submitted a pr. Not sure whether this'll break things, but this way we can get the process started.

**Comment by luftywiranda13** [comment]
![screen shot 2017-04-15 at 09 24 50](https://cloud.githubusercontent.com/assets/22868432/25060051/c39e8fa0-21bd-11e7-8ce6-fd74322d6596.png)

Just upgrade to **styled-components v1.4.5**
But, the **devtools console still gives me warning**

**Comment by ismay** [comment]
For me 1.4.5 fixes the devtools console warning, but still logs warnings when running my jest tests on the command line:

<img width="959" alt="screen shot 2017-04-15 at 09 23 05" src="https://cloud.githubusercontent.com/assets/7355199/25061737/2e1e9330-21bd-11e7-9362-e5f6e2839f1b.png">

PR #683 fixes those warnings.

**Comment by luftywiranda13** [comment]
hey @mxstbr @geelen,
this is **still an issue**

I just tried to do a **fresh install** of create-react-app
then install and import styled-components **(v1.4.5)** in App.js

the **devtools console** still logs the **proptypes warning**
the **terminal** also still logs the warning everytime I run a test

**Comment by ismay** [comment]
It's been fixed:

v1: https://github.com/styled-components/styled-components/commit/769be58e8558dd8d1bbbf3e4c5d3d93e802ebff0
v2: https://github.com/styled-components/styled-components/commit/9e7ce0e9881a144466a8cac85c5447973e81fe17

Just needs to be released on npm
