### ISSUE TITLE
injectGlobal does not vendor prefix

### ISSUE THREAD

**Issue by JuHwon** [styled-components/styled-components#699]
Does it have a reason why styles applied with injectGlobal have no auto vendor prefixing?
I created an example which shows the missing `appearance` vendor prefix.

## Version
1.4.5

## Reproduction
https://codesandbox.io/s/L90KWkW8A

## Expected Behavior
vendor prefixes at styled injected with injectGlobal

## Actual Behavior
vendor prefixes are not applied to styles applied with injectGlobal

**Comment by philpl** [comment]
It seems that the GlobalStyle model is missing its call to autoprefixing. For now you should be fine with v2 btw, but I'll push a hotfix.

I'm wondering how this went unnoticed for so long

**Comment by philpl** [comment]
I don't currently have an environment to test this. Does this fix your issue? https://github.com/styled-components/styled-components/pull/702

**Comment by cpsubrian** [comment]
@philpl :wink: https://github.com/styled-components/styled-components/issues/612#issuecomment-289527419

**Comment by philpl** [comment]
@cpsubrian I think you're confusing v1 and v2 ;) this stuff will never support themes, but autoprefixing should work

**Comment by cpsubrian** [comment]
@philpl hehe, just poking fun about the auto prefixing not working. Carry on :smile:

**Comment by cpsubrian** [comment]
@philpl Just out of curiosity, how would you do themed styles on html/body?

**Comment by k15a** [comment]
@cpsubrian A pretty simple solution would be:

```JS
import React from 'react'
import { injectGlobal, withTheme, ThemeProvider } from 'styled-components'

const GlobalStyles = ({ theme }) => {
    injectGlobal`
        // Use the ${theme} here
    `

    return null
}

const Main = () => <div>Hello World</div>

const App = () => (
    <ThemeProvider theme={yourTheme}>
        <div>
            <GlobalStyles />
            <Main />
        </div>
    </ThemeProvider>
)

export default App
```

**Comment by philpl** [comment]
@k15a That wouldn't work well, since the `injectGlobal` styles accumulate and are never deleted.

@cpsubrian Generally, I wouldn't even think about putting a theme on html/body :wink: It's possible, but at the same time it's totally sufficient to theme/style the highest React components, you have control over.

**Comment by k15a** [comment]
@philpl Yeah you shouldn't use this method if you're changing your theme frequently. But IMHO it's totally fine when you only change it few times at runtime.

**Comment by cpsubrian** [comment]
Thanks for the ideas all. @philpl Yeah I totally get that global theming isn't really a forte of `styled-components`, but in this case I'm trying to literally work out how to do a live-editable 'site' theme and there are a handful of styling props that need to be set on global elements (mainly background). Its possible I could sort something out with html,body,root just being height 100% and the styling getting applied to react containers, but that sometimes leads to weird bugs and loading jank.

**Comment by cpsubrian** [comment]
Also, sorry to hijack the thread, I should really move this convo to reactiflux or something.

**Comment by mxstbr** [comment]
@cpsubrian We have a community on Spectrum that's perfect for these kinds of questions! https://spectrum.chat/styled-components

I'm going to close this issue since there hasn't been any updates in a while, but feel free to reopen if you're still unsure how to do this!

**Comment by saadq** [comment]
I thought it might be better to comment here rather than raising a new issue. Was this supposed to be fixed in v2? I still seem to have issues with prefixing working with the following:

```js
import { injectGlobal } from 'styled-components'

injectGlobal`
  ::selection {
    background: blue;
    color: white;
  }
`
```

This doesn't seem to work in Firefox, unless I do this:

```js
import { injectGlobal } from 'styled-components'

injectGlobal`
  ::selection {
    background: blue;
    color: white;
  }

  ::-moz-selection {
    background: blue;
    color: white;
  }
`
```
