### ISSUE TITLE
What is the font use in the IDE screenshots?

### ISSUE THREAD

**Issue by AlainPilon** [styled-components/styled-components#70]
Sorry for asking a (near) non project related question, but what is the gorgeous font use on all the screenshots? And I am sure that I am not the only one wondering! thx

**Comment by tizmagik** [comment]
I believe it's [Operator Mono](http://www.typography.com/fonts/operator/styles/operatormonoscreensmart), if I'm not mistaken?

**Comment by AlainPilon** [comment]
oh god, a __200$__ font! 

Wonder if I can convince my boss that it will increase, if not my productivity, my enjoyment at the office!

**Comment by AlainPilon** [comment]
Found this as a free alternative: https://medium.com/@docodemore/an-alternative-to-operator-mono-font-6e5d040e1c7e#.iojpp1215

**Comment by mxstbr** [comment]
That's my editor, and it is indeed Operator Mono. I got it mostly because I take many screenshots of code and the italics impress people 😉

That being said, if you don't take screenshots often Fira Code is a great font with beautiful ligatures!
