### ISSUE TITLE
What is the best practice for styling heading?

### ISSUE THREAD

**Issue by luftywiranda13** [styled-components/styled-components#701]
Hi guys, been trying **styled-components** for a few days. **Soooo great!**

BTW, I have something to ask here,
Is this kind code is a good approach?

```
// @flow

import { rem } from 'polished';
import styled, { css } from 'styled-components';

const baseStyles = css`
  color: ${props => props.theme.colors.black || '#222'};
  line-height: 1.2;
`;

const H1 = styled.h1`
  ${baseStyles}
  font-size: ${rem('33px')};
`;

const H2 = styled.h2`
  ${baseStyles};
  font-size: ${rem('28px')};
`;

const H3 = styled.h3`
  ${baseStyles};
  font-size: ${rem('23px')};
`;

const H4 = styled.h4`
  ${baseStyles};
  font-size: ${rem('19px')};
`;

const Heading = {
  H1,
  H2,
  H3,
  H4,
};

module.exports = Heading;

```

**Comment by philpl** [comment]
Looks good!

I myself would give these components more meaningful names. Let's say `h1` is only used in certain situations, like the title of the site. In this case I'd call it `Title`. Or `h2` is always the heading of some text. Then I'd call it `Heading`.

But whatever suits your project is obviously best for you :smile:

Small thing btw, you don't have to pass a string into `rem`. A number is fine as well.

You could also rewrite your code like this in v2:

```js
const BaseHeader = styled.span`
  color: ${props => props.theme.colors.black || '#222'};
  line-height: 1.2;
`;

const h1 = BaseHeader.extendWith('h1')`
  font-size: ${rem(33)};
`
```

But that's more of an escape hatch :wink:

A small question, aren't you forgetting the `export` feature here? 😃

**Comment by luftywiranda13** [comment]
@philpl ahaha yess quite a mess 😳  

thanks man! gonna do a housekeeping thing to my code 😆

**Comment by hph** [comment]
@philpl I didn't see `extendWith` in the documentation site that you've been working on, I just wanted to give you a heads up in case you'd missed it.

**Comment by nath-codes** [comment]
Just in case anyone stumbles on here in future, 'extendWith' has been renamed to 'withComponent'.
[https://www.styled-components.com/docs/api#withcomponent](url)

So this:

`const h1 = BaseHeader.extendWith('h1')`
  font-size: ${rem(33)};
``

Is now this:

`const h1 = BaseHeader.withComponent('h1').extend`
  font-size: ${rem(33)};
``

**Comment by ezeikel** [comment]
Using `as` and a "level" `prop` to have one Component for h1-h5

```
import styled from 'styled-components';

const StyledHeading = styled.h1`
  font-family: var(--heading-font-family);
  font-style: normal;
  color: var(--color-black);
`;

const Heading = ({ level, ...rest }) => {
  return (
    <StyledHeading
      as={`h${level}`}
      {...rest}
    />
  )
};

Heading.defaultProps = {
  level: 1
};

export default Heading;
```

**Comment by kolin4** [comment]
`const Heading = ({ type, children }) => React.createElement(
  styled(type)`
   your styles
  `,
  {},
  children,
)


Heading.propTypes = {
  type: PropTypes.oneOf(['h1', 'h2', 'h3', 'h4', 'h5', 'h6'])
};
`

**Comment by pogojam** [comment]
I handled this by building a helper function  "changeTo()"  and implemented it into my switch inside Heading to maintain a universal base styled component.
`
const changeTo = (com, type) => {
  com.target = type;
  return com;
};

const withProps = (Component, { children, ...props }) => (
  <Component {...props}>{children}</Component>
);

const Heading = ({ type, ...props }) => {
  switch (type) {
    case "Sub":
      return withProps(changeTo(Sub, "h2"), props);
      break;
    default:
      return withProps(Standard, props);
  }
};

const Base = styled.h1``;

const Sub = styled(Base)``;

`

**Comment by HALfr0ZEN** [comment]
I know this problem is old but nevertheless this still might be helpful
I use this solution. Advantage is that you don't need .tsx file but just a regular .ts file

`
import styled from 'styled-components'

interface Props {
    level?: number
}

const Heading = styled.div.attrs<Props>(({level}) => ({
    as: 'h' + level
}))<Props>`
   //your style
`

Heading.defaultProps = {
    level: 1
}

export default Heading
`
