### ISSUE TITLE
Flow-Typed support for React Native

### ISSUE THREAD

**Issue by nofarius** [styled-components/styled-components#708]
While there is a libdef for styled-components in the [flow-typed](https://github.com/flowtype/flow-typed) repository, it doesn't support react native at all. I get the below error when flow checking.
```
  2: import styled from 'styled-components/native'
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^ styled-components/native. Required module not found
```

Any chance of getting flow-typed support for `styled-components/native`?

**Comment by relekang** [comment]
Oh, didn't think about that. We should make that happen. It might take a while before I can fix this, if someone is up to helping please submit a PR to flow-typed.

cc @styled-components/typers

**Comment by joeybaker** [comment]
PR submitted: https://github.com/flowtype/flow-typed/pull/836

**Comment by joeybaker** [comment]
PR has been merged upstream. This can be closed! ✅

**Comment by nofarius** [comment]
Thanks @joeybaker
