### ISSUE TITLE
How to add box-shadow for React-native? 

### ISSUE THREAD

**Issue by jasan-s** [styled-components/styled-components#709]
in essence: 
```
shadowOffset:{  width: 10,  height: 10,  },
shadowColor: 'black',
shadowOpacity: 1.0,
```

**Comment by k15a** [comment]
Just like normal CSS: https://developer.mozilla.org/de/docs/Web/CSS/box-shadow
```JS
const BoxShadow = styled.div`
  box-shadow: 10px 5px 5px black;
`

**Comment by jasan-s** [comment]
@k15a I forgot to add that this is on react-native

**Comment by jasan-s** [comment]
For some reason @k15a @mxstbr  the following two give me different results in terms of styling(equivalent property values): 
```
const styles = StyleSheet.create({
  containerStyle: {
    borderWidth: 1,
    borderRadius: 2,
    borderColor: '#ddd',
    borderBottomWidth: 0,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    elevation: 1,
    marginLeft: 5,
    marginRight: 5,
    marginTop: 10,
  }
})```

```const StyledView = styled.View`
  border-width: 1;
  border-radius: 2;
  border-color: #ddd;
  border-bottom-width: 0;
  shadow-color: #000;
  shadow-offset: {width: 0, height: 2};
  shadow-opacity: 0.8;
  shadow-radius: 2;
  elevation: 1;
  margin-left: 5;
  margin-right: 5;
  margin-top: 10;
  ```

**NOTICE THE DIFFERENT PLACEMENT OF SHADOW:**

![ (With Stylesheet create -- the shadow is on bottom)](https://cloud.githubusercontent.com/assets/13863953/25182897/e9b7bc60-24ca-11e7-841c-c52f7021a843.png)
![(With styles-components -- the shadow is on top)](https://cloud.githubusercontent.com/assets/13863953/25182847/c6dccd20-24ca-11e7-818a-e7eb95133d76.png)

**Comment by jacobp100** [comment]
You can use `shadow-offset: 5px 10px` where the values are width and height, respectively. I think you got the rest!

**Comment by guysegal** [comment]
These props are relevant only to iOS right? 

`shadow-color, shadow-offset, shadow-opacity, shadow-radius`

Will they work on Android?

**Comment by philpl** [comment]
@guysegal they won't since shadows are not supported on RN Android. But you can use elevation

**Comment by pie6k** [comment]
```
<View
      style={{
        shadowOpacity: 0.75,
        shadowRadius: 5,
        shadowColor: 'red',
        shadowOffset: { height: 0, width: 0 },
      }}
    >
```

**Comment by ColinFendrick** [comment]
Is this working? Trying to put some shadow on a view with the exact same above code and nothing is happening.

**Comment by jacobp100** [comment]
It only works for iOS IIRC

**Comment by ColinFendrick** [comment]
We're building React Native for iOS and it's not showing up.

**Comment by jacobp100** [comment]
Does it work with the native `StyleSheet.create`?

**Comment by philpl** [comment]
@ColinFendrick Does this definitely not work for you?

```
styled.View`
  shadow-opacity: 0.75;
  shadow-radius: 5px;
  shadow-color: red;
  shadow-offset: 0px 0px;
`
```

**Comment by ColinFendrick** [comment]
Figured out the problem. `overflow: hidden;` will ofc turn that box shadow off. Thanks.

**Comment by ikhattab** [comment]
This isn't working for me, I tried to add:

```
box-shadow: 10px 5px 5px black;
```

but it gives me the following warning:

```
Error:  Error: "boxShadow" is not a valid style property.
StyleSheet generated: {
  "borderBottomWidth": 1,
  "borderBottomColor": "#ebebeb",
  "display": "flex",
  "flexDirection": "row",
  "alignItems": "center",
  "backgroundColor": "#fff",
  "boxShadow": "10px 5px 5px black"
}
```

**Comment by jacobp100** [comment]
@mxstbr @philpl Do we want to try and support a translation from `box-shadow` to various `shadow-*` properties?

**Comment by philpl** [comment]
@jacobp100 Yes! I'd love that :heart: :smile:

**Comment by dakdreams** [comment]
my emulator is android but the shadow props dont work!!!

**Comment by k15a** [comment]
@dakdreams AFAIK android doesn't support shadows.

Try [elevation](https://facebook.github.io/react-native/docs/viewstyleproptypes.html):

> (Android-only) Sets the elevation of a view, using Android's underlying elevation API. This adds a drop shadow to the item and affects z-order for overlapping views. Only supported on Android 5.0+, has no effect on earlier versions.

**Comment by RyanWarner** [comment]
As @jasan-s pointed out, the shadows seem to be on the top instead of the bottom of the View. Any way around this?

**Comment by redbar0n** [comment]
Upvote here: https://react-native.canny.io/feature-requests/p/shadow-does-not-appear-if-overflow-hidden-is-set-on-ios

**Comment by Nemesis30G** [comment]
I tried this 
shadowOffset:{  width: 10,  height: 10,  },
shadowColor: 'black',
shadowOpacity: 1.0,

but I have some text inside the view and it make the text have shadow too, any way around this?

**Comment by SSTPIERRE2** [comment]
I just tried wrapping a scrollview with text in a view styled with shadow props, but as @Nemesis30G said the shadow actually applied to the text inside the scrollview, not around the borders of the view.. What gives?

**Comment by jacobp100** [comment]
Set a background colour on the scrollview

**Comment by DanielYoris1274** [comment]
This is different than CSS style.

**Comment by DanielYoris1274** [comment]
Inset is not working.

**Comment by DanielYoris1274** [comment]
1. **OK**

- [ ] 1

**Comment by jacobp100** [comment]
`inset` is not supported by React native

**Comment by Karniej** [comment]
The issue with shadowOffset should be documented a little bit better. The only way to work with shadowOffset on React Native was by using the shorthand property
 `boxShadow: 1px 10px 10px black`

**Comment by LetsNurtureGit** [comment]
elevation:4,
    shadowOffset: { width: 5, height: 5 },
    shadowColor: "grey",
    shadowOpacity: 0.5,
    shadowRadius: 10,

Dont forget to put margin and padding efficiently as the shadows wont fall out of the container view in android.. However in iOS it shudn't be an issue

**Comment by rickardinho** [comment]
So is anybody going to answer why shadows are appearing on top on IOS, no matter what the shadowOffset properties, @jasan-s pointed out?

**Comment by rajnishcoder** [comment]
> elevation:4,
> shadowOffset: { width: 5, height: 5 },
> shadowColor: "grey",
> shadowOpacity: 0.5,
> shadowRadius: 10,
> 
> Dont forget to put margin and padding efficiently as the shadows wont fall out of the container view in android.. However in iOS it shudn't be an issue

all above solutions doesn't worked in android but this works!!! :smiley:

**Comment by Kishanjvaghela** [comment]
try this https://www.npmjs.com/package/react-native-cardview

**Comment by skhetcho** [comment]
> Just like normal CSS: https://developer.mozilla.org/de/docs/Web/CSS/box-shadow
> 
> ```js
> const BoxShadow = styled.div`
>   box-shadow: 10px 5px 5px black;
> `
> ```

what is this syntax @k15a 
as we are used to with react native to have:
style: {
     //some react native css info
}

**Comment by bradennapier** [comment]
This seems to be working fine for me:

```javascript
const IconImage = styled.Image`
  height: 30px;
  width: 30px;
  shadow-color: #000;
  shadow-offset: 1px 1px;
  shadow-opacity: 0.5;
  shadow-radius: 2px;
`;
```

**Comment by jacoblukose** [comment]
> I tried this
> shadowOffset:{ width: 10, height: 10, },
> shadowColor: 'black',
> shadowOpacity: 1.0,
> 
> but I have some text inside the view and it make the text have shadow too, any way around this?

Hi is there a solution for this ?

**Comment by LetsNurtureGit** [comment]
> > elevation:4,
> > shadowOffset: { width: 5, height: 5 },
> > shadowColor: "grey",
> > shadowOpacity: 0.5,
> > shadowRadius: 10,
> > Dont forget to put margin and padding efficiently as the shadows wont fall out of the container view in android.. However in iOS it shudn't be an issue
> 
> all above solutions doesn't worked in android but this works!!! 😃

thanks
