### ISSUE TITLE
Local development?

### ISSUE THREAD

**Issue by tizmagik** [styled-components/styled-components#71]
I'm trying to hack on some things locally with `styled-components` but I get this error both with `npm link`ing and with a webpack alias pointing to `src/index.js` or `lib/index.js`:

```
ERROR in ../lib/constructors/keyframes.js
Module not found: Error: Can't resolve 'glamor/lib/hash' in '/Users/dev/Docum
ents/workspace/scratch/styled-components/lib/constructors'

...
ERROR in ../lib/models/ComponentStyle.js
...
ERROR in ../lib/utils/autoprefix.js
```

All "module not found" errors. Not sure what's up? Do you have a workflow for working locally?

**Comment by geelen** [comment]
Very strange. If you want to `npm link` you need to make sure that you're also running `npm run build:watch` to be filling the `lib` directory with output. Can you try that?

**Comment by tizmagik** [comment]
Ah okay, it turns out that apparently either webpack or something had issues with a nested package.json (my project was within styled-components project). Closing.
