### ISSUE TITLE
Hack to inject thirdsparty styles before styled-components injected styles and in some particular order

### ISSUE THREAD

**Issue by RIP21** [styled-components/styled-components#711]
Hi, everyone.

There is a common problem when you try to start to use `styled-components` and have already defined styles in separate CSS files described [here](https://github.com/styled-components/styled-components/blob/master/docs/existing-css.md):
>  Sadly, some tools (like the webpack style-loader) give you no control over the place they inject the CSS into, meaning you cannot move them after the styled-components one.

And typical and suggested hack is to use `&&` to increase specificity. 
We all know it's a bit ugly, but we have to deal with it.

But recently I found some hidden thing that probably nobody noticed before.
When you are importing styles this way.
```javascript
import './SomeCss.css';
```
Webpack actually loads it after `styled-components` styles and in some random unknown order so we cannot rely on that.

But interesting thing is that. When we import styles assigning them to some value it keeps order in which it goes in the code. So this code:
```javascript
import bootstrap from './b.css';
import font from './fonts.css';
import custom from './custom.css';
```
Results to the imported styles to head in that particular order like in the code and before styles that styled-components is injecting.

![1](https://cloud.githubusercontent.com/assets/3940079/25204499/059bd388-255e-11e7-82cb-706d4c39fe74.PNG)
![default](https://cloud.githubusercontent.com/assets/3940079/25204508/0b50ad26-255e-11e7-8d4e-802bc8e48d19.PNG)

So I think this hack is quite nice, and also ugly at some point :D But also works, so probably will be a good addition to the docs mentioned above. 

BTW. I'm using `create-react-app`, so probably with other configs, it could behave differently. But for CRA is just fine :)

Thanks.

**Comment by philpl** [comment]
Maybe we should add some notes to the "Existing Section" of the upcoming styled-components-website. Do take a look if you'd like :)

**Comment by niklasholm** [comment]
In case Google led you here: Nowadays [style-loader an option](https://webpack.js.org/loaders/style-loader/#insert) to provide a custom function to control where the new css is injected. Something like this:
```javascript
...
{
  loader: "style-loader",
  options: {
    insert: (node) => {
      const style = document.querySelector("head > style[data-styled=active]");
      if (style !== null) {
        document.head.insertBefore(node, style);
      } else {
        document.head.appendChild(node);
      }
    }
  }
}
...
```
