### ISSUE TITLE
Arrow function used ambiguously with a conditional expression

### ISSUE THREAD

**Issue by vizFlux** [styled-components/styled-components#713]
I am trying to do a conditional for my button height, but I bumped into an error of `Arrow function used ambiguously with a conditional expression`. Any idea how can I right this error? Thanks in advance.

```JavaScript
export const CTABtnContainer = styled.div`
  & > a {
    padding: 10px 24px;
    height: ${props => props.small ? '32px' : '40px'};
  }
`;
```

**Comment by k15a** [comment]
This sounds like an ESLint error. Just wrap you function body in parens.
