### ISSUE TITLE
What is the purpose of using tagged template literals in `styled-components`?

### ISSUE THREAD

**Issue by zerkms** [styled-components/styled-components#715]
The tag functions are implemented as

```js
  const styled = (tag: Target) =>
    (strings: Array<string>, ...interpolations: Array<Interpolation>) =>
      styledComponent(tag, css(strings, ...interpolations))

  // Shorthands for all valid HTML Elements
  domElements.forEach(domElement => {
    styled[domElement] = styled(domElement)
  })
```

and `css` is simply

```js
export default (strings: Array<string>, ...interpolations: Array<Interpolation>): RuleSet => (
  flatten(interleave(strings, interpolations))
)
```

and `interleave` simply joins the strings and interpolations.

So, why instead of tagged literals

```js
styled.button`...`
```

not use functions

```js
styled.button(`...`)
```

It would save some CPU cycles and memory.

Or am I missing something important?

**Comment by philpl** [comment]
Interleaving is actually not a huge performance hog, and it totally disappears when you enable preprocessing (experimental in v2).

We're using tagged template literals for an improved API. We receive all interpolations and can manipulate them in a more sophisticated manner, than just `toString`-ing everything.

For example this wouldn't be possible without tagged template literals:

```js
const mixin = css`...`

styled.div`
  /* this function would just be toString()'d */
  background: ${p => p.color || 'white'};

  /* this mixin wouldn't be flattened into the rest of the rules */
  ${mixin}
`
```

Max has an excellent article explaining the details behind tagged template literals btw: http://mxstbr.blog/2016/11/styled-components-magic-explained/
