### ISSUE TITLE
Proposal: Add sanitize function to prevent css value injection

### ISSUE THREAD

**Issue by Geeman201** [styled-components/styled-components#721]
Hi,

I am a newcomer to styled-components! Really [enjoyed using it for the first time](https://twitter.com/Geeman201/status/854728656815620097)! One of the things that caught me out was sanitising input before using it as a dynamic style (And I'd imagine it's likely to catch more than just me out). The [Security document](https://github.com/styled-components/styled-components/blob/master/docs/security.md) explains what could happen really well, and I soon realised where I was going wrong. 

Developers should be sanitising inputs but I envisage this as a 'defensive' option:

```javascript 
import styled, { sanitize } from 'styled-components';

const Button = styled.button`
  /* Adapt the colors based on primary prop */
  background: ${props => sanitize(props.primary)};
`;

export default Button;
```

I saw a discussion in #622 which discusses how a sanitise function would be hard for a prop which represents a whole css block, but for sanitising a prop which is a css value is surely relatively simple. Stripping anything from a `;`? I may be wrong but I can't think of a value which would have a semi-colon in?

I was thinking `sanitize`, `santizeCssValue` or `santizeValue`?

More than happy to have a go at implementing if you think this is a worthwhile feature.

**Comment by philpl** [comment]
We're not looking into adding helpers that aren't immediately needed or make sense in the "narrative" of the API. Also, such a helper would be easily written, I assume, and only be needed if user input is actually accepted, so I'd say this is up to the users :smile:

cc @geelen
