### ISSUE TITLE
Confusion around overriding styles on dynamically generated styled-components (i.e. you can't)

### ISSUE THREAD

**Issue by Josh-a-e** [styled-components/styled-components#722]
Whilst I suspect this is actually intended behaviour, but I found it confusing and I'd argue should be spelt out in the readme to save people similar confusion.

This issue is that when trying to override styled-components which are dynamically generated (quite possibly a bad practice anyway?), the overriding class gets added to the style tag above the class that is to be overridden, rather than below.

## Version
2.0.0-7

## Reproduction
https://www.webpackbin.com/bins/-KiFU4EtwF48Ff-HTZe4

## Expected Behaviour
```html
<style type="text/css">

...

.iJsmtH {color: blue;font-size: 2em;}
.dnrWkP {color: blue;font-size: 2em;}
.xdVw {color: yellow;}
</style>
```

## Actual Behaviour
```html
<style type="text/css">

...

.xdVw {color: yellow;}
.iJsmtH {color: blue;font-size: 2em;}
.dnrWkP {color: blue;font-size: 2em;}
</style>
```

**Comment by Josh-a-e** [comment]
Further to this, here's a real life, slightly less contrived example than the size one above:

```
import React from 'react';
import styled from 'styled-components';

type Props = {
  level: 1 | 2 | 3 | 4 | 5 | 6
};

const Header = ({ level = 2, ...props }: Props) => {
  const Element = styled[`h${level}`]`
  font-weight: normal;
  letter-spacing: 0.4em;
  text-transform: uppercase;
`;

  return <Element {...props} />;
};

export default Header;
```

**Comment by geelen** [comment]
Yeah this is totally expected behaviour. CSS for a Styled Component is injected in _the order in which the components are defined_. By delaying the definition of the `Button3` by wrapping it in a function, but having `Button4` outside, you're defining `Button4` first.

Generally, define your SCs at the top level and you'll be fine.
