### ISSUE TITLE
pass tagName="..." into styled components?

### ISSUE THREAD

**Issue by ianstormtaylor** [styled-components/styled-components#723]
Hey, I'm not sure if this has been suggested before, but I couldn't find it with a quick search.

I think there are legit cases where components need to be used in different contexts with different tag names. For example, buttons are sometimes `<button>` and other times `<span>` and other times `<a>`. Or sometimes you need to swap between `<div>` and `<span>`. Right now, as far as I can tell, there isn't an easy way to do that?

I was thinking it would be nice to have a `tagName` property that was first-classed that made this easy so that you can do...

```js
const Button = styled.span`
  ...
`

<Button tagName="button">Click Me</Button>
<Button tagName="a" href="...">I am a Link</Button>
```

What do you think?

I personally feel like all UI kits should provide this for their base-level components.

**Comment by k15a** [comment]
First of all buttons should never be `<span>` because of accessibility. Otherwise there was already a discussion here: https://github.com/styled-components/styled-components/issues/494
