### ISSUE TITLE
Usage of a deprecated flexbox API

### ISSUE THREAD

**Issue by MatthieuLemoine** [styled-components/styled-components#727]
## Version
1.4.5

## Reproduction

I use [lighthouse](https://developers.google.com/web/tools/lighthouse/) to test a PWA.

When using flexbox, one of the test fail because of the usage of a deprecated flexbox API.
Prefixed ``display : block`` and ``box-direction : vertical``, for instance, are indeed generated along new flexbox api ``display : flex`` and ``flex-direction : vertical``.

See [this link](https://developers.google.com/web/tools/lighthouse/audits/old-flexbox) for more details about deprecated flexbox API.

## Steps to reproduce

- Add a ``display : flex`` rule
- Generate a report from lighthouse

## Expected Behavior

Should only generates latest flexbox API rules or provide a way to disable deprecated rules.

## Actual Behavior

Generates old and deprecated flexbox API rules.

**Comment by geelen** [comment]
See #719
