### ISSUE TITLE
Components with secondary classnames

### ISSUE THREAD

**Issue by khankuan** [styled-components/styled-components#728]
Hi, I'm wondering if there is a solution to using styled-components with existing libraries. Lots of libraries adopt customization to css via multiple `className` props. For example, [react-select](https://github.com/JedWatson/react-select) uses `className` and `optionClassName` in a component. Would it be useful to support something like:
```
const MySelect = styled(ReactSelect)`
  border: red;
  [optionClassName]
  color: blue;
`
```

**Comment by philpl** [comment]
Just pass in `className` to the generated styled component and it'll be appended on the prop :wink:

**Comment by geelen** [comment]
Nah this is about optionClassName. This was the missing piece of the attrs
feature. I want to do it but I dunno if we should hold up v2 for it!

**Comment by khankuan** [comment]
Yup. @geelen any thoughts on how it might look like? Another alternative could be:
```
const MySelect = styled(ReactSelect)`
  border: red;
`.attr('optionClassName', `
  color: blue;
`)
```

**Comment by geelen** [comment]
The plan is for it to look like this:

```js
const MySelect = styled(ReactSelect).attrs({
  optionClassName: css`
    color: blue;
  `,
})`
  border: red;
`
```

But it's not a simple thing to implement, sadly. I'll have a go at it when I can!

**Comment by khankuan** [comment]
@geelen interesting! Just thinking a little boarder, what if `MySelect` allows it's parent to set `optionClassName` as well and will concatenate them? Eg.
```
// PageMySelect sets options to to red color
const PageMySelect = styled(MySelect).attrs({
  optionClassName: css`
    color: red;
  `,
})

// MySelect enlarges font-size of options in react-select 
const MySelect = styled(ReactSelect).attrs({
  optionClassName: css` // Need to ensure that optionClassName from parent is concatenated
    font-size: 20px;
  `,
})
```

**Comment by geelen** [comment]
Yeah you're buggered then. There's more of a discussion over at #184. I'm pretty sure the best way to do this is this:

```ks
const optionClassName = btoa(Math.random())

const MySelect = styled(ReactSelect).attrs({
  optionClassName
})`
  border: red;
  &.${ optionClassName } {
    color: blue;
  }
`

const MyOtherSelect = MySelect.extend`
  &.${ optionClassName } {
    color: blue;
  }
`
```

That way you only ever have one classname for things, and you can add styles without adding attributes. Attrs already allows a function syntax, which means you _could_ do the following:

```js
const PageMySelect = styled(MySelect).attrs({
  optionClassName: props => props.optionClassName + ' ' + someOtherClassName
})
```

But it kinda wouldn't work with the magical css classname generation thing. This is actually a really good example of how trying to make the `attrs` constructor more magical breaks down, thanks a lot.

**Comment by khankuan** [comment]
For the example on `optionClassName`, we may still cover a lot of use case if the `optionClassName` prop is prepended to the final className, similar to https://github.com/styled-components/styled-components/blob/v2/src/models/StyledComponent.js#L131

On the other hand, the syntax with `${ optionClassName }` felt a little complicated and I'm worried if we're indirectly developing a language. If we take a step back, is there an alternative way to define a function `scopedCss(cssString)` that deals with the css injection? E.g.
```
<ReactSelect
  className={styled.raw`font-size: 20px`}
  optionClassName={styled.raw`color: red`}
/>
```

**Comment by drFabio** [comment]
Styled.raw seems like a good solution.I stubled upon this on a similar case and that would suit it

**Comment by mxstbr** [comment]
We've decided against introducing a method that let's you manually get a CSS class name from a CSS string to avoid people overusing it and thusly defeating the whole point of the library. (it's strictness)

I'm going to close this issue because this is now possible with v2 and the `.attrs` selector:

```JS
const optionClassName = 'option';

const MySelect = styled(ReactSelect).attrs({
  optionClassName,
})`
  ${optionClassName} {
    // style an option here!
  }
`
```

**Comment by devboell** [comment]
Could I just ask why @mxstbr uses `${optionClassName}` notation and  @geelen uses `&.${ optionClassName }` ?

**Comment by mxstbr** [comment]
That's my bad, fixed it!

**Comment by devboell** [comment]
thank you, but isn't the ampersand required?

**Comment by khankuan** [comment]
@devboell ampersand is only required when you're chaining the classname in the parent component. In this case, `optionClassName` is a classname attached to the option component, which is a child of the parent. Hence, ampersand is not required.

**Comment by philpl** [comment]
@chochihim you generally can't nest rules in React Native. There's also nothing to go after, since there are no classes in React Native either. For most style props that have a varying name from `style` I often just go for the `.attrs` method and just use inline styles in that specific case

**Comment by chochihim** [comment]
@philpl I am not nesting rules in React Native. I am trying to style `TabBar` from [react-native-tab-view](https://github.com/react-native-community/react-native-tab-view) which contains custom style props like `tabStyle`, `indicatorStyle` etc. I tried below but failed:

```js
import { TabBar } from 'react-native-tab-view';

const optionStyle = 'indicatorStyle';

const StyledTabBar = styled(TabBar).attrs({
    optionStyle
})`
    .${optionStyle} {
        background-color: #08BA44;
    }
`;

export default StyledTabBar;
```
So I wonder if `.attrs` works for React Native.

**Comment by philpl** [comment]
@chochihim when you create that rule body inside the SC css there for optionStyle, that’s what I’m referring to as the nested rules due to the css-y nature of the term :)

The attrs method does work with react native

**Comment by chochihim** [comment]
@philpl So do you mean `.attrs ` works but not in the way I am using it for my case? Is it I can only use inline-style/StyleSheet like:

```js
const StyledTabBar = styled(TabBar)`
    background-color: white;
`;

const styles = StyleSheet.create({
    indicator: {
        backgroundColor: '#08BA44',
    }
});

const ExtendedTabBar = (props) =>
    <StyledTabBar
        indicatorStyle={styles.indicator}
        {...props}
    />
```
to provide style for optional style props like `indicatorStyle`?

**Comment by philpl** [comment]
@chochihim the prop in attrs works and it will be passed. But you’ll have to pass inline styles or a Stylesheet as in your new code snippet.

I also have to ask you to please post in spectrum, Gitter, etc, or open a new issue. This issue is mostly unrelated, closed, and you’ll ping everyone who participated in it.

**Comment by epsi-yahoo** [comment]
Hi,
So is it possible actually to do this only with styled-components (without inline styles) ?
Thanks

**Comment by uni0ue** [comment]
For use-cases that are not children of the component that receives the styles via className (but maybe a parent) you can target the styling of the specific element like this:

```
const Gallery = ({
  className,
  ...props
}) => <StyledDialog {...props} outerClassName={className} />;

const StyledGallery = styled(Gallery)`
   /* wrapper  styles go here */
`;

const StyledDialog = styled(Dialog)`
    /* inner styles go here */
`;

const Dialog = ({className, wrapperClassName}) => (
  <Wrapper className={wrapperClassName}>
    <Inner className={className} />
  </Wrapper>
)
```

**Comment by casr** [comment]
Woah, blast from the past! Re-reading this thread back, [my example](https://github.com/styled-components/styled-components/issues/728#issuecomment-454479697) could be rewritten using the suggestion earlier in [this thread](https://github.com/styled-components/styled-components/issues/728#issuecomment-312414854):

```javascript
function RemapModalClassNames(props) {
  const { className, contentClassName } = props;

  const remappedProps = {
    ...props,
    bodyOpenClassName: className,
    className: contentClassName,
  };

  return <ReactModal {...remappedProps} />;
}

const overlayClassName = "overlayClassName";
const contentClassName = "contentClassName";

const StyledModal = styled(RemapModalClassNames).attrs({
  contentClassName,
  overlayClassName,
})`
  overflow: hidden;

  .${overlayClassName} {
    position: fixed;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    background-color: rgba(0, 0, 0, 0.5);
  }

  .${contentClassName} {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    border: 1px solid rgb(204, 204, 204);
    background: white;
    overflow: auto;
    border-radius: 4px;
    outline: none;
    padding: 20px;
    margin: auto;
    width: 400px;
    height: 30%;
  }
`;
```

It feels less weird than my original example but it's still a bit awkward as:

- you need to know the internal structure of the component to make sure that whatever Styled Components assigns to `className` is always wrapping the rest of the classes. In [React Modal](https://www.npmjs.com/package/react-modal)'s case the `className` prop actually applies to a child of `bodyOpenClassName` and `overlayClassName` so we need to remap those classes around in `RemapModalClassNames`
- `overlayClassName` and `contentClassName` need to be made up and could end up clashing with other CSS in the project

It does benefit from not having a few wrapping instances of SC though!
