### ISSUE TITLE
styled.button Component doesn't respond to onClick

### ISSUE THREAD

**Issue by pheuter** [styled-components/styled-components#73]
### Description
Passing an `onClick` prop to a `styled.button` component does not seem to respond to click events.

### Demo
http://www.webpackbin.com/VJie-AdAW

**Comment by geelen** [comment]
Weird, you're looking at an old webpackbin link. How did you get there (we must have missed one)

Try this one: http://www.webpackbin.com/NkHNNXuAW

**Comment by sarbbottam** [comment]
Please see refer - http://www.webpackbin.com/V13pvJFAb modified version of http://www.webpackbin.com/NkHNNXuAW.

**Comment by geelen** [comment]
Yeah that one's running on an old version of `styled-components` as well:
![image](https://cloud.githubusercontent.com/assets/23264/19368366/714c820a-91eb-11e6-8f63-5c34963be734.png)

 Not sure why this is happening but it looks like it's not saving the version update. If you untick `styled-components` then search and add it again it should install `1.0.0` which works.

**Comment by sarbbottam** [comment]
Yep works.

>Not sure why this is happening but it looks like it's not saving the version update.
You got to save it once selected. 
> If you untick `styled-components` then search and add it again it should install `1.0.0`

See http://www.webpackbin.com/4J3rflt0W

I guess the issue is resolved.

**Comment by pheuter** [comment]
awesome, makes sense now! thanks for getting back so fast ☺️
