### ISSUE TITLE
Consuming styled-components child modules in libraries

### ISSUE THREAD

**Issue by petetnt** [styled-components/styled-components#732]
This isn't as much of a `styled-components` issue but more a split between usage question and a feature(ish) request, so feel free to close at will if this doesn't seem relevant to the library itself.

We use various libraries enhancing our `styled-components` usages and I have written few myself. In https://github.com/petetnt/styled-bootstrap-responsive-breakpoints I ran into a issue where I only needed a subset of `styled-components`, more specifically the `css` utility.

Including the module itself was of course pretty simple:

``` js
import { css } from 'styled-components';
```

Which did work perfectly, but... the bundle size grew in to full size of `styled-components`. I tried various ways of eliminating the dead code with `Webpack`, but nothing seemed to work (maybe because I was consuming the compiled code anyway?).

The good old trick was/is to import the module directly from the folder:

``` js
import css from `styled-components/constructors/css`
```

Which works... sort of. The file was `flow` typings attached, so without stripping the types you'll run into quite a lot of runtime errors immediately. The solution is quite obvious, strip the types with `babel` before using the modules. The bundle size is now minimal, but then again then I am transpiling modules from `node_modules` directly myself, which seems like a pretty sketchy idea. Also I have to serve a transpiled version of my library too, which creates a tiny bit of overhead to the development side.

My question/issue is one of the followings:

1) Am I doing something wrong and `Webpack` should totally have eliminated the dead code regardless?
2) If not, would there be any interest on either
2a) Offering pre-transpiled modules of some of the `styled-components` submodules either in the package itself
2b) or as standalone packages on `npm` which would be even more awesome!

**Comment by philpl** [comment]
> the bundle size grew in to full size of styled-components

Since it's a library that complements styled-components you should make it an external of your UMD bundle, and not actually include it :smile: We won't make separate modules for every file obviously :wink:

Also, try to avoid accessing a file like that, it will likely duplicate the code in the final bundle for Rollup and Webpack 2 builds, since we're pointing to our ES bundles there:

> "jsnext:main": "dist/styled-components.es.js",
> "module": "dist/styled-components.es.js",

**Comment by petetnt** [comment]
Thanks for the pointers 😊
