### ISSUE TITLE
Problem with utilizing props 

### ISSUE THREAD

**Issue by ifndefdeadmau5** [styled-components/styled-components#733]
## Version
1.4.5

## Reproduction
parent.js
```jsx
  <FloatingMenu background="red">
         {...}
   </FloatingMenu>
```
child.js
```js
const Container = styled.ul`
  background: ${props => props.background}
  }
`;
```
The props.background simply not working at all.
## Steps to reproduce
> git clone https://github.com/ifndefdeadmau5/react-floating-button-menu
> npm install
> npm start
## Expected Behavior
The props inside of template literal has to hold received props 

## Actual Behavior
Got undefined except boolean props. Also, the style doesn't change whenever props that determines it's style is changed

**Comment by k15a** [comment]
You need to pass the prop to the Container not the FloatingMenu.

**Comment by ifndefdeadmau5** [comment]
@k15a Sorry for unclear example. here is the full code 

https://github.com/ifndefdeadmau5/react-floating-button-menu/blob/master/src/FloatingMenu/FloatingMenu.js

**Comment by k15a** [comment]
You forgot a semicolon ;)

**Comment by k15a** [comment]
And you should pass the props down.
```
<Container background={this.props.background} onClick={this.toggleMenu}>
  {childrenWithProps}
</Container>
```

**Comment by ifndefdeadmau5** [comment]
@k15a 
Oh. So this is now work
```
 render() {
    return (
      <Container onClick={this.toggleMenu} background={this.props.background}>
        {childrenWithProps}
      </Container>
    );
  }
```

I thought it automatically hold props although I didn't pass it manually. Thanks...

**Comment by k15a** [comment]
Unfortunately we can't do any magic and you still have to pass your props around like you do in React.

**Comment by ifndefdeadmau5** [comment]
I struggled almost 4 hours like 'why this simple feature doesn't work' and finally decide to report a bug and totally don't regret it!! Thank you so much
