### ISSUE TITLE
API Consequences for Static CSS Extraction

### ISSUE THREAD

**Issue by jacobp100** [styled-components/styled-components#734]
Phil's excellent work on the babel plugin means that we can extract all non-dynamic styles into a static CSS stylesheet.

However, we need to think about the effects this has on the project. Take this code,

```js
const Button = styled.button`
  background: ${props => props.primary ? 'palevioletred' : 'white'};
  ${props => props.large && css`
    font-size: 2em;
  `}
`
```

While it is theoretically possible for this use-case to extracted into static CSS, we don't currently have this optimisation. Further more, we won't be able to optimise every case.

We can work around this.

```js
const Button = styled.button`
  background: white;

  &.primary {
    background: palevioletred;
  }

  &.large {
    font-size: 2em;
  }
`

<Button className="primary large">It mostly works like before</Button>
```

This can now be completely statically extracted.

However, this is no longer idiomatic styled-components. But **we can guarantee people will do this** for the sake of optimisation.

We need to continue static style extraction. But we also need to consider what we can change to have an idiomatic styled-components that better supports CSS extraction. Even if that changes what 'idiomatic styled-components' is.

Pinging @mxstbr @geelen @philpl

**Comment by diondiondion** [comment]
> This can now be completely statically extracted.

It arguably looks much cleaner, as well. 😛
On the other hand, your example is probably still quite extraction-friendly as you're just changing pre-set CSS rules depending on props, but you're not dynamically turning props into rules. Will something like the following be strictly impossible to be statically extracted?

```
const Button = styled.button`
  width: ${props => pxToRem(props.width)};
`
```

**Comment by philpl** [comment]
The entire point is for the users to not think about this too much, it will be documented however.

When interpolations are used, it is strictly runtime-critical CSS, so it must live on the client-side in the JS bundle. Thus I'm not too concerned to change what "idiomatic SC" would look like to suit static style extraction.

**Comment by diondiondion** [comment]
> Since your example is a function though that takes the props, it can never be statically extracted, since it isn't static ;)

Thanks. When you put it like that, I don't know why I even asked. ;)

**Comment by jacobp100** [comment]
> When interpolations are used

That's sort of what I'm getting at. Interpolations are used for mixins, variables, passing arbitrary props, conditionally applying styles, and more. Can we do any of these in a way that can be statically analysed?

**Comment by philpl** [comment]
@jacobp100 it requires more effort, but it should be possible. Mixins are not as simple though, since they might be external. This means that we'd need an internal method that adds more classnames to a styled component and need to generate our own ones for them.

Even then, I believe that we can enhance this as we go
