### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by valgreens** [styled-components/styled-components#738]
## Version
styled-components@1.4.5

Other relevant version information:
preact@8.1.0
preact-compat@3.14.1
webpack@1.14.0
webpack-dev-server@1.16.3

## Reproduction
Hi, I was trying to look for a way to share how to reproduce the issue but I don't really know how to given my set-up.

The issue seems to be related to `supports-color` dependency. It fails at index.js:2: `var argv = process.argv;` with the mentioned in title error message: `Uncaught ReferenceError: process is not defined`.

Is there any more information I can share with you that could help with this?

**Comment by k15a** [comment]
Are you requiring anything inside styled-components directly? Something like `import foo from 'styled-components/bar'`.

**Comment by valgreens** [comment]
No, just `import styled from 'styled-components';`

**Comment by k15a** [comment]
Could you try if it's working when you replace `styled-components` with `styled-components/dist/styled-components.js`

**Comment by valgreens** [comment]
:O hey that works!

**Comment by k15a** [comment]
You can temporary alias `styled-components` with `styled-components/dist/styled-components.js`.

**Comment by valgreens** [comment]
Will do. Thanks for your help!

**Comment by paulcdejean** [comment]
I'm getting this error, and when I try the workaround I get:

```
Could not find a declaration file for module 'styled-components/dist/styled-components.js'. 'c:/Users/Paul Dejean/Documents/timeburn/node_modules/styled-components/dist/styled-components.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/styled-components` if it exists or add a new declaration (.d.ts) file containing `declare module 'styled-components/dist/styled-components.js';`ts(7016)
```
