### ISSUE TITLE
props always default to false

### ISSUE THREAD

**Issue by Ricka7x** [styled-components/styled-components#739]
## Version
1.0.5

## Reproduction

https://www.webpackbin.com/bins/-KiWNpSUAYoyt8yXl_4v

## Steps to reproduce
1 - Create any styled component and pass it some props
2 - use ${props => props.value ? 'value': 'value'} syntax to do styling based on props
## Expected Behavior
Component should style components based on props values,
## Actual Behavior
Styled component always defaults to false

**Comment by k15a** [comment]
They default to `undefined` because they are not defined.
