### ISSUE TITLE
Can sibling be styled?

### ISSUE THREAD

**Issue by sarbbottam** [styled-components/styled-components#74]
For example, can I do something like - http://codepen.io/sarbbottam/pen/YGjXjq. If so, an example would be very helpful.

Nevertheless a great initiative. 👏 

Thanks!

**Comment by geelen** [comment]
Yep, no problems at all. We have Sass-style nesting, so you can just do this sort of thing:

```js
const Input = styled.input`
  opacity: 0;

  + label {
    position: relative;  
    &:before, &:after {
      content: '';
      position: absolute;
    }
    &:before {
      /* ... */
    }
    /* ... */
  }

  &:checked + label {
    /* ... */
  }
`

<div>
  <Input type="checkbox" />
  <label for="toggle">Toggle </label>
</div>
```

Personally, I'd put the styles on the outer `<div>` and call it something like `<Toggle>` like so:

```js
const Toggle = styled.div`
  > input { opacity: 0; }
  > input + label { /* ... */ }
  > input:checked + label { /* ... */ }
`

<Toggle>
  <input type="checkbox" />
  <label for="toggle">Toggle </label>
</div>
```

Good luck with it!

**Comment by drFabio** [comment]
How about a sibling with the same class as the component being styled?
Say I want to do this 
``` CSS
.foo + . foo {
  margin-left: 1rem;
}
```

**Comment by drFabio** [comment]
Nevermin just realized
```javascript
const StyledFoo = styled(Foo)`
  & + & {
    margin-left: 1rem;
  }`

```

**Comment by cbroberg** [comment]
No where else to turn :( 

I need help.

My brain is exploding trying to convert this CSS to styled-components. 
[https://gist.github.com/cbroberg/734b69d860268354b330e914f122217a](https://gist.github.com/cbroberg/734b69d860268354b330e914f122217a).

Any help here?

Thanks in advance for making styled-components

**Comment by philpl** [comment]
@cbroberg First of all, it's a lot easier to ask this question on Spectrum or StackOverflow. Or you could create a new issue as a last resort. :wink:

And second of all we introduced StyledComponent interpolations some time ago. This enables you to reference another StyledComponent component in your CSS which makes all of this possible.

I'm sure there's a more elegant way as well, but the exact CSS you posted does work.

Here's a quick reimplementation: https://codesandbox.io/s/k26ylrx6wo

Please also refer to the docs first next time, which have an FAQ section just about this topic: https://www.styled-components.com/docs/faqs#can-i-refer-to-other-components

**Comment by stavros-liaskos** [comment]
For future reference, here is the correct link from the docs:
https://www.styled-components.com/docs/advanced#referring-to-other-components

**Comment by birutaibm** [comment]
Is there something like `!` and `?` selectors from axe css post-processor?
