### ISSUE TITLE
innerRef doesnt register if you dynamically create the element

### ISSUE THREAD

**Issue by cjthedizzy** [styled-components/styled-components#743]
## Version
2

## Reproduction
```
const DynamicComponent = styled(({ children, tag, ...props }) => {
    return React.createElement(tag, props, children);
})`
// Some css
`;

// Usage
<DynamicComponent tag='div' innerRef={ref => this.someRef = ref} />
```

## Steps to reproduce
Use React.createElement to return an element to styled and try to use innerRef

## Expected Behavior
innerRef should be assigned to the returned React element

## Actual Behavior
ref is null

**Comment by philpl** [comment]
There's a couple of things here actually:

- I'm not sure which version you're using. Are you on v2.0.0-15?
- `innerRef` is turned into `ref` for targets that aren't styled components. Since you're passing in an anonymous functional component, the ref will point to it
- The problem however is that refs to functional components are not supported in React

I hope this helps you resolve this :)

You can actually also look at our tests here, if it's still unclear: https://github.com/styled-components/styled-components/blob/739e1a003cfd51f0dc07a64c01de0d8d93a3c945/src/test/basic.test.js#L61

**Comment by cjthedizzy** [comment]
The issue is the functional component I believe, derp. The ref in this case was giving me the styled component ref. Thank you

**Comment by cusxio** [comment]
@cjthedizzy, @philpl 

Since this pattern is fairly common in `styled-components`, is there any work around to get the "ref" of the component?

**Comment by cjthedizzy** [comment]
@cusxio refs for the component work fine using innerRef. React doesnt provide refs for functional components currently. If you're having a code specific issue I'd reccomend popping over to the gutter channel and posting a snippet. Lots of folks will to help there, including me

**Comment by cjthedizzy** [comment]
**Gitter

**Comment by cusxio** [comment]
```js
function buttonFactory() {
  return styled(
    ({
      tag = "button",
      children,
      flat,
      raised,
      primary,
      dense,
      fab,
      gradientRipple,
      btn48,
      ...other
    }) =>
      // console.log(other);
      createElement(tag, other, children)
  )`
    ${({ theme }) => theme.typography({ fontSize: "14px", fontWeight: "500" })}
    ${buttonStyles}
    ${isRaised}
    ${isFlat}
    ${isPrimary}
    ${isDense}
    ${isFab}
    ${is48}
  `;
}
```

I have the exact same code pattern as you. I need to somehow preserve this pattern and somehow get the "ref", is this possible? If not, what changes did you made to make your code snippet "work" ?

**Comment by philpl** [comment]
I'd consider writing a functional components inside the styled factory mostly an anti-pattern and thus uncommon actually.

`ref`s just *don't work* with functional components as they inherently don't have an **instance** to pass up. You'll need to pass on the `innerRef` prop and set `componentId` to some string on the functional component somehow, probably best with a small utility function.

This is a hack and not an actual recommended pattern.

The problem with changing the tag dynamically is that it violates the enforced best practices of styled-components. We had a big discussion about it, and ended up adding the `withComponent` method instead. Have a look and see whether that works better for your project: 

- https://www.styled-components.com/docs/basics#extending-styles
- https://www.styled-components.com/docs/api#withcomponent

**Comment by canadaduane** [comment]
I'm in a similar situation, but I'm confused by @philpl's comment:

```refs just don't work with functional components as they inherently don't have an instance to pass up```

The following is found in the React docs:
```
You can, however, use the ref attribute inside a functional component as long as you refer to a DOM element or a class component
```

I recognize the difference between a functional component and a class component. However, I'd like to do just as the React docs suggest, and save the ref inside a closure. When I use `innerRef`, I get a `null` argument passed back.

For context: I have a `Flex` StyledComponent that is a tab stop, and I need to call "blur()" on it to remove focus from the element.
