### ISSUE TITLE
Very large bundle size

### ISSUE THREAD

**Issue by SpencerCDixon** [styled-components/styled-components#748]
I'm probably doing something wrong with my webpack config but I noticed when I added style-components it added like 200kb to my bundled output.  Seems very odd... 

![screen shot 2017-04-26 at 6 34 05 pm](https://cloud.githubusercontent.com/assets/7471018/25459976/0e8b2420-2aaf-11e7-950f-be0de0bcc7a3.png)

```
     Asset       Size  Chunks                    Chunk Names
 bundle.js     290 kB       0  [emitted]  [big]  main
styles.css    7.92 kB       0  [emitted]         main
index.html  424 bytes          [emitted]
   [0] ./~/preact/dist/preact.js 20.5 kB {0} [built]
   [1] ./src/styles/index.js 259 bytes {0} [built]
   [2] ./~/styled-components/dist/styled-components.es.js 251 kB {0} [built]
   [4] ./src/styles/global.css 41 bytes {0} [built]
   [5] ./src/styles/normalize.css 41 bytes {0} [built]
   [7] ./src/main.js 370 bytes {0} [built]
```

Is there something special I have to do to make it so it's not so large??

**Comment by philpl** [comment]
No, that unfortunately seems correct. v2 will have a much smaller bundle size, as we've worked on this issue a lot.

Note that this is the unminified, uncompressed size. Even in v1 it will go down to 73kb, and 20.9kb gzip'd.

In v2 you're looking at 107kb raw, 33kB minified, 12kb gzip'd right now.

We've also added experimental preprocessing to v2's babel plugin, which removes the need for a css parser, which brings down the bundle size even more.

I hope that clears things up :)

**Comment by SpencerCDixon** [comment]
Excellent, just wanted to make sure I wasn't missing something obvious!  Thanks @philpl 👍

**Comment by siddharthkp** [comment]
I don't know if this is the right place, just trying to follow the contribution guide.

> Look for old & closed issues (replying might be ok if they're not too old or have no conclusion)

I really like using styled-components, but the size makes me wonder if I should look for a smaller alternative (like emotion), so I'd like to work on making styled-components smaller and stop asking
 that question 😄 

Note: 14k isn't crazy big for the feature set it gives, but smaller is better? (I do a bunch of performance work on slow networks so this probably bugs me more than others)

I know @philpl was working on a pre-processing mechanism for 3.x which could strip out some code from the runtime. Happy to contribute where I can.

**Comment by mxstbr** [comment]
@siddhartkp react-emotion is also 9kB min+gzip, so not a massive difference anymore.

If you want to work on this a bit that'd be awesome, a big win would probably be to remove all our singleton functions from the modules? (most files export a function to simulate fake dependency injection, but that's proven useless, so we can just get rid of the function exports and just make them normal modules)
