### ISSUE TITLE
v2 release candidate candidate

### ISSUE THREAD

**Issue by geelen** [styled-components/styled-components#750]
There's been a few commits to `v2` now without a release. I'd like to get them out there, but they break the old SSR apis. Perhaps we should push to a dist-tag of `@rc` instead of `@next` so we can keep moving but we don't break people's stuff for no reason while everything's still in flux.

Then again, this is all prerelease, so we should probably just keep `@next` as whatever is... you know... actually coming next.

@mxstbr @philpl is there anything else preventing another release atm?

**Comment by mxstbr** [comment]
Nope, I like pushing as `@rc`.

We should've probably made the current releases `@alpha` rather than `@next`, but it's too late now!

**Comment by geelen** [comment]
Cool I'll do that now then

**Comment by philpl** [comment]
@geelen sorry for the late reply. You should be able to recycle the merge in v2-rc. We have to check whether the flow prop-types babel plugin is up to date as well :/
