### ISSUE TITLE
setState causes flashing in safari

### ISSUE THREAD

**Issue by MaximilianLloyd** [styled-components/styled-components#755]
## Version
1.0.5

## Reproduction
I have this issue in a production project, but i have isolated the issue and put it in its own repo.
https://github.com/MaximilianLloyd/ReactBug
- clone repo
- `npm install`
- `npm run start`

## Steps to reproduce
- Open Safari
- Click the red square in the top right
- It is inconsistent, so if it does not show up the first time, try again.

## Expected Behavior
The expected behaviour can be found in both chrome and firefox. Where when you click on the next button (red square) it does not flash, and proceeds to the next page. I thought that maybe the reason it was happening was because it was the parent component running `setState()`, but when i called `setState()` on a deeply nested component in my production project, the flashing still persisted. The reason it flashes blue is because i set that as a fallback color for when the image is not loaded/rendered. 
![expected](https://cloud.githubusercontent.com/assets/10583205/25523146/ee639080-2c05-11e7-83d4-6d582f47ab64.gif)

## Actual Behavior
(tried to convert to gif but since the error is < 1 frame it was not visible) 
https://gfycat.com/LastImpeccableCats

**Comment by philpl** [comment]
I don't really know what this is getting at. I'm sorry.

If anything it seems that Safari is simply not rendering the image of the underlying nodes as an optimisation maybe.

But anyway — it doesn't look like it's a Styled Components bug since all it's doing is rendering some CSS, that doesn't change across the state in the parent changing.

**Comment by IljaDaderko** [comment]
@philpl I've been experiencing similar issues in safari changing styles based on props that change based on state. When prop changes safari flickers for a split second showing initial styling and than changes correctly to one based on prop. This is unnoticeable if there is no transition though.

Below is mobile nav component I am working on (in safari when you click on hamburger menu you will see flickering)

```
import React, { Component } from "react";
import styled, { css } from "styled-components";

const SContainer = styled.div`
  position: absolute;
  right: 10px;
  z-index: 10;
  margin-top: 3px;
  -webkit-tap-highlight-color: rgba(0, 0, 0, 0);

  svg {
    z-index: 1;
    margin-top: -19px;
    margin-right: -23px;
    margin-left: -27px;
    margin-bottom: -14px;
    width: 75px;
    height: 56.25px;
    cursor: pointer;
    transform: translate3d(0, 0, 0);
  }

  path {
    fill: none;
    transition: all 0.4s cubic-bezier(0.25, -0.25, 0.75, 1.25),
      all 0.4s cubic-bezier(0.25, -0.25, 0.75, 1.25);
    stroke-width: 30px;
    stroke-linecap: round;
    stroke: ${props => (props.open ? "#ffffff" : "#4db7c3")};
    stroke-dashoffset: 0px;
  }

  #hamburger-top,
  #hamburger-bottom {
    stroke-dasharray: 240px 950px;
  }

  #hamburger-middle {
    stroke-dasharray: 240px 240px;
  }

  ${props =>
    props.open &&
    css`
    #hamburger-top,
    #hamburger-bottom {
      stroke-dashoffset: -650px;
      stroke-dashoffset: -650px;
    }

    #hamburger-middle {
      stroke-dashoffset: -115px;
      stroke-dasharray: 1px 220px;
    }
  `};
`;

const SCover = styled.div`
  transition: all .3s ease-in;
  width: ${props => props.size};
  height: ${props => props.size};
  border-radius: 50% 0 50% 50%;
  transform-origin: top right;
  transform: scale(${props => (props.open ? 1 : 0)});
  position: fixed;
  background: #4db7c3;
  top: 0;
  right: 0;
  z-index: 0;
`;

class MobileNav extends Component {
  state = {
    open: false,
    size: `${(window.innerWidth > window.innerHeight
      ? window.innerWidth
      : window.innerHeight) * 2}px`
  };

  componentDidMount() {
    window.addEventListener("resize", this._onWindowResize, false);
  }

  componentWillUnmount() {
    window.removeEventListener("resize", this._onWindowResize, false);
  }

  _onWindowResize = () => {
    this.setState({
      size: `${(window.innerWidth > window.innerHeight
        ? window.innerWidth
        : window.innerHeight) * 2}px`
    });
  };

  render() {
    return (
      <SContainer open={this.state.open}>
        <SCover open={this.state.open} size={this.state.size} />
        <svg
          viewBox="0 0 800 600"
          onClick={() => this.setState({ open: !this.state.open })}
        >
          <path
            d="M300,220 C300,220 520,220 540,220 C740,220 640,540 520,420 C440,340 300,200 300,200"
            id="hamburger-top"
          />
          <path d="M300,320 L540,320" id="hamburger-middle" />
          <path
            d="M300,210 C300,210 520,210 540,210 C740,210 640,530 520,410 C440,330 300,190 300,190"
            id="hamburger-bottom"
            transform="translate(480, 320) scale(1, -1) translate(-480, -318) "
          />
        </svg>
      </SContainer>
    );
  }
}

export default MobileNav;

```

**Comment by philpl** [comment]
@IljaDaderko Even though the problem manifests similarly, it's unlikely that it's the same. I've also not seen another report for this yet in quite some time.

Can you create a new issue please? It's generally not a good idea to add on to closed issues that are possibly unrelated ;)
