### ISSUE TITLE
Ability to provide !important flag to every CSS properties with var

### ISSUE THREAD

**Issue by mbeaudru** [styled-components/styled-components#756]
Hi everyone, I work on a project where there is a default css (semantic-ui-css) that overides the CSS-in-JS made with styled-components and we have to use the !important flag everywhere to be sure it is applied.

I'm fully aware that it's not the styled-components fault, but I think it may be useful to have a way to pass in options (like "Apply !important flag to any css written for a specific styled-component") with a variable.

What do you think about it ?

**Comment by philpl** [comment]
Instead of applying `!important` to all your rules, we actually recommend to increases specificity artificially. So you can for example write:

```css
& {
  color: red;
}
```

instead of:

```css
color: red;
```

And that should work since it targets "&&" or ".class.class", which has a higher specificity than just ".class"

**Comment by geelen** [comment]
Just to clarify, you can use as many `&`s as you need:

```js
styled.div`
  & { ... } /* renders .cls {} */
  && { ... } /* renders .cls.cls {} */
  &&& { ... } /* renders .cls.cls.cls {} */
`
```

Pop one of your semantic UI selectors into https://specificity.keegan.st/ to figure out how many you need.
