### ISSUE TITLE
component.type.name === StyledComponent where it should be the real component.type.name value

### ISSUE THREAD

**Issue by klemieux** [styled-components/styled-components#759]
When wrapping a component (lets say BaseComponent) with `styled(BaseComponent)`, the type.name is changed to StyledComponent, which is the normal behavior.. But this causes problems when you want to assert the real component type.name value (which should be BaseComponent and not StyledComponent).

**Comment by philpl** [comment]
The resulting displayName should be "StyledComponent(BaseComponent)". We don't manipulate the name of the generated component class.

Are you using this for tests by any chance?

**Comment by klemieux** [comment]
Hi, ok I found my error. Using `type.name` returns `StyledComponent` as said, but `type.displayName` does return `Styled(BaseComponent)`
