### ISSUE TITLE
Create component containing children using styled API

### ISSUE THREAD

**Issue by woro83c** [styled-components/styled-components#76]
So obviously you can create a component like so:

    const Button = styled.button`
      background: #ccc;
    `;

But can you create that same component so that it has children, _without_ needing to create another component? I.e.:

    const ButtonWithIcon = () => (
      <Button>
        <i className="fa" />
      </Button>
    );

I just want Button to always contain an icon.

Cheers!

**Comment by geelen** [comment]
Why not create another component? They're just function calls. If you put your two code examples together they'll work fine:

```js
/* Button.js */

const Button = styled.button`
  background: #ccc;
`;

export default () => (
  <Button>
    <i className="fa" />
  </Button>
);
```

**Comment by woro83c** [comment]
Ah, gotcha. I'm still sorta new to the react world so excuse my ignorance.

Cheers!
