### ISSUE TITLE
Using evaluated calculation from calc() to use Math functions

### ISSUE THREAD

**Issue by cocacrave** [styled-components/styled-components#760]
I have a css calc() inside a media query like this:
```
line-height: calc(
  ${nRows.min}rem + ${nRows.max - nRows.min} *
  (100vw - ${opt.minvw}rem) / ${opt.maxvw - opt.minvw}
);
```

The problem is with using calc with vw unit. I have no way of knowing what the value of the calculation will be. I need to use Math.ceil() on the evaluated value but css calc() only lets you use + - * /.

The best I could think of is using a resize event listener and update the computed value. But since this line height calc is for all the text like paragraphs and headings on the site, it means a lot of re-rendering.

Is there a better solution for this kind of problem?

**Comment by philpl** [comment]
I don't see how there could be a different solution: Either you use `calc` and CSS and so on, or you use JS. It's really as simple as that unfortunately ^^

Also do consider, that this will only be happening *if* the user resizes the browser, and apart from that only once. If you want to optimise this, I suggest you take `calc` and `vw` out of the equation, and make it purely JS calculated. This way you can make sure that it only updates when it has to.
