### ISSUE TITLE
React-native: warning Node of type rule not supported as an inline style

### ISSUE THREAD

**Issue by buptkang** [styled-components/styled-components#770]
Hey, when I tried to use the below styling in react-native:

```
const Input = styled.input`
  font-size: 1.25em;
  padding: 0.5em;
  margin: 0.5em;
  color: palevioletred;
  background: papayawhip;
  border: none;
  border-radius: 3px;

  &:hover {
    box-shadow: inset 1px 1px 2px rgba(0,0,0,0.1);
  }
`;
```

I go the the title warning, which I do not know how to resolve it. If I delete the internal hover section, it works without warning. 

Thanks

**Comment by philpl** [comment]
You have to use the native import and a native component.

https://sc-next-docs.philpl.com/docs/basics#react-native

**Comment by buptkang** [comment]
Thanks @philpl

**Comment by bernatfortet** [comment]
Getting the same error, 
I'm importing native and using native components. 

I can't debug. So it's hard to figure it out. But it seems that the warning appears when I'm styling a TextInput. i've also tried using `styled.TextInput`

```
const Input = styled(TextInput)`
  flex:1; font-size:16px; line-height:16px;
  padding:7px 16px 6px;
  height: {p => p.inputHeight}px;
  color: ${c.black}
`
```

**Comment by geelen** [comment]
That's... super weird. Maybe try without the 'px' on the height. Or it could be the final semicolon missing?

**Comment by bernatfortet** [comment]
I just found the problem :/

`height: {p => p.inputHeight}px;`
instead of
`height: ${p => p.inputHeight}px;`
I was missing the `$` before the brackets

I wonder if there's a good way to alert for that.

Thanks anyway

**Comment by geelen** [comment]
Ha! I missed that too!

Not sure whether we can build in an alert, but ideally your editor's syntax highlighting would help you notice that that chunk is being treated as a string, not as JS.

**Comment by robbiemilejczak** [comment]
Sorry to add on I got this error in a different use case, passing a template string as a variable.

Simplified example:

```
const buttonStyle = `
  background-color: ${props => props.backgroundColor;
  height: 44;
`

export const Button = styled.TouchableHighlight`${buttonStyle};`
```

I was able to silence the error by changing the last line to

```
export const Button = styled.TouchableHighlight(buttonStyle)
```

which makes a lot of sense when you think about it. Just figured I'd share in case anyone ends up here from google like I did!
