### ISSUE TITLE
Styled-Components AutoComplete in Atom

### ISSUE THREAD

**Issue by bernatfortet** [styled-components/styled-components#772]
Do you know of any package that does autocompletion for styled-components that works in atom?

**Comment by philpl** [comment]
These two commits look like it should work with `language-css`, `language-babel` and `autocomplete-plus`, but I'm not an Atom user and lack the knowledge of how these JSON definitions work:

- https://github.com/gandm/language-babel/commit/6d3cbdd8f22a9f904c3de912b051c6382c67587a
- https://github.com/gandm/language-babel/commit/dcbcfa63c524ef12b6a28833d9f2f60889070f70

**Comment by bernatfortet** [comment]
@philpl I have those 3 packages but I don't get the autocomplete prompts.

I'll keep searching. 

Thanks

**Comment by gandm** [comment]
@bernatfortet `language-babel` provides auto-complete for css inside `styled-components`. `language-css` isn't required for this but `autocomplete-plus` is. I presume you have the latest copy of `language-babel` and that the file is being processed by it?

**Comment by mxstbr** [comment]
I get the auto completition with `language-babel` perfectly, so it must be something locally with your setup. Hope you can figure it out! :blush:

**Comment by happypeter** [comment]
works for me
