### ISSUE TITLE
[v2] @supports query always results to true, if there´s a nested @media query

### ISSUE THREAD

**Issue by oennen** [styled-components/styled-components#775]
## Version
2.0.0-17

## Reproduction

https://www.webpackbin.com/bins/-Kji-ewR2MGAKe_s1IPJ

## Steps to reproduce

see example above

## Expected Behavior

`@supports not (display: block)` should result to false and content should be ignored.
Title color should be palevioletred.

## Actual Behavior

`@supports not (display: block)` results to true and content is being included.
Title color is green.

**Comment by philpl** [comment]
@ThySultan This seems to be a problem with Stylis :) https://www.webpackbin.com/bins/-Kji2D_tAEbrLoEipsCh

**Comment by thysultan** [comment]
Landed a patch in v2.0.5.
