### ISSUE TITLE
Potential performance gains from CSSStyleRule.style

### ISSUE THREAD

**Issue by Andarist** [styled-components/styled-components#779]
Have you seen this approach https://medium.com/@oleg008/high-performance-dynamic-styles-db28c873940 ?

Im wondering if thats something you would consider doing, seems like a reasonable thing to do to avoid every style-related reconcilation (those generated by `styled-components` ofc). 

Basic idea I think would be to divide generated classes for a component into 2 categories:
- static
- dynamic

Static would be a one className aggregating all non-changing props.
But each dynamic style prop should generate its own className.

Both could be applied only during initial render and would never have to change, but content of those dynamic classes would be changed in run time in StyleSheets themselves and not in React's world.

WDYT?

**Comment by philpl** [comment]
This is something we could do in v3, once we have the split between dynamic and static rules. I think it's worth investigating, as it would also force us to clean up per-component stylesheet management.

**Comment by Andarist** [comment]
If I can help somehow, let me know.

**Comment by philpl** [comment]
@Andarist I'll update this thread once @geelen and me spec out how the integrated preprocessing + static extraction works. Once that's done it should be relatively simple to add stuff like this to the StyleSheet API.

**Comment by kof** [comment]
Cool I did something useful, published that article at the meetup in Berlin where @geelen was talking but we didn't have actual time to talk haha.

**Comment by probablyup** [comment]
@kitten is this still something we want to pursue?
