### ISSUE TITLE
[V2] Double extend not working in v2.0.0-17

### ISSUE THREAD

**Issue by ehtb** [styled-components/styled-components#780]
Hi, extending an already extended styled-component is not working in v2.0.0-17.

```
const a = styled.div`...`
const b = a.extend`...` ---> works
const c = b.extend`...` ---> not working
```

I hope this explains the issue enough, otherwise I can create an example gist

**Comment by philpl** [comment]
I'll take a look this evening. Thanks for reporting!

**Comment by kopax** [comment]
@philipl What is the status of this ? We are really looking to deploy in production and the v2 isn't released yet. Could it be possible to sumup all the v2 issues se we can have an overview of the critical bug ? I have seen v2 isn't working with IE10.

**Comment by bhough** [comment]
@kopax if labeled correctly, you can see the status of all v2 work, including bugs by checking out the `v2.0` milestone: https://github.com/styled-components/styled-components/milestone/5

**Comment by philpl** [comment]
Wasn't able to reproduce this: https://codesandbox.io/s/0RrgK5yNL

**Comment by ehtb** [comment]
Hi @philpl, thanks for the investigation: here is the example where it goes wrong: https://codesandbox.io/s/E93KZjYR0

As you can see it never picks up the other two background colors.

**Comment by mxstbr** [comment]
Lots of indirection in that example 😅 Removing all the media queries, the first `<Title />` styles are no longer applied. (notice the wrong font-size)

<img width="1035" alt="screen shot 2017-05-29 at 18 22 06" src="https://cloud.githubusercontent.com/assets/7525670/26556604/c03b2eee-449b-11e7-8458-28d62b3db00e.png">

Live demo: https://codesandbox.io/s/l7mGk5jg
