### ISSUE TITLE
[v2] & + & doesn't work as expected

### ISSUE THREAD

**Issue by wmertens** [styled-components/styled-components#781]
## Version
2-rc

## Reproduction

https://www.webpackbin.com/bins/-Kjnzw5p4Lk1CcaYZBii

There should be a thick black line between each number but that doesn't work as expected.

## Steps to reproduce

Use the selector `& + &` in a class that also has interpolation functions. Different props cause different interpolations and thus different class names.

## Expected Behavior

`&` should refer to a base class that is always the same.

## Actual Behavior

In the example, the class for the first component is `sc-bdVaJa eCITef` and the `& + &` rule becomes `.eCITef + .eCITef` instead of `.sc-bdVaJa + .sc-bdVaJa`

**Comment by k15a** [comment]
I think this is a duplicate of #774?

**Comment by wmertens** [comment]
Totally a duplicate, and I see the workaround is to do `& + ${() => Foo}` which is rather exotic but ok. Thanks!
