### ISSUE TITLE
ScrollView child layout must be applied through the contentContainerStyle prop

### ISSUE THREAD

**Issue by piuccio** [styled-components/styled-components#785]
## Version
1.4.6

## Reproduction

```js
import styled from 'styled-components/native';

const Scroll = styled.ScrollView`
  align-items: 'center';
`;
```

this code throws an error

```
ScrollView child layout (["alignItems"]) must be applied through the contentContainerStyle prop.
```

## Expected Behavior

I'd expect styled components would apply the property to the correct element.

## Actual Behavior

I ended up writing

```js
const styles = StyleSheet.create({
  center: {
    alignItems: 'center',
  },
});

<ScrollView contentContainerStyle={styles.center}>
    {children}
</Scroll>
```

**Comment by xsokev** [comment]
I was able to perform this using the following:
``` js
const Scroll = styled.ScrollView.attrs({
  contentContainerStyle: props => {
    return {
      alignItems: 'center',
      justifyContent: 'center'
    }
  }
})``
```

**Comment by mxstbr** [comment]
Yep this is why we added `.attrs`! Please use v2 and the `.attrs` helper to add styles to other props.

**Comment by cloud-walker** [comment]
its not possibile to use the `css` helper here?

```javascript
const Scroll = styled.ScrollView.attrs({
  contentContainerStyle: () => css`
    align-items: center;
    justify-content: center;
  `
})``
```

Its a bit odd to return to use object literal for this situation 🤔

**Comment by quantumproducer** [comment]
Bump, Subscribing

**Comment by LRNZ09** [comment]
I'm also having this issue on version `4.1.3`

**Comment by kolkol69** [comment]
If you are using react native with typescript, you can use it like this
`
interface ScrollViewProps {
  // usually I define here any props passed from component to style
}
const StyledScrollView = styled.ScrollView.attrs<ScrollViewProps>({
  contentContainerStyle: () => css`
    align-items: center;
  `,
})``;
`

**Comment by yhenni1989** [comment]
> If you are using react native with typescript, you can use it like this
> 
> ```ts
> const StyledScrollView = styled.ScrollView.attrs(() => ({
>   contentContainerStyle: {
>     alignItems: 'center',
>   },
> }))``;
> ```

Nice one! Why does this one relate to TypeScript only ?

**Comment by MaffooBristol** [comment]
kolkol69's answer is correct because styled-components has now deprecated the earlier method (as in, you should make attrs directly return a function rather than an object)

**Comment by dhruvash2u** [comment]
> If you are using react native with typescript, you can use it like this
> 
> ```ts
> const StyledScrollView = styled.ScrollView.attrs(() => ({
>   contentContainerStyle: {
>     alignItems: 'center',
>   },
> }))``;
> ```

To use your method, should I install or import any dependencies ??? 
if yes what should I do ??
please help!

**Comment by MaffooBristol** [comment]
@dhruvash2u No extra dependencies, it's built into styled-components. What have you tried so far? If it's not working with your current code, could you please share it?

**Comment by FaisalKhawaj** [comment]
I was using simple react native but when i used native base and placed everything in <Container> <Context>  it gives me this error. 
some one please guide me

**Comment by streuby** [comment]
This worked for me with react-native

const Scroll = styled.ScrollView.attrs((props) => ({
    contentContainerStyle: {
      flexGrow: 1,
      padding: 20,
    },
  }))`
    flex: 1;
  `;

**Comment by MaxInMoon** [comment]
Typescript : 

```
export const StyledScrollView = styled.ScrollView.attrs((props) => ({
  contentContainerStyle: {
    backgroundColor: "red", // default contentContainerStyle
    padding: 20,
    ...(props.contentContainerStyle as object), // override contentContainerStyle
  },
}))(() => ({
  // scrollview styles
}));
```
