### ISSUE TITLE
[V2] ThemeProvider only accepts single child

### ISSUE THREAD

**Issue by 0x80** [styled-components/styled-components#786]
I was trying to do something like this

```html
<ThemeProvider>
  <PageSection/>
  <PageSection/>
</ThemeProvider>
```

when I got `Invariant Violation: React.Children.only expected to receive a single React element child.`. Is there a reason `ThemeProvider` doesn't accept multiple children? Considering the provided functionality I would expect this to be quite trivial to implement, but maybe I'm overlooking something...

**Comment by k15a** [comment]
ThemeProvider would have to wrap the children in a div if it accepts multiple children because it only can return a single component. If the user has to pass a single children to ThemeProvider he can decide whether a extra div is needed.

**Comment by 0x80** [comment]
@k15a Thank, that makes sense now I think about it.
