### ISSUE TITLE
[V2] camelCased properties are not working the same in 2.0

### ISSUE THREAD

**Issue by bhough** [styled-components/styled-components#787]
Working on potentially moving polished over to using camelCased properties (https://github.com/styled-components/polished/issues/167) and in testing with 2.0 discovered that this seems to no longer be working the same way it did in V1.

They work when passed as objects within the string interpolation, but previously they worked without needing to be in an object.

Is this an intentional change we should be aware of?

## Version
2.0.0-17

## Reproduction
Doesn't work in 2.0.0-17: https://www.webpackbin.com/bins/-Kk-yp0vQFWgMO9gRTd0
Works in 2.0.0-17 (as object): https://www.webpackbin.com/bins/-Kjqz5YRz2-dp7NREedN
Works in 1.4.6: https://www.webpackbin.com/bins/-Kk-z5JKXRiM6WrhzTux

## Steps to reproduce
Add any CSS property using the camelCased version.

## Expected Behavior
The property is converted to the hyphenated version.

## Actual Behavior
The property is left camelCased and is invalid.

**Comment by philpl** [comment]
It indeed doesn't work, but to make it work we'd have to write a stylis middleware for something that I'd consider unexpected behaviour. I'm kind of baffled as to why this was part of styled-components v1 in the first place, i.e. where it was coming from before. Was it part of a postcss plugin that we used?

I don't think that we should fix this regression in v2 as it is one of the features that moves it farther away from actual CSS.

cc @geelen

**Comment by mxstbr** [comment]
The whole reason we added that was to make it possible for `polished` to support all CSS in JS solutions...

**Comment by geelen** [comment]
Yeah this came about because we converted everything from CSS to objects to use inline-style-autoprefixer then back to CSS string to use PostCSS. So this is behaviour I'm happy to lose.

FYI, if you use camel cased CSS properties inside _objects_, v2 works just fine:

```js
const Title = styled.h1`${{
  fontSize: '1.5em',
  textAlign: 'center',
  color: 'palevioletred'
}}`
```

Reproduction: https://www.webpackbin.com/bins/-KkjGYcrLZDO1doiMjEN

So, this shouldn't affect polished at all, right?

**Comment by geelen** [comment]
Oh right I just re-read your original issue. Yep, I don't see any reason to restore this behaviour from v1 to v2 as long as objects still work 100%.

**Comment by bhough** [comment]
Thanks folks! Just wanted to a) point it out in case it was unintentional and b) make sure that was going to be the case going forward just so we didn't end up building any functionality that assumed it (unlikely).

**Comment by mxstbr** [comment]
Oh yeah now that I re-read the initial issue that's perfectly fine, my bad! I thought it didn't work inside objects.
