### ISSUE TITLE
[V2] Placement of nested media queries breaks remaining nested styles in 2.0

### ISSUE THREAD

**Issue by bhough** [styled-components/styled-components#788]
Testing polished modules with 2.0 I came across this issue with the ordering of nested media queries in relation to other nested selectors in the same block. Moving the media query to the bottom of the block fixes it.

## Version
2.0.0-17

## Reproduction

Doesn't work with 2.0.0-17: https://www.webpackbin.com/bins/-Kk10y6IroX5Lo4gdO9j
Works with 1.4.6: https://www.webpackbin.com/bins/-Kk0u3Av2AAiXGvosxSg
Looks like it probably broke with 2.0.0-12 as 2.0.0-11 works: https://www.webpackbin.com/bins/-Kk11Qym5xQWn634CqWh

## Steps to reproduce
Nest a media query followed by another nested selector (:focus for example).

## Expected Behavior
Placeholder text should be pink (orange when focused).

## Actual Behavior
All the styling of nested elements after the media query are ignored (placeholder text stays grey).

**Comment by thysultan** [comment]
Thanks for finding this, the bug was in stylis, pushed a patched in the latest release(v2.0.9), the problem was in how it was vendor prefixing `::placeholder`, which only revealed itself when `::placholder`appearer after a `@media` block.

```css
@media (min-width: 537px) {
  border-bottom: 4px solid red;
}

&::placeholder {
  color: pink;
}
```
