### ISSUE TITLE
[Proposal] Decouple styles from elements

### ISSUE THREAD

**Issue by CompuIves** [styled-components/styled-components#790]
I've used `styled-components` in most of my recent projects and I love it! Thanks a lot for this library.

I like the idea of removing the mapping between component and classNames, though I think we're missing flexibility.

## 'Problem'

We currently do this:

```jsx
const Button = styled.button`
  color: white;
  font-size: 2rem;
`;

<Button>Hello</Button>
```

This is very easy to read and clear, but if we, for example, use this on other examples:

```jsx
const List = styled.ol`
  color: black;
`

const Item = styled.li`
  color: gray;
`

<List>
  <Item>test</Item>
  <Item>test2</Item>
</List>
```

It's harder to determine if `List` is an `ol` element or a `ul` element without searching for the styled component definition first.

Also, when I want to share styles between a `button` and an `a` component we need to have a separate style function that's shared:

```jsx
const styles = (props) => `
  color: ${props.theme.white};
`;

const Button = styled.button`
  ${styles}
`;

const LinkButton = styled.a`
  ${styles}
`;
```

This is complicated and the interpolations are handled differently.

So the two main pain points (for me) are:

1. It's unclear what HTML element is used when using a styled component
2. It's unclear on how to share styles between different html elements.

## Solution

This can be fixed by decoupling the HTML styles from the styling of the components. 
My suggestion is to use an API like this:

```jsx
const Button = styled`
  color: blue;
  background-color: green;
`;

<Button.a href="https://codesandbox.io">Go</Button.a>
<Button.button onClick={this.go}>Go</Button.button>
```

This is, in my opinion, still easy to read, you can see the HTML elements that are used and it's possible to reuse styles between elements.

If you still want to couple the styles to elements you can do this:

```jsx
const Button = styled`
  color: blue;
  background-color: green;
`;

export default Button.button;
```

This implementation has a problem as well, for some reason this is invalid JSX:

```jsx
<Foo(Bar) />
```

I don't know why, since `React.createElement(Foo(Bar), null, "Test");` is still valid. Would be cool if someone could explain this to me.

This can be solved by doing this:

```jsx
const Button = styled`
  color: blue;
  background-color: green;
`;

const LinkButton = Button(Link);

<LinkButton />
```

or by writing a babel plugin that can transpile it to valid JavaScript.

I can see that invalid `<Foo(Bar> />` could be the no-go of this approach. Still, I'm curious what you guys think of this concept.

From what I could find this issue is partially relevant: https://github.com/styled-components/styled-components/issues/316.
This is also applicable to other styling solutions. cc @kentcdodds.

**Comment by k15a** [comment]
Hey,

there was a big discussion here about his here: https://github.com/styled-components/styled-components/issues/494

You can also use the `css` helper to share styles between different elements.

```js
const styles = css`
  color: ${props => props.theme.white};
`;

const Button = styled.button`
  ${styles}
`;

const LinkButton = styled.a`
  ${styles}
`;
```

For the other problem you could give them different names like you did in your last example:
- `UnorderedList` vs `OrderedList`
- `Link` vs `ButtonLink`

If you want to share styles between them you can always use the css helper:

```js
const buttonStyles = css``

const Button = styled.button`
  ${buttonStyles}
  // button tag specific styles
`

const LinkButton = styled.a`
  ${buttonStyles}
  // a tag specifc styles
`
```

So all in all we recommend to use different names and share styles with the css helper. For the reasons why we don't want to decouple the styles from the elements you can read the discussion linked above.

I hope that helped you.

**Comment by mxstbr** [comment]
If we would allow an API like that we'd go back to where we were before:

```JS
// Vanilla:
<a className="button" />
// If we allowed the decoupling in styled-components
<Button tagName="a" />
```

**Comment by CompuIves** [comment]
Thanks a lot for linking the other discussion. Some great insights over there.

I'd say there is a difference between:

```jsx
<a className="button" />
```

and 

```jsx
<Button tagName="a" />
<Button.a />
```

There's an inherent mapping between the styles and the component in the second snippet, which I thought was the primary purpose of `styled-components`.

There are also some other use cases that are less obvious for needing multiple tags, but these are already mentioned in the other discussion. Tag independent styles are in my opinion one of the strengths of CSS, since this makes styles more reusable and tags sometimes exist for SEO rather than display purposes.

Thanks for the clarification, I'll think about this some more. I see that some of the mentioned issues in the other discussion are already fixed in v2, which is great!

**Comment by kentcdodds** [comment]
From the glamorous perspective, if you want to separate the component from the styles, then might I suggest using glamor directly?

```jsx
import {css} from 'glamor'
const button = css({/* your styles */})
<a {...button} />
<a className={button} />
```

Nice thing about this is sharing styles is pretty easy because they're just objects and glamor's API composes them nicely: `css(style1, style2, styles3)` (styles3 wins in the event of a conflict).

With this in mind, you could get the same thing with glamorous, where you share the styles objects and just pass those around when you make glamorous components, or use the jsx-style inspired API:

```jsx
<glamorous.Div css={someStyles} />
```

Many options here.
