### ISSUE TITLE
Unable to change page background via ThemeProvider and injectGlobal

### ISSUE THREAD

**Issue by three60five** [styled-components/styled-components#793]
My app has a "light" and "dark" theme. Right now, I set the background color of the page using `injectGlobal` and css on the html element, like:

```js
injectGlobal`
  html {
    background-color: #FFFFFF;
  }
`;
```

When trying to use the ThemeProvider component to change themes, I am unable to change the background color via the theme props. Is this use case supported? If not, what workarounds are supported?

**Comment by k15a** [comment]
You can't access the theme with `injectGlobal`. You could either style the highest component or use the `withTheme` helper to set the `background-color` with css:

```jsx
const Root = styled.div`
  background-color: ${props => props.theme.backgroundColor};
`
```

```jsx
import { withTheme } from 'styled-components'

const InjectGlobals = ({ theme }) => {
  document.body.style.backgroundColor = theme.backgroundColor

  return null
}

export default withTheme(InjectGlobals)
```

**Comment by three60five** [comment]
Thanks for the suggestions!

**Comment by creaux** [comment]
I found this as a best solution.

```javascript
import { Children } from 'react';
import { withTheme, injectGlobal } from 'styled-components';

const Global = ({ theme, children }) => {
  injectGlobal`
      font-family: ${theme.typography.secondary};
      color: ${theme.colors.dark}
    }
  `;
  return Children.only(children);
};

export default withTheme(Global);
```

**Comment by mxstbr** [comment]
See #1333 and the WIP PR for `createGlobalStyle` in #1416, this will very soon be much easier! :party:
