### ISSUE TITLE
ES6 React class using withTheme HoC causes flow errors

### ISSUE THREAD

**Issue by hongymagic** [styled-components/styled-components#794]
## Version
- 1.4.6
- Also uses flow-typed to pull styled-components definitions
- `flow-bin@0.46`

## Reproduction

https://github.com/hongymagic/bug-withTheme-styled-components

## Steps to reproduce

Pull above repo, then run `yarn && yarn flow`

## Expected Behavior

No errors to be reported by flow

## Actual Behavior

Flow reports errors. 

Seems like Flow interprets the `class Bar extends React.Component` as class type which is incompatible with `withTheme(component: Component)`.

It does not complain about the functional component.

There seems to be two errors here:

1. Input type to `withTheme`; and
2. Output type of `withTheme`.

The fixes _could_ be:

[Change both occurrences of `React$Component<...>` to `Class<React$Component<...>>` in flow type definition](https://github.com/hongymagic/bug-withTheme-styled-components/commit/7730f0209688a7a565c53f4c7789290af7922cda). Or maybe I've done something stupidly wrong, either way would love some feedback to close this issue.

**Comment by jebeck** [comment]
Also exists in styled-components v2, and same fix also works in my use case, which is using react-redux's `connect()` as well, i.e., `withTheme(connect(...)(MyComponent))`.

**Comment by relekang** [comment]
I have been playing around with the code in the reproduction error, but haven't gotten a solid fix yet. I have to read up on wrapping things in `Class<...>` to know if that is something we should do.

**Comment by tomasdev** [comment]
Also having this issue :(

BTW, the important piece is at https://github.com/hongymagic/bug-withTheme-styled-components/blob/master/src/Bar.js

**Comment by beautyfree** [comment]
With the latest version of packages, the problem is not reproduced. It seems possible to be closed
