### ISSUE TITLE
[v2]  SSR: styles generated on the server are missing a `key`

### ISSUE THREAD

**Issue by wmertens** [styled-components/styled-components#796]
## Version
2.0-rc 17

## Steps to reproduce

Follow the instructions to get a `styles` array from SRR. Use this in a prerender HTML react template.

## Expected Behavior

Everything works fine

## Actual Behavior

the `styles` array is an array of react elements without keys. This results in an error like 
```
Encountered two children with the same key, `5:$`. Child keys must be unique; when two children share a key, only the first child will be used.
```

**Comment by k15a** [comment]
Is this the same bug as https://github.com/styled-components/styled-components/issues/777?

**Comment by wmertens** [comment]
I only noticed the empty keys, but yes. Sorry for the noise.

**Comment by k15a** [comment]
No worries at all :)
