### ISSUE TITLE
key attribute is missing when re-styling a component

### ISSUE THREAD

**Issue by eric-burel** [styled-components/styled-components#797]
## Version
1.4.4

## Steps to reproduce

Styling an existing component and make it child of an iterator:

```jsx
const CenteredRow = styled(Row)`
display:flex;
justify-content:center;
`;

export default (props) => (
    <div>
    {props.rows
      .map(row => (
        <CenteredRow key={row.id}/>
     )
    }
    </div>
)
```

## Expected Behavior

Key attribute should be kept into the styled component, to prevent React from triggering a warning.
```js
<Styled(Row) key="foobar">
    <Row />
</Styled(Row)>
```
## Actual Behavior

Key attribute is simply removed. The tree looks like this:
```js
<Styled(Row)>
    <Row />
</Styled(Row)>
```

**Comment by k15a** [comment]
Could you post a reproduction on webpackbin.com or codesandbox.io?

**Comment by bhough** [comment]
@eric-burel Let me know if something is off about this recreation: https://www.webpackbin.com/bins/-KkgXDtZwLRZlrVeV8yH

It appears to be working as expected. Do the items in`props.row` have an id field? It appears it could be happening because`row.id` doesn't exist.

**Comment by philpl** [comment]
The `key` prop will not be visible in the child component. You can inspect it however in the React devtools. Since the prop is an internal to React it can't be filtered / removed / left out / etc. :wink:

I hope that answers this question

**Comment by eric-burel** [comment]
Well well well, guess what, the value I used as key was... undefined :) I hope one day Flow will allow me to catch this kind of mistakes. This is now solved.
Thanks for your help!
