### ISSUE TITLE
React Native Debugger doesn't show styles

### ISSUE THREAD

**Issue by bernatfortet** [styled-components/styled-components#805]
## Version
2.0.0-15

## Steps
- Create a styled component 
- Give it some styles
- Use React Native Debugger to inspect the created components

## Expected Behavior
- the styles used for the component should show up in the inspector

## Actual Behavior
- There's no styles at all

**Comment by k15a** [comment]
I can't reproduce this:

Styled Component:
```js
const Box = styled.View`
    flex: 1;
    align-items: center;
    justify-content: center;
    padding-top: ${Constants.statusBarHeight};
    background-color: blue;
`
```

![bildschirmfoto 2017-05-22 um 10 44 30](https://cloud.githubusercontent.com/assets/20357450/26299628/c470293a-3edb-11e7-9d6a-0881c3f4f5f8.jpg)
![bildschirmfoto 2017-05-22 um 10 44 43](https://cloud.githubusercontent.com/assets/20357450/26299629/c475c5a2-3edb-11e7-9f54-78c5e9eab247.jpg)

**Comment by imagentleman** [comment]
@k15a i believe @bernatfortet meant https://github.com/jhen0409/react-native-debugger not https://github.com/facebook/react-devtools/tree/master/packages/react-devtools

Created an issue on React Native Debugger, seems like it belongs there (https://github.com/jhen0409/react-native-debugger/issues/339)

btw @bernatfortet did you manage to fix that issue somehow?
