### ISSUE TITLE
Low-level API for testing injected styles?

### ISSUE THREAD

**Issue by 1999** [styled-components/styled-components#810]
Hey,

I couldn't find the proper way to test injected styles in the docs. Currently I'm trying to add assertions for injected styled component CSS property, but there's no styled-components' low level API for that.

What do I need to do here:

```typescript
import assert from 'assert';
import { shallow } from 'enzyme';
import styled from 'styled-components';
import { getStyledComponentStyles } from 'styled-components'; // proposal

const Button = styled.button`
  width: auto;
  color: ${(props: ButtonProps) => props.active ? 'black' : 'grey'};
`;

const mountedButton = shallow(<Button active={false}/>);
const buttonStyles = getStyledComponentStyles(mountedButton);

assert.strictEqual(buttonStyles.width, 'auto');
assert.strictEqual(buttonStyles.color, 'grey');
```

This is just an example of how I want to test the code.
It also seems like @george-payne's [solution](https://github.com/styled-components/styled-components/issues/118#issuecomment-297127524) is not working anymore (I can't find the "componentStyleSheet") and moreover it's too fragile to use it inside production tests.

Can you suggest me some solution here?

**Comment by k15a** [comment]
If you use Jest you can use [jest-styled-components](https://github.com/styled-components/jest-styled-components) which is pretty awesome. Otherwise, you probably can find an answer in the source code of it.

**Comment by 1999** [comment]
Unfortunately I don't use jest. After looking inside the code, I'm a bit surprised how it even works:
https://github.com/styled-components/jest-styled-components/blob/master/src/matchers/toHaveStyleRule.js#L6
https://github.com/styled-components/styled-components/blob/master/src/index.js#L37

There's no such thing as styleSheet in styled-components exports.

**Comment by 1999** [comment]
I was given the advice by @alexreardon and it's probably the best solution for 1.x version:

> For now the best you can do is export the style function and test them
