### ISSUE TITLE
v2 renders styles multiple times

### ISSUE THREAD

**Issue by chuanxie** [styled-components/styled-components#812]
in the v2, I try to use `sheet.getStyleElement()` in the html `head` section to render the styles for the SSR. but it renders multiple times like:  
`/* sc-component-id: sc-global-2635805295 */` style section couple times. 

I got the `injectGlobal` to set the body background image and fonts.
any idea?

**Comment by geelen** [comment]
Hmm that shouldn't be happening, can you post exactly what's being injected into the HEAD?

**Comment by chuanxie** [comment]
I move the css out of injectGlobal and it works fine now.
