### ISSUE TITLE
Feature request: isolated themes

### ISSUE THREAD

**Issue by alexreardon** [styled-components/styled-components#815]
Currently the `ThemeProvider` uses the key (`CHANNEL`) `__styled-components__` for its subscription function. I would like to put some values on a theme that I do not want consumers to have access to (they can also use styled components). One way of achieving this is to allow the ability to pass in a custom `channel` as a prop to `ThemeProvider`. This would allow different theme tree's to operate independently. If it cannot be a prop: then potentially there could be a function that returns a `ThemeProvider` when provided with a `channel`.

**Comment by k15a** [comment]
Probably the biggest problem with this is that the styled-components need to know the channel and if you have a different channel we can't figure out which theme do you want to use.

**Comment by alexreardon** [comment]
Great point @k15a. I did not think of the other end of the equation. I will have a think about it. In the mean time I have achieved the isolation of themes by prefixing particular values that go on the theme: (eg `private-theme-do-not-use:`). Then in the components that I want to know about it I can look them up. This achieves the desired outcome. However, I was thinking if there could be something in using different channels

**Comment by mxstbr** [comment]
I think namespacing solves this alright. At the beginning I thought the same thing with custom channels, but couldn't come up with anything that was nice to use and worked well, so we didn't implement anything.

If you have any ideas I'm happy to hear them! Until then I'll close this issue :blush:
