### ISSUE TITLE
Improve browser support

### ISSUE THREAD

**Issue by amsb** [styled-components/styled-components#82]
Using styled-components.com as an example, page rendering looks a bit spotty? I have similar experience with my own code using styled-components when tested on my Mac using the VirtualBox VMs provided by Microsoft. What are other people experiences? Is a polyfill needed?

![Browser test results](https://cloud.githubusercontent.com/assets/3449090/19397143/961ac834-9214-11e6-8648-0ac40414dd34.png)

[Browser screenshots powered by BrowserStack](https://developer.microsoft.com/en-us/microsoft-edge/tools/screenshots/?url=https%3A%2F%2Fstyled-components.com%2F)

**Comment by mxstbr** [comment]
It's interesting that it doesn't render on ID _at all_, not sure if that's a thing we messed up or react or something. Do you have access to logs in the console of those browsers? Let's get that support up!

**Comment by geelen** [comment]
Right it's due to missing `Symbol` on IE. We're not using it, but postcss is using `for (let x in y)` and babel transpiles that to something that uses Symbol.

There's a small `core-js` symbol polyfill we _should_ be able to use: https://github.com/zloirock/core-js/blob/v2.4.1/modules/es6.symbol.js

...but I won't get to that till tomorrow at the earliest. The real solution would be to change postcss to not use those loops, but that might be a while before I can do that one.

**Comment by amsb** [comment]
I updated [my example app](https://github.com/amsb/storybook_styled-components_example) to make it easier to test on the BrowserStack snapshots page Microsoft hosts and explicitly imported symbol from core-js at the top of my entrypoint (I think create-react-app might already be including it, but just to be sure). No luck, but maybe test doesn't remedy the need for Symbol deeper into the dependency tree?

**Comment by geelen** [comment]
Turned out to be easier than I thought. Pushed PR #91.

**Comment by amsb** [comment]
Thanks @geelen and @mxstbr! I confirm that my example app now renders on IE11. I assume the browser compatibility matrix for styled-components doesn't include IE10 or earlier since Microsoft isn't supporting these browsers on the desktop anymore themselves (with the exception of IE9 on Vista which will be EOL'ed April 2017).

Nevertheless, I'd be curious if any older versions of IE could be supported with a polyfill and think it would be helpful to have a sentence in the README communicating the browser compatibility targets.

**Comment by mxstbr** [comment]
> Nevertheless, I'd be curious if any older versions of IE could be supported with a polyfill

Is there any errors in the console for earlier versions? What's missing?

**Comment by amsb** [comment]
I downloaded an IE10 VM and dug deeper to find the issue, but someone else beat me to posting it and submitted #107. :)
