### ISSUE TITLE
Ready to use animations like Animate.css with styled-components

### ISSUE THREAD

**Issue by Tranzystor** [styled-components/styled-components#823]
Is there any possibility to use external library like [react-animations](https://github.com/FormidableLabs/react-animations) with styled-components?

I have a lot of code with styled-components and I'd like to avoid installing another styles engine (e.g. Aprhodite).

**Comment by k15a** [comment]
As far as I know this is not possible with styled-components. But you can always use the keyframes helper to create the animations.

```jsx
const fadeIn = keyframes`
  from {
    opacity: 0;
  }

  to {
    opacity: 1;
  }
`;

const Comp = styled.div`
  animation: ${fadeIn} 2s linear;
`
```

**Comment by Tranzystor** [comment]
Thanks for an answer.

That's the point that I would like to use prepared animations because it's faster and powerful. I have used _keyframes_ already but now I'd like to have more complex animations.

**Comment by k15a** [comment]
Mhh, I don't know if it's worth adding to styled-components just to support a single library.

**Comment by mxstbr** [comment]
You can use `react-animations` perfectly fine with styled-components: 

```JS
import styled, { keyframes } from 'styled-components';
import { fadeIn } from 'react-animations';

const fader = keyframes`${fadeIn}`;

const Title = styled.h1`
  font-size: 1.5em;
  text-align: center;
  color: palevioletred;
  animation: 1s ${fader} alternate infinite;
`;
```

Live demo: https://www.webpackbin.com/bins/-KktjocigcjvHnP_lPJp

**Comment by mxstbr** [comment]
Submitted a PR to react-animations to add an example: https://github.com/FormidableLabs/react-animations/pull/13

**Comment by chrischen** [comment]
React-animations is no longer updated.

**Comment by probablyup** [comment]
react-spring works great with styled components and supports hooks!
