### ISSUE TITLE
Interpolated style objects don't convert unitless number values to 'px'

### ISSUE THREAD

**Issue by kenwheeler** [styled-components/styled-components#825]
## Version
1.0.5

## Reproduction

https://codesandbox.io/s/kJGX2Qkr

## Steps to reproduce

Interpolate an object with a unitless value as shown above

## Expected Behavior

Unitless values would interpolate to add 'px'

## Actual Behavior
Unitless values are interpolated directly

**Comment by philpl** [comment]
Should be pretty simple. There was something inside react-dom that can even do this for us, since there's some properties that can be unitless e.g. `lineHeight`.

https://github.com/styled-components/styled-components/blob/master/src/utils/flatten.js#L10

**Comment by mxstbr** [comment]
We can't rely on the whitelist inside react Dom, since that'll get removed, and I'm also wary of introducing another whitelist. I'd rather not have this (pretty niche) feature that most people won't need than ship a bigger bundle to everybody?

**Comment by philpl** [comment]
@mxstbr Oh, it'll be removed? So you won't be able to use e.g `width` with a unitless number?

**Comment by kenwheeler** [comment]
That only applies to string values in React, width: '200' vs width: 200

**Comment by geelen** [comment]
Yeah I'm 100% against this. It comes up from time to time, even SC react native had unitless values until recently: https://github.com/styled-components/css-to-react-native/issues/20

Basically, there is no "default" unit in CSS. Most people think in pixels, but there are good reasons why that's not a good thing to be further entrenching. If you ever want convincing that 95% of your units should be rems/ems, check this video: https://www.youtube.com/watch?v=jPOBVaomzLE (it had a huge impact on me and changed how I understood inheritance in CSS and why it's awesome).

Interpolations in SC are rendering to CSS blocks so apart from camelCase-to-kebab-case I don't want to pretend they're anything else. The `attrs` helper can let you pass objects straight through to the `style` attribute where React can do what it wants with, but for SC, like CSS, you gotta specify your units.
