### ISSUE TITLE
Supporting 'progressive' css

### ISSUE THREAD

**Issue by chrisgreg** [styled-components/styled-components#826]
Just inspired from [Jake Archibalds comment on styletron](https://github.com/rtsao/styletron/issues/137) - and was curious if styled-components was thinking about supporting progressive CSS in v3 when static css extraction is ready?

@philpl mentioned his idea of using SSR + static css extraction to identify common CSS, splitting it from the page critical CSS then using webpack bundle splitting to check which components have common css and run the extraction there.

Thoughts?

**Comment by stereobooster** [comment]
Is there issue dedicated to static css extraction? Or some place where discussion about this feature happens?

**Comment by philpl** [comment]
@stereobooster No, I'll probably spike it in the next weeks as it's quite a lot of changes and then discuss it separately in the PR.

**Comment by philpl** [comment]
This won't actually be possible, even with the changes we're making in v3 (except if it'll be available as an option) because of the same reasons that we likely won't support static CSS extraction: https://github.com/styled-components/styled-components/issues/1018
