### ISSUE TITLE
ThemeProvider breaks react-storybook

### ISSUE THREAD

**Issue by amsb** [styled-components/styled-components#83]
I'd appreciate any pointers as I'm not sure where things break down when using styled-components `ThemProvider` with [react-storybook](https://github.com/kadirahq/react-storybook). I only experience this problem when wrapping the `styled` component in `ThemeProvider`. I created a minimal example repo that demonstrates the problem I'm experiencing:

https://github.com/amsb/storybook_styled-components_example

Here's what happens when I attempt to navigate in storybook after viewing a styled component wrapped in `ThemeProvider`:

![demo](https://cloud.githubusercontent.com/assets/3449090/19400666/31cb9df2-9225-11e6-91e6-e0b88a09fbd7.gif)

Same behavior if I remove the AddOn and directly wrap the component in `ThemeProvider` in the story itself. Maybe some conflict with context management when using `ThemeProvider` that blocks updates? There are no errors in the console.

**Comment by mxstbr** [comment]
Thank you for reporting this, I will take a look today! Sounds like they rely on some context updates which we might or might not be blocking.

**Comment by mxstbr** [comment]
Can you retry with `v1.0.4` of `styled-components`? If it was a context issue that should've fixed it.

**Comment by mnmtanish** [comment]
I just checked it out. The bug is still there.
https://github.com/mnmtanish/storybook_styled-components_example/pull/2

**Comment by mxstbr** [comment]
Thank you, this does seem to be something else then!

**Comment by amsb** [comment]
No errors in console.

**Comment by arunoda** [comment]
@mxstbr I didn't try this yet or read the code in full.
But I suspect the issue lies [here](https://github.com/styled-components/styled-components/blob/master/src/models/ThemeProvider.js#L36)

Components rendered on Storybook never see `componentWillReceiveProps` hook. That's because we always do the initial rendering.

**Comment by mxstbr** [comment]
> Components rendered on Storybook never see componentWillReceiveProps hook. That's because we always do the initial rendering.

I don't quite understand this – shouldn't the components still receive props?

**Comment by arunoda** [comment]
@mxstbr`componentWillReceiveProps` is no called in the initial render. In React Storybook, we only the do the initial render.

**Comment by thuringia** [comment]
Hi everyone,
not sure if this is related but I get a TypeError due to `ThemeProvider#unsubscribeToOuter` being undefined in `componentWillUnmount`.

**Comment by mxstbr** [comment]
@thuringia which version are you on? I'm pretty sure we fixed that a week or two ago!

**Comment by thuringia** [comment]
@mxstbr apparently we're still using 1.0.3. Seems like somebody pinned the versions without my knowledge. Sorry!

**Comment by jjstrat3** [comment]
@arunoda pardon my ignorance, but your statement about React Storybook only doing the initial render confuses me.  With addons like *Knobs*, I'm able to change props in realtime...how would this be different??

**Comment by kopax** [comment]
Is react-storybook now working with styled ?

**Comment by vernondegoede** [comment]
Yes, it's working fine. Just use the `addDecorator` method which comes with react-storybook.

**Comment by kopax** [comment]
@vernondegoede what should be the parameter passed to `addDecorator` ?

**Comment by vernondegoede** [comment]
@kopax https://gist.github.com/vernondegoede/0575d268d52e00f221cc86057fb938d1

**Comment by sternamuller** [comment]
I'm brand new to storybook. Getting this error: 
ThemeProvider: Please make your "theme" prop an object.
Any advise please?
