### ISSUE TITLE
Consistent Logo

### ISSUE THREAD

**Issue by una** [styled-components/styled-components#831]
## Version
1.0.5

## Reproduction

The emoji can vary depending on systems
https://twitter.com/mxstbr/status/867110085574701058

## Expected Behavior

Consistent Logo Refresh

## Explanation

It might be nice to update the logo a bit to move away from an emoji :)

## Explorations

![screen shot 2017-05-25 at 3 18 18 pm](https://cloud.githubusercontent.com/assets/1693164/26452510/7e9578b6-4160-11e7-9eb4-645f6e8b618b.jpg)

![screen shot 2017-05-25 at 3 33 56 pm](https://cloud.githubusercontent.com/assets/1693164/26452522/8aa88b66-4160-11e7-8db7-b12e72060430.jpg)

![screen shot 2017-05-25 at 3 36 10 pm](https://cloud.githubusercontent.com/assets/1693164/26452528/8e66c9f2-4160-11e7-8b75-9f43be189008.jpg)

**Comment by geelen** [comment]
Whoa. This... is your work right Una? This isn't just a particularly rad emoji on some platform I haven't seen yet, right? Cause I :heart: it.

**Comment by mxstbr** [comment]
I dig that gradient 😍 

Unsure if I like the compact version, it feels a bit unbalanced to me with the S and the reverse C.

**Comment by diondiondion** [comment]
Hm, the fact that it's using an emoji & context & platform dependent is what makes it charming to me.

I'd even go all in with it and replace all images on the website that have the emoji "baked in" with dynamic svgs that let the browser render it. But not sure what browser support looks like for that.

**Comment by philpl** [comment]
I think it'd be great to preserve the original feel of the border and the balance and just replace the emoji for now :) Also we need to make sure that the colours of the Emoji match the gradient of the new website ;)

**Comment by geelen** [comment]
Yeah that's why I've liked the default emoji with yellow skin tone. Alternatively we could randomly pick a skin tone every time the page is loaded.

**Comment by una** [comment]
RE: skintone, I chose a mid-tone one so it was more ambiguous. Yellow emoji hand (and other yellow emoji people) always makes me think of jaundice 😬

**Comment by probablyup** [comment]
Okay, I had a little "creative storm" and came up with this concept I'd like to call "engineer's salute":

![5075eb00-6390-4cea-9ca6-5b52728f4b2b](https://user-images.githubusercontent.com/570070/34645035-d8dca606-f311-11e7-8030-205eda6c7b13.JPG)

I wanted to make something that felt powerful. Impactful. Uplifting. Inclusive.

Can someone translate this into a graphic?

**Comment by probablyup** [comment]
I ended up resketching it in emoji-esque form:

![img_0492](https://user-images.githubusercontent.com/570070/35207131-4eff8bce-ff0f-11e7-94d4-6bd2d5c32209.jpg)

And this is my first try vectorizing it and doing some coloring like in the original drawing... idk I feel like the colors need to be softer or something.

![artboard 2](https://user-images.githubusercontent.com/570070/35207119-387d30ea-ff0f-11e7-8205-134106a8fad9.png)
