### ISSUE TITLE
encoding issue with v2

### ISSUE THREAD

**Issue by luisrudge** [styled-components/styled-components#832]
After upgrading my nextjs app to v2, I'm seeing an encoding issue with strings

## Version
2.0.0

## Expected Behavior (`v 2.0.0-7`)

![image](https://cloud.githubusercontent.com/assets/941075/26453644/deb24f74-413a-11e7-86a6-2fa914426b63.png)

## Actual Behavior

![image](https://cloud.githubusercontent.com/assets/941075/26453709/0af3d9b8-413b-11e7-9105-667faaf99ea7.png)

**Comment by philpl** [comment]
Interesting but I'm not sure how styled-components could affect this :/ are the meta tags if your site correct? And did any of the file encodings change to sth else than utf8?

**Comment by luisrudge** [comment]
Hmm.. I had to put my `<meta charSet="utf-8" />` as the first tag inside the `<head>` tag. Not sure why though 😝 
![image](https://cloud.githubusercontent.com/assets/941075/26454285/0e08a000-413d-11e7-9d3b-208209885e20.png)
