### ISSUE TITLE
Unitless properties in React Native

### ISSUE THREAD

**Issue by iRoachie** [styled-components/styled-components#835]
## Version
2.0.0 - styled-components
0.44 - React-native

## Steps to reproduce
Make a styled component having a property of padding: 16

## Expected Behavior
It should apply 16 padding on each side of the element

## Actual Behavior
Shows error in simulator

![screenshot_1495739199](https://cloud.githubusercontent.com/assets/5962998/26466182/cefb12ca-415b-11e7-831d-98aa2de38fe5.png)

**Comment by jukben** [comment]
Same with `margin`.

**Comment by geelen** [comment]
Hmm, not sure why the expanded properties aren't working, but I think you need to start adding `px` to lengths now across the board: https://github.com/styled-components/css-to-react-native/issues/20

**Comment by iRoachie** [comment]
Why should you need to add pixels? I understand this for browsers, but pixels is not a unit of measurement on mobile devices

**Comment by MatthieuLemoine** [comment]
Due to [styled-components/css-to-react-native#20](https://github.com/styled-components/css-to-react-native/issues/20), v2 is not a drop-in replacement. Migration from v1 is a burden because you have to replace all unitless rules as ```unitless === %``` now.

I think that this breaking change for RN users should be written in the README or in the documentation and added in the [blog post announcing v2](https://medium.com/styled-components/announcing-v2-f01ef3766ac2)

**Comment by mxstbr** [comment]
Yep sorry, I forgot to write that down. Mind submitting a Pull request to add a notice to the website?

**Comment by mxstbr** [comment]
There's a codemod to do this conversion for you, by the way!

**Comment by MatthieuLemoine** [comment]
@mxstbr Sure ! Can you share the link to the codemod ?

**Comment by k15a** [comment]
https://github.com/styled-components/styled-components-native-code-mod

**Comment by philpl** [comment]
@mxstbr @geelen I opened a discussion over here, since this is in theory an inconsistency with the single-value properties https://github.com/styled-components/css-to-react-native/issues/40

**Comment by iRoachie** [comment]
Is there any reason why the default for unit less values is percentages? This is really weird on mobile. Shouldn't stylesheet, inline and styled-components share the same api/structure?

**Comment by dbertella** [comment]
I don't know, I read everything you wrote about it but I'm not hundred percent sure it's the right thing to do, I mean, it looks wrong to me to add `px` to every (not every actually, some) margin and padding, I migrate to v2 just few hours ago and I had quite a work to do in my app that is not that big.
Not to mention that if you have some mixed code, some styled-components and some old stylesheets, or inline styles you will have to completely different behaviours from now on.

**Comment by mxstbr** [comment]
That's why there's a codemod that does all that work for you... https://github.com/styled-components/styled-components-native-code-mod

**Comment by iRoachie** [comment]
Having a codemod doesn't change the fact that the units aren't the same across styled-components, Stylesheet.create, and inline-styles. But I guess you guys already made up your minds. Thanks 👍

**Comment by mxstbr** [comment]
Totally open to more discussion about this! Don't just close the issue, we want to know about why this shouldn't be the way it is!

**Comment by jukben** [comment]
I'm personally also on the side of default behavior, which does not recognize px in Native context. I'm not seeing why I have to add 'px' while inline styles, etc. Work without it.

Also, the styles are not usually reused cross-platform, so the same behavior of the unit is not so important. Where is the main reason why v2 forcing adding px unit? What do you think?

**Comment by MatthieuLemoine** [comment]
@jukben In https://github.com/styled-components/css-to-react-native/issues/20 @jacobp100  said : 
> This would remove ambiguities in the flex shorthand, and would allow us to accept line-heights as a multiple of font-size in the font shorthand.

I don't think that cross-platform reuse is a good reason for enforcing unit as I have no issue doing cross-platform with styled v1 and react-native-web using unitless rules.

**Comment by dbertella** [comment]
I was thinking also that it should be react itself that should aim to have css cross platform not the `styled-componets` library on top of it. And correct me if I'm wrong but if you don't specify px in an inline style in react web it's already px by default, isn't it? I didn't try what happened with styled components, but I can see the point to have no unit by default!

I wouldn't force people to write px in react native because it can mislead people as well, we are not in the web are, we are not writing web view like I would expect using ionic for example. Here we are writing native code, and px has nothing to do with it.

In case we decide to keep the unit we have to document very well what needs px and what not as well, because it can be really weird that height and width don't require px but margin and padding do!

**Comment by geelen** [comment]
Yeah, these are fair points. There's only really the two units in React
native, right? px and percentage?

**Comment by jukben** [comment]
@geelen I actually thought that default unit in React Native is dp – density-independent pixels, isn't it? So there should be dp (usually written without unit) and percentage.

**Comment by iRoachie** [comment]
It's density independent. The reasons there's no unit is because the unit less property is converted to PT on iOS and DIP on android. If you actually want to get pixels, there's a method called getPixelSizeForLayoutSize

**Comment by jacobp100** [comment]
We're following the css spec: px units are density independent.

The biggest reason for following the spec (and requiring units) is that there's huge amounts of documentation already available for shorthands (MDN for example). In addition, the spec has put a lot of thought into shorthands and how to make them non-ambiguous.

**Comment by iRoachie** [comment]
@jacobp100 What does css have to do with mobile development? My point is that you should be able to use the same properties and values, with styled-components, Stylesheet.create(), and inline style={{}}. If you use pixels with either one of them it'll throw an error, because pixels is not a unit in mobile development. 
If i'm converting my react native app to use styled-components, I don't see why i should be using pixels, as it's not something that i've used before. It's really about keeping the developer in one frame of mind, and having not worry about a unit is a big plus.

**Comment by MatthieuLemoine** [comment]
I join @iRoachie on that. ```styled-components/native``` should mirror react-native API and allows similar rules declared with styled/Stylesheet/Inline style to work the same.

**Comment by MatthieuLemoine** [comment]
I get that the lib is named ```css-to-react-native``` and so it should follow the css spec and provides a mapping between css & RN styling API.
But styled-components/native users don't know about the ```css-to-react-native``` lib, they are accustomed to use unitless rules and the API provided by styled-components should not depend on another lib API.

**Comment by mxstbr** [comment]
> I get that the lib is named...

This has nothing to do with any name of any library, we wrote that specifically for `styled-components/native`. It does more than "just" append values.

----

The discussion here is basically:

- In v1 we mirrored the ReactNative StyleSheet API (just turned into strings)
- In v2 we decided to align more towards the CSS spec to get closer to actual CSS on ReactNative and provided a codemod to convert projects built on v1 into the way it works in v2. That wasn't communicated (that was 100% my bad) so it hit some people by surprise, thus this thread

The question boils down to: was the change towards CSS a communication or an API error?

**Comment by iRoachie** [comment]
I think we're really questioning why adding 'px' to a value should be required, and if it's the right way to go. 

Why would a unitless property be interpreted as % by default? 
If anything, why do some properties complain when not using px, and some do?

**Comment by morajabi** [comment]
i agree with @iRoachie Why?

**Comment by jacobp100** [comment]
@iRoachie 

> I think we're really questioning why adding 'px' to a value should be required, and if it's the right way to go.

It removes parsing ambiguity and is more intuitive coming from CSS—it's just CSS, not CSS-but-you-take-the-units-out.

> If anything, why do some properties complain when not using px, and some do?

For simple properties (`flex-grow`, `border-top-width`), numeric-like values (`1` and `1px`) are converted to numbers, and the rest (including `1%`) are converted to strings. This is because to enforce correct units on these simple properties, we would essentially create a whitelist of styles, which would need to be kept up-to-date with React Native.

However, for shorthand properties, we follow the spec; hence, units.

> unitless === %

> Why would a unitless property be interpreted as % by default?

See above—that's not quite true.

**Comment by iRoachie** [comment]
> It removes parsing ambiguity and is more intuitive coming from CSS—it's just CSS, not CSS-but-you-take-the-units-out.

Why is it based on CSS? I understand it uses react-native-to-css underneath, but what does that have to do with the react native developer that doesn't use 'px' at all?

I'm kinda getting that this issue is going around in circles with the same points being restated.

**Comment by jacobp100** [comment]
React Native's styling is based off CSS. It's most likely because they use objects for stylesheets that you don't write `px`.

**Comment by benjaminreid** [comment]
I'm going to tune in and say units _should_ be required.

My motivations for using `styled-components` (and what makes it so great) is for me to write as close to "normal" CSS as possible. This means using units regardless of what platform I'm building for.

I found it rather odd upon first using `styled-components` within React Native that I couldn‘t actually use the units, it went against my expectation.

Being able to copy some existing CSS that has units, paste it into React Native and it just work is also pretty cool.

🙃

**Comment by iRoachie** [comment]
@benjaminreid I have no prob with units. But if units are required, let **ALL** properties require units.

Typical example i just ran into in react native. `margin: 16px` works fine, `marginVertical: 16px` throws a red error screen. All these little things, the developer has to be constantly thinking about during working.

**Comment by benjaminreid** [comment]
@iRoachie Definitely, consistency is key. ✨

**Comment by jacobp100** [comment]
@iRoachie What error message are you getting when you try `marginVertical`? That should just work.

**Comment by iRoachie** [comment]
![screenshot_1496770677](https://user-images.githubusercontent.com/5962998/26843188-60399c06-4abd-11e7-90e8-5212af99481c.png)

**Comment by jacobp100** [comment]
And `marginVertical: 16` works?

**Comment by iRoachie** [comment]
Yup!

**Comment by jacobp100** [comment]
Can you try nuking your node_modules and reinstalling them?

**Comment by iRoachie** [comment]
@jacobp100 Did nothing

**Comment by iRoachie** [comment]
@jacobp100 So `marginVertical: 16` works, as well as `marginVertical: 16px`

**Comment by maurolionel** [comment]
For me it makes no sense having to add px as unit everywhere, especially when migrating from StyleSheet to styled-components/native.
I love not caring about units on ReactNative.
If you're migrating from web to native you have to import styled-components from /native now, it's predictable things could change.
I think it makes more sense to make some little changes on developer's code, for the sake of consistency between the library and the platform he's building the app for.
BTW: It would be more interesting being able to use em's or rem's for responsive font sizing.

**Comment by jacobp100** [comment]
You need to use pixels for letter spacing. This is on react native’s side, so not something we have control over

**Comment by ted-shinner** [comment]
allright then, i guess I'll have to cook up a formula based on pixel ratio and device measurements then!
