### ISSUE TITLE
Rollup errors?

### ISSUE THREAD

**Issue by geelen** [styled-components/styled-components#836]
Just noticed this locally:

`rollup-plugin-inject: failed to parse /Users/glen/src/projects/styled-components/styled-components/src/models/StyledComponent.js. Consider restricting the plugin to particular files via options.include`

Here it is on a recent travis run too: https://travis-ci.org/styled-components/styled-components/jobs/236046137#L310

Any ideas?

**Comment by santaclauze** [comment]
Same issue here. I use `styled-components` as well but my error comes from a styled-react-jsonschema-form -_-

**Comment by mxstbr** [comment]
I think this is due to circular imports, we had some of those in our vendor stuff that Rich got rid of when we moved to Rollup?

**Comment by mxstbr** [comment]
Don't happen anymore.
