### ISSUE TITLE
ServerStyleSheet typescript definition

### ISSUE THREAD

**Issue by juusaw** [styled-components/styled-components#838]
Hi,

Styled-components v2 is awesome, thanks! I'm using styled on a Typescript project and noticed that the SSR functionality, more specifically `ServerStyleSheet`, is missing Typescript definitions. I wrote the following definition to get around this. If it looks ok to you guys, I'd be happy to pull request.

```js
export class ServerStyleSheet {
  collectStyles(children: ReactElement<any>): ReactElement<any>
  getStyleTags(): string
  getStyleElement(): ReactElement<any>
  static create(): StyleSheet
}
``` 

I'd also add the following tests to `styled-component-test.tsx`

```js
// server-side rendering styles
const sheet = new ServerStyleSheet();
sheet.collectStyles(<ThemedButton name={name} />)
const styleString = sheet.getStyleTags();
const styleElement = sheet.getStyleElement();
```

**Comment by k15a** [comment]
Looks good to me :) PR would be cool 👍
