### ISSUE TITLE
Flow-typed libdef for v2

### ISSUE THREAD

**Issue by relekang** [styled-components/styled-components#843]
Just opening this task if someone is looking for v2 libdef so they know it is in progress. I am working on it at https://github.com/relekang/flow-typed/tree/fix/styled-components-v2. 

cc @styled-components/typers

**Comment by philpl** [comment]
Hiya, do you have any update on this? :) Unfortunately my Flow skills are not up to my TS skills, so I'd rather no offer my help. Sorry

**Comment by relekang** [comment]
Sorry no, my oss time has been spent on other stuff. I can take another try at it today and se how far I get.

I was wondering tho if we should take it back into the repo, but keep it as a libdef? Maybe put it in `typings/flow/index.flow.js` and `typings/flow/native.flow.js`. The workflow for adding it to the project would then be to install styled-components and add `node_modules/styled-components/typings/flow` under `[libs]` section of `.flowconfig`.

cc @ryyppy

**Comment by philpl** [comment]
@relekang It'd definitely be nicer, and I'm not quite clear on why we moved it over to flow-typed in the first place. Shouldn't it even add these libs automatically? I'm having some issues on v2 that it's using the included ones by default until I add the ignore statement to the config

**Comment by relekang** [comment]
> I'm not quite clear on why we moved it over to flow-typed in the first place.

This [tweet(-storm)](https://twitter.com/lbljeffmo/status/813434277018955776) 🙃 

> Shouldn't it even add these libs automatically?

The generate functionality in flow is currently broken as far as i know, have not had the time to test with 0.47 yet.

> I'm having some issues on v2 that it's using the included ones by default until I add the ignore statement to the config

Yeah, that should be fixed by my recent PR. One of the main problems here is that it surfaces relations with styled-components dependencies in the project using styled-components, which gives a bunch of weird errors. 

Moving to libdef was a good call, but I think it might make sense to keep them here. We could always PR them to flow-typed as well if people want to get them from there.

**Comment by IvanCoronado** [comment]
I am facing this problem just now. Waiting for that PR.
Thanks you @relekang

**Comment by relekang** [comment]
@philpl I opened the PR on flow-typed, it is not complete, but should be a good start. I will look into moving the libdef to this repo when I have more time. Need to figure out to test it without the flow-typed cli.

**Comment by relekang** [comment]
The PR was just merged to flow-typed. Please test it and report any issues here 🙏 

I did not get the time to add `attrs`, will look into that next week if nobody else want to fix it.

**Comment by kevin940726** [comment]
@relekang
Should this [line](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/styled-components_v2.x.x/flow_v0.25.x-/styled-components_v2.x.x.js#L17) be just `React$Component`? With the suffix of `<*, *, *>` fail my tests. Or is this my problem, doesn't have time to create a minimal example now 😢.

**Comment by relekang** [comment]
It should, if we remove `<*, *, *>` flow will complain that it is missing. What kind of errors are you getting?

**Comment by kevin940726** [comment]
I have been able to create a minimal project to duplicate the error. I create a project using `create-react-app` and use `styled-components v2.0.1`, `flow-bin v0.47.0`, and flow-typed. The main reason is that I use `styled` as a function and wrap with a custom component which is a class. And this is the error.

```
src/App.js:23
 23: const StyledApp = styled(App)`
                       ^^^^^^^^^^^ function call
 23: const StyledApp = styled(App)`
                              ^^^ class type: App. This type is incompatible with
 60:     (baseComponent: Component): StyledComponent,
                         ^^^^^^^^^ union: type application of identifier `React$Component` | function type. See lib: flow-typed/npm/styled-components_v2.x.x.js:60
  Member 1:
   20:   | React$Component<*, *, *>
           ^^^^^^^^^^^^^^^^^^^^^^^^ type application of identifier `React$Component`. See lib: flow-typed/npm/styled-components_v2.x.x.js:20
  Error:
   23: const StyledApp = styled(App)`
                                ^^^ class type: App. This type is incompatible with
   20:   | React$Component<*, *, *>
           ^^^^^^^^^^^^^^^^^^^^^^^^ React$Component. See lib: flow-typed/npm/styled-components_v2.x.x.js:20
  Member 2:
   21:   | (props: *) => React$Element<*>;
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. See lib: flow-typed/npm/styled-components_v2.x.x.js:21
  Error:
   21:   | (props: *) => React$Element<*>;
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. Callable signature not found in. See lib: flow-typed/npm/styled-components_v2.x.x.js:21
   23: const StyledApp = styled(App)`
                                ^^^ statics of App
```

Not sure what I was doing wrong here, sorry for not being able to help more. Tell me if you want a repo of the project 😄.

**Comment by relekang** [comment]
> Tell me if you want a repo of the project 😄.

That would be really helpful 🙂

**Comment by kevin940726** [comment]
@relekang 
[Here](https://github.com/kevin940726/styled-components-flow-typed) you go 😃 .

The steps I took.
1. create-react-app
2. `yarn add styled-components`
3. `yarn add -D flow-bin`
4. `yarn flow -- init`
5. ignore `node_modules` in `.flowconfig`
6. `flow-typed install styled-components@2.0.1`
6. Edit `src/App.js`
7. run `yarn flow`

What did I miss? Thanks in advance!

**Comment by corbanbrook** [comment]
I get the same errors, was able to fix it by making a small change to the installed flow-typed definition on line 19 to:

```
type $npm$styledComponents$Component =
  | ReactClass<*>
  | (props: *) => React$Element<*>;
```

**Comment by evenchange4** [comment]
@kevin940726 Flow-typed does not seem to be set up correctly. 

```diff
[libs]
# This is where your own flow-typed libdefs go
+flow-typed
```

[Here](https://github.com/MCS-Lite/mcs-lite/blob/master/.flowconfig#L18) is my project settings for reference. I think the issue is related to CRA [PR#2522](https://github.com/facebookincubator/create-react-app/pull/2522).

**Comment by kevin940726** [comment]
@evenchange4 hi 學長 😆 

But the flow documentation stated that (as far as my understanding) if we are installing via `flow-typed`, the libdef should _just work_ without explicitly specified in `.flowconfig`

> NOTE: Using the /flow-typed directory for libdefs is a convention that enables Flow to JustWork™ out of the box and encourages consistency across projects that use Flow, but it is also possible to explicitly configure Flow to look elsewhere for libdefs using the [libs] section of your .flowconfig.

Also, adding `flow-typed` under `[lib]` in `.flowconfig` does not work. 😢

**Comment by evenchange4** [comment]
Haha, 完全沒發現 @kevin940726 
I have clone your project, and you are right! I have no idea now. So weird. 😔

**Comment by luftywiranda13** [comment]
it's unnecessary to list `flow-typed` in `[libs]` https://flow.org/en/docs/config/libs/

**Comment by maxmalov** [comment]
Hey, do you have any plans for releasing libdefs for v3?

**Comment by probablyup** [comment]
https://github.com/flowtype/flow-typed/tree/master/definitions/npm/styled-components_v2.x.x

**Comment by probablyup** [comment]
@maxmalov see https://github.com/styled-components/styled-components/issues/1490, help wanted 😃
