### ISSUE TITLE
Typo in public site

### ISSUE THREAD

**Issue by tylerbrewer2** [styled-components/styled-components#845]
I was going to submit a PR for this...but I'm not sure where the new docs
 code is located. There's a small typo under "Attaching additional props", looks like there should be a space between "type" and "attribute." If the docs are open source I can submit a PR to fix it, otherwise thanks for making an awesome library and awesome docs 🎉 

<img width="954" alt="screen shot 2017-05-28 at 12 53 32 pm" src="https://cloud.githubusercontent.com/assets/10946524/26530553/f302e53a-43a4-11e7-8e9c-9be378140166.png">

**Comment by k15a** [comment]
The docs are at https://github.com/styled-components/styled-components-website. We are currently moving everything into a monorepo so we can do this as well. Nice spot :)

**Comment by tylerbrewer2** [comment]
@k15a awesome, just submitted the PR 👍

**Comment by mxstbr** [comment]
Thanks @tylerbrewer2! :tada:
