### ISSUE TITLE
Add info on how to contribute to v2 docs

### ISSUE THREAD

**Issue by JohnAlbin** [styled-components/styled-components#848]
I've searched this github repo for "docs" and "documentation, but other than the new website URL, https://www.styled-components.com/docs, I can't find any info on how to contribute to v2 docs.

**Comment by JohnAlbin** [comment]
Ah! I just found them in a new repo. https://github.com/styled-components/styled-components-website

**Comment by k15a** [comment]
We are currently moving everything into one repo.
