### ISSUE TITLE
Default Prop Interpolation

### ISSUE THREAD

**Issue by zhenyulin** [styled-components/styled-components#854]
It looks like currently the props are default to `undefined`, which makes it a bit too complex than it should be to define, for instance, default colors or any other styles.

**Comment by k15a** [comment]
They default to an empty object.

https://codesandbox.io/s/gL2V4R6ZG

**Comment by zhenyulin** [comment]
@k15a is there a way to define the default style via the interpolation of the default prop of the component?

something like this:
```export class Component extends PureComponent {
  static propTypes = {
     color: PropTypes.string
  };

  static defaultProps = {
    color: 'grey'
  };

 render(){
    ...
 }
}

export default styled(Component)`
  fill: ${prop => prop.color};
`;

Or is there a better way to do this?

**Comment by k15a** [comment]
Just use normal propTypes and defaultProps

```js
const Component = styled.div`
  fill: ${prop => prop.color};
`;

Component.propTypes = {
  color: PropTypes.string
}

Component.defaultProps = {
  color: 'grey'
}
```
