### ISSUE TITLE
Add TypeScript typings to 2.x

### ISSUE THREAD

**Issue by fruchtose** [styled-components/styled-components#855]
## Version
2.0.0

## Reproduction
Using TypeScript, try to write a component which is styled and mapped to a new component with `withComponent` and `extend`.

## Steps to reproduce
Try this code:

```ts
import styled from 'styled-components';

const Btn = styled.button``;

const BtnLink = Btn.withComponent('a').extend``;
```

## Expected Behavior
TypeScript compiles the component and outputs JS.

## Actual Behavior
TypeScript outputs the following error:

```
(5,21): error TS2339: Property 'withComponent' does not exist on type 'ComponentClass<ThemedOuterStyledProps<HTMLProps<HTMLButtonElement>, any>>'. 
```

## Notes
It looks like #646 was never addressed.

**Comment by philpl** [comment]
@fruchtose #646 was addressed but further updates are in progress here: https://github.com/styled-components/styled-components/pull/837

**Comment by fruchtose** [comment]
Great, thanks!
