### ISSUE TITLE
What are the supported browsers for styled-components autoprefixer?

### ISSUE THREAD

**Issue by jannisg** [styled-components/styled-components#856]
I've been looking through the docs and the Readme but couldn't find anything that actually states what the browser support is for `styled-components` once `autoprefixer` has done its thing.

I saw one (old) issue comment that mentioned that the `autoprefixer` preset matches the browser targets that `react` itself has (IE9+) but I think it would be good to add a small section to the docs about this *if* this is in fact the case.

Is there a definite answer/source where I can find the supported browser list?

**Comment by k15a** [comment]
We support everything that React supports and prefixes are added by [stylis](https://github.com/thysultan/stylis.js)

**Comment by mxstbr** [comment]
@jannisg good idea about adding that to the docs, mind submitting a PR against https://github.com/styled-components/styled-components-website? Thanks!

**Comment by kopax** [comment]
Hi, is this done? Or still no listing?

**Comment by mxstbr** [comment]
https://www.styled-components.com/docs/faqs#which-browsers-are-supported
