### ISSUE TITLE
styles wrongly composed when border-style is used

### ISSUE THREAD

**Issue by ivan-navarro-75** [styled-components/styled-components#857]
When I am using **border-style: solid** in combination with some other border properties the result that styled-components is returning me is not working

```js
const Input = styled.input`
  width: 100%;

  border-style: solid
  border-top-width: ${props => (props.underline ? '0' : '2px')};
  border-bottom-width: 2px;
`
```
is returning this:
```css
width: 100%;
border-style: solid border-top-width: 0;  <---BAD
border-bottom-width: 2px;
```

## Version
2.0.0-10

## Reproduction
https://www.webpackbin.com/bins/-KlTAoiCcv59O0CuMANn

**Comment by k15a** [comment]
You forgot a semicolon.

```js
const Input = styled.input`
  width: 100%;

  border-style: solid;
  border-top-width: ${props => (props.underline ? '0' : '2px')};
  border-bottom-width: 2px;
`
```

**Comment by ivan-navarro-75** [comment]
god! thanks! :weary:   

with the old version I didn't realize it.

**Comment by philpl** [comment]
The next patch version is going to use stylis 3 which adds missing semicolons :)
