### ISSUE TITLE
React Native does not overwrite existing Styles

### ISSUE THREAD

**Issue by JPeer264** [styled-components/styled-components#858]
## Version
StyledVersion: `2.0.0`
ReactNative: `0.43.3`
React: `16.0.0-alpha.6`

## Reproduction
```js
// you can copy this as is
import React from 'react';
import { View } from 'react-native';
import styled from 'styled-components/native';

const StyledText = styled.Text`
  color: red;
`;

const AlreadyStyledComponent = props => (
  <StyledText>{props.text}</StyledText>
);

const WhiteComponent = styled(StyledText)`
  color: white;
`;

const FailToOverwriteComponent = styled(AlreadyStyledComponent)`
  color: white;
`;

export default () => (
  <View>
    <AlreadyStyledComponent text="is red" />
    <WhiteComponent>Is white</WhiteComponent>
    <FailToOverwriteComponent text="should be white" />
  </View>
);
```

## Steps to reproduce
`FailToOverwriteComponent` is unable to overwrite the existing styles. If I pass just the styled components it works as I expected: `styled(StyledText)`. 

## Expected Behavior
`FailToOverwriteComponent` should be white.

## Actual Behavior
`FailToOverwriteComponent` is actually red, so it does not overwrite the color properly.

**Comment by zwenza** [comment]
hello! styled-components will provide you the styles via the `styles` prop. 
If you want to overwrite your styles you need to pass them to your component. 

This will fix your example:
```
const AlreadyStyledComponent = ({text, style}) => {
  return <StyledText style={style}>{text}</StyledText>
};
```

you can more information about this here: [docs](https://www.styled-components.com/docs/basics#styling-any-components). Just keep in mind that `className` is `style` in React Native  :)

**Comment by mxstbr** [comment]
We should probably mention that in the docs! @zwenza want to submit a PR? https://github.com/styled-components/styled-components-website

**Comment by JPeer264** [comment]
I was planning to do one, but I was busy until today. So I can do that as well if you like.
