### ISSUE TITLE
Interoperability with other libs

### ISSUE THREAD

**Issue by oliviertassinari** [styled-components/styled-components#860]
Opening an issue as @jgoux faced an interoperability issue between styled-components and jss with Material-UI:

While I can use the [`insertionPoint`](https://github.com/cssinjs/jss/blob/b841b18a9e564f35176174f3a2fdb1e7e35ec89a/docs/setup.md#specify-dom-insertion-point)  with JSS,
```html
<head>
    <title>JSS</title>
    <!-- jss -->
</head>
```

I can't find any way to determine the injection order of styled-components.
I have also noticed some other issue with css-modules.
Would it make sense to provide an insertion point option close to what JSS is doing?
It would be great to solve the issue that way:

```html
<head>
    <title>JSS</title>
    <!-- jss -->
    <!-- styled-components -->
</head>
```

## Version
1.0.5

## Reproduction

https://codesandbox.io/s/zqr56w532x

```jsx
import React from 'react';
import { render } from 'react-dom';
import styled from 'styled-components';
import { MuiThemeProvider } from 'material-ui/styles';
import { MenuItem } from 'material-ui/Menu';

const StyledMenuItem = styled(MenuItem)`
 background-color: red;
`;

const App = () => <StyledMenuItem>test</StyledMenuItem>;

render(<App />, document.getElementById('root'));
```

## Expected Behavior

UI
![capture d ecran 2017-05-31 a 23 11 20](https://cloud.githubusercontent.com/assets/3165635/26654275/7b091360-4656-11e7-9f6f-4d1e1fcb388c.png)

Injection order
![capture d ecran 2017-05-31 a 23 12 24](https://cloud.githubusercontent.com/assets/3165635/26654304/a4e0a090-4656-11e7-8971-0411d3c8cad9.png)

## Actual Behavior

UI
![capture d ecran 2017-05-31 a 23 12 53](https://cloud.githubusercontent.com/assets/3165635/26654312/b51475fe-4656-11e7-8b71-15de08248046.png)

Injection order
![capture d ecran 2017-05-31 a 23 13 18](https://cloud.githubusercontent.com/assets/3165635/26654377/fed1084c-4656-11e7-93eb-328b7f9b122e.png)

cc @kof.

**Comment by philpl** [comment]
@geelen seems rather easy to add now, right?

**Comment by adamgruber** [comment]
I have a similar issue trying to add normalize.css to my project. No matter where I put my import, the styled-component stylesheets are always injected above everything else. In cases of global resets, ordering is incredibly important.

**Comment by jgoux** [comment]
It's a big blocker for me as I'm using material-ui extensively along with styled-components. (which I both enjoy a lot btw!)

**Comment by cdharris** [comment]
I'm having the exact same issue trying to use styled-components with material-ui v1 alpha. 

The styled-components <styles> are being emitted higher up in the html document and are thus being overridden. 

Being able to specify an insert location seems like it would be a big help here.

**Comment by cdharris** [comment]
For anyone else struggling to use styled-components with the new v1 of material-ui. After hunting around for a while, I found that the comment used to direct their new insertion point is 
` <!-- jss-theme-reactor -->` rather than ` <!-- jss -->`
Hope this saves someone some time

**Comment by oliviertassinari** [comment]
@cdharris Material-UI will no longer rely on jss-theme-reactor in the next beta. `<!-- jss -->` will be the way to go.

**Comment by kof** [comment]
@oliviertassinari I would actually rather use something mui specific to distinguish mui insertion point and jss insertion point etc.

**Comment by oliviertassinari** [comment]
@kof Let's talk about it in https://github.com/callemall/material-ui/pull/7461. Sure, we can do that.

**Comment by vladimir-kondratenko** [comment]
@oliviertassinari What about this approach?
```javascript
const StyledMenuItem = styled(MenuItem).attrs({
  className: "test"
})`
  &.test {
    background-color: red;
  }
`;
```

**Comment by oliviertassinari** [comment]
@vladimir-kondratenko increasing the specificity will most likely work. But we have an opportunity to make is simpler.

**Comment by pavel06081991** [comment]
@oliviertassinari, which opportunity do you mean?

**Comment by mxstbr** [comment]
Just to note this here (see #1253), the `.attrs` isn't even necessary for this workaround, you can just use `&` to inject the generated class name:

```JS
const StyledMenuItem = styled(MenuItem)`
  &&& {
    background-color: red;
  }
`;
```

**Comment by techniq** [comment]
You could use a glamor plugin to modify the selector being injected, and thus increase specificity of all selectors as mentioned [here](https://github.com/threepointone/glamor/issues/107#issuecomment-260165887).  It's the same hack as `&&&` but at least you don't have to proliferate it to all your styled components.

**Comment by mxstbr** [comment]
@techniq what does a glamor plugin have to do with styled components? I'm not getting the connection here I'm afraid.

**Comment by PTaylour** [comment]
There is now a section in the docs that shows how to set the jss insertion point

https://material-ui-next.com/customization/css-in-js/#css-injection-order

**Comment by oliviertassinari** [comment]
As you can see in this [codesandbox](https://codesandbox.io/s/mzwqkk1p7j), no `!important` is required.

**Comment by designjudo** [comment]
I have a blocker with using styled-components with Material-ui in Prod. In development, everything works perfectly since I'm using styled(Button) hooks, and it generates the 'Mui' classes. Although, when in prod the classnames change to 'jss-1', 'jss-2' and override my styled components.

I can still workaround this with the && hack, but I'm not sure why the specificity issue changes only when in production?

**Comment by oliviertassinari** [comment]
@designjudo You can always use the [Global CSS option](https://material-ui-next.com/customization/css-in-js/#global-css) if you are in the rush.

**Comment by PTaylour** [comment]
@designjundo Is your production build stripping out html comments?

I'm using create-react-app, which has webpack configured to do just that.

You can use any DOM node as an insertion point, so one way round this is to do something like this:

```
const insertionPoint = document.getElementById('insertion-point-jss')

jss.setup({ insertionPoint })
``` 

Not pretty, but works if you provide an element before the final element in your header.

**Comment by designjudo** [comment]
I tested this out- in dev the insertion order is working, but breaks when webpack compiles.

I added a <style id=“insertion-point-jss”></style> to the Head to hook it.

After compiling the styled components appear before the jss. Maybe it’s something webpack is doing?

> 
> 

TYLER MATHES
WEB & GRAPHIC DESIGNER 
	904.235.9902
	design@tylermathes.com	 	 
	www.tylermathes.com	 	 
   


On Jan 16, 2018, at 10:44 AM, Pete Taylour <notifications@github.com> wrote:

@designjundo Is your production build stripping out html comments?

I'm using create-react-app, which has webpack configured to do just that.

You can use any DOM node as an insertion point, so one way round this is to do something like this:

const insertionPoint = document.getElementById('insertion-point-jss')

jss.setup({ insertionPoint })
Not pretty, but works if you provide an element before the final element in your header.

**Comment by designjudo** [comment]
@PTaylour Great suggestion here! This ended up being the solution. You rock! I think the alternative would have been to enable comments in the webpack config via nanocss

I used this string in the head and it's now inserting as it should.

`<style id="insertion-point-jss"></style>`

**Comment by designjudo** [comment]
I also wanted to add a note on the documentation, I couldn't get the new documentation to work, even after updating packages:

`import { createGenerateClassName, jssPreset } from 'material-ui/styles';
const jss = create(jssPreset());`

It still works using the old documentation when I use the previous solution:

`import { createGenerateClassName } from 'material-ui/styles';
import { preset } from ' jss ';

const jss = create(preset());`

**Comment by designjudo** [comment]
I also wanted to add a note on the documentation, I couldn't get the new documentation to work, even after updating packages:

```
import { createGenerateClassName, jssPreset } from 'material-ui/styles'; 
const jss = create(jssPreset());
```

It still works using the old documentation when I use the previous solution:

```
import { createGenerateClassName } from 'material-ui/styles';
import { preset } from ' jss ';

const jss = create(preset());
```
