### ISSUE TITLE
Missing Vendor Prefix

### ISSUE THREAD

**Issue by stephenmangion** [styled-components/styled-components#863]
Hi,

I am currently using styled-components v 2.0. I have an issue in Safari which is related to a missing vendor prefix from AutoPrefixer. This issue seems to have already been resolved in the latest version of AutoPrefixer.

https://github.com/postcss/autoprefixer/commit/a14935fea44b07da1c2408934b8cb3548310315a

Can anyone comfirm whether this has been resolved on this version of styled-components please?

**Comment by k15a** [comment]
Which version of styled-components are you using? The latest is 2.0.0 ;)

**Comment by stephenmangion** [comment]
Yes am using v.2.0.0

**Comment by k15a** [comment]
cc @thysultan

**Comment by philpl** [comment]
@stephenmangion can you post a reproduction please? Preferably on webpackbin or code sandbox :) it'd help @thysultan a lot in the debugging process

**Comment by thysultan** [comment]
🚢  [3.0.13](https://github.com/thysultan/stylis.js/blob/master/CHANGELOG.md#3013-june-02-2016)

**Comment by philpl** [comment]
Will be released as part of the next patch/minor version :) https://github.com/styled-components/styled-components/pull/829
