### ISSUE TITLE
Version 2.0.0 lacks proper type definitions under tagged commit 

### ISSUE THREAD

**Issue by seivan** [styled-components/styled-components#867]
https://github.com/styled-components/styled-components/tree/a01b6b40e69d6f9a7b12370d031bf2736c8784a0

That's tagged as 2.0.0 and it has outdated type definitions

**Comment by seivan** [comment]
Closing this because for some odd reason things seem to work even though the type definitions in that tag were updated three months ago.

**Comment by philpl** [comment]
We're aware. Thanks for closing it on your own, but we have multiple open and closed issues and PRs addressing this ;) Please search first next time, before opening a new one

**Comment by seivan** [comment]
@philpl I did search and https://github.com/styled-components/styled-components/issues/646 claims it's resolved. 

It's however still not merged in the tagged 2.0.0 release. 
https://github.com/styled-components/styled-components/tree/a01b6b40e69d6f9a7b12370d031bf2736c8784a0

**Comment by seivan** [comment]
I did search, you can even see my comments in the older issues from April.
