### ISSUE TITLE
Improve changelog: highlight important changes

### ISSUE THREAD

**Issue by Li0liQ** [styled-components/styled-components#872]
It would be nice to highlight important changes in the change log.
E.g. styled-components bumped a major version recently, however, it is unclear what are the breaking changes that required that. As result, it is difficult to foresee the impact of a potential upgrade to that version or what are the things to pay attention to.

**Comment by philpl** [comment]
I think it's a good proposal, but it could slow us down when merging proposed PRs. Instead we should probably just focus on writing good and readable github release notes. I've just added some for v2.0.0

**Comment by hongymagic** [comment]
Completely agree, came here to check the change log file, but couldn't see at a glance if upgrading had any obvious breaking changes.

**Comment by philpl** [comment]
Ok, I'm going to close this as after further consideration, release notes on github should be a sufficient improvement over the changelog
