### ISSUE TITLE
Add examples to showcase the right way to test styled components

### ISSUE THREAD

**Issue by DavidHe1127** [styled-components/styled-components#877]
Use `enzyme` and `jest`.

I am struggling with the correct approach to find and test the styled components - see my comments in `test.spec.js`. In my case, I have a normal react component that wraps a styled component. What I need to test out is to make sure the wrapped styled component always renders.  See my code snippets below.

For illustrating purpose, I simplify the code by providing minimal code.

**_Test.js_**
```javascript
import React from 'react';
import styled from 'styled-components';
import { Text, H5 } from '@lendi/lendi-components';
import style from '../styles';

const Subtitle = styled(Text)`
  font-size: 15px;
`;

function Test () {
  return (
    <div>
      <H5>
        {"This is a test"}
      </H5>
      <Subtitle style={style.center}>
        {"How can I test this?"}
      </Subtitle>
    </div>
    );
}

export default Test;
```
**_test.spec.js_**
```javascript
import React from 'react';

import Test from '../components/Test';
import styled from 'styled-components';
import { H5, Text } from '@lendi/lendi-components';
import { shallow } from 'enzyme';

describe('lets test', () => {

  const shallowRender = (props) => shallow(<Test />);

  it('H5 always rendered', () => {
    const loginWrapper = shallowRender();
    expect(loginWrapper.find(H5).length).toBe(1);
    expect(loginWrapper.find(H5).prop('children').length > 0).toEqual(true);
  });

  it('Subtitle always rendered', () => {
    const loginWrapper = shallowRender();

    const Subtitle = styled(Text)``;

    console.log(Subtitle.displayName); // Styled(Component) too generic that can not be used to test the 
                                                                   //  component rendering

    expect(loginWrapper.find(Subtitle.displayName));
    // expect(loginWrapper.find(H5).prop('children').length > 0).toEqual(true);
  });

});
```
`__mocks__/@lendi/lendi-components.js`
```javascript
import React from 'react';

function mockComponent (name) {
  return props => React.createElement(() => React.createElement(name), props, props.children);
}

const list = [
  'H5',
  'Text'
];

const mockups = list.reduce((prev, next) => {
  prev[next] = mockComponent(next);
  return prev;
}, {});

export const H5 = mockups.H5;
export const Text = mockups.Text;
```
**_index.js_**
```javascript
const style = {
  center: {
    textAlign: 'center'
  }
};

export default style;
```

**Comment by philpl** [comment]
You'll probably want to search for the actual SubTitle component here by just exporting it. The displayName will probably be `Styled(Text)`, depending on the child's displayName, but it's not stable enough to build a test on.

Instead you can also just fully mount it, or dive the shallow mount, and see whether the rendered text matches what you're expecting.

On the other hand –– and more off-topic of course –– I wouldn't recommend starting to test whether a component renders what it renders. And the key-phrase *"renders what it renders"* really is the point here. When you write JSX without any logic, and test whether sth mounts, you're either testing the child component, or you're testing whether JSX does its thing. This is more what snapshot tests are for. If that's not your thing, I'd go some components higher, and test container and structural components that actually contain some logic, and add some fixtures/checks for their content.

To also talk about the case where you're actually more testing the child component: In that case there should either just be tests for it separately, if it actually contains some logic, or if it's external, you should rely on the external libraries tests and correctness.

Btw. I'm not quite sure why you're using inline styles for `<Subtitle style={style.center}>`. That shouldn't be necessary :wink:

Hope this was helpful! There are some more issues which go into detail, on how to test some styled components. And all you might need is jest-styled-components for snapshot testing.

**Comment by DavidHe1127** [comment]
Thanks @philpl  Really appreciate your assistance. Regarding logical JSX, do you mean by something like this?

```javascript
let header;

if (enabled) {
    header = <div>This is enabled</div>
} else {
    header = <div>This is disabled</div>   
}

return <div>{header}</div>
```
Can you please show me examples?

thanks

**Comment by philpl** [comment]
Sure! So what I usually go for is sth like this:

### Pure Structural & Presentational Component

I'd snapshot this, or in projects that don't require any rigorous testing, only add the snapshot once it has been changed/broken once.

```js
const Test () => (
  <div>
    <H5>
      This is a test
    </H5>
    <Subtitle>
      How can I test this?
    </Subtitle>
  </div>
);
```

### Structural Component with some Logic and conditionals

Test this, or snapshot it with all conditionals, if the team prefers snapshots:

```js
const Test2 ({ conditional }) => (
  <div>
    <H5>
      {conditional ? 'This is a test' : 'This is one too'}
    </H5>
    <Subtitle>
      How can I test this?
    </Subtitle>
  </div>
);
```

### Container Components

Anything that has business logic in it, must be tested more thoroughly. But in that case there are probably some lower level functions (e.g. mapDispatchToProps / mapStateToProps) that can be tested purely from a functional perspective, rather than integrational (I'd consider testing an entire container integrational, if it doesn't do anything on its own)
