### ISSUE TITLE
Prefixing `backface-visibility` property

### ISSUE THREAD

**Issue by rtkhanas** [styled-components/styled-components#878]
## Version
2.0.0

## Reproduction

https://www.webpackbin.com/bins/-Km1s6lnhMXjBcpdK1tE

## Steps to reproduce

Check the button style.

## Expected Behavior

backface-visibility: hidden;
-webkit-backface-visibility: hidden;

## Actual Behavior

backface-visibility: hidden;

**Comment by thysultan** [comment]
patched in stylis 3.0.19

**Comment by k15a** [comment]
Awesome 💯
