### ISSUE TITLE
When a styled component is styled again it looses its defaultProps

### ISSUE THREAD

**Issue by diegohaz** [styled-components/styled-components#88]
Reproduction: https://jsfiddle.net/zeoqxm8p/

**Comment by mxstbr** [comment]
Wow, great catch! I'll see what we can do to mitigate that, very good catch!

**Comment by diegohaz** [comment]
I'll start a PR with a failing test and try to fix it.

**Comment by mxstbr** [comment]
Done by the amazing @diegohaz in #90! 👏
