### ISSUE TITLE
Bug when using Private Use Area UTF-8 codes that most icon libraries use.

### ISSUE THREAD

**Issue by Janther** [styled-components/styled-components#885]
## Version
2.0.1 On **WEB**

First of all, congratulations on the amazing library.
Second, I found this weird behaviour while adding some logic taken from Font-Awesome.
The bug happens when using Private Use Area UTF-8 codes that most icon libraries use.

## Reproduction

For example:

```ES6
styled.h1`
  &:before {
    content: "\f0a3";
  }
`
```
https://www.webpackbin.com/bins/-Km3ra09bbCUAqDwFkDk

## Expected Behavior
The CSS rendered should be

```CSS
.styledClass:before{
  content: "\f0a3";
}
```

## Actual Behavior

The CSS rendered should be
```CSS
.styledClass:before{
  content: "0a3";
}
```

<img width="291" alt="screenshot 2017-06-08 11 49 28" src="https://user-images.githubusercontent.com/1022054/26906368-e14d310c-4c40-11e7-8154-8485009aaf2a.png">

Plus the browser doesn't get the end of the string and keeps reading other rules.

<img width="322" alt="screenshot 2017-06-08 11 52 58" src="https://user-images.githubusercontent.com/1022054/26906515-e1441706-4c41-11e7-941b-d82182bb17ba.png">

**Comment by philpl** [comment]
Sounds like a normalisation bug with stylis. Can you confirm this by any chance, @thysultan? :)

**Comment by thysultan** [comment]
Depending on the possible `\<$>` codes that can be used in css, stylis could monkey-patch this in the compile step so that you also don't need to escape them, though this has the caveat of not being able to monkey-patch `\t`(tab) or `\n`(newline) characters.

**Comment by Janther** [comment]
Thank you @philpl it that solved it.
For a moment forgot that I was working in JS. Great library again people.

**Comment by thysultan** [comment]
pushed a patch that auto-escapes the un-escaped control characters that break browser css parsers `\0`, `\f`, '\v'.
