### ISSUE TITLE
Comments breaks generated css

### ISSUE THREAD

**Issue by Flydiverny** [styled-components/styled-components#888]
So after updating to 2.0.1 our active states on our styled react-router Links stopped working as intended. This seems to be cause by yet another (for us) issue with comments in the css.

## Version
2.0.1 (worked in 2.0.0)

## Reproduction

Tried reproducing this on webpackbin but haven't managed.
We also use the babel-plugin-styled-components to ease debugging.

## Steps to reproduce
Not sure you can actually reproduce it as I couldn't in webpackbin. But this is a stripped down snippet of what we have thats causing issues for us.
```js

const activeClassName = 'menu-option-active';

const Wrapper = styled(({ condition, children, ...props }) => (<Link {...props}>{children}</Link>)).attrs({
  activeClassName,
})`
  ...css...

  /** Comment */
  ${(props) => {
    let style;
    if (props.condition) {
      style = `.conditional-css {
          ...css...
       }`;
    }

    return style;
  }}


  &.${activeClassName} {
   ...css...
 }
```

## Expected Behavior
With condition true:
```
.jvUGat { ...css... }
.jvUGat .conditional-css { ...css... }
.jvUGat.menu-option-active { ...css... }
```
With condition false:
```
.jvUGat { ...css... }
.jvUGat.menu-option-active { ...css... }
```

## Actual Behavior
With condition true:
```
.jvUGat { ...css... }
.jvUGat   /** Comment */ .conditional-css { ...css... }
.jvUGat.menu-option-active { ...css... }
```
With condition false:
```
.jvUGat { ...css... }
.jvUGat /** Comment */&.menu-option-active { ...css... }
```

So especially in the case of the condition being false the generated CSS is getting weird. The comment cuts in between the generated name and even the `&` appears in the generated css.

Solution for us is easy to just remove the comment but figured I'll report having issues :)

**Comment by philpl** [comment]
cc @thysultan

In the meantime you can try the minify option on our babel plugin. It'll strip multiline comments, I think

**Comment by Flydiverny** [comment]
Found another comment lingering and butchering generated CSS. Disabling the babel plugin seems to fix both issues or just disabling the `minify` ie ```["styled-components", {
            "minify": false
          }]``` also fixes it. 
So issue seems more related to the plugin.

**Comment by philpl** [comment]
@Flydiverny That's definitely interesting. I don't really see how this could be caused by an upgrade from v2 to v2.0.1 then :/

**Comment by Flydiverny** [comment]
@philpl My only idea is if it could be related to that the plugin still uses stylis 2.x while styled-components was upgraded to stylis 3.x in 2.0.1 ? Tried downgrading to styled-components 2.0.0 and re-enabling minify but can't reproduce the issues there. The comments are removed as expected.

**Comment by philpl** [comment]
@Flydiverny we're not using stylis for the minification, only for experimental preprocessing

**Comment by nfarina** [comment]
Upgrading to styled-components v2.0.1 also broke my styles with comments - the parser seemed to discard all styles after the comment. I'm not sure of root cause yet though.

**Comment by diondiondion** [comment]
Same, had to manually revert to 2.0.0. Would probably be best to revert the release until this has been fixed.

**Comment by thysultan** [comment]
Can't tell if this is s-c or stylis related, @nfarina @didierfranc Do you have examples that can be tested... I use this for the [remove comments] test spec (https://github.com/thysultan/stylis.js/blob/master/tests/spec.js#L110)

**Comment by nfarina** [comment]
This is speculative (upgrading to 2.0.1 now to test it) but my hunch is that it's related to commenting out actual lines of CSS including colons/semicolons.

**Comment by nfarina** [comment]
OK, so this causes the bug:

```css
  /* Line one */
  /* Line two */
```

Removing the 2nd comment line "fixes" it. So it seems to be related to two consecutive comments?

**Comment by thysultan** [comment]
@nfarina What comes after `/* Line two */`?

**Comment by nfarina** [comment]
Updated my comment above - will delete this one (for email)

**Comment by nfarina** [comment]
Here's another example that breaks it right away (and in a different way - screws up the whole page layout):

```js
const Track = styled.div`
  width: 46px;
  height: 26px;
  border: 1px solid black;
  /* // */
  background: red;
`;
```

**Comment by thysultan** [comment]
This works with [stylis](https://stylis.js.org) @philpl [stringifyRules.js#L21](https://github.com/styled-components/styled-components/blob/master/src/utils/stringifyRules.js#L21) this might be the source of this.

**Comment by philpl** [comment]
Are most people here forgetting to mention that they're using the babel plugin possibly?

If it's not stylis, the only thing that could cause this is the optional babel plugin for v2 and it's minify option which is enabled by default ;)

https://github.com/styled-components/babel-plugin-styled-components/blob/master/src/visitors/minify.js

**Comment by diondiondion** [comment]
Guilty as charged.

**Comment by philpl** [comment]
Ok, I'll try to patch the plugin with the cases you guys mentioned :)

**Comment by philpl** [comment]
@Flydiverny @nfarina @diondiondion Please test and review this PR. It now correctly strips *all* comments. If everything is working correct, or if you're experiencing bugs while testing it, please leave a comment there.

cc @thysultan
