### ISSUE TITLE
[V2] Probable stylis bug with media-query and font-family 

### ISSUE THREAD

**Issue by PlanetIrata** [styled-components/styled-components#889]
Hi, I upgraded to SC2 and have problems with media queries not working anymore as expected. I read #789 about ordering styles correctly, but I find that setting the font-family after a media query seems to break it. Here is a webpackbin to reproduce the issue : [https://www.webpackbin.com/bins/-Km6JBa8goWFkSWl0nkc](https://www.webpackbin.com/bins/-Km6JBa8goWFkSWl0nkc)

It should display a 100px h1 but does not. Moving the font-family line before the media-query solve the issue.

/cc @thysultan

**Comment by thysultan** [comment]
What version of SC2 are you using? 2.0.1 uses stylis V3 that fixes possibly `@media` specificity issues.

**Comment by PlanetIrata** [comment]
Was using 2.0.0, upgrading to 2.0.1 seems to fix the Issue, sorry and thanks for your work.
