### ISSUE TITLE
Add Typescript type definitions

### ISSUE THREAD

**Issue by schickling** [styled-components/styled-components#89]
I'm almost sorry to bring this up since `styled-components` is using Flow (which is great!). Would you consider adding type definitions for Typescript (2) as well? That would be awesome for the other half of the community which went for Typescript instead of Flow for `undefined` reasons. 😆

**Comment by mxstbr** [comment]
I'd love to add libdefs for TypeScript – except I have no experience with TS and our flow types suck currently. (working on that soon though, see #51) If somebody wants to pick that up it'd be much appreciated!

**Comment by patrick91** [comment]
Typescript support has been releases in `v1.4.0` :)
