### ISSUE TITLE
Regression with nested selectors & pseudo elements

### ISSUE THREAD

**Issue by adamyonk** [styled-components/styled-components#894]
## Version
2.0.1

## Reproduction

https://www.webpackbin.com/bins/-Km846r9wLG4GxuWksp1

## Steps to reproduce

Hover over the text. If you change styled-components to `2.0.0` it works again.

## Expected Behavior

You should see `:after` text content

## Actual Behavior

You don't see `:after` text content

**Comment by thysultan** [comment]
patched in stylis 3.1.3

**Comment by k15a** [comment]
Great job like always. 🎉

**Comment by philpl** [comment]
@thysultan 3.1? I guess we'll need to publish a patch then ^^

**Comment by thysultan** [comment]
[https://semver.npmjs.com/](https://semver.npmjs.com/) I think the current range covers it.

**Comment by philpl** [comment]
@thysultan oh yea indeed. I never checked though, whether yarn is actually upgrading it though

**Comment by thysultan** [comment]
Yarn is locked to a specific version so that might need a patch.
