### ISSUE TITLE
Passing tagged template literals to .withComponent()

### ISSUE THREAD

**Issue by Jonarod** [styled-components/styled-components#899]
If I'm correct, styled-component's main feature leverages `tagged template literals` for its whole ecosystem, with the star function being  `styled` + `taggedTemplateLiterals`, so that we can create a new element and attach new styles to it:
```js
const Text = styled.span`
    fontSize: 1em;
`
```

Also, `extend` + `taggedTemplateLiterals` is possible so we can quite add styles to an existing element:
```js
const MyNewText = extend`
    fontSize: 2em;
`
```

The helper `css` also comes bundled with `taggedTemplateLiterals` : 
```js
const textStyles = css`
    font-size: 1em;
    color: #252525;
    margin-bottom: .4 rem;
`
```

Then we got the cool `withComponent` kid and can create a new element inheriting styles from another component:
```js
const Paragraph = Text.withComponent('p')
```
However, to my surprise, we cannot use `withComponent` + `taggedTemplateLiterals`...

This would be really nice : 

```js
const Text = styled.span`
    font-size: 1em;
    color: #252525;
    margin-bottom: .4 rem;
`
Text.h1 = Text.withComponent('h1')`
    font-size: 3em;
`
Text.h2 = Text.withComponent('h2')`
    font-size: 2.7em;
`
Text.h3 = Text.withComponent('h3')`
    font-size: 2.1em;
`
Text.h4 = Text.withComponent('h4')`
    font-size: 1.8em;
`
Text.h5 = Text.withComponent('h5')`
    font-size: 1.3em;
`
Text.h6 = Text.withComponent('h6')`
    font-size: .9em;
`
export default Text;
```

Today, I end up doing:
```js
const textStyles = css`
    font-size: 1em;
    color: #252525;
    margin-bottom: .4 rem;
`
Text = styled.span`
    ${textStyles}
`
Text.h1 = styled.h1`
    ${textStyles}
    font-size: 3em;
`
Text.h2 = styled.h2`
    ${textStyles}
    font-size: 2.7em;
`
Text.h3 = styled.h3`
    ${textStyles}
    font-size: 2.1em;
`
Text.h4 = styled.h4`
    ${textStyles}
    font-size: 1.8em;
`
Text.h5 = styled.h5`
    ${textStyles}
    font-size: 1.3em;
`
Text.h6 = styled.h6`
    ${textStyles}
    font-size: .9em;
`
export default Text;
```

Don't know if there are other patterns though (??), but for consistency I would like to see this feature. Not sure if this is difficult to implement or feasible at all. What do you think ?
;)

**Comment by mxstbr** [comment]
```JS
const Paragraph = Text.withComponent('p').extend`
  color: blue;
`
```

Reference explanation: #851

**Comment by mxstbr** [comment]
@philpl we should add this pattern to the docs since it seems like folks are confused about this!

**Comment by philpl** [comment]
@mxstbr Yea, it's mentioned but not really made that clear:

> // Use .withComponent together with .extend to both change the tag and use additional styles

https://www.styled-components.com/docs/basics#extending-styles

**Comment by Jonarod** [comment]
@philpl   My bad... 

The example does explain it indeed:
```js
const Button = styled.button`
	display: inline-block;
	color: palevioletred;
	font-size: 1em;
	margin: 1em;
	padding: 0.25em 1em;
	border: 2px solid palevioletred;
	border-radius: 3px;
`;
const Link = Button.withComponent('a')
const TomatoLink = Link.extend`
	color: tomato;
	border-color: tomato;
`;
render(
	<div>
		<Button>Normal Button</Button>
		<Link>Normal Link</Link>
		<TomatoLink>Tomato Link</TomatoLink>
	</div>
);
```

The abstraction `Component.extend` made me miss it while looking for explicit 
```js
const TomatoLink = Button.withComponent('a').extend`
	color: tomato;
	border-color: tomato;
`;
``` 
But it may be just me, sorry for that.

**Comment by philpl** [comment]
It's definitely not your fault :) It's easy to miss. I'll add another paragraph about chaining these two methods
