### ISSUE TITLE
TypeScript plugin? 

### ISSUE THREAD

**Issue by mohsen1** [styled-components/styled-components#900]
A TypeScript plugin for styled-components can greatly enhance dev experience by suggesting CSS autocomplete right inside styled component string literals.

See [GraphQL](https://github.com/Quramy/ts-graphql-plugin) plugin as an example.

**Comment by Igorbek** [comment]
This is something I was thinking to do in the next 2-3 weeks.

**Comment by Igorbek** [comment]
FYI, an update on the current state. I was able to make the transformer work, the working prototype published from the repo: https://github.com/Igorbek/typescript-plugin-styled-components

I'm going to polish it slightly and add documentation shortly.

**Comment by mxstbr** [comment]
@Igorbek how is that plugin looking? Do we want to move it to the `styled-components` org? It seems like something a lot of people will want!

**Comment by Igorbek** [comment]
The plugin is looking pretty well. It does it suppose to do, and I'm pretty happy with that.
Comparing to Babel plugin, it has only one feature - supplying components' names.

In terms of readiness, the only issue right now is that awesome-typescript-loader (one of two the most popular typescript loaders for webpack) [doesn't work](https://github.com/s-panferov/awesome-typescript-loader/issues/447) correctly in _watch_ mode. But they [on track](https://github.com/s-panferov/awesome-typescript-loader/pull/423) to fix it.

I've got [a contradictory message](https://github.com/styled-components/babel-plugin-styled-components/issues/41#issuecomment-308842308) from within a babel plugin repo, and I was not quite sure that `styled-components` org is interested in TS plugin.

Anyway, I'll be happy to move the plugin under SC org.

**Comment by mxstbr** [comment]
@philpl how is our webpack stuff going to replace the typescript plugin that adds autocomplete? That doesn't make any sense to me?

**Comment by philpl** [comment]
@mxstbr From the mentioned issue:

> I'm currently working on a plugin for TypeScript that would do mostly the same as this one, so that typescript users don't need to use Babel (in most cases it's problematic). The prototype is working pretty well, however nothing is documented, that's next on the list: 

So autocomplete is a super idea :) But the plugin shouldn't drop into what we'll do with our babel/webpack plugins in the future.

**Comment by Igorbek** [comment]
Ok, sorry everyone who was confused by my messages. I totally misread the original proposal regarding the TypeScript plugin. I don't know how that come that I understood something different. Maybe because that time I had started to work on the plugin.

The original proposal by @mohsen1 was about adding css auto-completion for editors for improving _development_ experience. However my plugin was intended to be used in compile time for improving _debugging_ experience. That does interfere with what you @philpl @mxstbr do with a webpack plugin, with nuances.

Sorry again, I'm leaving this conversation as too ashamed.

**Comment by mxstbr** [comment]
Haha No worries @IgorBek, still thank you very much for making that plugin!

**Comment by mxstbr** [comment]
There's now an official styled-components plugin for TypeScript by @Microsoft!! :scream: :100:

See here: https://github.com/Microsoft/typescript-styled-plugin
