### ISSUE TITLE
Webpack module bundling failure on v2.0.1 (_stylis2.default.set is not a fn)

### ISSUE THREAD

**Issue by MarkSMT** [styled-components/styled-components#901]
## Version
2.0.1

## Reproduction

Update from 2.0.0 to 2.0.1

## Issue

<img width="716" alt="screen shot 2017-06-09 at 22 36 55" src="https://user-images.githubusercontent.com/20295793/26993641-514fbfdc-4d64-11e7-8ff1-c68d9f896318.png">

I get this error after update. How can i fix this?

**Comment by MarkSMT** [comment]
<img width="673" alt="screen shot 2017-06-09 at 22 40 56" src="https://user-images.githubusercontent.com/20295793/26993726-bd5cb0d6-4d64-11e7-8d5e-47c315c4b498.png">

> stringifyRules.js

**Comment by philpl** [comment]
It seems that your stylis didn't upgrade initially, but it's impossible for me to tell you why ^^
