### ISSUE TITLE
[V.2.0.1] Parent inheritance problem

### ISSUE THREAD

**Issue by ehtb** [styled-components/styled-components#903]
Please check this: https://codesandbox.io/s/wplNXEN1J
Check `.modifier & {` underneath.

This JSX:
```
<Container>
  <div className='modifier'>
    <div className='wrapper'>Hello World, this is my first styled component!</div>
  </Container>
</div>

const Container = styled.div`
  .wrapper {
    background-color: green;
    .modifier & {
      background-color: red;
    }
  }
`;
```

Renders this HTML:
```
<div class="sc-bdVaJa YJEIW">
  <div class="modifier">
    <div class="wrapper">Hello World, this is my first styled component!</div>
  </div>
</div>
```

The CSS is compiled as:
```
.sc-bdVaJa {}
.YJEIW .wrapper{background-color: green;}
.wrapper .modifier .YJEIW{background-color: red;}
```

I think the modifier should be: `.YJEIW .modifier .wrapper`

**Comment by k15a** [comment]
Which styled-components version are you using?

**Comment by thysultan** [comment]
I'm trying think what should be the correct behavior here.

Going from how [sass](https://www.sassmeister.com/gist/2076736c7e60ce1a26780adec6879a3f) handles this, since

```
.modifier & {
color: red;
}
// produces
.modifier .YJEIW{
    color: red;
}
```
Shouldn't
```
.wrapper {
    .modifier & {
        color: red;
    }
 }
// produce
.modifier .YJEIW .wrapper
```

assuming `.YJEIW` is the enclosing namespace.

**Comment by ehtb** [comment]
@k15a v.2.0.1 (I added to the title).

> .YJEIW is the enclosing namespace.
@thysultan Could also be right yes, though that's more a library decision. I believe Sass would always put the modifier within the enclosing namespace, but outside it probably would serve more use cases and would be consistent with how `injectGlobal` would work.

**Comment by philpl** [comment]
Btw @ehtb. Not trying to chime in here, but:

I'm not sure what you're trying to achieve here, but `.modifier` in your example isn't a modifier as in BEM. It's just a separate element class.

Modifiers should use interpolations. No matter whether this is a bug or not, the code you're writing doesn't seem to follow some best practices :wink:

**Comment by ehtb** [comment]
Hi @philpl It is only to illustrate the issue, not to be a real world example.

**Comment by thysultan** [comment]
The way sass handles it looks more consistent across the board of possible uses. i.e would the following

```
.a{ .b { .c &{ color:red } } }
```
produce `.YJEIW .c .a .b` or `.YJEIW .a .c .b`?

@ehtb Can you give me example cases that one would be to able handle over the other?

```
.modifier <parents>

vs

.YJEIW .modifier <immediate parent>

vs

.YJEIW .modifier <parents(excluding top-level namespace)>
```

patterns

**Comment by k15a** [comment]
Sorry, I should have read the complete issue. I think the current behavior is great because the `&` acts like a variable for the generated class which is quite reasonable. This way you don't have to think twice how your current selector looks like because `&` gets replaced with the generated class and if there is no `&` in the selector the generated class is prepended.

**Comment by ehtb** [comment]
@k15a I agree, I feel that that is the correct behaviour too. I was unsure if the library wanted to render: `.YJEIW .modifier .wrapper`, or `.modifier .YJEIW .wrapper`. In the current version this is rendered as `.wrapper .modifier .YJEIW`, which I think is the actual bug.

**Comment by thysultan** [comment]
patched in stylis 3.1.6, works like it would in scss.

**Comment by philpl** [comment]
@thysultan awesome :tada:

@ehtb can you confirm, please, that it's now working correctly for you? 😄

**Comment by ehtb** [comment]
@thysultan Great, thanks for the fast fix!

@philpl Just did, can confirm that 2.0.1 with stylis 3.1.6 works. Awesome work!
