### ISSUE TITLE
Testing styled components with snapshots

### ISSUE THREAD

**Issue by jamieholliday** [styled-components/styled-components#907]
We are currently using styled components with Jest snapshot testing. Works pretty nicely except for if I add a new styled component to one of my react components it causes the css class names and then therefore the snapshots to change in multiple unrelated components.

The diffs in git are now all css classname changes in completely otherwise untouched parts of the codebase which is making the diffs both really large and also confusing.

So I am assuming by adding a new styled component some other place this affects how all the classnames are generated, throughout the project?

It this something I am doing wrong? Or is this by design? 
I'm using styled-components v2

**Comment by philpl** [comment]
There's a separate project that makes this whole experience with Jest a lot nicer: https://github.com/styled-components/jest-styled-components

:+1:

**Comment by jamieholliday** [comment]
Thanks, I did check out the project, and it looks like it makes the snapshot error messages nicer looking, which is great.

However the original issue still exists. I add a new styled component in one react component, unrelated components (not using the component I changed in any way) have their classnames updated so a new snapshot gets generated for multiple components, which makes the diff really big and misleading.

I'll try and create a reduced example to illustrate the issue.

If the class names are always being regenerated then I can look at another way of testing that doesn't use snapshots, however it is a nice feature.

Thanks for the quick response and all the work on this great library. Other than this small issue, I'm finding it awesome to use!

**Comment by philpl** [comment]
This should be circumventable with our babel-plugin with the ssr option. It generates stable componentIds. I'm not sure if that applies to the jest plugin though

**Comment by jamieholliday** [comment]
Ok just to document my findings here:  I just tried this out with both the babel-plugin ssr option and using jest-styled-components: ```expect(tree).toMatchStyledComponentsSnapshot()``` and looks like I'm still getting unrelated css class names being updated.

**Comment by philpl** [comment]
cc @MicheleBertoli

**Comment by MicheleBertoli** [comment]
Hello @jameslnewell, It'd be awesome if you could provide a minimal example to repro the issue.
I'll be happy to help and improve the package.

**Comment by philpl** [comment]
Lets move this conversation over to this issue please :) https://github.com/styled-components/jest-styled-components/issues/29
