### ISSUE TITLE
Best way to inject global based on theme provider

### ISSUE THREAD

**Issue by themre** [styled-components/styled-components#909]
Hi,
I'm trying to inject some global styles based on theme props (e.g. color of anchors etc.). I wanted to use injectGlobal with props from theme provider but it doesn't get registered (inside my App.js which is my entry component). Any suggestions much appreciated!

**Comment by k15a** [comment]
It's probably best to wrap your page in a Root component and apply your global style to this component. Other than that you can use withTheme to create a component which changes global styles.

**Comment by themre** [comment]
ok thanks. i ended up wrapping root app into SC.

**Comment by prependto** [comment]
What about if you need to target HTML / BODY

**Comment by k15a** [comment]
@prependto There is a new api coming soon which will help you with that: https://github.com/styled-components/styled-components/pull/1493
