### ISSUE TITLE
How to sort out styled-component linter warnings in create-react-app

### ISSUE THREAD

**Issue by serle** [styled-components/styled-components#911]
Many of us use create-react-app. When using styled components it comes up with: styled is unused even though it is used. Could you provide a small guide on how to adapt the create-react-app linter rules for styled components.

**Comment by k15a** [comment]
I've never had this issue. Could you share an example file where it errors?

**Comment by serle** [comment]
Please close, my mistake. Small component going out of use on re-factor

**Comment by k15a** [comment]
Nice to hear you solved the issue.
