### ISSUE TITLE
Invalid typings lead to svg tags are missed

### ISSUE THREAD

**Issue by IIIristraM** [styled-components/styled-components#913]
v2.0.1

Current typings contain line
`type ThemedStyledComponentFactories<T> = ThemedStyledComponentFactoriesHTML<T> & ThemedStyledComponentFactoriesHTML<T>; `

instead of
`type ThemedStyledComponentFactories<T> = ThemedStyledComponentFactoriesHTML<T> & ThemedStyledComponentFactoriesSVG<T>;`

**Comment by IIIristraM** [comment]
Everything Ok in the master branch, so probably it'll be fixed in next release.

**Comment by k15a** [comment]
Yes, this is already fixed.
