### ISSUE TITLE
Styled components don't update on forceUpdate

### ISSUE THREAD

**Issue by mqklin** [styled-components/styled-components#919]
## Version
1.0.5

## Reproduction

https://codesandbox.io/s/1jYVNX7ym

## Steps to reproduce
Just watch

## Expected Behavior
Font size should be changed every 3 seconds

## Actual Behavior
Font size isn't changed

**Comment by geelen** [comment]
Hmm, just confirmed this is also broken on 2.0: https://codesandbox.io/s/v2A7zkkV8

**Comment by mqklin** [comment]
@philipchmalts sure, but it should after `forceUpdate` as well I guess

**Comment by etienne-dldc** [comment]
Hi ✋ 
This does not not look like a bug to me...

`styled-components` does implement `shouldComponentUpdate` or some similar strategy to avoid recomputing styles every time which would lead to very bad performances.

In your example the problem is that your component is not pure, which mean you can't predict the output of the style because it does not rely only on iputs (props).

Also not that `forceUpdate` has pretty much nothing to do with that.  
`forceUpdate` only force the current component to re-render, not the entire tree ! This mean that if a child-component implement `shouldComponentUpdate` it will not be render. In your example, if you use `setState` to trigger the render you get the same result.

To solve your example you have to `Wrapper` pure which mean pass the font size as props like  @philipchmalts says, exept in his example `Wrapper` is pure but `App`is not. A cleaner approach would be to store all random values in App state.

**Comment by geelen** [comment]
Ah, yes of course. `forceUpdate` [will rerender the children](https://facebook.github.io/react/docs/react-component.html#forceupdate) but not _force_ them to rerender. So, your `App` will rerender but for `Wrapper`, `shouldComponentUpdate` kicks in and we don't re-render. There's no way around that, really.

As @philipchmalts points out, passing as a prop will do what you need.

**Comment by mqklin** [comment]
@geelen I want to update styles on `window.onresize` event to have responsive layout, and I make `forceUpdate` on every resize.
So I have to duplicate code? For example:

```
const Wrapper = styled.div`
  margin: ${props => props.margin};
  font-size: ${props => props.fontSize};
`;

...
@forceUpdateOnResize
class ResponsiveLayout extends React.Components {
  render() {
    const responsiveMargin = getResponsiveMargin(window.innerHeight);
    const responsiveFontSize = getResponsiveFontSize(window.innerHeight);
    return (
      <Wrapper margin={responsiveMargin} fontSize={responsiveFontSize}>
        Hello responsive!
      </Wrapper>
    );
  }
}
```

**Comment by k15a** [comment]
I think it's best to use setState instead of forceUpdate and throttle the resize calls to 60 times a second. And there it's good practice to just pass props to the styled-components. Why aren't you using viewport units `vw, vh` in combination with calc?

**Comment by mqklin** [comment]
@k15a Yes, I use throttle. I don't use viewport units, because it's much harder to reason about in my case. My code:



```
// forceUpdateOnResize HOC

import React, {Component} from 'react';
import {debounce} from 'lodash';

export default function forceUpdateOnResize(WrappedComponent) {
  return class extends Component {
    constructor(props) {
      super(props);
      this.update = debounce(this.update, 300);
    }

    componentDidMount() {
      window.addEventListener('resize', this.update);
    }

    componentWillUnmount() {
      window.removeEventListener('resize', this.update);
    }

    update = () => {
      this.forceUpdate();
    };

    render() {
      return <WrappedComponent {...this.props}/>;
    }
  };
}
```


```
// getSize util
// returns some size depending on current window width 
// (simple linear function between two points)

const x1 = 1440; // max width (Desktop)
const x2 = 320; // min width (Mobile)

export default function getSize({to: y1, from: y2}) {
  if (window.innerWidth > x1) {
    return y1;
  }

  const k = (y1 - y2) / (x1 - x2);

  const b = y1 - k * x1;

  return k * window.innerWidth + b;
}

```

```
// some component (I have a lot of these)

import React, {Component} from 'react';
import styled from 'styled-components';
import {Container} from 'App/dumb';
import {Link} from 'react-router-dom';
import {forceUpdateOnResize, getSize} from 'App/utils';

const Wr = styled.div`
`;

const Content = styled.header`
  display: flex;
  width: 100%;
  justify-content: center;
  align-items: center;
`;

const LinkWr = styled(Link)`
  display: flex;
  text-decoration: none;
`;

@forceUpdateOnResize
export default class TokenLaunchHeader extends Component {
  render() {
    return (
      <Wr
        style={{
          padding: `${getSize({to: 15, from: 10})}px 0`,
        }}
      >
        <Container>
          <Content role="banner">
            <LinkWr
              to="/token"
              style={{
                fontSize: `${getSize({to: 20, from: 16})}px`,
                letterSpacing: `${getSize({to: 1.8, from: 0.5})}px`,
              }}
            >
              TOKEN LAUNCH COMING SOON >
            </LinkWr>
          </Content>
        </Container>
      </Wr>
    );
  }
}
```

As you can see, I have to use inline `style` here, because passing props (or setState) would be even more weird.

**Comment by philpl** [comment]
@mqklin I'd definitely say that this is an anti pattern unfortunately :/

> because passing props (or setState) would be even more weird, because of duplicating the code.

That's a symptom/sign of it already being tedious.

You can use `getSize` inside your `forceUpdateOnResize` decorator, rename it, and maybe even use `getSize` from a prop to make that decorator agnostic to what it's doing.

Then pass the result down as a prop. Also, maybe you can consider currying the function, and passing in `to` and `from` first, resulting in a function that accepts `innerWidth`. That could also help. Then you'd only have to pass in `innerWidth` from your container.

The problem with the pattern you're using specifically is that it's rerendering your component as a side-effect of a window resize, while it's a direct, reactive consequence of a window resize.

**Comment by mqklin** [comment]
Yes, this is an anti pattern from the theoretical point. 

But it's almost ideal for this case, because I just need to have different sizes depending on window width. I don't need to scale this somehow. And this solution is very easy to add/edit/remove components/styles.

Thank you for your suggestion, but this logic is unnecessary for me. I'm just building a landing page :) And I wanted to make the syntax less cumbersome, without inline `style` attribute. It would be ideal.

**Comment by mqklin** [comment]
Don't get me wrong. I respect patterns, but as an ordinary developer (compared to libraries/frameworks developers) I don't have to be very "smart", because my customer wants to get this site as soon as possible. And he doesn't care about patterns, so I choose the fastest way to build this landing.

**Comment by philpl** [comment]
@mqklin I fully understand :) it's just a suggestion after all. Adding the properties to inline styles is totally not as bad as it first looks, since until v3 (or a potential earlier release) it'll be faster than our style injection.

However, there are some libraries for HOCs which just inject the window dimensions. It'd probably be faster than writing this from scratch and cleaner. So you wouldn't even have to implement my suggestion yourself ;)

**Comment by grahm** [comment]
Hey @mqklin I wrote a small reflowing wrapper, I'm not sure of the implications from using "React.cloneElement" but it might help you out. https://codesandbox.io/s/y37jk1qq01
