### ISSUE TITLE
Passing props to styled component breaks & ~ & behaviour

### ISSUE THREAD

**Issue by mqklin** [styled-components/styled-components#920]
## Version
2.1.0

## Reproduction

https://codesandbox.io/s/qYzMBoQj7

## Steps to reproduce
Just watch

## Expected Behavior
`World` word should be red as well as `Bla`

## Actual Behavior
Only `Bla` is red

**Comment by philpl** [comment]
It's being tracked as failing tests over here: https://github.com/styled-components/styled-components/pull/784
