### ISSUE TITLE
className hash causing problem with jest enzyme snapshot test

### ISSUE THREAD

**Issue by zhenyulin** [styled-components/styled-components#925]
I'm using the latest version of `styled-components`, and the className hash mechanism certainly works beautifully. 

However, it is causing some problem for my CI pipeline. I'm using jest, enzyme, enzyme-to-json to do snapshot test to make sure any change made to react components, will not impact the behaviour of the components. New className hashes generated during the test from time to time is breaking the test. Is there a helper library or any solution to strip out classNames in the snapshots?

**Comment by k15a** [comment]
There is already an issue at https://github.com/styled-components/jest-styled-components/issues/29
