### ISSUE TITLE
Is "target" within the styled component constructor documented

### ISSUE THREAD

**Issue by L3ARNING2B** [styled-components/styled-components#929]
## Version
2.1.0

## Is `target` documented

I am trying to look after a `static propTypes templateId` of elements that could come from React or could be wrapped in Styled. I needed to find a way to get the value if the component is nested into styled composed components.

I noticed the key `target` within the constructor of the styled components : 

![image](https://user-images.githubusercontent.com/16323134/27254012-8dd256c2-53a9-11e7-9534-90b04272ca5b.png)

I haven't seen the target documented but this is the value I want. Is it reliable to use it for futur development.

Thanks in advance.

**Comment by mxstbr** [comment]
This is an internal API that we might change, rename, remove or break in any patch version, thusly I would strongly recommend not using it.

What are you trying to do? Maybe we can help you achieve it without relying on internal APIs!
