### ISSUE TITLE
How add styled-components as an external for the rollup build ?

### ISSUE THREAD

**Issue by L3ARNING2B** [styled-components/styled-components#930]
Thanks again for your incredible work, 

I'm trying to add styled-components in my `rollup.config.js` as the reproduction below, but it throw an error. I had the similar issue for `react-router-dom` and solved it by renaming `react-router-dom` into `react-router-dom/Link` in externals of `rollup.config.js`.

How to do with `styled-components` ?

## Version styled-components
2.0.1

## Version rollup-plugin-babel
2.7.1

## Reproduction
https://paste.gnome.org/p5cjgzrlk

## Steps to reproduce
Add styled-components as an external and global package in rollup.config.js as example in reproduction above.

## Expected Behavior
Allow rollup build

## Actual Behavior
Throw error when build with rollup:
 ````
(babel plugin) An unexpected situation arose. Please raise an issue at https://github.com/rollup/rollup-plugin-babel/issues. Thanks!
node_modules/styled-components/dist/styled-components.es.js
````

**Comment by L3ARNING2B** [comment]
Finally i resolve my need with this in my rollup.config.js

````
export default {
  ...
  external: ['styled-components'],
  ...
  globals: { 'styled-components': 'styled' },
};

````
It's depend on how we import the package, in my case I import it in my files as:

`import styled from 'styled-components';`

**Comment by philpl** [comment]
Hiya, sorry for not replying earlier. 

For future reference, you can probably find a lot of common patterns across rollup configs in other projects. Even ours for example: https://github.com/styled-components/styled-components/blob/master/rollup.config.js#L79

The guide is a bit imprecise on these things, but normally it should warn you about these things and prompt you to add a global. I'm not sure why it didn't do this in your case

**Comment by testacode** [comment]
Concha de su madre
