### ISSUE TITLE
Template literals, React's css-in-js and Composition

### ISSUE THREAD

**Issue by sonaye** [styled-components/styled-components#932]
Consider the following piece.

```javascript
// @flow

import React from 'react';

// we are building a native experience
import styled from 'styled-components/native';

// it has a wrapper (a simple blank page, or card)
const Full = styled.View({ flex: 1 });
// you are doing it wrong! template literals are mandatory(! || ?)

// and a button that has two states
type button = {
  label: string,
  disabled?: boolean
};

const Button = styled.TouchableOpacity(null, props => <ButtonView {...props} />);
// styled.element(styles: Object = {}, child: Function = null)
// this is a proposed API
// Button is a styled-component that has a styled-component as its child
// styled.Foo()              === <Foo />
// styled.Foo(null, <Bar />) === <Foo><Bar /></Foo>
// styled.Foo(null, 'Lorem') === <Foo>Lorem</Foo>

// is regular javascript that bad? why force a syntax?
// is there a specific limitation that forces us to use template literals?
const ButtonView = styled.View(
  {
    alignItems: 'center',
    backgroundColor: ({ disabled }) => (disabled ? '#d8d8d8' : '#fff'),
    borderColor: ({ disabled }) => (disabled ? '#d8d8d8' : '#4285f4'),
    borderRadius: 20,
    borderWidth: 0.5,
    height: 40,
    marginBottom: 10,
    marginTop: 10
  },
  props => <ButtonLabel {...props} />
);
// lovely! and what we are used to in React Native

// Some components accept strings or numbers or even functions that generate them
const ButtonLabel = styled.Text(
  {
    color: ({ disabled }) => (disabled ? '#444' : '#4285f4')
  },
  ({ label }) => label
);

const Example = () => (
  <Full>
    <Button label="I am a button!" />
    <Button label="I am a disabled button!" disabled />
  </Full>
);
```

### Ideas and questions from the snippet above

- **Using regular javascript instead of template literals** is this currently possible? why? it's not as confusing, more intuitive, and one could argue that it's cleaner. I don't suggest breaking the current API, just wondering if this is possible (maybe someone already built it) or if the maintainers are open to adding support for this in the future.

- **Using React's css-in-js engine directly**, especially in React Native, it doesn't make sense for someone who ran from web dev. in the first place to go back to using CSS, it's off-putting for those who do mobile first work. Is it possible to opt-out from `css-to-react-native`?

- **Composition of styled-components**, meaning that we can pass a child node to the styled component directly when we declare it, this can be very powerful. Notice in the snippet how we kept passing children from the top component, all the props are passed by default with context, React Native is not even directly used here! this is a proposition for a introducing a new feature.

Thanks for the great work, this a great tool, these were my first impressions after trying to use it for the first time.

**Comment by philpl** [comment]
- One of our core principals is writing actual CSS, so we won't support objects
- Tagged template literals are *regular* JavaScript, albeit a new ES.next feature :wink:
- Composition for us means CSS composition, which is solved through our mixins
- Component extension is solved using `.extend` or direct wrapping in the styled factory, we're not adding more APIs that make everything less elegant and minimal

If you prefer object syntax for writing styling, you should maybe check out glamorous :smile:

But from a React perspective styled-components has a certain experience for a reason, and this experience is implemented in an almost identical way for React Native for cross-compatibility and familiarity.

**Comment by sonaye** [comment]
>One of our core principals is writing actual CSS, so we won't support objects

That's a bit harsh, don't you think? why not support both, or at least keep that idea open for discussion.

I should've used "old school" javascript instead of regular, you are right. Glamorous's implementation is exactly what I am looking for, thanks for the suggestion.

`.extend` is different, the parent must be the same element in order for it to work, you cannot extend styles between different elements, (passing them as child nodes), is my understanding correct? I cannot extend a div from a span, can I?

> Composition for us means CSS composition, which is solved through our mixins

Could you elaborate more on this?

**Comment by geelen** [comment]
> That's a bit harsh, don't you think? why not support both, or at least keep that idea open for discussion.

This is actually something that's come up multiple times on the issue tracker. It's a core design choice of styled-components to use CSS as its primary API.

Objects are fully supported as interpolations though: `` styled.div`${ { alignItems: 'center', ... } }` ``

**Comment by philpl** [comment]
> That's a bit harsh, don't you think? why not support both, or at least keep that idea open for discussion.

Yes, No, maybe! 😆  We have a lot of discussions around feature and API proposals, and at a certain point in v2 we drew a more rigorous line of which discussions we open up. This is not to censor anything, or because we don't believe that the proposals are good, of course. But it simply comes down to two reasons:

- As we add more features and APIs, if we're not careful, we give ourselves less room for "manoeuvring" towards new optimisations and eliminating edge cases
- The other reason is simply about ideas; At a certain point some things fit into the narrative of the library and into the vision, and some don't. This is a bit hard to convey, as long as we don't have a document for it, admittedly ^^

> .extend is different, the parent must be the same element in order for it to work, you cannot extend styles between different elements, (passing them as child nodes), is my understanding correct? I cannot extend a div from a span, can I?

I'm not sure I'm following here? If you'd like to switch the target/element of a styled component, you have `withComponent`.

>> Composition for us means CSS composition, which is solved through our mixins
> Could you elaborate more on this?

The `css` helper can be used to create fragments of CSS, which behave like mixins: https://www.styled-components.com/docs/api#css

Btw that website has a bunch of information on all of this, so I hope the appropriate sections answer most of your questions. :)
