### ISSUE TITLE
render problem

### ISSUE THREAD

**Issue by xianshannan** [styled-components/styled-components#935]
```js
class Test extends React.Compoent {
  render(){
    var StyledDiv = styled.div`
      width: 20px;
    `;
    return <StyledDiv url={this.props.url}/>
 }
}
```
When change state ,compoents used with styled will be removed by React and rendered again,it will not use the old  rendered html.
This will be a performance problem.
The code below,will just be renderd again by old rendered html.
```js
class Test extends React.Compoent {
  render(){
    var style = {width: "20px"};
    return <div style={style}/>
 }
}
```

**Comment by xianshannan** [comment]
I decided to use styled, but there was such a problem.

**Comment by philpl** [comment]
Styled Components are not supposed to be created dynamically. If you reason about your render method, a new component is created an every update ;)

Check out the docs on our website for more concrete examples to get started
