### ISSUE TITLE
Version 2.1.0 problem with "em"

### ISSUE THREAD

**Issue by marcelotmagalhaes** [styled-components/styled-components#936]
Hello everyone, I've just installed styled-components 2.1.0 and am toying to learn how to use it. I've got an issue when trying to set padding to a TextInput using em:

import styled from 'styled-components/native';

const LoginInput = styled.TextInput`
  padding: 1em;
  height: 40px;
`;

The simulator returns an error:

Failed to parse declaration "padding: 1em".

I've browsed the docs but couldn't find anything to clarify this issue.
Am I missing something silly for this to work?

**Comment by philpl** [comment]
React Native only supports % and px units ;)

cc @jacobp100
