### ISSUE TITLE
How to avoid duplication when having dynamic additional classes

### ISSUE THREAD

**Issue by PengyuanZhao** [styled-components/styled-components#937]
Hi, I expected the following code generates a single class, e.g. `.asdf` for the `a` tag with additional classes `.asdf.title1`, `.asdf.title2`.  But it returns duplicate classes for each different `props.title`. Any way to get around this?

```javascript
const CategoryLink = styled.a`
  position: relative;
  margin: 0 5px;
  padding: 0 10px;
  border-radius: 3px;
  border: 1px solid #fff;
  ...
  &.${props => props.title}:after {
    background: url(${props => props.bgUrl}) no-repeat center center / cover;
  }
`;
```

**Comment by geelen** [comment]
Not yet, sorry. It's something that will probably come in v3 which is being actively worked on, but it doesn't make as much difference as you might think. In the browser, duplicate styles don't really matter, and for server-side-rendering, gzip will largely minimise the impact of the duplication.

But yes, in future it'll be a bit smarter about extracting things.
