### ISSUE TITLE
SSR causes flash when DOM loads

### ISSUE THREAD

**Issue by clayne11** [styled-components/styled-components#938]
I'm having an issue when using SSR. If I disable JavaScript, my styles load perfectly. When the DOM actually loads, however, there's a flash of unstyled content before it properly renders the page once again.

### JavaScript disabled
![screen shot 2017-06-21 at 9 34 36 pm](https://user-images.githubusercontent.com/2831444/27413457-79b18500-56c9-11e7-9b69-1be64dc5d044.png)

### Flash of unstyled content
![screen shot 2017-06-21 at 9 34 40 pm](https://user-images.githubusercontent.com/2831444/27413462-8513a2ca-56c9-11e7-9cfb-bf0a47fcb660.png)

Any ideas as to what might be causing this? I'm using the Babel plugin with `ssr: true`.

**Comment by geelen** [comment]
No please no I fixed this it can't be happening again pls I have a family

**Comment by geelen** [comment]
Seriously though, can you post a gist of your HTML as it comes down from the server (view source will do it) and once the rendering is finished (`document.documentElement.outerHTML` should do it). Or, even better, run them both through an autoformatter and then post a DIFF here?

And just to double check, you're on v2 yes?

**Comment by clayne11** [comment]
I figured it out. I created the diff, then realized that I was injecting the styles on the server side into the body, not into the head. I moved the styles into the head and the problem disappeared.

Thanks!
