### ISSUE TITLE
Best practice for styles with dynamic properties 

### ISSUE THREAD

**Issue by corbanbrook** [styled-components/styled-components#940]
When styled components use dynamic properties it creates a complete copy of all the rules for each possible value at run time which has potential to bloat SSR payload and in general add more content to memory.

```
const A = styled.div`
  ... many rules ...

  background-color: ${props => props.bg};
`
```

In this example many rules is duplicated whenever props.bg is changed.

In general I have been using the styled hoc to wrap a base styled component of static rules with my dynamic rules like:

```
const A = styled.div`
   ... many rules ...
`

const B = styled(A)`
  background-color: ${props => props.bg};
`
```

The many rules are created once and the dynamic rules classes only contain what change.

Could styled achieve this abstraction automatically by detecting dynamic parts? Could we "mark" with custom syntax which rules need to be added to dynamic classes within one component?

Im interested in hearing how other people handle this problem or if it is currently not a concern.

**Comment by k15a** [comment]
This will probably come with version 3 of styled-components. We try to extract every static style property and only inject dynamic ones at run times.

**Comment by corbanbrook** [comment]
For the time being do you think it is wise to defensively add dynamic rules in the way I described above, or simply wait and see when v3 is released? Our team is starting a giant styled components refactor and want to have some best practices in place for dealing with this.

**Comment by k15a** [comment]
I think it's not worth to split dynamic rules and static ones unless you have really really many styled-components and updating them often. I don't think duplicated styles are worth the added complexity. When you SSR gzip can handle the duplicated styles really well and browsers normally don't have any problem with many styles.

**Comment by corbanbrook** [comment]
Noticed this issue: https://github.com/styled-components/styled-components/issues/134

**Comment by k15a** [comment]
For highly dynamic styles you can also use the .attrs method:

```js
const ColorAnimation = styled.div.attrs({
  style: props => ({
    color: props.color
  })
})`
  // static styles
`
```

**Comment by mxstbr** [comment]
Yep, you won't run into any issues there we make very sure that the ordering is correct!

**Comment by 13luck** [comment]
Already 4 beta, but still nothing.
@k15a, also bad, cuz you generate too much inline `style`.
