### ISSUE TITLE
Styling Image - React Native

### ISSUE THREAD

**Issue by marcelotmagalhaes** [styled-components/styled-components#941]
Hello everyone, I had a screen using an Image tag to display a background image. With default react native styling it works, but when I tried to convert to a styled component, if returned an error.

The js:
```jsx
import React, { Component } from 'react';
import { Image } from 'react-native';
import styled from 'styled-components/native';

const bgImage = styled.Image`
  flex: 1;
  width: undefined;
  height: undefined;
  background-color: transparent;
  display: flex;
  align-items: center;
  justify-content: center;
`;

export default class LoginScreen extends Component {
  render() {
    return (
      <bgImage source={require('../images/login_bg.jpg')}>

      </bgImage>
    );
  }
}
```

The error in the simulator:
```
Expected a component class, got [object Object].
```

I have other components using TextInput ou TouchableHighlight, and the styling is working perfectly.

**Comment by k15a** [comment]
Your components have to begin with an upper case letter. This way React knows that you want to render a component and not a normal element.

**Comment by marcelotmagalhaes** [comment]
Jesus... Thanks a lot @k15a, that is embarassing.

Here is the working class, because some of the styling was also unsupported:

import React, { Component } from 'react';
import { Image, Text } from 'react-native';
import styled from 'styled-components/native';

export default class LoginScreen extends Component {
  render() {
    return (
      <BgImage source={require('../images/login_bg.jpg')}>
        <Text>Test</Text>
      </BgImage>
    );
  }
}

const BgImage = styled.Image`
  background-color: transparent;
  display: flex;
  align-items: center;
  justify-content: center;
`;

**Comment by k15a** [comment]
Yes this is not supported:
```css
width: undefined;
height: undefined;
```

FYI you can use code fences to hightlight code in GitHub issues:

````md
```js
// code
```
````
