### ISSUE TITLE
Creating class from JS for passing to third party components

### ISSUE THREAD

**Issue by nschlehe** [styled-components/styled-components#943]
Is there any possibility to create classes from within JS to pass to third party components like e.g. CSSTransitionGroup or react-virtualized?
I'm looking for something like the following:
```js
const onEnterClass = styled.className`
   background-color: red;
`;

// This className can now be passed to third party components
<CSSTranstitionGroup
    transitionName={{
        enter: onEnterClass,
  }} />
```

**Comment by k15a** [comment]
This should work:

```jsx
const onEnterClass = btoa(Math.random())

const Component = styled(CSSTransitionGroup).attrs({
  transitionName: {
    enter: onEnterClass
  }
})`
  ${onEnterClass} {
    // rules
  }
`;

  <Component />
```

**Comment by nschlehe** [comment]
Thanks @k15a,
that was fast! Now SC feel even more awesome :)

**Comment by philpl** [comment]
To add to this, use a "magic string" constant like `const onEnterClass = '.is-entering'`, since `Math.random` is problematic in combination with SSR.

**Comment by k15a** [comment]
Yes, that's totally right. `const onEnterClass = btoa(Math.random())` wouldn't even work because it's not a class.

**Comment by szilagyikinga** [comment]
I am using the method described above but to add a custom "className" to a third party library:

```
const pageClassName = 'page';
const StyledReactPaginate = styled(ReactPaginate).attrs({
  pageClassName
})`
  .${pageClassName} {
     color: red;
  }
`;
```

The props pageClassName is correctly passed to the component but the css in not added to the page. Any idea what can be wrong? I am using styled-components 2.1.1

**Comment by k15a** [comment]
@szilagyikinga Maybe you should open an issue at ReactPaginate so they add the className prop to the dom. :)

**Comment by okcoker** [comment]
In searching for my particular issue, I keep ending up here so maybe I'm missing something.

If I have a button defined something like:
```js
const Button = styled.button`
   color: #000;
   background: #fff;
`;
```

How can I use the generated class name from `Button` for a library component? I'm not creating a new class here like the above comments. I'm just trying to do something like:

```js
<LibraryComponent className={Button.className} />
```

Is the expected solution for this supposed to be the following?

```js
styled(LibraryComponent)`
     ...duplicated Button styles
`
```

**Comment by k15a** [comment]
You can create a new Button component just for the LibraryComponent with the styles of your own Button component with `withComponent`.

```js
const Button = styled.button`
   color: #000;
   background: #fff;
   someDynamicRule: ${props => props.whatever ? whatever : okay};
`

const LibraryButton = Button.withComponent(LibraryComponent)
```

I hope that this is what you're looking for.

**Comment by okcoker** [comment]
@k15a I think that is indeed the correct function but doing `const LibraryButton = Button.withComponent(LibraryComponent)` doesn't account for the `whatever` attribute. Is the only way to have `LibraryComponent` have the same styles as `<Button whatever />` to have a separate extended component?
