### ISSUE TITLE
react-styleguidist compatibility

### ISSUE THREAD

**Issue by michaseel** [styled-components/styled-components#945]
@gweax already mentioned it in #637: It´s pretty hard to document your styled-components with react-styleguidist. 

**Example:**

```
const H1 = styled.h1`
  font-size: 1.5em;
  text-align: center;
`;
export default H1
```

does not export a real react component, that react-styleguidist can display.

instead i always need to do this **workaround**:

```
const H1 = styled.h1`
  font-size: 1.5em;
  text-align: center;
`;

const Headline = props => <H1 {...props} />;

export default Headline;
```

What is the Problem here? Or is it an issue with react-styleguidist?

**Comment by geelen** [comment]
Hmm that's strange. Does react-styleguidist work with, say, things that are wrapped in a Redux `connect` call? Because SC works really similarly—it's definitely exporting real React components, so there's no reason it shouldn't work...

**Comment by philpl** [comment]
We'll probably need more material to figure this out. Unfortunately, I believe we won't have time to set this up ourselves :(

Can you give us some details on what should happen, and some potential output?

This might be a problem with us not directly extending React.Component maybe?

**Comment by sapegin** [comment]
We actually have a @mxstbr approved way of using Styled Components with Styleguidist in the docs:

https://react-styleguidist.js.org/docs/cookbook#how-to-use-react-styleguidist-with-styled-components

**Comment by philpl** [comment]
@sapegin why's this workaround necessary? :smile: any way we can make it work without it?

**Comment by sapegin** [comment]
The only way I see it to make react-docgen understand this kind of exports: https://react-styleguidist.js.org/docs/components.html#limitations

**Comment by philpl** [comment]
@sapegin Aha, ok. So dynamically generated components will not be able to be targeted right now. Looks like that's an issue that can be opened over at styleguidist or react-docgen then :wink:

**Comment by mxstbr** [comment]
See here, apparently somebody just needs to build an extension to `react-docgen`? https://github.com/reactjs/react-docgen/issues/187

**Comment by philpl** [comment]
> I don't think it would beneficial to include this into the core. I wouldn't have the capacity to maintain it and it would make it harder for others (you I guess) to maintain it.

> react-docgen was built with custom extensions in mind, so I think an external package would make more sense, but I'd be happy to make changes to core as necessary to support this case.

looks like it's kind of up to us and styleguidist 😆

**Comment by sapegin** [comment]
I’m sure @mxstbr could help with marketing of this idea ;-)

**Comment by nickbreaton** [comment]
This may be something to bring up with react-styleguidist, but maybe we can make a resolver that basically "trusts" that we export a component. 

Basically anything with prop types could be valid:

```js
const MyComponent = {};

MyComponent.propTypes = {
  // ...
};

export default MyComponent;
```

Of course this would error when you try to render it, but it would be very useful for anything using prop types including styled-components: 

```js
const MyStyledComponent = styled.div`
  ${/* some styles */}
`;

MyStyledComponent.propTypes = {
  // ...
};

export default MyStyledComponent;
```

This could potentially help with `connect` issues and other similar problems. I would need to look more into how react-docgen does stuff, but it seems like a potential option that could extend past the styled-components community.

**Comment by sapegin** [comment]
I think simplified (trusting) loader should work in this case.

Someone in react-docgen issues was also suggesting to use comments to mark components, like this:

```js
/**
 * @component
 */
const MyStyledComponent = styled.div`
  ${/* some styles */}
`;

MyStyledComponent.propTypes = {
  // ...
};

export default MyStyledComponent;
```

**Comment by nickbreaton** [comment]
Yeah I think that might be the ideal API. I will definitely look into it soon.

**Comment by juanmndz** [comment]
I am wondering about the performance difference of using styled components under the recommended method in the docs vs the normal/simple way of creating it. I believe there is a minuscule difference but would like a technical answer.

**Comment by Jmeyering** [comment]
@nickbreaton 

I'm on the same page that the currently recommended "solution" doesn't work for many use cases and strips `styled-components` of a lot of it's functionality.

So I don't know what you have accomplished toward this yet, but I'm pretty motivated to create a solution to this problem. I've created an Annotation Resolver for react-docgen.

https://github.com/jmeyering/react-docgen-annotation-resolver

Currently this works and adds exports annotated with `@component` to the react-docgen definitions list, but react-docgen isn't able to handle the `TaggedTemplateExpression` node type at this point, so I think we are going to have to submit a PR to `react-docgen` enabling this functionality. 

Anyway any input you have would be helpful and if we could get this working that would be awesome.

**Comment by nickbreaton** [comment]
@Jmeyering 

I haven't gotten around to doing any work on this at all. I'm excited to hear the progress you have made. If you need any help, I can probably be of assistance.

**Comment by Jmeyering** [comment]
Submitted 

https://github.com/reactjs/react-docgen/pull/195

Which will enable react-docgen to work with styled components and the annotation resolver.

**Comment by jony89** [comment]
see my comments here as well : https://github.com/styled-components/styled-components/issues/637#issuecomment-332252608 

Hiding propTypes in the `StyledComponent` causes many more issues, examples : 

1. react styleguide
2. `storybook` + `info` addon
3. [react2angular](https://github.com/coatue-oss/react2angular)

**Comment by Jmeyering** [comment]
This problem is mostly solved and we're primarily waiting on react-docgen to merge in some PRs.

https://github.com/reactjs/react-docgen/pull/198

**Comment by kizu** [comment]
It seems that ↑ pr to docgen was merged, yay :)

**Comment by mxstbr** [comment]
Can somebody confirm that `styleguidist` now works out of the box with styled-components? :blush:

**Comment by Jmeyering** [comment]
While not "out of the box" it works with a styleguidist configuration tweak.

```
//styleguide.config.js
const annotationResolver = require("react-docgen-annotation-resolver").default;

  module.exports = {
  ...
    resolver: (ast, recast) => {
      const annotatedComponents = annotationResolver(ast, recast);
      const defaultComponents = defaultResolver(ast, recast);

      return annotatedComponents.concat(defaultComponents);
    },
  ...
}
```

**Comment by Jmeyering** [comment]
I've been meaning to PR some documentation but haven't found the time

You will need to also annotate styled-components that are exported
```
const MyComponent = styled.div``;

/**
  * @component
  */
export default MyComponent
```

**Comment by okonet** [comment]
@Jmeyering which version of RS is needed to make this work?

**Comment by sapegin** [comment]
@Jmeyering That’s awesome! I think we can enable this by default in Styleguidist.

**Comment by okonet** [comment]
@Jmeyering thanks for this! I've been using this solution for https://react.feedly.com and it's working great. This will become styleguidist default soon!

**Comment by Jmeyering** [comment]
👍  Glad this is working for everyone! I'm excited about this being enabled by default.

**Comment by lookapanda** [comment]
@Jmeyering This doesn't seem to work for me, sadly. I have the same as you above, but I still get that warning:

```
Warning: src/components/Card/Card.js matches a pattern defined in “components” or “sections” options in your style guide config but doesn’t export a component.
```

```jsx
const Card = styled.div`
 // some styles
`;

/**
 * @component
 */
export default Card;
```

**Comment by stepankuzmin** [comment]
Same as @lookapanda here.

```js
import React from 'react';
import styled from 'styled-components';

const SalmonButton = styled.button`
  background-color: salmon;
  border: 1px solid indianred;
  color: snow;
`;

/**
 * @component
 */
export default SalmonButton;
```

```js
"styled-components": "2.2.4"
"react-styleguidist": "6.0.33"
```

**Comment by sapegin** [comment]
It wasn’t released yet, will be out in 6.1.0 soon.

**Comment by fredjens** [comment]
Anyone having trouble with PropTypes not showing up?

```
import styled from 'styled-components';
import PropTypes from 'prop-types';

const Button = styled.button`
  background-color: red;
`;

Card.PropTypes = {
  large: PropTypes.bool,
};

/**
 * @component
 */
export default Button;
```
Styleguidist render the component, but the props are missing under **props & methods**.

**Comment by dallonf** [comment]
Try s/`Card.PropTypes`/`Card.propTypes`; I believe static prop types are lowercase.
