### ISSUE TITLE
Does styled-component allow css hot reloading?

### ISSUE THREAD

**Issue by bernatfortet** [styled-components/styled-components#946]
I've been looking in the documentation but I can't find if it's possible yet or not.

It's definitely not working on my end.

In my project normal css does the hot reloading.

Thanks

**Comment by philpl** [comment]
There is no explicit mechanism for css hot reloading. When hot reloading React components, styled-components will just reinject the CSS code.

Have you set up hot reloading correctly for js and React?

**Comment by bernatfortet** [comment]
I'm using the default [creact-react-app](https://github.com/facebookincubator/create-react-app) configuration. It comes with css hot reloading by default.

But it doesn't apply to styled-components. Probably because Styled-components are inside of .js files?

**Comment by k15a** [comment]
Create-react-app doesn't hot reload JS and React components. This means that styled-components aren't hot reloaded as well and thus our styles aren't hot reloaded as well because we don't generate .css files.

**Comment by bernatfortet** [comment]
@k15a that makes sense! after diving deeper into create-react-app's configuration I understand.

I'm adding hmr now but having some trouble.

Thanks anyway!
