### ISSUE TITLE
Adding Attr to non styled components

### ISSUE THREAD

**Issue by bernatfortet** [styled-components/styled-components#947]
## Version
2.0.1

When I do the following:
```
styled(MyComponent).attr({ title: 'foo' })` background:red; `
```
MyComponent is a react component

I get:

`__webpack_require__.i(...)(...).attr is not a function`

**Comment by k15a** [comment]
The method name is attrs.

**Comment by philpl** [comment]
I'll leave a link to the API docs here, if anyone finds this through the search :wink: https://www.styled-components.com/docs/api
