### ISSUE TITLE
Integrate Danger

### ISSUE THREAD

**Issue by mxstbr** [styled-components/styled-components#95]
[Danger](http://danger.systems) is a bot that let's you write rules that are used to automatically check each PR for common problems. (like "you forgot to add a changelog entry")

It's written in Ruby (a JS port is being worked on, though it's not ready yet), and I haven't done Ruby in a while, so I'd love if somebody from the community could help out with this!

*I might have to do some setup for the repo or a bot, but I'm sure we can figure that out as we go along in a PR.*

----

Some of the rules I imagine would be useful for this repo:

- Enforce CHANGELOG.md entries for each PR that touches `.js` files
- A change was made in `StyledComponent.js` that wasn't made in `StyledNativeComponent.js` – warn that this might have to be done
- Warn that changes to `ThemeProvider.js`, `StyledComponent.js` or `StyledNativeComponent.js` might be semver major changes if they touch the `context` stuff
- Don't let testing shortcuts be merged into master (`fit`, `fdescribe`, `it.only`, `describe.only`)
- Enforce rebases to remove "Merge master into bla" commits?
- Enforce that a test must be added for the changes? (not sure if this makes sense for everything, maybe enforce for all `.js` files in the `src/` folder except for `src/vendor`)
- Enforce a certain commit style? Not sure if this is really necessary.
- Anything else you can come up with that might be an issue with PRs more often than not!

**Comment by nickgnd** [comment]
Hi @mxstbr, I'd like work on this 😄 
I'll let you know how i proceed and I'll send you PR asap

**Comment by mxstbr** [comment]
Awesome, let me know how it goes!

**Comment by mxstbr** [comment]
Hey @nickgnd, just wondering if you maybe ran into issues? Can I help?

**Comment by nickgnd** [comment]
Hi @mxstbr, it's all ok :) Thanks for your interesting. I think I'll be able to send you a PR tomorrow night with almost all the rules you listed in the first comment, then we can improve them to better fit the project's needs.

The only thing a bit difficult is to test the rules specified because, also if I run Danger locally, it tests the rules against the latest Github PR, but it's not blocking

**Comment by mxstbr** [comment]
> I think I'll be able to send you a PR tomorrow night with almost all the rules you listed in the first comment, then we can improve them to better fit the project's needs.

Awesome, sounds good to me! Feel free to submit a WIP PR so you can iterate on the output!

**Comment by mxstbr** [comment]
Done by the amazing @nickgnd in #121! 🎉

**Comment by nickgnd** [comment]
@mxstbr wow, thanks! Let me know if you need further help on ruby stuff 🤓  💎
