### ISSUE TITLE
'writing-mode' property not prefixed

### ISSUE THREAD

**Issue by cohesively** [styled-components/styled-components#950]
## Version
2.1.0

## Steps to reproduce
Create a component using the following...
```
import styled from "styled-components";

const StyledDiv = styled.div`
  writing-mode: vertical-lr;
`;
```

## Expected Behavior
According to [Autoprefixer](https://autoprefixer.github.io/), the following CSS should be emitted:
```
-webkit-writing-mode: vertical-lr;
    -ms-writing-mode: tb-lr;
        writing-mode: vertical-lr;
```

## Actual Behavior
It appears that only the input property is emitted...
```
writing-mode: vertical-lr;
```

**Comment by k15a** [comment]
@thysultan

**Comment by mxstbr** [comment]
Moved to our parser: https://github.com/thysultan/stylis.js/issues/40
