### ISSUE TITLE
Using SC to style components that accept multiple classNames for different elements

### ISSUE THREAD

**Issue by sanfilippopablo** [styled-components/styled-components#951]
The standard way of styling components in React is passing a className to the component. SC takes advantage of that and injects automatically a className to the styled component. However, there are some third party components that accept multiple classNames for styling different parts of the component, like innerClassName, arrowClassName, or something like that. Another variation of this is react-toolbox, that accepts a theme prop wich is an object that contains multiple className for the different parts of the component.

With glamor, this is really easy:
```es6
import { css } from 'glamor'
import TheComponent from 'the-library/TheComponent'

let rule = css({
  color: 'red',
  ':hover': {
    color: 'pink'
  }
})

const Comp = () => (
  <TheComponent innerClassName={rule.toString()} />
)
```

I believe there is no way of doing this right now with styled-components. What can we do?

**Comment by sanfilippopablo** [comment]
Right off the top of my head, I'd like to do something like this:
```es6
import styled from 'styled-components'
import TheComponent from 'the-library/TheComponent'

const TheStyledComponent = styled(TheComponent)`
  %innerClassName {
    color: red;
    &:hover {
      color: pink;
    }
  }
`
```

Or something like that, you get the idea.

**Comment by k15a** [comment]
Take a look at https://github.com/styled-components/styled-components/issues/943

**Comment by sanfilippopablo** [comment]
Ahh, so sorry. I'm made a quick search but didn't find anything. Thanks!
