### ISSUE TITLE
React native: ScrollView scrolls to top on rerender

### ISSUE THREAD

**Issue by maksimdegtyarev** [styled-components/styled-components#953]
## Version
2.1.0

## Reproduction

```javascript
import React, { Component } from 'react';
import {
  AppRegistry,
  StyleSheet,
  Text,
  View,
  ScrollView
} from 'react-native';
import styled from 'styled-components/native';

export default class react_native_test extends Component {
  constructor(props) {
    super(props);
    this.state = {
      arg: 0
    };
  }
  componentDidMount() {
    window.setTimeout(() => {
      console.log('update');
      this.setState({
        arg: 1
      });
    }, 5000);
  }
  render() {
    const StyledScrollView = styled.ScrollView`
      flex: 1;
      paddingTop: 20;
    `;
    return (
      <StyledScrollView>
        {
          Array(100).fill('1').map((item, i) => <Text key={i}>{i}</Text>);
        }
      </StyledScrollView>
    );
  }
}

```

## Steps to reproduce
Wrap ScrollView component into styled.ScrollView and add any styles. Then just call setState and initiate rerender process. After rerender ScrollView scrolls to top.

## Expected Behavior
ScrollView save its scroll position.
## Actual Behavior
![styled](https://user-images.githubusercontent.com/2942880/27560536-2a9bbe7e-5acd-11e7-9624-c9014095e118.gif)
## PS
The same problem with TextInput. If we wrap TextInput into styled.TextInput, its lose own focus after component rerender.

**Comment by philpl** [comment]
```js
// ...
  render() {
    const StyledScrollView = styled.ScrollView`
      flex: 1;
      paddingTop: 20;
    `;
// ...
```

You're creating styled components dynamically here. This is not only slow, it's an anti pattern and leads to the behaviour you describe since the list and all its children **fully unmount and remount** on every render.

Remember that every styled component is a an **actual component**, that shouldn't be created dynamically. :wink:

For more pattern, check out our docs here: styled-components.com

**Comment by skantus** [comment]
> ```js
> // ...
>   render() {
>     const StyledScrollView = styled.ScrollView`
>       flex: 1;
>       paddingTop: 20;
>     `;
> // ...
> ```
> 
> You're creating styled components dynamically here. This is not only slow, it's an anti pattern and leads to the behaviour you describe since the list and all its children **fully unmount and remount** on every render.
> 
> Remember that every styled component is a an **actual component**, that shouldn't be created dynamically. 😉
> 
> For more pattern, check out our docs here: styled-components.com

You saved my day 💯
