### ISSUE TITLE
How to write common styles for two different elements?

### ISSUE THREAD

**Issue by THPubs** [styled-components/styled-components#954]
I have two components like this:
```jsx
export const ContactInput = styled.input`
  background-repeat: no-repeat;
  background-size: 1.5vw;
  background-position-y: 0.4vw;
  background-position-x: 100%;
  background-image: ${(props) => {
    if (props.valid === 'yetToValidate') {
      return `url(${warningIcon})`;
    } else if (props.valid === 'valid') {
      return `url(${successIcon})`;
    }
    return `url(${errorIcon})`;
  }};
`;

export const ContactInput = styled.textarea`
  background-repeat: no-repeat;
  background-size: 1.5vw;
  background-position-y: 0.4vw;
  background-position-x: 100%;
  background-image: ${(props) => {
    if (props.valid === 'yetToValidate') {
      return `url(${warningIcon})`;
    } else if (props.valid === 'valid') {
      return `url(${successIcon})`;
    }
    return `url(${errorIcon})`;
  }};
`;
```
As you can see, both the elements have the same styling. But they are two different elements. An `input` field and a `textarea`. How can I add a common style to this? The biggest Issue I have is both use props.

**Comment by philpl** [comment]
You can use mixins to  share code using the `css` helper, which is just another tagged template literal function:

```js
const mixin = css`
  background-repeat: no-repeat;
  background-size: 1.5vw;
  background-position-y: 0.4vw;
  background-position-x: 100%;
  background-image: ${(props) => {
    if (props.valid === 'yetToValidate') {
      return `url(${warningIcon})`;
    } else if (props.valid === 'valid') {
      return `url(${successIcon})`;
    }
    return `url(${errorIcon})`;
  }};
`

const ContactInput = styled.textarea`
  ${mixin}
`
```

https://www.styled-components.com/docs/api#css

**However** since you're only changing the tag here, it's advisable to use the `withComponent` method:

```js
const ContactTextarea = ContactInput.withComponent('textare')
```

https://www.styled-components.com/docs/api#withcomponent

Here is some prose on the extension pattern: https://www.styled-components.com/docs/basics#extending-styles

**Comment by THPubs** [comment]
Thanks @philpl I tried withComponent but got this error: `ContactInput.withComponent is not a function`. Any idea why?

**Comment by philpl** [comment]
@THPubs Make sure you're on v2 :wink:

**Comment by THPubs** [comment]
@philpl  Ahaa! Worked like a charm! Thanks a lot :smile:
