### ISSUE TITLE
[feature request] support styling Route element of 'react-router'

### ISSUE THREAD

**Issue by zhenyulin** [styled-components/styled-components#958]
It has been a bit tricky to apply global style with styled-components, and I don't want to use css-loaders just for several lines of global css code, and ideally position I found to inject the global style is at the Router object of react-router, which works well with redux `connect` function at the moment, but doesn't seem to respond to `styled`. Would it be possible to make it work here?

**Comment by epilande** [comment]
You can apply global styles using `injectGlobal`.

https://www.styled-components.com/docs/api#injectglobal

**Comment by mxstbr** [comment]
The `react-router` `Route` component only renders the component you pass it and doesn't take any styling properties, no class names and no `style` prop, so even if you injected global styles with `injectGlobal` they wouldn't be applied. (see [the render method of the Route component](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/modules/Route.js)

If you could tell us what you're trying to do we could help you more, but alas there's nothing styled-components (or a global CSS file for that matter) can do to help you here.

**Comment by zhenyulin** [comment]
@mxstbr thanks for demystifying this. I'm trying to find a proper place to define global styles, such as custom font, etc, without using anything other than styled-components. The idea behind my question is to bind the global style to a top level component/container, where the Router component appears to be a very good position. I may also try the even higher level App component, since Router doesn't render any style props.

It looks pretty much like what `injectGlobal` is doing. What would be the best-practice position to use `injectGlobal` under the file structure? This is currently a bit confusing, and I want to make a standard practice so that developers in my team can stick to it.

**Comment by k15a** [comment]
You should probably use injectGlobal just once and put it into your index.js file.

**Comment by zhenyulin** [comment]
@k15a thanks for the suggestion!

I'm using ThemeProvider as well, would it work somehow to inject them to the theme?

**Comment by zhenyulin** [comment]
```
import React from 'react';
import { Provider } from 'react-redux';
import { ThemeProvider, injectGlobal } from 'styled-components';
import createHistory from 'history/createBrowserHistory';
import { ConnectedRouter } from 'react-router-redux';

import setupStore from './store';
import Router from './router';
import { colors } from './theme';

const history = createHistory();
const store = setupStore(history);

export default function App() {
  return (
    <Provider store={store} >
      <ThemeProvider theme={colors}>
        <ConnectedRouter history={history}>
          <Router />
        </ConnectedRouter>
      </ThemeProvider>
    </Provider>
  );
}

injectGlobal`
  color: green;
`;
import React from 'react';
import { Provider } from 'react-redux';
import { ThemeProvider, injectGlobal } from 'styled-components';
import createHistory from 'history/createBrowserHistory';
import { ConnectedRouter } from 'react-router-redux';

import setupStore from './store';
import Router from './router';
import { colors } from './theme';

const history = createHistory();
const store = setupStore(history);

export default function App() {
  return (
    <Provider store={store} >
      <ThemeProvider theme={colors}>
        <ConnectedRouter history={history}>
          <Router />
        </ConnectedRouter>
      </ThemeProvider>
    </Provider>
  );
}

injectGlobal`
  color: green;
`;
```

Had a quick try of `injectGlobal`, which doesn't seem to work for me here, anything I took wrong?

**Comment by k15a** [comment]
You can't use the theme in injectGlobal. Then it's bet to create a Root component and inject the global styles there:

```jsx
const Root = styled.div`
    // global styles
`

const App = () => (
    <Router>
        <ThemeProvider>
            <Root>
                 <YourApp />
             </Root>
        </ThemeProvider>
    </Router>
)
```

**Comment by zhenyulin** [comment]
@k15a , my current solution is creating a Base component util, and wrap it on every container component passed to Route in Router

**Comment by k15a** [comment]
If you move your Base component to the position I mentioned you wouldn't have to wrap every component and can't forget it.

**Comment by zhenyulin** [comment]
Hi @k15a ,

Here's the render() of the <Router /> I posted earlier
```
render() {
    const { pages, footers } = this.props;
    const homePage = pages[0];
    return (
      <Switch>
        {pages.map(p => (
          <Route key={p} path={pagenameToRoute(p)} component={pagenameToComponent[p]} />
        ))}
        {footers.map(p => (
          <Route key={p} path={pagenameToRoute(p)} component={Home} />
        ))}
        <Redirect from="/" to={pagenameToRoute(homePage)} />
      </Switch>
    );
  }
```

follow your suggestion, should I move the <Base> to 
```
  <Provider store={store} >
      <ThemeProvider theme={colors}>
        <ConnectedRouter history={history}>
          <Base>
          <Router />
          </Base>
        </ConnectedRouter>
      </ThemeProvider>
    </Provider>
```
 This looks quite like `export default styled(Router)  ` to me

**Comment by zhenyulin** [comment]
@k15a tested it, works well. Thanks.

**Comment by zhenyulin** [comment]
@k15a the style works well, but it breaks the Router function actually for some reason

**Comment by zhenyulin** [comment]
```
export default function App() {
  return (
    <Provider store={store} >
      <ThemeProvider theme={colors}>
        <GlobalStyle>
          <ConnectedRouter history={history}>
            <Router />
          </ConnectedRouter>
        </GlobalStyle>
      </ThemeProvider>
    </Provider>
  );
}
```

This works well, think it might be useful to share.

**Comment by k15a** [comment]
Yeah I could imagine that `<Router />` must be a direct child of `<ConnectedRouter />`

**Comment by zhenyulin** [comment]
@k15a it looks like, in theory this might be something can be integrated into the <ThemeProvier>?

maybe like a props `<ThemeProvider globalStyle={} >`

**Comment by k15a** [comment]
In theory, we could add this of course but I don't think we should because we already have the tools to inject globals styles and it's pretty easy so we shouldn't add any more complexity.

**Comment by epilande** [comment]
@zhenyulin in https://github.com/styled-components/styled-components/issues/958#issuecomment-312240894, I think `injectGlobal` isn't working because you need to add a selector.   

Something like this should work.
```diff
injectGlobal`
+  body {
     color: green;
+  }
`;
```




Also you should be able to use your theme in `injectGlobal`. Assuming your theme is a javascript object, you can import it through out your app and use it just like any object. 

This is how my `global.js` looks like, then I import it in my app's main entry point.

```javascript
import { injectGlobal } from 'styled-components';
import fonts from './fonts';
import theme from './theme';

injectGlobal`
  html {
    background: ${theme.lightBackgroundColor};
  }

  body {
    font-family: ${theme.baseFont};
    color: ${theme.textColor};
  }

  ${fonts}
`;
```

**Comment by k15a** [comment]
@epilande Yeah of course totally missed that! Nevertheless, you can't use theme in ThemeProvider

**Comment by epilande** [comment]
Yeah that's the caveat; could lead to theme miss match if you change the `theme` in `ThemeProvider`

**Comment by OlivierDelalande** [comment]
Hello,

the doc says injectGlobal is deprecated, is there a way then to have react router and GlobalStyle from styled components working together ?

Having a app.js like this ? It seems i can't have GlobalStyle invoked like this...

...
render() {
    return (
        <Fragment>
          <Route ... />
          <Route ... />
          <GlobalStyle />
        </Fragment>
    );
  }
}
