### ISSUE TITLE
Controlling order of injectGlobal 

### ISSUE THREAD

**Issue by alexcroox** [styled-components/styled-components#965]
## Version
2.1.0

## Reproduction
Adding an `injectGlobal` in entry container
```
import cssReset from 'css-wipe'

injectGlobal`
   ${cssReset}
`
```

## Expected Behavior
Add reset styles to top of head

## Actual Behavior
It adds styles to bottom of head, below component specific styling

**Comment by sfrieson-tm** [comment]
This is an issue for me as well.  We have a few basic classnames like `.clearfix` and `.visually-hidden` that still need to be supported and work generally well, but every once in a while, the cascade will not result in the order we want/expect it to because we've expected the globals to be at the top.

**Comment by philpl** [comment]
This is not limited to `injectGlobal` as all styles will now end up in one style sheet that can be rehydrated. So I'm going to go ahead and close this issue and all future discussion can be moved here :wink: https://github.com/styled-components/styled-components/issues/860

@sfrieson-tm I think you're talking about the order inside the stylesheet here and not about the position of the style tag? That is a different question and handled by the *time* when you call `injectGlobal`. Make sure that it's called as early as possible and you shouldn't see any issues. If you do, try to increase specificity by doubling the class etc. You can also just use mixins, which is a more best practice oriented approach

**Comment by alexcroox** [comment]
This thread was about the position of the style tag for injectGlobal, it was being added after normal styled-components rules, when it was expected to be at the top as typically injectGlobal is used to add third party styles that might need to be overwritten inside components.

**Comment by philpl** [comment]
@alexcroox there is no separate style tag for it anymore, so you can't rely on that. It is meant as an escape hatch and thus not suitable for every scenario. However, if we fix the overall position of the style tag to be determinable, then you can rely on the fact that its styles will come first when the `injectGlobal` function is called before creating any other StyledComponents
