### ISSUE TITLE
.withComponent(Link) 'Unknown prop'

### ISSUE THREAD

**Issue by GoldenRust** [styled-components/styled-components#967]
When changing a styled components element using `withComponent` with `Link` from `react-router-dom` causes errors in react.

## Version
2.1.1
## Reproduction
https://www.webpackbin.com/bins/-KoDDes4XCRS2-VxAroy
(Look in console - not the log in webpackbin)
## Steps to reproduce
Create Styled component, change element to `Link` using `withComponent`
## Expected Behavior
Props not to be passed to html element
## Actual Behavior
Props are passed to html element
`Warning: Unknown prop 'primary' on <a> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in a (created by Link)
    in Link (created by Styled(Link))
    in Styled(Link) (created by Buttons)`

**Comment by k15a** [comment]
That's because we are only filtering props for HTML elements and not for React components.

**Comment by GoldenRust** [comment]
Thanks for clearing that up for me.

I thought this might be an issue with `react-router`'s Link component... 

Is there any workaround for this? I'd like to be able to have props on styled components using `Link`.

Since this isn't really an issue, I'll close this.

**Comment by philpl** [comment]
> Is there any workaround for this? I'd like to be able to have props on styled components using Link.

Unfortunately to get rid of it, you'll have to filter the props yourself by wrapping Link. This will be solved eventually, if/once React introduces prop namespaces. You can also just ignore the warning, since it's safe to render unknown props.
