### ISSUE TITLE
Custom namespacing and overriding

### ISSUE THREAD

**Issue by alex88** [styled-components/styled-components#968]
Question: We're trying to use styled components to style react components that'll be rendered on third party webpages.

I've looked at the docs and asked on gitter but haven't found an answer. Is there a way to apply a custom class prefix? Just to ensure it's something 'reserved' to our components and won't impact any other page?

Also would be possible to go create a global function/helper that goes through every rule and do something? (e.g. add !Important)

**Comment by k15a** [comment]
Why would you want to add a custom prefix if any class is a hash anyway? No one writes random classes in real CSS so you shouldn't worry about that.

It's not possible to go through all rules and add !important as far as I know.

**Comment by alex88** [comment]
@k15a well, just to be sure, if the host page uses styled components it's rare but not impossible right?

**Comment by probablyup** [comment]
It's like worrying about guids. Random enough that you shouldn't pay it
mind.

**Comment by alex88** [comment]
Well guids are much longer, anyway thanks for the explanation :)

**Comment by mxstbr** [comment]
The class is based on a hash of the contents of the class, so even if the classes overlap they'll apply the same styling anyway and it wouldn't matter!

**Comment by philpl** [comment]
- The changing class is based on the `componentId` and the generated CSS: https://github.com/styled-components/styled-components/blob/master/src/models/ComponentStyle.js#L32
- The `componentId` is based on the `displayName` plus an increment: https://github.com/styled-components/styled-components/blob/master/src/models/StyledComponent.js#L178
- murmurhashes are unlikely to collide

So you should be fine :smile:

If you'd like to guarantee uniqueness in an even safer manner, you can use the babel plugin to generate a `componentId` based on the file's properties as well: https://github.com/styled-components/babel-plugin-styled-components/blob/master/src/visitors/displayNameAndId.js#L88

**Comment by alex88** [comment]
Thank you @philpl for all the details! :)
