### ISSUE TITLE
refer to other component width

### ISSUE THREAD

**Issue by zero-t4** [styled-components/styled-components#969]
How can i refer to other component width, like this

```
const Link = styled.a`
	width: 20px;
	 height: 10px;
`;
const Icon = styled.svg\`
	height: 48px;
	width: ${Link.width + 10}px;
`
```

## Version
1.0.5

## Reproduction

https://www.webpackbin.com/bins/-KeeZCr0xKfutOfOujxN

**Comment by k15a** [comment]
That's not possible because we would have to update the Icon styles everytime you change the Link width.

**Comment by zero-t4** [comment]
Thanks
