### ISSUE TITLE
Q: How to style font icon div

### ISSUE THREAD

**Issue by serle** [styled-components/styled-components#970]
I previously rendered front icons in react like `<div className="icon-class" style={icon styling}/>` Is there a way to create a styled component from the styling, but have the ability to pass the className of the icon through as a property? i.e concatenate the additional className onto a one generated by styled component

**Comment by k15a** [comment]
Styled components adds the passed classname by default.

```jsx
const Icon = styled.div``
<Icon className="icon-class" />
```
