### ISSUE TITLE
Typescript: Exported variable 'VariableName' has or is using name 'StyledComponentClass' from external module "pathproject/node_modules/styled-components/typings/styled-components" but cannot be named.

### ISSUE THREAD

**Issue by rohmanhm** [styled-components/styled-components#973]
## Version
2.1.1
Typescript version 2.3.3

## Reproduction
I created styled-components variable
```javascript
const Wrapper = styled.header`
  background-color: red;
  height: 50px;
  width: 100%;
`
```
Until here It's still OK. But, it will throw error if I export `Wrapper`.
```javascript
export const Wrapper = styled.header`
             ▾▾▾▾▾▾▾
             [ts] Exported variable 'Wrapper' has or is using name 'StyledComponentClass' from external module "/path/project/node_modules/styled-components/typings/styled-components" but cannot be named.
             const Wrapper: StyledComponentClass<React.HTMLProps<HTMLElement>, any, React.HTMLProps<HTMLElement>>

  background-color: red;
  height: 50px;
  width: 100%;
`

```

## Expected Behavior
It's not throw type error

## Actual Behavior
Throw error
> [ts] Exported variable 'Wrapper' has or is using name 'StyledComponentClass' from external module "/path/project/node_modules/styled-components/typings/styled-components" but cannot be named.
const Wrapper: StyledComponentClass<React.HTMLProps<HTMLElement>, any, React.HTMLProps<HTMLElement>>

**Comment by rohmanhm** [comment]
If I set `tsconfig.json` declaration config to false it won't throw the error. But I need declaration file, so I must to enable it.

**Comment by rohmanhm** [comment]
cc @styled-components/typers

**Comment by rohmanhm** [comment]
Now it's work. I don't know why.
Thanks

**Comment by philpl** [comment]
cc @styled-components/typers

**Comment by Igorbek** [comment]
Was the issue reproduced?

**Comment by rohmanhm** [comment]
@Igorbek It always throw fails when I exported Component created by `styled-components`. But now it works. I don't know exactly why.

**Comment by Igorbek** [comment]
Ok, good to hear that it works now. There could be many reasons why it was not working, like conflicting typescript versions, incomplete modules set up and so on, I think if it is not reproducible anymore, we are good.

**Comment by rohmanhm** [comment]
> conflicting typescript versions

Maybe this is the reason. After downgrade typescript version it works.

**Comment by philpl** [comment]
@matt-erhart Please open a new issue with all versions, some setup info, and so on :smile:

**Comment by kevcenteno** [comment]
@matt-erhart @philpl Created the issue https://github.com/styled-components/styled-components/issues/1063

**Comment by trusktr** [comment]
I've opened a request to fix issues like these in TypeScript by bringing declaration files to parity with language features. https://github.com/microsoft/TypeScript/issues/35822
