### ISSUE TITLE
More meaningful/semantic class names during development

### ISSUE THREAD

**Issue by deathmood** [styled-components/styled-components#976]
Currently all generated class names look like this:

![image](https://user-images.githubusercontent.com/2758540/27953132-5e0bf8ca-6313-11e7-8bee-eb2b225a663d.png)

And it really causes problems while debugging. I do not understand where I am. Well of course I can switch between react devtools and inspector -- but it does not make it more convenient.

Is it possible to use class names similar to styled components names. Maybe with random prefix like:

```jsx
const Wrapper = styled.div`
  background: red;
`;
```

and the class name will be like `.frh743-Wrapper` or smth like this.

**Comment by philpl** [comment]
Yes, you can use the babel plugin to attach the displayName to the component's class https://github.com/styled-components/babel-plugin-styled-components

**Comment by davidtran** [comment]
How to use it with create-react-app. I added .babelrc but no effect on my app.

**Comment by zachwolf** [comment]
@davidtran currently you will need to eject your app, but it will be possible without ejecting in react-scripts v2 https://github.com/facebook/create-react-app/issues/2611

**Comment by CMCDragonkai** [comment]
What about using that in a type script environment?

**Comment by dimaqq** [comment]
Would be lovely to highlight this in the documentation :)
Also, which is the recommended way now, plugin or macros?
(https://www.styled-components.com/docs/tooling#babel-macro)

**Comment by davidluckystar** [comment]
+1, would like to have configurable option for CRA or some input script parameter like `--mode=development`

**Comment by helloint** [comment]
With the `displayName: true` I can see a readable class name on the component, like:
```
<button class="Button-asdf123 asdf123" />
```
But the css difinition is still under asdf123, like:
```
.asdf123 {
  color: blue;
}
```
What I expected is to see:
```
.Button-asdf123 {
  color: blue;
}
```
It appears that no such options... https://styled-components.com/docs/tooling#babel-plugin
