### ISSUE TITLE
Eslint React Native

### ISSUE THREAD

**Issue by shashkovdanil** [styled-components/styled-components#979]
I have eslint error 'View' is defined but never used.
How to fix?
![screen shot 2017-07-09 at 19 09 12](https://user-images.githubusercontent.com/19692986/27994575-24493986-64da-11e7-9893-5cb86dccb059.png)

**Comment by k15a** [comment]
Remove the import :) styled components imports the components already so there is no need for you to import them as well.

**Comment by shashkovdanil** [comment]
Thank you!
