### ISSUE TITLE
How to write Integration Tests?

### ISSUE THREAD

**Issue by PetrykowskiM** [styled-components/styled-components#983]
Hello,

I was wondering how you suggest to write integration tests? As I assume that I can not use the generated classes for that, using the whole hierarchy each time seems to be very cumbersome.

Thanks!

**Comment by philpl** [comment]
Check out jest-styled-components for snapshot and unit tests.

For integration tests you should never, not even without SC, rely on classnames, but on custom attributes e.g. a data-tag-id or just an id in some cases
