### ISSUE TITLE
Support for keyframes in primitive components

### ISSUE THREAD

**Issue by doque** [styled-components/styled-components#984]
I've been playing around rebuilding the `create-react-app` sample app using `styled-components/primitives`, which works flawlessly so far, with the exception being the `keyframes`.

Looking through issues, I found #397 which suggests this code:

```
import styledWeb from "styled-components";

const WebLogo = styledWeb.img`
    animation: ${rotationBuilder(10)} 4s linear infinite;
    height: 150px;
    width: 150px;
`;

function rotationBuilder(degree) {
  return keyframes`
    0% {
      transform: rotate(0deg);
    }
    25% {
      transform: rotate(-${degree}deg);
    }
    50% {
      transform: rotate(0deg);
      opacity: .9
    }
    75% {
      transform: rotate(${degree}deg);
    }
  `;
}
```
[Full sample here](https://www.webpackbin.com/bins/-KokoGiKEm4rUOjgsxQh).

This works beautifully for web, as expected.
However, I'm not able to apply the `keyframes` to the `Image` primitive, like this:

```
import styled from "styled-components/primitives";

const Logo = styled.Image`
  animation: ${rotationBuilder(10)} 4s linear infinite;
`
```
[Full sample here](https://www.webpackbin.com/bins/-KokokoVjjaWL64JNVS7).

The primitive works fine without the `animation` property, but adding it yields this error:
`Uncaught TypeError: allStylePropTypes[prop] is not a function` [(full stacktrace)](https://gist.github.com/doque/4356d7f8538043d81b972692cb60e926).

Any chance at getting this to work, possibly utilizing [react-native-facebook-keyframes](https://github.com/underscopeio/react-native-facebook-keyframes)?

It would be a rather nice feature to be able to write cross-platform animations using only `styled-components`.

**Comment by mxstbr** [comment]
I'd rather people just use animated as react-primitives suggests.

**Comment by mxstbr** [comment]
I don't think we should add support for anything special here, Animated works perfectly fine on react-native and if you're using `/primitives` you'll likely also want your animations to work cross-platform, so you should use it there too.

Closing!
