### ISSUE TITLE
Unexpectedly invokes componentWillUnmount() method

### ISSUE THREAD

**Issue by pawelgrzybek** [styled-components/styled-components#985]
## Version
2.1.1

## Reproduction

Love the way it works guys, amazing work! Came across one issue. Styled-components unexpectedly invoke a `componentWillUnmount()` lifecycle hook on a parent component. Let's have a look at two examples:

**1. React + ReactDOM**

Two components. The child one triggers a state change on parent one. It doesn't invoke `componentWillUnmount()` — as expected.

https://codepen.io/pawelgrzybek/pen/qjLdbq

**2. React + ReactDOM + styled-components**

Two components. The child one triggers a state change on parent one. The parent component is styled by styled-components (and this is the only difference between compared to previous CodePen). It does invoke `componentWillUnmount()` — unexpected.

https://codepen.io/pawelgrzybek/pen/vZvNmM

## Expected Behavior

Not to trigger `componentWillUnmount()`

## Actual Behavior

Invokes `componentWillUnmount()`

**Comment by philpl** [comment]
The styled factory and all its shortcuts return a component when created dynamically. So you're creating a new component on every call of render ;)

The docs have some examples on how to use it correctly. Just create a component and keep it around and use it in place of other elements

**Comment by pawelgrzybek** [comment]
Makes sense! Thank you. This is an example because this is what good people do in community —
 yeah?

https://codepen.io/pawelgrzybek/pen/JJwrqr?editors=1010

**Comment by philpl** [comment]
Yes, this should work fine
