### ISSUE TITLE
Dynamic page loading failed Error: Trying to replace an element that wasn't mounted!

### ISSUE THREAD

**Issue by DeividasK** [styled-components/styled-components#987]
## Version
`styled-components`: 2.1.1
`babel-plugin-styled-components`: 1.1.7

- SSR is configured with code-splitting using [react-boilerplate](https://www.reactboilerplate.com/).
- Some components are imported from an npm package which exports components styled with `styled-components`.

## Error stack trace
```
Dynamic page loading failed Error: Trying to replace an element that wasn't mounted!
    at BrowserTag.replaceElement (eval at ./node_modules/styled-components/lib/models/BrowserStyleSheet.js (main.js:4034), <anonymous>:122:36)
    at BrowserTag.addComponent (eval at ./node_modules/styled-components/lib/models/BrowserStyleSheet.js (main.js:4034), <anonymous>:63:27)
    at StyleSheet.getOrCreateTag (eval at ./node_modules/styled-components/lib/models/StyleSheet.js (main.js:4058), <anonymous>:141:18)
    at StyleSheet.deferredInject (eval at ./node_modules/styled-components/lib/models/StyleSheet.js (main.js:4058), <anonymous>:94:10)
    at new ComponentStyle (eval at ./node_modules/styled-components/lib/models/ComponentStyle.js (main.js:4042), <anonymous>:38:39)
    at createStyledComponent (eval at ./node_modules/styled-components/lib/models/StyledComponent.js (main.js:4074), <anonymous>:238:26)
    at templateFunction (eval at ./node_modules/styled-components/lib/constructors/constructWithOptions.js (main.js:3986), <anonymous>:26:14)
    at eval (eval at ./app/pages/CustomerStory/Quote.js (main.js:1815), <anonymous>:8:3)
    at Object../app/pages/CustomerStory/Quote.js (main.js:1815)
    at __webpack_require__ (main.js:660)
```

## Reproduction
I cannot reliably reproduce the error on webpackbin. Things I can reproduce:

- If I remove CSS injection on the server the error goes away (initially page is loaded without styles).
- Error happens only in some of the pages, but not in every page. However, when it happens, it usually happens consistently.
- Error always points to the same component. If I change / rename the component, the error starts pointing to another component, but the stacktrace is the same.
- Error sometimes points to the component, that is not even present on the page.
- We've never encountered this error when using `styled-components` v1. It started occurring once we switched to v2 (without any other changes to the setup).

## What I've tried
- Fiddling with `babel-plugin-styled-components` options
  - `ssr` on/off
  - `preprocess` on/off

Any suggestion that could point to the possible culprit / solution would be greatly appreciated.

**Comment by philpl** [comment]
Since this seems to be an SSR related issue, can you post some code on how you integrated our SSR API with the boilerplate? Cheers

cc @geelen

**Comment by philpl** [comment]
hm, I suspect that the two render phases are responsible for this trouble. Can you try this:

```js
import { ServerStyleSheet, StyleSheetManager } from 'styled-components'

// 1st render phase - triggers the sagas
renderToString(
  <StyleSheetManager sheet={new ServerStyleSheet().instance}>
);

// ...
// 2nd render phase

const sheet = new ServerStyleSheet();

const appMarkup = renderToString(
  sheet.collectStyles(
    <AppRoot store={store}>
      <RouterContext {...renderProps} />
    </AppRoot>
  )
);

// ...
const css = sheet.getStyleElement();
```

The problem seems to be that in the 1st phase you're rendering loads of Styled Components without them being captured with the server stylesheet. We can't reuse the same one for two rendering cycles, but we can try to use two separate ones, I believe

**Comment by DeividasK** [comment]
Tried this:

```jsx
import { ServerStyleSheet, StyleSheetManager } from 'styled-components'

// ...

// 1st render phase - triggers the sagas
renderToString(
  <StyleSheetManager sheet={new ServerStyleSheet().instance}>
    <AppRoot store={store}>
      <RouterContext {...renderProps} />
    </AppRoot>
  </StyleSheetManager>
);

// ...

// 2nd render phase - the sagas triggered in the first phase are resolved by now
const sheet = new ServerStyleSheet();

const appMarkup = renderToString(
  sheet.collectStyles(
    <AppRoot store={store}>
      <RouterContext {...renderProps} />
    </AppRoot>
  )
);

// capture the generated css
const css = sheet.getStyleElement();
```

and this

```js
import { ServerStyleSheet, StyleSheetManager } from 'styled-components'

// ...

const sheet = new ServerStyleSheet();

// 1st render phase - triggers the sagas
renderToString(
  <StyleSheetManager sheet={sheet.instance}>
    <AppRoot store={store}>
      <RouterContext {...renderProps} />
    </AppRoot>
  </StyleSheetManager>
);
// ...

// 2nd render phase - the sagas triggered in the first phase are resolved by now

const appMarkup = renderToString(
  sheet.collectStyles(
    <AppRoot store={store}>
      <RouterContext {...renderProps} />
    </AppRoot>
  )
);

// capture the generated css
const css = sheet.getStyleElement();
```

Both result in the same error.

**Comment by philpl** [comment]
> Error happens only in some of the pages, but not in every page. However, when it happens, it usually happens consistently.
> Error always points to the same component. If I change / rename the component, the error starts pointing to another component, but the stacktrace is the same.
> Error sometimes points to the component, that is not even present on the page.

Is there anything special about these components in the way they're used together with the state?

**Comment by philpl** [comment]
After reading through the code, I noticed that the error occurs when a style tag is not mounted in the head anymore. Which sounds weird. I'm not familiar with the rehydration yet, so @geelen might have to jump in.

Are you sure that the style tags are injected into the head statically and stay there?

https://github.com/styled-components/styled-components/blob/master/src/models/BrowserStyleSheet.js

**Comment by DeividasK** [comment]
Would it be possible to fail silently? Because when this error is thrown, the execution of the code stops and the page "breaks", which is undesired.

**Comment by philpl** [comment]
@DeividasK I'm not sure about that either, because it's a critical error in the rehydration. Again, Glen will probably be able to shine a light on this

**Comment by DeividasK** [comment]
@geelen Hey Glen, just wanted to bump this up. Any ideas / experiments that I could do to try and fix this would be really helpful.

**Comment by DeividasK** [comment]
He guys, any updates on this?

**Comment by philpl** [comment]
@DeividasK I can probably take a quick look and try out some things to solve this. Do you have a reproduction repo somewhere?

**Comment by DeividasK** [comment]
Hey Phil, not really. The main problem is that it is hard to precisely reproduce. The only way I am able to reproduce it now is in the main project repo. It disappears if I remove server side rendering. Removing code splitting does not help.

**Comment by DeividasK** [comment]
@philpl turns out that the issue was with duplicated styled-components modules. One of the dependencies for our npm package was `styled-components`. Once I removed that from `dependencies` to `devDependencies` (also added to `peerDependencies` for the warnings) AND in webpack config specified it with externals
```js
externals: {
    react: 'react',
    'react-dom': 'react-dom',
    'styled-components': 'styled-components',
  },
```
the issues have disappeared.

Simply removing it from dependencies did not help as it was necessary to specify it together with other external libraries.

I closed this issue, but I think it's worth having a discussion if styled-components should somehow detect and prevent this from happening.

**Comment by xiaolin** [comment]
I had a similar issue using `redux-connect` and `styled-components` on the server.

I was doing something very similar to @DeividasK 

```js
// capture the generated css
const css = sheet.getStyleElement();

const doc = renderToStaticMarkup(
  <HtmlDocument
    appMarkup={appMarkup}
    css={css}
  />
);
return `<!DOCTYPE html>\n${doc}`;
```

But on the client after the JS loads I would get an error `Trying to replace an element that wasn't mounted!`, causing some css to be missing.

I was able to fix it by changing

`const css = sheet.getStyleElement();` 
to
`const css = sheet.getStyleTags();`

and in my `HtmlDocument` I changed it from 
```jsx
<head>
  {css}
</head>
```
to
```jsx
<head>
  <style dangerouslySetInnerHTML={{ __html: css}} />
</head>
```

**Comment by ilanus** [comment]
@xiaolin I get the same error `Uncaught Error: Trying to replace an element that wasn't mounted!` however, this error is happening on the client-side only. I think `const styleTags = sheet.getStyleTags();` Is fine just gets the stylesheet tags from styled-components, have you found any clean solution for this?

**Comment by philpl** [comment]
@ilanus This issue is extremely old! Please refrain from commenting in older issues that have been resolved

Check the docs on how to set up SSR: https://www.styled-components.com/docs/advanced#server-side-rendering

- Using this API on the client is not supported
- If the error is on the client but the API is set up correctly make sure that the style tags are injected into your HTML's head

**Comment by jorilallo** [comment]
@philpl old or not, I also ran into issue with the Next.js example and was able to fix them with @xiaolin's tweak. Not trying to stir up shit but seems like other Next users might face similar issues.

**Comment by Coobaha** [comment]
This can be caused when multiple `styled-components` instances are used.

with npm use `npm dedupe`
with yarn add this to `package.json` with correct version and do `yarn install` after
```
"resolutions": {
  "styled-components": "your version"
}
```
