### ISSUE TITLE
Is it possible to strip out the actual styling and just return the markup of a styled-component?

### ISSUE THREAD

**Issue by chrisgreg** [styled-components/styled-components#988]
If you've got a module but multiple consumers, some consumers want to style it externally with CSS but some want to use the already existing styled-components version is it possible to strip out the actual styling and just return the markup and class names of a component?

Or would it make sense to create a raw component with classnames then use nested-selectors to style it with Styled Components?

**Comment by philpl** [comment]
Not sure why you closed this issue :wink:

You shouldn't use two methods to style the same structural component frankly.

```js
const Example = () => (
  <Item>
    <Text>ABC</Text>
  </Item>
)
```

Is still preferable to:

```js
const Example = ({ className }) => (
  <div className={`.example ${className}`}>
    <span>ABC</span>
  </div>
)

const StyledExample = styled(Example)`
  // ...
  
  > span {
    // ...
  }
`
```

So what is it exactly that you're trying to achieve? Optimally you shouldn't settle for something like css-modules in addition to styled-components for the same components.

We do have a section in our docs for this case, but it's really general and not too specific https://www.styled-components.com/docs/advanced#existing-css

**Comment by chrisgreg** [comment]
Haha sorry, realised there was no hook to do this so I though i'd close it.

So the idea is we'd have a component that'd be themed with styled-components by default but if someone wanted to style it with CSS but still use the markup they could.

**Comment by philpl** [comment]
@chrisgreg This is fundamentally in conflict with the enforced best practices of SC. So, if you create a structural component that has some styled-components inside, and attach some extra `className`s isn't that enough, or do you want to eject from styled-components in certain projects? That's not really a good idea, imho, since then you're going to end up having two sets of sources for CSS in two separate projects for the same components eventually :/

**Comment by chrisgreg** [comment]
Yeah so the reason is that some consumers may not be opting into styled components but the actual react markup and functionality will always be there. 

I know it's not ideal, just sort of based on requirements
