### ISSUE TITLE
Node of type rule not supported as an inline style

### ISSUE THREAD

**Issue by lucaorio** [styled-components/styled-components#989]
When using primitives, if I try to add a pseudo-class I get `Node of type rule not supported as an inline style`. I found a very similar ticket (#770), but I was unable to solve this problem.

```
import styled from 'styled-components/primitives';

const Ciao = styled.View`
  width: 100px;
  height: 100px;
  background: papayawhip;
  
  &:hover {
    background: palevioletred;
  }
`;
```

**Comment by philpl** [comment]
React Native is not a real css environment. One of the things it doesn't support is nesting and actually selectors in general. The same applies to React Primitives since it's based on the same base components.

**Comment by jeffreybrowning** [comment]
This should be added to the readme and documentation. I have only found this information, that some subset of the library is not available in React Native, here in this issue. Please percolate that up to more visible spots.

**Comment by mxstbr** [comment]
PRs very welcome @jeffreybrowning, PRs _very_ welcome: https://github.com/styled-components/styled-components-website

**Comment by zomars** [comment]
I'm guessing this is not supported also:

```js
const DealersListContainer = styled.View`
   @media (max-width: 700px) {
    background: palevioletred;
  }
`
```

Am I right?

**Comment by aks30498** [comment]
This isn't supported even now, right ?

**Comment by kopax-polyconseil** [comment]
Same here
