### ISSUE TITLE
Installing seems broken

### ISSUE THREAD

**Issue by schickling** [styled-components/styled-components#99]
## Version
1.0.5

## Reproduction
Clone [this repo](https://github.com/graphcool/docs/tree/dev) and run `yarn; npm start`.

## Expected Behavior

No errors 👀 

## Actual Behavior
![image](https://cloud.githubusercontent.com/assets/1567498/19419512/68cedec6-93d9-11e6-9099-0f657b897fb0.png)

**Comment by schickling** [comment]
Sorry for the title change. I also just tried with normal `npm` instead of `yarn`. Getting the same errors. Any idea?

**Comment by sheepsteak** [comment]
It looks like you're getting [1.0.6](https://github.com/graphcool/docs/blob/dev/yarn.lock#L4021) which has the .es.js bundle for Webpack v2 and Rollup so I think it's #100 that's causing you problems. For now I'd just go back 1.0.5 until it's fixed.

**Comment by geelen** [comment]
Not sure what's happening there, but I've just moved the `latest` tag off `1.0.6` for the moment. So new installs should get `1.0.5` by default. Will get @mxstbr or maybe @Rich-Harris to take a look, thanks!

**Comment by Rich-Harris** [comment]
@geelen @schickling apologies for the cockup – see https://github.com/styled-components/styled-components/issues/87#issuecomment-254062595 for the explanation and https://github.com/styled-components/styled-components/pull/100 for the fix

**Comment by mxstbr** [comment]
Fixed by @Rich-Harris in #100, soon to be released as v1.0.7!
