### ISSUE TITLE
Make the styling Framwork agnostic

### ISSUE THREAD

**Issue by Tokimon** [styled-components/styled-components#991]
I was wondering if it could be possible to decouple styled-components from React?

I am a big fan of React and I use it heavily in my daily work, but if I am building a smaller website, I might want to use a lighter framework like Mithril, to avoid too much of an overhead. But (at least as I understand it), you have to use React (or Preact) to use the awesomeness that is styled-components, which I think is too bad because I would really like to use styled-components ALL THE TIME 😄

I know that much of the cool features in styled components are due to fact that it returns a ready to use component, but it could be neat if you could use a lighter version of the styling scheme that just returns a class name that you then can use as you see fit, being it another UI framework or even jQuery for that matter.

This is kinda related to: #128, but instead of returning an actual component in your given framework, then you could use the styling composition (possibly with some degraded functionality) and only return the random class name.

**Comment by mxstbr** [comment]
There's lots of other CSS in JS frameworks that give you class names, I'd recommend using those.

`styled-components` feels so great specifically because it hides that from you and forces you to bind styles to components and is very strict about that! That sadly also means it's very hard to design a framework-agnostic version of it as it inherently has to create a "component", but what that component is differs between frameworks.

I hope that makes sense, in case you're not using React but still want to use something similar to `styled-components` I'd recommend [fela](https://github.com/rofrischmann/fela) by @rofrischmann which is a great, battle-tested framework-agnostic CSS-in-JS framework.

**Comment by philpl** [comment]
> I am a big fan of React and I use it heavily in my daily work, but if I am building a smaller website, I might want to use a lighter framework like Mithril, to avoid too much of an overhead

I really wanna add, if you like React, and you want a more lightweight js bundle size at the end of the day: Try preact & preact-compat :tada: :smile:

**Comment by Tokimon** [comment]
Ok thank you for the quick reply.
It makes sense. I just like the syntax of styled-components a lot better as it uses the string literal and can be linted, has code completion and all that jazz.
I will check out `flea` and other frameworks if I am working with another framework.

@philpl : Yeah I know and is probably what I will do 😄

**Comment by philpl** [comment]
@Tokimon It seems that `flea` was deleted? Anyhow. My personal suggestion is preact for lean sites. The problem with stuff like `mithril` and `flea` (and not specifically them, but a lot of frameworks that are published weekly, almost) is that most of the times the compromises are bad, they're a step below (P)React's good paradigms and lifecycle, or are pure js snobbery tbh. So unless you really need a different framework, I'd stick with the ones that allow you to access the vast ecosystems, and use stuff like—well—styled-components 😆

**Comment by mxstbr** [comment]
`fela` not `flea` :wink:

**Comment by philpl** [comment]
@mxstbr That makes sense, but I was confused since that's not a framework (?) Anyhow! haha

**Comment by Tokimon** [comment]
Just a final question on this subject:
My initial notion about decoupling styled-components from React was not (limited) to usage in React-like languages. I could see a use-case for this module in something like Vue, Angular, Ember, Backbone (and what have you) as well. So if I one day in the future wanted to use one of those frameworks, would I have to chose another module (like fela) or is there a way to use styled-components in those frameworks as well?

**Comment by philpl** [comment]
@Tokimon the usage of this will be very different, depending on the framework. There are already implementations for: vanilla DOM, vue, elm...

For v3 I'm extracting some preprocessing logic and css processing into a core lib. Together with our stylesheet implementation or Glamour's sheet anyone can port SC to another framework :)

**Comment by Tokimon** [comment]
ok cool. Thanks for update :)
